### ISSUE TITLE
Bitmex Invalid orderQty issue.

### ISSUE THREAD

**Issue by theantiqa** [ccxt/ccxt#7337]
Account Balance : {'info': [{'account': 1561781, 'currency': 'XBt', 'riskLimit': 1000000000000, 'prevState': '', 'state': '', 'action': '', 'amount': 110000, 'pendingCredit': 0, 'pendingDebit': 0, 'confirmedDebit': 0, 'prevRealisedPnl': 0, 'prevUnrealisedPnl': 0, 'grossComm': 0, 'grossOpenCost': 0, 'grossOpenPremium': 0, 'grossExecCost': 0, 'grossMarkValue': 0, 'riskValue': 0, 'taxableMargin': 0, 'initMargin': 0, 'maintMargin': 0, 'sessionMargin': 0, 'targetExcessMargin': 0, 'varMargin': 0, 'realisedPnl': 0, 'unrealisedPnl': 0, 'indicativeTax': 0, 'unrealisedProfit': 0, 'syntheticMargin': None, 'walletBalance': 110000, 'marginBalance': 110000, 'marginBalancePcnt': 1, 'marginLeverage': 0, 'marginUsedPcnt': 0, 'excessMargin': 110000, 'excessMarginPcnt': 1, 'availableMargin': 110000, 'withdrawableMargin': 110000, 'timestamp': '2020-07-23T10:19:57.459Z', 'grossLastValue': 0, 'commission': None}], 'BTC': {'free': 0.0011, 'used': 0.0, 'total': 0.0011}, 'free': {'BTC': 0.0011}, 'used': {'BTC': 0.0}, 'total': {'BTC': 0.0011}}

as you can see there is 0.0011 BTC balance.

when i am trying to place order for this symbol then it gives invalid quantity.
market_order = exchange.create_order("XBTU20", "market","sell", 0.000165)

Response :
bitmex {"error":{"message":"Invalid orderQty","name":"ValidationError"}}

Thanks
Tushar

**Comment by kroitor** [comment]
Please, follow the guidelines precisely:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

We need your verbose request/response for `createOrder` as explained above. Also, always use [GitHub markdown](https://guides.github.com/features/mastering-markdown/) for readability and padding, surround your code and/or output with triple backticks (&#096;&#096;&#096;), like shown below:

&#096;&#096;&#096;Python
put your code here, don't paste one line of code, paste your full short complete code snippet
&#096;&#096;&#096;

&#096;&#096;&#096;
your output here
&#096;&#096;&#096;

**Comment by theantiqa** [comment]
i have btc balance 0.0011

code for place order for 0.0002 amount.
''' market_order = exchange.create_order("XBTU20", "market","sell", 0.0002) '''

Output : 
''' bitmex {"error":{"message":"Invalid orderQty","name":"ValidationError"}} '''

**Comment by kroitor** [comment]
@theantiqa oh man... when we say _"follow precisely"_, we really mean it. That means you should read very carefully what is written by that link I've posted above, if you want to get the help quickly. Have you read it? Because if you did, and you want this issue to be resolved quickly, you want to follow it pedantically, literally to a word. That link says that you should always paste your version numbers. And you should always paste your verbose request and verbose response. You should always provide all of the above info, regardless of the issue you have (we will always ask for that info). Also, there's a second link that I've posted above that explains how to use GitHub Markdown . You should not confuse triple backticks (&#096;&#096;&#096;) with the quotes (`'''`) – those are different characters. When we say _"follow precisely"_ you really want to **follow precisely** (read all links **very very carefully** and make sure your posts correspond to the given information).

Thus your code should look like this:

```Python
import ccxt

exchange = ccxt.bitmex({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})

exchange.load_markets()

exchange.verbose = True  # ←---------------- ALWAYS ADD THIS IF YOU HAVE A PROBLEM

market_order = exchange.create_order("XBTU20", "market","sell", 0.0002)
```

↑ That will generate a lot of output, including the verbose request part and the verbose response part. Never skip that, otherwise resolving this issue will take longer time...

Basically, when you trade the `XBTU20`, you should specify the number of contracts.

To resolve this issue:

1. Make sure you understand the contract specification:

- https://www.bitmex.com/app/contract/XBTU20

2. Look into the XBTU20 market definition:

- https://github.com/ccxt/ccxt/wiki/Manual#market-structure

```Python
import ccxt
from pprint

exchange = ccxt.bitmex({
    'enableRateLimit': True,
})

exchange.load_markets()

pprint(exchange.markets['XBTU20'])
```

↑ The XBTU20 has the following `precision: { amount: 1, price: 0.5 },`. It is explained in the CCXT Manual here:

- https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits

That means, that your amount should be an integer number of contracts. You can sell or buy 0.0002 of a contract. You can buy and sell 1 contract, 2 contracts, etc.

Hope that answers your question.

**Comment by kroitor** [comment]
P.S. I highly recommend to read the entire Manual from top to bottom very carefully – it will save you a lot of time, many of the questions are already answered there:

- https://github.com/ccxt/ccxt/wiki/Manual

**Comment by theantiqa** [comment]
''' {'percentage': True, 'precision': {'amount': 1.0, 'price': 0.5}, 'limits': {'amount': {'min': None, 'max': None}, 'price': {'min': 0.5, 'max': 1000000.0}, 'cost': {'min': 1.0, 'max': 10000000.0}}, 'id': 'XBTU20', 'symbol': 'XBTU20', 'base': 'BTC', 'quote': 'USD', 'baseId': 'XBT', 'quoteId': 'USD', 'active': True, 'taker': 0.00075, 'maker': -0.00025, 'type': 'future', 'spot': False, 'swap': False, 'future': True, 'prediction': False, 'info': {'symbol': 'XBTU20', 'rootSymbol': 'XBT', 'state': 'Open', 'typ': 'FFCCSX', 'listing': '2020-03-13T08:00:00.000Z', 'front': '2020-07-31T12:00:00.000Z', 'expiry': '2020-09-25T12:00:00.000Z', 'settle': '2020-09-25T12:00:00.000Z', 'relistInterval': None, 'inverseLeg': '', 'sellLeg': '', 'buyLeg': '', 'optionStrikePcnt': None, 'optionStrikeRound': None, 'optionStrikePrice': None, 'optionMultiplier': None, 'positionCurrency': 'USD', 'underlying': 'XBT', 'quoteCurrency': 'USD', 'underlyingSymbol': 'XBT=', 'reference': 'BMEX', 'referenceSymbol': '.BXBT30M', 'calcInterval': None, 'publishInterval': None, 'publishTime': None, 'maxOrderQty': 10000000, 'maxPrice': 1000000, 'lotSize': 1, 'tickSize': 0.5, 'multiplier': -100000000, 'settlCurrency': 'XBt', 'underlyingToPositionMultiplier': None, 'underlyingToSettleMultiplier': -100000000, 'quoteToSettleMultiplier': None, 'isQuanto': False, 'isInverse': True, 'initMargin': 0.01, 'maintMargin': 0.004, 'riskLimit': 5000000000, 'riskStep': 5000000000, 'limit': None, 'capped': False, 'taxed': True, 'deleverage': True, 'makerFee': -0.00025, 'takerFee': 0.00075, 'settlementFee': 0.0005, 'insuranceFee': 0, 'fundingBaseSymbol': '', 'fundingQuoteSymbol': '', 'fundingPremiumSymbol': '', 'fundingTimestamp': None, 'fundingInterval': None, 'fundingRate': None, 'indicativeFundingRate': None, 'rebalanceTimestamp': None, 'rebalanceInterval': None, 'openingTimestamp': '2020-07-23T11:00:00.000Z', 'closingTimestamp': '2020-07-23T12:00:00.000Z', 'sessionInterval': '2000-01-01T01:00:00.000Z', 'prevClosePrice': 9469.26, 'limitDownPrice': None, 'limitUpPrice': None, 'bankruptLimitDownPrice': None, 'bankruptLimitUpPrice': None, 'prevTotalVolume': 4067758449, 'totalVolume': 4068362428, 'volume': 603979, 'volume24h': 35255815, 'prevTotalTurnover': 48439623877675, 'totalTurnover': 48445888428601, 'turnover': 6264550926, 'turnover24h': 366108592681, 'homeNotional24h': 3661.085926810003, 'foreignNotional24h': 35255815, 'prevPrice24h': 9456.5, 'vwap': 9630.2003, 'highPrice': 9800, 'lowPrice': 9440, 'lastPrice': 9657, 'lastPriceProtected': 9657, 'lastTickDirection': 'ZeroMinusTick', 'lastChangePcnt': 0.0212, 'bidPrice': 9657, 'midPrice': 9657.25, 'askPrice': 9657.5, 'impactBidPrice': 9657, 'impactMidPrice': 9657.25, 'impactAskPrice': 9657.5, 'hasLiquidity': True, 'openInterest': 174954181, 'openValue': 1813050177703, 'fairMethod': 'ImpactMidPrice', 'fairBasisRate': 0.08, 'fairBasis': 133.51, 'fairPrice': 9649.27, 'markMethod': 'FairPrice', 'markPrice': 9649.27, 'indicativeTaxRate': None, 'indicativeSettlePrice': 9515.76, 'optionUnderlyingPrice': None, 'settledPrice': None, 'timestamp': '2020-07-23T11:41:15.000Z'}} '''


as you can see in about output of market definition there is , 'limits': {'amount': {'min': None, 'max': None}} so how can i manage limit?

**Comment by kroitor** [comment]
> as you can see in about output of market definition there is , 'limits': {'amount': {'min': None, 'max': None}} so how can i manage limit?

Read the Manual, and don't confuse `limits` with `precision`:

- https://github.com/ccxt/ccxt/wiki/Manual#market-structure
- https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits

**Comment by kroitor** [comment]
@theantiqa also, once again, don't confuse triple backticks (&#096;&#096;&#096;) with the quotes (`'''`) – those are different characters.

**Comment by theantiqa** [comment]
output of  market definition :
```precision': {'amount': 1.0, 'price': 0.5}, 'limits': {'amount': {'min': None, 'max': None}```

as you can see in above result there you can see limits None. so how can i place minimum limit order?

**Comment by kroitor** [comment]
> as you can see in above result there you can see limits None. so how can i place minimum limit order?

When min limit is not defined by the exchange, you can place any amount that satisfies the precision, as documented in the CCXT Manual or precision and limits. Thus, the smallest order in this case is defined by the precision step for amounts (1 contract).

> that showing me order value 0.0001. but how can i get here 1 contract means 0.0001 order value in market definition?

You can see that from the `info` as described in the CCXT Manual on market structures.

> how to place stop loss limit order for bitmex?

See the example here:

- https://github.com/ccxt/ccxt/blob/master/examples/py/bitmex-create-order.py

**Comment by TusharDcs** [comment]
Market data for symbol XBTU20.

Output : 

``{'percentage': True, 'precision': {'amount': 1.0, 'price': 0.5}, 'limits': {'amount': {'min': None, 'max': None}, 'price': {'min': 0.5, 'max': 1000000.0}, 'cost': {'min': 1.0, 'max': 10000000.0}}, 'id': 'XBTU20', 'symbol': 'XBTU20', 'base': 'BTC', 'quote': 'USD', 'baseId': 'XBT', 'quoteId': 'USD', 'active': True, 'taker': 0.00075, 'maker': -0.00025, 'type': 'future', 'spot': False, 'swap': False, 'future': True, 'prediction': False, 'info': {'symbol': 'XBTU20', 'rootSymbol': 'XBT', 'state': 'Open', 'typ': 'FFCCSX', 'listing': '2020-03-13T08:00:00.000Z', 'front': '2020-07-31T12:00:00.000Z', 'expiry': '2020-09-25T12:00:00.000Z', 'settle': '2020-09-25T12:00:00.000Z', 'relistInterval': None, 'inverseLeg': '', 'sellLeg': '', 'buyLeg': '', 'optionStrikePcnt': None, 'optionStrikeRound': None, 'optionStrikePrice': None, 'optionMultiplier': None, 'positionCurrency': 'USD', 'underlying': 'XBT', 'quoteCurrency': 'USD', 'underlyingSymbol': 'XBT=', 'reference': 'BMEX', 'referenceSymbol': '.BXBT30M', 'calcInterval': None, 'publishInterval': None, 'publishTime': None, 'maxOrderQty': 10000000, 'maxPrice': 1000000, 'lotSize': 1, 'tickSize': 0.5, 'multiplier': -100000000, 'settlCurrency': 'XBt', 'underlyingToPositionMultiplier': None, 'underlyingToSettleMultiplier': -100000000, 'quoteToSettleMultiplier': None, 'isQuanto': False, 'isInverse': True, 'initMargin': 0.01, 'maintMargin': 0.004, 'riskLimit': 5000000000, 'riskStep': 5000000000, 'limit': None, 'capped': False, 'taxed': True, 'deleverage': True, 'makerFee': -0.00025, 'takerFee': 0.00075, 'settlementFee': 0.0005, 'insuranceFee': 0, 'fundingBaseSymbol': '', 'fundingQuoteSymbol': '', 'fundingPremiumSymbol': '', 'fundingTimestamp': None, 'fundingInterval': None, 'fundingRate': None, 'indicativeFundingRate': None, 'rebalanceTimestamp': None, 'rebalanceInterval': None, 'openingTimestamp': '2020-07-24T04:00:00.000Z', 'closingTimestamp': '2020-07-24T05:00:00.000Z', 'sessionInterval': '2000-01-01T01:00:00.000Z', 'prevClosePrice': 9663.89, 'limitDownPrice': None, 'limitUpPrice': None, 'bankruptLimitDownPrice': None, 'bankruptLimitUpPrice': None, 'prevTotalVolume': 4099316725, 'totalVolume': 4099519743, 'volume': 203018, 'volume24h': 38300679, 'prevTotalTurnover': 48764961001614, 'totalTurnover': 48767058940073, 'turnover': 2097938459, 'turnover24h': 395271421315, 'homeNotional24h': 3952.714213150005, 'foreignNotional24h': 38300679, 'prevPrice24h': 9641, 'vwap': 9689.9225, 'highPrice': 9823, 'lowPrice': 9586.5, 'lastPrice': 9667.5, 'lastPriceProtected': 9667.5, 'lastTickDirection': 'MinusTick', 'lastChangePcnt': 0.0027, 'bidPrice': 9667.5, 'midPrice': 9667.75, 'askPrice': 9668, 'impactBidPrice': 9664.6371, 'impactMidPrice': 9666.5, 'impactAskPrice': 9668.3747, 'hasLiquidity': True, 'openInterest': 175630393, 'openValue': 1816018263620, 'fairMethod': 'ImpactMidPrice', 'fairBasisRate': 0.07, 'fairBasis': 116.01, 'fairPrice': 9670.9, 'markMethod': 'FairPrice', 'markPrice': 9670.9, 'indicativeTaxRate': None, 'indicativeSettlePrice': 9554.89, 'optionUnderlyingPrice': None, 'settledPrice': None, 'timestamp': '2020-07-24T04:37:30.000Z'}}````

still i have same question how can i calculate or get 1 contract means 0.0001 order value? can you show me from above output?

Thanks

**Comment by kroitor** [comment]
@TusharDcs i've asked BitMEX about it and here's the answer from their tech support:

> Hi Igor,
> The order value is rounded to 4 decimals because your account settings are set to XBT.
> If you set the currency display to XBt, you will see the entire amount rounded to 8 decimals.
>
> ![bitmex-order-value-a](https://user-images.githubusercontent.com/1294454/88375057-8f8d8000-cda3-11ea-9972-64d9b1ba564f.png)
> ![bitmex-order-value-b](https://user-images.githubusercontent.com/1294454/88375074-96b48e00-cda3-11ea-96a2-90a16826bc4d.png)
> 
> Let me know if you have any further questions.
> 
> Regards,
> BitMEX

----------------------------------

As you can see from the above answer, that value is rounded according to user settings, those settings are user-specific and the rounding decimals are hardcoded in the BitMEX UI. The units are described here: https://en.bitcoin.it/wiki/Units

Thus, if you want to calculate 0.0001XBT from the contract definition, you would do the following:

```Python
import ccxt

exchange = ccxt.bitmex({
    'enableRateLimit': True
})

markets = exchange.load_markets()
symbol = 'XBTU20'
market = exchange.market(symbol)

units = {
    'XBT':  { 'decimals': 4, 'multiplier': 1 },  # bitcoin
    'mXBT': { 'decimals': 3, 'multiplier': 1000 },  # milli-bitcoin
    'μXBT': { 'decimals': 1, 'multiplier': 1000000, },  # micro-bitcoin
    'XBt':  { 'decimals': 0, 'multiplier': 100000000 },  # satoshi
}

# the following calculation depends on contract specifications
# one contract = 1 USD for XBTU20

num_contracts = 1
last_price = market['info']['lastPrice']  # or use fetch_ticker(symbol) to obtain the last price, because it changes rapidly
value = num_contracts / last_price

for unit in units:
    multiplier = units[unit]['multiplier']
    decimals = units[unit]['decimals']
    rounded_value = exchange.decimal_to_precision(value * multiplier, ccxt.ROUND, decimals)
    print(num_contracts, symbol, 'contracts =', rounded_value, unit)
```

I hope that answers your question.

**Comment by kroitor** [comment]
@TusharDcs alternatively:

- https://github.com/ccxt/ccxt/blob/master/examples/py/bitmex-order-value.py

-----------------------

```Python
# -*- coding: utf-8 -*-

import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt  # noqa: E402


exchange = ccxt.bitmex({
    'enableRateLimit': True
})

markets = exchange.load_markets()
symbol = 'XBTU20'
market = exchange.market(symbol)

units = {
    'XBT':  { 'decimals': 4, 'multiplier': 1 },  # bitcoin
    'mXBT': { 'decimals': 3, 'multiplier': 1000 },  # milli-bitcoin
    'μXBT': { 'decimals': 1, 'multiplier': 1000000, },  # micro-bitcoin
    'XBt':  { 'decimals': 0, 'multiplier': 100000000 },  # satoshi
}

# the following calculation depends on contract specifications
# one XBTU20 contract = 1 USD in Bitcoin

num_contracts = 1

while True:
    try:
        ticker = exchange.fetch_ticker(symbol)
        last_price = ticker['last']
        value = num_contracts / last_price
        print('---------------------------------------------------------------')
        print(exchange.iso8601(exchange.milliseconds()))
        for unit in units:
            multiplier = units[unit]['multiplier']
            decimals = units[unit]['decimals']
            rounded_value = exchange.decimal_to_precision(value * multiplier, ccxt.ROUND, decimals)  # alternatively, use ccxt.TRUNCATE here
            print(num_contracts, symbol, 'contracts =', rounded_value, unit)
    except e:
        pass
```
