### ISSUE TITLE
Use a listener for watch methods instead of promises

### ISSUE THREAD

**Issue by Colman** [ccxt/ccxt#7342]
- OS: Windows 7
- Programming Language version: node 12.14.1
- CCXT version: 0.2.99

Hi I'm trying to create a subscribe/unsubscribe service for the watch methods and I'm running into trouble. The behavior I'm looking for is the following:

```
const exchange = new ccxtpro.bitfinex();
let subbed = false;

function subscribe(listener) {
   new Promise(async (resolve, reject) => {
        subbed = true;
        while (true) {
            const ticker = await exchange.watchTicker("ETH/USD");
            if (subbed) {
                listener(ticker);
            } else {
                break;
            }
        }
    });
}

function unsubscribe() {
    subbed = false;
}
```

This works fine for the most part except when you unsubscribe and then subscribe right after. The problem is that watchTicker only sends the initial snapshot of the ticker the first time it's called. So when I subscribe the second time I don't get this snapshot and I have to wait for there to be a change in order to get data. This might not be an issue for active symbols like ETH/USD since new data is coming in all the time, but for other symbols you might not see a trade for hours. This means that from the POV of the listener it's going to be a really long time before a snapshot is received. So my question is, how can I build a sub/unsub system for ccxt? And why was the promise/while loop pattern used over something like this?

**Comment by kroitor** [comment]
Hi! The unsubscribe functionality is in the works and it will arrive asap.

However, in your case, you can solve it by using the _"throttling"_ mode with the _"real-time"_ mode. Both of them are described in the Manual:

- https://github.com/ccxt/ccxt/wiki/ccxt.pro.manual#real-time-vs-throttling

If the "throttling" mode of operation you would execute `await exchange.watchTicker` once and then use the `exchange.tickers` property to read the most recent snapshot from it.

And you can combine the two modes, so you can `await exchange.watchTicker ()`, without awaiting (the first call initiates the subscription for the balance updates).

```JavaScript
const symbol = 'ETH/USD'

await Promise.all ([
    async () => {
        // throttling mode
        // await is optional, alternatively you can launch it in bg without await
        await exchange.watchTicker (symbol)
        while (true) {
            // your reaction takes place here
            console.log (exchange.tickers[symbol])
            await exchange.sleep (100) // every 100 ms
        }
    },

    async () => {
        // real-time mode
        while (true) {
            const ticker = await exchange.watchTicker (symbol)
            // your reaction to the update takes place here
            console.log (ticker) // every update
        } catch (e) {
            console.log (e)
            throw e
        }
    }    
])
```

Let us know if the above does not answer your question.

**Comment by Colman** [comment]
Yeah that sort of solves it but the problem with that solution is that the higher the sleep time, the longer it takes to get the initial snapshot. And for my implementation it needs to be sent asap. And if the sleep time is lowered then you'll eventually be getting twice as many updates as you need which is also a problem. I know timelines for features is super hard to predict but do you have any sort of estimation for when the unsub feature will be available? Are we talking a few days or a few months?

**Comment by kroitor** [comment]
@Colman we hope to get it done within weeks. We are aware that it's a wanted feature.
