### ISSUE TITLE
AttributeError: module 'ccxt' has no attribute 'allcoin' error message

### ISSUE THREAD

**Issue by MiningAmazing** [ccxt/ccxt#7358]
Hi, let me know if I I'm reporting the issue in a wrong way, I've read it, I think this is the way, but I'm a newbie.

When checking the version I have, I see that it's not the latest, I Have 1.32.2, but I can't download version 1.32.3, and following the instructions to install it, it's not downloading the last. However, I don't know if that's the reason of the problem.

- OS: Windows 10 Pro V 2004 19041.364
- Programming Language version: Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)] on win32
- CCXT version:. 1.32.2

I'm executing each code line in python terminal.
```
>>> import numpy as np
>>> import ccxt
>>> exchanges = ["Allcoin", "Binance", "Bitfinex", "Bittrex", "Cex", "Cryptopia", "Exmo", "Gatecoin", "Hitbtc","Huobipro", "Kraken", "Kucoin", "Livecoin", "Okex", "Poloniex", "Qryptos", "Quadrigacx", "Southxchange", "Yobit"]
>>> allcoin = ccxt.allcoin()
```

```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: module 'ccxt' has no attribute 'allcoin'
```
Can you help me to find out which is the issue? Been googling but I didn't find anything helpful.

Thank you.

**Comment by kroitor** [comment]
Duplicate:

- https://github.com/ccxt/ccxt/issues/6249

Let us know if the above does not answer the question.

**Comment by MiningAmazing** [comment]
FYI, in the end worked with this list:

`exchanges = ["Binance", "Bitfinex", "Bittrex", "Cex","Exmo", "Hitbtc","Huobipro", "Kraken", "Kucoin", "Livecoin", "Okex", "Poloniex","Southxchange", "Yobit"]`

I know there are more, but I need to find a way to add all of them without defining them before, maybe there's no need to do it? Anyway, there's no reason to answer yet, I didn't search for an answere. At least for what I'm testing, that's their approach :)

Again, thanks for your quick reply.

**Comment by kroitor** [comment]
> maybe there's no need to do it?

```Python
import ccxt
wanted_exchanges = ['allcoin', 'bittrex', 'bitfinex']
working_exchanges = [id for id in wanted_exchanges if id in ccxt.exchanges]
print(working_exchanges)
```
