### ISSUE TITLE
nonce gets out of order

### ISSUE THREAD

**Issue by mkutny** [ccxt/ccxt#736]
I do sometimes issue requests simultaneously and rely on the rate limiter to serialize them.

Let's say I use `ava` testing framework and my testfile looks something like this:
```
for (/*list of exchanges*/) {
  const exchange = new ccxt[exchangeId](keys[exchangeId]);

  test(`${exchange.id}: InsufficientFunds`, testInsufficientFunds, exchange, symbol, amount, price);
  test(`${exchange.id}: InvalidOrder`, testInvalidOrder, exchange, 1);
}
```

`ava` runs its `test`s concurrently and (quite seldom but still) I get something like:

> invalid nonce parameter, you sent: 1512312887, you should send: 1512312889

Obviously, requests get mixed somewhere between signature and actual fetch.

And the only place I can think of where they can be mixed is inside `executeRestRequest`. It doesn't put `fetch`es in sequence explicitly so might it happen that `node` mixes them?

**Comment by kroitor** [comment]
> invalid nonce parameter, you sent: 1512312887, you should send: 1512312889

Do you get this line from the exchange, or do you print yourself?

**Comment by kroitor** [comment]
To me this looks as if the following is happening:
1. You send 1512312887
2. You immediately send 1512312888
3. 1512312888 gets there first, the nonce is updated
4. 1512312887 arrives late, (sent 1512312887, should send 1512312889)

So, in fact, those requests get **sent** in order but can **arrive** out of order due to the connectionless nature of HTTP. I don't really see a workaround for this, unless we wait for one private request to finish (until we receive a reply for the request that was sent previously) before issuing the next one... Any ideas?

**Comment by kroitor** [comment]
However, the above can also indicate a bug somewhere in current implementation of the `throttle()` mechanism...

**Comment by mkutny** [comment]
> Do you get this line from the exchange, or do you print it yourself?

I've been chasing the cause of `nonce too small` for quite a while and finally (and luckily) got this one from the exchange. At least now we can discard the possibility that they get signed the same (milli)second.

BTW, I was always wondering why by default `nonce()` returns seconds (and only sometimes you override it to milliseconds). Why not have milliseconds as a default?

> So, in fact, those requests get sent in order but can arrive out of order due to the connectionless nature of HTTP.

Never thought about this option... I guess it's the reason.

> I don't really see a workaround for this, unless we wait for one private request to finish (until we receive a reply for the request that was sent previously) before issuing the next one.

In essence that's what we effectively achieve by:
```
await exchange.oneRequest();
await exchange.anotherRequest();
```
This is basically userland serialization. I bet if you don't get nonces from time to time you execute requests in this manner.

But actually userland serialization can be improved inside `ccxt` if we let the next request to depart once we started receiving a response from previous one, not only after we've completely received it.


> The way to verify this is to add nonce (http header/body) logging to console after signing the request, before the request is sent (verbose = true), then see if nonces get sent in sequential order.

Now I managed to easily reproduce it with just:
```
quoine.cancelOrder(1); // non-blocking
quoine.cancelOrder(1); // non-blocking
```

Here's the response:

```
quoine, nonce: 1512323876076 // from console.log()
quoine PUT https://api.quoine.com/orders/138913374/cancel 
Request:
 { 'X-Quoine-API-Version': '2',
  'Content-Type': 'application/json',
  nonce: 1512323876076,
  'X-Quoine-Auth': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL29yZGVycy8xMzg5MTMzNzQvY2FuY2VsIiwibm9uY2UiOjE1MTIzMjM4NzYwNzYsInRva2VuX2lkIjoxMjY4MTAsImlhdCI6MTUxMjMyMzg3NjA3Nn0.zqqKWN__XBDAlmhjqc8Vye5LsiuBtg_QbFhOdIeyOWw' } undefined

quoine, nonce: 1512323876088 // from console.log()
quoine PUT https://api.quoine.com/orders/138913374/cancel 
Request:
 { 'X-Quoine-API-Version': '2',
  'Content-Type': 'application/json',
  nonce: 1512323876088,
  'X-Quoine-Auth': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL29yZGVycy8xMzg5MTMzNzQvY2FuY2VsIiwibm9uY2UiOjE1MTIzMjM4NzYwODgsInRva2VuX2lkIjoxMjY4MTAsImlhdCI6MTUxMjMyMzg3NjA4OH0.LgUsTbZdJO5qbtbdJBX7oKQNWeJJypxIpm845-yBx04' } undefined
quoine PUT https://api.quoine.com/orders/138913374/cancel 200 OK 
Response:
{"id":138913374,"order_type":null,"quantity":"0.0","disc_quantity":"0.0","iceberg_total_quantity":"0.0","side":null,"filled_quantity":"0.0","price":"0.0","created_at":null,"updated_at":null,"status":null,"leverage_level":0,"source_exchange":null,"product_id":0,"product_code":null,"funding_currency":null,"crypto_account_id":null,"currency_pair_code":null,"average_price":"0.0","target":null,"order_fee":"0.0","source_action":null,"unwound_trade_id":null,"trade_id":null}

quoine PUT https://api.quoine.com/orders/138913374/cancel 401 Unauthorized 
Response:
Nonce is too small
```

**Comment by kroitor** [comment]
> This is basically userland serialization. I bet if you don't get nonces from time to time you execute requests in this manner.

We avoid mixing private requests, mostly. But yes, we have them from time to time.

> But actually userland serialization can be improved inside ccxt if we let the next request to depart once we started receiving a response from previous one, not only after we've completely received it.

Yep, we need to switch the underlying HTTP `fetch()` transport/wrappings to something stream-based, apparently. What substitution would you suggest?

**Comment by kroitor** [comment]
> BTW, I was always wondering why by default nonce() returns seconds (and only sometimes you override it to milliseconds). Why not have milliseconds as a default?

Some exchanges won't accept milliseconds, but practically all of them accept seconds. In fact, I think we should invert (set default to milliseconds and override the outliers).

**Comment by mkutny** [comment]
> Yep, we need to switch the underlying HTTP fetch() transport/wrappings to something stream-based, apparently. What substitution would you suggest?

I just finished testing and I think I'd switch to keepalive connections. Actually, I've found it surprising that you don't use them (probably due to legacy reasons).

> Some exchanges won't accept milliseconds, but practically all of them accept seconds. In fact, I think we should invert (set default to milliseconds and override the outliers).

Agree!

**Comment by kroitor** [comment]
> I just finished testing and I think I'd switch to keepalive connections. Actually, I've found it surprising that you don't use them (probably due to legacy reasons).

We also did a test for HTTP/2 but most of exchanges don't support it. Anyway, feel free to change it, if you see a straightforward edit for this, I'll do my best to rework this part asap.

**Comment by kroitor** [comment]
More to this: after reviewing this whole issue we think this behaviour should be user-controlled (optional), namely, whether it should wait for the beginning of a reply before sending the next request or not. 

There's a strong-counter argument against turning it on by default: most of the time we need bursts of requests to still continue working. The support for bursts of requests is implemented with [Token Bucket](https://en.wikipedia.org/wiki/Token_bucket) inside `throttle()` (added by @samholt in Python initially, ported later to JS). 

A *burst* is a pack of rapid consequent requests after a longer delay. Most of exchanges don't rate-limit in exact terms. They say "300 requests per minute", meaning that you can send all 300 on the very first second and then wait a minute until sending another pack, and that is still below their rate limit (perfectly fine). So most exchanges will do a *bucketed* type of rate limiting, like Kraken, for example: https://www.kraken.com/en-us/help/api#api-call-rate-limit.

So, if we wait before sending the next request, we lose the ability to send out requests in bursts. However, in practice, we prefer having them available over the nonce ordering, and yes, the occasional nonce error is unpleasant, but tolerable. Waiting for too long may be even less pleasant and less tolerable, but this depends on your particular use case, of course.

Hope it clarifies this a little bit.

**Comment by mkutny** [comment]
With keepalive we have just one syn/ack and one TLS handshake but a serial execution.

With per-request connections we achieve parallelism but every request gets its separate session setup overhead.

You're basically saying that the latter is necessarily faster. Well, I'm more inclined to agree but would love to performance test, just out of curiosity.

I tried to test with Kraken but having timeout errors every other try. Could you suggest another burst-friendly exchange to test with?

**Comment by mkutny** [comment]
> Our token bucket implementation supports all of that, you should definitely figure out how to control it if you want to be more efficient.

BTW, does it mean that you don't plan to spread individual bucket configurations over exchange implementations?

**Comment by kroitor** [comment]
> Could you suggest another burst-friendly exchange to test with?

Well, practically all of them... https://docs.gdax.com/#rate-limits 

```
PUBLIC ENDPOINTS
We throttle public endpoints by IP: 3 requests per second, up to 6 requests per second in bursts.

PRIVATE ENDPOINTS
We throttle private endpoints by user ID: 5 requests per second, up to 10 requests per second in bursts.
```

> BTW, does it mean that you don't plan to spread individual bucket configurations over exchange implementations?

In fact, it means the opposite ) We are going to add tokenBucket configs to all exchanges ) So, please, do send PRs on this matter, your help on this would be appreciated a lot, as always! Thx!
