### ISSUE TITLE
bitmex leverage order.

### ISSUE THREAD

**Issue by TusharDcs** [ccxt/ccxt#7367]
Hi,

how can i place bitmex leverage order. can you write code for it?
Example : want to place leverage order for 10x of quantity 10 USD.  that means it will use only 1$ margin of my balance.  if you don't understand what i said then look into video(https://www.youtube.com/watch?v=hNu6usVzkvY). and start from 8:23 min. 

**please write code for leverage order with market, limit ,stop limit, take profit.** 

Thanks

**Comment by kroitor** [comment]
Hi!

This question has been answered already, let us know if the following does not answer your question:

- https://github.com/ccxt/ccxt/blob/master/examples/py/bitmex-create-order.py
- https://github.com/ccxt/ccxt/issues/2499#issuecomment-514820304
- https://github.com/ccxt/ccxt/issues/6399#issuecomment-577304202
- https://github.com/ccxt/ccxt/issues/4900#issuecomment-478237122
- https://github.com/ccxt/ccxt/search?q=bitmex+leverage&type=Issues
-

**Comment by TusharDcs** [comment]
![image](https://user-images.githubusercontent.com/68111937/88545598-d21bba80-d038-11ea-9920-dcf743e1985d.png)
can we have Reduce Only option in create Limit order in bitmex. 

Thanks

**Comment by kroitor** [comment]
> can we have Reduce Only option in create Limit order in bitmex.

Yes, it is documented in the CCXT Manual and in BitMEX API docs:

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params
- https://www.bitmex.com/api/explorer/#!/Order/Order_new

For example:
```Python
import ccxt
from pprint import pprint

exchange = ccxt.bitmex({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})

symbol = 'BTC/USD'
params = {  # exchange-specific endpoint-specific params
    'execInst' => 'ReduceOnly',
    # YOUR OTHER PARAMS HERE...
);
amount = 50;  # the size of your position
price = 9000;  # ←----------- YOUR LIMIT PRICE HERE
response = $exchange.create_order(symbol, 'limit', 'sell', amount, price, params)
pprint(response)
```

**Comment by TusharDcs** [comment]
Thanks

**Comment by TusharDcs** [comment]
Hi,

can we have socket api for bitmex so that can i get continuous update of order status which i have placed. 
like, if any action on order occur i will get event from socket so i can get next action on that event.

Thanks

**Comment by kroitor** [comment]
@TusharDcs the WS APIs are added in CCXT Pro, however, the private APIs there are still a work in progress.

- https://ccxt.pro/
- https://github.com/ccxt/ccxt/issues/6543
