### ISSUE TITLE
Why must exactly 2 trades? A order has more than one trades! 

### ISSUE THREAD

**Issue by imdgr886** [ccxt/ccxt#7374]
https://github.com/ccxt/ccxt/blob/a249d59f9d4fc89338fef32f5322ba8f71387223/js/okex.js#L2717

**Comment by kroitor** [comment]
@imdgr886 that code is not for parsing orders. It is used for parsing the ledger entries. Each trade in the ledger is represented by 2 sides, the buyer and the seller side. Hope that answers your question.
