### ISSUE TITLE
exchange.fetch_ohlcv seem to return values of another pair instead of BTC/USD

### ISSUE THREAD

**Issue by Princeton007** [ccxt/ccxt#7376]
- OS: Windows 10
- Programming Language version: Python 3.7.7
- CCXT version: 1.32.12

```
import ccxt
import pprint
exchange = ccxt.bitfinex({
    'apiKey': '**',
    'secret': '**',
})

ohlc = exchange.fetch_ohlcv('BTC/USD', '1d', limit = 2)
pprint.pprint(ohlc)
```
Output:
```
[[1364688000000, 92.5, 93.74999, 91.0, 93.033, 3083.0797907500005],
 [1364774400000, 93.25, 105.9, 92.49999, 103.999, 5224.401312970002]]
```
So far it seems to work but: 
The BTC/USD price is around 10k more or less, but the returned OHLCV seem to belong to another pair. 
Am I doing somethign wrong?

Doing the same with Kraken returns
```
[[1533772800000, 6275.9, 6630.5, 6179.1, 6536.0, 5940.66974731],
 [1533859200000, 6536.0, 6579.1, 6010.0, 6141.5, 7526.68665808]]
```

**Comment by kroitor** [comment]
> Am I doing somethign wrong?

Yes, you're using old data. You may want to use BTC/USDT instead.

```Python
import ccxt
import pprint
exchange = ccxt.bitfinex({
    'enableRateLimit': True,  # required by the Manual https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
    'apiKey': '**',
    'secret': '**',
})

exchange.load_markets()

# enable the verbose mode as documented in the Manual https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

exchange.verbose = True

ohlc = exchange.fetch_ohlcv('BTC/USD', '1d', limit = 2)

for candle in ohlc:
    print(exchange.iso8601(candle[0]), candle[1:])
```

In verbose mode you can verify that CCXT does not change those values, what you see is what you get from the exchange directly. Always use the verbose mode as documented in the troubleshooting section in Manual.

Check the timestamp of each candle.

And apply the pagination as documented in the Manual if you want a specific datetime rane:

- https://github.com/ccxt/ccxt/wiki/Manual#pagination

I hope that answers your question, let us know if not. Feel free to reopen this issue or just ask further questions if any.

**Comment by Princeton007** [comment]
@kroitor thanks for the super-fast answer again. Obviously Limit=2 returns the first 2 bars, not the last two as I thought it would. I just figured it out, the BTC price was so low at that time. 

```
2013-03-31T00:00:00.000Z [92.5, 93.74999, 91.0, 93.033, 3083.0797907500005]
2013-04-01T00:00:00.000Z [93.25, 105.9, 92.49999, 103.999, 5224.401312970002]
```

Do you have a good suggestion how to catch only the last bar's close in an easy way, or do I have to use the "since" parameter?

**Comment by kroitor** [comment]
> I guess I have to use the "since" parameter

Yes, that is documented in the Manual, if you want a specific range, you should apply pagination with the `since` argument.

**Comment by Princeton007** [comment]
OK thanks, maybe soleone else needs it so I post what I've done. 
This is maybe not the smartest way yet but it works:

```
exchange = ccxt.bitfinex({
    'enableRateLimit': True,
    'apiKey': '**',
    'secret': '**',
})
from datetime import datetime
from datetime import timezone
dt_obj = datetime.now(timezone.utc)
millisec = (dt_obj.timestamp() * 1000) - 2*24*60*60*1000  # -> calculate timestamp in ms, 2 days before now
ohlc = exchange.fetch_ohlcv(symbol, '1d', since=millisec)
for candle in ohlc:
    print(exchange.iso8601(candle[0]), candle[1:])
```
