### ISSUE TITLE
binance isolated margin end points enabled

### ISSUE THREAD

**Issue by lampardlb** [ccxt/ccxt#7384]
please see: https://binance-docs.github.io/apidocs/spot/en/#change-log

2020-07-28

ISOLATED MARGIN

New parameters "isIsolated" and "symbol" added for isolated margin in the following endpoints:

POST /sapi/v1/margin/loan
POST /sapi/v1/margin/repay
New parameter "isIsolated" and new response field "isIsolated" added for isolated margin in the following endpoints:

POST /sapi/v1/margin/order
DELETE /sapi/v1/margin/order
GET /sapi/v1/margin/order
GET /sapi/v1/margin/openOrders
GET /sapi/v1/margin/allOrders
GET /sapi/v1/margin/myTrades
New parameter "isolatedSymbol" and new response field "isolatedSymbol" added for isolated margin in the following endpoints:

GET /sapi/v1/margin/loan
GET /sapi/v1/margin/repay
GET /sapi/v1/margin/interestHistory
New parameter "isolatedSymbol" and new response field "isIsolated" added for isolated margin in the following endpoint GET /sapi/v1/margin/forceLiquidationRec

New parameter "isolatedSymbol" added for isolated margin in the following endpoints:

GET /sapi/v1/margin/maxBorrowable
GET /sapi/v1/margin/maxTransferable

**New endpoints for isolated margin:

POST /sapi/v1/margin/isolated/create
POST /sapi/v1/margin/isolated/transfer
GET /sapi/v1/margin/isolated/transfer
GET /sapi/v1/margin/isolated/account
GET /sapi/v1/margin/isolated/pair
GET /sapi/v1/margin/isolated/allPairs
New endpoints for listenKey management of isolated margin account:

POST /sapi/v1/userDataStream/isolated
PUT /sapi/v1/userDataStream/isolated
DELETE /sapi/v1/userDataStream/isolated**

**Comment by lampardlb** [comment]
Thanks for your assignment @kroitor . Can I clarify: the endpoints added near the bottom of the list will need new codes to work, right?

**Comment by kroitor** [comment]
@lampardlb yes, we will add them asap.

**Comment by lampardlb** [comment]
Thanks @kroitor , no worries - sorry I did not mean to push you!

**Comment by ALIANS-PRODUCTIONS** [comment]
Hi there, is it possible to retrieve the borrow limits  in Cross Margin account (Binance) using CCXT?
Apologies if this is documented, this was the closes post i could find.
I need to get the last column on the screen shot below (borrow limit, depending on user account)  
![image](https://user-images.githubusercontent.com/21268921/193633981-51236b74-2c2e-482f-bca5-d4ffffaefcdb.png)

Thank you
