### ISSUE TITLE
Binance get margin open orders: ccxt.base.errors.RequestTimeout

### ISSUE THREAD

**Issue by baeriswyld** [ccxt/ccxt#7385]
- OS: Ubuntu
- Programming Language version: python
- CCXT version: 1.20.48

Probably a simple bug!
Every now and then when checking open orders for the margin account on binance with:
ccxt.**sapiGetMarginOpenOrders()**

I get request timeout:
- ccxt.base.errors.RequestTimeout
- and from Binance side: {"code":-2014,"msg":"API-key format invalid."}

Any idea why sometimes my API-key format is invalid and other times it is ?

thank you!

**Comment by kroitor** [comment]
@baeriswyld how do you initialize the exchange instance?

We need the code to reproduce it and your verbose request/response output, as documented in the docs:

Please, follow these guides precisely:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

**Comment by baeriswyld** [comment]
@kroitor, hi

the error arrives from time to time when doing this.

```
from ccxt import async_support as ccxt

conf = {"keyname_exchange":{
    "key": "####",
    "secret": "####"}}

provider_name = "binance"
key_name = "keyname_exchange"

provider = eval("ccxt.%s({'apiKey': conf['%s']['key'], "
            "'secret': conf['%s']['secret'], "
            "'verbose': False})" % (provider_name, key_name, key_name))

import asyncio
async def open_orders(provider):
    orders = await provider.sapiGetMarginOpenOrders()
    print("Open orders: {}".format(orders))

loop = asyncio.get_event_loop()
loop.create_task(open_orders(provider))

```

**Comment by kroitor** [comment]
@baeriswyld you're missing the rate-limiter. You should always enable it, or add a custom one, as explained in the Manual here:

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit

Also, if you delete this exchange instance and restart the script too frequently, you will break the rate limits as well. So , the proper way of doing it is to share the exchange instance among the iterations of the loop that reads the orders.

In general, I would highly recommend to read the entire manual from top to bottom – it will save your time.

```Python
import asyncio
from pprint import pprint
from ccxt import async_support as ccxt

exchange_id = "binance"
config = {
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,  #  ←------------------------- add this
}

async def open_orders(exchange_id, config):
    exchange = getattr(ccxt, exchange_id)(config)
    while i in range(0, 1000):
        print('---------------------------------------------------')
        print('Iteration', i)
        # reuse the same exchange in a loop instead of restarting this entire script
        orders = await exchange.sapiGetMarginOpenOrders()  
        pprint(orders)
    await exchange.close()

loop = asyncio.get_event_loop()
loop.create_task(open_orders(exchange_id))
```

Let us know if that does not answer your question.

**Comment by baeriswyld** [comment]
Hi thanks for this!

very helpful.

I share the exchange instance across the whole code. So it cannot be this.

I get the error even when I enable the rate limits.

Binance has a special ratelimit for OpenOrders:

2020-07-17
There is now a request limit specifically for the sapi/v1/margin/allOrders endpoint at 60 raw requests per minute for a single IP address.
https://binance-docs.github.io/apidocs/spot/en/#change-log

is maybe the ratelimit in ccxt binance not up to date for this ?

**Comment by kroitor** [comment]
@baeriswyld the default rateLimit for Binance is set to 500ms, that is 120 requests per minute. You can tweak it as described in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties

```Python
import asyncio
from pprint import pprint
from ccxt import async_support as ccxt

exchange_id = "binance"
config = {
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,  #  ←------------------------- add this
    # 'rateLimit': 500,  # ←----------------- default
}

exchange = getattr(ccxt, exchange_id)(config)

print('Default rate limit:', exchange.rateLimit)

exchange.rateLimit = 60000  # once in a minute

print('Actual rate limit:', exchange.rateLimit)
```

You problem is actually caused by this limitation of the Binance API, as documented in their API docs:

> When all symbols are returned, the number of requests counted against the rate limiter is equal to the number of symbols currently trading on the exchange.

![Screen-Shot-2020-07-30-at-15 47 17](https://user-images.githubusercontent.com/1294454/88925121-c7e9fe00-d27c-11ea-86a1-38123d9a7592.jpg)

Binance has more than 800 pairs. And they allow 1200 requests per minute.

That means, each of your calls without a symbol will cost 1 request * 800 pairs = 800. Thus you can do this request approximately (roughly) once every minute. So, if you set your rate-limit to 60 seconds, you should be fine.

```Python
import asyncio
from pprint import pprint
from ccxt import async_support as ccxt

exchange_id = "binance"
config = {
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,  #  ←------------------------- add this
    'rateLimit': 60000,  # ←-------------- 60000 ms = 60 sec
}

async def open_orders(exchange_id, config):
    exchange = getattr(ccxt, exchange_id)(config)
    while i in range(0, 1000):
        print('---------------------------------------------------')
        print('Iteration', i)
        # reuse the same exchange in a loop instead of restarting this entire script
        orders = await exchange.sapiGetMarginOpenOrders()  
        pprint(orders)
    await exchange.close()

loop = asyncio.get_event_loop()
loop.create_task(open_orders(exchange_id))
```

--------------------------------------------------

Alternatively, if you add a symbol argument, then each call will cost 1, and you can do 1200 of such requests every minute:

```Python
import asyncio
from pprint import pprint
from ccxt import async_support as ccxt

exchange_id = "binance"
config = {
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,  #  ←------------------------- add this
}

async def open_orders(exchange_id, config):
    exchange = getattr(ccxt, exchange_id)(config)

    await exchange.load_markets()  #  ←------------------------------ load all markets first
    symbol = 'BTC/USDT'
    market = exchange.market(symbol)

    while i in range(0, 1000):
        print('---------------------------------------------------')
        print('Iteration', i)
        # reuse the same exchange in a loop instead of restarting this entire script
        orders = await exchange.sapiGetMarginOpenOrders({
            'symbol': market['id'],  #  as described in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
        })  
        pprint(orders)
    await exchange.close()

loop = asyncio.get_event_loop()
loop.create_task(open_orders(exchange_id))
```

I hope that answers your question.

**Comment by baeriswyld** [comment]
thank you @kroitor .

I did the call with the symbol added,
however, after the 4th call (symbol="BTCUSDT") i get the RequestTimeout error...

Not sure if call per symbol is really counted with cost 1. 
Could this be an error on Binance side?

```
from ccxt import async_support as ccxt
import time

exchange_id = "binance"
config = {
    'apiKey': '###',
    'secret': '###',
    'enableRateLimit': True
}

provider = getattr(ccxt, exchange_id)(config)

import asyncio
async def open_orders(provider):
    t0=time.time()
    params = {"symbol":"BTCUSDT"}
    orders = await provider.sapiGetMarginOpenOrders(params)
    print("Open orders: {}, loaded in: {}".format(orders, time.time() - t0))

loop = asyncio.get_event_loop()
for i in range(10):
    loop.create_task(open_orders(provider))
```

Output, error after the 9th call:

```
Open orders: [], loaded in: 0.4037661552429199
Open orders: [], loaded in: 0.7908356189727783
Open orders: [], loaded in: 1.3177800178527832
Open orders: [], loaded in: 2.355193614959717
Open orders: [], loaded in: 3.880181074142456
Open orders: [], loaded in: 4.330535173416138
Open orders: [], loaded in: 8.391566276550293
Open orders: [], loaded in: 11.124841451644897
Task exception was never retrieved
future: <Task finished coro=<open_orders() done, defined at <ipython-input-1-af6e1bbc7a84>:14> exception=RequestTimeout('G .... -->> RequestTimeout error
```

thank you so much for your help !!!
