### ISSUE TITLE
 fetchOrders with all symbols ? 

### ISSUE THREAD

**Issue by alexandrebouttier** [ccxt/ccxt#7389]
Hello, I would like to know if anyone has a solution to get all the orders of all the symbols of the exchange, because with fetchOrders only one 1 is limited, which is not practical, I would like to get everything back, if anyone has a solution in javacript, thanks.

**Comment by kroitor** [comment]
@alexandrebouttier Binance API requires a symbol, i don't think you can workaround that.

- https://binance-docs.github.io/apidocs/spot/en/#query-order-user_data
- https://binance-docs.github.io/apidocs/futures/en/#query-order-user_data
- ...

In general, you can't get everything in one query. Some exchanges would allow you to omit the symbol, but most of them wll require a symbol. So, you will need to query your symbols one by one, or use multiple keypairs to poll each symbol constantly on separate machines.

Let us know if that does not answer the question.

**Comment by alexandrebouttier** [comment]
thank you for your answer, so you don't have to choose to map on all the symbols, and to do the fetchOrders, heavy but if there are no other solutions

**Comment by alexandrebouttier** [comment]
@kroitor 
Good with a map on all the symbols it works, but unfortunately my ip is quickly banned.
My question is it possible to launch the request with the IP of the user and not the IP of my server, to work around this problem, because I am developing an application with MeteorJS / React to allow users to track their portfolios crypto with all exchanges, so if the request is always from the web server, and not from the user's p on my application, it is unmanageable I could put limits, if there are too many users everything will crash, if anyone has an idea? thank you

**Comment by kroitor** [comment]
@alexandrebouttier how do you initialize the exchange?

**Comment by alexandrebouttier** [comment]
I get the keys back to use it then

  ```
const exchangeClass = ccxt[platformKey.exchangeName];
        const exchange = new exchangeClass({
          apiKey: platformKey.apikey,
          secret: CryptoJS.AES.decrypt(
            platformKey.apisecret,
            'xxxxxxxxxxxxxxxxxx'
          ),
          timeout: 30000,
          enableRateLimit: true,
        });
```

**Comment by kroitor** [comment]
@alexandrebouttier you're having one exchange class instance per each exchange, right? Do you have more than one instance of the same exchange working in parallel?

**Comment by alexandrebouttier** [comment]
I call my getOrders method on the client side when the user and on the orders page

``import { check } from 'meteor/check';
import { Meteor } from 'meteor/meteor';
import { Orders } from './orders';
import { Apikeys } from '../apikeys/apikeys';
import { Platforms } from '../platforms/platforms';

const ccxt = require('ccxt');

Meteor.methods({
  getOrders() {
    console.log('getOrders');
    const userApikeys = Apikeys.find({ user_id: Meteor.userId() }).fetch();

    if (userApikeys) {
      userApikeys.map((platformKey) => {
        const exchangeName = platformKey.platformName;
        const exchangeClass = ccxt[exchangeName];
        const exchange = new exchangeClass({
          apiKey: platformKey.apikey,
          secret: CryptoJS.AES.decrypt(
            platformKey.apisecret,
            'XXXXXXXXXXXXXX'
          ),
          timeout: 30000,
          enableRateLimit: true,
        });

        const platform = Platforms.findOne({
          _id: platformKey.platform_id,
        });

        platform &&
          platform.symbols &&
          platform.symbols.map((symbol) => {
            return exchange
              .fetchOrders(symbol)
              .then((orders) => {
                orders &&
                  orders.map((order) => {
                    if (
                      Orders.find({
                        user_id: Meteor.userId(),
                        id: order.id,
                      }).count() === 0
                    ) {
                      return Orders.insert({
                        user_id: Meteor.userId(),
                        platform_id: platformKey.platform_id,
                        platformName: platformKey.platformName,
                        apikey: platformKey.apiKey,
                        id: order.id,
                        info: order.info,
                        clientOrderId: order.clientOrderId,
                        timestamp: order.timestamp,
                        datetime: order.datetime,
                        symbol: order.symbol,
                        type: order.type,
                        side: order.side,
                        price: order.price,
                        amount: order.amount,
                        cost: order.cost,
                        average: order.average,
                        filled: order.filled,
                        remaining: order.remaining,
                        status: order.status,
                        createdAt: new Date(),
                      });
                    }
                  });
              })
              .catch((err) => {
                throw new Meteor.Error('bad', 'Erreur de sync' + err);
              });
          });
      });
    }
  },
});

**Comment by kroitor** [comment]
@alexandrebouttier ok, and which specific error do you get?  Also, do you understand how the rate-limiting works?

**Comment by kroitor** [comment]
@alexandrebouttier the rate-limiter belong to an exchange instance, so if you call your implementation of `getOrders`, it will create an exchange instance, will do a short operation (a call to fetchOrder), and then will destroy the exchange instance, effectively destroying the rate-limiter as well. If, you call `getOrders` frequently, or do something like that in parallel (create-call-destroy), then your exchange instances are not shared across your calls to `getOrders`. You're may be creating them and destroying them on every call to `getOrders`. If that is the case, I'd recommend to share the exchange instances over the entire Meteor application (one class instance of each specific exchange per application / per IP / per machine). If that code is launched by the user of your App on the user's machine, then you should make sure that you share the same exchange instances throughout the entire app. You can simply have a property like `.exchanges` on your Meteor app, and create them once upon program launch. Let us know if that doesn't help.

**Comment by alexandrebouttier** [comment]
Yes, that's what I'm trying to do to be able to launch all ccxt requests by the user's ip client, not fully understood to resolve this with MeteorJS knowing that the user has the possibility of having several exchanges " api keys store in db so I already know what platforms it uses

**Comment by kroitor** [comment]
@alexandrebouttier on the user side a meteor app is nothing more than just a browser app, and you can't fully communicate with all exchanges directly from the users' browsers due to CORS limitations. Only a few exchanges support CORS, while most of the exchanges don't.

- https://github.com/ccxt/ccxt/wiki/Install#cors-access-control-allow-origin
- https://en.wikipedia.org/wiki/Cross-origin_resource_sharing

So, if you want to serve multiple users you will want to consider scaling the architecture of your application.

**Comment by alexandrebouttier** [comment]
Thank you to you for your help and for your commitment, I will look on my own, if I do not unfortunately find my project will serve me for personal use, really a pity that the platforms limited by ip, and not by API key, CCXT was a good solution, too bad the platforms are not open enough, I wonder which api it uses Cointracking  https://www.cointracking.info/
