### ISSUE TITLE
Where is the code that is responsible for filters on binance? (PHP)

### ISSUE THREAD

**Issue by StasToken** [ccxt/ccxt#7391]
Actually, this is just a question, for the sake of academic interest I wanted to see how you have implemented checking [these filters](https://binance-docs.github.io/apidocs/spot/en/#filters) But how can I not find the implementation in the code, can you tell me where to look?

**Comment by kroitor** [comment]
The filters are available in each market['info'].

The implementation is here:

- https://github.com/ccxt/ccxt/blob/master/js/binance.js#L557
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/binance.py#L570
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/async_support/binance.py#L570
- https://github.com/ccxt/ccxt/blob/master/php/binance.php#L564

Those values are unified as market properties, as described in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#market-structure
- https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits

------------------------------------------------

You can get the raw filters as is from Binance API like shown below:

```PHP
$exchange_id = 'binance';
$exchange_class = "\\ccxt\\" . $exchange_id;
$exchange = $exchange_class(array(
    'enableRateLimit' => true,
))

$exchange->load_markets();
$symbol = 'BTC/USDT';
$market = $exchange->market($symbol);
print_r($market['info']['filters']);
```

Let us know if that does not answer your question.

**Comment by StasToken** [comment]
@kroitor Many thanks!
