### ISSUE TITLE
Binance future MARKET order creation

### ISSUE THREAD

**Issue by w0dm4n** [ccxt/ccxt#7394]
- OS: Windows 10
- Programming Language version: JS `node v12.16.3`
- CCXT version: 1.32.23

Hello, there is an issue on /fapi/v1/order (Binance future order creation),
when using defaultType 'future' `this.exchange.options.defaultType = 'future'` on the exchange class and sending a 'createOrder' request with a LIMIT type 
` const order = await this.exchange.createOrder('${coin}/${market}', 'LIMIT', 'buy', quantity, price)` is working well

but as using 'MARKET' type (according to the list here: https://binance-docs.github.io/apidocs/futures/en/#new-order-trade)
the sent payload replace `quantity` by `quoteOrderQty` which do not exist on the possible parameters (link above) with an invalid amount:

```
timestamp=1596123848562&recvWindow=5000&symbol=ETHUSDT&type=MARKET&side=BUY&quoteOrderQty=5&signature=7c0a3173efcf5b6120e10407fb1c79ed1f64e3f686bbcbb9a678286ff72331bb
```
which result as response from binance: 
```
{"code":-1102,"msg":"A mandatory parameter was not sent, was empty/null, or malformed."}
```

**Comment by kroitor** [comment]
@w0dm4n how do you create the market order? If you specify the price there and it is not `undefined`, it will multiply amount * price. Just omit the price for a market order. Let us know if that does not help, or just post the code you use for creating market orders.

**Comment by kroitor** [comment]
Duplicate: 

- https://github.com/ccxt/ccxt/issues/6396
- https://github.com/ccxt/ccxt/issues/6391

**Comment by w0dm4n** [comment]
> Duplicate:
> 
> * #6396
> * #6391

Removed the price for an undefined value according to the update and it's now working! thanks for the quick answer 👍

**Comment by Mazon7** [comment]
@frosty00 @kroitor  yes, I just mixed these two settings which was my stupid fault)
Anyways, having such helpful community means a lot! 💪🏻
