### ISSUE TITLE
Setting aggregation points on orderbook

### ISSUE THREAD

**Issue by brennanfife** [ccxt/ccxt#7403]
Must start off by saying today was the first time I came across this library and am already really liking it. I've been able to pull in orders from Coinbase Pro into some JS with the correct limits and now wish to set some aggregation points. On this exchange, it lets users aggregate (or round) the orders from between 0.01, 0.5, 0.10, 0.50, 1.00, 2.50, 5.00, and 10.0 intervals. Currently, I have a polling function with the following logic:

```
(async () => {
        const CCXT = ccxt as any;
        const exchange = new CCXT['coinbasepro']({
          enableRateLimit: true,
        }) as ccxt.Exchange;

        await exchange.loadMarkets();

        const orderbook = await exchange.fetchOrderBook('BTC/USD');
        console.log('orderbook:', orderbook);
      })();
```

I was reading this [doc](https://buildmedia.readthedocs.org/media/pdf/ccxt/stable/ccxt.pdf) I found on Google, but felt a little overwhelmed. Any help or guidance would be very much appreciated

**Comment by brennanfife** [comment]
Would this be a call I would need to manually filter for after getting back my orders or could I find this under Coinbase's API doc's somewhere? Was reading over the manual tonight, thinking I needed to pass in the 3rd argument parameters for exchange.fetchOrderBook(symbol); but still couldn't get to a potential solution answer.

**Comment by kroitor** [comment]
Hi!

After `fetchOrderBook`, you can apply some not very hard logic to aggregate bids and asks how you like. In other words, this is not really a question about CCXT, but more a question about how to use JavaScript/TypeScript for grouping amounts by prices rounded to a certain step size.

See the following example, let us know if that does not answer your question:

- https://github.com/ccxt/ccxt/tree/master/examples/js/aggregate-orderbook.js

```JavaScript
const ccxt = require ('ccxt')

const aggregateOrderBookSide = function (orderbookSide, precision = undefined) {
    const result = []
    const amounts = {}
    for (let i = 0; i < orderbookSide.length; i++) {
        const ask = orderbookSide[i]
        let price = ask[0]
        if (precision !== undefined) {
            price = ccxt.decimalToPrecision (price, ccxt.ROUND, precision, ccxt.TICK_SIZE)
        }
        amounts[price] = (amounts[price] || 0) + ask[1]
    }
    Object.keys (amounts).forEach (price => {
        result.push ([
            parseFloat (price),
            amounts[price]
        ])
    })
    return result
}

const aggregateOrderBook = function (orderbook, precision = undefined) {
    let asks = aggregateOrderBookSide(orderbook['asks'], precision)
    let bids = aggregateOrderBookSide(orderbook['bids'], precision)
    return {
        'asks': ccxt.sortBy (asks, 0),
        'bids': ccxt.sortBy (bids, 0, true),
        'timestamp': orderbook['timestamp'],
        'datetime': orderbook['datetime'],
        'nonce': orderbook['nonce'],
    };
}

;(async () => {

    const exchange = new ccxt.coinbasepro({
        enableRateLimit: true,
    })

    await exchange.loadMarkets ()

    // exchange.verbose = true // uncomment for verbose debug output

    // level 2 (default)
    const orderbook = await exchange.fetchOrderBook('BTC/USD')

    // or level 3
    // const orderbook = await exchange.fetchOrderBook('BTC/USD', undefined, { 'level': 3 })

    const step = 0.5 // 0.01, 0.1, 0.5, 1.0, 2.5, 5.0, 10.0
    console.log (aggregateOrderBook (orderbook, step))

})();
```
