### ISSUE TITLE
[KRAKEN] Fetch my trades is date limited

### ISSUE THREAD

**Issue by fogkaspoker** [ccxt/ccxt#7404]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/FAQ
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Proxmox container
- Programming Language version: 3.8.3 | packaged by conda-forge
- CCXT version: 1.32.2

When I fetch my trades, I always get the trades starting from 27/05/2020. Even though I specified the "since" and put a very high "limit" on the call. Here is the code
```
exchange = ccxt.kraken ({  # ←---------- you create the `exchange` here
    'apiKey': API_KEY,  # ←------------------- replace with your apiKey
    'secret': API_SEC,  # ←------------------- replace with your secret
    'verbose' : True
})
markets = exchange.load_markets()
strades = exchange.fetch_my_trades(symbol=None, since=1546461164000, limit=None, params={})



[{'id': 'xxxxxxx',
  'order': 'xxxx',
  'info': {'ordertxid': 'xxxxx',
   'postxid': 'xxxxx',
   'pair': 'xxxxxx',
   'time': xxxxx,
   'type': 'xxx',
   'ordertype': 'xxxx',
   'price': 'xxx',
   'cost': 'xxx',
   'fee': 'xxx',
   'vol': 'xxxx',
   'margin': '0.00000000',
   'misc': '',
   'id': 'xxxxxxx'},
  **'timestamp': 1590541224083,
  'datetime': '2020-05-27T01:00:24.083Z',**


how can I fetch the trades older than that date? maybe 2 years older.

Thanks in advance.

**Comment by kroitor** [comment]
It's hard to help without seeing the actual verbose output, can you share it?
Do you see those earlier trades on the website?
Are you sure that those trades belong to that exact keypair?

**Comment by fogkaspoker** [comment]
HI,

Thanks for the answer:



- It's hard to help without seeing the actual verbose output, can you share it?

I'm not sure how to get a verbose output from Jupyter. is there any quick way to do this? --> I'll be checking.

- Do you see those earlier trades on the website?

Yes. I can see all the trades directly in the exchange, and I can even download them in CSV. but I'm trying to read them directly using ccxt


- Are you sure that those trades belong to that exact keypair?

I do not understand the question. But the output should give all the trades regardless of the keypair. and it is how is working now. But It does not go back further than 27 May 2020.

**Comment by kroitor** [comment]
@fogkaspoker let us know if this example does not answer your question:

- https://github.com/ccxt/ccxt/tree/master/examples/py/kraken-fetch-my-trades-pagination.py

```Python
import ccxt


exchange = ccxt.kraken({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_API_SECRET',
    'enableRateLimit': True,  # required by the Manual https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
})

exchange.load_markets()

# exchange.verbose = True  # uncomment for verbose debug output

exchange.rateLimit = 10000  # set a higher value if you get rate-limiting errors

all_trades = []
offset = 0
while True:
    trades = exchange.fetch_my_trades(symbol=None, since=None, limit=None, params={'ofs': offset})
    print('-----------------------------------------------------------------')
    print(exchange.iso8601(exchange.milliseconds()), 'Fetched', len(trades), 'trades')
    if len(trades) < 1:
        break
    else:
        first = exchange.safe_value(trades, 0)
        last = exchange.safe_value(trades, len(trades) - 1)
        print('From:', first['datetime'])
        print('To:', last['datetime'])
        all_trades = trades + all_trades
        offset += len(trades)
    print(len(all_trades), 'trades fetched in total')

print('-----------------------------------------------------------------')
print(len(all_trades), 'trades fetched')
first = exchange.safe_value(all_trades, 0)
if first:
    last = exchange.safe_value(all_trades, len(all_trades) - 1)
    print('First:', first['datetime'])
    print('Last:', last['datetime'])
```

**Comment by fogkaspoker** [comment]
Hello,

Thanks for this, It is working like a charm now. With this code I can get all the trades since the beginning.

Thanks!!
