### ISSUE TITLE
What happens if exchange.createLimitSellOrder call fails due to broken network connection?

### ISSUE THREAD

**Issue by dmitriano** [ccxt/ccxt#7411]
OS: Windows 10
Programming Language version: JavaScript v8.12.0
CCXT version: 1.25.75
Exchange: binance
Method: exchange.createLimitSellOrder/exchange.createBuySellOrder

Consider the following scenario:

I am trying to create a sell order, for example:

```
        try
        {
            const newOrder = await exchange.createLimitSellOrder('BTC/USDT', 1000, 12000);
        }
        catch (e)
        {
            //what should I do here?
        }

```
in your code inside `createLimitSellOrder` function implementation you send HTTP request, Binance receives it and creates the order, but within a nanosecond after that some bad guy unplugs a network cable, so you do not receive HTTP response and throw an exception because TCP connection is broken. At this point the order is created, but I do not have its ID.

Is my understanding of this scenario correct?

If yes, the obvious workarounds are:

1) Check the balance.
2) Find the order by the price.
3) Find the order by date.

but they all are not adult, but for children :)

probably a more adult way is to 

4) Call `exchange.FetchOpenOrders` and/or `exchange.FetchClosedOrders` and compare the result with previously saved orders.

but it is ugly.

Is there a better way to handle this?

**Comment by kroitor** [comment]
> If yes, the obvious workarounds are:
>
> Check the balance.
> Find the order by the price.
> Find the order by date.
> but they all are not adult, but for children :)
>
> probably a more adult way is to
>
> Call exchange.FetchOpenOrders and/or exchange.FetchClosedOrders and compare the result with previously saved orders.

The general approach is to use all possible means to restore the order and to make sure that your logic works how you want it. Also, pay attention to error handling (try/catch and retries) while you are handling the errors with async methods.

You should use `fetchOrders` or `fetchOpenOrders` + `fetchClosedOrders` (whatever is available). 

You should use the `clientOrderId` param where applicable. It's a user-specific order id, and you can identify your orders by matching them against a `clientOrderId`. So, if your order placement request reached the exchange, the order will have a `clientOrderId`. If you can't find the `clientOrderId` among your recent open and closed orders, that means, the order has not been placed.

Also, you can restore previously closed orders from `fetchMyTrades`. Sometimes the ledger entries from `fetchLedger` can help. 

In pseudocode it would look like shown below, write the missing sections yourself:

```JavaScript
async function restoreOrder (timestamp, symbol, type, side, amount, price, params) {

    let done = false
    
    while (!done) {

        let order = undefined

        if (exchange.has.fetchOrders) {
            try {
                const orders = await exchange.fetchOrders (symbol)
                order = restoreFromOrders (orders, timestamp, symbol, type, side, amount, price, params)
                if (order !== undefined) {
                    return order
                }
            } catch (e) {
                // retry ?
            }
        } 

        if (exchange.has.fetchOpenOrders) {
            // retry if necessary....
            const openOrders = exchange.fetchOpenOrders (symbol)
            order = restoreFromOrders (orders, timestamp, symbol, type, side, amount, price, params)
            if (order !== undefined) {
                return order
            }
        }

        if (exchange.has.fetchClosedOrders) {
            // ...
        }

        if (exchange.has.fetchMyTrades) {
            // your logic here...
        }

        if (exchange.has.fetchLedger) {
            // ...
        }

        // detect recent balance changes by matching against the balance history

        // order not found == order placement failed and the order has not been placed or has not reached the exchange?
    }
}

async function restoreFromOrders (orders, timestamp, symbol, type, side, timestamp, amount, price, params) {

    const clientOrderId = this.safeString (params, 'clientOrderId');
    const ordersByClientOrderId = exchange.groupBy (orders, 'clientOrderId');

    // console.log (ordersByClientOrderId)

    const order = exchange.safeValue (ordersByClientOrderId, clientOrderId);

    if (order === undefined) {

        // not found
        // restore by matching order timestamp, symbol, type, side, amount, price, etc
        
    } else {

        return order
    }
}

const symbol = 'BTC/USDT'
const type = 'limit'
const side = 'sell'
const amount = 1000
const price = 12000
const clientOrderId = exchange.uuid ()
const params = { clientOrderId }

try {

    let order = await exchange.createOrder (symbol, type, side, amount, price, params)

} catch (e) {

    // what should I do here?

    order = await restoreOrder (symbol, type, side, amount, price, params)

}
```

Hope that answers your question.
