### ISSUE TITLE
error to get GetWebSocketsToken on Kraken

### ISSUE THREAD

**Issue by melnikovsa** [ccxt/ccxt#7423]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/FAQ
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version: python3.8
- CCXT version: 1.22.96

```
connector_cls = getattr(ccxt, 'kraken', None)

connector_params = {
      'apiKey': self.exchange_api_key,
      'secret': self.exchange_api_secret,
      'timeout': 30_000
}

await exchange.fetch2('GetWebSocketsToken', api='private', method='GET', params={})
```

```
kraken {"error":["EGeneral:Invalid arguments"]}
```

**Comment by kroitor** [comment]
```Python
import asyncio
import ccxt.async_support as ccxt 


async def test_kraken():
    exchange = ccxt.kraken({
        'apiKey': 'YOUR_API_KEY',
        'secret': 'YOUR_SECREY',
        'enableRateLimit': True,  # required by the Manual! https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
    })
    exchange.load_markets()
    response = await exchange.private_post_getwebsocketstoken()
    print(response)
    await exchange.close()


asyncio.get_event_loop().run_until_complete(test_kraken())
```

------------

```Python
connector_cls = getattr(ccxt, 'kraken', None)

connector_params = {
      'apiKey': self.exchange_api_key,
      'secret': self.exchange_api_secret,
      'timeout': 30_000,
      'enableRateLimit': True,  # required by the Manual! https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
}

await exchange.fetch2('GetWebSocketsToken', api='private', method='POST', params={})
```

I'd recommend to read the entire Manual from top to bottom, it will save your time:

- https://github.com/ccxt/ccxt/wiki
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- ...

Let us know if the above does not answer your question.
