### ISSUE TITLE
Typo "occured"

### ISSUE THREAD

**Issue by scottwedge** [ccxt/ccxt#7425]
Occurred is spelled "occured" several times in the code.

**Comment by kroitor** [comment]
@scottwedge if you mean this:

<img width="433" alt="Screen Shot 2020-08-07 at 21 46 36" src="https://user-images.githubusercontent.com/1294454/89678236-864df880-d8f7-11ea-95f8-93f9f5b3cc7a.png">

That's the phrasing from the exchange APIs "as is". We don't add corrections to those, they should match the response most of the time.

Let me know if you find more.
