### ISSUE TITLE
New Exchange: MCDEX

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#7431]
MCDEX is a dex with decent trading volume (order book, AMM) and derivative contracts ETH-Perp and soon LINK-Perp and BTC-Perp contracts.

https://mcdex.io/
https://mcdex.io/doc/api/#introduction
https://t.me/Mcdex/15701
https://t.me/Mcdex/12789

**Comment by frosty00** [comment]
dead exchange
