### ISSUE TITLE
BitMax Auth Error

### ISSUE THREAD

**Issue by Stevenje** [ccxt/ccxt#7435]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/FAQ
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:

let bitmax = new ccxt.bitmax({
apiKey: XXXXX,
secret: XXXX
})

  console.log(bitmax.id, await bitmax.fetchBalance());

```
AuthenticationError: bitmax {"code":200001,"message":"API signature mismatch","reason":"AUTHENTICATION_FAILED"}
```

**Comment by kroitor** [comment]
Your apiKey should have a length of 32 symbols, and the secret should have a length of 64 symbols.

```JavaScript
const ccxt = require ('ccxt')

async test () {

    const exchange = new ccxt.bitmax({
        'apiKey': 'YOUR_API_KEY',
        'secret': 'YOUR_SECRET',
        'enableRateLimit': true, // required: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
    })

    const balance = await exchange.fetchBalance ()
    console.log (exchange.id, balance)

}

console.log ('CCXT Version:', ccxt.version)

test ()
```

↑ If it doesn't work, paste your verbose request/response and version numbers:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by Stevenje** [comment]
Thanks for the quick help! Yes Api and secret do match required lengths. I've also tried regenerating them and still no luck

**CCXT Version: 1.32.87**

`fetch:
 bitmax GET https://bitmax.io/api/pro/v1/futures/contracts 
Request:
 {} 
 undefined 

handleRestResponse:
 bitmax GET https://bitmax.io/api/pro/v1/futures/contracts 200 OK 
Response:
 {
  Date: 'Sun, 09 Aug 2020 18:36:55 GMT',
  'Content-Type': 'application/json',
  'Transfer-Encoding': 'chunked',
  Connection: 'close',
  'Set-Cookie': '__cfduid=de02d06cc4d308a2a027be705081618661596998215; expires=Tue, 08-Sep-20 18:36:55 GMT; path=/; domain=.bitmax.io; HttpOnly; SameSite=Lax; Secure',
  Instance: '7-_-3',
  'Strict-Transport-Security': 'max-age=15552000; includeSubDomains; preload',
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Content-Type-Options': 'nosniff',
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Request-Id': '04761bfe570000d505bfba5200000001',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Cf-Ray': '5c0395dd5bead505-MIA',
  'Content-Encoding': 'gzip'
} 
 {"code":0,"data":[{"symbol":"BTC-PERP","displayName":"BTCUSDT","tradingStartTime":1579701600000,"collapseDecimals":"1,0.1,0.01","minQty":"0.000000001","maxQty":"1000000000","minNotional":"0","maxNotional":"1000000","statusCode":"Normal","statusMessage":"","tickSize":"0.25","lotSize":"0.0001","priceScale":2,"qtyScale":4,"notionalScale":2}]} 

fetch:
 bitmax GET https://bitmax.io/api/pro/v1/info 
Request:
 {
  'x-auth-key': 'U69ZjCo8suG1XFBtU7MKsLopfl6LKFcN',
  'x-auth-timestamp': '1596998215599',
  'x-auth-signature': 'iCmTduMDkHT91BJecsJYFGvXzKJZ86XF2iJnGtFam8Q='
} 
 undefined 

handleRestResponse:
 bitmax GET https://bitmax.io/api/pro/v1/info 200 OK 
Response:
 {
  Date: 'Sun, 09 Aug 2020 18:36:55 GMT',
  'Content-Type': 'application/json',
  'Transfer-Encoding': 'chunked',
  Connection: 'close',
  'Set-Cookie': '__cfduid=dc6c500776fba598b99c09748f47965bf1596998215; expires=Tue, 08-Sep-20 18:36:55 GMT; path=/; domain=.bitmax.io; HttpOnly; SameSite=Lax; Secure',
  Instance: '_-_-2',
  'Strict-Transport-Security': 'max-age=15552000; includeSubDomains; preload',
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Content-Type-Options': 'nosniff',
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Request-Id': '04761c00470000e9547d843200000001',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Cf-Ray': '5c0395e07e5fe954-MIA',
  'Content-Encoding': 'gzip'
} 
 {"code":200001,"message":"API signature mismatch","reason":"AUTHENTICATION_FAILED"} 

(node:22700) UnhandledPromiseRejectionWarning: AuthenticationError: bitmax {"code":200001,"message":"API signature mismatch","reason":"AUTHENTICATION_FAILED"}
    at bitmax.throwExactlyMatchedException (/Users/steven/Documents/nodetrader/node_modules/ccxt/js/base/Exchange.js:553:19)
    at bitmax.handleErrors (/Users/steven/Documents/nodetrader/node_modules/ccxt/js/bitmax.js:1716:18)
    at /Users/steven/Documents/nodetrader/node_modules/ccxt/js/base/Exchange.js:649:18
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async timeout (/Users/steven/Documents/nodetrader/node_modules/ccxt/js/base/functions/time.js:183:24)
    at async bitmax.fetchAccounts (/Users/steven/Documents/nodetrader/node_modules/ccxt/js/bitmax.js:489:24)
    at async bitmax.loadAccounts (/Users/steven/Documents/nodetrader/node_modules/ccxt/js/base/Exchange.js:738:33)
    at async bitmax.fetchBalance (/Users/steven/Documents/nodetrader/node_modules/ccxt/js/bitmax.js:522:9)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:22700) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22700) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by Stevenje** [comment]
PS. I have successfully authenticated to several other exchanges and the issue is only with BitMax

**Comment by kroitor** [comment]
@Stevenje somehow, my older keypair works, while a new keypair does not work... Which makes me think it could be an issue on BitMax, because the signing algorithm is identical in both cases. I will investigate further and will get back to you as soon as possible.

**Comment by Stevenje** [comment]
@kroitor Thank you!

**Comment by kroitor** [comment]
@Stevenje a couple of quick questions, just to clarify:

- is this the first key on the list of your keys, when you open the "API setting" section on BitMax's website?
- is this the only existing key on that same list?

**Comment by Stevenje** [comment]
@kroitor It's a brand new account and on the API settings page I have 2 api keys set up. The first one initially didn't work with ccxt so I created a second to test if I had missed something. 

They're both in Account 1 and in the top right when I hover over the question mark it says - "You will need to include account group in the URL for all your private RESTful and WebSocket requests."

Are we currently passing the account group?

**Comment by kroitor** [comment]
@Stevenje 

> Are we currently passing the account group?

Yes, but in your case it breaks even before that – upon fetching your accountGroup from the `https://bitmax.io/api/pro/v1/info` endpoint. I've raised this to BitMax's support, will report back here.

**Comment by kroitor** [comment]
@Stevenje let us know if you still have issues with it after upgrading to CCXT 1.33.2+. Thx!

**Comment by Stevenje** [comment]
@kroitor working great, thanks a lot! Great work. 

By the way, any chance of supporting https://bilaxy.com/ in the future?
