### ISSUE TITLE
HitBTC2 intermittently "order not found

### ISSUE THREAD

**Issue by fqlx** [ccxt/ccxt#7440]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/FAQ
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Linux
- Programming Language version: Python
- CCXT version: 1.32.36

It seems CCXT is intermittently finding to the order id on HitBtc.  I believe this is a Hitbtc issue.

```print(hitbtc.fetch_order('XXXXX'))```

**Comment by kroitor** [comment]
@fqlx It depends on the actual call sequence. HitBTC differentiates the orders by "active" or "historical" regardless of the orders' statuses, this is why it is one of those rare exchanges that has two versions of `fetchOrder`:

1. `fetchOrder` for "historical" orders
2. `fetchOpenorder` for "active" orders

```Python
import ccxt
from pprint import pprint
pprint(ccxt.hitbtc().has)
```

All orders with HitBTC are "active" for a while, then become "historical".

If the above does not answer your question, please paste the code to reproduce the issue including exchange instantation, but without your keys. We also need your verbose requests+responses as described here:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

Feel free to reopen this issue or just ask further questions if any.

**Comment by fqlx** [comment]
I am seeing the fetch_order for "historical" orders work, then sequentially fail, and work again. This doesn't seem related to active orders as I'm not using that API.

Code:
```
for x in range(0, 3):
    try:
        print(hitbtc.fetch_order('order_id_redacted'))
    except Exception as e:
        print(e)
        continue
```

Output:
```
$ python3 hitbtc.py
hitbtc order order_id_redacted not found
{'id': 'order_id_redacted', 'clientOrderId': 'order_id_redacted', 'timestamp': 1597092670791, 'datetime': '2020-08-10T20:51:10.791Z', 'lastTradeTimestamp': 1597092670791, 'status': 'failed', 'symbol': 'BTC/USDT', 'type': 'limit', 'side': 'sell', 'price': 11797.42, 'average': None, 'amount': 0.0487, 'cost': 0.0, 'filled': 0.0, 'remaining': 0.0487, 'fee': None, 'trades': None, 'info': {'id': 280419516463, 'clientOrderId': 'order_id_redacted', 'symbol': 'BTCUSD', 'side': 'sell', 'status': 'expired', 'type': 'limit', 'timeInForce': 'IOC', 'quantity': '0.04870', 'price': '11797.42', 'avgPrice': '0', 'cumQuantity': '0', 'createdAt': '2020-08-10T20:51:10.791Z', 'updatedAt': '2020-08-10T20:51:10.791Z'}}
hitbtc order order_id_redacted not found
```

Here it was not found, successful, and not found again. This intermittently working is why I think it's a HitBtc issue not pulling the historical orders. Thoughts?

**Comment by kroitor** [comment]
> This intermittently working is why I think it's a HitBtc issue not pulling the historical orders.

I would agree to that. If you can raise to HitBTC's tech support and report back here – we will be very thankful.
