### ISSUE TITLE
HitBTC2 intermittently "order not found" when fetching order by id

### ISSUE THREAD

**Issue by fqlx** [ccxt/ccxt#7441]
- OS: Linux
- Programming Language version: Python
- CCXT version: 1.32.36

It seems Hitbtc is intermittently failing to fetch the order id.  I believe this is a HitBtc issue where the API is randomly failing?
Does anyone have a work around?

For example loop the following code:
```print(hitbtc.fetch_order('XXXXX'))```

"Order not found" will appear 30% of the time.

May be related to issue #2301

**Comment by kroitor** [comment]
Answered in this duplicate issue:

- https://github.com/ccxt/ccxt/issues/7440#issuecomment-671577487
