### ISSUE TITLE
Ho to handle  BadSymbol  error?

### ISSUE THREAD

**Issue by optima66** [ccxt/ccxt#7445]
I am trying to learn how to handle errors, in particular case BadSymbol error.
I have this code:
What do I do wrong?
 
```
try:
     trades = ccxt_binance.fetch_my_trades(symbol, None, None, params)
except ccxt.base.errors.BadSymbol as err:
    print('error')
```

**Comment by kroitor** [comment]
@optima66 try this:

```Python
wrong_symbol = 'foobar'
try:
     trades = ccxt_binance.fetch_my_trades(wrong_symbol, None, None, params)
except ccxt.BadSymbol as err:
    print(e)
```

Hope that answers your question.

> What do I do wrong?

For the future, when asking a question, please, always follow the guidelines precisely:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

In general, to be able to help, we need:

- your version numbers
- your code to reproduce the issue
- the output that you get on your screen (error trace, etc)
- verbose request+response

Please make sure to follow the above instructions literally to a word.

**Comment by optima66** [comment]
`AttributeError: module 'ccxt' has no attribute 'BadSymbol'
`

**Comment by kroitor** [comment]
@optima66 how do you import ccxt? 

Try this:

```Python
import ccxt
print(ccxt.BadSymbol)
```

**Comment by optima66** [comment]
```
CCXT Version: 1.18.1226
Internal Server Error: /orders
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/root/coins/coins_new/coins_new2/main_app/views.py", line 19, in orders
    print(ccxt.BadSymbol)
AttributeError: module 'ccxt' has no attribute 'BadSymbol'
```

**Comment by kroitor** [comment]
> CCXT Version: 1.18.1226

That version is too old. Please update to the most recent version 1.32.94+.
In general, checking your version number is step 1 in any troubleshooting sequence:

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

**Comment by optima66** [comment]
thanks!
