### ISSUE TITLE
How to use websocket in python?

### ISSUE THREAD

**Issue by nihow666** [ccxt/ccxt#745]
hi
How to use websocket in python
thx!

**Comment by kroitor** [comment]
Hi! Sorry, but your question is duplicate. We currently don't have support for WS, but we are working on it and it is on the way. More about it in the Manual and here:

- https://github.com/ccxt/ccxt/search?q=ws&type=Issues
- https://github.com/ccxt/ccxt/search?q=websocket&type=Issues
