### ISSUE TITLE
Is it possible to see the 'has' dictionary of ccxt pro without a subscription?

### ISSUE THREAD

**Issue by AlgoQ** [ccxt/ccxt#7451]
I want to know if bitmex has the function 'watchOhlcv' before I buy the ccxt pro subscription, is this possible?
Wouldn't it be great to also include the ccxt pro functions to the ccxt has dictionary of every ccxt pro verified exchange?

**Comment by kroitor** [comment]
<img width="729" alt="Screen Shot 2020-08-11 at 21 12 55" src="https://user-images.githubusercontent.com/1294454/89933266-7bf16e80-dc17-11ea-8fa9-c75ac8c07b22.png">

We will add these tables to the corresponding Manuals so that they are rebuilt automatically upon every build.

**Comment by 646b** [comment]
Where can I find updated table?

**Comment by riko105** [comment]
Hello!

@kroitor It Will be good to have a place with up-to-date features available for each exchange in pro-subscription.

Best Regards.

**Comment by frosty00** [comment]
@riko105 @646b we will add this to the ccxtpro website. we are currently extremely busy so please bear with us

**Comment by JanssensKobe** [comment]
Any updates on this?

**Comment by kroitor** [comment]
@JanssensKobe not yet, but we will hopefully add that soon, will post here immediately.
