### ISSUE TITLE
[FTX] fetch_deposits bug

### ISSUE THREAD

**Issue by nikky78** [ccxt/ccxt#7452]
I am getting the very same error as this issue https://github.com/ccxt/ccxt/issues/6732 but on the FTX exchange.

```
>>> ftx= ccxt.ftx(config=config)
>>> deposits = ftx.fetchDeposits('ETH')
```

I am getting the error:

```
  File "<ipython-input-331-fe3af29d7856>", line 1, in <module>
    deposits = ftx.fetchDeposits('ETH')

  File "\Anaconda3\lib\site-packages\ccxt\ftx.py", line 1310, in fetch_deposits
    return self.parse_transactions(result)

  File "\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 1645, in parse_transactions
    array = [self.extend(self.parse_transaction(transaction, currency), params) for transaction in array]

  File "\Anaconda3\lib\site-packages\ccxt\base\exchange.py", line 1645, in <listcomp>
    array = [self.extend(self.parse_transaction(transaction, currency), params) for transaction in array]

TypeError: parse_transaction() takes 2 positional arguments but 3 were given
```

ccxt version: 1.28.13

**Comment by kroitor** [comment]
@nikky78 what's your version of CCXT?

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by nikky78** [comment]
> @nikky78 what's your version of CCXT?
> 
> * https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

my bad, I have updated the thread with this info

**Comment by kroitor** [comment]
@nikky78 let us know if you still have the same issue with CCXT version 1.33.4+, the new build will arrive in 15 minutes. Thx for reporting!

**Comment by nikky78** [comment]
> @nikky78 let us know if you still have the same issue with CCXT version 1.33.4+, the new build will arrive in 15 minutes. Thx for reporting!

Great ! Thanks for your quick reply!

**Comment by nikky78** [comment]
Actually, right now I get AttributeError: 'ftx' object has no attribute 'fetchDeposits'

**Comment by kroitor** [comment]
Please, paste your output:
```Python
import ccxt
from pprint import pprint
print('CCXT version:', ccxt.__version__)
exchange = ccxt.ftx({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_API_SECRET',
})
exchange.load_markets()
exchange.verbose = True
pprint(exchange.has)
deposits = exchange.fetchDeposits('ETH')
pprint(deposits)
```

↑ Paste your entire output here.

**Comment by nikky78** [comment]
Okay, it was a bug on my side this time I guess, it works like a charm now! Thank you Kroitor!
