### ISSUE TITLE
No live watch_ohlcv data for bitmex (ccxt pro)

### ISSUE THREAD

**Issue by JanssensKobe** [ccxt/ccxt#7453]
Hello, I've just bought the ccxt pro subscription to get access to the up to date ohlcv (BTC/USD) from the bitmex. But now I see the endpoint is 1 minute based and not live data (like binance). Is it possible to gather live ohlcv data from bitmex another way (I wanted to calculated the MACD live and because the rate limit of bitmex is only 60/min, I really want to use websockets)?

Code:
```python
import ccxtpro
import asyncio

async def main(loop):
    exchange = ccxtpro.bitmex({'enableRateLimit': True, 'asyncio_loop': loop})
    while True:
        ohlcv = await exchange.watch_ohlcv('BTC/USD')
        print(ohlcv)
    await exchange.close()

loop = asyncio.new_event_loop()
loop.run_until_complete(main(loop))
```

**Comment by kroitor** [comment]
> Is it possible to gather live ohlcv data from bitmex another way (I wanted to calculated the MACD live and because the rate limit of bitmex is only 60/min, I really want to use websockets)?

Yes. However, you should understand the types of data and how they relate to each other.

On an exchange market trades happen over time, all the time. The history of trades is the primary source of public data. Apart from that, the orders are placed, matched and canceled all the time, so, the orderbook is also your primary data.

All other public data types like tickers, OHLCV candles – are secondary types, derived from the primary sources.

A ticker is nothing more than a statistical calculation over the trades and the orderbook – for 24 hours.
An OHLCV candle is nothing more than a statistical calculation over the trades – in intervals of 1m, 5m, 1h, 12h, 1d, etc.

It is up to the exchange to decide when and how frequently to update that calculation. This is why some exchanges like Binance can send you frequent updates (many times per minute). And some other exchanges can send you less frequent updates (once a minute, for example).

If you process the trades correctly, you should be able to calculate the OHLCV candles in real-time on your side. Suppose, you're calculating 1m-candles:

O = the price of the first trade within that minute
H = the highest price of all trades within that minute
L = the lowest price of all trades within that minute
C = the price of the last trade within that minute
BaseVolume = the sum of amounts of all trades within that minute
QuoteVolume = the sum of costs of all trades within that minute

↑ From there, logically, you can have your own OHLCVs built from trades on your side and those will be as close to real-time trades as possible.

Hope that answers your question.
