### ISSUE TITLE
How do you get the latest orders from Binance?

### ISSUE THREAD

**Issue by viniciussvl** [ccxt/ccxt#7457]
Hi, I'm trying to get the latest orders from Binance, this was my attempt using milliseconds but to no avail, it returns orders from me a few hours ago and not minutes ago.

- OS: Windows 10
- Programming Language version: JavaScript
- CCXT version: 1.28

```
async getOrders(symbol, params = {}) {
        let orders = []
        let since = this.binance.milliseconds() - 2592000000
      
        try {
            orders = await this.binance.fetchClosedOrders(symbol, since, 500)
        } catch (e) {
            let error = {
                error: this.extractErrorMessage(e.message)
            }
            return error
        }

        return orders
    }
```

**Comment by kroitor** [comment]
> How do you get the latest orders from Binance?

If you want the most recent orders, just omit the `since` and `limit` or use `undefined` for those two arguments.

```JavaScript
    async getOrders(symbol, params = {}) {
        try {
            return await this.binance.fetchClosedOrders(symbol)
        } catch (e) {
            let error = {
                error: this.extractErrorMessage(e.message)
            }
            return error
        }
    }
```

Let us know if that does not answer your question.

**Comment by viniciussvl** [comment]
> > Como você recebe os últimos pedidos da Binance?
> 
> Se quiser os pedidos mais recentes, basta omitir `since`e `limit`ou usar `undefined`para esses dois argumentos.
> 
> ```js
>      getOrders assíncronos ( símbolo , parâmetros =  { } )  { 
>         tente  { 
>             retornar  isso . binance . fetchClosedOrders ( símbolo ) 
>         }  catch  ( e )  { 
>             return  { 
>                 error : this . extractErrorMessage ( e . mensagem ) 
>             } 
>         } 
>     }
> ```
> 
> Informe-nos se isso não responder à sua pergunta.

Sorry to be reopening, is that this method is not working for me, it returns orders from 5 days ago and ordered by increasing date and not decreasing.

**Comment by kroitor** [comment]
> Sorry to be reopening, is that this method is not working for me, it returns orders from 5 days ago 

Please, use the pagination as documented in the Manual and shown in the examples:

- https://github.com/ccxt/ccxt/wiki/Manual#pagination
- https://github.com/ccxt/ccxt/tree/master/examples

> and ordered by increasing date and not decreasing.

You can sort it on the client side how you like, CCXT always returns entries sorted by timestamp in ascending order.
