### ISSUE TITLE
bitmart orders endpoint requires an accessToken option or a prior call to signIn() method

### ISSUE THREAD

**Issue by jiazechen** [ccxt/ccxt#7459]
my codes:

php

$bitmart = new \ccxt\bitmart ([
          'apiKey' => 'xxx',
          'secret' => 'xxx',
          'uid' => 'xxx',
          'timeout' => 30000]);

$bitmart->create_order('ETH/USDT', 'limit', 'sell', 10, 200);

throw error: 

ccxt\AuthenticationError: bitmart orders endpoint requires an accessToken option or a prior call to signIn() method in xxx

**Comment by kroitor** [comment]
@jiazechen BitMart has changed the auth scheme slightly, we will adjust the code in CCXT shortly.

**Comment by yen-a** [comment]
Still unresolved?

**Comment by kroitor** [comment]
@yen-a the fix is in the works right now, will upload it soon, hopefully.
