### ISSUE TITLE
New- gmright2 extension in market

### ISSUE THREAD

**Issue by bitokenja3** [ccxt/ccxt#7460]
https://www.google.com/url?sa=t&source=web&rct=j&url=https://woocommerce.com/vendor/gmright2/&ved=2ahUKEwjbw533qpjrAhVMGs0KHaPBDHEQFjAAegQIARAB&usg=AOvVaw2lCSSR2C3h_yadIqVodM2P

**Comment by bitokenja3** [comment]
I think this would be the best things for user who don't know about to start using it

**Comment by kroitor** [comment]
I don't think it's a place for promoting it here. Closing it for now.
