### ISSUE TITLE
PHEMEX: "cancel_all_orders" not implemented although supported by the exchange

### ISSUE THREAD

**Issue by scoriiu** [ccxt/ccxt#7464]
PHEMEX: "cancel_all_orders" not implemented although supported by the exchange
https://github.com/phemex/phemex-api-docs/blob/master/Public-Contract-API-en.md#cancelall

- OS:
- Programming Language version: Python
- CCXT version: 1.33.4

**Comment by scoriiu** [comment]
Excellent work as usual. Thanks!

**Comment by scoriiu** [comment]
@kroitor There is a bug in the implementation that causes a crash here -> https://github.com/ccxt/ccxt/blob/cbd40376bdb7584a227017ea7c9cc29ea4caf598/python/ccxt/phemex.py#L1832
`market['swap']` is used prior to be initialised

Exception `'NoneType' object is not subscriptable'`

**Comment by kroitor** [comment]
@scoriiu pardon, my bad, i've uploaded a fix to it, and it will arrive in 15 minutes in CCXT 1.33.15+. Thx for pointing it out!

**Comment by scoriiu** [comment]
Cool, thanks!
