### ISSUE TITLE
Kucoin ccxt : BadRequest for limit order

### ISSUE THREAD

**Issue by nikky78** [ccxt/ccxt#7468]
OS: windows 10
Programming Language version: python 3.7
CCXT version: 1.33.4

sending limit margin order like this

```
order = exchange.create_limit_buy_order(
            symbol, 
            exchange.amount_to_precision(symbol, amount), 
            exchange.price_to_precision(symbol, price), 
            {'tradeType': 'MARGIN_BUY'})
```

and get the very uncanny error:
`BadRequest: 交易类型不合法`

**Comment by kroitor** [comment]
According to the KuCoin docs the `tradeType` param should be `MARGIN_TRADE`, not `MARGIN_BUY`:

- https://docs.kucoin.com/#place-a-new-order

**Comment by nikky78** [comment]
My bad, I copied past mixed code. My issue was with MARGIN_TRADE. I have updated the ticket

**Comment by nikky78** [comment]
Solved. Thanks
