### ISSUE TITLE
question about binance error

### ISSUE THREAD

**Issue by Fcl69** [ccxt/ccxt#747]
Hello,

the other day I've enocuntered this error maessage:

>   File "ccxt/binance.py", line 587, in handle_errors
    raise InvalidOrder(self.id + ' order amount should be evenly divisible by lot size, use self.amount_to_lots(symbol, amount) ' + body)
ccxt.base.errors.InvalidOrder: binance order amount should be evenly divisible by lot size, use self.amount_to_lots(symbol, amount) 

Details about the order:
> Exchange: binance, side: buy, symbol: ETH/BTC, trade amount: 2.09

Can you please help me to understand what does it mean - "order amount should be evenly divisible by lot size"?

**Comment by kroitor** [comment]
Hi! This is described here: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md !
