### ISSUE TITLE
kucoin privateGetOrdersOrderId does not return filled price 

### ISSUE THREAD

**Issue by nikky78** [ccxt/ccxt#7470]
ccxt version: 1.33.4
programming language: python 3.7

I am trying to get the price at which an order has been filled doing 

exchange.privateGetOrdersOrderId({'orderId': order.get('id')}) 

but the price returned in is 0, while it has been filled at 0.138951 USDT.

Is there perhaps another way to get the price ? even for a direct market order, the price retireved in the order is None

**Comment by kroitor** [comment]
> I am trying to get the price at which an order has been filled doing
> exchange.privateGetOrdersOrderId({'orderId': order.get('id')})
> but the price returned in is 0, while it has been filled at 0.138951 USDT.

When you call `privateGetOrdersOrderId` is direct call to an [implicit API endpoint](https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods) – what you see, is what you get from the exchange API itself.

> Is there perhaps another way to get the price ? even for a direct market order, the price retireved in the order is None

You may want to check your actuals fills (executed trades, `fetchMyTrades` / `fetch_my_trades`) with the [unified CCXT API](https://github.com/ccxt/ccxt/wiki/Manual#unified-api) and then sum the trades' amounts.

I would highly recommend to read the entire Manual from top to bottom – it will save your time, really:

- https://github.com/ccxt/ccxt/wiki
- https://github.com/ccxt/ccxt/wiki/Manual

Let us know if the above does not answer your question.
