### ISSUE TITLE
[gateio] suggest improvement 

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#7477]
gateio v2 api for fetchMyTrades has two options: one with a `tid` param, and one without: https://api.gateio.io/api2#trade

The current ccxt implementation requires an option to be set: 

`'fetchTradesMethod': 'public_get_tradehistory_id', // 'public_get_tradehistory_id_tid'
`

It might be simpler if we could just detect in the `fetchMyTrades` method if (or not) the user has passed the optional a `tid` parameter, and if so we should use the `public_get_tradehistory_id_tid` version of the api call.

**Comment by npomfret** [comment]
thanks!

**Comment by kroitor** [comment]
@npomfret thx to you and to @frosty00 !
