### ISSUE TITLE
doesn't throw exception on binance API limit exceed

### ISSUE THREAD

**Issue by aero-108** [ccxt/ccxt#7484]
- Programming Language version: Python
- CCXT version: 0.3.47

On await exchange.load_markets() 
if ```ccxt.base.errors.DDoSProtection: binance 429 Too Many Requests``` been fired, loop just stuck.
No throwing any exception.

In order to simulate the issue, attached code creating many processes for watchOHLCV. 
In log by PID number its clear, loop just stuck.

Example
```
root@b:/# cat test_api_exceed.log | grep 23784:
23784:[MainThread]:DEBUG      2020-08-19 21:41:15 asyncio                        __init__                             54  : Using selector: EpollSelector
23784:[MainThread]:DEBUG      2020-08-19 21:41:15 ccxt.base.exchange             fetch                                104 : GET https://api.binance.com/api/v3/exchangeInfo, Request: None None
23784:[MainThread]:DEBUG      2020-08-19 21:41:15 ccxt.base.exchange             fetch                                134 : GET https://api.binance.com/api/v3/exchangeInfo, Response: 429 <CIMultiDictProxy('Content-Type': 'application/json;charset=UTF-8', 
'Content-Length': '171', 'Connection': 'keep-alive', 'Date': 'Wed, 19 Aug 2020 21:41:15 GMT', 'Server': 'nginx', 
'x-mbx-uuid': 'e1a09a39-91d0-494e-9e9d-4d7af58cd3b6', 'x-mbx-used-weight': '1380', 
'x-mbx-used-weight-1m': '1380', 'retry-after': '0', 
'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 
'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 
'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 
'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 
'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 
'Expires': '0', 'X-Cache': 'Error from cloudfront', 
'Via': '1.1 3f6fbf009bb5cf969f92ba2e59576614.cloudfront.net (CloudFront)', 
'X-Amz-Cf-Pop': 'FRA53-C1', 
'X-Amz-Cf-Id': 'wgrwZYxAXxHKmoFf1w1bjWKfPR3R-nXmyqlKQwQSTQhLTQbsvhBOMA==')> {"code":-1003,"msg":"Too much request weight used; current limit is 1200 request weight per 1 MINUTE. Please use the websocket for live updates to avoid polling the API."}


And that's it.
```

Question is not about respect exchange API limits,
given scenario is just example, and it doesn't work as should.

Code
```
import logging
import ccxtpro
import ccxt
import asyncio
import multiprocessing
from time import sleep

EXCHANGE_NAME = 'binance'

LOG_FORMAT = ('%(process)d:[%(threadName)s]:%(levelname) -10s %(asctime)s %(name) -30s %(funcName) '
              '-35s %(lineno) -5d: %(message)s')
logging.basicConfig(level=logging.DEBUG, format=LOG_FORMAT, datefmt='%Y-%m-%d %H:%M:%S',
                    filename='test_api_exceed.log')


async def main(symbol, timeframe):
    exchange_class = getattr(ccxtpro, EXCHANGE_NAME)
    exchange = exchange_class({'enableRateLimit': True, 'verbose': False})
    await exchange.load_markets()

    while True:
        try:
            ohlcvs = await exchange.watch_ohlcv(symbol, timeframe, None, 1000)
            now = exchange.milliseconds()
            logging.info(('EXCEPTION', exchange.iso8601(now), symbol, timeframe, ohlcvs))
        except Exception as e:
            raise Exception(e)


def process_worker(symbol, timeframe):
    asyncio.get_event_loop().run_until_complete(main(symbol, timeframe))


if __name__ == "__main__":
    exchange_class = getattr(ccxt, EXCHANGE_NAME)
    exchange = exchange_class({'enableRateLimit': True, 'verbose': False})
    exchange.load_markets()

    for symbol in exchange.symbols:
        if not exchange.market(symbol)['active']:
            continue

        for timeframe in exchange.timeframes.keys():
            p = multiprocessing.Process(target=process_worker, kwargs={'symbol': symbol,
                                                                       'timeframe': timeframe})
            p.start()

    while True:
        sleep(3600)
```
[test_api_limits_exceed.py.zip](https://github.com/ccxt/ccxt/files/5099508/test_api_limits_exceed.py.zip)

**Comment by frosty00** [comment]
It's probably because you are using multiprocessing (and running ccxt in a seperate process) which is not triggering an error in the parent process. https://docs.python.org/3/library/multiprocessing.html#sharing-state-between-processes

**Comment by aero-108** [comment]
Disagree, I don’t expect exception in parent process. Exception should be thrown inside child process, multiprocessing doesn’t make any difference, it’s just an example how to reach Binance API limit.

**Comment by kroitor** [comment]
@aero-108 Hi! 

First of all, mixing the multiprocessing with asyncio async/await concurrency is a bad idea. 

You will get all sorts of issues upon trying to run that code on the same machine with the same exchange.

First, you should really respect the rate limits. You're creating an exchange instance in your parent process and load the markets there.
Then for each symbol you create a new exchange instance and load the markets there as well. The problem is that those worker processes don't know anything about the rate limits used in other workers and in the parent process.
So, you are effectively resetting the rate-limiter in every worker process and since you start them all simultaneously, you eventually hit a rate limits, because each of your child worker processes does not respect the rate limits with the other workers in mind.
That leads to sending too many requests at once from all workers at once and Binance will not allow that.
If that happens you will get a RateLimitExceeded exception or a DDoSProtection exception.
And that exception is actually thrown here:

```
async def main(symbol, timeframe):
    exchange_class = getattr(ccxtpro, EXCHANGE_NAME)
    exchange = exchange_class({'enableRateLimit': True, 'verbose': False})


    await exchange.load_markets()  # ←-- RateLimitExceeded exception thrown HERE


    while True:
        try:
            ohlcvs = await exchange.watch_ohlcv(symbol, timeframe, None, 1000)
            now = exchange.milliseconds()
            logging.info(('EXCEPTION', exchange.iso8601(now), symbol, timeframe, ohlcvs))
        except Exception as e:
            raise Exception(e)
```

↑ upon your call to await exchange.load_markets() one of your worker processes will throw an exception. 
But you don't catch it anywhere. The exception simply interrupts your worker process. 
And you're not reading any process return values or stderr output from your workers in order to catch that exception.
Thus there is no wonder why you don't catch it in your workers.

Change it like so:

```
async def main(symbol, timeframe):
    exchange_class = getattr(ccxtpro, EXCHANGE_NAME)
    exchange = exchange_class({'enableRateLimit': True, 'verbose': False})
    while True:
        try:
            await exchange.load_markets()
            ohlcvs = await exchange.watch_ohlcv(symbol, timeframe, None, 1000)
            now = exchange.milliseconds()
            print(symbol, 'fetched successfully')
        except Exception as e:
            print(symbol, 'failed')
            print(e)
```

Instead of reinventing _a process pool_, i'd recommend to stick to the asyncio concurrency and simply launch your concurrent workers/watch-loops using asyncio's `gather` function.

Let us know if the above does not answer your question.

**Comment by Kinzowa** [comment]
Hi Igor,

I noticed that some exchanges (okex, bitfinex) return a Too many Request when requesting multiple streams in a loop, while some others don't complain (binance, ftx).

Was wondering if it's an appropriate workaround to insert a blocking `time.sleep(5)` before the `while True:` or if there is a more elegant solution. I would appreciate your thought on how to handle large number of streams per exchanges, for example to monitor the top 20 pairs per trading volume in spot, swap and future markets. 

This is my code for what I'm trying to achieve:


```
    async def loop(asyncio_loop, symbol, tp):

        time.sleep(5)

        client = getattr(ccxtpro, exchange)({
            'enableRateLimit': True,
            'asyncio_loop': asyncio_loop,
        })

        client.options['asyncio_loop'] = asyncio_loop
        client.options['defaultType'] = tp

        while True:
            try:
                orderbook = await client.watch_order_book(symbol)
                print(exchange, tp, symbol, orderbook['asks'][0], orderbook['bids'][0])
                await client.sleep(20000)

            except Exception as e:
                raise e

        await client.close()
```

And the `symbols` I request for `swap`, `spot` and `futures` (between 50 and 60 in total):

```
['UNI-USDT-SWAP', 'YFII-USDT-SWAP', 'YFI-USDT-SWAP', 'ETH-USD-SWAP', 'SUSHI-USDT-SWAP', 'LINK-USDT-SWAP', 'ETH-USDT-SWAP', 'LINK-USD-SWAP', 'BTC-USD-SWAP', 'CRV-USDT-SWAP', 'BCH-USD-SWAP', 'BTC-USDT-SWAP', 'UMA-USDT-SWAP', 'EOS-USD-SWAP', 'DOT-USDT-SWAP', 'UNI-USD-SWAP', 'XTZ-USDT-SWAP', 'JST-USDT-SWAP', 'SUN-USDT-SWAP', 'LTC-USD-SWAP']

['BTC/USDT', 'ETH/USDT', 'YFII/USDT', 'YFI/USDT', 'OKB/USDT', 'UNI/USDT', 'BCH/USDT', 'LINK/USDT', 'DOT/USDT', 'WGRT/USDT', 'BSV/USDT', 'PAY/USDT', 'EOS/USDT', 'LTC/USDT', 'TRX/USDT', 'XMR/USDT', 'UMA/USDT', 'ZEC/USDT', 'SUSHI/USDT', 'XTZ/USDT']

['ETH-USD-201225', 'BTC-USD-201225', 'LTC-USD-201225', 'BCH-USD-201225', 'ETH-USD-201016', 'BTC-USDT-201225', 'ETH-USD-210326', 'EOS-USD-201225', 'BSV-USD-201225', 'ETH-USDT-201225', 'LTC-USD-201016', 'LINK-USD-201225', 'ETC-USD-201225', 'XRP-USD-201225', 'LINK-USDT-201225', 'BTC-USDT-201016', 'ETH-USDT-210326', 'LTC-USD-210326', 'BTC-USDT-210326', 'ETC-USD-201016']
```

**Comment by kroitor** [comment]
@Kinzowa I think you're creating one exchange instance per each symbol, instead of reusing the same exchange instance, thus, violating this documented rule: https://github.com/ccxt/ccxt/wiki/Manual#notes-on-rate-limiter

Reuse the same exchange instance instead, as shown, for example, here:

- https://github.com/ccxt/ccxt/blob/master/examples/ccxt.pro/py/many-exchanges-many-streams.py#L24

Let me know if that does not help.

**Comment by kroitor** [comment]
@Kinzowa actually, sorry, this example is wrong, it does the same as your code (creating one exchange per symbol): https://github.com/ccxt/ccxt/blob/master/examples/ccxt.pro/py/many-exchanges-many-streams.py#L24

I'll post a proper example shortly.

**Comment by kroitor** [comment]
@Kinzowa check this example on how to reuse the exchange across multiple symbols:

- https://github.com/ccxt/ccxt/blob/master/examples/ccxt.pro/py/many-exchanges-many-streams.py (I've edited the source)

```Python
# -*- coding: utf-8 -*-

import ccxtpro
from asyncio import gather, get_event_loop


async def symbol_loop(exchange, symbol):
    print('Starting the', exchange.id, 'symbol loop with', symbol)
    while True:
        try:
            orderbook = await exchange.watch_order_book(symbol)
            now = exchange.milliseconds()
            print(exchange.iso8601(now), exchange.id, symbol, orderbook['asks'][0], orderbook['bids'][0])
        except Exception as e:
            print(str(e))
            # raise e  # uncomment to break all loops in case of an error in any one of them
            break  # you can break just this one loop if it fails

async def exchange_loop(asyncio_loop, exchange_id, symbols):
    print('Starting the', exchange_id, 'exchange loop with', symbols)
    exchange = getattr(ccxtpro, exchange_id)({
        'enableRateLimit': True,
        'asyncio_loop': asyncio_loop,
    })
    loops = [symbol_loop(exchange, symbol) for symbol in symbols]
    await gather(*loops)
    await exchange.close()


async def main(asyncio_loop):
    symbols = ['BTC/USDT', 'ETH/BTC']
    # symbols = []
    exchanges = {
        'okex': symbols + ['ETH/USDT'],
        'binance': symbols,
    }
    loops = [exchange_loop(asyncio_loop, exchange_id, symbols) for exchange_id, symbols in exchanges.items()]
    await asyncio.gather(*loops)


if __name__ == '__main__':
    asyncio_loop = get_event_loop()
    asyncio_loop.run_until_complete(main(asyncio_loop))
```

**Comment by Kinzowa** [comment]
Much appreciated, thanks!
