### ISSUE TITLE
timeouts in javascript leave node process hanging

### ISSUE THREAD

**Issue by jla415** [ccxt/ccxt#749]
Hello

Currently the timeout timers are not cleared from ccxt requests leaving the node process hanging until the timer resolves in functions.js

Example code:

```javascript

const ccxt = require('./ccxt')

const bittrex = new ccxt.bittrex({timeout: 10000})

let start = Date.now();

bittrex.load_markets().then(() => console.log('finished in %d ms', Date.now() - start));
```

Result:

```bash
$ time node timeout_example.js 
finished in 879 ms

real    0m10.735s
user    0m0.214s
sys     0m0.040s
```

Expected result would be for the node process to exit in 879ms, not 10.735s

I would suggest saving the id from https://github.com/ccxt/ccxt/blob/f2bc03ec9c293a5f123989c7c247a05d5e58f02d/js/base/functions.js#L17 and clearing the timeout when the fetch request promise is resolved.

**Comment by kroitor** [comment]
Thanks for reporting this! Will fix very soon!

**Comment by jla415** [comment]
Thank you for the quick fix

**Comment by mkutny** [comment]
Oh, my God!

I was always curious what causes node to wait for a while before exiting but never had a chance to dig into the problem.

Awesome!!!
