### ISSUE TITLE
[Upbit] Is there any method like wapiGetAssetDetail() on binance

### ISSUE THREAD

**Issue by gloomydumber** [ccxt/ccxt#7501]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows
- Programming Language version: Python 3.6
- CCXT version: 1.33.4

```
import ccxt
exchange = ccxt.binance({
    'apiKey': 'mykey',
    'secret': 'mysecret',
    'fetchCurrencies': True,
    'fetchDeposits': True,
    'fetchWithdrawals': True
})
data = exchange.wapiGetAssetDetail()
print(data)
```

```
{
    "CTR": {
        "depositStatus": false,
        "depositTip": "Delisted, Deposit Suspended",
        "minWithdrawAmount": 70.0,
        "withdrawFee": 35.0,
        "withdrawStatus": true
    },
    "MATIC": {
        "depositStatus": true,
        "minWithdrawAmount": 190.0,
        "withdrawFee": 95.0,
        "withdrawStatus": true
    },
    "MXN": {
        "depositStatus": true,
        "minWithdrawAmount": 0.0,
        "withdrawFee": 0.0,
        "withdrawStatus": false
    },
    "STPT": {
        "depositStatus": true,
        "minWithdrawAmount": 194.0,
        "withdrawFee": 97.0,
        "withdrawStatus": true
    },
    "UGX": {
        "depositStatus": true,
        "minWithdrawAmount": 0.0,
        "withdrawFee": 0.0,
#....
```
as u can see,
On Binance API, can see Exchange's deposit/withdraw status with _wapiGetAssetDetail()_ (although it requires apiKeys)
(i find it out through #5104 )

i just want to ask, is there any method like this  _wapiGetAssetDetail()_ on Upbit ?

thx, kroiter
i always appreciate for your help

**Comment by tangible-idea** [comment]
@gloomydumber 
https://docs.upbit.com/reference#%EC%9E%85%EC%B6%9C%EA%B8%88-%ED%98%84%ED%99%A9
What about this?

The endpoint is this: 
https://api.upbit.com/v1/status/wallet

**Comment by gloomydumber** [comment]
@tangible-idea Private이라 Public으로 된 게 혹시 있나 물어봤는데 Public은 없어서 말씀해주신 endpoint로 처리했었네요 ㅎㅎ.. 답변 감사합니다
