### ISSUE TITLE
Does CCXT support Paper trading or dummy wallets having Test coins ?

### ISSUE THREAD

**Issue by AbdulHadiSaeed** [ccxt/ccxt#7506]
I have created dummy wallet and add test/dummy coins (1Btc) on Bitmex, Bittrex  exchange, Now I am trying to do trading through ccxt for testing purpose but Invalid API and zero balance is showing while fetching the balance. So Does ccxt support dummy coins/ Paper trading or not?

Thank You in Advance.

**Comment by kroitor** [comment]
> So Does ccxt support dummy coins/ Paper trading or not?

CCXT supports whatever test currencies are available from the exchange itself, as well as sandboxes/testnets.

> Now I am trying to do trading through ccxt for testing purpose but Invalid API and zero balance is showing while fetching the balance.

In order to be able to help you we need you to follow these guidelines precisely:

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help ← we need all of this information from you

Please, paste your code to reproduce it including the exchange instantiation but without your keys of course. Also, please, make sure to post your complete verbose request+response for the failing call as explained above.

**Comment by AbdulHadiSaeed** [comment]
Thanks for your response.

Can we do fake trading, For example: buy btc using dummy coin and then sell that coin to another exchange or within exchange? 

Can we do Transaction using test currencies?

**Comment by Usmankhokhar123** [comment]
Can we do transactions by using python, like buy and sell using test coins provided by demo accounts

**Comment by AsadullahSoomro** [comment]
Does CCXT library support paper trading?

**Comment by kroitor** [comment]
I would highly suggest to read the CCXT Manual from top to bottom – it will really save your time, most of these questions are answered by the structure of this lib:

- https://github.com/ccxt/ccxt/wiki/Manual

@Usmankhokhar123 you can do everything that is supported by the API of this or that exchange. Very few exchanges have it, afaik.

> Can we do Transaction using test currencies?

With some exchanges you may be able to do that, again, depends on the exchange in question.

> Does CCXT library support paper trading?

Nope, CCXT is not a bot, it supports things that are supported by the exchanges. If the exchange allows this or that mode – you will be able to use it with CCXT. All things related to your strategy and trading mode – is up to you. CCXT is a backbone for your paper trading. You can find some examples here on how to do this or that here:

- https://github.com/ccxt/ccxt/tree/master/examples

Let us know if the above does not answer your questions. Feel free to reopen this issue or just ask further questions if any.

**Comment by Usmankhokhar123** [comment]
@kroitor issue is that, exchanges like bitmex and bybit supports demo accounts and these exchanges also provide us test coins, but when we run the script in python like function of fetch balance, it shows us zero balance while in actual demo account it shows around 1 BTC, and also sometimes it gives exception of invalid API, kindly suggest me some solution for this.

**Comment by AsadullahSoomro** [comment]
Can someone tell us regarding following problems:
Currently we're facing issue related to exchanges like bitmex and bybit supports demo accounts and these exchanges also provide us test coins, but when we run the script in python like function of fetch balance, it shows us zero balance while in actual demo account it shows around 1 BTC, and also sometimes it gives exception of invalid API, kindly suggest me some solution for this.

So we need to know that Does ccxt support dummy coins/ Paper trading or not?
Thank you!

**Comment by kroitor** [comment]
@AsadullahSoomro can you please paste your code to reproduce it and your verbose request+response precisely as described here: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by AsadullahSoomro** [comment]
import ccxt

x = ccxt.bybit({
'apiKey': '',
'secret': '',
'enableRateLimit': True,
})

account_balance = x.fetch_balance()
print(account_balance)
print("\n")


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
08/29/20,
11:13:04 PM

**Comment by AsadullahSoomro** [comment]
> @AsadullahSoomro can you please paste your code to reproduce it and your verbose request+response precisely as described here: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help ?


import ccxt

x = ccxt.bybit({
'apiKey': '',
'secret': '',
'enableRateLimit': True,
})

account_balance = x.fetch_balance()
print(account_balance)
print("\n")

**Comment by kroitor** [comment]
@AsadullahSoomro you have to switch to the sandbox/testnet and use the testnet credentials:

```Python
import ccxt
from pprint import pprint

exchange = ccxt.bybit({
    'apiKey': 'YOUR_TESTNET_API_KEY',
    'secret': 'YOUR_TESTNET_SECRET',
    'enableRateLimit': True,
})

exchange.set_sandbox_mode(True)  # ←----------- ADD THIS

exchange.load_markets()

# exchange.verbose = True  # uncomment for debug output

pprint(exchange.fetch_balance())
```

↑ Let us know if that does not help.

**Comment by Princeton007** [comment]
Not sure if this is related to this topic or if it's an exchange issue (I opened a ticket with Bitfinex already):
When trying to place a margin market order at the papertrading account, I receive the following exception:

ccxt.base.errors.ExchangeError: bitfinex {"message":"Paper Trading is only allowed across Paper Trading users."}

Trying to place the same order in Bitfinex GUI returns in another error: Insufficient balance (u1)

Although there is enough tradable balance on the Margin account. 

Any ideas, suggestions what could be the issue?
