### ISSUE TITLE
Do the recent metainfo update PRs suggest incoming deprecation?

### ISSUE THREAD

**Issue by binares** [ccxt/ccxt#7507]
I noticed that @An-Net has updated many `has` dicts of different exchanges, sometimes e.g. adding `'fetchTicker': true` despite it already being defaulted in the Exchange base class. Does this mean there is a plan to default all to `False`? (I'm asking because in that case I'll have to make some changes in my own repos).

**Comment by frosty00** [comment]
Not necessarily, I would just say it is more complete to have all the `has` properties in the derived (subclass) exchange files.

**Comment by binares** [comment]
Ah, that explains it, thanks.
