### ISSUE TITLE
kraken.purgeCachedOrders throwing

### ISSUE THREAD

**Issue by dmnode** [ccxt/ccxt#7510]
Hi, after updating to most recent version of ccxt today, purgeCachedOrders throws an exception for kraken exchange

- OS: Ubuntu
- Programming Language version: Node v12.18.3
- CCXT version: 1.33.52

```
let before = kraken.milliseconds() - 24*60*60*1000;
kraken.purgeCachedOrders(before);
```

```
TypeError: Cannot convert undefined or null to object at Function.values () at kraken.purgeCachedOrders (node_modules/ccxt/js/base/Exchange.js:803:14)
```

**Comment by kroitor** [comment]
Hi! Thx for reporting, will fix shortly. A quick question: why would you want to call purgeCachedOrders on kraken? (It does not use the `.orders` cache)

**Comment by dmnode** [comment]
Thanks for the comment! Actually, I do not need orders cache at all, for any exchange. Just, from the manual, https://github.com/ccxt/ccxt/wiki/Manual#orders-cache, I somehow understood it is always on by default and there is no way to deactivate it, so I need to run purge. Is there a general way to deactivate orders cache, so I need to not set it specifically to each exchange?

**Comment by kroitor** [comment]
> I somehow understood it is always on by default and there is no way to deactivate it, so I need to run purge. 

Yes, at this time you can't deactivate it, so you need to call it from time to time, depending on the purpose of the app, I was just asking.

> Is there a general way to deactivate orders cache, so I need to not set it specifically to each exchange?

That call should not fail, after the fix. Let us know if you still have issues with it after upgrading to version 1.33.53, it will arrive in 15 minutes.

**Comment by dmnode** [comment]
Great, thanks, works fine now. An option to check whether the exchange actually uses orders cache, so one could run purge only where needed, would be quite useful. regards

**Comment by kroitor** [comment]
@dmnode we think of removing the .orders cache and the emulation from CCXT entirely, and probably make a separate addon package with the emulation functionality, thanks for your involvement, we appreciate your feedback!
