### ISSUE TITLE
The capacity of C: disk gets to decrease rapidly as I execute "watch_ticker" method

### ISSUE THREAD

**Issue by CHEYULIU** [ccxt/ccxt#7511]
- OS: windows 10
- Programming Language version: python 3.7
- CCXTPRO version: I have no idea where to see the version of my installed ccxtpro

The problem is as I mentioned in the title, after I ran the following codes, the capacity of C: disk rapidly increased. However, the size of the csv file, which saves the retrieved data, did not contain the corresponding amount of occupied capacity in my C: disk. I cannot find out the reasons and where does the extra files or buffer (I'm not sure if it is called "buffer") exist. 

The following codes run well, so there is no error.
```
async def main_pro_huobi(loop, symbol='BTC/USDT'):
    exchange = ccxtpro.huobipro({
        'enableRateLimit': True,
        'asyncio_loop': loop,
        'options': {
            'defaultType': 'future',
        }
    })
    x1 = 0
    while True:
        try:
            ticker_btc = await exchange.watch_ticker(symbol=symbol)
            index_time = x1
            timestamp_val = ticker_btc['timestamp']
            open_val = ticker_btc['open']
            high_val = ticker_btc['high']
            low_val = ticker_btc['low']
            close_val = ticker_btc['last']
            vol = ticker_btc['baseVolume']
            sym = ticker_btc['symbol']

            with open('C:/'') as csv_file:
                csv_writer = csv.DictWriter(csv_file, fieldnames=field_names)
                info = {
                    'index': index_time,
                    'timestamp_val': timestamp_val,
                    'open_value': open_val,
                    'high_value': high_val,
                    'low_value': low_val,
                    'close_value': close_val,
                    'volume': vol
                }
                csv_writer.writerow(info)
                print(index_time, timestamp_val, open_val, high_val, low_val, close_val, vol)
            x1 += 1
        except Exception as e:
            print(e)
            pass

if __name__ == "__main__":
    ticker_list = ['BTC/USDT', 'ETH/USDT', 'LTC/USDT', 'XRP/USDT', 'BCH/USDT']
    exchange_list = ['binance', 'huobi']
    field_names = ['index', 'timestamp_val', 'open_value', 'high_value', 'low_value', 'close_value', 'volume']
    for k in exchange_list:
        for j in ticker_list:
            with open('C:/' + k + j.split('/')[0] + '.csv', 'w', newline='') as csv_file:
                csv_writer = csv.DictWriter(csv_file, fieldnames=field_names)
                csv_writer.writeheader()

    loop = asyncio.new_event_loop()

    for i in ticker_list:
        loop.create_task(main_pro_binance(loop, i))
        loop.create_task(main_pro_huobi(loop, i))
    loop.run_forever()
```

**Comment by kroitor** [comment]
@CHEYULIU 

This line does not look right to me:

```
            with open('C:/'') as csv_file:
```

↑ Are you sure that you want to open `C:/'` and write to it?

**Comment by CHEYULIU** [comment]
> 
> 
> @CHEYULIU
> 
> This line does not look right to me:
> 
> ```
>             with open('C:/'') as csv_file:
> ```
> 
> ↑ Are you sure that you want to open `C:/'` and write to it?

I abbreviated the name of the path. In fact, I open a file on desktop and write to it. 
By the way, I have used another third party software to scan all of files on the C disk and deleted all of large files, but the problem still exist. Plus, I also stopped executing the script for several days. Have you ever met with the similar problem before? Any tips will help. Thanks!

**Comment by Matoran** [comment]
You can use Process Explorer https://docs.microsoft.com/fr-fr/sysinternals/downloads/process-explorer 
Download it, launch procexp64.exe right click in columns => select columns... => Process I/O => check Write Bytes

You then will see which process is writing to your HDD.

If anyone would have the same problem on linux just install iotop and use `iotop -a` to discover which process is guilty.

**Comment by CHEYULIU** [comment]
> 
> 
> You can use Process Explorer https://docs.microsoft.com/fr-fr/sysinternals/downloads/process-explorer
> Download it, launch procexp64.exe right click in columns => select columns... => Process I/O => check Write Bytes
> 
> You then will see which process is writing to your HDD.
> 
> If anyone would have the same problem on linux just install iotop and use `iotop -a` to discover which process is guilty.

Thanks! I will try it. 👍

**Comment by kroitor** [comment]
@CHEYULIU we will post an example of how to store ticker values to csv with respect to rate-limits.

**Comment by CHEYULIU** [comment]
> 
> 
> @CHEYULIU we will post an example of how to store ticker values to csv with respect to rate-limits.

That would be great! Thanks!

By the way, can you tell me what is the problem with my code? How to improve it? Since my strategy involves trading several cryptos at the same time, the way I came up with is using the Websocket method to get data asynchronously from binance exchange and read the data from local file synchronously. Do you think this logic making sense? I am also curious how would you code if you want to retrieve several tickers value asynchronously.

**Comment by kroitor** [comment]
@CHEYULIU 

> By the way, can you tell me what is the problem with my code? How to improve it?

At this time it violates the rate limiting rules apart from a few other issues:

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/wiki/Manual#notes-on-rate-limiter

We will post a proper example script asap.

**Comment by CHEYULIU** [comment]
> 
> 
> @CHEYULIU
> 
> > By the way, can you tell me what is the problem with my code? How to improve it?
> 
> At this time it violates the rate limiting rules apart from a few other issues:
> 
>     * https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
> 
>     * https://github.com/ccxt/ccxt/wiki/Manual#notes-on-rate-limiter
> 
> 
> We will post a proper example script asap.

Got it! I originally thought there would be no rate limiting issues as I used ccxtpro method to retrieve data, and my codes worked well for me actually. The only problem is that I mentioned on my post. Anyway, I will be patient waiting for example script. Thanks!

Oh by the way, in the first place I used ccxt method to try to get several tickers values and indeed met with the rate limiting issues you mentioned, so that is why I turned to use ccxtpro method.

**Comment by Matoran** [comment]
> > You can use Process Explorer https://docs.microsoft.com/fr-fr/sysinternals/downloads/process-explorer
> > Download it, launch procexp64.exe right click in columns => select columns... => Process I/O => check Write Bytes
> > You then will see which process is writing to your HDD.
> > If anyone would have the same problem on linux just install iotop and use `iotop -a` to discover which process is guilty.
> 
> Did you mean like this?
> 
> <img alt="io" width="557" src="https://user-images.githubusercontent.com/31812232/91630006-8a55cd80-ea00-11ea-80ae-fa76b432af10.png">
> 
> If I was correct, can I assume this is the reason why my C disk has been written by the firefox.exe?
> Can I find out where is the file that the thread wrote data in? Thanks for your response. 👍

No, when you open the process explorer you should have this, except the two last columns
![image](https://user-images.githubusercontent.com/4539516/91665283-7fd12c00-eb05-11ea-9161-d190c881cf07.png)
right click in any column name (for example Company Name) => select columns... => Process I/O => check Write Bytes

![image](https://user-images.githubusercontent.com/4539516/91665332-d76f9780-eb05-11ea-9405-b623d20c2951.png)
You then can incriminate the process after a while, for me chrome is the most writing program since I opened my session.

**Comment by CHEYULIU** [comment]
> 
> 
> > > You can use Process Explorer https://docs.microsoft.com/fr-fr/sysinternals/downloads/process-explorer
> > > Download it, launch procexp64.exe right click in columns => select columns... => Process I/O => check Write Bytes
> > > You then will see which process is writing to your HDD.
> > > If anyone would have the same problem on linux just install iotop and use `iotop -a` to discover which process is guilty.
> > 
> > 
> > Did you mean like this?
> > <img alt="io" width="557" src="https://user-images.githubusercontent.com/31812232/91630006-8a55cd80-ea00-11ea-80ae-fa76b432af10.png">
> > If I was correct, can I assume this is the reason why my C disk has been written by the firefox.exe?
> > Can I find out where is the file that the thread wrote data in? Thanks for your response. 👍
> 
> No, when you open the process explorer you should have this, except the two last columns
> ![image](https://user-images.githubusercontent.com/4539516/91665283-7fd12c00-eb05-11ea-9161-d190c881cf07.png)
> right click in any column name (for example Company Name) => select columns... => Process I/O => check Write Bytes
> 
> ![image](https://user-images.githubusercontent.com/4539516/91665332-d76f9780-eb05-11ea-9405-b623d20c2951.png)
> You then can incriminate the process after a while, for me chrome is the most writing program since I opened my session.
> 
> Launch it as administrator, otherwise, you will have some processes without any information.

Got it! May I ask what is the definition of the column "I/O Write Bytes" ? Take your example, what does 583.9 MB mean? Does that mean chrome is writing this amount of data into disk per hour? And how to set it as admin?

**Comment by Matoran** [comment]
My bad you should use the column from "Process Disk" => Writes Bytes, the value represent the total amount written to disk since process explorer is launched. Like any other program on Windows you can left click on it and run as admin. I/O Write Bytes is network usage (and some other I/O ops but not disk)

**Comment by kroitor** [comment]
@CHEYULIU let us know if this example does not resolve your problem:

- https://github.com/ccxt/ccxt/blob/master/examples/ccxt.pro/py/watch-ticker-to-csv.py

```Python
# -*- coding: utf-8 -*-

from asyncio import gather, get_event_loop
import ccxtpro
from pprint import pprint


async def watch_ticker_continuously(exchange, symbol):
    filename = exchange.id + '-' + symbol.replace('/', '-') + '.csv'
    print('Watching', exchange.id, symbol, filename)
    keys = ['index', 'exchange', 'symbol', 'timestamp', 'open', 'high', 'low', 'close', 'baseVolume']
    with open(filename, 'w') as file:
        file.write(','.join(keys) + "\n")
    index = 0
    while True:
        try:
            ticker = await exchange.watch_ticker(symbol)
            values = [str(index), exchange.id] + [str(ticker[key]) for key in keys[2:]]
            print(*values)
            with open(filename, 'a') as file:
                file.write(','.join(values) + "\n")
            index += 1
        except Exception as e:
            print(e)


async def watch_tickers_continuously(loop, exchange_id, overrides, symbols):
    defaults = {
        'enableRateLimit': True, # required https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
        'asyncio_loop': loop,
    }
    exchange_class = getattr(ccxtpro, exchange_id)
    exchange = exchange_class(ccxtpro.Exchange.extend(defaults, overrides))
    coroutines = [watch_ticker_continuously(exchange, symbol) for symbol in symbols]
    await gather(*coroutines)
    await exchange.close()


async def main(loop):
    exchanges = {
        'binance': {'options': {'defaultType': 'future'}},
        'huobipro': {}
    }
    symbols = ['BTC/USDT', 'ETH/USDT', 'LTC/USDT', 'XRP/USDT', 'BCH/USDT']
    coroutines = [watch_tickers_continuously(loop, exchange_id, exchanges[exchange_id], symbols) for exchange_id in exchanges.keys()]
    return await gather(*coroutines)

if __name__ == "__main__":
    loop = get_event_loop()
    loop.run_until_complete(main(loop))

```
