### ISSUE TITLE
[bitfinex] price formatting

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#7512]
const exchangeId = 'bitfinex2';
        const exchange = new ccxt[exchangeId]();
        await exchange.loadMarkets();

        console.log(exchange.priceToPrecision('TRX/ETH', 0.000061255));

> 0.000061255

When I place a limit order at this price (in `TRX/ETH`), the order that gets created on the exchange looks like:

            {
                "id": "49701388294",
                "timestamp": 1598324705144,
                "datetime": "2020-08-25T03:05:05.144Z",
                "side": "sell",
                "symbol": "TRX/ETH",
                "amount": 331.13538315,
                "price": 0.00006125, <-- this is not the price specified
                "filled": 0,
                "remaining": 331.13538315,
                "type": "limit",
                "status": "open",
                "info": [49701388294, null, 1598324705144, "tTRXETH", 1598324705144, 1598324705144, -331.13538315, -331.13538315, "EXCHANGE LIMIT", null, null, null, 0, "ACTIVE", null, null, 0.00006125, 0, 0, 0, null, null, null, 0, 0, null, null, null, "API>BFX", null, null, null],
                "clientOrderId": "1598324705144",
                "cost": 0,
                "average": 0
            }

**Comment by kroitor** [comment]
@npomfret as you can see from the `info` – it's the price returned from Bitfinex itself. Looks like the exchange will truncate certain values to 5 significant digits + 8 decimal digits max: https://docs.bitfinex.com/docs/introduction#:~:text=The%20precision%20level%20of%20all,be%20cut%20by%20the%20API.
Will fix the `priceToPrecision` for Bitfinex shortly.

**Comment by npomfret** [comment]
@kroitor thank you
