### ISSUE TITLE
[coinmate] open order amount wrong

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#7514]
https://coinmate.docs.apiary.io/#reference/order/get-open-orders

It looks like the rest api for open orders returns the amount remaining, not the original amount.  I got this response for an order that was placed with an amount of `1.43408088` (after it pas partially filled with a trade of size `0.00100148`):

1.43408088 - 0.00100148 = 1.4330794

         {
            "id": "891692920",
            "cost": 0,
            "info": {"id": 891692920, "type": "SELL", "price": 0.02418, "amount": 1.4330794, "hidden": false, "trailing": false, "stopPrice": null, "timestamp": 1598374679192, "currencyPair": "BCH_BTC", "clientOrderId": null, "orderTradeType": "LIMIT", "originalStopPrice": null, "marketPriceAtLastUpdate": null, "trailingUpdatedTimestamp": null, "marketPriceAtOrderCreation": null},
            "side": "sell",
            "type": "limit",
            "price": 0.02418,
            "amount": 1.4330794,
            "filled": 0,
            "status": "open",
            "symbol": "BCH/BTC",
            "datetime": "2020-08-25T16:57:59.192Z",
            "remaining": 1.4330794,
            "timestamp": 1598374679192
        }

**Comment by kroitor** [comment]
@npomfret do you suggest to set the `amount` and `filled` to `undefined` in this case?

**Comment by npomfret** [comment]
Exactly, yes.

**Comment by npomfret** [comment]
I just updated but the fix doesn't seem to have worked as expected:

        const exchangeId = 'coinmate';
        const exchange = new ccxt[exchangeId]();
        await exchange.loadMarkets();

        const order = await exchange.parseOrder({
            "id": 891692920,
            "type": "SELL",
            "price": 0.02418,
            "amount": 1.4330794,
            "hidden": false,
            "trailing": false,
            "stopPrice": null,
            "timestamp": 1598374679192,
            "currencyPair": "BCH_BTC",
            "clientOrderId": null,
            "orderTradeType": "LIMIT",
            "originalStopPrice": null,
            "marketPriceAtLastUpdate": null,
            "trailingUpdatedTimestamp": null,
            "marketPriceAtOrderCreation": null
        },);
        console.log(order);

Produces:

```
{ id: '891692920',
  clientOrderId: undefined,
  timestamp: 1598374679192,
  datetime: '2020-08-25T16:57:59.192Z',
  lastTradeTimestamp: undefined,
  symbol: 'BCH/BTC',
  type: 'limit',
  side: 'sell',
  price: 0.02418,
  amount: 1.4330794,
  cost: undefined,
  average: undefined,
  filled: undefined,
  remaining: undefined,
  status: undefined,
  trades: undefined,
  info:...
  fee: undefined }
```

**Comment by kroitor** [comment]
@npomfret pardon, my bad, a small typo, fixed it, should be ok in the next build.

**Comment by npomfret** [comment]
thanks, looks good
