### ISSUE TITLE
ACX post multi orders incorrect signature

### ISSUE THREAD

**Issue by scoshil** [ccxt/ccxt#752]
I'm trying to test sending multiple orders with ACX using their orders/multi endpoint, but having issues with the signature.

All the other public and private endpoints/functions I've tested work as per the documentation, just this one that's giving me an error.

I saw someone else post a similar-looking issue re Bittrex signatures but not sure if this is the same issue.

Code: 
```
acx = ccxt.acx({'apiKey':ACXKey1,'secret':ACXSecret1})
acx.load_markets()
acx.verbose = True
new_order_multi = acx.private_post_orders_multi({'market':'btcaud','orders':{'side':'buy','volume':'0.01','price':'10000'}})
print(new_order_multi)

```

Error:

```
ccxt.base.errors.AuthenticationError: acx POST https://acx.io/api/api/v2/orders/multi.json 401 Unauthorized  {"error":{"code":2005,"message":"Signature 3e1b5463600a1f8f5169ec3db741b2d7a6673b338d5ef2614d08f1668817f30c is incorrect."}}


```

Am I somehow using incorrect syntax or is there an issue here?

Thanks!

EDIT:

Playing around with another method:

Typo (extra 'd'):
```
new_order = acx.private_post_orders({'market':'btcaud','sidde':'buy','volume':0.01,'price':1000})
```
yields:
```
acx POST https://acx.io/api/api/v2/orders.json 400 Bad Request  {"error":{"code":1001,"message":"side is missing, side does not have a valid value"}}
```
while a different typo: (extra "/")
```
new_order = acx.private_post_orders({'market':'btcaud','si/de':'buy','volume':0.01,'price':1000})
```
yields the same authentication error:
```
acx POST https://acx.io/api/api/v2/orders.json 401 Unauthorized  {"error":{"code":2005,"message":"Signature 92bbc054536f93c0df829766739e12d58917553508e31cd9b901c75a6062a507 is incorrect."}}
```

Which leads me to believe it's some sort of syntax error....but I'm at a loss as to what exactly I've done wrong

**Comment by kroitor** [comment]
Hi! Thanks for reporting, I will look into this asap and will get back to you with my findings.

**Comment by kroitor** [comment]
This bug was due to their very weird flavor of multidimensional array urlencoding. Anyway, this should work normally as of version 1.10.333. We will be happy if you report back whether you have any difficulties with it. Thanks!
