### ISSUE TITLE
Does CCXT support Paper trading or dummy wallets having Test coins?

### ISSUE THREAD

**Issue by AsadullahSoomro** [ccxt/ccxt#7520]
Can anyOne tell us regarding the following problems:
Currently, we're facing issue related to exchanges like BitMEX and bybit supports demo accounts and these exchanges also provide us test coins, but when we run the script in python like function of fetch balance, it shows us zero balance while in actual demo account it shows around 1 BTC, and also sometimes it gives exception of invalid API, kindly suggest me some solution for this.

So we need to know that Does ccxt support dummy coins/ Paper trading or not?

Thank you in advance!

**Comment by kroitor** [comment]
Hi! Plz do not duplicate the issues, we will provide the answers in your initial issue here: https://github.com/ccxt/ccxt/issues/7506#issuecomment-680932129
