### ISSUE TITLE
Did poloniex disable access to api keys from US?

### ISSUE THREAD

**Issue by gerardo15** [ccxt/ccxt#7523]
- OS: Ubuntu
- Programming Language version: NodeJs
- CCXT version: 1.33.57

Did poloniex disable access to api keys from US? if i use a VPN and test api connection to any other country fetchbalance would work!

If Ip is from the US i get the following error:

{ ExchangeError: poloniex {"error":"Our systems have detected that you may reside in a location we cannot provide service to. Please log into your account to resolve this issue."}

**Comment by kroitor** [comment]
https://www.google.com/search?q=poloniex+service+us+customers&oq=poloniex+service+us+customers

<img width="867" alt="Screen Shot 2020-08-28 at 16 20 25" src="https://user-images.githubusercontent.com/1294454/91565137-6932a580-e94a-11ea-8162-44d7ad35f95b.png">

Let us know if the above does not answer your question.
