### ISSUE TITLE
[HOW-TO] Get all trades from exchange if you only know base currencies

### ISSUE THREAD

**Issue by c0dehunter** [ccxt/ccxt#7524]
- OS: Linux
- Programming Language version: PHP 7.3
- CCXT version: 1.33.50

```
$id = "\\ccxt\\binance";
$exchange = new $id();
$exchange->apiKey = $key;
$exchange->secret= $secret;
$exchange->enableRateLimit = true;

for($balance : $exchange->fetchBalance()) {
	
	// get trades user has made with this coin, e.g. "BTC/*"
	
	$symbol = "BTC/USDT"; // <----- HERE IS THE PROBLEM: I only know base pair (BTC)
	$since = $exchange->milliseconds() - (1000*60*60*24);
	$trades = $exchange->fetchMyTrades ($symbol, $since, 10);
}
```

How can you fetch all trades the user has made for the coins he currently holds? I know which coins the user presently has (`fetchBalance()`), but I don't know the trade pairs. I tried with e.g. "BTC/*", but this doesn't work.

**Comment by kroitor** [comment]
Let us know if this example does not answer your question: https://github.com/ccxt/ccxt/blob/master/examples/php/binance-fetch-all-trades-for-all-traded-symbols.php

```PHP
<?php

$root = dirname (dirname (dirname (__FILE__)));

include $root . '/ccxt.php';

date_default_timezone_set ('UTC');

$id = "\\ccxt\\binance";
$exchange = new $id(array(
    'apiKey' => 'YOUR_API_KEY',
    'secret' => 'YOUR_SECRET',
    'enableRateLimit' => true,
));

$exchange->load_markets();
$balance = $exchange->fetch_balance();

$total = $balance['total'];

$all_matching_symbols = array();

foreach ($total as $currency_code => $value) {

    echo "-------------------------------------------------------------------\n";
    echo "Currency code: ", $currency_code, " value: ", $value, "\n";

    if ($value > 0) {

        // get all related markets with
        //   either base currency === currency code from the balance structure
        //      or quote currency === currency code from the balance structure

        $matching_markets = array_filter(array_values($exchange->markets), function ($market) use ($currency_code) {
            return ($market['base'] === $currency_code) || ($market['quote'] === $currency_code);
        });

        $matching_symbols = $exchange->pluck ($matching_markets, 'symbol');

        echo "Matching symbols:\n";
        print_r($matching_symbols);

        $all_matching_symbols = array_merge ($all_matching_symbols, $matching_symbols);
    }
}

echo "========================================================================\n";
print_r($exchange->unique ($all_matching_symbols));

$all_trades_for_all_symbols = array();

// ----------------------------------------------------------------------------

function fetch_all_my_trades($exchange, $symbol) {

    $from_id = '0';
    $params = array('fromId' => $from_id);
    $previous_from_id = $from_id;

    $all_trades = array();

    while (true) {

        echo "------------------------------------------------------------------\n";
        echo "Fetching with params:\n";
        print_r($params);
        $trades = $exchange->fetch_my_trades($symbol, null, null, $params);
        echo "Fetched ", count($trades), ' ', $symbol, " trades\n";
        if (count($trades)) {
            $last_trade = $trades[count($trades) - 1];
            if ($last_trade['id'] == $previous_from_id) {
                break;
            } else {
                $params['fromId'] = $last_trade['id'];
                $previous_from_id = $last_trade['id'];
                $all_trades = array_merge ($all_trades, $trades);
            }
        } else {
            break;
        }
    }

    echo "Fetched ", count($all_trades), ' ', $symbol, " trades\n";
    for ($i = 0; $i < count($all_trades); $i++) {
        $trade = $all_trades[$i];
        echo $i, ' ', $trade['symbol'], ' ', $trade['id'], ' ', $trade['datetime'], ' ', $trade['amount'], "\n";
    }

    return $all_trades;
}

// ----------------------------------------------------------------------------

foreach ($all_matching_symbols as $symbol) {

    echo "=================================================================\n";
    echo "Fetching all ", $symbol, " trades\n";

    // fetch all trades for the $symbol, with pagination
    $trades = fetch_all_my_trades($exchange, $symbol);

    echo count($trades), ' ' , $symbol, " trades\n";

    $all_trades_for_all_symbols = array_merge ($all_trades_for_all_symbols, $trades);

}

// do whatever you want with $all_trades_for_all_symbols

?>
```

**Comment by c0dehunter** [comment]
While this technically does answer the question, it's hard to use it in a real use case scenario due to the number of API calls required.

I am writing a portfolio-like program, which provides a snapshot of the user's account balance and last trades (e.g. last 20 trades). This will be used by hundreds of users, so it should be quick to refresh (e.g. 1 API call for balances, which is already true, and 1 API call for last trades). 

Is there any way to achieve this with CCXT? Maybe, based on [Query all OCO](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#query-all-oco-user_data) Binance API endpoint?

**Comment by kroitor** [comment]
> While this technically does answer the question, it's hard to use it in my use case due to the number of API calls required.

This was your initial request, **all trades**, specifically:

> How can you fetch all trades the user has made for the coins he currently holds?

So, if you want to fetch all historical trades for a user – there's no other way to do that via Binance's REST API except with multiple calls per user. It's not a limitation of CCXT, it is a limitation of the exchanges' APIs, as explained here: https://github.com/ccxt/ccxt/wiki/Manual#pagination

> I am writing a portfolio-like program, which provides a simplified snapshot of the user's account balance and last (e.g. 20) trades. 

If you only need the most recent trades, then the number of calls can be lowered down to 1 call to `fetchMyTrades` per user. Also, some exchanges will require a symbol for the `fetchMyTrades` call. In that case you can fetch the history with 1 call to `fetchMyTrades` per user per symbol. All of that is not a limitation of CCXT, it's a limitation of the underlying exchanges' APIs as you can see from their API docs.

> This will be used by hundreds of users, so it should be quick to refresh (e.g. 1 API call for balances, which is already true, and 1 API call for last trades).

If your application is going to be used by hundreds of users and you want to collect data on their behalf in a centralized fashion, then you should be aware that you should not attempt to do that without taking rate limits and other things into consideration. 

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit

Doing all of your system's work on a single intermediary server serving hundreds of users and accessing private APIs on behalf of users from the same physical server+IP – is a bad idea.

You can:

- either architect your backend (server-side) and factor-in scalability from the very start (run it in a cloud or distribute the loads and requests over a network of servers)
- preload the data for your registered users into your system in the background with respect to rate limits
- delegate this functionality to the frontend of your app (client-side)
- ...

Let me know if that does not answer your question.
