### ISSUE TITLE
cannot add seats for CCXT pro subscription

### ISSUE THREAD

**Issue by icytrader** [ccxt/ccxt#7526]
Hi,

There seems no place to actually add a seat. https://ccxt.pro/seats#

I tried to Search GitHub by username, but there is no result or any response from the web.

Can you advise please?

**Comment by kroitor** [comment]
@icytrader can you plz retry the search now (https://ccxt.pro/seats) and let me know if that works for you or not?

**Comment by icytrader** [comment]
> @icytrader can you plz retry the search now (https://ccxt.pro/seats) and let me know if it works for you or not?

It doess not work. I put in the username and press Enter but no reponse.

**Comment by icytrader** [comment]
![image](https://user-images.githubusercontent.com/56503955/91531019-ae50da80-e93e-11ea-9ad7-6f767da6beff.png)
I also tried clicking this icon but no response.

**Comment by kroitor** [comment]
Can you please show your web inspector (js error output from the browser)? Need to check if there's any errors there.

The search should work as follows: you type a username (no need to hit Enter) and below the search bar there should appear the search results (clickable usernames). Also, can you plz refresh the browser cache? I'll try to reproduce it on my side in the meantime.

**Comment by kroitor** [comment]
@icytrader as far as I see you don't have an active subscription right now, your previous professional order has expired on 14 of Aug. You need an active subscription in order to manage the seats. We will make that more intuitive in the seats interface. Let us know if that does not answer your question.

**Comment by kroitor** [comment]
@icytrader plz feel free to reopen this issue if you still have difficulties with it after clearing the cache and force-reloading the page with cmd+r or ctrl+f5. If you can, post your web inspector output, that will help narrow it down. Thx!

**Comment by icytrader** [comment]
Thanks. I realized that my subscription has expired. However when I tried to renew it, I see the Buy More button is grayed out and the page does not respond if I clicked Buy More, Upgrade or Downgrade. Can you check please?









------------------ Original ------------------

**Comment by kroitor** [comment]
@icytrader have you tried clearing the cache? Please, paste a screenshot of what you see, your browser version and your web inspector output, we will look into it.
