### ISSUE TITLE
ccxt.base.errors.InvalidOrder: liquid {"errors":{"price":["must_be_positive"]}}

### ISSUE THREAD

**Issue by mapapuche** [ccxt/ccxt#7527]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows 10
- Programming Language version: python 3.8
- CCXT version: ccxt-1.33.61

```
   order = exchange_to_buy.create_limit_buy_order(
            'EWT/BTC',
            23.0,
            0.00108999)
```

```
  File "main.py", line 173, in buy
    order = exchange_to_buy.create_limit_buy_order(
  File "/mnt/c/Projects/arbitrage/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1801, in create_limit_buy_order
    return self.create_order(symbol, 'limit', 'buy', *args)
  File "/mnt/c/Projects/arbitrage/venv/lib/python3.8/site-packages/ccxt/liquid.py", line 652, in create_order
    response = self.privatePostOrders(self.extend(request, params))
  File "/mnt/c/Projects/arbitrage/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 465, in inner
    return entry(_self, **inner_kwargs)
  File "/mnt/c/Projects/arbitrage/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 490, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/mnt/c/Projects/arbitrage/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 486, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/mnt/c/Projects/arbitrage/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 597, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/mnt/c/Projects/arbitrage/venv/lib/python3.8/site-packages/ccxt/liquid.py", line 1059, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, message, feedback)
  File "/mnt/c/Projects/arbitrage/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 504, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.InvalidOrder: liquid {"errors":{"price":["must_be_positive"]}}
```

I would also add, from 1 or 2 week i got lot of exceptions on Liquid exchange. I don't know what change because 1 month ago i didn't get any trouble with Liquid.

**Comment by kroitor** [comment]
Can you please paste your full verbose request+response?

Like so:

```Python
exchange.load_markets()
exchange.verbose = True
order = exchange_to_buy.create_limit_buy_order('EWT/BTC', 23.0, 0.00108999)
```

↑ Paste all the output here, please.

**Comment by mapapuche** [comment]
Verbose output :
`Request: POST https://api.liquid.com/orders {'X-Quoine-API-Version': '2', 'Content-Type': 'application/json', 'X-Quoine-Auth': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkXVCJ9.eyJwYXRoIjoiL29yZGycyIsInRva2VuX2lkIjoiMTU0OD0MyIsImlhdCI6MTU5ODYyNTMyMCwibm9uY2UiOjE1OTg2MjUzMjA0Th9.QfdFoi4SmOkyuynGTL3FuoOM_zCF6vxC1Yc8BOv6os', 'User-Agent': 'python-requests/2.24.0', 'Accept-Encoding': 'gzip, deflate'} {"order_type":"limit","product_id":"553","side":"sell","quantity":"0","price":"0"}

Response: POST https://api.liquid.com/orders 422 {'Date': 'Fri, 28 Aug 2020 14:35:23 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '97', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=d9aab907a3bebec299652d381babe271598625322; expires=Sun, 27-Sep-20 14:35:22 GMT; path=/; domain=.liquid.com; HttpOnly; SameSite=Lax; Secure, _vax_session=BAh7BkkiD3Nlc3Npb25faWQGOgZVEkiJTUzNjA1NmYOWI2ZDVmNzNiOWNjYWIzMTY0MTllMjE4BjsAVA%3D%3D--08286d68a5b2f7b21afdebc1444748f30797524c; path=/; secure; HttpOnly', 'Cache-Control': 'no-cache', 'Content-Encoding': 'gzip', 'Status': '422 Unprocessable Entity', 'Strict-Transport-Security': 'max-age=2592000', 'Vary': 'Accept-Encoding', 'Via': '1.1 spaces-router (2995ba6bec0f)', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'X-Powered-By': 'Phusion Passenger 5.1.2', 'X-Rack-Cache': 'invalidate, pass', 'X-Request-Id': '10a5964e-0d06-94e3-e54f-69dbb1267ef4', 'X-Runtime': '0.023969', 'X-Ua-Compatible': 'IE=Edge,chrome=1', 'X-Xss-Protection': '1; mode=block', 'CF-Cache-Status': 'DYNAMIC', 'cf-request-id': '04d717afd00000c0564b0a200000001', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '5c9ec22c8fadc025-MRS'} {"errors":{"price":["must_be_positive"],"quantity":["less_than_order_size"]}}
Traceback (most recent call last):
  File "/mnt/c/Projects/arbitrage/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 585, in fetch
    response.raise_for_status()
  File "/mnt/c/Projects/arbitrage/venv/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.liquid.com/orders`

**Comment by mapapuche** [comment]
[](url)

**Comment by kroitor** [comment]
This is weird, I get an adequate request with proper size and price on my side with your values:

```
mbp:ccxt igorkroitor$ python3 examples/py/cli.py liquid create_limit_sell_order EWT/BTC 7.1 0.00113212 --verbose
Python v3.7.2
CCXT v1.33.61

mbp:ccxt igorkroitor$ python3 examples/py/cli.py liquid create_limit_sell_order EWT/BTC 7.1 0.00113212 --verbose
Python v3.7.2
CCXT v1.33.61

Request: POST https://api.liquid.com/orders {'X-Quoine-API-Version': '2', 'Content-Type': 'application/json', 'X-Quoine-Auth': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL29yZGVycyIsInRva2VuX2lkIjoiNzQzNjk3IiwiaWF0IjoxNTk4NjI5NjA2LCJub25jZSI6MTU5ODYyOTYwNjQ2M30.zRTyWz786UnurY6D45ERphwC24O4zK9Bit7MJlNm8cc', 'User-Agent': 'python-requests/2.21.0', 'Accept-Encoding': 'gzip, deflate'} {"order_type":"limit","product_id":"553","side":"sell","quantity":"7.1","price":"0.00113212"}

Response: POST https://api.liquid.com/orders 422 {'Date': 'Fri, 28 Aug 2020 15:46:46 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '73', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=dbacb05a51badf25cc9e07737f1c85cb71598629606; expires=Sun, 27-Sep-20 15:46:46 GMT; path=/; domain=.liquid.com; HttpOnly; SameSite=Lax; Secure, _vax_session=BAh7BkkiD3Nlc3Npb25faWQGOgZFVEkiJWFiZjI4MDYwZTA2Yzg0NDZiMTk5YWFiYTJhODVmOTI0BjsAVA%3D%3D--3e753b0a2158b4337a479066426a8caa8e0b85ee; path=/; secure; HttpOnly', 'Cache-Control': 'no-cache', 'Content-Encoding': 'gzip', 'Status': '422 Unprocessable Entity', 'Strict-Transport-Security': 'max-age=2592000', 'Vary': 'Accept-Encoding', 'Via': '1.1 spaces-router (2995ba6bec0f)', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'X-Powered-By': 'Phusion Passenger 5.1.2', 'X-Rack-Cache': 'invalidate, pass', 'X-Request-Id': '6f8e66f8-49c2-cd8d-add1-7ca41e7aedcc', 'X-Runtime': '0.032957', 'X-Ua-Compatible': 'IE=Edge,chrome=1', 'X-Xss-Protection': '1; mode=block', 'CF-Cache-Status': 'DYNAMIC', 'cf-request-id': '04d7590c5a0000d6fd621dc200000001', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '5c9f2ac09e9dd6fd-FRA'} {"errors":{"user":["not_enough_free_balance"]}}
```

In my case i get `not_enough_free_balance`, but the requested values of size and price are ok as you can see from the above output...

What's your actual runtime version of ccxt?

Please, run this in your environment to see the actual version number (not pip3 list)

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
```

**Comment by mapapuche** [comment]
Version with your print is : CCXT Version: 1.33.61

here how i init liquid: 
```
    exchange_class = getattr(ccxt, 'liquid')
    liquid = exchange_class({
        'apiKey': '1548743',
        'secret': 'Iej0jQmO33NPDYtpav8OuimaROdPDniKOgGGoxFWKUvdsA8/T3Tp+3Aqf3CcndgTjAcytgm1FrGfRwYbkjQSrA==',
        'timeout': 30000,
        'enableRateLimit': True,
    })
```

Do you think problem can be link to my liquid account ? Or maybe problem is linked to the paid i'm trading ? I trade on EWT/BTC and i know liquid removed EUR/EWT pair so maybe somthing wrong from that

**Comment by mapapuche** [comment]
here the print you ask me : CCXT Version: 1.33.61

The code where i initiate : 
```
    exchange_class = getattr(ccxt, 'liquid')
    liquid = exchange_class({
        'apiKey': 'key',
        'secret': 'key',
        'timeout': 30000,
        'enableRateLimit': True,
    })
```

Do you think that can come from the pair i trade ? I'm trading on EWT/BTC.

**Comment by kroitor** [comment]
> I will continue to check deeper, if that work for you i have probably do something wrong. Or maybe error "not_enough_free_balance" is catch before the error i get ?

I don't think so, because in my output those values look correct.

Also, you can test your values as follows:

```Python
exchange = ccxt.liquid({
    'enableRateLimit': True,
})

exchange.load_markets()

print(exchange.amount_to_precision('EWT/BTC', 7.1))
print(exchange.price_to_precision('EWT/BTC', 0.00113212))
```

↑ What do you see?

**Comment by mapapuche** [comment]
```
Traceback (most recent call last):
  File "main.py", line 502, in <module>
    print('Amount:', liquid.amount_to_precision('EWT/BTC', 7.1))
  File "/mnt/c/Projects/arbitrage/venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1264, in amount_to_precision
    return self.decimal_to_precision(amount, TRUNCATE, self.markets[symbol]['precision']['amount'], self.precisionMode)
TypeError: 'NoneType' object is not subscriptable
```

**Comment by kroitor** [comment]
@mapapuche did you load the markets?

**Comment by mapapuche** [comment]
Amount: 7.1
Price: 0.00113212

**Comment by kroitor** [comment]
@mapapuche ok, now, change this snippet for your keys, and try this:

```Python
import ccxt

exchange = ccxt.liquid({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,
})

markets = exchange.load_markets()

print('Amount:', exchange.amount_to_precision('EWT/BTC', 7.1))
print('Price:', exchange.price_to_precision('EWT/BTC', 0.00113212))

order = exchange.create_limit_sell_order('EWT/BTC', 7.1, 0.00113212)
print(order)
```

↑ This should work.

> if i remove all my code and only do that + order buy it's working ... So problem is on my side sorry. i don't know where but i'll find xd

Yep, that's what i'm trying to say, your values get zeroed outside of CCXT most likely. You can test that with the snippet from this comment.

**Comment by mapapuche** [comment]
Yes sorry for waste of time. thank for the support

**Comment by JosephWN** [comment]
> here the print you ask me : CCXT Version: 1.33.61
> 
> The code where i initiate :
> 
> ```
>     exchange_class = getattr(ccxt, 'liquid')
>     liquid = exchange_class({
>         'apiKey': 'key',
>         'secret': 'key',
>         'timeout': 30000,
>         'enableRateLimit': True,
>     })
> ```
> 
> I will continue to check deeper, if that work for you i have probably do something wrong. Or maybe error "not_enough_free_balance" is catch before the error i get ?
> 
> PS : I have this error only on Liquid, all other exchange are ok. That very weird because it's the same code for all exchange, and with other exchange that sell / buy order is OK and work well.

I have same issue as yours, in recent CCXT versions (may be 1.33.XX?). 
Create_limit_order of liquid always raised exceptions like "quantity":["less_than_order_size"], but other exchanges works well.

I did not change my code, so I guess something went wrong in CCXT updates. Now I am working on finding the reason.

PS: Liquid works well on CCXT ver1.32.1 in my code.

**Comment by kroitor** [comment]
@JosephWN 

Enable the verbose mode and check your values against order limits and precision:

- https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting


```Python
import ccxt

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.liquid({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,
})

markets = exchange.load_markets()

symbol = 'EWT/BTC'  # ←------------------- YOUR SYMBOL HERE

market = exchange.market(symbol)
pprint(market)
print('------------------------------------------------------------------------------')
print(symbol, 'limits:')
pprint(market['limits'])
print('------------------------------------------------------------------------------')
print(symbol, 'precision:')
pprint(market['precision'])
print('------------------------------------------------------------------------------')

amount = 123.45  # ←------------------- YOUR AMOUNT HERE
price = 54.321  # ←------------------- YOUR PRICE HERE

print('Your amount:', amount)
print('Your price:', price)

exchange.verbose = True

order = exchange.create_order(symbol, 'limit', 'sell', amount, price)
pprint(order)
```

**Comment by JosephWN** [comment]
> @JosephWN
> 
> Enable the verbose mode and check your values against order limits and precision:
> 
> * https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits
> * https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
> 
> ```python
> import ccxt
> 
> print('CCXT Version:', ccxt.__version__)
> 
> exchange = ccxt.liquid({
>     'apiKey': 'YOUR_API_KEY',
>     'secret': 'YOUR_SECRET',
>     'enableRateLimit': True,
> })
> 
> markets = exchange.load_markets()
> 
> symbol = 'EWT/BTC'  # ←------------------- YOUR SYMBOL HERE
> 
> market = exchange.market(symbol)
> pprint(market)
> print('------------------------------------------------------------------------------')
> print(symbol, 'limits:')
> pprint(market['limits'])
> print('------------------------------------------------------------------------------')
> print(symbol, 'precision:')
> pprint(market['precision'])
> print('------------------------------------------------------------------------------')
> 
> amount = 123.45  # ←------------------- YOUR AMOUNT HERE
> price = 54.321  # ←------------------- YOUR PRICE HERE
> 
> print('Your amount:', amount)
> print('Your price:', price)
> 
> print('------------------------------------------------------------------------------')
> 
> exchange.verbose = True
> 
> order = exchange.create_order(symbol, 'limit', 'sell', amount, price)
> pprint(order)
> ```

Thx, my trading pair is 'BTC/JPY', I found the amount precision maybe the problem.
When I use CCXT 1.32.1, calling 'pp(liquid_markets['BTC/JPY'])', I got 'precision': {'amount': 8, 'price': 5}.
When I use CCXT 1.33.68, calling 'pp(liquid_markets['BTC/JPY'])', I got 'precision': {'amount': 1e-8, 'price': 5}.

The precision amount should be 8, not 1e-8.

**Comment by kroitor** [comment]
@JosephWN with TICK_SIZE precisionMode the precision values are floats as opposed to the DECIMAL_DIGITS precisionMode, this is documented here:

- https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits

Here's what I see on my side for Liquid with CCXT 1.33.72:

```
mbp:python igorkroitor$ python3
Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> exchange = ccxt.liquid({'enableRateLimit':True})
>>> markets = exchange.load_markets()
>>> print('CCXT Version:', ccxt.__version__)
CCXT Version: 1.33.72
>>> market = exchange.market('BTC/JPY')
>>> print(market['precision'])
{'amount': 1e-08, 'price': 1.0}
>>> print(market['limits'])
{'amount': {'min': 0.001, 'max': None}, 'price': {'min': None, 'max': None}, 'cost': {'min': None, 'max': None}}
>>>
```

↑ Do you see the same results on your side?

**Comment by mapapuche** [comment]
@JosephWN 
My problem was because i copy the data from exchange to new variable called "exchange_to_buy" then when i do exchange_to_buy.buy_order() i got error. I think (i don't know why) we can't copy the variable received from exchange = ccxt.liquid() to another variable. 

Also, to be sure if the problem come from code or from you (as i did haha ) you should run the snippe code t kroitor gived from outside of your code :
```
import ccxt

exchange = ccxt.liquid({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,
})


markets = exchange.load_markets()

print('Amount:', exchange.amount_to_precision('EWT/BTC', 7.1))
print('Price:', exchange.price_to_precision('EWT/BTC', 0.00113212))

order = exchange.create_limit_sell_order('EWT/BTC', 7.1, 0.00113212)
print(order)

```
