### ISSUE TITLE
fetch_balance() rounds big floats - parse_json() method problem

### ISSUE THREAD

**Issue by Djusk8** [ccxt/ccxt#7528]
- OS: OS Independent
- Programming Language version: Python 3.7
- CCXT version: 1.33.61

I got this problem with YoBit exchange, but I think this affects all exchanges because it's incorrect operation of `parse_json()` method of base `Exchange` class.

So, I have an YoBit account with relatively big amount of LIZA coin, in my case - 3526246938.98713**386** LIZA
I called the `fetch_balance()` method and got balance with 3526246938.98713**4** LIZA. As you can see last 3 digits '386' was rounded to 1 digit '4'. 

I got similar behavior with all balances which total length is more than 16 digits, luckily there aren't many of them. 

I tried to find the cause and I think the problem is with `parse_json()` method in this block of code:

```
    def fetch(self, url, method='GET', headers=None, body=None):
        """Perform a HTTP request and return decoded JSON data"""
        request_headers = self.prepare_request_headers(headers)
        url = self.proxy + url

        if self.verbose:
            self.print("\nRequest:", method, url, request_headers, body)
        self.logger.debug("%s %s, Request: %s %s", method, url, request_headers, body)

        request_body = body
        if body:
            body = body.encode()

        self.session.cookies.clear()

        http_response = None
        http_status_code = None
        http_status_text = None
        json_response = None
        try:
            response = self.session.request(
                method,
                url,
                data=body,
                headers=request_headers,
                timeout=int(self.timeout / 1000),
                proxies=self.proxies,
                verify=self.verify
            )
            # does not try to detect encoding
            response.encoding = 'utf-8'
            http_response = response.text
            http_status_code = response.status_code
            http_status_text = response.reason
            json_response = self.parse_json(http_response)     <- problem there !!!
            headers = response.headers
.....
.....
```

After fetching balance data from server `http_response` variable contains right amount of LIZA.
But when data parsed by `self.parse_json()` variable `json_response` cantain wrong rounded data.

On the left side of screenshot is `http_response`, on the right side - `json_response`
![Screenshot 2020-08-28 at 15 35 25](https://user-images.githubusercontent.com/35682654/91564835-e6a9e600-e949-11ea-878f-cfba07b8bca4.png)

**Comment by kroitor** [comment]
@Djusk8 it's an issue of the built-in json-parser + python fp precision:

```Python
mbp:ccxt igorkroitor$ python3
Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import json
>>> json.loads('{"liza":3526246938.98713386}')
{'liza': 3526246938.987134}
```

In other words, the precision of python floats is usually enough for most purposes. String-based fp support is discussed here: https://github.com/ccxt/ccxt/issues/522

If you really want string-based access to those millionths digits `...386` – you can access the last response as text and parse it how you want: 

```Python
exchange.fetch_balance()
print(exchange.last_http_response)
```

Let us know if the above does not answer your question.

**Comment by Djusk8** [comment]
Thanks for datailed explanation!
