### ISSUE TITLE
How to group trades by order_id

### ISSUE THREAD

**Issue by optima66** [ccxt/ccxt#7529]
**Python**
I am using `fetch_my_trades`  method to get orders from binance:  
```
exchange.fetch_my_trades (symbol = "BTC/USDT", since = None, limit = None, params = {})
```
Sometimes from one order I can get several trades that has common order_id
**For example one of my orders resulted in four trades:**
```
order_id:2943727870 | BTC/USDT | 0.023179 | buy | 2020-08-15 10:58:27.533000
order_id:2943727870|BTC/USDT|0.010628|buy|2020-08-15 10:58:24.820000
order_id:2943727870|BTC/USDT|0.007173|buy|2020-08-15 10:58:24.807000
order_id:2943727870|BTC/USDT|0.023179\|buy\|2020-08-15 10:58:27.533000
```
Is there a built in possibility or may be api endpoint to group these trades by order and instead four trades show just one with average fill price?

**Comment by kroitor** [comment]
> I am using fetch_my_trades method to get orders from binance:

The `fetch_my_trades` method is for fetching trades, don't confuse trades with orders. Orders are usually fetched with `fetch_open_orders`, `fetch_closed_orders`, `fetch_orders`, `fetch_order`, etc.

This is explained in the Manual here: https://github.com/ccxt/ccxt/wiki/Manual#how-orders-are-related-to-trades

I highly recommend to read the entire Manual from top to bottom – it will save your time:

- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/wiki/Manual

To answer your question on how to group trades by order id:

```Python
trades = exchange.fetch_my_trades (symbol = "BTC/USDT", since = None, limit = None, params = {})
trades_by_order_id = exchange.group_by(trades, 'order');
```

or

```Python
trades = exchange.fetch_my_trades (symbol = "BTC/USDT", since = None, limit = None, params = {})
trades_by_order_id = {}
for trade in trades:
    order_id = trade['order']
    if order_id in trades_by_order_id:
        trades_by_order_id[order_id].append (trade)
    else:
        trades_by_order_id[order_id] = [ trade ]
```

Let us know if the above does not answer your question.
