### ISSUE TITLE
Is there way to get all YoBit OPEN orders?

### ISSUE THREAD

**Issue by CryptoTropico** [ccxt/ccxt#753]
It may be an obvious thing! But I can't find this anywhere!

I am using:

> exchange.fetchOpenOrders();

But it looks like I need to specify the pair, otherwise it returns this error:

`errors.js:3 Uncaught (in promise) ExchangeError: yobit fetchOrders requires a symbol
    at yobit.fetchOrders (https://unpkg.com/ccxt@1.10.286/build/ccxt.browser.js:19502:19)
    at yobit.fetchOpenOrders (https://unpkg.com/ccxt@1.10.286/build/ccxt.browser.js:19539:33)`

Thank you guys.

**Comment by kroitor** [comment]
> But it looks like I need to specify the pair, otherwise it returns this error:

Unfortunately, YoBit indeed requires you to specify a symbol to fetch open orders (they only server orders for a particular pair and they can't serve mixed orders). The same is true for all BTC-e clones: Liqui, Tidex, Wex, YoBit..

Sorry, but this is not something we can workaround. It's a limitation of their API. So you will have to supply a symbol. Does this answer your question?
