### ISSUE TITLE
Binance future symbol `SXP` is not supported

### ISSUE THREAD

**Issue by ChenLi0830** [ccxt/ccxt#7530]
Binance future new symbol `SXP` is not supported in the current version. 

- OS: Centos
- Programming Language version: Node 12
- CCXT version: latest ccxt.pro - #e624d6e35f121e6bf94fa9fe864f46de5829a416

Same code works for other symbols in future such as BTC, ETH, etc. However, when trying to trade SXP, it stopped working..

```
 BadSymbol: binance does not have market symbol SXP/USD
    at binance.market (/tradeExecution/node_modules/ccxt.pro/node_modules/ccxt/js/base/Exchange.js:938:15)
    at binance.watchOrderBook (/tradeExecution/node_modules/ccxt.pro/js/binance.js:81:29)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    ...
  constructor: [Function: BadSymbol],
  name: 'BadSymbol'

```

**Comment by kroitor** [comment]
@ChenLi0830 Binance does not have SXP/USD, it has SXP/USDT instead: https://fapi.binance.com/fapi/v1/exchangeInfo what you see is what you get from the exchange API itself directly, CCXT does not decide which symbols are available. 

```
import ccxt
exchange = ccxt.binance({'enableRateLimit':True})
markets = exchange.load_markets()
for symbol in exchange.symbols:
     print(symbol)
```

Hope that answers your question.

**Comment by ChenLi0830** [comment]
Hey @kroitor Thank you for the quickly reply! It was a typo on my side. Best
