### ISSUE TITLE
Pro Intellisense missing Order TS type 

### ISSUE THREAD

**Issue by Stevenje** [ccxt/ccxt#7539]
![image](https://user-images.githubusercontent.com/4363358/91713044-98196900-eb4e-11ea-962a-a02504b92388.png)

**Comment by kroitor** [comment]
The trades should be of type ccxt.Trade[], orders should be of type ccxt.Order[], this is explained here:

- https://github.com/ccxt/ccxt/wiki/Manual#how-orders-are-related-to-trades

Let us know if that does not answer your question.

**Comment by Stevenje** [comment]
Hey @kroitor my issue was that the order type is missing from ccxtpro, nothing to do with trades vs orders.

**Comment by kroitor** [comment]
@Stevenje i mean it's inherited in CCXT Pro from CCXT, so you can import it from CCXT (there's no need to duplicate the export in Pro in this case).
