### ISSUE TITLE
Crex24 Withdraw Issue

### ISSUE THREAD

**Issue by srdante** [ccxt/ccxt#7544]
I always used CCXT to make automated withdrawals normally at Crex24, but due to some update on their API, the feeCurrency parameter is now mandatory, which is not included in the code. 

However, it can be solved by inserting the following code on line 1262, on PHP version:

```
'feeCurrency' => $currency['id'],
```

- OS:Ubuntu 18.04
- Programming Language version:PHP
- CCXT version:1.33.79

```
$ccxt->withdraw(strtoupper('doge'), 1000, 'DBTgfjXpJeFednbqx82Jz96QfeyRwosURs');
```

```
{"status":500,"result":"Exchange Error: Crex24 {\"errorDescription\":\"Mandatory parameter 'feeCurrency' is missing.\"}
```

**Comment by kroitor** [comment]
@srdante you can specify the feeCurrency via `params`, just like with any other unified method:

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

```PHP
$code = 'DOGE';
$currency = $exchange->currency($code);
$params = array('feeCurrency' => $currency['id']);
$exchange->withdraw($code, 1000, 'DBTgfjXpJeFednbqx82Jz96QfeyRwosURs', $params);
```

If you update to CCXT 1.33.80 (the new build will arrive in 15 minutes), the `feeCurrency` will be filled in for you (will be the same as the withdrawal currency by default).

Thx for reporting it! 

If you have further issues with it, please, make sure to follow these guidelines precisely: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help. Feel free to reopen this issue or just ask further questions if any.
