### ISSUE TITLE
Gateio version

### ISSUE THREAD

**Issue by monk-after-90s** [ccxt/ccxt#7547]
In [https://github.com/ccxt/ccxt#supported-cryptocurrency-exchange-markets](url)  the version of gateio is 2. However, in practice, it seems not:
```Python
gateio=ccxt.gateio()
print(gateio.urls['api'])
#{'public': 'https://data.gate.io/api', 'private': 'https://data.gate.io/api'}
```
In gateio api document, v2 api url is  https://data.gateio.la/api2.

**Comment by kroitor** [comment]
It is using v2. The symbol `2` is appended to the base URLs and gateio has changed the base URLs a few times:

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```Python
import ccxt
from pprint import pprint

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.gateio({
    'enableRateLimit': True,  # required: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
})
markets = exchange.load_markets()

exchange.verbose = True  # enable to see the actual URLs and requests

response = exchange.fetch_ticker('ETH/BTC')
pprint(response)
```

Let us know if that does not answer your question.

**Comment by monk-after-90s** [comment]
@kroitor Well, it seems really version 2.
My problem came from this scene:
```python
import ccxt
gateio=ccxt.gateio({"apiKey": "argrwegfgfgertqertqergertg","secret": "ertwertqergfgsertgwetertwert",})
gateio.load_markets()
gateio.create_order('ELF/USDT','limit','buy',100,0.1)
#{'id': '15770792916', 'clientOrderId': None, 'datetime':...
gateio.cancel_order(15770792916,'ELF/USDT')
gateio.fetch_orders('ELF/USDT')
#[]
```
And gateio don't have 'fetchClosedOrders' method.
So how to get gateio order history?

**Comment by kroitor** [comment]
@monk-after-90s

> And gateio don't have 'fetchClosedOrders' method.
> So how to get gateio order history?

The exchanges usually have:
- either fetchOpenOrders (fetch_open_orders) + fetchClosedOrders (fetch_closed_orders)
- or fetchOrders

You can use the above to get your history of orders.

**Comment by monk-after-90s** [comment]
> @monk-after-90s
> 
> > And gateio don't have 'fetchClosedOrders' method.
> > So how to get gateio order history?
> 
> The exchanges usually have:
> 
>     * either fetchOpenOrders (fetch_open_orders) + fetchClosedOrders (fetch_closed_orders)
> 
>     * or fetchOrders (fetch_orders) – for open+closed orders
> 
> 
> You can use the above to get your history of orders.

As show above, gateio fetch_orders method don't behave well.

**Comment by kroitor** [comment]
@monk-after-90s 

> As show above, both fetch_orders and fetch_closed_orders method don't behave well for gateio.

What do you mean?

**Comment by monk-after-90s** [comment]
> @kroitor Well, it seems really version 2.
> My problem came from this scene:
> 
> ```python
> import ccxt
> gateio=ccxt.gateio({"apiKey": "argrwegfgfgertqertqergertg","secret": "ertwertqergfgsertgwetertwert",})
> gateio.load_markets()
> gateio.create_order('ELF/USDT','limit','buy',100,0.1)
> #{'id': '15770792916', 'clientOrderId': None, 'datetime':...
> gateio.cancel_order(15770792916,'ELF/USDT')
> gateio.fetch_orders('ELF/USDT')
> #[]
> ```
> 
> And gateio don't have 'fetchClosedOrders' method.
> So how to get gateio order history?

The code shows that gateio fetch_orders doesn't work. And gateio has no fetch_closed_orders. 
So there is no way to get order history. 
Gateio fetch_open_orders works well.
I want order history.

**Comment by kroitor** [comment]
@monk-after-90s it does work, but it does not return canceled orders. You can also use `fetchOrder` to check the status of the order returned from `createOrder` by `id`. That is not a limitation of CCXT, though, it is more like a limitation of the Gate.io API itself. In other words, some exchanges require you to store your history for yourself. You can deduce some of it from the history of your personal trades as well.
