### ISSUE TITLE
can not import ccxt.async in python

### ISSUE THREAD

**Issue by Mambix** [ccxt/ccxt#755]
Just did `pip install ccxt` and when trying to use it I get this:

```
>>> import ccxt.async as ccxt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/ccxt/async/__init__.py", line 11, in <module>
    from ccxt.async.base.exchange import Exchange                   # noqa: F401
  File "/usr/local/lib/python2.7/site-packages/ccxt/async/base/__init__.py", line 4, in <module>
    from ccxt.async.base import exchange
  File "/usr/local/lib/python2.7/site-packages/ccxt/async/base/exchange.py", line 58
    async def wait_for_token(self):
            ^
SyntaxError: invalid syntax
>>> 
```

**Comment by kroitor** [comment]
The `async` functionality is Python3 only!

**Comment by Mambix** [comment]
I see. might be worth adding a note in docs

**Comment by kroitor** [comment]
@Mambix this has been documented here:
https://github.com/ccxt/ccxt/wiki/Manual#synchronous-vs-asynchronous-calls

![screen-shot-2017-12-06-at-00 22 16](https://user-images.githubusercontent.com/1294454/33631448-adf1d3da-da1b-11e7-954f-76a2efd0514e.jpg)

**Comment by kroitor** [comment]
From the main README (frontpage of the lib):

![screen-shot-2017-12-06-at-00 24 20](https://user-images.githubusercontent.com/1294454/33631556-f7d109da-da1b-11e7-8641-2a08b56f021e.jpg)
