### ISSUE TITLE
Binance futures fetch balance failing for undefined offset: 0

### ISSUE THREAD

**Issue by etiennez0r** [ccxt/ccxt#7550]
https://github.com/ccxt/ccxt/blob/302c93d6f4f3bfd299e1a55451ba1bf93d6a5b1c/php/binance.php#L817

Hello Guys! 

on this line in think it should be 

if (gettype($response) === 'array' && count(array_filter(array_keys($response), 'is_string')) != 0)

instead of (!gettype($response) === 'array' && count(array_filter(array_keys($response), 'is_string')) == 0)

Its not entering in the IF statement with what it receives as you can see in attached picture.

![image](https://user-images.githubusercontent.com/5843949/91873080-9cc14880-ec46-11ea-8ff5-e158f34f877b.png)

**Comment by kroitor** [comment]
Please, update to the most recent version, this bug has been addressed already. Checking your version number if the first step in the troubleshooting sequence:

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

Let us know if you still have the same issue with the most recent version of CCXT. Thx!

**Comment by kroitor** [comment]
P.S. https://github.com/ccxt/ccxt/blob/master/php/binance.php#L817
