### ISSUE TITLE
CCXT Pro Demo data is wrong

### ISSUE THREAD

**Issue by diwenshi61** [ccxt/ccxt#7551]
(Closed and reopened because I accidentally pressed enter before typing out the issue)
I was looking at your CCXT Pro product, and it appears that the Demo you show has incorrect data on the Poloniex exchange due to the price increment being wrong.
![image](https://user-images.githubusercontent.com/51501270/91936084-af875c00-ecde-11ea-85ff-5d6d8c17f73f.png)

**Comment by kroitor** [comment]
@diwenshi61 hi! Thx for reporting! The data itself is ok, however, the values were truncated upon rendering, fixed that.
