### ISSUE TITLE
Memory leak detected for bybit.js

### ISSUE THREAD

**Issue by molarro** [ccxt/ccxt#7552]
On every request (e.g. createOrder or fetchTickers) doing via bybit.js new "system / JSArrayBufferData" object is added to memory and don't released. 
This behavior is detected with the help of memory snapshot in Chrome DevTools running Nodejs in inspect mode.  Please look at the screenshot:
![bybit-memory-leak](https://user-images.githubusercontent.com/17534971/92002626-b6e34f80-ed48-11ea-986f-f4a291499119.png)
 
### Environment
- OS: Docker Nodejs container - Debian GNU/Linux 9 (stretch)
- Programming Language version: Nodejs version - 13, running by pm2
- CCXT version: 1.33.86

### How to replicate the issue

1. Run Nodejs in inspect mode.
2. Connect Chrome DevTools to Nodejs inspect.
3. Take a memory heap snapshot in Chrome.
4. Measure size of JSArrayBufferData objects.
5. Make multiple requests via bybit.js, e.g. 100 requests to 'fetchTickers' .
6. Take the new memory snapshot.
7. Inspect JSArrayBufferData one more time.
8. You should see a lot of new JSArrayBufferData objects with size ~1600 bytes each like in screenshot.  

### Code to reproduce
```
const ccxt = require ('ccxt');

// Take new memory snapshots in Chrome, while executing this function.
(function() {
    console.log(ccxt.version);

    let callCnt = 0;
    let interval = setInterval(async () => {
        callCnt++;

        let bybit = new ccxt.bybit();
        let res = await bybit.fetchTicker('BTC/USDT');
        console.log(res['symbol'], res['bid'], res['ask']);

        if (callCnt === 100) { // +100 new JSArrayBufferData objects after 100 sec.
            clearInterval(interval);
        }
    }, 1000);
})();
```
P.S. In others exchanges there is no such problem.

**Comment by kroitor** [comment]
@molarro just to clarify, you're getting the above behavior with the most recent version 1.33.86+, right?

**Comment by molarro** [comment]
> @molarro just to clarify, you're getting the above behavior with the most recent version 1.33.86+, right?
Yes, at first we used 1.27, then upgrade to 1.33.86 - same issue.

**Comment by kroitor** [comment]
@molarro we have addresses this issue previously, can you plz verify that your runtime version is up to date?

I mean, running something like this in your Chrome console to make sure that the actually used version is the most recent version:

```JavaScript
console.log (ccxt.version)
```

**Comment by kroitor** [comment]
@molarro also, if you can, please, paste the code you use to reproduce it:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by molarro** [comment]
@kroitor Yes, we exactly use 1.33.93 and I have updated my post with a sample code to reproduce.

**Comment by frosty00** [comment]
looks like it is working good for me in node with no memory leak. sometimes it can take the garbage collector a few seconds to clean up

**Comment by molarro** [comment]
> looks like it is working good for me in node with no memory leak. sometimes it can take the garbage collector a few seconds to clean up

Oddly, in our Nodejs, every hour amount of JSArrayBufferData objects increase until out of memory.

**Comment by molarro** [comment]
Does  growth of JSArrayBufferData objects depends on request method (e.g. http, sockets) used in particular exchange library? Also, can request execution speed and amount impact on amount of  JSArrayBufferData objects? 

Using Binance and Kucoin there are no additional JSArrayBufferData objects with content like 'api.bybit.com:443:::::::::::' - only using Bybit, Deribit and ftx.

**Comment by frosty00** [comment]
for now you can fix this by doing:

```
const ccxt = require ('ccxt');

// Take new memory snapshots in Chrome, while executing this function.
(function() {
    console.log(ccxt.version);

    let callCnt = 0;
    let bybit = new ccxt.bybit(); // <-- this

    let interval = setInterval(async () => {
        callCnt++;

        let res = await bybit.fetchTicker('BTC/USDT');
        console.log(res['symbol'], res['bid'], res['ask']);

        if (callCnt === 100) { // +100 new JSArrayBufferData objects after 100 sec.
            clearInterval(interval);
        }
    }, 1000);
})();
```

we are working on a proper fix

**Comment by ttodua** [comment]
Even though there has not been posted any follow-up, the solution proposed by @frosty00 is the correct way how you should initiate the exchange (as it definitely needs to be out from loop). Otherwise, as the object will not die inside interval, then of course, the increase in memory will be expected.
Let us know if anyone has any similar issue.
