### ISSUE TITLE
ques: cost in trade structure is inclusive of fee ?

### ISSUE THREAD

**Issue by abhishekr-bh** [ccxt/ccxt#7556]
Hi
I had a small doubt, is the 'cost' field. calculated as price * amount inclusive of fee or not ?
If the price * amount is `x` and the fee is `y`, then cost is `x + y` or just `x`

**Comment by abhishekr-bh** [comment]
It is including fees, written in the comments

`// total cost (including fees), price * amount`

**Comment by fkaleo** [comment]
> It is including fees, written in the comments
> 
> `// total cost (including fees), price * amount`

that sounds contradictory: computing `price*amount` I don't think will include the fees right?

**Comment by kroitor** [comment]
@fkaleo it means _"gross"_ values. So, `total cost = filled * price`, that's the amount pre-fees, and the fees have to be applied afterwards. We will change that comment to make it less confusing, thanks for pointing it out!

**Comment by fkaleo** [comment]
> @fkaleo it means _"gross"_ values. So, `total cost = filled * price`, that's the amount pre-fees, and the fees have to be applied afterwards. We will change that comment to make it less confusing, thanks for pointing it out!

thank you very much @kroitor ! I spent 30 minutes going through manual and bug reports to figure this one out *for sure* as I found contradicting information.

**Comment by kroitor** [comment]
@fkaleo please, don't hesitate if you find more of these! Your PRs are welcome!
