### ISSUE TITLE
How to do Transactions like buy and sell between two exchanges with the help of test coins in python using ccxt Library ?

### ISSUE THREAD

**Issue by AsadullahSoomro** [ccxt/ccxt#7561]
How to do Transactions like buy and sell between two exchanges with the help of test coins in python
using CCXT Library?

**Comment by AsadullahSoomro** [comment]
Can anyOne tell me that how to do a transaction between two exchange  using dummy test coins in python
using CCXT Library?

**Comment by kroitor** [comment]
@AsadullahSoomro the exchanges have a unified method called `withdraw` – it is documented in the CCXT Manual.
I would highly recommend you to read the entire Manual from top to bottom, most of the questions are already answered there. Check out the examples as well.

- https://github.com/ccxt/ccxt/wiki
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/tree/master/examples

If you have a difficulty with the code afterwards, please post your code snippet, your verbose output, and other info as explained here:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

Let us know if the above info does not answer your question.
