### ISSUE TITLE
question about currency formatting

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#7563]
const currency = 'XRP';
        const rawAmount = 9164.154999999999;
        const exchangeId = 'hitbtc';

        const exchange = new ccxt[exchangeId]();
        await exchange.loadMarkets();

        const precision = exchange.currencies[currency]['precision']
        console.log({precision});

        const formatted = exchange.currencyToPrecision(currency, rawAmount);
        console.log({formatted})

Produces:

```
{ precision: 8 }
{ formatted: '9168' }
```

I was expecting it for format the value to `9164.1550`.  Is this because the precision mode is TICK_SIZE ? If so, can you suggest a way to currently format an amount for withdrawal (`9164.1550` in this case IS valid).

**Comment by kroitor** [comment]
@npomfret it was a bug, a conflict of TICK_SIZE in the markets vs DECIMAL_PLACES in the currencies. I've uploaded a fix for it, now it's TICK_SIZE everywhere in HitBTC, let me know if you have further issues with it after upgrading to 1.34.4. The new build will arrive in 15 minutes. Thx again for your involvement!

**Comment by npomfret** [comment]
Perfect, thank you
