### ISSUE TITLE
Arbitrage trading

### ISSUE THREAD

**Issue by CopurOnur** [ccxt/ccxt#757]
@kroitor 
Hello guys,
I am new to the ccxt library and I want to use the library for building an arbitrage trading bot on python. I have checked the example on https://github.com/ccxt/ccxt/blob/master/examples/py/arbitrage-pairs.py
but I am still not confident about how to create a bot. If there is a template code that you can share with me, I could get an idea how to build the bot. 
Thanks for your attention.

**Comment by kroitor** [comment]
We will be posting new examples soon and hope to share a bot skeleton there, however, you should be prepared to create a strategy of your own, nobody will invent it for you, and guys that do have a strategy aren't really eager to share their profits ) Welcome to our world of friendly sharks.

If you want a bot template, see here:
- https://github.com/ccxt/ccxt/network/dependents
- https://github.com/kroitor?page=1&tab=stars&utf8=%E2%9C%93&q=bot
- https://github.com/ccxt/ccxt/blob/6b9199c8c88a01269ea6132c3097f2c726c127a6/doc/checklist.rst

Hope it helps. I'd close this for now, feel free to reopen this issue if needed or just ask questions if you have any. Thanks!
