### ISSUE TITLE
How to place margin leverage order on bitfinex?

### ISSUE THREAD

**Issue by nkasimova** [ccxt/ccxt#7571]
- OS: Ubuntu 18
- Programming Language version: python 3.7.7
- CCXT version: 1.28.49

Hi,

I would like to set up leverage 4 (1:4 or 25%) on bitfinex 'BTC/USDT'

First of all, I tried:
bitfinex.create_market_sell_order(symbol, btc_volume * 4, {'type': 'market', 'lev': '4'}) 
but, when I handly calculated leverage value like this: btc_volume * 4 * price_sell / used_USDT, where used_USDT is bitfinex.fetch_balance({'type': 'trading'})['used']['USDT'] , I got 4.867583077733511 instead of expected 4

After that I tried to set up 25 as percentage equivalent of leverage 4
bitfinex.create_market_sell_order(symbol, btc_volume * 4, {'type': 'market', 'lev': '25.0'})
however I got 4.912040237654479 as calculated by hand leverage value 

So, I've got that the value is floatting and my param 'lev' doesn't work
Next, I tried 'leverage' instead of 'lev' and even 'initial_margin' because .fapiPrivate_post_leverage() doesn't exist for bitfinex 
And I also tried bitfinex.create_order(symbol, 'market', 'sell', btc_volume * 4, None, { 'lev': "25"}), but it works only for exchange not for margin
Help me, please

**Comment by kroitor** [comment]
Hi @nkasimova !

What's your `btc_value`? Can you please paste your verbose output?

```Python
exchange.load_markets()

exchange.verbose = True  # after load_markets()

balance = exchange.fetch_balance({'type': 'trading'})
print('Balance:', balance['used']['USDT'])

print('---------------------------------------------------------------------------')

print('BTC Volume:', btc_volume)

print('---------------------------------------------------------------------------')

market_sell = exchange.create_market_sell_order(symbol, btc_volume * 4, {'type':'market', 'lev':'4'})
print('Market sell:', market_sell)

print('---------------------------------------------------------------------------')

balance = exchange.fetch_balance({'type': 'trading'})
print('Balance:', balance['used']['USDT'])
```

**Comment by kroitor** [comment]
@nkasimova we need more info from you in order to help, namely your verbose request+response as explained here: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help. Feel free to reopen this issue or just ask further questions if any. Closing it for now if you don't mind.
