### ISSUE TITLE
ByBit auth error handling

### ISSUE THREAD

**Issue by dducted** [ccxt/ccxt#7573]
Hi,

I am using python. Trying to except an Authentication Error with `except ccxt.AuthenticationError as e:`. It works all fine with Bitmex, Deribit, Binance however ByBit is throwing me the following:

`ccxt.base.errors.ExchangeError: bybit {"ret_code":10003,"ret_msg":"invalid api_key","ext_code":"","ext_info":"","result":null,"time_now":"1599547085.415797"}`

Not sure why `invalid api_key` returns an `ExchangeError`. Is that normal to happen?

Thanks for your help.

**Comment by kroitor** [comment]
> Is that normal to happen?

Nope, it's not. The problem is that the exchange does not document all possible error codes in this case. So, we have to add those error mappings upon encountering them. I've uploaded a fix for it, let us know if you have issues with it after upgrading CCXT to version 1.34.9+. Thx for reporting it!
