### ISSUE TITLE
Transaction between multiple exchanges?

### ISSUE THREAD

**Issue by Usmankhokhar123** [ccxt/ccxt#7574]
how can I do some Transaction like buy and sell between two exchanges using CCXT?
Is there any function for that? or any way so I could do that

**Comment by kroitor** [comment]
> Is there any function for that? or any way so I could do that

Yes, this is done with the `withdraw` unified method: https://github.com/ccxt/ccxt/wiki/Manual#withdraw
You pick the source exchange you want to send the money from and call a withdraw method with it specifying the destination exchange – this way you transfer funds between two exchanges.

I would highly recommend reading the entire Manual from top to bottom – it will really save your time:

- https://github.com/ccxt/ccxt/wiki
- https://github.com/ccxt/ccxt/wiki/Manual

Let us know if that does not help.
