### ISSUE TITLE
Adjust leverage Using php - Found only solution using python 

### ISSUE THREAD

**Issue by Yassineelma** [ccxt/ccxt#7576]
Hello im trying to create a small program to create future orders i found this script to create future order 
https://github.com/ccxt/ccxt/issues/6315
I will use this code 
`
Date_default_timezone_set('UTC');
include 'ccxt.php';
$exchange_id = 'binance';
$exchange_class = "\\ccxt\\$exchange_id";
$binance = new $exchange_class(array(
    'apiKey' => "apiKey",
    'secret' => "secret",
    'timeout' => 30000,
    'enableRateLimit' => true,
    'options' => array('defaultType' => "future")
));

$symbol = "BTC/USDT";
$quantity = 0.002;
$price = 5000;

// add this ↓
$binance->load_markets();
$binance->verbose = true; // ←------ verbose mode on

var_dump ($binance->id, $binance->createOrder($symbol,"limit","buy",$quantity, $price)); 
`

What i need is to adjust leverage also i found this solution in python but don't have an idea how to apply it in php is it the same function 

`binance.fapiPrivate_post_leverage({
    "symbol": market['id'],  # convert a unified CCXT symbol to an exchange-specific market id
    # "symbol": "BTCUSDT",  # same thing, note there's no slash in the exchange-specific id
    "leverage": 10,
marginType: 'ISOLATED',
})`

Please if you can help me figure it out 
Thanks in advance

**Comment by kroitor** [comment]
Let us know if the following example does not answer your question:

- https://github.com/ccxt/ccxt/tree/master/examples/php/binance-set-futures-leverage.php

```PHP
<?php
include 'ccxt.php';

// https://github.com/ccxt/ccxt/wiki/Manual#instantiation

date_default_timezone_set('UTC');

$exchange_id = 'binance';
$exchange_class = "\\ccxt\\$exchange_id";
$exchange = new $exchange_class(array(
    'apiKey' => 'YOUR_API_KEY',
    'secret' => 'YOUR_SECRET',
    'enableRateLimit' => true,
    'options' => array(
        'defaultType' => 'future'
    ),
));

$exchange->load_markets(); // https://github.com/ccxt/ccxt/wiki/Manual#loading-markets

// $exchange->verbose = true; // verbose mode on, uncomment for debugging

$symbol = 'BTC/USDT';

$market = $exchange->market($symbol);

// https://github.com/ccxt/ccxt/wiki/Manual#passing-parameters-to-api-methods
$params = array(
    'symbol' => $market['id'], // convert a unified CCXT symbol to an exchange-specific market id
    'leverage' => 10,
);

// https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
$response = $exchange->fapiPrivate_post_leverage($params);

print_r ($response);
```

> is it the same function 

Yes, it is the same function, you can call any endpoint using the implicit API methods as explained in the Manual here:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

I highly recommend to read the entire Manual from top to bottom, it will really save your time, most of your questions are already answered there.

- https://github.com/ccxt/ccxt/wiki
- https://github.com/ccxt/ccxt/wiki/Manual
