### ISSUE TITLE
Transaction between two exchanges.

### ISSUE THREAD

**Issue by AsadullahSoomro** [ccxt/ccxt#7579]
@kroitor 
How can I do a transaction like buy and sell from one exchange to another using CCXT, For that, I am using the bybit testnet account and BitMEX testnet account, Kindly help me
Thank You!

**Comment by AsadullahSoomro** [comment]
How to do Transactions like buying and selling between two exchanges with the help of test coins in python using ccxt Library?

**Comment by kroitor** [comment]
@AsadullahSoomro please, don't duplicate the issues, we will respond in your original issue: https://github.com/ccxt/ccxt/issues/7561
