### ISSUE TITLE
Bitmex watch orders prob using websockets

### ISSUE THREAD

**Issue by dducted** [ccxt/ccxt#7580]
Hi,

I was wondering if there is a way to watch orders, esp. Take Profits and Stop Losses on BItmex. I have seen this [issue](https://github.com/ccxt/ccxt/issues/6995) which comes probably close to what I am looking for however its not clear for me how to implement it.

Any help is appreciated. Thank you!

**Comment by kroitor** [comment]
Hi! The unified private WS API is still a work in progress, we are adding those methods right now.

Here's a full list for the moment:

<img width="729" alt="Screen Shot 2020-09-10 at 17 53 56" src="https://user-images.githubusercontent.com/1294454/92749372-b8d39100-f38e-11ea-8c1a-7460f83f0fa6.png">

↑ We have already implemented private `watchMyTrades` for BitMEX, `watchOrders` is coming within a week or so.

Hope that answers your question, let us know if not. Feel free to reopen this issue or just ask further questions if any.

**Comment by dducted** [comment]
Thanks for your prompt response, kroitor. `watchMyTrades` is what I am looking for. Do you have by any chance an example? I do know its work in progress as you mentioned but maybe you have an example? Would be interested in python. 

Thank you!

**Comment by kroitor** [comment]
@dducted 

> Do you have by any chance an example?

```Python
  # -*- coding: utf-8 -*-

from asyncio import get_event_loop
import ccxtpro


async def watch_my_trades(exchange, symbol):
    while True:
        try:
            trades = await exchange.watch_my_trades(symbol, since=timestamp)
            print('--------------------------------------------------------------')
            print('Cached', len(trades), 'last trades')
        except Exception as e:
            print(type(e).__name__, str(e))
            # break  # or retry?


async def main(loop):
    exchange = ccxtpro.bitmex({
        'enableRateLimit': True,
        'asyncio_loop':loop,
        'apiKey': 'YOUR_API_KEY',
        'secret': 'YOUR_SECRET',
    })
    await watch_my_trades(exchange, 'BTC/USDT')
    await exchange.close()


if __name__ == '__main__':
    loop = get_event_loop()
    loop.run_until_complete(main(loop))
```

Let me know if that does not help.

**Comment by bitog** [comment]
Thanks for the snippet. Works!

Maybe you could give me an advice on my current setup. I have a few different sets of API keys strored in a DB. Right now when running the code it will connect to the DBs first row, only and will fetch the websockets. The accounts below that are being ignored. I assume Id have to set up a thread for each account to be able to fetch all them live via webhooks? Is that correct or do you have another idea how I could archive that?

Thanks again for your help!
