### ISSUE TITLE
Test placing order

### ISSUE THREAD

**Issue by bitog** [ccxt/ccxt#7582]
Hi,

I was trying to test placing an order (on bitmex) using:

```
params = {
    'test': True,  # test if it's valid, but don't actually place it
}
```

I wasn't able to find anything better and it also seem to didn't work. Is there a way of testing an order placement on Bitmex?

Thank you very much!

**Comment by kroitor** [comment]
@bitog hi! All exchanges do it differently, so it's hard to fully unify this aspect. Some exchanges allow you to submit a flag to test order placement. Other exchanges have sandboxes/testnets, basically the same thing as a real exchange, except that all money is virtual. In case of BitMEX you want to switch to a testnet, this is done like so:

```Python
import ccxt

exchange = ccxt.bitmex({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})

exchange.set_sandbox_mode(True)

order = exchange.create_order(symbol, type, side, amount, price)
```

Hope that answers your question, let us know if not.
