### ISSUE TITLE
Question huobiapi PHP Sapi /cross-margin/orders/{order-id}/repay

### ISSUE THREAD

**Issue by StasToken** [ccxt/ccxt#7589]
- OS: Ubuntu 19.04
- Programming Language version: php 7.3
- CCXT version: 1.33.40

Question on the use of SAPI

[According to this documentation](https://huobiapi.github.io/docs/spot/v1/en/#request-a-margin-loan-2)
When sending a request I should call the method like this:
`POST https://api.huobi.pro/v1/cross-margin/orders`

`$request = [
            'currency' => $coin,
            'amount' => $amount
        ];
        $data = $this->drive->privatePostCrossMarginOrders($request);`

This is clear to me... [but how can](https://huobiapi.github.io/docs/spot/v1/en/#repay-margin-loan-2) I call the method here? when is there a variable in the link?

`POST https://api.huobi.pro/v1/cross-margin/orders/{order-id}/repay`

How should I call the API method? when is a variable in the address?
`$this->drive->privatePostCrossMargin?????????????????Repay`

**Comment by kroitor** [comment]
Hi! We will update Huobi's endpoint definitions asap and will get back to you with an example.

**Comment by StasToken** [comment]
Thank you looking forward to it!

**Comment by StasToken** [comment]
@kroitor - Can I find out how long it will take? it's just that if it takes many months I'll figure something out with crutches until it's fixed.

**Comment by kroitor** [comment]
@StasToken I hope to get it done before the end of this week.

**Comment by kroitor** [comment]
@StasToken

> This is clear to me... but how can I call the method here? when is there a variable in the link?

It goes into params and it gets substituted in the URL/query.
With CCXT 1.34.39+ you can now do the following:

```PHP
$this->drive->privatePostCrossMarginOrdersIdRepay(array(
    'currency' => $coin,
    'amount' => $amount,
    'id' => $orderId,
));
```

Let us know if that does not solve the issue for you.

**Comment by StasToken** [comment]
@kroitor - Many thanks!
