### ISSUE TITLE
Luno does not implement limits or precision and this prevents trades

### ISSUE THREAD

**Issue by WilhelmErasmus** [ccxt/ccxt#759]
I am using gekko(https://github.com/askmike/gekko/pull/1365) and trades are prevented from occuring by this. Possibly by implementing a standard limit of 0 if an exchange does not define its own limit.

**Comment by kroitor** [comment]
Thanks for reporting! Will look into it asap.

**Comment by kroitor** [comment]
Unfortunately, Luno does not have any means or docs on precisions and limits yet. We pass the incoming args to it as is. So, you're free to choose whatever limit for your values you want. We will keep an eye on their docs and will update accordingly. Closing it for now, if you don't mind.
