### ISSUE TITLE
Get URL of some order or private query 

### ISSUE THREAD

**Issue by bashman** [ccxt/ccxt#7602]
Greetings. 

Given symbol, amounts, api keys... It is possible to get the signed URL from ccxt?, for example I want to use the layer of signature and composition of the url, with the parameters, and get complete url string. 

I am language agnostic, but i can work in python or php.

**Comment by frosty00** [comment]
yes, you can overwrite fetch as so - 


```
def wrapper(func):
    def inner(url, *args):
        print(url)
        return func(url, *args)
    return inner

exchange = ccxt.binance()
exchange.fetch = wrapper(exchange.fetch)
exchange.fetch_order_book('ETH/BTC')
# make any request here
```
