### ISSUE TITLE
Binance Futures - Get deposit/withdraw/transaction hisotry

### ISSUE THREAD

**Issue by charlesedwards** [ccxt/ccxt#7605]
Unable to pull data per the above on Futures testnet, and get following error:
```
ccxt.base.errors.NotSupported: binance does not have a testnet/sandbox URL for wapi endpoints
```

Is this just because it is testnet?  Should the ```exchange.fetch_deposits() ``` command work for a live account?

Thanks!

**Comment by kroitor** [comment]
> Is this just because it is testnet? Should the exchange.fetch_deposits() command work for a live account?

Yes. It works for me with a live account. Let me know if that does not answer the question.

**Comment by charlesedwards** [comment]
When will it be functional on testnet?

Thanks

Igor Kroitor <notifications@github.com> schrieb am Do., 17. Sep. 2020,
10:49 nachm.:

**Comment by kroitor** [comment]
@charlesedwards 

> When will it be functional on testnet?

As soon as Binance adds it, you might want to forward this question to the Binance's tech support.
