### ISSUE TITLE
phemex all of a sudden broken - python - load_markets

### ISSUE THREAD

**Issue by adamrg73** [ccxt/ccxt#7608]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Ubuntu 18.04
- Programming Language version: Python 3.6.9
- CCXT version: CCXT Version: 1.34.7

```
Traceback (most recent call last):
  File "ccxt_test_7.py", line 115, in <module>
    phemex_markets = phemex.load_markets()
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 1326, in load_markets
    markets = self.fetch_markets(params)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/phemex.py", line 650, in fetch_markets
    market = self.parse_swap_market(market)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/phemex.py", line 394, in parse_swap_market
    maker = self.from_en(makerFeeRateEr, ratioScale, 0.00000001)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/phemex.py", line 804, in from_en
    return float(self.decimal_to_precision(en * math.pow(10, -scale), ROUND, precision, precisionMode))
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

**Comment by kroitor** [comment]
Please, update to the most recent version, this issue has been addressed recently. Let us know if you have further difficulties with it after upgrading.

**Comment by adamrg73** [comment]
will do thx again

**Comment by adamrg73** [comment]
hi this worked:
pip3 install ccxt==1.34.38

and my script is working again.
thanks, is this going to happen often though? just wondering what happened, is phemex updating their api often ?

**Comment by kroitor** [comment]
> thanks, is this going to happen often though? just wondering what happened, is phemex updating their api often ?

Nope, it is not expected to happen too often, but as you've noticed it can happen occasionally.
