### ISSUE TITLE
CoinEx adding $limit to API publicGetMarketKline

### ISSUE THREAD

**Issue by jacobbdavis1991** [ccxt/ccxt#7609]
Hello! In using CoinEx fetchOHLCV it defaults to 100, I have found that if you add this on line 391 in coinex.php

        //Adds Limit into CoinEx - Max 1000 per their Documentation
        if ($limit > 1000) {
            $request['limit'] = 1000;
        } else {
            $request['limit'] = $limit;
        }

This allows you to add a limit in the call up to 1000. Hope this helps implement in the release!

**Comment by kroitor** [comment]
@jacobbdavis1991 thx! Please, update to CCXT 1.34.38+ and use the `limit` pagination param to pass the value you need: https://github.com/ccxt/ccxt/wiki/Manual#pagination. Thx for reporting!
