### ISSUE TITLE
Binance: Timestamp for this request is outside of the recvWindow

### ISSUE THREAD

**Issue by nucwzq** [ccxt/ccxt#761]
ccxt.base.errors.ExchangeNotAvailable: binance GET https://api.binance.com/api/v3/account?timestamp=1512541759554&signature=3ba4ae0ff09589889c60082902f0bae89f45920d0fb764670c65ef6fa4ea9751 400 Bad Request  {"code":-1021,"msg":"Timestamp for this request is outside of the recvWindow."}

the error is derived from the follow code:

bina.fetch_balance()

**Comment by kroitor** [comment]
What's your system time? Is it in sync with global UTC time?

**Comment by kroitor** [comment]
http://currentmillis.com/

**Comment by nucwzq** [comment]
It seems the local time, and I test the following code:

print time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(time.time()))

the output is: 2017-12-06 14:39:09

**Comment by kroitor** [comment]
Do this:

```Python
import ccxt
exchange = ccxt.binance()
exchange_time = exchange.public_get_time()['serverTime']
your_time = exchange.milliseconds()
print('Exchange time:', exchange_time, exchange.iso8601(exchange_time))
print('Your time:', your_time, exchange.iso8601(your_time))
```

**Comment by nucwzq** [comment]
It is working!!! Thanks!!!!!!!!!!!!!!

**Comment by kroitor** [comment]
@nucwzq did you change your system time to fix it?

**Comment by nucwzq** [comment]
That I can't remember...

**Comment by kroitor** [comment]
@nucwzq I mean just now, did you change your time to make it work?

**Comment by nucwzq** [comment]
@kroitor yes, I run your above-mentioned code and the sys time is changed now.

**Comment by kroitor** [comment]
Ok, thanks for reporting back! Cheers!

**Comment by nucwzq** [comment]
@kroitor it's coooollll, thanks!!!

**Comment by Evandar276** [comment]
If your server is running on Linux, just execute this script - it will update system time

`sudo date -s "$(wget -qSO- --max-redirect=0 google.com 2>&1 | grep Date: | cut -d' ' -f5-8)Z"`

Binance API should run instantly after this.

**Comment by kroitor** [comment]
@Evandar276 thanks for this hint as well! Noe, however, that system clock can actually go out of synch pretty quickly, in less than 15 minutes. So this command has to be run frequently enough, or it can be substituted for a time-synchronizing daemon like nptd or whatever. My 2 cents.

**Comment by kroitor** [comment]
More about it:
- https://github.com/ccxt/ccxt/issues/936
- https://github.com/ccxt/ccxt/issues/850

**Comment by Evandar276** [comment]
I had this problem on server which is running several years :) It was two minutes back, but I agree, I will install nptd to automate this.

**Comment by jorijnsmit** [comment]
My MacBook 2015 does this too much! Time will lag behind like 15 seconds every couple of weeks. Apparently this could be due to the suspend function... I find it odd that it doesn't get fixed automatically because I have auto time sync enabled in my macOS settings.

Anyway `ntpdate` did the trick for me:
```
sudo ntpdate -vu time.apple.com
27 Apr 13:58:00 ntpdate[8708]: ntpdate 4.2.8p10@1.3728-o Tue Mar 21 14:36:42 UTC 2017 (136~2590)
27 Apr 13:58:21 ntpdate[8708]: step time server 17.253.52.125 offset 14.300642 sec
```

**Comment by kroitor** [comment]
@Evandar276 , @jorijnsmit thanks for the follow-up!

**Comment by avatar-lavventura** [comment]
> My MacBook 2015 does this too much! Time will lag behind like 15 seconds every couple of weeks. Apparently this could be due to the suspend function... I find it odd that it doesn't get fixed automatically because I have auto time sync enabled in my macOS settings.
> 
> Anyway `ntpdate` did the trick for me:
> 
> ```
> sudo ntpdate -vu time.apple.com
> 27 Apr 13:58:00 ntpdate[8708]: ntpdate 4.2.8p10@1.3728-o Tue Mar 21 14:36:42 UTC 2017 (136~2590)
> 27 Apr 13:58:21 ntpdate[8708]: step time server 17.253.52.125 offset 14.300642 sec
> ```

Should we do `sudo ntpdate -vu time.apple.com` each time we are running `ccxt`? or single time would be enough?

**Comment by kroitor** [comment]
@avatar-lavventura you can set up regular timesync or enable the `adjustForTimeDifference` option: https://github.com/ccxt/ccxt/issues/936#issuecomment-373222292 CCXT does not have much to do with it, it's a requirement of the exchanges to make sure your time is in sync.

**Comment by avatar-lavventura** [comment]
@kroitor I have a digital-ocean VM that is deployed in Singapore, I believe that's why I am having timesync issue.


I have the following recommended setup, but still I was having the same proble.:

```
exchange = ccxt.binance({
    "options": {"default_type": "futures",  "adjustForTimeDifference": True},
     "enableRateLimit": True,  
})
```
--------

- I ran your solution as: ```sudo ntpdate -vu time.apple.com```
```
$./time.py  # seems like its times are pretty close.
Exchange UTC time: 1624813330330 None
Your____ UTC time: 1624813330374 2021-06-27T17:02:10.374Z
```

In addition to that, to be bullet proof should I do following: like your linked comment, please note that I am in Python:

```
exchange.fetch_ticker(symbol, {'recvWindow': 10000000})
```

**Comment by kroitor** [comment]
> I have the following recommended setup, but still I was having the same proble.:
> 
> ```
> exchange = ccxt.binance({
>     "options": {"default_type": "futures",  "adjustForTimeDifference": True},
>      "enableRateLimit": True,  
> })
> ```

That is wrong, there's no `default_type` option, it's called `defaultType` and the value for it is `future` instead of `futures`. If your version of ccxt is up to date (1.52+) i suggest the following instantiation code:

```Python
exchange = ccxt.binanceusdm({'options': {'adustForTimeDifference': True}})
```



> In addition to that, to be bullet proof should I do following: like your linked comment, please note that I am in Python:
> 
> ```
> exchange.fetch_ticker(symbol, {'recvWindow': 10000000})
> ```

No, you should not do that if your time is in sync.

**Comment by avatar-lavventura** [comment]
@kroitor Thanks. I was way behind in `cctx` version, updated as you guided.

Small question,  `exchange = ccxt.binanceusdm({'options': {'adustForTimeDifference': True}})` misses the ```"enableRateLimit": True``` parameter, is it recommended to add it as well if we are checking every 10 milliseconds.

like:

```
exchange = ccxt.binanceusdm({'options': {'adustForTimeDifference': True}, "enableRateLimit": True})
```

**Comment by kroitor** [comment]
@avatar-lavventura 

> misses the "enableRateLimit": True parameter, is it recommended to add it as well if we are checking every 10 milliseconds.

It is enabled by default in the most recent versions, so you don't have to enable the rate limiter explicitly.

**Comment by avatar-lavventura** [comment]
The way was able to solve it:

```bash
$ sudo apt install systemd-timesyncd
$ sudo timedatectl set-timezone UTC
$ sudo systemctl restart systemd-timesyncd.service
$ systemctl status systemd-timesyncd
● systemd-timesyncd.service - Network Time Synchronization
     Loaded: loaded (/lib/systemd/system/systemd-timesyncd.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2021-09-27 16:48:53 UTC; 1h 16min ago
       Docs: man:systemd-timesyncd.service(8)
   Main PID: 1279481 (systemd-timesyn)
     Status: "Initial synchronization to time server 169.254.169.254:123 (169.254.169.254)."
      Tasks: 2 (limit: 19203)
     Memory: 1.4M
     CGroup: /system.slice/systemd-timesyncd.service
             └─1279481 /lib/systemd/systemd-timesyncd
```

-----

Or adding following line into `crontab -e` : 

```
*/15 * * * * /path/to/your/script.sh
```

Where `/path/to/your/script.sh` contains line from https://github.com/ccxt/ccxt/issues/761#issuecomment-355839537, which will be run every 15 minutes like @kroitor suggested.

**Comment by kroitor** [comment]
@avatar-lavventura thx for your feedback!
