### ISSUE TITLE
BitMax AUTHENTICATION_FAILED: Request data isn't value: x-auth-key

### ISSUE THREAD

**Issue by c0dehunter** [ccxt/ccxt#7612]
- OS: Linux
- Programming Language version: PHP 7.3
- CCXT version: 1.33.50

```
$id = "\\ccxt\\bitmax";
$exchange = new $id();
$exchange->apiKey = "u38rGIkpr3gcAYa1AH9chfHqTh2QFHgZ"; // testing API key
$exchange->secret= "RX46TNuEiAyIzBgiCFSnAuswzpsUNFo2Fg7n3TUJmWFRG5QLDAaaB4CuAmG36f5s";
$exchange->enableRateLimit = true;

for($balance : $exchange->fetchBalance()) {
	...
}
```

Error:

```
[Authentication] bitmax {\"code\":200001,\"message\":\"Request data isn't value:
x-auth-key\",\"reason\":\"AUTHENTICATION_FAILED\"}
```

**Comment by kroitor** [comment]
@c0dehunter is it an old API key? Does that happen if you re-create a new key pair on the exchange’s website? They have recently updated their API, so, old keys might stop working. Let us know if you have the same issue with a new keypair.

**Comment by c0dehunter** [comment]
No, it's just freshly made key.

**Comment by kroitor** [comment]
@c0dehunter thx for reporting, fixed the bug in PHP. Please, update to 1.34.41 in 15 minutes and let us know if the issue is resolved or if you still have the same difficulties with it. I've tested it on my side and it should work properly now. Thx again!

**Comment by c0dehunter** [comment]
@kroitor  All thanks to you for the quick fix!
