### ISSUE TITLE
Phemex sandbox mode doesnt work

### ISSUE THREAD

**Issue by adamrg73** [ccxt/ccxt#7618]
I couldnt get any exchange sandbox mode to work, and Id like to get phemex working if possible rather than testing with real money.
API signature failed

**Comment by kroitor** [comment]
@adamrg73 do you use the production apiKey with the testnet/sandbox?

**Comment by kroitor** [comment]
Phemex's testnet requires a pair of sandbox keys, you can create them here: https://testnet.phemex.com
Let us know if that does not answer your question.

**Comment by adamrg73** [comment]
Hi, I while back when was trying sandbox mode Im pretty sure I did this. Also want to note that I wasnt able to get sandbox on many exchanges I tried with ccxt.  Also I wanted to note on here I had someone on the @Phemex_API telegram channel tell me that the keys need to be all lowercase to work. I havent tried it yet. Just wanted to contribute this here.
When I try it I will post back
thanks again
cheers
