### ISSUE TITLE
How to do a limit fill or kill order with phemex exchange?

### ISSUE THREAD

**Issue by adamrg73** [ccxt/ccxt#7620]
Hi how do you do a limit order but fill or kill setting with phemex exchange?
thanks

**Comment by adamrg73** [comment]
Hi any news on this, I see it in the python source, but its commented out.. Im assuming maybe its not implemented yet?

**Comment by kroitor** [comment]
@adamrg73 hi! Pardon for the delay with the answer on this. Basically, it is supported from the very beginning.
Whenever you see a commented-out param in the code, that means you can use params overrides to add those specific fields to your unified `create_order` call as documented in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

```Python
params = {
    'timeInForce': 'FillOrKill', 
}
exchange.create_order(symbol, type, side, amount, price, params)
```

Let us know if that does not answer your question.

**Comment by adamrg73** [comment]
`params = {
                    'timeInForce': 'FillOrKill',
                    }
            r1=exchange.create_order(coin1['symbol'], 'limit', 'buy', amount_c1, coin1['ask'], params)
            print(r1)`

I'm getting 
Exception found  kucoin BadRequest kucoin Time in Force parameter invalid.

**Comment by adamrg73** [comment]
I think
'FOK'
is working, gona test with proper order size.
