### ISSUE TITLE
New exchange: tradesatoshi.com

### ISSUE THREAD

**Issue by mazertwo** [ccxt/ccxt#763]
Hi!

Can you add tradesatoshi.com?

API: https://github.com/WorldBot/Trade-Satoshi-API/blob/master/api_tradesatoshi.php

**Comment by kroitor** [comment]
I mostly have their public API ready, working on the private part now. If anyone would like to offer help with this, let me know, I'll upload it. Thanks!

**Comment by denniswong34** [comment]
@kroitor Could you upload it?? i'm interested in it.

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/pull/1781

**Comment by crackfoo** [comment]
Is there a php version of this available yet?

Thanks!

**Comment by kroitor** [comment]
@crackfoo the PHP version is generated automatically from JS code: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support

**Comment by crackfoo** [comment]
oh ok, thanks! I'll check out #1781

**Comment by crackfoo** [comment]
Seems the tradesatoshi.js file has the urls for bittrex api... 

[error] [exception.ccxt\ExchangeNotAvailable] ccxt\ExchangeNotAvailable: tradesatoshi GET https://bittrex.com/api/*/public/getcurrencies 400 Bad Request

https://github.com/ccxt/ccxt/commit/90d9d19ceb8835f8a0127e77fc9e25daafd96808#diff-b08509f138bb00fdbeef27b06527ca1eR52

**Comment by kroitor** [comment]
Yeah, sorry, it is in a very early stage, therefore not merged yet. Pardon for the confusion.

**Comment by crackfoo** [comment]
gotcha, thanks no worries

**Comment by crackfoo** [comment]
Still poking away at this one?

**Comment by crackfoo** [comment]
@kroitor this still on the to-do?

thnx

**Comment by seanspotatobusiness** [comment]
The only thing I want to do is get my trade history from Tradesatoshi but I can't figure out the authentication process. Can anyone advise what I need to read about to do produce the required POST header, preferably in Python?

**Comment by crackfoo** [comment]
@kroitor just wondering again if you've got this one done up?

**Comment by kroitor** [comment]
@crackfoo As long as this issue is open – it means that the work on it is not done yet. Hope to get to it as soon as possible, this week, hopefully. When we finish tradesatoshi, we will merge the corresponding PR #1781 and will close this issue as well.

**Comment by crackfoo** [comment]
ok thanks for your reply

**Comment by crackfoo** [comment]
@kroitor sorry to keep bugg'n ya, been able to get some progress on this?

**Comment by kroitor** [comment]
@crackfoo )) https://github.com/ccxt/ccxt/wiki/FAQ#whats-your-progress-on-adding-the-feature-foo-that-was-requested-earlier-how-do-you-do-implementing-exchange-bar
Will do it asap, after merging #2296.

**Comment by crackfoo** [comment]
Just checking if you've progressed with this exchange....

Thanks

**Comment by crypto-maniac** [comment]
up please

**Comment by crackfoo** [comment]
Is this still in your queue to push an update to @kroitor ?

**Comment by crackfoo** [comment]
> @crackfoo yes, I hope to finish it as soon as I have the time for it, your contributions and help are very welcome! )

thanks I appreciate it. I've tried to poke away at it but it ends in disaster. I'm not a developer so I don't really understand all the bits to get in place.

Cheers

**Comment by crackfoo** [comment]
@kroitor I knwo you're busy, just wonder about tradesatoshi?

**Comment by kroitor** [comment]
@crackfoo plz see the answer here: https://github.com/ccxt/ccxt/issues/5822

**Comment by An-Net** [comment]
Shutdown since 20 February 2020:

- https://twitter.com/TradeSatoshi/status/1230509341142220800

- https://cryptoiq.co/tradesatoshi-crypto-exchange-closing-down-has-all-the-signs-of-being-an-exit-scam/

- https://www.reddit.com/r/garlicoin/comments/f8ikrf/tradesatoshi_crypto_exchange_closing_down/

![Снимок экрана 2020-03-27 в 3 11 56](https://user-images.githubusercontent.com/51840849/77708422-1dfe1a80-6fd9-11ea-9030-efaaabb52c38.png)
