### ISSUE TITLE
How to trade from multiple api keys?

### ISSUE THREAD

**Issue by DeusNexus** [ccxt/ccxt#7633]
I want to know what is the best way to open a trade on multiple api keys and couldn't find any information.

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/issues/6304
- https://github.com/ccxt/ccxt/issues/5139#issuecomment-493696881

Let us know if that does not answer your question.
