### ISSUE TITLE
Binance coin-margined websocket streams in CCXT Pro

### ISSUE THREAD

**Issue by diwenshi61** [ccxt/ccxt#7636]
Binance coin-margined websocket streams are virtually the same as USDT-margined, just with a different base endpoint, and should be able to be added easily

I was able to use the streams in python by adding the endpoint in binance.py under 'delivery' (python 3.8)
```
                'api': {
                    'ws': {
                        'spot': 'wss://stream.binance.com:9443/ws',
                        'margin': 'wss://stream.binance.com:9443/ws',
                        'future': 'wss://fstream.binance.com/ws',
                        'delivery': 'wss://dstream.binance.com/ws',
                    },
                },
```
Should work the same in js and php, but I haven't tested it yet.

**Comment by kroitor** [comment]
Added in CCXT Pro 0.4.15+. Thanks for your patience!
