### ISSUE TITLE
How to place and fetch Bitfinex Exchange and Margin Stop Limit Orders correctly

### ISSUE THREAD

**Issue by Princeton007** [ccxt/ccxt#7637]
Actually I don't think this is an "issue" but for clarification if I chose the "right" args for placing Stop Limit Orders (Margin and Exchange) for Bitfinex. It took me a while to figure it out and want to know if there is a better way doing this. 

- OS: Windows & Linux
- Programming Language version: Python 3.7
- CCXT version: 1.34.59

- The Limit price will only be accepted as string - ok, no problem
- In the API documentation is is described as "price_aux_limit" but in reality I have to deliver "sell_stoplimit_price" and "buy_stoplimit_price" which is a bit confusing to me.

see: https://docs.bitfinex.com/reference#rest-auth-submit-order
price_aux_limit
string
Auxiliary Limit price (for STOP LIMIT)

Here is how it works for exchange and margin: 
```
# Margin Stop Limit
order = exchange.create_order('BTC/USD', 'limit', 'sell', amount, stop_sell_price, {'type': 'stop limit', 'sell_stoplimit_price': str(limit_sell_price)})
print(f'Order wurde platziert. {order}')

order = exchange.create_order('BTC/USD', 'limit', 'buy', amount, stop_buy_price, {'type': 'stop limit', 'buy_stoplimit_price': str(limit_buy_price)})
print(f'Order wurde platziert. {order}')

# exchange Stop Limit

order = exchange.create_order('BTC/USD', 'limit', 'sell', amount, stop_sell_price, {'type': 'exchange stop limit', 'sell_stoplimit_price': str(limit_sell_price)})
print(f'Order wurde platziert. {order}')

order = exchange.create_order('BTC/USD', 'limit', 'buy', amount, stop_buy_price, {'type': 'exchange stop limit', 'buy_stoplimit_price': str(limit_buy_price)})
print(f'Order wurde platziert. {order}')
```

So again, basically I want to understand if this is the right way, at least it is one of possible ways it works... :-)

Furthermore I have another question and this might be an issue: 
I placed a  Margin Stop Sell Order
with a 

Stop Price: 10330
Limit Price: 10350
which returns the following. I can't fee the Limit price (although it is displayed in the web GUI:

```
{'amount': 0.0006,
 'average': 0.0,
 'clientOrderId': None,
 'cost': None,
 'datetime': '2020-09-28T14:15:27.000Z',
 'fee': None,
 'filled': 0.0,
 'id': '52037031413',
 'info': {'avg_execution_price': '0.0',
          'cid': 51326520571,
          'cid_date': '2020-09-28',
          'exchange': 'bitfinex',
          'executed_amount': '0.0',
          'gid': None,
          'id': 52037031413,
          'is_cancelled': False,
          'is_hidden': False,
          'is_live': True,
          'meta': None,
          'oco_order': None,
          'original_amount': '0.0006',
          'price': '10330.0',
          'remaining_amount': '0.0006',
          'side': 'sell',
          'src': 'api',
          'symbol': 'btcusd',
          'timestamp': '1601302527.0',
          'type': 'exchange stop limit',
          'was_forced': False},
 'lastTradeTimestamp': None,
 'price': 10330.0,
 'remaining': 0.0006,
 'side': 'sell',
 'status': 'open',
 'symbol': 'BTC/USD',
 'timestamp': 1601302527000,
 'trades': None,
 'type': 'stop'}
 ```
Thanks

**Comment by doksyilji** [comment]
This issue is still open

**Comment by Princeton007** [comment]
Hi, I upgraded to latest CCXT version 2.5.29 and Margin Orders won't places anymore, they are converted to EXCHANGE instead.
exchange.create_order(symbol, 'market', 'buy', amount, None, {'stopPrice': str(stop_buy_price)}) 
returns
{'info': ['110927056354', None, '1672866867071', 'tTESTBTC:TESTUSDT', '1672866867071', '1672866867071', '0.002', '0.002', 'EXCHANGE STOP', None, None, None, '0', 'ACTIVE', None, None, '18000', '0', '0', '0', None, None, None, '0', '0', None, None, None, 'API>BFX', None, None, {}], 'id': '110927056354', 'clientOrderId': '1672866867071', 'timestamp': 1672866867071, 'datetime': '2023-01-04T21:14:27.071Z', 'lastTradeTimestamp': None, 'symbol': 'TESTBTC/TESTUSDT', 'type': 'market', 'timeInForce': 'GTC', 'postOnly': False, 'side': 'buy', 'price': None, 'stopPrice': 18000.0, 'triggerPrice': 18000.0, 'amount': 0.002, 'cost': None, 'average': None, 'filled': 0.0, 'remaining': 0.002, 'status': 'open', 'fee': None, 'trades': [], 'fees': []}

**Comment by samgermain** [comment]
> Hi, I upgraded to latest CCXT version 2.5.29 and Margin Orders won't be placed, they are converted to EXCHANGE instead.
> 
> ```python
> exchange.create_order(symbol, 'market', 'buy', amount, None, {'stopPrice': str(stop_buy_price)}) 
> ```
> 
> returns
> 
> ```python
> {'info': ['110927056354', None, '1672866867071', 'tTESTBTC:TESTUSDT', '1672866867071', '1672866867071', '0.002', '0.002', 'EXCHANGE STOP', None, None, None, '0', 'ACTIVE', None, None, '18000', '0', '0', '0', None, None, None, '0', '0', None, None, None, 'API>BFX', None, None, {}], 'id': '110927056354', 'clientOrderId': '1672866867071', 'timestamp': 1672866867071, 'datetime': '2023-01-04T21:14:27.071Z', 'lastTradeTimestamp': None, 'symbol': 'TESTBTC/TESTUSDT', 'type': 'market', 'timeInForce': 'GTC', 'postOnly': False, 'side': 'buy', 'price': None, 'stopPrice': 18000.0, 'triggerPrice': 18000.0, 'amount': 0.002, 'cost': None, 'average': None, 'filled': 0.0, 'remaining': 0.002, 'status': 'open', 'fee': None, 'trades': [], 'fees': []}
> ```

Here is an explanation of our stopLossPrice and stopLoss order schemas https://github.com/ccxt/ccxt/issues/13822

**Comment by ttodua** [comment]
to execute order on bitfinex margin markets, you just add `marginMode` param:
```
result = await ex.create_order('BTC/USDT', 'limit', 'buy', 0.3, 55000, {'marginMode': 'cross'});
```
