### ISSUE TITLE
Phemex - position status - python - always reading zero for unrealized pnl

### ISSUE THREAD

**Issue by adamrg73** [ccxt/ccxt#7639]
{'accountID': IBLANKEDTHISFORGITHUB, 'symbol': 'ETHUSD', 'currency': 'USD', 'side': 'Sell', 'positionStatus': 'Normal', 'crossMargin': False, 'leverageEr': 2000000000, 'leverage': 20.0, 'initMarginReqEr': 5000000, 'initMarginReq': 0.05, 'maintMarginReqEr': 1000000, 'maintMarginReq': 0.01, 'riskLimitEv': 5000000000, 'riskLimit': 500000.0, 'size': 4, 'value': 7.245, 'valueEv': 72450, 'avgEntryPriceEp': 3622500, 'avgEntryPrice': 362.25, 'posCostEv': 3680, 'posCost': 0.368, 'assignedPosBalanceEv': 3689, 'assignedPosBalance': 0.3689, 'bankruptCommEv': 58, 'bankruptComm': 0.0058, 'bankruptPriceEp': 3804000, 'bankruptPrice': 380.4, 'positionMarginEv': 3631, 'positionMargin': 0.3631, 'liquidationPriceEp': 3767500, 'liquidationPrice': 376.75, 'deleveragePercentileEr': 0, 'deleveragePercentile': 0.0, 'buyValueToCostEr': 5146250, 'buyValueToCost': 0.0514625, 'sellValueToCostEr': 5153750, 'sellValueToCost': 0.0515375, 'markPriceEp': 3622975, 'markPrice': 362.2975, 'markValueEv': 0, 'markValue': None, 'unRealisedPosLossEv': 0, 'unRealisedPosLoss': None, 'estimatedOrdLossEv': 0, 'estimatedOrdLoss': 0.0, 'usedBalanceEv': 3689, 'usedBalance': 0.3689, 'takeProfitEp': 0, 'takeProfit': None, 'stopLossEp': 0, 'stopLoss': None, 'cumClosedPnlEv': -106, 'cumFundingFeeEv': 13, 'cumTransactFeeEv': 4067, 'realisedPnlEv': 0, 'realisedPnl': None, 'cumRealisedPnlEv': 0, 'cumRealisedPnl': None}

**Comment by kroitor** [comment]
@adamrg73 if you're 100% sure that the value must be be different, then you may want to forward this message to the Phemex tech support directly, since what you see above is what you get from the exchange first-hand (CCXT does not transform that info). We will also report this to them and will post back here our findings.

**Comment by adamrg73** [comment]
what exchanges do you recommend that work best like all these paramaters with ccxt, less than 0 or 0 limit order(maker) fees, and no KYC check so I can get up and running asap..
thanks again

**Comment by kroitor** [comment]
@adamrg73 let me know if this example does not answer your question:

- https://github.com/ccxt/ccxt/blob/master/examples/py/async-market-making-symbols.py

```Python
# -*- coding: utf-8 -*-

from asyncio import gather, get_event_loop
from pprint import pprint
import ccxt.async_support as ccxt


async def load_markets(exchange):
    results = None
    try:
        await exchange.load_markets()
        print('Loaded', len(exchange.symbols), exchange.id, 'symbols')
        results = []
        for market in exchange.markets.values():
            if market['maker'] <= 0:
                results.append({'exchange': exchange.id, 'symbol': market['symbol']})
        if len(results) < 1:
            results = None
    except:
        results = None
    await exchange.close()
    return results


async def main(loop):
    config = {'enableRateLimit': True, 'asyncio_loop': loop}
    exchanges = [getattr(ccxt, exchange_id)(config) for exchange_id in ccxt.exchanges]
    # exchanges = [exchange for exchange in exchanges if exchange.certified]
    results = await gather(*[load_markets(exchange) for exchange in exchanges])
    results = [result for result in results if result is not None]
    return results


if __name__ == '__main__':
    loop = get_event_loop()
    pprint(loop.run_until_complete(main(loop)))
```

**Comment by adamrg73** [comment]
I will try this this afternoon..thx. i have another question i will post in another thread that is priority. thx again.

**Comment by adamrg73** [comment]
Ya that code was good.. lykke is the only exchange that has a good amount of symbols for taker fees 0%, and im going to test more but maker orders on phemex seem to be taking too long to fill..

**Comment by docek** [comment]
Phemex does not provide unrealized PnL over API. From their API documentation:
---------------------
Note unRealizedPnlEv needs to be calculated in client side with latest markPrice, formula is as below.

Inverse contract: unRealizedPnl = (posSize/contractSize)/avgEntryPrice - (posSize/contractSize)/markPrice)

Linear contract:  unRealizedPnl = (posSize/contractSize) * markPrice - (posSize/contractSize)/avgEntryPrice

posSize is a signed vaule. contractSize is a fixed value.
----------------------
https://github.com/phemex/phemex-api-docs/blob/master/Public-Contract-API-en.md

**Comment by kroitor** [comment]
@docek thanks for your feedback!
@adamrg73 let us know if that does not answer your question.

**Comment by adamrg73** [comment]
can we implement this REST link to get the unrealized pnl

<img width="1072" alt="Screen Shot 2021-01-17 at 12 16 37 PM" src="https://user-images.githubusercontent.com/70821026/104850618-1be5af00-58be-11eb-9b24-e1733aad855f.png">
<img width="1066" alt="Screen Shot 2021-01-17 at 12 16 29 PM" src="https://user-images.githubusercontent.com/70821026/104850621-1e480900-58be-11eb-90c8-986abd181ad9.png">

**Comment by kroitor** [comment]
@adamrg73 

> can we implement this REST link to get the unrealized pnl

All endpoints are already included in CCXT, use [unified `fetchPositions`](https://github.com/ccxt/ccxt/wiki/Manual#using-fetchpositions) or [implicit API methods](https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods)

**Comment by docek** [comment]
Be aware that the implicit API call privateGetAccountsAccountPositions (used in fetchPositions) does not give up to date markPrice. Current markPrice need to be fetched separatly using fetchTicker().
