### ISSUE TITLE
Bybit: Wrong Currency for trade fee in case of linear perpetuals

### ISSUE THREAD

**Issue by scoriiu** [ccxt/ccxt#7641]
- OS: OSX
- Programming Language version: Python
- CCXT version: '1.34.54'
- Symbol: BTCUSDT
- Exchange: Bybit

ccxt.fetch_my_trades sets the currency to base currency for fee in case of the linear perpetual trades:

Here is the code snippet in CCXT that does this:
```
def parse_trade(self, trade, market=None):
        ...
        if feeCost is not None:
            fee = {
                'cost': feeCost,
                'currency': base,
                'rate': self.safe_float(trade, 'fee_rate'),
            }
```
Output:
`{'cost': 0.0733995, 'currency': 'BTC', 'rate': 0.00075}`

Expected currency 'USDT'

**Comment by scoriiu** [comment]
<img width="753" alt="Screenshot 2020-09-29 at 11 08 45" src="https://user-images.githubusercontent.com/32566135/94530704-26633680-0244-11eb-8ecf-542cbecddcce.png">

@kroitor Also another one which is more important. The trade price is not the exec_price, but the order creation price.

**Comment by scoriiu** [comment]
@kroitor Any updates on this?

**Comment by kroitor** [comment]
@scoriiu pardon for the delay, will fix it shortly, thx for your patience and for the feedback!

**Comment by scoriiu** [comment]
No problem. Will you also fix the issue with the exec price of the trade?

**Comment by kroitor** [comment]
@scoriiu yep, will fix both and will ping you back here when it's done.
