### ISSUE TITLE
Phemex limit order post only - ensuring market maker - incentive fees - how to

### ISSUE THREAD

**Issue by adamrg73** [ccxt/ccxt#7644]
How to I mark this as question..?

ok...so i was just on support with phemex, and theyre saying to ensure that the limit orders are market maker and go into the order book, to make sure the fees are market maker fees which is -0.025 bonus incentive, I have to check off the Postonly on the user interface..but I need to do this with my bot, so how can I do this with ccxt? or do i need to use their api directly?

see screenshot

<img width="338" alt="Screen Shot 2020-09-29 at 3 55 53 PM" src="https://user-images.githubusercontent.com/70821026/94609068-558d9e00-026c-11eb-87fc-9053bcb1363e.png">

**Comment by kroitor** [comment]
> or do i need to use their api directly?

With CCXT you are already using their API directly. CCXT includes all endpoints and supports all params.
All you want to do is to add a parameter override to your `create_order` call:

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

```Python
import ccxt
exchange = ccxt.phemex({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})

params = {
    'timeInForce': 'PostOnly'
}
exchange.create_order(symbol, type, side, amount, price, params)
```

Let me know if that does not answer your question.

**Comment by kroitor** [comment]
P.S. Find all possible params here: 

- https://github.com/phemex/phemex-api-docs/blob/master/Public-Spot-API-en.md#place-order
- https://github.com/phemex/phemex-api-docs/blob/master/Public-Contract-API-en.md#placeorder
