### ISSUE TITLE
[exmo] possible incorrect order status

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#7670]
I'm getting exmo orders with a closed status that are still open.  I can't track the true cause down, but I suspect it might be something to do with the cache.  Is it possible to remove/disable order caching? It doesn't work in my environment at all because I have a distributed system (not every instance of ccxt will see every order).

**Comment by kroitor** [comment]
Related: https://github.com/ccxt/ccxt/issues/7287
