### ISSUE TITLE
AttributeError: 'huobipro' object has no attribute 'purge_cached_orders'

### ISSUE THREAD

**Issue by jaseisen105** [ccxt/ccxt#7681]
I recently upgraded from `ccxt==1.26.54 ccxtpro==0.1.73` and am now getting this error.  Was the functionality removed?

- OS: ubuntu 16
- Programming Language version: python 3.6
- CCXT version: `ccxt=1.35.2 pro==0.3.88`

```
c = ccxtpro.huobipro()
c.purge_cached_orders(c.milliseconds())
```

```
AttributeError: 'huobipro' object has no attribute 'purge_cached_orders'
```

**Comment by kroitor** [comment]
@jaseisen105 yes, the old order cache is replaced with a better caching mechanism in CCXT Pro, which purges itself automatically keeping its size below `exchange.options['ordersLimit']`.

Let us know if that does not answer your question.

**Comment by marcoismobile** [comment]
@kroitor Just to be sure..
The old 'purge_cached_orders' is removed from CCXT and replaced by the `exchange.options['ordersLimit']` option in CCXP **Pro** only? Or is the 'ordersLimit' option also working in the **normal** version of CCXT? Or is the complete functionality removed from the normal CCXT version?

**Comment by kroitor** [comment]
@marcoismobile the order cache will be removed from the base version of CCXT, and will be detached to a standalone plugin/adapter along with the purge functionality for those who need it.
