### ISSUE TITLE
How can I get historical ohlcv data of binance and okex as many as possible?

### ISSUE THREAD

**Issue by chaconne67** [ccxt/ccxt#7688]
Hi~ I am using ccxt and ccxtpro. How can I get ohlcv data of binance and okex as many as possible?
Could you give me sample code please? I

**Comment by kroitor** [comment]
@chaconne67 hi! Which symbols do you need?

**Comment by chaconne67** [comment]
BTC/USDT and 1min fists. can I change params?

**Comment by kroitor** [comment]
> can I change params?

Yes, have you read the Manual? If you're new to CCXT I'd highly recommend to read the entire CCXT Manual from top to bottom, the `fetchOHLCV` method for historical OHLCVs is explained there as well.

- https://github.com/ccxt/ccxt/wiki
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-candlestick-charts
- https://github.com/ccxt/ccxt/wiki/Manual#pagination

You can also find the examples here:

- https://github.com/ccxt/ccxt/tree/master/examples/

Which programming language do you use?

**Comment by kroitor** [comment]
@chaconne67 

> - BTC/USDT and 1min firsts.

It can be done in a million of ways, for example:

https://github.com/ccxt/ccxt/issues/6871#issuecomment-626130973
https://github.com/ccxt/ccxt/blob/master/examples/py/fetch-all-okex-ohclv.py

**Comment by kroitor** [comment]
Binance: https://github.com/ccxt/ccxt/blob/master/examples/py/binance-fetch-ohlcv-to-csv.py

**Comment by kroitor** [comment]
Let us know if the above examples do not answer your question.
