### ISSUE TITLE
Proxy security

### ISSUE THREAD

**Issue by 4nzor** [ccxt/ccxt#7692]
Hello, we have a need to use private https proxies to avoid rate limits, is it possible that the proxy server owner can intercept the API keys?

**Comment by frosty00** [comment]
I don't believe so, since the secret key is never send over http, just a signature derived from it

**Comment by kroitor** [comment]
@4nzor 

- There are exchanges who rely on the security of the underlying HTTPS encryption, by their API design only the apiKey is required and it is sent over HTTPS in the open. There's maybe a few of those exchanges. Sending sensitive info to those exchanges over an unreliable proxy is not recommended.
- The majority of the exchanges require apiKey (also sent in the open) and secret (not sent through), so, even if the underlying HTTPS security fails, knowing the apiKey is not enough to do any damage. Each request has to be signed with the secret part that is kept on the client side and never sent over the internet.

If you instantiate a CCXT exchange, you can check the `exchange.requiredCredentials` property to see whether it's a single apiKey or a pair of apiKey+secret. Some exchanges require 3 or 4 pieces of credentials for the authentication, but those are also rare.

Let us know if the above does not answer your question.
