### ISSUE TITLE
Trade simulation

### ISSUE THREAD

**Issue by orkenstein** [ccxt/ccxt#770]
Are there any platform, that provide trade simulation?

**Comment by kroitor** [comment]
Don't know if there's a package in JS, but I know of backtrader.com (they integrate CCXT: https://community.backtrader.com/topic/623/anyone-use-backtrader-to-do-live-trading-on-bitcoin-exchange/32). To me this whole task boils down to data aggregation (in a scalable way).
However, it depends pretty much on what type of simulation you want, whether it is paper trading on live feeds or backtesting with historical data...

**Comment by orkenstein** [comment]
@kroitor Paper trading on live feeds with something more "real", then just random sell/buy orders execution.

**Comment by kroitor** [comment]
@orkenstein there's no readily available solution. For that you will need Machine Learning to make trading decisions (you should think scalable: cloud computing, management, paying for all of this), and you will need both live feeds and historical feeds for training your neural networks. I don't know of an existing end-user solution to this. I guess, you will have to make it.

**Comment by orkenstein** [comment]
Any good sources of historical data? 
This [one](https://bitinfocharts.com/markets/livecoin/ltc-btc-all.html) is really cool, but no trace of API.
I'd like to have detailed exchange-specific history for multiple pairs.
Thanks

**Comment by kroitor** [comment]
@orkenstein i'd like to have that too! I guess, thousands of people would like that as well, so, if you come up with a solution to this, you're going to make yourself a fortune. Check this out: https://coinigy.com

**Comment by orkenstein** [comment]
@kroitor sweet pricing :D

**Comment by kroitor** [comment]
Would you mind if I close this? Let us know if you still have any questions )

**Comment by orkenstein** [comment]
@kroitor, sure, enough for now.
Lemme know if something else shows up.
Thanks in advance.
