### ISSUE TITLE
When I try to fetch ftx margin, futures, and default balance it gives me the same results

### ISSUE THREAD

**Issue by optima66** [ccxt/ccxt#7707]
python latest version and latest version of ccxt

When I try to fetch ftx margin, futures, and default balance it gives me the same results:
ccxt_ftx.fetch_balance(params={'type': 'margin'})
ccxt_ftx.fetch_balance(params={'type': 'future'})
ccxt_ftx.fetch_balance()

Is it ok?

**Comment by kroitor** [comment]
@optima66 at this time the unified `fetchBalance` method supports just the spot balance. If you want to get the info about your margin and futures positions, please, use the implicit methods as described in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

```Python
print(exchange.private_get_positions())
```

You can get all the info provided by the exchange with a combination of implicit calls.

Let us know if that does not answer your question.
