### ISSUE TITLE
[binance] Why is parse_ohlcv() method incomplete?

### ISSUE THREAD

**Issue by Acid3croco** [ccxt/ccxt#7708]
- OS: macOs Catalina 10.15
- Programming Language version: Python 3.8.1
- CCXT version: 1.35.40

Hello, 
In the binance.py file, when we use ```fetch_ohlcv()```, to parse the response it uses ```parse_ohlcv()```. In this function, it only get the first 6 elements of the response of binance. Is their any problem with adding the last ones? or maybe something I didn't think about that cause adding the lasts ones a problem. 
Thanks

binance.py, line 1140:
```
    def parse_ohlcv(self, ohlcv, market=None):
        #
        #     [
        #         1591478520000,
        #         "0.02501300",
        #         "0.02501800",
        #         "0.02500000",
        #         "0.02500000",
        #         "22.19000000",
        #         1591478579999,
        #         "0.55490906",
        #         40,
        #         "10.92900000",
        #         "0.27336462",
        #         "0"
        #     ]
        #
        return [
            self.safe_integer(ohlcv, 0),
            self.safe_float(ohlcv, 1),
            self.safe_float(ohlcv, 2),
            self.safe_float(ohlcv, 3),
            self.safe_float(ohlcv, 4),
            self.safe_float(ohlcv, 5),
        ]
```

**Comment by kroitor** [comment]
Historically, the volume reported in OHLCVs is the base volume. The majority of the exchanges provide just that info. Most of the TA algos will rely on that. Some exchanges may provide more info, including the quoteVolume, the order count and so on. However, CCXT unifies the common subset of functionality, even if some exchange gives more info.

You can easily subclass it and parse the other values how you want:


```Python
import ccxt
from pprint import pprint

class my_binance(ccxt.binance):
    def parse_ohlcv(self, ohlcv, market=None):
        return [
            self.safe_integer(ohlcv, 0),
            self.safe_float(ohlcv, 1),
            self.safe_float(ohlcv, 2),
            self.safe_float(ohlcv, 3),
            self.safe_float(ohlcv, 4),
            self.safe_float(ohlcv, 5),
            # ...
        ];


exchange = my_binance({
    'enableRateLimit': True,  # as required by the Manual https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
})

symbol = 'BTC/USDT'
timeframe = '1m'
ohlcvs = exchange.fetch_ohlcv(symbol, timeframe)
pprint(ohlcvs)
```

We will look into adding fetchOHLCVC and fetchOHLCVV further down the road.

Let us know if the above does not answer your question.

**Comment by ttodua** [comment]
Note, [fetchOHLCVV PR](https://github.com/ccxt/ccxt/pull/14743) is under the development now.
