### ISSUE TITLE
Kucoin: fetchBalance returns empty balance

### ISSUE THREAD

**Issue by c0dehunter** [ccxt/ccxt#7712]
- OS: Linux
- Programming Language version: PHP 7.3
- CCXT version: 1.35.43

```
$id = "\\ccxt\\kucoin";
$exchange = new $id();
$exchange->apiKey = "5ed759368e1d410008a437c3"; // testing API key, account has 3 USDT
$exchange->secret = "42447246-4abe-45ba-96d3-02bd32ce96f2";
$exchange->password= "p4gy%IaR9Kyy8hzklat^1^wp";
$exchange->enableRateLimit = true;

for($balance : $exchange->fetchBalance()) {
	...
}
```

**Error**:
Returns empty balance. We tested with multiple exchange accounts and API keys. The test API key (above) has 3 USDT in the main wallet. Others had more.

_Main wallet:_
![image](https://user-images.githubusercontent.com/1484658/95341225-a0508b00-08e8-11eb-8f9d-12bdbdcacd97.png)

_API key:_
![image](https://user-images.githubusercontent.com/1484658/95341302-b4948800-08e8-11eb-98da-cc62e896be33.png)

**Comment by kroitor** [comment]
@c0dehunter plz always paste your verbose request+response, regardless of the type of the issue, since most of the question can be quickly resolved this way.


```PHP
$id = "\\ccxt\\kucoin";
$exchange = new $id();
$exchange->apiKey = "5ed759368e1d410008a437c3"; // testing API key, account has 3 USDT
$exchange->secret = "42447246-4abe-45ba-96d3-02bd32ce96f2";
$exchange->password= "p4gy%IaR9Kyy8hzklat^1^wp";
$exchange->enableRateLimit = true;

$type = 'main'; // or 'trade' by default

$exchange.options['fetchBalance']['type'] = $type;
for($balance : $exchange->fetchBalance()) {
	...
}

// or
// for($balance : $exchange->fetchBalance(array ('type' => $type))) {
//	...
// }
```

- https://github.com/ccxt/ccxt/blob/master/php/kucoin.php#L234
- https://github.com/ccxt/ccxt/blob/master/php/kucoin.php#L1609

Let us know if the above does not answer your question.

**Comment by c0dehunter** [comment]
@kroitor Thank you! I know better now how to use the library and will be able to solve this myself next time.
