### ISSUE TITLE
XMR (Monero) Withdrawal and Payment ID example

### ISSUE THREAD

**Issue by Fcl69** [ccxt/ccxt#772]
Hello!

Many (all?) exchanges require both wallet + payment ID to deposit XMR (Monero).
Therefore, once withdrawing you should specify both wallet address and payment id. I failed to find a code example for payment id param:
`exchange.withdraw (currency, amount, address, params = {})`

Could you please help it?

Thank you in advance,

**Comment by kroitor** [comment]
@Fcl69 it is exchange-specific currently, we don't have this particular aspect of XMR unified yet. However, we have started a major rework of currencies, so we hope to support for that soon. In the meantime, you will have to look the name of that param in exchanges' docs. We will notify you on progress. Let me know if the above does not answer your question. Thx!

**Comment by Fcl69** [comment]
Ok, got it. So... just to confirm. Here's what binance API says, for example:
> addressTag | STRING | NO | Secondary address identifier for coins like XRP,XMR etc.

Does it mean my code should look like that:
`exchange.withdraw ('XMR', 1, 'address', params = {addressTag='payment_id'})`
?

**Comment by kroitor** [comment]
@Fcl69 

> Does it mean my code should look like that:
> exchange.withdraw ('XMR', 1, 'address', params = {addressTag='payment_id'})

Almost, the exact meaning is:

```Python
exchange.withdraw ('XMR', 1, 'address',{'addressTag':'payment_id'})
```

**Comment by Fcl69** [comment]
gotcha! Thank you so much as always!
