### ISSUE TITLE
binance GET https://www.binance.com/exchange/public/product The read operation timed out 

### ISSUE THREAD

**Issue by nucwzq** [ccxt/ccxt#774]
ccxt.base.errors.ExchangeNotAvailable: binance GET https://www.binance.com/exchange/public/product The read operation timed out

The problem often appears, has anyone met the same problems?

**Comment by kroitor** [comment]
@nucwzq that endpoint is deprecated since recently, please update your ccxt version ;)

**Comment by nucwzq** [comment]
@kroitor thank u for replying me so fast, you mean I just need top update the ccxt version by "pip install ccxt",  and it will be addressed?

**Comment by kroitor** [comment]
@nucwzq yep, exactly... but you should do `pip install ccxt -U` (-U means "upgrade")

**Comment by nucwzq** [comment]
@kroitor ok, thank u, i will try it at once.

**Comment by kroitor** [comment]
Let us know if the problem goes away.

**Comment by nucwzq** [comment]
the problem is addressed, but there is another new problem
do the code: exchange.markets[coin]['info']['tradedMoney']
and the error is: KeyError: 'tradedMoney'

**Comment by kroitor** [comment]
@nucwzq you should not use the exchange-specific `info` field, because that was changed with the  endpoint. So you're trying to access the non-existing exchange-specific field, and you basically generate the exception by doing that. It's a reason not to use exchange-specific fields. Please, read this very carefully from the beginning to the very end: https://github.com/ccxt/ccxt/wiki/Manual (it has answers to most of these questions).

**Comment by nucwzq** [comment]
@kroitor ok, thank u.

**Comment by kroitor** [comment]
I would close this for now if you don't mind, let me know if I can help you with anything else. Thx!

**Comment by nucwzq** [comment]
@kroitor ok

**Comment by nucwzq** [comment]
Dear @kroitor , i still have no idea about " not to use exchange-specific fields." , what shoud i do? For example, i want got the current tradedMoney of 'BCD/BTC'.

**Comment by kroitor** [comment]
@nucwzq their current API does not return that anymore, but let me ask why do you need `tradedMoney`? Or what do you need it for? How did you interpret that?

**Comment by nucwzq** [comment]
@kroitor I want find the active coins, and i use the trading volume (tradedMoney) as a index.

**Comment by nucwzq** [comment]
@kroitor the  trading volume in one day.

**Comment by kroitor** [comment]
@nucwzq 24-hour trading volume?

**Comment by nucwzq** [comment]
@kroitor yes, with to BTC

**Comment by kroitor** [comment]
@nucwzq why not using tickers for that? Those are unified and are standardized in ccxt for all exchanges... moreover most people will use tickers for that...

**Comment by nucwzq** [comment]
@kroitor ok, i will try it.

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/wiki/Manual#price-tickers

**Comment by nucwzq** [comment]
@kroitor whether the methods "fetch_ticker"  have a selection to get the ticker information with in diffirent  time interval, for example 1h, 30min........

**Comment by kroitor** [comment]
All tickers contain 24-hour stats. If you need historical volumes, use fetchTrades / fetchOHLCV

**Comment by nucwzq** [comment]
@kroitor thanks for u kindness!!!!

**Comment by nucwzq** [comment]
@kroitor whether should i set a time sleep between any two request, for example:
print(exchange.fetch_ticker('BCPT/BTC'))
time.sleep(bina.rateLimit / 1000) # time.sleep wants seconds
print(exchange.fetch_ticker('BCD/BTC'))

**Comment by kroitor** [comment]
```
exchange = ccxt.binance({'enableRateLimit': True})  # ← enable built-in rate limiter

# do multiple rate-limited requests sequentially

print(exchange.fetch_ticker('BCPT/BTC')
print(exchange.fetch_ticker('BCD/BTC')
print(exchange.fetch_ticker('BCPT/BTC')
print(exchange.fetch_ticker('BCD/BTC')
print(exchange.fetch_ticker('BCPT/BTC')
print(exchange.fetch_ticker('BCD/BTC')

# in a loop

while True:
    print(exchange.fetch_ticker('BCPT/BTC')
    print(exchange.fetch_ticker('BCD/BTC')
```

**Comment by nucwzq** [comment]
@kroitor you mean I just need to add the code “”exchange = ccxt.binance({'enableRateLimit': True})“” in my program.

**Comment by kroitor** [comment]
@nucwzq yes... and error handling of course.

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/tree/master/examples

**Comment by nucwzq** [comment]
@kroitor As for a private API request, how to set the param {'enableRateLimit': True}?

exchange = ccxt.binance({
    'apiKey': '....',
    'secret': '...',
})

**Comment by kroitor** [comment]
```Python
exchange = ccxt.binance({
    'apiKey': '....',
    'secret': '...',
    'enableRateLimit': True,
})
```

If you want a **real** advice: start reading right now. I will not be able to guide you to money step by step. You will still have to spend some time learning, reading the Manual, watching examples, understanding how it works.

**Comment by nucwzq** [comment]
@kroitor OK, Thanks!!!! I will read the Manual at once, thank u so much!!!!

**Comment by nucwzq** [comment]
dear @kroitor is there a "," behind the ( 'enableRateLimit': True ) or not?

exchange = ccxt.binance({
    'apiKey': '...',
    'secret': '...',
    'enableRateLimit': True,           (here  the , )
})

**Comment by kroitor** [comment]
@nucwzq doesn't matter, same result both with and without it

This is ok:

```Python
exchange = ccxt.binance({
    'apiKey': '...',
    'secret': '...',
    'enableRateLimit': True
})
```

This is also ok:

```Python
```Python
exchange = ccxt.binance({
    'apiKey': '...',
    'secret': '...',
    'enableRateLimit': True,
})
```

You definitely need to learn more Python first, then move to algorithmic trading. Your questions obviously come from the lack of basic Python programming skills, because your questions are not related to the library itself, but are related to Python syntax rules.

**Comment by nucwzq** [comment]
@kroitor I am very grateful to you for your advice.
