### ISSUE TITLE
Binance implicit requests raise an exception even though its response is successful.

### ISSUE THREAD

**Issue by crazyguitar** [ccxt/ccxt#7742]
- OS: MacOS 10.14.6
- Programming Language version: node v13.11.0
- CCXT version: 1.35.73

Hi,

I tried to run the following snippet

```js
'use strict'

require('dotenv').config()
const ccxt = require ('ccxt');

const binance = new ccxt.binance({
  apiKey: process.env.API_KEY,
  secret: process.env.API_SECRET,
})

async function run() {
  return binance.sapiGetMiningPubAlgoList({})
}

run()
  .then(req => console.log(req))
  .catch(e => console.log(e))

# node test.js
```

Then I got an error 

```js
ExchangeError: binance {"code":0,"msg":"","data":[{"algoName":"sha256","algoId":1,"poolIndex":0,"unit":"h/s"}]}
    at binance.handleErrors (/Users/chang-ning/Documents/tradingjs/node_modules/ccxt/js/binance.js:2546:19)
    at /Users/chang-ning/Documents/tradingjs/node_modules/ccxt/js/base/Exchange.js:599:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async timeout (/Users/chang-ning/Documents/tradingjs/node_modules/ccxt/js/base/functions/time.js:195:24)
    at async binance.request (/Users/chang-ning/Documents/tradingjs/node_modules/ccxt/js/binance.js:2554:26) {
  constructor: [Function: ExchangeError],
  name: 'ExchangeError'
}
```

Based on [binance api doc](https://binance-docs.github.io/apidocs/spot/en/#acquiring-algorithm-market_data), I discovered that this api return ``{{"code":0, ...}`` which has key, "code". Therefore, I traced code and discovered this [line](https://github.com/ccxt/ccxt/blob/74187f7a2656fb23def5ecc5fb4a4ea6287382e9/js/binance.js#L2277) which did not exclude ``code == 0``. How do I solve this issues?

**Comment by kroitor** [comment]
@crazyguitar thx for reporting it, we've uploaded a fix and it should work fine in the new version 1.35.75+, please update your CCXT in 20 minutes, and let us know if you have further difficulties with it. Thx again!

**Comment by crazyguitar** [comment]
Thank you so much!

**Comment by crazyguitar** [comment]
Work fine now! 👍
