### ISSUE TITLE
[gateio] withdrawal fees

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#7752]
This code can be user to download some non-api data that contains withdrawal fees

    const res = await request({
        method: 'GET',
        uri: 'https://www.gate.io/en/fee',
    });

    const {body} = res;
    const lines = body.split("\n");
    const line = lines.find(line => line.trim().startsWith("const withdraw_feelist"))
    const json = line.substring(line.indexOf("{"), line.indexOf(";"));

    const items = JSON.parse(json);

Note that inside the results is an example of fees for withdrawing one currency that has many withdrawal options where multiple chains are supported.  For example: USDT can be withdrawn using the ETH blockchain (via ERC20), or the TRON blockchain (via TRC20):

    "USDT": {
      "no": 3,
      "symbol": "USDT",
      "name": "Tether",
      "name_cn": "Tether",
      "fee_usdt": "-",
      "fee_btc": "0.2%",
      "fee_eth": "0.2%",
      "deposit": 0,
      "withdraw_percent": "0%",
      "withdraw_fix": 5, <-- figure out what this means when usdt_erc20_withdraw_txfee and usdt_trc20_withdraw_txfee are present
      "withdraw_day_limit": 300000,
      "withdraw_day_limit_remain": 299999,
      "withdraw_amount_mini": 55,
      "withdraw_eachtime_limit": 1000000,
      "usdt_erc20_withdraw_txfee": "5.0",
      "usdt_trc20_withdraw_txfee": "0.0"
    },

**Comment by CherryDT** [comment]
This is available in the API too as `GET /wallet/withdraw_status`: https://www.gate.io/docs/apiv4/en/index.html#retrieve-withdrawal-status

The individual chains' fees are available as `withdraw_fix_on_chain_<chain>`:

```json
  {
    currency: 'USDT',
    name: 'Tether',
    name_cn: 'Tether',
    deposit: '0',
    withdraw_percent: '0%',
    withdraw_fix: '40',
    withdraw_day_limit: '300000',
    withdraw_day_limit_remain: '300000',
    withdraw_amount_mini: '50',
    withdraw_eachtime_limit: '3000000',
    withdraw_fix_on_chain_BTC: 40,
    withdraw_fix_on_chain_ETH: 5,
    withdraw_fix_on_chain_TRX: 0,
    withdraw_fix_on_chain_BSC: 5,
    withdraw_fix_on_chain_EOS: 10,
    withdraw_fix_on_chain_HT: 5,
    withdraw_fix_on_chain_SOL: 5
  }
```

**Comment by frosty00** [comment]
currently supported with `fetchFundingFees`

**Comment by eduardodudu27** [comment]
How can I get python withdrawal rates?
