### ISSUE TITLE
[binance] fetchCurrencies (+ question)

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#7753]
I'm looking at implementing `fetchCurrencies` on Binance using `sapiGetCapitalConfigGetall`.  This endpoint requires auth unfortunately (like okex).

I'm particularly interested in getting the withdrawal fees out.  In binance, there are often multiple options for withdrawals if the currency is supported on multiple chains:

```
{
  coin: 'BUSD',
  depositAllEnable: true,
  withdrawAllEnable: true,
  name: 'BUSD',
  free: '0',
  locked: '0',
  freeze: '0',
  withdrawing: '0',
  ipoing: '0',
  ipoable: '0',
  storage: '0',
  isLegalMoney: false,
  trading: true,
  networkList: [
    {
      network: 'BNB',
      coin: 'BUSD',
      withdrawIntegerMultiple: '0.00000001',
      isDefault: false,
      depositEnable: true,
      withdrawEnable: true,
      depositDesc: '',
      withdrawDesc: '',
      specialTips: 'Both a MEMO and an Address are required to successfully deposit your BUSD BEP2 tokens to Binance.',
      name: 'BEP2',
      resetAddressStatus: false,
      addressRegex: '^(bnb1)[0-9a-z]{38}$',
      memoRegex: '^[0-9A-Za-z\\-_]{1,120}$',
      withdrawFee: '0.028',
      withdrawMin: '0.056',
      withdrawMax: '0',
      minConfirm: 1,
      unLockConfirm: 0
    },
    {
      network: 'BSC',
      coin: 'BUSD',
      withdrawIntegerMultiple: '0.00000001',
      isDefault: false,
      depositEnable: true,
      withdrawEnable: true,
      depositDesc: '',
      withdrawDesc: '',
      specialTips: '',
      name: 'BEP20 (BSC)',
      resetAddressStatus: false,
      addressRegex: '^(0x)[0-9A-Fa-f]{40}$',
      memoRegex: '',
      withdrawFee: '0.05',
      withdrawMin: '0.1',
      withdrawMax: '0',
      minConfirm: 15,
      unLockConfirm: 0
    },
    {
      network: 'ETH',
      coin: 'BUSD',
      withdrawIntegerMultiple: '0.00000001',
      isDefault: true,
      depositEnable: true,
      withdrawEnable: true,
      depositDesc: '',
      withdrawDesc: '',
      specialTips: '',
      name: 'ERC20',
      resetAddressStatus: false,
      addressRegex: '^(0x)[0-9A-Fa-f]{40}$',
      memoRegex: '',
      withdrawFee: '3',
      withdrawMin: '3.01',
      withdrawMax: '0',
      minConfirm: 12,
      unLockConfirm: 0
    }
  ]
}
```

How should we module multiple withdrawal options in ccxt?  Currently I think the fee is just a simple numeric field.

**Comment by kroitor** [comment]
> How should we module multiple withdrawal options in ccxt? Currently I think the fee is just a simple numeric field.

If you return `undefined` from fetchCurrencies it will fallback to its current behavior by default, so we could probably add this trick to all exchanges involved, including binance, bibox, okex,...

```JavaScript
async fetchCurrencies (params = {}) {
    if (this.checkRequiredCredentials (false)) {
        return undefined; // fallback to default, as if there is no fetchCurrencies available
    } else {
        // private call...
    }
}
```

Though, in this case you will have to set up your credentials before your first call to CCXT.
Alternatively, we can make this behavior optional, or even add an (option+fallback).

```JavaScript
async fetchCurrencies (params = {}) {
    if (this.checkRequiredCredentials (false)) {
        const options = this.safeValue (this.options, 'fetchCurrencies', {});
        const throwErrorOnMissingCredentials = this.safeValue (options, 'throwErrorOnMissingCredentials', false);
        if (throwErrorOnMissingCredentials) {
            throw new AuthenticationError (this.id + " fetchCurrencies requires API credentials with options['throwErrorOnMissingCredentials'] === true");
        } else {
            return undefined; // fallback to default, as if there is no fetchCurrencies available
        }
    } else {
        // private call...
    }
}
```

What do you think on the above?

**Comment by npomfret** [comment]
That wasn't exactly was I was asking, but in answer I think the best thing would be to enhance the `has` functionality so it's no longer a boolean, but an object instead.  That object could describe the feature in more detail.  As for your two examples above, I prefer the 2nd with the feedback.

My question was regarding how to model fees.  A number of exchanges now have multiple withdrawal options not just for fiat currencies, but also for crypto where that token is supported on multiple chains.  So currently (I think) in ccxt we have currencies with a single `fee: <number>` field, right?  But that isn't sufficient in the example I posted above from binance.  We need something with more structure, like:

   fee: [{amount: <number>, chain: <text>}, ...]

If there are no options, then the existing solution is ok, but the user needs to understand that the data is either an array or a number.  Better I think is to always have an array, and just use the currency for the `chain` property.

Perhaps `fee` should be `withdrawalFee` as some exchanges have deposit fees.

**Comment by kroitor** [comment]
@npomfret i'd agree with most of what you said in regard of the fee structure, though, i'd make it a dict indexed by the `chain`. And we might have to unify the "chain symbols" standard. Something like "BTC", "ERC20", "TRC20", etc...

As for `fee` vs `withdrawalFee` – yes, we should split them.
Check this comment: https://github.com/ccxt/ccxt/blob/master/js/kraken.js#L402

**Comment by kroitor** [comment]
In some cases, the fees may depend on the size of the transfer, so we could do something like:

```JavaScript
// ...
'fee': this.safeFloat (currency, 'fee'); //  keep it as_is_to_make_it_backward_compatible,
'fees': {
    'deposit': {
        'ERC20': [
            [ 0, 0.01 ], // ←------------- depending on the amount
            [ 1, 0.001 ],
        ]
        'TRC20': 0.002,
    },
    // ...
},
// ...

**Comment by npomfret** [comment]
Ok, so what structure should fetchCurrencies return?  I guess the `fees` object from your example above.  Then the base class could just pick one to put in the old `fee` property ?

**Comment by npomfret** [comment]
something like this: https://github.com/ccxt/ccxt/pull/7799
