### ISSUE TITLE
How to watch open positions at Binance with websocket and CCXT Pro?

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#7754]
Hello,

I was wondering if it is possible to watch positions at Binance with the CCXT pro version? seems there is no watchPosition() available for a websocket alternative to fapiPrivateGetPositionRisk(). 

Thank you,

**Comment by kroitor** [comment]
Hi! 

> I was wondering if it is possible to watch positions at Binance with the CCXT pro version?

Not yet, but it's in the works right now.

> seems there is no watchPosition() available for a websocket alternative to fapiPrivateGetPositionRisk().

We hope to get it implemented and unified asap.

Let us know if the above does not answer your question.
