### ISSUE TITLE
[gateio] currencies are missing symbol field

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#7759]

**Comment by kroitor** [comment]
The `.currencies` don't have a `symbol` though, they have an `id `and the currency `code`.

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/wiki/Manual#currency-structure

**Comment by kroitor** [comment]
Or have I misunderstood the issue?

**Comment by npomfret** [comment]
Oh, sorry. I'm getting code and symbol mixed up.
