### ISSUE TITLE
Bitfinex margin open stop limit order shows no LIMIT price 

### ISSUE THREAD

**Issue by Princeton007** [ccxt/ccxt#7766]
Hello, 
I have another question, maybe it's an issue:

- OS: Windows 10, Linux
- Programming Language version: Python 3.7
- CCXT version: 1.36.10

When I fetch the open orders, CCXT returns only the stop price, not the limit price:
```
exchange.load_markets()
pprint.pprint(exchange.fetchOpenOrders())
```
Is this a matter of CCXT or Bitfinex API? There should be a PRICE_AUX_LIMIT according to https://docs.bitfinex.com/reference#rest-auth-orders
```
Request: POST https://api.bitfinex.com/v1/orders {'X-BFX-APIKEY': '*', 'X-BFX-PAYLOAD': '*', 'X-BFX-SIGNATURE': '*', 'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate'} {"nonce":"1602581107941","request":"/v1/orders"}

Response: POST https://api.bitfinex.com/v1/orders 200 {'Date': 'Tue, 13 Oct 2020 09:25:07 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': '__cfduid=*; expires=Thu, 12-Nov-20 09:25:07 GMT; path=/; domain=.bitfinex.com; HttpOnly; SameSite=Lax', 'X-Frame-Options': 'SAMEORIGIN', 'X-XSS-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'ETag': 'W/"*"', 'Cache-Control': 'max-age=0, private, must-revalidate', 'X-Request-Id': 'ce894c50-84a7-437f-9850-80051cd542b6', 'X-Runtime': '0.009797', 'Referrer-Policy': 'same-origin', 'X-Download-Options': 'noopen', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains;', 'X-Permitted-Cross-Domain-Policies': 'none', 'CF-Cache-Status': 'DYNAMIC', 'cf-request-id': '*', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Server': 'cloudflare', 'CF-RAY': '5e1802f49a6c9808-FRA', 'Content-Encoding': 'gzip'} [{"id":52474350029,"cid":85028465,"cid_date":"2020-10-11","gid":null,"symbol":"btcusd","exchange":"bitfinex","price":"11016.0","avg_execution_price":"0.0","side":"sell","type":"stop limit","timestamp":"1602374485.0","is_live":true,"is_cancelled":false,"is_hidden":false,"oco_order":null,"was_forced":false,"original_amount":"0.001","remaining_amount":"0.001","executed_amount":"0.0","src":"api","meta":null}]


[{'amount': 0.001,
  'average': 0.0,
  'clientOrderId': None,
  'cost': None,
  'datetime': '2020-10-11T00:01:25.000Z',
  'fee': None,
  'filled': 0.0,
  'id': '52474350029',
  'info': {'avg_execution_price': '0.0',
           'cid': 85028465,
           'cid_date': '2020-10-11',
           'exchange': 'bitfinex',
           'executed_amount': '0.0',
           'gid': None,
           'id': 52474350029,
           'is_cancelled': False,
           'is_hidden': False,
           'is_live': True,
           'meta': None,
           'oco_order': None,
           'original_amount': '0.001',
           'price': '11016.0',
           'remaining_amount': '0.001',
           'side': 'sell',
           'src': 'api',
           'symbol': 'btcusd',
           'timestamp': '1602374485.0',
           'type': 'stop limit',
           'was_forced': False},
  'lastTradeTimestamp': None,
  'price': 11016.0,
  'remaining': 0.001,
  'side': 'sell',
  'status': 'open',
  'symbol': 'BTC/USD',
  'timestamp': 1602374485000,
  'trades': None,
  'type': 'stop limit'}]

```

**Comment by kroitor** [comment]
> Is this a matter of CCXT or Bitfinex API?

This is a matter of Bitfinex API.
As documented in the CCXT Manual (https://github.com/ccxt/ccxt/wiki/Manual#order-structure), you can see the original response from Bitfinex in the `info` field, that contains the info from the exchange first-hand, untouched. There's no PRICE_AUX_LIMIT inside `info` there.

You can also see the entire verbose request+response in your snippet above – it does not contain the PRICE_AUX_LIMIT either.

Let us know if that does not answer your question.

**Comment by kroitor** [comment]
Actually, it looks like you're using bitfinex v1, and you're comparing it to the bitfinex v2 docs. The bitfinex2 implementation is available in CCXT for bitfinex API v2, however, it's still a work in progress so some methods may be missing there.

**Comment by Princeton007** [comment]
@kroitor indeed! I was using V1. thanks for the heads-up, I'm changing it now and I see that from the "info" I can get also the Limit Price now!

**Comment by gambitov** [comment]
dear @kroitor, I am trying to set a stop loss in bitfinex but I have an issue: "Invalid order type."

`bitfinex.create_order(symbol, '**STOP_LOSS_LIMIT**', side_target, amount, stop_price, params={'stopPrice':stop_price})`

Could you help where I can find valid order types for bitfinex, please

**Comment by kroitor** [comment]
@gambitov you can find all params for bitfinex here: https://docs.bitfinex.com/v1/reference#rest-auth-new-order, let us know if that does not help.
