### ISSUE TITLE
Bitstamp withdrawals

### ISSUE THREAD

**Issue by Felipe-Mangueira** [ccxt/ccxt#777]
Hi, @kroitor,

By reading the API documentation from Bitstamp, I noticed there is a POST method to request withdrawals of many crypto-coins. Apparently, this feature is not implemented on the last version. I would very thankful if you could implement this method on the next update. Is there any chance of this desire come true?

**Comment by kroitor** [comment]
> Is there any chance of this desire come true?

Absolutely not! No way! Never! Just forget about it! We would implement any method, but not that one!

**Comment by Felipe-Mangueira** [comment]
Hi, @kroitor,

Do you have any expected date of launching the next update with this method implemented?

Thanks for your time.

**Comment by kroitor** [comment]
@Felipe-Mangueira not yet, but, I'd suggest... would you want to try submitting a PR on that? If not, we will deliver it soon, hopefully.

**Comment by Felipe-Mangueira** [comment]
Ok, @kroitor, Sorry for disturbing you with my anxiety. I'll respect the time of your team.

**Comment by kroitor** [comment]
We got a followup on this in #963. Hope to merge very soon. I am closing this as a duplicate now, suggest moving our discussion to that post. Thank you!
