### ISSUE TITLE
binance margin stop loss limit order

### ISSUE THREAD

**Issue by Fcl69** [ccxt/ccxt#7783]
OS: linux
ccxt: latest
lang: python3

Can you please help me figuring out how to create margin stop limit order? Can't nail it for whatever reason. Here is the closest I got so far:

```
    exch = ccxt.binance({ "apiKey":"'', "secret":""
     "options": {
            "defaultType": "margin",  # or 'margin'}
    })
   exch.create_order(symbol='BTC/USDT', type='limit', side='sell', amount=0.01, price=9800, params={'stopPrice':9900, 'orderType':'STOP_LOSS_LIMIT'})
```

**Comment by kroitor** [comment]
@Fcl69 hi! Please, always paste your verbose output!

Also, make sure you enable the rate limiter and don't violate this doc: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

```Python
import ccxt
print('CCXT Version', ccxt.__version__)
exchange = ccxt.binance({
    "apiKey":"'',
    "secret":"",
    "enableRateLimit": True,
    "options": {
        "defaultType": "margin",
    }
})
exchange.load_markets()
exchange.verbose = True  # enable verbose mode after loading the markets
exchange.create_order('BTC/USDT', 'STOP_LOSS_LIMIT', 'sell', 0.01, 9800, {'stopPrice':9900})
```

↑ Please, paste your entire output here.

**Comment by Fcl69** [comment]
Ok, your solution seems to work now. I think I messed up in the future account vs margin account.

H/e is there an explicit method for margin stop loss limit?

**Comment by kroitor** [comment]
> H/e is there an explicit method for margin stop loss limit?

You can do that either with `create_order` as shown above or with an implicit method as described in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

Let us know if that does not resolve the issue.
