### ISSUE TITLE
Method watchCreateOrder

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#7784]
Hello,

I try to figure out what can be done with the current version of CCXP Pro, could you confirm creation/cancellation of orders isn't available? at Binance or another exchange. 

Thank you,

**Comment by kroitor** [comment]
@Kinzowa in most cases the order creation and cancellation is not available via the WS API. Binance does not offer that functionality. The WS usage pattern is such that you subscribe to watch WS order updates, then create place a new order vis REST and then receive the updates about it via the WS subscription. That is what a `watchCreateOrder` will do in CCXT when we add it (hopefully soon). Some exchanges allow creating orders via WS – we are covering that as well, but at this time it is not fully implemented yet. We will ping you when it arrives. Let us know if that does not answer your question.
