### ISSUE TITLE
New exchanges: whaleclub.co and paxful.com

### ISSUE THREAD

**Issue by zo34** [ccxt/ccxt#782]
Two exchanges I would love to see added are:

whaleclub.co
paxful.com

Thanks!

**Comment by kroitor** [comment]
Hi!

whaleclub.co doesn't have an orderbook, doesn't have an API that resembles an exchange.
paxful.com is also not an exchange, more like a offer-sell platform for bitcoins.

Sorry, but we're not integrating them if they don't offer an exchange API. Let us know if we can help you with anything else.

**Comment by jjhesk** [comment]
@kroitor i think they have the api. http://docs.whaleclub.co/

**Comment by kroitor** [comment]
@jjhesk if you take a closer look at it, you'll notice that is not a conventional exchange API, for example, they have no endpoint for order books. So, they give you their own price feed. Because of that, we cannot really integrate it the way it is. Let me know if I'm missing something.
