### ISSUE TITLE
Does websocket share the same agent with http?

### ISSUE THREAD

**Issue by Cinux-Chosan** [ccxt/ccxt#7823]
I have passed `{ agent }` to exchange's constructor, but Only HTTP requests can be accessed successfully
, websocket still can't connect to exchange server; BTW, `https-proxy-agent` does work with websocket. How to proxy websocket in ccxt.pro?

**Comment by kroitor** [comment]
@Cinux-Chosan pass `{ httpsAgent }` instead of `{ agent }`, and make sure that your agent is an instance of https.Agent.

Let us know if that does not answer your question.

**Comment by kroitor** [comment]
P.S. @Cinux-Chosan also check this as well:

- https://github.com/ccxt/ccxt/issues/6272
- https://github.com/ccxt/ccxt/issues/6272#issuecomment-565525103
