### ISSUE TITLE
[okex] cant place market order on futures api

### ISSUE THREAD

**Issue by meetmangukiya** [ccxt/ccxt#7829]
- OS: Linux
- Programming Language version: 3.9.6
- CCXT version: 1.36.46

```
  await exchange.createOrder("MNBTC-USDT-201023", "4", "buy", 1, undefined, {
    order_type: 4,
  });
```

```
(node:164618) UnhandledPromiseRejectionWarning: BadSymbol: okex {"error_message":"orderType is an invalid parameter","code":30024,"error_code":"30024","message":"orderType is an invalid parameter"}
    at okex.throwExactlyMatchedException (/home/meet/dev/flamy/romain/bot/node_modules/ccxt/js/base/Exchange.js:532:19)
    at okex.handleErrors (/home/meet/dev/flamy/romain/bot/node_modules/ccxt/js/okex.js:3319:18)
    at /home/meet/dev/flamy/romain/bot/node_modules/ccxt/js/base/Exchange.js:600:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at timeout (/home/meet/dev/flamy/romain/bot/node_modules/ccxt/js/base/functions/time.js:195:24)
    at okex.createOrder (/home/meet/dev/flamy/romain/bot/node_modules/ccxt/js/okex.js:1929:26)
(node:164618) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:164618) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Contacted okex, turns out we cannot have match_price 1 and order_type 4 at the same time. However, the only way to make it market order is to set order_type to 4 from what i see in code. Since the market / limit order parameter from the unified api is rather being used to determine open long, open short, close long, close short

**Comment by kroitor** [comment]
> Contacted okex, turns out we cannot have match_price 1 and order_type 4 at the same time. 

What should be the correct combination for the order type you're trying to place, though? What kind of order are you trying to place? Is it an open long, open short, close long or close short order?

**Comment by kroitor** [comment]
@meetmangukiya it looks like a bug in the current implementation of okex.js to me, but in order to resolve it we need a bit more info about your intent.

**Comment by meetmangukiya** [comment]
I was able to comment out the [match_price parameter line](https://github.com/ccxt/ccxt/blob/master/js/okex.js#L1887) and get the position to open. 
```ts
  await exchange.createOrder("MNBTC-USDT-201023", "1", "buy", 1, undefined, {
    order_type: 4,
  });
```

I still think maybe we'd want to use `limit` and `market` as we do in the unified api and specify the type(open long, open short, close long, close short) by specifying in the params, like we do in TRAILING orders in binance? That seems more intuitive.

**Comment by kroitor** [comment]
> I still think maybe we'd want to use limit and market as we do in the unified api and specify the type(open long, open short, close long, close short) by specifying in the params, like we do in TRAILING orders in binance? That seems more intuitive.

Yep, I'll add the edits asap.

**Comment by meetmangukiya** [comment]
I am not sure if this fixes everything or breaks anything else. The docs regarding match_price seem unclear. If yes would mean best bid or best ask I'd think specifying yes i.e. best bid / best ask is the same as market order which we specify with order_type as 4. 

> Whether order is placed at best counter party price (‘0’:no ‘1’:yes). The parameter is defaulted as ‘0’. If it is set as '1', the price parameter will be ignored，When posting orders at best bid price, order_type can only be '0' (regular order)

However, they also mention best bid price orders need to be type 0?

**Comment by kroitor** [comment]
> However, they also mention specifically that best bid price orders need to be type 0?

Yeah, that's what is confusing. I think they mean that the spent amount on futures has to be specified in the settlement currency (how much to spend for the contracts, instead of the number of contracts).

Basically, my guess about this sentence is:

> When posting orders at best bid price, order_type can only be '0' (regular order)

↑ this is probably a result of a poor translation, and that sentence most likely means this functionality which also mirrored on the spot markets: https://github.com/ccxt/ccxt/blob/master/js/okex.js#L1906

**Comment by kroitor** [comment]
@meetmangukiya to clarify, after this:

```JavaScript
  await exchange.createOrder("MNBTC-USDT-201023", "1", "buy", 1, undefined, {
    order_type: 4,
  });
```

What's your result? You got one contract for the best bid?

**Comment by meetmangukiya** [comment]
The result has been this position 
![image](https://user-images.githubusercontent.com/7620533/96474100-1097ce80-1250-11eb-902c-c7978751b34a.png)
From the docs, it seems like it has to be number of contracts

**Comment by kroitor** [comment]
@meetmangukiya alright, thanks, that clarifies a lot, I will push the edits asap!

**Comment by meetmangukiya** [comment]
Further clarifying on okexapi telegram group - https://t.me/OKExAPI/42327

**Comment by meetmangukiya** [comment]
Yep, we do not want to use match_price for market orders. Can set it to 1 for limit orders with no price.

**Comment by kroitor** [comment]
@meetmangukiya appreciate your help and feedback!

**Comment by meetmangukiya** [comment]
And I appreciate your work on this library :slightly_smiling_face:

**Comment by kroitor** [comment]
@meetmangukiya if you update to version 1.36.70 in 20 minutes, you should be able to use it either way:

```JavaScript
await exchange.createOrder("MNBTC-USDT-201023", "market", "buy", 1, undefined, { type: '1' }); // open long
// ...
await exchange.createOrder("MNBTC-USDT-201023", "1", "buy", 1, undefined, { order_type: '4' }); // open long
// ...
await exchange.createOrder("MNBTC-USDT-201023", "market", "buy", 1, undefined, { 'type': '4', order_type: '4' });
// ...
```

**Comment by meetmangukiya** [comment]
Alright, thanks!
