### ISSUE TITLE
What is the best way to know if the market is available or not?

### ISSUE THREAD

**Issue by dhmk815** [ccxt/ccxt#783]
What is the best way to know if the market is available or not?
For example, last price of 'BTC/CNY' in 'quoine' exchange can be fetched even if the market has been closed.

**Comment by kroitor** [comment]
@dhmk815 currently, we have started to unify the `active` market property, however, it is not unified for all exchanges yet. We will be happy if you contribute to this work. We are also reworking the currencies API (fetchCurrencies) to be able to track disabled funding along with inactive markets. Let me know if it answers your question or not. Thx!
