### ISSUE TITLE
bug in Exchange base class `hash` method

### ISSUE THREAD

**Issue by purplebrabus** [ccxt/ccxt#7833]
- OS: Windows 10
- Programming Language version: Python 3.8
- CCXT version: 1.36.45

Static method `hash` of base Exchange class has a bug inside when being used with 'keccak` hashing algorithm needed for all Web3 required exchanges. `web3` attribute of the Exchange class is `None` because Exchange class hasn't been initiated since it's staticmethod. Eventually the hash() function throws an exception and all private endpoints of these exchanges are impossible to use.

```
    binary = bytes(Exchange.web3.sha3(request))
AttributeError: 'NoneType' object has no attribute 'sha3'
```

**Comment by kroitor** [comment]
@khranovsky1337 you have to install web3 in order to use it, do you have the web3 package installed?

**Comment by purplebrabus** [comment]
yep i do! but the web3 attribute is just None by default before you call its __init__  right?

**Comment by purplebrabus** [comment]
when i change line 1072 from `binary = bytes(Exchange.web3.sha3(request))` to `binary = bytes(Web3.sha3(request))` it works just fine

**Comment by kroitor** [comment]
@purplebrabus if you add `requiredWeb3: True` to the exchange constructor arguments, it should work from there. We will try and fix this on our side as well.

```Python
exchange = getattr(ccxt, exchange_id)({
    'requiresWeb3': True,
    'enableRateLimit': True,
    # ...
})
```

**Comment by kroitor** [comment]
@purplebrabus we will debug this and will get back to you shortly.

**Comment by kroitor** [comment]
@purplebrabus let us know if you have further issues with it after upgrading to CCXT 1.36.69+ (the new build will arrive in 20 minutes). We will be happy if you report back whether it is resolved on your side or not. Thx for your feedback!

**Comment by purplebrabus** [comment]
Yes, issue has been successfully resolved, thank you for the quick response!

**Comment by kroitor** [comment]
@purplebrabus appreciate your help!
