### ISSUE TITLE
idex2 wrapper: symbol is None in .fetch_my_trades()

### ISSUE THREAD

**Issue by purplebrabus** [ccxt/ccxt#7837]
- OS: Windows 10
- Programming Language version: Python 3.8
- CCXT version: 1.36.70

`idex2.fetch_my_trades()`: the `symbol `in the result trades is `None`. Looking at the `idex2.parse_trade()` method which handles the duality of public and private trades, it turns out that in case of private trades there is no symbol although it is presented in the `trade['market']`:
```
409        if market is not None:
410            symbol = market['symbol']
```

so there probably should be something like:
```
409        if market is not None:
410            symbol = market['symbol']
411        else:
412            marketId = self.safe_string(trade, 'market')
413            symbol = self.safe_symbol(marketId, delimiter='-')
```

**Comment by frosty00** [comment]
@purplebrabus I've fixed this in #7838 https://github.com/ccxt/ccxt/pull/7838/commits/902bd18c1c354d60f970c4a85c3ef78e00774e3e
