### ISSUE TITLE
Bitbank missing XLM/JPY symbol (hardcoded)

### ISSUE THREAD

**Issue by codemonkeyno1** [ccxt/ccxt#7844]
Recently added symbol not yet in ccxt.

Error:  "ccxt.base.errors.BadSymbol: bitbank does not have market symbol XLM/JPY"

**Comment by codemonkeyno1** [comment]
Hi, missing new symbol QTUM/JPY (hardcoded)

**Comment by codemonkeyno1** [comment]
Can you please commit to python version as well?

**Comment by kroitor** [comment]
> Can you please commit to python version as well?

- https://github.com/ccxt/ccxt/wiki/FAQ#hey-the-fix-youve-uploaded-is-in-js-would-you-fix-python--php-as-well-please

**Comment by codemonkeyno1** [comment]
Apologies, thanks!

**Comment by codemonkeyno1** [comment]
Hi, missing new symbol BAT/JPY (hardcoded)
