### ISSUE TITLE
[idex] fetch_orders_helper wallet bug

### ISSUE THREAD

**Issue by purplebrabus** [ccxt/ccxt#7847]
- OS: Windows 10
- Programming Language version: Python 3.8
- CCXT version: 1.36.76

in case of using additional `wallet` param in fetch_open_orders:
```
ccxt.idex().fetch_open_orders(params={'wallet': '0xETH_ADDRESS'}) 
```

in `fetch_orders_helper`, line 645 this wallet is ignored and self.WalletAddress is put instead which results in undesired behavior especially if `self.walletAddress` == `None`:
```
request = {
            'nonce': self.uuidv1(),
            'wallet': self.walletAddress,
}
```

Proposal fix:
```
request = {
            'nonce': self.uuidv1(),
            'wallet': params.get('wallet', self.walletAddress),
}
```

**Comment by purplebrabus** [comment]
everywhere else `params={'wallet': '0xETH_ADDRESS'}` seem to be working!

**Comment by frosty00** [comment]
right but in line `655` it is extended. Overriding the wallet seems to be working for me.

**Comment by frosty00** [comment]
can you post the verbose request of some code you are having trouble with

**Comment by purplebrabus** [comment]
Weird it seems like i cannot reproduce the issue myself now too 😂. Okay will open another one if i find it once more and provide more details
