### ISSUE TITLE
"Sub-account function is not enabled" Error for Binance API

### ISSUE THREAD

**Issue by charlesedwards** [ccxt/ccxt#7848]
Hi guys, trying to query my sub-account history.  I use this api for trading on Binance Futures and it works fine, but when I run the following code I get an error:

```
binance.wapiGetSubAccountTransferHistory({'email':'xxx@xxx.com'})
```
Error: 
```
ccxt.base.errors.ExchangeError: binance {"msg":"Sub-account function is not enabled.","success":false}
```

Any ideas whats wrong here?

Thanks!

**Comment by charlesedwards** [comment]
@kroitor 🙏

**Comment by kroitor** [comment]
@charlesedwards that message is coming from Binance API itself, it tells you to enable sub-accounts on the API Key. I think you should check the sub-account checkbox in your API key settings on the Binance website. Let us know if that does not help.
