### ISSUE TITLE
 What is the issue , kindly help me I am getting Binance testnet fetch futures balance error "code -2015 Invalid API-key, IP, or permissions for action"

### ISSUE THREAD

**Issue by AsadullahSoomro** [ccxt/ccxt#7851]
I am using Binance testnet account API Keys for trading for testing purposes. 
I want to do some trading programmatically, while I have some test coins in my wallet and I have traded manually buy-sell but right now It is generating an Invalid API key error, what is the issue,   
kindly help me.

Thanks in advance!

- Windows:
- Programming Language version: Python 3.6
- CCXT version:Version: 1.36.77
- pip version 20.2.2 

``Binance_testnet = ccxt.binance({
    'apiKey': ' ',
    'secret': '  ',
    'enableRateLimit': True,
})
Bybit_testnet.set_sandbox_mode(True)
Binance_testnet.load_markets()
Binance_testnet.verbose = True
print(Binance_testnet.fetch_balance())
``

> Request: GET https://api.binance.com/api/v3/account?timestamp=1603342638752&recvWindow=5000&signature=ae650ba96987e16f94a262873c4dfe757988bb863246491b6fd34582a8163f26 {'X-MBX-APIKEY': '7e114e164ace95135bc6e27756118dc855b43a394835978bbeae01d0a726b6a8', 'User-Agent': 'python-requests/2.23.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.binance.com/api/v3/account?timestamp=1603342638752&recvWindow=5000&signature=ae650ba96987e16f94a262873c4dfe757988bb863246491b6fd34582a8163f26 401 {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '70', 'Connection': 'keep-alive', 'Date': 'Thu, 22 Oct 2020 04:57:20 GMT', 'Server': 'nginx', 'x-mbx-uuid': '7138d796-8d9c-4b4c-9f36-d4b1c45fa09b', 'x-mbx-used-weight': '8', 'x-mbx-used-weight-1m': '8', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 591e4b30042bbdbd8631e77408ae5aa6.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'SIN2-C1', 'X-Amz-Cf-Id': 'aOsqi23kwJGTLfZER21zSLugtOrdTs1TFyyZ2RTeTFQFTFfi1j-TXg=='} {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
Traceback (most recent call last):
  File "C:\Users\Asad\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\base\exchange.py", line 557, in fetch
    response.raise_for_status()
  File "C:\Users\Asad\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.binance.com/api/v3/account?timestamp=1603342638752&recvWindow=5000&signature=ae650ba96987e16f94a262873c4dfe757988bb863246491b6fd34582a8163f26

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Asad/PycharmProjects/Simple-Trading-Bot/main.py", line 22, in <module>
    print(Binance_testnet.fetch_balance())
  File "C:\Users\Asad\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\binance.py", line 549, in fetch_balance
    response = getattr(self, method)(query)
  File "C:\Users\Asad\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\base\exchange.py", line 444, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\Asad\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\binance.py", line 1763, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\Asad\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\base\exchange.py", line 463, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\Asad\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\base\exchange.py", line 569, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\Asad\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\binance.py", line 1757, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, error, feedback)
  File "C:\Users\Asad\AppData\Local\Programs\Python\Python36-32\lib\site-packages\ccxt\base\exchange.py", line 481, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}

Process finished with exit code 1

**Comment by AsadullahSoomro** [comment]
I am using Binance testnet account API Keys for trading for testing purposes.
I want to do some trading programmatically, while I have some test coins in my wallet and I have traded manually buy-sell but right now It is generating an Invalid API key error, what is the issue,
kindly help me.

Thanks in advance!

**Comment by kroitor** [comment]
@AsadullahSoomro have you enabled proper permissions on your API key on Binance's website? Make sure you don't have the IP restrictions configured. Also, make sure that the key itself is correct.

**Comment by kroitor** [comment]
This string does not look like a correct API key to me, since it has to be a mixed-case letters:                `7e114e164ace95135bc6e27756118dc855b43a394835978bbeae01d0a726b6a8`

**Comment by AsadullahSoomro** [comment]
@kroitor 
I am using a Binance Testnet account having test USD coins I want to trade programmatically Instead of manually trading.
Please guide.
When I am clicking API tab on Binance Portal it's showing  https://binance-docs.github.io/apidocs/futures/en/#change-log

https://testnet.binancefuture.com/en/futures/BTCUSDT

**Comment by AsadullahSoomro** [comment]
Currently, I am using testnet wallet having some USD coins I have successfully trade manually But now I wanna trade through programmatically: First of check balance through this `code`
`import ccxt

app = Flask(__name__)

Binance_testnet = ccxt.binance({
    'apiKey': '7e114e164ace95135bc6e27756118dc855b43a394835978bbeae01d0a726b6a8',
    'secret': 'f054bcd389ef98f41d16f7f85cc525c49377fd350eb6381838342a001d48bad1',
    'enableRateLimit': True,

})

# Bybit_testnet.set_sandbox_mode(True)
Binance_testnet.load_markets()
Binance_testnet.verbose = True
#Binance_testnet.set_sandbox_mode(True)
print(Binance_testnet.fetch_balance())`

**Comment by kroitor** [comment]
@AsadullahSoomro do you understand what an API key is and how it is different from your USDT wallet credentials? The API keypair is a key + secret that you get on the Binance website.

**Comment by AsadullahSoomro** [comment]
Respected Sir @kroitor 
actually, I am testing with default keys that binance testnet has provided to me after some manually trading.

**Comment by kroitor** [comment]
@AsadullahSoomro in order to use the private APIs you have to strictly follow the Manual, to a word. 

- https://github.com/ccxt/ccxt/wiki
- https://github.com/ccxt/ccxt/wiki/Manual

I'd highly recommend to read the entire Manual from top to bottom at least once, it will save you a ton of time.

You have to configure your credentials precisely according to the Authentication section:

- https://github.com/ccxt/ccxt/wiki/Manual#authentication

To obtain the Binance API Key you have to register with Binance and create a keypair in your user account settings on Binance's website. In this case the message you're reading is coming from Binance itself and it tells you: _"Invalid API-key, IP, or permissions for action."_. That means your key is invalid. So you have to put a proper API key in the CCXT constructor.

Let us know if that does not answer your question.
