### ISSUE TITLE
[binance] Set ammount by USDT instead of a coin

### ISSUE THREAD

**Issue by Guayab0** [ccxt/ccxt#7853]
Hello, i'm very new to coding and i'm running this on Python 3.8 and its working perfectly, thank you very much for your work. But as you probably already know, in this case, when you set the ammount value, youre specifying in this case the ammount of BNB instead of USDT. If i wanted to choose the ammount by USDT, or maybe if i did 'BNB/BTC' to choose the ammount by BTC so i don't have to worry about how much the ticker in front costs. Maybe this is a very simple thing to solve but i searched on the manual and i couldnt find another command that did this. Thanks in advance!

```
symbol = 'BNB/USDT'
type = 'market'  # or 'market'
side = 'buy'  # or 'buy'
amount = 0.62
price = None  # or None
```

**Comment by kroitor** [comment]
Hi! 

Please, check this duplicate issue, it has been answered there: https://github.com/ccxt/ccxt/issues/6391#issuecomment-576247330. 

I would highly recommend to start with reading the entire Manual from top to bottom, it will save your time. 

- https://github.com/ccxt/ccxt/wiki
- https://github.com/ccxt/ccxt/wiki/Manual

If you have a question in the learning process, it is likely answered already, so I would highly recommend to use the search over the issues and comments in this repository. Also, check out the FAQ: https://github.com/ccxt/ccxt/wiki/FAQ. Let us know if that does not help.

**Comment by Guayab0** [comment]
So, based on the answer to the other guy, i saw you posted two different types of code, it wasnt very clear, so lets say i want to buy $2000 on a market order, would this be correct? The question would be if i set the 2000 on the additional params, what do i set on the amount value? Because no value will create an error apparently. I get that cost = amount * price, but if the price is already set on the market order, having to choose the ammount conflicts me, because you only choose one or the other. Sorry for the hassle.

```
symbol = 'BNB/USDT'
type = 'market'  # or 'market'
side = 'buy'  # or 'buy'
amount = 0
price = None  # or None

# extra params and overrides if needed
params = {
    'quoteOrderQty': 2000,  # binance-specific
}

order = exchange.create_order(symbol, type, side, amount, price, params)

```

**Comment by kroitor** [comment]
> lets say i want to buy $2000 on a market order, would this be correct?

Yes

> The question would be if i set the 2000 on the additional params, what do i set on the amount value? Because no value will create an error apparently. I get that cost = amount * price, the price is already set by the market so 'None' on price makes sense, but having to choose the ammount twice conflicts me. Sorry for the hassle.

If you specify `quoteOrderQty`, the value you pass in the `amount` is ignored.

**Comment by wildabrek** [comment]
Hi
I tried to use quoteOrderQty but when i add it to params I got this error:

--------------------------------->

**ccxt.base.errors.BadRequest: binance {"code":-1102,"msg":"A mandatory parameter was not sent, was empty/null, or malformed."}**

my codes are here:

params = {
        'quoteOrderQty': 100,
        'leverage': 10,
    }

order = exchange.create_market_order('DOGE/USDT', 'buy', 0, None, params)

Also tried with lots of amount and price and params variances.

My CCXT Version is 1.53.22

PS: if i dont use quoteOrderQty it creates order in futures with leverage but it is always like this, 
amount = amountThatIwant/leverage. 
So i can not create order with the amount of i want.

Please help me.

**Comment by kroitor** [comment]
@wildabrek Please, paste your verbose output here: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help, also let us know how you initialize the exchange instance (without showing your keys ofc).
