### ISSUE TITLE
Inconsistent Precision

### ISSUE THREAD

**Issue by timolson** [ccxt/ccxt#7854]
BinanceUS markets report precision as number of decimal places:

```'precision': {'base': 8, 'quote': 4, 'amount': 6, 'price': 2},```

However, CoinbasePro markets report precision as a quantum:

```'precision': {'amount': 1e-08, 'price': 0.01}```

One or the other of these is wrong and it's completely breaking my system, since there is no automatic way to know which semantics are being reported for a given exchange.

**Comment by kroitor** [comment]
@timolson it is all documented, check the `exchange.precisionMode` and this section of the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#market-structure
- https://github.com/ccxt/ccxt/wiki/Manual#methods-for-formatting-decimals

Let us know if that does not answer your question.
