### ISSUE TITLE
Invalid Api key

### ISSUE THREAD

**Issue by UsmanKhOkhar16** [ccxt/ccxt#7863]
I have made demo account on Binance Future Exchange. I found the API key and Secret Key there. When I use these Keys Programmatically, it is generating an error of "Invalid API key or permission"
Kindly Help me regarding this issue
Thanks in advance

**Comment by kroitor** [comment]
> When I use these Keys Programmatically, it is generating an error of "Invalid API key or permission"

We require the following in order to be able to help you, otherwise we will be guessing:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

↑ Can you please provide that info precisely as described in the FAQ (literally to a word) ? We need your code to reproduce it and your verbose request+response. If you don't know how to make the verbose request+response log – it is also documented here: https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

Also, please paste what you see on your API key settings page (https://www.binance.com/en/usercenter/settings/api-management), so that we could see the URL address and the key settings:

<img width="1778" alt="Screen Shot 2020-10-26 at 08 18 29" src="https://user-images.githubusercontent.com/1294454/97136320-e10f2780-1763-11eb-8d06-fb0626696ba7.png">

**Comment by UsmanKhOkhar16** [comment]
Actually I am  using Binance Testnet Account for testing purpose. and it is generating this error **"ccxt.base.errors.AuthenticationError: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}"**

I have attach the image that this Binance Testnet account I am using. and API keys that I am using are found on the bottom section of the portal.
![Capture11](https://user-images.githubusercontent.com/68140597/97137434-9bf4f080-1777-11eb-9337-7721d32ada22.PNG)

**Comment by UsmanKhOkhar16** [comment]
@kroitor you can see that, It is showing **Binance Future**, and in the bottom is the column of **API Key** from where I a using API Key

**Comment by kroitor** [comment]
@UsmanKhOkhar16 

```Python
import ccxt
print('CCXT version:', ccxt.__version__)

exchange = ccxt.binance({
    'apiKey': 'YOUR_API_KEY',  # for the sandbox testnet
    'secret': 'YOUR_SECRET',  # for the sandbox testnet
    'enableRateLimit': True,
})

exchange.set_sandbox_mode(True)  # ←-------------- add this to switch to the sandbox/testnet

print(exchange.fetch_balance())
```

Let us know if that does not answer your question. Feel free to reopen it if you have further difficulties with it.

**Comment by UsmanKhOkhar16** [comment]
@kroitor I have run the same code that you have provide to me, again it is generating the same issue

C:\Users\Usman\PycharmProjects\TradingBot\venv\Scripts\python.exe "C:/Users/Usman/PycharmProjects/Trading Bot/buysell.py"
CCXT version: 1.34.5
Traceback (most recent call last):
  File "C:\Users\Usman\PycharmProjects\TradingBot\venv\lib\site-packages\ccxt\base\exchange.py", line 585, in fetch
    response.raise_for_status()
  File "C:\Users\Usman\PycharmProjects\TradingBot\venv\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://testnet.binance.vision/api/v3/account?timestamp=1603692795656&recvWindow=5000&signature=15fb48dd344e404142b753476a7188cdbf036852abb372a73ab92eea489b2c60

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Usman/PycharmProjects/Trading Bot/buysell.py", line 140, in <module>
    print(exchange.fetch_balance())
  File "C:\Users\Usman\PycharmProjects\TradingBot\venv\lib\site-packages\ccxt\binance.py", line 654, in fetch_balance
    response = getattr(self, method)(query)
  File "C:\Users\Usman\PycharmProjects\TradingBot\venv\lib\site-packages\ccxt\base\exchange.py", line 465, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\Usman\PycharmProjects\TradingBot\venv\lib\site-packages\ccxt\binance.py", line 2142, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\Usman\PycharmProjects\TradingBot\venv\lib\site-packages\ccxt\base\exchange.py", line 486, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\Usman\PycharmProjects\TradingBot\venv\lib\site-packages\ccxt\base\exchange.py", line 597, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\Usman\PycharmProjects\TradingBot\venv\lib\site-packages\ccxt\binance.py", line 2136, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, error, feedback)
  File "C:\Users\Usman\PycharmProjects\TradingBot\venv\lib\site-packages\ccxt\base\exchange.py", line 504, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}

Process finished with exit code 1

**Comment by kroitor** [comment]
@UsmanKhOkhar16 please paste your verbose output:

```Python
import ccxt
print('CCXT version:', ccxt.__version__)

exchange = ccxt.binance({
    'apiKey': 'YOUR_API_KEY',  # for the sandbox testnet
    'secret': 'YOUR_SECRET',  # for the sandbox testnet
    'enableRateLimit': True,
})

exchange.set_sandbox_mode(True)  # ←-------------- add this to switch to the sandbox/testnet

markets = exchange.load_markets()

exchange.verbose = True  # after load_markets()

print(exchange.fetch_balance())
```

**Comment by UsmanKhOkhar16** [comment]
C:\Users\Usman\PycharmProjects\TradingBot\venv\Scripts\python.exe "C:/Users/Usman/PycharmProjects/Trading Bot/buysell.py"
CCXT version: 1.34.5

Request: GET https://testnet.binance.vision/api/v3/account?timestamp=1603693258684&recvWindow=5000&signature=0a05bce073b51a5d55212a5a82b09085fbe7dee8628548bdbd14b06006baf6e8 {'X-MBX-APIKEY': 'f6e617d63149405b776e4ac6479000cf4552434ba68a4bbe500dfd7a89a1b426', 'User-Agent': 'python-requests/2.24.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://testnet.binance.vision/api/v3/account?timestamp=1603693258684&recvWindow=5000&signature=0a05bce073b51a5d55212a5a82b09085fbe7dee8628548bdbd14b06006baf6e8 401 {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '70', 'Connection': 'keep-alive', 'Date': 'Mon, 26 Oct 2020 06:21:01 GMT', 'Server': 'nginx', 'x-mbx-uuid': '3f5449f7-054c-4f65-8600-a391f5286d1e', 'x-mbx-used-weight': '6', 'x-mbx-used-weight-1m': '6', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 e497a374a72f730d53e35606cbbb4aa5.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'FJR50-C1', 'X-Amz-Cf-Id': '7vgc-2daFKIphtc_uhMBL994-PPax2Cf3Cgp9pPxcKUld3yszjhrGw=='} {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
Traceback (most recent call last):
  File "C:\Users\Usman\PycharmProjects\TradingBot\venv\lib\site-packages\ccxt\base\exchange.py", line 585, in fetch
    response.raise_for_status()
  File "C:\Users\Usman\PycharmProjects\TradingBot\venv\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://testnet.binance.vision/api/v3/account?timestamp=1603693258684&recvWindow=5000&signature=0a05bce073b51a5d55212a5a82b09085fbe7dee8628548bdbd14b06006baf6e8

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Usman/PycharmProjects/Trading Bot/buysell.py", line 144, in <module>
    print(exchange.fetch_balance())
  File "C:\Users\Usman\PycharmProjects\TradingBot\venv\lib\site-packages\ccxt\binance.py", line 654, in fetch_balance
    response = getattr(self, method)(query)
  File "C:\Users\Usman\PycharmProjects\TradingBot\venv\lib\site-packages\ccxt\base\exchange.py", line 465, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\Usman\PycharmProjects\TradingBot\venv\lib\site-packages\ccxt\binance.py", line 2142, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\Usman\PycharmProjects\TradingBot\venv\lib\site-packages\ccxt\base\exchange.py", line 486, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\Usman\PycharmProjects\TradingBot\venv\lib\site-packages\ccxt\base\exchange.py", line 597, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\Usman\PycharmProjects\TradingBot\venv\lib\site-packages\ccxt\binance.py", line 2136, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, error, feedback)
  File "C:\Users\Usman\PycharmProjects\TradingBot\venv\lib\site-packages\ccxt\base\exchange.py", line 504, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}

Process finished with exit code 1

**Comment by UsmanKhOkhar16** [comment]
@kroitor

**Comment by kroitor** [comment]
This does not look like a correct API key to me: `f6e617d63149405b776e4ac6479000cf4552434ba68a4bbe500dfd7a89a1b426` – can you paste a screenshot showing the settings for that key?

**Comment by UsmanKhOkhar16** [comment]
![image](https://user-images.githubusercontent.com/68140597/97140135-ce095100-177d-11eb-8cf6-4f8cb888fd22.png)

**Comment by UsmanKhOkhar16** [comment]
@kroitor

**Comment by kroitor** [comment]
@UsmanKhOkhar16 if it's a futures key, then you also need to specify the defaultType in the options. This works on my side with my keypair:

```Python
import ccxt
print('CCXT version:', ccxt.__version__)

exchange = ccxt.binance({
    'apiKey': '16db8b4176457d63fdc0fd8b2c9418f669237cc9620c8c04c3b8973c7e0c39b3',
    'secret': 'a0d07130b34f3debfcfe29d9faf5d2fcf6bdc3b83566d03a0a973a6bc4ab90a4',
    'options': {
        'defaultType': 'future'
    },
    'enableRateLimit': True,  # required by the Manual
})

exchange.set_sandbox_mode(True)  # ←-------------- add this to switch to the sandbox/testnet

markets = exchange.load_markets()

exchange.verbose = True  # after load_markets()

print(exchange.fetch_balance())
```

Let me know if it doesn't work for you. If it works, just change it for your keys and retry with your keypair. Let me know if that helps or not.

**Comment by UsmanKhOkhar16** [comment]
It is working
Thank You so much

**Comment by kroitor** [comment]
@UsmanKhOkhar16 thx for the feedback!
