### ISSUE TITLE
How to share markets among all the exchanges with the same type?

### ISSUE THREAD

**Issue by Cinux-Chosan** [ccxt/ccxt#7864]
I think some common data like `markets` should be shared among all the exchange instances with the same type because they are always the same. There is no need to fetch them everytime, maybe they could be static properties of each Exchange class, but they are not.. 

so I tried to share them with the simple code:

```js
const ccxt = require('ccxt');
const globalOkex = new ccxt.okex();

!(async () => {
  await globalOkex.loadMarkets(); // load markets only once

  const okex = await createOkex({
    apiKey: MY_API_KEY,
    secret: MY_SECRET,
    password: MY_PASSWORD,
  });

  console.log(await okex.fetchBalance()); // Error: AuthenticationError: okex requires `apiKey` credential
})();

function createOkex(config) {
  const { apiKey, secret, password } = config;
  const okex = new ccxt.okex();
  return Object.assign(okex, globalOkex, { apiKey, secret, password }); // share data with Object.assign
}
```

Then I got an error : `Error: AuthenticationError: okex requires `apiKey` credential`, but I did assign the apiKey..

And I found the reason in `ccxt/js/base/Exchange.js`:

```js
defineRestApi (api, methodName, paths = []) {
  // ...
  const partial = async (params) => this[methodName] (path, typeArgument, uppercaseMethod, params || {})
  this[camelcase]  = partial
  this[underscore] = partial
  // ...
```

Every method such as `spotGetAccounts` is defined with an arrow function as a local property, not inherit from its proto chain ...

And `enumerable` is `true`:

```js
console.log(Object.getOwnPropertyDescriptor(globalOkex, 'spotGetAccounts')).enumerable // true
```

That is why they were assigned to new created okex.

Finally, I had to traverse `globalOkex`:

```js
const ccxt = require('ccxt');
const globalOkex = new ccxt.okex();

!(async () => {
  await globalOkex.loadMarkets(); // load markets only once

  const okex = await createOkex({
    apiKey: MY_API_KEY,
    secret: MY_SECRET,
    password: MY_PASSWORD,
  });

  console.log(await okex.fetchBalance()); // OK, problem solved
})();

function createOkex(config) {
  const { apiKey, secret, password } = config;
  const okex = new ccxt.okex();

  for (const key in globalOkex) {  // traverse globalOkex
    if (globalOkex.hasOwnProperty(key)) {
      const value = globalOkex[key];
      if (!value instanceof Function) {
        okex[key] = value;
      }
    }
  }

  return Object.assign(okex, { apiKey, secret, password });
}
```

But I don't think this is a good way, Is there a better way to share common data among all exchanges of the same type？

**Comment by kroitor** [comment]
@Cinux-Chosan let us know if this example does not answer your question: https://github.com/ccxt/ccxt/blob/master/examples/js/shared-load-markets.js

**Comment by Cinux-Chosan** [comment]
Thanks, it works.

Maybe it's better that the property name list could be mounted as a static property on Exchange Class so that we don't have to worry about what's in it and when it is updated.

```js
[
  'ids',
  'markets',
  'markets_by_id',
  'marketsById',
  'currencies',
  'currencies_by_id',
  'baseCurrencies',
  'quoteCurrencies',
  'symbols',
].forEach(propertyName => {
  exchange[propertyName] = globalExchange[propertyName];
});
```

to 

```js
Exchange.staticPropertyNameList.forEach(propertyName => {
  exchange[propertyName] = globalExchange[propertyName];
});
```

:)

**Comment by kroitor** [comment]
@Cinux-Chosan we will consider adding that, thx for your feedback!
