### ISSUE TITLE
How to dynamically change proxies for an async exchange?

### ISSUE THREAD

**Issue by 4nzor** [ccxt/ccxt#7865]
- OS: Windows
- Programming Language version: Python 3.7
- CCXT version: 1.34.11

Hi! I use async_utils with a proxy (a ThreadPool is also allocated for each proxy) and for each proxy I have to create connector and session.

How correct is this and can I specify a proxy without creating a session?
```
    tasks = [] 
    start = time()

    connector = aiohttp_socks.ProxyConnector.from_url(proxy.socks, loop=loop)  
    session = aiohttp.ClientSession(connector=connector, loop=loop, timeout=500)  

    exchange_class = getattr(async_support, ex_wrap.ex_type)
    exchange_client = exchange_class({
        'asyncio_loop': loop,
        'session': session,
        'apiKey': api_key,
        'secret': api_secret,
        'recvWindow': 10000000000,
        'verbose': False,
        'enableRateLimit': True,
    })

    for symbol in tickers:
        tasks.append(exchange_client.fetch_my_trade(symbol, since=since))
    all_trades = await asyncio.gather(*tasks)
    await connector.close()
    await session.close()
    await exchange_client.close()
    return all_trades
```

**Comment by kroitor** [comment]
> How correct is this and can I specify a proxy without creating a session?

That is correct. I don't think that `aiohttp` offers a different way of using multiple proxies in parallel, unless you write a new session subclass of your own to manage your connections and their states.

But you can do `exchange.session = proxy_session_1`, `exchange.session = proxy_session2` on the fly.

Let us know if that does not answer your question.
