### ISSUE TITLE
bybit order price is wrong

### ISSUE THREAD

**Issue by fonzmeister** [ccxt/ccxt#7867]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version: Python
- CCXT version: 1.36.85
```
order = bybit.fetchOrder(None, 'BTC/USD', {'stop_order_id': ANORDERID})
```

```
{'info': {'user_id': 696988,
  'symbol': 'BTCUSD',
  'side': 'Sell',
  'order_type': 'Market',
  'price': '6947.5',
  'qty': 784,
  'time_in_force': 'FillOrKill',
  'order_status': 'Filled',
  'ext_fields': {'o_req_num': -3568870016294},
  'last_exec_time': '1603731717.4075341',
  'last_exec_price': '12804',
  'leaves_qty': 0,
  'leaves_value': '0',
  'cum_exec_qty': 784,
  'cum_exec_value': '0.06123086',
  'cum_exec_fee': '0.00004593',
  'reject_reason': 'EC_NoError',
  'cancel_type': 'UNKNOWN',
  'order_link_id': '',
  'created_at': '2020-10-25T12:00:14.098163Z',
  'updated_at': '2020-10-26T17:01:57.407534Z',
  'order_id': 'eaf5b8a7-e1c9-4bfd-bb8d-d64e0ca0cb2e'},
 'id': 'eaf5b8a7-e1c9-4bfd-bb8d-d64e0ca0cb2e',
 'clientOrderId': None,
 'timestamp': 1603627214098,
 'datetime': '2020-10-25T12:00:14.098Z',
 'lastTradeTimestamp': 1603731717407,
 'symbol': 'BTC/USD',
 'type': 'market',
 'side': 'sell',
 'price': 6947.5,
 'amount': 784.0,
 'cost': 0.06123086,
 'average': None,
 'filled': 784.0,
 'remaining': 0.0,
 'status': 'closed',
 'fee': {'cost': 4.593e-05, 'currency': 'BTC'},
 'trades': None}
```

I suddenly noticed this which is very weird. It might also be an issue on bybits side. A stoporder was triggered and the price reported back was 6947.5. THis is totally wrong (price = ~12800 atm).

The 'last_exec_price': '12804', is the correct data, maybe good to map price to this?

**Comment by kroitor** [comment]
@fonzmeister as you can see from the `info`, that price is coming from bybit itself... If you calculate the amount over cost, that's 784 / 0.06123086 = 12804,00111969683261, so their value of 6947.5 is wrong. The `last_exec_price` also points to 12804. Never seen this before with bybit. Should we set the `price` to `undefined` for bybit market orders, and fill the average price from amount/cost instead?

**Comment by fonzmeister** [comment]
that might be a better idea than to use the 'last_exec_price'. And indeed it is very strange. Never saw this as well so far

I'll add this case in my tests, see if they are going to fix it or not (and will report back if they do). Probably not worth it to try to get into contact

**Comment by fonzmeister** [comment]
BTW, if I query other orders in my history these are all fine... So either something suddenly changed on their end or it is just a single weird thing that happened

**Comment by fonzmeister** [comment]
I get an zero by division error when I try to get an order.

order:
```
{'info': {'user_id': ---,
  'symbol': 'BTCUSD',
  'side': 'Buy',
  'order_type': 'Market',
  'price': '10344',
  'qty': 462,
  'time_in_force': 'ImmediateOrCancel',
  'order_status': 'Active',
  'ext_fields': {},
  'leaves_qty': 0,
  'leaves_value': '0',
  'cum_exec_qty': 0,
  'cum_exec_value': None,
  'cum_exec_fee': None,
  'reject_reason': '',
  'cancel_type': '',
  'order_link_id': '',
  'created_at': '2020-09-09T20:00:15Z',
  'updated_at': '2020-09-10T01:38:44Z',
  'order_id': '---'},
 'id': '----',
 'clientOrderId': None,
 'timestamp': 1599681615000,
 'datetime': '2020-09-09T20:00:15.000Z',
 'lastTradeTimestamp': None,
 'symbol': 'BTC/USD',
 'type': 'market',
 'side': 'buy',
 'price': 10344.0,
 'amount': 462.0,
 'cost': 0.0,
 'average': None,
 'filled': 0.0,
 'remaining': 0.0,
 'status': 'open',
 'fee': None,
 'trades': None}
```

response:
```
Response: GET https://api.bybit.com/v2/private/stop-order?api_key=---&recv_window=5000&stop_order_id=####&symbol=BTCUSD&timestamp=1603875514080&sign=##### 200 {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '618', 'Expires': 'Wed, 28 Oct 2020 08:58:34 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Wed, 28 Oct 2020 08:58:34 GMT', 'Connection': 'keep-alive'} {"ret_code":0,"ret_msg":"OK","ext_code":"","ext_info":"","result":{"user_id":####,"symbol":"BTCUSD","side":"Buy","order_type":"Market","price":"10344","qty":462,"time_in_force":"ImmediateOrCancel","order_status":"Active","ext_fields":{},"leaves_qty":0,"leaves_value":"0","cum_exec_qty":0,"cum_exec_value":null,"cum_exec_fee":null,"reject_reason":"","cancel_type":"","order_link_id":"","created_at":"2020-09-09T20:00:15Z","updated_at":"2020-09-10T01:38:44Z","order_id":"##-##-##-##-##"},"time_now":"1603875514.191007","rate_limit_status":598,"rate_limit_reset_ms":1603875514189,"rate_limit":600}
```

error:
```
Traceback (most recent call last):
  File "C:\Users\erikj\AppData\Roaming\Python\Python38\site-packages\ccxt\bybit.py", line 1185, in fetch_order
    return self.parse_order(result, market)
  File "C:\Users\erikj\AppData\Roaming\Python\Python38\site-packages\ccxt\bybit.py", line 1060, in parse_order
    average = filled / cost
ZeroDivisionError: float division by zero
```

**Comment by fasenderos** [comment]
I'm facing same issue, that's the reason taken from the [offical telegram channel of Bybit](https://t.me/BybitAPI/72556). I hope it will be helpful to the next

> Market orders are technically (in the backend) just limit orders submitted at a worse price in the internal system to reduce the chance of a flash crash or something similar, ie a trader might submit a market order but they didn't expect it to execute at a price significantly worse than the last price as they know it. So the `price` returned here is that internal price value. If you want the true execution price, would recommend subscribing to the `execution` WS.
