### ISSUE TITLE
GDAX fetching ohlcv with the "since" parameter doesn't work properly

### ISSUE THREAD

**Issue by 3droj7** [ccxt/ccxt#787]
Hey,

When using the GDAX exchange for getting OHLCV, it seems to ignore the "since" parameter and it retrieves the last 200 records of the OHLCV table.

```
exc = ccxt.gdax()
exc.fetch_ohlcv("BTC/USD", "1d", 1000*(time.time()-(60*60*24*30)))
```
I tried to fetch the last 30 days and it got me the last 200 day..
Btw, it worked with the "kraken" exchange

**Comment by brdu** [comment]
What are the [0] and [length-1] dates of the array? 

I was going to create an issue for this after looking into it more. Looks to me like gdax is returning OHLCV in order [new, .., old] where other exchanges return in [old, .., new]

**Comment by 3droj7** [comment]
The values are -
[0] = 1512691200000L # 2017-12-08 02:00:00
[-1] = 1494633600000L # 2017-05-13 03:00:00

**Comment by brdu** [comment]
Ah ok not related then. Does `time.time()` return milliseconds or seconds? Whats the value `1000*(time.time()-(60*60*24*30))` outputs?

Gdax returns a max 200 candles.. so the timestamp is probably off by a lot.

**Comment by 3droj7** [comment]
Ok... It seems that I used the version from PyPI and not from the repository. 
It works for me now. Sorry for the waste of time.
By the way, there is no significant difference in gdax.py between PyPi and the latest version which is weird \:

**Comment by kroitor** [comment]
@3droj7 thanks for the feedback! As you may know, we are under active development, therefore we ask our users to update frequently. New fixes and features are added daily.

@brdu respect for the support!

**Comment by brdu** [comment]
@kroitor thanks for all the hard work on this awesome library!
