### ISSUE TITLE
Binance USDT-Ⓜ Futures (futures/usdt-margined)

### ISSUE THREAD

**Issue by NaeimAbdi** [ccxt/ccxt#7871]
Hi, 
I'm trying to make an order on the USDT-Ⓜ Futures market(futures/usdt-margined) on Binance exchange by using CCXT. But in order types I have only three options "orderTypes":["LIMIT","MARKET","STOP"]. I need more options for order type and some options like reduceOnly on this market. 
What should I do?
Thanks for your attention.

**Comment by kroitor** [comment]
@NaeimAbdi hi! You can place all types of orders supported by Binance's API.

Please, check this example:

- https://github.com/ccxt/ccxt/blob/master/examples/py/binance-conditional-orders.py

See how `params`-overrides are passed there. You can pass any of the supported fields this way. And this is also documented in the Manual here:

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

Let us know if it does not answer your question. Feel free to reopen this issue or just ask further questions, if any.
