### ISSUE TITLE
Currently I am getting Error of Binance testnet ccxt.base.errors.NotSupported: Binance does not have a sandbox URL

### ISSUE THREAD

**Issue by AsadullahSoomro** [ccxt/ccxt#7878]
I am using Binance testnet account API Keys for trading for testing purposes.
Currently, I am getting Error of Binance testnet ccxt.base.errors.NotSupported: Binance does not have a sandbox UR right now It is generating Error of Binance testnet ccxt.base.errors.NotSupported: **Binance does not have a sandbox UR**, 
**what is the issue, while the same code is working on other machines kindly help me.**

Windows:

- Programming Language version: Python 3.6
- CCXT version:Version: 1.36.77
- pip version 20.2.2

`'''import ccxt
import time
import datetime
import binance

actual_quantity = 1
symbol = 'BTC/USDT'

Binance_testnet = ccxt.binance({
    'apiKey': '',
    'secret': '',
    'options': {'defaultType': 'future'},
    'enableRateLimit': True,
})

#exchange.set_sandbox_mode(True)
#exchange.load_markets()
#exchange.verbose = True

#exchange.set_sandbox_mode(True)
Binance_testnet.set_sandbox_mode(True)
Binance_testnet.verbose = True

print(Binance_testnet.fetch_balance())'''
import ccxt
from pprint import pprint

Binance_Testnet = ccxt.binance({
    'apiKey': '',
    'secret': '',
    'options': {
        'defaultType': 'future'  
    },
    'enableRateLimit': True,  
})

Binance_Testnet.verbose = True
Binance_Testnet.set_sandbox_mode(True)

balance = Binance_Testnet.fetch_balance()
print(balance)
`
 ---------Error---------
in set_sandbox_mode
    raise NotSupported(self.id + ' does not have a sandbox URL')
ccxt.base.errors.NotSupported: binance does not have a sandbox URL
right now It is generating Error of Binance testnet ccxt.base.errors.NotSupported: **Binance does not have a sandbox UR**, 

**Thanks in advance!**

**Comment by kroitor** [comment]
@AsadullahSoomro run this code on the machine that does not work:

```Python
import ccxt
print('CCXT runtime version:', ccxt.__version__)
```

↑ What do you see?

**Comment by AsadullahSoomro** [comment]
@kroitor 
Please check this output: 

CCXT runtime version: 1.24.33

Process finished with exit code 0

**Comment by AsadullahSoomro** [comment]
**OutPut**

CCXT runtime version: 1.24.33

**Comment by kroitor** [comment]
@AsadullahSoomro your version of CCXT is too old. Please, update it. This is step 1 in the trouble shooting sequence: https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting. Let us know if that does not help.

**Comment by AsadullahSoomro** [comment]
it's working fine now
@kroitor  **Thanks a lot**
