### ISSUE TITLE
GDAX request timestamp expired

### ISSUE THREAD

**Issue by j-a-m-l** [ccxt/ccxt#788]
While I was trying GDAX API, I had problems connecting to it (`{"message":"request timestamp expired"}`).

I've solved them using a custom nonce generator, based on the [official GDAX Node.js client](
https://github.com/coinbase/gdax-node/blob/9a59db269857d10cb449c44cd6a0f51c630abd5c/lib/request_signer.js#L15):
```
nonce = ()=> Date.now() / 1000
```

Could this be considered a bug or improvement, or it was just a personal issue?

**Comment by kroitor** [comment]
Hi!

> Could this be considered a bug or improvement, or it was just a personal issue?

In fact, this is documented in the Manual:
- https://github.com/kroitor/ccxt/wiki/Manual#overriding-the-nonce
- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/wiki/Manual#authentication

Let us know if you have more questions! I'd close this for now as a duplicate, if you don't mind. Feel free to reopen it if needed.

**Comment by j-a-m-l** [comment]
I read that parts of the manual: it is very useful to have that documented. But my question was more about the policy about that. Shouldn't ccxt use the right kind of nonce generator?
If not, all users are forced to waste time investigating the same problem every time they try a new exchange.
Wouldn't it be better if is in the ccxt codebase? Contributors would help with it.

**Comment by kroitor** [comment]
>  Shouldn't ccxt use the right kind of nonce generator?

For GDAX the default nonce is 1-to-1 identical to your function:
- https://github.com/ccxt/ccxt/blob/master/js/base/Exchange.js#L236
- https://github.com/ccxt/ccxt/blob/master/js/base/Exchange.js#L82

> If not, all users are forced to waste time investigating the same problem every time they try a new exchange.

If you could provide a code snippet to reproduce the problem + your verbose output of it according to this, that would help a lot: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue. Currently, we don't even know the method name that you are calling, and GDAX has rate limits that are different from their documented rate-limits (proof: https://github.com/ccxt/ccxt/issues/794)

Moreover, a request timeout is not a nonce issue at all. It is a connectivity or a rate-limit issue. The nonce issue is usually reported by GDAX with a message like: "Rate limit exceeded"...

You can use the built-in rate limiter from ccxt to limit your requests and avoid problems:

- https://github.com/ccxt/ccxt/blob/master/examples/html/basic-rate-limiting.html
- https://github.com/ccxt/ccxt/blob/master/examples/js/builtin-rate-limiting-rest-poller.js
- https://github.com/ccxt/ccxt/blob/master/examples/js/live-orderbook.js
- https://github.com/ccxt/ccxt/blob/master/examples/js/live-ticker.js (for fetchTicker, GDAX rate-limit does not conform to their docs)...

Search this repo for "enableRateLimit" to find more examples and explanations...

Let me know if the above helps. Thx!

**Comment by kizbitz** [comment]
Adding a note for anyone else that might be searching for a resolution in the future. 

Check your system time. If it's off by a minute you'll get this error. - See: https://github.com/coinbase/coinbase-php/issues/65#issuecomment-147353697

**Comment by kroitor** [comment]
Related: #1265

**Comment by PalvaiArjun** [comment]
Hi Guys,
I am seeing this issue "{\"message\":\"request timestamp expired\"}" with any/all private methods calls, where as public methods are returning status 200.
Below are examples of Public and Private method calls I made.

**Public**: working fine
authedClient.getProductTicker('ETH-USD',
  (error, response, data) => {
        if (error) {
        // handle the error
    } else {
        var i = 0
        var jsonString = JSON.stringify(response)
        fs.writeFile("response.json", jsonString, 'utf-8', function(err) {
                if (err) {
                    return console.log(err);
                }
            })
    }
  });

**Private** : Failed with time-stamp expired
authedClient.getFills(
  (error, response, data) => {
        if (error) {
        // handle the error
    } else {
        var jsonString = JSON.stringify(data)
        fs.writeFile("getFills.json", jsonString, 'utf-8', function(err) {
                if (err) {
                    return console.log(err);
                }
            })
    }
  });

**request_signer.js**
const timestamp = Date.now() / 1000;  //  1516414164.510 => Sun Jan 18 1970 13:13:34 (UTC)

I tried the code with "const timestamp = Date.now()", though this returns present time(Sat Jan 20 2018 02:09:24 (UTC)) I see no success.

Any help is much appreciated.

Thanks
Arjun

**Comment by kroitor** [comment]
@PalvaiArjun is you system clock synchronized frequently (once in 15 minutes or less) ? You timezone should be UTC and the time has to be synched like described here, for example: https://github.com/ccxt/ccxt/issues/850#issuecomment-353774447

**Comment by PalvaiArjun** [comment]
Hi kroitor,
Thanks for the quick response.
I still see the same error. The timezone is (UTC -05:00). The time will sync every 720 seconds. My system time is in sync with https://time.is/ 

After I update my registry and sync time. The expire time and CB-ACCESS-TIMESTAMP are both same time. 

Below is the error message it returns.
{"statusCode":400,"body":"{\"message\":\"request timestamp expired\"}","headers":{"date":"Sat, 20 Jan 2018 04:25:16 GMT","content-type":"application/json; charset=utf-8","content-length":"39","connection":"close","set-cookie":["__cfduid=****; expires=Sun, 20-Jan-19 04:25:16 GMT; path=/; domain=.gdax.com; HttpOnly"],"access-control-allow-headers":"Content-Type, Accept, cb-session, cb-fp","access-control-allow-methods":"GET,POST,DELETE,PUT","access-control-allow-origin":"*","access-control-expose-headers":"cb-before, cb-after","access-control-max-age":"7200","etag":"W/\"27-****\"","strict-transport-security":"max-age=15552000; includeSubDomains; preload","x-content-type-options":"nosniff","expect-ct":"max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"","server":"cloudflare","cf-ray":"3dff44d3bef49f4e-IAD"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"api.gdax.com","port":443,"hostname":"api.gdax.com","hash":null,"search":null,"query":null,"pathname":"/accounts/7d0f7d8e-dd34-4d9c-a846-06f431c381ba/ledger","path":"/accounts/7d0f7d8e-dd34-4d9c-a846-06f431c381ba/ledger","href":"https://api.gdax.com/accounts/7d0f7d8e-dd34-4d9c-a846-06f431c381ba/ledger"},"method":"GET","headers":{"User-Agent":"gdax-node-client","Accept":"application/json","Content-Type":"application/json","CB-ACCESS-KEY":"******","CB-ACCESS-SIGN":"*******","CB-ACCESS-TIMESTAMP":1516422316295,"CB-ACCESS-PASSPHRASE":"******"}}}

**Comment by kroitor** [comment]
@PalvaiArjun you don't seem to be working with GDAX via ccxt... We can't eally comment on `gdax-node-client`.
