### ISSUE TITLE
[bithumb] can't parse PartialFilled Order

### ISSUE THREAD

**Issue by jkjin7** [ccxt/ccxt#7888]
I found a bug that bithumb.js > parseOrder() cannot see filled/remaining amount correctly.
Bithumb does not return filled or remaining amount value by `fetchOrder` not like `fetchOpenOrder`.
So users should parse `contract` to calculate filled/remaining amount as the official doc says, but on the code line around 601 of bithumb.js, there's none of it.
Therefore, ccxt.bithumb does not parse PartialFilled(Canceled) order.

Thank you!

- OS: Ubuntu 18.04
- Programming Language version: js
- CCXT version: 1.33.23

```
        let remaining = this.safeFloat (order, 'units_remaining');
        if (remaining === undefined) {
            if (status === 'closed') {
                remaining = 0;
            } else {
                remaining = amount;
            }
        }
```

```
fetchOrder {
    "order_status": "Cancel",
    "contract": [
        ...some executed trades...
    ]
}
```

**Comment by kroitor** [comment]
Hi @jkjin7 ! Can you please paste your code to reproduce it (a complete snippet, including the exchange instantiation, but without your keys) and your **verbose request + response**? We need that info in order to be able to resolve it quickly.
Please, follow these guides literally:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

**Comment by jkjin7** [comment]
Sorry for that I did not follow the guideline, but it's hard to give full information you requested.
Because, I have solved this problem by using other module instead of ccxt, and reproducing data is prohibited currently by my company's security.
I can only give you some sample code I used to test and a full response of `fetchOrder` when the problem occured.

```
;(async () => {
  console.log(await bithumb.fetchOrder('C0101000000191911363', 'BTC/KRW'))
})()

{
  order_date: '1603161798539254',
  type: 'ask',
  order_status: 'Cancel',
  order_currency: 'BTC',
  payment_currency: 'KRW',
  watch_price: '0',
  order_price: '13344000',
  order_qty: '0.0125',
  cancel_date: '1603161803809993',
  cancel_type: '사용자취소',
  contract: [
    {
      transaction_date: '1603161799976383',
      price: '13344000',
      units: '0.0015',
      fee_currency: 'KRW',
      fee: '0',
      total: '20016'
    }
  ],
  order_id: 'C0101000000191911363'
}
```
