### ISSUE TITLE
AttributeError: module 'ccxtpro' has no attribute 'binance'

### ISSUE THREAD

**Issue by yangzh9106** [ccxt/ccxt#7889]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

https://github.com/ccxt/ccxt/blob/master/FAQ
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of ccxt.version to https://github.com/ccxt/ccxt/blob/master/package.json#L3

OS: Windows 10
Programming Language version: Python 3.7
CCXT version: 1.37.3
CCXTPRO version: 1.0.1
```
import ccxtpro
import asyncio
async def main():
    exchange = ccxtpro.binance({'enableRateLimit': True})
    while True:
          orderbook = await exchange.watch_order_book('ETH/BTC')
          print(orderbook['asks'][0], orderbook['bids'][0])
asyncio.get_event_loop().run_until_complete(main())
```

```
The following line of code throws  AttributeError: module 'ccxtpro' has no attribute 'binance'
```

**Comment by kroitor** [comment]
@yangzh9106 what's the name of your py-file?

**Comment by yangzh9106** [comment]
[
![屏幕截图 2020-10-30 174016](https://user-images.githubusercontent.com/52728728/97689771-0939b600-1ad7-11eb-944d-ed19ab3650bd.png)
](url)
i don't have filenames that looks  like "ccxtpro".

**Comment by kroitor** [comment]
@yangzh9106 you have obtained the ccxt.pro license and have installed it like so: https://github.com/ccxt/ccxt/wiki/ccxt.pro.install right? If you're a customer of CCXT Pro, then installation should be done from the CCXT Pro private repository, which is not available to public. The `pip install ccxtpro` will install a public stub, that is empty – it does not have any functionality and it is there to prevent name squatting. The actual package must be installed from the CCXT Pro private repo according to the installation instructions linked in this message.
@yangzh9106 a question to your: how do you install it?

**Comment by yangzh9106** [comment]
thx, i use" pip install ccxtpro". i will try the other way and check. thank you ~

**Comment by kroitor** [comment]
@yangzh9106 yep, in other words, CCXT is a free open-source product, CCXT Pro is a commercial open-source product. Having the CCXT Pro license you should follow the installation instructions for CCXT Pro. Let us know if that does not answer your question. Feel free to reopen this issue or just ask further questions if any. Don't forget to deinstall the stub `pip uninstall ccxtpro` before reinstalling it properly from the private repo.
