### ISSUE TITLE
load_markets returning empty results on a cloud instance (Python).

### ISSUE THREAD

**Issue by mak-pun** [ccxt/ccxt#7896]
For some reason, it always returns `{}`. I've also tried to generate a new key pair from the exchange as suggested when troubleshooting but that didn't help.

I have tried doing a curl request directly from Digital Ocean instance and it's working fine.

`$ curl "https://api.gemini.com/v1/symbols`
`["btcusd","ethbtc","ethusd","zecusd","zecbtc","zeceth", "zecbch", "zecltc", "bchusd", "bchbtc", "bcheth", "ltcusd", "ltcbtc", "ltceth", "ltcbch", "batusd", "daiusd", "linkusd", "oxtusd", "batbtc", "linkbtc", "oxtbtc", "bateth", "linketh", "oxteth", "ampusd", "compusd", "paxgusd", "mkrusd", "zrxusd", "kncusd", "manausd", "storjusd", "snxusd", "crvusd", "balusd", "uniusd", "renusd", "umausd", "yfiusd", "btcdai", "ethdai", "aaveusd", "filusd", "btceur", "btcgbp", "etheur", "ethgbp"]`

- OS: Ubuntu 18.04.1 LTS (Bionic Beaver)
- Programming Language version: Python 3.6.9 
- CCXT version: 1.37.2

```
import ccxt
import logging
logging.basicConfig(level=logging.DEBUG)

if __name__ == '__main__':

    exchange_id = 'gemini'
    config = {
        'timeout': 30000,
        'enableRateLimit': True,
        'verbose': True,
        "apiKey": "xxx",
        "secret": "xxx",
        "password": "xxx"
    }

    exchange_class = getattr(ccxt, exchange_id)

    connection = exchange_class(config)

    connection.set_sandbox_mode(True)

    markets = connection.load_markets()

    print(markets)
```

The log is quite long so I've pasted it in pastebin.com

```
https://pastebin.com/6EfsK8vW
```

**Comment by kroitor** [comment]
@mak-pun do you have the same issue with the most recent version of CCXT? Make sure your version is 1.37.7 or higher. It has been addressed recently: 

- https://github.com/ccxt/ccxt/issues/7894
- https://github.com/ccxt/ccxt/issues/7874

Let us know if the above does not answer your question. Feel free to reopen this issue or just ask further questions if any.
