### ISSUE TITLE
[binance] fetchLedger missing

### ISSUE THREAD

**Issue by bigcountry-scav** [ccxt/ccxt#7897]
Is there a plan to add fetchLedger to Binance?

- OS: Windows 10
- Programming Language version: JS
- CCXT version: 1.37.7

**Comment by kroitor** [comment]
@bigcountry-scav in short, yes: https://github.com/ccxt/ccxt/wiki/FAQ#when-will-you-add-feature-foo-for-exchange-bar--whats-the-estimated-time-when-should-we-expect-this

**Comment by ttodua** [comment]
it's added already. closing this issue.
