### ISSUE TITLE
How can I fetch positions in my Binance Testnet Account?

### ISSUE THREAD

**Issue by UsmanKhOkhar16** [ccxt/ccxt#7900]
I am using Binance Testnet account, kindly let me know how can I get the details from the positions bar? 
Which Function I can use for fetching Positions details in my binance testnet account?
Kindly help me regarding this.
Thank You.

**Comment by kroitor** [comment]
For Binance you can do that using the fetchBalance() method. Let us know if this example does not answer your question:

- https://github.com/ccxt/ccxt/tree/master/examples/py/binance-futures-potisions.py

```Python
# -*- coding: utf-8 -*-

import ccxt
from pprint import pprint

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.binance({
    'apiKey': 'YOUR_TESTNET_API_KEY',
    'secret': 'YOUR_TESTNET_API_SECRET',
    'enableRateLimit': True,  # https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
    'options': {
        'defaultType': 'future',
    },
})

exchange.set_sandbox_mode(True)  # comment if you're not using the testnet
markets = exchange.load_markets()
exchange.verbose = True  # debug output

balance = exchange.fetch_balance()
positions = balance['info']['positions']
pprint(positions)
```

**Comment by UsmanKhOkhar16** [comment]
@kroitor Thank You
It is working

**Comment by barresoft** [comment]
Now, with version 1.89.99, for SAND/BUSD you can use:

`pprint(exchange.fetch_positions(['SAND/BUSD']))`

**Comment by Elton-gif** [comment]
And for node.js ?

**Comment by DukiChoi** [comment]
@kroitor Thank you so much for the code... I was looking for this for a whole day.
