### ISSUE TITLE
how can we fetch Current market price of BTC on binance exchange?

### ISSUE THREAD

**Issue by UsmanKhOkhar16** [ccxt/ccxt#7901]
How can we fetch current market price of BTC on binance exchange using CCXT.

- Programming language: python
- operating system: windows
- CCXT version: 1.34.5
- pip version: 20.2.4

**Comment by kroitor** [comment]
This is documented in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual

TO work with this library efficiently, I recommend to read the entire Manual from top to bottom at least once – it will save your time, really.

You can fetch the market price using either:

- `fetchTicker()`
- `fetchTickers()`
- `fetchOrderBook()`
- `fetchTrades()`

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.binance({
    'enableRateLimit': True,  # required by the Manual
})

ticker = exchange.fetch_ticker('BTC/USDT')
print(ticker['last'])
```
