### ISSUE TITLE
problem about installing ccxtpro

### ISSUE THREAD

**Issue by yangzh9106** [ccxt/ccxt#7913]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:windows10
- Programming Language version: python 3.7
- CCXT version:1.36.95

I try to install ccxtpro from the git, but fail.
![微信图片_20201102092835](https://user-images.githubusercontent.com/52728728/97821556-d4537c00-1ced-11eb-9b12-1e7d00d0cc81.png)
need help!

**Comment by kroitor** [comment]
Have you got the access to the repo from https://ccxt.pro?

**Comment by yangzh9106** [comment]
i see~ thank you~
