### ISSUE TITLE
how to get the future price of huobipro

### ISSUE THREAD

**Issue by yangzh9106** [ccxt/ccxt#7914]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:windows
- Programming Language version:python3.7
- CCXT version:1.36.95

```
import ccxt
from pprint import pprint

exchange = ccxt.binance({
    'apiKey': '*********',
    'secret': '*********',
    'options': {
        'defaultType': 'future'  # ←------------- defaultType inside options  spot/future
    },
    'enableRateLimit': True,  # required by the Manual
})

symbols = [
    'FIL/USDT'#,'BTC/USDT', 'ETH/USDT', 'ETH/BTC' 
]

```
from the example above, i can get the binance's future price. but it seems doesn't work, when i use "ccxt.okex" or "ccxt.huobipro" 
I also want to know, how to get the swap price~

**Comment by kroitor** [comment]
Huobi DM is not supported yet, only spot markets are available with Huobi Pro, hope to add Huobi DM as soon as possible:

- #5646

**Comment by 1key** [comment]
+1 voor Huobi (pro) Derivates.
Any update on the ETA?
