### ISSUE TITLE
Implement fetchDeposits of bitfinex2

### ISSUE THREAD

**Issue by wehrstedt** [ccxt/ccxt#7920]
- OS: Windows 10
- Programming Language version:Programming Language version: node -v -> v14.15.0
- CCXT version: 1.37.16

Bitfinex v2 supports listing deposits, but the current implementation not. Here is an example output of a small ethereum deposit on my account:
```js
const client = new ccxt.bitfinex2({
	apiKey: "xxx",
	secret: "yyyy"
});

const deposits = await client.client.privatePostAuthRMovementsCurrencyHist({
	currency: "ETH"
});
```

JSON.stringify(deposity, null,4)
```json
[
	[
	  18263729,
	  "ETH",
	  "ETHEREUM",
	  null,
	  null,
	  1604348826000,
	  1604348826000,
	  null,
	  null,
	  "COMPLETED",
	  null,
	  null,
	  0.02397963,
	  0,
	  null,
	  null,
	  "0xvug3npu45xm437sjjyw583cd2f264xpfhzoahmu9",
	  null,
	  null,
	  null,
	  "0xopfog56usqmv2b89mqvfpho5evmrv6biug5vp77m9jvivncdos4wrae36g6zk2d658",
	  null,
	],
  ]
```

Heres the API documentation: [Link](https://docs.bitfinex.com/reference#rest-auth-movements)
Any chances to implement this? :)

**Comment by dmatora** [comment]
still getting bitfinex2 fetchDeposits() is not supported yet
why only fetchTransactions?
