### ISSUE TITLE
Request to fix FTX fetchBalance

### ISSUE THREAD

**Issue by alexanderluce** [ccxt/ccxt#7921]
Request to fix FTX fetchBalance function

The FTX fetchBalance function currently returns the balance of the user account, but does not include account positions. Because of this, when a user makes a trade the asset they purchase is not reflected under fetchBalance, all that is returned is the underlying currency balance that was used to purchase the asset.

https://docs.ftx.com/#get-positions

**Comment by kroitor** [comment]
This functionality will be added as a separate unified method, `fetchPositions()`: https://github.com/ccxt/ccxt/issues/4834

To get positions from FTX in an exchange-specific way, please see these issues:

- https://github.com/ccxt/ccxt/issues/6362#issuecomment-573367512
- https://github.com/ccxt/ccxt/issues/6860
- https://github.com/ccxt/ccxt/issues/7242
- https://github.com/ccxt/ccxt/search?q=ftx+get+positions&type=issues
