### ISSUE TITLE
Wrong okcoin precision

### ISSUE THREAD

**Issue by aurelianito** [ccxt/ccxt#7924]
Using latest python library (installed with pip, version 1.37.18, as informed in `ccxt.__version__`) precision returns a small float instead of an integer for OKCoin markets (as explained in https://github.com/ccxt/ccxt/wiki/Manual#market-structure)

Steps to reproduce:
```
from ccxt import okcoin
okc = okcoin({})
okc.load_markets()
print(okc.market('USDT/USD')['precision'])
```

**Comment by kroitor** [comment]
@aurelianito plz read these notes: https://github.com/ccxt/ccxt/wiki/Manual#methods-for-formatting-decimals, on `exchange.precisionMode`. OKEX as well as a bunch of other exchanges uses the TICK_SIZE precision mode, so the numbers there are floats. Let us know that does not answer your question.
