### ISSUE TITLE
creating a bitfinex order using affiliate code

### ISSUE THREAD

**Issue by eugenioclrc** [ccxt/ccxt#7927]
https://blog.bitfinex.com/affiliate-program/explaining-the-developers-reward/

will this do it?
`api.createOrder(p.market, 'limit', p.side, p.amount, p.price, { meta: { aff_code: 'AFFILIATE_CODE' } });`

**Comment by kroitor** [comment]
@eugenioclrc with Bitfinex v1 (`ccxt.bitfinex`) this should work:

```JavaScript
api.createOrder(p.market, 'limit', p.side, p.amount, p.price, { aff_code: 'AFFILIATE_CODE' });
```

With Bitfinex v2 (`ccxt.bitfinex2`) your code should work:

```JavaScript
api.createOrder(p.market, 'limit', p.side, p.amount, p.price, { meta: { aff_code: 'AFFILIATE_CODE' } });
```

Let us know if that does not answer your question.
