### ISSUE TITLE
Consuming trade-by-trade with watchTrades in a loop

### ISSUE THREAD

**Issue by e36-cicd** [ccxt/ccxt#7929]
Hi,

When handling a while loop in ccxt.pro that awaits on watchTrades, I see that the Array is being filled up to the limit, but it's never cleared. For example, with a tradesLimit of 100, it fills up until 100 and then stops updating.

Do I need to clear it manually or something? I assumed that each value returned from await on watchTrades will provide the next batch of trades, up to tradesLimit...

Thanks!

**Comment by kroitor** [comment]
@e36-cicd the array cache works this way: when you start watching the trades, it's empty. When the exchange sends the next pack of trades, those trades are added to the array cache. It will store up to `exchange.options['tradesLimit']` trades in the cache (the limit is 1000 by default). When a new pack of trades arrives and there's no more space in the cache, it will delete the oldest values and will push the newest values. So it's a rolling window deque, not exactly a list. At any point in time the array cache will contain up to 1000 most recent trades. So, the cache will start filling itself from 0 to 1000 trades and upon reaching 1000 it will start overwriting the oldest trades in FIFO order, like a ring buffer.

When the `watchOrderBook` call is resolved and you get the stored trades (most recent 1000 trades), and then the `since` and `limit` pagination is applied to the trades stored in the cache. If you're not using the pagination params, then you will get all the stored trades to the moment. If you wish to distinguish newly incoming trades from the old trades – you can track those trades by the last received trade id.

Let us know if that does not answer your question.

**Comment by yanirj** [comment]
Hi,

The goal of what I need is on each loop iteration, get only the *new* trades that I haven't seen yet. There can be more than 1 trade on each loop since there are times that there are batches of trades...

So, couple of questions here:
1. The 'since' parameter, at least for binance, is filtering on the 'timestamp' field and not the trade id. I'm looking for a general way to only receive new trades.

So I tried using this code, but it still doesn't work as I expect:

```
let last_ts = 0;
while (true) {
  trades = await exchange.watchTrades(symbol, last_ts, 100);
  // Here I expect trades to be only the new trades that I haven't seen yet, but that's not the case...
  last_ts = trades[trades.length - 1]['timestamp']
}
```

2. I even tried your cli.js to check, and set a limit of '1', so I expected to only receive a single new trade each time, clearing out all older trades, but it seems like this only makes it save the first trade it sees, never handing out any new trades. This is again not what I was expecting.

```
# node examples/js/cli.js binance watchTrades BTC/USDT 0 1
binance.watchTrades (BTC/USDT, 0, 1)
    timestamp |                 datetime |   symbol |        id | order | type | takerOrMaker | side |    price |   amount |          cost | fee
------------------------------------------------------------------------------------------------------------------------------------------------
1604498145082 | 2020-11-04T13:55:45.082Z | BTC/USDT | 451705227 |       |      |        taker |  buy | 13859.68 | 0.539556 | 7478.07350208 |
1 objects
    timestamp |                 datetime |   symbol |        id | order | type | takerOrMaker | side |    price |   amount |          cost | fee
------------------------------------------------------------------------------------------------------------------------------------------------
1604498145082 | 2020-11-04T13:55:45.082Z | BTC/USDT | 451705227 |       |      |        taker |  buy | 13859.68 | 0.539556 | 7478.07350208 |
1 objects
    timestamp |                 datetime |   symbol |        id | order | type | takerOrMaker | side |    price |   amount |          cost | fee
------------------------------------------------------------------------------------------------------------------------------------------------
1604498145082 | 2020-11-04T13:55:45.082Z | BTC/USDT | 451705227 |       |      |        taker |  buy | 13859.68 | 0.539556 | 7478.07350208 |
1 objects
    timestamp |                 datetime |   symbol |        id | order | type | takerOrMaker | side |    price |   amount |          cost | fee
------------------------------------------------------------------------------------------------------------------------------------------------
1604498145082 | 2020-11-04T13:55:45.082Z | BTC/USDT | 451705227 |       |      |        taker |  buy | 13859.68 | 0.539556 | 7478.07350208 |
1 objects
    timestamp |                 datetime |   symbol |        id | order | type | takerOrMaker | side |    price |   amount |          cost | fee
------------------------------------------------------------------------------------------------------------------------------------------------
```

Thanks.

**Comment by e36-cicd** [comment]
Hi,

The goal of what I need is on each loop iteration, get only the *new* trades that I haven't seen yet. There can be more than 1 trade on each loop since there are times that there are batches of trades...

So, couple of questions here:
1. The 'since' parameter, at least for binance, is filtering on the 'timestamp' field and not the trade id. I'm looking for a general way to only receive new trades.

So I tried using this code, but it still doesn't work as I expect:

```
let last_ts = 0;
while (true) {
  trades = await exchange.watchTrades(symbol, last_ts, 100);
  // Here I expect trades to be only the new trades that I haven't seen yet, but that's not the case...
  last_ts = trades[trades.length - 1]['timestamp']
}
```

2. I even tried your cli.js to check, and set a limit of '1', so I expected to only receive a single new trade each time, clearing out all older trades, but it seems like this only makes it save the first trade it sees, never handing out any new trades. This is again not what I was expecting.

```
# node examples/js/cli.js binance watchTrades BTC/USDT 0 1
binance.watchTrades (BTC/USDT, 0, 1)
    timestamp |                 datetime |   symbol |        id | order | type | takerOrMaker | side |    price |   amount |          cost | fee
------------------------------------------------------------------------------------------------------------------------------------------------
1604498145082 | 2020-11-04T13:55:45.082Z | BTC/USDT | 451705227 |       |      |        taker |  buy | 13859.68 | 0.539556 | 7478.07350208 |
1 objects
    timestamp |                 datetime |   symbol |        id | order | type | takerOrMaker | side |    price |   amount |          cost | fee
------------------------------------------------------------------------------------------------------------------------------------------------
1604498145082 | 2020-11-04T13:55:45.082Z | BTC/USDT | 451705227 |       |      |        taker |  buy | 13859.68 | 0.539556 | 7478.07350208 |
1 objects
    timestamp |                 datetime |   symbol |        id | order | type | takerOrMaker | side |    price |   amount |          cost | fee
------------------------------------------------------------------------------------------------------------------------------------------------
1604498145082 | 2020-11-04T13:55:45.082Z | BTC/USDT | 451705227 |       |      |        taker |  buy | 13859.68 | 0.539556 | 7478.07350208 |
1 objects
    timestamp |                 datetime |   symbol |        id | order | type | takerOrMaker | side |    price |   amount |          cost | fee
------------------------------------------------------------------------------------------------------------------------------------------------
1604498145082 | 2020-11-04T13:55:45.082Z | BTC/USDT | 451705227 |       |      |        taker |  buy | 13859.68 | 0.539556 | 7478.07350208 |
1 objects
    timestamp |                 datetime |   symbol |        id | order | type | takerOrMaker | side |    price |   amount |          cost | fee
------------------------------------------------------------------------------------------------------------------------------------------------
```

Thanks.

**Comment by kroitor** [comment]
@e36-cicd hold on, i will post an example shortly.

**Comment by kroitor** [comment]
@e36-cicd let me know if this example does not answer your question or if you have difficulties with it:

- https://github.com/ccxt/ccxt/blob/master/examples/ccxt.pro/js/watch-new-trades.js

```JavaScript
'use strict';

const ccxtpro = require ('ccxt.pro');

(async () => {

    const streams = {
        'binance': 'BTC/USDT',
        'okex': 'BTC/USDT'
    };

    await Promise.all (Object.keys (streams).map (exchangeId =>

        (async () => {

            const exchange = new ccxtpro[exchangeId] ({
                enableRateLimit: true,
                options: {
                    tradesLimit: 100, // lower = better, 1000 by default
                },
            })
            const symbol = streams[exchangeId]
            let lastId = ''
            while (true) {
                console.log ('---')
                try {
                    const trades = await exchange.watch_trades (symbol)
                    for (let i = 0; i < trades.length; i++) {
                        const trade = trades[i]
                        if (trade['id'] > lastId) {
                            console.log (exchange.iso8601 (exchange.milliseconds ()), exchange.id, trade['symbol'], trade['id'], trade['datetime'], trade['price'], trade['amount'])
                            lastId = trade['id']
                        }
                    }
                } catch (e) {
                    console.log (symbol, e)
                }
            }

        }) ())
    )
}) ()
```

**Comment by kroitor** [comment]
@e36-cicd we're also working on a mode that will return just the new trades.

**Comment by e36-cicd** [comment]
That snippet worked, thanks. I was trying to avoid having to traverse an array on each update, so I'm looking forward for your new mode.

May I suggest that you have new mode like that but for order book deltas as well? We'd like to be able to receive only the updated book levels upon each iteration instead of simply the snapshot of the book on each iteration...

**Comment by e36-cicd** [comment]
Hi,

We ran into an issue with Bitmex using that solution. The trade IDs aren't simply numbers, but UUID strings. Can you please explain how should we handle it for Bitmex exactly?

Thanks

**Comment by kroitor** [comment]
@e36-cicd will post an example here asap.

**Comment by kroitor** [comment]
@e36-cicd Please, check the example below. It will work universally for all exchanges. It will return just the new trades on every iteration of the watch-loop. Let us know if this does not help:

- https://github.com/ccxt/ccxt/blob/master/examples/ccxt.pro/py/consume-all-trades.py

```Python
import ccxtpro
from asyncio import get_event_loop


async def consume_all_trades(exchange, symbol):
    await exchange.load_markets()
    while True:
        try:
            trades = await exchange.watch_trades(symbol)
            print('----------------------------------------------------------------------')
            print(exchange.iso8601(exchange.milliseconds()), 'received', len(trades), 'new', symbol, 'trades:')
            for trade in trades:
                print(exchange.id, symbol, trade['datetime'], trade['amount'], trade['price'])
            exchange.trades[symbol].clear()
        except Exception as e:
            print(type(e).__name__, str(e))
    await exchange.close()


loop = get_event_loop()
exchange = ccxtpro.bitmex({
    'enableRateLimit': True,
    'asyncio_loop': loop,
})

symbol = 'BTC/USD'

loop.run_until_complete(consume_all_trades(exchange, symbol))
```
