### ISSUE TITLE
Big latency placing/canceling orders with IDEX

### ISSUE THREAD

**Issue by Avarong** [ccxt/ccxt#7931]
I have ping about 5ms with exchange. But when i place or cancel order, i have ~700ms latency, that is very large and a problem for hft. How can i lower it? Suppose «await self.load_markets()» may add a latency and i can not find body of «self.privatePostOrders(request)» with pycharm. Where may i see it?

- OS: Windows Server 2012r2
- Programming Language version: Python 3.8
- CCXT version: 0.4.53

```
client = ccxtpro.idex({'enableRateLimit': False,
    'apiKey': api_key,
    'secret': secret,
    'walletAddress': address,
    'privateKey': private_key,
    'verbose': False,  # switch it to False if you don't want the HTTP log
})
order=await client.create_order('UBT/ETH','limit','sell',500,0.01065)
await client.cancel_order(order['id'])
```

**Comment by Avarong** [comment]
Oh, it bacame even greater, when i added 2 markets for trading. 1400-1600ms! And it stayed the same, when I ended trading 3 markets and continued with 1. May be async_client is not asynchronous in some points? I have 5ms ping, so latency should be 12-13ms at all, regardless of the number of markets.

**Comment by kroitor** [comment]
Hi!

> and i can not find body of «self.privatePostOrders(request)» with pycharm. Where may i see it?

This is documented here: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

> I have ping about 5ms with exchange. But when i place or cancel order, i have ~700ms latency, that is very large and a problem for hft. How can i lower it? Suppose «await self.load_markets()» may add a latency

You need the info about the markets in order to create the order properly.

You can have this program:

```Python
exchange = ccxt.exchange(...)
result = exchannge.create_order(...)
```

Which is identical to this program:

```Python
exchange = ccxt.exchange(...)
markets = exchange.load_markets()
result = exchange.create_order(...)
```

The `create_order` call will load the markets, if you don't call it by hand. Also, if the markets are already loaded, that call does nothing and returns immediately.

This is explained in the Manual here: https://github.com/ccxt/ccxt/wiki/Manual#loading-markets

So, if you relaunch your program over and over, it will destroy the exchange and all the loaded markets. And it will have to reload the markets everytime, that will cause some of the delay. In order to avoid this, it is highly recommended to follow the Manual closely, most of these aspects are documented there. Instead of relaunching your program externally, restructure the code to run the relaunch the logic inside the program itself to reuse the exchange instance. In pseudocode that would look like so:

```Python
exchange = ccxt.exchange(...)
while True:
    if should_create_order:
        markets = exchange.load_markets()  # preloads markets just once
        result = exchange.create_order(...)  # reuse the exchange to avoid reloading markets
    else if should_do_something_else:
        do_something_else()
    else:
        exchange.sleep()
```

-------------------------------------------------------------------------------

In order to resolve this issue, I'd suggest to measure the time taken by the `create_order` call, having preloaded the markets, with the rate-limiter turned off.

```Python
client = ccxtpro.idex({
    'enableRateLimit': True,  # https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
    'apiKey': api_key,
    'secret': secret,
    'walletAddress': address,
    'privateKey': private_key,
})
await exchange.load_markets()
print('Sleeping before measuring the time...')
await exchange.sleep(5000)
print('Done sleeping before measuring the time...')
exchange.enableRateLimit = False  # turn it off to measure this call
exchange.verbose = True
started = exchange.milliseconds()
order = await client.create_order('UBT/ETH','limit','sell',500,0.01065)
exchange.enableRateLimit = True
elapsed = exchange.milliseconds() - started
print('Elapsed time:', elapsed)
```

Also, have you tried any type of profiling for your code above?

**Comment by Avarong** [comment]
Elapsed time: 821

It is interesting, that latency from my PC(with windows10) is smaller, than from server(Elapsed time: 331). And it is close to my ping from PC(100-400ms). So, it can be a problem working with windows server??

PS. I do not use some libraries for profiling, just measure as in your snippet.

**Comment by kroitor** [comment]
@Avarong we are investigating on our side, and we may have to optimize the ECDSA implementation, will be back to you with our findings asap.

**Comment by Avarong** [comment]
Can you tell me, if your "ECDSA implementation" is connected with windows server properties and cause a latency and i should just wait? Because i have strange situation. 250-300ms from my PC(with ping ~100ms), 700+ms from windows server 2012r2(ping 5ms) and i tryed from another server, but i can not install web3 because it wants visual studio, but visual studio do not installs, because it does not support windows server 2012(without r2) and it is quit difficult for me to install new windows... So it is very hard to understand, what should i do at all(

**Comment by kroitor** [comment]
@Avarong i suggest to some more thorough profiling to locate the cause:

```Python
import ccxtpro
from asyncio import get_event_loop

print('CCXT Pro Version', ccxtpro.__version__)

class idex(ccxtpro.idex):
    def sign(self, path, api='public', method='GET', params={}, headers=None, body=None):
        started = self.milliseconds()
        result = super(idex, self).sign(path, api, method, params, headers, body)
        elapsed = self.milliseconds () - started
        print('Signing time:', elapsed)
        return result

    async def fetch(self, url, method='GET', headers=None, body=None):
        started = self.milliseconds()
        result = await super(idex, self).fetch(url, method, headers, body)
        elapsed = self.milliseconds () - started
        print('Fetching time:', elapsed)
        return result


async def main(loop):
    exchange = idex({
        'asyncio_loop': loop,
        'enableRateLimit': True,  # https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
        'apiKey': '',
        'secret': '',
        'walletAddress': '',
        'privateKey': '',
    })
    await exchange.load_markets()
    print('Sleeping before measuring the time...')
    await exchange.sleep(5000)
    print('Done sleeping before measuring the time...')
    exchange.enableRateLimit = False  # turn it off to measure this call
    exchange.verbose = True
    started = exchange.milliseconds()
    order = await exchange.create_order('UBT/ETH','limit','sell',100000,0.01065)
    exchange.enableRateLimit = True
    elapsed = exchange.milliseconds() - started
    print('Total elapsed time:', elapsed)


loop = get_event_loop()
loop.run_until_complete(main(loop))
```

↑ Please, paste your output with this snippet

**Comment by Avarong** [comment]
From my PC(windows10):
"
CCXT Pro Version 0.4.53

Signing time: 0
Fetching time: 683
Signing time: 0
Fetching time: 123
Sleeping before measuring the time...
Done sleeping before measuring the time...
Signing time: 0

Request: POST https://api.idex.io/v1/orders {'Content-Type': 'application/json', 'IDEX-API-Key': xxx...}

Response: POST https://api.idex.io/v1/orders 200 <CIMultiDictProxy('Date': 'Sat, 07 Nov 2020 07:17:28 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'IDEX REST API', 'Access-Control-Allow-Credentials': 'true', 'Content-Encoding': 'gzip', 'IDEX-Request-ID': xxx...}
Fetching time: 180
Total elapsed time: 294
"
==========================

From my server(windows server 2012r2):
"
CCXT Pro Version 0.4.53

Signing time: 0
Fetching time: 198
Signing time: 0
Fetching time: 41
Sleeping before measuring the time...
Done sleeping before measuring the time...
Signing time: 0

Request: POST https://api.idex.io/v1/orders {'Content-Type': 'application/json', 'IDEX-API-Key': xxx...}

Response: POST https://api.idex.io/v1/orders 200 <CIMultiDictProxy('Date': 'Sat, 07 Nov 2020 07:25:18 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Server': 'IDEX REST API', 'Access-Control-Allow-Credentials': 'true', 'Content-Encoding': 'gzip', 'IDEX-Request-ID': xxx...}
Fetching time: 131
Total elapsed time: 691
"

**Comment by Avarong** [comment]
By the way. I have Python 3.7 on my PC and 3.8 on server.

**Comment by frosty00** [comment]
@kroitor the signing happens inside the `createOrder` not in `sign`

**Comment by kroitor** [comment]
@Avarong from your output it looks like most of the time is eaten inside `createOrder` before sending the call to IDEX, we will try to optimize it and will get back to you asap. Under Windows the time differs by two or more times because the of the underlying code differences. This is not in the scope of CCXT, most of the time is eaten inside the dependency code, but we will try to optimize it and will be back to you as soon as possible. Thx for your feedback!

**Comment by Avarong** [comment]
Ok, thank you, i'm waiting.

**Comment by Avarong** [comment]
Hi! How is it going? Is any progress? Tell please, when do you plan to end this work?

**Comment by frosty00** [comment]
We will get to it, maybe this week or the next

**Comment by Avarong** [comment]
Hi. 2 weeks passed. Is any difficulties to fix that?

**Comment by frosty00** [comment]
@Avarong I'm working on it now!

**Comment by ttodua** [comment]
anyone who had this issue, please update to latest CCXT version and if there are still problems, feel free to re-open the issue.
