### ISSUE TITLE
fetch_tickers only responds with a list

### ISSUE THREAD

**Issue by alvarolloret** [ccxt/ccxt#7932]
- OS: WSL
- Programming Language version: Python3.7
- CCXT version:  1.34.46

When using the command `fetch_tickers()` in binance exchange we are supposed to get all tickers. However, we only get a list of tickers without the info.
     exchange.binance.fetch_tickers()

Ouptut expected: { 'BTC/USDT': {'info' : ..., 'ask': ...}, 'BTC/ETH':  {'info' : ..., 'ask': ...}}
Output recieved: ['BTC/USDT', 'BTC/ETH' ...] (only a list)

**Comment by kroitor** [comment]
@alvarolloret please update to the most recent version of CCXT 1.37.27+ and let us know if you have the same issue with it:

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
