### ISSUE TITLE
Bittrexx BAD_REQUEST 

### ISSUE THREAD

**Issue by presence35** [ccxt/ccxt#7933]
- OS: linux
- Programming Language version: php
- CCXT version: latest

```
$orders = $exchange->fetchOpenOrders(null,null,100);

```

```
bittrex {"code":"BAD_REQUEST","detail":"Refer to the data field for specific field validation failures.","data":{"invalidRequestParameter":"type"}}

But it's receiving my orders properly, so I'm not sure why there error is happening.
```

**Comment by kroitor** [comment]
@presence35 please, paste your output in verbose mode:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by presence35** [comment]
Attached verbose. Thanks.
[output.txt](https://github.com/ccxt/ccxt/files/5502113/output.txt)
