### ISSUE TITLE
[Bitmax] Bitmax myTrades not supported yet

### ISSUE THREAD

**Issue by makarid** [ccxt/ccxt#7934]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Ubuntu 18.04
- Programming Language version: Javascript
- CCXT version: 1.37.27

```
REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS
```
let mytrades = await bitmax.fetchMyTrades(symbol)

console.log(mytrades)

```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
```
(node:24663) UnhandledPromiseRejectionWarning: NotSupported: 0 fetchMyTrades not supported yet

Hello, do you considering adding this feature.Thanks

**Comment by kroitor** [comment]
Hi! BitMax does not have an endpoint for the `fetchMyTrades` call. It has `fetchOrder`, `fetchOrders`, `fetchOpenOrders`, `fetchClosedOrders`, etc... See the `exchange.has` metainfo for BitMax:

```JavaScript
const ccxt = require('ccxt')
const exchange = new ccxt.bitmax({ enableRateLimit: true })
console.log(exchange.has)
```

- https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties
