### ISSUE TITLE
[IDEX] TypeError on fetchBalances of not linked address

### ISSUE THREAD

**Issue by krychla1** [ccxt/ccxt#7936]
- OS: Win10
- Programming Language version: node
- CCXT version: 1.37.27

When trying to fetch balances of an address not linked to an account, improper exception is raised.

```
idex GET https://api-sandbox.idex.io//v1/balances?nonce=xxx&wallet=xxx  401 Unauthorized 
Response:
 {
  'Access-Control-Allow-Credentials': 'true',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Type': 'application/json',
  Date: 'Thu, 05 Nov 2020 16:17:13 GMT',
  'Idex-Request-Id': '9a2SnT_u',
  Server: 'IDEX REST API',
  'Transfer-Encoding': 'chunked'
} 
 {"code":"WALLET_NOT_ASSOCIATED","message":"The wallet requested has not been associated with this account.  Associate it then try again."}
```
```

TypeError: Cannot read property 'slice' of undefined
    at idex.signMessage (node_modules\ccxt\js\base\Exchange.js:1368:70)
    at idex.signMessageString (node_modules\ccxt\js\base\Exchange.js:1374:32)
    at idex.associateWallet (node_modules\ccxt\js\idex.js:864:32)
    at idex.fetchBalance (node_modules\ccxt\js\idex.js:571:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
Expected:
Response error code or error message in the exception.

**Comment by frosty00** [comment]
> idex GET https://api-sandbox.idex.io//v1/balances?nonce=xxx&wallet=xxx  401 Unauthorized 

> 1.37.27

it looks like your version of ccxt is outdated. can you update to the latest version of ccxt and try again

**Comment by kroitor** [comment]
@krychla1 

```JavaScript
const ccxt = require('ccxt')
console.log (ccxt.version)
```

Let us know if you have this issue with the most recent version 1.37.27+

**Comment by krychla1** [comment]
I updated it just before submitting this bug, guys you're quick :D 

Unfortunately, also 1.37.28 has the same issue.

**Comment by kroitor** [comment]
@krychla1 i mean, you're testing the runtime version number, as shown in my previous post above, right? In other words, you're printing it to console inside your program, right?

**Comment by krychla1** [comment]
Yes, both console.log(ccxt.version) and npm list ccxt are equal -> 1.37.28

**Comment by kroitor** [comment]
@krychla1 we will debug and will be back to you with a fix as soon as we can. Thanks!

**Comment by krychla1** [comment]
Hi kroitor. 
I've been digging around the stack trace, particulary wondering why signMessage is in fetchBalances. 
I had no idea ccxt grew to create ethereum signatures. Nice one! Of course I haven't provided my privateKey into the ccxt instantiation. By providing it, it passes.

So you can skip the debug, sorry for trouble. Although a simple check/error on missing secrets could make things more clear in the future.
