### ISSUE TITLE
Calculator

### ISSUE THREAD

**Issue by cadmufasa** [ccxt/ccxt#7945]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Linux
- Programming Language version: Python 2.7
- CCXT version:1.34.38

```
REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS
N/A
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
`N/A

Hi,

Is there a function available that will allow one to convert USD to BTC (as an example)? Would be looking for similar results when using ETH/USD, XRP/USD, etc.

TIA

**Comment by kroitor** [comment]
I've posted an example of such a function here: https://github.com/ccxt/ccxt/issues/7944#issuecomment-723648470
