### ISSUE TITLE
Setting Stop Loss for trades that  are to be leveraged

### ISSUE THREAD

**Issue by cadmufasa** [ccxt/ccxt#7946]
Hi - sorry for duplicate on the last issue.

Basically, I found this information here which is straight forward to determine how much one could loose (liquidation_level/liquidation_amount) should they choose a certain amount of leverage a  https://help.mycoinstory.com/hc/en-us/articles/360040573012-Liquidation

I was wondering 2 things :
1. What functionality can one use to find the amount of leverage currently associated to a currency pair (ex: can I execute something that will allow me to see that 10X is associated with BTC/USDT)? 

2. What is the best way for one to set a stop_loss for a potential trade when they have calculated the whereby the liquidation_level/liquidation_amount has been calculated (but an order has not been created - so - a position does not exist). 

For example, for a trade where I want to spend 200 USD, I might decide to use 30X leverage. So, this would be an amount I would have to spend  (in total) would be 6000 USD. 

If I use 6000 USD to buy BTC for $15000 (expecting it to go up) - but - instead it goes down to $14990, one would think that they have lost only $10. But, since a leverage of 30X has been used, it would be more than that.
 
What would be the value? How can one calculate this in advance before a position has been created (again, that number would be used to set a stop loss). For example, I might only wish to lose a maximum of $50.

TIA

**Comment by ttodua** [comment]
This issue has been stale, so closing for now. if still wanted any help, let us know.

for future readers: 
1) after loading exchange, the markets could have set `min/max` leverage values. if not, then try a dedicated method `fetchLeverageTiers` to see max leverage values
2) see embedded [`stopLoss`](https://docs.ccxt.com/#/README?id=stoploss-and-takeprofit-orders-attached-to-a-position) or a dedicated [`stopLossPrice`](https://docs.ccxt.com/#/README?id=stop-loss-orders) to have a stop-loss.
about calculations, it should be done on user-side
