### ISSUE TITLE
Unable to fetchOrderbook from futures markets (USDT-futures)

### ISSUE THREAD

**Issue by JanssensKobe** [ccxt/ccxt#7949]
Since half an hour I'm unable to fetch the orderbook from futures pairs. I've also tried the function 'fetchTicker' but I got the same error. I'm running the last ccxt version. I'm still able to fetch the orderbooks for spot markets.

Code:
```python
import ccxt

connection = ccxt.binance({
    'apiKey': 'xxx',
    'secret': 'xxx',
    'enableRateLimit': True
})

connection.options['defaultType'] = 'future'

connection.load_markets()
orderbook = connection.fetch_order_book('BTC/USDT')
```
Error:
```
Traceback (most recent call last):
  File "fetchOrderbook.py", line 12, in <module>
    orderbook = connection.fetch_order_book('BTC/USDT')
  File "/home/kobej/.local/lib/python3.8/site-packages/ccxt/binance.py", line 1019, in fetch_order_book
    market = self.market(symbol)
  File "/home/kobej/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1818, in market
    raise BadSymbol('{} does not have market symbol {}'.format(self.id, symbol))
ccxt.base.errors.BadSymbol: binance does not have market symbol BTC/USDT
```

System Info:
Operating System: Manjaro Linux
KDE Plasma Version: 5.20.2
KDE Frameworks Version: 5.75.0
Qt Version: 5.15.1
Kernel Version: 5.8.18-1-MANJARO
OS Type: 64-bit
Processors: 12 × Intel® Core™ i7-9750H CPU @ 2.60GHz
Memory: 15.6 GiB of RAM
Graphics Processor: GeForce RTX 2070 with Max-Q Design/PCIe/SSE2

CCXT Version: 
1.37.50

**Comment by kroitor** [comment]
They changed the output of those endpoints a bit, will fix this shortly.

**Comment by kroitor** [comment]
@JanssensKobe should be ok in 1.37.51+, thx for the feedback, appreciate it!
