### ISSUE TITLE
"binance does not have market symbol BTC/USDT" from binance futures

### ISSUE THREAD

**Issue by bongkook** [ccxt/ccxt#7950]
When I use binance futures I get the following error from yesterday.
Error: binance does not have market symbol BTC/USDT
It looks like the symbol has changed.
I would appreciate it if you can check.

- OS:
- Programming Language version: node.js
- CCXT version: 1.37.50

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/7949

Fixed in CCXT 1.37.51+

**Comment by bongkook** [comment]
Thank you very much!

**Comment by rafaelfaria** [comment]
That still happens to me.

```
es/ccxt/dist/cjs/src/base/Exchange.js:3002
        throw new errors.BadSymbol(this.id + ' does not have market symbol ' + symbol);
              ^

BadSymbol: bybit does not have market symbol BTC/USDT
```

or 

```
ccxt/dist/cjs/src/binance.js:1567
        throw new errors.BadSymbol(this.id + ' does not have market symbol ' + symbol);
              ^

BadSymbol: binance does not have market symbol BTC/USDT
```


I do call `loadMarkets()` before hand then

```
const historicalData = await exchangeInstance.fetchOHLCV('BTC/USDT', '1m','1683349628728');
```

**Comment by rafaelfaria** [comment]
apparently the problem is the proxy.
