### ISSUE TITLE
Does CCXT Pro auto reconnect on error?

### ISSUE THREAD

**Issue by icytrader** [ccxt/ccxt#7951]
Hi from time to time I have been experiencing "NetworkError: connection closed by remote server, closing code 1006" on my websocket connections so I am looking into how the client is handling this event.

Reading the source code of onClose and onError methods: https://github.com/kroitor/ccxt.pro/blob/master/js/base/Client.js, I can't find any handlers about auto reconnection.  Would appreciate if you can help me understand whether and how the client is doing the auto reconncetions. 

Thanks

- OS: Windows
- Programming Language version: Node.JS
- CCXT version:

**Comment by kroitor** [comment]
@icytrader basically, if the connection is dropped, you should catch the NetworkError exception and your next call to a `watch*-method` should reconnect for you in the background (unless a working connection is already established). Let us know if that does not answer your question or if you have difficulties with it. Feel free to reopen this issue or just ask further questions if any.
