### ISSUE TITLE
FetchMyTrades not including OTC (token conversions)

### ISSUE THREAD

**Issue by cipiasentini** [ccxt/ccxt#7952]
- OS: Ubuntu 20.04
- Programming Language version: Javascript
- CCXT version: 1.34.25

```
let ccxt_exchange = new ccxt[exchange] ({
        headers: {
          'FTX-SUBACCOUNT': subaccount,
        },
        password: password,
        apiKey: key,
        secret: secret,
        timeout: 30000,
        enableRateLimit: true,
})

let limit = ccxt_page_limit ? ccxt_page_limit : 100;
let symbol = market;
trades = await ccxt_exchange.fetchMyTrades(symbol, since, limit, exchange_params);   


```
There's no problem with the response other than (for FTX for instance) when I go manually to gather all the trades from my subaccount I also get the trades that are 'OTC' (these are the tokens conversions). But on the response from the api call I am not getting those trades.

I know that using the FTX API I can get the 'conversions' using ```GET /otc/quotes/{quoteId}``` but this request won't return me the timestamp either.

What I want to accomplish is generating my balance at a given point in time. That's why I need all trades, deposits, withdrawals and convertions. I can get the first three without any problem, the issue is with the latter.

**Comment by ttodua** [comment]
FTX has been gone , and imo `fetchBalance` is also what the users could use in such case. so, i'm closing this issue for now. if anyone experiences any related issue again, let us know.
