### ISSUE TITLE
[cex] error mapping

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#7953]
`ExchangeError: cex {"error":"rate limit exceeded"}` - needs mapping... but the code already exists (is it a case sensitivity thing?)

            'exceptions': {
                'exact': {},
                'broad': {
                    'Insufficient funds': InsufficientFunds,
                    'Nonce must be incremented': InvalidNonce,
                    'Invalid Order': InvalidOrder,
                    'Order not found': OrderNotFound,
                    'Rate limit exceeded': RateLimitExceeded,
                    'Invalid API key': AuthenticationError,
                    'There was an error while placing your order': InvalidOrder,
                    'Sorry, too many clients already': DDoSProtection,
                },
            },

**Comment by kroitor** [comment]
> but the code already exists (is it a case sensitivity thing?)

Yes, but more so, it's an errorlist inconsistency / API doc inconsistency thing.
