### ISSUE TITLE
Bitmex Testnet Positions

### ISSUE THREAD

**Issue by UsmanKhOkhar16** [ccxt/ccxt#7955]
I am using Bitmex Testnet Exchange. I want to find positions details programmatically. Kindly provide me code or function so that I could be able to find this.
Language: Python
CCXT version: 1.34.5
Thank You
Regards
Usman Khokhar

**Comment by kroitor** [comment]
Hi!

You can do it with the most recent version of CCXT 1.37.61+ like so:

```
import ccxt
from pprint import pprint


print('CCXT Version:', ccxt.__version__)

exchange = ccxt.bitmex({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,
})

markets = exchange.load_markets()

# exchange.verbose = True  # uncomment for debugging purposes if it does not work

positions = exchange.fetch_positions()
pprint(positions)
```

Make sure your version is up to date. Let us know if the above does not help.
