### ISSUE TITLE
Expires time set in the past

### ISSUE THREAD

**Issue by jimmi199** [ccxt/ccxt#7956]
Hello all,

ok so basically I have been running my ccxt based script on a google cloud server for ages without any problem at all. Now I have moved all of my scripts to a raspberry pi and I am getting a specific issue.

basically I keep geeting timedout becuase it says that my expires time is set in the past. Below is a snippet of the code I am running. I tried to synchrnooise the clock of my raspberry pi to a NTP server which has had a positvie affect and I get much less timeouts however they continue to happen every now and then. the error is the following:

`{'error': {'message': 'This request has expired - expires is in the past. Current time: 1534543214', 'name': 'HTTPError'}}`

My question is could someone please tell me how to set the expires time futher in the future in the exchange.private_get_position function? im not sure how to pass it parameters or what syntax to use.

`  position = exchange.private_get_position()`
   `gain = position[1]['unrealisedRoePcnt']`

THank you in advance

**Comment by kroitor** [comment]
Unfortunately, Raspberry Pi is a 32-bit system, where many exchanges will require 64-bit timestamps. Therefore 64-bit integers get an overflow and truncation down to 32-bit values, which will always lead to expired timestamps in the past. This has been answered here: https://github.com/ccxt/ccxt/issues/5978
Let us know if that does not answer your question.

**Comment by jimmi19** [comment]
Hi thanks for your reply. I am using a raspberry pi 4 which has a Broadcom BCM2711, Quad core Cortex-A72 (ARM v8) 64-bit SoC @ 1.5GHz. Maybe it's my OS. I have raspbian installed which now that I think about it I'm not sure if it's 32-bit or 64-bit. I will check it out and let you know.

Thanks again.
