### ISSUE TITLE
FetchOpenOrders on Binance futures

### ISSUE THREAD

**Issue by jortiexx** [ccxt/ccxt#7957]
- OS: Centos
- Programming Language version: PHP
- CCXT version: 1.37.59

```
$exchange_id = 'binance';
$exchange_class = "\\ccxt\\$exchange_id";
$binance = new $exchange_class(array(
    'apiKey' => 'aaaaaaaaaa',
    'secret' => 'aaaaaaaaaaa',
    'timeout' => 30000,
    'enableRateLimit' => true,
    'options' => array('defaultType' => "future")
));

$binance->load_markets();
$balance = $binance->fetch_open_orders('LTCUSDT');
print_r ($balance);
```

```
Empty array
```

This code only shows open spot positions. How can I fetch my open futures positions?

**Comment by kroitor** [comment]
@jortiexx please, update your CCXT to version 1.37.59+. Binance has updated their API two days ago:

- https://github.com/ccxt/ccxt/issues/7950
- https://github.com/ccxt/ccxt/issues/7949
