### ISSUE TITLE
How to use scrape_candles_to_csv on Binance Futures data

### ISSUE THREAD

**Issue by Kalelv45** [ccxt/ccxt#7958]
- OS: MacOS Mojave
- Programming Language version: Python 
- CCXT version: 1.25

how can I make sure that the data pulled is from Binance Futures market?

```python
binance = ccxt.binance ({'options': {'defaultType': 'future',}})
scrape_candles_to_csv('BTC_USDT_5m_binance.csv', 'binance', 500, str(k), '5m', '2020-11-01T00:00:00Z', 750)
```

right now it pulls the data from the spot market

**Comment by kroitor** [comment]
Please, update your CCXT version to 1.37.59+: https://github.com/ccxt/ccxt/issues/7957#issuecomment-725636215

**Comment by Kalelv45** [comment]
it still downloads the spot market data. Can you write an example on how can I download 5m candles of BTC / USDT on binance futures market (python)

**Comment by kroitor** [comment]
@Kalelv45 have you figured it out?
