### ISSUE TITLE
Same symbol in different exchange with different name

### ISSUE THREAD

**Issue by leoplct** [ccxt/ccxt#796]
Binance --> IOTA/ETH
Bitfinex --> IOT/ETH

or

Bittrex BTC/USDT
Bitfinex BTC/USD

These two symbols refer to the same exchange rate. How do deal with only one symbol?

**Comment by kroitor** [comment]
> Binance --> IOTA/ETH
> Bitfinex --> IOT/ETH

IOTA is correct, IOT is a mistake. This was fixed.

> Bittrex BTC/USDT
> Bitfinex BTC/USD

USDT is **not the same** as USD. This pair will not be corrected. Please read about the differences between Tether USD and USD. Bittrex has BTC/USDT only, whereas Bitfinex supports both types of currencies (funding) and trades BTC/USD.

On USDT/Bitfinex you probably want to read this: https://www.reddit.com/r/bitfinex/
