### ISSUE TITLE
FTX conditional order price update

### ISSUE THREAD

**Issue by mlshin** [ccxt/ccxt#7961]
Programming Language version: Python 3.7 ( 64bit)
CCXT version: 1.37.59
FTX market

Hi
How can i update the price of conditional trigger orders without delete it ?
I am using the Stop limit order and try to update the price.

This is my place trigger method
`                    side = input1
                    stopPrice = input2
                    quantity = input3
                    orderid=0
                    limitPrice=None
                   `

` orderid = self.exchange.createOrder(self.symbol, "stop", side, quantity, limitPrice, { "triggerPrice": stopPrice })["info"]["id"]`

**Comment by kroitor** [comment]
1. update to CCXT 1.37.63+
2. use `editOrder` like so:

```Python
from pprint import pprint

order = self.exchange.create_order(self.symbol, "stop", side, quantity, limitPrice, { "triggerPrice": stopPrice })

edited_order = self.exchange.edit_order(order['id'], order['symbol'], order['type'], order['side'], order['amount'], None, {
    'triggerPrice': 12345.67,  # your new price here
})

pprint(edited_order)
```

Let us know if that helps or not.
Thx!

**Comment by mlshin** [comment]
> 1. update to CCXT 1.37.63+
> 2. use `editOrder` like so:
> 
> ```python
> from pprint import pprint
> 
> order = self.exchange.create_order(self.symbol, "stop", side, quantity, limitPrice, { "triggerPrice": stopPrice })
> 
> edited_order = self.exchange.edit_order(order['id'], order['symbol'], order['type'], order['side'], order['amount'], None, {
>     'triggerPrice': 12345.67,  # your new price here
> })
> 
> pprint(edited_order)
> ```
> 
> Let us know if that helps or not.
> Thx!

Thank you for your support .
Code is working without any error . The point is ID is changing after editing. I think this is happening on the server .
in any way I can use this code .
Thanks.

**Comment by kroitor** [comment]
> I think this is happening on the server .

Yes, they will do cancel+create on the server, as documented in their API docs.
