### ISSUE TITLE
bitfinex v2 fetchMarkets has broken flags

### ISSUE THREAD

**Issue by sonirico** [ccxt/ccxt#7964]
- OS: linux
- Programming Language version: nodejs v12.16.0
- CCXT version: 1.37.61

Hello there. As of now, bitfinex **v2** client for javascript fetches market information from one **v1** endpoint [https://api.bitfinex.com/v1/symbols_details ](https://api.bitfinex.com/v1/symbols_details), yielding incorrect results for the `spot` market flag, which always is set to `false`. This is a critical issue for apps which heavily rely on this flag to filter only tradeable spot assets.

Either way, v2 api provides [this](https://api.bitfinex.com/v2/conf/pub:list:pair:exchange) endpoint under [config](https://docs.bitfinex.com/reference#rest-public-conf) section, which could be use to flag correctly _spot_, _margin_, and _future_ markets.

**Comment by kroitor** [comment]
@sonirico will get this sorted shortly, thanks for reporting!

**Comment by fbadiola** [comment]
Also, you can get spot, margin and futures symbols in a single http call:
https://api.bitfinex.com/v2/conf/pub:list:pair:exchange,pub:list:pair:margin,pub:list:pair:futures

```typescript
type SpotSymbols = string[];
type MarginSymbols = string[];
type FuturesSymbols = string[];
type Result = [ SpotSymbols, MarginSymbols, FuturesSymbols ]
```
