### ISSUE TITLE
Coinbase Pro : proxy string (wrongly?) concatenated with URL

### ISSUE THREAD

**Issue by PierreMardon** [ccxt/ccxt#7968]
- OS: macOS
- Programming Language version: TypeScript / es2017
- CCXT version: ^1.34.7

```
const client = new ccxt.coinbasepro({
        apiKey: '',
        secret: '',
        enableRateLimit: true,
        proxy: '159.65.158.141:1080',
        options: {adjustForTimeDifference: true} as Exchange['options'],
      })
await client.loadMarkets()
```

```
ExchangeNotAvailable 	coinbasepro GET 159.65.158.141:1080https://api.pro.coinbase.com/currencies  Only HTTP(S) protocols are supported
details:
{
  constructor: [class ExchangeNotAvailable extends NetworkError],
  name: 'ExchangeNotAvailable'
}
error stack:
• Exchange.js:395 <anonymous>
    node_modules/ccxt/js/base/Exchange.js:395:35

• time.js:195 timeout
    node_modules/ccxt/js/base/functions/time.js:195:24

```

I don't get why it's done this way but it seems it's expected to concatenate the proxy string to the URL

<img width="996" alt="Capture d’écran 2020-11-12 à 20 44 19" src="https://user-images.githubusercontent.com/327473/98988404-e6bc8980-2527-11eb-960b-3d93b82db468.png">

**Comment by kroitor** [comment]
This is related to the use of the `proxy` property. The `proxy` property is intended to be used with CORS proxies only (for web browsers). When using a CORS proxy, the proxy is prepended to the URL.

If you're dealing with server-side code and you don't have to work with CORS, and instead you want to use a regular HTTPS or SOCKS proxy, then you should not touch the `proxy` property. 

- https://github.com/ccxt/ccxt/wiki/Install#proxy

Instead:
1. update to the most recent version of CCXT 1.37.65+
2. pass a proxying httpsAgent to it depending on the type of your proxy, as shown below, for example:

```JavaScript
'use strict';

const ccxt = require ('ccxt')
    , SocksProxyAgent = require ('socks-proxy-agent')
    , socks = 'socks://127.0.0.1:7000'
    , httpsAgent = new SocksProxyAgent (socks)
    , exchange = new ccxt.binance ({
        enableRateLimit: true,
        httpsAgent,
    })
```

or

```JavaScript
'use strict';

const ccxt = require ('ccxt')
   , HttpsProxyAgent = require ('https-proxy-agent')
   , proxy = process.env.http_proxy || 'http://168.63.76.32:3128' // HTTP/HTTPS proxy to connect to
   , httpsAgent = new HttpsProxyAgent (proxy)
    , exchange = new ccxt.binance ({
        enableRateLimit: true,
        httpsAgent,
    })
```

Let us know if the above does not answer your question.

P.S. Make sure your version is up to date.

**Comment by PierreMardon** [comment]
Very clear, thank you!
I'll try this asap and report back here.

**Comment by PierreMardon** [comment]
It works as expected : meaning it fails for cloudflare reasons on coinbase :P
Sorry I missed the proxy section in the install doc..!

**Comment by kroitor** [comment]
@PierreMardon thx for reporting back!
