### ISSUE TITLE
Bybit endpoints being upgraded

### ISSUE THREAD

**Issue by JezcoGuy** [ccxt/ccxt#7977]
- OS: Ubuntu 20.04.1 LTS
- Programming Language version: Python 3.8.5
- CCXT version: 1.37.69

Hi,

Recently received a message from Bybit, with regards to their REST API being upgraded and some endpoints being removed as of December 17 2020:

https://bybit-exchange.github.io/docs/inverse/#2020-11-10

As far as I can see, most of the endpoints referenced in that doc are already in use in CCXT. My issue is that I'm using openapi_post_stop_order_create, openapi_get_stop_order_list , openapi_post_stop_order_replace, which are set to be removed and don't appear to have /v2/private equivalent available in CCXT, being /v2/private/stop-order/create, /v2/private/stop-order/list, /v2/private/stop-order/replace respectively.

**Comment by kroitor** [comment]
Hi! We are working on these changes, will post here asap.

**Comment by bigcountry-scav** [comment]
yes would be great if the replace endpoints could be updated as well

/v2/private/stop-order/replace

**Comment by kroitor** [comment]
@bigcountry-scav yep, we will add that as well and will push the changes soon.

**Comment by daikts** [comment]
was this closed because the endpoints have been upgraded? I see some bybit changes in recent commit history but no explicit message about an upgrade.

**Comment by JezcoGuy** [comment]
@daikts Yes, closed for that reason. I can confirm that the updated endpoints I've used have tested fine.
