### ISSUE TITLE
Limit order always executes at maximum set limit price

### ISSUE THREAD

**Issue by mklosi** [ccxt/ccxt#7979]
There is smth I don't understand about limit orders and how they are executed on binance. I am led to believe that a limit order will execute at the limit set **_or better_**. But based on numerous tests, I see it always executes at the limit set, no matter how high it is set. Here is an example for a buy order, where I set the limit at 10% higher (which is ridiculously high just to make the point) than the ask price. 

```
price:
{'ask': 0.003907, 'bid': 0.003904}

orders:
[{'info': {'symbol': 'LTCBTC', 'orderId': 437641845, 'orderListId': -1, 'clientOrderId': 'some-id', 'transactTime': 1605473031619, 'price': '0.00429700', 'origQty': '0.65000000', 'executedQty': '0.65000000', 'cummulativeQuoteQty': '0.00253912', 'status': 'FILLED', 'timeInForce': 'GTC', 'type': 'LIMIT', 'side': 'BUY'}, 'id': '437641845', 'clientOrderId': 'fjkfdjfdjk', 'timestamp': 1605473031619, 'datetime': '2020-11-15T20:43:51.619Z', 'lastTradeTimestamp': None, 'symbol': 'LTC/BTC', 'type': 'limit', 'side': 'buy', 'price': 0.004297, 'amount': 0.65, 'cost': 0.00253912, 'average': 0.003906338461538462, 'filled': 0.65, 'remaining': 0.0, 'status': 'closed', 'fee': None, 'trades': None}]
```
ask price: 0.003907
executed price: 0.004297 -> 10% increase 

Is there smth I don't understand?

**Comment by kroitor** [comment]
> Is there smth I don't understand?

See the `average` field, it contains the actual average executed price (0.003906338461538462). The `price` field will contain the ordered price value (0.004297). The `cost` field as reported by Binance (`cummulativeQuoteQty`) is supposedly lying, you might want to check that by summing the costs of trades for this order (`fetchMyTrades`).

Do you use the Binance testnet for the tests or do you test on the actual production server?

**Comment by mklosi** [comment]
So here is another order and the corresponding trade. I see the price between the order and trade also differ by 10%: 

order: 
```
[
  {
    "info": {
      "symbol": "XRPBTC",
      "orderId": 429308436,
      "orderListId": -1,
      "clientOrderId": "...........",
      "transactTime": 1605475762844,
      "price": "0.00001850",
      "origQty": "15.00000000",
      "executedQty": "15.00000000",
      "cummulativeQuoteQty": "0.00025230",
      "status": "FILLED",
      "timeInForce": "GTC",
      "type": "LIMIT",
      "side": "BUY"
    },
    "id": "429308436",
    "clientOrderId": ".................",
    "timestamp": 1605475762844,
    "datetime": "2020-11-15T21:29:22.844Z",
    "lastTradeTimestamp": "None",
    "symbol": "XRP/BTC",
    "type": "limit",
    "side": "buy",
    "price": 0.0000185,
    "amount": 15.0,
    "cost": 0.0002523,
    "average": 0.00001682,
    "filled": 15.0,
    "remaining": 0.0,
    "status": "closed",
    "fee": "None",
    "trades": "None"
  }
]
```

trade: 
```
[
  {
    "info": {
      "symbol": "XRPBTC",
      "id": 78434404,
      "orderId": 429308436,
      "orderListId": -1,
      "price": "0.00001682",
      "qty": "15.00000000",
      "quoteQty": "0.00025230",
      "commission": "0.00010924",
      "commissionAsset": "BNB",
      "time": 1605475762844,
      "isBuyer": "True",
      "isMaker": "False",
      "isBestMatch": "True"
    },
    "timestamp": 1605475762844,
    "datetime": "2020-11-15T21:29:22.844Z",
    "symbol": "XRP/BTC",
    "id": "78434404",
    "order": "429308436",
    "type": "None",
    "side": "buy",
    "takerOrMaker": "taker",
    "price": 0.00001682,
    "amount": 15.0,
    "cost": 0.0002523,
    "fee": {
      "cost": 0.00010924,
      "currency": "BNB"
    }
  }
]
```

| Do you use the Binance testnet for the tests or do you test on the actual production server?
I'm using the live server 

| Do you use the futures with leverage?
I'm not currently using futures.

**Comment by kroitor** [comment]
@mklosi on the XRP/BTC trade – I don't see a problem with this one, looks correct to me, what's wrong with it?

**Comment by mklosi** [comment]
well, I'm wondering why the "price" reported by the "order" is 10% higher than the "price" reported by the "trade". 10% so happens to be what I've put as the price for the limit order -> ask price in the moment of trade + 10%. I am sure if I put a limit order at a price = ask_price + 50%, the order will report that high price. I don't want to test 50% though, since I already lost a bunch of money testing this :)      

Shouldn't the price reported by the "order" match that of the "trade"?

**Comment by kroitor** [comment]
> Shouldn't the price reported by the "order" match that of the "trade"?

No, the price reported by the order – is the price reported by the exchange, in this case, it's the price of you order upon placing it (the price you've ordered). The `average` price should match the average across trades. And the cost should match the sum of costs of trades.

**Comment by mklosi** [comment]
so in this case the order was filled all-in-once, and the actual price that the order was filled at, is the "average" field. price is just an echo to the limit price I set when I placed the order, not the actual price that the order was executed at, correct?

**Comment by kroitor** [comment]
> ok so in this case, since the order was filled all-in-once, the actual price that the order was filled at, is the "average" field. The "price" field is just an echo to the limit price I set when I placed the order, not the actual price that the order was executed at, correct?

Yes, that is correct, but only if the order was filled with a single trade at once. If it was filled with more than one trade, then the actual true filling price is the price of each trade. 

Let me know if that does not answer your question. Feel free to reopen this issue or just ask further questions, if any.

**Comment by mklosi** [comment]
now it makes sense, and it's pretty basic actually. thank you. that was very helpful. I didn't think about the fact that the limit price I set is echoed back to me.
