### ISSUE TITLE
Hitbtc v2 fetchOrder(id)

### ISSUE THREAD

**Issue by adi90x** [ccxt/ccxt#798]
Hello , 

Seems that Hitbtc V2 api is getting undefined for the price when trying to fetch an order by id.
It seems to work fine with v1 api ! 

Regards,

**Comment by kroitor** [comment]
Hi! Can you please paste your code snippet and **verbose** output? We will take a look into it. Thx!

**Comment by adi90x** [comment]
Thx for the quick answer , I am using your example : examples/js/fech-orders.js
Just replacing bitrex by hitbtcv2 , and using `fetchOpenOrders` instead of `fetchOrders` ( not available for Hitbtc) 
Running that will return a `const order` with undefined price & cost property .
While it perfectly work with v1 API.

How do you put verbose output ? 
Do you need any other informations ?

Regards,

**Comment by kroitor** [comment]
> Running that will return a const order with undefined price & cost property .
> While it perfectly work with v1 API.

We will look into it, however, the following debug info would be helpful:

> How do you put verbose output ?

Set `.verbose = true` property on your exchange instance or in constructor params.

- https://github.com/kroitor/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
- https://github.com/ccxt/ccxt/wiki/Manual ←

**Comment by adi90x** [comment]
Ok so some more informations 

- : NodeJs 9.2.0 ,ccxt last npm version
- : Hitbtc v2 - function : fetchOrder  ( same function in v1 is working as expected )
- : Code snippet :
`"use strict";

const ccxt = require ('../../ccxt')
const asTable = require ('as-table')
const log = require ('ololog')

require ('ansicolor').nice;

const exchange = new ccxt.hitbtc2 ({
    apiKey: "APIKEY",
    secret: "SECRET",
    enableRateLimit: true,
    verbose: true,
})

async function test () {
     const order = await exchange.fetchOrder ('532ce2a6d1224926869c8e1b71680b2b')
    log (order)
}

test ()`
- : Stacktrace :
`hitbtc2 GET https://api.hitbtc.com/api/2/history/order?clientOrderId=532ce2a6d1224926869c8e1b71680b2b 
Request:
 { Authorization: 'Basic MzhhYjVjNGRmMmE3YjJiYTMzMzdlOWIwOTYzOTcwNTI6NDBjMjZkN2Q0MWRkYmI0MDRhZTg0MWY1YjNkZmE1MmE=',
  'Content-Type': 'application/json' } undefined
hitbtc2 GET https://api.hitbtc.com/api/2/history/order?clientOrderId=532ce2a6d1224926869c8e1b71680b2b 200 OK 
Response:
[{"id":998901208,"clientOrderId":"532ce2a6d1224926869c8e1b71680b2b","symbol":"BCNUSD","side":"sell","status":"new","type":"limit","timeInForce":"GTC","quantity":"1000","cumQuantity":"0","createdAt":"2017-06-01T20:34:02.796Z","updatedAt":"2017-06-01T20:34:02.796Z"}]
{        id:   "532ce2a6d1224926869c8e1b71680b2b",
  timestamp:    1496349242796,
   datetime:   "2017-06-01T20:34:02.796Z",
    created:    1496349242796,
    updated:    1496349242796,
     status:   "open",
     symbol:   "BCN/USD",
       type:   "limit",
       side:   "sell",
      price:    undefined,
     amount:    1000,
       cost:    undefined,
     filled:    0,
  remaining:    1000,
        fee:    undefined,
       info: {            id:  998901208,
               clientOrderId: "532ce2a6d1224926869c8e1b71680b2b",
                      symbol: "BCNUSD",
                        side: "sell",
                      status: "new",
                        type: "limit",
                 timeInForce: "GTC",
                    quantity: "1000",
                 cumQuantity: "0",
                   createdAt: "2017-06-01T20:34:02.796Z",
                   updatedAt: "2017-06-01T20:34:02.796Z"          } } (test @ fetch-orders.js:24)
`

**Comment by kroitor** [comment]
This is by design (not a bug). Unfortunately, HitBTC v2 will not return the initial price of the order, when you fetch it. Each order (as well as any other structure returned from ccxt) contains an `info` field, that holds the response from the exchange, untouched, as is. That `info` field is exchange specific (differs depending on the exchange). It is there for you to be able to verify the output. Other fields around `info` are *unified* parsed namings, those are generated by ccxt from `info` in cross-exchange-compatible way.

So, if you look at it carefully, you'll see that the price is missing there (in the `info` returned from HitBTC v2). 

![hitbtc-order-price](https://user-images.githubusercontent.com/1294454/33791604-41bd896c-dc9f-11e7-9839-ba9a4b075447.jpg)

If you place an order with ccxt, then it gets cached (till next restart) and the price is remembered. So if you fetch it later, you will see the price there (ccxt will put it there for you). But if the order in question was not placed within this run of ccxt (via website or other software, or during a previous run), there is no way for the library to know the initial price of your previously placed order.

From here you have two options:
- Add caching on your side to track the info that might needed but missing to keep track of your history (this is beyond the scope of the library).
- Fetch the trades for that order to find the actual filling price.

Let us know if the above answers your question or not. Thx!

**Comment by vvinni** [comment]
Hi @kroitor !

I want to thank you and all the people involved in the dev of this lib!! 

Sorry, I know that this is not the correct place to do it... but I didnt find the right one!

I´ve finished a bot that trade in kraken and I know that the time spent in it is a fraction of the time it would take without ccxt.

After some time of testing... if its profitable ... I will donate 5% of my earnings montly as long as I run it!

I did a lott of things with the library before the bot itself... scripts for statistics... for data storage from the markets... webui for opening specific orders... and with ccxt and python all of it took almost no time!

Congrats for the awesome work and all the answers here! Helped me a lot!!

Anyway... thank you very very much!!


P.S. My english is a little rusty... not my first language...

**Comment by adi90x** [comment]
Perfect, thanks a lot , for your work !
CCXT is really awesome !


2017-12-09 5:40 GMT+01:00 Igor Kroitor <notifications@github.com>:

**Comment by Fcl69** [comment]
>Fetch the trades for that order to find the actual filling price (this can be done with the library).

Can you please provide an example? I've failed to compile the request using unified API.

**Comment by kroitor** [comment]
@hippylover 

> This is not correct. Hitbtc v2 api DO get the price but it is not retrieved with ccxt for some reason(not in info or unified).

Can you point where the price is in your own output? Because you say it's there, but I don't see it anywhere in their response, which is contained in the `info` field untouched (as is, from the exchange). No price there. Am I blind?

**Comment by adi90x** [comment]
@kroitor : I think he has the price only in the curl request (first code Block)  this is because ccxt is not using Order endpoint to fetch the order but OrderHistory...
I send a pull request to change that

**Comment by kroitor** [comment]
@adi90x you just need to use fetchOpenOrder (id) for that...

**Comment by adi90x** [comment]
Yes but Order will work for open and closed order, and will fetch the price
(and be more consistent with other exchange no ?)

**Comment by kroitor** [comment]
> Yes but Order will work for open

Yes

> and closed order

No ) I would not write it all, if it was that easy ;)

**Comment by adi90x** [comment]
Just try with an old order and it seems to be working ...

**Comment by adi90x** [comment]
Forgot previous comment ! Wasn't the good one ^^ No idea of what is going on with that one !
