### ISSUE TITLE
BTCturk: fetchBalance() not working anymore (btcturk.com/api/ticker GET 405 Method not supported anymore)

### ISSUE THREAD

**Issue by c0dehunter** [ccxt/ccxt#7985]
- OS: Linux
- Programming Language version: PHP 7.3
- CCXT version: 1.35.19

```
<?php
$id = "\\ccxt\\btcturk";
$exchange = new $id();
$exchange->apiKey = "271b718c-7cf7-48f2-a139-4f5cfce4e98e"; // testing API key
$exchange->secret = "LHzcTRf9/KMtnJ4M02gVglziNlWk8oGu";
$exchange->enableRateLimit = true;

for($balance : $exchange->fetchBalance())
	print_r($balance);
?>
```

**Error**:
```
{"msg":"[Exchange Not Available] https:\/\/www.btcturk.com\/api\/ticker GET 405 Method not supported anymore. Please
refer to https:\/\/docs.btcturk.com (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline,
on maintenance, DDoS protection, rate-limiting in effect)","exchange":"btcturk","balances":{}}
```

It seems API v1 is not working anymore and v2 should now be used (https://docs.btcturk.com/#ticker).

**Comment by kroitor** [comment]
> It seems API v1 is not working anymore and v2 should now be used (https://docs.btcturk.com/#ticker).

Yep: https://github.com/ccxt/ccxt/issues?q=btcturk+is%3Aopen

**Comment by c0dehunter** [comment]
@kroitor I've seen there is a release candidate for v2 here: https://github.com/ccxt/ccxt/pull/6945 but it's a javascript file. How could I get PHP version of this so I could help test it? I am not very familiar with your conversion engines py-js-php.

**Comment by kroitor** [comment]
@c0dehunter you should be able to build that PR like so, assuming you have Node.js installed:

```shell
git clone https://github.com/ccxt/ccxt.git
cd ccxt
git checkout -b mehmetcanyegen-master master
git pull https://github.com/mehmetcanyegen/ccxt.git master
npm install
npm run build
```

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-build--run-tests-on-your-local-machine

**Comment by kroitor** [comment]
We will upgrade it to v2 in the master CCXT asap.

**Comment by c0dehunter** [comment]
@kroitor I just wanted to let you know that the pull request doesn't work properly for `fetchBalance()`: https://github.com/ccxt/ccxt/pull/6945#issuecomment-728993233

**Comment by c0dehunter** [comment]
@kroitor is there any way you could support v2? We've got many users asking about it :)

**Comment by kroitor** [comment]
@c0dehunter sorry for the delay, I will get to it as soon as I can!
