### ISSUE TITLE
Gemini Parser Deprecated 

### ISSUE THREAD

**Issue by JTraversa** [ccxt/ccxt#7989]
I tried searching through issues for any current tickets related to Gemini's parsing with no luck, apologies if this is a duplicate. Just looks like Gemini has updated their order size limit page and the parser has become non-functional.

- OS: Windows
- Programming Language version: Python 
- CCXT version: 1.30.28

Code isn't necessary to reproduce issue, Gemini has changed their order limit page and the parser no longer works.

```
ccxt.ExchangeError: gemini the Gemini API doc HTML markup has changed, breaking the parser of order limits and precision info for Gemini markets.
```

**Comment by kroitor** [comment]
Your version is too old, just update it:

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/issues?q=gemini
- https://github.com/ccxt/ccxt/issues/7874
- https://github.com/ccxt/ccxt/issues/7875
- ...
