### ISSUE TITLE
[ftx] cancelOpenOrder(symbol...)

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#7990]
I'm having problems with cancelling all order for a symbol on ftx.  All my open orders seemed to get canceled. In this example, I'm trying to cancel my BTC futures, but my ETH futures also seem to get canceled.

```
handleRestResponse:
 ftx DELETE https://ftx.com/api/orders?conditionalOrdersOnly=false&limitOrdersOnly=false&market=BTC-PERP 200 OK 
Response:
 {
  'Account-Id': 'xxx',
...
} 
 {"result":"Orders queued for cancellation","success":true}
```

The docs make it look like the delete endpoint is expecting a json document in the body https://docs.ftx.com/?javascript#cancel-all-orders

**Comment by kroitor** [comment]
@npomfret thx for reporting it, plz let me know if you have difficulties with version 1.37.73, it will be available shortly.

**Comment by npomfret** [comment]
That's working - many thanks

**Comment by kroitor** [comment]
@npomfret thx to you for your involvement!
