### ISSUE TITLE
How can I get the positon details of phemex exchange using python code

### ISSUE THREAD

**Issue by AsadullahSoomro** [ccxt/ccxt#7993]
I am using Phemex testnet account API Keys for the trading for testing purposes.
Currently,  I wanna get the **position details** of the Phemex exchange. kindly help me.

Windows:
Programming Language version: Python 3.6
CCXT version:Version: 1.37.0
pip version 20.2.2
`
    positions = exchange.privateGetPositionList()
   
or
    #balance = exchange.fetch_balance()
    positions = balance['info']['positions']
    print(exchange.privateGetAccountsAccountPositions({'currency':'BTCUSD'}))
   
`
error 
phemex {"msg":"Failed to find currency BTCUSD","code":10500}

Thanks in advance!

**Comment by kroitor** [comment]
Hi! We will provide the answer shortly in this duplicate issue: https://github.com/ccxt/ccxt/issues/7994
