### ISSUE TITLE
Can I get the position details of phemex exchange using this function 'phemex' object has no attribute 'private_get_position_list'

### ISSUE THREAD

**Issue by AsadullahSoomro** [ccxt/ccxt#7994]
I am using Phemex testnet account API Keys for the trading for testing purposes.
Currently, I wanna get the position details of the Phemex exchange. 
kindly help me.

Windows:
Programming Language version: Python 3.6
CCXT version:Version: 1.37.0
pip version 20.2.2
`

print("Positions", exchange.private_get_position_list({"symbol": 'BTCUSD'}))

positions = exchange.privateGetPositionList()

or
#balance = exchange.fetch_balance()
positions = balance['info']['positions']
print(exchange.privateGetAccountsAccountPositions({'currency':'BTCUSD'}))

`
error
'phemex' object has no attribute 'private_get_position_list'

Thanks in advance!

**Comment by kroitor** [comment]
1. Update to CCXT 1.37.92
2. Edit this snippet for your keys and values (read through the comments carefully), then run this snippet and make sure that your version of CCXT is up to date:

- https://github.com/ccxt/ccxt/tree/master/examples/py/phemex-positions.py

```Python
# -*- coding: utf-8 -*-

from pprint import pprint
import ccxt


print('CCXT Version:', ccxt.__version__)

exchange = ccxt.phemex({
    'enableRateLimit': True,  # https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
    # 'apiKey': 'YOUR_API_KEY',  # testnet keys if using the testnet sandbox
    # 'secret': 'YOUR_SECRET',  # testnet keys if using the testnet sandbox
    'options': {
        'defaultType': 'swap',
    },
})

# exchange.set_sandbox_mode(True)  # uncomment to use the testnet sandbox

markets = exchange.load_markets()

# example 1
positions = exchange.fetch_positions(None, None, None, {'code':'BTC'})
pprint(positions)

print('------------------------------------------------------------')

# example 2
positions = exchange.fetch_positions(None, None, None, {'currency':'BTC'})
pprint(positions)

print('------------------------------------------------------------')

# example 3
balance = exchange.fetch_balance({'code':'BTC'})
pprint(balance['info']['data']['positions'])

print('------------------------------------------------------------')

# example 4
balance = exchange.fetch_balance({'currency':'BTC'})
pprint(balance['info']['data']['positions'])

print('------------------------------------------------------------')

# example 5
# https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
response = exchange.private_get_accounts_accountpositions({'currency': 'BTC'})
pprint(response['data']['positions'])

```

Let us know if that does not help or does not answer your question.
