### ISSUE TITLE
BINANCE: COIN- M Futures. How to place orders and pull data in these markets and not USDT-M futures. 

### ISSUE THREAD

**Issue by Kalelv45** [ccxt/ccxt#7995]
- OS: MacOS Mojave
- Programming Language version: Python 
- CCXT version: 1.37.59

I don't understand how to pull data and place orders on the Coin-M futures on Binance. 
When I reference the tickers, I can just get the USDT-M futures.
Does anyone know how to reference those markets?
when I load the market tickers, I can't seem to find these COIN-M contracts.

**Comment by kroitor** [comment]
You have to set the options['defaultType'] to `delivery` prior to (re)loading the markets for COIN-M contracts:

```Python
import ccxt
exchange = ccxt.binance({
    'enableRateLimit': True,
    'options': {
        'defaultType': 'delivery',
    },
})

markets = exchange.load_markets()
# ...
```

Let us know if that does not answer your question.
