### ISSUE TITLE
[Binance] get X-MBX-USED-WEIGHT and X-MBX-ORDER-COUNT from http response headers

### ISSUE THREAD

**Issue by nvhien1992** [ccxt/ccxt#7996]
Hi,

May I know if ccxt supports getting http header from the response?
I want to fetch some info from that header (as title).

Thanks,
Hien

**Comment by kroitor** [comment]
@nvhien1992 hi!

> May I know if ccxt supports getting http header from the response?

Yes, the last received headers are stored in the `exchange.last_response_headers` property on the exchange instance:

```
const response = await exchange.fetchTicker ('ETH/BTC')
console.log (exchange.last_response_headers)
```

- https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties

Let us know if that does not answer your question.

**Comment by nvhien1992** [comment]
Great! That's what I want.
Many thanks, Kroitor!
/Hien
