### ISSUE TITLE
lack of interface to get X-MBX-USED-WEIGHT (binance)

### ISSUE THREAD

**Issue by colourful-land** [ccxt/ccxt#7999]
Hi I couldn't find the api to get the X-MBX-USED-WEIGHT when using binance.

This is the HTTP header filed they used to tell bots whether or not they will be punished for requesting too frequently. [Their document](https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#ip-limits) has

> Every request will contain X-MBX-USED-WEIGHT-(intervalNum)(intervalLetter) in the response headers which has the current used weight for the IP for all request rate limiters defined.

Thanks. The call I am using is `binance.fetchBalance()` but this question is valid for any calls.

**Comment by kroitor** [comment]
Please, see this duplicate issue: https://github.com/ccxt/ccxt/issues/7996. Let us know if that does not answer your question.
