### ISSUE TITLE
PHP Proxy

### ISSUE THREAD

**Issue by anotherfriend** [ccxt/ccxt#8005]
Please, check topic.
https://github.com/ccxt/ccxt/issues/7198#issuecomment-651233621

```PHP
// initialize the exchange

// ...

// configure proxy
curl_setopt($exchange->curl, CURLOPT_PROXY, '201.93.126.118:3128'); // host:port
curl_setopt($exchange->curl, CURLOPT_PROXYUSERPWD, 'username:pass123');
curl_setopt($exchange->curl, CURLOPT_PROXYTYPE, "CURLPROXY_HTTP"); // HTTP, HTTPS, HTTP_1_0, SOCKS4, SOCKS4A, SOCKS5, 

// ...

// your logic here...
```

Let us know if that does not help.

_Originally posted by @kroitor in https://github.com/ccxt/ccxt/issues/7992#issuecomment-729988034_

**Comment by kroitor** [comment]
@anotherfriend plz don't duplicate issues, we don't miss your messages and will reply as soon as we can.
