### ISSUE TITLE
fetch_ohlcv on testnet_Bybit stop working suddenly ('Markets not loaded')

### ISSUE THREAD

**Issue by Serendepon** [ccxt/ccxt#8006]
- OS: Windows
- Programming Language version: Python

Hello Igor!
I have an issue with fetch_ohlcv on bybit testnet, which worked perefectly for, like, a year. Maybe you can check?

Code (pretty standard):
```
...
timeframe = '1m'
limit=51
interval = bybit.parse_timeframe(timeframe) * 1000

if 'test' in bybit.urls:
    bybit.urls['api'] = bybit.urls['test']

bybit.load_markets()

since = bybit.round_timeframe(timeframe, bybit.milliseconds(), ROUND_UP) - (limit * interval)
ohlcv = bybit.fetch_ohlcv('BTC/USD', timeframe, since=since, limit=limit)
```

Response:
```
  File "C:\42.py", line 334, in <module>
    ohlcv = bybit.fetch_ohlcv('BTC/USD', timeframe, since=since, limit=limit)
  File "E:\Python38\lib\site-packages\ccxt\bybit.py", line 700, in fetch_ohlcv
    market = self.market(symbol)
  File "E:\Python38\lib\site-packages\ccxt\base\exchange.py", line 1815, in mark
et
    raise ExchangeError('Markets not loaded')
ccxt.base.errors.ExchangeError: Markets not loaded
```

**Comment by kroitor** [comment]
Hi @Serendepon! Whats your version of CCXT?

Also, don't do this:

```Python
if 'test' in bybit.urls:
    bybit.urls['api'] = bybit.urls['test']
```

... instead do this ...

```Python
import ccxt
from pprint import pprint

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.bybit({'enableRateLimit': True})

# exchange.verbose = True  # uncomment for debugging purposes

exchange.set_sandbox_mode(True)

markets = exchange.load_markets()

ohlcv = exchange.fetch_ohlcv('BTC/USD', '1m')
pprint(ohlcv)
```

If that does not work, please paste your verbose output.

**Comment by Serendepon** [comment]
CCXT Version: 1.38.5

Request: GET https://api-testnet.bybit.com/v2/public/symbols {'Accept-Encoding':
 'gzip, deflate'} None

Response: GET https://api-testnet.bybit.com/v2/public/symbols 200 {'Content-Type
': 'application/json; charset=utf-8', 'Content-Length': '4582', 'Expires': 'Fri,
 20 Nov 2020 23:44:59 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'P
ragma': 'no-cache', 'Date': 'Fri, 20 Nov 2020 23:44:59 GMT', 'Connection': 'keep
-alive'} {"ret_code":0,"ret_msg":"OK","ext_code":"","ext_info":"","result":[{"sy
mbol":"BTCUSD","symbol_alias":"BTCUSD","status":"Trading","base_currency":"BTC",
"quote_currency":"USD","price_scale":2,"taker_fee":"0.00075","maker_fee":"-0.000
25","leverage_filter":{"min_leverage":1,"max_leverage":100,"leverage_step":"0.01
"},"price_filter":{"min_price":"0.5","max_price":"999999.5","tick_size":"0.5"},"
lot_size_filter":{"max_trading_qty":1000000,"min_trading_qty":1,"qty_step":1}},{
"symbol":"ETHUSD","symbol_alias":"ETHUSD","status":"Trading","base_currency":"ET
H","quote_currency":"USD","price_scale":2,"taker_fee":"0.00075","maker_fee":"-0.
00025","leverage_filter":{"min_leverage":1,"max_leverage":50,"leverage_step":"0.
01"},"price_filter":{"min_price":"0.05","max_price":"99999.95","tick_size":"0.05
"},"lot_size_filter":{"max_trading_qty":1000000,"min_trading_qty":1,"qty_step":1
}},{"symbol":"EOSUSD","symbol_alias":"EOSUSD","status":"Trading","base_currency"
:"EOS","quote_currency":"USD","price_scale":3,"taker_fee":"0.00075","maker_fee":
"-0.00025","leverage_filter":{"min_leverage":1,"max_leverage":50,"leverage_step"
:"0.01"},"price_filter":{"min_price":"0.001","max_price":"1999.999","tick_size":
"0.001"},"lot_size_filter":{"max_trading_qty":1000000,"min_trading_qty":1,"qty_s
tep":1}},{"symbol":"XRPUSD","symbol_alias":"XRPUSD","status":"Trading","base_cur
rency":"XRP","quote_currency":"USD","price_scale":4,"taker_fee":"0.00075","maker
_fee":"-0.00025","leverage_filter":{"min_leverage":1,"max_leverage":50,"leverage
_step":"0.01"},"price_filter":{"min_price":"0.0001","max_price":"199.9999","tick
_size":"0.0001"},"lot_size_filter":{"max_trading_qty":1000000,"min_trading_qty":
1,"qty_step":1}},{"symbol":"BTCUSDT","symbol_alias":"BTCUSDT","status":"Trading"
,"base_currency":"BTC","quote_currency":"USDT","price_scale":2,"taker_fee":"0.00
075","maker_fee":"-0.00025","leverage_filter":{"min_leverage":1,"max_leverage":1
00,"leverage_step":"0.01"},"price_filter":{"min_price":"0.5","max_price":"999999
.5","tick_size":"0.5"},"lot_size_filter":{"max_trading_qty":100,"min_trading_qty
":0.001,"qty_step":0.001}},{"symbol":"ETHUSDT","symbol_alias":"ETHUSDT","status"
:"Trading","base_currency":"ETH","quote_currency":"USDT","price_scale":2,"taker_
fee":"0.00075","maker_fee":"-0.00025","leverage_filter":{"min_leverage":1,"max_l
everage":50,"leverage_step":"0.01"},"price_filter":{"min_price":"0.5","max_price
":"100000","tick_size":"0.05"},"lot_size_filter":{"max_trading_qty":1000,"min_tr
ading_qty":0.01,"qty_step":0.01}},{"symbol":"LTCUSDT","symbol_alias":"LTCUSDT","
status":"Trading","base_currency":"LTC","quote_currency":"USDT","price_scale":2,
"taker_fee":"0.00075","maker_fee":"-0.00025","leverage_filter":{"min_leverage":1
,"max_leverage":25,"leverage_step":"0.01"},"price_filter":{"min_price":"0.01","m
ax_price":"20000","tick_size":"0.01"},"lot_size_filter":{"max_trading_qty":10000
,"min_trading_qty":0.1,"qty_step":0.1}},{"symbol":"XTZUSDT","symbol_alias":"XTZU
SDT","status":"Trading","base_currency":"XTZ","quote_currency":"USDT","price_sca
le":3,"taker_fee":"0.00075","maker_fee":"-0.00025","leverage_filter":{"min_lever
age":1,"max_leverage":25,"leverage_step":"0.01"},"price_filter":{"min_price":"0.
001","max_price":"2000","tick_size":"0.001"},"lot_size_filter":{"max_trading_qty
":100000,"min_trading_qty":0.1,"qty_step":0.1}},{"symbol":"LINKUSDT","symbol_ali
as":"LINKUSDT","status":"Trading","base_currency":"LINK","quote_currency":"USDT"
,"price_scale":3,"taker_fee":"0.00075","maker_fee":"-0.00025","leverage_filter":
{"min_leverage":1,"max_leverage":25,"leverage_step":"0.01"},"price_filter":{"min
_price":"0.001","max_price":"2000","tick_size":"0.001"},"lot_size_filter":{"max_
trading_qty":100000,"min_trading_qty":0.1,"qty_step":0.1}},{"symbol":"BTCUSDZ20"
,"symbol_alias":"BTCUSD1225","status":"Trading","base_currency":"BTC","quote_cur
rency":"USD","price_scale":2,"taker_fee":"0.00075","maker_fee":"-0.00025","lever
age_filter":{"min_leverage":1,"max_leverage":100,"leverage_step":"0.01"},"price_
filter":{"min_price":"0.5","max_price":"999999.5","tick_size":"0.5"},"lot_size_f
ilter":{"max_trading_qty":1000000,"min_trading_qty":1,"qty_step":1}},{"symbol":"
BTCUSDH21","symbol_alias":"BTCUSD0326","status":"Trading","base_currency":"BTC",
"quote_currency":"USD","price_scale":2,"taker_fee":"0.00075","maker_fee":"-0.000
25","leverage_filter":{"min_leverage":1,"max_leverage":100,"leverage_step":"0.01
"},"price_filter":{"min_price":"0.5","max_price":"999999.5","tick_size":"0.5"},"
lot_size_filter":{"max_trading_qty":1000000,"min_trading_qty":1,"qty_step":1}}],
"time_now":"1605915899.605521"}

Request: GET https://api-testnet.bybit.com/v2/public/symbols {'Accept-Encoding':
 'gzip, deflate'} None

Response: GET https://api-testnet.bybit.com/v2/public/symbols 200 {'Content-Type
': 'application/json; charset=utf-8', 'Content-Length': '4582', 'Expires': 'Fri,
 20 Nov 2020 23:44:59 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'P
ragma': 'no-cache', 'Date': 'Fri, 20 Nov 2020 23:44:59 GMT', 'Connection': 'keep
-alive'} {"ret_code":0,"ret_msg":"OK","ext_code":"","ext_info":"","result":[{"sy
mbol":"BTCUSD","symbol_alias":"BTCUSD","status":"Trading","base_currency":"BTC",
"quote_currency":"USD","price_scale":2,"taker_fee":"0.00075","maker_fee":"-0.000
25","leverage_filter":{"min_leverage":1,"max_leverage":100,"leverage_step":"0.01
"},"price_filter":{"min_price":"0.5","max_price":"999999.5","tick_size":"0.5"},"
lot_size_filter":{"max_trading_qty":1000000,"min_trading_qty":1,"qty_step":1}},{
"symbol":"ETHUSD","symbol_alias":"ETHUSD","status":"Trading","base_currency":"ET
H","quote_currency":"USD","price_scale":2,"taker_fee":"0.00075","maker_fee":"-0.
00025","leverage_filter":{"min_leverage":1,"max_leverage":50,"leverage_step":"0.
01"},"price_filter":{"min_price":"0.05","max_price":"99999.95","tick_size":"0.05
"},"lot_size_filter":{"max_trading_qty":1000000,"min_trading_qty":1,"qty_step":1
}},{"symbol":"EOSUSD","symbol_alias":"EOSUSD","status":"Trading","base_currency"
:"EOS","quote_currency":"USD","price_scale":3,"taker_fee":"0.00075","maker_fee":
"-0.00025","leverage_filter":{"min_leverage":1,"max_leverage":50,"leverage_step"
:"0.01"},"price_filter":{"min_price":"0.001","max_price":"1999.999","tick_size":
"0.001"},"lot_size_filter":{"max_trading_qty":1000000,"min_trading_qty":1,"qty_s
tep":1}},{"symbol":"XRPUSD","symbol_alias":"XRPUSD","status":"Trading","base_cur
rency":"XRP","quote_currency":"USD","price_scale":4,"taker_fee":"0.00075","maker
_fee":"-0.00025","leverage_filter":{"min_leverage":1,"max_leverage":50,"leverage
_step":"0.01"},"price_filter":{"min_price":"0.0001","max_price":"199.9999","tick
_size":"0.0001"},"lot_size_filter":{"max_trading_qty":1000000,"min_trading_qty":
1,"qty_step":1}},{"symbol":"BTCUSDT","symbol_alias":"BTCUSDT","status":"Trading"
,"base_currency":"BTC","quote_currency":"USDT","price_scale":2,"taker_fee":"0.00
075","maker_fee":"-0.00025","leverage_filter":{"min_leverage":1,"max_leverage":1
00,"leverage_step":"0.01"},"price_filter":{"min_price":"0.5","max_price":"999999
.5","tick_size":"0.5"},"lot_size_filter":{"max_trading_qty":100,"min_trading_qty
":0.001,"qty_step":0.001}},{"symbol":"ETHUSDT","symbol_alias":"ETHUSDT","status"
:"Trading","base_currency":"ETH","quote_currency":"USDT","price_scale":2,"taker_
fee":"0.00075","maker_fee":"-0.00025","leverage_filter":{"min_leverage":1,"max_l
everage":50,"leverage_step":"0.01"},"price_filter":{"min_price":"0.5","max_price
":"100000","tick_size":"0.05"},"lot_size_filter":{"max_trading_qty":1000,"min_tr
ading_qty":0.01,"qty_step":0.01}},{"symbol":"LTCUSDT","symbol_alias":"LTCUSDT","
status":"Trading","base_currency":"LTC","quote_currency":"USDT","price_scale":2,
"taker_fee":"0.00075","maker_fee":"-0.00025","leverage_filter":{"min_leverage":1
,"max_leverage":25,"leverage_step":"0.01"},"price_filter":{"min_price":"0.01","m
ax_price":"20000","tick_size":"0.01"},"lot_size_filter":{"max_trading_qty":10000
,"min_trading_qty":0.1,"qty_step":0.1}},{"symbol":"XTZUSDT","symbol_alias":"XTZU
SDT","status":"Trading","base_currency":"XTZ","quote_currency":"USDT","price_sca
le":3,"taker_fee":"0.00075","maker_fee":"-0.00025","leverage_filter":{"min_lever
age":1,"max_leverage":25,"leverage_step":"0.01"},"price_filter":{"min_price":"0.
001","max_price":"2000","tick_size":"0.001"},"lot_size_filter":{"max_trading_qty
":100000,"min_trading_qty":0.1,"qty_step":0.1}},{"symbol":"LINKUSDT","symbol_ali
as":"LINKUSDT","status":"Trading","base_currency":"LINK","quote_currency":"USDT"
,"price_scale":3,"taker_fee":"0.00075","maker_fee":"-0.00025","leverage_filter":
{"min_leverage":1,"max_leverage":25,"leverage_step":"0.01"},"price_filter":{"min
_price":"0.001","max_price":"2000","tick_size":"0.001"},"lot_size_filter":{"max_
trading_qty":100000,"min_trading_qty":0.1,"qty_step":0.1}},{"symbol":"BTCUSDZ20"
,"symbol_alias":"BTCUSD1225","status":"Trading","base_currency":"BTC","quote_cur
rency":"USD","price_scale":2,"taker_fee":"0.00075","maker_fee":"-0.00025","lever
age_filter":{"min_leverage":1,"max_leverage":100,"leverage_step":"0.01"},"price_
filter":{"min_price":"0.5","max_price":"999999.5","tick_size":"0.5"},"lot_size_f
ilter":{"max_trading_qty":1000000,"min_trading_qty":1,"qty_step":1}},{"symbol":"
BTCUSDH21","symbol_alias":"BTCUSD0326","status":"Trading","base_currency":"BTC",
"quote_currency":"USD","price_scale":2,"taker_fee":"0.00075","maker_fee":"-0.000
25","leverage_filter":{"min_leverage":1,"max_leverage":100,"leverage_step":"0.01
"},"price_filter":{"min_price":"0.5","max_price":"999999.5","tick_size":"0.5"},"
lot_size_filter":{"max_trading_qty":1000000,"min_trading_qty":1,"qty_step":1}}],
"time_now":"1605915899.839895"}
Traceback (most recent call last):
  File "C:\python38\pB-42.py", line 342, in <module>
    ohlcv = exchange.fetch_ohlcv('BTC/USD', '1m')
  File "E:\Python38\lib\site-packages\ccxt\bybit.py", line 700, in fetch_ohlcv
    market = self.market(symbol)
  File "E:\Python38\lib\site-packages\ccxt\base\exchange.py", line 1815, in mark
et
    raise ExchangeError('Markets not loaded')
ccxt.base.errors.ExchangeError: Markets not loaded

**Comment by kroitor** [comment]
@Serendepon please update to CCXT version 1.38.6 (it will arrive in 20 minutes) and let us know if you still have the same issue on your side. We've uploaded a few edits and this issue should be fixed in the new version. Thanks for reporting!

**Comment by Serendepon** [comment]
Thanks Igor, works like a charm
