### ISSUE TITLE
Bybit fetchBalance Question

### ISSUE THREAD

**Issue by bigcountry-scav** [ccxt/ccxt#8010]
- OS: Win 10
- Programming Language version: JS
- CCXT version: 1.38.10

Not so much of an issue but more a question. The fetchBalance method on Bybit parses the response and uses "equity" for the totalBalance instead of wallet_balance. Why is this the case? I would think wallet_balance would be better and also align with results from say Bitmex. With equity your total balance is decreasing/increasing with unrealised pnl.

Thanks for all the work you do.

**Comment by gcamata** [comment]
Hey guys, I don't see any changes in https://github.com/ccxt/ccxt/commit/bdf9ca3428e2622a06db2443ab659b48ce5fc3da that address this-- am I missing something? Is there a reason `equity` is used instead of `wallet_balance`, which would fit the total balance model more closely? Thank you for the help!
