### ISSUE TITLE
[yobit] trade fees problem

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#8011]
yobit charges trade fees for buy orders in the quote ccy, and sell trades have the fee in the base ccy.  It looks like ccxt assumes its all in the base ccy.

**Comment by kroitor** [comment]
@npomfret can you please paste the verbose output? Because we for the fees we use the currency designed by the exchange API: https://github.com/ccxt/ccxt/blob/master/js/yobit.js#L441

**Comment by kroitor** [comment]
@npomfret feel free to reopen this, we will look into it further.
