### ISSUE TITLE
[Question] Transpiling constructor() overrides

### ISSUE THREAD

**Issue by bmschwartz** [ccxt/ccxt#8012]
I'm not having any luck getting an overridden `constructor()` in JS to translate to an `__init__()` function in Python. What is the expected behavior?

**Comment by kroitor** [comment]
The constructor is not transpiled yet, do "the thing" in the `describe()` method of a corresponding derived exchange file.

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#transpiled-generated-files

Let us know if that does not answer your question. Feel free to reopen this or just ask further questions if any.

**Comment by bmschwartz** [comment]
Thank you, that helps.
