### ISSUE TITLE
OKEX: SWAP Leverage Request - HTTP Error / Invalid JSON format

### ISSUE THREAD

**Issue by Rishirandhawa** [ccxt/ccxt#8013]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:Mac
- Programming Language version: Python 3.8
- CCXT version: Latest

```
#Instantiate OKeX Exchange
exchange_id = 'okex'
exchange_class = getattr(ccxt, exchange_id)
exchange = exchange_class({
    'apiKey': api_key,
    'secret': api_secret,
    'password' : api_passphrase,
    'timeout': 30000,
    'enableRateLimit': True,
    'options': {
        'adjustForTimeDifference': True,
        'defaultType': 'swap',
        'verbose': True
    }
})

symbol = 'ADA-USDT'
response = exchange.swap_post_accounts_instrument_id_leverage({"instrument_id": symbol})```

```
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
~/projects/trading-bot/env/lib/python3.8/site-packages/ccxt/base/exchange.py in fetch(self, url, method, headers, body)
    587             self.logger.debug("%s %s, Response: %s %s %s", method, url, http_status_code, headers, http_response)
--> 588             response.raise_for_status()
    589 

~/projects/trading-bot/env/lib/python3.8/site-packages/requests/models.py in raise_for_status(self)
    940         if http_error_msg:
--> 941             raise HTTPError(http_error_msg, response=self)
    942 

HTTPError: 400 Client Error:  for url: https://www.okex.com/api/swap/v3/accounts/ADA-USDT/leverage

During handling of the above exception, another exception occurred:

ExchangeError                             Traceback (most recent call last)
<ipython-input-25-85cd1e3a46a0> in <module>
      2 
      3 symbol = 'ADA-USDT'
----> 4 response = exchange.swap_post_accounts_instrument_id_leverage({"instrument_id": symbol})
      5 #response = exchange.swap_post_accounts_instrument_id_leverage(symbol)
      6 

~/projects/trading-bot/env/lib/python3.8/site-packages/ccxt/base/exchange.py in inner(_self, params)
    463                             if params is not None:
    464                                 inner_kwargs['params'] = params
--> 465                             return entry(_self, **inner_kwargs)
    466                         return inner
    467                     to_bind = partialer()

~/projects/trading-bot/env/lib/python3.8/site-packages/ccxt/base/exchange.py in request(self, path, api, method, params, headers, body)
    488     def request(self, path, api='public', method='GET', params={}, headers=None, body=None):
    489         """Exchange.request is the entry point for all generated methods"""
--> 490         return self.fetch2(path, api, method, params, headers, body)
    491 
    492     @staticmethod

~/projects/trading-bot/env/lib/python3.8/site-packages/ccxt/base/exchange.py in fetch2(self, path, api, method, params, headers, body)
    484         self.lastRestRequestTimestamp = self.milliseconds()
    485         request = self.sign(path, api, method, params, headers, body)
--> 486         return self.fetch(request['url'], request['method'], request['headers'], request['body'])
    487 
    488     def request(self, path, api='public', method='GET', params={}, headers=None, body=None):

~/projects/trading-bot/env/lib/python3.8/site-packages/ccxt/base/exchange.py in fetch(self, url, method, headers, body)
    602         except HTTPError as e:
    603             details = ' '.join([self.id, method, url])
--> 604             self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
    605             self.handle_http_status_code(http_status_code, http_status_text, url, method, http_response)
    606             raise ExchangeError(details) from e

~/projects/trading-bot/env/lib/python3.8/site-packages/ccxt/okex.py in handle_errors(self, code, reason, url, method, headers, body, response, requestHeaders, requestBody)
   3460             self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
   3461         if nonZeroErrorCode or nonEmptyMessage:
-> 3462             raise ExchangeError(feedback)  # unknown message

ExchangeError: okex {"error_message":"Invalid JSON format","message":"Invalid JSON format"}```

**Comment by kroitor** [comment]
If you are using the POST implicit endpoint, then you have to submit all params as required by OKEX API docs here: https://www.okex.com/docs/en/#swap-swap---leverage. 

I think you are confusing it with the GET implicit endpoint: https://www.okex.com/docs/en/#swap-swap---settings.

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

Apart from the above, you are also not using a proper instrument id for a swap market:

- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

----

Change your code like so:

```Python
symbol = 'ADA-USDT-SWAP'
response = exchange.swap_get_accounts_instrument_id_leverage({"instrument_id": symbol})
```

Let us know if that does not answer your question.

**Comment by Rishirandhawa** [comment]
Thank you. Worked perfectly!
