### ISSUE TITLE
OKEX: AssertionError while converting amount 

### ISSUE THREAD

**Issue by Rishirandhawa** [ccxt/ccxt#8018]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Mac / Linux
- Programming Language version: Py 3.8
- CCXT version: Latest

```
exchange_id = 'okex'
exchange_class = getattr(ccxt, exchange_id)
exchange = exchange_class({
    'apiKey': api_key,
    'secret': api_secret,
    'password' : api_passphrase,
    'timeout': 30000,
    'enableRateLimit': True,
    'options': {
        'adjustForTimeDifference': True,
        'defaultType': 'spot',
        'verbose': True
    }
})
markets = exchange.load_markets()

instrument = 'ADA/USDT'
amount = 600.18984208275957
amount_precision = exchange.markets[instrument]['precision']['amount']
trade_amount = exchange.decimal_to_precision(amount, TRUNCATE, amount_precision, DECIMAL_PLACES)
print(trade_amount)```

```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-154-c68a3657c51d> in <module>
     18 amount = 600.18984208275957
     19 amount_precision = exchange.markets[instrument]['precision']['amount']
---> 20 trade_amount = exchange.decimal_to_precision(amount, TRUNCATE, amount_precision, DECIMAL_PLACES)
     21 print(trade_amount)

~/projects/trading-bot/env/lib/python3.8/site-packages/ccxt/base/decimal_to_precision.py in decimal_to_precision(n, rounding_mode, precision, counting_mode, padding_mode)
     39         assert(isinstance(precision, float) or isinstance(precision, numbers.Integral))
     40     else:
---> 41         assert(isinstance(precision, numbers.Integral))
     42     assert rounding_mode in [TRUNCATE, ROUND]
     43     assert counting_mode in [DECIMAL_PLACES, SIGNIFICANT_DIGITS, TICK_SIZE]

AssertionError: 

ADDITIONAL INFO - Seems  exchange.markets[instrument]['precision']['amount'] is returning float instead of int```

**Comment by kroitor** [comment]
This is not an issue, please read the Manual on precision modes, `TICK_SIZE` in particular:

- https://github.com/ccxt/ccxt/wiki/Manual#methods-for-formatting-decimals

**Comment by kroitor** [comment]
@Rishirandhawa change your code like so:

```Python
amount_precision = exchange.markets[instrument]['precision']['amount']
trade_amount = exchange.decimal_to_precision(amount, TRUNCATE, amount_precision, exchange.precisionMode)
```

or better use amountToPrecision:

```Python
trade_amount = exchange.amount_to_precision(symbol, amount)
```

Hope that helps. Let me know if not.

**Comment by Rishirandhawa** [comment]
Worked like charm! Thank you.
