### ISSUE TITLE
Creating Trailing Stop Limit on Phemex

### ISSUE THREAD

**Issue by efz00** [ccxt/ccxt#8021]
- OS: Mac
- Programming Language version: Python 3.6
- CCXT version: 1.38.13
I'm trying to create a stoplimit trailing buy order on phemex. My goal is to make my bot create this order .05 below current bid.

```
        phemex.create_order(symbol = 'ETH/USD', type = 'StopLimit', side = 'buy', amount = 1, params = {
            'ordType': 'StopLimit',
            'pegPriceType': 'TrailingStopPeg',
            'pegOffsetValueEp': .05,
            'triggerType': 'ByLastPrice'
                        })
```

This code is throwing this error: ccxt.base.errors.InvalidOrder: phemex {"code":11046,"msg":"TE_TRIGGER_PRICE_TOO_SMALL","data":null}

The phemex api says that this error means "Details: Conditional order trigger price is too low". Not sure what I need to change here.

Any help is appreciated, thanks!

**Comment by carlosmiei** [comment]
Hello @efz00 
To create a stop-limit order, it's mandatory to specify the price at which the asset should be bought or sold (trigger price) and the stop price.

I've also noticed that you're using a spot symbol, but trailing orders are only available in contract trading. Lastly, the `pegOffsetValueEp` needs to be scaled too.

So for your example to work, I needed to tweak it a bit:

```Python
ethSymbol = 'ETH/USD:USD'
ethPrice = 1000
stopPrice = 5000
trailingOrder = exchange.create_order(symbol = ethSymbol, type = 'StopLimit', side = 'buy', amount = 1, price = ethPrice, params = {
    'stopPrice': stopPrice,
    'ordType': 'StopLimit',
    'pegPriceType': 'TrailingStopPeg',
    'pegOffsetValueEp': 10000, # needs to be scaled
    'triggerType': 'ByMarkPrice'
    }
)
```
If you don't want to define these prices, you can opt for a stop-market order instead. You can check out an example here  https://github.com/ccxt/ccxt/blob/master/examples/py/phemex-open-cancel-close-positions.py#L37
