### ISSUE TITLE
Binance fee sometimes wrong

### ISSUE THREAD

**Issue by xmatthias** [ccxt/ccxt#8025]
- OS: linux (not relevant)
- Programming Language version: python (not relevant)
- CCXT version: 1.38.13 (i know it's not the very latest, but it's not really relevant for the below either).

According to the [ccxt manual](https://github.com/ccxt/ccxt/wiki/Manual#order-structure) - ccxt will provide a order as follows.
<details>
<summary>Expand for details)</summary>

``` js
{
    'id':                '12345-67890:09876/54321', // string
    'clientOrderId':     'abcdef-ghijklmnop-qrstuvwxyz', // a user-defined clientOrderId, if any
    'datetime':          '2017-08-17 12:42:48.000', // ISO8601 datetime of 'timestamp' with milliseconds
    'timestamp':          1502962946216, // order placing/opening Unix timestamp in milliseconds
    'lastTradeTimestamp': 1502962956216, // Unix timestamp of the most recent trade on this order
    'status':      'open',        // 'open', 'closed', 'canceled'
    'symbol':      'ETH/BTC',     // symbol
    'type':        'limit',       // 'market', 'limit'
    'timeInForce': 'GTC',         // 'GTC', 'IOC', 'FOK', 'PO'
    'side':        'buy',         // 'buy', 'sell'
    'price':        0.06917684,   // float price in quote currency (may be empty for market orders)
    'average':      0.06917684,   // float average filling price
    'amount':       1.5,          // ordered amount of base currency
    'filled':       1.1,          // filled amount of base currency
    'remaining':    0.4,          // remaining amount to fill
    'cost':         0.076094524,  // 'filled' * 'price' (filling price used where available)
    'trades':     [ ... ],        // a list of order trades/executions
    'fee': {                      // fee info, if available
        'currency': 'BTC',        // which currency the fee is (usually quote)
        'cost': 0.0009,           // the fee amount in that currency
        'rate': 0.002,            // the fee rate (if available)
    },
    'info': { ... },              // the original unparsed order structure as is
}
```

</details>

For binance, this order structure is returned for both `create_order()`, as well as for `fetch_order()`.

According to my observations, the `fee` key is always empty for `fetch_order()` calls (probably because the API does not provide this info).

However, for `create_order()` calls (with orders that fill immediately, like market orders) the fee structure is populated based on `fills`

Relevant code snippet:
https://github.com/ccxt/ccxt/blob/2a0ccc3e5e8fc71c08d8b8feced4e9f770603fff/js/binance.js#L1541-L1555

This will work great as long as the Fee currency is the same across all trades, however recently we've observed multiple occurances where the fee currency is different between single trades that executed as part of one order.

Unfortunately, we don't have the API response values (as this seems to be a somehow isolated problem only happening from time to time (so far i've seen it 3 times from different users).

(example screenshot).
![image](https://user-images.githubusercontent.com/9531438/99936116-a4cee700-2d62-11eb-96da-a47450fa06d0.png)

The below is a fake-response from the API (based on the Binance documentation, matching the above screenshot's sells).

``` jsonc
{
  "symbol": "ETHUSDT",
  "orderId": xx,
  "orderListId": -1, //Unless OCO, value will be -1
  "clientOrderId": "xxx",
  "transactTime": 0000000000,
  "price": "0.00000000",
  "origQty": "0.08933",
  "executedQty": "0.08933",
  "cummulativeQuoteQty": "0.08933",
  "status": "FILLED",
  "timeInForce": "GTC",
  "type": "MARKET",
  "side": "SELL",
  "fills": [
{
      "price": "563.24",
      "qty": "0.00001",
      "commission": "0.00000013",
      "commissionAsset": "BNB"
    },
    {
      "price": "564.24",
      "qty": "0.08932",
      "commission": "0.05030681",
      "commissionAsset": "USDT"
    }
  ]
}

```

Based on the code linked above, this will result in a fee key as follows:

``` js
//... 
'fee': {
    'currency': 'BNB', //Currency is taken from the first trade
    'cost': 0.05030694, //  0.05030681 + 0.00000013
}
```

This would suggest that a fee of 0.05 BNB was paid - which however is not quite reality - as in reality, 0.051 USDT was paid max (taking rounding etc. into account).

---

I understand that the ccxt structure does not allow for more than 1 fee currency to be present at any given point, and i guess changing this might not be easy, as it would break everyones code relying on fee beeing an object, not an array.
An alternative would be to "give up" if more than one currency is found - and leave the fee-object empty.
While this would take away "some" convenience, i think not having this is better than returning a wrong result.

**Comment by kroitor** [comment]
> I understand that the ccxt structure does not allow for more than 1 fee currency to be present at any given point, and i guess changing this might not be easy, as it would break everyones code relying on fee beeing an object, not an array.

It actually does, we sometimes return an array of `fees` if a single `fee` is not decideable due to mixed currencies, for example: bigone, bitpanda, bithumb, hbtc, itbit, okex. Will add that to Binance as well.

**Comment by xmatthias** [comment]
Oh i wasn't aware of this!
Would be good to also add this to the documentation, then ;)

**Comment by frosty00** [comment]
this has been fixed in safeOrder2
