### ISSUE TITLE
How to find current leverage on Binance

### ISSUE THREAD

**Issue by cadmufasa** [ccxt/ccxt#8027]
- OS: Linux
- Programming Language version: Python 3.7
- CCXT version:  1.34.38

```
```
Hello,

**I know that the following code** 

[... snip ...]

exchange = t_icon.initialize_connection( market_type )
exchange.load_markets()
positions = exchange.fapiPrivate_get_positionrisk() 

[... snip ...]

**produces the following output**
```

{'data': [{'entryPrice': '607.27308',
           'isAutoAddMargin': 'false',
           'isolatedMargin': '0.00000000',
           'leverage': '20'  <---- looking for this
           'liquidationPrice': '0',
           'marginType': 'cross',
           'markPrice': '614.58000000',
           'maxNotionalValue': '1000000',
           'positionAmt': '2.000',
           'positionSide': 'LONG',
           'symbol': 'ETHUSDT',
           'unRealizedProfit': '14.61384000'},
          {'entryPrice': '18437.40000',
           'isAutoAddMargin': 'false',
           'isolatedMargin': '7.60823434',
           leverage': '3',   <----- looking for this
           'liquidationPrice': '15854.31916331',
           'marginType': 'isolated',
           'markPrice': '18326.98000000',
           'maxNotionalValue': '200000000',
           'positionAmt': '0.003',
           'positionSide': 'LONG',
           'symbol': 'BTCUSDT',
           'unRealizedProfit': '-0.33126000'}],




```
```

```
**Question**: How can one find the leverage without using  **exchange.fapiPrivate_get_positionrisk()** ?

**Goal:** to see the current value of the leverage (do not want to have to fetch positions in order to find out what the current leverage is)

**Comment by kroitor** [comment]
Hi! Binance does not have an account-wide leverage setting. It has leverage per position. You can get your current leverage for a specific symbol/position from the list of positions as you've posted above. You can set your initial leverage on a symbol/position with the `fapiPrivatePostLeverage` implicit method.

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

```Python
import ccxt
from pprint import pprint

print(ccxt.__version__)

exchange = ccxt.binance({
    'enableRateLimit': True,
    'options': 'defaultType': { 'future': },
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})

markets = exchange.load_markets()

symbol = 'BTC/USDT'
market = exchange.market(symbol)

response = exchange.fapiPrivatePostLeverage({
    'symbol': market['id'],  # market id
    'leverage': 1,  # 1-255
})

pprint(response)
```

Let us know if that does not answer your question.

**Comment by ilhanketrez** [comment]
> Hi! Binance does not have an account-wide leverage setting. It has leverage per position. You can get your current leverage for a specific symbol/position from the list of positions as you've posted above. You can set your initial leverage on a symbol/position with the `fapiPrivatePostLeverage` implicit method.
> 
> * https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
> 
> ```python
> import ccxt
> from pprint import pprint
> 
> print(ccxt.__version__)
> 
> exchange = ccxt.binance({
>     'enableRateLimit': True,
>     'options': 'defaultType': { 'future': },
>     'apiKey': 'YOUR_API_KEY',
>     'secret': 'YOUR_SECRET',
> })
> 
> markets = exchange.load_markets()
> 
> symbol = 'BTC/USDT'
> market = exchange.market(symbol)
> 
> response = exchange.fapiPrivatePostLeverage({
>     'symbol': market['id'],  # market id
>     'leverage': 1,  # 1-255
> })
> 
> pprint(response)
> ```
> 
> Let us know if that does not answer your question.

Hi

> Hi! Binance does not have an account-wide leverage setting. It has leverage per position. You can get your current leverage for a specific symbol/position from the list of positions as you've posted above. You can set your initial leverage on a symbol/position with the `fapiPrivatePostLeverage` implicit method.
> 
> * https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
> 
> ```python
> import ccxt
> from pprint import pprint
> 
> print(ccxt.__version__)
> 
> exchange = ccxt.binance({
>     'enableRateLimit': True,
>     'options': 'defaultType': { 'future': },
>     'apiKey': 'YOUR_API_KEY',
>     'secret': 'YOUR_SECRET',
> })
> 
> markets = exchange.load_markets()
> 
> symbol = 'BTC/USDT'
> market = exchange.market(symbol)
> 
> response = exchange.fapiPrivatePostLeverage({
>     'symbol': market['id'],  # market id
>     'leverage': 1,  # 1-255
> })
> 
> pprint(response)
> ```
> 
> Let us know if that does not answer your question.

Hi,

Can we get the set leverage (and/or min/max leverages) of a market (etc BTC/USDT) before opening a position?

**Comment by ilhanketrez** [comment]
Hi,

Can we get the set leverage (and/or min/max leverages) of a market (etc BTC/USDT) before opening a position?

**Comment by carlosmiei** [comment]
> TC/USDT)

Hello @ilhanketrez, you can, but if you're handing derivatives a I would use the unified symbol instead (BTC/USDT:USDT)

**Comment by ilhanketrez** [comment]
Thanks but usage is still not clear to me.

exchange.load_markets()["BTC/USDT"] returns many market properties but exchange.load_markets()["BTC/USDT:USDT"] returns error.

**Comment by tatolevicz** [comment]
> Hi,
> 
> Can we get the set leverage (and/or min/max leverages) of a market (etc BTC/USDT) before opening a position?

i'm looking for this and it actually doesn't seem to exist. How one can get the leverage for a symbol before open a position?
