### ISSUE TITLE
Binance Futures get funding rate

### ISSUE THREAD

**Issue by topchatz** [ccxt/ccxt#8028]
- OS: Mac
- Programming Language version: Python 3.7
- CCXT version: 1.38.9
- Exchange: Binance Futures

Hi, apologies for the stupid question, but I can't find anything via google to help. I'm trying to get the funding rate for example for BTC/USDT on Binance Futures (currently about 0.066%).

I have the exchange set up as this:

binancefFutures = ccxt.binance({'enableRateLimit': True,
    'options': {'defaultType': 'future'},})

I came across this thread:

https://github.com/ccxt/ccxt/issues/6535

But I'm not smart enough to work out how to use it, and get the current funding rate and even the historical funding.

Any help would be really appreciated, cheers

**Comment by kroitor** [comment]
I'd highly recommend to read the docs from top to bottom: https://github.com/ccxt/ccxt/wiki/Manual, there's nothing out of the ordinary, and it will really save your time.

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
- https://github.com/ccxt/ccxt/wiki/Manual#passing-parameters-to-api-methods
- https://binance-docs.github.io/apidocs/futures/en/#get-funding-rate-history

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
from pprint import pprint

exchange = ccxt.binance({
    'enableRateLimit': True,
    'options': {
        'defaultType': 'future',
    },
})

markets = exchange.load_markets()
# exchange.verbose = True  # uncomment for debugging

symbol = 'BTC/USDT'
market = exchange.market(symbol)

response = exchange.fapiPublic_get_fundingrate({
    'symbol': market['id'],
    # 'startTime': exchange.parse8601('2020-11-25T00:00:00Z'),  # ms to get funding rate from INCLUSIVE.
    # 'endTime': exchange.parse8601('2020-11-26T00:00:00Z'),  # ms to get funding rate until INCLUSIVE.
    # 'limit': 100,  # default 100, max 1000
})

pprint(response)
```

Let us know if the above does not answer your question. Feel free to reopen this issue or just ask further questions, if any.

**Comment by thisisloze** [comment]
This doesnt work for nodejs.
`const ccxt = require ('ccxt')
const exchange = new ccxt["binance"]({ enableRateLimit: true });
(async function () {
console.log(await exchange.fapiPublic_get_openInterest("BTC/USDT"))
}) ();`

exchange.fapiPublic_get_openInterest is not a function

**Comment by kroitor** [comment]
@thisisloze you should use it as described in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

```JavaScript
const ccxt = require ('ccxt')
console.log ('CCXT Version:', ccxt.version) // make sure it's the latest

const exchange = new ccxt.binance({
    'enableRateLimit': true,
    'options': { 'defaultType': 'future' },
})

async function main () {

    await exchange.loadMarkets ()
    
    const symbol = 'BTC/USDT'
    const market = exchange.market (symbol)
    
    const response = await exchange.fapiPublicGetOpenInterest({'symbol': market['id']})
    console.log (response)
}

main()
```

```
~/ccxt $ node examples/js/cli binance | grep terest
  sapiGetMarginInterestHistory: [AsyncFunction: partial],
  sapi_get_margin_interesthistory: [AsyncFunction: partial],
  sapiGetLendingUnionInterestHistory: [AsyncFunction: partial],
  sapi_get_lending_union_interesthistory: [AsyncFunction: partial],
  dapiPublicGetOpenInterest: [AsyncFunction: partial],
  dapiPublic_get_openinterest: [AsyncFunction: partial],
  dapiDataGetOpenInterestHist: [AsyncFunction: partial],
  dapiData_get_openinteresthist: [AsyncFunction: partial],
  fapiPublicGetOpenInterest: [AsyncFunction: partial],
  fapiPublic_get_openinterest: [AsyncFunction: partial],
  fapiDataGetOpenInterestHist: [AsyncFunction: partial],
  fapiData_get_openinteresthist: [AsyncFunction: partial],
```

**Comment by thisisloze** [comment]
Thanks!

**Comment by Madanraj-Delta** [comment]
How to find fapiPublic_get_fundingrate is the name for funding rate ? Couldnt able to get that.

**Comment by kroitor** [comment]
@Madanraj-Delta you can get a list of all implicit endpoints as documented in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api

**Comment by Madanraj-Delta** [comment]
If there is not endpoint in api but has a websocket can i get it here..

**Comment by kroitor** [comment]
@Madanraj-Delta There is an endpoint for funding rates:

```Python
import ccxt
exchange = ccxt.binance()
methods = list(dir(exchange))
for method in methods:
    if 'funding' in method:
        print(method)
```

You can call those endpoints as documented in the Manual: 

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api
- https://github.com/ccxt/ccxt/wiki/Manual#passing-parameters-to-api-methods

I would recommend using the unified method instead: 

```Python
import ccxt
from pprint import pprint
exchange = ccxt.binance()
pprint(exchange.has)
```

- https://github.com/ccxt/ccxt/blob/master/python/ccxt/binance.py#L3718
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/binance.py#L3748
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/binance.py#L4313
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/binance.py#L3808
- ...

In general, I'd highly recommend reading the entire Manual from top to bottom – it has the answers to most of these questions and it will really save your time.

**Comment by Madanraj-Delta** [comment]
Could you please help me in other exchange other than binance. And in binance there is "dapiPublic_get_fundingrate" in methods but not inside the binance.py . Couldnt understand..

**Comment by kroitor** [comment]
@Madanraj-Delta 

> And in binance there is "dapiPublic_get_fundingrate" in methods but not inside the binance.py

This is answered here: 

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
- https://github.com/ccxt/ccxt/wiki/Manual#api-method-naming-conventions

**Comment by Madanraj-Delta** [comment]
Thank you 


okex_response=okex_exchange.public_get_public_funding_rate({
    "instId": "BTC-USD-SWAP",
})

**Comment by kroitor** [comment]
@Madanraj-Delta the rate limits should be handled for you as described here: 

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/wiki/Manual#notes-on-rate-limiter

Also, check the examples here:

- https://github.com/ccxt/ccxt/tree/master/examples/
- https://github.com/ccxt/ccxt/tree/master/examples/py
- https://github.com/ccxt/ccxt/tree/master/examples/#see-also

**Comment by Madanraj-Delta** [comment]
In Bitfinex, couldnt see the funding rate so the exchange doesnt offer it? Its the case..  @kroitor

**Comment by kroitor** [comment]
@Madanraj-Delta check these endpoints:

```Python
import ccxt
exchange = ccxt.bitfinex2()
methods = list(dir(exchange))
for method in methods:
    if 'funding' in method:
        print(method)
```

**Comment by Madanraj-Delta** [comment]
Does ending with 2 defines the version? 
```
fetch_funding_fee
fetch_funding_fees
parse_funding_rate
parse_funding_rates
private_post_auth_r_funding_credits
private_post_auth_r_funding_credits_hist
private_post_auth_r_funding_credits_symbol
private_post_auth_r_funding_credits_symbol_hist
private_post_auth_r_funding_loans
private_post_auth_r_funding_loans_hist
private_post_auth_r_funding_loans_symbol
private_post_auth_r_funding_loans_symbol_hist
private_post_auth_r_funding_offers
private_post_auth_r_funding_offers_hist
private_post_auth_r_funding_offers_symbol
private_post_auth_r_funding_offers_symbol_hist
private_post_auth_r_funding_trades_hist
private_post_auth_r_funding_trades_symbol_hist
private_post_auth_r_info_funding_key
private_post_auth_w_funding_auto
private_post_auth_w_funding_close
private_post_auth_w_funding_keep
private_post_auth_w_funding_offer_cancel
private_post_auth_w_funding_offer_cancel_all
private_post_auth_w_funding_offer_submit
public_get_funding_stats_symbol_hist
```
These methods are there and there is no funding rate mentioned..
And i couldnt see funding rate in their api also.. Does the provide.. @kroitor

**Comment by Madanraj-Delta** [comment]
Couldnt see in huobi and huobi pro too..

@kroitor

**Comment by kroitor** [comment]
@Madanraj-Delta Huobi Futures are not supported in CCXT yet, but will be added within a few days.

**Comment by Madanraj-Delta** [comment]
ok thank you

**Comment by Madanraj-Delta** [comment]
In Delta-Exchange, there is funding rates in tickers api. that not in methods.. Please add the same..
`
https://api.delta.exchange/v2/tickers`

Here there is funding rates mentioned above url but not in the below code.
```

import ccxt
exchange = ccxt.delta()
methods = list(dir(exchange))
for method in methods:
    if 'funding' in method:
        print(method)
```
```
fetch_funding_fee
fetch_funding_fees
parse_funding_rate
parse_funding_rates
```

@kroitor

**Comment by avatar-lavventura** [comment]
> ```bash
> response = await exchange.fapiPublicGetOpenInterest()
> ```
> 

Is it normal that this function does not return funding rate for `BELUSDTPERP`?

**Comment by kroitor** [comment]
@avatar-lavventura absolutely normal, since that is the exchange-specific endpoint for open interest, not for funding rate. I suggest using the `exchange.fetchFundingRate()` unified method instead.

**Comment by avatar-lavventura** [comment]
With ` "limit": 1000` parameter I was able to fetch `BELUSDT`  as well. I will look into `binanceusdm.fetchFundingRate` thanks

**Comment by avatar-lavventura** [comment]
With ` "limit": 1000` parameter I was able to fetch `BELUSDT`  as well.

I will look into `binanceusdm.fetchFundingRate` thanks ; seems like we hava to provide symbol, hence we have to make individiual calls for all the symbols in `USDTPERP` one by one , if we want to fetch fundingRate for all

**Comment by avatar-lavventura** [comment]
Hoping this might help someone, I fetch with funding rates > 0.75%:

```python
#!/usr/bin/env python3

import ccxt


def main():
    #  https://docs.ccxt.com/en/latest/manual.html#funding-rate
    exchange = ccxt.binanceusdm(
        {
            "enableRateLimit": True,
            "options": {
                "defaultType": "future",
            },
        }
    )
    funding = {}
    response = exchange.fetchFundingRates()
    for symbol in response:
        funding_rate = response[symbol]["info"]["lastFundingRate"]
        if abs(float(funding_rate)) > 0.0075:
            funding[symbol] = response[symbol]["info"]
            funding[symbol]["lastFundingRate"] = float(funding[symbol]["lastFundingRate"])

    print(funding)


if __name__ == "__main__":
    main()
```

**Comment by BamsoonPapa** [comment]
@kroitor 
Hello, I want to find out funding fee history with CCXT. Not funding rate. In Binance mobile app., we can find out our own funding fee amount exactly. Is it possible to access exact funding fee amounts of certain SYMBOL? (I have implemented logic which can calculate funding fee with 'funding rate history' but it had small inaccuracy. So I asked.)
