### ISSUE TITLE
'phemex' object has no attribute 'safeStirng'

### ISSUE THREAD

**Issue by kostanjsek** [ccxt/ccxt#8030]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:  Ubuntu 18.04.5 LTS
- Programming Language version: Python 3.6.9
- CCXT version: 1.38.13

import ccxt
exchange = ccxt.phemex({...api data...})
res = exchange.createOrder('LTC/USDT', 'limit', 'buy', 1, 50)

OUTPUT:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ccxt/phemex.py", line 1803, in create_order
    return self.parse_order(data, market)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/phemex.py", line 1669, in parse_order
    return self.parse_spot_order(order, market)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/phemex.py", line 1566, in parse_spot_order
    timeInForce = self.parse_time_in_force(self.safeStirng(order, 'timeInForce'))
AttributeError: 'phemex' object has no attribute 'safeStirng'

**Comment by kroitor** [comment]
Hi @kostanjsek ! Thx for reporting this typo! @ndubel has fixed it in 1.38.14+, the new build will arrive in 20 minutes. Let us know if you have further difficulties with it.
