### ISSUE TITLE
HitBtc fetch_balance return only first 300 balances

### ISSUE THREAD

**Issue by kostanjsek** [ccxt/ccxt#8031]
HitBTC fetch balance returns balance only for first 300 coins. If there are balances for the rest of the coins you will not see them.

- OS: Ubuntu 18.04.5 LTS
- Programming Language version: Python 3.6.9
- CCXT version: 1.38.13

```
import ccxt
exchange = ccxt.hitbtc({...api_data...})
res = exchange.fetch_balance()
```

```
Unable to handle::'Too large to show contents. Max items to show: 300'
```

**Comment by kroitor** [comment]
Hi @kostanjsek ! Can you please paste your full verbose output?

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.hitbtc({...api_data...})
markets = exchange.load_markets()
exchange.verbose = True  # after load_markets(), to reduce the output
res = exchange.fetch_balance()
```

**Comment by kostanjsek** [comment]
It was a bug in VS Code, not showing more than 300 results. It works fine in CLI.
Thank you for your quick response.

**Comment by kroitor** [comment]
@kostanjsek thanks for your feedback!
