### ISSUE TITLE
Bybit fetchOrders(): Database [db_user_data] not configured

### ISSUE THREAD

**Issue by Serendepon** [ccxt/ccxt#8034]
Hello Igor!
fetchOrders() stop working

- OS: Windows
- Programming Language version: Python
- CCXT version: 1.38.16
- Exchange: Bybit testnet

```
import ccxt
from pprint import pprint
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.bybit({'enableRateLimit': True})
exchange.verbose = True  # uncomment for debugging purposes

exchange.set_sandbox_mode(True)
markets = exchange.load_markets()

print('CCXT Version:', ccxt.__version__)
orders2 = bybit.fetchOrders('BTC/USD')
```

```
CCXT Version: 1.38.16

Request: GET https://api-testnet.bybit.com/open-api/order/list?api_key=eqXX1IqKg
JW2OkSqha&recv_window=5000&symbol=BTCUSD&timestamp=1606269315789&sign=25d8d09916
d3f30867ef222582359aaef77cc193824c350b647c98768c9bdcf4 {'Accept-Encoding': 'gzip
, deflate'} None

Response: GET https://api-testnet.bybit.com/open-api/order/list?api_key=eqXX1IqK
gJW2OkSqha&recv_window=5000&symbol=BTCUSD&timestamp=1606269315789&sign=25d8d0991
6d3f30867ef222582359aaef77cc193824c350b647c98768c9bdcf4 200 {'Content-Type': 'ap
plication/json', 'Server': 'nginx', 'Access-Control-Allow-Origin': '*', 'Access-
Control-Allow-Credentials': 'false', 'Content-Encoding': 'gzip', 'Expires': 'Wed
, 25 Nov 2020 01:55:16 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', '
Pragma': 'no-cache', 'Date': 'Wed, 25 Nov 2020 01:55:16 GMT', 'Content-Length':
'165', 'Connection': 'keep-alive', 'Vary': 'Accept-Encoding'} {"ret_code":-1,"re
t_msg":"Database [db_user_data] not configured.","ext_code":"","result":null,"ex
t_info":null,"time_now":"1606269316.023710","rate_limit_status":599,"rate_limit_
reset_ms":1606269316033,"rate_limit":600}
```

**Comment by kroitor** [comment]
@Serendepon this is the response from the exchange: `{"ret_code":-1,"re
t_msg":"Database [db_user_data] not configured.","ext_code":"","result":null,"ex
t_info":null,"time_now":"1606269316.023710","rate_limit_status":599,"rate_limit_
reset_ms":1606269316033,"rate_limit":600}`. Have you checked your account/keys on the testnet?

**Comment by Serendepon** [comment]
Yeah, i just created a new pair of keys and tryed with it - still same result

**Comment by kroitor** [comment]
@Serendepon they're migrating to v2, i'll upload a fix asap.

**Comment by alesha1488** [comment]
Programming Language version: PHP
CCXT version: 1.38.34
Exchange: Bybit testnet

same error for me

[Exchange Error] bybit {"ret_code":-1,"ret_msg":"Database [db_user_data] not configured.","ext_code":"","result":null,"ext_info":null,"time_now":"1606468034.555418","rate_limit_status":599,"rate_limit_reset_ms":1606468034564,"rate_limit":600}

**Comment by kroitor** [comment]
@alesha1488 i'm working on a fix, hope to get it resolved soon.

**Comment by Serendepon** [comment]
Aaaand it's working now

**Comment by kroitor** [comment]
@Serendepon the problem is harder to solve, since apparently Bybit is changing the output on their end, we haven't fixed it on our side yet (working on their v2 updates right now).

**Comment by shoemoney** [comment]
If your messing with the linear side i swear it updates weekly...
