### ISSUE TITLE
New exchanges that accept BitGo transfers

### ISSUE THREAD

**Issue by zzo** [ccxt/ccxt#804]
Besides Bitstamp they are:

bitquick, coinhako, fold, genesis, korbit, paxful, triv, unocoin, and wirex

instant btc transfers = easy arb :)  

thanks for the killer module!

(oh list came from https://www.bitgo.com/solutions#instant)

**Comment by kroitor** [comment]
Hi!

- bitquick is forwarding me to localbitcoins, they don't have an orderbook, no usual means of conventional trading, requires a direct contact between the buyer and the seller, not an exchange in common sense
- coinhako is a wallet service, no API, not an exchange at all
- fold - I can't even find their site in google, it's an end-user application, not an exchange
- genesistrading – no API, can't find any useful docs
- korbit – **will integrate soon**
- paxful – not an exchange, but an offer aggregation system, no conventional API
- triv - not a conventional exchange, just a money processing/conversion service, no API
- unocoin – a wallet service, not a conventional exchange
- wirex – not an exchange, it's a fiat conversion application

> instant btc transfers = easy arb :)

instant btc transfers + 3 days per a fiat transfer = shitty arb :)

> thanks for the killer module!

Thanks for your feedback! It is really important to us! )
