### ISSUE TITLE
Binance Future Testnet : binance does not have market symbol X

### ISSUE THREAD

**Issue by safwen1** [ccxt/ccxt#8041]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Ubuntu
- Programming Language version: Python
- CCXT version:  1.38.20

```
exchange_data = {
                'timeout': 10000,
                'enableRateLimit': True,
                'options': {
                    'defaultType': 'future',
                }
            }

exchange = getattr(ccxt, 'binance')(exchange_data)

# To use Future testnet API ( https://testnet.binancefuture.com/ )
exchange.urls['api']['fapiPublic'] = exchange.urls['test']['fapiPublic']
exchange.urls['api']['fapiPrivate'] = exchange.urls['test']['fapiPrivate']
exchange.urls['api']['fapiPrivateV2'] = exchange.urls['test']['fapiPrivateV2']

last_price = float((await exchange.fetch_ticker('ETH/USDT'))['last'])
```

```

Error : binance does not have market symbol ETH/USDT
```

The same code works if we are using Binance Future production API. The testnet used to work too in previous Binance versions ( or maybe previous CCXT versions ? )

**Comment by kroitor** [comment]
Please, paste your actual runtime version of CCXT, run this snippet in your Python:

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
```

**Comment by safwen1** [comment]
@kroitor We are using CCXT pro :

CCXT Version: 1.38.20
CCXT Pro Version: 0.4.55

**Comment by kroitor** [comment]
@safwen1 looks like Binance has updated their API again, uploading the patch now...

**Comment by kroitor** [comment]
Ok, the fix will arrive in 20 minutes or so. Thanks for reporting this issue!

1. Wait ~20 minutes for the auto build to finish.
2. Update CCXT to 1.38.26+
3. Update CCXT Pro to 0.4.76+
4. Run the exact code snippet below.
5. Please, paste your verbose output if it doesn't work.

```Python
import ccxt.async_support as ccxt
import ccxtpro
from asyncio import gather, get_event_loop
from pprint import pprint


print('CCXT Version:', ccxt.__version__)
print('CCXT Pro Version:', ccxtpro.__version__)


async def main(asyncio_loop):
    print('Starting', id)
    exchange = ccxtpro.binance({
        'enableRateLimit': True,
        'asyncio_loop': asyncio_loop,
        'options': {
            'defaultType': 'future',
        },
    })
    exchange.set_sandbox_mode(True)
    markets = await exchange.load_markets()
    # exchange.verbose = True
    print('----------------------------------------------------------------')
    ticker = await exchange.fetch_ticker('ETH/USDT')
    pprint(ticker)
    await exchange.close()


if __name__ == '__main__':
    asyncio_loop = get_event_loop()
    asyncio_loop.run_until_complete(main(asyncio_loop))
```

Let us know if that does not help.

**Comment by safwen1** [comment]
@kroitor Our CCXT **pro** subscription is over so I won't be able to make that update. However updating the free CCXT seems to fix it. Cheers!

**Comment by kroitor** [comment]
@safwen1 yes, the problem is fixed in CCXT, and CCXT Pro inherits from there.
