### ISSUE TITLE
Liquid createOrder response cost properties undefined 

### ISSUE THREAD

**Issue by julesGoullee** [ccxt/ccxt#8043]
CCXT version: 1.38.28
When calling `createOrder` type market, the cost properties in the response is undefined

**Comment by kroitor** [comment]
Hi @julesGoullee ! Can you please paste your request+response in verbose mode?

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```Python
markets = exchange.load_markets()
exchange.verbose = True  # after loading the markets
exchange.create_order(symbol, ...
```

↑ Plz, paste the request and the response.

**Comment by julesGoullee** [comment]
@kroitor please find there the log in verbose:

```
fetch:
 liquid POST https://api.liquid.com/orders 
Request:
 {"order_type":"market","product_id":"690","side":"sell","quantity":"3000"} 

handleRestResponse:
 liquid POST https://api.liquid.com/orders 200 OK 
Response:
 {"id":3556871340,"order_type":"market","quantity":"3000.0","disc_quantity":"0.0","iceberg_total_quantity":"0.0","side":"sell","filled_quantity":"3000.0","price":0.00000013,"created_at":1606584065,"updated_at":1606584065,"status":"filled","leverage_level":1,"source_exchange":"QUOINE","product_id":690,"margin_type":null,"take_profit":null,"stop_loss":null,"trading_type":"spot","product_code":"CASH","funding_currency":"BTC","crypto_account_id":null,"currency_pair_code":"AMNBTC","average_price":0.0,"target":"spot","order_fee":0.0,"source_action":"manual","unwound_trade_id":null,"trade_id":null,"client_order_id":null} 
```


The order returned by ccxt:
```
{
  id: '3556871340',
  clientOrderId: undefined,
  timestamp: 1606584065000,
  datetime: '2020-11-28T17:21:05.000Z',
  lastTradeTimestamp: undefined,
  type: 'market',
  timeInForce: undefined,
  status: 'closed',
  symbol: 'AMN/BTC',
  side: 'sell',
  price: 1.3e-7,
  amount: 3000,
  filled: 3000,
  cost: undefined,
  remaining: 0,
  average: 0,
  trades: [],
  fee: { currency: 'BTC', cost: 0 },
  info: {
    id: 3556871340,
    order_type: 'market',
    quantity: '3000.0',
    disc_quantity: '0.0',
    iceberg_total_quantity: '0.0',
    side: 'sell',
    filled_quantity: '3000.0',
    price: 1.3e-7,
    created_at: 1606584065,
    updated_at: 1606584065,
    status: 'filled',
    leverage_level: 1,
    source_exchange: 'QUOINE',
    product_id: 690,
    margin_type: null,
    take_profit: null,
    stop_loss: null,
    trading_type: 'spot',
    product_code: 'CASH',
    funding_currency: 'BTC',
    crypto_account_id: null,
    currency_pair_code: 'AMNBTC',
    average_price: 0,
    target: 'spot',
    order_fee: 0,
    source_action: 'manual',
    unwound_trade_id: null,
    trade_id: null,
    client_order_id: null
  }
}
```

**Comment by julesGoullee** [comment]
@kroitor As I can see in liquid.js file, the response parser expects trades but seems to be empty

**Comment by kroitor** [comment]
@julesGoullee yeah, basically, there's no way to tell the cost from the info provided by the exchange API.

**Comment by kroitor** [comment]
@julesGoullee i'd suggest to forward a request to Liquid's tech support asking to add it to their API, i'd close this issue until they add it on their side. What do you say?

**Comment by julesGoullee** [comment]
@kroitor So I received an answer from the Liquid team: "Please try to fetch the order after getting a successful create order, which shows the order as filled."
Do you think it makes sense to implement this way?

**Comment by kroitor** [comment]
@julesGoullee 

> So I received an answer from the Liquid team: "Please try to fetch the order after getting a successful create order, which shows the order as filled."

thanks for the feedback!

> Do you think it makes sense to implement this way?

Liquid's `fetchOrder()` is already implemented, however, it is up to you to call it, we will not do this automatically in CCXT for reasons related to rate-limiting and other technical aspects, the rule of thumb across the lib is one HTTP request per unified call. So, at this point, there's little we can do on our side, I'd close this issue for now, what do you think?

**Comment by julesGoullee** [comment]
Yes, I agree with your point. Let's close the issue then, thx for your help @kroitor
