### ISSUE TITLE
New exchange: getbtc.org

### ISSUE THREAD

**Issue by dhmk815** [ccxt/ccxt#805]
please, add new exchange called 'getbtc.org'.
Following is api document.
https://getbtc.org/api-docs.php
Always thank you.

**Comment by kroitor** [comment]
@dhmk815 they report empty orderbooks:

- https://getbtc.org/api/order-book?currency=USD ← BTC/USD
- https://getbtc.org/api/order-book?currency=EUR ← BTC/EUR
- https://getbtc.org/api/order-book?currency=RUB ← BTC/RUB

To me it looks like there is no trade going on there. Do you really think we need it?

**Comment by kroitor** [comment]
The exchange is now closing down: https://twitter.com/ExchangeGetBTC/status/1115315738556993537 and may be reborn later. We're delisting it at this point.
