### ISSUE TITLE
Binance average price problem

### ISSUE THREAD

**Issue by e20916** [ccxt/ccxt#8054]
Hi, 
When i create order for binance futures, there is a problem with that price.  I just try for 0.001 btc. Look at the picture below, my order was given at 17004.5 but it's average 17042.32. What is the cause of it? First entity of picture is ordered manually on binance, second with code below. What is the reason for this huge difference?
![image](https://user-images.githubusercontent.com/73392790/100514624-751b4700-3187-11eb-81af-9fde9fb2c5d4.png)

- OS: Windows 10
- Programming Language version: python 3.7.6
- CCXT version: 1.38.26

```
order_type = 'limit' 
symbol = 'BTC/USDT'
side = 'sell'
amount = 0.001
price = 17004.5
order = exchange.create_order(symbol, order_type, side, amount, price)

**Comment by kroitor** [comment]
Hi! If your selling price `17004.5` is lower than the current buying market price on the orderbook, the exchange will fulfill your order for the best available price, which will be better than the price you've ordered. You've ordered 17004.5, and the exchange gave you 17042.32 which is better than you've asked.

This is how order matching works in general across all exchanges and it is documented in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#how-orders-and-trades-are-related

I would highly recommend to read the entire Manual from top to bottom, it will save your time.
Let us know if the above does not answer your question. Feel free to reopen it or just ask further questions if any.

**Comment by e20916** [comment]
thanks kroitor i got it
