### ISSUE TITLE
Functionality support for crypto swap

### ISSUE THREAD

**Issue by kofi-boateng** [ccxt/ccxt#8056]
Hi,

I am researching into creating a swap app like simpleswap.io but it is taking me too long to pin point on which api to use. I have reviewed binance-chain atomic-swap and ccxt and this is putting me in circles. If anyone on here can tell me if ccxt can be used to handle crypto swap. I prefer Python language so is there any python resource out there that could help me implement my swap app?

**Comment by ttodua** [comment]
That is not correct understanding about CCXT. If anyone is about building an exchange/swap, then the engine has to be searched in other directions, and CCXT is not an exchange/swap engine. I advise to look through the readme of CCXT to understand what it does. It can swap (trade) crypto through other exchanges/dex's, but itself it's not backend engine for swap app.
Feel free to open the issue if you have any problems/questions related directly to CCXT.
