### ISSUE TITLE
Binance Trailing stop-order

### ISSUE THREAD

**Issue by e20916** [ccxt/ccxt#8057]
Hi, i want to create trailing stop order on binance but i got error:
BadRequest: binance {"code":-1102,"msg":"A mandatory parameter was not sent, was empty/null, or malformed."}

I investigate all the manual, and faq but i don't find anything for trailing stop order.
OS: Windows 10
Programming Language version: python 3.7.6
CCXT version: 1.38.26

My code is:
  
    symbol = 'BTC/USDT'
    side = 'sell'
    amount = 0.001
    order_type = 'TRAILING_STOP_MARKET'  
    activation_price = 17200
    rate = 0.2

    params = { 'callbackRate': rate}

    order = exchange.create_order(symbol, order_type, side,amount,activation_price, params)

**Comment by kroitor** [comment]
1. update to CCXT 1.38.49+
2. use this code:

```Python
import ccxt

print('CCXT version:', ccxt.__version__)

exchange = ccxt.binance({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'options': {
        'defaultType': 'future',
    },
})

markets = exchange.load_markets()
# exchange.verbose = True  # uncomment for debugging

symbol = 'BTC/USDT'
side = 'sell'
amount = 0.001
order_type = 'TRAILING_STOP_MARKET'
rate = '0.2'
price = None
params = {
    'stopPrice': 17200,
    'callbackRate': rate
}

order = exchange.create_order(symbol, order_type, side, amount, price, params)
```

Let us know if that does not help. Feel free to reopen this issue or just ask further questions if any. If it doesn't work, please uncomment the verbose mode switch in the code above and paste your verbose output here.

**Comment by Maarten0578** [comment]
Hey kroiter,
i am able to place a order with this code but the act. price doesn't want to set, can you give a hint :).

symbol = 'ALPHA/USDT'
side = 'buy'
amount = 10
order_type = 'TRAILING_STOP_MARKET'
rate = '0.2'
price  = 0.9
params = {
    'stopPrice': 0.9,
    'callbackRate': rate

so what i want is a activation price of 0.9 usdt

**Comment by evanherve** [comment]
Hi,

According to this :
[https://binance-docs.github.io/apidocs/futures/en/#new-order-trade](url)

I tried to set the activation price with 'activationPrice' instead of 'stopPrice' and it seems to be working

**Comment by kroitor** [comment]
@evanherve thx for your feedback!

**Comment by Maarten0578** [comment]
hi 
thanks it works now, i didn't adjust that parameter properly last time i guess.

thanks

**Comment by Eliasjamal** [comment]
> hi
> thanks it works now, i didn't adjust that parameter properly last time i guess.
> 
> thanks

What did you do? Do you have an example?
