### ISSUE TITLE
How to configure VPN?

### ISSUE THREAD

**Issue by mick-liu** [ccxt/ccxt#8061]
Hello,

Before I introduce my problem, I would like to make a short preview about how the problem happened. Recently I have come to China. I know there is a firewall in this country, so I bought a VPN to help me deal with the banning problem. After I applied the method of using proxy IP, it raised the error as below. I have checked out the #2522 and #4540, but I found the error responses are different. And I cannot solve the problem. Please lead me to solve the problem. Thanks~

- OS: windows 10
- Programming Language version: python 3.7
- CCXT version: 1.28.85
- VPN: Express

```
exchange = ccxt.binance({
    'proxies': {
        'http': 'http://45.135.186.113:49665',
        'https': 'https://45.135.186.113:49665',
    },
})
markets = exchange.load_markets()
print(markets)
```

```
Traceback (most recent call last):
  File "C:\Users\subao\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Users\subao\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\connection.py", line 79, in create_connection
    raise err
  File "C:\Users\subao\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\connection.py", line 69, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\Python37\lib\site-packages\urllib3\connectionpool.py", line 594, in urlopen
    self._prepare_proxy(conn)
  File ".\Python37\lib\site-packages\urllib3\connectionpool.py", line 815, in _prepare_proxy
    conn.connect()
  File ".\Python37\lib\site-packages\urllib3\connection.py", line 314, in connect
    conn = self._new_conn()
  File ".\Python37\lib\site-packages\urllib3\connection.py", line 176, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x000001FFEE28F240>, 'Connection to 45.135.186.113 timed out. (connect timeout=10)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File ".\Python37\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File ".\Python37\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001FFEE28F240>, 'Connection to 45.135.186.113 timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\Python37\lib\site-packages\ccxt\base\exchange.py", line 548, in fetch
    verify=self.verify
  File ".\Python37\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File ".\Python37\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File ".\Python37\lib\site-packages\requests\adapters.py", line 504, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/exchangeInfo (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001FFEE28F240>, 'Connection to 45.135.186.113 timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./timezone_adj.py", line 15, in <module>
    markets = exchange.load_markets()
  File ".\Python37\lib\site-packages\ccxt\base\exchange.py", line 1298, in load_markets
    markets = self.fetch_markets(params)
  File ".\Python37\lib\site-packages\ccxt\binance.py", line 386, in fetch_markets
    response = getattr(self, method)(query)
  File ".\Python37\lib\site-packages\ccxt\base\exchange.py", line 449, in inner
    return entry(_self, **inner_kwargs)
  File ".\Python37\lib\site-packages\ccxt\binance.py", line 1928, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File ".\site-packages\ccxt\base\exchange.py", line 468, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File ".\site-packages\ccxt\base\exchange.py", line 568, in fetch
    raise RequestTimeout(method + ' ' + url)
ccxt.base.errors.RequestTimeout: GET https://api.binance.com/api/v3/exchangeInfo
```

**Comment by mick-liu** [comment]
Because I am not equipped too much knowledge about proxy IP or something about that. I assumed the reasons about the problems are the way I found out my Proxy IP and port, but I am not sure. Here is my way.

1. Enter this page: https://www.expressvpn.com/what-is-my-ip to see my IP.
2. Use my commend prompt to execute the following two line of codes.
```
>>> ipconfig
>>> netstat -a
```
![image](https://user-images.githubusercontent.com/31812232/100544377-33c28e80-3290-11eb-91fc-c0f894285063.png)
3. Randomly select the number after column such as 51203 to be my port.

That is all I have done.

**Comment by kroitor** [comment]
Hi! 

First of all, there's a distinction between a VPN connection and a proxy connection. 

If you have obtained VPN, you can configure it on your system and connect to your VPN as documented by the provider of your VPN. Once you've configured and connected to your VPN in your OS settings, from there connecting to Binance with CCXT does not require any proxies whatsoever. So, if you have configured your VPN in your OS, this should work

```Python
import ccxt
exchange = ccxt.binance({
    'enableRateLimit': True,  # https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
})
markets = exchange.load_markets()
print(markets)
```

If, on the other hand, you have obtained a proxy, you should set up the proxies, depending on the type of your proxy and the authentication used, as documented by the provider of your proxy. I think, you don't have to specify a proxy in your case.

Do you have the VPN properly configured and connected in your OS?

**Comment by mick-liu** [comment]
> Do you have the VPN properly configured and connected in your OS? The provider of the VPN usually provides the instructions on how to configure the VPN and how to connect to it with popular operating systems, including Windows 10.

Got it, this might be the reason why I got this error. I did not manually configure the VPN before. I am asking the provider of the VPN now, and I will configure the VPN and give you the feedback as soon as possible.

**Comment by kroitor** [comment]
@mick-liu if you're using ExpressVPN, this might help: https://www.google.com/search?q=how+to+configure+expressvpn+windows+10, usually you get the instructions upon signing up with the VPN provider. I'd close this issue for now since it's not really an issue with CCXT. It's more about the VPN configuration that depends on your OS and on your VPN provider. Feel free to reopen it if needed or just ask further questions if any. We will be thankful for your feedback, let us know if you have a followup on this.

**Comment by mick-liu** [comment]
> 
> 
> @mick-liu if you're using ExpressVPN, this might help: https://www.google.com/search?q=how+to+configure+expressvpn+windows+10, usually you get the instructions upon signing up with the VPN provider. I'd close this issue for now since it's not really an issue with CCXT. It's more about the VPN configuration that depends on your OS and on your VPN provider. Feel free to reopen it if needed or just ask further questions if any. We will be thankful for your feedback, let us know if you have a followup on this.

I solved the problem by applying the method that you mentioned. Thank you so much! @kroitor 👍

**Comment by kroitor** [comment]
@mick-liu awesome, thx for reporting back!
