### ISSUE TITLE
bittrex IOC problem

### ISSUE THREAD

**Issue by Showgofar** [ccxt/ccxt#8062]
- OS: debian
- Programming Language version: PHP
- CCXT version: latest

Hello I had updated CCXT to the latest version and noticed that i have problem with placing IOC orders at Bittrex (all other exchanges works fine like it was)
Im getting the following error 

[Mon, 30 Nov 2020 06:19:55.3224] [pid=46249, track=36] Cannot create order: bittrex {"code":"BAD_REQUEST","detail":"Refer to the data field for specific field validation failures or extra fields in the body that were rejected.","data":{"newOrder.TimeInForce":["Error converting value \"IOC\" to type 'System.Nullable`1[Bittrex.Platform.Models.TimeInForce]'. Path 'TimeInForce', line 1, position 157."]}}, 1 attempts
REQUEST: ["first_exchange","limit","sell",38.886687,"0.000021",{"timeInForce":"IOC"},"errors"]

**Comment by kroitor** [comment]
Hi! 

It has to be `{'timeInForce':'IMMEDIATE_OR_CANCEL'}` for Bittrex: https://bittrex.github.io/api/v3#/definitions/NewOrder. This is still subject to unification.

Let us know if that does not answer your question.
