### ISSUE TITLE
New Exchange: Birake/Bitdorado

### ISSUE THREAD

**Issue by meligo** [ccxt/ccxt#8063]
hey 

Would it be possible to implement the code for Birake Exchange? if you can point me to how to do it myself (am a developer) then I can make it as a contribution to this repo. 

thanks & kind regards

**Comment by kroitor** [comment]
@meligo hi! You are welcome to submit a PR, however, it has to strictly follow all CONTRIBUTING guidelines to a word: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md. We will get to it as soon as possible. Unfortunately, we can't give guarantees on the free work for reasons explained in our FAQ: https://github.com/ccxt/ccxt/wiki/FAQ, we have a backlog of 80+ new integrations for reviewing and merging, hope for your understanding. If you want to prioritize it, please, reach out to info@ccxt.trade. Let us know if that does not answer your question.

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/5819
