### ISSUE TITLE
Code that previously worked with Binance API is no longer working ( ccxt.base.errors.NotSupported: binance does not have a testnet/sandbox URL for sapi endpoints)

### ISSUE THREAD

**Issue by cadmufasa** [ccxt/ccxt#8064]
- OS : Ubuntu 19.10 (Linux)
- Programming Language version: Python 3.7
- CCXT version:  1.34.38

Hi, 

I had some code that was working before but is no longer working now.

The problem seems to be with:
**exchange.sapi_post_futures_transfer**

Before, for me, it worked on both TEST and PROD servers. But now, when running it on TEST, I get the following error:
**ccxt.base.errors.NotSupported: binance does not have a testnet/sandbox URL for sapi endpoints**

**Question:** Has something changed? If so, what can one do to fix the problem?

TIA

**This is how I am connecting to the server:**
```
    def __init__( self, client_id : int = 0, exchange_type : str =  t_bin_param.BIN_TRADE_SPOT, \
                    binance_server_mode : str = 'TEST' ):

        if not ( client_id > 0 and binance_server_mode == 'TEST' or binance_server_mode == 'PROD'):
            raise ValueError ( '-29553', ' data passed in not valid ' + str ( self.binance_server_mode ))

        if not ( exchange_type == t_bin_param.BIN_TRADE_SPOT  or exchange_type == t_bin_param.BIN_TRADE_MARGIN or \
                exchange_type == t_bin_param.BIN_TRADE_FUTURES ):
            raise ValueError ( '-48593', ' data passed in not valid ' + str ( self.binance_server_mode ))

        self.client_id                = client_id
        self.exchange_type     = exchange_type
        self.server_mode        = binance_server_mode

        # get the logoin paramters
        self.__exchange_server_login( )
        return
```

    def __exchange_server_login( self ):

      [... snip ...[
       elif ( self.exchange_type == t_bin_param.BIN_TRADE_FUTURES ):
            self.exchange = ccxt.binance({
                'apiKey': FUTURES_LD_API_KEY, 'secret': FUTURES_LD_API_SECRET, 'timeout': 30000, 'enableRateLimit': True,
                'rateLimit': 250, 'options': { 'defaultType': 'future', 'adjustForTimeDifference': True,},
            })
            logging.info("\t->TRADE ACCOUNT: FUTURES")

        if ( self.server_mode == 'TEST' ):
            self.exchange.set_sandbox_mode(True) # TESTING SANDBOX

        #self.exchange.verbose = True  # UNCOMMENT THIS AFTER LOADING THE MARKETS FOR DEBUGGING
        self.exchange.load_markets()
     [... snitp ...]

**Below is the code that is actually running:**

```
            in_symbol          = in_symbol.upper()
            base_currency      = in_symbol.split('/')[0] # like BTC
            quote_currency     = in_symbol.split('/')[1] # like USDT

            code        = quote_currency
            amount      = float( in_amount  )
            currency    = self.exchange.currency(code)

            transfer_value = 3          # assume it is going FROM: SPOT TO: a COIN- futures account
            if ( code == 'USDT' ):
                transfer_value = 1      # assume it is going FROM: SPOT TO: a USDT futures account

            in_symbol = in_symbol.replace("/", "")
            response = self.exchange.sapi_post_futures_transfer({
                'asset' : currency['id'],
                'amount': self.exchange.amount_to_precision( in_symbol,  abs( float( amount)) ),
                'type'  : transfer_value })

            print('Moving', code, 'funds from your spot account to your futures account')
```

**But am receiving the following error BUT it used to work: **

**ERROR: ccxt.base.errors.NotSupported: binance does not have a testnet/sandbox URL for sapi endpoints**
```
ERR-FEC3A96B8   Traceback (most recent call last):
  File "/root/trade_exchange/api_work/trade_binance/bin_kroitor.py", line 306, in money_move_from_futures_to_spot
    'type'  : transfer_value })
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 465, in inner
    return entry(_self, **inner_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/binance.py", line 2363, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/base/exchange.py", line 485, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.7/dist-packages/ccxt/binance.py", line 2252, in sign
    raise NotSupported(self.id + ' does not have a testnet/sandbox URL for ' + api + ' endpoints')
ccxt.base.errors.NotSupported: binance does not have a testnet/sandbox URL for sapi endpoints
```

**Comment by kroitor** [comment]
Binance never had a testnet for margin trading (`sapi` endpoints).
It will work on production though.

<img width="462" alt="Screen Shot 2020-11-30 at 16 40 44" src="https://user-images.githubusercontent.com/1294454/100616901-d0d20580-332a-11eb-973f-4d7187dc7e95.png">

```
Igor Kroitor, [30.11.20 16:39]
Hi everyone! A quick question: can we use /sapi/ endpoints with Binance testnet?
This endpoint says 404: https://testnet.binance.vision/sapi/v1/margin/allPairs

Paul, [30.11.20 16:39]
no

Igor Kroitor, [30.11.20 16:40]
So, no way to test margin trading right now, correct?

Paul, [30.11.20 16:40]
correct

Igor Kroitor, [30.11.20 16:40]
Thank you!
```

Let us know if that does not answer your question.

**Comment by dpalmeira** [comment]
Hi @kroitor, I have a quick question.
Why if I use the CCXT v 1.41.71 it works against https://testnet.binancefuture.com for futures: Open Trades, Adjust SL and TP, Close Positions, etc. it seems to works fine, and I can see the operations in the Web UI just fine (Tested today 20-Feb-2021), but if I put the same Python code with CCXT v 1.42.8 (latest tag) it does not work raising the same error: **_"binance does not have a testnet/sandbox URL for sapi endpoints"_** ?

BTW I'm using futures with:
` 
'options': {
       'defaultType': 'future'  # ['spot', 'margin', or 'future']
}
`
I don't understand... is it maybe caused because Binance have the testnet for futures, and you post your conclusion some months ago?

Thank you for your time.
Diego

**Comment by kroitor** [comment]
@dpalmeira please, help us help you – always paste your code and verbose output: 

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.binance({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'options': { 'defaultType': 'future' },
})

exchange.set_sandbox_mode(True)

markets = exchange.load_markets()

exchange.verbose = True

balance = exchange.fetch_balance()
```

**Comment by dpalmeira** [comment]
Sorry,
Here is the same result just testing your code:
after execute your example I got:

`
CCXT Version: 1.42.8
[20-02-21 18:54] brokers     : ERROR    Error: Connection with the Broker cannot be establish: binance does not have a testnet/sandbox URL for sapi endpoints
`

Error occurs at:
`
import ccxt
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.binance({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'options': { 'defaultType': 'future' },
})

exchange.set_sandbox_mode(True)

markets = exchange.load_markets() **<-- HERE !**

exchange.verbose = True

balance = exchange.fetch_balance()
`

**Comment by kroitor** [comment]
@dpalmeira that snippet should've printed a lot more output, is that all you see?

**Comment by kroitor** [comment]
@dpalmeira nevermind, reproduced the bug, will fix shortly, thanks for reporting!

**Comment by dpalmeira** [comment]
Sorry, I got more info:

`
  File "/Users/user/projects/trading/VT/venv/lib/python3.7/site-packages/ccxt/base/exchange.py", line 1357, in load_markets
    currencies = self.fetch_currencies()
  File "/Users/user/projects/trading/VT/venv/lib/python3.7/site-packages/ccxt/binance.py", line 617, in fetch_currencies
    response = self.sapiGetCapitalConfigGetall(params)
  File "/Users/user/projects/trading/VT/venv/lib/python3.7/site-packages/ccxt/base/exchange.py", line 466, in inner
    return entry(_self, **inner_kwargs)
  File "/Users/user/projects/trading/VT/venv/lib/python3.7/site-packages/ccxt/binance.py", line 2694, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/Users/user/projects/trading/VT/venv/lib/python3.7/site-packages/ccxt/base/exchange.py", line 486, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "/Users/user/projects/trading/VT/venv/lib/python3.7/site-packages/ccxt/binance.py", line 2582, in sign
    raise NotSupported(self.id + ' does not have a testnet/sandbox URL for ' + api + ' endpoints')
ccxt.base.errors.NotSupported: binance does not have a testnet/sandbox URL for sapi endpoints
`

**Comment by kroitor** [comment]
@dpalmeira please, upgrade to 1.42.10 in ~20 minutes and let us know if the issue is resolved for you.

**Comment by dpalmeira** [comment]
Yeahh!! It works well again with the v 1.42.10 (I tested your example, plus my original code)

Thank you so much for your help @kroitor it was really a fast fix!

**Comment by kroitor** [comment]
@dpalmeira thanks for your feedback, appreciate it!
