### ISSUE TITLE
Binance Future Websocket (CCXT PRO)

### ISSUE THREAD

**Issue by safwen1** [ccxt/ccxt#8067]
- OS: Ubuntu
- Programming Language version: Python
- CCXT version: 1.38.26
- CCXT PRO version: 0.4.55

Using CCXT Pro, we are able to watch the orders websocket stream in Binance exchange (Spot mode):

```
order_updates = await exchange.watch_orders()
```

This code detects order updates and works well for **SPOT** mode. However it is not working for **Future** ( No order update events received).

Is Future mode websocket not supported yet or is there something wrong with our code ?

**Comment by frosty00** [comment]
@safwen1 we currently don't have support for future order book updates but we are trying to add it ASAP

**Comment by kroitor** [comment]
@safwen1 yes, the support for Binance's WS+futures is in the works right now, we will let you know when it arrives.

**Comment by molarro** [comment]
I am very sorry, after what time can I expect WS+futures feature introduction?

**Comment by safwen1** [comment]
Same request here @kroitor it would be great to know when this will be available

**Comment by kroitor** [comment]
@safwen1 @molarro we are working on it, and it will arrive shortly, we're aware of the demand and we're doing our best to make it available as soon as possible.

**Comment by wunderb1t358** [comment]
I am very apologize, is there any update?

**Comment by kroitor** [comment]
@wunderb1t358 we have already pushed some of the updates, and we are going to fully support public and private WS APIs for Binance futures and derivatives before the end of the week. I'll post here immediately.

**Comment by safwen1** [comment]
@kroitor Thanks for the update. While testing the new feature we discovered that the Binance Spot watcher is not working anymore. 

Concerned File : /python/ccxtpro/binance.py

`message = self.safe_value(message, 'o', message)`

The 'o' key of the object message contains the infos of a Futures websocket message, however for the spot it will only contain the order type (MARKET/LIMIT)

Would you like me to open up another issue for this ?

**Comment by kroitor** [comment]
@safwen1 thank you for reporting it, that's definitely a newly introduced bug. No need for a new issue, the fix will arrive in 0.5.52 in ~20 minutes. It would be awesome if you report back here if the issue is resolved for you after upgrading. Thanks again!

**Comment by safwen1** [comment]
@kroitor Issue resolved. Thanks again.

**Comment by safwen1** [comment]
@kroitor 
Using CCXT Pro we can now watch the websocket stream for any new order updates on the Binance Future exchange. However after a while it stops working until the watch is restarted, and without any visible error. I suspect this is related to this part of the binance [documentation](https://binance-docs.github.io/apidocs/futures/en/#user-data-streams). 

_A User Data Stream listenKey is valid for 60 minutes after creation._

Should the listenKey be updated every hour?

**Comment by kroitor** [comment]
@safwen1 i will debug it to figure a fix and will get back to you here immediately.

**Comment by wunderb1t** [comment]
We just tested the case on limit order, there was no any interruption after one hour. 
Tested on CCXT 0.5.61 for JS.

**Comment by safwen1** [comment]
@wunderb1t I have tested your version ( 0.5.61 ) and the problem is still there in Python.

**Comment by kroitor** [comment]
@safwen1 make sure your version of CCXT is up to date aswell.

**Comment by safwen1** [comment]
@kroitor I have wrapped the watch line in a try-catch block and I get 2 types of errors after some time:
- Connection closed by remote server, closing code 1000
- 1006

**Comment by kroitor** [comment]
@safwen1 

> and I get 2 types of errors after some time

Those are normal, you just ignore them and your next call to the watch-method on a consecutive iteration of the loop will restore the connection automatically as documented in the Manual: https://github.com/ccxt/ccxt/wiki/ccxt.pro.manual#streaming-specifics

If you have issues with that using a specific exchange, please open a new issue and paste this info: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by Sewake** [comment]
@kroitor I also have an issue with Binance Future Websocket with ccxtpro.

OS: Ubuntu
Programming Language version: Python
CCXT version: 1.45.66 and also tried to bump to 1.48.25
CCXT PRO version: 0.6.31

I don't have any event when listening to future orderbooks:

```
import asyncio
import ccxtpro


async def loop_orderbook(exchange, symbol, params):
    while True:
        book = await exchange.watch_order_book(symbol, limit=5, params=params)
        print(book)


async def main(asyncio_loop):
    exchange = ccxtpro.binance({
        'enableRateLimit': True,
        'asyncio_loop': asyncio_loop,
    })
    symbols = ['BTC/USDT', 'ETH/USDT']
    params = {'type': 'future'}

    loops = [loop_orderbook(exchange, symbol, params) for symbol in symbols]
    await asyncio.gather(*loops)
    await exchange.close()

if __name__ == '__main__':
    asyncio_loop = asyncio.get_event_loop()
    asyncio_loop.run_until_complete(main(asyncio_loop))

```

The same code return events with SPOT when I remove the `{'type': 'future'}` params. Am I doing something wrong or Binance future orderbook websocket doesn't work atm ?
