### ISSUE TITLE
Missing candles for "binance.fetch_ohlcv"

### ISSUE THREAD

**Issue by mklosi** [ccxt/ccxt#8068]
There are missing 1m candles for a whole hour on "2020-11-30T06:00:00.000Z"
All symbols seem to be affected. 

tested with ccxt 1.38.65, 1.38.9

The code: 
```
import ccxt
import pandas as pd

client = ccxt.binance()
candles = client.fetch_ohlcv(
    "ETH/BTC",
    timeframe="1m",
    params={
        "limit": 6,
        "startTime": 1606715820000,  # GMT: Monday, November 30, 2020 5:57:00 AM
    }
)
df = pd.DataFrame(
    candles,
    columns=["ts", "open", "high", "low", "close", "volume"]
)
df.insert(0, "dt", pd.DataFrame(df["ts"].apply(client.iso8601)))
print(df)
```

Produces output: 
```
                         dt             ts  ...     close   volume
0  2020-11-30T05:57:00.000Z  1606715820000  ...  0.031469   19.556
1  2020-11-30T05:58:00.000Z  1606715880000  ...  0.031472   14.468
2  2020-11-30T05:59:00.000Z  1606715940000  ...  0.031453   10.106
3  2020-11-30T07:00:00.000Z  1606719600000  ...  0.031469   60.115
4  2020-11-30T07:01:00.000Z  1606719660000  ...  0.031465   73.479
5  2020-11-30T07:02:00.000Z  1606719720000  ...  0.031462  119.429

[6 rows x 7 columns]
```

**Comment by kroitor** [comment]
This is not an issue, it is documented in the Manual: 

- https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-candlestick-charts

> The returned list of candles may have one or more missing periods, if the exchange did not have any trades for the specified timerange and symbol. To a user that would appear as gaps in a continuous list of candles. That is considered normal. If the exchange did not have any candles at that time, the CCXT library will show the results as returned from the exchange itself.

Let us know if that does not answer your question.
