### ISSUE TITLE
Bitmex Request Expired

### ISSUE THREAD

**Issue by bigcountry-scav** [ccxt/ccxt#8069]
- OS: Win 10
- Programming Language version: 1.38.65
- CCXT version: 1.38.65

I have tried numerous things but under windows I fail to read https://testnet.bitmex.com/api/v1/instrument/activeAndIndices with the below error which would make me think that I have a clock sync issue even though my time drift is 4ms from NTP. This works fine under WSL just not in Windows. Just seeing if you got any other ideas to try?

Thanks

```
{"message":"bitmex {\"error\":{\"message\":\"This request has expired - `expires` is in the past. Current time: 1606861816\",\"name\":\"HTTPError\"}}
```

**Comment by bigcountry-scav** [comment]
It appears to work in Firefox but not chrome or ide where I am trying to use ccxt.

**Comment by kroitor** [comment]
@bigcountry-scav how do you sync your clock on the windows machine?

**Comment by bigcountry-scav** [comment]
I have overwritten my ntp server forced w32time sync also have tried tools like network time.

**Comment by kroitor** [comment]
@bigcountry-scav you have to make sure that it is in sync with UTC:

> I have overwritten my ntp server forced w32time sync also have tried tools like network time.

Just enabling the time sync in windows settings is not enough, check this issue: https://github.com/ccxt/ccxt/issues/936#issuecomment-353774479

Let us know if that does not help.

**Comment by bigcountry-scav** [comment]
Yeah I have it already set to sync every 15 minutes I found an issue in code though so this is resolved now thanks.
