### ISSUE TITLE
Digifinex Withdraw Function Missing

### ISSUE THREAD

**Issue by drsavant-pub** [ccxt/ccxt#8070]
Digifinex is missing the withdraw function.

I found the API Doc: Request withdrawal
https://docs.digifinex.vip/en-ww/v3/#request-withdrawal

Please advise.

OS: win 8.1
Programming Language version: nodejs v12.16.1
CCXT version: 1.38.66

```
let ccxt = require('ccxt')
let exchange = new ccxt.digifinex
exchange.verbose
let type = 'withdraw'

    if (exchange.has[type]){
        console.log  ('Yes! ' + exchange.name + ' has a ' + type + ' function.')
    } else {
        console.log  ('No! ' + exchange.name + ' has NO ' + type + ' function.')
    }
```

```
No! DigiFinex has NO withdraw function.
```

**Comment by kroitor** [comment]
<img width="2766" alt="Screen Shot 2020-12-02 at 17 28 24" src="https://user-images.githubusercontent.com/1294454/100885536-d020a700-34c3-11eb-9e3e-d9fb50cf0018.png">
