### ISSUE TITLE
Luno market tickers from publicGetTickers are undefined

### ISSUE THREAD

**Issue by bgins** [ccxt/ccxt#8073]
When calling `fetchMarkets` on Luno, the `markets` returned by `publicGetTickers` are missing `tickers` (or possibly `markets` are undefined).

- OS: RunKit
- Programming Language version: node 15.3.0
- CCXT version: 1.18.591

Code to reproduce:
```
var ccxt = require("ccxt")

const exchangeClient = new ccxt['luno']();
const markets = await exchangeClient.fetchMarkets();
console.log(JSON.stringify(markets));
```

Exception:
```
TypeError: Cannot read property 'length' of undefined
```

Exception thrown here:
https://github.com/ccxt/ccxt/blob/aa962ac5096c8ba236285c21afc20c5e6c64c367/js/luno.js#L102

RunKit with this example: https://runkit.com/embed/1om1fusajqls

Luno appears to be returning markets from their APi with

```
curl https://api.luno.com/api/exchange/1/markets
```

though perhaps this is not the underlying call.

**Comment by kroitor** [comment]
@bgins version 1.18.591 is not supported anymore.

1. Update your version of CCXT to the most recent 1.38.75+: https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
2. Follow the Manual precisely: 
    - https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
    - https://github.com/ccxt/ccxt/wiki/Manual#error-handling
3. If the above does not help, paste your request+response in verbose mode:
    - https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```JavaScript
const ccxt = require ('ccxt')

console.log ('CCXT Version:', ccxt.version)

const exchange = new ccxt.luno ({
    enableRateLimit: true,
    verbose: true,
})

;(async () => {

    await exchange.loadMarkets ();
    console.log (exchange.symbols)

}) ()
```

**Comment by kroitor** [comment]
P.S. We will add the `markets` endpoint asap.

**Comment by bgins** [comment]
Apologies, I did not notice that RunKit had an older version of CCXT.

The `fetchMarkets` call works now. Perhaps the fault was due to an outage on Luno's end.
