### ISSUE TITLE
[wavesexchange.py] - 'timeInForce' Questions

### ISSUE THREAD

**Issue by Maxximiliann** [ccxt/ccxt#8077]
What is the proper way to set a two hour expiration on buy/sell orders for the WAVES Exchange?

**Comment by ttodua** [comment]
whoever wants, `defaultExpiry` should be passed (milliseconds value). e.g. for 2 hours:
```
ex.create_order (symbol, type, side, amount, price, { 'defaultExpiry' : 2 * 60 * 60 * 1000 })
```
