### ISSUE TITLE
liquid precision format not consistent

### ISSUE THREAD

**Issue by blaaaaaaa** [ccxt/ccxt#8080]
ccxt-1.38.84 win10

On liquid exchange the precision is in the format of decimals: 
liq.load_markets()["BTC/USD"]["precision"]
{'amount': 1e-08, 'price': 0.01}
It gives the tick size, so it is a different format to the other exchanges. Could be dangerous.

**Comment by kroitor** [comment]
Plz read the Manual and let us know if that does not answer your question: https://github.com/ccxt/ccxt/wiki/Manual#methods-for-formatting-decimals
