### ISSUE TITLE
Mercado exchange is not showing the candle

### ISSUE THREAD

**Issue by ramondepieri** [ccxt/ccxt#8082]
When call the fetch_ohlcv to the mercado exchange nothing is happening. I tried with differents params but I was not able to do it work.
I tried to do some debug, bug without success. When I look to the fetch_ohlcv I figured out that the self.v4PublicGetCoinCandle is return 'None' on 'candel' key

Test code:
```
if mercado.has['fetchOHLCV']:
    for symbol in m.ex.markets:
        time.sleep(mercado.rateLimit / 1000) # time.sleep wants seconds
        print(symbol, mercado.fetch_ohlcv(symbol, '1h', limit=60)) # one day
```

![image](https://user-images.githubusercontent.com/6942734/101247977-815d5200-36fb-11eb-83af-3afb25d8b0db.png)

**Comment by ttodua** [comment]
this issue had been resolved in the past, closed.
