### ISSUE TITLE
OCO functionality and Confirmation of order execution

### ISSUE THREAD

**Issue by cadmufasa** [ccxt/ccxt#8088]
OS : Ubuntu 19.10 (Linux)
Programming Language version: Python 3.7
CCXT version: 1.34.38

Hi there,

I have been following these links to gather information on the use of OCO:

https://academy.binance.com/en/articles/what-is-an-oco-order
https://github.com/ccxt/ccxt/issues/5966
https://github.com/ccxt/ccxt/issues/6192
https://binance-docs.github.io/apidocs/spot/en/#new-oco-trade
https://www.binance.com/au/support/faq/360032605831-How-to-Use-OCO-One-Cancels-the-Other-Order-Type

On this particular link:
https://www.binance.com/au/support/faq/360032605831-How-to-Use-OCO-One-Cancels-the-Other-Order-Type

**For example:**
`You have 300 USDT in your account, and you think the overall trend of the BNB/USDT market is going up. You want to enter the market at a reasonable price. The last traded price of BNB is 28.05 USDT, and the resistance is around 29.50 USDT. You want to buy BNB when it hits 27.00 USDT, but you also don’t want to miss out on the opportunity when the price breaks the resistance price.`

**For the part of** 
`when it hits 27.00 USDT, but you also don’t want to miss out on the opportunity `

**Can you clarify: Does this mean that the OCO is for a "I want to buy it at a cheaper price - but - if I can't I will get some at ANY price**" 

**Also**

**Can you confirm:** this functionality appears to create an order only (it is just you would get it at a cheap price or an expensive price). **So, one would have to create a STOP LOSS order -** *after* **the BUY order goes through**

**Question: is there a way to get an alert once the order has been filled?** Or - does one have to constantly poll the Order number to see if the **status** has changed from **NEW** to **FILLED**  (this would be fine for **MARKET** orders as they fill pretty fast - one can poll the results every 5 seconds - **BUT - for LIMIT orders**, these could take days to fill and it would seem that polling every 5 seconds to check if the status has changed from NEW to FILLED could get one's account banned.

Is there some way to come about this?

**Comment by ttodua** [comment]
OCO order (as already described) means such submission of two orders, as when one of the order becomes executed, the another order is cancelled automatically by exchange engine. 

To your another question - it depends what orders you embed inside OCO. OCO doesn't mean automatically that you submit "entry" orders, as OCO orders can be both "exit" orders, or one-entry & one-exit. 

Let's say, you have a "flat position" and you want to buy some coins to sell it at higher price later to make profit. 
Then you can combine two entry orders in OCO, and when one of those two orders is executed, then thereafter (independently of already submitted OCO)  you can create new orders (be it either "take-profit" or "stop-loss" or both of them).

Lastly, get "notified" when order status changes, there are two ways:
A) Polling (as you said, and fetching order once in every 5 seconds is quite safe way and you will never get banned from binance and also neither from any other normal exchange)

or

B) using websocket connections with [ccxt-pro](https://ccxt.pro/) . The method you want will be `watchOrders`. See the example here to fully understand how it works and customize to your needs: https://github.com/ccxt/ccxt/blob/master/examples/ccxt.pro/py/binance-watch-orders-being-placed.py
