### ISSUE TITLE
fetch_ohlcv() fetches different and especially wrong dates for different exchanges

### ISSUE THREAD

**Issue by rufusroger** [ccxt/ccxt#8091]
- OS: Ubuntu 20.04
- Programming Language version: Python 3.8.5
- CCXT version: 1.38.87

Several hours I am troubleshooting, the strange behaviour of fetch_ohlcv() and I am not able to reliably fetch the correct data for any tested exchange. I assume that the response is somewhat representing the limit of those exchanges? But even then I would expect the initial data to represent at least the candles beginning with the given date.

Any help or update would be appreciated very much.

The behaviour seems correlated with issues like [this one](https://github.com/ccxt/ccxt/issues/5695) or [this one](https://github.com/ccxt/ccxt/issues/2877).

```
from datetime import datetime
import pandas as pd
import ccxt
bitvavo = ccxt.bitvavo()
bitvavo_data = pd.DataFrame(bitvavo.fetchOHLCV(symbol='BTC/EUR', timeframe='1h', since=bitvavo.parse8601('2020-01-01T00:00:00')),
                    columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
kraken = ccxt.kraken()
kraken_data = pd.DataFrame(kraken.fetchOHLCV(symbol='BTC/EUR', timeframe='1h', since=kraken.parse8601('2020-01-01T00:00:00')),
                    columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
binance = ccxt.binance()
binance_data = pd.DataFrame(binance.fetchOHLCV(symbol='BTC/EUR', timeframe='1h', since=binance.parse8601('2020-01-01T00:00:00')),
                    columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])

print(f'BITVAVO First candle:\t{bitvavo_data["timestamp"].values[0]}\t{datetime.fromtimestamp(bitvavo_data["timestamp"].values[0]/1000)}')
print(f'KRAKEN  First candle:\t{kraken_data["timestamp"].values[0]}\t{datetime.fromtimestamp(kraken_data["timestamp"].values[0]/1000)}')
print(f'BINANCE First candle:\t{binance_data["timestamp"].values[0]}\t{datetime.fromtimestamp(binance_data["timestamp"].values[0]/1000)}')
print(f'BITVAVO Last candle:\t{bitvavo_data["timestamp"].values[-1]}\t{datetime.fromtimestamp(bitvavo_data["timestamp"].values[-1]/1000)}')
print(f'KRAKEN  Last candle:\t{kraken_data["timestamp"].values[-1]}\t{datetime.fromtimestamp(kraken_data["timestamp"].values[-1]/1000)}')
print(f'BINANCE Last candle:\t{binance_data["timestamp"].values[-1]}\t{datetime.fromtimestamp(binance_data["timestamp"].values[-1]/1000)}')
```

```
BITVAVO First candle:	1602115200000	2020-10-08 02:00:00
KRAKEN  First candle:	1604710800000	2020-11-07 02:00:00
BINANCE First candle:	1578038400000	2020-01-03 09:00:00
BITVAVO Last candle:	1607299200000	2020-12-07 01:00:00
KRAKEN  Last candle:	1607299200000	2020-12-07 01:00:00
BINANCE Last candle:	1579834800000	2020-01-24 04:00:00
```

**Comment by kroitor** [comment]
This is covered in the Manual and in a few previous issues:

- https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-candlestick-charts
- https://github.com/ccxt/ccxt/issues/215#issuecomment-372084180
- https://github.com/ccxt/ccxt/issues/4136#issuecomment-437136014

You can expect a limited number of candles into the past from some exchanges, including Kraken.
Let us know if that does not answer your question.

**Comment by rufusroger** [comment]
Oh snap, I thought to have read the manual a little more carefully..
Thank you for that quick response. And of course a overwhelming ThankYou for all the whole library - You are golden!

**Comment by RianBrug** [comment]
so, I'm working fine fetching data from Binance, but Kraken doesnt seems to work properly. 

here's the code, the config setup is for kraken, but changing 'exchange = ccxt.binance' , so do the rateLimit = 1000, works fine to Binance (printing old and older epochs using timeframe 1minute - that's my goal). 

`import os
import sys
import time

# -----------------------------------------------------------------------------

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

# -----------------------------------------------------------------------------

import ccxt  # noqa: E402

# -----------------------------------------------------------------------------
# common constants

msec = 1000
minute = 60 * msec
hold = 30

# -----------------------------------------------------------------------------

exchange = ccxt.kraken({
    'rateLimit': 3000,
    'enableRateLimit': True,
    # 'verbose': True,
})

# -----------------------------------------------------------------------------

from_datetime = '2020-01-01 00:00:00'
from_timestamp = exchange.parse8601(from_datetime)

# -----------------------------------------------------------------------------

now = exchange.milliseconds()

# -----------------------------------------------------------------------------

data = []

while from_timestamp < now:

    try:

        print(exchange.milliseconds(), 'Fetching candles starting from', exchange.iso8601(from_timestamp))
        ohlcvs = exchange.fetch_ohlcv('USDT/USD', '1m', from_timestamp)
        print(exchange.milliseconds(), 'Fetched', len(ohlcvs), 'candles')
        first = ohlcvs[0][0]
        last = ohlcvs[-1][0]
        print('First candle epoch', first, exchange.iso8601(first))
        print('Last candle epoch', last, exchange.iso8601(last))
        from_timestamp += len(ohlcvs) * minute
        data += ohlcvs

    except (ccxt.ExchangeError, ccxt.AuthenticationError, ccxt.ExchangeNotAvailable, ccxt.RequestTimeout) as error:

        print('Got an error', type(error).__name__, error.args, ', retrying in', hold, 'seconds...')
        time.sleep(hold)`

pprint of KRAKEN configs (as you can see the epochs are always the same, not pooling from older and older
`1617089605768 Fetching candles starting from 2020-01-01T00:00:00.000Z
1617089612068 Fetched 720 candles
First candle epoch 1617046440000 2021-03-29T19:34:00.000Z
Last candle epoch 1617089580000 2021-03-30T07:33:00.000Z
1617089612069 Fetching candles starting from 2020-01-01T12:00:00.000Z
1617089615066 Fetched 720 candles
First candle epoch 1617046440000 2021-03-29T19:34:00.000Z
Last candle epoch 1617089580000 2021-03-30T07:33:00.000Z
1617089615066 Fetching candles starting from 2020-01-02T00:00:00.000Z
1617089618078 Fetched 720 candles
`

pprint from BINANCE config
`1617089400186 Fetching candles starting from 2020-01-01T00:00:00.000Z
1617089401800 Fetched 500 candles
First candle epoch 1577836800000 2020-01-01T00:00:00.000Z
Last candle epoch 1577866740000 2020-01-01T08:19:00.000Z
1617089401801 Fetching candles starting from 2020-01-01T08:20:00.000Z
1617089402803 Fetched 500 candles
First candle epoch 1577866800000 2020-01-01T08:20:00.000Z
Last candle epoch 1577896740000 2020-01-01T16:39:00.000Z
1617089402803 Fetching candles starting from 2020-01-01T16:40:00.000Z
1617089403814 Fetched 500 candles
First candle epoch 1577896800000 2020-01-01T16:40:00.000Z
Last candle epoch 1577926740000 2020-01-02T00:59:00.000Z
1617089403814 Fetching candles starting from 2020-01-02T01:00:00.000Z
1617089404819 Fetched 500 candles
First candle epoch 1577926800000 2020-01-02T01:00:00.000Z
Last candle epoch 1577956740000 2020-01-02T09:19:00.000Z
1617089404819 Fetching candles starting from 2020-01-02T09:20:00.000Z
1617089406094 Fetched 500 candles
First candle epoch 1577956800000 2020-01-02T09:20:00.000Z
Last candle epoch 1577986740000 2020-01-02T17:39:00.000Z
1617089406094 Fetching candles starting from 2020-01-02T17:40:00.000Z
1617089406815 Fetched 500 candles
First candle epoch 1577986800000 2020-01-02T17:40:00.000Z
Last candle epoch 1578016740000 2020-01-03T01:59:00.000Z
1617089406815 Fetching candles starting from 2020-01-03T02:00:00.000Z
1617089407799 Fetched 500 candles
First candle epoch 1578016800000 2020-01-03T02:00:00.000Z
Last candle epoch 1578046740000 2020-01-03T10:19:00.000Z
1617089407800 Fetching candles starting from 2020-01-03T10:20:00.000Z
1617089409076 Fetched 500 candles
First candle epoch 1578046800000 2020-01-03T10:20:00.000Z
Last candle epoch 1578076740000 2020-01-03T18:39:00.000Z
1617089409076 Fetching candles starting from 2020-01-03T18:40:00.000Z
1617089410626 Fetched 500 candles
First candle epoch 1578076800000 2020-01-03T18:40:00.000Z
Last candle epoch 1578106740000 2020-01-04T02:59:00.000Z
1617089410626 Fetching candles starting from 2020-01-04T03:00:00.000Z
1617089410998 Fetched 500 candles
First candle epoch 1578106800000 2020-01-04T03:00:00.000Z
Last candle epoch 1578136740000 2020-01-04T11:19:00.000Z
1617089410998 Fetching candles starting from 2020-01-04T11:20:00.000Z
1617089411997 Fetched 500 candles
`
