### ISSUE TITLE
idex.io fetchBalance

### ISSUE THREAD

**Issue by BHruska** [ccxt/ccxt#8092]
Just tried to add basic functionality for a new exchange, idex.io, modeling it after the other six or so exchanges I've worked with.  I realize this exchange is more of a DEX, so I figured it might be different, but no luck so far. 

When trying to fetchBalance, its asking for private_key, 

ccxt.base.errors.AuthenticationError: requires `privateKey`

So thinking that was the wallet address, I added that, and it then asked for walletAddress.

So is there any example code of how to this exchange is initiated differently?

**Comment by kroitor** [comment]
Let us know if this does not answer your question:

- https://github.com/ccxt/ccxt/blob/master/python/ccxt/idex.py#L127
- https://github.com/ccxt/ccxt/wiki/Manual#credential-validation

**Comment by BHruska** [comment]
What is privateKey?  I have a walletAddress.  That makes sense to me, but what privatekey would I ever send over an API call?

**Comment by kroitor** [comment]
@BHruska the privateKey is not sent over an API call, it is used to sign some of the requests.

**Comment by BHruska** [comment]
Got it working.  Thanks for your help.
