### ISSUE TITLE
How to get single update of watchOrders and watchBalance?

### ISSUE THREAD

**Issue by zsyh** [ccxt/ccxt#8093]
How to get which order is updated in watchOrders and which currency is updated in watchBalance?

I saw a line of code in binance.py that said
```orders.append(parsed)```
I just need the `parsed` single order information.

For example, this is watchOrders return (only show important fields).
```
[{"id": 1, "status": "open", "filled": 0.0, "amount": 1.0}, {"id": 2, "status": "canceled", "filled": 0.0, "amount": 1.0}]
```
at some time, order 1 is canceled, then the watchOrders returns:
```
[{"id": 1, "status": "canceled", "filled": 0.0, "amount": 1.0}, {"id": 2, "status": "canceled", "filled": 0.0, "amount": 1.0}]
```
but I need
```
{"id": 1, "status": "canceled", "filled": 0.0, "amount": 1.0}
```

The example for watchBalance return is (only show important fields):
```
{"USDT": {"total": 100}, "BTC": {"total": 0.0}, "ETH": {"total": 0.0}}
```
at some time, I bought some BTC and watchBalance returns:
```
{"USDT": {"total": 0.0}, "BTC": {"total": 0.005}, "ETH": {"total": 0.0}}
```
but I need this information (which currency's balance is updated during this websocket message)
```
{"USDT": {"total": 0.0}, "BTC": {"total": 0.005}}
```

**Comment by kroitor** [comment]
We are working on a mode to return just the updated entities, hope to get it uploaded soon.

**Comment by Matoran** [comment]
The `E` value should be used (event time which is in raw response only), but for simplicity you can probably use `lastTradeTimestamp` like that:
```python
since = None
while True:
  orders = await self.exchange.watch_orders()
  orders = self.exchange.filter_by_since_limit(orders, since=since, key='lastTradeTimestamp')
  since = str(int(orders[-1]['lastTradeTimestamp'])+1)
```
Note that `lastTradeTimestamp` is a string, you should be careful about the comparison. If you use one more digit `'100' > '20'` is `False`. But you should be safe as current timestamp `1609089523020` is today and `9609089491857` is 2 July 2274 :D. Test on your side, of course, don't trust me. You can lose money.

**Comment by ttodua** [comment]
in latest ccxt version this issue should be gone, if still an issue, let us know
