### ISSUE TITLE
Trying to: npm install ccxt

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#8094]
OS: Windows Server 2019 Datacenter
Programming Language version: Node.js
CCXT version: trying to install the latest
Exchange: All Exchanges
Node.js 15.3.0 installed
Method: npm install ccxt

Hello!

I am trying to install ccxt. I have used this in Mars 2019 and got help with installing which could be seen on this link:
https://github.com/ccxt/ccxt/issues/4650

But it seems that something gets stuck after, I write:
`npm install ccxt`

I am not sure if I do something wrong and if it looks like I have dont this correctly in the CMD image?

Thank you!

![image](https://user-images.githubusercontent.com/47510843/101395260-fbdbcc80-38c9-11eb-88b1-a6e4d83d0061.png)

**Comment by jackpotcityco** [comment]
It seems that the installation worked after 18 minutes.

However, I might wonder. It seems that the version I have when looking at the image in my first post is: 1.18.226
and that the latest version is: 1.18.242 if that is correct.

I wonder if there is any command to upgrade to the latest version?

Thank you!

**Comment by kroitor** [comment]
> and that the latest version is: 1.18.242 if that is correct.

That is not the latest version! The latest version is **1.38.89**! 

You can see it on top of our main page here: https://github.com/ccxt/ccxt/blob/master/README.md

<img width="987" alt="Screen Shot 2020-12-07 at 22 53 30" src="https://user-images.githubusercontent.com/1294454/101398396-0f456280-38df-11eb-8b10-db0d6134aee6.png">


> I wonder if there is any command to upgrade to the latest version?

I'd recommend a full uninstall and a clean reinstall: https://docs.npmjs.com/cli/v6/commands/npm-update

Let us know if that does not answer your question. Feel free to reopen it or just ask further questions if any.

**Comment by jackpotcityco** [comment]
Kroitor,

Thank you!

Yes, 1.38.89 was the latest version. I wa trying to read on the link: https://docs.npmjs.com/cli/v6/commands/npm-update

I think I got very confused of what commands to actually use there. Is there a way to show how to?:

1. Do a full uninstall
2. Do a clean reinstall of version: 1.38.89

I think it would be a great start if possible /Thank you

**Comment by kroitor** [comment]
@jackpotcityco in your project folder:

```
npm uninstall -g ccxt
npm uninstall ccxt
npm install ccxt
```

The last command should print the most recent version when it's done.

**Comment by jackpotcityco** [comment]
It looked like this when I runned the above commands. I am not sure if this looks correct?
![image](https://user-images.githubusercontent.com/47510843/101400429-34cb6f80-38d1-11eb-88e7-bb60000e8aa5.png)

**Comment by kroitor** [comment]
@jackpotcityco do this:

```
npm ls | grep ccxt
```

which version is it?

**Comment by jackpotcityco** [comment]
Yes, it seems to be correct. It shows: 1.38.89

C:\myproject>npm ls
package@1.0.0 C:\myproject
+-- ccxt@1.38.89
+-- chokidar@2.1.2
+-- iconv-lite@0.4.24
`-- ololog@1.1.117

I beleive this is correct then. 

Thank you very much for your help. Now I should have everything setup to start with the code.
