### ISSUE TITLE
BINANCE symbol error

### ISSUE THREAD

**Issue by jagdpantherjung** [ccxt/ccxt#8098]
As we found similar issue on 11-Nov (the issue fixed with hot patch), 
symbol error issue was found during using ccxt and ccxtpro again

I was using versions as below
ccxt: 1.35.34
ccxtpro:  0.3.96

ccxt returned error with following command with future symbol
but no error with delivery symbol (BTCUSD_PERP)
**exchange.fetch_order_book('BTC/USDT')
ccxt.base.errors.BadSymbol: binance does not have market symbol BTC/USDT**

**exchange.fetch_order_book('BTCUSDT')
ccxt.base.errors.BadSymbol: binance {"code":-1121,"msg":"Invalid symbol."}**

therefore I updated ccxt base and pro
and now it returns error with delivery symbol and no error with future symbol
ccxt: 1.38.94
ccxtpro:  0.4.83
**exchange.fetch_order_book('BTCUSD_PERP')
ccxt.base.errors.BadSymbol: binance does not have market symbol BTCUSD_PERP**

**Comment by kroitor** [comment]
Please, update your versions to the most recent: CCXT 1.38.94+, CCXT Pro 0.4.83+.

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

Let us know if you have the same issue after upgrading to the most recent version.
Feel free to reopen this issue or just ask further questions if any.

Code to check your version and symbols:

```Python
import ccxt

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.binance({
    'enableRateLimit': True,
    'options': { 'defaultType': 'future' },
})

exchange.load_markets()

# exchange.verbose = True  # uncomment for debugging

for symbol in exchange.symbols:
    market = exchange.market(symbol)
    print(market['id'], market['symbol'], market['type'])

orderbook = exchange.fetch_order_book('BTC/USDT')
print(orderbook)
```
