### ISSUE TITLE
Binance symbol error for delivery markets

### ISSUE THREAD

**Issue by jagdpantherjung** [ccxt/ccxt#8099]
- OS: MAC OS
- Programming Language version: python 3.8
- CCXT version: ccxt: 1.38.94 / ccxtpro: 0.4.83

after update to the latest version,
ccxt doesn't handle Binance delivery market symbol properly 
 

< code block >
exchange = ccxt.binance(
    {
        'enableRateLimit': True,
        'options': {'defaultType': 'delivery'}
    }
)
print(exchange.fetch_order_book('BTCUSD_PERP'))

< error msg>
raise BadSymbol('{} does not have market symbol {}'.format(self.id, symbol))
ccxt.base.errors.BadSymbol: binance does not have market symbol BTCUSD_PERP

**Comment by kroitor** [comment]
Please, check the list of supported symbols:

```Python
import ccxt

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.binance({
    'enableRateLimit': True,
    'options': { 'defaultType': 'future' },
})

exchange.load_markets()

for symbol in symbols:
    market = exchange.market(symbol)
    print(market['id'], market['symbol'], market['type'])
```

- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

Let us know if that does not answer your question.
