### ISSUE TITLE
error in pip install 

### ISSUE THREAD

**Issue by smehra69** [ccxt/ccxt#8102]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows 10
- Programming Language version: Python 3.9
- CCXT version:

I have installed python 3.9
When I am trying to install any package through pip install I get the following error:-

ERROR: Could not install packages due to an EnvironmentError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/beautifulsoup4/beautifulsoup4-4.9.3.tar.gz (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1105: The handshake operation timed out')))

Kindly help to resolve. This pc is behind a proxy.

**Comment by kroitor** [comment]
Looks like your proxy does not let your connection through to pypi.org. Have you tried installing other pip packages? Because this is not an issue with CCXT, this is more like a machine-specific or system-specific config issue or network connectivity issue on your side.

**Comment by kroitor** [comment]
Let us know if this does not help: https://stackoverflow.com/questions/30992717/proxy-awareness-with-pip
