### ISSUE TITLE
[cex.io] Incorrect order parsing (cost)

### ISSUE THREAD

**Issue by nudabagana** [ccxt/ccxt#8103]
- OS: Manjaro (linux)
- Programming Language version: Node v15.2.1
- CCXT version: 1.39.1

fetchOrder returns incorrect cost when you have both taker and maker trades. 

currently, ccxt parses cex orders like this:
```js
cost = this.safeFloat (order, 'ta:' + market['quote']);
if (cost === undefined) {
    cost = this.safeFloat (order, 'tta:' + market['quote']);
}
```
However, if you have both taker and maker trades, cost should be the sum of both. Something like this:
```js
cost = this.sum(this.safeFloat (order, 'ta:' + market['quote']),  cost = this.safeFloat (order, 'tta:' + market['quote']));
```

**Comment by nudabagana** [comment]
Any estimation, when this is getting fixed?

**Comment by kroitor** [comment]
@nudabagana should be ok as of CCXT 1.40.19+, it will arrive in ~20 minutes. Thanks for the feedback and pardon for the long wait. Please, don't hesitate if you find more.
