### ISSUE TITLE
[SCAM REPORT] Bibox - suspected scam

### ISSUE THREAD

**Issue by Rekamserg** [ccxt/ccxt#8107]
Good afternoon.
I use a translator from Russian.

The Bibox team deceived their users and many people suffered.

The SAFE coin team updated their coins to SAFE2, then updated SAFE2 to COVER. The Bibox exchange made an announcement and on 12/04/2020 launched the COVER coin trading and opened the coin deposit. The coin withdrawal has been closed. Many users bought the COVER coin. Then the trading was closed and the coin was removed from the exchange. The announcement to replace SAFE2 with COVER was removed.
COVER coins of users were exchanged for SAFE. This is a coin with an old contract and is worth nothing.
The Bibox exchange did not make any announcements. They deceived their users and are banned in the official Telegram group.

I made a deposit of COVER coin to Bibox exchange. I received the coins on my account. They took my Cover coins and gave me old SAFE coins with a different contract. These coins cannot be sold anywhere. They don't cost anything.

I believe that the Bibox exchange deceived its users, and also committed theft. Traded real COVER coins for old SAFE coins.

**Comment by ttodua** [comment]
bibox is no longer included in ccxt
