### ISSUE TITLE
Binance futures limit_maker order

### ISSUE THREAD

**Issue by kaiserex** [ccxt/ccxt#8110]
Hi,

I am trying to send a post_only order to Binance futures, according to one of responses found here.

CCXT version: 1.39.2
Code bellow: 

keys = {
        'options': {'defaultType': 'future'},
        'apiKey': key,
        'secret': secret,
        'enableRateLimit': True,
        'verbose': False,
        'urls': {
            'api': {
                'public': 'https://fapi.binance.com/fapi/v1',
                'private': 'https://fapi.binance.com/fapi/v1'
            }}
    }

ccxt.binance(keys).create_order(ticker, 'limit_maker', order_side, order_size, order_price)

And i am getting this error:
ccxt.base.errors.InvalidOrder: binance limit_maker is not a valid order type in future market ETH/USDT

Any suggestions how one could send a post_only order in the futures market?

**Comment by kroitor** [comment]
@kaiserex hi!

```Python
import ccxt

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.binance({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'options': {
        'defaultType': 'future',
    },
})

response = exchange.create_order('BTC/USDT', 'limit', 'sell', amount, price)
```

- https://binance-docs.github.io/apidocs/futures/en/#public-endpoints-info

<img width="1300" alt="Screen Shot 2020-12-10 at 21 30 08" src="https://user-images.githubusercontent.com/1294454/101814306-064ad000-3b2f-11eb-87fe-b5993696a94d.png">


Let us know if the above does not answer your question.

**Comment by kaiserex** [comment]
Thank you 

> @kaiserex hi!
> 
> ```python
> import ccxt
> 
> print('CCXT Version:', ccxt.__version__)
> 
> exchange = ccxt.binance({
>     'enableRateLimit': True,
>     'apiKey': 'YOUR_API_KEY',
>     'secret': 'YOUR_SECRET',
>     'options': {
>         'defaultType': 'future',
>     },
> })
> 
> response = exchange.create_order('BTC/USDT', 'limit', 'sell', amount, price)
> ```
> 
> * https://binance-docs.github.io/apidocs/futures/en/#public-endpoints-info
> 
> <img alt="Screen Shot 2020-12-10 at 21 30 08" width="1300" src="https://user-images.githubusercontent.com/1294454/101814306-064ad000-3b2f-11eb-87fe-b5993696a94d.png">
> 
> Let us know if the above does not answer your question.

Thank you for such a quick reply.
Do i understand correctly that Binance futures do not allow to send post_only orders via api at all?

In their user interface, they have a checkbox for post_only, so i figured there must be some way.
Screenshot: 
![Screenshot from 2020-12-10 20-37-30](https://user-images.githubusercontent.com/25899070/101815194-de0ba300-3b27-11eb-9da0-5b8c435654a8.png)

**Comment by kroitor** [comment]
> Do i understand correctly that Binance futures do not allow to send post_only orders via api at all?

Binance does support post-only futures-orders, but this is done using the timeInForce param override:

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-params

More details:

- https://binance-docs.github.io/apidocs/futures/en/#public-endpoints-info

<img width="1440" alt="Screen Shot 2020-12-10 at 21 41 59" src="https://user-images.githubusercontent.com/1294454/101815606-d69cc780-3b30-11eb-9b12-5d0cfdf8b4ab.png">

- https://binance-docs.github.io/apidocs/futures/en/#new-order-trade

<img width="1680" alt="Screen Shot 2020-12-10 at 21 44 24" src="https://user-images.githubusercontent.com/1294454/101815698-f9c77700-3b30-11eb-8fd4-1d190f3b5762.png">

So:

```Python
import ccxt

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.binance({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'options': {
        'defaultType': 'future',
    },
})

params = {'timeInForce': 'GTX'}  # ←------------------------------------------ ↓
response = exchange.create_order('BTC/USDT', 'limit', 'sell', amount, price, params)

**Comment by kaiserex** [comment]
Huge thanks, this is exactly what i was looking for.
