### ISSUE TITLE
TheRockTrading: update fetchOHLCV = true

### ISSUE THREAD

**Issue by RevFlux** [ccxt/ccxt#8114]
I'm starting to use ccxt with The Rock Trading and the fetchOHLCV is stated as 'emulated'.
I asked to The Rock Trading guys and they are confirming that OHLCV is available in The Rock Trading API.
Could you update 'therock' support to fetchOHLCV?

Thank you un advance!

**Comment by pcriadoperez** [comment]
Hi @RevFlux sorry for the late response and thanks for pointing this out.

We added fetchOHLCV to the rock with this PR https://github.com/ccxt/ccxt/pull/13671

**Comment by kroitor** [comment]
TheRock exchange now supports fetchOHLCV as of CCXT 1.84.18.
