### ISSUE TITLE
Do you support watch* methods for Binance and FTX in ccxt pro now? 

### ISSUE THREAD

**Issue by molarro** [ccxt/ccxt#8118]
Which watch*  methods you currently support for Binance and FTX?  
Especially interested in `watchOrders`, `watchCreateOrder` and `watchCancelOrder`.

**Comment by kroitor** [comment]
Hi!

> Which watch* methods you currently support for Binance and FTX?
> Especially interested in watchOrders, watchCreateOrder and watchCancelOrder.

We support Binance watchOrders for spot orders, the derivatives-orders are a work in progress right now.
We also support watchOrders for FTX.
We do not support watchCreateOrder / watchCancelOrder yet.

<img width="734" alt="Screen Shot 2020-12-16 at 19 33 32" src="https://user-images.githubusercontent.com/1294454/102377462-bdcf5e80-3fd5-11eb-8c56-7a640642af7c.png">


Let us know if that does not answer your question.
