### ISSUE TITLE
Consistency of trade amount across exchanges 

### ISSUE THREAD

**Issue by leoplct** [ccxt/ccxt#812]
When I place a new **Buy** order on Bitfinex the amount is in the Base currency, instead on Gdax is in the quote currency. This create a lot of confusion and messy code. Would be great to have a unified thing and have it all in quote currency.

**Comment by kroitor** [comment]
@leoplct can you post your code, please?  https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue
