### ISSUE TITLE
How to cancel_order with bithumb?

### ISSUE THREAD

**Issue by Eavan0103** [ccxt/ccxt#8120]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Win10
- Programming Language version: Eng
- CCXT version: 1.39.42

Can you help?
I want to cancel_order on Bithumb.

-----------------------------------------------------------------
TestOrder ={'info': {'order_currency': 'XRP',
  'payment_currency': 'KRW',
  'order_id': 'Cxxxxxxxxxxxx',
  'order_date': '1608182275266181',
  'type': 'bid',
  'watch_price': '0',
  'units': '100',
  'units_remaining': '100',
  'price': '500'},
 'id': 'Cxxxxxxxxxxxxxxxxxx',
 'clientOrderId': None,
 'timestamp': 1608182275266,
 'datetime': '2020-12-17T05:17:55.266Z',
 'lastTradeTimestamp': None,
 'symbol': 'XRP/KRW',
 'type': 'limit',
 'timeInForce': None,
 'postOnly': None,
 'side': 'buy',
 'price': 500.0,
 'stopPrice': None,
 'amount': 100.0,
 'cost': None,
 'average': None,
 'filled': 0,
 'remaining': 100.0,
 'status': None,
 'fee': None,
 'trades': None}

bithunb.cancel_order(TestOrder['id'])  ??????
bithunb.cancel_order(TestOrder['id'], TestOrder['symbol'])  ?????
bithunb.cancel_order(TestOrder['id'], TestOrder['symbol'], TestOrder['side'])  ?????

Traceback (most recent call last):

  File "<ipython-input-47-dc0136ea42ae>", line 1, in <module>
    ExchangesNameAPI[TempExchange].cancel_order(TempOpenOrderN['id'], TempOpenOrderN['symbol'])

  File "C:\ProgramData\Anaconda3\lib\site-packages\ccxt\bithumb.py", line 727, in cancel_order
    raise ArgumentsRequired(self.id + ' cancelOrder requires a `symbol` argument and a `side` parameter(sell or buy)')

ArgumentsRequired: bithumb cancelOrder requires a `symbol` argument and a `side` parameter(sell or buy)

All of the following errors occur.
Please tell me how to do it.
Thank you.

**Comment by kroitor** [comment]
This is documented here: https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-params

```Python
params = {'side': TestOrder['side']}  # ←---------------------↓
exchange.cancel_order(TestOrder['id'], TestOrder['symbol'], params)
```

**Comment by Eavan0103** [comment]
> This is documented here: https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-params
> 
> ```python
> params = {'side': TestOrder['side']}  # ←---------------------↓
> exchange.cancel_order(TestOrder['id'], TestOrder['symbol'], params)
> ```
> 
> or
> 
> ```python
> exchange.cancel_order(TestOrder['id'], TestOrder['symbol'], {'side': TestOrder['side']})
> ```

kroitor 
It works well.
Thank you.
