### ISSUE TITLE
 Get percentage of an order

### ISSUE THREAD

**Issue by alexandrebouttier** [ccxt/ccxt#8125]
Hello, I am coding a bot that copies my binance account and executes orders on multiple clients, but I block to find a solution to know when I sell or buy per part, for example I open an order at 100 % on BTC and then I sell that 20% how to calculate this? so that on my clients, they also sell only 20%

thank you

**Comment by kroitor** [comment]
Hi! Pardon for a long delay with the answer. Can you please elaborate on the question a bit? It's not clear which percentages are in question. Basically, if you follow the Manual precisely, you can use the balance info and the order info with basic math to calculate the numbers how you want.

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by ttodua** [comment]
As @ kroitor suggested above, it might have fixed the issue, but there was no clear description neither follow-up for this issue, so closing it for now.
