### ISSUE TITLE
Библиотека не работает на PHP

### ISSUE THREAD

**Issue by sunlit2000** [ccxt/ccxt#813]
Добрый день!
Запускаю PHP скрипт ($version = '1.10.337') на локальном сервере Denwer (in win7)
![ccxt](https://user-images.githubusercontent.com/10777331/33804345-a86317bc-dd9a-11e7-8acb-626dbf8efdbd.jpg)
. 
PHP 5.3.13, cURL 7.24.0, Multibyte - enabled,  PCRE 8.12, iconv 1.11
Все модули запущены.

Мой index.php
`include 'ccxt.php';

$poloniex = new \ccxt\poloniex  ();
$poloniex_markets = $poloniex->load_markets ();
var_dump ($poloniex_markets);
var_dump ($poloniex->fetch_order_book ($poloniex->symbols[0]));`

**Возможно очень много ошибок при компиляции из JS в PHP...**
1. Parse error: syntax error, unexpected '[' in www\php\base\Exchange.php on line 206
Меняю $result = []; на $result = array();

2. Parse error: syntax error, unexpected '[' in www\php\base\Exchange.php on line 754
Меняю $response_headers[$name] = [trim ($header[1])]; на $response_headers[$name] = trim ($header[1]);

3. Parse error: syntax error, unexpected '[' in Z:\home\t1.ru\www\php\poloniex.php on line 163
Меняю return [
            $ohlcv['date'] * 1000,
            $ohlcv['open'],
            $ohlcv['high'],
            $ohlcv['low'],
            $ohlcv['close'],
            $ohlcv['volume'],
        ];
на
return array(
            $ohlcv['date'] * 1000,
            $ohlcv['open'],
            $ohlcv['high'],
            $ohlcv['low'],
            $ohlcv['close'],
            $ohlcv['volume'],
        );

4. Parse error: syntax error, unexpected '[' in Z:\home\t1.ru\www\php\poloniex.php on line 482
Меняю public function parse_open_orders ($orders, $market, $result = []) { на public function parse_open_orders ($orders, $market, $result = array()) {

После исправлений 3 и 4 файл poloniex.php работает корректно - возвращаюсь в index.php
И тут уже очень много ошибок (прикрепил скриншоты).

Может быть есть рабочая библиотека под PHP?

**Comment by kroitor** [comment]
@sunlit2000 с версией 1.10.344 то же самое?

> Может быть есть рабочая библиотека под PHP?

Она работает у большинства, однако, непонятно, каким образом OHLCV связаны с fetch_order_book... Надо начать с простого:

1. Работает ли вот это (да/нет) ?

```PHP
include 'ccxt.php';
$poloniex = new \ccxt\poloniex ();
$poloniex_markets = $poloniex->load_markets ();
var_dump ($poloniex_markets);
var_dump ($poloniex->fetch_order_book ($poloniex->symbols[0]));
```

**Comment by sunlit2000** [comment]
> С версией 1.10.344 то же самое?
Да, причем те же самые ошибки в начале в файлах exchange и poloniex

> Она работает у большинства, возможно, проблемы связаны с версией PHP – 5.3.13 очень старая...
Сейчас попробую обновить на OpenServer 5.2.7 LAMP, возможно проблема в версии PHP

> Работает ли вот это в последней версии ccxt (да/нет) ?
Нет, ошибки аналогичные

Где находится функция publicGetReturnTicker на которую ссылается poloniex.php?

**Comment by kroitor** [comment]
@sunlit2000 

> Сейчас попробую обновить на OpenServer 5.2.7 LAMP, возможно проблема в версии PHP

Я проверял на PHP5.6.3 / MacOS и на PHP7 почти везде — работает... скорее всего дело в версии PHP.

> Где находится функция publicGetReturnTicker на которую ссылается poloniex.php?

Генерируются автоматически в define_rest_api из перечисленных в $this->api endpoint'ов. Там местами используются замыкания из-за которых старый PHP может ругаться.

**Comment by sunlit2000** [comment]
Ок. Буду тестировать на другом окружении. СПАСИБО за труд! Надеюсь он приносит свои плоды ;-)

**Comment by sunlit2000** [comment]
Таки проблема была в версии PHP....Последний OpenServer PHP5.5 завелось с пол оборота, буду посмотреть.

**Comment by sunlit2000** [comment]
Забыл спросить, на русском языке нет мануала?

**Comment by kroitor** [comment]
@sunlit2000 к сожалению, ещё нет... мы были бы признательны за помощь в переводе.
