### ISSUE TITLE
Kraken commonCurrencies don't apply for staking types

### ISSUE THREAD

**Issue by SqueezedLight** [ccxt/ccxt#8133]
Hi again,
staking types are properly handled but commonCurrencies do not effect staking currencies. Kraken returns `XBT.M` but it's not mapped to `BTC.M` by `ccxt`.

A quick and dirty fix could be to just add the staking currencies as `commonCurrencies` like that:
```js
commonCurrencies: {
        'XBT': 'BTC',
        'XBT.M': 'BTC.M',
        'XDG': 'DOGE',
        'REPV2': 'REP',
        'REP': 'REPV1',
},
```

But this has the disadvantage that it has to be maintained if currencies or additional extensions are added by kraken. Much better would be to let the `commonCurrencies` also trigger for substrings like `XBT.M`.

What do you think?

EDIT: Currently `XBT` is the only staking asset with this problem.

**Comment by kroitor** [comment]
@SqueezedLight i think you're right, will add that to commonCurrencies for now and will think of a generalized approach if Kraken adds many more of similar asset names later.
