### ISSUE TITLE
OrderNotFound: binance {"code":-2013,"msg":"Order does not exist."}

### ISSUE THREAD

**Issue by gglamenace** [ccxt/ccxt#8134]
- OS: Windows
- Programming Language version: Node JS
- CCXT version: 1.18.988
Exchange: Binance
Method: fetch_order

Is there a way to manage this error which occurs sometimes?

**Comment by kroitor** [comment]
Just catch it as you usually do with exceptions and add your handling how you want. This is documented here:

- https://github.com/ccxt/ccxt/wiki/Manual#error-handling

Let us know if that does not answer your question.

**Comment by kroitor** [comment]
P.S. Just in case, if it's a ETH/USDT futures order, you might want to upgrade to the most recent version of CCXT.
