### ISSUE TITLE
ExchangeError: kucoin fetchOrderBook limit argument must be undefined, 20 or 100

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#8138]
OS: Windows Server 2019 Datacenter
Programming Language version: Node.js 15.3.0
CCXT version: 1.38.89
Exchange: All Exchanges or kucoin
Method: fetchOrderBook

Hello!

I have a question about when returning the OrderBook for an exchange. The code below works for 24 exchanges but encountered an error message for kucoin suddenly yesterday. 

What I am trying to do is to retreive a Maximum of 5 depths from the orderbook. So if there is only 3 depths, then those 3 will be retreived. If there are 12 depths, still only 5 depths should be retreived.

The below code produces the error:
**ExchangeError: kucoin fetchOrderBook limit argument must be undefined, 20 or 100**

I am not sure what this error means or how to write the code to avoid this error?

Thank you!

```
'use strict';
const ccxt = require('ccxt');

//Declare kucoin
let kucoin = new ccxt.kucoin();
const orderbook = kucoin.fetchOrderBook("DEGO/USDT", 5);
```

**Comment by kroitor** [comment]
> I am not sure what this error means or how to write the code to avoid this error?

It literally means that the `limit` argument must be `undefined`, `20` or `100` and Kucoin won't accept anything else, so `5` will not work.

This is not a question about CCXT, but more like a question on how to code basic things in JavaScript.

```JavaScript
'use strict';

const ccxt = require('ccxt')

console.log ('CCXT Version:', ccxt.version)

async main () {
    const exchange = new ccxt.kucoin ({
        enableRateLimit: true, // required https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
    })
    const symbol = 'DEGO/USDT'
    const limit = 20
    const orderbook = await exchange.fetchOrderBook (symbol, 20)
    // limit it to 5 bids and 5 asks
    const limitedOrderbook = {
        'asks': orderbook['asks'].slice (0, 5),
        'bids': orderbook['bids'].slice (0, 5),
        'nonce': orderbook['nonce'],
        'timestamp': orderbook['timestamp'],
        'datetime': orderbook['datetime'],
    }
    console.log (limitedOrderbook)
}

main ()
```

Let us know if that does not answer your question.

**Comment by jackpotcityco** [comment]
Thank you,

Yes, I think I got confused of the ```undefined``` word there. For it to be undefined and at the same time have a certain value got me confused I think.
But then I know that some exchanges require certain orderbook depths there.

Thank you for your help!
