### ISSUE TITLE
Wrong multiplier in Anxpro

### ISSUE THREAD

**Issue by rubobaquero** [ccxt/ccxt#814]
In the CCXT's Anxpro definition, the multiplier applied for creating orders for price_int parameter is always 10^5. According to Anxpro docs, it should be 10^8 or 10^5 depending of the pair.

https://anxv2.docs.apiary.io/#reference/data-object-definition

**Comment by kroitor** [comment]
Thank you for reporting this! Will look into it and fix it shortly!
