### ISSUE TITLE
Examples for phemex leverage trades

### ISSUE THREAD

**Issue by BHruska** [ccxt/ccxt#8143]
I see you added phemex recently.  Was looking for some sample python code for executing a leveraged BTC trade.  

Examples in general are so great, and I assume the best place to see them is here, but I see nothing for this.

**Comment by carlosmiei** [comment]
"Hello @BHruska , please check out this snippet where a contract order with leverage is created: 

```Python
import ccxt # noqa: E402

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.phemex({
    'enableRateLimit': True,
	'apiKey': 'YOUR_API_KEY',
	'secret': 'YOUR_SECRET',
	'options': {
	'defaultType': 'swap',
	},
})
amount = 5
symbol = 'BTC/USD:USD'

# Change leverage to the desired value
leverageResponse = exchange.set_leverage(5, symbol)

# Opening a pending contract (limit) order
order = exchange.create_order(symbol, 'market', 'buy', amount)
print(order)
```

You can also see a complete example here: https://github.com/ccxt/ccxt/blob/master/examples/py/phemex-leverage-orders.py"
