### ISSUE TITLE
Implicit API methods in CCXT Pro

### ISSUE THREAD

**Issue by diwenshi61** [ccxt/ccxt#8146]
ccxt-1.39.61 ccxtpro-0.5.1 python3.8.5

I was trying to add the new universalTransfer Binance endpoints to the implicit API methods.

In my local copy of ccxt's binance.py, I added 'sub-account/universalTransfer' under 'api'['sapi']['get'] and 'api'['sapi']['post']. These appear in ccxt and work fine, but not in ccxtpro. How do I add these endpoints in a way that is seen in ccxtpro?

**Comment by kroitor** [comment]
1. uninstall the unedited ccxt `pip uninstall ccxt`
2. install the ccxt you've patched with `pip install /path/to/your/patched/ccxt`

Let us know if that does not answer your question.

We will add those endpoint to the master version as well.
