### ISSUE TITLE
binance does not have market symbol TWT/USDT

### ISSUE THREAD

**Issue by bongkook** [ccxt/ccxt#8156]
- OS:Mac
- Programming Language version:node.js
- CCXT version:1.39.54

I ran it with the symbol ETH/USDT specified in binance.createOrder, but the following error occurred. What is the cause?
"binance does not have market symbol TWT/USDT"
It doesn't happen all the time, it happens occasionally.

**Comment by kroitor** [comment]
@bongkook you're placing the order against the TWT/USDT market which does not exist with Binance. Use the verbose mode for troubleshooting. Let us know if that does not answer your question.

- https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
- https://github.com/ccxt/ccxt/wiki/Manual#loading-markets
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

Feel free to reopen this issue or just ask further questions if any.
