### ISSUE TITLE
Get Binance FIAT Transaction History

### ISSUE THREAD

**Issue by claudiogreco** [ccxt/ccxt#8160]
Hello,

I would need to get the Binance FIAT transaction history you can find at www.binance.com/en/my/wallet/history/deposit-fiat. Unfortunately, I cannot find a method to do that through CCXT. Could you help me? Thank you in advance for your attention.

Best,
Claudio

**Comment by kroitor** [comment]
- https://stackoverflow.com/questions/63263500/binance-api-endpoint-for-fiat-deposits-from-bank-card

I'd suggest to forward this question to Binance: https://t.me/binance_api_english

CCXT supports all endpoints listed in Binance's API docs:

- https://binance-docs.github.io/apidocs/spot/en/

If you don't get your fiat deposits with `exchange.sapi_get_capital_deposit_hisrec()` or `exchange.fetchDeposits()`, then there is no way of fetching the fiat transactions via API as far as I know.

**Comment by diwenshi61** [comment]
If there's a functionality found on the website but not in the API documentation, you can find the undocumented endpoint by checking network requests on that page. When I visit that page, I see a get request to https://www.binance.com/gateway-api/v3/public/haodesk/common/config/js?pathName=/en/my/wallet/history/deposit-crypto&h=www.binance.com which may be what you're looking for. However, these endpoints are finicky and obviously undocumented, and can change without notice, making them difficult to use for any application, so I'd wait for Binance to add these to the documented API.

**Comment by kroitor** [comment]
@diwenshi61 100% agree!

**Comment by RusDyn** [comment]
> If there's a functionality found on the website but not in the API documentation, you can find the undocumented endpoint by checking network requests on that page. When I visit that page, I see a get request to https://www.binance.com/gateway-api/v3/public/haodesk/common/config/js?pathName=/en/my/wallet/history/deposit-crypto&h=www.binance.com which may be what you're looking for. However, these endpoints are finicky and obviously undocumented, and can change without notice, making them difficult to use for any application, so I'd wait for Binance to add these to the documented API.

Hi,
Do you think it's possible to use this endpoint with API keys?

**Comment by kroitor** [comment]
@RusDyn hi! No, I think it requires website authentication which is different from the API authentication. I would not recommend relying on the web APIs.
