### ISSUE TITLE
How to fetch fiat balance from coinbase?

### ISSUE THREAD

**Issue by art1313** [ccxt/ccxt#8163]
Hi I was wondering if its possible to fetch GBP or EUR balances from coinbase? looks like fetch_balance() only returns crypto and USD balance.

Thanks.

**Comment by jaguarqc** [comment]
fetch_balance does not return USD as far as I know. 
It returns your balances thru a list of cryptos.
You can always call:
`const gbp = await coinbase.publicGetPricesSymbolBuy({'symbol': 'BTC-GBP'})`
(will return `{ data: { base: 'BTC', currency: 'GBP', amount: '21585.79' } }` )
 to get the pair value and simply make the math.

**Comment by kroitor** [comment]
@jaguarqc thank you!

@art1313 let us know if the above does not answer your question.
