### ISSUE TITLE
Exchange-specific websocket streams in CCXT Pro

### ISSUE THREAD

**Issue by diwenshi61** [ccxt/ccxt#8174]
Was wondering if there are built-in ways to watch websockets that are not part of the unified API.

For example, (ccxt-1.39.77 ccxtpro-0.5.3 python 3.8.5)

```
import asyncio
import ccxtpro

async def main():

    binance = ccxtpro.binance({
        'apiKey': api_key_here,
        'secret': api_secret_here,
        'enableRateLimit': False,
        'options': {
            'defaultType': 'future'
        }
    })

    print(await binance.watch_public('btcusdt@trade'))
    print(await binance.watch_public('btcusdt@miniTicker'))

if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())
```

Obviously this isn't how the websockets should be used, it's just for demonstration purposes.

The first one works fine (unified API method), but the second one hangs and never completes.
I think the ideal implementation would be if the second one would return something like
`[{'info': {some_stuff_here: something_here}]`
like the unified API methods but without any parsing.

**Comment by kroitor** [comment]
@diwenshi61 there's currently no general way of watching exchange-specific streams, but we will add that layer soon. In the meantime you will need to also override the handling of messages to make it work with the code you posted above, so:

- https://github.com/ccxt/ccxt/tree/master/examples/ccxt.pro/py/watch-custom-exchange-specific-streams.py

```Python
import asyncio
import ccxtpro


class MyBinance(ccxtpro.binance):

    def handle_mini_ticker(self, client, message):
        market_id = self.safe_string_lower(message, 's')
        message_hash = market_id + '@miniTicker'
        client.resolve(message, message_hash)

    def handle_message(self, client, message):
        handlers = {
            '24hrMiniTicker': self.handle_mini_ticker,
            # add other custom handlers here
        }
        e = self.safe_string(message, 'e')
        method = self.safe_value(handlers, e)
        if method:
            return method(client, message)
        else:
            return super(MyBinance, self).handle_message(client, message)


async def main():
    exchange = MyBinance({
        'enableRateLimit': False,
        'options': {
            'defaultType': 'future'
        }
    })
    await exchange.load_markets()
    # exchange.verbose = True  # uncomment for debugging purposes
    market = exchange.market('BTC/USDT')
    message_hash = market['lowercaseId'] + '@miniTicker'
    while True:
        try:
            print(await exchange.watch_public(message_hash))
        except Exception as e:
            print(type(e).__name__, str(e))
    await exchange.close()


if __name__ == '__main__':
    asyncio.get_event_loop().run_until_complete(main())
```

We understand that this is not the best way to watch exchange-specific streams, but, as you've noted, it's not the intended usage, so we will add more functionality to make this particular aspect more convenient.

Let us know if that does not answer your question.
