### ISSUE TITLE
Kraken starts using XXBT->BTC and ZUSD->USD; mappings provided

### ISSUE THREAD

**Issue by c0dehunter** [ccxt/ccxt#8176]
Kraken really likes to change ticker names it seems. They now added "Z" in front of all fiat symbols and "X" in front of crypto symbols.

I have added mappings to PHP manually. I am bad at JS so I can't contribute yet directly (hopefully, soon). Could you please add these? Or maybe we should add a function for this so we don't need to add manually each time Kraken lists new asset.

```
'commonCurrencies' => array(
	'XXBT' => 'BTC', // https://support.kraken.com/hc/en-us/articles/360001185506-How-to-interpret-asset-codes
	'XBT' => 'BTC',
	'XBT.M' => 'BTC.M', // https://support.kraken.com/hc/en-us/articles/360039879471-What-is-Asset-S-and-Asset-M-
	'XETH' => 'ETH',
	'XETC' => 'ETC'
	'XLTC' => 'LTC',
	'XDG' => 'DOGE',
	'XXDG' => 'DOGE',
	'XXTZ' => 'XTZ',
	'XXRP' => 'XRP',
	'XXMR' => 'XMR',
	'XXLM' => 'XLM',
	'XMLN' => 'MLN',
	'REPV2' => 'REP',
	'XREPV2' => 'REP',
	'REP' => 'REPV1',
	'XREP' => 'REPV1'
	'ZUSD' => 'USD',
	'ZEUR' => 'EUR',
	'ZGBP' => 'GBP',
	'ZJPY' => 'JPY',
	'ZCAD' => 'CAD',
),
```

**Comment by kroitor** [comment]
This is already handled in the most recent version of CCXT. Let us know if you have difficulties with it.

**Comment by c0dehunter** [comment]
I am using the latest version 1.39.52 and fetch_balance() doesn't return correct symbols.

** Code: **
```
- OS: Linux
- Programming Language version: PHP 7.3
- CCXT version: 1.39.52

$id = "\\ccxt\\kraken";
$exchange = new $id();
$exchange->apiKey = "XXXX"; // testing API key
$exchange->secret = "YYYY";
$exchange->enableRateLimit = true;

for($balance : $exchange->fetchBalance()) {
	print_r($balance["total"]);
}
```


** Output: **
```
Array
(
[0] => Request:
[1] => POST
[2] => https://api.kraken.com/0/private/Balance
[3] => Array
(
[API-Key] => 1miBoxpxY9/8pUIAq+VrQGJojGJIjXwSeF0AtNZoALQFATRlqIrfnhg/
[API-Sign] => lWFvdy95zdxWGt3qIlH4av+/fD1ZMhJxeilE0jO3Oo3WScOtPFVjZrGOHDKH1qf7RMrLZrI0ZIGuvVBTUWa1Hg==
[Content-Type] => application/x-www-form-urlencoded
)

[4] => nonce=1609239365800
)
Array
(
[0] => Response:
[1] => POST
[2] => https://api.kraken.com/0/private/Balance
[3] => 200
[4] =>
[5] => Array
(
[Date] => Tue, 29 Dec 2020 10:56:06 GMT
[Content-Type] => application/json; charset=utf-8
[Transfer-Encoding] => chunked
[Connection] => keep-alive
[Set-Cookie] => __cfduid=d9c63890b29939bea5954302dc315d2dc1609239365; expires=Thu, 28-Jan-21 10:56:05 GMT; path=/;
domain=.kraken.com; HttpOnly; SameSite=Lax
[Content-Encoding] => gzip
[Vary] => Accept-Encoding
[Strict-Transport-Security] => max-age=15768000
[CF-Cache-Status] => DYNAMIC
[Cf-Request-Id] => 074fbd20c2000040ea002b0000000001
[Expect-CT] => max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
[Server] => cloudflare
[CF-RAY] => 6092fe146c5540ea-LHR
)

[6] =>
{"error":[],"result":{"ZUSD":"0.5546","ZEUR":"0.1547","KFEE":"3276.66","XXBT":"0.0000079590","XXLM":"0.00000040","XETH":"0.0000086800","XICN":"0.0000000000","XXMR":"0.0000000000","USDT":"0.12038005","XMLN":"0.0000000000","BCH":"0.0000000000","USDC":"0.05819000"}}
)
{"msg":"OK","exchange":"kraken","balances":{"ZUSD":0.5546,"ZEUR":0.1547,"KFEE":3276.66,"USDT":0.12038005,"USDC":0.05819}}
```

**Comment by kroitor** [comment]
@c0dehunter thx, will check that and will get back to you shortly!

**Comment by c0dehunter** [comment]
@kroitor please give me a few more minutes to double-check my code and will get back shortly.

**Comment by kroitor** [comment]
@c0dehunter no worries, i've reproduced it on my side, fixing now!

**Comment by kroitor** [comment]
@c0dehunter can you please paste your complete output here (without your keys) using the following snippet with the most recent version of CCXT? ↓

```PHP
$id = "\\ccxt\\kraken";
$exchange = new $id(array(
    'apiKey' => 'YOUR_API_KEY',
    'secret' => 'YOUR_SECRET',
    'enableRateLimit' => true,
));
$markets = $exchange->load_markets();
$exchange->verbose = true;
$balance = $exchange->fetch_balance();
print('------------------------------------------------------')
print_r($balance);
```

**Comment by c0dehunter** [comment]
@kroitor It works properly if I call `$markets = $exchange->load_markets();` first! Without it doesn't work, I guess because CCXT doesn't have the required data (symbols) yet. But calling this extra function takes 6 seconds and it doesn't seem to be cached. We have hundreds of calls per minute on our backend that use fetch_balance() function.

1.) Do we need to call `$exchange->load_markets();` for all exchanges or is this required just for Kraken?
2.) Can this be cached so it doesn't take so much time for each call?

**Comment by kroitor** [comment]
@c0dehunter a call to load_markets() must be built into Kraken, it's actually called automatically in every method except fetch_balance – it was missing there for historical reasons, i've added it just now, it will arrive in version 0.39.88+ in ~20 minutes, from there it should work fine without having to load the markets manually and without having to change your code. 

All of this is explained here: https://github.com/ccxt/ccxt/wiki/Manual#loading-markets

> 1.) Do we need to call $exchange->load_markets(); for all exchanges or is this required just for Kraken?

No need to call it – cause it will be called for you and cached (make sure your version is 0.39.88 or higher).

> 2.) Can the results of $exchange->load_markets(); be cached internally in CCXT so it doesn't take so much time for each call?

Just follow that link to the Manual, it explains how the markets are loaded and cached on the exchange instance.

Let me know if that does not help.

**Comment by c0dehunter** [comment]
Thanks a 1337x times!

**Comment by c0dehunter** [comment]
@kroitor It's working now (ticker symbols) but seems caching is not working for me and I think I know why - because it is cached in memory, not on disk, right?

Our use case is like this, very simplified:

1. We have an API endpoint on our server: `xyz.com/get_balance.php?exchange=kraken&key=xxx&secret=yyy`
2. Contents of `get_balance.php` is something like
```
$id = "\\ccxt\\{$_GET['exchange']}";
$exchange = new $id(array(
    'apiKey' => '$_GET['key']}',
    'secret' => '$_GET['secret']}',
    'enableRateLimit' => true,
)); // I think cache will always be missing at this point, no?
$balance = $exchange->fetch_balance();
// return balance to user
```
3. This endpoint is called by end-users many times per minute. I am afraid `$exchange` object will not have cache available from previous calls, or will it? If not, then how can we fix this?

**Comment by kroitor** [comment]
@c0dehunter i'll post an example shortly...

**Comment by kroitor** [comment]
@c0dehunter 

1. plz upgrade to 0.39.89+ (fixed one more minor bug)
2. use this snippet for reference (run it multiple times to see the disk cache in effect):

- https://github.com/ccxt/ccxt/blob/master/examples/php/shared-markets.php

```PHP
<?php

$root = dirname (dirname (dirname (__FILE__)));

include $root . '/ccxt.php';

date_default_timezone_set ('UTC');

// ----------------------------------------------------------------------------
// an example of how to load markets for each exchange just once
// in order to save memory and time for initializing multiple exchange instances
// see these issues for details:
// - https://github.com/ccxt/ccxt/issues/7312
// - https://github.com/ccxt/ccxt/issues/8176
// ----------------------------------------------------------------------------

$keys = array(
    'ids',
    'markets',
    'markets_by_id',
    'marketsById',
    'currencies',
    'currencies_by_id',
    'base_currencies',
    'quote_currencies',
    'symbols',
);


$id = 'kraken';
$exchange_class = "\\ccxt\\{$id}";
$exchange = new $exchange_class(array(
    'enableRateLimit' => true,
));

$markets_on_disk = "./{$id}.markets.json";

$exchange->verbose = true; // this is a debug output to demonstrate which networking calls are being issued

if (file_exists($markets_on_disk)) {

    $cache = json_decode(file_get_contents($markets_on_disk), true);
    foreach ($keys as $key) {
        $exchange->{$key} = $cache[$key];
    }

} else {

    $exchange->load_markets();
    $cache = array();
    foreach ($keys as $key) {
        $cache[$key] = $exchange->{$key};
    }
    file_put_contents($markets_on_disk, json_encode($cache));
}

$exchange->fetch_ticker('ETH/BTC');
```

**Comment by c0dehunter** [comment]
Works great!

I made this into a function:

```
$id = "\\ccxt\\kraken";
$exchange = new $id();
$exchange->apiKey = "xxx";
$exchange->secret = "yyy";
$exchange->enableRateLimit = true;

load_cache($exchange);


function load_cache(&$exchange) {
	$diskCacheFile = "your_path_to/ccxt_cache/{$exchange->id}.markets.json"; // make sure it's chmodded, if needed
	$keys = array(
		'ids',
		'markets',
		'markets_by_id',
		'marketsById',
		'currencies',
		'currencies_by_id',
		'base_currencies',
		'quote_currencies',
		'symbols',
	);

	if (file_exists($diskCacheFile) && time() - filemtime($diskCacheFile) < 24 * 3600) {
		// if cache not older than 24 hours
		$cache = json_decode(file_get_contents($diskCacheFile), true);
		foreach ($keys as $key)
			$exchange->{$key} = $cache[$key];
	} else {
		$exchange->load_markets();
		$cache = array();
		foreach ($keys as $key)
			$cache[$key] = $exchange->{$key};
		file_put_contents($diskCacheFile, json_encode($cache));
	}
}
```
