### ISSUE TITLE
mercado.fetch_order not implemented yet

### ISSUE THREAD

**Issue by Felipe-Mangueira** [ccxt/ccxt#818]
Hey again, @kroitor.

I am currently implementing stop-loss strategies in Mercado Bitcoin, but the fetch_order function from it is not implemented yet, neither fetch_order_status.

I really need this function to stop my losses when I cannot stand in front of my trading plataform. Could you help me with this, as soon as you can, please?

Thank you so much!!

**Comment by kroitor** [comment]
Hey, @Felipe-Mangueira ! I've uploaded it, however, I might need your help with testing and debugging it. Let me know if you have any issues with that method after updating to 1.10.347 (I will need `.verbose = true` output, of course). Thx!

**Comment by Felipe-Mangueira** [comment]
Hey @kroitor.

I made a test with a order totally executed but it returned a key error. Could you check where is the problem, please? See the log:

'''
Connected to pydev debugger (build 172.3544.46)
https://www.mercadobitcoin.net/tapi/v3/ POST https://www.mercadobitcoin.net/tapi/v3/ 
Request: {'Content-Type': 'application/x-www-form-urlencoded', 'TAPI-ID': 'TAPI-ID', 'TAPI-MAC': 'TAPI-MAC', 'User-Agent': 'ccxt/1.10.349 (+https://github.com/ccxt/ccxt) Python/3.6.2', 'Accept-Encoding': 'gzip, deflate'} tapi_method=get_order&tapi_nonce=1512942264096&coin_pair=BRLBCH&order_id=685648
POST https://www.mercadobitcoin.net/tapi/v3/ 
Response: Date: Sun, 10 Dec 2017 21:44:24 GMT
Content-Type: application/json
Connection: close
Server: Apache
Vary: Cookie
X-Frame-Options: SAMEORIGIN
Set-Cookie: visid_incap_619276=PjsOtG0KSHWETFw0nS4SJLiqLVoAAAAAQUIPAAAAAADMbl4QuArG77BvM8by6tPX; expires=Mon, 10 Dec 2018 13:02:51 GMT; path=/; Domain=.mercadobitcoin.net
Set-Cookie: nlbi_619276=04BmPguQLjtHkhMe2TZ0lAAAAAD4cZjMJNcLzdmiYibAcqCJ; path=/; Domain=.mercadobitcoin.net
Set-Cookie: incap_ses_785_619276=LCfkW1eJ00EE++SHfOHkCriqLVoAAAAAduribIwkua0Xicj8ZkkPPg==; path=/; Domain=.mercadobitcoin.net
Set-Cookie: ___utmvmmzulzpm=OfnJVDsgWnF; path=/; Max-Age=900
Set-Cookie: ___utmvamzulzpm=jTjxHww; path=/; Max-Age=900
Set-Cookie: ___utmvbmzulzpm=fZA
    XVpOEalx: Kth; path=/; Max-Age=900
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Iinfo: 7-19763609-19763613 NNNN CT(184 188 0) RT(1512942263711 57) q(0 0 4 -1) r(6 6) U6
X-CDN: Incapsula
Content-Encoding: gzip
Transfer-Encoding: chunked

 {"response_data": {"order": {"order_id": 685648, "coin_pair": "BRLBCH", "order_type": 2, "status": 4, "has_fills": true, "quantity": "0.36572000", "limit_price": "4652.00000", "executed_quantity": "0.36572000", "executed_price_avg": "4652.00000", "fee": "11.90930608", "created_timestamp": "1512940569", "updated_timestamp": "1512940569", "operations": [{"operation_id": 260948, "quantity": "0.36572000", "price": "4652.00000", "fee_rate": "0.70", "executed_timestamp": "1512940569"}]}}, "status_code": 100, "server_unix_timestamp": "1512942264"}
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.1\helpers\pydev\pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.1\helpers\pydev\pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/MANGUEIRA/PycharmProjects/Bots Projects/teste/teste.py", line 87, in <module>
    x = mercado.fetch_order('685648', symbol='BCH/BRL')
  File "C:\Program Files\Python36\lib\site-packages\ccxt\mercado.py", line 225, in fetch_order
    return self.parse_order(response['result'])
KeyError: 'result'
'''

**Comment by kroitor** [comment]
Ok, that was a minor parsing issue, I've fixed it, and now it should work normally (update to 1.10.351+). As always, I'll be happy if you report back whether it now works smoothly or not on your side. Thx a lot!

**Comment by Felipe-Mangueira** [comment]
Hi @kroitor, Sorry for my delay on reporting back to you. I've tested the update and it's working fine. Thanks for your support like always.

**Comment by dbzalpha** [comment]
Thanks for the correction! 
Though we have a little typo at line 249 for async_support/mercado.py
`timestamp = self.safeIneteger(order, 'created_timestamp') #typo
timestamp = self.safe_integer(order, 'created_timestamp') #correct with safe_integer`
