### ISSUE TITLE
How to install CCXT Pro?

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#8182]
OS: Windows Server 2019 Datacenter
Programming Language version: Node.js
CCXT version: trying to install the latest ccxt pro
Node.js 15.3.0 installed
Method: npm install ccxt  (pro version)

Hello!

I have the **ccxt** installed and wonder how I should also install the **ccxt pro** version as I am interested to work with the WebSockets.

I have red on this link under: **JavaScript Dependency**
https://ccxt.readthedocs.io/en/latest/ccxt.pro.install.html

I have manually added this as mentioned there to the file: package.json: 
```
// package.json
{
  // ...
  "dependencies": {
    "ccxt.pro": "git+https://github.com/kroitor/ccxt.pro.git"
  }
  // ...
}
```

Then it says the below:
_"Running npm install in the same folder after adding the above to package.json will install CCXT Pro to your node_modules/. To update it later run npm update ccxt.pro."_

I am not sure exactly what I should do here now so I do this correctly.
1. Should I in CMD when having my directory choosen, - just enter: **npm install**   ?
2. Should I after this when having my directory choosen, - just enter: **npm update ccxt.pro**   ? 

I beleive it is best to ask so I am not doing anything wrong or if I miss any detail there.

Thank you!

**Comment by kroitor** [comment]
Hi! 

> I have red on this link under: JavaScript Dependency
> https://ccxt.readthedocs.io/en/latest/ccxt.pro.install.html

Please, don't use RTD – it's outdated. All doc are here: 

- https://github.com/ccxt/ccxt/wiki
- CCXT: https://github.com/ccxt/ccxt/wiki/Manual, https://github.com/ccxt/ccxt/wiki/Install
- CCXT Pro: https://github.com/ccxt/ccxt/wiki/ccxt.pro.manual, https://github.com/ccxt/ccxt/wiki/ccxt.pro.install

The access to the CCXT Pro repository is paid-only, you will need to obtain the license at https://ccxt.pro. For that reason you can't install it from the npm repository and you should only install it as described in the installation manual: https://github.com/ccxt/ccxt/wiki/ccxt.pro.install#javascript

The CCXT Pro licensing is explained in this issue (highly recommend reading it): https://github.com/ccxt/ccxt/issues/6543

Let us know if that does not answer your question. Feel free to reopen it or just ask further questions if any.

**Comment by jackpotcityco** [comment]
Thank you, I understand, then I will look in the links at the correct place there only.

Yes, I understand. I wansn't sure about it but then I will look at the licenses on the links for the pro version there.

Thank you for all the information, I will read it.

Thank you!
