### ISSUE TITLE
Poloniex   Missing Symbol - REEF/USDT

### ISSUE THREAD

**Issue by Rishirandhawa** [ccxt/ccxt#8183]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: MAC
- Programming Language version: Py Latest
- CCXT version: Latest

```
instrument = 'REEF/USDT'
candle_count = 250
candle_size = '30m'

params = {
    'limit': str(candle_count)
}
candles = exchange.fetch_ohlcv (instrument, candle_size, params=params)
```

```
---------------------------------------------------------------------------
BadSymbol                                 Traceback (most recent call last)
<ipython-input-110-fd0c6ba28009> in <module>
      9     'limit': str(candle_count)
     10 }
---> 11 candles = exchange.fetch_ohlcv (instrument, candle_size, params=params)
     12 df = pd.DataFrame(candles)
     13 df.columns = ['datetime', 'o', 'h', 'l', 'c', 'v']

~/projects/trading-bot/env/lib/python3.8/site-packages/ccxt/poloniex.py in fetch_ohlcv(self, symbol, timeframe, since, limit, params)
    264     def fetch_ohlcv(self, symbol, timeframe='5m', since=None, limit=None, params={}):
    265         self.load_markets()
--> 266         market = self.market(symbol)
    267         request = {
    268             'currencyPair': market['id'],

~/projects/trading-bot/env/lib/python3.8/site-packages/ccxt/base/exchange.py in market(self, symbol)
   1816         if isinstance(symbol, basestring) and (symbol in self.markets):
   1817             return self.markets[symbol]
-> 1818         raise BadSymbol('{} does not have market symbol {}'.format(self.id, symbol))
   1819 
   1820     def market_ids(self, symbols):

BadSymbol: poloniex does not have market symbol REEF/USDT```

**Comment by kroitor** [comment]
Please, try these snippets:

```Python
import ccxt

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.poloniex({'enableRateLimit': True})
markets = exchange.load_markets()
print(exchange.market('REEF/USDT'))
```

-----------

```Python
import ccxt

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.poloniex({'enableRateLimit': True})

response = exchange.fetch_ohlcv('REEF/USDT', '30m')
print(response)
```

-----

```
mbp:python igorkroitor$ python3
Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>>
>>> print('CCXT Version:', ccxt.__version__)
CCXT Version: 1.39.92
>>>
>>> exchange = ccxt.poloniex({'enableRateLimit': True})
>>>
>>> response = exchange.fetch_ohlcv('REEF/USDT', '30m')
>>> print(response)
[[1609376400000, 0.01396002, 0.01396002, 0.01396002, 0.01396002, 2031.41222433], [1609378200000, 0.01396002, 0.01396002, 0.01396002, 0.01396002, 0.0], [1609380000000, 0.01396002, 0.01396002, 0.01396002, 0.01396002, 0.0], [1609381800000, 0.0115, 0.0115, 0.0115, 0.0115, 500.0]]
```

Please, paste your output here.

**Comment by Rishirandhawa** [comment]
CCXT Version: 1.39.83
{'percentage': True, 'maker': 0.0009, 'taker': 0.0009, 'precision': {'amount': 8, 'price': 8}, 'limits': {'amount': {'min': 1e-06, 'max': 1000000000}, 'price': {'min': 1e-08, 'max': 1000000000}, 'cost': {'min': 1.0}}, 'id': 'USDT_REEF', 'numericId': 502, 'symbol': 'REEF/USDT', 'baseId': 'REEF', 'quoteId': 'USDT', 'base': 'REEF', 'quote': 'USDT', 'active': True, 'info': {'id': 502, 'last': '0.01150000', 'lowestAsk': '0.01396000', 'highestBid': '0.01120000', 'percentChange': '-0.17621894', 'baseVolume': '34.10855528', 'quoteVolume': '2531.41222433', 'isFrozen': '0', 'high24hr': '0.01396002', 'low24hr': '0.01150000'}}

===============
CCXT Version: 1.39.83
[[1609376400000, 0.01396002, 0.01396002, 0.01396002, 0.01396002, 2031.41222433], [1609378200000, 0.01396002, 0.01396002, 0.01396002, 0.01396002, 0.0], [1609380000000, 0.01396002, 0.01396002, 0.01396002, 0.01396002, 0.0], [1609381800000, 0.0115, 0.0115, 0.0115, 0.0115, 500.0], [1609383600000, 0.0112, 0.0112, 0.0112, 0.0112, 722.31031607]]

**Comment by kroitor** [comment]
@Rishirandhawa so, it works.

**Comment by kroitor** [comment]
@Rishirandhawa let us know if you have further difficulties with it. The above snippets show that 'REEF/USDT' is available. Feel free to reopen this issue or just ask more questions if any.

**Comment by Rishirandhawa** [comment]
Thanks Igor. Did some digging and it turns out it's a very lightly traded instrument. I am pulling 500 limit and it seems because it had only 4-5 records so it led to the logical exception. Not sure why it mentioned - BadSymbol: poloniex does not have market symbol REEF/USDT for this symbol  ...... at the time.

Thanks again for checking
