### ISSUE TITLE
 'KC-API-KEY-VERSION': '2'  causes error with kucoin api

### ISSUE THREAD

**Issue by r4VP4** [ccxt/ccxt#8187]
- OS:Windows 10
- Programming Language version:Python 3.8.7
- CCXT version:1.39.93

```
import ccxt

from runsim.runtestconfig import auth


def check_kucoin():
    exchange = 'kucoin'
    exchange_cls = ccxt.kucoin({'apiKey': auth[exchange]['API_KEY'],
                            'secret': auth[exchange]['API_SECRET'],
                            'password': auth[exchange]['API_PW']})

    testdata = exchange_cls.fetch_accounts()
    print(testdata)


if __name__ == '__main__':
    check_kucoin()
```

```
ccxt.base.errors.AuthenticationError: Invalid KC-API-PASSPHRASE
```

Hy,

you changed the parameters for the kucoin api auth and added 'KC-API-KEY-VERSION': '2' in CCXT version 1.39.93. But as endpoint there is still '/api/v1/accounts' used. This does not work together and causes the above error. This is my result from debugging. Or am i missing something and have to tell ccxt to use the v2-version of the api with some parameters?

**Comment by kroitor** [comment]
Hold on, will resolve this shortly.

**Comment by kroitor** [comment]
@r4VP4 is your API key v1 or v2?

**Comment by kroitor** [comment]
As of CCXT 1.39.95:

If you are using a **v1 apiKey**:

```Python
import ccxt
exchange = ccxt.kucoin({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_API_SECRET',
    'password': 'YOUR_API_PASSWORD',
    'headers': {
        'KC-API-KEY-VERSION': '1',
    },
    },
})
```

If you are using a **v2 apiKey**:

```Python
import ccxt
exchange = ccxt.kucoin({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_API_SECRET',
    'password': 'YOUR_API_PASSWORD',
    },
})
```

**Comment by r4VP4** [comment]
version of my apikey is v2. works perfect now with version 1.39.96. Thank You for the extremely fast support!
