### ISSUE TITLE
#8180 When using the code from the commit number: 0409739 nothing gets printed for future only access account

### ISSUE THREAD

**Issue by lcgamarra** [ccxt/ccxt#8190]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Ubuntu 20.04.1 LTS
- Programming Language version: Python 3.8
- CCXT version: 0.4.69

```

import ccxtpro
from asyncio import get_event_loop


async def main():
    exchange = ccxtpro.binance({
        'enableRateLimit': True,
        'options': {
            'defaultType': 'future',
        },
    })
    symbol = 'BTCUSDT'
    while True:
        try:
            orderbook = await exchange.watch_order_book(symbol)
            print(orderbook['bids'][0], orderbook['asks'][0])
        except Exception as e:
            print(type(e).__name__, str(e))
    await exchange.close()


loop = get_event_loop()
loop.run_until_complete(main())


```

```
The code run but nothing gets printed
```

**Comment by kroitor** [comment]
@lcgamarra I suggest resolving it in the previous issue here: https://github.com/ccxt/ccxt/issues/8180, i will debug this with a futures-only account and will get back to you.
