### ISSUE TITLE
Accelerating  'fetchBalance()' calls

### ISSUE THREAD

**Issue by Maxximiliann** [ccxt/ccxt#8192]
- OS: Ubuntu 20.04.1 LTS
- Programming Language version: Python 3.8.2
- CCXT version: 1.40.3

```
import ccxt
import datetime

def main():
   begin_time = datetime.datetime.now()

    waves_exchange = ccxt.wavesexchange({
        'apiKey': 'API_KEY',
        'secret': 'SECRET_KEY', })

    balances = waves_exchange.fetchBalance()
    balances
    print(datetime.datetime.now() - begin_time)

if __name__ == '__main__':
    main()
```

Execution times:
```

0:00:02.750107
0:00:02.825959
0:00:02.698161
0:00:02.946584
0:00:02.950273
0:00:02.902294
0:00:03.264627
0:00:02.935728

```
Any suggestions on how to dramatically reduce these call times?

**Comment by kroitor** [comment]
You can control your rate-limit manually, by setting the corresponding exchange properties as explained in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties
- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit

Let us know if that does not help or does not answer your question. Feel free to reopen it or just ask further questions if any.

**Comment by kroitor** [comment]
@Maxximiliann also, reuse the exchange instance, cause it will load the markets, as explained in the Manual as well: 

- https://github.com/ccxt/ccxt/wiki/Manual#loading-markets
- https://github.com/ccxt/ccxt/wiki/Manual#notes-on-rate-limiter

```Python
import ccxt
import datetime

def main():

    waves_exchange = ccxt.wavesexchange({
        'rateLimit': 1000,  # override with your value if necessary
        'enableRateLimit': True,
        'apiKey': 'API_KEY',
        'secret': 'SECRET_KEY',
    })
        
    print('-----------------------------------------------------------')
    print('First call:')
    begin_time = datetime.datetime.now()
    balances = waves_exchange.fetchBalance()
    print(datetime.datetime.now() - begin_time)
    
    while True: 
        print('-----------------------------------------------------------')
        print('Subsequent call:')
        begin_time = datetime.datetime.now()
        balances = waves_exchange.fetchBalance()
        print(datetime.datetime.now() - begin_time)

if __name__ == '__main__':
    main()
```

**Comment by Maxximiliann** [comment]
> @Maxximiliann also, reuse the exchange instance, cause it will load the markets, as explained in the Manual as well:
> 
>     * https://github.com/ccxt/ccxt/wiki/Manual#loading-markets
> 
>     * https://github.com/ccxt/ccxt/wiki/Manual#notes-on-rate-limiter
> 
> 
> ```python
> import ccxt
> import datetime
> 
> def main():
> 
>     waves_exchange = ccxt.wavesexchange({
>         'rateLimit': 1000,  # override with your value if necessary
>         'enableRateLimit': True,
>         'apiKey': 'API_KEY',
>         'secret': 'SECRET_KEY',
>         # other credentials...        
>     })
>         
>     print('-----------------------------------------------------------')
>     print('First call:')
>     begin_time = datetime.datetime.now()
>     balances = waves_exchange.fetchBalance()
>     print(datetime.datetime.now() - begin_time)
>     
>     while True: 
>         print('-----------------------------------------------------------')
>         print('Subsequent call:')
>         begin_time = datetime.datetime.now()
>         balances = waves_exchange.fetchBalance()
>         print(datetime.datetime.now() - begin_time)
> 
> if __name__ == '__main__':
>     main()
> ```

Thanks so much for your timely help! :+1:
