### ISSUE TITLE
Stop price would trigger immediately

### ISSUE THREAD

**Issue by dadouz** [ccxt/ccxt#8194]
Hi CCTX Team,

I m getting all the time following error: {"code":-2010,"msg":"Stop price would trigger immediately."}
Failed to create order with binance  ||  OrderImmediatelyFillable  ||  binance Stop price would trigger immediately. 

Yesterday in the evening with the same code, I was able to create the orders.

        await exchange.load_markets()  # force-preload markets first

        exchange.verbose = True  # this is for debugging

        symbol = 'XRPDOWN/USDT'
        ticker = await exchange.fetch_ticker(symbol)
        print('Last price:', '{:f}'.format(ticker['last']))
        tp = 'stop_loss_limit' #type = 'STOP_LOSS_LIMIT'
        side = 'buy'
        amount = 100  # your amount
        price = 0.584  # your limit price
        # overrides
        params = {
            'stopPrice': 0.585,  # your stop price
            'timeInForce': 'GTC'
        }
        try:
            order = await exchange.create_order(symbol, tp, side, amount, price, params)
        except Exception as e:
            print('Failed to create order with', exchange.id, ' || ', type(e).__name__, ' || ', str(e))

Output:
Last price: 0.606000

Request: POST https://api.binance.com/api/v3/order {'X-MBX-APIKEY': 'blablabla', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate'} timestamp=1609575538699&recvWindow=5000&symbol=XRPDOWNUSDT&type=STOP_LOSS_LIMIT&side=BUY&newOrderRespType=RESULT&quantity=100&price=0.584&timeInForce=GTC&stopPrice=0.585&signature=blablabla

Response: POST https://api.binance.com/api/v3/order 400 <CIMultiDictProxy('Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '60', 'Connection': 'keep-alive', 'Date': 'Sat, 02 Jan 2021 08:18:59 GMT', 'Server': 'nginx', 'x-mbx-uuid': '8f5caf00-39b9-456e-abc3-51d2ff9591ba', 'x-mbx-used-weight': '9', 'x-mbx-used-weight-1m': '9', 'x-mbx-order-count-10s': '1', 'x-mbx-order-count-1d': '42', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 abc3ecd1d98ae9cd426d47386509de19.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'AMS50-C1', 'X-Amz-Cf-Id': 'blablabla==')> {"code":-2010,"msg":"Stop price would trigger immediately."}

Thanks in advance for your help.

**Comment by kroitor** [comment]
Hi!

This was answered here:

- https://dev.binance.vision/t/order-would-trigger-immediately-error/245
- https://github.com/ccxt/ccxt/issues/7239#issuecomment-655466312
- https://github.com/ccxt/ccxt/issues/3097
- https://github.com/ccxt/ccxt/issues?q=Stop+price+would+trigger+immediately.

Hope that answers the question, let us know if not.

**Comment by DrakoAI** [comment]
Sometimes my bot generates the orders well and sometimes I get the error:
`binance.exceptions.BinanceAPIException: APIError(code=-2021): Order would immediately trigger.`
I already checked my parameters over and over again and I can't find the error. I am generating the TAKE_PROFIT_MARKET order with .002 percent and the STOP_MARKET order with .96 percent.
Any suggestions on what might be going on, please?

**Comment by julioflima** [comment]
> Sometimes my bot generates the orders well and sometimes I get the error:
> 
> `binance.exceptions.BinanceAPIException: APIError(code=-2021): Order would immediately trigger.`
> 
> I already checked my parameters over and over again and I can't find the error. I am generating the MARKET order of 1 SOLUSDT with a TAKE_PROFIT_MARKET order with .002 percent and the STOP_MARKET order with .96 percent. Any suggestions on what might be going on, please?

Same here.

**Comment by Wes-Thomas-1995** [comment]
> 

I get the same error - is there a reason for this?

**Comment by entwwwicklung** [comment]
same thing

**Comment by kookic** [comment]
freqtrade 2022.11  env
same
