### ISSUE TITLE
[btcmarkets] withdrawal amount needs fee adding to it

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#8196]

**Comment by kroitor** [comment]
It contradicts your previous PR though: https://github.com/ccxt/ccxt/pull/7948
How do you suggest to resolve it?

**Comment by npomfret** [comment]
I know - maybe their end changed?  Look at this

```
{
  "id": "525706512",
  "fee": {
    "cost": 0.001,
    "currency": "ETH"
  },
  "info": {
    "id": "525706512",
    "fee": "0.001",
    "type": "Withdraw",
    "amount": "0.1",
    "status": "Complete",
    "assetName": "ETH",
    "lastUpdate": "2017-08-09T08:52:06.298000Z",
    "description": "ETH withdraw from [sss] to Address: ccc amount: 0.10000000 fee: 0.00000000",
    "creationTime": "2017-08-09T08:49:13.920000Z",
    "paymentDetail": {
      "txId": "ccc",
      "address": "ccc"
    }
  },
  "txid": "ccc",
  "type": "withdrawal",
  "amount": 0.099,
  "status": "ok",
  "_source": "rest api",
  "address": "ccc",
  "updated": 1502268726298,
  "currency": "ETH",
  "datetime": "2017-08-09T08:49:13.920Z",
  "addressTo": "ccc",
  "timestamp": 1502268553920
}
```

**Comment by npomfret** [comment]
Also, did we alter the meaning of the net/gross amounts for withdrawals.  I certainly use to the the balanced changes by the amount, but now almost all implementations has the balance change by the amount + fee.

**Comment by npomfret** [comment]
ok, this this was a withdrawal from btcmarkets and the corresponding desposit on Coinbase

```
{
  "id": "6500322438",
  "fee": "0.0003",
  "type": "Withdraw",
  "amount": "0.35",
  "status": "Complete",
  "assetName": "BTC",
  "lastUpdate": "2020-09-05T14:47:02.965000Z",
  "description": "BTC withdraw from [ddd] to Address: ddd amount: 0.35",
  "creationTime": "2020-09-05T14:46:16.200000Z",
  "paymentDetail": {
    "txId": "1e6b6be93f035a3b17729431de97e6cd7892032c8324754fcc29dbc69580f0d8",
    "address": "ddd"
  }
}
```

```
{
  "id": "f7d14f79-d983-524b-ace4-74146b59255a",
  "from": {
    "currency": "BTC",
    "resource": "bitcoin_network"
  },
  "type": "send",
  "amount": {
    "amount": "0.34970000",
    "currency": "BTC"
  },
  "status": "completed",
  "details": {
    "title": "Received Bitcoin",
    "header": "Received 0.3497 BTC (£2,713.29)",
    "health": "positive",
    "subtitle": "From Bitcoin address"
  },
  "network": {
    "hash": "1e6b6be93f035a3b17729431de97e6cd7892032c8324754fcc29dbc69580f0d8",
    "status": "confirmed",
    "transaction_url": "https://blockchain.info/tx/1e6b6be93f035a3b17729431de97e6cd7892032c8324754fcc29dbc69580f0d8",
    "status_description": null
  },
  "resource": "transaction",
  "created_at": "2020-09-05T14:47:07Z",
  "updated_at": "2020-09-05T15:00:25Z",
  "description": null,
  "native_amount": {
    "amount": "2713.29",
    "currency": "GBP"
  },
  "resource_path": "/v2/accounts/ddd",
  "instant_exchange": false
}
```

@kroitor my btcmarkets balance change was 0.35, the fee was 0.0003, and the receiver got 0.3497.  What is the correct code?

**Comment by kroitor** [comment]
@npomfret i'd say, we should decide whether the fee should be included into withdrawals or not. I'd rather have the net amount instead of the gross amount in transactions. So, the current code indeed looks correct for btcmarkets. It may be wrong for other exchanges, though. Assuming that the current code works, should we close this issue then?

**Comment by npomfret** [comment]
So the 'amount' should be the amount that is received, and the balance should reduce by the amount + fee?

**Comment by kroitor** [comment]
@npomfret first we need to investigate what is the default with the majority of the exchanges and then decide whether it should be a gross amount or a net amount (that will allow us to answer whether the balance should be reduced by amount or by amount + fee).

**Comment by kroitor** [comment]
With btcmarkets the exchange returns a gross amount (and this is often the case with the rest of the exchanges i think), so it's mostly a gross amount across the exchanges and then the balance should be reduced by `amount`.
We will test and write out all exchanges to draw a final decision on this aspect. Closing this for now, feel free to reopen it or just ask further questions if any.
