### ISSUE TITLE
ошибка в binance.php

### ISSUE THREAD

**Issue by manzor29** [ccxt/ccxt#820]
Судя по всему, имеется ошибка в библиотеке **ccxt/php/binance.php**.
В методе `fetch_my_trades` отсутствует команда `$this->load_markets();` перед выражением `$market = $this->market ($symbol);`, что при попытке получить список сделок пользователя биржи Binance приводит к ошибке `Illegal string offset 'id'`.
Полагаю, что такая же ошибка будет возникать при вызове метода `cancel_order`.

**Comment by kroitor** [comment]
@manzor29 благодарим за feedback! Исправим в самое ближайшее время.

**Comment by kroitor** [comment]
Эта проблема решена в версии 1.10.350. Ещё раз спасибо за помощь!
