### ISSUE TITLE
How to catch errors without the whole application to crash each time

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#8200]
OS: Windows Server 2019 Datacenter
Programming Language version: Node.js 15.3.0
CCXT version: 1.38.89
Exchange: All Exchanges
Method: await exchange.fetchTickers();

Hello!

I am using the below code to: ``exchange.fetchTickers();``. The code works good. I am using a ``watcher.on`` which reacts on when a file is created. Then running the code ``fetchTickers`` for all exchanges that supports: ``fetchTickers()``.

However probably on average, every 5-10 minutes or after 20 times this process runs. I get an error which terminates the whole Node.js application which I don't want to.

The error occurs and I am trying to catch the error to prevent the application to crash here:
``catch((error) => { console.error(error); });``

I have also tried the commented "try and catch{]" around the ``let tickerProcessing`` as seen in the code. But the application still crashes. I am not sure how to prevent this and had bad luck to reproduce the problem with other simple code not related to ccxt so I could ask this in a javascript forum. 

So I try my luck here and perheps also if we should handle those errors correctly somehow?
Below are some of the errors that are occuring.

![image](https://user-images.githubusercontent.com/47510843/103469917-74b83200-4d6b-11eb-940f-af440f7552d2.png)

```'use strict';
const ccxt = require('ccxt');
const fs = require('fs');
const path = require('path');
var chokidar = require('chokidar');
var watcher = chokidar.watch('C:/myproject/temp/tickers', { ignored: /^\./, persistent: true });
var i;

//Cache some memories first
var exchangesArray = [];
var exchangesNameArray = [];
(async () => {
    const allexchanges = ccxt.exchanges.filter((id) => !['coinmarketcap', 'theocean', 'digifinex', 'xbtce', 'btcturk', 'coingi', 'ripio',
        'dsx', 'tidex', 'yobit', 'eterbase', 'rightbtc', 'exmo', 'zb', 'huobipro'].includes(id))
        .map(async (id) => {
            const Exchange = ccxt[id];
            const exchange = new Exchange({ enableRateLimit: true, 'timeout': 240000 });

            if (exchange.has['fetchTickers']) {

                exchangesArray.push(exchange);
                exchangesNameArray.push(id);
            }
        });

    await Promise.all(allexchanges);
})();



//Cached Memories
const exchanges = exchangesArray; //Holds exchange object
const exchangesnames = exchangesNameArray; //Holds exchange name

//*************************************************************************************************************************************************************************************
//FETCH ALL TICKERS
//*************************************************************************************************************************************************************************************
//File Watcher
watcher.on('add', function (path2) {

    //Use cached memories to do the "fetchTickers()" as fast as possible
    var exchangesToLogArray = fs.readFileSync('C:/myproject/temp/tradingexchanges.txt', 'utf8').toString().split('\n').toString().trim();
    if (path2.includes("gettickers")) {

        var i;
        (async () => {
            console.log(`start`);
            const start = Date.now();


            //Use cached memories to do the "fetchTickers()" as fast as possible
            var tickersPromises = []
            for (i = 0; i < exchanges.length; i++) { //Only log choose exchanges


                // pop one exchange from the array
                if (exchangesToLogArray.includes(exchangesnames[i])) {
                    console.log(exchangesnames[i]);

                    const exchange = exchanges[i]
                    const exchangename = exchangesnames[i]


                    //try {
                    let tickerProcessing = new Promise(async (resolve) => {
                        // probably do a try catch in here
                        const tickers = await exchange.fetchTickers();
                        const dumpFile = path.join('C:/myproject/tickers', `${exchangename}Tickers.txt`);
                        await fs.promises.writeFile(dumpFile, JSON.stringify(tickers));
                        resolve()
                    }).catch((error) => { console.error(error); });

                    tickersPromises.push(tickerProcessing)
                    //} catch (e) { console.error(e.exchange); }

                }
            }

            // wait for all of them to execute or fail
            await Promise.all(tickersPromises)


            const end = Date.now();
            await fs.promises.writeFile('C:/myproject/temp/tickers/readyflag.txt', 'dummy'); //readyflagfile when all tickers has been downloaded!
            console.log(`Tickers in ${(end - start) / 1000} seconds`);
        })();
    }
});```

**Comment by kroitor** [comment]
@jackpotcityco hi! In short, you have to handle exceptions and catch them, however, this is more about how to code in JavaScript rather than how to use CCXT. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch

Please, hold on, we will write out a proper example here.

**Comment by jackpotcityco** [comment]
Thank you for the links. That was very good to read about the exceptions there. It is true, it is more a javascript issue rather than CCXT.  However it is strange as I did try the ``try{} catch{}`` code which I did comment out in my code there but still the application crashed. It looked like in the examples on the links there. But I must miss something anyway which make it crash.

Thank you, I would be very curious to see what I could miss on how properely catch the error without terminating the application.

**Comment by kroitor** [comment]
@jackpotcityco let us know if these examples don't help:

- https://github.com/ccxt/ccxt/tree/master/examples/js/fetch-all-tickers-to-files-2.js
- https://github.com/ccxt/ccxt/tree/master/examples/js/fetch-all-tickers-to-files.js

**Comment by jackpotcityco** [comment]
kroitor,

Thank you very much for those examples. They did help out. I thought about the below line as an alternative in case any request did not succeed if still wanting all the other requests:

`        // wait until as many, hopefully all promises succeeded
        try { await Promise.allSettled(promises); } catch (error) { }`
