### ISSUE TITLE
ccxt.pro:  "this.watch is not a function"

### ISSUE THREAD

**Issue by wunderb1t358** [ccxt/ccxt#8209]
Any of watch* methods of ccxt.pro returns` "TypeError: this.watch is not a function"`.
Installation method via package.json: 
`"ccxt.pro": "git+https://xxxxxxxxxxxx:x-oauth-basic@github.com/kroitor/ccxt.pro.git"`

- OS: DEBIAN stretch (Docker)
- Programming Language version: NodeJS (v13.12.0)
- CCXT version: CCXT Pro version 0.5.20

CODE_TO_REPRODUCE:
```
const ccxtpro = require ('ccxt.pro');
async function monitor() {
    const exchange = new ccxtpro.binance({
        enableRateLimit: true
    });

    console.log ('CCXT Pro version', ccxtpro.version);

    let res = await exchange.watchOrderBook ('BNB/USDT', 5);

    console.log(res);
}

monitor(); // TypeError: this.watch is not a function
```

**Comment by kroitor** [comment]
@wunderb1t358 does it work for you if you install it using the `npm install` command as described here:

- https://github.com/ccxt/ccxt/wiki/ccxt.pro.install#javascript

?

**Comment by kroitor** [comment]
Please, paste your output:

```JavaScript
const ccxtpro = require ('ccxt.pro');
console.log ('CCXT Pro version:', ccxtpro.version);
```

**Comment by wunderb1t358** [comment]
> @wunderb1t358 that snippet works for me, so it must be an install issue.
> 
> 1. Have you launched `npm install` after editing your `package.json` ?
> 2. Does it work for you if you install it using the `npm install` command as described here:
> 
> * https://github.com/ccxt/ccxt/wiki/ccxt.pro.install#javascript
> 
> ?

Yes, it is impossible without token due to  `Authentication failed for 'https://github.com/kroitor/ccxt.pro.git/'`

**Comment by kroitor** [comment]
@wunderb1t358 

> Yes, it is impossible without token due to Authentication failed for 'https://github.com/kroitor/ccxt.pro.git/'

Have you configured your GitHub authentication in the terminal? `npm` will not install if your authentication fails

I would highly recommend configuring the SSH auth with git/GitHub:

- https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/connecting-to-github-with-ssh

If you configure your git/GitHub auth in the terminal properly, you will be able to install it with `npm` directly.

--------------------------

Alternatively, you can install it indirectly by cloning the repo and installing from it, in your project, like so:

```bash
# in your project folder:
git clone https://github.com/kroitor/ccxt.pro.git  # it will ask for your username and password
npm install ./ccxt.pro  # install it from the cloned repository
```

Let me know if that does not help. Feel free to reopen this issue or just ask further questions if any.
