### ISSUE TITLE
Allcoin.com has two more currencies

### ISSUE THREAD

**Issue by bugking** [ccxt/ccxt#821]
'CNET' & 'CK.USD'

I suggest that it's more flexible to introduce a parameter 'currencies' for fetch_market method in https://github.com/ccxt/ccxt/blob/master/python/ccxt/allcoin.py, with default value as ['BTC', 'ETH', 'USD', 'QTUM'] or the latest currencies ['BTC', 'ETH', 'USD', 'QTUM', 'CNET', 'CK.USD']:
1. it's more flexible to support more currencies without updating the code
2. if an user only cares certain types of currencies of one exchange, it's more convenient to avoid loading all currencies markets information.

**Comment by kroitor** [comment]
Hi! We added those by hand as a quickfix. Should be available in ccxt 1.10.352+.
And thanks for the suggestion, btw! However, we think it might be even better to scrape the data from their web API (https://www.allcoin.com/Home/MarketOverViewDetail/), we will rework the fetchMarkets for allcoin, hopefully, soon, and will keep you updated, of course. We also appreciate all contributions and PRs. Thx!

**Comment by bugking** [comment]
great work! 👍
