### ISSUE TITLE
FTX How to query underlying index price of futures?

### ISSUE THREAD

**Issue by WestXu** [ccxt/ccxt#8212]
FTX uses a constituent index to back a future, as well as many other exchanges. It's accessible through offical API of FTX (see https://docs.ftx.com/#get-future for the index return). But how to access that data via ccxt?

**Comment by kroitor** [comment]
You can call any API endpoints with CCXT using the implicit API methods as described in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

```Python
import ccxt
from pprint import pprint

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.ftx({
    'enableRateLimit': True
})

response = exchange.public_get_futures()
pprint(response)
```

Let us know if that does not answer your question.
