### ISSUE TITLE
FTX watchOrders returns  "Only have permissions for subaccount test"

### ISSUE THREAD

**Issue by wunderb1t358** [ccxt/ccxt#8215]
`await exchange.watchOrders();` returns ExchangeError ` Only have permissions for subaccount test`
For example `await exchange.watchTrades('BTC/USD');` works without error. 

- OS:  DEBIAN stretch (Docker)
- Programming Language version: NodeJS (v13.12.0)
- CCXT version:  Pro version 0.5.20

**Code to reproduce:**
```
const ccxt = require('ccxt.pro');
async function monitor() {
    const exchange = new ccxt.ftx ({
        enableRateLimit: true,
        apiKey: 'API_KEY',
        secret: 'SECRET_KEY',
        headers: { 'FTX-SUBACCOUNT': 'test' }
    });
    
    // real-time mode
    const limit = 5; // optional
    while (true) {
        try {
            const orders = await exchange.watchOrders();
            console.log (orders) // every update
        } catch (e) {
            console.log (e);
            throw e // uncomment to stop the loop on exceptions
        }
    }
}

monitor(); // ExchangeError: Only have permissions for subaccount test

**Comment by kroitor** [comment]
@wunderb1t358 the FTX subaccounts are supported in CCXT, but not in CCXT Pro yet, we're working on a fix, will upload it asap and will let you know immediately.

**Comment by wunderb1t358** [comment]
> @wunderb1t358 the FTX subaccounts are supported in CCXT, but not in CCXT Pro yet, we're working on a fix, will upload it asap and will let you know immediately.

Thank you! As FTX is very popular it is critically important for us.

**Comment by wunderb1t358** [comment]
I am very apologize, is there any update?

**Comment by kroitor** [comment]
@wunderb1t358 pardon for the long wait, this is fixed in CCXT Pro 0.5.44+. Thank you for reporting!

**Comment by coding-for-money** [comment]
我也碰到了 ，需要传母账号的key,secret,和子账号的名字

**Comment by kroitor** [comment]
@wunderb1t358 check the answers in these issues:

- https://github.com/ccxt/ccxt/search?q=ftx+subaccount
- https://github.com/ccxt/ccxt/issues/10794
- https://github.com/ccxt/ccxt/issues/9805

**Comment by ttodua** [comment]
Update: from now, you can now directly add the parameter in any method (without need to set the headers in exchange initialization properties), like:

`createOrder/FerchBalance( ..., ...,  params:{ "FTX-SUBACCOUNT":"mySubAcc"} ) `   

Note: `FTXUS-SUBACCOUNT` for ftx.us users.
