### ISSUE TITLE
[yobit] post bch fork mapping

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#8217]
Am i right in thinking that BCHN is the dominant BCH currency and is the one that is now referred to as BCH in ccxt?

```
{
  limits: {
    amount: { min: 0.0001, max: undefined },
    price: { min: 1e-8, max: 10000 },
    cost: { min: 0.1, max: undefined }
  },
  precision: { amount: 8, price: 8 },
  tierBased: undefined,
  percentage: undefined,
  taker: 0.002,
  maker: 0.002,
  id: 'bchabc_usd',
  symbol: 'BCH/USD',
  base: 'BCH',
  quote: 'USD',
  baseId: 'bchabc',
  quoteId: 'usd',
  active: true,
  info: {
    decimal_places: 8,
    min_price: 1e-8,
    max_price: 10000,
    min_amount: 0.0001,
    min_total: 0.1,
    hidden: 0,
    fee: 0.2,
    fee_buyer: 0.2,
    fee_seller: 0.2
  }
}
{
  limits: {
    amount: { min: 0.0001, max: undefined },
    price: { min: 1e-8, max: 10000 },
    cost: { min: 0.0001, max: undefined }
  },
  precision: { amount: 8, price: 8 },
  tierBased: undefined,
  percentage: undefined,
  taker: 0.002,
  maker: 0.002,
  id: 'bchabc_usdt',
  symbol: 'BCH/USDT',
  base: 'BCH',
  quote: 'USDT',
  baseId: 'bchabc',
  quoteId: 'usdt',
  active: true,
  info: {
    decimal_places: 8,
    min_price: 1e-8,
    max_price: 10000,
    min_amount: 0.0001,
    min_total: 0.0001,
    hidden: 0,
    fee: 0.2,
    fee_buyer: 0.2,
    fee_seller: 0.2
  }
}
{
  limits: {
    amount: { min: 0.0001, max: undefined },
    price: { min: 1e-8, max: 10000 },
    cost: { min: 0.1, max: undefined }
  },
  precision: { amount: 8, price: 8 },
  tierBased: undefined,
  percentage: undefined,
  taker: 0.002,
  maker: 0.002,
  id: 'bchn_usd',
  symbol: 'BCHN/USD',
  base: 'BCHN',
  quote: 'USD',
  baseId: 'bchn',
  quoteId: 'usd',
  active: true,
  info: {
    decimal_places: 8,
    min_price: 1e-8,
    max_price: 10000,
    min_amount: 0.0001,
    min_total: 0.1,
    hidden: 0,
    fee: 0.2,
    fee_buyer: 0.2,
    fee_seller: 0.2
  }
}

```

**Comment by kroitor** [comment]
@npomfret CCXT currently uses BCH ABC for the BCH, and BSV for BCH SV. Do we need to change that?

**Comment by npomfret** [comment]
UGH, I hate this stupid currency.

According to CMC...

BCHABC (https://coinmarketcap.com/currencies/bitcoin-cash-abc-2/) started in November 2020 and it's price is around 15USD.

The major BCH fork, I think, is sometimes called BCHN (or BCH node) https://coinmarketcap.com/currencies/bitcoin-cash/ and it's price is around 450USD.

I think maybe we need to use the tickers for each exchange to figure out which ones they support.

**Comment by npomfret** [comment]
@kroitor are you able to help with this issue soon?  would really appreciate it

**Comment by kroitor** [comment]
@npomfret yep, will do my best to get it fixed in a day or two

**Comment by ANNITA-WORLD-2020** [comment]
![FB_IMG_16094672007028349](https://user-images.githubusercontent.com/77267161/104347662-77691300-5533-11eb-8bbd-06c48c48770e.jpg)
![FB_IMG_16094672391603387](https://user-images.githubusercontent.com/77267161/104347707-82bc3e80-5533-11eb-9f3b-563b351b7134.jpg)
![FB_IMG_16094672535866165](https://user-images.githubusercontent.com/77267161/104347714-84860200-5533-11eb-9bb1-37393359f45a.jpg)
![FB_IMG_16094672214284695](https://user-images.githubusercontent.com/77267161/104347717-851e9880-5533-11eb-9a7a-4c91ae714abf.jpg)
![FB_IMG_16094672643153766](https://user-images.githubusercontent.com/77267161/104347720-85b72f00-5533-11eb-9775-7311192b9ea1.jpg)
![FB_IMG_16094671963304481](https://user-images.githubusercontent.com/77267161/104347725-8780f280-5533-11eb-9b43-043162a39218.jpg)
![FB_IMG_16094672489231586](https://user-images.githubusercontent.com/77267161/104347729-88b21f80-5533-11eb-9d82-387c4c96c5e9.jpg)
![FB_IMG_16094671916377685](https://user-images.githubusercontent.com/77267161/104347734-894ab600-5533-11eb-9268-9b46cebfa276.jpg)
![FB_IMG_16094672439017356](https://user-images.githubusercontent.com/77267161/104347738-8a7be300-5533-11eb-8d75-478e3a01dad6.jpg)
![FB_IMG_16094671866167127](https://user-images.githubusercontent.com/77267161/104347741-8b147980-5533-11eb-8dc1-a0ca8fd27275.jpg)
![Uploading FB_IMG_16094083624669840.jpg…]()

**Comment by ANNITA-WORLD-2020** [comment]
![FB_IMG_16094671820992229](https://user-images.githubusercontent.com/77267161/104347754-8f409700-5533-11eb-8d24-8b09a24d18d2.jpg)
![Uploading FB_IMG_16094671728259292.jpg…]()

**Comment by ANNITA-WORLD-2020** [comment]
![FB_IMG_16094671336275420](https://user-images.githubusercontent.com/77267161/104347772-936cb480-5533-11eb-8d4b-93758a3b3156.jpg)
Ths
![Uploading FB_IMG_16094671408333759.jpg…
![FB_IMG_16094672007028349](https://user-images.githubusercontent.com/77267161/104347781-95367800-5533-11eb-98fc-bf8b0b0cd4b5.jpg)
![FB_IMG_16094672332403462](https://user-images.githubusercontent.com/77267161/104347785-9667a500-5533-11eb-832e-277ff1c556f8.jpg).  


Www.facebook.com/Anytar1987. 

Thank you verry much

**Comment by npomfret** [comment]
Any chance we could sort this BCHN problem out soon?  I think bitfinex has the same issue.

**Comment by kroitor** [comment]
@npomfret yes, i'll get to it within a few hours and will post back here.

**Comment by m2m4m6m8m10** [comment]
can you please give me the link of trading bot that you are using in yobit exchange platform

**Comment by ttodua** [comment]
Yobit is no longer part of CCXT. Closing this issue for now.

**Comment by ttodua** [comment]
sorry, i accidentally confused yobit with another exchange and marked it incorrectly closed. re-opening the issue.
