### ISSUE TITLE
Stop releasing so many release.

### ISSUE THREAD

**Issue by Gr1dd** [ccxt/ccxt#822]
Stop releasing so many release.

**Comment by Swoorup** [comment]
Not their fault. Its a community project, I assume maintaining this library requires a lot of effort cause they require to maintain compatibility with the upstream api.

**Comment by kroitor** [comment]
@Gr1dd we're releasing a new patch version if an edit introduces a significant change (like a fix or a new method), or new APIs... you will have to pay us if you want us to stop )) just kidding...
Do you have any difficulty skipping them if you don't want them so often? I didn't quite get the request. People usually demand the opposite. If there's a reason why we shouldn't upload so often, let us know.
