### ISSUE TITLE
ftx place advanced order

### ISSUE THREAD

**Issue by linklee** [ccxt/ccxt#8220]
os: ubuntu
python
How can one place advanced order on ftx ?
Something like this:
https://prnt.sc/wico77

**Comment by linklee** [comment]
@kroitor  any updates on this?:)

**Comment by diwenshi61** [comment]
I believe what you're looking for are trigger orders. These have a different endpoint than regular orders and the implicit method is private_post_conditional_orders (or privatePostConditionalOrders). I believe that these order types are not standardized in CCXT yet but may be in the future.
The exact parameters that you need to send are documented in FTX API docs [here](https://docs.ftx.com/#place-trigger-order).
Example:
```
ftx = ccxt.ftx()
ftx.private_post_conditional_orders({"market": "XRP-PERP", "side": "sell", "triggerPrice": 0.306525, "size": 31431.0, "type": "stop", "reduceOnly": False})

```

**Comment by kroitor** [comment]
CCXT unifies conditional orders with `create_order` in the recent versions, and it will fill the values depending on the order `type`, like `stop` or `takeProfit` or `trailingStop`.

Let us know if this example does not answer your question:

- https://github.com/ccxt/ccxt/blob/master/examples/py/ftx-conditional-orders.py
