### ISSUE TITLE
Manually stop watch* socket

### ISSUE THREAD

**Issue by wunderb1t358** [ccxt/ccxt#8225]
Is it possible to manually stop watch* socket connection if it is not needed anymore? 

- OS: DEBIAN stretch (Docker)
- Programming Language version: NodeJS (v13.12.0)
- CCXT version: Pro version 0.5.20

```
while (true) {
    try { 
       // HOW TO STOP CONNECTION?
        const orders = await exchange.watchOrders();
        console.log (orders) // every update

    } catch (e) {
        console.log (e);
        // throw e // uncomment to stop the loop on exceptions
    }
}
```

**Comment by kroitor** [comment]
Hi! At this time we don't have the `unwatch*` methods unified yet, so the only way to drop it is to `await exchange.close()` and re-create the exchange-instance. We will add the corresponding unwatch-methods very soon to unsubscribe from the existing streams. However, not all exchanges will support that functionality, due the limitations on their side.

**Comment by kroitor** [comment]
Let us know if the above does not answer your question. Feel free to reopen it or just ask further questions if any. We will announce the arrival of `unwatch` methods here on GitHub.

**Comment by hajdbo** [comment]
I wish ccxt.pro had this. For my use case, it's very slow to close/re-create the instance.
