### ISSUE TITLE
How watch* connection will be reused for private API?

### ISSUE THREAD

**Issue by wunderb1t358** [ccxt/ccxt#8226]
Do I correctly understand that connection for `watchOrders` will be reused for the same private API if exists? 

- OS: DEBIAN stretch (Docker)
- Programming Language version: NodeJS (v13.12.0)
- CCXT version: Pro version 0.5.20

```
const exchange = new ccxt.binance({
    enableRateLimit: true,
    apiKey: 'apiKey',
    secret: 'secretKey'
});

for (let i = 0; i <= 1; i++) {
    while (true) {
        try {
            // Will be open only one socket connection?
            const orders = await exchange.watchOrders();

        } catch (e) {
            throw e;
        }
    }
}
```

**Comment by kroitor** [comment]
> Do I correctly understand that connection for watchOrders will be reused for the same private API if exists?

Yes, that is correct, the library will reuse the same connection if it already exists. In general, there's often just one connection per exchange. Sometimes, the exchange might require two connections: one for all public feeds, and another one for the private feeds.

Let us know if that does not help.
