### ISSUE TITLE
Callback on watch* connection interruption

### ISSUE THREAD

**Issue by wunderb1t358** [ccxt/ccxt#8227]
How to set callback on `watch*` connection interruption? 
Is it enough to use `try/catch` like in example code below?

- OS: DEBIAN stretch (Docker)
- Programming Language version: NodeJS (v13.12.0)
- CCXT version: Pro version 0.5.20

```
const exchange = new ccxt.binance({
  enableRateLimit: true,
  apiKey: "apiKey",
  secret: "secretKey"
});

while (true) {
  try {
      // Connection is interrupted
      const orders = await exchange.watchOrders();
  
  } catch (e) {
      // Do business logic in connection interruption case ...
      // On next iteration connection probably  will be restored ...
  }
}
```

**Comment by kroitor** [comment]
@wunderb1t358 yes, that is the correct code to handle it and it should be enough. Please, let us know if you have difficulties with that.
