### ISSUE TITLE
Huobipro: orderbook frozen with watch_order_book

### ISSUE THREAD

**Issue by Ricardus312** [ccxt/ccxt#8232]
- OS: Windows 10
- Programming Language version: Python 3.8.5
- CCXT version: 1.40.26
- CCXT.pro version: 0.5.24

This snippet of code will raise after a while because the orderbook is not anymore updated and gets frozen forever. It happens only on huobipro and has been reproduced on many symbols many times. It has been checked by manually opening the exchange in the browser that the API is not reflecting the prices showed in the browser. My program runs many exchanges simultaneously and this only happens with huobipro.

I was using the public API and tried to use an API key and it keeps happening.

```
import ccxtpro
import asyncio
import traceback

print('CCXT Pro Version:', ccxtpro.__version__)


counter_delta = 0
prev_update = ()


def check_delta(orderbook):
    
    global counter_delta, prev_update
    
    update = orderbook['bids'][0], orderbook['asks'][0]
    
    if update==prev_update:
        print(update)
        counter_delta += 1
    else: counter_delta = 0
    
    prev_update = update
    
    if counter_delta>=1000: raise Exception('Book frozen')
    
    

async def main():
    
    exchange = ccxtpro.huobipro({'enableRateLimit': True})
    await exchange.load_markets()
#    exchange.verbose = True  # uncomment for debugging purposes
    while True:
        try:
            orderbook = await exchange.watch_order_book('ETH/USDT')
            check_delta(orderbook)
        except Exception as e:
            traceback.print_exception(type(e), e, e.__traceback__)
            break
    await exchange.close()
    
    
asyncio.get_event_loop().run_until_complete(main())
```

```

```

**Comment by elitwilliams** [comment]
@Ricardus312 were you able to produce a fix this? I'm running into the same problem - only on huobipro - and ideally I wouldn't have to restart the connection every time it freezes / write a custom integration.
