### ISSUE TITLE
set type of trigger price market or last price 

### ISSUE THREAD

**Issue by linklee** [ccxt/ccxt#8233]
- UBUNTU
- PYTHON

```
order = ccxt_bot.create_order(coin, # market
		'trailingStop', # type
		side, # side
		amount, # amount
		17145.137999999999, # price can be ignored!
		{
		"trailValue": trail_value,
		"retryUntilFilled": True,
		"reduceOnly":True}
		)

```
Right now I use code above for trailing stop order. 
How can I use it to trigger not mark price but last price?
(The exchange i use is ftx if it is revelevant)

**Comment by kroitor** [comment]
Let us know if this does not answer your question:

- https://help.ftx.com/hc/en-us/articles/360031896592-Advanced-Order-Types

> Note that all of the stop order types are triggered by the mark price of the relevant market.  Mark price is the median of bid, ask, and last.
