### ISSUE TITLE
ftx set leverage for order

### ISSUE THREAD

**Issue by linklee** [ccxt/ccxt#8234]
- UBUNTU:
- PYTHON:
- CCXT version:
Version: 1.30.34

```
1. ccxt_bot.create_order(coin, 'limit', 'buy', amount, value, {'leverage': 5})
2.ccxt_bot.private_post_position_leverage({"symbol": coin, "leverage": "5"})
```
I tried the ways above to change leverage
(the first method was suggested [here](https://github.com/ccxt/ccxt/issues/4900)) 
but neither of them work 

How do I change leverage?

**Comment by kroitor** [comment]
With FTX your leverage is set per account (account-wide). You can do that using the implicit API methods as described in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

See this example:

- https://github.com/ccxt/ccxt/blob/master/examples/py/ftx-set-leverage.py

```Python
import ccxt
from pprint import pprint

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.ftx({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET', 
})

# pprint(dir(exchange))  # uncomment to print all available methods

markets = exchange.load_markets()

# exchange.verbose = True  # uncomment for debugging

# see https://docs.ftx.com/#change-account-leverage for more details
response = exchange.private_post_account_leverage({
    'leverage': 10,
})

pprint(response)
```

Let us know if that does not answer your question.
