### ISSUE TITLE
FTX futures entryprice for position not working

### ISSUE THREAD

**Issue by linklee** [ccxt/ccxt#8238]
- UBUNTU:
- PYTHON 3.9
- CCXT version:1.30.34

```
while True:
   positions = ccxt_bot.private_get_positions()['result']
   position = postions[0]
   print(position)
   
```

This gives me different output for my position entryPrice
https://prnt.sc/wk8suj
https://prnt.sc/wk8x90

Hovewer I hold just 1 position:
https://prnt.sc/wk8xvl
https://prnt.sc/wk8y7t

**Comment by linklee** [comment]
UPD: I guess it gives current price instead of entryPrice

**Comment by diwenshi61** [comment]
According to FTX docs (https://docs.ftx.com/#get-positions),

entryPrice: Average cost of this position after pnl was last realized: whenever unrealized pnl gets realized, this field gets set to mark price, unrealizedPnL is set to 0, and realizedPnl changes by the previous value for unrealizedPnl.

So whenever you realize any PnL the entryPrice will change.

**Comment by linklee** [comment]
Thanks for clarification
Sounds weird, this is not obvious and not so user-friendly from ftx...

So, how can one get real entryPrice (or average open price?)
https://prnt.sc/wkcwxm

**Comment by diwenshi61** [comment]
Using the get_positions endpoint you may calculate the original values yourself or keep track of historical entryPrice. You probably want to look at the fills endpoint (https://docs.ftx.com/#fills) as it seems to be more useful for your purposes.

**Comment by linklee** [comment]
how can i call fills endpoint from ccxt ?

**Comment by diwenshi61** [comment]
Should be fetchMyTrades.

**Comment by kroitor** [comment]
@diwenshi61 thank you very much for your involvement! We really appreciate your help!

@linklee let us know if the above answers don't help. Feel free to reopen this issue or just ask further questions if any.

**Comment by belqit** [comment]
entryPrice = entryPrice - (realizedPnl / size)
