### ISSUE TITLE
IP address used for requests

### ISSUE THREAD

**Issue by janeCMD** [ccxt/ccxt#824]
This is more an idea than issue. 

Wondering if it would be possible to mount in the support for overriding IP address used for requests. In CURL, the parameter used for that is CURLOPT_INTERFACE. This would enable to set used IP address or proxy for all API calls, i sometime need it due to harsh restrictions some exchanges have on amount of public requests. I already built my own library for caching requests, but this is not always enough for certain uses. It should be not much work to enable this.

Thanks

**Comment by kroitor** [comment]
@janeCMD can you submit a pr on that?

**Comment by janeCMD** [comment]
Sorry i dont understand what you mean by PR and how to submit that ? You mean pull request ?

**Comment by kroitor** [comment]
@janeCMD yeah, PR = pull request )

**Comment by janeCMD** [comment]
Some guidance please ? I am not very github pro...

**Comment by kroitor** [comment]
@janeCMD : https://help.github.com/articles/creating-a-pull-request/
However, if you're not familiar with it or don't want to do this, don't bother, I'll do it anyways, asap. Let me know if you're going to give it a try.

**Comment by janeCMD** [comment]
@kroitor I don't mind to add it myself, just wondering if this needs to be done in all languages at same time? Also, as far as my knowledge goes, you need to create branch first then can pull it, right ? But i dont see the way how to do it. Never did it before here.

**Comment by kroitor** [comment]
@janeCMD: in terms of github you need to create a fork (it's a branch in itself), add your edits there, then make a pull request from inside it.

> just wondering if this needs to be done in all languages at same time?

We can edit PHP only for now.

**Comment by janeCMD** [comment]
@kroitor Just wandering, is the Exchange class attribute 'proxy' used for something ? Because its already there in constructor, but didnt find its use in the code...

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/wiki/Install#proxy

**Comment by janeCMD** [comment]
Seems like proxy is not used in php and the way its used is different from classic proxies. Anyway, i added IP Override and created pull request. Lines to do the proxy part i commented out. Its for using CURL_PROXY to change IP.

**Comment by janeCMD** [comment]
> https://github.com/ccxt/ccxt/blob/master/php/base/Exchange.php#L682
Overseen the line, its done same way as in JS.
IP Override i added is to be used with other IPs assigned to server
Commented out code is to be used with proxy server like squid, if you buy bunch of private proxies from some provider online. That could also be useful
