### ISSUE TITLE
Kucoin : balance is missing in the standard part of the response

### ISSUE THREAD

**Issue by sebnyc** [ccxt/ccxt#8243]
Hi,

I am a new ccxt user, currently testing it with different exchanges.
While fetching balances from Kucoin, I get a response that includes the "info" part with Kucoin original response, but there is nothing in the standard part of the response.

Is there something I am doing wrong ?

- OS: MacOS
- Programming Language version: PHP
- CCXT version: 1.40.30 (checked with \ccxt\Exchange::VERSION)

My code :
```
        $exchangeCode = "kucoin";
        $exchange_class = "\\ccxt\\$exchangeCode";
        $exchange = new $exchange_class ($credentials);
        $exchange->enableRateLimit = true;
        $exchange->verbose = true;
        $exchange->loadMarkets();
        $response = $exchange->fetchBalance();
```

The response (I didn't paste the whole verbose response because it doesn't seem to me that communication with Kucoin is relevant here, let me know if it is necessary) :
```
{
        "free": [],
        "info": {
            "code": "200000",
            "data": [
                {
                    "available": "0.07664085",
                    "balance": "0.07664085",
                    "currency": "ETH",
                    "holds": "0",
                    "id": "5ffba4400bf6f000060a7dd3",
                    "type": "main"
                }
            ]
        },
        "total": [],
        "used": []
}
```

**Comment by kroitor** [comment]
Hi!

```PHP
        $exchangeCode = "kucoin";
        $exchange_class = "\\ccxt\\$exchangeCode";
        $exchange = new $exchange_class ($credentials);
        $exchange->enableRateLimit = true;
        $exchange->verbose = true;
        $exchange->loadMarkets();
        $response = $exchange->fetchBalance(); // default
        var_dump$(response);
        $response = $exchange->fetchBalance({'type':'trade'}); // default
        var_dump$(response);
        $response = $exchange->fetchBalance({'type':'main'});
        var_dump$(response);
```

Let us know if that does not answer your question.

**Comment by sebnyc** [comment]
Thank you so much for your fast response !

Adding ['type' => 'main'] totally helped and populated the standard part 
of the response with this balance.

Are you considering allowing users to retrieve their total balance 
(including this example of 'main' balance) without having to use 
exchange-specific parameters ?
It looks to me that it could be a useful feature.

Best,
Sebastien

**Comment by kroitor** [comment]
@sebnyc we will consider adding that feature, however, it's not our immediate priority right now since it can be done with a few sequential calls in the userland as well. Will get to it as soon as we can.
