### ISSUE TITLE
Bybit - has no attribute privateGetGetDeposits while calling fetch_deposits

### ISSUE THREAD

**Issue by docek** [ccxt/ccxt#8250]
- OS: Linux on ChromeOS
- Programming Language version: Python 3.8
- CCXT version: 1.40.35

```
import ccxt

e = ccxt.bybit({
    'enableRateLimit': True,
    'testnet': True,
    #'verbose': True
})

e.apiKey = 'xxx'
e.secret = 'xxx'

e.fetch_deposits('BTC')
```

```
Traceback (most recent call last):
  File "/home/tomasmarada/Honeybadger/honeybadger/temp.py", line 97, in <module>
    e.fetch_deposits('BTC')
  File "/opt/minconda3/lib/python3.8/site-packages/ccxt/bybit.py", line 1800, in fetch_deposits
    response = self.privateGetGetDeposits(self.extend(request, params))
AttributeError: 'bybit' object has no attribute 'privateGetGetDeposits'
```

**Comment by kroitor** [comment]
Bybit is broken due to an API update on the exchange side, we're working on a fix:

- https://github.com/ccxt/ccxt/issues?q=bybit+is%3Aopen
- https://github.com/ccxt/ccxt/issues/8150
- https://github.com/ccxt/ccxt/issues/8034
- ...

**Comment by docek** [comment]
@kroitor I would like to reopen this issue, since it persists even in the current release 1.40.44

**Comment by kroitor** [comment]
@docek please paste your full verbose output from this snippet, including the runtime version number

**Comment by docek** [comment]
@kroitor your reaction time and fixing speed are inspirational!

**Comment by kroitor** [comment]
@docek thx for your participation. Had to use the ledger endpoint for it, since they don't have a standalone path for deposits (they do have a withdrawals endpoint though). It should be ok in 1.40.45, tested it on my side. Let me know if you still have issues with it.
