### ISSUE TITLE
[huobi] add the swap api

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#8262]
https://huobiapi.github.io/docs/coin_margined_swap/v1/en/#introduction

**Comment by npomfret** [comment]
https://github.com/ccxt/ccxt/pull/8264

**Comment by kmotLeb** [comment]
> https://huobiapi.github.io/docs/coin_margined_swap/v1/en/#introduction

Gandu

**Comment by limulidae** [comment]
is the PR verified?

**Comment by samgermain** [comment]
Further discussion should be moved to https://github.com/ccxt/ccxt/issues/11606
