### ISSUE TITLE
Getting liquidation price from open positions and open positions for a single market in Binance Futures

### ISSUE THREAD

**Issue by Jacks349** [ccxt/ccxt#8265]
OS: Windows
Programming Language version: Python 3.8
CCXT version: 1.39.14 (latest)

Hello! I am using the latest version of CCXT to test the Binance Futures API. I'm having an hard time figuring out if i can get open positions for a specific market along with the liquidation price for each position.

Here is what i have so far:

```
exchange = ccxt.binance({
    'apiKey': key,
    'secret': secret,
    'enableRateLimit': True,  
    'options': {
        'defaultType': 'future',
    }
})

response = exchange.fetch_balance({})

print(response['info'])
```

This is good, but the response will be open positions for all the markets, instead of a specific one. Another problem is that the response doesn't have the liquidation price for the position. Is it because Binance itself doesn't give that data? Thanks in advance!

**Comment by samgermain** [comment]
# To get all open positions

```
import ccxt
import json
import sys
from pprint import pprint

print('python', sys.version)
print('CCXT Version:', ccxt.__version__)

with open('../keys.local.json', 'r') as config_text:
    config = json.load(config_text)

binance = ccxt.binanceusdm(config['binanceusdm'])
binance.loadMarkets()

positions = binance.fetch_positions([symbol])
pprint(positions)
```

---------------

# To get the liquidation price for an open position

```
import ccxt
import json
import sys

print('python', sys.version)
print('CCXT Version:', ccxt.__version__)

binance = ccxt.binanceusdm({
    'apiKey': '...',
    'secret': '...',
})
binance.loadMarkets()
symbol = 'XRP/USDT'

positions = binance.fetch_positions([symbol])

if len(positions) > 0:
    pos = positions[0]
    liquidation_price = pos['liquidationPrice']
    print(liquidation_price)
else:
    print(f'No open positions for {symbol}')
```

-----------------------

Feel free to open the issue again if you have any more questions
