### ISSUE TITLE
A lot of slippage on market orders without stoploss and take profit params

### ISSUE THREAD

**Issue by adamrg73** [ccxt/ccxt#8276]
I have a question... im noticing a lot of slippage with my market orders not using stoploss or take profit params. Im just checking the percentage of price vs my entry price, and executing at certain percentage.  Will stop loss and take profit help with slippage to get the exact price I want to execute?

currently Im refreshing every second and executing a market order when percentage hits my targets.
Im using ccxt with phemex.

Thanks

**Comment by kroitor** [comment]
> I have a question... im noticing a lot of slippage with my market orders not using stoploss or take profit params. Im just checking the percentage of price vs my entry price, and executing at certain percentage.

This is very common thing across exchanges and markets, and it is pretty much expected, especially at times of high volatility like we saw recently and still seeing it now. 

> Im just checking the percentage of price vs my entry price, and executing at certain percentage. Will stop loss and take profit help with slippage to get the exact price I want to execute?

No. The key here is the fact that you want **the exact price**. That's a standard limit order, not a market order. An additional postOnly flag for your limit order will help ensure the exact price. 

Also, your slippage depends on how exactly you calculate the volume-weighed prices to derive the amount of your market order. How do you calculate it? Which formulas do you use? How does that code look like? Without the info, we can only guess, so, please share the details. Cause you can't just use the best bid/best ask price for your calculations, you have to be pedantic and calculate it based on market depth with respect to the existing volumes in the orderbook. That still won't guarantee you from slippage though, but may rule out other bugs.

> currently Im refreshing every second and executing a market order when percentage hits my targets.
Im using ccxt with phemex.

A derivatives exchange like Phemex or any other exchange usually processes a very large number of orders, the number of orders placed and canceled in 24h can count in hundreds of thousands or millions, that means the orderbook will change rather frequently, say, a million times over 24 hour = 12 times per second.
