### ISSUE TITLE
Decoding the alphanumeric secret key

### ISSUE THREAD

**Issue by nazariyv** [ccxt/ccxt#828]
Hi,

This is a question. I have checked out the first two pages of the closed issues labelled "question" and was not able to find something relating to this. I might not have searched too well, though.

Here is my question. I was reading the GDAX API Authentication documentation and noticed the following note: `Remember to first base64-decode the alphanumeric secret string (resulting in 64 bytes) before using it as the key for HMAC. `. An example that they show is like this:
```
hmac_key = base64.b64decode(self.secret_key)
signature = hmac.new(hmac_key, message, hashlib.sha256)
```

I then went on to the base exchange class in ccxt. And noticed that an encoded version of a secret is used:
```
@staticmethod
 def hmac(request, secret, algorithm=hashlib.sha256, digest='hex'):
        h = hmac.new(secret, request, algorithm)
```

where this method is called from here:
```
@staticmethod
def jwt(request, secret, algorithm=hashlib.sha256, alg='HS256'):
        header = Exchange.encode(Exchange.json({
            'alg': alg,
            'typ': 'JWT',
        }))
        encodedHeader = Exchange.base64urlencode(header)
        encodedData = Exchange.base64urlencode(Exchange.encode(Exchange.json(request)))
        token = encodedHeader + '.' + encodedData
        hmac = Exchange.hmac(Exchange.encode(token), Exchange.encode(secret), algorithm, 'binary')
```
where `Exchange.encode(secret)` is a "utf-8" encoded string. i.e. it is not base64 decoded as per comments in the GDAX API documentation. I am a bit paranoid about security and would like to confirm what is going on here.

Thanks! :)

**Comment by kroitor** [comment]
>  I am a bit paranoid about security and would like to confirm what is going on here.

Base64 is not secure. It is an encoding, not an encryption algorithm. So it's easily decoded. You can do it manually online if you google for `base64 decode`. Don't be a paranoid, be informed and confident.

> where Exchange.encode(secret) is a "utf-8" encoded string
You're looking at JWT implementation which is only used in Quoine/Qryptos. GDAX does not use Json Web Tokens for authentication, their sign method is in `gdax.js`.

Let me know if it answers your questions or not.

**Comment by nazariyv** [comment]
It does, thanks. How does it go from the python code to js then? I can see, for example, in one of the trading examples you use exchange.fetch_balance(), so if I go to gdax.py to .fetch_balance() method it uses .privateGetAccounts() method on the self, where self has exchange super class and yet I cannot find the method neither in exchange.py nor in gdax.py.

**Comment by kroitor** [comment]
Oh, those are created atuomatically from the endpoints list in the constructor (`define_rest_api()`), explained here:
- https://github.com/ccxt/ccxt/issues/237
- https://github.com/ccxt/ccxt/wiki/Manual#api-methods--endpoints

**Comment by nazariyv** [comment]
Oh yes! I was reading about it. Thanks for reminding. 

How does this python code get access to signing processes in gdax.js? Because I can only see .py files in my ccxt python library (I installed through pip install).

**Comment by kroitor** [comment]
@nazariyv JS files get converted to Py (and JS, and Typescript, ...) upon each build. More about it here: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

**Comment by nazariyv** [comment]
Got it thanks :)

**Comment by kroitor** [comment]
@nazariyv do you mind if I close this for now?

**Comment by nazariyv** [comment]
I don't. go ahead. Thanks for the help.

**Comment by kroitor** [comment]
P.S. If you compare Python code to JS code / PHP code, you'll immediately notice, that it is mapped one-to-one... same syntax ) Did you know that you can code in 4 languages at once? )

**Comment by nazariyv** [comment]
I have noticed it :) I can put down 4 additional languages in my CV now. What is the missing one: Python, JS, PHP, ...?)

**Comment by kroitor** [comment]
Typescript ;) We will add more )
