### ISSUE TITLE
Perpetual swap contracts implementation on some exchanges. 

### ISSUE THREAD

**Issue by Cleric334** [ccxt/ccxt#8280]
Hello

Does ccxt support perpetual swap contracts on all of the exchanges they are present at, or just some?

Such exchanges as Bitmart, Bit-z, Bitget have perpetual swap contracts, but I can't see them being implemented in ccxt

Maybe I am doing something wrong?

**Comment by kroitor** [comment]
Hi!

We are in the process of unifying the contract trading aspects, some exchange may have those contracts, but they are not fully unified in CCXT yet. In the meantime you can use implicit API methods to call those methods as described in the Manual.

More about it here: 

- https://github.com/ccxt/ccxt/issues/4834
- https://github.com/ccxt/ccxt/wiki/Manual#positions
