### ISSUE TITLE
Rightbtc.com changed endpoint of api

### ISSUE THREAD

**Issue by BarrieBoi** [ccxt/ccxt#8281]
For the exchange rightbtc.com the endpoints of their api did change. 

ccxt version: Version: 1.40.54
The current api endpoint: https://www.rightbtc.com/api/public/depth/ETHBTC
Expected endpoint: https://api.rightbtc.com/v1/pub/depth/ETHBTC or https://www.rightbtc.com/v1/pub/depth/ETHBTC

so basically api/public/ --> v1/pub/

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/5942
