### ISSUE TITLE
Consider changing the response format for EXMO transactions

### ISSUE THREAD

**Issue by xenohunter** [ccxt/ccxt#8285]
- OS: Arch Linux
- Programming Language version: Python 3.8
- CCXT version: 1.40.43

Right now, EXMO returns blockchain addresses only for the `withdrawal` transactions:
```
{
    "info": {
        "dt": "1609***",
        "type": "withdrawal",
        "curr": "BTC",
        "status": "paid",
        "provider": "BTC",
        "amount": "1.23",

        # blockchain address
        "account": "BTC: 3J98t1WpEZ73CNmQviecrnyiWrnqRhWNLy",

        "txid": ""
    },
    "address": "3J98t1WpEZ73CNmQviecrnyiWrnqRhWNLy",
    ...
}
```
For the `deposit` transactions, EXMO returns some kind of their inner account ID:
```
{
    "info": {
        "dt": "1608***",
        "type": "deposit",
        "curr": "ATOM",
        "status": "transferred",
        "provider": "ATOM",
        "amount": "1.23",

        # EXMO's inner ID
        "account": "12345678",

        "txid": "***"
    },
    "address": "12345678",
    ...
}
```
But — they both make their way to the `address` field of the object returned by CCXT. Since these are different entities, wouldn't you like to consider making the field `address` empty for the deposits from EXMO? That would make it easier to discriminate blockchain addresses from inner IDs, and the latter ones are in the `info` anyway.

Thanks in advance!

**Comment by kroitor** [comment]
@xenohunter hi! Thanks for reporting it! A quick question on your ATOM transaction above is it a deposit or an internal transfer within the exchange?

**Comment by xenohunter** [comment]
@kroitor, thank you for changing it! Concerning your question, both of transactions above are external (one is a deposit, and one is a withdrawal).

**Comment by kroitor** [comment]
@xenohunter thx for the feedback!
