### ISSUE TITLE
BITMEX: fetching orders information not implemented yet

### ISSUE THREAD

**Issue by evgen-y2k** [ccxt/ccxt#829]
Hi.
Not working all function around fetching orders information. 
For example:
`ccxt.base.errors.NotSupported: bitmex fetch_open_orders() not implemented yet`
Can you halp me? I need some for check order status. Best solution - function fetch_open_orders().
Or may be fetch_order_status() , fetch_orders(), fetch_order().

**Comment by kroitor** [comment]
@evgen-y2k you can use their custom API to submit a request to their private endpoint, as ccxt supports all of them. See `print(dir(ccxt.bitmex())` for a list of methods. Then consult their docs for a list of params and submit the request like written here: https://github.com/ccxt/ccxt/wiki/Manual#passing-parameters-to-api-methods

That is, until we implement their order API. Let me know if this answers your question or not.

**Comment by evgen-y2k** [comment]
I found `privateGetOrder()` and this function work (return all orders) but I need use parameter `{"open": true}` for filtering only opened orders. If I try `privateGetOrder({"open": true})` function return not filtered orders list. In the BITMEX API description I found:
"**Implementation Notes
To get open orders only, send {"open": true} in the filter param**"
URL example:
`https://testnet.bitmex.com/api/v1/order?filter=%7B%22open%22%3A%20true%7D&count=100&reverse=false`
How I can give parameters to function `privateGetOrder()`?

**Comment by evgen-y2k** [comment]
So, I found solution.
`privateGetOrder({'filter':json.dumps({'open': True})})`
It work as I need.
Thank you for the help.

**Comment by kroitor** [comment]
@evgen-y2k thank you for reporting back!

**Comment by bestlinkXx** [comment]
Hello,

Can you help me to get the correct function to get order status please ?

I need to know it too.
This function gave me this : "list indices must be integers, not str."

Thank you so much !

**Comment by kroitor** [comment]
@bestlinkXx https://github.com/ccxt/ccxt/wiki/Manual#querying-orders
