### ISSUE TITLE
fetch_ohlcv() per exchange max limit param ?

### ISSUE THREAD

**Issue by tudorelu** [ccxt/ccxt#8295]
I'm wondering if there is a field in the ccxt exchange object that describes the maximum possible value for the 'limit' parameter when calling the fetch_ohlcv function. 

Asking because I want to fetch historical ohlcv data, and will do so by calling fetch_ohlcv multiple times with different values for the 'since' parameter. I know some exchanges will return the maximum limit if your limit parameter is more than they enable, but some will only return 1 candle, so I want to avoid that, while making a minimum number of calls to the exchange api.

**Comment by kroitor** [comment]
Hi! We don't have this fully unified yet, but we hope to get it covered asap. More about it here: https://github.com/ccxt/ccxt/issues?q=features+is%3Aopen
Apparently, for the best coverage, we might need a swagger-type schema of features, cause you want to know not just the limits, but also the rate limits, the other required / optional params, unified params overrides, etc.

**Comment by kroitor** [comment]
I'd suggest to move this discussion to #6772 , if you don't mind. Thanks for your involvement!
