### ISSUE TITLE
phemex fetch orders sandbox mode not working

### ISSUE THREAD

**Issue by adamrg73** [ccxt/ccxt#8296]
orders = exchange.fetch_orders(symbol)
print(orders)

not working.. works without sandbox mode though..

**Comment by kroitor** [comment]
@adamrg73 hi! Can you please paste your verbose output? 

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by adamrg73** [comment]
fetchedClosedOrders:

Request: GET https://testnet-api.phemex.com/exchange/order/list?symbol=YFIUSD {'x-phemex-access-token': '17020f11-dbd6-4d24-a019-a34663493a96', 'x-phemex-request-expiry': '1610892843', 'x-phemex-request-signature': 'ce7c950ac0e9e9982ea0120d76fab0cf41e340bea48f14ec73ee6dd30c802469', 'User-Agent': 'python-requests/2.24.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://testnet-api.phemex.com/exchange/order/list?symbol=YFIUSD 200 {'Content-Type': 'application/json;charset=utf-8', 'Content-Length': '71', 'Connection': 'keep-alive', 'Date': 'Sun, 17 Jan 2021 14:13:03 GMT', 'Set-Cookie': 'AWSALB=6PyvlsB/g7o9husauBYfPW4lfRgBvM3bS1/Mdr6Vr34WMe5eCGHI5REoMsGNjI2tONr/2s8DXK8AyxmcfrLDmLD4w7gX2IzWYPtF4VryP1F6VvOflJJuoEKteFhx; Expires=Sun, 24 Jan 2021 14:13:03 GMT; Path=/, AWSALBCORS=6PyvlsB/g7o9husauBYfPW4lfRgBvM3bS1/Mdr6Vr34WMe5eCGHI5REoMsGNjI2tONr/2s8DXK8AyxmcfrLDmLD4w7gX2IzWYPtF4VryP1F6VvOflJJuoEKteFhx; Expires=Sun, 24 Jan 2021 14:13:03 GMT; Path=/; SameSite=None, JSESSIONID=node0tpc02j4fvi4v10bmme3dv02gl270035.node0; Path=/phemex-user', 'Server': 'nginx', 'x-phemex-request-tracing': 'f85ea68f-84ce-4582-9f62-7b0ac544f1d1', 'X-RateLimit-Remaining': '194', 'X-RateLimit-Capacity': '200', 'Expires': 'Thu, 01 Jan 1970 00:00:00 GMT', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Xss-Protection': '1; mode=block', 'X-Frame-Options': 'SAMEORIGIN', 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'origin-when-cross-origin', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 4d95e17a6f22c6bea5ad0f9769f73450.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'EWR52-C4', 'X-Amz-Cf-Id': '7l5ygDJUqLGrqan4wESwGz93l3ng9nN9bDtONRYnAwDCZ7uUCukegA=='} {"code":0,"msg":"OK","data":{"total":-1,"rows":[]}}
[]

This is a screenshot of the order history in phemex testnet:

<img width="1002" alt="Screen Shot 2021-01-17 at 9 20 03 AM" src="https://user-images.githubusercontent.com/70821026/104845829-77f00980-58a5-11eb-9ce4-038f28f192fb.png">

**Comment by kroitor** [comment]
@adamrg73 could that be a wrong api key? `17020f11-dbd6-4d24-a019-a34663493a96`

**Comment by adamrg73** [comment]
No I dont think its wrong as it works to buy and sell..

**Comment by kroitor** [comment]
@adamrg73 got it, we're investigating, will be back to you shortly!

**Comment by kroitor** [comment]
@adamrg73 just to clarify – are you sure that this is the right key that has those orders? Could you be using a different key for creating the orders (the key for creating orders differs from the key you use to place the orders). Can you check that the apiKey matches in your API config settings on the Phemex website?

**Comment by adamrg73** [comment]
thanks for the help so far. It is the same id that the script is running in testnet.
<img width="613" alt="Screen Shot 2021-01-19 at 8 43 51 AM" src="https://user-images.githubusercontent.com/70821026/105042685-8586ca00-5a32-11eb-85b5-3a8343d7a4a6.png">

<img width="312" alt="Screen Shot 2021-01-19 at 8 43 00 AM" src="https://user-images.githubusercontent.com/70821026/105042746-9b948a80-5a32-11eb-8b7e-aa99db112f9a.png">

**Comment by kroitor** [comment]
@adamrg73 understood thank you! One more thing: do you have the same issue with the most recent version of CCXT 1.40.77+?

**Comment by adamrg73** [comment]
I havent tried it with most recent version

**Comment by adamrg73** [comment]
Have you had a chance to test this with the latest version of ccxt?

**Comment by kroitor** [comment]
@adamrg73 i'm always testing with the most recent version, since i'm one of the developers of the most recent version. In general, when you have any type of issue, we need your code to reproduce the issue and the complete output in verbose mode. Without that information it might take very long to resolve the issue.

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

Below is a snippet we would expect from you. Please, run it on your side and paste your output here:

```
import ccxt
from pprint import pprint

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.phemex({
    'enableRateLimit': True,
    "apiKey": "3c5d9085-6e22-409e-9d4d-d2d2836c5b32",
    "secret": "fV1y3vE99M0V710zKc4DwahU9k75ZhySoIDrf_6FcURjZTAxOWJkNi1jOWM2LTQ2ODAtOTA3YS1kMThmNjk4ZjY4Mzk"
})

exchange.set_sandbox_mode(True)

markets = exchange.load_markets()

symbol = 'YFI/USD'

order = exchange.create_order(symbol, 'market', 'buy', 1)
order = exchange.create_order(symbol, 'market', 'sell', 1)

exchange.verbose = True

orders = exchange.fetch_closed_orders(symbol)

print('Fetched', len(orders), 'orders')
pprint(orders)
```

↑ What do you see when you run it on your side? I've tested it on my side and it works with my keypair on the testnet...

**Comment by adamrg73** [comment]
must be the version, I guess an update was done since I installed ccxt on this server because I got:

CCXT Version: 1.34.38

Request: GET https://testnet-api.phemex.com/exchange/order/list?symbol=YFIUSD {'x-phemex-access-token': '17020f11-dbd6-4d24-a019-a34663493a96', 'x-phemex-request-expiry': '1611196942', 'x-phemex-request-signature': '81c8c550183f5c2a05b0e0966de2b1d47f985814113acdc064af4b620f9ea75c', 'User-Agent': 'python-requests/2.24.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://testnet-api.phemex.com/exchange/order/list?symbol=YFIUSD 200 {'Content-Type': 'application/json;charset=utf-8', 'Content-Length': '71', 'Connection': 'keep-alive', 'Date': 'Thu, 21 Jan 2021 02:41:23 GMT', 'Set-Cookie': 'AWSALB=gxgyhNvBBPx3XFSe3oF3P9idX05Rrpl9wN9M9possvMO/Zu0QuvqG/CGA6h1KRkj7SHOxbHHk6qSth8EUb6MEFdd9tYf+s5y2Dj5/+p9RYGrEDcXzrWM5IXfyKQO; Expires=Thu, 28 Jan 2021 02:41:23 GMT; Path=/, AWSALBCORS=gxgyhNvBBPx3XFSe3oF3P9idX05Rrpl9wN9M9possvMO/Zu0QuvqG/CGA6h1KRkj7SHOxbHHk6qSth8EUb6MEFdd9tYf+s5y2Dj5/+p9RYGrEDcXzrWM5IXfyKQO; Expires=Thu, 28 Jan 2021 02:41:23 GMT; Path=/; SameSite=None, JSESSIONID=node01opjvfnleswb318mhdnk1mpa8s2404.node0; Path=/phemex-user, cookiesession1=678A3E11OPQRSTUVWXYZJKLMNPQR6111;Expires=Fri, 21 Jan 2022 02:41:23 GMT;Path=/;HttpOnly', 'Server': 'nginx', 'x-phemex-request-tracing': '20ef72b8-3a4f-4417-89cf-72a8a827b9e6', 'X-RateLimit-Remaining': '184', 'X-RateLimit-Capacity': '200', 'Expires': 'Thu, 01 Jan 1970 00:00:00 GMT', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Xss-Protection': '1; mode=block', 'X-Frame-Options': 'SAMEORIGIN', 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'origin-when-cross-origin', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 0d9932dd4d2694056e54537f60730ff5.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'EWR52-C4', 'X-Amz-Cf-Id': 'J6By1hsM63h9vrFYAffTgqcyoTXyFUxYtkxre1076xEpN-9TUtROAA=='} {"code":0,"msg":"OK","data":{"total":-1,"rows":[]}}
Fetched 0 orders
[]



appreciate you testing with yours, I will have to update ccxt on this server, I was just worried about breaking any of my other code running..

**Comment by kroitor** [comment]
@adamrg73 this is my output with 1.40.82:

```
mbp:python igorkroitor$ python3
Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> from pprint import pprint
>>>
>>> print('CCXT Version:', ccxt.__version__)
CCXT Version: 1.40.82
>>>
>>> exchange = ccxt.phemex({
...     'enableRateLimit': True,
...     "apiKey": "3c5d9085-6e22-409e-9d4d-d2d2836c5b32",
...     "secret": "fV1y3vE99M0V710zKc4DwahU9k75ZhySoIDrf_6FcURjZTAxOWJkNi1jOWM2LTQ2ODAtOTA3YS1kMThmNjk4ZjY4Mzk"
... })
>>>
>>> exchange.set_sandbox_mode(True)
>>>
>>> markets = exchange.load_markets()
>>>
>>> symbol = 'YFI/USD'
>>>
>>> order = exchange.create_order(symbol, 'market', 'buy', 1)
>>> order = exchange.create_order(symbol, 'market', 'sell', 1)
>>>
>>> exchange.verbose = True
>>>
>>> orders = exchange.fetch_closed_orders(symbol)

Request: GET https://testnet-api.phemex.com/exchange/order/list?symbol=YFIUSD {'x-phemex-access-token': '3c5d9085-6e22-409e-9d4d-d2d2836c5b32', 'x-phemex-request-expiry': '1611195662', 'x-phemex-request-signature': '50e3220cc0f78755552fd863f1d5a3963a399e0b0be8caf66aa87857599457d3', 'User-Agent': 'python-requests/2.21.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://testnet-api.phemex.com/exchange/order/list?symbol=YFIUSD 200 {'Content-Type': 'application/json;charset=utf-8', 'Content-Length': '967', 'Connection': 'keep-alive', 'Date': 'Thu, 21 Jan 2021 02:20:02 GMT', 'Set-Cookie': 'AWSALB=Phnf6UMiRpiIJiiuoBMTsHRau52sXcQnqk+/Whm5Hz/aB/6QXftZ1eWqMoxNUIawY7Oqf1PvOz8vDej474ToJLEFg1zkqG0jtyHJUn+sO96OqOBk7H9IJhp/1MbW; Expires=Thu, 28 Jan 2021 02:20:02 GMT; Path=/, AWSALBCORS=Phnf6UMiRpiIJiiuoBMTsHRau52sXcQnqk+/Whm5Hz/aB/6QXftZ1eWqMoxNUIawY7Oqf1PvOz8vDej474ToJLEFg1zkqG0jtyHJUn+sO96OqOBk7H9IJhp/1MbW; Expires=Thu, 28 Jan 2021 02:20:02 GMT; Path=/; SameSite=None, JSESSIONID=node04xsdd10clv8bfcs117tzkkmo792.node0; Path=/phemex-user, cookiesession1=678A3E11RSTUVWGHIJKLMNOPQRSTC64C;Expires=Fri, 21 Jan 2022 02:20:02 GMT;Path=/;HttpOnly', 'Server': 'nginx', 'x-phemex-request-tracing': '383adf1c-257c-4027-96e8-68f87d338539', 'X-RateLimit-Remaining': '199', 'X-RateLimit-Capacity': '200', 'Expires': 'Thu, 01 Jan 1970 00:00:00 GMT', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Xss-Protection': '1; mode=block', 'X-Frame-Options': 'SAMEORIGIN', 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'origin-when-cross-origin', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 ead12ea8a5dacf72daa302814186069d.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'HEL50-C2', 'X-Amz-Cf-Id': 'tDi9kd_5jajLt3jjcZ8Cqj0zNBbQ30T-hAiN1XTNMJlkXc48-9QHAQ=='} {"code":0,"msg":"OK","data":{"total":-1,"rows":[{"orderID":"b23230d5-36bb-4586-986e-70a226988ff8","clOrdID":"","symbol":"YFIUSD","side":"Sell","orderType":"Market","actionTimeNs":1611195602098734593,"priceEp":241920000,"price":null,"orderQty":1,"displayQty":0,"timeInForce":"ImmediateOrCancel","reduceOnly":false,"takeProfitEp":0,"takeProfit":null,"stopLossEp":0,"closedPnlEv":-105,"closedPnl":null,"closedSize":1,"cumQty":1,"cumValueEv":32256,"cumValue":null,"leavesQty":0,"leavesValueEv":0,"leavesValue":null,"stopLoss":null,"stopDirection":"UNSPECIFIED","ordStatus":"Filled","transactTimeNs":1611195602103581359,"bizError":0,"platform":5},{"orderID":"0ca95014-5bac-42cb-a338-c84639980d4b","clOrdID":"","symbol":"YFIUSD","side":"Buy","orderType":"Market","actionTimeNs":1611195601570735842,"priceEp":332295000,"price":null,"orderQty":1,"displayQty":0,"timeInForce":"ImmediateOrCancel","reduceOnly":false,"takeProfitEp":0,"takeProfit":null,"stopLossEp":0,"closedPnlEv":0,"closedPnl":null,"closedSize":0,"cumQty":1,"cumValueEv":32361,"cumValue":null,"leavesQty":0,"leavesValueEv":0,"leavesValue":null,"stopLoss":null,"stopDirection":"UNSPECIFIED","ordStatus":"Filled","transactTimeNs":1611195601575793310,"bizError":0,"platform":5},{"orderID":"efd8c358-c994-4261-a21a-39cbcf089fd9","clOrdID":"","symbol":"YFIUSD","side":"Sell","orderType":"Market","actionTimeNs":1611195350979682853,"priceEp":243345000,"price":null,"orderQty":1,"displayQty":0,"timeInForce":"ImmediateOrCancel","reduceOnly":false,"takeProfitEp":0,"takeProfit":null,"stopLossEp":0,"closedPnlEv":-115,"closedPnl":null,"closedSize":1,"cumQty":1,"cumValueEv":32446,"cumValue":null,"leavesQty":0,"leavesValueEv":0,"leavesValue":null,"stopLoss":null,"stopDirection":"UNSPECIFIED","ordStatus":"Filled","transactTimeNs":1611195350982809115,"bizError":0,"platform":5},{"orderID":"14d770e5-93a5-4e4f-94b4-1c945698ec47","clOrdID":"","symbol":"YFIUSD","side":"Buy","orderType":"Market","actionTimeNs":1611195346451688054,"priceEp":334510000,"price":null,"orderQty":1,"displayQty":0,"timeInForce":"ImmediateOrCancel","reduceOnly":false,"takeProfitEp":0,"takeProfit":null,"stopLossEp":0,"closedPnlEv":0,"closedPnl":null,"closedSize":0,"cumQty":1,"cumValueEv":32561,"cumValue":null,"leavesQty":0,"leavesValueEv":0,"leavesValue":null,"stopLoss":null,"stopDirection":"UNSPECIFIED","ordStatus":"Filled","transactTimeNs":1611195346457364668,"bizError":0,"platform":5},{"orderID":"7c63301b-06e8-47b3-8426-8102e8a41c00","clOrdID":"","symbol":"YFIUSD","side":"Sell","orderType":"Market","actionTimeNs":1611195273147853208,"priceEp":0,"price":null,"orderQty":1,"displayQty":0,"timeInForce":"ImmediateOrCancel","reduceOnly":false,"takeProfitEp":0,"takeProfit":null,"stopLossEp":0,"closedPnlEv":0,"closedPnl":null,"closedSize":0,"cumQty":0,"cumValueEv":0,"cumValue":null,"leavesQty":0,"leavesValueEv":0,"leavesValue":null,"stopLoss":null,"stopDirection":"UNSPECIFIED","ordStatus":"Rejected","transactTimeNs":1611195273147853208,"bizError":11082,"platform":5},{"orderID":"d67be550-ad9b-4880-a61f-a4faef6e73d4","clOrdID":"","symbol":"YFIUSD","side":"Buy","orderType":"Market","actionTimeNs":1611195247511981021,"priceEp":0,"price":null,"orderQty":1,"displayQty":0,"timeInForce":"ImmediateOrCancel","reduceOnly":false,"takeProfitEp":0,"takeProfit":null,"stopLossEp":0,"closedPnlEv":0,"closedPnl":null,"closedSize":0,"cumQty":0,"cumValueEv":0,"cumValue":null,"leavesQty":0,"leavesValueEv":0,"leavesValue":null,"stopLoss":null,"stopDirection":"UNSPECIFIED","ordStatus":"Rejected","transactTimeNs":1611195247511981021,"bizError":11082,"platform":5}]}}
>>>
>>> print('Fetched', len(orders), 'orders')
Fetched 6 orders
>>> pprint(orders)
[{'amount': 1.0,
  'average': None,
  'clientOrderId': None,
  'cost': None,
  'datetime': '2021-01-21T02:14:07.511Z',
  'fee': None,
  'filled': 0.0,
  'id': 'd67be550-ad9b-4880-a61f-a4faef6e73d4',
  'info': {'actionTimeNs': 1611195247511981021,
           'bizError': 11082,
           'clOrdID': '',
           'closedPnl': None,
           'closedPnlEv': 0,
           'closedSize': 0,
           'cumQty': 0,
           'cumValue': None,
           'cumValueEv': 0,
           'displayQty': 0,
           'leavesQty': 0,
           'leavesValue': None,
           'leavesValueEv': 0,
           'ordStatus': 'Rejected',
           'orderID': 'd67be550-ad9b-4880-a61f-a4faef6e73d4',
           'orderQty': 1,
           'orderType': 'Market',
           'platform': 5,
           'price': None,
           'priceEp': 0,
           'reduceOnly': False,
           'side': 'Buy',
           'stopDirection': 'UNSPECIFIED',
           'stopLoss': None,
           'stopLossEp': 0,
           'symbol': 'YFIUSD',
           'takeProfit': None,
           'takeProfitEp': 0,
           'timeInForce': 'ImmediateOrCancel',
           'transactTimeNs': 1611195247511981021},
  'lastTradeTimestamp': 1611195247511,
  'postOnly': False,
  'price': 0.0,
  'remaining': 0.0,
  'side': 'buy',
  'status': 'rejected',
  'stopPrice': None,
  'symbol': 'YFI/USD',
  'timeInForce': 'IOC',
  'timestamp': 1611195247511,
  'trades': None,
  'type': 'market'},
  ...
 {'amount': 1.0,
  'average': None,
  'clientOrderId': None,
  'cost': None,
  'datetime': '2021-01-21T02:20:02.098Z',
  'fee': None,
  'filled': 1.0,
  'id': 'b23230d5-36bb-4586-986e-70a226988ff8',
  'info': {'actionTimeNs': 1611195602098734593,
           'bizError': 0,
           'clOrdID': '',
           'closedPnl': None,
           'closedPnlEv': -105,
           'closedSize': 1,
           'cumQty': 1,
           'cumValue': None,
           'cumValueEv': 32256,
           'displayQty': 0,
           'leavesQty': 0,
           'leavesValue': None,
           'leavesValueEv': 0,
           'ordStatus': 'Filled',
           'orderID': 'b23230d5-36bb-4586-986e-70a226988ff8',
           'orderQty': 1,
           'orderType': 'Market',
           'platform': 5,
           'price': None,
           'priceEp': 241920000,
           'reduceOnly': False,
           'side': 'Sell',
           'stopDirection': 'UNSPECIFIED',
           'stopLoss': None,
           'stopLossEp': 0,
           'symbol': 'YFIUSD',
           'takeProfit': None,
           'takeProfitEp': 0,
           'timeInForce': 'ImmediateOrCancel',
           'transactTimeNs': 1611195602103581359},
  'lastTradeTimestamp': 1611195602103,
  'postOnly': False,
  'price': 24192.0,
  'remaining': 0.0,
  'side': 'sell',
  'status': 'closed',
  'stopPrice': None,
  'symbol': 'YFI/USD',
  'timeInForce': 'IOC',
  'timestamp': 1611195602098,
  'trades': None,
  'type': 'market'}]
```

**Comment by adamrg73** [comment]
hmm strange. I updated ccxt on my macbook. and still no order list.

CCXT Version: 1.40.83

Request: GET https://testnet-api.phemex.com/exchange/order/list?symbol=YFIUSD {'x-phemex-access-token': '2f1e38e1-8c8f-43a7-b6ad-7e54fb3c121f', 'x-phemex-request-expiry': '1611197636', 'x-phemex-request-signature': '05f91f86899ace82e99043c65cb70436abbdf521eb5ce2b735adcf2c5fe292e3', 'User-Agent': 'python-requests/2.24.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://testnet-api.phemex.com/exchange/order/list?symbol=YFIUSD 200 {'Content-Type': 'application/json;charset=utf-8', 'Content-Length': '71', 'Connection': 'keep-alive', 'Date': 'Thu, 21 Jan 2021 02:52:57 GMT', 'Set-Cookie': 'AWSALB=CJZWT72zc6s66kb1MWCm4dZEwKAC70oFTf2/QSaFkl3QTOrAKj4H1idEr4+zALooq1G4uV7yQQOPfsozeLwpBTln22LpIY8QHubErA2EJPkxydp/BSW+OpEwfRum; Expires=Thu, 28 Jan 2021 02:52:57 GMT; Path=/, AWSALBCORS=CJZWT72zc6s66kb1MWCm4dZEwKAC70oFTf2/QSaFkl3QTOrAKj4H1idEr4+zALooq1G4uV7yQQOPfsozeLwpBTln22LpIY8QHubErA2EJPkxydp/BSW+OpEwfRum; Expires=Thu, 28 Jan 2021 02:52:57 GMT; Path=/; SameSite=None, JSESSIONID=node0vyvki0rled0212pdz15uw0siu3199.node0; Path=/phemex-user, cookiesession1=678A3E11JKLMNOPQRSTUV12345672A6F;Expires=Fri, 21 Jan 2022 02:52:57 GMT;Path=/;HttpOnly', 'Server': 'nginx', 'x-phemex-request-tracing': '4d36fe3f-5bb4-4abf-be67-8d7a11a62bb8', 'X-RateLimit-Remaining': '163', 'X-RateLimit-Capacity': '200', 'Expires': 'Thu, 01 Jan 1970 00:00:00 GMT', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Xss-Protection': '1; mode=block', 'X-Frame-Options': 'SAMEORIGIN', 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'origin-when-cross-origin', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 703b08cef218787c0412d1e05c5a7766.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'YTO50-C1', 'X-Amz-Cf-Id': '6vt2zZ3K9QCkO_I9rhXezRNAepRmETAdynBPds1CUSMjPsDYyU7_mw=='} {"code":0,"msg":"OK","data":{"total":-1,"rows":[]}}
Fetched 0 orders
[]

**Comment by kroitor** [comment]
@adamrg73 are you running the same snippet i posted above (with my keypair) ?

**Comment by adamrg73** [comment]
No I put my keypairs.
I can make keys and if you give me an IP address I will make you a key to test. Reason I need to use testnet is because I cant keep testing strategies with real money, its too much money.

**Comment by kroitor** [comment]
@adamrg73 try my snippet, if it works – the problem is almost certainly with the keypair you're using.

**Comment by adamrg73** [comment]
I just made new keypairs and put it into the code sample you gave me. Give me an IP address Ill make you a set and show you.  Also funny though, the testnet keys worked with both my home IP address when it was set to the my vps..

**Comment by kroitor** [comment]
@adamrg73 first, we need to know if my snippet works for you unchanged (with my keypair) – does it work for you?

**Comment by adamrg73** [comment]
ya with your keys I got results.. weird.

**Comment by kroitor** [comment]
@adamrg73 you're using https://testnet.phemex.com to generate the testnet keys, right?

**Comment by adamrg73** [comment]
import ccxt
from pprint import pprint

print('CCXT Version:', ccxt.__version__)
#17020f11-dbd6-4d24-a019-a34663493a96 tLkCK3bqrSlBUIrZihiz_1mFoyPAAcfRvN4yyWsSa3diM2RkMDFlYy1jODk1LTRkNTAtYjY0ZS02OWNlOGM3YjY3NjM
exchange = ccxt.phemex({
    'enableRateLimit': True,
    #"apiKey": "17020f11-dbd6-4d24-a019-a34663493a96",
    "apiKey":"2f1e38e1-8c8f-43a7-b6ad-7e54fb3c121f",
    "secret":"14QgUyC1GisP3hSDPjvIhiL10WoMWTclK_7HPKleDDBjOWVlYjdjZC01MzAzLTRkYmQtODA5Ni1mZmMyOWIwMjQyMDE"
    #"secret": "tLkCK3bqrSlBUIrZihiz_1mFoyPAAcfRvN4yyWsSa3diM2RkMDFlYy1jODk1LTRkNTAtYjY0ZS02OWNlOGM3YjY3NjM"
})

exchange.set_sandbox_mode(True)

markets = exchange.load_markets()

symbol = 'YFI/USD'

order = exchange.create_order(symbol, 'market', 'buy', 1)
order = exchange.create_order(symbol, 'market', 'sell', 1)

exchange.verbose = True

orders = exchange.fetch_closed_orders(symbol)
print('Fetched', len(orders), 'orders')
pprint(orders)

**Comment by adamrg73** [comment]
<img width="810" alt="Screen Shot 2021-01-20 at 10 05 43 PM" src="https://user-images.githubusercontent.com/70821026/105274693-ac94e700-5b6b-11eb-80c3-890c07e5f4b4.png">

**Comment by adamrg73** [comment]
Dont know why the bound ip address didnt get in there for this test3, but the orders are being place on my testnet I watch it..

**Comment by kroitor** [comment]
@adamrg73 yeah, pardon, you've posted that screenshot above. I just tested with your keypair – empty results on my side. I'd recommend reaching out to Phemex's tech support on this issue, it seems to be on the exchange side.

**Comment by kroitor** [comment]
@adamrg73 one more thing i'd recommend trying – sign up for a random new account with a temporary email, create a new keypair, and try it – does that work for you? (just for the sake of testing)

**Comment by adamrg73** [comment]
ya something going on for sure on their side.. but its really good to know that they have the support to make it work since you tested it with me. I really appreciate that you tested on your end.. I think im confident they can fix this now.. I will reach out to them more.

**Comment by kroitor** [comment]
@adamrg73 it would be worth trying with a random new account – signing up with testnet.phemex.com is free and does not require any KYC, so, i'd give it another chance. It would be great if you could check that and report back here. Thx!

**Comment by adamrg73** [comment]
Ya you know what.. I will definitely create a new account to do this so I can get going testing my strategies without using real money loll.. I will keep you posted on that, and also the response I get from the phemex telegram API chat, they dont respond too quick, but someone did reply showing ccxt javascript working.. so looks like my account is somehow buggy or not enabled..

**Comment by adamrg73** [comment]
Ya I just made a new account on phemex, not a sub account, completely new account. And I made new keys of course.. and it works on my vps with older ccxt version
:)
thanks a lot kroitor..!

**Comment by kroitor** [comment]
@adamrg73 ok, i'll close this for now, feel free to reopen it if needed or just ask further questions if any.

**Comment by adamrg73** [comment]
Ok np thx again!
