### ISSUE TITLE
Dash privatesend via ccxt

### ISSUE THREAD

**Issue by benlvovsky** [ccxt/ccxt#8299]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Mac OS
- Programming Language version: python 3.75
- CCXT version:

```
withdraw = exchange.withdraw('DASH', 1, 'PrivateSend') # I need to know how to do PrivateSend for Dash

```

```
???
```

**Comment by kroitor** [comment]
@benlvovsky which exchange is it? The CCXT lib is not used to send or receive crypto, it is used to talk to crypto exchanges.

**Comment by benlvovsky** [comment]
Kraken

**Comment by kroitor** [comment]
@benlvovsky Kraken API does not allow you to choose that afaik: https://www.kraken.com/features/api#withdraw-funds
Let us know if that does not answer your question. Feel free to reopen this issue or just ask further questions if any.
