### ISSUE TITLE
[coinfloor] there is a new rest api

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#8303]
https://github.com/coinfloor/API/blob/master/BIST_v2.md#coinfloor-bist-api-version-2

At a glance it looks the same as version 1 unfortunately.

**Comment by stumac85** [comment]
Just a heads up, as of last night the old api url has been disabled. You will need to manually set the address via something similar to what I did:

`$ccxt_coinfloor->urls['api'] = 'https://webapi.coinfloor.co.uk/v2/bist';`
