### ISSUE TITLE
Closing position orders rejected in Binance Hedge Mode

### ISSUE THREAD

**Issue by Rishirandhawa** [ccxt/ccxt#8304]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Mac/ Ubuntu
- Programming Language version: Py latest
- CCXT version: 1.40.33

```
    exchange = exchange_class({
        'apiKey': api_key,
        'secret': api_secret,
        'timeout': 30000,
        'enableRateLimit': True,
        'options': {
            'defaultType': 'future',
            'adjustForTimeDifference': True
        },
    })
    
        symbol = 'ZEC/USDT'
        type = 'market
        side = 'sell
        amount = 0.003
        price = None
        params = { 
            'positionSide': 'LONG'
             }
        order = exchange.create_order(symbol, type, side, amount, price, params)
```

Note : Hedge mode is enabled for exchange/account, placement of orders working fine. Issue encountered only at the time of closing. Not sure why it is saying ReduceOnly Order rejected because there is no ReduceOnly param being sent. Order amount is also equal to the full open position amount and not partial.

```
ccxt.base.errors.ExchangeError: binance {"code":-2022,"msg":"ReduceOnly Order is rejected."}
2021-01-17 17:35:51  - Close trade failure:  ZEC/USDT binance {"code":-2022,"msg":"ReduceOnly Order is rejected."}
type market, position_side LONG, order_side sell, instrument ZEC/USDT, quantity 0.003)```

**Comment by nuriAngraini** [comment]
Liave

**Comment by Rishirandhawa** [comment]
Hi... any update on this issue yet ?

**Comment by Rishirandhawa** [comment]
Please see below the output .. from what I could reproduce .... Setup 👍 
1 Created Buy order with amount 4 --- worked fine
2. Created Sell order with amount 2 ---- worked fine
3. Created Sell order with amount 2 ---- Leads to error described below. The expected behavior is to close the remaining position

#createMarketOrder

symbol = 'ADA/USDT'
position_side = 'LONG'
side = 'sell'
amount = 2
price=None
params = { 
            'positionSide': position_side
             }
order = exchange.create_market_order(symbol, side, amount, price, params)
order

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
~/projects/trading-bot/env/lib/python3.8/site-packages/ccxt/base/exchange.py in fetch(self, url, method, headers, body)
    588             self.logger.debug("%s %s, Response: %s %s %s", method, url, http_status_code, headers, http_response)
--> 589             response.raise_for_status()
    590 

~/projects/trading-bot/env/lib/python3.8/site-packages/requests/models.py in raise_for_status(self)
    942         if http_error_msg:
--> 943             raise HTTPError(http_error_msg, response=self)
    944 

HTTPError: 400 Client Error: Bad Request for url: https://fapi.binance.com/fapi/v1/order

During handling of the above exception, another exception occurred:

ExchangeError                             Traceback (most recent call last)
<ipython-input-18-e0a658fbdfbd> in <module>
      9             'positionSide': position_side
     10              }
---> 11 order = exchange.create_market_order(symbol, side, amount, price, params)
     12 order

~/projects/trading-bot/env/lib/python3.8/site-packages/ccxt/base/exchange.py in create_market_order(self, symbol, side, amount, price, params)
   1860 
   1861     def create_market_order(self, symbol, side, amount, price=None, params={}) -> dict:
-> 1862         return self.create_order(symbol, 'market', side, amount, price, params)
   1863 
   1864     def create_limit_buy_order(self, symbol, amount, price=None, params={}) -> dict:

~/projects/trading-bot/env/lib/python3.8/site-packages/ccxt/binance.py in create_order(self, symbol, type, side, amount, price, params)
   1716                 params = self.omit(params, 'stopPrice')
   1717                 request['stopPrice'] = self.price_to_precision(symbol, stopPrice)
-> 1718         response = getattr(self, method)(self.extend(request, params))
   1719         return self.parse_order(response, market)
   1720 

~/projects/trading-bot/env/lib/python3.8/site-packages/ccxt/base/exchange.py in inner(_self, params)
    464                             if params is not None:
    465                                 inner_kwargs['params'] = params
--> 466                             return entry(_self, **inner_kwargs)
    467                         return inner
    468                     to_bind = partialer()

~/projects/trading-bot/env/lib/python3.8/site-packages/ccxt/binance.py in request(self, path, api, method, params, headers, body)
   2543 
   2544     def request(self, path, api='public', method='GET', params={}, headers=None, body=None):
-> 2545         response = self.fetch2(path, api, method, params, headers, body)
   2546         # a workaround for {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action."}
   2547         if (api == 'private') or (api == 'wapi'):

~/projects/trading-bot/env/lib/python3.8/site-packages/ccxt/base/exchange.py in fetch2(self, path, api, method, params, headers, body)
    485         self.lastRestRequestTimestamp = self.milliseconds()
    486         request = self.sign(path, api, method, params, headers, body)
--> 487         return self.fetch(request['url'], request['method'], request['headers'], request['body'])
    488 
    489     def request(self, path, api='public', method='GET', params={}, headers=None, body=None):

~/projects/trading-bot/env/lib/python3.8/site-packages/ccxt/base/exchange.py in fetch(self, url, method, headers, body)
    603         except HTTPError as e:
    604             details = ' '.join([self.id, method, url])
--> 605             self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
    606             self.handle_http_status_code(http_status_code, http_status_text, url, method, http_response)
    607             raise ExchangeError(details) from e

~/projects/trading-bot/env/lib/python3.8/site-packages/ccxt/binance.py in handle_errors(self, code, reason, url, method, headers, body, response, requestHeaders, requestBody)
   2538             feedback = self.id + ' ' + body
   2539             self.throw_exactly_matched_exception(self.exceptions, error, feedback)
-> 2540             raise ExchangeError(feedback)
   2541         if not success:
   2542             raise ExchangeError(self.id + ' ' + body)

ExchangeError: binance {"code":-2022,"msg":"ReduceOnly Order is rejected."}

**Comment by klemensz** [comment]
@Rishirandhawa Have you found a solution for your problem?

**Comment by ttodua** [comment]
Late reply here, but I've tested your codes and found out, that there is no issue in CCXT, but it might be misunderstanding.
For example, when using hedge-mode on binance, you should choose `positionMode` either `SHORT` or `LONG` depending which side position you want to get affected. for example, if you want to open or close **long** position (so, your createOrder only affected **long** positions), you need to use `positionMode : LONG`. 
So, when you want to close long positions, you correctly use `sell` as side, however, you have to keep `positionMode: 'LONG'` param too. 
But lastly, when you get `{"code":-2022,"msg":"ReduceOnly Order is rejected."}`  - I have tested that several times and can confirm that error comes, but only when the position is already closed. I know we don't use  `ReduceOnly` param there and binance error mentions that, but it's because, `side: 'sell'  & positionMode: 'LONG'` is translated automatically as 'ReduceOnly' action inside binance's API engine, thus it tells us back that "there is nothing left in position to get redeced/closed", so the error is valid (just their phrase is not ideally worded, they'd better told: "There is no position on this side, so nothing can be closed/reduced").

Thus, you should find out some issue in your userland code, because that error means the position was already closed and you have submited the `sell` order after it. I can't say how, it's you who should find out what went wrong in your bot, double check it, and let us know if you find any issue in CCXT.
