### ISSUE TITLE
[gateio] request for v4

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#8306]
The v4 rest api looks much better than v2 - it include trade history

https://www.gate.io/docs/apiv4/en/index.html#list-personal-trading-history

**Comment by Kalindro** [comment]
Any update on this V4 API integrations? V2 lacks so much

**Comment by kroitor** [comment]
@Kalindro we are working on the upgrade, and will hopefully deliver it soon.

**Comment by ndubel** [comment]
There is also an annoying glitch in v2 if price precision > 8 and I try to `fetchOpenOrders` I get `price` rounded to precision 8:

```
info: {
      orderNumber: '60707322161',
      orderType: '1',
      type: 'buy',
      rate: '0.00000001',
      amount: '100000.00000000',
      total: '0.00130000',
      initialRate: '0.00000001',
      initialAmount: '100000',
      filledRate: '0.00000001',
      filledAmount: '0',
      currencyPair: 'hsc_eth',
      timestamp: '1625753365',
      status: 'open'
    },
```
So price is `0.00000001`
But `total` / `amount` gives a real order `price` `0.000000013`

**Comment by marmotz** [comment]
Any news for gate.io apiv4 release ?

**Comment by kroitor** [comment]
@marmotz we will add it as soon as we can: https://github.com/ccxt/ccxt/wiki/FAQ
