### ISSUE TITLE
Precision in markets where the buy order is given in quote currency

### ISSUE THREAD

**Issue by unaiasegi** [ccxt/ccxt#8310]
Hello,

I have a question regarding the market precision dictionary in exchanges where the buy order amount must be provided in quote currency. 

Even if the buy amount must be provided in quote currency, the precision dictionary of these markets does not include the 'cost' key, which is basically the amount in quote currency. They only provide the 'amount' (the amount in base currency) and 'price' keys. Therefore, I do not understand which one should I pick (or transform) to check the precision of the market in quote currency.

This problem does not exist in exchanges where every (buy and sell) amount must be provided in base currency as the precision dictionary does include the 'amount' key which is expressed in base currency.

Thank you very much in advance,

Unai

**Comment by kroitor** [comment]
Hi!

> which one should I pick (or transform) to check the precision of the market in quote currency.

Both the price and the cost are usually expressed in the same currency, and have the same precision, so you can use the price precision to format your cost.

Let us know if that does not answer your question.

**Comment by unaiasegi** [comment]
It does answer my question, very much appreciated.
Great job!
