### ISSUE TITLE
Not Getting Liquidation Price from Open Positions

### ISSUE THREAD

**Issue by AsadullahSoomro** [ccxt/ccxt#8311]
OS: Windows
Programming Language version: Python 3.8
CCXT version: 1.39.14 (latest)
Hello!
I am using the latest version of CCXT to get positions details, all the things I am getting is perfect but I can’t get Liquidation price there. It is always showing Liquidation Price = 0, Kindly suggest some other function or another way from where I can get actual liquidation price
Here is what I have so far:
Binance_Testnet = ccxt.binance({
    'apiKey': key,
    'secret': secret,
    'enableRateLimit': True,  
    'options': {
        'defaultType': 'future',
    }
})
positions = Binance_Testnet.fapiPrivateGetPositionRisk()
print(positions)

Thanks in Advance..!

Out Snapshot
:
{'symbol': 'BTCUSDT', 'positionAmt': '0.020', 'entryPrice': '37159.96866', 'markPrice': '35702.56423954', 'unRealizedProfit': '-29.14808840', 'liquidationPrice': '0', 'leverage': '1', 'maxNotionalValue': '9223372036854775807', 'marginType': 'cross', 'isolatedMargin': '0.00000000', 'isAutoAddMargin': 'false', 'positionSide': 'BOTH', 'notional': '714.05128479'},

**Comment by kroitor** [comment]
@AsadullahSoomro Hi! Which liquidation price does the Binance website show to you on your BTC/USDT position?

**Comment by kroitor** [comment]
There's only two relevant endpoints for your positions:

```Python
positions = Binance_Testnet.fapiPrivateGetPositionRisk()
```

or

```Python
positions = Binance_Testnet.fapiPrivateV2GetPositionRisk()
```

If Binance API says that your liqudation price is 0 and the Binance website shows a non-zero liquidation price, then I'd suggest to ask here: https://t.me/binance_api_english

Let us know if the above does not help.

**Comment by AsadullahSoomro** [comment]
Dear Sir @kroitor, Thanks for replying.
On the Binance portal side, BTC/USDT position is displaying
when our side sell orders are going close short then showing position when side sell orders are going to be close short. 

`positions = Binance_Testnet.fapiPrivateGetPositionRisk()
print(positions)`

{'symbol': 'BTCUSDT', 'positionAmt': '0.020', 'entryPrice': '37159.96866', 'markPrice': '35702.56423954', 'unRealizedProfit': '-29.14808840', 'liquidationPrice': '0', 'leverage': '1', 'maxNotionalValue': '9223372036854775807', 'marginType': 'cross', 'isolatedMargin': '0.00000000', 'isAutoAddMargin': 'false', 'positionSide': 'BOTH', 'notional': '714.05128479'},

**Comment by kroitor** [comment]
@AsadullahSoomro @AsadullahSoomro have you tried `fapiPrivateV2GetPositionRisk` as was suggested above?

**Comment by AsadullahSoomro** [comment]
Yes, I have also checked this function `fapiPrivateV2GetPositionRisk`

> 'BTCUSDT', 'positionAmt': '0.001', 'entryPrice': '31113.61000', 'markPrice': '31307.30286461', 'unRealizedProfit': '0.19369286', '**liquidationPrice': '0'**, 'leverage': '1', 'maxNotionalValue': '9223372036854775807', 'marginType': 'cross', 'isolatedMargin': '0.00000000', 'isAutoAddMargin': 'false', 'positionSide': 'BOTH', 'notional': '31.30730286'},

**Comment by kroitor** [comment]
@AsadullahSoomro if you can't get the liquidationPrice from either `fapiPrivateGetPositionRisk` or `fapiPrivateV2GetPositionRisk` – then i'd suggest to forward the question to Binance's tech support. 
Which liquidation price do you see for your BTC/USDT position on the Binance website?
Have you tried opening a ticket with them?

**Comment by AsadullahSoomro** [comment]
Dear Sir @kroitor Thanks for replying..
Sir, currently, I am trying to fetch the liquidation price in a binance exchange using python script as it is not showing on the portal side as well as in positions data. 
further, I have checked liquidation manually using mentioned blew link 
[Binance Futures Calculator]
After calculating Liquidation Manually.
Only Showing close short positions on the Binance Testnet portal side
I am using Testnet On the Binance portal side, BTC/USDT position is displaying
(https://www.binance.com/en/support/articles/360036498511-How-to-Use-Binance-Futures-Calculator)

**Comment by kroitor** [comment]
@AsadullahSoomro can you post a screenshot of your values you use with the futures liquidation price calculator ?

I think, it has to be calculated using these rules: https://www.binance.com/en/support/faq/b3c689c1f50a44cabb3a84e663b81d93

**Comment by snapdotNG** [comment]
From what I can see your leverage is "1" which is basically like you are trading spot you are not using any leverage and technically you can never get liquidated unless price falls to zero line. Try changing leverage to value greater than 1.
