### ISSUE TITLE
Revised Issue #8311 Not Getting Liquidation Price from Open Positions

### ISSUE THREAD

**Issue by AsadullahSoomro** [ccxt/ccxt#8317]
Dear Sir 
On the Binance portal side, BTC/USDT position is displaying
when our side sell orders are going close short then showing position when side sell orders are going to be close short. 

It is always showing Liquidation Price = 0, On BTC/USDT position
Kindly suggest some other function or another way from where I can get the actual liquidation price.

`positions = Binance_Testnet.fapiPrivateGetPositionRisk()

print(positions)`

{'symbol': 'BTCUSDT', 'positionAmt': '0.020', 'entryPrice': '37159.96866', 'markPrice': '35702.56423954', 'unRealizedProfit': '-29.14808840', 'liquidationPrice': '0', 'leverage': '1', 'maxNotionalValue': '9223372036854775807', 'marginType': 'cross', 'isolatedMargin': '0.00000000', 'isAutoAddMargin': 'false', 'positionSide': 'BOTH', 'notional': '714.05128479'},

**Comment by AsadullahSoomro** [comment]
Dear Sir @kroitor,

On the Binance portal side, BTC/USDT position is displaying
**when our side sell orders are going close short then showing position when side sell orders are going to be close short.** 

**It is always showing Liquidation Price = 0, On BTC/USDT position**
Kindly suggest some other function or another way from where I can get the actual liquidation price.

```
`positions = Binance_Testnet.fapiPrivateGetPositionRisk()

print(positions)`
```

{'symbol': '**BTCUSDT**', 'positionAmt': '0.020', 'entryPrice': '37159.96866', 'markPrice': '35702.56423954', 'unRealizedProfit': '-29.14808840', 'liquidationPrice': '0', 'leverage': '1', 'maxNotionalValue': '9223372036854775807', 'marginType': 'cross', 'isolatedMargin': '0.00000000', 'isAutoAddMargin': 'false', 'positionSide': 'BOTH', 'notional': '714.05128479'},

**Comment by kroitor** [comment]
@AsadullahSoomro replied in your original issue here: https://github.com/ccxt/ccxt/issues/8311#issuecomment-764278642, let's keep it in the original issue for less duplication.
