### ISSUE TITLE
The field `amount` in CoinEx transactions is the sum of both amount and fee

### ISSUE THREAD

**Issue by xenohunter** [ccxt/ccxt#8321]
- OS: Arch Linux
- Programming Language version: Python 3.8.5
- CCXT version: 1.38.48 (initially was found in 1.37.34)

While requesting deposits and withdrawals from CoinEx, the raw data from the exchange (that which is then stored in the `info` field of the CCXT transaction object) contains fields `amount` and `actual_amount`. Here, `amount` is the sum of transaction amount and its fee while `actual_amount` is only the amount itself.

Because of this, the final returning value is inconsistent with that from other exchanges. I think it would be better to use amount from the `actual_amount` field in the final CCXT transaction object.

**Comment by kroitor** [comment]
@xenohunter please, see this answer: https://github.com/ccxt/ccxt/pull/8335#issuecomment-766156984
We will add more on that to the Manual, to make it less confusing.

**Comment by kroitor** [comment]
Added a few clarifications here: https://github.com/ccxt/ccxt/blob/master/wiki/Manual.md#transaction-fees

**Comment by kroitor** [comment]
@xenohunter after having another discussion with the contributors, we think that it makes sense to unify the amounts as net amounts, so you're right, we will fix CoinEx parsing method shortly.

**Comment by xenohunter** [comment]
@kroitor, thank you very much!
