### ISSUE TITLE
Binance Coin Future quantity min amount limit and precision issue

### ISSUE THREAD

**Issue by koradiyakaushal** [ccxt/ccxt#8322]
- OS: Windows
- Programming Language version: python 3.8.7
- CCXT version: 1.40.23

```
import ccxt
exchange = ccxt.binance({
    'apiKey': API_key,
    'secret': Secret_key,
    # 'timeout': 30000,
    'enableRateLimit': True,
    'hedgeMode': False,
    'options': {
        'defaultType': 'delivery',  # testnet urls work with futures
    }
})
markets = exchange.load_markets()
exchange.verbose = True
print(exchange.create_order("ETH/USD", "market", "buy", 0.02, price=None, params={}))
```

```
Request: POST https://dapi.binance.com/dapi/v1/order {'X-MBX-APIKEY': '', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate'} timestamp=1611236325992&recvWindow=5000&symbol=ETHUSD_PERP&type=MARKET&side=BUY&quantity=0&signature=

Response: POST https://dapi.binance.com/dapi/v1/order 400 {'Content-Type': 'application/json', 'Content-Length': '47', 'Connection': 'keep-alive', 'Date': 'Thu, 21 Jan 2021 13:38:47 GMT', 'Server': 'Tengine', 'X-MBX-USED-WEIGHT-1M': '2', 'X-MBX-ORDER-COUNT-1M': '1', 'x-response-time': '1ms', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'origin-when-cross-origin', 'Strict-Transport-Security': 'max-age=31536000; 
includeSubdomains', 'X-Cache': 'Error from cloudfront'} {"code":-4003,"msg":"Quantity less than zero."}

ccxt.base.errors.ExchangeError: binance {"code":-4003,"msg":"Quantity less than zero."}
```

I am trying to create a market order with coin futures ETH USD pair. I have 0.02 ETH in my account, 

main error quantity is less than zero from binance but when ccxt calls binance we are passing quantity 0, so it looks precision and limits is problem

limits for ETHUSD : {'amount': {'min': 1.0, 'max': 100000.0}, 'price': {'min': 0.01, 'max': 100000.0}, 'cost': {'min': None, 'max': None}, 'market': {'min': 1.0, 'max': 100000.0}}  

Precision for ETHUSD: {'base': 8, 'quote': 8, 'amount': 0, 'price': 2}

it looks it fails below condition:
Order amount >= limits['min']['amount']

does that mean we can't create an order for ETHUSD for less than 1 ETH?

**Comment by kroitor** [comment]
@koradiyakaushal when trading ETH/USD contracts, you are not buying or selling ETH or USD. You're buying and selling whole ETHUSD contracts (it's not a pair, it's a single thing). Therefore you can't buy a fraction of a contract. You cannot buy 0.5 contract, 0.1 contract and so on. You can only buy and sell contracts in whole quantities, like 1, 2, 3, etc.
You can see that the amount precision for Binance is 0, meaning 0 decimal digits are allowed.
This is covered in the Manual here: https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits

Let us know if that does not answer your question.

**Comment by koradiyakaushal** [comment]
@kroitor thanks for the clarification, but i am sure for coin m futures in binance we can purchase with base asset. In binance there is option to select unit preference for contract/base asset. i am adding screenshot. problem with contract is it's varying based on each pairs for Ex. For BtcUsd it's 100 usd/1 contract. although for EthUsd it's 10usd/1 contract. 
Reference : https://www.binance.com/in/support/faq/a4470430e3164c13932be8967961aede

![IMG_20210122_223459.jpg](https://user-images.githubusercontent.com/36811899/105521642-2eb71400-5d02-11eb-84a2-901d060236e5.jpg) 

i have been already using LinkUsd perpetual with size in link and it's working fine. also binance is allowing quantity in decimal for coin futures. let me know if we can override the unified method or binance method.

**Comment by kroitor** [comment]
@koradiyakaushal once again, with Binance's API you can only order whole quantities of contracts. You can pay with USDT or with the base coin for the contracts depending on your settings on the exchange website, but you cannot buy a half of a contract with the API anyway:

- https://binance-docs.github.io/apidocs/delivery/en/#new-order-trade

```Python
from pprint import pprint
import ccxt

exchange = ccxt.binance({
    'enableRateLimit': True,
    'options': {
        'defaultType': 'delivery',
    }
})
markets = exchange.load_markets()
pprint(exchange.markets['ETH/USD'])
```

```Python
{'active': True,
 'base': 'ETH',
 'baseId': 'ETH',
 'delivery': True,
 'future': False,
 'id': 'ETHUSD_PERP',
 'info': {'baseAsset': 'ETH',
          'baseAssetPrecision': 8,
          'contractSize': 10,
          'contractStatus': 'TRADING',
          'contractType': 'PERPETUAL',
          'deliveryDate': 4133404800000,
          'equalQtyPrecision': 4,
          'filters': [{'filterType': 'PRICE_FILTER',
                       'maxPrice': '100000',
                       'minPrice': '0.01',
                       'tickSize': '0.01'},
                      {'filterType': 'LOT_SIZE',
                       'maxQty': '100000',
                       'minQty': '1',  # ←------------------------------------------------------- min 1
                       'stepSize': '1'},  # ←------------------------------------------------------- step 1
                      {'filterType': 'MARKET_LOT_SIZE',
                       'maxQty': '100000',
                       'minQty': '1',
                       'stepSize': '1'},
                      {'filterType': 'MAX_NUM_ORDERS', 'limit': 200},
                      {'filterType': 'MAX_NUM_ALGO_ORDERS', 'limit': 100},
                      {'filterType': 'PERCENT_PRICE',
                       'multiplierDecimal': '4',
                       'multiplierDown': '0.8500',
                       'multiplierUp': '1.1500'}],
          'maintMarginPercent': '2.5000',
          'marginAsset': 'ETH',
          'onboardDate': 1597734000000,
          'orderTypes': ['LIMIT',
                         'MARKET',
                         'STOP',
                         'STOP_MARKET',
                         'TAKE_PROFIT',
                         'TAKE_PROFIT_MARKET',
                         'TRAILING_STOP_MARKET'],
          'pair': 'ETHUSD',
          'pricePrecision': 2,
          'quantityPrecision': 0,
          'quoteAsset': 'USD',
          'quotePrecision': 8,
          'requiredMarginPercent': '5.0000',
          'symbol': 'ETHUSD_PERP',
          'timeInForce': ['GTC', 'IOC', 'FOK', 'GTX'],
          'triggerProtect': '0.0500',
          'underlyingSubType': [],
          'underlyingType': 'COIN'},
 'limits': {'amount': {'max': 100000.0, 'min': 1.0},
            'cost': {'max': None, 'min': None},
            'market': {'max': 100000.0, 'min': 1.0},
            'price': {'max': 100000.0, 'min': 0.01}},
 'lowercaseId': 'ethusd_perp',
 'maker': 0.001,
 'margin': True,
 'percentage': True,
 'precision': {'amount': 0, 'base': 8, 'price': 2, 'quote': 8},
 'quote': 'USD',
 'quoteId': 'USD',
 'spot': False,
 'symbol': 'ETH/USD',
 'taker': 0.001,
 'tierBased': False,
 'type': 'delivery'}
 ```
 
 Let me know if the above does not answer your question.

**Comment by koradiyakaushal** [comment]
@kroitor thanks for quick response. let me share the coin futures LinkUsd perpetual example with code snippet and binance screenshot.

**Comment by koradiyakaushal** [comment]
@kroitor I understood how it was working for LINKUSD. in the backend they are converting base coin to contracts, link has only 10USD/1 Contract. and my unit preference in binance was a coin. Do you have any idea about how we can change the unit of preference via API for Binance coin futures? because they affect the order. right now we need to manually update that. also, is it possible to pass quantity as a percentage of wallet balance while creating an order? Thanks for your time.

**Comment by kroitor** [comment]
> Do you have any idea about how we can change the unit of preference via API for Binance coin futures?

Tbh, I don't think it's possible, at this time with the current version of Binance's API.

> also, is it possible to pass quantity as a percentage of wallet balance while creating an order?

Binance and CCXT will not do this for you, but will give you the instruments to do it in the userland. You can fetch the balance as described in the CCXT Manual, multiply it by your percentage value and then place the order using the result from the previous step. I'm pretty sure there's no other way of doing it with Binance (or any other exchange) right now.

**Comment by Eternal-Sunshine** [comment]
It was working earlier with 1$ also. Binance suddenly changed the rule. 
We got panicked in the team. 
It got clarified now.

**Comment by robzer** [comment]
hi @kroitor on the same topic of futures on binance, it sounds silly but i cannot get the transfer call to work. code below.

OS:mac
Programming Language version: python 3.5.2
CCXT version: latest

```

bfut = ccxt.binance({
    'apiKey': '',
    'secret': '',
    'enableRateLimit': True,
    'options': {
        'defaultType': 'future',  # ←-------------- quotes and 'future'
    },
})

code = 'USDT'
amount = 1.45

bfut.sapi_get_futures_transfer({'asset': code, 'amount': amount, 'type': 1})

```
i get the below error

``` 

ExchangeError: binance {"code":-6016,"msg":"Parameter err"}


Request: GET https://api.binance.com/sapi/v1/futures/transfer?timestamp=1618700915662&recvWindow=5000&asset=USDT&amount=1.45&type=1&signature=c28dc5bd0175198016 {'X-MBX-APIKEY': 'UCAC', 'User-Agent': 'python-requests/2.23.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.binance.com/sapi/v1/futures/transfer?timestamp=1618700915662&recvWindow=5000&asset=USDT&amount=1.45&type=1&signature=c299823288dc54e56a7db6b175c2 400 {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '36', 'Connection': 'keep-alive', 'Date': 'Sat, 17 Apr 2021 23:08:35 GMT', 'Server': 'nginx', 'X-SAPI-USED-IP-WEIGHT-1M': '10', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 9c84783d5ba0d7f283d777ded10c791a.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'DFW3-C1', 'X-Amz-Cf-Id': 'U0H8redpWiiSonIsgW1Od7DzFvhYLlmUt5VhYnquTd3XJ-5yjFcstQ=='} {"code":-6016,"msg":"Parameter err"}
---------------------------------------------------------------------------

**Comment by kroitor** [comment]
@robzer don't confuse GET with POST:

- https://binance-docs.github.io/apidocs/spot/en/#user-universal-transfer

> POST /sapi/v1/asset/transfer and GET /sapi/v1/asset/transfer.

**Comment by kroitor** [comment]
@robzer 

```Python
bfut.sapi_post_futures_transfer({
    'asset': code,
    'amount': bfut.currency_to_precision(code, amount),
    'type': 'MAIN_UMFUTURE' // see https://binance-docs.github.io/apidocs/spot/en/#user-universal-transfer
})
```

@robzer lmk if that does not help

**Comment by robzer** [comment]
of course, sorry about his, zzz i need sleep. thx for the quick answer.
Ah thanks for flagging the universal transfer feature. Will definitely consider it.
