### ISSUE TITLE
phemex fetch_balance not showing contract USD account balances?

### ISSUE THREAD

**Issue by adamrg73** [ccxt/ccxt#8325]
I noticed in the verbose output link it says spot/wallets, I wonder if we just need to change it to contract/wallets.. I will look at phemex API, but if you know how to get contract balances please let me know..I am using sandbox/testnet for this test btw..
thanks

Request: GET https://testnet-api.phemex.com/spot/wallets {'x-phemex-access-token': '8af89d75-6d56-4c07-aaf6-4ec038d74f29', 'x-phemex-request-expiry': '1611269103', 'x-phemex-request-signature': '32b200703e745cbf73ee62289fe00c88c5148b03c5fa28b8ba61feec6f101888', 'User-Agent': 'python-requests/2.24.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://testnet-api.phemex.com/spot/wallets 200 {'Content-Type': 'application/json', 'Content-Length': '279', 'Connection': 'keep-alive', 'Date': 'Thu, 21 Jan 2021 22:44:03 GMT', 'Set-Cookie': 'AWSALB=TD9paDU7FopSNnvjUTv8tm2SDl5juLPyPiwlRJbss3bvNSfxyl+XIZv7cxdXr75T3VLRZEZnWU3+rfhkq31Cc3Xbpla0nvekJBhNjfRRStnm8UFy5Io39qBNXdIj; Expires=Thu, 28 Jan 2021 22:44:03 GMT; Path=/, AWSALBCORS=TD9paDU7FopSNnvjUTv8tm2SDl5juLPyPiwlRJbss3bvNSfxyl+XIZv7cxdXr75T3VLRZEZnWU3+rfhkq31Cc3Xbpla0nvekJBhNjfRRStnm8UFy5Io39qBNXdIj; Expires=Thu, 28 Jan 2021 22:44:03 GMT; Path=/; SameSite=None', 'Server': 'nginx', 'x-phemex-request-tracing': '0ba49b7b-5368-4eeb-997b-ace2e9c3cddb', 'X-RateLimit-Remaining': '196', 'X-RateLimit-Capacity': '200', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate, no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Xss-Protection': '1; mode=block', 'X-Frame-Options': 'SAMEORIGIN', 'X-Content-Type-Options': 'nosniff', 'Referrer-Policy': 'origin-when-cross-origin', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 df34174e06a3ec2969f1c48a3cd66ca3.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'EWR52-C4', 'X-Amz-Cf-Id': '4OsmHYaH47VwBud2-M0tAPpk0PZ1Ci_0HdtMuDNe5-KOEwvapKwvsA=='} {"code":0,"msg":"","data":[{"currency":"BTC","balanceEv":50000000,"lockedTradingBalanceEv":0,"lockedWithdrawEv":0,"lastUpdateTimeNs":1611199887409902877,"walletVid":0},{"currency":"USDT","balanceEv":490000000000,"lockedTradingBalanceEv":0,"lockedWithdrawEv":0,"lastUpdateTimeNs":1611200091089478396,"walletVid":0},{"currency":"ETH","balanceEv":0,"lockedTradingBalanceEv":0,"lockedWithdrawEv":0,"lastUpdateTimeNs":1611199887409902877,"walletVid":0},{"currency":"XRP","balanceEv":0,"lockedTradingBalanceEv":0,"lockedWithdrawEv":0,"lastUpdateTimeNs":1611199887409902877,"walletVid":0},{"currency":"LINK","balanceEv":0,"lockedTradingBalanceEv":0,"lockedWithdrawEv":0,"lastUpdateTimeNs":1611199887409902877,"walletVid":0},{"currency":"XTZ","balanceEv":0,"lockedTradingBalanceEv":0,"lockedWithdrawEv":0,"lastUpdateTimeNs":1611199887409902877,"walletVid":0},{"currency":"LTC","balanceEv":0,"lockedTradingBalanceEv":0,"lockedWithdrawEv":0,"lastUpdateTimeNs":1611199887409902877,"walletVid":0},{"currency":"ADA","balanceEv":0,"lockedTradingBalanceEv":0,"lockedWithdrawEv":0,"lastUpdateTimeNs":1611199887409902877,"walletVid":0},{"currency":"TRX","balanceEv":0,"lockedTradingBalanceEv":0,"lockedWithdrawEv":0,"lastUpdateTimeNs":1611199887409902877,"walletVid":0},{"currency":"ONT","balanceEv":0,"lockedTradingBalanceEv":0,"lockedWithdrawEv":0,"lastUpdateTimeNs":1611199887409902877,"walletVid":0},{"currency":"BCH","balanceEv":0,"lockedTradingBalanceEv":0,"lockedWithdrawEv":0,"lastUpdateTimeNs":1611199887409902877,"walletVid":0},{"currency":"NEO","balanceEv":0,"lockedTradingBalanceEv":0,"lockedWithdrawEv":0,"lastUpdateTimeNs":1611199887409902877,"walletVid":0},{"currency":"EOS","balanceEv":0,"lockedTradingBalanceEv":0,"lockedWithdrawEv":0,"lastUpdateTimeNs":1611199887409902877,"walletVid":0}]}
{'info': {'code': 0, 'msg': '', 'data': [{'currency': 'BTC', 'balanceEv': 50000000, 'lockedTradingBalanceEv': 0, 'lockedWithdrawEv': 0, 'lastUpdateTimeNs': 1611199887409902877, 'walletVid': 0}, {'currency': 'USDT', 'balanceEv': 490000000000, 'lockedTradingBalanceEv': 0, 'lockedWithdrawEv': 0, 'lastUpdateTimeNs': 1611200091089478396, 'walletVid': 0}, {'currency': 'ETH', 'balanceEv': 0, 'lockedTradingBalanceEv': 0, 'lockedWithdrawEv': 0, 'lastUpdateTimeNs': 1611199887409902877, 'walletVid': 0}, {'currency': 'XRP', 'balanceEv': 0, 'lockedTradingBalanceEv': 0, 'lockedWithdrawEv': 0, 'lastUpdateTimeNs': 1611199887409902877, 'walletVid': 0}, {'currency': 'LINK', 'balanceEv': 0, 'lockedTradingBalanceEv': 0, 'lockedWithdrawEv': 0, 'lastUpdateTimeNs': 1611199887409902877, 'walletVid': 0}, {'currency': 'XTZ', 'balanceEv': 0, 'lockedTradingBalanceEv': 0, 'lockedWithdrawEv': 0, 'lastUpdateTimeNs': 1611199887409902877, 'walletVid': 0}, {'currency': 'LTC', 'balanceEv': 0, 'lockedTradingBalanceEv': 0, 'lockedWithdrawEv': 0, 'lastUpdateTimeNs': 1611199887409902877, 'walletVid': 0}, {'currency': 'ADA', 'balanceEv': 0, 'lockedTradingBalanceEv': 0, 'lockedWithdrawEv': 0, 'lastUpdateTimeNs': 1611199887409902877, 'walletVid': 0}, {'currency': 'TRX', 'balanceEv': 0, 'lockedTradingBalanceEv': 0, 'lockedWithdrawEv': 0, 'lastUpdateTimeNs': 1611199887409902877, 'walletVid': 0}, {'currency': 'ONT', 'balanceEv': 0, 'lockedTradingBalanceEv': 0, 'lockedWithdrawEv': 0, 'lastUpdateTimeNs': 1611199887409902877, 'walletVid': 0}, {'currency': 'BCH', 'balanceEv': 0, 'lockedTradingBalanceEv': 0, 'lockedWithdrawEv': 0, 'lastUpdateTimeNs': 1611199887409902877, 'walletVid': 0}, {'currency': 'NEO', 'balanceEv': 0, 'lockedTradingBalanceEv': 0, 'lockedWithdrawEv': 0, 'lastUpdateTimeNs': 1611199887409902877, 'walletVid': 0}, {'currency': 'EOS', 'balanceEv': 0, 'lockedTradingBalanceEv': 0, 'lockedWithdrawEv': 0, 'lastUpdateTimeNs': 1611199887409902877, 'walletVid': 0}]}, 'BTC': {'free': 0.5, 'used': 0.0, 'total': 0.5}, 'USDT': {'free': 4900.0, 'used': 0.0, 'total': 4900.0}, 'ETH': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'XRP': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'LINK': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'XTZ': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'LTC': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'ADA': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'TRX': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'ONT': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'BCH': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'NEO': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'EOS': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'free': {'BTC': 0.5, 'USDT': 4900.0, 'ETH': 0.0, 'XRP': 0.0, 'LINK': 0.0, 'XTZ': 0.0, 'LTC': 0.0, 'ADA': 0.0, 'TRX': 0.0, 'ONT': 0.0, 'BCH': 0.0, 'NEO': 0.0, 'EOS': 0.0}, 'used': {'BTC': 0.0, 'USDT': 0.0, 'ETH': 0.0, 'XRP': 0.0, 'LINK': 0.0, 'XTZ': 0.0, 'LTC': 0.0, 'ADA': 0.0, 'TRX': 0.0, 'ONT': 0.0, 'BCH': 0.0, 'NEO': 0.0, 'EOS': 0.0}, 'total': {'BTC': 0.5, 'USDT': 4900.0, 'ETH': 0.0, 'XRP': 0.0, 'LINK': 0.0, 'XTZ': 0.0, 'LTC': 0.0, 'ADA': 0.0, 'TRX': 0.0, 'ONT': 0.0, 'BCH': 0.0, 'NEO': 0.0, 'EOS': 0.0}}

**Comment by adamrg73** [comment]
I had to look through and track down the code for a while to figure out this what I needed to do.. this is the correct way yes?

params={"type":"swap","code":"USD"}
response = exchange.fetch_balance(params=params)
print(response)
print('response USD')
print(response['USD'])

...
response USD
{'free': 98.6436, 'used': 0.0, 'total': 98.6436}

**Comment by kroitor** [comment]
@adamrg73 yes, that is the correct code to use it, Phemex's API requires a currency code to fetch specific positions and balances. Thank you for reporting back! I'm sure it will help other users as well!

**Comment by adamrg73** [comment]
Ok good to know! Thanks again! Im glad to contribute!

**Comment by fmgit** [comment]
Thanks

> I had to look through and track down the code for a while to figure out this what I needed to do.. this is the correct way yes?
> 
> params={"type":"swap","code":"USD"} response = exchange.fetch_balance(params=params) print(response) print('response USD') print(response['USD'])
> 
> ... response USD {'free': 98.6436, 'used': 0.0, 'total': 98.6436}

Very helpful, thank you!

**Comment by jackRoark** [comment]
> I had to look through and track down the code for a while....
> params={"type":"swap","code":"USD"} 

Awesome. How did you figure out "type" should be "swap" and not "contract"?

**Comment by jackRoark** [comment]
nevermind, all set. (note to self: RTFM)
