### ISSUE TITLE
[yobit] calculateFee looks wrong

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#8326]
I believe the fee for trades in yobit is always in the quote currency.  There is code in `calculateFee` that switches between base and quote based on side.  I'm wondering why this is here?

**Comment by kroitor** [comment]
>  I'm wondering why this is here?

Most likely, for historical reasons...

> I believe the fee for trades in yobit is always in the quote currency.

Are you sure? If yes, we will change yobit's code to match.

**Comment by npomfret** [comment]
yep, it looks that way.  i've added up hundreds of transactions, and with the fee as it is now I get quite a big error.  changing the fee so its the quote ccy reduces the error significantly (but doesn't eliminate it - i think the exchange sometimes treats buys as sells)
