### ISSUE TITLE
[FTX] fetch_my_trades only shows most recent 200 trades

### ISSUE THREAD

**Issue by jtfarks** [ccxt/ccxt#8327]
- OS: Ubuntu
- Programming Language version: python
- CCXT version: 1.4.86

```
ftx = ccxt.ftx({
   'apiKey': apiKeys.ftx_exch_key,
   'secret': apiKeys.ftx_exch_secret,
})

if exchange.has['fetchMyTrades']:
       
        raw_data = exchange.fetch_my_trades(symbol=None, since=1602288000, limit=200, params={})
```

What I am trying to do if get all trades from a predefined time (i.e how i assumed since would work). However it will only show me the most recent 200 trades since that time, not the oldest trades which would allow me to paginate. I cant work out how to paginate with this as the last datetime in the output is the most recent trade and not the most recent of the oldest 200. 

Is there a work around?

**Comment by jtfarks** [comment]
Looks like I fixed it myself.

I had already tried changing :
```
limit=200.
```
and that had no impact.
What I had to do was increase it and then pass something along the lines of 

```
params={'end_time': float(datetime.timestamp(now)),})

```
in the function and it gave me the full history. I still cant work out how to do the pagination in reverse, but I no longer need to.

**Comment by kroitor** [comment]
@jtfarks i was writing the example with `end_time` as you posted ) Just to confirm – this is a "known issue" with FTX. Thx for reporting back! Don't hesitate if you have further questions or issues.

**Comment by jtfarks** [comment]
Thanks for that. Is there a list of known issues anywhere? I had a feeling it might have been an issue with the FTX api and so dug out the end_time from their API docks. 

I looked here to see if there were any notes refering to anything, but couldn't see anything.

https://github.com/ccxt/ccxt/blob/master/python/ccxt/ftx.py

**Comment by kroitor** [comment]
In general, you can find a list of all related issues here:

- https://github.com/ccxt/ccxt/issues
- https://github.com/ccxt/ccxt/issues?q=ftx

That specific issue was not on the list, but we were aware of it, and we will probably add a default value of end_time = now to `fetchMyTrades` shortly.
