### ISSUE TITLE
bybit  parseOrder() average price is inverted for USDT markets

### ISSUE THREAD

**Issue by furryboffin** [ccxt/ccxt#8328]
I have having to do averagePrice = 1/order.average  for USDT markets to get the right average price for market orders.  This is due to the difference in the nature of the two types of contracts on bybit. BTCUSD contracts and BTCUSDT contracts are fundamentally different.

**Comment by furryboffin** [comment]
There is no need for example code because it's such a simple problem.

**Comment by furryboffin** [comment]
I forgot to mention. I am using the javascript version, and I am on the latest version.  ccxt@1.40.86

**Comment by frosty00** [comment]
has since been fixed

**Comment by furryboffin** [comment]
Just got stung by this LOL. updated CCXT on my bot and forgot about my hack to fix it...
