### ISSUE TITLE
fetch_trades sorts by timestamp

### ISSUE THREAD

**Issue by ManuelSchneid3r** [ccxt/ccxt#8329]
![image](https://user-images.githubusercontent.com/3252315/105514693-17613200-5cd4-11eb-8442-af08267dedb3.png)

This is a bunch of trades which I get from Binance. This violates my assertions of  increasing ids.
This is not what binance delivers:

https://api.binance.com/api/v3/aggTrades?symbol=BTCUSDT&fromId=1195414&limit=3
```json
[
  {
    "a": 1195414,
    "p": "11498.75000000",
    "q": "0.00490100",
    "f": 1291817,
    "l": 1291817,
    "T": 1512378391578,
    "m": false,
    "M": true
  },
  {
    "a": 1195415,
    "p": "11498.56000000",
    "q": "0.08170400",
    "f": 1291818,
    "l": 1291818,
    "T": 1512378392510,
    "m": false,
    "M": true
  },
  {
    "a": 1195416,
    "p": "11498.75000000",
    "q": "0.00490100",
    "f": 1291817,
    "l": 1291817,
    "T": 1512378391578,
    "m": false,
    "M": true
  }
]
```

What is the problem here?

**Comment by kroitor** [comment]
@ManuelSchneid3r when parsing aggregate trades, the trade id is set to the value of `a`, and then all resulting trades are sorted by timestamp `T`. The problem is that Binance will return an aggregate having an id > previous id, and a timestamp < previous timestamp. Does that answer your question?

**Comment by ManuelSchneid3r** [comment]
Sure but why are they sorted?

**Comment by kroitor** [comment]
@ManuelSchneid3r we will add an exchange-specific option for Binance to leave the aggregates unsorted (or sorted by ids in the order returned from Binance by default).

**Comment by kroitor** [comment]
@ManuelSchneid3r the above behavior is also documented in the Manual on fetchTrades. Let us know if that does not answer your question. Feel free to reopen it or just ask further questions if any.
