### ISSUE TITLE
Not appear buy/sell

### ISSUE THREAD

**Issue by dynarian** [ccxt/ccxt#8330]
I want to take the market data from ex. kraken, I use this code, but I do not see in the result that it includes the purchase and sale price of the cryptocurrencies.
Is there any function to get the value of BTC / EUR in kraken in real time or that of BTC / EUR in various exchanges in real time?
Thanks !!, I use PHP.

$root = dirname (dirname (dirname (__FILE__)));
include $root . '/ccxt.php';
$id = 'kraken';
$exchange = '\\ccxt\\' . $id;
$empresa = new $exchange ();
$res =var_dump ($empresa->load_markets ());

**Comment by kroitor** [comment]
Hi! Please, read the Manual from top to bottom and see the examples – everything is already explained in detail there:

- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki/Manual#price-tickers
- https://github.com/ccxt/ccxt/wiki/Manual#order-book
- https://github.com/ccxt/ccxt/tree/master/examples/php/

Let us know if you have further questions after the above.
