### ISSUE TITLE
Howto ???

### ISSUE THREAD

**Issue by dynarian** [ccxt/ccxt#8334]
I need to be able to make the exchange variable to get data from its market.
My code is...

$exchange = new \ccxt\kraken(array (
    'verbose' => false,
    'timeout' => 30000,
));

Thanks!!

**Comment by kroitor** [comment]
Please, read the Manual and see the examples, it's all covered there:

- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/tree/master/examples

Let us know if that does not answer your question.

**Comment by dynarian** [comment]
Igor, not exist refetence for my question in the documentation. In my
example code have modify kraken for variable data, but no exist reference
about this in the manual.

**Comment by kroitor** [comment]
@dynarian 

```PHP
$exchange = new \ccxt\kraken(array (
    'enableRateLimit' => true,
));

// you have initialized the exchange
// now use it to issue your calls as documented in the Manual
// for example ...

var_dump($exchange->fetchTicker('ETH/BTC'));

var_dump($exchange->fetchOrderBook('ETH/BTC'));

var_dump($exchange->fetchTrades('ETH/BTC'));

// your other code and calls here ...
```

All of the above is documented in the Manual.

**Comment by dynarian** [comment]
Ok, not understand my question. I need change exchange in the code say

$exchange = new \ccxt\kraken...

Need kraken in variable data...

**Comment by kroitor** [comment]
@dynarian ok, but this is also covered in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#instantiation

```PHP
$id = 'kraken'; // your variable
$exchange_class = '\\ccxt\\' . $id
$exchange = new $exchange(array(
    'enableRateLimit': true,
});
```

↑ This is not really a question about using CCXT, it's more like a question on how to use PHP.

**Comment by dynarian** [comment]
Ok. Thanks 4 U patients

**Comment by kroitor** [comment]
@dynarian i'd highly recommend taking a look here: 

- https://github.com/ccxt/ccxt/tree/master/examples/
- https://github.com/ccxt/ccxt/tree/master/examples/php/

Let us know if that does not help.
