### ISSUE TITLE
Inconsistent symbol names for Binance Futures

### ISSUE THREAD

**Issue by projenix** [ccxt/ccxt#8339]
- OS: Linux
- Programming Language version: Python 3.8.6 and Python 3.8.5
- CCXT version: 1.40.83
- 
Code:
```
exchange.load_markets()
symbols = exchange.symbols
print(symbols)
```
In my workstation it gives: 
```
['1INCHUSDT', 'AAVEUSDT', 'ADAUSDT', 'AKROUSDT', 'ALGOUSDT', 'ALPHAUSDT', 'ATOMUSDT', 'AVAXUSDT', 'AXSUSDT', 'BALUSDT', 'BANDUSDT', 'BATUSDT', 'BCHUSDT', 'BELUSDT', 'BLZUSDT', 'BNBUSDT', 'BTCBUSD', 'BTCUSDT', 'BZRXUSDT', 'CHZUSDT', 'COMPUSDT', 'CRVUSDT', 'CTKUSDT', 'CVCUSDT', 'DASHUSDT', 'DEFIUSDT', 'DOGEUSDT', 'DOTECOUSDT', 'DOTUSDT', 'EGLDUSDT', 'ENJUSDT', 'EOSUSDT', 'ETCUSDT', 'ETHUSDT', 'FILUSDT', 'FLMUSDT', 'FTMUSDT', 'GRTUSDT', 'HNTUSDT', 'ICXUSDT', 'IOSTUSDT', 'IOTAUSDT', 'KAVAUSDT', 'KNCUSDT', 'KSMUSDT', 'LINKUSDT', 'LRCUSDT', 'LTCUSDT', 'MATICUSDT', 'MKRUSDT', 'NEARUSDT', 'NEOUSDT', 'OCEANUSDT', 'OMGUSDT', 'ONTUSDT', 'QTUMUSDT', 'RENUSDT', 'RLCUSDT', 'RSRUSDT', 'RUNEUSDT', 'SKLUSDT', 'SNXUSDT', 'SOLUSDT', 'SRMUSDT', 'STORJUSDT', 'SUSHIUSDT', 'SXPUSDT', 'THETAUSDT', 'TOMOUSDT', 'TRBUSDT', 'TRXUSDT', 'UNIUSDT', 'VETUSDT', 'WAVESUSDT', 'XLMUSDT', 'XMRUSDT', 'XRPUSDT', 'XTZUSDT', 'YFIIUSDT', 'YFIUSDT', 'ZECUSDT', 'ZENUSDT', 'ZILUSDT', 'ZRXUSDT']

```
But in the server (with same ccxt version but python 3.8.5) it gives:

```
['1INCH/USDT', 'AAVE/USDT', 'ADA/USDT', 'AKRO/USDT', 'ALGO/USDT', 'ALPHA/USDT', 'ATOM/USDT', 'AVAX/USDT', 'AXS/USDT', 'BAL/USDT', 'BAND/USDT', 'BAT/USDT', 'BCH/USDT', 'BEL/USDT', 'BLZ/USDT', 'BNB/USDT', 'BTC/BUSD', 'BTC/USDT', 'BZRX/USDT', 'CHZ/USDT', 'COMP/USDT', 'CRV/USDT', 'CTK/USDT', 'CVC/USDT', 'DASH/USDT', 'DEFI/USDT', 'DOGE/USDT', 'DOT/USDT', 'DOTECO/USDT', 'EGLD/USDT', 'ENJ/USDT', 'EOS/USDT', 'ETC/USDT', 'ETH/USDT', 'FIL/USDT', 'FLM/USDT', 'FTM/USDT', 'GRT/USDT', 'HNT/USDT', 'ICX/USDT', 'IOST/USDT', 'IOTA/USDT', 'KAVA/USDT', 'KNC/USDT', 'KSM/USDT', 'LINK/USDT', 'LRC/USDT', 'LTC/USDT', 'MATIC/USDT', 'MKR/USDT', 'NEAR/USDT', 'NEO/USDT', 'OCEAN/USDT', 'OMG/USDT', 'ONT/USDT', 'QTUM/USDT', 'REN/USDT', 'RLC/USDT', 'RSR/USDT', 'RUNE/USDT', 'SKL/USDT', 'SNX/USDT', 'SOL/USDT', 'SRM/USDT', 'STORJ/USDT', 'SUSHI/USDT', 'SXP/USDT', 'THETA/USDT', 'TOMO/USDT', 'TRB/USDT', 'TRX/USDT', 'UNI/USDT', 'VET/USDT', 'WAVES/USDT', 'XLM/USDT', 'XMR/USDT', 'XRP/USDT', 'XTZ/USDT', 'YFI/USDT', 'YFII/USDT', 'ZEC/USDT', 'ZEN/USDT', 'ZIL/USDT', 'ZRX/USDT']

```
This is currently breaking my deployment, any idea how to fix?

Edit:

Also on one place it's saying symbol is BTC/USDT and on another place it's saying the symbol is BTCUSDT:

```
'id': 'BTCUSDT',
		'lowercaseId': 'btcusdt',
		'symbol': 'BTC/USDT',
		'base': 'BTC',
		'quote': 'USDT',
		'baseId': 'BTC',
		'quoteId': 'USDT',
		'info': {
			'symbol': 'BTCUSDT',
...

```

**Comment by kroitor** [comment]
Hi!

> This is currently breaking my deployment, any idea how to fix?

Run this on both of your machines and paste your runtime versions here please:

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
```

**Comment by projenix** [comment]
Hey your intuition was correct!

On the workstation I've got version: 1.35.72

Whereas on the server I've got version: 1.40.83

So I assume there was a change in symbol notation in CCXT, right? so is that change stable now, should I upgrade and stick to "AAA/BBB" notation from now on in all code?

Thanks a lot for your help,

**Comment by kroitor** [comment]
@projenix 

> So I assume there was a change in symbol notation in CCXT, right? 

Yes, Binance has updated their API recently.

> so is that change stable now, should I upgrade and stick to "AAA/BBB" notation from now on in all code?

The unification of futures is a work in progress, so it may be subject to change, but we will of course do our best to avoid breaking changes, or will announce them beforehand.

Let us know if that does not answer your question. Feel free to reopen it if needed or just ask further questions if any.

**Comment by projenix** [comment]
@kroitor That does answer my question, thank you very much for your help.
