### ISSUE TITLE
bybit: sign error for conditional market orders when stop/base price is a round number

### ISSUE THREAD

**Issue by daikts** [ccxt/ccxt#8340]
- OS: Ubuntu 20.04
- Programming Language version: Python 3.9
- CCXT version: 1.40.94

Hey Igor,

This seems pretty crazy to have gone by without being reported so I'm hoping this is either an incoming API change or an unexpected dependency upgrade that's suddenly causing. But in either case, this is what I'm seeing:

```python
import ccxt

bybit = ccxt.bybit()
bybit.apiKey = "cox"
bybit.secret = "dix"
bybit.urls["api"] = bybit.urls["test"]

bybit.create_order("BTC/USD", "Market", "buy", 16,
                   params={
                       'order_link_id': "peen",
                       'stop_px': 31320.0,
                       'base_price': 31319.0,
                       'trigger_by': 'LastPrice'
                   })
```

Error:
```
ExchangeError: bybit {"ret_code":10004,"ret_msg":"error sign! origin_string[api_key=<redacted>\u0026base_price=31319.0\u0026order_link_id=peen\u0026order_type=Market\u0026qty=16\u0026recv_window=5000\u0026side=Buy\u0026stop_px=31320.0\u0026symbol=BTCUSD\u0026time_in_force=GoodTillCancel\u0026timestamp=1611516960917\u0026trigger_by=LastPrice]","ext_code":"","ext_info":"","result":null,"time_now":"1611516961.337532"}
```

What's bizarre is that this is only happening if the stopPx/base_price is a round number (no decimal). So in the example above, it should succeed if the prices are `31320.5` and `31319.5`. I dug into the py source code, and tried casting the params to ints beforehand, and that seems to fix it:

Adding this after L1293 in bybit.py (sorry don't have time to find it in the JS source):
```python
                if request["stop_px"] == round(request["stop_px"]):
                    request["stop_px"] = int(request["stop_px"])
                if request["base_price"] == round(request["base_price"]):
                    request["base_price"] = int(request["base_price"])
```

Is this an edge case in the signing algo? Or one of my params throwing the system off? New weirdness on testnet? It was certainly not happening before (I upgrade ccxt recently). Happy to file a PR if you (or anyone else) can confirm there is a bug here.

**Comment by kroitor** [comment]
@daikts just to make sure, please, run the snippet below and paste your runtime output (not `pip list`!). This is a known problem with Bybit, we will get it resolved, but first we need to rule out versioning issues:

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
```

**Comment by daikts** [comment]
Found this, seems legit: 
https://github.com/verata-veritatis/pybit/blob/master/pybit/__init__.py#L1258

**Comment by daikts** [comment]
Yep, version confirmed from running that snippet:
`CCXT Version: 1.40.94`

**Comment by kroitor** [comment]
@daikts i mean,

> Found this, seems legit:
> https://github.com/verata-veritatis/pybit/blob/master/pybit/__init__.py#L1258

I mean, we have this: 

- https://github.com/ccxt/ccxt/blob/master/js/bybit.js#L2202
- https://github.com/ccxt/ccxt/issues/7377
- https://github.com/ccxt/ccxt/issues/7515

Bybit does not like zeroed decimals, however it makes exceptions for stopPrice for some reason. They might have changed or fixed this bug on their side – I will debug it and will get back to you asap!

**Comment by daikts** [comment]
^ doesn't that bit of code fail due to the fact that the query is left unchanged, while auth is modified? I think we need to replace that in both?

**Comment by kroitor** [comment]
> ^ doesn't that bit of code fail due to the fact that the query is left unchanged, while auth is modified? I think we need to replace the .0 with nothing both in the query as well as auth?

I thought so too, but after spending a few sleepless nights a few months ago, i'm pretty sure it's the way they do it on the exchange side (I know it's crazy – ask them why).

Can you plz post your verbose output? It will help speed up the fix:

```Python
import ccxt

bybit = ccxt.bybit()
bybit.apiKey = "cox"
bybit.secret = "dix"
bybit.urls["api"] = bybit.urls["test"]
bybit.enableRateLimit = True  # as required in the Manual

markets = bybit.load_markets()

bybit.verbose = True  # after loading the markets

bybit.create_order("BTC/USD", "Market", "buy", 16,
                   params={
                       'order_link_id': "peen",
                       'stop_px': 31320.0,
                       'base_price': 31319.0,
                       'trigger_by': 'LastPrice'
                   })
```

**Comment by daikts** [comment]
You got it, cheers for jumping on this so quick:
```
Request: POST https://api-testnet.bybit.com/v2/private/stop-order/create {'Content-Type': 'application/json', 'Accept-Encoding': 'gzip, deflate'} {"side":"Buy","symbol":"BTCUSD","order_type":"Market","qty":16,"time_in_force":"GoodTillCancel","order_link_id":"peen123","stop_px":31320.0,"base_price":31319.0,"trigger_by":"LastPrice","api_key":"<redacted>","recv_window":5000,"timestamp":1611518252337,"sign":"e1cb17a8da8f1e0d80aa157407e677d7655126968d06fe861142ea72d4ffe761"}

Response: POST https://api-testnet.bybit.com/v2/private/stop-order/create 200 {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '408', 'Expires': 'Sun, 24 Jan 2021 19:57:32 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Sun, 24 Jan 2021 19:57:32 GMT', 'Connection': 'keep-alive'} {"ret_code":10004,"ret_msg":"error sign! origin_string[api_key=<redacted>\u0026base_price=31319.0\u0026order_link_id=peen123\u0026order_type=Market\u0026qty=16\u0026recv_window=5000\u0026side=Buy\u0026stop_px=31320.0\u0026symbol=BTCUSD\u0026time_in_force=GoodTillCancel\u0026timestamp=1611518252337\u0026trigger_by=LastPrice]","ext_code":"","ext_info":"","result":null,"time_now":"1611518252.808444"}
```

**Comment by kroitor** [comment]
@daikts thx for quick reports!

The last thing I wanted to ask, can you plz try this snippet on your side and let me know if it makes a difference:

```Python
import ccxt

class Mybit(ccxt.bybit):
    def sign(self, path, api='public', method='GET', params={}, headers=None, body=None):
        url = self.implode_params(self.urls['api'], {'hostname': self.hostname})
        type = self.safe_string(api, 0)
        section = self.safe_string(api, 1)
        request = '/' + type + '/' + section + '/' + path
        # public v2
        if section == 'public':
            if params:
                request += '?' + self.rawencode(params)
        elif type == 'public':
            if params:
                request += '?' + self.rawencode(params)
        else:
            self.check_required_credentials()
            timestamp = self.nonce()
            query = self.extend(params, {
                'api_key': self.apiKey,
                'recv_window': self.options['recvWindow'],
                'timestamp': timestamp,
            })
            auth = self.rawencode(self.keysort(query))
            signature = self.hmac(self.encode(auth), self.encode(self.secret))
            if method == 'POST':
                body = self.json(self.extend(query, {
                    'sign': signature,
                }))
                headers = {
                    'Content-Type': 'application/json',
                }
            else:
                request += '?' + auth + '&sign=' + signature
        url += request
        return {'url': url, 'method': method, 'body': body, 'headers': headers}

bybit = Mybit()
bybit.apiKey = "cox"
bybit.secret = "dix"
bybit.set_sandbox_mode(True)
bybit.enableRateLimit = True  # as required in the Manual

markets = bybit.load_markets()

bybit.verbose = True  # after loading the markets

bybit.create_order("BTC/USD", "market", "buy", 16,
                   params={
                       'order_link_id': "peen",
                       'stop_px': 31320.0,
                       'base_price': 31319.0,
                       'trigger_by': 'LastPrice'
                   })
```

↑ If this works for you, i'll upload the fix immediately.

**Comment by kroitor** [comment]
@daikts Bybit's API wasn't too good at first, which is why we had to add a workaround, but now they have fixed it, apparently, and the workaround is not necessary anymore, so they're making progress towards a better API. I'll push the fix in a few minutes.  Thx for your feedback!
