### ISSUE TITLE
Error in logic for FTX edit_order

### ISSUE THREAD

**Issue by alexander3605** [ccxt/ccxt#8346]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: MacOS BigSur 11.1
- Programming Language version: Python 3.8.6
- CCXT version: 1.40.77
---
Hi! There is an issue with the function
```python
ccxt.async_support.ftx.edit_order()
```
I get the following error when providing the `id` to the function (or the `client_order_id` through the params dictionary)
```
  File "/Users/alse/myprj/broker.py", line 178, in edit_order
    await self._exchange.edit_order(
  File "/Users/alse/myprj/.venv/lib/python3.8/site-packages/ccxt/async_support/ftx.py", line 1174, in edit_order
    response = await getattr(self, method)(self.extend(request, params))
  File "/Users/alse/myprj/.venv/lib/python3.8/site-packages/ccxt/async_support/base/exchange.py", line 95, in fetch2
    return await self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Users/alse/myprj/.venv/lib/python3.8/site-packages/ccxt/async_support/base/exchange.py", line 153, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/Users/alse/myprj/.venv/lib/python3.8/site-packages/ccxt/async_support/ftx.py", line 1742, in handle_errors
    self.throw_broadly_matched_exception(self.exceptions['broad'], error, feedback)
  File "/Users/alse/myprj/.venv/lib/python3.8/site-packages/ccxt/base/exchange.py", line 509, in throw_broadly_matched_exception
    raise broad[broad_key](message)
ccxt.base.errors.ExchangeNotAvailable: ftx {"error":"An unexpected error occurred, please try again later (4D5D1E8A00).","success":false}
```

### Proposed fix
The code for the function has a bug aroung line 1162. The code is now as follows:
```python
        else:
            if clientOrderId is None:
                method = 'privatePostOrdersByClientIdClientOrderIdModify'
                request['client_order_id'] = clientOrderId
                # request['clientId'] = clientOrderId
            else:
                method = 'privatePostOrdersOrderIdModify'
                request['order_id'] = id
```
As you can see above, when `clientOrderId is None` the `clientOrderId` is used, and viceversa `id` is used when `clientOrderId` is valid. This makes the API URL to be always `https://ftx.com/api/orders/by_client_id/None/modify` (unless both `id` and `clientOrderId` are specified, which is not ideal).

My proposed fix (tested and working) is to simply switch the body of the two branches of the if-else statement, as follows
```python
        else:
            if clientOrderId is None:
                method = 'privatePostOrdersOrderIdModify'
                request['order_id'] = id
            else:
                method = 'privatePostOrdersByClientIdClientOrderIdModify'
                request['client_order_id'] = clientOrderId
                # request['clientId'] = clientOrderId
```

**Comment by kroitor** [comment]
@alexander3605 thank you for reporting it!

**Comment by alexander3605** [comment]
Thank you @kroitor!! 🚀 🚀
