### ISSUE TITLE
Async CCXT Pro with Classes Questions:

### ISSUE THREAD

**Issue by me1029134** [ccxt/ccxt#8347]
Python Version: Python 3.8.5
CCXT Pro version: 0.5.42
CCXT version: 1.41.3
Running on: Windows and Linux

THANK YOU for your help! I've been stuck on this problem for a week or two.  It's probably mostly related to my code and me not being familiar with asyncio and less anything to do with CCXT but I would GREATLY appreciate any help or advice on the error or anything else that you see that can be improved. .

Overview:  I'm trying to look at the websocket prices (using CCXT Pro), and place orders asynchronously (with Async CCXT and not rate limit, as I'll be doing this on my side). Price data is coming in through websockets, and going out with async rest calls. 

Main Problem: If I don't "await asyncio.sleep(5)" after I initialize the async exchange class I get an error:
"Exception has occurred: AttributeError: 'CcxtAsyncExchange' object has no attribute 'markets'"

Main Questions:
1. Am I going about this class thing all wrong? Is there a better approach?
2. Should I be using __aenter__ in the class? Should I not be using an __init__?
3. When I stop the program or it crashes. What's the best way to close the exchange class? Should I put "asyncio.run(self.exchange.close())" in a "__del__(self)" / destructor?
4. Should I or can I combine by Async CCXT with CCXT Pro? But not have a rate limiter on the Async CCXT and Do have a rate limiter on CCXT Pro (Because I think it stops working if I don't). 

Below is a simple version of the Class and the Main Program (PYTHON):
"main_program.py"
``` 
import asyncio
from exchange_class import CcxtAsyncExchange as ccxt_async_exchange
from exchange_class import CcxtProExchange as ccxt_pro_exchange

async def buy_coins(exchange_accxt, event):
    while True:
        try:
            await event.wait()
            event.clear()
            if 'ETH/USDT' in exchange_accxt.ticks.keys() and 'BTC/USDT' in exchange_accxt.ticks.keys(): 
                if exchange_accxt.ticks['ETH/USDT']['bid'] > exchange_accxt.ticks['BTC/USDT']['bid'] / 10:
                    order1 = asyncio.create_task( exchange_accxt.create_order('ETH/USDT', 'Market', 'buy', .1) )
                    order2 = asyncio.create_task( exchange_accxt.create_order('BTC/USDT', 'Market', 'sell', .1) )
                    order1_return = await order1
                    order2_return = await order2
        except:
            pass

async def update_current_price(websocket_exchange, exchange_accxt, symbol, event):
    while True:
        try:
            ticker = await websocket_exchange.watch_ticker(symbol)
            event.set()
            exchange_accxt.ticks[symbol] = ticker 
        except:
            pass

async def main(loop):
    exchange_id = 'binanceus'
    symbols = ['BTC/USDT', 'ETH/USDT']

    exchange_accxt = ccxt_async_exchange(loop, exchange_id)
    await asyncio.sleep(5) # I need this for some reason. Can't figure it out :(
    print(exchange_accxt.markets)
    websocket_exchange = ccxt_pro_exchange(exchange_id)
    
    event = asyncio.Event()

    tasks = [ update_current_price(websocket_exchange.websocket_exchange, exchange_accxt, symbol, event) for symbol in symbols ]
    tasks.append(buy_coins(exchange_accxt, event) )
    await asyncio.gather(*tasks)

if __name__ == '__main__':
    #asyncio.run(main(loop), debug=True)
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main(loop))
```
"exchange_class.py"
```
import ccxt.async_support as accxt
import ccxtpro

# Async Class
class CcxtAsyncExchange(): # Would it be better if I herit ccxt.async_support?
    def __init__(self, loop, exchange_id = 'binance'):
        #asyncio.run(self.create(exchange_id)) #Doing this becuase you can't have await outside an async function. And can't make __init__ async
        loop.create_task(self.create(exchange_id))

    # Do I need to do something with __aenter__ instead of __init__?
    
    def __exit__(self): # Is this the correct way to close, when I abruptly stop code (Ctrl-C)?... Thank you.
        asyncio.run(self.exchange.close())

    async def create(self, exchange_id):
        exchange_class = getattr(accxt, exchange_id) 
        self.exchange = exchange_class({
            "apiKey": "API", 
            "secret": "SECRET",
            'verbose': True,
            #'enableRateLimit': True, # would like to make trades concurently, and handle the rate limit on my side.
        }) 

        self.markets = await self.load_markets() 
        self.balances = await self.fetch_balance()
        self.ticks = {}

    async def load_markets(self):    
        return await self.exchange.load_markets()

    async def fetch_balance(self):    
        return await self.exchange.fetch_balance()

    async def create_order(self, symbol, type, side, amount, price=None, params={}):
        print('order happening')    
        return await self.exchange.create_order(symbol, type, side, amount, price=None, params={})


# CCXT PRO Class
class CcxtProExchange(): # Would it be better if I herit ccxt.async_support
    def __init__(self, exchange_id = 'binance'):
        # Setup websockets with CCXT_PRO
        websocket_exchange_class = getattr(ccxtpro, exchange_id)  
        self.websocket_exchange = websocket_exchange_class({
            'enableRateLimit': True,
            'verbose': True,
            'options': {
                'watchTicker': {'name': 'bookTicker'},
            },
        })

    def __exit__(self):
        asyncio.run(self.websocket_exchange.close() ) # not sure if that's correct
```

```
ERROR:
Error: Line 54: Exception has occurred: AttributeError: 'CcxtAsyncExchange' object has no attribute 'markets'
```

Thank you for all your amazing work and help! I really appreciate it!

**Comment by frosty00** [comment]
>     print(exchange_accxt.markets)

this is the reason you are getting the attribute markets not found. in your code you import some classes which are not derived from ccxt:

```
from exchange_class import CcxtAsyncExchange as ccxt_async_exchange
from exchange_class import CcxtProExchange as ccxt_pro_exchange
```

and you haven't defined the markets on these classes... nothing to do with ccxt

```
def __exit__(self):
        asyncio.run(self.websocket_exchange.close() ) # not sure if that's correct
```
     
this is not correct for multiple reasons, the first is that `__exit__` is only used to exit a context manager (think of the `with` statement. secondly, `asyncio.run` will open a new event loop, instead you want to use the current loop to close it.

> Below is a simple version of the Class and the Main Program (PYTHON):

this is hardly a simple program! you can remove the `await event` statements and design it in a different way.

**Comment by kroitor** [comment]
@me1029134 I'll post a proper example here on how to use ws ccxt.pro + rest ccxt, hold on.

**Comment by me1029134** [comment]
Thanks, @frosty00 I really appreciate your help!

Sorry for the length of the program. :\ The real program is much longer :). 

Are you saying my exchange interface class (the second program file above) should be derived from CCXT (or maybe CCXT Pro)? If I was going to add a custom log function and maybe some other things, should it still be a class inherited from CCXT (Pro Maybe)?

That makes sense about the __exit__ I'll pass the current loop into the object and then do "self.websocket_exchange.close()" Thank you!

@kroitor Thank you. Yeah if you have an example, I would greatly appreciate it. I'm still confused probably about having classes with Asyncio and why I need that "await asyncio.sleep(5)" line, or it doesn't work. (seems like it should be waiting already)... Thank you very much!

**Comment by frosty00** [comment]
you can take a look at the examples here https://github.com/ccxt/ccxt/tree/master/examples/ccxt.pro/py

**Comment by me1029134** [comment]
Thanks @frosty00, I'll read those examples again. 

I guess the main question would be. If I want to have a rate limit on my websockets (because I think I have to, correct?... seems like it doesn't work if I don't). And use a Async Rest approach without a Rate Limit. Should I define one CCXT Pro object, and one Async CCXT Obj? Is that correct?

**Comment by me1029134** [comment]
Thanks
