### ISSUE TITLE
exchange.symbols and exchange.fetch_currencies() both empty?

### ISSUE THREAD

**Issue by epignatelli** [ccxt/ccxt#8351]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: MacOs
- Programming Language version: Python 3.8
- CCXT version: 1.40.63

```
import ccxt

ccxt.bitmex().symbols
ccxt.bitmex().fetch_currencies()
```

```
# symbols
{}
# currencies
{}
```

**Comment by kroitor** [comment]
Please, read the Manual, it will save you a ton of time: 

- https://github.com/ccxt/ccxt/wiki/Manual#loading-markets
- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki

Also, see the examples here:

- https://github.com/ccxt/ccxt/tree/master/examples/

Let us know if you have further questions after that.
