### ISSUE TITLE
auth/calc/deriv/collateral/limits to be added to bitfinex2.py

### ISSUE THREAD

**Issue by uncentral** [ccxt/ccxt#8359]
'auth/calc/deriv/collateral/limits', to be added to bitfinex2.py

- OS: Windows 10
- Programming Language version: Python
- CCXT version: 1.41.5

```
print(bitfinexFtr.private_post_auth_calc_deriv_collateral_limits())
```

```
print(bitfinexFtr.private_post_auth_calc_deriv_collateral_limits())
AttributeError: 'bitfinex2' object has no attribute 'private_post_auth_calc_deriv_collateral_limits'```

**Comment by oscar562** [comment]
> 'auth/calc/deriv/collateral/limits', to be added to bitfinex2.py
> 
> - OS: Windows 10
> - Programming Language version: Python
> - CCXT version: 1.41.5
> 
> ```
> print(bitfinexFtr.private_post_auth_calc_deriv_collateral_limits())
> ```
> 
> ```
> print(bitfinexFtr.private_post_auth_calc_deriv_collateral_limits())
> AttributeError: 'bitfinex2' object has no attribute 'private_post_auth_calc_deriv_collateral_limits'```
>
