### ISSUE TITLE
Mixed-up balance info in BTC Markets

### ISSUE THREAD

**Issue by cogat** [ccxt/ccxt#836]
`cctx.btcmarkets().fetch_balances()` uses the following code to return balances:

            free = float(balance['balance'] / multiplier)
            used = float(balance['pendingFunds'] / multiplier)
            account = {
                'free': free,
                'used': used,
                'total': self.sum(free, used),
            }

However `balance['balance']` is the total balance, not the free balance. The code should be:

            total = float(balance['balance'] / multiplier)
            used = float(balance['pendingFunds'] / multiplier)
            account = {
                'total': total,
                'used': used,
                'free': self.sum(total, -used)
            }

**Comment by kroitor** [comment]
Thanks for reporting, will fix right away!

**Comment by kroitor** [comment]
Fixed in 1.10.370. Let us know if you have any other difficulties with it! And thanks again for a thorough report!
