### ISSUE TITLE
Create an order in the binance test net with php

### ISSUE THREAD

**Issue by federosso** [ccxt/ccxt#8360]
Hello
I would like to test binance orders with php
I tried to use this code but it doesn't work:

`$exchange = new $exchange_id (array (
    'apiKey' => $key, 
    'secret' => $secret,
    'set_sandbox_mode' => True,
    // 'private' => 'https://testnet.binance.vision/api/v3/order',
    'private' => 'https://testnet.binance.vision/api/v3',
));

$symbol = 'EUR / USDT';
$type = 'market';
$side = 'sell';
$amount = 10;

$params = array (
    'test' => True,
);

$order = $ exchange-> create_order ($symbol, $type, $side, null, $amount, $params);

print_r ($order);`

I get this error: [Exchange Error] binance {"code": - 2015, "msg": "Invalid API-key, IP, or permissions for action."}

The api key I entered are those generated in the binance net spot test: https://testnet.binance.vision
This means that the commands: 'private' => 'https://testnet.binance.vision/api/v3', 'test' => True, 'set_sandbox_mode' => True,
they are not recognized and therefore CCXT always refers to real binance servers. in fact if I use the api key of my real account
[Exchange Error] binance {"code": - 1013, "msg": "Invalid quantity."} (Because I don't have funds for that coin pair).

What parameters do I need to set in $exchange to use the binance net test?
can you give me some examples in php?
thanks a lot

**Comment by kroitor** [comment]
@federosso hi!

You should switch to the sandbox mode using a method call (not an exchange property):

```PHP
$exchange = new $exchange_id (array (
    'apiKey' => $key, 
    'secret' => $secret,
    'enableRateLimit' => true, // https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
));

$exchange->set_sandbox_mode(true);

$symbol = 'EUR / USDT';
$type = 'market';
$side = 'sell';
$amount = 10;

$params = array (
    'test' => True,
);

$order = $ exchange-> create_order ($symbol, $type, $side, null, $amount, $params);

print_r ($order);
```

More info here:

- https://github.com/ccxt/ccxt/wiki
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/tree/master/examples/

Let us know if that does not help or does not answer your question. Feel free to reopen it or just ask further questions if any.

**Comment by kroitor** [comment]
P.S. edited the snippet above slightly.

**Comment by federosso** [comment]
fantastic now it's great!
Thanks so much

`
try {

    $exchange = new $exchange_id (array (
        'apiKey' => $key, // ←------------ replace with your keys
        'secret' => $secret, 
        'enableRateLimit' => true, // https://github.com/ccxt/ccxt/wiki/Manual#rate-limi      
    ));

    $exchange->set_sandbox_mode(true); // imposta la chiamata al server di simulazione


    $markets = $exchange->load_markets(true); // force to reload chache
    //print_r ($markets);

    echo "<br>Available Market: ";
    foreach ($markets as $arr_key => $arr_val) {

        // seleziono solo le coppie su cui è possibile fare trading
        if(($arr_val["info"]["status"] == "TRADING")&&( $arr_val["spot"] = 1)){
            echo "<br>".$arr_key." , ".$arr_val["info"]["filters"][2]["minQty"];
        }
    }

    
    echo "<br>Available Balance: ";
    $balance = $exchange->fetch_balance();
    //print_r ($balance);

    foreach ($balance["info"]["balances"] as $id => $val) {

        echo "<br>".$val["asset"].": ".$val["free"];
    }

        
    $symbol = 'BNB/USDT';
    $type = 'market'; // # or 'market', or 'Stop' or 'StopLimit'
    $side = 'sell'; // or 'buy'
    $amount = 100;


    $order = $exchange->create_order ($symbol, $type, $side, $amount);
    echo "<br>"; 
    print_r ($order);
    

} catch (\ccxt\NetworkError $e) {
    echo '[Network Error] ' . $e->getMessage () . "\n";
} catch (\ccxt\ExchangeError $e) {
    echo '[Exchange Error] ' . $e->getMessage () . "\n";
} catch (Exception $e) {
    echo '[Error] ' . $e->getMessage () . "\n";
}

`
