### ISSUE TITLE
Binance futures testnet errors in latest ccxt version

### ISSUE THREAD

**Issue by Gennttii** [ccxt/ccxt#8365]
I had an older ccxt version and it was all working okay, but now I updated to latest version and nothing is working..

At first I got this error : 
`{ AuthenticationError: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action, request ip: xx.xx.xx.xx"}`
Then after searching found this and the error didn't show anymore:
`exchange.set_sandbox_mode(true)  `

When I try to create an order I get this error: 
`{ ExchangeError: binance {"code":-2019,"msg":"Margin is insufficient."}`

When I try to set leverage to 100 I get this error :
``{ ExchangeError: binance {"code":-4028,"msg":"Leverage 100 is not valid"}`

And there can be other errors that I have not figured yet..

How to fix these?

**Comment by kroitor** [comment]
Hi!

Please, paste your runtime info: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help



> At first I got this error :
> `{ AuthenticationError: binance {"code":-2015,"msg":"Invalid API-key, IP, or permissions for action, request ip: xx.xx.xx.xx"}`
> Then after searching found this and the error didn't show anymore:
> `exchange.set_sandbox_mode(true)`

Is your intent to you the Binance testnet or the Binance production server? The rule is simple, you have to use the testnet keys if you switch to the sandbox testnet, and vice versa.

> When I try to create an order I get this error:
> `{ ExchangeError: binance {"code":-2019,"msg":"Margin is insufficient."}`

That error message literally says itself. What's the question about it?

> When I try to set leverage to 100 I get this error :
> `{ ExchangeError: binance {"code":-4028,"msg":"Leverage 100 is not valid"}`

Same thing here. Can you tell which specific part of it is not clear?

**Comment by Gennttii** [comment]
I want to use Binance futures testnet. How do I fix the first error. Does it mean my IP is banned? Should I set sandboxmode to true to use Futures Testnet?

About the other errors, they are simple, I have sufficient margin , thats why I am asking why is this error. Second one, why the leverage 100 is not valid when you can change it up to 125 for BTCBUSD pair..

**Comment by Gennttii** [comment]
Before these errors , after update I was getting error for the `BTC/USDT` pair when creating order: 
`{ BadSymbol: binance {"code":-1121,"msg":"Invalid symbol."}`

So I thought Binance changed this pair to `BTC/BUSD`,

But not working.. How do I fix the `BadSymbol` error when creating an order with the pair `BTC/USDT`?

**Comment by kroitor** [comment]
Let's start with the basics, change for your futures-testnet keys and paste your output:

```JavaScript
const ccxt = require ('./ccxt')

console.log ('CCXT Version:', ccxt.version)

async function main () {
    const exchange = new ccxt.binance({
        'apiKey': 'YOUR_FUTURES_TESTNET_API_KEY',
        'secret': 'YOUR_FUTURES_TESTNET_SECRET',
        'enableRateLimit': true,
        'options': { 'defaultType': 'future' },
    })
    
    exchange.setSandboxMode (true)
    
    await exchange.loadMarkets ()
        
    const balance = await exchange.fetchBalance()
    console.log ('Balance:')
    console.log (balance)
    console.log ('------------------------------------------------')
    
    const response = await exchange.fapiPrivateGetLeverageBracket ()
    
    const responseByMarketId = exchange.indexBy (response, 'symbol')
    
    const symbol = 'BTC/USDT'
    const market = exchange.market (symbol)
    
    const leverageBracket = exchange.safeValue (responseByMarketId, market['id'])
    console.log ('Leverage bracket for', symbol)
    console.log (leverageBracket)
    
}

main()
```

**Comment by Gennttii** [comment]
CCXT Version: 1.41.12
Balance:
{ info:
   { feeTier: 0,
     canTrade: true,
     canDeposit: true,
     canWithdraw: true,
     updateTime: 0,
     totalInitialMargin: '284.62574248',
     totalMaintMargin: '113.85029699',
     totalWalletBalance: '9907.07569534',
     totalUnrealizedProfit: '20.64508121',
     totalMarginBalance: '9927.72077655',
     totalPositionInitialMargin: '284.62574248',
     totalOpenOrderInitialMargin: '0.00000000',
     totalCrossWalletBalance: '9907.07569534',
     totalCrossUnPnl: '20.64508121',
     availableBalance: '9643.09503407',
     maxWithdrawAmount: '9643.09503407',
     assets: [ [Object], [Object], [Object] ],
     positions:
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        ... 88 more items ] },
  USDT:
   { free: 9643.09503407, used: 284.62574248, total: 9927.72077655 },
  BNB: { free: 0, used: 0, total: 0 },
  BUSD: { free: 0, used: 0, total: 0 },
  free: { USDT: 9643.09503407, BNB: 0, BUSD: 0 },
  used: { USDT: 284.62574248, BNB: 0, BUSD: 0 },
  total: { USDT: 9927.72077655, BNB: 0, BUSD: 0 } }
------------------------------------------------
Leverage bracket for BTC/USDT
{ symbol: 'BTCUSDT_210326',
  brackets:
   [ { bracket: 1,
       initialLeverage: 125,
       notionalCap: 50000,
       notionalFloor: 0,
       maintMarginRatio: 0.004,
       cum: 0 },
     { bracket: 2,
       initialLeverage: 100,
       notionalCap: 250000,
       notionalFloor: 50000,
       maintMarginRatio: 0.005,
       cum: 50 },
     { bracket: 3,
       initialLeverage: 50,
       notionalCap: 1000000,
       notionalFloor: 250000,
       maintMarginRatio: 0.01,
       cum: 1300 },
     { bracket: 4,
       initialLeverage: 20,
       notionalCap: 5000000,
       notionalFloor: 1000000,
       maintMarginRatio: 0.025,
       cum: 16300 },
     { bracket: 5,
       initialLeverage: 10,
       notionalCap: 20000000,
       notionalFloor: 5000000,
       maintMarginRatio: 0.05,
       cum: 141300 },
     { bracket: 6,
       initialLeverage: 5,
       notionalCap: 50000000,
       notionalFloor: 20000000,
       maintMarginRatio: 0.1,
       cum: 1141300 },
     { bracket: 7,
       initialLeverage: 4,
       notionalCap: 100000000,
       notionalFloor: 50000000,
       maintMarginRatio: 0.125,
       cum: 2391300 },
     { bracket: 8,
       initialLeverage: 3,
       notionalCap: 200000000,
       notionalFloor: 100000000,
       maintMarginRatio: 0.15,
       cum: 4891300 },
     { bracket: 9,
       initialLeverage: 2,
       notionalCap: '9223372036854775807',
       notionalFloor: 200000000,
       maintMarginRatio: 0.25,
       cum: 24891300 } ] }

**Comment by Gennttii** [comment]
Also when I try to open an order like like this : 
` await exchange.createOrder (  "BTC/USDT", 'market', 'sell', 1, undefined , { positionSide: 'SHORT' })`

shows me this error : `{ BadSymbol: binance {"code":-1121,"msg":"Invalid symbol."}`

I always opened orders with this symbol `"BTC/USDT"`, Idk what changed..!

**Comment by kroitor** [comment]
@Gennttii i think i see where that bug comes from, will push a fix shortly, please, hold on.

**Comment by darklago** [comment]
Hi
I have the same problem today with Invalid symbol on BTC/USDT so yesterday it works...

**Comment by kroitor** [comment]
@Gennttii @darklago please, update to CCXT version 1.41.17 (the new build will arrive in 20 minutes) and let us know if you still have this issue.

**Comment by darklago** [comment]
> @Gennttii @darklago please, update your CCXT to version 1.41.17 (the new build will arrive in 20 minutes) and let us know if you still have this issue.

It work thanks

**Comment by kroitor** [comment]
Thanks for your feedback!

**Comment by darklago** [comment]
> Thanks for your feedback!

but now bid_price and bid_volume is empty and it wasn't with the previous version

**Comment by kroitor** [comment]
@darklago plz paste your code+verbose output: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by darklago** [comment]
` $market = $binancefab->fetch_ticker($pair);				
            var_dump($market);
            $PrixMarket = $market["info"]["bidPrice"];
            //$PrixMarket = $market["info"]["lastPrice"];`

`array(20) {
  ["symbol"]=>
  string(8) "BTC/USDT"
  ["timestamp"]=>
  int(1611935091810)
  ["datetime"]=>
  string(24) "2021-01-29T15:44:51.810Z"
  ["high"]=>
  float(38641.1)
  ["low"]=>
  float(31660)
  ["bid"]=>
  NULL
  ["bidVolume"]=>
  NULL
  ["ask"]=>
  NULL
  ["askVolume"]=>
  NULL
  ["vwap"]=>
  float(35069.14)
  ["open"]=>
  float(31973.67)
  ["close"]=>
  float(37188.58)
  ["last"]=>
  float(37188.58)
  ["previousClose"]=>
  NULL
  ["change"]=>
  float(5214.91)
  ["percentage"]=>
  float(16.31)
  ["average"]=>
  NULL
  ["baseVolume"]=>
  float(613728.193)
  ["quoteVolume"]=>
  float(21522920351.76)
  ["info"]=>
  array(16) {
    ["symbol"]=>
    string(7) "BTCUSDT"
    ["priceChange"]=>
    string(7) "5214.91"
    ["priceChangePercent"]=>
    string(6) "16.310"
    ["weightedAvgPrice"]=>
    string(8) "35069.14"
    ["lastPrice"]=>
    string(8) "37188.58"
    ["lastQty"]=>
    string(5) "0.001"
    ["openPrice"]=>
    string(8) "31973.67"
    ["highPrice"]=>
    string(8) "38641.10"
    ["lowPrice"]=>
    string(8) "31660.00"
    ["volume"]=>
    string(10) "613728.193"
    ["quoteVolume"]=>
    string(14) "21522920351.76"
    ["openTime"]=>
    int(1611848640000)
    ["closeTime"]=>
    int(1611935091810)
    ["firstId"]=>
    int(447417346)
    ["lastId"]=>
    int(452503914)
    ["count"]=>
    int(5081542)
  }
}
`

**Comment by kroitor** [comment]
@darklago how do you initialize the exchange instance?

**Comment by kroitor** [comment]
@darklago inside the ticker you have the `info` structure, which is the response returned from the exchange as is, untouched. As you can see, there's no way to deduce bidPrice and bidVolume from the ticker info returned by Binance with this endpoint.

**Comment by kroitor** [comment]
@darklago more about it here: https://github.com/ccxt/ccxt/wiki/Manual#ticker-structure

**Comment by darklago** [comment]
I tried this morning with lastest version 1.41.28 and it seems solved. thanks
