### ISSUE TITLE
FTX  /wallet/all_balances

### ISSUE THREAD

**Issue by mlshin** [ccxt/ccxt#8367]
Hi

Python 3.7
ccxt~=1.40.77
FTX

I could not find to get all balance from all account on FTX
Could you please help me about this ?

GET /wallet/all_balances
https://docs.ftx.com/#get-balances-of-all-accounts

**Comment by kroitor** [comment]
1. Update to the most recent version of CCXT.
2. Try the snippet below.
3. Let us know if that does not help

```Python
import ccxt
from pprint import pprint

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.ftx({
    'enableRateLimit': True,
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})

response = exchange.private_get_wallet_all_balances()
pprint(response)
```

**Comment by kroitor** [comment]
More about it here:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

**Comment by mlshin** [comment]
> More about it here:
> 
> * https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

Thank you so much.
