### ISSUE TITLE
Invalid Symbol

### ISSUE THREAD

**Issue by UsmanKhOkhar16** [ccxt/ccxt#8368]
OS: Windows 10
python version: Python 3.8.5
Programming Language: Python3
CCXT version: 1.41.13
Exchange: Binance Testnet

Hi, when I am using symbol "BTCUSDT", It is generating an error that "Binance does not have market symbol BTCUSDT". And When I am using symbol "BTC/USDT", It is generating me error when I am placing buy order that is "binance {"code":-1121,"msg":"Invalid symbol."}" also it is not showing me proper results like I have 4 buy orders in the Open Orders, but it is showing me Null when I am using function "fetch_open_orders".
I am getting this problem from 2 to 3 days, before that It was working fine.
Please help about this.
Thanks.
Regards Usman KhOkhar

The code I am using is mention Below:
**import ccxt
Binance_Testnet = ccxt.binance({
     'apiKey': api, 
    'secret': secret, 
    'enableRateLimit': True, 
    'options': {'defaultType': 'future',},
})
Binance_Testnet.set_sandbox_mode(True)
symbol = "BTC/USDT"
open_order = Binance_Testnet.fetch_open_orders(symbol=symbol)
print("Open : " , open_order)
Binance_Testnet.create_limit_buy_order(symbol, quantity_per_order, buy_value)**

**Output:**

Open :  []
Exchange error raised. Details below:
 binance {"code":-1121,"msg":"Invalid symbol."}

![image](https://user-images.githubusercontent.com/68140597/106349199-df6a7800-62ed-11eb-9751-212f4e92e339.png)

**Comment by kroitor** [comment]
Hi! Please, update to the most recent version and let us know if that does not resolve your issue.

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
