### ISSUE TITLE
Increase Rate Limit for FTX(US)

### ISSUE THREAD

**Issue by Jay54520** [ccxt/ccxt#8369]
Current rate limit is 100, can increase to 1000 // 30 = 33;
> Please do not send more than 30 requests per second: doing so will result in HTTP 429 errors.

https://docs.ftx.us/#rate-limits
https://docs.ftx.com/#rate-limits

**Comment by kroitor** [comment]
@Jay54520 please, check this section on rate-limiting here: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit, it is documented that by default `rateLimit` is set to a slightly sub-optimal default and you can override it how you want.

```Python
import ccxt
exchange = ccxt.ftx({
    'enableRateLimit': True,
    'rateLimit': 34
})

# or 

exchange.rateLimit = 33
```

You can override all properties like that and this is also covered here: 

- https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties
- https://github.com/ccxt/ccxt/wiki/Manual#overriding-exchange-properties-upon-instantiation

Let us know if that does not answer your question.
