### ISSUE TITLE
FTX Heartbeat

### ISSUE THREAD

**Issue by mlshin** [ccxt/ccxt#8371]
ccxt~=1.40.77
python  = 3.7

Hi 
is there any heartbeat method for FTX to check connection is alive or dead ?

**Comment by kroitor** [comment]
@mlshin hi! CCXT is a RESTful lib, everytime it makes a request – there's either a new connection or an old connection is reused. The lifetime of a HTTPs connection is driven by the underlying keepAlive flag.
Let us know if that does not answer your question.
