### ISSUE TITLE
PHP Binance loadMarkets() | Warning: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by weerdenburg** [ccxt/ccxt#8373]
- OS: Herkoku stack 20
- Programming Language version: PHP 7.4.x
- CCXT version: 1.40.80

```
$classname = '\\ccxt\\binance';
$ccxtExchange = new $classname($options);
$ccxtExchange->enableRateLimit = true;
if ($loadMarkets) {
      $ccxtExchange->loadMarkets(); <= The ErrorException was triggered here.
}
```

```
ErrorException
Warning: count(): Parameter must be an array or an object that implements Countable

/app/vendor/ccxt/ccxt/php/binance.php in ccxt\binance::fetch_markets at line 725

 $markets = $this->safe_value($response, 'symbols');
$result = array();
for ($i = 0; $i < count($markets); $i++) { <= The ErrorException occurred here.
      $market = $markets[$i];
```

It seems that Binance did not send a correct response and therefore this loop failed.
I think it would be good if there would be a check on $markets so a more clear Exception could be thrown, or retry? Or whatever is more suitable.

I had a few of these errors in my Sentry logs, so it's not a big deal, but I think it would be good, if it will be fixed.

**Comment by kroitor** [comment]
@weerdenburg hi! Do you have the same issue with the most recent version of the lib?
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

**Comment by ExaByt3s** [comment]
PHP 7.3.26-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Jan 13 2021 08:00:44)
CCXT v.1.41.64

the same error happens to me 


  count(): Parameter must be an array or an object that implements Countable

  at vendor/ccxt/ccxt/php/binance.php:762
    758|             $this->load_time_difference();
    759|         }
    760|         $markets = $this->safe_value($response, 'symbols');
    761|         $result = array();
  > 762|         for ($i = 0; $i < count($markets); $i++) {
    763|             $market = $markets[$i];
    764|             $spot = ($type === 'spot');
    765|             $future = ($type === 'future');
    766|             $delivery = ($type === 'delivery');

**Comment by kroitor** [comment]
@ExaByt3s do you have this with the most recent version of the lib?

**Comment by frosty00** [comment]
> CCXT v.1.41.64

**Comment by kroitor** [comment]
@ExaByt3s paste your output with version 1.41.80:

<?php

date_default_timezone_set ('UTC');

echo 'CCXT v' . \ccxt\Exchange::VERSION . "\n";

$exchange_class = '\\ccxt\\binance';
$exchange = new $exchange_class({
    'enableRateLimit' => true,
});

$exchange-verbose = true;
$exchange->load_markets();

**Comment by ExaByt3s** [comment]
sorry for the delay in reply, apparently it is fixed in the latest version 
CCXT v1.41.81

Array
(
    [0] => Request:
    [1] => GET
    [2] => https://api.binance.com/api/v3/exchangeInfo
    [3] => Array
        (
        )

    [4] => 
)
Array
(
    [0] => Response:
    [1] => GET
    [2] => https://api.binance.com/api/v3/exchangeInfo
    [3] => 200
    [4] => 
    [5] => Array
        (
            [Content-Type] => application/json;charset=UTF-8
            [Content-Length] => 40225
            [Connection] => keep-alive
            [Date] => Thu, 11 Feb 2021 13:54:41 GMT
            [Server] => nginx
            [X-Mbx-Uuid] => c0093a2e-afc4-497d-bdba-b872a3994ec3
            [X-Mbx-Used-Weight] => 1
            [X-Mbx-Used-Weight-1m] => 1
            [Content-Encoding] => gzip
            [Strict-Transport-Security] => max-age=31536000; includeSubdomains
            [X-Frame-Options] => SAMEORIGIN
            [X-Xss-Protection] => 1; mode=block
            [X-Content-Type-Options] => nosniff
            [Content-Security-Policy] => default-src 'self'
            [X-Content-Security-Policy] => default-src 'self'
            [X-WebKit-CSP] => default-src 'self'
            [Cache-Control] => no-cache, no-store, must-revalidate
            [Pragma] => no-cache
            [Expires] => 0
            [Access-Control-Allow-Origin] => *
            [Access-Control-Allow-Methods] => GET, HEAD, OPTIONS
            [X-Cache] => Miss from cloudfront
            [Via] => 1.1 c3f257ad7ec4633c503cd21a690fa4dd.cloudfront.net (CloudFront)
            [X-Amz-Cf-Pop] => MIA3-C2
            [X-Amz-Cf-Id] => 0linntpztL4RQz9SbYvABBSs9HYn7pGaHjf5mBISP1zs30XKddblaw==
        )

    [6] => {"timezone":"UTC","serverTime":1613051681928,"rateLimits":[{"rateLimitType":"REQUEST_WEIGHT","interval":"MINUTE","intervalNum":1,"limit":1200}

**Comment by weerdenburg** [comment]
This was not a constant error, it only occurred when Binance did not send a correct response and therefore the loop failed.
So only if there is added a check in the latest release, then this is fixed... otherwise it is not...

At this moment I don't see any similar errors in my logs, but I can't tell you if it is really fixed in the latest version or not.

**Comment by kroitor** [comment]
@weerdenburg if you encounter this issue we will need the verbose output to resolve it (https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help)
