### ISSUE TITLE
'ccxt' has no attribute ...

### ISSUE THREAD

**Issue by lifengmds** [ccxt/ccxt#8374]
Something wrong, just installed ccxt and tried demo code to print ccxt.version or ccxt.exchanges, but doesn't work

- OS:
- Programming Language version: python 3.9.1
- CCXT version: ccxt-1.41.31

```
import ccxt
print(ccxt.exchanges) # print a list of all available exchange classes
```

```
AttributeError: partially initialized module 'ccxt' has no attribute 'version' (most likely due to a circular import)
```

**Comment by kroitor** [comment]
@lifengmds do you have a filename `ccxt.py` in your project?

**Comment by lifengmds** [comment]
> @lifengmds do you have a filename `ccxt.py` in your project/folder? (that will cause conflicts like the above)

oh, yes! that's why!!

**Comment by lifengmds** [comment]
> > @lifengmds do you have a filename `ccxt.py` in your project/folder? (that will cause conflicts like the above)
> 
> oh, yes! that's why!!

I should laugh at myself...

**Comment by lifengmds** [comment]
> @lifengmds do you have a filename `ccxt.py` in your project/folder? (that will cause conflicts like the above)

I rename the file , and it's still the same error

**Comment by kroitor** [comment]
@lifengmds how do you install it?

**Comment by lifengmds** [comment]
> @lifengmds how do you install it?

pip3 install ccxt

Requirement already satisfied: ccxt in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (1.41.31)
Requirement already satisfied: setuptools>=38.5.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ccxt) (49.2.1)
Requirement already satisfied: yarl==1.1.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ccxt) (1.1.0)
Requirement already satisfied: requests>=2.18.4 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ccxt) (2.25.1)
Requirement already satisfied: certifi>=2018.1.18 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ccxt) (2020.12.5)
Requirement already satisfied: aiodns<2.1,>=1.1.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ccxt) (2.0.0)
Requirement already satisfied: cryptography>=2.6.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ccxt) (3.3.1)
Requirement already satisfied: aiohttp<3.8,>=3.7.2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from ccxt) (3.7.3)
Requirement already satisfied: multidict>=4.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from yarl==1.1.0->ccxt) (5.1.0)
Requirement already satisfied: idna>=2.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from yarl==1.1.0->ccxt) (2.10)
Requirement already satisfied: pycares>=3.0.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from aiodns<2.1,>=1.1.1->ccxt) (3.1.1)
Requirement already satisfied: async-timeout<4.0,>=3.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from aiohttp<3.8,>=3.7.2->ccxt) (3.0.1)
Requirement already satisfied: typing-extensions>=3.6.5 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from aiohttp<3.8,>=3.7.2->ccxt) (3.7.4.3)
Requirement already satisfied: chardet<4.0,>=2.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from aiohttp<3.8,>=3.7.2->ccxt) (3.0.4)
Requirement already satisfied: attrs>=17.3.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from aiohttp<3.8,>=3.7.2->ccxt) (20.3.0)
Requirement already satisfied: cffi>=1.12 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from cryptography>=2.6.1->ccxt) (1.14.4)
Requirement already satisfied: six>=1.4.1 in /Users/fng/Library/Python/3.9/lib/python/site-packages (from cryptography>=2.6.1->ccxt) (1.15.0)
Requirement already satisfied: pycparser in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from cffi>=1.12->cryptography>=2.6.1->ccxt) (2.20)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from requests>=2.18.4->ccxt) (1.26.2)

**Comment by kroitor** [comment]
@lifengmds what's the command you use to test it? What do you see if you run `ls -alh` in the same working directory?

**Comment by kroitor** [comment]
@lifengmds try this short snippet (run `python3` and copypaste the snippet below):

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
```

**Comment by lifengmds** [comment]
> @lifengmds try this short snippet (run `python3` and copypaste the snippet below):
> 
> ```python
> import ccxt
> print('CCXT Version:', ccxt.__version__)
> ```

yes, this works

**Comment by kroitor** [comment]
@lifengmds this should work as well as the rest of it:

```Python
import ccxt
print(ccxt.exchanges)
```

**Comment by lifengmds** [comment]
> @lifengmds this should work as well as the rest of it:
> 
> ```python
> import ccxt
> print(ccxt.exchanges)
> ```

Thank you for your help!
