### ISSUE TITLE
ftx, incorrect mappings for entryPrice and realizedPnl

### ISSUE THREAD

**Issue by qtmspin** [ccxt/ccxt#8376]
Windows
Python 3
1.41.41

ftx.py?

private_get_positions() 
fetch_positions()

I believe these are returning incorrect mappings.  Entry price is showing the actual current market price and realized pnl is showing unrealized pnl.  I'm trading the ETH-PERP contract.

Love the library!  You all have done an amazing job.

Thanks!
Matt

**Comment by kroitor** [comment]
Hi!

> private_get_positions()

What you get from implicit methods (https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods) is the response from the exchange as is – you might want to forward your question to the FTX.

Let us know if that does not help.

**Comment by 0if** [comment]
I'm also seeing this with JS client

**Comment by kroitor** [comment]
@0if please, follow the guidelines: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by 0if** [comment]
Apologies. I was able to resolve this using the privateGetPositions method as such:
`const params = {
        'showAvgPrice': true,      
      }
var positions = (await exchange.privateGetPositions(params)).result;`

**Comment by kroitor** [comment]
@0if thx for your feedback!
