### ISSUE TITLE
ccxt support fore coinex perpetuals?

### ISSUE THREAD

**Issue by chiwalfrm** [ccxt/ccxt#8377]
latest version of CCXT does not appear to support coinex perpetuals.  Is this on the roadmap?

This was the only comment I found written on 1/31/2020
https://github.com/ccxt/ccxt/issues/6435#issuecomment-580918359

which said:

"CoinEx does have a perpetual API, but it was added in October 2019, long after CoinEx REST API was integrated in CCXT. So, what you have in CCXT is CoinEx without a perpetual API (yet). We will add the support for it as soon as we can." -kroitor

**Comment by kroitor** [comment]
Hi! At this time CoinEx's perpetuals are not supported in CCXT yet, just the spot markets. We didn't have a chance to address it for CoinEx yet, but we have started the work on unifying the contract trading and will hopefully get the futures and other derivatives fully unified in the coming weeks. Will let you know when it arrives.
