### ISSUE TITLE
Please help me solve this problem

### ISSUE THREAD

**Issue by hackingwhangjuncomputer** [ccxt/ccxt#8378]
- OS:big sur 11.1
- Programming Language version:python 3.6
- CCXT version: AttributeError: module 'ccxt' has no attribute 'version'

```
import ccxt
import pybithumb
import time
import smtplib
import io
from email.mime.text import MIMEText
import os
import sys

binance = ccxt.binance()
ticker = binance.fetch_ticker('ETH/BTC')
real = pybithumb.get_current_price("BTC")
f2 = open("base_line.txt", 'r')
base_line = 37330000.0
id = open("id.txt",'r')
pwd = open("pwd.txt",'r')
port = 9334


binance = ccxt.binance({
    'apiKey': 'my_api_key',
    'secret': 'my_secret_key',
    'enableRateLimit': True,
})
params = {
    'test': True,  # test if it's valid, but don't actually place it
}
s = smtplib.SMTP('smtp.gmail.com', 587)

s.starttls()
s.login("junseopwhang@gmail.com", my_gmail_key")




binance = binance.fetch_balance()
while True: 
	print(base_line)
	if base_line < real:
		time.sleep(1)
		print(binance.create_order("BTC/ETH", "limit", "sell", "1.0", "0.060154", params))
		print('buy')
		msg = MIMEText("buy")
		msg['Subject'] = '제목 :비트코인 정보!'
		s.sendmail("junseopwhang@gmail.com", "junseopwhang@kakao.com", msg.as_string())
		time.sleep(1)
		
	if base_line > real:
		time.sleep(1)
		print(binance.create_order("BTC/ETH", "limit", "sell", "1.0", "0.060154", params))
		print("sell")
		msg = MIMEText("sell")
		msg['Subject'] = '제목 :비트코인 정보!'
		s.sendmail("junseopwhang@gmail.com", "junseopwhang@kakao.com", msg.as_string())
		time.sleep(1)
		

	
```

```
/Users/junseopwhang/opt/anaconda3/envs/bitcoin_make_auto/lib/python3.5/site-packages/ccxt/base/exchange.py:32: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.
  from cryptography.hazmat import backends
37330000.0
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    print(binance.create_order("BTC/ETH", "limit", "sell", "1.0", "0.060154", params))
AttributeError: 'dict' object has no attribute 'create_order'
```

**Comment by hackingwhangjuncomputer** [comment]
help!!!!!!!!!

**Comment by me1029134** [comment]
You are setting "binance" in two spots. Change this:

binance = binance.fetch_balance()
To 

binance_balance = binance.fetch_balance()

**Comment by kroitor** [comment]
@me1029134 thank you for your help!

@hackingwhangjuncomputer we hope that answers your question, let us know if not.

**Comment by hackingwhangjuncomputer** [comment]
from cryptography.hazmat import backends
37330000.0
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    print(binance.create_order("BTC/ETH", "limit", "sell", "1.0", "0.060154", params))
  File "/Users/junseopwhang/opt/anaconda3/envs/bitcoin_make_auto/lib/python3.5/site-packages/ccxt/binance.py", line 1561, in create_order
    market = self.market(symbol)
  File "/Users/junseopwhang/opt/anaconda3/envs/bitcoin_make_auto/lib/python3.5/site-packages/ccxt/base/exchange.py", line 1818, in market
    raise BadSymbol('{} does not have market symbol {}'.format(self.id, symbol))
ccxt.base.errors.BadSymbol: binance does not have market symbol BTC/ETH



...........................?????

**Comment by hackingwhangjuncomputer** [comment]
from cryptography.hazmat import backends
37330000.0
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    print(binance.create_order("BTC/ETH", "limit", "sell", "1.0", "0.060154", params))
  File "/Users/junseopwhang/opt/anaconda3/envs/bitcoin_make_auto/lib/python3.5/site-packages/ccxt/binance.py", line 1561, in create_order
    market = self.market(symbol)
  File "/Users/junseopwhang/opt/anaconda3/envs/bitcoin_make_auto/lib/python3.5/site-packages/ccxt/base/exchange.py", line 1818, in market
    raise BadSymbol('{} does not have market symbol {}'.format(self.id, symbol))
ccxt.base.errors.BadSymbol: binance does not have market symbol BTC/ETH

**Comment by kroitor** [comment]
@hackingwhangjuncomputer binance does not have BTC/ETH, but it has ETH/BTC. Please, read the Manual, it is all covered there: 

- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/wiki/Manual

**Comment by hackingwhangjuncomputer** [comment]
yes, thank you very much, but I have a question. What to buy when buying bitcoin with that api?

**Comment by kroitor** [comment]
@hackingwhangjuncomputer when trading spot markets like ETH/BTC, you're buying ETH for BTC and selling ETH for BTC. That is explained in the Manual, please read it from top to bottom – it will really save your time.
