### ISSUE TITLE
Issue with timestamp parse of data feed needs help

### ISSUE THREAD

**Issue by lifengmds** [ccxt/ccxt#8379]
Hi,
I have some problems to read the timestamp from the datafeed download from CCXT. No matter what I tried, it can't parse the datetime info.

Pandas code:

> dataframe = pandas.read_csv(
        datapath,
        skiprows=1,
        header=1,
        date_parser=parsedate,
        parse_dates=True,
        index_col=0,
    )

data feed format:
>  Timestamp,Open,High,Low,Close,Volume
    1611658800000,32247.2,32249.98,32105.36,32139.29,616.047753
    1611659700000,32139.29,32186.61,31807.19,31968.65,804.456726
    1611660600000,31968.65,32048.88,31733.0,32040.8,680.101376
  
Firstly, pandas default date parser couldn't process it and returned error
```
  dt = tstamp.to_pydatetime()
AttributeError: 'numpy.int64' object has no attribute 'to_pydatetime'
```

Secondly I defined a parser function but returned error :
```
ValueError: year 53041 is out of range
```

 parser function:

>  def parsedate(timestamp):
    if type(timestamp) is str: timestamp = int(timestamp)  # put up with timestamp being in string format
    if timestamp > 1e10: timestamp // 1000 # put up with timestamp being in microseconds
    return datetime.utcfromtimestamp(float(timestamp)).replace(tzinfo=tz.tzutc())

- OS: Mac
- Programming Language version: python3
- CCXT version: newest

**Comment by kroitor** [comment]
Hi!

Change your date-parsing to convert milliseconds to datetime:

```Python
def parsedate(timestamp):
    return datetime.utcfromtimestamp(timestamp / 1000)
```

Let us know if that does not help.

**Comment by lifengmds** [comment]
It worked well! thanks!
