### ISSUE TITLE
FTX has subaccount in HTTP header

### ISSUE THREAD

**Issue by Andytreee** [ccxt/ccxt#8383]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version: 1.38.87

```
REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS
```
FTX offers subaccounts,so if you want to access private apis in ur subaccounts，u should add 'FTX-SUBACCOUNT' in request headers.FTX's api doc lists below.
![image](https://user-images.githubusercontent.com/22608268/106695586-dc38fa00-6615-11eb-9e2e-2e0495500e78.png)
https://docs.ftx.com/#rest-api
![image](https://user-images.githubusercontent.com/22608268/106695929-9597cf80-6616-11eb-83c9-3009a482e004.png)

```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
```
If not supplied, server response 401

**Comment by kroitor** [comment]
@Andytreee if your question is how to use it:

```JavaScript
const ccxt = require ('ccxt')
const exchange = new ccxt.ftx({
    'enableRateLimit': true,
    'headers': {
        'FTX-SUBACCOUNT': 'YOUR_SUBACCOUNT',
    },
})

// your calls here
```

- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties

Let us know if that does not help.

**Comment by ttodua** [comment]
Update: from now, you can now directly add the parameter in any method (without need to set the headers in exchange initialization properties), like:

`createOrder/FerchBalance( ..., ...,  params:{ "FTX-SUBACCOUNT":"mySubAcc"} ) `   

Note: `FTXUS-SUBACCOUNT` for ftx.us users.
