### ISSUE TITLE
Binance missing in takerlongshortRatio, etc.

### ISSUE THREAD

**Issue by thisisloze** [ccxt/ccxt#8384]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Win
- Programming Language version: node
- CCXT version:

takerlongshortRatio, openInterest, ect are not included. but they are in the binance.js.

**Comment by kroitor** [comment]
Hi!

Please, paste your version numbers, your code and your verbose output:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by thisisloze** [comment]
Will do

**Comment by thisisloze** [comment]
"_from": "ccxt",
  "_id": "ccxt@1.41.41",
  
  Code is 
  `const ccxt = require ('ccxt')
const exchange = new ccxt["binance"]({ enableRateLimit: true });
(async function () {
console.log(await exchange.fapiDataopenInterest("BTC/USDT"))
}) ();
`

Error is fapiDataopenInteres doesnt exist.

**Comment by thisisloze** [comment]
TypeError: exchange.fapiDataopenInterest is not a function

**Comment by thisisloze** [comment]
Just wondering if there is a way to use it or do I have to code it in myself. Like I said binaince.js has it in the headers.

`                'fapiPublic': {
                    'get': [
                        'ping',
                        'time',
                        'exchangeInfo',
                        'depth',
                        'trades',
                        'historicalTrades',
                        'aggTrades',
                        'klines',
                        'fundingRate',
                        'premiumIndex',
                        'ticker/24hr',
                        'ticker/price',
                        'ticker/bookTicker',
                        'allForceOrders',
                        'openInterest',
                        'indexInfo',
                    ],
                },`

**Comment by kroitor** [comment]
@thisisloze answered here: https://github.com/ccxt/ccxt/issues/8028#issuecomment-773422589

**Comment by thisisloze** [comment]
```
 const symbol = 'BTC/USDT'
    const market = exchange.market (symbol)
    const takerlongshortRatio = await exchange.fapiDataGetTakerLongShortRatio({'symbol': market['id'], 'period': "5m", 'limit': 1})
    console.log(takerlongshortRatio)
```

(node:7720) UnhandledPromiseRejectionWarning: TypeError: exchange.fapiDataGettakerlongshortRatio is not a function
    at main (C:\projects\testApi\index.js:39:48)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:7720) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7720) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by kroitor** [comment]
```
const symbol = 'BTC/USDT'
  const market = exchange.market (symbol)
  const takerlongshortRatio = await exchange.fapiDataGetTakerlongshortRatio({'symbol': market['id'], 'period': "5m", 'limit': 1})
  console.log(takerlongshortRatio)
```

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

Let us know if that does not help.
