### ISSUE TITLE
Binance Futures API connecting to wrong symbol

### ISSUE THREAD

**Issue by codemonkeyno1** [ccxt/ccxt#8387]
Python 3.7, Latest ccxt version

ccxt exchange.fetch_bids_asks() is mapping "BTC/USDT" to Binance symbol "BTCUSDT_210326", which is wrong.  Should be mapped to symbol "BTCUSDT" instead.  Very dangerous.

**Comment by Krisseck** [comment]
Got this same bug in JS library. Made an futures order for "BTC/USDT", the JSON response says 
```
{ info:
   { symbol: 'BTCUSDT_210326',
     status: 'NEW',
   },
   ...
  symbol: 'BTC/USDT',
  type: 'market'}
  ```

**Comment by kroitor** [comment]
@Krisseck what is your version of CCXT?

**Comment by kroitor** [comment]
@Krisseck you have to upgrade to 1.41.51+: 

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

The exchanges update their APIs, so you want to keep your software up to date as well.

**Comment by Krisseck** [comment]
> @Krisseck what is your version of CCXT?

It was 1.40.88, upgrading worked, thanks!

**Comment by kroitor** [comment]
@Krisseck thx for reporting back!
