### ISSUE TITLE
Slow Websocket closing in python client

### ISSUE THREAD

**Issue by pietrodn** [ccxt/ccxt#8391]
- OS: macOS 11.2
- Programming Language version: Python 3.9.1
- CCXT version: `ccxtpro==0.5.51`

## Reproduction steps

Run this script.

```python
import asyncio
import time

from ccxtpro import ftx


async def main() -> None:
    client = ftx()
    ticker = await client.watch_ticker("BTC-PERP")

    print("Closing...")
    close_start_time = time.monotonic()
    await client.close()
    close_finish_time = time.monotonic()
    print(f"Client closed in {close_finish_time-close_start_time:.2f} seconds.")


if __name__ == '__main__':
    asyncio.run(main())
```

## Results

```
Closing...
Client closed in 10.00 seconds.
```

If one of the functions opening a Websocket client is called (`watch_ticker()`, `watch_orders()`, ...), then the client takes exactly 10 seconds to close.

It seems that the time to close is influenced by the websocket timeout implicitly set in `create_connection()`, in the file `ccxtpro/base/aiohttp_client.py` at line 74. If I set the websocket timeout to 5 seconds instead of the default of 10 seconds, the connection closes in 5 seconds.

## Expected behaviour

The Websocket client should close without timing out.

**Comment by kroitor** [comment]
@pietrodn thank you, we're working on a clean sync shutdown, hope to get that fixed soon!

**Comment by pietrodn** [comment]
The problem is solved in the latest version of CCXT: the shutdown is instantaneous.
Closing this issue, thank you for the hard work 🙏

**Comment by kroitor** [comment]
@pietrodn thanks to you for your feedback, and to @frosty00 for the fix! Don't hesitate if anything.
