### ISSUE TITLE
limiting candles through ohlcv seems not to be working

### ISSUE THREAD

**Issue by beursdummy** [ccxt/ccxt#8392]
so i have 2 bots running

one on 1.41.51 and one on the latest 1.41.53

when I both run ohlcv i get this for BTC

candles_5m = binance_futures.fetch_ohlcv(symbol='BTC/USDT',timeframe='5m',limit=2,)

1.41.53
LOW: 18081.65
HIGH: 41662.12939

1.41.51
LOW: 36751.29632
HIGH: 38050.696749999996

so price for the last version is showing numbers that are way off. Is it possible that it is ALWAYS taking last 1500 candles?

**Comment by kroitor** [comment]
@beursdummy replied to your question here: https://github.com/ccxt/ccxt/issues/8386#issuecomment-772694958, please let us know if you have the same problem with 1.41.54, it will arrive in 20 minutes.
