### ISSUE TITLE
fetch_deposit_address with network binance php

### ISSUE THREAD

**Issue by mahdi4187** [ccxt/ccxt#8396]
how to get fetch_deposit_address in another network in php?

```
$data     = [
        'network' => 'TRC20'
    ];
    $response = Binance::fetch_deposit_address( 'USDT' , $data );
```
response :

binance {"msg":"The deposit has been closed","success":false}

**Comment by kroitor** [comment]
1. Make sure to upgrade to version 1.41.60+
2. Fix the arguments in your call:

```PHP
$exchange = new \ccxt\binance([
    'enableRateLimit' => true,
]);

$params = [
    'network' => 'TRX',
]
$response = $exchange->fetch_deposit_address('USDT', $params);
```

Let us know if that does not answer your question.
