### ISSUE TITLE
Is it possible to get baseVolume, or volume traded, in the last hour as opposed to the last 24 on Binance?

### ISSUE THREAD

**Issue by DavidWillLaw** [ccxt/ccxt#8397]
Sorry if this is the wrong place to ask!

I'm interested in getting the volume of a pair traded in the last hour, or even more granularly minute to minute if possible. I understand that baseVolume is the volume traded in 24 hours, but this isn't quite particular enough for me.

Any help is much appreciated, thank you.

**Comment by kroitor** [comment]
Hi!

Yes that is possible, you can get that from OHLCV candles which stand for Open, High, Low, Close and Volume.
More about it here:

- https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-candlestick-charts
- https://github.com/ccxt/ccxt/wiki/Manual#pagination
- https://github.com/ccxt/ccxt/tree/master/examples

Let us know if that does not answer your question.

**Comment by kroitor** [comment]
You can also get a list of recent public trades and calculate the volumes from there with the most precise first-order info (trades). OHLCV candles and 24h-tickers calculated by the exchange are second-order statistical data that is derived from the first-order log of public trades (fills).

**Comment by DavidWillLaw** [comment]
I'll take a look into that then, thank you Kroitor!
