### ISSUE TITLE
fetch_ohlcv should be useable without endTime for this usecase

### ISSUE THREAD

**Issue by yazeed** [ccxt/ccxt#8399]
Recent changes made to fetch_ohlcv on binance.php prevent us from using fetch_ohlcv to grab the oldest OHLCVs for a pair, due to an enforced use of endTime parameter. I used to be able to call fetch_ohlcv with 0 startTime in previous versions to grab the oldest OHLCV from Binance, because endTime was not used.

I propose the following change to this code block in binance.php to allow use of startTime without endTime in fetch_ohlcv requests, if called with $since => null.

```
if ($since !== null) {
      $request['startTime'] = $since;
      $endTime = $this->sum($since, $limit * $duration * 1000 - 1);
      $now = $this->milliseconds();
      $request['endTime'] = min ($now, $endTime);
} 
```

to:

```
if ($since !== null) {
      $request['startTime'] = $since;
      $endTime = $this->sum($since, $limit * $duration * 1000 - 1);
      $now = $this->milliseconds();
      $request['endTime'] = min ($now, $endTime);
} elseif($since === null) {
      $request['startTime'] = 0;
}
```

This way, if you call the function with null, it defaults to 0 startTime and no endTime, which brings the oldest candles for that pair from Binance. Then if you'd want to use startTime with endTime, I can always provide 0 to $since parameter.

Eitherway, if you see a better way to do this, please propose it here. I don't think endTime should be enforced for this specific usecase.

If approved, I'll submit a PR.

- OS: Ubuntu 20.04
- Programming Language version: PHP 7.4
- CCXT version: 1.4.61

**Comment by kroitor** [comment]
@yazeed what is your output? ↓

```PHP
include_once ('./ccxt.php');

date_default_timezone_set ('UTC');

echo 'CCXT v' . \ccxt\Exchange::VERSION . "\n";

$exchange = new \ccxt\binance(array(
    'enableRateLimit' => true,
));

$exchange->load_markets();

$since = $exchange->parse8601('2020-01-01T00:00:00Z');
$ohlcvs = $exchange->fetch_ohlcv('BTC/USDT', '5m', $since);
$num_ohlcvs = count($ohlcvs);
echo "Fetched ", $num_ohlcvs, "ohlcvs.\n";
if ($num_ohlcvs) {
    echo "Starting from ", $exchange->iso8601 ($ohlcvs[0][0]), "\n";
    echo "Ending on ", $exchange->iso8601 ($ohlcvs[$num_ohlcvs - 1][0]), "\n";
}
```

-----------------------------------

```PHP
~/ccxt $ php -a
Interactive shell

php > include_once ('./ccxt.php');
php >
php > date_default_timezone_set ('UTC');
php >
php > echo 'CCXT v' . \ccxt\Exchange::VERSION . "\n";
CCXT v1.41.61
php >
php > $exchange = new \ccxt\binance(array(
php (     'enableRateLimit' => true,
php ( ));
php >
php > $exchange->load_markets();
php >
php > $since = $exchange->parse8601('2020-01-01T00:00:00Z');
php > $ohlcvs = $exchange->fetch_ohlcv('BTC/USDT', '5m', $since);
php > $num_ohlcvs = count($ohlcvs);
php > echo "Fetched ", $num_ohlcvs, "ohlcvs.\n";
Fetched 500ohlcvs.
php > if ($num_ohlcvs) {
php {     echo "Starting from ", $exchange->iso8601 ($ohlcvs[0][0]), "\n";
php {     echo "Ending on ", $exchange->iso8601 ($ohlcvs[$num_ohlcvs - 1][0]), "\n";
php { }
Starting from 2020-01-01T00:00:00.000Z
Ending on 2020-01-02T17:35:00.000Z
```

**Comment by yazeed** [comment]
My output is as follows, but I don't see how what you've asked me to do is relevant to what I posted.

```
CCXT v1.41.61
Fetched 500ohlcvs.
Starting from 2020-01-01T00:00:00.000Z
Ending on 2020-01-02T17:35:00.000Z
```

**Comment by yazeed** [comment]
I just noticed that  you've fixed this in commit aa77ab0 on binance.js, but that's inconsistent with binance.php.

**Comment by kroitor** [comment]
@yazeed please upgrade to 1.41.62, it has been fixed in js/python/php:

- https://github.com/ccxt/ccxt/wiki/FAQ#hey-the-fix-youve-uploaded-is-in-js-would-you-fix-python--php-as-well-please
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support

Let us know if you still have issues with CCXT 1.41.62+.

**Comment by yazeed** [comment]
Thank you, my bad, it works now. Apologies. Have a great day or evening wherever you are!

**Comment by kroitor** [comment]
@yazeed thx for your feedback!
