### ISSUE TITLE
fetch_my_trades method miss sapi (margin account) type

### ISSUE THREAD

**Issue by ksanderer** [ccxt/ccxt#8401]
https://github.com/ccxt/ccxt/blob/a5c9f852d93668e55803c0198178bc1ac658b4b1/python/ccxt/async_support/binance.py#L1963

Now we have to use instead

```
resp = api.sapiGetMarginAllOrders(params={"symbol": f"BUSDUSDT"})
```

**Comment by diwenshi61** [comment]
I think that endpoint points to getting all margin orders. The endpoint for trades is GET /sapi/v1/margin/myTrades. Since this only gets trades on margin, I think it's probably best to split up getting spot and margin trades by adding a type 'margin' for getting margin trades.
