### ISSUE TITLE
Binance Quarterly futures market overrides normal futures market

### ISSUE THREAD

**Issue by fartat** [ccxt/ccxt#8404]
HI!

I am using the latest version of ccxt for PHP, on php 7.4.

3 days ago Binance opened a new BTCUSDT market (BTCUSDT Quarterly 0326) - https://www.binance.com/en/futures/btcusdt_quarter - here is the announcment : https://www.binance.com/en/support/faq/3ae441db4ae740e19af3fe9228eb6619

My bot started trading on this market and i didn't know why... And found out that $binance->load_markets() is retuning only 1 BTCUSDT market and is returning the quarterly one.

Here is how to reproduce:

```
$exchange = '\\ccxt\\binance';

$bot = new $exchange(array(
    'apiKey' => "...your key...",
    'secret' => "...your secret...",
    'timeout' => 30000,
    'enableRateLimit' => true,
    'options' => array(
        'defaultType' => 'future'
    )
));

$markets = $bot->load_markets();
```

If you print_r($markets); you'll notice that the array with key [BTC/USDT] will have [id] => BTCUSDT_210326 but [symbol] => BTC/USDT and [info][contractType] => CURRENT_QUARTER

There should be another market with same symbol but [info][contractType] => PERPETUAL

It's quarterly - https://www.binance.com/en/futures/btcusdt_quarter vs perpetual - https://www.binance.com/en/futures/BTCUSDT

I did some digging and the problem is in Exchange.php in "set_markets" function. Because if you print_r() the raw data coming from binance you will see 2 different markets on the same symbol.

[0] => Array(
    [id] => BTCUSDT
    [lowercaseId] => btcusdt
    [symbol] => BTC/USDT
    [base] => BTC
    [quote] => USDT
    [baseId] => BTC
    [quoteId] => USDT
    [info] => Array(
        [symbol] => BTCUSDT
        [pair] => BTCUSDT
        [contractType] => PERPETUAL

AND:

[88] => Array(
    [id] => BTCUSDT_210326
    [lowercaseId] => btcusdt_210326
    [symbol] => BTC/USDT
    [base] => BTC
    [quote] => USDT
    [baseId] => BTC
    [quoteId] => USDT
    [info] => Array(
        [symbol] => BTCUSDT_210326
        [pair] => BTCUSDT
        [contractType] => CURRENT_QUARTER

No idea how to fix this...

**Comment by kroitor** [comment]
@fartat this issue has been addressed already, just upgrade your version of CCXT to the most recent one and you'll be fine (binance changed the API output a few days ago):

- https://github.com/ccxt/ccxt/issues/8386
- https://github.com/ccxt/ccxt/issues/8387
