### ISSUE TITLE
Mercado Bitcoin: Creating market orders

### ISSUE THREAD

**Issue by Felipe-Mangueira** [ccxt/ccxt#841]
Hi, @kroitor,

It's possible to place market orders manually on Mercado Bitcoin. Although I have not seen any reference in the API documentation of this kind of order, I guess this method could be implementable. I would like to ask you to check whether I am right or not. Case I'm right, could you implement this method on ccxt library?

Thank you again and sorry for making too many request too often.

**Comment by Felipe-Mangueira** [comment]
> Can you link to the source of this info?

Sorry, @kroitor, but i cannot link to the source because it's only available on private space. I've attached a picture of my screen showing this possibility.

> Do you mean placing market orders with their website interface?

Yes, I do. Please, see below:

![market order on mercado bitcoin](https://user-images.githubusercontent.com/25753215/33904682-6ede2fa2-df63-11e7-8c6c-8a071e968e2e.jpg)

**Comment by kroitor** [comment]
Unfortunately, scraping all the necessary info from their website would require multiple sequential requests + 2fa, so, if that takes more than one request, it automatically means that the call to create a market order would take much longer time than usual limit orders. The introduced lag kills the purpose of a market order in the first place. When we place market orders we want immediate prices with as little lag as possible, and if the lag is 100-1000ms, this is not very tolerable anymore. You may end up buying or selling for a much worse price than you expect, especially, if you consider scaling this up to higher volumes. Moreover, even if making multiple requests would be tolerable, scraping and reverse-engineering their web protocol is currently beyond the scope of the library. So, I'm afraid, we will not add market orders for Mercado Bitcoin, until they integrate that into their API or until they document market orders in it at the very least. On the other hand, we would merge this functionality of course, if you (or anyone else) can submit an implementation or a PR on that. I'd close this for now, until further development. Sorry.

**Comment by Felipe-Mangueira** [comment]
Ok, @kroitor. Fair enough.

Thanks anyway for your concern. If Mercado Bitcoin integrates this funcionality to their API, I request it to you again.
