### ISSUE TITLE
problem with scrape_candles_to_csv on Binance, missing latest candles. 

### ISSUE THREAD

**Issue by Kalelv45** [ccxt/ccxt#8411]
- OS: Mac OS Big Sur 
- Programming Language version: Python 3.9
- CCXT version: 1.41.51

```python
scrape_candles_to_csv('ADA_BTC_binance.csv', 'binance', 500, 'ADA/BTC, i, '2020-01-01T00:00:00Z', 1500)
    
```

```
Saved 2992 candles from 2020-01-29T19:00:00.000Z to 2020-12-28T02:00:00.000Z to ADA_BTC_1h_bitmex.csv```

Usually before the update it would download till the latest candle, right now it seems that if 1500 candles don't fit, it just stop earlier. 
How can I fix this?

**Comment by kroitor** [comment]
@Kalelv45 do you have the same issue with the most recent version of the lib? Binance has changed the inner workings of the API recently, and we have pushed some updates.

**Comment by Kalelv45** [comment]
`python 
# -*- coding: utf-8 -*-

import os
import sys
import csv
import ccxt 




# -----------------------------------------------------------------------------

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt  # noqa: E402


# -----------------------------------------------------------------------------

def retry_fetch_ohlcv(exchange, max_retries, symbol, timeframe, since, limit):
    num_retries = 0
    try:
        num_retries += 1
        ohlcv = exchange.fetch_ohlcv(symbol, timeframe, since, limit)
        # print('Fetched', len(ohlcv), symbol, 'candles from', exchange.iso8601 (ohlcv[0][0]), 'to', exchange.iso8601 (ohlcv[-1][0]))
        return ohlcv
    except Exception:
        if num_retries > max_retries:
            raise  # Exception('Failed to fetch', timeframe, symbol, 'OHLCV in', max_retries, 'attempts')


def scrape_ohlcv(exchange, max_retries, symbol, timeframe, since, limit):
    earliest_timestamp = exchange.milliseconds()
    timeframe_duration_in_seconds = exchange.parse_timeframe(timeframe)
    timeframe_duration_in_ms = timeframe_duration_in_seconds * 1000
    timedelta = limit * timeframe_duration_in_ms
    all_ohlcv = []
    while True:
        fetch_since = earliest_timestamp - timedelta
        ohlcv = retry_fetch_ohlcv(exchange, max_retries, symbol, timeframe, fetch_since, limit)
        # if we have reached the beginning of history
        if ohlcv[0][0] >= earliest_timestamp:
            break
        earliest_timestamp = ohlcv[0][0]
        all_ohlcv = ohlcv + all_ohlcv
        #print(len(all_ohlcv), 'candles in total from', exchange.iso8601(all_ohlcv[0][0]), 'to', exchange.iso8601(all_ohlcv[-1][0]))
        # if we have reached the checkpoint
        if fetch_since < since:
            break
    return exchange.filter_by_since_limit(all_ohlcv, since, None, key=0)


def write_to_csv(filename, data):
    with open(filename, mode='w') as output_file:
        csv_writer = csv.writer(output_file, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
        csv_writer.writerows(data)


def scrape_candles_to_csv(filename, exchange_id, max_retries, symbol, timeframe, since, limit):
    # instantiate the exchange by id
    exchange = getattr(ccxt, exchange_id)({
        'enableRateLimit': True, 
        'options': {
        'defaultType': 'future',  # ←-------------- quotes and 'future'
    } # required by the Manual
    })
    # convert since from string to milliseconds integer if needed
    if isinstance(since, str):
        since = exchange.parse8601(since)

    # preload all markets from the exchange
    #exchange.load_markets()
    # fetch all candles
    ohlcv = scrape_ohlcv(exchange, max_retries, symbol, timeframe, since, limit)
    # save them to csv file
    write_to_csv(filename, ohlcv)
    print('Saved', len(ohlcv), 'candles from', exchange.iso8601(ohlcv[0][0]), 'to', exchange.iso8601(ohlcv[-1][0]), 'to', filename)


`

**Comment by Kalelv45** [comment]
```python 
# -*- coding: utf-8 -*-

import os
import sys
import csv
import ccxt 




# -----------------------------------------------------------------------------

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt  # noqa: E402


# -----------------------------------------------------------------------------

def retry_fetch_ohlcv(exchange, max_retries, symbol, timeframe, since, limit):
    num_retries = 0
    try:
        num_retries += 1
        ohlcv = exchange.fetch_ohlcv(symbol, timeframe, since, limit)
        # print('Fetched', len(ohlcv), symbol, 'candles from', exchange.iso8601 (ohlcv[0][0]), 'to', exchange.iso8601 (ohlcv[-1][0]))
        return ohlcv
    except Exception:
        if num_retries > max_retries:
            raise  # Exception('Failed to fetch', timeframe, symbol, 'OHLCV in', max_retries, 'attempts')


def scrape_ohlcv(exchange, max_retries, symbol, timeframe, since, limit):
    earliest_timestamp = exchange.milliseconds()
    timeframe_duration_in_seconds = exchange.parse_timeframe(timeframe)
    timeframe_duration_in_ms = timeframe_duration_in_seconds * 1000
    timedelta = limit * timeframe_duration_in_ms
    all_ohlcv = []
    while True:
        fetch_since = earliest_timestamp - timedelta
        ohlcv = retry_fetch_ohlcv(exchange, max_retries, symbol, timeframe, fetch_since, limit)
        # if we have reached the beginning of history
        if ohlcv[0][0] >= earliest_timestamp:
            break
        earliest_timestamp = ohlcv[0][0]
        all_ohlcv = ohlcv + all_ohlcv
        #print(len(all_ohlcv), 'candles in total from', exchange.iso8601(all_ohlcv[0][0]), 'to', exchange.iso8601(all_ohlcv[-1][0]))
        # if we have reached the checkpoint
        if fetch_since < since:
            break
    return exchange.filter_by_since_limit(all_ohlcv, since, None, key=0)


def write_to_csv(filename, data):
    with open(filename, mode='w') as output_file:
        csv_writer = csv.writer(output_file, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
        csv_writer.writerows(data)


def scrape_candles_to_csv(filename, exchange_id, max_retries, symbol, timeframe, since, limit):
    # instantiate the exchange by id
    exchange = getattr(ccxt, exchange_id)({
        'enableRateLimit': True, 
        'options': {
        'defaultType': 'future',  # ←-------------- quotes and 'future'
    } # required by the Manual
    })
    # convert since from string to milliseconds integer if needed
    if isinstance(since, str):
        since = exchange.parse8601(since)

    # preload all markets from the exchange
    #exchange.load_markets()
    # fetch all candles
    ohlcv = scrape_ohlcv(exchange, max_retries, symbol, timeframe, since, limit)
    # save them to csv file
    write_to_csv(filename, ohlcv)
    print('Saved', len(ohlcv), 'candles from', exchange.iso8601(ohlcv[0][0]), 'to', exchange.iso8601(ohlcv[-1][0]), 'to', filename)


 ```

**Comment by kroitor** [comment]
@Kalelv45 do you have this issue with CCXT 1.41.68?

**Comment by Kalelv45** [comment]
> @Kalelv45 do you have this issue with CCXT 1.41.68?

yess I do. It stops earlier anyway. Just upgraded form 1.41.51

**Comment by kroitor** [comment]
@Kalelv45 which timeframe is it?

**Comment by Kalelv45** [comment]
I have seen that I have copied this file from examples/py/binance-fetch-ohlcv-to-csv.py 
where the last commit was in April 2020. Maybe is not working anymore? Where can I find the new version of the same file?

**Comment by kroitor** [comment]
@Kalelv45 i will debug and will get back to you

**Comment by Kalelv45** [comment]
It seems to be a problem that affect only the spot market, on futures, it download the last till the last candle at the present moment.

**Comment by Kalelv45** [comment]
Sorry to have waisted your time, it seems I have solved the problem. Wish you well as always and thanks for your ready hand for help.

**Comment by kroitor** [comment]
> Sorry to have waisted your time, it seems I have solved the problem. 

Please, elaborate a bit on the solution, it could help save the time for the other people.

**Comment by Kalelv45** [comment]
> > Sorry to have waisted your time, it seems I have solved the problem.
> 
> Please, elaborate a bit on the solution, it could help save the time for the other people. How did you fix it?

The file I shared works fine, I was wrongly importing another one. That didn't for some reason go till the end. If I change future to spot on the file I shared it works flawlessly.
