### ISSUE TITLE
% taker & maker

### ISSUE THREAD

**Issue by dynarian** [ccxt/ccxt#8412]
I have read the documentation and I understand that the taker and maker data (eg 0.0026 and 0.0016 respectively for the ETH / BTC pairs) represent 0.26 and 0.16%, the normal thing is to multiply by 100 to have the respective%. is my interpretation correct?

I ask why BITSO for the same pair (ETH / BTC) would stay at 7.5 and 9.8% which is a lot ...

**Comment by kroitor** [comment]
> I have read the documentation and I understand that the taker and maker data (eg 0.0026 and 0.0016 respectively for the ETH / BTC pairs) represent 0.26 and 0.16%, the normal thing is to multiply by 100 to have the respective%. is my interpretation correct?

Yes, that is correct.

> I ask why BITSO for the same pair (ETH / BTC) would stay at 7.5 and 9.8% which is a lot ...

That looks like a bug, i've pushed a fix to it and the fix will arrive with the new build 1.41.69 in ~20 minutes. It will be great if you report back whether that resolves the issue for you or not after upgrading to the most recent version.
