### ISSUE TITLE
how to get binance isolated margin account information?

### ISSUE THREAD

**Issue by chiwalfrm** [ccxt/ccxt#8415]
I know how to  get binance account information using fetchBalance() but I can't figure out how to do it for isolated-margin account.

for cross-margin:
```
binance = ccxt.binance({'options': { 'defaultType': 'margin' }})
binance.fetchBalance()

```
for futures:
```
binance = ccxt.binance({'options': { 'defaultType': 'future' }})
binance.fetchBalance()
```

for spot:
```
binance = ccxt.binance()
binance.fetchBalance()
```

Can someone help me?  Thank you!

**Comment by chiwalfrm** [comment]
figured it out

```
binance = ccxt.binance()
binance.sapi_get_margin_isolated_account()

```
closing this issue.

**Comment by kroitor** [comment]
@chiwalfrm thanks for your feedback!

Please, make sure to follow this: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
