### ISSUE TITLE
Kucoin kucoin.fetchOrderBook("BTC/USDT") returns error

### ISSUE THREAD

**Issue by DmitryVil** [ccxt/ccxt#8416]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: windows 10 
- Programming Language version: python 3.8
- CCXT version:  '1.39.51'

```
import ccxt
kucoin = ccxt.kucoin()
book = kucoin.fetchOrderBook("BTC/USDT")
```

```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://openapi-v2.kucoin.com/api/v1/market/orderbook/level2?symbol=BTC-USDT
....
ccxt.base.errors.NotSupported: not exist
```
**kucoin.fetchBalance()   works properly**

**Comment by kroitor** [comment]
Please, upgrade to the most recent version of CCXT, this issue has been addressed yesterday:

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/issues/8409
