### ISSUE TITLE
issue with withdraw

### ISSUE THREAD

**Issue by kingofclubstroy** [ccxt/ccxt#842]
Hey, I withdrew funds from bittrex and it has taken well over 12 hours, and so i started to look into it and it says that for binance (the exchange I tried to transfer to) "Depositing Monero to binance requires BOTH a deposit address and deposit payment ID, if you fail to include the payment ID with your deposit the funds will be lost forever". So now i'm wondering how i can include a payment ID, i see on the withdraw function it takes a param dict, but i can't seem to find the function it calls to make the request "accountGetWithdraw()" anywhere, it would be nice to see that function, or at the very least find the format i need to add the payment ID parameter, and potentially to add a deposit tag as ripple requires that as well.
Thanks in advance!

**Comment by kroitor** [comment]
Hi!

This question has been answered here:

- https://github.com/ccxt/ccxt/issues/303 (custom APIs, question and answer)
- https://github.com/ccxt/ccxt/issues/526 (unified API, question and answer)

Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#passing-parameters-to-api-methods (custom APIs)
- https://github.com/ccxt/ccxt/wiki/Manual#unified-api (unified API)

> Note, that most of methods of the unified API accept an optional params parameter. It is an associative array (a dictionary, empty by default) containing the params you want to override. Use the params dictionary if you need to pass a custom setting or an optional parameter to your unified query.

If you don't mind, I would close this for now as a duplicate. Let us know if we can help with anything else. Thx!

**Comment by kingofclubstroy** [comment]
Thank you for that, that has definitely helped, I was also wondering how i would be able to receive the paymentId from Bittrex before i call the withdraw function so i could pass it in as a parameter, i can only see a way to get paymentId when looking at withdrawal history, thanks again for your time, your library is great and you have been very helpful!

**Comment by kroitor** [comment]
@kingofclubstroy 

> Kirk Portas @kirkportas 05:44
Hey guys, I just started and built a portfolio overview tool with ccxt this past week, its an amazing library I'm looking to calculate all fiat/usd deposits made into a few exchanges, does anyone know if that's built into the lib already? e.g. (fetchDeposits)

> Igor Kroitor @kroitor 07:12 that particular aspect isn't unified yet, so there's no fetchDeposits for now (but we have plans on unifying it as well), however you can still use ccxt to fetch deposits and withdrawals with exchange-specific APIs that are built into the lib. I don't know your language, but you should be able to see the list of all available methods like so:
```
console.log (new ccxt.kraken ())   // JavaScript
print (dir (ccxt.hitbtc ()))        # Python
var_dump (new \ccxt\okcoinusd ()); // PHP
```

> Kirk Portas @kirkportas 07:14 Awesome. I'll give a go at using those, and maybe come back for a PR sometime.

> Igor Kroitor @kroitor 07:15 And from there you choose your method and pass the params like so: https://github.com/ccxt/ccxt/wiki/Manual#passing-parameters-to-api-methods

Also: https://github.com/ccxt/ccxt/issues/727 )

**Comment by kingofclubstroy** [comment]
I'm sorry to be a bother, but i can, and have been able to get withdrawal history, and maybe i am misunderstanding this, but it seems to me to be able to withdraw certain coins i need to include extra parameter like payment id into the withdrawal function, but i don't know how to receive the payment id before i call withdraw, i can see it when i fetch withdrawal history after i have made the withdrawal, but don't i need it before that in order for it to work?

**Comment by kroitor** [comment]
It depends on the exchange you're withdrawing from.

> but don't i need it before that in order for it to work

Yes, you do. Use `fetchDepositAddress()` for that: https://github.com/ccxt/ccxt/pull/699

**Comment by kroitor** [comment]
> should i just call

Yes )

> just want to get this right and working so i don't lose more coins by improperly withdrawing

Use the smallest amount possible )

**Comment by kingofclubstroy** [comment]
alright i will try with a smaller amount, thanks for your help and time!
