### ISSUE TITLE
How can I get my position list by Bybit?

### ISSUE THREAD

**Issue by sonokino18** [ccxt/ccxt#8420]
- OS: win10
- Programming Language version: python3.8
- CCXT version: up to date

I want to get my position list so I wrote the code like this

exchange.private_get_position_list({"symbol": 'BTCUSD'}))['result'] 

but I got an error message saying 
AttributeError: 'bybit' object has no attribute 'private_get_position_list'

How can I fix it?

**Comment by frosty00** [comment]
can you show us all the code you are running **without** your apiKeys

**Comment by sonokino18** [comment]
my code is simple
---------------------------------
import ccxt

bybit = ccxt.bybit({
    'enableRateLimit': True,
    'options': {
        'adjustForTimeDifference': True,
    },
    'apiKey': 'my api key',
    'secret': 'my secret',
})

print(bybit.private_get_position_list({"symbol": 'BTCUSD'})['result'])

**Comment by sonokino18** [comment]
I wrote this code for checking how much position I am holding (ex. long position, 100 amount, price: 38000$)
Especially I want to find out that  whether my order is successfully matched or not. 
If you know an alternative way to get this kind of data, lt would be okay. thx.

**Comment by kroitor** [comment]
@sonokino18 let us know if this example does not help:

- https://github.com/ccxt/ccxt/tree/master/examples/py/bybit-positions.py

```Python
import ccxt  # noqa: E402

from pprint import pprint

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.bybit ({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,  # https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
})

# https://github.com/ccxt/ccxt/wiki/Manual#loading-markets

markets = exchange.load_markets()

# exchange.verbose = True  # uncomment for debugging

# -----------------------------------------------------------------------------

symbol = 'BTC/USDT'
market = exchange.market(symbol)

response = exchange.private_linear_get_position_list({'symbol':market['id']})
linear_positions = response['result']
pprint(linear_positions)

# -----------------------------------------------------------------------------

symbol = 'BTC/USD'
market = exchange.market(symbol)

response = exchange.v2_private_get_position_list({'symbol':market['id']})
inverse_positions = response['result']
pprint(inverse_positions)
```

**Comment by sonokino18** [comment]
It woks!!! 
Thanks a lot :)

**Comment by gancarani** [comment]
Hi,
I'm getting the position but not the sign of the position. Is there a way to get the sign?
