### ISSUE TITLE
watchCreateOrder/watchCancelOrder not supported yet?

### ISSUE THREAD

**Issue by wunderb1t** [ccxt/ccxt#8423]
watchCreateOrder/watchCancelOrder is currently not supported for any exchange in ccxt pro?

**Comment by kroitor** [comment]
Most of the the exchanges don't have the means for placing the orders over WS, so it boils down to `createOrder` + `watchOrders`. In other words, you should be able to watch your orders while they're being created (which is what you want as far as I understand).
Let us know if that does not answer your question.
