### ISSUE TITLE
kucoin deprecated endpoints causing "ccxt.base.errors.NotSupported: not exist" error with limit=20 or limit=100 arguments on fetch_order_book()

### ISSUE THREAD

**Issue by elitwilliams** [ccxt/ccxt#8424]
Kucoin deprecated some endpoints and it appears to be causing some issues with ccxt. The deprecation notice does not appear to be in their docs yet (?), but please see (poorly worded) email info from them below. Using `limit=20` or `limit=100` arguments in `fetch_order_book()` calls throw an error, but `limit=None` still works. This also impacts ccxt.pro since the order_book snapshot makes a `fetch_order_book()` call. Thanks! Please let me know if I can be of further help.

- OS: macOS, Big Sur v11.2
- Programming Language version: Python 3.8.5
- CCXT version: 1.41.70

```
import ccxt
print(ccxt.kucoin().fetch_order_book(symbol="BTC/USDT", limit=20))
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 589, in fetch
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://openapi-v2.kucoin.com/api/v2/market/orderbook/level2_20?symbol=BTC-USDT

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/eliwilliams/Desktop/test.py", line 2, in <module>
    print(ccxt.kucoin().fetch_order_book(symbol="BTC/USDT", limit=20))
  File "/usr/local/lib/python3.8/site-packages/ccxt/kucoin.py", line 720, in fetch_order_book
    response = self.publicGetMarketOrderbookLevelLevel(self.extend(request, params))
  File "/usr/local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 466, in inner
    return entry(_self, **inner_kwargs)
  File "/usr/local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 491, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 487, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 605, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/usr/local/lib/python3.8/site-packages/ccxt/kucoin.py", line 1716, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, message)
  File "/usr/local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 505, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.NotSupported: not exist
```

Kucoin e-mail to customers:

> 
> Dear KuCoin Users,
> 
> In order to further improve the quality of service, KuCoin will be disabling obsolete API and websocket functions at 6:00:00 am February 7, 2021 (UTC). During this period, spot websocket message push will be unstable, and there will be a short-term impact on market-related interfaces. Futures will not be affected.
> 
> The functions are as follows：
> 1. The V1 interface of all Level-2 Order Books (aggregated): GET/api/v1/market/orderbook/level2
> 2. All Level-3 Order Book (atomic) interfaces: GET /api/v1/market/orderbook/level3
> 3. Old version websocket: Full MatchEngine Data (Level 3)
> 4. Websocket private channel topic ({topic}:privateChannel:{userId})
> 
> If you are currently using any of the above endpoints and functions, please ensure that you leave sufficient time to change or migrate to other endpoints to not affect your normal trading.We apologize for any inconvenience this may cause.Thanks for your support!
> 
> The KuCoin Team

---

**Comment by kroitor** [comment]
Please, upgrade to the most recent version, this is step 1 in the troubleshooting sequence:

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

This issue has been addressed and fixed:

- https://github.com/ccxt/ccxt/issues/8416
- https://github.com/ccxt/ccxt/issues/8409

Let us know if you have difficulties with it after upgrading to the most recent version of CCXT.

**Comment by elitwilliams** [comment]
I am running ccxt v1.41.70 and ccxtpro v0.5.57 which are the current versions. Arguments of `limit=20` and `limit=100` for partial depth order book info do still break the `fetch_order_book()` call. As mentioned `limit=None` works for full order book depth, so I will use that for now. Thanks!

**Comment by kroitor** [comment]
@elitwilliams 

> Arguments of limit=20 and limit=100 for partial depth order book info do still break the fetch_order_book() call.

I will investigate the `limit` issue and will get back to you asap. Thanks for your feedback!
