### ISSUE TITLE
Questions about using 'https-proxy-agent' to make requests

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#8428]
OS: Windows Server 2019 Datacenter
Programming Language version: Node.js 15.3.0
CCXT version: 1.38.89
Exchange: All Exchanges
Method: https-proxy-agent

Hello!

I am trying to use a proxy to retreive the orderbook. Now the IP: "http://185.236.202.205:3128" is a free and shared IP address which worked at the time when I wrote this post by checking it here: "https://www.infobyip.com/proxychecker.php"

However when I run the code, I get an error that says: 
**ExchangeNotAvailable: bitfinex GET https://api.bitfinex.com/v1/symbols system request to https://api.bitfinex.com/v1/symbols failed, reason: socket hang up**

I might have 3 questions.

**Question 1:** 
Have I put the code correctly like this or do I miss something (Why does the connection hang up. I tried both binance,bitfinex)?

**Question 2:**
Initially, I am thinking of using for example 10 different IP addresses which I will rotate in order to get many orderbooks at the very same time. I beleive using this proxy method is a good idéa to do it?

**Question 3**
If using API keys in the request. The request would be bind to my user on the exchange. How does that work if they see that different IP addresses are used faster then they allow for the rate limit?

Thank you!

```'use strict';
const ccxt = require('ccxt'),
                    HttpsProxyAgent = require('https-proxy-agent');

const proxy = 'http://185.236.202.205:3128'; // HTTP/HTTPS proxy to connect to
const agent = new HttpsProxyAgent(proxy);

(async () => {
    const start = Date.now();

    const exchange = new ccxt.bitfinex({ enableRateLimit: true, agent, 'timeout': 10000 });
    const orderbook = await exchange.fetchOrderBook("BTC/USDT", 5); 
    console.log(orderbook);


    const end = Date.now();
    console.log(`OrderBooks in ${(end - start) / 1000} seconds`);
})()

**Comment by kroitor** [comment]
> Have I put the code correctly like this or do I miss something (Why does the connection hang up. I tried both binance,bitfinex)?

That proxy is not responding to public requests: 

<img width="1661" alt="Screenshot 2021-03-13 at 01 43 38" src="https://user-images.githubusercontent.com/1294454/111006310-a538cf80-839d-11eb-8497-538f652a5480.png">

> Initially, I am thinking of using for example 10 different IP addresses which I will rotate in order to get many orderbooks at the very same time. I beleive using this proxy method is a good idéa to do it?

Yes it will work.

> If using API keys in the request. The request would be bind to my user on the exchange. How does that work if they see that different IP addresses are used faster then they allow for the rate limit?

Some exchanges rate-limit by apiKeys, other exchanges rate-limit by IP, others remember both apiKeys+IP. In most cases, you should not use the same private keypair with multiple instances of the same exchange simultaneously in parallel, unless you are implementing your own custom rate-limiting to properly manage your request queue and nonce numbers.

Let us know if the above does not answer your questions. Feel free to reopen it or just ask further questions if any.
