### ISSUE TITLE
{     "code": -2014,     "msg": "API-key format invalid." } Binance Postman

### ISSUE THREAD

**Issue by GaussDeMoivre** [ccxt/ccxt#8429]
Hello, i downloaded the binance collection for postman. I was following the tutorial, then got this error for my first GET Account Information request. However the GET server time works, which implies that the collection and environment are well set. I doubled check my API keys and they are correct as well. I'm sure that the problem is with the timestamp. Hope someone had the same problem and fixed it. Thank

**Comment by kroitor** [comment]
@GaussDeMoivre hi! Are you using CCXT?

**Comment by GaussDeMoivre** [comment]
> @GaussDeMoivre hi! Are you using CCXT?
> You may want to recreate the api keypair and make sure that you've copied the new keypair correctly. Also, you will need to set up permissions on the keypair.

Hello @kroitor ! I created new keys and i'm still using the Spot Testnet API so there's no permissions to handle. I used Postman so that i wouldn't have to pass through all the programming and could directly use the API, so no i didnt use CCXT.
Could i integrate the CCXT into Postman?

**Comment by GaussDeMoivre** [comment]
I found it, it has to do with the internal clock

**Comment by mojtabaAmiraslanpour** [comment]
> I found it, it has to do with the internal clock

I have the same problem, What do you mean by the internal clock?

**Comment by huiruo** [comment]
> I found it, it has to do with the internal clock

I have the same problem, What do you mean by the internal clock?

**Comment by averinpro** [comment]
Did you find how to solve the problem? The error appears from time to time

**Comment by huiruo** [comment]
Yes, I have. Please refer to this project: https://github.com/huiruo/cryptocurrency-trading


---Original---
From: "Averin.pro Артемий ***@***.***&gt;
Date: Mon, Dec 20, 2021 19:48 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ccxt/ccxt] {     "code": -2014,     "msg": "API-key format invalid." } Binance Postman (#8429)




 
Did you find how to solve the problem? The error appears from time to time

**Comment by ChenHaoJie9527** [comment]
> 是的，我有。请参考本项目：[https ://github.com/huiruo/cryptocurrency-trading](https://github.com/huiruo/cryptocurrency-trading)
> […](#)
> ---原文--- 来自：“Averin.pro Артемий ***@***.***> 日期：2021 年 12 月 20 日星期一晚上 19​​:48 至：***@***.* **>;抄送：***@***.******@***.***>;主题：回复：[ccxt/ccxt] {“代码”：-2014，“ msg": "API-key format invalid." } Binance Postman ( #8429 ) 你找到解决办法了吗收到此消息是因为您发表了评论。消息 ID：***@***.***>
hello,I didn't receive the method you said

**Comment by zgpnuaa** [comment]
If the computer is using a proxy, 'requests_trust_env':True should be added to the config.
My successful  config is as fellows:
```
exchange = ccxt.binance(config={
    'apiKey': 'XXX',
    'secret': 'XXX',
    'enableRateLimit': True,
    'timeout':100000,
    'requests_trust_env':True,
    'options': {
            'adjustForTimeDifference':True,
        }
}) 
```

**Comment by Mr-Fubowen** [comment]
Here is the solution
This is a bug of the developer. The custom API request header was not used.

step1: This is the called code.
` 
const opts = {
    apiKey: API_KEY,
    basePath: 'https://api.binance.com',
    privateKey: PRIVATE_KEY,
    timeout: 10000,
    timeUnit: TimeUnit.millisecond,
    wsURL: SPOT_WS_STREAMS_PROD_URL,
    customHeaders: {
        **'X-MBX-APIKEY': API_KEY**
    }
}

const AccountApi = new SpotRestAPI.AccountApi(opts)
`
step2: Check out this link to fix this bug.
https://github.com/binance/binance-connector-js/issues/529
