### ISSUE TITLE
Wrong currency on Wex

### ISSUE THREAD

**Issue by alexsith** [ccxt/ccxt#843]
Hello. 
I found mistake: 
wexnz = ccxt.wex();
to_ob = wexnz.fetch_order_book('DASH/USD', {'depth': 10});

But where is no DASH at Wex, only DSH, which is Dash coin.

Thank you for such a greate framework!

**Comment by kroitor** [comment]
Hi! This is not an error: https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

**Comment by kroitor** [comment]
However, I might be actually wrong... Sorry, do you mean that the substitution of DSH → DASH is wrong?

**Comment by kroitor** [comment]
No, it looks like I'm not...
```
>>> ccxt.bittrex().fetch_ticker('DASH/BTC')['last']
0.05267087
>>> ccxt.kraken().fetch_ticker('DASH/BTC')['last']
0.05066
>>> ccxt.wex().fetch_ticker('DASH/BTC')['last']
0.0516
>>> ccxt.bitfinex().fetch_ticker('DASH/BTC')['last']
0.051145
>>> 
```

**Comment by kroitor** [comment]
<img width="685" alt="screen shot 2017-12-12 at 23 00 46" src="https://user-images.githubusercontent.com/1294454/33905635-5abd6768-df90-11e7-9661-3ff6467da89e.png">
<img width="631" alt="screen shot 2017-12-12 at 23 01 04" src="https://user-images.githubusercontent.com/1294454/33905637-5c966256-df90-11e7-8406-0ca43a3d55e6.png">

**Comment by alexsith** [comment]
Thank you. I guess it is mistake in wex web-interface, because on their trade-chart there is "dashcoin/eur", that was confuse for me
