### ISSUE TITLE
Limit on open watchOrders connections 

### ISSUE THREAD

**Issue by wunderb1t** [ccxt/ccxt#8430]
Is there limitation on open watchOrders connections from side of exchanges? Mostly FTX and Binance are interesting.

**Comment by kroitor** [comment]
@wunderb1t in general you don't really need more than one, unless you're using multiple accounts in parallel... why?

**Comment by wunderb1t** [comment]
In our app we need to monitor multiple accounts of our users. So with user number growth,  number of open connection also will grow. Therefore it is important to know about limitations for open connections in parallel.

**Comment by diwenshi61** [comment]
Binance websocket limits are not very restrictive and allow for up to 1024 streams per connection, as for per IP address, it is unclear. You can see the limits specified [here](https://binance-docs.github.io/apidocs/spot/en/#limits).
FTX does not seem to cap max websockets open, and I believe all limits are per subaccount and not per IP address.
