### ISSUE TITLE
Binance testnet orders expired?

### ISSUE THREAD

**Issue by reynard80** [ccxt/ccxt#8437]
- OS: Ubuntu Server
- Programming Language version: NodeJS v14.15.4
- CCXT version: v1.41.64

I'm trying to place orders on the Binance Spot testnet. However, all orders get status 'Expired' without getting filled. I can't find any docs on the testnet, but is this normal? Do all order just expire on the testnet?

I tried various methods but none work, example:
`        const order = await client.createMarketBuyOrder(
            strategy.asset + '/' + strategy.currency, 
            strategy.quantity,
        );`

I always get:
`{
  info: {
    symbol: 'BTCBUSD',
    orderId: 646,
    orderListId: -1,
    clientOrderId: 'x-...',
    transactTime: 1612902432828,
    price: '0.00000000',
    origQty: '0.01000000',
    executedQty: '0.00000000',
    cummulativeQuoteQty: '0.00000000',
    status: 'EXPIRED',
    timeInForce: 'GTC',
    type: 'MARKET',
    side: 'BUY',
    fills: []
  },
  id: '646',
  clientOrderId: 'x-...',
  timestamp: 1612902432828,
  datetime: '2021-02-09T20:27:12.828Z',
  lastTradeTimestamp: undefined,
  symbol: 'BTC/BUSD',
  type: 'market',
  timeInForce: 'GTC',
  postOnly: false,
  side: 'buy',
  price: 0,
  stopPrice: undefined,
  amount: 0.01,
  cost: 0,
  average: undefined,
  filled: 0,
  remaining: 0.01,
  status: 'expired',
  fee: undefined,
  trades: []
}`

Edit: added complete verbose

**Comment by kroitor** [comment]
@reynard80 Please, paste the entire verbose info:

```JavaScript
await client.loadMarkets()
client.verbose = true
const order = await client.createMarketBuyOrder( strategy.asset + '/' + strategy.currency, strategy.quantity, );
```

Do not cut out `info`, cause it should make obvious where that expired status comes from. If it is in the `info` then it comes from Binance itself, and you might want to ask here about it: https://t.me/binance_api_english

**Comment by reynard80** [comment]
I've added the verbose 'info'. I don't see anything suspicious?

Binance telegram group is a good suggestion.

**Comment by cherbert** [comment]
Probably lack of liquidity in the market you are trading. Try BNB/USDT

**Comment by reynard80** [comment]
You're right, thanks guys. Sorry for posting this as a ccxt issue. Will try the Binance API Telegram group first in the future.

**Comment by kroitor** [comment]
@cherbert, @reynard80 thx for your help and feedback!

**Comment by Jaaposaur** [comment]
I realize this has been closed but was the problem simply lack of liquidity. Im hitting the same issue but only with OCO orders. Im trading BNB/UDST. Orders always expire roughly at the end of the 5 min candle.
