### ISSUE TITLE
Kucoin No longer fetches OrderBooks Properly

### ISSUE THREAD

**Issue by arun4444** [ccxt/ccxt#8438]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:

```
https://github.com/ccxt/ccxt/blob/master/js/kucoin.js#L735
Generates a bad URL under v2 of kucoin API
leads to:
https://openapi-v2.kucoin.com/api/v2/market/orderbook/level2_20?symbol=ETH-BTC
404
Valid URL seems to be:
https://openapi-v2.kucoin.com/api/v2/market/orderbook/level2?symbol=ETH-BTC

```

```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
```

**Comment by kroitor** [comment]
Duplicate: 

- https://github.com/ccxt/ccxt/issues/8424
- https://github.com/ccxt/ccxt/issues/8416

**Comment by kroitor** [comment]
P.S. Just upgrade to the most recent version of CCXT.
