### ISSUE TITLE
create_order fails for hitbtc, price starts with spaces

### ISSUE THREAD

**Issue by hansvanzutphen** [ccxt/ccxt#844]
If you create a limit buy or sell order, there's an sprintf in create_order:
$order['price'] = sprintf ('%10f', $price);
If the price is small this will give a number that starts with spaces, and that returns an error (a very confusing one I might add...). I've for now replaced it by %010f (since I'm not sure if the 10 is there for a reason).

**Comment by hansvanzutphen** [comment]
On top of that I just saw that it rounds it wrong (uses 6 digits instead of 8)

**Comment by kroitor** [comment]
Hi! I will take a look into it asap. In the meantime, I'd recommend to migrate to HitBTC v2 API, because v1 is deprecated and it will be abandoned sooner or later (most likely, sooner). I'll get back you with a follow up on this.

**Comment by kroitor** [comment]
> On top of that I just saw that it rounds it wrong (uses 6 digits instead of 8)

The rounding is done by the HitBTC itself, based on this:
- https://github.com/hitbtc-com/hitbtc-api/blob/master/APIv1.md#currency-symbols
- https://api.hitbtc.com/#create-new-order

**Comment by kroitor** [comment]
This is fixed in 1.10.373. Let us know if you have any difficulties with it. Thx!
