### ISSUE TITLE
Problem with last price python vs php

### ISSUE THREAD

**Issue by AloneInTheDark** [ccxt/ccxt#8442]
We have a problem related with Kraken and other Exchange price request. 

Below you can find the script we use to request those info through Python and it works. 

```
import ccxt
from pprint import pprint

exchange = ccxt.kraken ({
    'enabelRateLimit': True,
})
exchange.load_markets()
symbol = 'ADA/EUR'
v = exchange.fetch_ticker(symbol)
print(v)

```

But if we try doing it in PHP, it doesn’t work anymore, although it seems to be the same code. Below PHP not working example: 

```
$symbol='ADA/EUR';
$id = 'kraken';
$exchange = '\\ccxt\\' . $id;
$exchange = new $exchange ();
$v = $exchange->fetch_ticker($symbol);
var_dump($v);

```

It give us the following error:

**_Fatal error: Fatal error: Uncaught ccxt\BadSymbol: kraken does not have market symbol ADA/EUR_**

- OS: Windows 10
- Programming Language version: python 3.8 , php  7.2.1
- CCXT version: 1.41.78

**Comment by ttodua** [comment]
It's a bit old topic, but kraken works fine now, tested both your snippets and they do work as expected. probably there was some temporary issue back in the past, by the time you opened the issue. Let us know if you have any further issues in ccxt.
