### ISSUE TITLE
Custom message handling in CCXT Pro

### ISSUE THREAD

**Issue by diwenshi61** [ccxt/ccxt#8447]
Currently, CCXT Pro routes messages to the correct internal handler function through a local variable "methods" within that class's handle_message method.
e,g,
```
methods = {
     'some_update': self.method,
     'some_other_update': self.method,
     'another_update': self.another_method
}
```
I think that making this variable an instance or class variable could be valuable for code customization while having little impact on existing functionality. Users can then add custom handlers without having to modify the base code, for example
```
def print_message(client, message):
    print(message)

some_exchange = ccxtpro.some_exchange()
some_exchange.methods['sample_method'] = print_message
```
would allow the user to print out all messages with content "sample_method" easily, or if the user still wanted to maintain existing functionality:
```
def print_message_and_call_original_method(client, message, method):
    print(message)
    method(client, message)

some_exchange = ccxtpro.some_exchange()
original_method = some_exchange.methods['sample_method']
some_exchange.methods['sample_method'] = lambda client, message: print_message_and_call_original_method(client, message, original_method)
```

I want to know what you think of this suggestion. Perhaps there is something that I'm missing which makes this impractical, as well. Any feedback is appreciated, thanks!

**Comment by kroitor** [comment]
@diwenshi61 this is a good way of customization, but it is only applicable to exchange-specific (non-unified) streams. If that's ok, we will export those routing properties.

**Comment by diwenshi61** [comment]
> 
> 
> @diwenshi61 this is a good way of customization, but it is only applicable to exchange-specific (non-unified) streams. If that's ok, we will export those routing properties.
True, definitely it would be most useful for non-unified streams. But I also think that even for unified methods, there are benefits that can be realized, even if they are niche. For example, existing methods could be removed if they are unneeded for a performance speedup.

**Comment by kroitor** [comment]
@diwenshi61 yeah, that makes sense. We will add the edits.

**Comment by ttodua** [comment]
for now, to override internal handler, users can override `exchange.handle_message` (in python) or `.handleMessage` (in js) method. in near future we would support hooking into ws streams. users are advised to monitor ccxt announcements for notice: https://discord.com/channels/690203284119617602/1057748769690619984
