### ISSUE TITLE
Binance API error code":-1104,"msg":"Not all sent parameters were read

### ISSUE THREAD

**Issue by FredYellow** [ccxt/ccxt#8449]
Hi, 

When trying to create a limit buy order I get an error from the API. This is the verbose output:

`2021-02-12 11:43:02.456558 - create_order - Attempt 0

Request: POST https://api.binance.com/api/v3/order 
{'X-MBX-APIKEY': 'my api key', 
'Content-Type': 
'application/x-www-form-urlencoded', 
'User-Agent': 'python-requests/2.25.1', 
'Accept-Encoding': 'gzip, 
deflate'} 

timestamp=1613126582968&
recvWindow=5000&
symbol=ETHBTC&
type=LIMIT&
side=BUY&
newClientOrderId=x-R4BD3Ss5d4fs64s4152cd6e07f4&
newOrderRespType=RESULT&
quantity=0&
price=0.037708&
timeInForce=GTC&
created=1611324900000&
signature=3db80e619c1956549ds8d4sd65s40826d7aa7f521abf750243210bddafc

Response: POST https://api.binance.com/api/v3/order 
400 {'Content-Type': 'application/json;charset=UTF-8', 
'Content-Length': '99', 
'Connection': 'keep-alive', 
'Date': 'Fri, 12 Feb 2021 10:43:05 GMT', 
'Server': 'nginx', 'x-mbx-uuid': '5s6ds569-5c61-424b-9545-11aa287d02ad', 
'x-mbx-used-weight': '9', 
'x-mbx-used-weight-1m': '9', 
'Strict-Transport-Security': 
'max-age=31536000; includeSubdomains', 
'X-Frame-Options': 'SAMEORIGIN', 
'X-Xss-Protection': '1; mode=block', 
'X-Content-Type-Options': 'nosniff', 
'Content-Security-Policy': "default-src 'self'", 
'X-Content-Security-Policy': "default-src 'self'", 
'X-WebKit-CSP': "default-src 'self'", 
'Cache-Control': 'no-cache, no-store, must-revalidate', 
'Pragma': 'no-cache', 
'Expires': '0', 
'X-Cache': 'Error from cloudfront', 
'Via': '1.1 63cf97e5788s65df4s6d42e2ca29.cloudfront.net (CloudFront)', 
'X-Amz-Cf-Pop': 'AMS50-C1', 
'X-Amz-Cf-Id': 'JF6LLU6s5fr4e6sefgNrPSeV9r9_CAiJvsuxE1LyAzwt_iMWueg=='} {"code":-1104,"msg":"Not all sent parameters were read; read '11' parameter(s) but was sent '12'."}`

I formatted the output to be easily readable.
What is the issue with my create order request? The Quantity being 0? Then I would expect a different error from Binance about the minimum order quantity.

**Comment by kroitor** [comment]
Hi!

You should follow these rules: https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits

Assuming that your amount is `amount`:

```
print(exchange,amount_to_precision(symbol, amount))  # will print your value formatted to precision
```

↑ If this is 0, you're not meeting the `precision` or `limits` criteria for the `symbol` that you use.

Let us know if that does not answer your question.

**Comment by FredYellow** [comment]
Excellent response, that worked for me!
