### ISSUE TITLE
Daily withdraw limit used

### ISSUE THREAD

**Issue by napster3000** [ccxt/ccxt#845]
- [ ] bug report
- [x] question
- [ ] feature request

- Operating System: Unix
- Language +version: JS
- CCXT version:
- Exchange: Gdax, Poloniex
- Method: Withdraw 

### Description

Is it possibile to access how much of the daily withdraw limit I have used? 

###

[![Gitter](https://badges.gitter.im/ccxt-dev/ccxt.svg)](https://gitter.im/ccxt-dev/ccxt?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by kroitor** [comment]
> Is it possibile to access how much of the daily withdraw limit I have used?

You will have to fetch your withdraw history with a custom method from ccxt for each particular exchange and calculate the limits from there.

To get a list of all available methods with the exchange:

```
Object.keys (new ccxt.poloniex ())
      .filter (key => typeof exchange[key] == 'function')
      .map (key => console.log (key))

Object.keys (new ccxt.gdax ())
      .filter (key => typeof exchange[key] == 'function')
      .map (key => console.log (key))
```

More about calling custom methods and passing params: 

- https://github.com/ccxt/ccxt/wiki/Manual#api-methods--endpoints
- https://github.com/ccxt/ccxt/wiki/Manual#passing-parameters-to-api-methods

Let me know if this answers your question or not.
