### ISSUE TITLE
Question. How can we receive events when the orders are filled?

### ISSUE THREAD

**Issue by Danilo-Araujo-Silva** [ccxt/ccxt#8451]
If we want to use CCXT to place a limit or stop limit order,
can we create it on a way that we receive an event when the order is filled?

If yes, can you please point me to what we can use?

If not, what do you think it would be the best workaround to simulate this feature with the available methods?
(One simple solution would be checking the last trade every second, but maybe we have something better)

**Comment by frosty00** [comment]
The best way for this is to use `watchOrders` over the WebSocket connection in https://ccxt.pro

It's a paid subscription for the WebSocket APIs
