### ISSUE TITLE
filter_by_since_limit bugs

### ISSUE THREAD

**Issue by diwenshi61** [ccxt/ccxt#8456]
In ccxtpro, some files have bugs in them using this function.
filter_by_since_limit(self, array, since=None, limit=None, key='timestamp', tail=False)
has an argument 'key' in it, however some functions seem to miss this, and some do not sort by tail though they probably should.

ftx.py line 113:
return self.filter_by_since_limit(trades, since, limit, True)

gateio.py line 429:
return self.filter_by_since_limit(orders, since, limit)
(not sure, but I think this is meant to be sorted in reverse too)

hitbtc.py line 185:
return self.filter_by_since_limit(trades, since, limit, True)

idex.py line 139, 220, 445, 560:
return self.filter_by_since_limit(trades, since, limit)
return self.filter_by_since_limit(ohlcv, since, limit)
return self.filter_by_since_limit(orders, since, limit)
return self.filter_by_since_limit(transactions, since, limit)
(not sure, but I think this is meant to be sorted in reverse too)

upbit.py line 55:
return self.filter_by_since_limit(trades, since, limit, True)

Needs to be fixed in the js implementation.

**Comment by diwenshi61** [comment]
Hi @kroitor, I noticed that you removed the True argument in your fix. I think that the fix should be to add the key parameter, since the desired implementation should still be to count the limit from the tail.

**Comment by kroitor** [comment]
@diwenshi61 yes, it will count from tail if `since` is None, i think it should be the way it is now, let me know if I'm missing something.

**Comment by diwenshi61** [comment]
@kroitor these lines don't seem to agree:
(https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/exchange.py line 1781)
```
    def filter_by_since_limit(self, array, since=None, limit=None, key='timestamp', tail=False):
        array = self.to_array(array)
        if since is not None:
            array = [entry for entry in array if entry[key] >= since]
        if limit is not None:
            array = array[-limit:] if tail and (since is None) else array[:limit]
        return array
```
Is it supposed to be `if tail or since is None` here?

**Comment by kroitor** [comment]
@diwenshi61 the logic goes this way:

- if `since` is specified – we are not counting from tail, even if tail is True
- if `since` is not specified – we can count from tail, if tail = True

Does that make sense?

**Comment by diwenshi61** [comment]
@kroitor The logic makes sense there, yes. But I believe we want to have tail to be True - because otherwise, we won't be counting from the last trade, once we've received `limit` trades we'll be stuck returning the first `limit` trades over and over. So what we'd want would be to change the line to
`return self.filter_by_since_limit(trades, since, limit, 'timestamp', True)`
since this will make the trades iterate from the end, when since is not specified.
