### ISSUE TITLE
Query kucoin for all past user trades returns nothing

### ISSUE THREAD

**Issue by LefterisJP** [ccxt/ccxt#8457]
- OS: Linux
- Programming Language version: Python v3.7.9
- CCXT version: 1.41.87

Hello. I have been trying to use ccxt to fetch all past Kucoin closed orders of some user's api key. I read some relevant past closed issues, and noticed that you must query the endpoint in increments of 1 week as per [this](https://github.com/ccxt/ccxt/blob/master/examples/py/kucoin-fetch-closed-orders-pagination.py) example in your docs.

I tried to do that with a slightly modified version as the original failed. The `"endAt"` has to be no more than a week after `"startAt"` so the `max` had to be switched to a `min`, or an error is returned. Also I start since the founding of Kucoin (09/2017 according to google).

```python
# -*- coding: utf-8 -*-

import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')

import ccxt  # noqa: E402

exchange = ccxt.kucoin({
    "apiKey": "KEY",
    "secret": "SECRET",
    "password": "PASSWORD",
    'enableRateLimit': True,
})
exchange.load_markets()
# exchange.verbose = True  # enable verbose mode after loading the markets

symbol = None  # all orders
now = exchange.milliseconds()
day = 24 * 3600 * 1000
week = 7 * day
since = 1504224000000 # founding of kucoin in ms 
limit = 20
found_orders_num = 0

while since < now:

    end = min(since + week, now)
    params = {'endAt': end}
    orders = exchange.fetch_closed_orders(symbol, since, limit, params)
    print(exchange.iso8601(since), '-', exchange.iso8601(end), len(orders), 'orders')
    found_orders_num += len(orders)
    if len(orders) == limit:
        since = orders[-1]['timestamp']
    else:
        since += week

print(f'Found {found_orders_num} orders')
```

This returns 0 closed orders. Even though essentially the `since` parameters starts at the founding of Kucoin and the user does have closed trades in their account.

What am I doing wrong? Am I missing something? Shouldn't the above return any trades the user has completed in their account since they started using the exchange?

**Comment by LefterisJP** [comment]
Worthy of noting. The above is for old trades. The aforementioned user had trades in 2018 and early 2019.

I got the api key of a different user who had more recent trades (inside 2020 only). And the script returned all of them.

So perhaps it's something to do with old kucoin trades?

**Comment by kroitor** [comment]
@LefterisJP yes, there was a change in KuCoin API v1 vs v2, search the history for KuCoin issues and announcements:

- https://github.com/ccxt/ccxt/issues?q=kucoin+v1+label%3Aannouncement
- https://github.com/ccxt/ccxt/issues/4579
- https://github.com/ccxt/ccxt/issues/4696
- https://github.com/ccxt/ccxt/issues/4699
- ...

Let us know if that does not answer your issue.

**Comment by LefterisJP** [comment]
Hey @kroitor thank you for your answer.

I already saw those but what I am not sure about is this. Is there any way whatsoever through the kucoin api (either via ccxt lib or not) to query for those older trades of a user? Or is it just not possible?

**Comment by kroitor** [comment]
@LefterisJP i'm afraid they have fully removed the support for v1 endpoints after a while, so there is no way to go that far in the past afaik...

**Comment by kroitor** [comment]
... unless you can find a CSV report on the website or ask for it via tech support.

**Comment by LefterisJP** [comment]
> unless you can find a CSV report on the website or ask for it via tech support.

Thank you.

That is what I need some confirmation for. And the cutoff date is the v2 date mentioned as `1550448000000  # 2019-02-18T00:00:00Z` in your code I suppose?

**Comment by kroitor** [comment]
@LefterisJP yep, those comments were added shortly after.

**Comment by LefterisJP** [comment]
@kroitor All right I see.

So even though the endpoints:

- `api/v1/hist-deposits`
- `api/v1/hist-withdrawals`
- `api/v1/hist-orders`

exist, they will just do nothing since they can't return anything before 2019-02-18 or after?

I am also mentioning it since it is in your code:
https://github.com/ccxt/ccxt/blob/ed5f6f424f7777db03022df8dcc6553b3230006b/python/ccxt/kucoin.py#L1381-L1385
https://github.com/ccxt/ccxt/blob/ed5f6f424f7777db03022df8dcc6553b3230006b/python/ccxt/kucoin.py#L1439-L1445
https://github.com/ccxt/ccxt/blob/ed5f6f424f7777db03022df8dcc6553b3230006b/python/ccxt/kucoin.py#L1032-L1037

So the logic of using the `hist-` endpoints until 2019-02-18 and the normal ones after does not actually work anymore then?

**Comment by kroitor** [comment]
@LefterisJP i've tested it on my side – works for me:

<img width="1453" alt="Screenshot 2021-02-14 at 20 21 49" src="https://user-images.githubusercontent.com/1294454/107883820-4ac56400-6f02-11eb-92c7-0547b92389c7.png">

```Python
from pprint import pprint
import ccxt

print('CCXT Version:', ccxt.__version__)
exchange = ccxt.kucoin({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'password': 'YOUR_PASSWORD',
    'enableRateLimit': True,
    'options': {'fetchMyTradesMethod':'private_get_hist_orders'}
})

since = exchange.parse8601('2018-01-01T00:00:00Z')
trades = exchange.fetch_my_trades(None, since)
pprint(trades)
```

**Comment by LefterisJP** [comment]
Hey @kroitor thank you. The key then was `'options': {'fetchMyTradesMethod':'private_get_hist_orders'}` and that this one underneath deals in seconds not milliseconds.

Thank you for your time and quick responses.

**Comment by pavitrakumar78** [comment]
Hi, the solution suggested by Kroitor does not work for me.

has this endpoint been removed from Kucoin? 

I'm using kucoinfutures class and the following does not return any trades:
```
        since = exchange.parse8601('2021-01-01T00:00:00Z')
        all_future_trades = exchange.fetch_my_trades(None, since)
```
However, the follow returns just the trades made in the lat 24 hrs:
```
        all_future_trades = exchange.fetch_my_trades(params={'pageSize': 100})
```

The only endpoint that works in getting old orders is `fetch_closed_orders` - is this the current state of Kucoin API? or am I doing something incorrectly?

**Comment by ttodua** [comment]
for future readers - [this answer](https://github.com/ccxt/ccxt/issues/10922#issuecomment-996339513) might help you.
