### ISSUE TITLE
error with costToPrecision on bittrex.py

### ISSUE THREAD

**Issue by kingofclubstroy** [ccxt/ccxt#846]
Is it a bug report, a question or feature request? <sup>*(choose one)*</sup>

- [x] bug report
- [ ] question
- [ ] feature request

- Operating System: python
- Language +version: 2.7
- CCXT version:
- Exchange:
- Method: 

### Description

Error with costToPrecision on bittrex.py:

 def cost_to_precision(self, symbol, cost):
        return self.truncate(float(cost), self.markets[symbol].precision.price)

it should be:

def cost_to_precision(self, symbol, cost):
        return self.truncate(float(cost), self.markets[symbol]["precision"]["price"])

### Verbose output

[Troubleshooting](https://github.com/kroitor/ccxt/wiki/Manual#troubleshooting)

```
COPYPASTE_YOUR_VERBOSE_OUTPUT_HERE
```

**For questions and discussions join our gitter chat:** 

[![Gitter](https://badges.gitter.im/ccxt-dev/ccxt.svg)](https://gitter.im/ccxt-dev/ccxt?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Comment by kroitor** [comment]
Fixed in 1.10.376! Thanks for reporting! Let us know if you have any other difficulties with it.
