### ISSUE TITLE
Okex optionGetAccounts() not working 

### ISSUE THREAD

**Issue by drixie** [ccxt/ccxt#8461]
I ran this code `okex.optionGetAccounts().then(result => console.log(result))` and got the following response in the terminal: 

`(node:20901) UnhandledPromiseRejectionWarning: ExchangeError: okex {"code":404,"data":{},"detailMsg":"","error_code":"404","error_message":"Not Found","msg":"Not Found"}
    at okex.handleErrors (/backend/node_modules/ccxt/js/okex.js:3634:19)
    at /backend/node_modules/ccxt/js/base/Exchange.js:602:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async timeout (/node_modules/ccxt/js/base/functions/time.js:195:24)
(node:20901) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20901) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

This is what the option section of okex.api looks like: 

`option: {
      get: [
        "accounts",
        "{underlying}/position",
        "accounts/{underlying}",
        "orders/{underlying}",
        "fills/{underlying}",
        "accounts/{underlying}/ledger",
        "trade_fee",
        "orders/{underlying}/{order_id}",
        "orders/{underlying}/{client_oid}",
        "underlying",
        "instruments/{underlying}",
        "instruments/{underlying}/summary",
        "instruments/{underlying}/summary/{instrument_id}",
        "instruments/{instrument_id}/book",
        "instruments/{instrument_id}/trades",
        "instruments/{instrument_id}/ticker",
        "instruments/{instrument_id}/candles",
      ],
      post: [
        "order",
        "orders",
        "cancel_order/{underlying}/{order_id}",
        "cancel_order/{underlying}/{client_oid}",
        "cancel_batch_orders/{underlying}",
        "amend_order/{underlying}",
        "amend_batch_orders/{underlying}",
      ],
    },`

Not sure if this is ccxt issue or if something has changed on their end.

**Comment by drixie** [comment]
Additional update to comply with issue submission guideline: 

Language: Javascript (Node)
Version number: 12.20.1
CCXT lib version number: ccxt@1.41.89
Exchange: Okex
Method being called: okex.optiongetAccounts()

Request: 
```okex.verbose=true
okex.optionGetAccounts()
.then(result=>console.log(result))
.catch(error=>console.log(error))```

Response: 
```
handleRestResponse:
 okex GET https://www.okex.com/api/option/v3/accounts 404 Not Found 
Response:
 {
  'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate',
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '62203e57c8901372-YVR',
  'Cf-Request-Id': '0848054ada0000137288aab000000001',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Type': 'application/json',
  Date: 'Mon, 15 Feb 2021 16:00:44 GMT',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Expires: '0',
  Pragma: 'no-cache',
  Server: 'cloudflare',
  'Set-Cookie': '__cfduid=d6876c1e46f454b7139d4e848069cd7441613404844; expires=Wed, 17-Mar-21 16:00:44 GMT; path=/; domain=.okex.com; HttpOnly; SameSite=Lax, locale=en_US; Max-Age=604800; Expires=Mon, 22-Feb-2021 16:00:44 GMT; Path=/, locale=en_US; Max-Age=604800; Expires=Mon, 22-Feb-2021 16:00:44 GMT; Path=/',
  'Transfer-Encoding': 'chunked',
  Vary: 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers',
  'X-Brokerid': '0',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'X-Xss-Protection': '1; mode=block'
} 
 {"code":404,"data":{},"detailMsg":"","error_code":"404","error_message":"Not Found","msg":"Not Found"} 

ExchangeError: okex {"code":404,"data":{},"detailMsg":"","error_code":"404","error_message":"Not Found","msg":"Not Found"}
    at okex.handleErrors (/backend/node_modules/ccxt/js/okex.js:3634:19)
    at/backend/node_modules/ccxt/js/base/Exchange.js:602:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async timeout (/backend/node_modules/ccxt/js/base/functions/time.js:195:24) {
  constructor: [class ExchangeError extends BaseError]
}
```

**Comment by drixie** [comment]
For reference, okex.spotGetAccounts() is working as expected. I am yet to test okex.futuresGetAccounts() and okex.marginGetAccounts(). 

There are a number of other methods in the option section that are not working. I will probably create a separate issue for them

**Comment by ttodua** [comment]
This issue refers to old v3 api, which is no longer existent in ccxt, as we use V5 now. Feel free to open any issue you might come across.
