### ISSUE TITLE
Okex optionPlaceOrder Error 36222 issue

### ISSUE THREAD

**Issue by drixie** [ccxt/ccxt#8463]
No matter what price I put (higher, lower, or equal to the bid price, I keep getting this error message: 

`{"result":"true","error_message":"Order price is breaching highest buy limit","error_code":"36222","client_oid":"tradetactics1","order_id":"-1"}`

**Comment by kroitor** [comment]
@drixie please, follow the guidelines precisely and paste your code, your version numbers, and **your verbose output**: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help otherwise it will be very hard to guess it.

**Comment by drixie** [comment]
Language: Javascript (Node)
Version number: 12.20.1
CCXT lib version number: ccxt@1.41.89
Exchange: Okex
Method being called: okex.optionPlaceOrder()

Code: ```
okex.verbose=true
okex.optionPostOrder({
    "client-oid": "tradetactics1", 
    "instrument_id": "ETH-USD-210226-2120-C", 
    "side": "buy",
    "order_type": "0",
    "price": 53, 
    "size": "1", 
    "match_price": "0"
}).then(result => console.log(result))
.catch(error => console.log(error))```

Response: 
```
 {"client-oid":"tradetactics1","instrument_id":"ETH-USD-210226-2120-C","side":"buy","order_type":"0","price":53,"size":"1","match_price":"0"} 

handleRestResponse:
 okex POST https://www.okex.com/api/option/v3/order 400 Bad Request 
Response:
 {
  'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate',
  'Cf-Cache-Status': 'DYNAMIC',
  'Cf-Ray': '621ce65c5d42f4ae-YVR',
  'Cf-Request-Id': '0845ee4db80000f4aed892a000000001',
  Connection: 'keep-alive',
  'Content-Length': '144',
  'Content-Type': 'application/json',
  Date: 'Mon, 15 Feb 2021 06:16:23 GMT',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Expires: '0',
  Pragma: 'no-cache',
  Server: 'cloudflare',
  'Set-Cookie': '__cfduid=db6f6888a373bd89f242eb7661471751e1613369783; expires=Wed, 17-Mar-21 06:16:23 GMT; path=/; domain=.okex.com; HttpOnly; SameSite=Lax, locale=en_US; Max-Age=604800; Expires=Mon, 22-Feb-2021 06:16:23 GMT; Path=/',
  'X-Brokerid': '0',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'X-Xss-Protection': '1; mode=block'
} 
 {"result":"true","error_message":"Order price is breaching highest buy limit","error_code":"36222","client_oid":"tradetactics1","order_id":"-1"} 

InvalidOrder: okex {"result":"true","error_message":"Order price is breaching highest buy limit","error_code":"36222","client_oid":"tradetactics1","order_id":"-1"}
    at okex.throwExactlyMatchedException (/backend/node_modules/ccxt/js/base/Exchange.js:532:19)
    at okex.handleErrors /backend/node_modules/ccxt/js/okex.js:3631:18)
    at/backend/node_modules/ccxt/js/base/Exchange.js:602:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async timeout (/backend/node_modules/ccxt/js/base/functions/time.js:195:24) {
  constructor: [class InvalidOrder extends ExchangeError]
}
```

**Comment by drixie** [comment]
@kroitor The issue comes from the price I believe. I was submitting the USD (price: 53) based on what I see in the UI, but the API expects the price to be in the base currency (in this case ETH). I did not get the error after converting 53 USD to the ETH equivalent and submitting the order with it
