### ISSUE TITLE
hasFetchOHLCV and hasFetchTickers removed since v1.1

### ISSUE THREAD

**Issue by mmehrle** [ccxt/ccxt#8466]
OS: OS X
CCXT version: 1.41.92
Language: python

I have not touched ccxt for over two years and just upgraded to the latest version. Tried to run a test code that prints the services offered by each exchange. The following calls failed:

 print("offers ticks: {}".format(exchange.hasFetchTickers))
 print("offers OHLCV: {}".format(exchange.hasFetchOHLCV))

Question: What happened to these calls and can that information still be captured? I see that OHLCV data is still supported, so I assume that call has moved to somewhere else.

Question 2: Is there a page that shows all the exchange related queries? I would like to show if live or historical data can be fetched, orders can be placed, data limits, etc. I already have a pertinent script which I have copied below for your convenience/edification ;-)

`import sys
import ccxt

EXCHANGE = 'binance'

def main(argv):
    #print_market_details(argv, show_order_book=False)
    print_market_overview(argv)

def print_market_overview(argv):
    global EXCHANGE
    if (len(argv) > 1):
        EXCHANGE = argv[1:]
    exchange = getattr(ccxt, EXCHANGE)({
        # 'verbose': True,
    })

    print("market id: {}".format(exchange.id))
    markets = exchange.load_markets()
    print("name: {}".format(exchange.id))
    print("countries: {}".format(exchange.countries))
    print("urls: {}".format(exchange.urls))
    print("version: {}".format(exchange.version))
    print("api: {}".format(exchange.api))
    # print("offers ticks: {}".format(exchange.))
    # print("offers OHLCV: {}".format(exchange.hasFetchOHLCV))
    if hasattr(exchange, 'timeframes'):
        print("time frames: {}".format(exchange.timeframes))
    print("timeout: {}".format(exchange.timeout))
    print("rate limit: {}".format(exchange.rateLimit))
    print("verbose: {}".format(exchange.verbose))
    if hasattr(exchange, 'symbols'):
        print("symbols: {}".format(",".join(exchange.symbols)))
    if hasattr(exchange, 'currencies'):
        print("currencies: {}".format(",".join(exchange.currencies)))
    if hasattr(exchange, 'markets_by_id'):
        print("markets by id: {}".format(",".join(exchange.markets_by_id)))
    print("proxy: {}".format(exchange.proxy))
    print("api key: {}".format(exchange.apiKey))
    print("secret: {}".format(exchange.secret))
    print("password: {}".format(exchange.password))
    print("string user id: {}".format(exchange.uid))

def print_market_details(argv, show_order_book=False):
    global EXCHANGE
    if (len(argv) > 1):
        EXCHANGE = argv[1:]
    exchange = getattr(ccxt, EXCHANGE)({
        # 'verbose': True,
    })
    print("MARKETS for {}".format(exchange.id))
    markets = exchange.load_markets()
    for market in markets:
        print ('\nccxt symbol: {}'.format(market))
        print ('{} id: {}'.format(EXCHANGE, exchange.market_id(market)))
        mkts = exchange.markets[market]

        if show_order_book:
            orderbook = exchange.fetch_order_book(exchange.symbols[0])
            bid = orderbook['bids'][0][0] if len(orderbook['bids']) > 0 else None
            ask = orderbook['asks'][0][0] if len(orderbook['asks']) > 0 else None
            spread = (ask - bid) if (bid and ask) else None
            print (exchange.id, 'market price', {'bid': sthrf(bid), 'ask': sthrf(ask), 'spread': sthrf(spread)})

        for meta in mkts:
            if (meta != 'info'):
                print ('  {}'.format(meta))
                details = mkts[meta]
                print('    {}'.format(details))

                # print(exchange.symbols)
                #
                # for currency in exchange.currencies:
                #     print (currency)

# scientific to human readable format
def sthrf(num):
    base, expo = str(num).split('e')
    return '%.*f' % (len(base) - 2 + abs(int(expo)), num)

if __name__ == '__main__':
    sys.exit(main(sys.argv))
`

Thanks in advance.

**Comment by kroitor** [comment]
@mmehrle please, check here: 

- https://github.com/ccxt/ccxt/wiki/Manual#exchange-metadata

Use `exchange.has['fetchOHLCV'] / exchange.has['fetchTickers']`.

Let us know if that does not answer your question.

**Comment by mmehrle** [comment]
Thanks! I added another question in the interim.

**Comment by kroitor** [comment]
@mmehrle 

> Question 2: Is there a page that shows all the exchange related queries? I would like to show if live or historical data can be fetched, orders can be placed, data limits, etc. I already have a pertinent script which I have copied below for your convenience/edification. Unfortunately the formatting is getting screwed up - apologies.

See here:

- https://github.com/ccxt/ccxt/tree/master/examples/js/exchange-capabilities.js

<img width="2766" alt="Screenshot 2021-02-16 at 14 47 16" src="https://user-images.githubusercontent.com/1294454/108058992-e15e6600-7065-11eb-876a-c53e0734b07f.png">

**Comment by mmehrle** [comment]
Awesome! BTW, congrats on the progress. Looks like ccxt has come  LONG way since I dropped the ball two years back (health reasons). Looking forward to working with it moving forward.
