### ISSUE TITLE
Kucoin fetchMyTrades endpoint

### ISSUE THREAD

**Issue by sebnyc** [ccxt/ccxt#8471]
I am pulling deposits, withdrawals and trades from Kucoin.
Kucoin has these strange endpoint duplicates depending if the transactions were before or after 2019-02-18.

With fetchDeposits and fetchWithdrawals methods, CCXT selects the appropriate endpoint depending on $since parameter.
It looks like fetchMyTrades doesn't select the right method when it's called with a $since parameter before 2019-02-18. It is triggering api/v1/fills while it should trigger /api/v1/hist-orders.

- OS: MacOS
- Programming Language version: PHP
- CCXT version: 1.41.96

My code :
```
$since = 946684800000; // Year 2000
$params = array (
    'currentPage' => 1,
    'pageSize' => 500
);

$transactions = $exchange->fetchMyTrades(null, $since, null, $params);
```

Verbose output :
```
Array
(
[0] => Request:
[1] => GET
[2] => https://openapi-v2.kucoin.com/api/v1/fills?startAt=946684800000&currentPage=1&pageSize=500
[3] => Array
(

```

**Comment by kroitor** [comment]
Let us know if this does not help:

- https://github.com/ccxt/ccxt/issues/8457

**Comment by sebnyc** [comment]
@kroitor It looks like it does the trick, thank you so much.
