### ISSUE TITLE
How can I fix it in Bybit? HTTPError: 403 Client Error: Forbidden for url

### ISSUE THREAD

**Issue by sonokino18** [ccxt/ccxt#8473]
- OS: win 10
- Programming Language version: python
- CCXT version: up to date

Hi.
I was running my code without error for a while.
But today I got an error message like

requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.bybit.com/v2/public/time

How can I fix it?

my code is as follows
-----------------------
import ccxt

binance = ccxt.binance()

bybit = ccxt.bybit({
    'enableRateLimit': True,
    'options': {
        'adjustForTimeDifference': True,
    },
    'apiKey': 'my api',
    'secret': 'my secret',
})

markets = bybit.load_markets()

-----------------------------------------------------------
then an error message occurs :

2021-02-17 11:56:16 - Task preparing to start
Feb 17 11:56:59 Traceback (most recent call last):
Feb 17 11:56:59   File "/home/sonokino/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 589, in fetch
Feb 17 11:56:59     response.raise_for_status()
Feb 17 11:56:59   File "/usr/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
Feb 17 11:56:59     raise HTTPError(http_error_msg, response=self)
Feb 17 11:56:59 requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.bybit.com/v2/public/time
Feb 17 11:56:59 
Feb 17 11:56:59 During handling of the above exception, another exception occurred:
Feb 17 11:56:59 
Feb 17 11:56:59 Traceback (most recent call last):
Feb 17 11:56:59   File "/home/sonokino/test2222.py", line 18, in <module>
Feb 17 11:56:59     markets = bybit.load_markets() 
Feb 17 11:56:59   File "/home/sonokino/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1355, in load_markets
Feb 17 11:56:59     markets = self.fetch_markets(params)
Feb 17 11:56:59   File "/home/sonokino/.local/lib/python3.8/site-packages/ccxt/bybit.py", line 349, in fetch_markets
Feb 17 11:56:59     self.load_time_difference()
Feb 17 11:56:59   File "/home/sonokino/.local/lib/python3.8/site-packages/ccxt/bybit.py", line 328, in load_time_difference
Feb 17 11:56:59     serverTime = self.fetch_time(params)
Feb 17 11:56:59   File "/home/sonokino/.local/lib/python3.8/site-packages/ccxt/bybit.py", line 334, in fetch_time
Feb 17 11:56:59     response = self.v2PublicGetTime(params)
Feb 17 11:56:59   File "/home/sonokino/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 466, in inner
Feb 17 11:56:59     return entry(_self, **inner_kwargs)
Feb 17 11:56:59   File "/home/sonokino/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 491, in request
Feb 17 11:56:59     return self.fetch2(path, api, method, params, headers, body)
Feb 17 11:56:59   File "/home/sonokino/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 487, in fetch2
Feb 17 11:56:59     return self.fetch(request['url'], request['method'], request['headers'], request['body'])
Feb 17 11:56:59   File "/home/sonokino/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 606, in fetch
Feb 17 11:56:59     self.handle_http_status_code(http_status_code, http_status_text, url, method, http_response)
Feb 17 11:56:59   File "/home/sonokino/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 637, in handle_http_status_code
Feb 17 11:56:59     raise Exception(' '.join([self.id, method, url, string_code, http_status_text, body]))
Feb 17 11:56:59 ccxt.base.errors.RateLimitExceeded: bybit GET https://api.bybit.com/v2/public/time 403 Forbidden <HTML><HEAD>
Feb 17 11:56:59 <TITLE>Access Denied</TITLE>
Feb 17 11:56:59 </HEAD><BODY>
Feb 17 11:56:59 <H1>Access Denied</H1>
Feb 17 11:56:59  
Feb 17 11:56:59 You don't have permission to access "http&#58;&#47;&#47;api&#46;bybit&#46;com&#47;v2&#47;public&#47;time" on this server.<P>
Feb 17 11:56:59 Reference&#32;&#35;18&#46;fff4317&#46;1613563018&#46;ae3b326

**Comment by kroitor** [comment]
@sonokino18 hi! You are missing the rate limiter: 

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/wiki/Manual#notes-on-rate-limiter

Let us know if that does not answer your question.

**Comment by poloten4uk** [comment]
> @kroitor Does this apply also to this error message i am getting once in a while.. ? `You don't have permission to access api.bybit.com/public/symbols` ? ![image](https://user-images.githubusercontent.com/5032389/167128374-d983a819-15e9-44be-91df-cf3f31eed774.png)

Recieve this error as well, time to time... redeploy helps. not sure what is the issue.

**Comment by ryanreed357** [comment]
Did you get it

**Comment by Rasoooll** [comment]
> > @kroitor Does this apply also to this error message i am getting once in a while.. ? `You don't have permission to access api.bybit.com/public/symbols` ? ![image](https://user-images.githubusercontent.com/5032389/167128374-d983a819-15e9-44be-91df-cf3f31eed774.png)
> 
> Recieve this error as well, time to time... redeploy helps. not sure what is the issue.

I have the same issue , tested with proxy and no luck
is there a way to fix it?
I have my rateLimiter set to true and this error is killing me
please help

**Comment by zigzag-way** [comment]
I have the same... looks like they have changes security policies on the server

**Comment by carlosmiei** [comment]
@zigzag-way What's your ccxt version?

**Comment by Prince-Hamza** [comment]
am facing same issue works fine on localhost but 403 when deployed to heroku

**Comment by roberlin** [comment]
the same from google cloud but not from gitpod dev...

**Comment by inductor69** [comment]
Make sure thay your timestamp is in sync with server time
`server_time - recv_window <= timestamp < server_time + 1000`
