### ISSUE TITLE
ccxt bithumb withdraw tag problem

### ISSUE THREAD

**Issue by kimtaehun1** [ccxt/ccxt#8475]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: window
- Programming Language version: python 3.7
- CCXT version: recent

```
REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS
```

bithumb_ccxt = ccxt.bithumb()
bithumb_ccxt.apiKey = bithumb_apiKey  
bithumb_ccxt.secret =bithumb_secret  
bithumb_ccxt.enableRateLimit = True
bithumb_ccxt.withdraw('EOS', 0.5, address = address['address'] , tag =  address['tag']  )

```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
```
{'info': {'status': '0000'}, 'id': None}

receive message from bithumb -> "The withdrawal was canceled because you did not enter a memo"

I try to send EOS bithumb to binance using ccxt withdraw function but it doesn't work. 

There was no error in the code, but the coin was not sent because the memo was not sent to the Bithumb server.

**Comment by kroitor** [comment]
@kimtaehun1 what is your exact CCXT version number?

```Python
import ccxt
print(ccxt.__version__)
```

**Comment by kimtaehun1** [comment]
> @kimtaehun1 what is your exact CCXT version number?
> 
> ```python
> import ccxt
> print(ccxt.__version__)
> ```
1.41.89
