### ISSUE TITLE
New Exchange: IRONX

### ISSUE THREAD

**Issue by AsadullahSoomro** [ccxt/ccxt#8479]
Hi!
Currently, I am exploring IRONX fx cryptocurrency trading My Questions about IRONX Exchange.. Does the CCXT library support this exchange Either RealNEt or TEstnet..?

Thanks...!

**Comment by diwenshi61** [comment]
Not supported at the moment. See the list of supported exchanges [here](https://github.com/ccxt/ccxt#supported-cryptocurrency-exchange-markets).

**Comment by quangbaotran** [comment]
Thanks
