### ISSUE TITLE
PHP Error - User-Agent header is required.

### ISSUE THREAD

**Issue by TomAshley303** [ccxt/ccxt#848]
OS: Ubuntu 16.04

Expected to print fetched trades. Instead got user-agent error.

Code:

```
require ('../includes/ccxt/ccxt.php');

$gdax = new \ccxt\gdax();

var_dump ($gdax->fetch_trades ('BTC/USD'));
```

Error:

`PHP Fatal error:  Uncaught ccxt\ExchangeError: gdax {"message":"User-Agent header is required."} in /home/user/www/madax/includes/ccxt/php/gdax.php:522
Stack trace:
#0 /home/user/www/madax/includes/ccxt/php/base/Exchange.php(777): ccxt\gdax->handle_errors(400, '', 'https://api.gda...', 'GET', Array, '{"message":"Use...')
#1 /home/user/www/madax/includes/ccxt/php/base/Exchange.php(629): ccxt\Exchange->fetch('https://api.gda...', 'GET', Array, NULL)
#2 /home/user/www/madax/includes/ccxt/php/gdax.php(529): ccxt\Exchange->fetch2('products', 'public', 'GET', Array, NULL, NULL)
#3 [internal function]: ccxt\gdax->request('products', 'public', 'GET', Array)
#4 /home/user/www/madax/includes/ccxt/php/base/Exchange.php(572): call_user_func(Array, 'products', 'public', 'GET', Array)
#5 [internal function]: ccxt\Exchange->ccxt\{closure}()
#6 /home/user/www/madax/includes/ccxt/php/base/Exchange.php(1386): call_user_func_array(Object(Closure), Array)
#7 /home/user/www/madax/includes/ccxt/php/gdax.php(126): ccxt\Exchange- in /home/user/www/madax/includes/ccxt/php/gdax.php on line 522`

**Comment by kroitor** [comment]
This should be fixed in version 1.10.377. Let us know if you still have any difficulty with it. Thx!
