### ISSUE TITLE
Fetch_ohlcv can handle np.int64 for the parameter "since".

### ISSUE THREAD

**Issue by kenfus** [ccxt/ccxt#8483]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows 10 
- Programming Language version: Python 3.8.4
- CCXT version: 1.41.97

```
exchange.fetch_ohlcv(symbol = 'BTC/USDT', timeframe = '1m', since = np.int64(1613682060000), limit = 1)
```

```
ExchangeError: binance {"code":-1023,"msg":"Start time is greater than end time."}
```
Easily fixed by changing the code in the following way:

exchange.fetch_ohlcv(symbol = 'BTC/USDT', timeframe = '1m', since = int(np.int64(1613682060000)), limit = 1)

**Comment by kroitor** [comment]
> Easily fixed by changing the code in the following way:

Yep, that must be handled in the userland as you've pointed, we will not add the support for `np` to the master branch atm.

Let us know if anything.

**Comment by nerddan** [comment]
It would be great if you can do a type check at the beginning of all public APIs.

```python
async def fetch_ohlcv(self, symbol, timeframe='1m', since=None, limit=None, params={}):
    if not isinstance(since, (int, None)):
        raise TypeError
```

**Comment by kroitor** [comment]
@nerddan it's documented throughout the Manual, that `since` can be an integer in milliseconds or None. Not all users would like the extra checks, therefore we think the extra checks should be handled on the user-side.
