### ISSUE TITLE
Fetch balance in USDT for Kraken, Huobi, Binance and Binance future

### ISSUE THREAD

**Issue by Naografix** [ccxt/ccxt#8485]
Hello!

Currently I retrieve all my cryptos on  Kraken, Huobi, Binance and Binance Future and calculate the total in USDT. But just to know: Does CCXT already offer a system allowing it? I haven’t found it.

Thank you

**Comment by kroitor** [comment]
> Does CCXT already offer a system allowing it?

CCXT is a framework which allows you to make such a system. You can fetch the USDT prices for the assets on your balance, then fetch the balance itself and do a basic multiplication. All of this is described in the Manual and in the examples.

Check these issues:

- https://github.com/ccxt/ccxt/issues/1986
- https://github.com/ccxt/ccxt/issues/3149
- https://github.com/ccxt/ccxt/blob/master/examples/js/fetch-all-balances.js
- https://github.com/ccxt/ccxt/wiki/

Let us know if that does not answer your question.

**Comment by Naografix** [comment]
Yup ok, it's already what I did. My initiale question was: "Was ccxt calculating in USDT all my balances itself?"

But thanks!

**Comment by kroitor** [comment]
@Naografix nope, it does not cconvert the balances for you, but it gives you the prices and balances to calculate their values in any currency on your side.
