### ISSUE TITLE
Last update has broken fetch_ohlcv with since parameter on Binance

### ISSUE THREAD

**Issue by Ricardus312** [ccxt/ccxt#8486]
- OS: Windows 10
- Programming Language version: python 3.7
- CCXT version: 1.42.8

After updating ccxt to 1.42.8 from 1.40.88 my code using fetch_ohlcv with the parameter "since" has stopped working and it returns an empty list. If I don't use the since parameter it works.

Downgrading the library back to 1.40.88 has solved the problem

This code works:
```
exchange = getattr(ccxt, 'binance')()
await exchange.fetch_ohlcv('BTC/USDT', '1m')
```
This code doesn't works
```
exchange = getattr(ccxt, 'binance')()
await exchange.fetch_ohlcv('BTC/USDT', '1m', 1613753220000)
```

**Comment by kroitor** [comment]
Please, always paste your VERBOSE output:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```Python
import ccxt
from pprint import pprint
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.binance({
    'enableRateLimit': True,
})
markets = exchange.load_markets()
exchange.verbose = True
response = exchange.fetch_ohlcv('BTC/USDT', '1m', 1613753220000)
pprint(response)
print('Fetched', len(response), 'candles')
```

↑  Paste your entire output here, please.

**Comment by Ricardus312** [comment]
Output: [ ]

**Comment by kroitor** [comment]
@Ricardus312 your output from that snippet can't be just `[]`. It has to print much more lines, including version numbers, request, response, and the resulting array. Can you please follow the guides precisely? Otherwise it might take much more time to help you.

**Comment by Ricardus312** [comment]
Sorry, I thought you wanted the output of my code.

I am not able to reproduce the error with your snippet. The only thing I can tell is that my code stopped working after upgrading the version of ccxt, and it is working again after downgrading.

**Comment by kroitor** [comment]
@Ricardus312 i can't help you without seeing the code, unfortunately. If my snippet works and your code does not – paste your snippet, but please make it as short as mine, or close to that, so that i would not have to invent it or edit it too much, something i could copypaste and run to reproduce your problem – as you understand, without the code we are pretty much guessing.

**Comment by Ricardus312** [comment]
I understand, don't worry, it's just that I don't have the time to look into this on more detail right now. I will keep working with the last version of the library that worked for me and will investigate this later.

Thank's for your help anyway.
