### ISSUE TITLE
KuCoin retreive Locked Up balances in Pool-X

### ISSUE THREAD

**Issue by willwillis** [ccxt/ccxt#8487]
It's not clear to me how to retrieve the balance of "staked" coins that I have under KuCoin's "pool" account type. `fetch_total_balance()` shows what is in the trading account type, and `fetchAccounts()` only shows the balance of the staking rewards I've earned. I'd like to know how to query the API so I can see that I have 25 EOS staked, and I've received 0.03 EOS in rewards. I understand that because I've staked these coins they're basically out of my possession.. I'm hoping there's a way to query just how much I've lent out to the pool programmatically. 

- OS: Manjaro Linux 5.10.15-1-MANJARO
- Programming Language version: Python 3.9
- CCXT version: 1.42.8

```
import os
import sys
import pprint
import ccxt
pp = pprint.PrettyPrinter(indent=4)

kucoin = ccxt.kucoin({
   'apiKey': " ",
   'secret': "  ",
   'verbose': False,  # switch it to False if you don't want the HTTP log
   'password': ' '
})

total_bal = kucoin.fetch_total_balance()
pp.pprint(total_bal)

accounts = kucoin.fetchAccounts();

for holding in accounts:
    symbol = holding['currency']
    available = float(holding['info']['available'])
    balance = float(holding['info']['balance'])
    account_type = holding['type']
    if balance != 0 and available != 0:
        print(f"""KuCoin {account_type} {symbol}: {balance} / {available} """)
        if symbol == 'EOS':
            pp.pprint(holding)
```

```
{   '1INCH': 7.0584,
    'EOS': 1.7656,
    'XRP': 142.48667749}

KuCoin trade EOS: 138.7656 / 138.7656 
{   'currency': 'EOS',
    'id': '6022d352422b69000630b4a4',
    'info': {   'available': '1.7656',   # In Trading Account
                'balance': '1.7656',
                'currency': 'EOS',
                'holds': '0',
                'id': '6022d352422b69000630b4a4',
                'type': 'trade'},
    'type': 'trade'}
KuCoin trade 1INCH: 7.0584 / 77.0584 
KuCoin trade XRP: 142.48667749 / 142.48667749 
KuCoin pool EOS: 0.03082185 / 0.03082185 
{   'currency': 'EOS',
    'id': '601b752d9064a600066e919c',
    'info': {   'available': '0.03082185',
                'balance': '0.03082185',  # Rewards from staking (highlighted in red below)
                'currency': 'EOS',
                'holds': '0',
                'id': '601b752d9064a600066e919c',
                'type': 'pool'},
    'type': 'pool'}

```

I'm able to pull back `Available` balance, I'd like to get back `Locked Up` as well.

![image](https://user-images.githubusercontent.com/46991/108583289-1ab10300-72fe-11eb-90f4-18614921e878.png)

**Comment by ttodua** [comment]
It's a bit old topic, but anyway, you can see that kucoin has [`accountsByType` property](https://github.com/ccxt/ccxt/blob/master/js/kucoin.js#L430) , where you can see available 'account-types' you can query for.
I suggest you try the below one and it might solve your issue:
```
...
kucoin = ccxt.kucoin({
   'apiKey': " ",
   'secret': "  ",
   'password': ' '
})

total_bal = kucoin.fetch_balance( {'defaultType': 'mining'})
print(total_bal)
```
that will show your pool-related balances specifically for kucoin. 
If you will experience any other issue, let us know.
