### ISSUE TITLE
Binance fetchBalance() (and possibly other functions in php lib) not returning correctly after 1.42.4 release 

### ISSUE THREAD

**Issue by rxall** [ccxt/ccxt#8494]
First off - I really appreciate all the work that's gone into this.

- OS: Linux
- Programming Language version: php
- CCXT version: 1.42.4 and later

**Code to reproduce**
```
$exchange = new \ccxt\binance(array(
	'apiKey' => [API_KEY]
	'secret' => [API_SECRET],
));

//$exchange->verbose = True;

print_r($balances = $exchange->fetchBalance());
```

Expected output, balances, actual output none. The exact same sample code works with CCXT releases 1.42.3 and under.

**Comment by frosty00** [comment]
hello @rxall,

we will investigate this right away

**Comment by frosty00** [comment]
@rxall we have found the issue, it is related to the new `fetch_currencies` method added to binance, we will debug and fix this asap!

**Comment by frosty00** [comment]
@rxall I've uploaded a fix, thanks for spotting this bug ;0

**Comment by rxall** [comment]
nice one, thanks
