### ISSUE TITLE
okex websoket  fetch kline ?

### ISSUE THREAD

**Issue by bitProfessor** [ccxt/ccxt#8499]
okex restapi fetch wrong kline data!!!

**Comment by kroitor** [comment]
@bitProfessor please, always paste your version numbers, your code to reproduce the issue and your verbose output: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by kroitor** [comment]
Feel free to reopen it if necessary, or just ask further questions if any.
