### ISSUE TITLE
Binance error: Timestamp for this request was 1000ms ahead of the server's time.

### ISSUE THREAD

**Issue by stonemonk** [ccxt/ccxt#850]
Trying to use Binance, I get this error trying to call `fetch_total_balance` (probably other methods also but I didn't test any others yet):

```
ccxt.base.errors.ExchangeNotAvailable: binance GET https://api.binance.com/api/v3/account?timestamp=1513233650395329&signature=.... 400 {"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}
```

I already double checked that my system is syncing to internet time.  Could it be a timezone handling issue in CCXT?

I found [this thread](https://github.com/sammchardy/python-binance/issues/2) which shows an example using the python-binance library to check the time delay and I don't see an issue with that library which is why I am guessing it could be a timezone issue in CCXT.  When I run:

```
>>> import time
>>> from binance.client import Client
>>> client = Client(api_key, api_secret)
>>> int(time.time() * 1000) - client.get_server_time()['serverTime']
```

I consistently get a result around 260ms.

**Comment by kroitor** [comment]
Hi! This issue was also covered here (also has an alternative solution to the problem) 

https://github.com/ccxt/ccxt/issues/773

```
mbp:python igorkroitor$ python
Python 2.7.13 (default, Jun  5 2017, 10:04:07) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> b = ccxt.binance()
>>> import time
>>> print(b.milliseconds(), b.nonce(), time.time()*1000, time.time()*1000 - b.public_get_time()['serverTime'])
(1513244780698, 1513244780698, 1513244780698.4849, -552.51513671875)
>>> print(b.milliseconds(), b.nonce(), time.time()*1000, time.time()*1000 - b.public_get_time()['serverTime'])
(1513244787223, 1513244787223, 1513244787223.836, -477.1630859375)
>>> print(b.milliseconds(), b.nonce(), time.time()*1000, time.time()*1000 - b.public_get_time()['serverTime'])
(1513244788791, 1513244788791, 1513244788791.9668, -578.031982421875)
>>> print(b.milliseconds(), b.nonce(), time.time()*1000, time.time()*1000 - b.public_get_time()['serverTime'])
(1513244790247, 1513244790247, 1513244790247.578, -492.4208984375)
>>> print(b.milliseconds(), b.nonce(), time.time()*1000, time.time()*1000 - b.public_get_time()['serverTime'])
(1513244791639, 1513244791639, 1513244791639.586, -468.4140625)
>>> print(b.milliseconds(), b.nonce(), time.time()*1000, time.time()*1000 - b.public_get_time()['serverTime'])
(1513244794183, 1513244794183, 1513244794183.464, -502.535888671875)
>>> 
```

> I already double checked that my system is syncing to internet time. 

Well, a difference of 260ms actually tells the opposite, as far as I understand... Or do I miss something? This can also be an issue with the Binance timesync itself.

You can set `.verbose = True` on binance instance, or pass that in constructor:
```Python
binance = ccxt.binance({'verbose': True})
```

This will print out the HTTP body + headers + nonces (timestamps) that get sent to Binance and you
can compare those values to actual local time on your system + against some online time service.

Does this help?

**Comment by stonemonk** [comment]
Okay, I found the problem.  I am initializing with this option:

`'nonce': Exchange.microseconds`

I am doing this because using the default was producing errors for me with Poloniex (I was getting errors with Poloniex in the case that there was a network issue and I retry to request quickly. With the default, the server would give an error that my nonce was the same as last request because it was my re-try was so quick.  But using microseconds fixes it and the 2nd attempt to Poloniex works well).

But for Binance, its means means its sending the microseconds int value which is orders of magnitude different than the real timestamp (locally and on binance server).

While the simple solution is to not include the above for Binance, it starts to get ugly for me if I need to pass certain config options only for certain exchanges.

Rather I would definitely consider this a bug in CCXT.  It should not send a microsecond int nonce as a timestamp to Binance, it should always send a real timestamp.

**Comment by kroitor** [comment]
> Rather I would definitely consider this a bug in CCXT.

I'm not quite getting... you redefine the nonce for microseconds for binance, you don't want to do it any other way, despite that Binance rejects that, and you consider this a bug in ccxt, despite that inside ccxt the default nonce is seconds or milliseconds (not microseconds) for most exchanges?

> It should not send a microsecond int nonce as a timestamp to Binance, it should always send a real timestamp.

It sends whatever is returned from nonce(). If it is a seconds-timestamp, it will send seconds. If it is a milliseconds-timestamp (Binance does not accept anything else except milliseconds), it will send those. If you set it to microseconds, it will send microseconds and Binance will not like it. This is not a bug, obviously.

**Comment by stonemonk** [comment]
I mean that a nonce is not the same thing as a timestamp.  A nonce may be derived from or include a timestamp of course, but its not the same.

Some exchanges want a nonce and CCXT should use whatever is specified in the config (`'nonce': Exchange.microseconds`).

But Binance wants a real timestamp and it is used for different purposes than a nonce.  Yes it also acts in effect like a nonce to prevent replay attacks, but its *also* used to ensure transaction timing.  As such, it **never** makes sense to send anything but a real **UTC epoch milliseconds timestamp**.   Trying to send a nonce code in place of such a timestamp is invalid and would never be accepted by Binance.

So I am just saying that CCXT should ignore the nonce config for Binance because Binance never asks for a nonce, it asks for a timestamp.

**Comment by stonemonk** [comment]
But its okay, I can just work around it on my side also..

**Comment by kroitor** [comment]
> But its okay, I can just work around it on my side also..

No, I think you're right, I've changed that from `nonce = this.nonce()` to `nonce = this.milliseconds()` in the implementation of Binance. Should be available in 5 minutes in the next version.

**Comment by stonemonk** [comment]
Cheers, and thanks for your hard work on this project, its really awesome!  It has saved me lots of time. 

If my projects every become profitable, I will send you some coin. :)

**Comment by shprink** [comment]
Running 1.10.445 and still have this issue

**Comment by kroitor** [comment]
@shprink are you sure you have exactly the same issue? (the "1000ms ahead" one). Do you have time synch enabled on your system?

**Comment by awhitehouse104** [comment]
Same "1000ms ahead" for me today on 1.10.459

**Comment by kroitor** [comment]
From Binance:

```
Igor Kroitor, [23.12.17 21:24]
Hi, again! We're receiving reports of multiple timestamp-related errors from users who have time synch enabled, and who didn't have this problem with the same code previously. Most of the time "timestamp more than 1000ms ahead of server time" and "timestamp outside of recvWindow"... the 2nd one can probably be tackled by choosing a greater recvWindow, however, the first one is making us subtract a thousand from an otherwise-synchronized time... Is there a better way to solve these issues?

Ninj0r, [24.12.17 11:59]
Timestamp related issues on are on the users end. Synch your clocks (and keep them in sync) and you'll not have issues. Synching your clock is not a one time thing; clocks drift for a host of reasons and need to be repeatedly synced. This is why the default on ntpd is to sync clocks at least every 1024 s (17mins 4 seconds). If the user can't prove they synced their clock within that timeframe, I'm not going to investigate it.

Ninj0r, [24.12.17 12:01]
I'll look into this.

Igor Kroitor, [24.12.17 12:07]
they mostly set default time synch in windows 10

Igor Kroitor, [24.12.17 12:08]
(always on)

Ninj0r, [24.12.17 12:08]
Yeah, which typically does something like a time synch once a day if even that.
```

- http://www.thewindowsclub.com/change-internet-time-update-interval-windows
- https://technet.microsoft.com/en-us/library/cc773263(WS.10).aspx
- https://www.opentechguides.com/how-to/article/windows-10/121/windows-10-internet-time.html

Guys, from the above, I guess, it follows, that you need to change the frequency of your time synch updates (set smaller intervals for time polling). You can either do this by googling for it or with 3rd party software. Mac users can change their ntpd settings to alter the time synch params. Hope it helps.

**Comment by awhitehouse104** [comment]
Thanks, using `ntp` on ubuntu worked for me.

https://www.digitalocean.com/community/tutorials/how-to-set-up-time-synchronization-on-ubuntu-16-04

**Comment by dpacmittal** [comment]
How do make sure time is synced on an android device? I'm using this library in an android app which I'm distributing and the users are getting time sync errors. I'm using react native and JS version of the library.

**Comment by jasonmellone** [comment]
@kroitor I just synched my clock but still getting the isse:
`binance.exceptions.BinanceAPIException: APIError(code=-1021): Timestamp for this request was 1000ms ahead of the server's time.`

I have:
`get_account(recvWindow=6000000)`

The odd thing is that this works intermittently.

I also deleted and recreated my api key already.

**Comment by kroitor** [comment]
@jasonmellone 

> I just synched my clock

Unfortunately, just synching the clock does not work. You have to set up frequent time synchronization with your system (each 10 minutes). Make sure your timezone is not DST. Unfortunately, without seeing your code and without having the knowing about your system it's hard to tell anything exactly. I mean these details: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

If that does not help, you can try solutions from this issue: https://github.com/ccxt/ccxt/pull/1477

Namely, for Binance, you can update to most recent version and do this upon instantiation:

```Python
import ccxt
b = ccxt.binance({ 'options': { 'adjustForTimeDifference': True }})
```

It will adjust for the clock unsynchronization itself, but this is less secure.

**Comment by jasonmellone** [comment]
@kroitor Sorry, I realized I needed to update my library. After updating I am now getting [this error](https://github.com/sammchardy/python-binance/issues/151)

**Comment by kroitor** [comment]
@jasonmellone Sorry, but that isn't a ccxt error at all anymore. It's the error with some different python package of yours (maybe binance-client or dateparser). Not something we can help you with. Just uninstall the unnecessary packages, if you don't use them and they break your setup.

**Comment by jdimstrnate** [comment]
So I tried multiple approaches.    For my case what worked was a reboot. lol

**Comment by kroitor** [comment]
@jdimstrnate thanks for reporting and for a helpful hint!

**Comment by sheunaluko** [comment]
For those on ubuntu thanks to awhitehouse104

His post also worked for me.. follow the link and install the ntp package as it says! 
heres his message 
- --- - - 

Thanks, using ntp on ubuntu worked for me.https://www.digitalocean.com/community/tutorials/how-to-set-up-time-synchronization-on-ubuntu-16-04

**Comment by mgavaudan** [comment]
Rebooting also worked for me. I use a Mac OS.

**Comment by ShervinDD** [comment]
In Windows synchronising it manually fixed it for me. Go to date and time settings, Internet Time tab > Change settings > update now. The requests to Binance should work and no longer throw the 1021 error.

Windows 7 defaults to synchronising with internet time every week. You can manually change the sync time to daily by editing the registry. Instructions can be found here: https://superuser.com/questions/529367/automatically-sync-windows-time-more-often-than-default?#comment1385466_821537

**Comment by jeffryhartanto** [comment]
I got this problem just now, I had reboot and sync my time but the problem persist. Also, I don't want to go with insecure solution.. Any idea how to solve this issue securely?

**Comment by kroitor** [comment]
@jeffryhartanto 

> and synced my time

[Unfortunately, just synching the clock does not work. ↑](https://github.com/ccxt/ccxt/issues/850#issuecomment-361112005)

**Comment by jeffryhartanto** [comment]
It works by adding `'options': { 'adjustForTimeDifference': true }`, but you said that it's less secure.. Can you elaborate more on why it's so? Thanks in advance.

**Comment by kroitor** [comment]
@jeffryhartanto 

> It works by adding 'options': { 'adjustForTimeDifference': true }, but you said that it's less secure..
> Can you elaborate more on why it's so?

It is so formally or theoretically, but, most likely, for you it practically means little or it is of very little significance for common user applications.

Basically, the exchange requires the timestamps of your requests to be synced with their clock. This is a security requirement, because the synced timestamp is used during authentication. If the timestamp of a request is out of order or is too late, then the exchange can drop it as *"malicious"*. It is an additional layer of protection, or, in other words, a layer of security. If you enable adjustment for time difference between you and their server then some late packets may be accepted by the exchange. Thus, by enabling the adjustment you violate that exchange's security requirement. And, in general, when you violate any security requirement – this is less secure. That's theory. 

However, in practice, this mostly means nothing to you, as nobody will really be able to steal your money, gain access over your account, private data, do damage or anything. What it really means is that if a hacker had enough energy he would crack your account password a little faster with `adjustForTimeDifference`. But because nobody is even close to having that much energy on Earth and nobody has the technology to overcome those limitations yet, your security is ok, and it's practically safe to enable the time adjustment.

One side-effect of using adjustForTimeDifference instead of setting up a proper regular/frequent timesync is that working with the same API key from different unsynched computers may throw nonce exceptions from time to time. Apart from that, the level of security mostly remains the same.

**Comment by jeffryhartanto** [comment]
Oh, understood.. Thanks a lot for the explanation..

**Comment by miracle2k** [comment]
Just to clarify for any reader of this, the original change from Dec 2017, which changed the behaviour of binance to not use the nonce, but to always use the milliseconds, was effectively reverted in `https://github.com/ccxt/ccxt/commit/36105a438375d599d52f2e057d0484b1ff223a4f` - so setting `{nonce: somethingCustom}` on a binance instance will cause this error.

**Comment by deangelo200** [comment]
im getting {'msg': '{"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server\'s time."}', 'success': False}
how can i fix it im using python-binance #noobprogramer

**Comment by kroitor** [comment]
@deangelo200 with `ccxt` this can be easily done as described above + in the linked issues, as for `python-binance`, I guess, you should ask here https://github.com/sammchardy/python-binance/issues instead.

**Comment by MrRobotXX** [comment]
from control panel > date and time > internet time
change the server to >>>> time.nist.gov

**Comment by hivemall** [comment]
on debian do: `sudo apt install ntp` should fix it right away

**Comment by jorisw** [comment]
Wouldn't `adjustForTimeDifference` possible put trades in the wrong candles?

**Comment by kroitor** [comment]
@jorisw nope, since each trade is timestamped.

**Comment by normanlmfung** [comment]
For Windows, try this: https://steemit.com/crypto/@biyi/how-to-resolve-binance-s-timestamp-ahead-of-server-s-time-challenge
net stop w32time
w32tm /unregister
w32tm /register
net start w32time
w32tm /resync

**Comment by gui-gng** [comment]
@normanlmfung  This worked for me, thanks!

**Comment by Joonel** [comment]
"Sync now" button in the Settings fixed the issue.

**Comment by amarjit-singh** [comment]
> "Sync now" button in the Settings fixed the issue. (Windows 11)

The sync now button in win 11 fixed the issue but after syncing the system time didn't change.

**Comment by umitki** [comment]
I will tell what i did. For windows, i opened the time and click de sync the clock with windows server. When i did it, it worked! Before you do anything, try this.

**Comment by Lucas-BLP** [comment]
On windows:

Worked once but still get the errors sometimes:
> @jasonmellone
> ```python
> import ccxt
> b = ccxt.binance({ 'options': { 'adjustForTimeDifference': True }})
> ```
> It will adjust for the clock unsynchronization itself, but this is less secure.

To fix it, run synchronization
> from control panel > date and time > internet time >>>> Synchronize

**Comment by greglopes123** [comment]
hey guys, i had this time problem on windows 10, i just went to control panel, date and hour, internet hour and refresh it. worked just like that

**Comment by kroitor** [comment]
> hey guys, i had this time problem on windows 10, i just went to control panel, date and hour, internet hour and refresh it. worked just like that

Yes, the problem is that in some cases it doesn't work and it requires some editing of your registry.

**Comment by deepak0418** [comment]
I just tried below and start working fine for me in windows 10 with Python 3.9

binance.nonce = lambda: binance.fetch_time() 
data = binance.fetch_tickers(market_symbols)

**Comment by ulrickpsp** [comment]
In my case in Windows10, hitting sync time button under date/time preferences solved the issue.

**Comment by normanlmfung** [comment]
yes, i discovered that. Not sure since when Unclesoft added that button. We didnt have that button in the olden days.

**Comment by flpmatt** [comment]
This worked like a charm!

**Comment by Naoufal-Charafat** [comment]
En mi caso en Windows10, presionar el botón de sincronización de hora en las preferencias de fecha / hora resolvió el problema.

**Comment by ghotiv** [comment]
> I just tried below and start working fine for me in windows 10 with Python 3.9
> 
> binance.nonce = lambda: binance.fetch_time() data = binance.fetch_tickers(symbols)

this wored for me

**Comment by charlesdarkwind** [comment]
Not using ccxt but on ubuntu and nothing works, even having ntp installed for time synch.

**Comment by mercyplaisir** [comment]
hello @kroitor using binance for the timestamp issue.

i have found out for me the way it works is i have two function for timestamp and for different use.

def now_timestamp():
""" from my computer"""
    return int(round(time.time() * 1000))

def binance_timestamp():  
"""from binance"""
    rs = requests.get("https://fapi.binance.com/fapi/v1/time")
    return rs.json()['serverTime']


for things i retreive from the exchange i use my computer timestamp else doesnt work.
and for things i post on exhange(buy,sell) i use their timestamp else doesnt work.

what your pov on that?

**Comment by TnzGit** [comment]
> I just tried below and start working fine for me in windows 10 with Python 3.9
> 
> binance.nonce = lambda: binance.fetch_time() data = binance.fetch_tickers(symbols)

this worked great! My time's synced but somehow I still get noticable time difference between local and binance server. This saved my day
