### ISSUE TITLE
Could you please list the Crypto.com exchange?

### ISSUE THREAD

**Issue by whiteneilys** [ccxt/ccxt#8506]
I want to manage everything related to cryptocurrency trading in CCXT. 
The exchange information is as follows.

URL - https://crypto.com/exchange/

API - https://exchange-docs.crypto.com/

CoinmarketCap Exchange Ranking : 23
  https://coinmarketcap.com/rankings/exchanges/

**Comment by kroitor** [comment]
Duplicate: 

- https://github.com/ccxt/ccxt/issues/6817

We will add it asap: 

- https://github.com/ccxt/ccxt/wiki/FAQ
