### ISSUE TITLE
Binance showing canceled orders / fetchOrder lagging

### ISSUE THREAD

**Issue by poiseis** [ccxt/ccxt#8507]
- OS: Windows 10 
- Programming Language version: Python 3,5
- CCXT version: ccxt-1.42.20

► After canceling the order, binance occasionaly shows the order anyway in e.sapi_get_margin_openorders() , mean while the asset is kept as used, so it's more than a ghost feedbeck. 
► Ghost cancelled orders also shown in binance website (Orders>Margin Orders), but not on the trading page.
► A ghost cancelled order can be an old order, so it's not the last order always
► Ghost order migth show up later, so after is cleared, a minute later it starts ghosting.
► When i try to canlcel  a ghost order, it returns {"code":-2011,"msg":"Unknown order sent."}
► My code was okey 2 days ago, it started to happen, than i coded most of the part again.

-A one explanation might be i pulled so many request, than binance put me in a low prior server, executes the cancellation but not updating the screen.
-Another theory is binance is having trouble due to the extreme market demand.
-A conspiracy, binance is occasionaly slowing down the algo trades to make money. But,  not sure about that.  :F
 -May be a temprory server eror, and i should just have to wait?

```python
from time import sleep
import ccxt
e= ccxt.binance({"apiKey":YOUR_API,
                 "secret":YOUR_SECRET,
                 "enableRateLimit" : True,
                 'options': {'defaultType':'margin'},
                 "verbose" : True })

price = 40001 #TYPE a non realistic value!!! Like $40000 when price is $52000

while True:
    OpenOrders = e.sapi_get_margin_openorders()
    while len(OpenOrders) >0:
        _CancelReport = e.sapiDeleteMarginOrder({"symbol": OpenOrders[0]["symbol"], "orderId": OpenOrders[0]["orderId"]})
        print("PROOF OF CANCELLED ORDER: \norderId:{}, status:{}\n\n".format(_CancelReport["orderId"], _CancelReport["status"]))
        OpenOrders = e.sapi_get_margin_openorders() #refreshing

        if len(OpenOrders) != 0:
            print("remaining orders count : ", len(OpenOrders) ) #this should be 0 now
            print("remaining order id: ", OpenOrders[0]["orderId"])
            print("cancelled order id: ",_CancelReport["orderId"])
            input("This is the problem")

    #we create a new  order>
    e.createLimitBuyOrder("BTC/USDT", 0.00035, price) #minimum amount typed
    print("sleeping 5 sec")
    sleep(5)
```
```
PROOF OF CANCELLED ORDER: 
orderId:4947769488, status:CANCELED
remaining orders count :  1
remaining order id:  4947769488
cancelled order id:  4947769488
This is the problem
```
```
Request: GET https://api.binance.com/sapi/v1/margin/openOrders?recvWindow=5000&timestamp=1614091979861&signature=01a677b7cd04ceeae531384df70c61ade63f0112b138053a9d3a911fcae2598f {'Accept-Encoding': 'gzip, deflate', 'X-MBX-APIKEY': '***', 'User-Agent': 'python-requests/2.22.0'} None
Response: GET https://api.binance.com/sapi/v1/margin/openOrders?recvWindow=5000&timestamp=1614091979861&signature=01a677b7cd04ceeae531384df70c61ade63f0112b138053a9d3a911fcae2598f 200 {'X-SAPI-USED-IP-WEIGHT-1M': '10', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, HEAD, OPTIONS', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Content-Security-Policy': "default-src 'self'", 'Content-Type': 'application/json;charset=UTF-8', 'Expires': '0', 'X-Cache': 'Miss from cloudfront', 'X-Content-Security-Policy': "default-src 'self'", 'Connection': 'keep-alive', 'Date': 'Tue, 23 Feb 2021 14:53:00 GMT', 'X-WebKit-CSP': "default-src 'self'", 'X-Amz-Cf-Pop': 'CDG3-C1', 'Via': '1.1 0138d08818c0b73b51c0b0e96c9c49f2.cloudfront.net (CloudFront)', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Xss-Protection': '1; mode=block', 'X-Amz-Cf-Id': '9bQkztMan7FQ1_6VJ0zWycg5YOcj3sLjr7X6FjYNykBgu_BOLEbBpg==', 'Server': 'nginx', 'Transfer-Encoding': 'chunked', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding'} [{"symbol":"BTCUSDT","orderId":4947747384,"clientOrderId":"x-R4BD3S82b54add60e8bda812c7c91","price":"40001","origQty":"0.00035","executedQty":"0","cummulativeQuoteQty":"0","status":"NEW","timeInForce":"GTC","type":"LIMIT","side":"BUY","stopPrice":"0","icebergQty":"0","time":1614091894927,"updateTime":1614091894927,"isWorking":true,"isIsolated":false}]
Request: DELETE https://api.binance.com/sapi/v1/margin/order?orderId=4947747384&symbol=BTCUSDT&recvWindow=5000&timestamp=1614091980361&signature=59a00d579eba8327b549d61329dd225aa8509bcae3ae5923bb1b6886bf156048 {'Accept-Encoding': 'gzip, deflate', 'X-MBX-APIKEY': '**', 'User-Agent': 'python-requests/2.22.0'} None
Response: DELETE https://api.binance.com/sapi/v1/margin/order?orderId=4947747384&symbol=BTCUSDT&recvWindow=5000&timestamp=1614091980361&signature=59a00d579eba8327b549d61329dd225aa8509bcae3ae5923bb1b6886bf156048 400 {'Via': '1.1 0138d08818c0b73b51c0b0e96c9c49f2.cloudfront.net (CloudFront)', 'Cache-Control': 'no-cache, no-store, must-revalidate', 'X-SAPI-USED-IP-WEIGHT-1M': '10', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'SAMEORIGIN', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Xss-Protection': '1; mode=block', 'X-Amz-Cf-Id': 'A25wpQawUFU1uzqJRbhT1dzF2OzVrj56Hq0TFh9zUNUBg1czvow2oA==', 'Server': 'nginx', 'Content-Security-Policy': "default-src 'self'", 'Content-Type': 'application/json;charset=UTF-8', 'Expires': '0', 'Content-Length': '42', 'X-Cache': 'Error from cloudfront', 'Pragma': 'no-cache', 'X-Content-Security-Policy': "default-src 'self'", 'Connection': 'keep-alive', 'Date': 'Tue, 23 Feb 2021 14:53:00 GMT', 'X-WebKit-CSP': "default-src 'self'", 'X-Amz-Cf-Pop': 'CDG3-C1'} {"code":-2011,"msg":"Unknown order sent."}
```

**Comment by AlonOhayon** [comment]
also the having same issue last couple of hours

**Comment by kroitor** [comment]
Obviously, this is not something we control in CCXT, so it will depend on the exchange. Especially at times of high volatility like we saw this month. Price swings amounting to 20% never helped improve latencies, the exchange is overwhelmed and even had a few outages recently, reported on Binance groups.

**Comment by poiseis** [comment]
thank you very much for the fast reply, Thank you kroitor, we love you!

 I knew what is happening but I wanted to make my problem public so others don't bother with it, Binance has many server nodes to handle all requests, so they handle the critical part first, but screening servers awaits some minutes to respond to people. 

So I have suppressed all errors, and keep working the cancellation loop until it disappears, 

To extract a benefit from this problem; if we land a server in China would we get the same problem? What is the best way to put us on a server for binance?  :)

By the way, I'm having also trouble while fetching OHLCV data, I saw some error codes which I have never seen in 3 years...

**Comment by kroitor** [comment]
> To extract a benefit from this problem; if we land a server in China would we get the same problem? What is the best way to put us on a server for binance? :)

You might want to reach out to the exchange to see if they offer colocation, however, when their system is down or lagging globally for everyone, i don't think that proximity to their datacenter will make any difference. It's not a matter of overloaded links between you and binance, it's more like a matter of overloaded binance.

> By the way, I'm having also trouble while fetching OHLCV data, I saw some error codes which I have never seen in 3 years...

Yeah, many people have reported problems with the exchanges (binance is not the only one affected). I can understand your frustration, we hope that they will get over it soon, just as they did before.
