### ISSUE TITLE
Kucoin cancel all orders endpoint

### ISSUE THREAD

**Issue by Kalindro** [ccxt/ccxt#8508]
- OS: Win 10 Pro
- Programming Language version: Python 3.7.9
- CCXT version: 1.42.22

Hi,

I've seen the request about new Kucoin endpoints (https://github.com/ccxt/ccxt/pull/6767). I'm not github pro but seems like they changes are commited? But for Python I can't see the new endpoints like cancell_all_orders that would change my life (https://docs.kucoin.com/#cancel-single-order-by-clientoid). Can we get the function?

**Comment by Kalindro** [comment]
Thanks for the update. Can you remove `id` argument from `async def cancel_all_orders(self, id, symbol=None, params={})`? This endpoint doesn't require order ID as it's cancell all. I workaround by just declaring `id = None` but yeah, for consistency with rest of the exchanges functions.

**Comment by kroitor** [comment]
@Kalindro thanks for pointing it out, removed the `id` argument, should be all good in 1.42.28+. I've also added the support for canceling a single order by clientOrderId.
