### ISSUE TITLE
(BInance) How can i transfer balance from future to spot

### ISSUE THREAD

**Issue by optimize0107** [ccxt/ccxt#8511]
- OS: Ubuntu 18
- Programming Language version: python
- CCXT version: 1.41.96

Is there any method for transfer USDT balance from future to spot in binance?

And spot to future balance too.

**Comment by diwenshi61** [comment]
Here is the relevant info in Binance API docs:
[For universal transfer in the same account](https://binance-docs.github.io/apidocs/spot/en/#user-universal-transfer)
[For universal transfer between subaccounts](https://binance-docs.github.io/apidocs/spot/en/#universal-transfer-for-master-account)
In your code, to access these endpoints, follow the [implicit methods section of the documentation](https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods).
If you have additional questions please ask.
Cheers!
