### ISSUE TITLE
Currencies precision returning None [Binance, BitMEX]

### ISSUE THREAD

**Issue by cjdsellers** [ccxt/ccxt#8515]
- OS: Linux Ubuntu 18.04 LTS
- Programming Language version: Python 3.9.1
- CCXT version: 1.42.29

When calling for the loaded currencies, the precision is returning None;
```
self._client.currencies.items()
```

```
{'id': 'AAVE', 'numericId': None, 'code': 'AAVE', 'precision': None}
```

I think this started from around  1.42.18
Tested on Binance spot and BitMEX

**Comment by cjdsellers** [comment]
When running 1.42.18

```
{'id': 'AAVE', 'numericId': None, 'code': 'AAVE', 'precision': 8}
```

**Comment by kroitor** [comment]
@cjdsellers please, check with the most recent version:

```shell
~/ccxt $ python3 examples/py/cli.py binance currency AAVE
Python v3.8.2
CCXT v1.42.29
{'code': 'AAVE', 'id': 'AAVE', 'numericId': None, 'precision': 8}
```

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.binance({'enableRateLimit': True})
markets = exchange.load_markets()
currency = exchange.currency('AAVE')
print(currency)
```

**Comment by cjdsellers** [comment]
Could be something in my code because I have a similar script to the above and thats working.

Should a precision ever return None though? Below is latest for BitMEX

```
    "TRX": {
        "code": "TRX",
        "id": "TRX",
        "numericId": null,
        "precision": 1.0
    },
    "UNI": {
        "code": "UNI",
        "id": "UNI",
        "numericId": null,
        "precision": null
    },
    "USD": {
        "code": "USD",
        "id": "USD",
        "numericId": null,
        "precision": 0.01
    },
```

**Comment by kroitor** [comment]
@cjdsellers that is possible, if there's no active market with the AAVE currency to determine precision from there.

**Comment by cjdsellers** [comment]
I mean for `UNI` as above

**Comment by kroitor** [comment]
@cjdsellers it's the same for UNI.

**Comment by cjdsellers** [comment]
Ok thanks for your help. I'll make some changes to handled these cases.

Cheers for the immediate support!
