### ISSUE TITLE
ccxt wavesexchange fetchBalance() not working

### ISSUE THREAD

**Issue by AsadullahSoomro** [ccxt/ccxt#8522]
Hi,
Currently, I have tried to check wallet balance and to get market data throughout both ccxt and client library functions that are the client.fetch balance(params={"currency": "BTC"}) and balances = waves_exchange.fetch_free_balance()

I have also updated the pip version 

**But** again and again, I am getting this exception of please help me...
Thanks in advance!

OS: Windows 10 Pro
Programming Language version: python 3.8.5
CCXT version: 1.37.70
pip v== 21.0.1

Code:

`import ccxt
#print(dir(ccxt.wavesexchange))
#print(ccxt.exchanges)
waves_exchange = ccxt.wavesexchange({
    'apiKey': 'Public_key',
    'secret': 'Private_key',
    'enableRateLimit': True,
})
waves_exchange.load_markets()
waves_exchange.verbose = True
balances = waves_exchange.fetch_free_balance(params={"currency": "BTC"})
print(balances)
`
Output:
ccxt.base.errors.Authentication Error: Waves-exchange API-key must be a base58 encoded public key.

**Comment by frosty00** [comment]
make sure you are using a waves account with a seed 

![Screenshot 2021-02-26 at 10 58 34](https://user-images.githubusercontent.com/14319357/109292113-c936d580-7821-11eb-9bb5-1187cfd817ff.png)

you can find the private key and public key in the settings

![Screenshot 2021-02-26 at 10 57 35](https://user-images.githubusercontent.com/14319357/109291930-883ec100-7821-11eb-8f1a-14befd3e3b12.png)

**Comment by AsadullahSoomro** [comment]
Alright, I am checking it.   
Thank you for your assist.

**Comment by AsadullahSoomro** [comment]
I have checked But again the same exception of 

`import ccxt
# print(dir(ccxt.wavesexchange))
#print(ccxt.exchanges)
waves_exchange = ccxt.wavesexchange({
    'apiKey': ' ',
    'secret': ' ',
    'enableRateLimit': True,
})
waves_exchange.load_markets()
balances = waves_exchange.fetch_free_balance(params={"currency": "BTC"})
print(balances)`
> raise AuthenticationError(self.id + ' apiKey must be a base58 encoded public key')
ccxt.base.errors.AuthenticationError: wavesexchange apiKey must be a base58 encoded public key

**Comment by frosty00** [comment]
The apiKey should be the public key from the settings page:

It should look like this

```
import ccxt

waves = ccxt.wavesexchange({
    "apiKey": "AXXn8nBX4XfLQF7hLqiSm12kxvehjizBXW1TanxSZ1gF",
    "secret": "21Q9Uxmq1mrrzY6bxmGfXbx9h35JxBv91xd5axhWksxP"
})

print(waves.fetch_balance())
```

![Screenshot 2021-02-26 at 13 43 01](https://user-images.githubusercontent.com/14319357/109307498-a6fc8200-7838-11eb-8024-fdf6e3d0793e.png)

**Comment by frosty00** [comment]
should be fixed in the current version of ccxt
