### ISSUE TITLE
Okex Perpetual - Change leverage

### ISSUE THREAD

**Issue by JanssensKobe** [ccxt/ccxt#8525]
I'm trying to change the leverage for Okex Perpetual markets. I was trying to use this endpoint https://www.okex.com/docs/en/#swap-swap---leverage, is this the futures_post_accounts_underlying_leverage endpoint on ccxt? If so, how do I use it when I try this I get a NameError.

- OS: Windows 10
- Programming Language version: Python 3.9
- CCXT version: 1.42.32

```python
import ccxt

connection = ccxt.okex({'apiKey': 'xxx', 'secretKey': 'xxx', 'enableRateLimit': True, 'options' : {'defaultType': 'future'}})

connection.load_markets()

exchangeSpecificMarket = connection.markets['AAVE/USDT']

connection.futures_post_accounts_underlying_leverage({'instrument_id': exchangeSpecificMarket['id'], 'leverage': leverage, 'side': 3})
```

```
Traceback (most recent call last):
  File "D:\trabro2\test\testSetLeverageOkex.py", line 9, in <module>
    connection.futures_post_accounts_underlying_leverage({'instrument_id': exchangeSpecificMarket['id'], 'leverage': leverage, 'side': 3})
NameError: name 'leverage' is not defined
```

**Comment by kroitor** [comment]
@JanssensKobe this line:

```
NameError: name 'leverage' is not defined
```

says _"in your code you have not defined the value for the variable called leverage that you use"_.

**Comment by JanssensKobe** [comment]
Yeah, that is the problem. I want to change the leverage and the input parameters according to Okex api docu are 'instrument_id', 'leverage' and 'side' (https://www.okex.com/docs/en/#swap-swap---leverage). So am I using the wrong function to set the leverage? When I print the functions of okex 'futures_post_accounts_underlying_leverage' is the only function that relates to this I think?
