### ISSUE TITLE
Change in Okex Testnet/Sandbox

### ISSUE THREAD

**Issue by drixie** [ccxt/ccxt#8532]
Language: Javascript (Node)
Version number: 12.20.1
CCXT lib version number: ccxt@1.42.45
Exchange: Okex

When you do okex.setSandboxMode(true), an error message comes up indicating the library is trying to connect to https://testnet.okex.com/api...

That URL however is not available any longer. Okex has a different system for setting up a sandbox account now (which they are calling "Demo Trading"). The API for Demo trading is v5 and can be found here - https://www.okex.com/docs-v5/en/#rest-api-account-set-position-mode (shared with me by their customer support) 

For reference, the live API is v3

**Comment by kroitor** [comment]
This issue is fixed in CCXT 1.68+
