### ISSUE TITLE
Error Authenticating Kucoin Sandbox 

### ISSUE THREAD

**Issue by drixie** [ccxt/ccxt#8533]
Language: Javascript (Node)
Version number: 12.20.1
CCXT lib version number: ccxt@1.42.45
Exchange: Kucoin

```
kucoin = ccxt.kucoin({
apiKey: "",
secret: "",
password: ""
})
kucoin.setSandboxMode(true)
const fetchedPositions = await kucoin.fetchBalance()
console.log(fetchedPositions)
```

```
UnhandledPromiseRejectionWarning: AuthenticationError: Invalid KC-API-PASSPHRASE
```

I have checked multiple times, and I am sure I am using the correct apiKey, secret, and password. The live version authenticates fine

**Comment by kroitor** [comment]
@drixie exchanges usually have standalone sandbox keypairs for the testnet, you have to go to the testnet website and sign up there: https://sandbox.kucoin.com/

Live keys are not always interchangeable with sandbox keys. Do not use your live keys with the testnet.

Let us know if that does not answer your question.

**Comment by drixie** [comment]
@kroitor Thanks for the response. No, it does not answer my question. Before reporting the issue, I created a separate keypair at the sandbox link you shared, and it is giving me the error I shared above. I did not use live keys with the testnet. I used sandbox keys with the testnet and tried it two times with two separate accounts just to be sure. 

Can you confirm this on your end and let me know if the Kucoin sandbox works for you with a testnet keypair?

**Comment by kroitor** [comment]
@drixie got it, I will check on my side and will get back to you.

**Comment by kroitor** [comment]
I've done some tests, and weirdly enough, KuCoin sandbox does not work for me with a new keypair+password either. Apparently it does not support v2 authentication... We will have to reach out to KuCoin to get this resolved.

**Comment by drixie** [comment]
@kroitor Thanks for testing it out. Let me know if KuCoin responds to you

**Comment by eightbit** [comment]
+1 to join this thread. KuCoin sandbox produces this error: 
```
403
{'code': '400006', 'msg': 'Invalid request ip'}
```
I know the params are correct and my ip is whitelisted in sandbox account.

**Comment by kroitor** [comment]
@eightbit if you see `Invalid Request IP`, then make sure that your source IP is in your whitelist for the API key in question.

**Comment by eightbit** [comment]
> @eightbit if you see `Invalid Request IP`, then make sure that your source IP is in your whitelist for the API key in question.

Yes, I have done that from the beginning. Also verified that my IP has not changed.

**Comment by JonPHenry** [comment]
I can confirm the following works for me in sandbox mode...

`let kucoin = new ccxt.kucoin({

        //apiKey: 'my key',
        //secret: 'my secret',

        // Sandbox Info
        apiKey: 'my sandbox key',
        secret: 'my sandbox  secret',

        password: 'D9LhzRMpd8QX',
    })
    kucoin.setSandboxMode(true)`

**Comment by JonPHenry** [comment]
I can confirm the following works in sandbox mode...

    let kucoin = new ccxt.kucoin({
        apiKey: 'my sandbox key',
        secret: 'my sandbox  secret',     
        password: 'my passphrase',
    })
    kucoin.setSandboxMode(true)
    console.log(kucoin.id, await kucoin.fetchBalance())

**Comment by kroitor** [comment]
@JonPHenry does it work for you with a fresh new sandbox API keypair?

**Comment by JonPHenry** [comment]
> @JonPHenry does it work for you with a fresh new sandbox API keypair?

I'm not at home atm to try a new key. When I get home tonight I'll try one out.

**Comment by ttodua** [comment]
this issue has been stale for a while, recent ccxt version should not carry the issue.
if anyone would still face any problem, post a follow-up.
