### ISSUE TITLE
How to create a limit buy order using the full available amount on the right-hand side of the pair?

### ISSUE THREAD

**Issue by Danilo-Araujo-Silva** [ccxt/ccxt#8539]
Considering that we are using Binance, and we would like to trade over the pair **ETH/BTC**, for example.

What would it be the best way to create a limit buy order using the full available amount on the right-hand side of the pair?

For example, let's consider, for explaining purposes, that the price of the pair ETH/BTC is like `10 ETH -> 1 BTC`,
and we have a total amount of `20 BTC` in our balance.

If we were using the Binance UI, we could create a limit buy order (buying ETH) using 100% of our BTC balance (in this case 20 BTC), and we could stipulate the price of 10 ETH for 1 BTC. So when this order is fulfilled, we would get 200 ETH in our balance. How can we do that with CCXT?

Please note, that if this was the inverse, selling ETH, would be easier, since we could get the current ETH balance and sell it all for the stipulated price, with a code like this one (python):

```
eth_balance = ccxt_exchange_instance.fetchBalance()['free']['ETH']
ccxt_exchange_instance.create_order(
  'ETH/BTC',
  'limit',
  'sell',
  eth_balance,
  10, # 10 ETH -> 1 BTC
  {}
)
```

**Comment by xCuri0** [comment]
Use a market order and ```quoteOrderQty``` in params to specify amount in the quote currency (BTC)

**Comment by kroitor** [comment]
@Danilo-Araujo-Silva you can use the `quoteOrderQty` as @xCuri0 mentioned above, or just calculate the amounts in userland: https://github.com/ccxt/ccxt/issues/8210

Let us know if that does not answer your question.

**Comment by kroitor** [comment]
P.S. `quoteOrderQty` will work with market orders only:

```Python
ccxt_exchange_instance.create_order(
  'ETH/BTC',
  'market',
  'sell',
  None,
  None,
  {'quoteOrderQty':btc_balance}
)

**Comment by Danilo-Araujo-Silva** [comment]
Hi @xCuri0 and @kroitor,

Thanks for pointing me to use the `quoteOrderQty`

Unfortunately I need limit orders instead of market ones, since in my case these orders should not be fulfilled immediately.

What could I use as a workaround for that?
You said that I could calculate this in userland, what did you have in mind?

**Comment by kroitor** [comment]
> What could I use as a workaround for that?
> You said that I could calculate this in userland, what did you have in mind?

A limit order requires the amount and the price, where:

```
cost (quoteOrderQty) = amount * price
```

Therefore when both multipliers are known, you can use pure logic + arithmetics to calculate the values of your limit order.

```Python
symbol = 'BTC/USDT'
markets = exchange.load_markets()
market = exchange.market(symbol)
quote = market['quote']
balance = exchange.fetch_total_balance()
cost = balance[quote]
ticker = exchange.fetch_ticker(symbol)
price = ticker['last']
amount = cost / price
order = exchange.create_order(symbol, 'limit', side, amount, price)
```
