### ISSUE TITLE
Do you mind if I submit a pull request?

### ISSUE THREAD

**Issue by mudisdirty** [ccxt/ccxt#854]
Is it a bug report, a question or feature request? <sup>*(choose one)*</sup>

- [ ] bug report
- [x] question
- [ ] feature request

I fixed several small issues with qryptos and unicode handling in python3.  Do you mind if I push a branch a create a merge request?

**Comment by kroitor** [comment]
Thank you! We welcome all contributions! Please read this first: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md. We will be happy to see a pull request from you!

**Comment by kroitor** [comment]
I'd close this for now until we have a followup, if you don't mind. Let us know if you have any questions or if you need any assistance. We will be waiting for a contribution from you, thx!
