### ISSUE TITLE
I'm getting this issue of xena exchnage does not have a sandbox URL Using CCXT?

### ISSUE THREAD

**Issue by AsadullahSoomro** [ccxt/ccxt#8540]
OS: Windows
Programming Language version: Python 3.8
CCXT version: 1.42.49 (latest)

Hello!
I am using the latest version of CCXT to get private data from my Xena testnet account like BTC Balance etc.
But getting below ccxt error

Out Snapshot
:  raise NotSupported(self.id + ' does not have a sandbox URL')
ccxt.base.errors.NotSupported: xena does not have a sandbox URL

`import ccxt
print(ccxt.exchanges)
print(dir(ccxt.xena))
Xena_exchange = ccxt.xena({
    'apiKey': '',
    'secret': '',
    'enableRateLimit': True,
})
Xena_exchange.load_markets()
Xena_exchange.set_sandbox_mode(True)

balances = Xena_exchange.fetch_free_balance(params={"currency": "BTC"})
print(balances)`

Please guide me
Thanks in Advance..!

**Comment by kroitor** [comment]
@AsadullahSoomro i've added the testnet/sandbox URLs for Xena. Please upgrade to 1.42.51, the auto build will arrive in ~20 minutes. Let us know if you still have issues with it after upgrading to the most recent version. Thanks for the feedback!

**Comment by AsadullahSoomro** [comment]
I am checking it again.
Alright,
Thanks a lot.

**Comment by kroitor** [comment]
@AsadullahSoomro our Travis CI will push 1.42.51 in ~15 minutes. Don't hesitate if anything. Thx!
