### ISSUE TITLE
Error in fetch_ohlcv in phemex

### ISSUE THREAD

**Issue by maxmahbk** [ccxt/ccxt#8541]
- OS: Windows 10 Pro   19042.746
- Programming Language version: python
- CCXT version: ccxt 1.42.52

Failed fetch_ticker and fetch_ohlcv, i use this code without problems many months
But today i try edit my bot and report error ***TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'***

![Capture](https://user-images.githubusercontent.com/70783418/109896452-82365d80-7cc3-11eb-925f-8bbb14a62948.JPG)

**Comment by kroitor** [comment]
@maxmahbk please, always follow the guidelines precisely, don't paste text as images:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

Let us know if you still have this issue with the most recent version using this code:

```Python
import ccxt
from pprint import pprint

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.phemex({
    'enableRateLimit': True,
})

markets = exchange.load_markets()

# exchange.verbose = True  # uncomment for debugging purposes

ohlcvs = exchange.fetch_ohlcv('BTC/USD', '1m', None, 50)
pprint(ohlcvs)
```

If you have a problem with the above code, please paste your verbose output. Feel free to reopen this issue or just ask further questions if any.

**Comment by maxmahbk** [comment]
Thank you very much

I misunderstanding my ccxt version it resolved after update ccxt to last
version.

**Comment by pavan344** [comment]
Hi Guys While I use fetch_ohlcv to get the data in my bot, after running it for couple of hours, the connection is closed by remote server. How can I overcome this "**ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054,None))"**

How can I make sure it wont close connection

**Comment by kroitor** [comment]
@pavan344 please, paste your version numbers and a complete snippet of code, including the instantiation, but without your keys, ideally, follow these steps precisely: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help, otherwise we're mostly guessing, hope for your understanding. Please, provide as much information as you can.
