### ISSUE TITLE
Kraken loadMarkets - TypeError: Cannot use 'in' operator to search for 'error' in undefined

### ISSUE THREAD

**Issue by deman4ik** [ccxt/ccxt#8554]
- OS: Mac OS
- Programming Language version: node v14.15.1
- CCXT version: 1.42.54

I don't know how to reproduce it now but I think this is some internal thing.
Just found this error in logs.

```
const exchange = new ccxt.kraken({
  apiKey: "",
  secret: ""
});
await exchange.loadMarkets();
```

```
TypeError: Cannot use 'in' operator to search for 'error' in undefined\n 
at kraken.handleErrors (/usr/src/app/node_modules/ccxt/js/kraken.js:1832:29)\n 
at /usr/src/app/node_modules/ccxt/js/base/Exchange.js:594:18\n 
at runMicrotasks (<anonymous>)\n at processTicksAndRejections (internal/process/task_queues.js:93:5)\n 
at async timeout (/usr/src/app/node_modules/ccxt/js/base/functions/time.js:195:24)\n 
at async kraken.fetchMarkets (/usr/src/app/node_modules/ccxt/js/kraken.js:252:26)\n 
at async kraken.loadMarketsHelper (/usr/src/app/node_modules/ccxt/js/base/Exchange.js:660:25)\n 
at async PrivateConnector.getBalances (/usr/src/app/dist/apps/connector-worker/main.js:3619:9)
```

**Comment by kroitor** [comment]
```JavaScript
const ccxt = require ('ccxt')
console.log ('CCXT Version:', ccxt.version)
async main () {
    const exchange = new ccxt.kraken({ enableRateLimit: true, verbose: true })
    await exchange.loadMarkets()
    console.log ('-----------------------------------------------')
    console.log(exchange.markets)
}
main ()
```

↑ Please paste your output using this snippet.

**Comment by kroitor** [comment]
P.S. If the above snippet works, but some other code doesn't work, that indicates a problem in the other code. Please paste a short (but complete) snippet to reproduce. Remove all irrelevant parts, remove your codelines one by one until you're left with just 10-20 lines that replicate the issue.

**Comment by deman4ik** [comment]
Yes it works now and it worked after a couple of retries with no code/environment changes.
May be this was some network or exchange issues but this error message seemed suspicious to me.

**Comment by kroitor** [comment]
@deman4ik i've added a bit more to the error handler, please, let me know if you experience the same issue with the new version 1.42.60 (it will arrive in ~20 minutes). Thanks for your feedback!
