### ISSUE TITLE
Binance fetchTrades with since argument

### ISSUE THREAD

**Issue by Deathamns** [ccxt/ccxt#856]
If `since` is used in `fetchTrades` on Binance, the result will be an `ExchangeNotAvailable` error.

The [docs](https://www.binance.com/restapipub.html#user-content-market-data-endpoints) don't mention it, but it seems that the `endTime` parameter is required too if the `startTime` is used (which is used when the `since` argument is used).

https://api.binance.com/api/v1/aggTrades?symbol=ETHBTC&startTime=1513255356130&limit=500
vs
https://api.binance.com/api/v1/aggTrades?symbol=ETHBTC&startTime=1513255356130&endTime=1513259430825&limit=500

**Comment by kroitor** [comment]
@Deathamns what would you suggest as a solution to this?

**Comment by Deathamns** [comment]
I couldn't decide, that's why I created an issue.

They don't allow more than a day, so there are two possibilities when `since` is given.
endTime = since + 24h
endTime = now - 24h

**Comment by kroitor** [comment]
@Deathamns we will choose #1, endTime = since + 24h, that is what would be most convenient from a user perspective (it is still overrideable with extra `params`, if you need a specific time-range)...

**Comment by kroitor** [comment]
@Deathamns thank you for reporting this, uploaded a fix for it, will be available in the next version in 5-10 minutes.

**Comment by ZIYUNCHEN** [comment]
Running into similar issue from this one.  I see we need to pass in additional parameters pulling trades from binance. Although it still gives me error msg below:

trades=exchange.fetch_trades(currency_pair,since=utc_min_ago*1000,params={'startTime':utc_min_ago*1000,'endTime':utc_now*1000})

ccxt.base.errors.InvalidOrder: binance {"code":-1100,"msg":"Illegal characters found in parameter 'startTime'; legal range is '^[0-9]{1,20}$'."}

**Comment by kroitor** [comment]
@ZIYUNCHEN 

> Running into similar issue from this one. I see we need to pass in additional parameters pulling trades from binance.

You can do time conversions with CCXT 1.14.77

```
mbp:python igorkroitor$ python
Python 2.7.13 (default, Jun  5 2017, 10:04:07)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> exchange = ccxt.binance()
>>> since = exchange.parse8601('2018-01-01T00:00:00')
>>> trades = exchange.fetch_trades('ETH/BTC', since)
>>> trades[0]['datetime']
'2018-01-01T00:00:00.171Z'
>>> trades[10]['datetime']
'2018-01-01T00:00:01.846Z'
>>> trades[20]['datetime']
'2018-01-01T00:00:02.462Z'
>>>```

**Comment by kroitor** [comment]
@ZIYUNCHEN 

```Python
>>> trades = exchange.fetch_trades('ETH/BTC', since - 24 * 60 * 60 * 1000)  # one hour back
>>> trades[0]['datetime']
'2017-12-31T00:00:00.513Z'
>>> trades[10]['datetime']
'2017-12-31T00:00:07.628Z'
>>> trades[20]['datetime']
'2017-12-31T00:00:12.560Z'
>>>
```
