### ISSUE TITLE
Request blocked by CORS policy

### ISSUE THREAD

**Issue by mmehrle** [ccxt/ccxt#8561]
I ran the following JavaScript successfully in my browser during testing:

```
<script type="text/javascript">
const exchange = new ccxt.binance();

if (exchange.has['fetchTicker']) {
    exchange.fetchTicker ('BTC/USDT', '1m')
    .then(function(data) {
      var btc = data.last;
      console.log(btc);
      console.log(data);
      return btc;
    })
}
</script>
```

I switched over to kraken and received the following error:

_Access to fetch at 'https://api.binance.com/api/v3/ticker/24hr?0=1&1=m&symbol=BTCUSDT' from origin 'https://xxxxxxxxxxxx.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.._

Fine, so I switch back to binance but now I'm getting the very same error there as well! I've got this running on my webserver and I hope my domain hasn't been added to some block list. Setting up a proxy server isn't an option for me. Is there a work around?

**Comment by mmehrle** [comment]
Follow up: I actually set up a proxy server (cors.py) on my server but now I'm getting this:

GET https://xxxxxxxxxxxx:8080/https://api.binance.com/api/v3/exchangeInfo net::ERR_NAME_NOT_RESOLVED
executeRestRequest @ ccxt.browser.js:3723
fetch @ ccxt.browser.js:3843
fetch2 @ ccxt.browser.js:3853
async function (async)
fetch2 @ ccxt.browser.js:3849
request @ ccxt.browser.js:11395
partial @ ccxt.browser.js:3798
fetchMarkets @ ccxt.browser.js:9627
loadMarketsHelper @ ccxt.browser.js:4032
loadMarkets @ ccxt.browser.js:4040
fetchTicker @ ccxt.browser.js:10004
(anonymous) @ ccxt-fetch-ohlcv.html:29

Here's my JS code (again running inside a browser):

```
<script type="text/javascript">
const exchange = new ccxt.binance({'enableRateLimit': true})
exchange.proxy = 'https://xxxxxxxxxxx:8080/'

if (exchange.has['fetchTicker']) {
    exchange.fetchTicker ('BTC/USDT', '1m')
    .then(function(data) {
      var btc = data.last;
      console.log(btc);
      console.log(data);
      return btc;
    })
}
</script>
```

**Comment by kroitor** [comment]
@mmehrle your CORS-proxy is http (not https):

```HTML
<script type="text/javascript">
const exchange = new ccxt.binance({'enableRateLimit': true})
exchange.proxy = 'http://xxxxxxxxxxx:8080/'  // ←---------------------- changed https → http

if (exchange.has['fetchTicker']) {
    exchange.fetchTicker ('BTC/USDT', '1m')
    .then(function(data) {
      var btc = data.last;
      console.log(btc);
      console.log(data);
      return btc;
    })
}
</script>
```

Make sure your proxy is running and try this script ↑
Does it work this way?

**Comment by mmehrle** [comment]
Actually see above - my latest response shows it with https. That cors.py script however doesn't work with https it seems:

echo | openssl s_client --connect xxxxxxxxxxx.com:8080 2>/dev/null | openssl x509 -noout -text | grep -Ei "Subject:|Issuer:|Before|After|DNS" | sed "s/^[ \t]*//"
unable to load certificate
140703661552128:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:Expecting: TRUSTED CERTIFICATE
===

**Comment by mmehrle** [comment]
FYI - I misunderstood and changed it back to http. However that produces the following error in my script:

`ccxt.browser.js:3723 Mixed Content: The page at 'https://xxxxxxxxxxx.com/cryptonaissance/ccxt-fetch-ohlcv.html' was loaded over HTTPS, but requested an insecure resource 'http://xxxxxxxx:8080/https://api.binance.com/api/v3/exchangeInfo'. This request has been blocked; the content must be served over HTTPS.`

**Comment by kroitor** [comment]
@mmehrle you will need a HTTPS CORS proxy if your page is served over HTTPS, or just add an NGINX in front of your CORS to serve HTTPS, while keeping the source code of the proxy HTTP-specific.

**Comment by mmehrle** [comment]
Would proxy.py work? https://pypi.org/project/proxy.py/#start-proxypy

**Comment by kroitor** [comment]
@mmehrle it may work if properly configured, however, you will have to use the `proxies` property for regular instead of `proxy` property for CORS. https://github.com/ccxt/ccxt/wiki/Install#proxy

**Comment by mmehrle** [comment]
@kroitor Before I spend a lot of time and resources setting this up I want to make sure that a reverse proxy actually works. I just tried a public one and the script still failed:

```
<script type="text/javascript">
//console.log(fetchOHLCV());
</script>

<script type="text/javascript">
const exchange = new ccxt.binance({'enableRateLimit': true})
exchange.proxy = 'https://thingproxy.freeboard.io/fetch/'

if (exchange.has['fetchTicker']) {
    exchange.fetchTicker ('BTC/USDT', '1m')
    .then(function(data) {
      var btc = data.last;
      console.log(btc);
      console.log(data);
      return btc;
    })
}
</script>
```

**Error:**
Access to fetch at 'https://thingproxy.freeboard.io/fetch/https://api.binance.com/api/v3/exchangeInfo' from origin 'https://xxxxxxxxx.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

So is the problem related to me using a public proxy? Reading the docs my understanding was that a public proxy was permissible.

**Comment by mmehrle** [comment]
@kroitor **Good news!** I set up corsproxy on my server and it's now working again. These are the instructions for CentOS but I'm sure they can be easily adapted for another distro:

https://github.com/caltechlibrary/corsproxy/blob/main/admin/README.md#configuring-the-use-of-https

**Comment by kroitor** [comment]
@mmehrle thx for your feedback! Cheers!
