### ISSUE TITLE
HitBTC does not have a sandbox URL 

### ISSUE THREAD

**Issue by AsadullahSoomro** [ccxt/ccxt#8569]
Hi,
Currently, I am trying to check wallet balance and to get market data throughout both ccxt  library functions 

I have also updated the pip version

But again and again, I am getting this exception hitbtc does not have a sandbox URL
please help me...

Thanks in advance!

**OS:** Windows 10 Pro
**Programming Language version:** python 3.8.5
**CCXT version:** 1.42.53
**pip v**== 21.0.1

**Code:**

`import ccxt

exchange = ccxt.hitbtc({
    'apiKey': '',
    'secret': '',
    'enableRateLimit': True,
})
exchange.load_markets()
exchange.set_sandbox_mode(True)

balance = exchange.fetch_balance({'currency': 'BTC'})`
**Output:**
 raise NotSupported(self.id + ' does not have a sandbox URL')
ccxt.base.errors.NotSupported: hitbtc does not have a sandbox URL

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/8570#issuecomment-796454258
