### ISSUE TITLE
CCXT does not support HitBTC sandbox URL?? 

### ISSUE THREAD

**Issue by AsadullahSoomro** [ccxt/ccxt#8570]
Hello!

I am using HitBTC Testnet Account having a dummy balance for trading. 
I have created API and the secret to get the private data throughout ccxt library functions.

Currently, I am getting the exception of hitbtc does not have a sandbox URL

please guide me.

[HitBTC Testnet](https://demo.hitbtc.com/btc-to-usdt)

Thanks in advance!

**OS**: Windows 10 Pro
Programming Language version: python 3.8.5
**CCXT version**: 1.42.53
pip v== 21.0.1

**Code**:

`import ccxt

exchange = ccxt.hitbtc({
'apiKey': '',
'secret': '',
'enableRateLimit': True,
})
exchange.load_markets()
exchange.set_sandbox_mode(True)

balance = exchange.fetch_balance({'currency': 'BTC'})`

**Output**:

**raise NotSupported(self.id + ' does not have a sandbox URL')
ccxt.base.errors.NotSupported: hitbtc does not have a sandbox URL**

**Comment by kroitor** [comment]
Hi! HitBTC didn't have a sandbox URL for historical reasons, I have pushed the URLs for it, and the testnet should be available in CCXT as of version 1.42.75. The new build will arrive in ~20 minutes. Please, let us know after upgrading if that solves the issue for you or not. Thanks for your feedback!

**Comment by UsmanKhOkhar16** [comment]
@kroitor @AsadullahSoomro
OS: Windows 10 Pro
Programming Language version: python 3.8.5
CCXT version: 1.42.53
pip v== 21.0.1 
Hi, I am trying to fetch the data from the Positions, But I cant find any function that can fetch positions data.
Kindly look into this.
Thanks in advance

**Comment by kroitor** [comment]
@UsmanKhOkhar16 we will add that asap! Thx for your feedback!
