### ISSUE TITLE
Question about TICK_SIZE precision

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#8572]
OS: Windows Server 2019 Datacenter
Programming Language version: Node.js 15.3.0
CCXT version: 1.38.89
Exchange: All Exchanges
Method: decimalToPrecision

Hello!

I have red about precision and limits here:
[https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits](url)

I understand the examples of how to round: **"good" and "bad"**.
I just want to confirm a question mark for precisions so I am sure:

**TICK_SIZE**
Exchange FTX and for BTC/USD: **"precision":{"amount":0.0001,"price":1}**

Question 1: As I understand we must send prices like: 55001, 55002, 55003 and not 55001.0, 55002.0, 55003.0 ?
Question 2: As I understand we must send amounts like: 1.0123, 0.7894 ?

Thank you!

**Comment by frosty00** [comment]
> Question 1: As I understand we must send prices like: 55001, 55002, 55003 and not 55001.0, 55002.0, 55003.0 ?

It does not matter if you send a price like 55001 or 55001.0 as they are treated the same by ccxt. You cannot send 55001.5 or 55001.1234

> Question 2: As I understand we must send amounts like: 1.0123, 0.7894 ?

Yes this is correct, you must not send amounts like 1.01234 or 0.12345

**Comment by jackpotcityco** [comment]
That is great!

Thank you for your help, I felt 98% sure but now it is clear.

Thank you!
