### ISSUE TITLE
How to declare decimalToPrecision 

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#8576]
OS: Windows Server 2019 Datacenter
Programming Language version: Node.js 15.3.0
CCXT version: 1.38.89
Exchange: All Exchanges
Method: decimalToPrecision 

Hello!

I am trying to find the decimalToPrecision function in the library but are not sure I can find it. 
What is the proper way to define this function in javascript?
```
'use strict';
const ccxt = require('ccxt');

let exchange = new ccxt.bitfinex(); 

exchange.decimalToPrecision //does not exist here?
ccxt.decimalToPrecision //does not exist here?
```
As I understand, we should use decimalToPrecision when putting precisions to amount and price?

Thank you!

**Comment by jackpotcityco** [comment]
It seems that decimalToPrecision is not shown in the compiler when writing the code but still exists and works.
So I think this should be correct then.

```
let exchange = new ccxt.bitfinex(); //ROUND, TRUNCATE
var roundedNum = exchange.decimalToPrecision(123.456, ccxt.TRUNCATE, -1, 0); //(x, roundingMode, numPrecisionDigits, countingMode = DECIMAL_PLACES, paddingMode = NO_PADDING)
console.log(roundedNum); //Shows 120
```

**Comment by kroitor** [comment]
@jackpotcityco i've added some noted on it here: https://github.com/ccxt/ccxt/wiki/Manual#methods-for-formatting-decimals

Basically, all you need is `amountToPrecision`, `priceToPrecision`. Let us know if that does not help.
