### ISSUE TITLE
FTX - fetchTrades - Start and End times specified incorrectly

### ISSUE THREAD

**Issue by lostless13** [ccxt/ccxt#8590]
- OS:
- Programming Language version: Javascript
- CCXT version: ccxt@1.42.77

Current behavior:
Make request to ftx using fetchTrades endpoint. Set since parameter to any time in the past. It will always return the latest trades.

The FTX fetch trades endpoint functions in reverse the current ccxt implementation. If you provide the end_date parameter, it will provide trades occurring immediately before the provided end_times up to the limit provided. eg:
```
https://ftx.com/api/markets/BTC/USD/trades?limit=100&end_time=1581445910
```

Below, will provide the latest 100 trades for any start time in the past:
```
https://ftx.com/api/markets/BTC/USD/trades?limit=100&start_time=1581445910
```

Current request times implementation:
```
        if (since !== undefined) {
            request['start_time'] = parseInt (since / 1000);
            // start_time doesn't work without end_time
            request['end_time'] = this.seconds ();
        }
```

**Comment by diwenshi61** [comment]
Not sure about this - https://ftx.com/api/markets/BTC/USD/trades?limit=100&start_time=1581445910 provides the latest 100 trades for me, ignoring the start time parameter. It doesn't seem like the start_time parameter is accepted without an end_time, as documented in the code.

If you want to limit the trades, it seems that it needs to be done on the client side rather than the server side, as FTX will not serve a limited number of trades starting from a start_time as far as I can see.

**Comment by lostless13** [comment]
> Not sure about this - https://ftx.com/api/markets/BTC/USD/trades?limit=100&start_time=1581445910 provides the latest 100 trades for me, ignoring the start time parameter. It doesn't seem like the start_time parameter is accepted without an end_time, as documented in the code.
> 
> If you want to limit the trades, it seems that it needs to be done on the client side rather than the server side, as FTX will not serve a limited number of trades starting from a start_time as far as I can see.

I guess the solution to getting historical trades through ccxt would be to pass an end_time through the params field?

**Comment by kroitor** [comment]
@lostless13 yes, that's exactly the way to paginate FTX trades, you have to stick to end_time. Their API allowed querying from start_time before, but not anymore. Closing this for now, feel free to reopen it if needed or just ask further questions if any.
