### ISSUE TITLE
Closing completely a position at Market price with Binance

### ISSUE THREAD

**Issue by zed2zed** [ccxt/ccxt#8598]
Hello,

I want to close a position with ccxt (PHP) at maket price.

I read here and there that it was necessary to create an opposite order, but at the given time I would not know the exact price of my value and the order to be given to liquidate everything. 
If I bought 0.01 BTC and now I have 0.01759, I want to liquidate 0.01759 BTC. Knowing that a second later the value will have changed. 

How to close position at market price like in Binance application ?

Thank you

**Comment by kroitor** [comment]
Hi!

> I read here and there that it was necessary to create an opposite order, but at the given time I would not know the exact price of my value and the order to be given to liquidate everything.

When the limit price is unknown, you should liquidate at market price. So, basically, if you bought 100 coins, you should sell 100 coins at market price to close your position. This will depend on the type of your position (whether it's isolated or cross margin), and whether it's a one-way or hedged position. Can you elaborate on the type of your position? Maybe, post some code?

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by ttodua** [comment]
I deem this issue to be closed, as there has been no reply or any detail from user to understand what s/he wanted. 
in two words, whatever could have been said, @ kroitor mentioned above. 
Also, as the topic mentions `binance` specifically, I might add a reference to my another reply in similar topic: https://github.com/ccxt/ccxt/issues/8304#issuecomment-1289485719 
which suggests that even if you have a long position with i.e. `0.123` amount, if you make `exchange.create_order('BTC/USDT:USDT', 'market', 'sell', 0.777, null, ['positionSide'=>'LONG' ] )` it will still close the position fully. 
But as already mentioned above, the original post is missing much details and we can't say more about it.

Let us know if you have further issues with CCXT and reply follow-up if you will read this.
