### ISSUE TITLE
Network Errors. Unable to download even one complete set of historical candles.

### ISSUE THREAD

**Issue by mrwonderfulness** [ccxt/ccxt#8599]
No matter how low I set the limit, the connection always drops out. Usually it is able to get about 1 year of data before the errors below occur. Since this is public data, I am not using a key. Does that effect how much data can be downloaded? 
Thanks for looking. 

- OS: Mac
- Programming Language version: Python 3.8
- CCXT version:most recent

```
def scrape_ohlcv(symbol):

    exchange = ccxt.binance({
    'rateLimit': 200,
    'enableRateLimit': True,
    #'verbose': True,
    })

    start_timestamp = exchange.fetch_ohlcv(symbol, '1m', since=0, limit=1)[0][0]

    now = exchange.milliseconds()

    data = []

    while start_timestamp < end_time:

        try:


            print(exchange.iso8601(exchange.milliseconds()))
            print(f'Fetching {symbol} minutes from:')
            print(exchange.iso8601(start_timestamp))
            ohlcvs = exchange.fetch_ohlcv(symbol, '1m', since=start_timestamp, limit=200 )
            print('Fetched', len(ohlcvs), 'minutes')
            print()
            start_timestamp = ohlcvs[-1][0]
            data += ohlcvs
            time.sleep(1)

        except (ccxt.ExchangeError, ccxt.AuthenticationError, ccxt.ExchangeNotAvailable, ccxt.RequestTimeout) as error:

            print('Got an error', type(error).__name__, error.args, ', retrying in', hold, 'seconds...')
            time.sleep(hold)

    return data```

```
Traceback (most recent call last)

ConnectionResetError: [Errno 104] Connection reset by peer

urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

ccxt.base.errors.NetworkError: binance GET https://api.binance.com/api/v3/klines?symbol=BTCUSDT&interval=1m&startTime=1540008480000&limit=200
```

**Comment by kroitor** [comment]
Can you please post your verbose output before the crash? It will print your headers and rate limits there... You should not change the `rateLimit` unless you're 100% sure.

**Comment by mrwonderfulness** [comment]
this is the beginning of the message right at the crash. before this, there is just data ohlcv data. 

Request: GET https://api.binance.com/api/v3/klines?symbol=BTCUSDT&interval=1m&startTime=1552389300000&
limit=200 {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate'} None           
Traceback (most recent call last):                                                                    
  File "/home/ge/miniconda3/envs/artemis/lib/python3.8/site-packages/urllib3/connectionpool.py", l
ine 699, in urlopen                                                                                   
    httplib_response = self._make_request(                                                            
  File "/home/ge/miniconda3/envs/artemis/lib/python3.8/site-packages/urllib3/connectionpool.py", l
ine 445, in _make_request                                                                             
    six.raise_from(e, None)                                                                           
  File "<string>", line 3, in raise_from                                                              
  File "/home/ge/miniconda3/envs/artemis/lib/python3.8/site-packages/urllib3/connectionpool.py", l
ine 440, in _make_request                                                                             
    httplib_response = conn.getresponse()                                                             
  File "/home/ge/miniconda3/envs/artemis/lib/python3.8/http/client.py", line 1347, in getresponse 
    response.begin()                                                                                  
  File "/home/ge/miniconda3/envs/artemis/lib/python3.8/http/client.py", line 307, in begin        
    version, status, reason = self._read_status()
  File "/home/ge/miniconda3/envs/artemis/lib/python3.8/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/home/ge/miniconda3/envs/artemis/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/home/ge/miniconda3/envs/artemis/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/home/ge/miniconda3/envs/artemis/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by kroitor** [comment]
Please, upgrade to CCXT 1.43.13+ (the new build will arrive in ~20 minutes) and change the following line like so:

```
        except (ccxt.ExchangeError, ccxt.AuthenticationError, ccxt.ExchangeNotAvailable, ccxt.RequestTimeout) as error:
```
↓
```
        except (ccxt.ExchangeError, ccxt.NetworkError, ccxt.AuthenticationError, ccxt.ExchangeNotAvailable, ccxt.RequestTimeout) as error:
```

Let us know if the above does not help.

**Comment by mrwonderfulness** [comment]
or, perhaps you mean this, from the very beginning after running the python code:

Request: GET https://api.binance.com/api/v3/klines?symbol=BTCUSDT&interval=1m&startTime=0&limit=1 {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate'} None                                                                             
                                                                                                                                                                                                                                                                
Response: GET https://api.binance.com/api/v3/klines?symbol=BTCUSDT&interval=1m&startTime=0&limit=1 200 {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '170', 'Connection': 'keep-alive', 'Date': 'Sun, 14 Mar 2021 02:49:08 GMT', 'Server'
: 'nginx', 'x-mbx-uuid': '55e3d65d-9940-41c5-8241-9725653aa980', 'x-mbx-used-weight': '2', 'x-mbx-used-weight-1m': '2', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block'
, 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', '
Expires': '0', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, HEAD, OPTIONS', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 04c2f7c6be96060d3defd0bb02b9dbde.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'NRT12-C3', 'X-Amz-Cf-Id'
: '-9Wu5lLCdCO_MC0p17ohGwKh5i0aLZPhl7oUgFcCAA9PsRhpDmMhhA=='} [[1502942400000,"4261.48000000","4261.48000000","4261.48000000","4261.48000000","1.77518300",1502942459999,"7564.90685084",3,"0.07518300","320.39085084","7960.54017996"]]

**Comment by mrwonderfulness** [comment]
I upgraded CCXT to the most recent version, and I am no longer getting the error above, but now it gets stuck at 2018-02-08T00:28:00.000Z. It seems to continually fetch the same minute over and over until I cancel with Crtl-c.

It's the first time I've had this problem. Here is the verbose output that comes each time at the above kline minute..over, and over:

Request: GET https://api.binance.com/api/v3/klines?symbol=BTCUSDT&interval=1m&limit=500&startTime=1518049680000&endTime=1518079679999 {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.binance.com/api/v3/klines?symbol=BTCUSDT&interval=1m&limit=500&startTime=1518049680000&endTime=1518079679999 200 {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '163', 'Connection': 'keep-alive', 'Date': 'Sun, 14 Mar 2021 05:52:26 GMT', 'Server': 'nginx', 'x-mbx-uuid': '8ac2de23-202f-4a08-8422-b79a0ae69891', 'x-mbx-used-weight': '53', 'x-mbx-used-weight-1m': '53', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, HEAD, OPTIONS', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 d0f0387f17e342499361c2e2e88948b2.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'NRT12-C2', 'X-Amz-Cf-Id': 'eEHuLWp2xYrAu_INdNp6dTz0O3svv881Ob7fESPMJbG5ZJOUSAWJpw=='} [[1518049680000,"7790.00000000","7794.91000000","7783.81000000","7784.02000000","8.15356400",1518049694788,"63515.48081620",100,"6.60431900","51454.16786924","0"]]
Fetched 1 minutes

**Comment by mrwonderfulness** [comment]
After trying a few times, it appears to not be able to fetch beyond the above time:
2018-02-08T00:28:00.000Z

Why would it stop there?

**Comment by kroitor** [comment]
@mrwonderfulness see this issue: https://github.com/ccxt/ccxt/issues/4170

Basically, it paginates in ranges of 500 minutes, and there was a gap longer than 500 minutes there. You just need to change the script slightly to not pause on empty response and continue paginating...

**Comment by mrwonderfulness** [comment]
It's strange, I just did a test to limit the amount per fetch to 100, to. see if it hangs at the above time. 
It does stop fetching new data, but now stops at 2017-09-06T15:59:00.000Z.

**Comment by mrwonderfulness** [comment]
Is there an example in the examples page? This must be a pretty fairly common problem?

**Comment by kroitor** [comment]
@mrwonderfulness i'll post a link shortly.

**Comment by mrwonderfulness** [comment]
Thank you!

**Comment by kroitor** [comment]
@mrwonderfulness i've updated that example, please, check here:

- https://github.com/ccxt/ccxt/blob/master/examples/py/binance-fetch-ohlcv-to-csv.py

```Python
# -*- coding: utf-8 -*-

import os
import sys
import csv
import ccxt


# -----------------------------------------------------------------------------

def retry_fetch_ohlcv(exchange, max_retries, symbol, timeframe, since, limit):
    num_retries = 0
    try:
        num_retries += 1
        ohlcv = exchange.fetch_ohlcv(symbol, timeframe, since, limit)
        # print('Fetched', len(ohlcv), symbol, 'candles from', exchange.iso8601 (ohlcv[0][0]), 'to', exchange.iso8601 (ohlcv[-1][0]))
        return ohlcv
    except Exception:
        if num_retries > max_retries:
            raise  # Exception('Failed to fetch', timeframe, symbol, 'OHLCV in', max_retries, 'attempts')


def scrape_ohlcv(exchange, max_retries, symbol, timeframe, since, limit):
    timeframe_duration_in_seconds = exchange.parse_timeframe(timeframe)
    timeframe_duration_in_ms = timeframe_duration_in_seconds * 1000
    timedelta = limit * timeframe_duration_in_ms
    now = exchange.milliseconds()
    all_ohlcv = []
    fetch_since = since
    while fetch_since < now:
        ohlcv = retry_fetch_ohlcv(exchange, max_retries, symbol, timeframe, fetch_since, limit)
        fetch_since = (ohlcv[-1][0] + 1) if len(ohlcv) else fetch_since + timedelta
        all_ohlcv = all_ohlcv + ohlcv
        if len(all_ohlcv):
            print(len(all_ohlcv), 'candles in total from', exchange.iso8601(all_ohlcv[0][0]), 'to', exchange.iso8601(all_ohlcv[-1][0]))
        else:
            print(len(all_ohlcv), 'candles in total from', exchange.iso8601(fetch_since))
    return exchange.filter_by_since_limit(all_ohlcv, since, None, key=0)


def write_to_csv(filename, data):
    with open(filename, mode='w') as output_file:
        csv_writer = csv.writer(output_file, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
        csv_writer.writerows(data)


def scrape_candles_to_csv(filename, exchange_id, max_retries, symbol, timeframe, since, limit):
    # instantiate the exchange by id
    exchange = getattr(ccxt, exchange_id)({
        'enableRateLimit': True,  # required by the Manual
    })
    # convert since from string to milliseconds integer if needed
    if isinstance(since, str):
        since = exchange.parse8601(since)
    # preload all markets from the exchange
    exchange.load_markets()
    # fetch all candles
    ohlcv = scrape_ohlcv(exchange, max_retries, symbol, timeframe, since, limit)
    # save them to csv file
    write_to_csv(filename, ohlcv)
    print('Saved', len(ohlcv), 'candles from', exchange.iso8601(ohlcv[0][0]), 'to', exchange.iso8601(ohlcv[-1][0]), 'to', filename)


# -----------------------------------------------------------------------------
# Binance's BTC/USDT candles start on 2017-08-17
scrape_candles_to_csv('binance.csv', 'binance', 3, 'BTC/USDT', '1m', '2017-08-17T00:00:00Z', 100)
```

**Comment by mrwonderfulness** [comment]
is this where the magic happens? :)
'''
fetch_since = (ohlcv[-1][0] + 1) if len(ohlcv) else fetch_since + timedelta
'''

**Comment by kroitor** [comment]
@mrwonderfulness yep, it's a pretty simple logic, if there's no gap – continue from last known candle, otherwise add limit period and continue.

**Comment by mrwonderfulness** [comment]
Thanks for your help, I'll try to get it to work. Cheers.

**Comment by mrwonderfulness** [comment]
I have one question about the code above. If there is a time gap on the exchange(due to maintainance, etc.), don't you have to fetch from the next minute, rather than the `timedelta` in order to not miss any minutes...meaning, don't we have to keep searching minute by minute until the next one is available? (if we are fetching 1 minute ohlcv)

**Comment by kroitor** [comment]
@mrwonderfulness it there's a gap, then there's definitely no candles within `timedelta`, so it only makes to continue beyond `timedelta`.

**Comment by mrwonderfulness** [comment]
but isn't `timedelta` the time in ms * the limit, which could be, for example, `500`. In this case you jump 500 minutes ahead, but the next available minutes might be 5 minutes later.

**Comment by kroitor** [comment]
@mrwonderfulness it will only jump 500 minutes ahead, if it is 100% sure that there are no candles within the timeframe of 500 candles ahead (a gap of at least 500 candles). Otherwise, it will catch those candles on a previous iteration and will continue from the last candle.

**Comment by kroitor** [comment]
I've updated that line to make it clearer:

```
        fetch_since = (ohlcv[-1][0] + 1) if len(ohlcv) else (fetch_since + timedelta)
```

**Comment by mrwonderfulness** [comment]
thanks again.
