### ISSUE TITLE
Coincheck: GET request with parameters

### ISSUE THREAD

**Issue by forzavortis** [ccxt/ccxt#861]
Coincheck: GET request with parameters

- Language:　python3.5
- CCXT version: newest
- Exchange: Coincheck

```
coincheck.request('exchange/leverage/positions', 'private', method='GET')
```
returns normal.

But, when I add parameters, coincheck returns error.
```
coincheck.request('exchange/leverage/positions', 'private', method='GET', params={'status':'open'})
```
returns 
```
403 Forbidden
The request could not be satisfied.
Bad request.
```

Not only ```exchange/leverage/positions``` request, but also other GET request with parameters make same response.

**Comment by kroitor** [comment]
Hi! Thanks for reporting! I will take a look and will get back to you soon.
