### ISSUE TITLE
How to get the array rateLimits reported by Binance at /api/v1/exchangeInfo ?

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#8626]
Hello,

I'm trying to implement a request weight count for Binance and I would like to get the array `rateLimits` bellow reported by Binance at `/api/v1/exchangeInfo`. My problem is this information is not available in the fields of the exchange class. Could you please tell me how I could access it after initializing the client ?

Thank you

```
	"rateLimits": [{
		"rateLimitType": "REQUEST_WEIGHT",
		"interval": "MINUTE",
		"intervalNum": 1,
		"limit": 1200
	}, {
		"rateLimitType": "ORDERS",
		"interval": "SECOND",
		"intervalNum": 10,
		"limit": 100
	}, {
		"rateLimitType": "ORDERS",
		"interval": "DAY",
		"intervalNum": 1,
		"limit": 200000
	}]
```

**Comment by kroitor** [comment]
@Kinzowa hi!

You can do that in many ways, for example using exchange properties or with implicit methods as described in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

```Python
import ccxt
from pprint import pprint

print('CCXT Version:', ccxt.__version__)
exchange = ccxt.binance({'enableRateLimit': True})

# option 1
response = exchange.publicGetExchangeInfo()
pprint(response)
print('--------------------------------------------------')

# option 2
response = exchange.fetchMarkets()
pprint(exchange.last_json_response)
print('--------------------------------------------------')

# ...
```

Let us know if that does not answer your question.
