### ISSUE TITLE
can not instantiate with SubAccount ( FTX) 

### ISSUE THREAD

**Issue by Merrick17** [ccxt/ccxt#8629]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:Linux
- Programming Language version: Js (Nod 12.21) 
- CCXT version:1.43.1

```
I can't find how to add the SubAccount as a params for FTX 
try {
    ftx = await new cctx.ftx({
      apiKey: "MY API KEY",
      secret: "SECRET",
    });
    console.log(ftx);
    let balance = await ftx.fetchBalance();
    console.log(balance);
  } catch (error) {
    console.log(error.message);
  }
```

```
ftx {"error":"Only have permissions for subaccount ReadyRaider","success":false}
```

**Comment by kroitor** [comment]
Add the subaccount headers as explained in this duplicate issue: https://github.com/ccxt/ccxt/issues/6985#issuecomment-636520340

```JavaScript
const exchange = new ccxt.ftx({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': true,
    'headers': {
        'FTX-SUBACCOUNT': 'ReadyRaider',   
    ),
));
```

Let us know if that does not help.

**Comment by Merrick17** [comment]
it started showing Not Logged In issue 
ftx {"success":false,"error":"Not logged in"}

**Comment by kroitor** [comment]
@Merrick17 is it a sandbox key or a live production key?

**Comment by kroitor** [comment]
@Merrick17 let us know if this does not help:

- https://github.com/ccxt/ccxt/issues/7554#issuecomment-686152859

**Comment by Merrick17** [comment]
My timestamp and the oen from the server are not sync , 
should I change my time settings ?

**Comment by kroitor** [comment]
@Merrick17 yes:

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

**Comment by Merrick17** [comment]
Hey sorry for being late , I've changed my time and it's the same issue

**Comment by kroitor** [comment]
@Merrick17 have you checked the keys? Is it a sandbox key or a production key?
Have you read this issue: https://github.com/ccxt/ccxt/issues/7554#issuecomment-686152859 ?

**Comment by ttodua** [comment]
Update: from now, you can now directly add the parameter in any method (without need to set the headers in exchange initialization properties), like:

`createOrder/FerchBalance( ..., ...,  params:{ "FTX-SUBACCOUNT":"mySubAcc"} ) `   

Note: `FTXUS-SUBACCOUNT` for ftx.us users.
