### ISSUE TITLE
Add support for OKEX Futures position replication 

### ISSUE THREAD

**Issue by rac1964** [ccxt/ccxt#8635]
It appears that okex only supports the private watch method watchBalances - which is not sufficient to fully replicate my futures position including entry prices.  It looks like the REST call fetch_my_trades() also does not work for (OKEX  error :"'okex' object has no attribute 'futureGetFills'")

Is there an alternative recommended method to get current futures position including entry/avg price?

**Comment by kroitor** [comment]
Try `fetch_positions()` or `fetch_position()`, those methods are a work in progress, but they should be available in the most recent version of CCXT. Let us know if that does not help. Feel free to reopen this issue or just ask further questions if anything.

**Comment by kroitor** [comment]
P.S. You can also call any OKEX endpoint using implicit API methods as explained in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods
- https://github.com/ccxt/ccxt/tree/master/examples

**Comment by rac1964** [comment]
I used the implicit methods and they worked. Thanks

**Comment by kroitor** [comment]
@rac1964 thanks for your feedback!
