### ISSUE TITLE
Prices format from fetch_ohlcv

### ISSUE THREAD

**Issue by AGTGreg** [ccxt/ccxt#8636]
Hi,
Is there a way to get the prices form fetch_ohlcv in a format other than float? Floats are not a good fit for our analysis.
In the python-binance library we used to get those prices as strings which was really helpfull because we could do our own conversion to Decimals or Integers to do our analysis and also keep the original prices in strings for other tasks.
Is something like this possible in CCXT? Is there a work around?

Thank you in advance, and thanks for making this incredible library :)

**Comment by kroitor** [comment]
There's many ways to do it, you can override parse_ohlcv for example:

```Python
import ccxt

class MyBinance(ccxt.binance):
    def parse_ohlcv(self, ohlcv, market=None):
        #
        #     [
        #         1591478520000,
        #         "0.02501300",
        #         "0.02501800",
        #         "0.02500000",
        #         "0.02500000",
        #         "22.19000000",
        #         1591478579999,
        #         "0.55490906",
        #         40,
        #         "10.92900000",
        #         "0.27336462",
        #         "0"
        #     ]
        #
        return [
            self.safe_integer(ohlcv, 0),
            self.safe_string(ohlcv, 1),
            self.safe_string(ohlcv, 2),
            self.safe_string(ohlcv, 3),
            self.safe_string(ohlcv, 4),
            self.safe_string(ohlcv, 5),
        ]

exchange = MyBinance({
    'enableRateLimit': True,
    'parse_ohlcv': 
})

# ...
```

Let us know if that does not help.

**Comment by kroitor** [comment]
P.S. we are also working on a more convenient exchange-wide option to switch from floats to string representations here: 

- https://github.com/ccxt/ccxt/pull/8630
