### ISSUE TITLE
fetchOrder() for huobipro

### ISSUE THREAD

**Issue by tandazhi** [ccxt/ccxt#866]
PASTE_YOUR_TEXT_DESCRIPTION_HERE

- OS: unbutu 16
- Language: python
- CCXT version:  1.10.357
- Exchange: huobipro
- Method:fetchOrder()

```
COPYPASTE_YOUR_CODE_TO_REPRODUCE_THE_BUG_HERE
DO_NOT_DELETE_THE_BACKTICKS_AROUND_THE_CODE
```
>>> orderInfo = p.fetchOrder(order['id'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 803, in fetch_order
    raise NotSupported(self.id + ' fetch_order() is not implemented yet')
ccxt.base.errors.NotSupported: huobipro fetch_order() is not implemented yet

```
COPYPASTE_YOUR_VERBOSE_OUTPUT_HERE
https://github.com/kroitor/ccxt/wiki/Manual#troubleshooting
DO_NOT_DELETE_THE_BACKTICKS_AROUND_THE_OUTPUT
```

Is there any other method to get specific order infomation for huobipro?

Thanks!

**Comment by tandazhi** [comment]
using below code can get specific order infomation.
`p=ccxt.huobipro()
p.apiKey=''
p.secret=''
order=p.createLimitSellOrder('LTC/BTC', 1, 0.18)
response = p.privateGetOrderOrdersId({'id':order['id']})
orderInfo=p.parse_orders([response['data']], 'LTC/BTC', None, None)
`

**Comment by kroitor** [comment]
@tandazhi thank you! We will add it to the implementation of fetchOrder for Huobi Pro.

**Comment by atjason** [comment]
@kroitor @tandazhi  Seems this feature still not be implemented. Suggest to reopen this issue.

**Comment by runrun88** [comment]
OS: windows 10
Language: python
CCXT version: 3.7
Exchange: huobipro
Method:fetch_Order()

How Can I use  fetch_Order() in  huobi ?
I use this ::
self.huobi.fetch_order( self,order_result.id ) 
but Finds it is wrong.

Thanks very  much .

**Comment by kroitor** [comment]
@runrun88 see the answer here: https://github.com/ccxt/ccxt/issues/5237
