### ISSUE TITLE
kraken: symbol returned in fetchOrderBook doesn't always match requested pair

### ISSUE THREAD

**Issue by opub** [ccxt/ccxt#8662]
The Kraken Depth API for fetchOrderBook doesn't always return the same symbol pair that was requested. While the pair is correct the format might be different. e.g. requesting `AAVEUSD` but getting `AAVE\/USD` in the response. This then breaks the `kraken.fetchOrderBook` function because it tries to look up the attribute by the symbol. 

I have contacted their support regarding this. Their response:

> It looks like you are seeing the WebSocket pair name on the REST API endpoint.
> 
> https://api.kraken.com/0/public/AssetPairs?pair=AAVEUSD
> 
> {"error":[],"result":{"AAVEUSD":{"altname":"AAVEUSD","wsname":"AAVE\/USD","aclass_base":"currency","base":"AAVE","aclass_quote":"currency","quote":"ZUSD","lot":"unit","pair_decimals":2,"lot_decimals":8,"lot_multiplier":1,"leverage_buy":[],"leverage_sell":[],"fees":[[0,0.26],[50000,0.24],[100000,0.22],[250000,0.2],[500000,0.18],[1000000,0.16],[2500000,0.14],[5000000,0.12],[10000000,0.1]],"fees_maker":[[0,0.16],[50000,0.14],[100000,0.12],[250000,0.1],[500000,0.08],[1000000,0.06],[2500000,0.04],[5000000,0.02],[10000000,0]],"fee_volume_currency":"ZUSD","margin_call":80,"margin_stop":40,"ordermin":"0.05"}}}
> 
> This is probably a side effect of the upcoming symbol changes. The WebSocket symbol version should only be returned when the assetVersion parameter is enabled:
> $ ./krakenapi Depth pair=xbtusd count=5 assetVersion=1
> 
> {"error":[],"result":{"BTC\/USD":{"asks":[["56143.30000","0.537",1615925880],["56145.00000","0.400",1615925877],["56145.40000","0.357",1615925878],["56148.20000","0.713",1615925878],["56149.50000","0.355",1615925877]],"bids":[["56139.80000","0.400",1615925880],["56138.50000","0.016",1615925880],["56138.00000","1.000",1615925880],["56134.40000","0.390",1615925880],["56133.80000","0.005",1615925878]]}}}
> The assetVersion is a new and undocumented parameter. The purpose for it is to allow our clients to use the 'same' pair symbol for each API (REST, WebSocket, ect).
> 
> This will also allow us to continue to support the legacy version of our pair names.

- OS: Windows 10
- Programming Language version: Node v14.16.0
- CCXT version: 1.43.25

The results are not consistent but this code will eventually reproduce it. It typically takes 200-300 requests before one fails.
```
    const exchange = new ccxt['kraken']({ rateLimit: 600, enableRateLimit: true });
    const markets = await exchange.loadMarkets();
    exchange.verbose = true;

    let count = 0;
    while(true) {
        for (const m of Object.values(markets)) {
            try {
                if(m.active && !m.darkpool) {
                    console.log('fetch', count++, m.symbol);
                    await exchange.fetchOrderBook(m.symbol);
                }
            }
            catch(e) {
                console.error(e, e.stack);
                process.exit(count);
            }
        }
    }
```

Here is the resulting error
```
TypeError: Cannot use 'in' operator to search for 'bids' in undefined
    at kraken.parseOrderBook (C:\Projects\node_modules\ccxt\js\base\Exchange.js:940:38)
    at kraken.fetchOrderBook (C:\Projects\node_modules\ccxt\js\kraken.js:517:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async C:\Projects\test.js:24:21 TypeError: Cannot use 'in' operator to search for 'bids' in undefined
```

Here is the verbose output from one of the failures.
```
handleRestResponse:
 kraken GET https://api.kraken.com/0/public/Depth?pair=AAVEUSD 200 OK 
Response:
 {
  'Cache-Control': 'public,max-age=4,smaxage=4',
  'Cf-Cache-Status': 'EXPIRED',
  'Cf-Ray': '631096ddeb4a9222-EWR',
  'Cf-Request-Id': '08de3c9eae00009222b5a69000000001',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Type': 'application/json; charset=utf-8',
  Date: 'Tue, 16 Mar 2021 20:04:13 GMT',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Set-Cookie': '__cfduid=dfc7e2d4904b3ed189b48a1bc79f5f2181615925053; expires=Thu, 15-Apr-21 20:04:13 GMT; path=/; domain=.kraken.com; HttpOnly; SameSite=Lax, __cf_bm=c1c90d5493276dfb5bfd6c3cc45fc00b2eea4c9d-1615925053-1800-AfSwv3HDLCC1cXNAmjLI3QKN2L+5/KtJwNlyVE0vKCvoXf9uXqbaBa9NFzePbpQ18LIWRPD2N0i6dXqxXVjretY=; path=/; expires=Tue, 16-Mar-21 20:34:13 GMT; domain=.kraken.com; HttpOnly; Secure; SameSite=None',
  'Strict-Transport-Security': 'max-age=15768000',
  'Transfer-Encoding': 'chunked',
  Vary: 'Accept-Encoding'
} 
 {"error":[],"result":{"AAVE\/USD":{"asks":[...], "bids":[...]}}}
```

If this line in `kraken.js`
```
const orderbook = this.safeValue (result, market['id']);
```
is replaced with this then the error condition would be addressed
```
const orderbook = this.safeValue (result, Object.getOwnPropertyNames(result)[0]);
```
but I'm new to CCXT and I don't know if this is safe with how CCXT generates the other language implementations.

**Comment by kroitor** [comment]
@opub thx for reporting, we will fix this asap!

**Comment by kroitor** [comment]
@opub what is your version of CCXT?

I've tried this script with the most recent version, it went 3 or 4 cycles over all pairs (that is 400+ pairs) without an error:

```JavaScript
const ccxt = require ('ccxt');

console.log ('CCXT Version:', ccxt.__version__)

async function main () {
    const exchange = new ccxt['kraken']({ rateLimit: 600, enableRateLimit: true });
    const markets = await exchange.loadMarkets();
    exchange.verbose = true;

    let count = 0;
    while(true) {
        for (const m of Object.values(markets)) {
            try {
                if(m.active && !m.darkpool) {
                    console.log('fetch', count++, m.symbol);
                    await exchange.fetchOrderBook(m.symbol);
                }
            }
            catch(e) {
                console.error(e, e.stack);
                process.exit(count);
            }
        }
    }
}

main ()
```

It is still running, I will keep an eye on it.

**Comment by kroitor** [comment]
Ok, I've reproduced it after a few cycles. Working on a fix now.

**Comment by kroitor** [comment]
Alright, I've pushed a fix, please, let us know if you have issues with after upgrading your version of CCXT to 1.43.56+, the new build will arrive in ~20 minutes. Thx again for your feedback!
