### ISSUE TITLE
How to create a close order in Bybit BTC/USDT market??

### ISSUE THREAD

**Issue by moki2744** [ccxt/ccxt#8665]
- OS: Window10
- Programming Language version: Python 3.8
- CCXT version: latest version

```
What function should i use to make the close order in Bybit BTC/USDT market??
Open Long : create_limit_buy_order('BTC/USDT', Qty, Price) 
Open Short : create_limit_sell_order('BTC/USDT', Qty, Price)
Close Short : ??????
Close Long : ??????
```

**Comment by Kalelv45** [comment]
You mean that you don't want an hedge position? but You want to close a position and open a new one?

**Comment by moki2744** [comment]
For example,
If I have 3bit long position but I want to make 2bit long position.
Then, I have to make 1bit close order for the 3bit long position. (Position : 2bit Long → Good!!)
But, If I use the create_limit_sell_order, it makes the new 1bit short position and 3bit long position is still alive.
(Position : 3bit Long + 1bit Short  → Bad!!)

I'm not good at English,, I hope you to understand my word

**Comment by kroitor** [comment]
@moki2744 let us know if this does not help:

```Python
# for Bybit

exchange.load_markets()
# exchange.verbose = True  # uncomment for debugging
params = {
    'reduce_only': True,
    'close_on_trigger': True,
}
order = exchange.create_order('ETH/USDT', 'limit', 'sell', amount, price, params)
```

All supported params: https://bybit-exchange.github.io/docs/linear/#t-introduction

**Comment by moki2744** [comment]
Thanks, it works very well!!!

**Comment by kroitor** [comment]
@moki2744 thx for your feedback!
