### ISSUE TITLE
Bybit how not to create a hedge position.

### ISSUE THREAD

**Issue by Kalelv45** [ccxt/ccxt#8666]
- OS: OS Mojave
- Programming Language version: python 
- CCXT version: 1.41+ 

let's say I'm short 0.05 contracts. I want to go long 0.05, so I create an order of size = 0.05 + 0.05 (one for closing the existing one and one to open the new position). 
On bybit by default on the USDT futures contract it creates a hedge position. 
What do I have to insert inside the params= so that it close the existing one. Thanks. 
```python 
size = 0.1
binance.create_order(symbol='ETH/USDT', type='limit', side='buy', amount= size, price= 1700, params=????? )
```

**Comment by moki2744** [comment]
Is there any way to solve this problem?? in current ccxt version?? T-T

**Comment by kroitor** [comment]
@Kalelv45 is your question about Binance or Bybit? I'll post the examples here.

**Comment by kroitor** [comment]
@moki2744 yes, there is a way to solve this problem using params overrides, as documented in the Manual, i will write and push the examples asap.

**Comment by kroitor** [comment]
Let us know if this duplicate issue does not answer your question:

- https://github.com/ccxt/ccxt/issues/7713#issuecomment-707183873

**Comment by kroitor** [comment]
```Python
exchange.load_markets()
exchange.verbose = True
params = {
    'reduce_only': True,
    'close_on_trigger': True,
}
order = exchange.create_order("ETH/USDT", "limit", "sell", amount, price, params)
```

**Comment by Kalelv45** [comment]
@kroitor It solves some of the problems. But not completely. Let me explain. The problem is on by bit. 

I have a strategy that will post long and short order at the same time on the order book. This implies that I have no idea which order will be filled first.  
I cannot use close_on_trigger cause it will say that I have not an open position to close.  
I would like to know if there is a params that works as this:
If you do not have an open position, open a new position, if you have an open position on the opposite side, close that position. 
Hope it is clear enough, and I was able to explain myself.

**Comment by kroitor** [comment]
@Kalelv45 `close_on_trigger` is for stop-orders only, if you're using regular limit orders, then just remove `close_on_trigger`, and keep `reduce_only`. Let me know if that does not help.

**Comment by Kalelv45** [comment]
@kroitor 
The problem is that with reduce only I must have an open position to post that kind of order. 
Instead using a market making strategy on other exchanges I have always limit orders in both sides that automatically cancel each other when both are filled. 
Now I find my self wanting to use the same strategy also on by bit, but how can I post orders that are not hedging order when I have an open position of zero. 

let's price of eth is 1800 I want to post in the next hour a sell order of 0.1 at price + 1$, and a buy order of 0.1 at price -1$.
Now during this hour both order got filled what kind of setting should I have had in place to make sure that in the next hour my open position is 0. (like in any other exchange)?????

**Comment by freegab** [comment]
> @Kalelv45 `close_on_trigger` is for stop-orders only, if you're using regular limit orders, then just remove `close_on_trigger`, and keep `reduce_only`. Let me know if that does not help.

Using bybit, how can I close a short/long at market price? I've tried 'reduce_only': True and 'close_on_trigger': True but it doesn't close my open orders, it just keeps adding to the position

**Comment by hibana2077** [comment]
Hello , I have same question , can you solve this question ?

**Comment by mpcref** [comment]
For anyone looking for the answer...
You need to specify one-way mode like this:
```js
const oneWayMode = { position_idx: 0 };
bybit.createOrder(symbol, type, side, amount, price, oneWayMode);
```

**Comment by Utayaki** [comment]
> For anyone looking for the answer... You need to specify one-way mode like this:
> 
> ```js
> const oneWayMode = { position_idx: 0 };
> bybit.createOrder(symbol, type, side, amount, price, oneWayMode);
> ```

Doesn't work 
BadRequest: bybit {"retCode":10001,"retMsg":"position idx not match position mode","result":{},"retExtInfo":{},"time":1675856993985}

**Comment by mpcref** [comment]
@Utayaki make sure your account is configured for one-way mode.
