### ISSUE TITLE
how to use websocket via ccxt accessing binance?

### ISSUE THREAD

**Issue by franklee00** [ccxt/ccxt#8667]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: mac OSX
- Programming Language version: Python 3.9
- CCXT version: 1.4.3

```
REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS
```

```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
```

**Comment by kroitor** [comment]
Hi!

You have to follow the Manual:

1. Install CCXT Pro: https://github.com/ccxt/ccxt/wiki/ccxt.pro.install
2. Use as documented in the Manual and in the examples:

- CCXT Manual: 
    - https://github.com/ccxt/ccxt/wiki
    - https://github.com/ccxt/ccxt/wiki/Manual
    
- CCXT Pro Manual:
    - https://github.com/ccxt/ccxt/wiki/ccxt.pro.manual
    
- Examples:
    - https://github.com/ccxt/ccxt/tree/master/examples
    - https://github.com/ccxt/ccxt/tree/master/examples/ccxt.pro
    
Let us know if that does not answer your question. Feel free to reopen it or just ask further questions if any.
