### ISSUE TITLE
New Exchange: https://p2pb2b.io/ 

### ISSUE THREAD

**Issue by cryptonit** [ccxt/ccxt#8669]
please add this exchange as supported
link to api doc: https://github.com/P2pb2b-team/p2pb2b-api-docs/blob/master/api-doc.md

**Comment by kroitor** [comment]
Duplicate:

- https://github.com/ccxt/ccxt/issues/4158
- https://github.com/ccxt/ccxt/pull/6018
- https://github.com/ccxt/ccxt/issues/5277
