### ISSUE TITLE
Unable to combine stop-loss order and take-profit order on Binance futures

### ISSUE THREAD

**Issue by t0mm4rx** [ccxt/ccxt#8673]
Hi! First of all, a huge thanks for your awesome work.

I would like to know if anyone have succeed to combine stop_market and take_profit_market orders on Binance Futures.

For now I have:
```python
# We open a long position
params = {
   'timeInForce': 'GTC'
}
self.client.create_order(self.bot.ticker, 'LIMIT', 'buy', qty, price, params)

# We add a stop loss for this position with 'closePosition'='true'
params = {
    'stopPrice': stop_loss_price,
    'closePosition': 'true'
}
self.client.create_order(self.bot.ticker, 'STOP_MARKET', 'sell', qty, stop_loss_price, params)

# We add a take profit for this position with 'closePosition'='true'
params = {
    'stopPrice': take_profit_price,
    'closePosition': 'true'
}
self.client.create_order(self.bot.ticker, 'TAKE_PROFIT_MARKET', 'sell', qty, take_profit_price, params)
```

This creates successfully a new order with SL/TP:
<img width="459" alt="Screenshot 2021-03-19 at 14 27 19" src="https://user-images.githubusercontent.com/23388480/111787618-7354cb00-88bf-11eb-9551-4371266b83dc.png">

This code is working for individual stop:
- if the stop loss is hit first, the position is successfully closed, but the the take profit won't be cancelled. If the price goes up, it will trigger it as a short position.
- if the take profit is hit first, the position is successfully closed, but the the stop loss won't be cancelled. If the price goes down, it will trigger it as a short position.

What would be the normal behaviour is that when one of the two stops is hit, the other one is cancelled as well.
Maybe I miss some parameter?
Thanks, and I understand it might be on Binance side.

- OS: MacOS
- Programming Language version: Python3
- CCXT version: 1.43.74

**Comment by kroitor** [comment]
Basically, the short answer is: Binance has TP+SL orders on the web interface, but not on the API yet. The API allows TP or SL, but not TP+SL:

- https://www.reddit.com/r/binance/comments/l4mpvc/tpsl_order_via_api/
- https://dev.binance.vision/t/ccxt-tp-sl-order/636

This is not an issue with CCXT, it's just not available from the API yet.

Let us know if that does not answer your question.

**Comment by t0mm4rx** [comment]
Ok, I implement a custom cancel order so.
Thank you for the clear and fast response.
