### ISSUE TITLE
KuCoin create order by quote amount not working?

### ISSUE THREAD

**Issue by frzsombor** [ccxt/ccxt#8674]
When I try to create a new market buy/sell order on KuCoin by providing the quote amount using the `quoteAmount` parameter, like this:

```
kucoin.createOrder(symbol, 'market', 'buy', (void 0), (void 0), {
    'quoteAmount': value
});
```

I receive the following error [[here]](https://github.com/ccxt/ccxt/blob/4d44ea37047db5833230d0aa5c89f43dcce430aa/js/kucoin.js#L845):
`TypeError: Cannot read property 'toString' of undefined`.

I saw that this has been implemented more than a year ago in #6035, but I think there is a problem with that:

```
if (this.safeValue (params, 'quoteAmount')) {
    // used to create market order by quote amount - https://github.com/ccxt/ccxt/issues/4876
    request['funds'] = this.amountToPrecision (symbol, amount);  //<- ERROR! 'amount' used here accidentally instead of value of 'quoteAmount'?
} else {
    request['size'] = this.amountToPrecision (symbol, amount);
}
```

---

- Programming Language version: Node.Js v14.15.5
- CCXT version: v1.43.71
- CCXT Pro version: v0.6.9

**Comment by kroitor** [comment]
@frzsombor please, upgrade to version 1.43.77 (the new build will arrive in ~20 minutes) and supply `cost` or `funds`:

```
kucoin.createOrder(symbol, 'market', 'buy', (void 0), (void 0), {
    'funds': 123.45
});
```

Let us know if that does not help.

**Comment by frzsombor** [comment]
Thanks for the quick help!

Unfortunately I'm still getting an error, now:
`Error: Balance insufficient!`

A few things that I've found while debugging:
- [This line](https://github.com/ccxt/ccxt/blob/1.43.77/js/kucoin.js#L851) seems to override the function of [this line](https://github.com/ccxt/ccxt/blob/1.43.77/js/kucoin.js#L846) causing the formatted precision to be "reverted" to the original length - and I think this causes the error.
- I'm wondering: When I'm trying to create a buy order on a XXX/YYY pair and have 0.00066907 'YYY' and want to use it all, the library truncates the amount to 0.0006. However, when I edited the value before sending it to the exchange to 0.000668, it worked. But, when I entered 0.000669 or provided more digits, it failed. Why? I know there are precision related limits, but if 0.000668 succeeds, and I have 0.00066907 on my account, why 0.000669 fails?
- I think you maybe forgot [this part](https://github.com/ccxt/ccxt/blob/1.43.77/js/kucoin.js#L883) when you changed `quoteAmount` to `cost` and `funds`.
- Also isn't changing `quoteAmount` to `cost` and `funds` considered a breaking change?

**Comment by kroitor** [comment]
@frzsombor thx for your feedback!

> This line seems to override the function of this line causing the formatted precision to be "reverted" to the original length - and this causes the error.

Pushed a fix for that.

> I'm wondering: When I'm trying to create a buy order on a XXX/YYY pair and have 0.00066907 'YYY' and want to use it all, the library truncates the amount to 0.0006. However, when I edited the value before sending it to the exchange to 0.000668, it worked. But, when I entered 0.000669 or provided more digits, it failed. Why? I know there are precision related limits, but if 0.000668 succeeds, and I have 0.00066907 on my account, why 0.000669 fails?

It may be related to this: https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits

> I think you maybe forgot this part when you changed quoteAmount to cost and funds.

Yep, fixed that.

> Also thinking about others: isn't changing quoteAmount to cost and funds considered a breaking change?

It is a breaking change, but we are unifying everything under this same schema.

**Comment by frzsombor** [comment]
Unfortunately still not working, getting the same "Error: Balance insufficient!" error.

Now, it looks like the new [costToPrecision](https://github.com/ccxt/ccxt/blob/1.43.78/js/kucoin.js#L843) leaves the `request['funds']` at 8 number length precision (`0.00061202`), but KuCoin only accepts 5(-6?) as I found [above](https://github.com/ccxt/ccxt/issues/8674#issuecomment-803033289).

And this is actually strange, because when I've checked `this.markets[symbol].precision` it showed `precision: {amount: 4, price: 8}`, for the symbol, so I don't understand the problem. Is KuCoin giving bad market data or `costToPrecision` is used accidentally instead of `amountToPrecision`/`priceToPrecision`?

**Comment by kroitor** [comment]
@frzsombor 

> so I don't understand the problem. Is KuCoin giving bad market data or costToPrecision is used accidentally

The problem is that by logical reasoning `funds` should accept quote cost precision, but it still accepts base precision only. I've pushed another fixup, please let me know if you still have this issue with 1.43.80, it will be available in ~20 minutes.
