### ISSUE TITLE
get funding rates history for ftx

### ISSUE THREAD

**Issue by linklee** [ccxt/ccxt#8676]
OS windows
Python 3x
hello I want to calc how much did I pay in funding fees  for past month on ftx exchange
https://prnt.sc/10q4go8

How can I do this?

(used some google and some search) still don't get it

**Comment by kroitor** [comment]
You can do that using implicit methods as described in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

This way you can call all API endpoints available from the underlying exchange.

Check this example:

- https://github.com/ccxt/ccxt/blob/master/examples/py/ftx-funding-payments.py

Let us know if that does not answer your question.
