### ISSUE TITLE
Use in a Vue webpack poject

### ISSUE THREAD

**Issue by lucacalcaterra** [ccxt/ccxt#8677]
Hi,

i'm quite bad in webpack config, i would ask how i can import ccxt  in a vue webpack 5 project using.

Thanks !

**Comment by kroitor** [comment]
Hi!

Does this answer your question:

- https://www.google.com/search?q=ccxt+vue

There are some examples of vue-apps using CCXT:

- https://github.com/MoiOcanas/vue-ccxt
- https://github.com/kireerik/adonuxt-ccxt-example
