### ISSUE TITLE
C-CEX: User-Agent Required

### ISSUE THREAD

**Issue by hassiweb** [ccxt/ccxt#868]
When using the API of C-CEX, the User-Agent would be required. Would you please fix the code?

Specifically, I tried the public and/or private APIs of C-CEX on Python, but the C-CEX server returns a message as follow: 

>The owner of this website (c-cex.com) has banned your access based on your browser's signature (3ce371f02fba6ad7-ua48).

I tried some ways to fix it, then it seems it would be okay to only modify `userAgent` (the value does not matter) in `exchange.py`.

P.S. thank you very much for developing this kind of very useful API wrapper.

**Comment by kroitor** [comment]
@hassiweb, you don't need to change `exchange.py`, just set the userAgent property to any string you want.

```
ccex = ccxt.ccex ()
ccex.userAgent = ccex.userAgents['chrome'];
```

or

```
ccex = ccxt.ccex ({
    'userAgent': 'YOUR_USERAGENT_STRING',
})
```

Let me know if this answers your question or not.

**Comment by hassiweb** [comment]
Thank you for your quick response and giving the simple solution! I'll try it soon.

**Comment by jjhesk** [comment]
@kroitor looks like that is has the cloudflare block again with the 1.10.804

**Comment by jjhesk** [comment]
@kroitor can this one adding to the default options. { cloudflareheader:true }
```javascript
exchange.headers = await scrapeCloudflareHttpHeaderCookie (exchange.urls.www)
```

**Comment by kroitor** [comment]
@jjhesk we will consider adding this, however, it's a very heavy dependency...
