### ISSUE TITLE
Bithumb BTC market fetchTicker error

### ISSUE THREAD

**Issue by Jonggu-lee** [ccxt/ccxt#8680]
Hello.

I am using Python 3.9.2 ccxt 1.43.27

There is small error in bithumb (exchange)  fetchTicker function.
The problem is that fetchTicker function always load KRW market, not BTC market.

When I command :

bithumb = ccxt.bithumb({
    'verbose' : True,
})
bithumb.fetchTicker('ETH/BTC')

fetchTicker get data from
https://api.bithumb.com/public/ticker/ETH

In order to load the BTC market, data must be received from the following sources :
https://api.bithumb.com/public/ticker/ETH_BTC

https://api.bithumb.com/public/ticker/ETH
is KRW market data, and it is same as
https://api.bithumb.com/public/ticker/ETH_KRW

Thank you.

**Comment by kroitor** [comment]
Duplicate:

- https://github.com/ccxt/ccxt/issues/8236
- https://github.com/ccxt/ccxt/issues/2694

Let us know if the above does not answer your question.
