### ISSUE TITLE
What is the difference between currency_to_precision() and amount_to_precision() ?

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#8685]
Hello,

I try to figure out what is the difference between the two because amount is usually an amount of currency on spot markets. So `amount_to_precision()` can be used to properly format the precision of an order but could you tell me when one should use `currency_to_precision()` ?

Thank you,

**Comment by kroitor** [comment]
Hi!

The difference is the first argument, one is for market trading precision, the other is for currency funding precision.

```Python
exchange.amount_to_precision(symbol, amount)  # ccxt uses this for orders
                           # ↓ vs ↑
exchange.currency_to_precision(code, amount)  # ccxt uses this for withdrawals, transfers, loans
```

```Python
exchange.amount_to_precision('BTC/USDT', 123.4567890)  # format amount to BTC precision for orders
exchange.currency_to_precision('BTC', 123.4567890)  # format to BTC precision for withdrawals, transfers, loans...
```

Let us know if that does not answer your question.
