### ISSUE TITLE
How to buy cryptocurrency with all BTC in my wallet

### ISSUE THREAD

**Issue by Xaytek** [ccxt/ccxt#8686]
Windows Python 3.6.5 ccxt 1.43.87

I want to buy on the binance exchange, for example, the DEGO cryptocurrency for BTC and want to buy with all the BTC what i have, could not find such a method.
Example I have 1 BTC and I want to buy DEGO on 1 bitcoin indicating only the price and how much BTC i have like

midle_of_prise = 0.0000234
amountBTC = 1
order = exchange.create_order("DEGO/BTC", 'limit', 'buy', amount, midle_of_prise, params)

**Comment by adamwirski** [comment]
I would calculate it.
amount = amountBTC / midle_of_prise

**Comment by kroitor** [comment]
@Xaytek https://github.com/ccxt/ccxt/search?q=binance+quoteOrderQty&type=issues ← let us know if that does not answer your question.
