### ISSUE TITLE
Deribit invalid credentials

### ISSUE THREAD

**Issue by hubavka** [ccxt/ccxt#8696]
I use the same credentials with another wrapper and can connect fine, but getting this error with ccxt private calls

- OS: MAC
- Programming Language version: node v14.5.0
- CCXT version: 1.43.77

```
exchange = new ccxt.deribit({
      'apiKey': 'XXXX',
      'secret': 'XXXX',
      'enableRateLimit': true,
  })

const deribittradesccxt = await exchange.privateGetGetUserTradesByCurrency(currency = 'BTC');
```

```
(node:39360) UnhandledPromiseRejectionWarning: AuthenticationError: deribit {"jsonrpc":"2.0","error":{"message":"invalid_credentials","code":13004},"testnet":false,"usIn":1616444742558343,"usOut":1616444742558590,"usDiff":247}
```

**Comment by kroitor** [comment]
@hubavka in certain cases, the keys cannot be used interchangeably across different software, cause some software will screw your nonce as documented in the Manual: 

- https://github.com/ccxt/ccxt/wiki/Manual#authentication
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

Try a fresh new keypair in CCXT first. Then retry it in CCXT. Then try it with the other software. Then retry with CCXT again. If it fails with CCXT after your other software, then the other software is setting the nonce too high, making your key unusable with the other libs.

**Comment by frosty00** [comment]
Hi @hubavka 

The reason for your error is that your code is wrong

```
const deribittradesccxt = await exchange.privateGetGetUserTradesByCurrency(currency = 'BTC');
```

instead pls try

```
console.log (await exchange.privateGetGetUserTradesByCurrency({ currency :'BTC' }))
```

or 

```
console.log (await exchange.fetchMyTrades ('BTC'))
```

**Comment by hubavka** [comment]
> console.log (await exchange.privateGetGetUserTradesByCurrency({ currency : 'BTC' }))

This worked. Thank You!
