### ISSUE TITLE
Modify SL/TP of Position

### ISSUE THREAD

**Issue by psywolf85** [ccxt/ccxt#8705]
Hi, thank you for your wonderful work!

Just a small question. Is it possible in a prebuilt way to modify a position? SL and TP to be accurate.
I couldn't find anything in the docs and after my first day with the software, I'm getting tired and would appreciate if you can give me a hint.

Best Regards

**Comment by kroitor** [comment]
Hi! This aspect is not fully unified yet, so it will depend on the exchange in question. In general, you can do everything that the exchanges' APIs allow you to do (CCXT supports all endpoints), with implicit methods as described here:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

Can you share a bit more details? Namely, this:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by ttodua** [comment]
The issue has not got any follow-up from OP, so I'll close this one. However, to add small note for future readers:
- to modify SL/TP or **any order** you can just use `editOrder` method.  The logic can also be the following:
```
exchange = new ccxt.binance();
// exchange['options']['defaulType']= 'swap'; //swap, future or whatever
orders = await exchange.fetchOpenOrders ('BTC/USDT');
// then iterate through open orders to determine which are your stoploss/profittarget ones, and note their order 'id'
// then...
result = await exchange.editOrder (____the_order_id_here____, symbol, type, side, amount, price , params );
```
something like this, depending your parameters or logic.
Let us know if you find any issues in CCXT.

**Comment by Sfuarf** [comment]
Hi there, 

I have been trying to follow along with the suggestions in this post and the associated ones too.

I have found the order_id of the stop loss order as per your suggestion using the "orderType": "conditional".

However, when I go to use this in the ByBit Edit order function

`response = exchange.edit_order(id=order_id, symbol=symbol, side = side, type='Market', price=0.6100)`

I get the following error:

`bybit {"ret_code":30005,"ret_msg":"stop_order_type[StopLoss] cannot replace price[6100]","ext_code":"","ext_info":"","result":null,"time_now":"1664289656.183022","rate_limit_status":99,"rate_limit_reset_ms":1664289656181,"rate_limit":100}`

Any help would be greatly appreciated! 

Thanks!
