### ISSUE TITLE
How to get the real-time funding rate at Binance future ?

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#8707]
Hello,

I'm trying to get the [real time funding rate](https://www.binance.com/en/futures/funding-history/0) for Binance and everything I found is for the historical funding rate at `/fapi/v1/fundingRate`. It seems there is no REST endpoint for the real time data but could you tell me if it's possible with Websocket and CCXT Pro ?

Thank you,

**Comment by uncentral** [comment]
Dear Kinzowa,

The endpoint for the realtime funding rate for USDT margined futures on Binance is fapi/v1/premiumIndex. 

So in cctx you would need to call market.fapiPublic_get_premiumindex()

good luck,

**Comment by Kinzowa** [comment]
Thank you @uncentral
