### ISSUE TITLE
Best way to get an order outcome?

### ISSUE THREAD

**Issue by beniloew** [ccxt/ccxt#871]
So, i tried to use the order id in order to query for transactions corresponding to that id, but no success.
I was thinking about using the timestamp of the order and put it in the 'since' param when asking for transactions, and then walk over all transactions and check their order id.

Is there a better way?
Thanks!

**Comment by kroitor** [comment]
The order API is a work in progress, described here: https://github.com/kroitor/ccxt/wiki/Manual#querying-orders

In general there are several ways to check for the outcome of the order:

1. `fetchOrder()`, `fetchOrders()`, `fetchOpenOrders()`, `fetchClosedOrders()`
2. `fetchMyTrades()`, `fetchOrderTrades()`
3. Keep a local order cache and track balances
4 ....

Some of those methods may still miss their implementations for some exchanges, but we will unify the entire order API sooner or later. However, you can still access those endpoints with ccxt with a set of custom exchanges APIs built into the lib (described in the Manual). 

> i tried to use the order id in order to query for transactions corresponding to that id, but no success

You need to be much more specific, which exchange, which methods, maybe, paste your code snippet...

**Comment by beniloew** [comment]
Thanks for your answer.
The thing is, that orders status not always include the outcome of the deal.
If the order is closed, the outcome will sometimes be in the trade info.

Regarding the code, you are right. The thing is, is there a way of not
being specific about a specific exchange, but rather a generic way to get
that information?


On Dec 17, 2017 2:54 PM, "Igor Kroitor" <notifications@github.com> wrote:

The order API is a work in progress, described here:
https://github.com/kroitor/ccxt/wiki/Manual#querying-orders

In general there are several ways to check for the outcome of the order:

   1. fetchOrder(), fetchOrders(), fetchOpenOrders(), fetchClosedOrders()
   2. fetchMyTrades(), fetchOrderTrades()
   3. Keep a local order cache and track balances
   4 ....

Some of those methods may still miss their implementations for some
exchanges, but we will unify the entire order API sooner or later. However,
you can still access those endpoints with ccxt with a set of custom
exchanges APIs built into the lib (described in the Manual).

i tried to use the order id in order to query for transactions
corresponding to that id, but no success

You need to be much more specific, which exchange, which methods, maybe,
paste your code snippet...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ccxt/ccxt/issues/871#issuecomment-352253787>, or mute
the thread

**Comment by beniloew** [comment]
I guess that fetch_order_trades is what i'm looking for, but unfortunately
currently available for poloniex...
will send PR if i'll end up implementing it myself
Thanks again!

2017-12-17 14:54 GMT+02:00 Igor Kroitor <notifications@github.com>:

**Comment by kroitor** [comment]
> If the order is closed, the outcome will sometimes be in the trade info.

What *outcome* in particular do you mean? Most exchanges serve order history with output fee info, the amounts, the executed amounts, the fill-prices. You only need the trade info, if you want to calculate the totals precisely. However, this may still require some customization... 

> The thing is, is there a way of not being specific about a specific exchange, but rather a generic way to get that information?

The unified order API is being developed in CCXT just for that (but it's a work in progress, yes). I'd recommend to read the entire Manual, most of the info on custom and unified API is there.

> will send PR if i'll end up implementing it myself

Thanks so much! We welcome all contributions! Let us know if you have questions with that, we will be happy to assist. Please read this, if you decide to give it a try: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md

I would close this issue for now (if you don't mind). Feel free to reopen it if needed, or just ask questions, I'll respond asap.
