### ISSUE TITLE
New lib version returns strings, instead of floats

### ISSUE THREAD

**Issue by TomaszLakota** [ccxt/ccxt#8713]
Hi, just a quick bug report, new lib version `ccxt-1.44.30-py2.py3-none-any.whl` some methods return incorrect types at least for FTX exchange:
`account.fetchTicker(symbol, params={})`
`account.fetch_trades(symbol, since=start)`
I'm getting strings instead of floats for prices, sizes etc., it was working fine just an hour ago and it still works in colab notebook, where lib version is `ccxt-1.44.28-py2.py3-none-any.whl`.

**Comment by kroitor** [comment]
@TomaszLakota hi! Please, paste your verbose output: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by frosty00** [comment]
@TomaszLakota we've just merged #8628 that's why

**Comment by frosty00** [comment]
also are you looking inside of `response['info']` by any chance?

**Comment by TomaszLakota** [comment]
Yes, I am. I've set verbose to true and I can see that there are floats in the HTTP response.

**Comment by kroitor** [comment]
@TomaszLakota we are in the process of adding the support for arbitrary-precision fixed-point math, that mostly involves strings. CCXT will return the tickers and the trades as described in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#ticker-structure
- https://github.com/ccxt/ccxt/wiki/Manual#trade-structure-1

↑ The values around `info` will be floats.
You can also switch that substitution like so:

```Python
exchange = ccxt.ftx({
    'enableRateLimit': True,
    'quoteJsonNumbers': False,  # ←--------- this way, though, not recommended.
})
```

Let us know if the above does not answer your question. Feel free to reopen this issue or just ask further questions if any.

**Comment by TomaszLakota** [comment]
Setting `'quoteJsonNumbers': False` worked, thanks

**Comment by kroitor** [comment]
@TomaszLakota ok, though, please be aware that this is not recommended, cause in financial terms, floats aren't safe, which is the main reason for our migration.

**Comment by tredondo** [comment]
>     * https://github.com/ccxt/ccxt/wiki/Manual#trade-structure-1

Just a note that the link above should be without `-1`.

What is the status of fixed point / big number support in the JS version of the library? #522 hasn't had an update since 2018?

**Comment by kroitor** [comment]
@tredondo

> What is the status of fixed point / big number support in the JS version of the library? #522 hasn't had an update since 2018?

We are actually working on it right now very actively, hope to add it soon: 

- https://github.com/ccxt/ccxt/pull/8628
- https://github.com/ccxt/ccxt/pulls?q=is%3Apr+precise+is%3Aclosed+
- https://github.com/ccxt/ccxt/pull/8630
- https://github.com/ccxt/ccxt/wiki/FAQ#whats-your-progress-on-adding-the-feature-foo-that-was-requested-earlier-how-do-you-do-implementing-exchange-bar
