### ISSUE TITLE
Beginner in Bitcoin

### ISSUE THREAD

**Issue by maha885** [ccxt/ccxt#8715]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

Hello, I am completely beginner in this so I want to know how to start ? Please help to aware me .

- OS:
- Programming Language version:
- CCXT version:

```
REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS
```

```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
```

**Comment by kroitor** [comment]
@maha885 hi! If you're completely new to Bitcoin, then there may be better places for learning the basics about cryptocurrencies and trading, this repository is mostly for advanced users who have already grown out of manual operations into the automation.

I'd start from here:

- https://www.google.com/search?q=what+is+bitcoin
- https://www.google.com/search?q=how+bitcoin+works
- https://www.youtube.com/results?search_query=what+is+bitcoin
- https://www.youtube.com/results?search_query=how+bitcoin+works

... and basically follow the links from there. Hope that helps.

**Comment by kroitor** [comment]
@maha885 you can find CCXT docs here:

- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/wiki/Manual

**Comment by maha885** [comment]
Thank you
