### ISSUE TITLE
OkcoinUSD withdraw

### ISSUE THREAD

**Issue by leoplct** [ccxt/ccxt#872]
Can you integrate withdraw with OkCoinUSD?

- OS: unix
- Language: JS
- CCXT version:
- Exchange: OkcoinUSD
- Method: Withdraw (to crypto address)

**Comment by kroitor** [comment]
Done in 1.10.395.

**Comment by leoplct** [comment]
Thank you!

I'm getting this error, but I cannot understand the reason and what params are missing

```
exchange.apiKey = process.env.OKCOINUSD_API_KEY
exchange.secret = process.env.OKCOINUSD_API_SECRET
exchange.password = process.env.OKCOINUSD_API_PASSWORD
...

  exchange.withdraw(

            currency_target,
            withdraw_amount,
            crypto_address,
            {'chargefee': chargefee }

          ).then(res => {
            console.log(res);
          }).catch(err => console.error("Withdrawing error: " + err))
```


`Withdrawing error: Error: okcoinusd {"result":false,"error_code":10000}`

**Comment by leoplct** [comment]
I found this solution. ?trade_pwd is not passed

          exchange_origin.withdraw(

            currency_target,
            withdraw_amount.toFixed(5),
            crypto_address,
            {'chargefee': chargefee, 'trade_pwd': process.env.OKCOINUSD_API_PASSWORD }

          ).then(res => {
            console.log(res);
          }).catch(err => console.error("Withdrawing error: " + err))

**Comment by kroitor** [comment]
@leoplct oh, missed it somehow... How did it pass my test then %) Anyway, I will fix it right away! Thank you so much for reporting!
