### ISSUE TITLE
Binance broker API

### ISSUE THREAD

**Issue by RusDyn** [ccxt/ccxt#8735]
Hi,

Is this possible to use broker methods on Binance?
Like this one:
POST /sapi/v1/broker/universalTransfer

https://binance-docs.github.io/Brokerage-API/Brokerage_Operation_Endpoints/#universal-transfer

**Comment by kroitor** [comment]
@RusDyn you will be able to call those endpoints via implicit methods as described in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods if you upgrade your version of CCXT to 1.44.71 in ~20 minutes. Thx for pointing it out!

**Comment by RusDyn** [comment]
Just checked. Works like a charm.

Thanks, @kroitor for the update.

**Comment by kroitor** [comment]
@RusDyn thx for your feedback!
