### ISSUE TITLE
change localhost to IP - Swagger

### ISSUE THREAD

**Issue by erichegit** [ccxt/ccxt#8736]
CCXT REST - 2.5.0

```
Server=http://localhost:3000/
```
How to change the Swagger URL - localhost is not working for me, since I need an IP-Address to get the calls working.
With Postman no issue - but I would like to use the "/explorer"

```
Server=http://192.168.1.10:3000/
```

**Comment by kroitor** [comment]
@erichegit please, forward your question here: https://github.com/ccxt-rest/ccxt-rest
