### ISSUE TITLE
Is it safe to use prices from the orderdepths directly in regard of price precision

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#8739]
OS: Windows Server 2019 Datacenter
Programming Language version: Node.js 15.3.0
CCXT version: 1.38.89
Exchange: All Exchanges
Method: precision and limits

Hello!

I have a question about the precision when it comes to prices for a symbol when creating limit and marketorders.

For example we can get the orderbook like below:
```
(async () => {
const exchange = new ccxt.bitfinex({ enableRateLimit: true, agent, 'timeout': 10000 });
const orderbook = await exchange.fetchOrderBook("ETH/BTC", 5);
console.log(orderbook);
})()
```
This gives a structure like this with price and volume per orderdepth:
```
    [ 0.030365, 7.76077035 ],
    [ 0.030366, 7 ],
    [ 0.030368, 0.069 ],
    [ 0.03037, 1.19718266 ],
    [ 0.030376, 12 ]
```

My question is how safe it would be to directly just use the price from any of the orderdepths when `createOrder(...)`
What I mean, would it be safe to just take a price without using the `exchange.decimalToPrecision` to round it to correct precision.

Would it be safe to just take the prices from the orderdepths from all exchanges or should one anyway use `exchange.decimalToPrecision` function for safety?

Thank you!

**Comment by kroitor** [comment]
@jackpotcityco Hi! It should be safe, CCXT will format those values according to exchange precision before sending them out. Let us know if you run into any issues with that.

**Comment by jackpotcityco** [comment]
Hi! Thank you, that is great. Then I will only focus on the precision for the amounts then.

Thank you for the help!
