### ISSUE TITLE
huobipro does not have market symbol ethusdt

### ISSUE THREAD

**Issue by rthickling** [ccxt/ccxt#8742]
- OS: Ubuntu 20.10
- Programming Language version: Python 3.8.6
- CCXT version: 1.45.40

```
import ccxt
eh = ccxt.huobipro()
sh = 'ethusdt'
mh = eh.market(sh)
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/richard/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 1869, in market
    raise BadSymbol('{} does not have market symbol {}'.format(self.id, symbol))
ccxt.base.errors.BadSymbol: huobipro does not have market symbol ethusdt
```

**Comment by kroitor** [comment]
Answered in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

**Comment by rthickling** [comment]
Great - thank you.  Sorry for the stupid question effectively.
So I just do: 
```
import ccxt
eh = ccxt.huobipro()
sh = 'ethusdt'
mh = eh.market(eh.markets_by_id[sh]['symbol'])
```
Thanks again!

**Comment by kroitor** [comment]
> So I just do:
> 
> ```
> import ccxt
> eh = ccxt.huobipro()
> sh = 'ethusdt'
> mh = eh.market(eh.markets_by_id[sh]['symbol'])
> ```

You can simply do this:

```Python
import ccxt
exchange = ccxt.huobipro({
    'enableRateLimit': True,  # required! https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
})
exchange.load_markets()  # https://github.com/ccxt/ccxt/wiki/Manual#loading-markets
market = exchange.market('ETH/USDT')
```

I would highly recommend reading the entire Manual from top to bottom – it will really save you a lot of time:

- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/wiki/Manual

**Comment by kroitor** [comment]
P.S. You might also want to check the examples: https://github.com/ccxt/ccxt/tree/master/examples

**Comment by rthickling** [comment]
Hi - thanks, and apologies.  I'm coming from the angle of _exchange_ symbols ("market ids") because I'm pulling data from the exchange's websockets.  Therefore it's their ids I start with.  I nevertheless want to use `ccxt` to give me the last traded price.  I didn't realise there was a normalised concept of "symbol" - though that stands to reason.
Thank you for your time - and I'm sorry I wasted a bit of it!
