### ISSUE TITLE
Is there a way to check if credentials can withdraw?

### ISSUE THREAD

**Issue by rueiwoqp** [ccxt/ccxt#8748]
I'd like to check if API credentials for an exchange have the authorization to withdraw before using them. Is it possible? I see that you can check if the exchange has the capability of withdrawing but I don't see a way to check the credentials without trying to withdraw something.

**Comment by kroitor** [comment]
Please, use the `exchange.checkRequiredCredentials()` / `echange.check_required_credentials()` base method.  That checks if the keys are set. However, if you want to check the permissions on the keys, then you can attempt a withdrawal and try-catch the exception that will be thrown on a lack of permissions.

There's no unified method to check permissions on the key yet (very few exchanges actually have this in their API), but for the exchanges that support this you can still do it with implicit API methods as described in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods

We will do our best to add this permission-checking-feature as soon as possible. Let us know if that does not answer your questions.
