### ISSUE TITLE
[Okex] api v5 released, v3 closed

### ISSUE THREAD

**Issue by krychla1** [ccxt/ccxt#8760]
Hello,
just want to notify you that okex has released v5 api, v3 is no longer available for new users. 
https://www.okex.com/academy/en/complete-guide-to-okex-api-v5-upgrade

Consider upgrade please.
Thank you.

**Comment by kroitor** [comment]
@krychla1 we are working on it, hope to deliver this week.

**Comment by adamwirski** [comment]
V5 seems much easier to work on and understand since it's using unified account mode. 
@kroitor is there any test version of ccxt for V5 okex that I can try, or what's the ETA? I don't know if I should retrieve my old account with V3 or juust wait couple of days for the update xD

**Comment by adamwirski** [comment]
According to https://www.okex.com/academy/en/complete-guide-to-okex-api-v5-upgrade : 
'REST authentication in API v5 is the same as in API v3 (i.e. sign in the request header).', so at least this part can be reused.

**Comment by amalcaraz** [comment]
Thanks for supporting this change!
How is it going? Will it be delivered soon?

**Comment by deceneucapital** [comment]
Hi Kroitor,

Any update when OKEx v5 integration will be completed and released?

**Comment by kroitor** [comment]
Hi! It's one of the topmost priorities rn, we will release it within a week or so, hopefully, this weekend.

**Comment by limulidae** [comment]
thank you for supporting v5 api.

**Comment by adamwirski** [comment]
Hello, what's the status, @kroitor ?

**Comment by Bit-Bag** [comment]
> Hi! It's one of the topmost priorities rn, we will release it within a week or so, hopefully, this weekend.

how about v5~bro?

**Comment by deerme** [comment]
> > Hi! It's one of the topmost priorities rn, we will release it within a week or so, hopefully, this weekend.
> 
> how about v5~bro?
This guy (https://github.com/quantmew/okex-py/blob/main/example_v5.py) has released an lib python3 for okex api v5, at least, it works for me for the basics (like getting balances and the order book), it serves as an option until ccxt has v5 version support.

**Comment by ishest** [comment]
is there any time estimation for the v5 release?

**Comment by kroitor** [comment]
We're working on it, will push within days.

**Comment by IIPoliII** [comment]
The V5 api doesn't work on 3commas, is it please possible to enable v3 api even for new users..
https://help.3commas.io/en/articles/3109057-okex-how-to-create-api-keys

**Comment by kroitor** [comment]
@IIPoliII no worries, we usually have a transition period. Apart from that in CCXT the APIs are unified. We will do our best to make switching from v3 to v5 as easy and as smooth as possible.

**Comment by wanghaogood** [comment]
Any updates on v5?

**Comment by adamwirski** [comment]
Let me answer (joke) on behalf of ccxt team: 'its one of our top priorities right now, will push within few days'

**Comment by ulexxander** [comment]
Really need v5 api support too 😄

**Comment by t13340033021** [comment]
okex is going to be baned by CCP. no worry

**Comment by zlex7** [comment]
Hey, just following up on earlier questions here - should we expect support for v5 soon?

**Comment by kroitor** [comment]
> Hey, just following up on earlier questions here - should we expect support for v5 soon?
Yes we are finishing it rn, and will finally push it very soon, it's within hours.

**Comment by zlex7** [comment]
great to hear, looking forward to seeing it later today!

**Comment by wanghaogood** [comment]
> > Hey, just following up on earlier questions here - should we expect support for v5 soon?
> 
> Yes we are finishing it rn, and will finally push it very soon, it's within hours.

Is CCXTPRO for OKEx v5 Websocket also ready?

**Comment by kroitor** [comment]
@wanghaogood the ws-version is still in progress, but it will follow soon after.

**Comment by zlex7** [comment]
So is this done? Just following up based on the given ETA - I need to decide whether to program my own client

**Comment by suspended** [comment]
Looking forward to seeing it later today!

**Comment by drsavant-pub** [comment]
@kroitor Hi, it seems there's a lot of interest in this update.  I'm also interested in this upgrade.  

I just want to say I appreciate all your hard work.  

Thank You!

**Comment by kroitor** [comment]
@drsavant-pub it's under `okex5` in the most recent version of CCXT. Your help testing it out is very much appreciated!

**Comment by drsavant-pub** [comment]
@kroitor Where would you like me to post the results of my tests?  Here?

**Comment by kroitor** [comment]
@drsavant-pub yes, plz post here or, alternatively, just open a new issue if it's more convenient to you – that would really help speed it up!

**Comment by drsavant-pub** [comment]
@kroitor 

- OS: Win 8.1
- NodeJS:  v14.15.4
- ccxt:  v1.50.84

### Here are the methods I've tested so far:
- fetchTicker
- fetchStatus
- fetchDepositAddress (reports an old address for TRX but I don't believe this is an issue w/ccxt)

**These all seem to work fine.**

### There Are Issues Obtaining The Balance:

- exchange.fetchBalance() **works fine!  It retrieves the  balances in the spot/trading account**
- however, exchange.accountGetWallet() (used to obtain the wallet/funding account balance) is reported as a function in ccxt (okex5 implicit functions), but when you try to run it, it says, "accountGetWallet is not a function".  I also tried: accountGetWalletCurrency() and getAssetValuation() the same error.  I'm not sure what method, if any, will obtain the balance for the wallet/funding account.  The [end-point for Get Funding Balance in the API](https://www.okex.com/docs-v5/en/#rest-api-funding-get-balance) is:  _GET /api/v5/asset/balances_, but I can't find anything in the okex5 implicit methods that referrers to asset balances

_Note: without the ability to check the balance of the wallet/funding account I can't test deposits, which use the wallet/funding account balance as a means of knowing when the funds have arrived._

### transfers are NOT working:

- exchange.accountPostTransfer() "**is not a function**".  [The end-point in the API](https://www.okex.com/docs-v5/en/#rest-api-funding-funds-transfer) is:  _POST /api/v5/asset/transfer_ and there's nothing that reads: asset or transfer in okex5 implicit methods except: accountPostTransfer, which isn't working.

### withdrawal is NOT working:
The verbose response is rather long so it's attached: (over 322K characters)
[20210606-withdraw error.txt](https://github.com/ccxt/ccxt/files/6604833/20210606-withdraw.error.txt)

I did see this error: {"code":"58001","data":[],"msg":"**Incorrect trade password**"}.  However, I use the same password here as I used for: fetchDepositAddress() and fetchBalance() (for the spot/trading account) and the password worked there just fine.  

_(If you want the code I'll attach it here.  It's also long.  I use the getLastWithdraw() method.  I should try to condense it.)_

### Final Note:
I'm still banging away at the basics for a bunch of exchanges, but trading is next on my list to do.  Hopefully this week I'll test trading on okex5.

Here's hoping you're able to get okex up and working soon!

Thank you for building ccxt!

PS I hope this helps you!  I know it's a short list, but I'll keep testing okex methods and post my findings here.

**Comment by drsavant-pub** [comment]
Is this issue closed, and if so, is it now working or still being worked on?  

I've been out of the loop for over a month, but last night I updated ccxt and tried to get some balance information and it failed, so I'm wondering if this issue has been resolved in ccxt?

**Comment by kroitor** [comment]
@drsavant-pub i will get to it very soon, pardon for the long wait!

**Comment by kroitor** [comment]
> ### There Are Issues Obtaining The Balance:
> * however, exchange.accountGetWallet() (used to obtain the wallet/funding account balance) is reported as a function in ccxt (okex5 implicit functions), but when you try to run it, it says, "accountGetWallet is not a function".  I also tried: accountGetWalletCurrency() and getAssetValuation() the same error.  I'm not sure what method, if any, will obtain the balance for the wallet/funding account.  The [end-point for Get Funding Balance in the API](https://www.okex.com/docs-v5/en/#rest-api-funding-get-balance) is:  _GET /api/v5/asset/balances_, but I can't find anything in the okex5 implicit methods that referrers to asset balances

OKEX v5 has completely changed the url naming schema, now it's:

- `privateGetAccountBalance`
- `privateGetAssetBalances`
- `privateGetAssetCurrencies`

All implicit endpoints are exchange-specific and API-version-specific.

You can see all methods like so:

```Python
import ccxt
from pprint import pprint
print('CCXT Version:', ccxt.__version__)
pprint(list(dir(ccxt.okex5())))
```

As of CCXT 1.52.90 we have added the support for a `type` param for fetchBalance, which is either `account`/`trade` or `funding`.

> ### transfers are NOT working:
> * exchange.accountPostTransfer() "**is not a function**".  [The end-point in the API](https://www.okex.com/docs-v5/en/#rest-api-funding-funds-transfer) is:  _POST /api/v5/asset/transfer_ and there's nothing that reads: asset or transfer in okex5 implicit methods except: accountPostTransfer, which isn't working.

It's `privatePostAssetTransfer`. We will add the unified fetchTransfers as in Binance.

Will follow up on the other issues mentioned above.

**Comment by kroitor** [comment]
@drsavant-pub 

> withdrawal is NOT working:
> The verbose response is rather long so it's attached: (over 322K characters)
> 20210606-withdraw error.txt
> I did see this error: {"code":"58001","data":[],"msg":"Incorrect trade password"}. However, I use the same password here as  I used for: fetchDepositAddress() and fetchBalance() (for the spot/trading account) and the password worked there just fine.

`fetchBalance()` and `fetchDepositAddress()` use the API key password (exchange.password), while `withdraw()` also requires the funding password. OKEX has 3 passwords:
- login password
- funding password (withdraw requires this)
- api key passphrase (private apis require this)

<img width="889" alt="Screenshot 2021-07-17 at 11 51 27" src="https://user-images.githubusercontent.com/1294454/126031895-2c4deaff-2a11-4747-8cf7-9ac803547577.png">
<img width="1457" alt="Screenshot 2021-07-17 at 11 51 00" src="https://user-images.githubusercontent.com/1294454/126031897-872e7b10-3c31-40c2-912b-3c728b1a5996.png">

The proper way of withdrawing with OKEX v5 is:

```Python
import ccxt
exchange = ccxt.okex5({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_API_SECRET',
    'password': 'YOUR_API_PASSPHRASE',
})

markets = exchange.load_markets()
exchange.verbose = True

code = 'ETH'
amount = 1
address = 'YOUR_ADDRESS'
tag = None
params = {
    'pwd': 'YOUR_FUNDING_PASSWORD',
}
response = exchange.withdraw(code, amount, address, tag, params)
```
