### ISSUE TITLE
Question: automatic retries (all exchanges) and Poloniex seq issue

### ISSUE THREAD

**Issue by osnwt** [ccxt/ccxt#877]
Just found your library and want ask two questions.

Scripting some bot applications, in some cases it is convenient if API is able to retry unsuccessful operations up to N times with X delay if error is potentially recoverable. For instance, if exchange returned internal server error or timeout being under high load. In my API I pass optional retry number to constructor and optional retry log handler which is called with args to log something like "retry 3 of 5: a recoverable error message".

I guess this is not supported here and should be implemented by wrapping API calls into own retry handler. Did I miss something, or how do you recommend to handle such cases?

Related question is with Poloniex API. As I said, I retry recoverable errors. In case of Poloniex it often gives API errors if few HTTPS calls arrive not in the order they were sent. Sequence ids are not increasing, and Poloniex effectively rejects calls with ids less than out of order request. That's a nasty error when you cancel few orders and realise that last request came first, and all others are ignored.

In my implementation I check returned errors and retry calls in such case. Anyway, Poloniex API does not guarantee in order requests processing unless you wait for response or timeout (very long sometimes) before sending a next request. Having a retry handler, it could process such cases.

What do you think? Is it possible to implement this in the mainstream code, or should I wrap each ccxt function into a retry handler myself?

**Comment by kroitor** [comment]
Hi!

We are doing this on client side now (not in the library), but we actually think of migrating this into the library, as this code indeed seems to be needed frequently. However, it has to be done for 3+ languages at once (https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md) and has to account for backoff delays in order to avoid flooding the exchanges with retries during their downtime...

```
    // ---------------------------------------------------------------------------

    const retryWithBackoff = async function (delay, max, callee) {

        let backoff = delay

        while (true) {

            try {

                let result = await callee ()
                return result

            } catch (e) {

                if (!(e instanceof NetworkError))
                    throw e

                backoff = Math.min (max, backoff * 2);
                await sleep (backoff);
            }
        }
    }
```

We hope to add this into the library very soon. Let me know if I answered your question or not.

**Comment by osnwt** [comment]
Thank you for the example of handling. But in real case it should be tuneable for details of each exchange. In my app I am not so much concerned with long downtime network errors, but with occasional internal errors. The best example of such error is Poloniex wrong sequence of API calls I mentioned above. With normal operation it still has quite high probability to return error "Nonce must be greater than...". It is not a NetworkError, and it is recoverable, and it does not require backoff since next call will be successful.

Why I mention Poloniex is because many even paid apps have this issue with it. Most exchanges just require unique Nonce,  while Poloniex requires them to be strictly increasing. Since https is not a WebSocket, calls may arrive out of order and this must be handled internally, not on the client side.

So the retry handler to be included must be intelligent to handle such cases and not being limited by NetworkErrors only with fixed backoff strategy. In my case I set max number of retries (3-5) without backoff, retry only for recoverable errors (obviously it can't recover insufficient funds error by repeating the call), but if it still fails - pass this as an Exception to the client side to handle fatal error.

**Comment by kroitor** [comment]
> So the retry handler to be included must be intelligent to handle such cases and not being limited by NetworkErrors only with fixed backoff strategy. In my case I set max number of retries (3-5) without backoff, retry only for recoverable errors (obviously it can't recover insufficient funds error or 403 error by repeating the call), but if it still fails - pass this as an Exception to the client side to handle fatal error.

Thanks for your considerations on this as well! For now this is an app-level logic, but, as I mentioned, we are going to move it inside the lib. Let me know if I can help with anything else right away.

**Comment by osnwt** [comment]
Here is an example of retry wrapper for Poloniex I used:

```javascript
if (this._retryCount) {
  this.private[fn] = this._retry.bind(this, this._retryCount, this.private[fn]);
}

// Automatically repeats failed call to a function up to n times
_retry(n, fn, ...args) {
  if (n <= 1) {
    return fn.apply(this, args);
  } else {
    return fn.apply(this, args).catch(error => {
      // Do not retry if error is unrecoverable
      let retry = true;
      // TODO:
      //  - add more unrecoverable and/or recoverable error codes and strings
      //  - provide rate limiting for 429 errors

      // List of status codes that have no sense to retry:
      const noRetryCodes = [403, 422];
      // Unless error message contains any of these strings:
      const retryMatch = [
        'Nonce must be greater than',
      ];

      if (error instanceof ExchangeError) {
        if (noRetryCodes.includes(error.statusCode)) {
          if (!retryMatch.some(pattern => ~error.message.indexOf(pattern))) {
            retry = false;
          }
        }
      }
      if (retry) {
        // Call user-supplied retry logging function
        this._retryCallback(error, this._retryCount - n + 1, this._retryCount);
        return this._retry(n - 1, fn, ...args);
      }
      return Promise.reject(error);
    });
  }
```

**Comment by kroitor** [comment]
Thanks! We will use it for reference as well. Would you mind if I close this issue for now until we have a followup on this?

**Comment by osnwt** [comment]
Sure

**Comment by kroitor** [comment]
Ok, let me know if you have any other questions, feel free to reopen it if needed. BTW, ccxt has built-in rate-limiting (see examples/js).
