### ISSUE TITLE
Replace order. Feature request.

### ISSUE THREAD

**Issue by cfytrok** [ccxt/ccxt#8781]
I know, there is edit_order method. But it is slow. It cancles order, waits responce and creates new order. Is there way to send cancle_order and create_order requests consistently in a single http session? Without waiting for responce on cancel request.

**Comment by kroitor** [comment]
> Is there way to send cancle_order and create_order requests consistently in a single http session? Without waiting for responce on cancel request.

We implement `exchange.has['editOrder'] === true` method that does exactly that, if the exchange in question supports editing the orders. If the underlying exchange does not have a corresponding endpoint to do that in a single request, then the library falls back to the `exchange.has['editOrder'] === 'emulated'` method. Some exchanges may not be fully unified yet. More details here: https://github.com/ccxt/ccxt/wiki/Manual#exchange-metadata

Let us know if the above does not answer your question.

**Comment by cfytrok** [comment]
My question is about Binance. It doesn't support editing orders. So library falls back to 'emulated' method. 'Emulated' method sends 2 request in 2 http sessions. Is it possible to speed up 'emulated' method? There is no need to wait cancle_order response. One can send both requests sequentialy in 1 http session.

**Comment by kroitor** [comment]
@cfytrok you can just add this override, for example:

```Python
    async def edit_order(self, id, symbol, *args):
        if not self.enableRateLimit:
            raise ExchangeError('updateOrder() requires enableRateLimit = true')
        asyncio.ensure_future(self.cancel_order(id, symbol))
        return await self.create_order(symbol, *args)
```

**Comment by cfytrok** [comment]
Does your implementation guarantee that exchange receieves requests in the same order they were send? I want to use balance that has been freed, when order was canceled. If the order of the requests changes, I will get an InsufficientFunds error.

**Comment by kroitor** [comment]
The library guarantees that it will send out the requests in the order you execute them, but it cannot guarantee that your requests will arrive in the same order to the exchange due to the fundamental nature of the internet routing.

**Comment by cfytrok** [comment]
TCP guarantees delivery of data and also guarantees that packets will be delivered in the same order in which they were sent. Is it possible to send both requests asyncronously using single TCP connection?

**Comment by kroitor** [comment]
@cfytrok CCXT uses `requests` in python sync mode, and it uses the built-in `node` client in js, and `curl` in PHP, all of those libs enable the keep-alive, so it should be reusing the same connection where possible. You can also control it how you want.

**Comment by cfytrok** [comment]
Python in async mode uses aiohttp. It doesn't support HTTP Pipelining. Closed.
