### ISSUE TITLE
Bitfinex fetchBalance() Incorrect 

### ISSUE THREAD

**Issue by PolybitSol** [ccxt/ccxt#879]
Hey,

The unified fetchBalance method for Bitfinex produces erroneous values, calculating only the balance amounts for currencies held in the main exchange account, and does not include balances in the margin account. As you can see from the sample below, the raw info shows a BTC balance of 0.48, while the unified values show only a 0.38 total. 

- OS: Debian
- Language: JS
- CCXT version: 1.10.393
- Exchange: Bitfinex
- Method: fetchBalance()

```
{ info: 
    [ [ 'exchange', 'BCH', 0.00432805, 0, null ],
      [ 'exchange', 'BTC', 0.3806368, 0, null ],
      [ 'exchange', 'BTG', 0.00001671, 0, null ],
      [ 'exchange', 'DSH', 0.00106497, 0, null ],
      [ 'exchange', 'ETC', 0.00091715, 0, null ],
      [ 'exchange', 'XMR', 4.4e-7, 0, null ],
      [ 'exchange', 'XRP', 0.00313, 0, null ],
      [ 'exchange', 'ZEC', 0.00531749, 0, null ],
      [ 'exchange', 'USD', 1.38979773, 0, null ],
      [ 'margin', 'BTC', 0.1, 0, null ] ],
   BCH: { free: null, used: 0, total: 0.00432805 },
   BTC: { free: null, used: 0, total: 0.3806368 },
   BTG: { free: null, used: 0, total: 0.00001671 },
   DASH: { free: null, used: 0, total: 0.00106497 },
   ETC: { free: null, used: 0, total: 0.00091715 },
   XMR: { free: null, used: 0, total: 4.4e-7 },
   XRP: { free: null, used: 0, total: 0.00313 },
   ZEC: { free: null, used: 0, total: 0.00531749 },
   USD: { free: null, used: 0, total: 1.38979773 },
   free: 
    { BCH: null,
      BTC: null,
      BTG: null,
      DASH: null,
      ETC: null,
      XMR: null,
      XRP: null,
      ZEC: null,
      USD: null },
   used: 
    { BCH: 0,
      BTC: 0,
      BTG: 0,
      DASH: 0,
      ETC: 0,
      XMR: 0,
      XRP: 0,
      ZEC: 0,
      USD: 0 },
   total: 
    { BCH: 0.00432805,
      BTC: 0.3806368,
      BTG: 0.00001671,
      DASH: 0.00106497,
      ETC: 0.00091715,
      XMR: 4.4e-7,
      XRP: 0.00313,
      ZEC: 0.00531749,
      USD: 1.38979773 } }
```

**Comment by kroitor** [comment]
Hi! 

We don't sum margin and trading balances. 

CCXT currently unifies *trading* accounts and *trading* balances for most of exchanges, but it does not unify margin/leveraged/position accounts.

By default the Bitfinex fetchBalance will return exchange balance only, if you need the margin balance, you can fetch it like shown here: https://github.com/ccxt/ccxt/issues/601#issuecomment-345545702. 

You will have to sum them up in userland if you want margin+exchange total until that is unified in the library. Let me know if this answers your question or not.

**Comment by PolybitSol** [comment]
Hey,

Thanks for the reply - the method you describe is how I am currently doing it, I just mistook the purpose of the unified balance as supplying data on all accounts, whoops! Thanks for the quick reply, and as always, keep up the great work!

**Comment by kroitor** [comment]
Ok, let us know if you have any other questions with it. I'm closing this for now, until we get to unify the margin trading. Thx for the feedback!
