### ISSUE TITLE
Can this be run in browser using the pkg source?

### ISSUE THREAD

**Issue by ETHMOONBASE** [ccxt/ccxt#880]
From what I understand chrome can basically run something comparable to node and all that is needed is an html file with
<script type="text/javascript" src="https://unpkg.com/ccxt"></script> in the header. but how do you run the example js files from that screen once you open the html file. thank you.

**Comment by kroitor** [comment]
Hi! Sure! CCXT is designed to work from the browser (where CORS is supported, or via a CORS-proxy)

More about it here: 
- https://github.com/ccxt/ccxt/wiki/Install#javascript-for-use-with-the-script-tag
- https://github.com/ccxt/ccxt/wiki/Install#cors-access-control-allow-origin

```HTML
<!DOCTYPE HTML>
<html>
<head>
    <title>CCXT Basic example for the browser</title>
    <script type="text/javascript" src="https://unpkg.com/ccxt"></script>
    <script>
        document.addEventListener("DOMContentLoaded", function(){
                alert ('ccxt version ' + ccxt.version + ' supporting '+ ccxt.exchanges.length.toString () + ' exchanges');
        });
    </script>
</head>
<body>
<p>Hello, CCXT!</p>
</body>
</html>
```

**Comment by ETHMOONBASE** [comment]
ok awesome thank you. i loaded that page, i guess i was wondering how I start the instances like the ones in examples folder.

**Comment by kroitor** [comment]
@ETHMOONBASE sorry, do you still have that question, or is it now clear?

**Comment by ETHMOONBASE** [comment]
yea, so i was trying to run one of these examples.

https://github.com/ccxt/ccxt/tree/master/examples

I guess I was wondering how you call them to load from the console. But I think maybe Im just being a pest so ill just play around with it sorry.

**Comment by kroitor** [comment]
@ETHMOONBASE 

> I guess I was wondering how you call them to load from the console.

1. Clone the repository to your desktop
2. Having Node.js installed, In the repo folder type:

```
node examples/js/symbols bittrex # or any other example...
```

**Comment by kroitor** [comment]
https://www.youtube.com/watch?v=yoZpRMGRcyo

**Comment by ETHMOONBASE** [comment]
yea, i was trying to do that allnight, cloned the repo, downloaded latest version of node, installed in the folder to get dependencies, tried to run example file and got this

C:\Users\**\Desktop\**\ccxt\ccxt-master\examples\js>node tickers.js
module.js:557
    throw err;
    ^

Error: Cannot find module 'crypto-js'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\**\Desktop\**\ccxt\ccxt-master\js\base\functions.js:5:18)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)

C:\Users\**\Desktop\**\ccxt\ccxt-master\examples\js>

**Comment by kroitor** [comment]
1. In `C:\users\Desktop\ccxt\ccxt-master` run `npm install`
2. From the same directory run `node examples/js/tickers` and follow instructions from there.

**Comment by ETHMOONBASE** [comment]
yep, did that, few times actually haha

**Comment by ETHMOONBASE** [comment]
I will mess around with it, i wont keep bumping this thread, i know this is for smarter people haha, wont bother anymore. thank you for all the tips thusfar

**Comment by kroitor** [comment]
@ETHMOONBASE did what exactly? 

Here's a screenshot of me cloning the repo into a temporary folder, then running `npm install`, then running the example:

<img width="854" alt="screen shot 2017-12-18 at 05 18 18" src="https://user-images.githubusercontent.com/1294454/34087247-e1602bb8-e3b2-11e7-8267-538a2edd815c.png">

Post your screenshot repeating the same. Pay attention to paths.

**Comment by ETHMOONBASE** [comment]
ok. so if i get this working,it should show in browser then too? or is this just command prompt only using node locally.

**Comment by kroitor** [comment]
@ETHMOONBASE it shows how to launch it from console with node (the answer to your second question). Before that I showed you how to link against it in your browser (your first question). You can combine the code from examples + your HTML to make examples work from the browser. Those examples are currently designed for running from console, because after you link against the library, the syntax/usage is the same. So, it should be trivial to launch the same code within a browser.

**Comment by ETHMOONBASE** [comment]
![image](https://user-images.githubusercontent.com/29618511/34087425-fafdc32e-e370-11e7-9988-f5b454eab418.png)

Ok i think i got it

**Comment by ETHMOONBASE** [comment]
now ill play around with it more. the main reason  i tried to use ccxt was because i couldnt find any bots on github that were legit and had livecoin usage. i was looking for a bot to do one simple thing, keep an order on top of the book on a certain pair, and update it when someone else places one higher.
