### ISSUE TITLE
Close position in Hedge mode

### ISSUE THREAD

**Issue by zed2zed** [ccxt/ccxt#8801]
Hello,

I want to use Hedge mode with **Binance**.

In Hedge mode you can open two opposites positions (BUY and SELL in the same time).
In Hedge mode in Binance there is a dedicated interface to open orders and another to close them.

How do I close a position with CCXT?
If I use my standard code I get this error "Order's position side does not match user's setting."

_...
$symbol = "BTC/USDT";
$amount=0.001;
$type = 'market';
$side="buy";
$price=null;
$params = array();
$order = $binance->create_order($symbol, $type, $side, $amount, $price, $params);
..._

In this code unlike the interface I do not indicate anywhere whether to close or open a position.

Can you help me ?

**Comment by zed2zed** [comment]
I found the solution with these settings
You have to choose LONG or SHORT.

$params = array('closePosition' => "True","positionSide" => "LONG");

And with a strop price :
$params = array('closePosition' => "True","stopPrice" => 60000,"positionSide" => "SHORT");

**Comment by kroitor** [comment]
@zed2zed thanks for your feedback! Pardon for the delays with our replies. Please, don't hesitate if anything.
