### ISSUE TITLE
Binance Futures: Whats the "expired" order status?"

### ISSUE THREAD

**Issue by 4nzor** [ccxt/ccxt#8806]
I set a stop market order as a stop loss, but for some unknown reason its status becomes expired, can you tell me why? This information is not available in the binance documentation.

<code lang="python">
data = {
            'symbol': self.symbol,
            'type': order_b_type,
            'side': side,
            'price': price,
            'amount': amount,
            'params': params
}

       

        
stop_loss_json = self.exchange.create_order(
                    **data
                )
</code>

**Comment by kroitor** [comment]
@4nzor hi! Please, paste your code and your verbose output: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
