### ISSUE TITLE
Missing UpdateTime to the  exchange.fetch_positions() in environment PRD but in environment TEST is present ?

### ISSUE THREAD

**Issue by boujrafh** [ccxt/ccxt#8814]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: LINUX 
- Programming Language version: PYTHON
- CCXT version: 1.43.21

The Exchange is Binance

Missing UpdateTime to the exchange.fetch_positions() in environment PRD but in environment TEST is present ?

Do you have the same problem because this updateTime is very important from my code.

` {'symbol': 'KAVAUSDT', 'initialMargin': '2.78996000', 'maintMargin': '0.13949800', 'unrealizedProfit': '-0.68524000', 'positionInitialMargin': '2.78996000', 'openOrderInitialMargin': '0', 'leverage': '5', 'isolated': True, 'entryPrice': '7.31752', 'maxNotional': '250000', 'positionSide': 'BOTH', 'positionAmt': '2.0', 'notional': '13.94980000', 'isolatedWallet': '2.93034514'}
`

**Comment by kroitor** [comment]
@boujrafh can you please post your request+response in verbose mode? https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by ttodua** [comment]
The issue hasn't got any follow-up. For future readers, while reading the response of `fetchPosition(s)` you can also check it's `info` property to get all available fields that exchange provides and is not unified yet in ccxt.

 let us know if you face any issue with current updated CCXT version.
