### ISSUE TITLE
Kraken partial fills (Possible rounding error??)

### ISSUE THREAD

**Issue by joemama0s** [ccxt/ccxt#8816]
Python 3.9.0
ccxt 1.46.35
Kraken
create_market_sell_order/create_market_buy_order
Windows 10

Hi. Im just trying to do a simple buy and sell example with litecoin. For the sake of simplicity, I ran code that first gets my balance with fetch_balance['total'] then executed a `create_market_buy_order`. Confirmed the program did in fact buy exactly one litecoin in the kraken api. I then went to sell it, replacing the create market buy with `print(exchange.create_market_sell_order(symbol="LTC/USD", amount=1))` and this finished by selling 0.9999999 coin, saying "Insignificant volume remaining". However, the same thing happened when selling 200 doge, I bought 200 and sold 199.999999. Am I doing something wrong or both times did I hit exactly 1e-08 volume short. Any help or advice would be really appreciated!

```
{'USD': 496.1893, 'LTC': 2e-08, 'DOGE': 1e-08}
{
    "amount": 1.0, <----------#
    "average": 220.88,
    "clientOrderId": "0",
    "cost": 220.88,
    "datetime": "2021-04-06T01:50:28.972Z",
    "fee": {
        "cost": 0.57,
        "currency": "USD",
        "rate": null
    },
    "fees": [
        {
            "cost": 0.57,
            "currency": "USD",
            "rate": null
        }
    ],
    "filled": 0.99999998, <-----------#
    "id": "<ID>",
    "info": {
        "closetm": "1617673828.9767",
        "cost": "220.88",
        "descr": {
            "close": "",
            "leverage": "none",
            "order": "sell 1.00000000 LTCUSD @ market", <---------#
            "ordertype": "market",
            "pair": "LTCUSD",
            "price": "0",
            "price2": "0",
            "type": "sell"
        },
        "expiretm": "0",
        "fee": "0.57",
        "id": "<ID>",
        "limitprice": "0.00000",
        "misc": "partial",
        "oflags": "fciq",
        "opentm": "1617673828.9725",
        "price": "220.88",
        "reason": "Insignificant volume remaining", <--------# ???????
        "refid": null,
        "starttm": "0",
        "status": "closed",
        "stopprice": "0.00000",
        "trades": [
            "<ID>"
        ],
        "userref": "0",
        "vol": "1.00000000",
        "vol_exec": "0.99999998"
    },
    "lastTradeTimestamp": null,
    "postOnly": null,
    "price": 220.88,
    "remaining": 1.9999999989472883e-08, <--------# ????
    "side": "sell",
    "status": "closed",
    "stopPrice": 0.0,
    "symbol": "LTC/USD",
    "timeInForce": null,
    "timestamp": 1617673828972,
    "trades": [
        {
            "amount": null,
            "cost": null,
            "datetime": null,
            "fee": null,
            "id": "<ID>",
            "info": "<ID>",
            "order": "<ID>",
            "price": null,
            "side": null,
            "symbol": "LTC/USD",
            "takerOrMaker": null,
            "timestamp": null,
            "type": null
        }
    ],
    "type": "market"
}```

**Comment by kroitor** [comment]
@joemama0s your order may be filled partially, so a single order can be filled with multiple trades. That is explained here: 

- https://github.com/ccxt/ccxt/wiki/Manual#how-orders-are-related-to-trades

Suppose you sell 200 DOGE. Your order is filled by 100 DOGE on first trade, then 50 DOGE on the second trade and so on, up to 200. When the remaining volume of your order is less than the exchange's minimal precision, then the remaining volume is insignificant, and your order is considered "fulfilled/closed". That is how the standard maker-taker model works with pretty much any exchange.

Let us know if that does not answer your question.

**Comment by kroitor** [comment]
P.S. You can verify that in verbose mode, by checking the exchanges' return values directly:
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

**Comment by joemama0s** [comment]
ah thanks sorry about that. I actually "read" this section, but didnt quite understand it and figured I could get away with skipping through it.... I learned my lesson and thanks for helping out!
