### ISSUE TITLE
How to get Current Leverage for Binance Futures Api npm

### ISSUE THREAD

**Issue by vikasdc** [ccxt/ccxt#8821]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:

```
REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS
```

```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
```

**Comment by uncentral** [comment]
Hey Vikasdc,

Leverage is not an actionable thing to monitor. So it's better to keep an eye on the liquidation price.

But it's off course interesting to know. You'll have to calculate it manually by taking the sum of all the dollar values of your positions and dividing by your collateral.

Your collateral (or simply balance) you can get as follows: 
```
binanceFtr = ccxt.binance({
    'apiKey': 'APIKEY',
    'secret': 'APISECRET',
    'options': { 'defaultType': 'future' } })
BINftrUSDT  = binanceFtr.fetch_balance()['USDT']['total']
```
The positions part of the unified api is a work in progress I believe, so you'll have to use the 
binanceFtr.fapiPrivateGetAccount() implicit method for your positions sizes and then 
binanceFtr.fetchTicker(TICKER) for the price of all those positions.
then multiply all of the position sizes and tickers and sum the result. You now have the dollar value of all your positions.

Then you divide the dolar value of all your positions with the collateral, et voila!

good luck.

**Comment by kroitor** [comment]
@uncentral thx for your help!
@vikasdc let us know if the above does not answer your question, closing this for now.
