### ISSUE TITLE
Parallel processing when creating orders

### ISSUE THREAD

**Issue by valderind4** [ccxt/ccxt#8824]
Hello,

I am using Laravel job-batch and even forcing parallel processing the orders are created in a sequencial way, this is so bad for my plataform because I need to make a "copy trading" system, creating a lot of orders in differents accounts and acctually this is taking a lot of time and doing the strategy for inputing, to fail.

What should I do?

**Comment by kroitor** [comment]
Hi! Let us know if this section does not answer your question: https://github.com/ccxt/ccxt/wiki/Manual#rate-limit – it explains why there has to be a delay and why the requests have to be executed sequentially because of the `nonce` mechanism.

**Comment by frosty00** [comment]
@kroitor pls merge #8808 so that people can use ccxt in their Laravel projects

**Comment by frosty00** [comment]
also @valderind4 checkout async php in ccxt https://github.com/ccxt/ccxt/tree/master/examples/async-php
