### ISSUE TITLE
New exchange: STEX.com (formerly known as stocks.exchange)

### ISSUE THREAD

**Issue by osnwt** [ccxt/ccxt#884]
This not very well-known yet exchange has some coins not supported by many others (yet).

Site: https://stocks.exchange
API: https://docs.google.com/document/d/1mU8ecTlzfDtT1hmZJ-dXezMudLnfD4ZeNBr_oxFwdGI

**Comment by osnwt** [comment]
Trying to support it, found that their API does not work for some methods (say, to get trade history). It returns API error even using their own web test page.

But worse, the whole site including API is protected by Cloudflare that is not set up properly. It performs browser check for scripting. I worked around it using some tricks, but still not all API functions work.

I'm trying to contact devs to fix it. Meanwhile do not spend time yet until they fix all issues. If they do, I will try to write a code and then let you know.

**Comment by kroitor** [comment]
Thanks for the notice! 

Btw, it is sometimes possible to workaround Cloudflare with cookie scraping tools:
- https://github.com/codemanki/cloudscraper
- https://github.com/Anorov/cloudflare-scrape

**Comment by osnwt** [comment]
Yes, I used cloudscraper for that. It works great, but whole protection setup is not good. Even via web interface it requires browser checks every hour or so, and even writing a ticket, after I clicked "Send", I've got browser check and "Page not found". I hope they fix it, or it makes no sense trying to overcome incorrect setup.

**Comment by osnwt** [comment]
After you added a custom fetch hook, I can try to implement this (if/when time permits). They have fixed the issue with TradeHistory. But the API still isn't reliable, today I saw missed history records while orders were closed properly - including the history on their web UI. And it still has broken Cloudflare setup.

Right now my own API interface implementation works for me (with very limited testing) for all documented methods (but some of them are not documented in full or properly). Could you please have a look at the API and suggest which already supported exchange is similar to be taken as a prototype? So I can reuse already written code as much as possible instead of reinventing the wheel.

**Comment by osnwt** [comment]
Also, assuming the worst case, if cloudscraper will be required, how do you recommend to reference it? I should 'require' it in the API class, but this will demand it on the upper level and not for javascript only. I can do private branch, but maybe you have other ideas?

**Comment by kroitor** [comment]
>  I can do private branch, but maybe you have other ideas?

I would leave it outside of the library and would let the user decide ) Just need to add a proper usage example and that's it. No need to integrate it into the basecode, as far as I can tell. Let me know if you think differently, I may be missing something.

> Could you please have a look at the API and suggest which already supported exchange is similar to be taken as a prototype?

From a brief overview I can tell that it is a mix of Liqui (and other BTC-e clones, like wex, tidex) for the private part and Bittrex APIs for the public part. Those two you should look at mostly, as they look most similar to stocks.exchange.

**Comment by osnwt** [comment]
If I understand you right, the support for it should be added using base code, but provide an example of custom wrapper to use it in real life until they fix the issue with Cloudflare. Sounds good.

**Comment by kroitor** [comment]
> If I understand you right, the support for it should be added using base code, but provide an example of custom wrapper to use it in real life until they fix the issue with Cloudflare. Sounds good.

Just to clarify, what I was trying to say: we have the `.fetchImplementation` override now, and in Python we have `python-requests` sessions, so the task of supporting cloudflare-scrape is mostly solved as far as we would like to go for it in the library. So, from here we believe, we should not add anything cloudflare-related *into the library*, but we should add an example of how to attach a cfscraper for using it *with the library*. Does it makes sense?

**Comment by osnwt** [comment]
I meant exactly that.

**Comment by kroitor** [comment]
@osnwt ok, cool! Let me know if you have any other questions! Thx!

**Comment by yenten** [comment]
concluding is there branch/fork with support of stocks?

**Comment by osnwt** [comment]
It is quite unreliable yet (including API). It could be supported, but I didn't waste time for that.

**Comment by yenten** [comment]
But can I have code or need to write my own :D? Maybe even raw outdated drafts?

**Comment by osnwt** [comment]
I did not write an API for this exchange for ccxt. Maybe someone did.
I tried to use self-written one (not for ccxt). You may try to implement it for ccxt.
StEx has good API test page to verify if things work as they should.

**Comment by yenten** [comment]
I got it, thx!

**Comment by osnwt** [comment]
This exchange's issue is inconsistent behaviour. Sometimes trade history (I need) does not contain some my trades, sometimes public history lags for many minutes, etc. Having inconsistent tables for bids/asks or negative account balances is also not a rare thing there according to reports. That's why I dropped ideas to write an API module for it. I didn't expect so many issues.

Look at this, sometimes such state can lasts for minutes even after refreshes. And that's only one example, there are many...

<img width="1173" alt="stex" src="https://user-images.githubusercontent.com/1081613/35618259-7a93222c-068b-11e8-9882-3767cde6ceb4.png">

**Comment by osnwt** [comment]
I saw question in email but can't see it here (removed?). I hate python and never tried it for API. But I found some weirdness with rate limiting too. I tried their API test page and requested the same call around once per second, 5 times - and had banned for a minute due to rate limiting. There is no any statements about rate limiting, but it is quite hard in reality. That's yet another one weirdness of that exchange. I asked them via tickets and by email to clarify, I've never got any answers. It seems they're not interested in good reputation.

**Comment by crackfoo** [comment]
I thought I saw this exchange one day in the past? Did it get removed?

**Comment by kroitor** [comment]
> I thought I saw this exchange one day in the past? 

This one hasn't been in the library yet ) It is on the way. You probably confused it with SouthXChange.

> Did it get removed?

Nope )

**Comment by osnwt** [comment]
Forget about it, they only add new coins, don't respond or fix issues. I moved out all from this exchange. BTC-Alpha (still not in ccxt - why?) or Graviex seems to be much better ones - and they also add new coins the Stocks.Exchange used to do.

**Comment by crackfoo** [comment]
@kroitor ok thanks!

@osnwt I know what you mean. They're poor with support but seems they've added better management for that now? Not sure, I did give up on them as well but they've coins I'd like to add to my pool again ^_^

**Comment by osnwt** [comment]
I had some tickets which were closed unanswered. If they improve their support, shouldn't they if not fix, but at least answer? This clearly tells me do not put anything real to this exchange.

<img width="460" alt="stex-issues" src="https://user-images.githubusercontent.com/1081613/37722192-6cd008ee-2d3c-11e8-9da1-8b7c251a0d23.png">

And all tickets were closed. GREAT SUPPORT!

**Comment by osnwt** [comment]
Look at vicex.io, soon to be open (few days). It will not have API at first, but I expect better support from them and acceptable listing policy for same coins STEX used to list.

**Comment by valentinbora** [comment]
API Docs now at http://help.stocks.exchange/api-integration

**Comment by jpfleury** [comment]
Issue's title should be edited. This exchange changed its name and website from "Stocks.exchange" to "STEX.com".

**Comment by kroitor** [comment]
https://www.stex.com/2018/09/we-are-moving-to-stex-com/
