### ISSUE TITLE
New exchange: cobinhood

### ISSUE THREAD

**Issue by hunsnowboarder** [ccxt/ccxt#885]
Please add also https://cobinhood.com/home to the exchange availibilty as it is a zero fee exchange.
Thank you very much in advance and appreciate so much your work and effort guys! Keep doing this! And of course Happy Hollidays!

**Comment by Deathamns** [comment]
Working on it... However their API seems to be quite experimental, property names changed while I was testing.

**Comment by kroitor** [comment]
Added in an "experimental" state in the most recent version of ccxt, we will be happy for your help with testing it. Thx!

**Comment by vidur149** [comment]
Cobinhood is not working. Please check

**Comment by kroitor** [comment]
@vidur149 your version of ccxt is too old, please update it to the most recent one, cobinhood was added not so long ago, follow these instructions:
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
