### ISSUE TITLE
[binance] symbol mapping - EPS

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#8909]
https://www.binance.com/en/trade/EPS_USDT?layout=basic
https://research.binance.com/en/projects/ellipsis
https://coinmarketcap.com/currencies/ellipsis/

Price of 1 Ellipsis is about 4.6USD.

I think it's in conflict with:

https://coinmarketcap.com/currencies/epanus/

Price of 1 Epanus is about 0.45USD.

**Comment by kroitor** [comment]
@npomfret the price of EPS on Binance from your link corresponds to the price of EPS, though. And Binance says explicitly that it is Ellipsis. I'm not sure if there's any conflict here. Can you elaborate?

**Comment by ndubel** [comment]
probably whe need to rename EPS to Epanus on Probit and Crex24
