### ISSUE TITLE
BCH/coins orderbooks missing from BitBay exchange

### ISSUE THREAD

**Issue by Felipe-Mangueira** [ccxt/ccxt#892]
Hey, @kroitor,

I am missing BCH's orderbooks, BCH/PLN included, from Bitbay exchange. Could you add it as soon as you can, please? Thanks in advance.

- OS: Windows 10
- Language: English
- CCXT version: 1.10.354
- Exchange: Bitbay
- Method: fetch_order_book

```
bitbay = ccxt.bitbay({'nonce': lambda: int(time.time() * 1000)})
bitbay.uid = 'user'
bitbay.apiKey = 'apiKey'
bitbay.secret = 'secret'
bitbay.password = 'password'
bitbay.verbose = True

x = bitbay.fetch_order_book('BCH/PLN')
```

```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.1\helpers\pydev\pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.1\helpers\pydev\pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/fmangueira/PycharmProjects/Bot Projects/teste/teste.py", line 95, in <module>
    x = bitbay.fetch_order_book('BCH/PLN')
  File "C:\Program Files\Python36\lib\site-packages\ccxt\bitbay.py", line 99, in fetch_order_book
    'id': self.market_id(symbol),
  File "C:\Program Files\Python36\lib\site-packages\ccxt\base\exchange.py", line 924, in market_id
    market = self.market(symbol)
  File "C:\Program Files\Python36\lib\site-packages\ccxt\base\exchange.py", line 918, in market
    raise ExchangeError(self.id + ' does not have market symbol ' + str(symbol))
ccxt.base.errors.ExchangeError: bitbay does not have market symbol BCH/PLN
```

**Comment by kroitor** [comment]
Added BCH/PLN and BTG/PLN in 1.10.410+. Unfortunately, they still don't offer a list of traded symbols with their API, so we have to keep it hardcoded for now. I guess we will have to switch to scraping that list from their website soon, otherwise it will be hard to keep it up to date.

**Comment by Felipe-Mangueira** [comment]
Hi, @kroitor,

Thank for your return, but I meant Bitbay not Bitmarket. The BCH's orderbooks is missing from Bitbay exchange. Could you take a look, please?

Besides, I have a problem to fetch my balance, which is definitely not empty. Could you take a look at this, as well? I'm getting the 503 error code. Please, see the log:

'''
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.1\helpers\pydev\pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.1\helpers\pydev\pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/fmangueira/PycharmProjects/Bot Projects/teste/teste.py", line 94, in <module>
    x = bitbay.fetch_balance()
  File "C:\Program Files\Python36\lib\site-packages\ccxt\bitbay.py", line 95, in fetch_balance
    raise ExchangeError(self.id + ' empty balance response ' + self.json(response))
ccxt.base.errors.ExchangeError: bitbay empty balance response {"code":503,"message":"Invalid moment parameter. Request time doesn't match current server time"}
'''

**Comment by kroitor** [comment]
@Felipe-Mangueira lol... that happens ) Bitmarket required an update to their list of pairs anyway )) I'll update bitbay as well and will get back to you on the error.

**Comment by kroitor** [comment]
Bitbay should be up to date now... On the error you have – make sure your clock is synchronized. 
If synchronizing time does not help, please post verbose output of it, we will need to see the nonce numbers.

P.S. Post code in backticks (&#96;&#96;&#96;) not in quotes (''').

**Comment by Felipe-Mangueira** [comment]
Hi, @kroitor.

>On the error you have – make sure your clock is synchronized.

Sorry for the noob question, but how do I do that? When I override the nonce parameter and set the  bitbay exchange like this (described on your ccxt manual)...
```
bitbay = ccxt.bitbay({'nonce': lambda: int(time.time() * 1000)})
```
... I get the error 503. However, when I do not override any nonce like this... 
```
bitbay = ccxt.bitbay()
```
... I receive the balance without problems. So, as I intend to request the bitbay's server more than one time per second, I assume this last possibility is not suitable and, at last, I do not know what to do. If you could give me a tip, I would thank you one more time. See the verbose output when I get the error:
```
https://bitbay.net/API/Trading/tradingApi.php POST https://bitbay.net/API/Trading/tradingApi.php 
Request: {'Content-Type': 'application/x-www-form-urlencoded', 'API-Key': 'API-Key', 'API-Hash': 'API-Hash', 'Accept-Encoding': 'gzip, deflate'} method=info&moment=1513645709209
Traceback (most recent call last):
POST https://bitbay.net/API/Trading/tradingApi.php 
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.1\helpers\pydev\pydevd.py", line 1599, in <module>
Response: Date: Tue, 19 Dec 2017 01:08:29 GMT
Content-Type: text/plain;charset=UTF-8
Content-Length: 108
Connection: close
Set-Cookie: __cfduid=defd04929c9efbeaaacec214782fd011f1513645709; expires=Wed, 19-Dec-18 01:08:29 GMT; path=/; domain=.bitbay.net; HttpOnly
Content-Disposition: inline;filename=f.txt
X-Content-Type-Options: nosniff
X-Frame-Options: sameorigin
Vary: Accept-Encoding
Content-Encoding: gzip
Server: cloudflare-nginx
CF-RAY: 3cf678938a924b8d-GRU

 {"code":503,"message":"Invalid moment parameter. Request time doesn't match current server time"}
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.1\helpers\pydev\pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2017.2.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/MANGUEIRA/PycharmProjects/Bots Projects/OctoplusBot/Octoplus_0.3.0.py", line 95, in <module>
    x = bitbay.fetch_balance()
  File "C:\Program Files\Python36\lib\site-packages\ccxt\bitbay.py", line 111, in fetch_balance
    raise ExchangeError(self.id + ' empty balance response ' + self.json(response))
ccxt.base.errors.ExchangeError: bitbay empty balance response {"code":503,"message":"Invalid moment parameter. Request time doesn't match current server time"}
```

**Comment by kroitor** [comment]
You can't call it more frequently than once per second.

<img width="860" alt="screen shot 2017-12-19 at 04 28 03" src="https://user-images.githubusercontent.com/1294454/34136073-2ab28aa0-e475-11e7-9bc2-1801e3e9994d.png">

<img width="724" alt="screen shot 2017-12-19 at 04 28 36" src="https://user-images.githubusercontent.com/1294454/34136077-2df1dcfc-e475-11e7-8ae5-cb39c9f29f93.png">

> When I override the nonce parameter and set the bitbay exchange like this (described on your ccxt manual)...

No need to override the nonce at all – it won't work for this particular exchange.

> So, as I intend to request the bitbay's server more than one time per second, I assume this last possibility is not suitable and, at last, I do not know what to do.

Add a manual delay of 1 second before doing each subsequent private call with time.sleep (1), or, better use the built-in rate-limiter that will send out your requests once per second:

```Python
bitbay = ccxt.bitbay({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True, # or .enableRateLimit = True later
})

# print 10 times, once per second
for i in range(0, 10):
    print(bitbay.fetch_balance())
```

Also look through examples on how to use the built-in rate limiter with sync Python and async Python 3: https://github.com/ccxt/ccxt/tree/master/examples/py

**Comment by kroitor** [comment]
@Felipe-Mangueira more about rate-limiting:

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/wiki/Manual#authentication
- https://github.com/ccxt/ccxt/wiki/Manual#overriding-the-nonce (this one you've already read, apparently)

**Comment by Felipe-Mangueira** [comment]
Ok, @kroitor, I'll take your advices (I have read this docs already).
On my strategy, sometimes I overload the server from Mercado Bitcoin with 3 request at once on 3 different threads (for example), and after then I wait 3 seconds and I have not been banished yet. I think I should override the nonce with a milliseconds one, since I want to make private requests more frequently than once per second, sometimes, but I cannot.

**Comment by kroitor** [comment]
> sometimes I overload the server from Mercado Bitcoin with 3 request at once on 3 different threads (for example), and after then I wait 3 seconds and I have not been banished yet

This is because most exchanges support *bursts* of requests... Our built-in rate limiter supports that, if you set a proper .rateLimit + tokenBucket settings, then you can send out your requests in bursts, this is needed by most of traders, they don't want to be regular, they want to be responsive (send many requests in short periods of time, while still staying below the rate limit in longer term) This is somewhat explained here:
- https://github.com/ccxt/ccxt/pull/373 (initial proposal to switch from a regular scheduler to token bucket)
- https://github.com/ccxt/ccxt/issues/736
- https://github.com/ccxt/ccxt/issues/297

The token bucket algorithm is very flexible and allows very precise control, but, unfortunately, it is still not documented (this library is under development). So you will have to [read about it](https://en.wikipedia.org/wiki/Token_bucket), and then learn to use the implementation from ccxt, or wait until we document it properly...

All of the above is true for most major exchanges, but not for BitBay. BitBay demands 1 request per second by design (they will refuse to accept any other params). It's just how it works. We can't workaround this limitation.

**Comment by Felipe-Mangueira** [comment]
Ok, @kroitor. I got it... I will have to accept this limitation or give up on this exchange because it doesn't fit my needs.

Anyway, I really appreciate your patience and concern.
