### ISSUE TITLE
Question about ClientOrderId and cancelOrder()

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#8925]
OS: Windows Server 2019 Datacenter
Programming Language version: Node.js 15.3.0
CCXT version: 1.47.3
Exchange: All Exchanges
Method: ClientOrderId and `cancelOrder()`

Hello!

I have a question about the `clientOrderId` that could be added when creating an order:
```
exchange.createOrder (symbol, type, side, amount, price, { 'clientOrderId': 'Hello', })
```
The manual says this: https://ccxt.readthedocs.io/en/latest/manual.html
_This is only available for the exchanges that do support clientOrderId at this time._

I wonder how to know what exchanges that support the clientOrderId. I have tried to run the below code, which exchanges that do support the `cancelOrder` method, since they need a clientOrderId as an argument:
```
(async () => {
    const allexchanges = ccxt.exchanges.filter((id) => !['coinmarketcap'].includes(id))
        .map(async (id) => {

            const Exchange = ccxt[id];
            const exchange = new Exchange({ enableRateLimit: true, 'timeout': 10000 });
            console.log(exchange.has['cancelOrder'] + "___" + id);
        });
    await Promise.all(allexchanges);
})();
```
**Question 1:**
Is it true that all exchanges that shows `TRUE` for the `cancelOrder` method also supports the `clientOrderId` ?

**Question 2:**
**Manual says this:** 
**cancelOrder  (id, symbol, params)** method. _Note, that some exchanges require a second symbol parameter even to cancel a known order by id._
How to know which exchanges that also need the symbol parameter?

**Question 3:**
For example the exchanges Coinbase and Whitebit as seen in above code doesn't support the `cancelOrder`  method. 
I wonder if it would be possible to add a `clientOrderId` to that order and then also, if it is not possible to cancel orders on those exchanges?

Thank you!

**Comment by kroitor** [comment]
> Is it true that all exchanges that shows TRUE for the cancelOrder method also supports the clientOrderId ?

No, but we are doing our best to add it where it is missing. This is hard, since not all exchanges support it at all.

> How to know which exchanges that also need the symbol parameter?

Just always pass it assuming that the exchange always requires it.

> I wonder if it would be possible to add a clientOrderId to that order and then also, if it is not possible to cancel orders on those exchanges?

Afaik, Coinbase Pro does not support client order ids for canceling orders.

Let us know if that does not answer your questions.

**Comment by jackpotcityco** [comment]
Yes, I can imagine it must be many difficulties there.

I think I must ask again to be sure, since this part is so important to understand.

1. If the `exchange.has['cancelOrder']` shows `true` and that exchange doesn't support `clientOrderId` in ccxt. Is it then possible to cancel a specific order in the ccxt API in any way that just was sent and how would one cancel the order. For example a limit order? If not, will the order just stay open if never filled?

2. How would it be possible to know which exchanges that supports the `clientOrderId` in the ccxt?

3. I wonder if this could be practical - as a side/workaround solution where possible to see what is happening with a specific order that doesn't support the `clientOrderId`:
Let us say that we send an amount of 1.5789 ETH on the binance exchange and let us assume that the `clientOrderId` is not supported. If this amount is a unique amount order that I just sent among many orders during the last 30 seconds using the `since` parameter. It should work to call: `fetchOpenOrders, fetchClosedOrders, fetchMyTrades` to search for the order where amount is 1.5789 ETH to locate this order?
