### ISSUE TITLE
What to put as Amount in exchange.createOrder()

### ISSUE THREAD

**Issue by jackpotcityco** [ccxt/ccxt#8926]
OS: Windows Server 2019 Datacenter
Programming Language version: Node.js 15.3.0
CCXT version: 1.47.3
Exchange: All Exchanges
Method: Amount in `exchange.createOrder()`

Hello!

I have a question about the `amount` when creating an order:
```
exchange.createOrder (symbol, type, side, amount, price, { 'clientOrderId': 'Hello', })
```
The manual says this: https://ccxt.readthedocs.io/en/latest/manual.html
_**Amount: how much of currency you want to trade**. 
1. This usually refers to base currency of the trading pair symbol, 
2. Though some exchanges require the amount in quote currency a
3. And a few of them require base or quote amount depending on the side of the order. See their API docs for details._

How to know which one of those 3 scenarios.
Is this information avaliable in the API somewhere or is it only possible to know this by looking at the exchanges websites(API details)?

Thank you!

**Comment by frosty00** [comment]
```
How to know which one of those 3 scenarios.
Is this information avaliable in the API somewhere or is it only possible to know this by looking at the exchanges websites(API details)?
```

You can't really without testing the exchange by making a test order outside of the price range of the market. So you could test it by making a bid for BTC/USDT at 10k for example. For 90+% of exchanges the amount refers to the amount in the base currency.

**Comment by jackpotcityco** [comment]
Frosty00, Thank you for that information.

Then I will need to try it like that in order to know which one to use on different exchanges.

Thank you!
