### ISSUE TITLE
Add watch order websocket

### ISSUE THREAD

**Issue by dangkhoaest** [ccxt/ccxt#8936]
Hello,
I'm a member of ccxt pro.

Do you have any plan to add watch order websocket ? I can become a sponsor to accelerate if you guy have a plan soon.

Thank you so much for making a great library and all you do for community.

**Comment by kroitor** [comment]
@dangkhoaest hi! Yes, we do have plans for `watchOrder`, though it is not the topmost priority at this time. In any case, we will add it as soon as we can. In the meantime, you can just filter the response returned from `watchOrders` by order id or by any other criteria to get your specific order (the same result as `watchOrder` would give you). Let us know if that does not answer your question. Feel free to reopen this issue or just ask further questions if any.
