### ISSUE TITLE
Install ccxt on linux server via Python setup file

### ISSUE THREAD

**Issue by rnnyrk** [ccxt/ccxt#8940]
Hi,

I'm trying to install CCXT (Pro) via a Python setup file on a Linux server. I'd found [this explanation](https://github.com/ccxt/ccxt/wiki/ccxt.pro.install#python-dependency) in the README. Unfortunately the installation is stuck as soon as it does try to install the CCXT or CCXT Pro package. When I delete one or both packages from the setup requires list it runs without any problems. 

The installation gets stuck on `Reading https://pypi.org/simple/ccxt/`  as shown in the screenshot. Any suggestions?

- OS: MacOS / Linux server
- Programming Language version: Python
- CCXT version: see below

```
from setuptools import setup, find_packages

requires = [
    'aiodns==2.0.0',
    'aiohttp==3.7.4.post0',
    'async-timeout==3.0.1',
    'attrs==20.3.0',
    'ccxt==1.47.49',
    'ccxtpro @ git+https://github.com/kroitor/ccxt.pro.git#subdirectory=python',
    'certifi==2020.12.5',
    'cffi==1.14.5',
    'chardet==4.0.0',
    'cryptography==3.4.7',
    'greenlet==1.0.0',
    'idna==2.10',
    'multidict==5.1.0',
    'numpy==1.20.2',
    'pandas==1.2.3',
    'psycopg2-binary==2.8.6',
    'pycares==3.1.1',
    'pycparser==2.20',
    'python-dateutil==2.8.1',
    'pytz==2021.1',
    'requests==2.25.1',
    'six==1.15.0',
    'SQLAlchemy==1.4.7',
    'typing-extensions==3.7.4.3',
    'urllib3==1.26.4',
    'yarl==1.1.0'
]

setup(
    name='crypto_arbit',
    version='0.0.1',
    install_requires=requires,
)
```

<img width="943" alt="Screenshot 2021-04-12 at 14 02 31" src="https://user-images.githubusercontent.com/4519142/114391415-c442a100-9b97-11eb-807a-205d2c0861d6.png">

**Comment by kroitor** [comment]
Hi! I'd suggest trying to preinstall `ccxt` first, just to see if it makes a difference. Does `pip install ccxt` or `pip3 install ccxt` work for you? It might be that the size of the package is larger than average, since it includes a lot of code for a lot of exchanges, though it should not hang for over a few minutes. Does it hang for long in your case?

**Comment by kroitor** [comment]
JFYI, you can find the corresponding version of CCXT 1.47.49 on PyPI's website here: https://pypi.org/project/ccxt/

**Comment by kroitor** [comment]
Also, you can enable pip's verbose mode / logfile upon installing ccxt to see what's taking so long.

- https://pip.pypa.io/en/stable/reference/pip/

**Comment by rnnyrk** [comment]
Installing it directly on the server seems to work. Any idea what the issue might be?

**Comment by kroitor** [comment]
@rnnyrk that is hard to tell without more details from you, a pip log would probably explain it. Could be a networking glitch or smth. You should be able to install ccxtpro now. Does it work for you?

**Comment by rnnyrk** [comment]
Unfortunately I can't figure out how to run verbose mode since I'm using a setup file to install my packages. I run the command `python3 $PDIR-$VERSION/setup.py install` on which the installation of the ccxt package gets stuck. 

I'm sot so lucky installing the pro package either. I'd add only the ccxt pro package to my setup.py, following [your manual](https://github.com/ccxt/ccxt/wiki/ccxt.pro.install#python-dependency). Although the package seems to install, when running my script I get the error `AttributeError: module 'ccxtpro' has no attribute 'binance'`
Googled the issue and [found one of your replies on another questions](https://github.com/ccxt/ccxt/issues/7889#issuecomment-719452464). Error seemed to be caused by installing a public stub of the pro package. So I still have to figure out how to install via a setup.py file with the correct ssh keys or https credentials.

**Comment by kroitor** [comment]
@rnnyrk i would not recommend embedding the credentials into your setup.py file, instead, i'd rather add some self-explaining helpers and ask the user to install it locally with this import-code:

```Python
try:
    import ccxtpro
except Exception as e:
    raise Exception('Looks like you do not have CCXT Pro installed. Please, install CCXT Pro onto your system first')
    
if not getattr(ccxtpro, 'exchanges'):
    raise Exception('Looks like you have installed the stub package instead of the private CCXT Pro package, please reinstall according to the CCXT Pro Install Manual')
```

**Comment by rnnyrk** [comment]
Ah sorry. Good one, will add the explanation indeed. Thanks for the code examples 👌
