### ISSUE TITLE
How long to create an order 

### ISSUE THREAD

**Issue by zed2zed** [ccxt/ccxt#8957]
Hello,

I find your library very useful.

But with PHP between the moment I open a PHP page that will create an order and where it appear on Binance it takes 3 seconds.
It may seem fast but on Binance Future with a leverage level these 3 seconds can make you lose money.

Do these 3 seconds come more from my linux machine?
From PHP ? Unoptimized language 
Or Binance? Server time response.

Thank you

**Comment by diwenshi61** [comment]
This can depend on a variety of factors. Depending on your internet connection and your location relative to Binance servers, the round-trip latency may be very high. Note that depending on your location, the Binance matching engine may have significantly higher latency than the Binance website. In general you can assume that processor time on your end << network latency.

**Comment by ttodua** [comment]
A bit late reply here, but for any/future readers :
- when you start your script, the initial moment of market-loading takes several seconds (1+) typically, depending the exchange and how many markets it is loading. so, even if you were at fastest machine with faster internet, such code will always take more than regular call. try to load markets at first _(if you dont call it manually, it still happens in the backgrounds in first unified method)_
```
$binance = new ccxt.binance();
$binance->load_markets();
$first_time = $binance->milliseconds();
$order = $binance->create_order (...);
print ( "FIRST STOP:", $start_time - $binance->milliseconds() );
```

and in such case, you will see that after markets are loaded, then every next call happen with their natural speed. 

Let us know if you experience any further issue in CCXT.
