### ISSUE TITLE
question: How to get order's id ?

### ISSUE THREAD

**Issue by denisenkoaj** [ccxt/ccxt#896]
- Language: js
- CCXT version: last
- Exchange: Binance
- Method: createMarketSellOrder

Hello guys! How to get order's id after creating market order ? and order's status: success or failure ? For example:
let binance  = new ccxt.binance({ verbose: true });
.. add api keys..
binance.createMarketSellOrder('BTC/USDT', 2);

I have either response with:
{"code":-2010,"msg":"Account has insufficient balance for requested action."}
either response with order information.

But i can see response only in console, how to get this information in code ?

**Comment by kroitor** [comment]
@denisenkoaj you should catch and handle JS exceptions.

Docs: 

- https://github.com/ccxt/ccxt/wiki/Manual#error-handling

Examples including error handling:

- https://github.com/ccxt/ccxt/blob/master/examples/js/proxy-round-robin.js
- https://github.com/ccxt/ccxt/blob/master/examples/js/load-all-tickers-at-once.js
