### ISSUE TITLE
Poloniex - fetch_order fatal error

### ISSUE THREAD

**Issue by janeCMD** [ccxt/ccxt#897]
Hi,

> Fatal error: Call to undefined function ccxt\OrderNotCached() in /var/www/cryptoedge/ccxt/php/poloniex.php on line 471.

It seems like its 2 error thrown at the same time, first is that it didnt find the order, second you see above. The error is happening to me with order which is supposed to be executed ('closed'). I checked the code, and see how you implemented fetchOrder method for poloniex. Then i checked their API. Do i see well they support only fetching open orders ? And CCXT seems to be trying to get closed orders or order info from openOrders API. I guess something needs to be done here... Have no idea what, but maybe you will.

Am i just trying to work with exchanges, which API just sucks (CEX.IO, Poloniex), or is it only bittrex and kraken have proper API ?

**Comment by kroitor** [comment]
Hi!

Error #1 is explained here:

- https://github.com/ccxt/ccxt/issues/569
- https://github.com/ccxt/ccxt/pull/102
- https://github.com/ccxt/ccxt/issues/96
- https://github.com/ccxt/ccxt/issues/71

Error #2 may be fixed with the latest version of the library, which version do you have?

**Comment by janeCMD** [comment]
@kroitor I dont have newest version, can update it, by error 2 you mean getting order not from open orders API but trades ?

**Comment by kroitor** [comment]
@janeCMD no, by error 2 i mean `Fatal error: Call to undefined function ccxt\OrderNotCached()`...  as for the generic solution on fetching the trades for order management – we are working on it intensively (reworking the cache system right now). In the meantime you should save orders that were created with ccxt, and reload them from disk... For orders that were created outside of ccxt you will have to use fetchMyTrades()... We will notify you when we refactor it. Let me know if this answers your question or not. Thx!

**Comment by janeCMD** [comment]
@kroitor yes, basically all answered. I would have one more question, hope not stupid one. The IDs in trade APIs (globalTradeId, tradeId) - is one of them identical to order ID at poloniex ? I have orders placed on exchange saved, ofcourse, but my logic is tight to confirmation, that order was closed, rather than close it, when its not found in openOrders anymore. That is method prone to problems, for example user will cancel the order using other software or on exchange itself, or exchange does close the order on their behalf.

**Comment by kroitor** [comment]
> The IDs in trade APIs (globalTradeId, tradeId) - is one of them identical to order ID at poloniex ?

No, one order can result in many trades, so trade id != order id... each trade (if you fetch it with fetchMyTrades) will contain an `order` field with order id and an `id` field with the trade id... The logical structure is like `order_id = [ trade_id, trade_id, trade_id, ... ]`.

> That is method prone to problems

It is, that's why we are going to switch to fetchMyTrades as a generic solution to this.

Feel free to ask questions, if you have any more left. We will let you know when the update for it is available. Thx!
