### ISSUE TITLE
How to know when symbols are successfully subscribed to ws in ccxt.pro?

### ISSUE THREAD

**Issue by teneon** [ccxt/ccxt#8971]
- OS: Linux
- Programming Language version: Node
- version: 1.41.86

Hi there,

i have a question regarding ccxt.pro. I subscribed 100 symbols via watchTrade method (as in the examples) to Kraken exchange. I've noticed that rateLimit for Kraken is 3000ms by default. This means that 1 symbol is subscribed to ws every 3 seconds. 100 * 3 = 300 seconds. So the difference between first and last symbol being subscribed is 5 minutes. First symbol already has 5 minutes of data, while last one has zero data. Limit 3000ms for Kraken seems a bit high? I tried to set exchange.rateLimit  = 1500 and they didn't block me. When i tried to set enableRateLimit = false, they allowed me to subscribe 50 symbols immediately, but 51th to 100th were all blocked by Kraken :) Any suggestions are welcome, although that is not my main question.

I would like to be notified somehow when symbol has been successfully subscribed or if an error occured.
Is there a method, a hookup, callback or something which could be used, to be notified programmatically when each symbol (of those 100) has been successfully subscribed? Also is there a way to know when all symbols (that were added via watchTrade to queue) are successfully subscribed?

I have set `verbose: true` at instantiation.
```
    this.exchange = new ccxtpro.kraken({
      apiKey: KRAKEN_API_KEY,
      secret: KRAKEN_SECRET,
      timeout: 30000,
      enableRateLimit: true,
      verbose: true,
      options: {
        tradesLimit: 1
      }
    });
    this.exchange.rateLimit = 1500;
```

In verbose mode, additional details are being displayed in the console, which could be useful.
```
2021-04-13T15:52:25.809Z connecting to wss://ws.kraken.com
2021-04-13T15:52:26.639Z onUpgrade
2021-04-13T15:52:26.639Z onOpen
2021-04-13T15:52:26.640Z sending {
  event: 'subscribe',
  reqid: 1,
  pair: [ 'AAVE/EUR' ],
  subscription: { name: 'trade' }
}
2021-04-13T15:52:26.640Z sending {
  event: 'subscribe',
  reqid: 2,
  pair: [ 'ADA/EUR' ],
  subscription: { name: 'trade' }
}
2021-04-13T15:52:26.640Z sending {
  event: 'subscribe',
  reqid: 3,
  pair: [ 'ALGO/EUR' ],
  subscription: { name: 'trade' }
}

...

2021-04-13T15:52:26.649Z onMessage {
  connectionID: '15359497752685309399',
  event: 'systemStatus',
  status: 'online',
  version: '1.8.3'
}
2021-04-13T15:52:26.832Z onMessage {
  channelID: 4337,
  channelName: 'trade',
  event: 'subscriptionStatus',
  pair: 'AAVE/EUR',
  reqid: 1,
  status: 'subscribed',
  subscription: { name: 'trade' }
}
2021-04-13T15:52:26.850Z onMessage {
  channelID: 1473,
  channelName: 'trade',
  event: 'subscriptionStatus',
  pair: 'ADA/EUR',
  reqid: 2,
  status: 'subscribed',
  subscription: { name: 'trade' }
}

...

```
Is it possible to programmatically access these messages? Would that be a way to go or do you have some other suggestion(s)? :)

thank you and best regards,
Neon

**Comment by kroitor** [comment]
> Is it possible to programmatically access these messages? Would that be a way to go or do you have some other suggestion(s)? :)

That subscription confirmation does not necessarily carry any information to proceed, i would rather recommend waiting for the first response from the corresponding watch-method – that confirms the subscription.

Also, you can specify the onConnected callback, as explained here:

- https://github.com/ccxt/ccxt/issues/8245

Assuming you have the most recent versions of CCXT and CCXT Pro:

```JavaScript
class MyKraken extends ccxtpro.kraken {

    onConnected (client) {
        console.log ('Connected')
    }
    
    handleSubscriptionStatus (client, message) {
        console.log ('Subscribed', message)
        return super.handleSubscriptionStatus (client, message)
    }

})

const exchange = new MyKraken ({
    'enableRateLimit': true,
})
```

Let us know if that does not answer your question. Feel free to reopen this issue or just ask further questions if any.

**Comment by teneon** [comment]
Thank you for reply ;) These methods could be useful, specially `handleSubscriptionStatus`. It is important to know when a trade is actually subscribed. E.g. ,If you subscribe to 100+ symbols, it will take a few mins to actually subscribe them all to watchTrade and watchOrderBook completely. Among those 100+ symbols there will be ones that have very little liquidity and therefore trade might not happen for another few minutes and if i am waiting for the first trade data to arrive (which could be the confirmation of subscription), then i am losing several minutes of opportunity to start recording stats for this symbol (even if that means writing zeros to the DB), becasue then we know exactly that we were subscribed, but there were no trades (low liquidity). It is important for live trading and as data for backtesting.

There are limitations for each exchange (e.g. subscribing too many pairs too quickly) and there is nothing we can do about it, which is fine. But we should all try to avoid any unneccessary gapes or delays in data, because of our implementation.

I've tested 3 exchanges for now and here is the subscription data they return.

Kraken:
```
Subscribed {
  channelID: 2305,
  channelName: 'trade',
  event: 'subscriptionStatus',
  pair: 'XBT/USDT',
  reqid: 1,
  status: 'subscribed',
  subscription: { name: 'trade' }
}
```

Binance:
```
Subscribed { result: null, id: 1 }
```

Bitstamp:
```
Subscribed {
  event: 'bts:subscription_succeeded',
  channel: 'live_trades_btceur',
  data: {}
}
```

For me personally, it would be pretty messy to parse pairs based on these responses, as they all have different structure and symbol names might be tricky to parse, Binance doesn't even return symbol name in the response etc. 

I would like to suggest, the **unification of subscription responses from exchanges**.
Could this unification be added in the future :-) ?

I have read somewhere in the issues that you guys are working on unWatchMethods. That is excellent news. Very fundamental and useful. It is important to have this "fine control" over the whole system and if exchanges allow that, "our" library should support it as well.

**onDisconnect, onError... or something similar?**

I also have another question. Example: All symbols are subscribed and we are trading and recording data for days. Then something happens. Network issues (either no ethernet adapter or lag in responses) and data stops flowing in. I know that behind the scenes you detect that instantly and you try to reconnect etc.

Is there a hook, callback or something that could instantly notify us, if system went offline or perhaps if one of the exchanges is down or something? I would like to instantly know (at the same exact time as you detect it behind the scenes), if we are down and what was the cause (there might be different error messages), so i can adjust trader, data writer and other things instantly. 

To me it seems like that you are trying to make things as simple as possible for the end user, which is great, but
i think sometimes we need more fine control over the whole process. It's not always good to have a black box that does everything for you behind the scenes, without having the ability to take full control over the whole process when you want it or need it.

p.s. i am really thankful for your help, quick responses and your work overall, this project is amazing, good job guys.

best regards,
Neon

**Comment by kroitor** [comment]
@teneon thank you for your very detailed response, we really appreciate your feedback! We are of course going to unify the aspect of on-subscription updates, including the unified symbols and channel names. Totally agreed with pretty much everything you said! Will do our best to roll out those features asap!

**Comment by teneon** [comment]
No problem :D Thank you Igor. So just to be clear. Right now, there is no hook or something similar which could help me detect disconnects, network errors, offline status? It's ok, i will wait for implementation, just want to be clear that currently i can't detect this, correct?

**Comment by kroitor** [comment]
@teneon actually, there are specific methods called `onClose`, `onError` and `onConnected`, you can find them here: https://github.com/kroitor/ccxt.pro/blob/master/js/base/Exchange.js#L140. And you can override those just as you would do with any other method. We will try to make them even more unified in the near future. 

Let me know if that does not help.
