### ISSUE TITLE
How does Binance withdraw coins through USDT-TRC20

### ISSUE THREAD

**Issue by q15197721923** [ccxt/ccxt#8972]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:WIN 10
- Programming Language version:  node.js v10.17.0
- CCXT version: 1.46.89

```
   let exchange = new ccxt.binance({
                apiKey: Exchange.binance.apiKey,
                secret: Exchange.binance.secretKey,
                enableRateLimit: true,
                hedgeMode: true,
                options: {
                    defaultType: 'future',
                }
            })
      exchange.verbose = true;
      let withdraw = await exchange.withdraw(symbol,amount,address);
      let parseResult = util.parseResult("succeed",true,withdraw);
      res.json(parseResult)
```

```
{\"msg\":\"-4007=Address verification failed\",\"success\":false}
```

**Comment by frosty00** [comment]
you can do this:

```
await exchange.withdraw('USDT',amount,address, { 'network': 'TRX' });
```
