### ISSUE TITLE
How to install and run ?

### ISSUE THREAD

**Issue by TuSuNaMi** [ccxt/ccxt#900]
Hello,

I'm installed with root user and this command npm install ccxt my linux machine. 

But whats next I dont know, your documentation so expert for freebie. 

Please help me 

Thanks,

**Comment by kroitor** [comment]
> But whats next I dont know, your documentation so expert for freebie.

- https://steemit.com/steemdev/@codewithcheese/looking-for-arbitrage-opportunies-with-javascript-library-cctx-supporting-70-exchanges
- https://hackr.io/tutorials/learn-node-js
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/tree/master/examples

This library requires technical skills and experience with at least one programming language. If you have little programming experience, I'd recommend you to google for "Node.js tutorials", "Node.js examples", "Node.js getting started", etc. I'm closing this for now, if you don't mind.
