### ISSUE TITLE
no attribute 'futures_create_order'

### ISSUE THREAD

**Issue by DjDemir** [ccxt/ccxt#9001]
I use CCXT in Python for make a bot but i trying this code and get an error.
Do you have any idea for why?

by the way, sorry for my English.

- OS: Win 10
- Programming Language version: Python 3.8.8
- CCXT version: 1.47.61

```
import ccxt

exchange = ccxt.binance({
    'apiKey': 'MY_API_KEY',
    'secret': 'MY_API_SEVRET',
    'enableRateLimit': True,
    'options': {
        'defaultType': 'future',
    },
})

exchange.futures_create_order(
          symbol='BTCUSDT',
          side='BUY',
          type="MARKET",
          positionSide='SHORT',
          quantity=0.001,
          leverage=21   
)
```

```
Traceback (most recent call last):
  File "C:/Users/Tardis/PycharmProjects/CCXT/CCXT_STackOverFlow.py", line 12, in <module>
    exchange.futures_create_order(
AttributeError: 'binance' object has no attribute 'futures_create_order'
```

**Comment by kroitor** [comment]
There is no such method as `futures_create_order`.
Please, follow the Manual and use `create_order` + `params` overrides:

- https://github.com/ccxt/ccxt/wiki/Manual#placing-orders
- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

In general, we recommend reading the entire Manual from top to bottom at least once – it will really save your time.

You can see all available methods like so:

```Python
from pprint import pprint
import ccxt
pprint(dir(ccxt.hitbtc()))
```

------------

Change your code like so:

```Python
import ccxt

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.binance({
    'apiKey': 'MY_API_KEY',
    'secret': 'MY_API_SECRET',
    'enableRateLimit': True,
    'options': {
        'defaultType': 'future',
    },
})

markets = exchange.load_markets()

# uncomment for debugging
# exchange.verbose = True

symbol = 'BTC/USDT'
type = 'market'
side = 'buy'
amount = 0.001
price = None  # market order
params = {
    'positionSide': 'SHORT'
}
exchange.create_order(symbol, type, side, amount, price, params)
```

You can find all supported exchange-specific params here:

- https://binance-docs.github.io/apidocs/futures/en/#new-order-trade

Hope that answer your question.

**Comment by DjDemir** [comment]
Thank you so much for your answer.
when I try your code, i get a few error.

```
Traceback (most recent call last):
  File "C:\Users\Tardis\PycharmProjects\CCXT\venv\lib\site-packages\ccxt\base\exchange.py", line 606, in fetch
    response.raise_for_status()
  File "C:\Users\Tardis\PycharmProjects\CCXT\venv\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://fapi.binance.com/fapi/v1/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Tardis/PycharmProjects/CCXT/CCXT_STackOverFlow.py", line 28, in <module>
    exchange.create_order(symbol, type, side, amount, price, params)
  File "C:\Users\Tardis\PycharmProjects\CCXT\venv\lib\site-packages\ccxt\binance.py", line 1912, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "C:\Users\Tardis\PycharmProjects\CCXT\venv\lib\site-packages\ccxt\base\exchange.py", line 474, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\Tardis\PycharmProjects\CCXT\venv\lib\site-packages\ccxt\binance.py", line 2908, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\Tardis\PycharmProjects\CCXT\venv\lib\site-packages\ccxt\base\exchange.py", line 495, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Users\Tardis\PycharmProjects\CCXT\venv\lib\site-packages\ccxt\base\exchange.py", line 622, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Users\Tardis\PycharmProjects\CCXT\venv\lib\site-packages\ccxt\binance.py", line 2903, in handle_errors
    raise ExchangeError(feedback)
ccxt.base.errors.ExchangeError: binance {"code":-2022,"msg":"ReduceOnly Order is rejected."}

Response: POST https://fapi.binance.com/fapi/v1/order 400 {'Content-Type': 'application/json', 'Content-Length': '52', 'Connection': 'keep-alive', 'Date': 'Sat, 17 Apr 2021 12:36:44 GMT', 'Server': 'Tengine', 'X-MBX-USED-WEIGHT-1M': '2', 'X-MBX-ORDER-COUNT-10S': '0', 'X-MBX-ORDER-COUNT-1M': '2', 'x-response-time': '4ms', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 182732bb63f7d4f88e7cac0874b0cfef.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'AMS50-C1', 'X-Amz-Cf-Id': '2Ubg9K8nqEhMOjxsi3PhIFQgOhYX4kSsO7nCKQqhNC5ImuSOHSn-jA=='} {"code":-2022,"msg":"ReduceOnly Order is rejected."}

Process finished with exit code 1
```

**Comment by kroitor** [comment]
@DjDemir let us know if this does not answer your question: https://dev.binance.vision/t/why-do-you-get-reduceonly-rejection-errors/1198

**Comment by DjDemir** [comment]
i can't register in Binance Dev, because they closed New registrations for my location. (maximum limit reached).

**Comment by kroitor** [comment]
@DjDemir Let us know if this does not help:

<img width="1160" alt="Screenshot 2021-04-17 at 17 06 14" src="https://user-images.githubusercontent.com/1294454/115115844-491a2a00-9f9f-11eb-9454-c622b918c92c.png">

> A:
> Several reasons you might want to check for reduceOnly order rejection:
> 1. You don’t have any position to close
> 2. You’re at the edge of liquidation
> 3. You have other open orders that would be filled before the failed one and close all positions
> A little bit explanation for #3 -
> Let’s say your current position is 1 BTC for short; And you have an open order to close this BTC at 10000; If you place another order to close 1 BTC at 9999, it’d be rejected. (Because the order with 10000 for sure would be filled and close everything before this “9999” order )
> If you still think you shouldn’t have been rejected after checking above things, please contact CS

**Comment by DjDemir** [comment]
Thank you so much.

```
1. "You don’t have any position to close"  <- Yes, i don't have any position to close and i already don't try close position. i try create a order.
2. "You’re at the edge of liquidation" <- No, I'm not.
3. "You have other open orders that would be filled before the failed one and close all positions" <- No, i dont have any order.
```

I guess I can't do this

**Comment by kroitor** [comment]
@DjDemir i'd suggest forwarding the question to Binance's tech support, they might shed more light on it.

**Comment by kroitor** [comment]
@DjDemir if your position is not hedged, then you don't have to specify positionSide.

Does this work for you:

```Python
import ccxt

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.binance({
    'apiKey': 'MY_API_KEY',
    'secret': 'MY_API_SECRET',
    'enableRateLimit': True,
    'options': {
        'defaultType': 'future',
    },
})

markets = exchange.load_markets()

# uncomment for debugging
# exchange.verbose = True

symbol = 'BTC/USDT'
type = 'market'
side = 'buy'
amount = 0.001
exchange.create_order(symbol, type, side, amount)
```

**Comment by DjDemir** [comment]
> @DjDemir if your position is not hedged, then you don't have to specify positionSide.
> 
> Does this work for you? ↓
> 
> ```python
> import ccxt
> 
> print('CCXT Version:', ccxt.__version__)
> 
> exchange = ccxt.binance({
>     'apiKey': 'MY_API_KEY',
>     'secret': 'MY_API_SECRET',
>     'enableRateLimit': True,
>     'options': {
>         'defaultType': 'future',
>     },
> })
> 
> markets = exchange.load_markets()
> 
> # uncomment for debugging
> # exchange.verbose = True
> 
> symbol = 'BTC/USDT'
> type = 'market'
> side = 'buy'
> amount = 0.001
> exchange.create_order(symbol, type, side, amount)
> ```

Thank you so much.
yes, my order has been done now
Thank you so much again.
God bless you ':)

**Comment by DjDemir** [comment]
So, How do I set level of leverage?

**Comment by kroitor** [comment]
@DjDemir you can do that as explained here: https://github.com/ccxt/ccxt/issues/6978#issuecomment-631038879

**Comment by DjDemir** [comment]
> @DjDemir you can do that as explained here: [#6978 (comment)](https://github.com/ccxt/ccxt/issues/6978#issuecomment-631038879)

Thank you so much. 
and can I ask one more question?
How can I use my full balance for purchase?

**Comment by kroitor** [comment]
@DjDemir yes, though, that is exchange specific:

- https://github.com/ccxt/ccxt/issues?q=createOrder+quote++currency

I'd highly recommend reading the Manual from top to bottom.

Also, check the examples here: 

- https://github.com/ccxt/ccxt/tree/master/examples

**Comment by DjDemir** [comment]
Thank you so much
