### ISSUE TITLE
NDAX,  fetch_order_book returns only asks and empty bids

### ISSUE THREAD

**Issue by rallis** [ccxt/ccxt#9019]
- OS: MacOS 10.14
- Programming Language version: Python
- CCXT version: latest master (3863b5e1d6c77d719ac102b0243964c4946e7abb)

```
For Exchange  NDAX,  fetch_order_book returns only asks and empty bids.  
The call to the exchange is correct, response is fine, the bug is while parsing the response.
Type conversion string VS int of levelSide variable is causing it.
```
https://github.com/ccxt/ccxt/blob/master/python/ccxt/ndax.py#L388-L389 
and 
https://github.com/ccxt/ccxt/blob/master/python/ccxt/ndax.py#L421

```
int(levelSide) OR
levelSide == '0'
fixes it.

I can submit a PR for python but not sure if the PR needs to fix it in all three languages.
```

**Comment by rallis** [comment]
Submitted this PR for fixing it 
https://github.com/ccxt/ccxt/pull/9020

**Comment by kroitor** [comment]
@rallis thank you!
