### ISSUE TITLE
Parse error: syntax error, unexpected '.', expecting ',' or ';' in /ccxt/ccxt.php on line 35

### ISSUE THREAD

**Issue by janeCMD** [ccxt/ccxt#902]
Please help. I updated CCXT and this... I rewrote old version and have no idea, what this error means, i dont see any syntax error there myself.

**Comment by kroitor** [comment]
We don't have ccxt/ccxt.php in the repository, I guess it's your file... Can you try a clean install?

**Comment by janeCMD** [comment]
The file is there, in master (ccxt.php, updated 22 minutes ago). Only the folder i have ccxt in is called 'ccxt'

**Comment by kroitor** [comment]
@janeCMD which command did you use to update it?

**Comment by janeCMD** [comment]
@kroitor Just downloaded the zip, unpacked and copied to server ... The file ccxt.php contains const declaration, which is likely not allowed. This is what i found: 

https://stackoverflow.com/questions/10969342/parse-error-syntax-error-unexpected-expecting-or

I dont know if this could be related to php version, as there were some changes regarding these things in later PHPs

**Comment by kroitor** [comment]
@janeCMD and your version of PHP is?

**Comment by janeCMD** [comment]
5.5.38-1~dotdeb+7.1

**Comment by kroitor** [comment]
@janeCMD yeah, unfortunately, support for const expressions was added as of PHP 5.6+... Can you update ccxt once again and check if the problem is gone with the new version of it? I've added a workaround for this issue, however, I can't test it with 5.5 right now... Your test+report would be very helpful. Thx a lot!

**Comment by kroitor** [comment]
@janeCMD did you succeed with the newest version of it? Let us know, plz.

**Comment by janeCMD** [comment]
@kroitor I will let you know tomorow, off work now, thanks for help
