### ISSUE TITLE
Precision format in poloniex

### ISSUE THREAD

**Issue by nanaknihal** [ccxt/ccxt#9028]
- OS: macOS Catalina
- Programming Language version:
- CCXT version: ccxt==1.48.25,  ccxtpro == idk, pip3 freeze wasn't showing it but I just updated <1h ago. But it probably shouldn't matter for this issue

In coinbasepro and ftx, self.client.market(self.symbol)['precision'] gives the increments for price and size. But in poloniex, it gives the number of decimal places for those, rather than increments. I can fix it, but would be good to have a consistent format. If it helps i'll fix and PR. I suppose poloniex doesn't have increments other than 1*10^x.  If anything, I would suggest precision should mean digits to round and increment should be the actual decimal. But that would not be backward compatible with coinbase and ftx and i assume everything else, so it would be helpful to fix poloniex.

```
p =ccxtpro.poloniex({'enableRateLimit' : True, 'apiKey': config.poloniex['key'], 'secret': config.poloniex['secret']})
        await p.load_markets()
        vals = p.market(self.symbol)['precision']
        {'amount': 8, 'price': 8}

p =ccxtpro.coinbasepro({'enableRateLimit' : True, 'apiKey': config.poloniex['key'], 'secret': config.poloniex['secret']})
        await p.load_markets()
        vals = p.market(self.symbol)['precision']
        {'amount': 0.001, 'price': 0.0001}

```

Thanks

**Comment by kroitor** [comment]
Hi!

The type of value under `precision` will depend on `exchange.precisionMode`. 

This is by design, and it is documented in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits
- https://github.com/ccxt/ccxt/wiki/Manual#methods-for-formatting-decimals

Let us know if the above does not answer your question.

**Comment by nanaknihal** [comment]
Hmmm. Well, thanks for that clarification. That's a great feature. Unfortunately, I must be doing something wrong or that doesn't work for poloniex. I tried:
```
p.precisionMode = 'TICK_SIZE'
        p.options['precisionMode'] = 'TICK_SIZE'
```
and it doesn't change the output.

**Comment by kroitor** [comment]
@nanaknihal it is a read-only option, so you should interpret it, but you should not change it, cause it is set by the underlying exchange API. Instead, please, use the methods for formatting decimals in a unified way (then you won't have to bother at all about the type of precision used by each exchange):

- https://github.com/ccxt/ccxt/wiki/Manual#methods-for-formatting-decimals

Let me know if that does not help.

**Comment by kroitor** [comment]
@nanaknihal one more thing: it is not a string, it's a predefined constant, (`ccxt.TICK_SIZE`, `ccxt.DECIMAL_PLACES`, ...)

**Comment by nanaknihal** [comment]
Thanks, was just wonder where the enums were

**Comment by kroitor** [comment]
@nanaknihal you can find them here: https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/decimal_to_precision.py
