### ISSUE TITLE
Failed to upgrade ccxt pro level

### ISSUE THREAD

**Issue by ChenLi0830** [ccxt/ccxt#9038]
I am trying to upgrade to ccxt pro `professional` from `beginner`. However, I could not make the upgrade effective immediately. 

After paying for the upgrade, in the "seats" tab, it's still showing me as beginner level with 0 seats left. 

In the orders tab, it's showing that the professional level is not available until Aug 2021, which is the end of my beginner level (shown below). @kroitor could you help me to fix it so that I have access to the professional level asap? Thanks!

![image](https://user-images.githubusercontent.com/9557418/115484048-e1661800-a206-11eb-9759-c8adcc97a94d.png)

**Comment by kroitor** [comment]
Hi @ChenLi0830 ! CCXT Pro is a prepaid subscription, so your next plan will start after your previously-paid plan ends by default. However, we have switched your tier to professional, so that you could use it right away. Let us know if that does not help. Thank you for using CCXT Pro!

**Comment by ChenLi0830** [comment]
Hi @kroitor, I just confirmed that it's working for me now, I appreciate your help!
