### ISSUE TITLE
Margin Isolated Repay - BINANCE

### ISSUE THREAD

**Issue by esteban2006** [ccxt/ccxt#9042]
Hello @kroitor I am trying to develope a manual pay method under Isolated margin (BINANCE), I get to have to total to pay with no  problem (borrow + interest), but when I try to pay the amount that is also the amount stated by Binance I get an error Repay amount exceeds borrow amount (please see bellow). maybe this is not a CCXT problem, but I would like to know if you have an specific method for a manual repay or how can I calculate the total to pay and actually the repay.

Regards,

MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version: python 3.6
- CCXT version:  1.47.49

```
```
`import time
import requests
from pprint import pprint
fdb = FetchDataBinance()

def getMarketMarginDetails(self, symbol, lookingFor=None, reverse=False):

        symbol = symbol.upper()
        baseAsset = symbol.split('/')[0]
        if lookingFor is None or lookingFor == None:
            lookingFor = 'free'

        if reverse:
            assets = 'quoteAsset'
            asset = 1
        else:
            assets = 'baseAsset'
            asset = 0

        balance = self.binanceMargin.sapi_get_margin_isolated_account()

        for i in range(0,2):
            try:
                for i in balance['assets']:
                    if i['symbol'] == symbol.split('/')[0] + symbol.split('/')[1]:

                        pprint(i[assets])

                        if  FetchDataBinance.isDigit(i[assets][lookingFor]):
                            return (float(i[assets][lookingFor]))
                        else:
                            return (i[assets][lookingFor])
            except Exception as e:
                print('Binance server is to crowded now () failed')
                print(e)
                return None

def getMyPrecision(self, symbol):
        symbol = symbol.upper()
        precision = {}
        for i in range(0, 2):
            try:
                data = self.binanceMargin.fetch_markets()

                for i in data:
                    if symbol == symbol:
                        precision = (i['precision'])
                break
            except Exception as e:
                print(e)
                time.sleep(5)
                continue

        return precision

def makeManualRepay(self, symbol, reverse=False, possiblePayments=[]):

        # verificar si amount se solamente el interes o debe de incluir el prestamo

        symbol = symbol.upper()
        if reverse:
            asset = 0
        else:
            asset = 1

        if possiblePayments == []:
            return None

        error = 0
        pay = 0

        print ('Entrando a pagar')
        for possiblePayment in possiblePayments:
            try:
                pay = self.binanceMargin.sapiPostMarginRepay({
                'symbol' : symbol.split('/')[0] + symbol.split('/')[1],
                'asset' : symbol.split('/')[asset],
                'isIsolated' : True,
                'amount' : possiblePayment,
                'timeInForce': 'GTC'
                })
                break
            except Exception as e:
                error += 1
                print ('Error {}: {} total a pagar {}'.format(error, e, possiblePayment))
                continue

        return pay

totalRepay = (float(fdb.getMarketMarginDetails(symbol, 'borrowed')) + float(fdb.getMarketMarginDetails(symbol, 'interest')))
p = (fdb.getMyPrecision(symbol))
possiblePayments = ( [FetchDataBinance.truncate(totalRepay, n) for n in range(0,p['base']-1)])
possiblePayments.reverse()
print (fdb.makeManualRepay(symbol=symbol, possiblePayments=possiblePayments))`

```


```

```

Error 1: binance {"code":-3015,"msg":"Repay amount exceeds borrow amount."} total a pagar 10.000166
Error 2: binance {"code":-3015,"msg":"Repay amount exceeds borrow amount."} total a pagar 10.00016
Error 3: binance {"code":-3015,"msg":"Repay amount exceeds borrow amount."} total a pagar 10.0001
Error 4: binance {"code":-3015,"msg":"Repay amount exceeds borrow amount."} total a pagar 10.0
Error 5: binance {"code":-3015,"msg":"Repay amount exceeds borrow amount."} total a pagar 10.0
Error 6: binance {"code":-3015,"msg":"Repay amount exceeds borrow amount."} total a pagar 10.0
Error 7: binance {"code":-3015,"msg":"Repay amount exceeds borrow amount."} total a pagar 10.0
0



```

**Comment by samgermain** [comment]
Did you ever figure out your issue? 

By the way, adding a unified method to repay interest is something on my todo list. If someone else were to start the process, I would be sure to jump in with implementing it on other exchanges in order to speed up the process.
