### ISSUE TITLE
Insufficient resolution in timestamps

### ISSUE THREAD

**Issue by gitcnd** [ccxt/ccxt#9045]
ccxt is *awesome*, but I WISH they'd not done such weirdness with the times. It's adding unnecessary 000's to most things, while truncating upto 4 digits of genuine resolution from some exchanges at the same time.

I know this is a monster change, but, sometimes the cancer needs to be removed so a product can grow and stay healthy... can we PLEASE change the times to be floats - using normal "unix" time for the integer part, and sub-seconds (to whatever real original resolution the underlying exchange supports, e.g. nanoseconds or better) for the decimal part?

```
e.g. STOP! doing this: 1618911721000
e.g. START doing this: 1618911721.5536022
```

**Comment by kroitor** [comment]
@gitcnd hi! Can you list the exchanges that lose nanoseconds-precision?

**Comment by frosty00** [comment]
> can we PLEASE change the times to be floats - using normal "unix" time for the integer part, and sub-seconds (to whatever real original resolution the underlying exchange supports, e.g. nanoseconds or better) for the decimal part?

No, this is a horrible idea

**Comment by gitcnd** [comment]
@kroitor - to list just the ones that happen to be on my screen right now: kraken, ftx, kucoin, phemex, bitstamp ...  and I'm only observing 20 of the >100 exchanges you support - so it's a high proportion of data-loss that's going on.  Not all exchanges support sequential trade ID's, so higher-precision time for correct ordering is important.

**Comment by kroitor** [comment]
@gitcnd can you post the code to reproduce it? We need more details on the specific endpoints.

**Comment by gitcnd** [comment]
Here are some of the ones I noticed that I care about:

`#phemex: info[0]/1000000000 symbol price amount side

$s = {               # 1619145594 396215031
       'recv_time' => '1619147560.08697',
       'symbols' => 'ADA/USD',
       'exchange' => 'phemex',
       'dat' => {
                  'datetime' => '2021-04-23T02:39:54.396Z',
                  'timestamp' => '1619145594396',
                  'side' => 'buy',
                  'price' => '0.9928',
                  'info' => [
                              '1619145594396215031',    # 2021/04/23 02:39:54.396215031
                              'Buy',
                              9928,
                              13
                            ],
                  'id' => undef,
                  'takerOrMaker' => undef,
                  'order' => undef,
                  'type' => undef,
                  'amount' => '0.0013',
                  'symbol' => 'ADA/USD',
                  'fee' => undef,
                  'cost' => undef
                }
     };



#gateio: info{time} symbol price amount side id

$s = {
       'exchange' => 'gateio',
       'symbols' => '1INCH/ETH',
       'recv_time' => '1619147562.55922',
       'dat' => {
                  'symbol' => '1INCH/ETH',
                  'amount' => '0.95',
                  'cost' => '0.0018297',
                  'fee' => undef,
                  'takerOrMaker' => undef,
                  'type' => undef,
                  'order' => undef,
                  'price' => '0.001926',
                  'info' => {
                              'type' => 'sell',
                              'id' => 821397404,
                              'time' => '1619140983.84418',
                              'price' => '0.001926',
                              'amount' => '0.95'
                            },
                  'id' => '821397404',
                  'datetime' => '2021-04-23T01:23:03.844Z',
                  'side' => 'sell',
                  'timestamp' => '1619140983844'
                }
     };

#ftx: (info{time}) symbol price amount side id info{liquidation}

$s = {
       'symbols' => 'AAVE-0625',
       'exchange' => 'ftx',
       'recv_time' => '1619147564.06516',
       'dat' => {
                  'info' => {
                              'id' => 857552472,
                              'time' => '2021-04-23T03:12:43.927511+00:00',
                              'price' => '359.07',
                              'liquidation' => bless( do{\(my $o = 1)}, 'JSON::PP::Boolean' ),
                              'size' => '1.39',
                              'side' => 'buy'
                            },
                  'id' => '857552472',
                  'price' => '359.07',
                  'timestamp' => '1619147563927',
                  'side' => 'buy',
                  'datetime' => '2021-04-23T03:12:43.927Z',
                  'fee' => undef,
                  'cost' => '499.1073',
                  'amount' => '1.39',
                  'symbol' => 'AAVE-0625',
                  'order' => undef,
                  'type' => undef,
                  'takerOrMaker' => undef
                }
     };


#kucoin: info{time}/1000000000 symbol price amount side info{makerOrderId} info{takerOrderId}

$s = {
       'dat' => {
                  'side' => 'buy',
                  'timestamp' => '1619147564492',
                  'datetime' => '2021-04-23T03:12:44.492Z',
                  'info' => {
                              'symbol' => 'AAVE-BTC',
                              'makerOrderId' => '60823a7d82ed340006d2eafc',
                              'size' => '0.001',
                              'tradeId' => '60823b2c8336721f1130db62',
                              'type' => 'match',
                              'time' => '1619147564492212586',
                              'takerOrderId' => '60823b2c6ac0850006385035',
                              'sequence' => '1612815705242',
                              'price' => '0.006722',
                              'side' => 'buy'
                            },
                  'id' => '60823b2c8336721f1130db62',
                  'price' => '0.006722',
                  'takerOrMaker' => undef,
                  'order' => undef,
                  'type' => undef,
                  'cost' => '6.722e-06',
                  'fee' => undef,
                  'amount' => '0.001',
                  'symbol' => 'AAVE/BTC'
                },
       'recv_time' => '1619147564.56878',
       'symbols' => 'AAVE/BTC',
       'exchange' => 'kucoin'
     };





#coinbasepro: (info{time}) symbol price amount side id info{type}[0] info{taker_order_id}- info{maker_order_id}-

$s = {
       'dat' => {
                  'price' => '244.044',
                  'info' => {
                              'side' => 'sell',
                              'taker_order_id' => '3443cd1f-94a7-4828-9412-3b57f96f4a0b',
                              'trade_id' => 316853,
                              'time' => '2021-04-23T03:12:49.293715Z',
                              'price' => '244.044',
                              'sequence' => 161772785,
                              'product_id' => 'AAVE-GBP',
                              'maker_order_id' => '457a187e-da2c-4f02-8c5f-8ad2efde7dd8',
                              'type' => 'match',
                              'size' => '0.829'
                            },
                  'id' => '316853',
                  'datetime' => '2021-04-23T03:12:49.293Z',
                  'side' => 'buy',
                  'timestamp' => '1619147569293',
                  'symbol' => 'AAVE/GBP',
                  'amount' => '0.829',
                  'fee' => {
                             'rate' => undef,
                             'cost' => undef,
                             'currency' => undef
                           },
                  'cost' => '202.312476',
                  'order' => undef,
                  'type' => undef,
                  'takerOrMaker' => undef
                },
       'recv_time' => '1619147569.3479',
       'symbols' => 'AAVE/GBP',
       'exchange' => 'coinbasepro'
     };

#bitstamp: info{microtimestamp}/1000000 symbol price amount side id info{sell_order_id} info{buy_order_id}

$s = {
       'recv_time' => '1619147573.54741',
       'exchange' => 'bitstamp',
       'symbols' => 'BCH/USD',
       'dat' => {
                  'takerOrMaker' => undef,
                  'type' => undef,
                  'order' => undef,
                  'fee' => undef,
                  'cost' => '43.61672',
                  'amount' => '0.056',
                  'symbol' => 'BCH/USD',
                  'timestamp' => '1619147573402',
                  'side' => 'sell',
                  'datetime' => '2021-04-23T03:12:53.402Z',
                  'info' => {
                              'price_str' => '778.87',
                              'type' => 1,
                              'amount_str' => '0.05600000',
                              'amount' => '0.056',
                              'microtimestamp' => '1619147573402000',
                              'timestamp' => '1619147573',
                              'id' => 166731011,
                              'price' => '778.87',
                              'sell_order_id' => '1352960404459520',
                              'buy_order_id' => '1352960396931074'
                            },
                  'id' => '166731011',
                  'price' => '778.87'
                }
     };

#kraken: info[2] symbol price amount side

$s = {
       'dat' => {
                  'cost' => '216.384',
                  'fee' => undef,
                  'symbol' => 'AAVE/USD',
                  'amount' => '0.64',
                  'takerOrMaker' => undef,
                  'order' => undef,
                  'type' => 'market',
                  'info' => [
                              '338.10000',
                              '0.64000000',
                              '1619147575.199312',
                              'b',
                              'm',
                              ''
                            ],
                  'id' => undef,
                  'price' => '338.1',
                  'timestamp' => '1619147575199',
                  'side' => 'buy',
                  'datetime' => '2021-04-23T03:12:55.199Z'
                },
       'recv_time' => '1619147575.23437',
       'symbols' => 'AAVE/USD',
       'exchange' => 'kraken'
     };

`

* bitstamp: I'm not sure if their microtimestamp trailing 000 is significant

**Comment by gitcnd** [comment]
Here are some of the ones I noticed that I care about:

```
#phemex: info[0]/1000000000 symbol price amount side

$s = {               # 1619145594 396215031
       'recv_time' => '1619147560.08697',
       'symbols' => 'ADA/USD',
       'exchange' => 'phemex',
       'dat' => {
                  'datetime' => '2021-04-23T02:39:54.396Z',
                  'timestamp' => '1619145594396',
                  'side' => 'buy',
                  'price' => '0.9928',
                  'info' => [
                              '1619145594396215031',    # 2021/04/23 02:39:54.396215031
                              'Buy',
                              9928,
                              13
                            ],
                  'id' => undef,
                  'takerOrMaker' => undef,
                  'order' => undef,
                  'type' => undef,
                  'amount' => '0.0013',
                  'symbol' => 'ADA/USD',
                  'fee' => undef,
                  'cost' => undef
                }
     };



#gateio: info{time} symbol price amount side id

$s = {
       'exchange' => 'gateio',
       'symbols' => '1INCH/ETH',
       'recv_time' => '1619147562.55922',
       'dat' => {
                  'symbol' => '1INCH/ETH',
                  'amount' => '0.95',
                  'cost' => '0.0018297',
                  'fee' => undef,
                  'takerOrMaker' => undef,
                  'type' => undef,
                  'order' => undef,
                  'price' => '0.001926',
                  'info' => {
                              'type' => 'sell',
                              'id' => 821397404,
                              'time' => '1619140983.84418',
                              'price' => '0.001926',
                              'amount' => '0.95'
                            },
                  'id' => '821397404',
                  'datetime' => '2021-04-23T01:23:03.844Z',
                  'side' => 'sell',
                  'timestamp' => '1619140983844'
                }
     };

#ftx: (info{time}) symbol price amount side id info{liquidation}

$s = {
       'symbols' => 'AAVE-0625',
       'exchange' => 'ftx',
       'recv_time' => '1619147564.06516',
       'dat' => {
                  'info' => {
                              'id' => 857552472,
                              'time' => '2021-04-23T03:12:43.927511+00:00',
                              'price' => '359.07',
                              'liquidation' => bless( do{\(my $o = 1)}, 'JSON::PP::Boolean' ),
                              'size' => '1.39',
                              'side' => 'buy'
                            },
                  'id' => '857552472',
                  'price' => '359.07',
                  'timestamp' => '1619147563927',
                  'side' => 'buy',
                  'datetime' => '2021-04-23T03:12:43.927Z',
                  'fee' => undef,
                  'cost' => '499.1073',
                  'amount' => '1.39',
                  'symbol' => 'AAVE-0625',
                  'order' => undef,
                  'type' => undef,
                  'takerOrMaker' => undef
                }
     };


#kucoin: info{time}/1000000000 symbol price amount side info{makerOrderId} info{takerOrderId}

$s = {
       'dat' => {
                  'side' => 'buy',
                  'timestamp' => '1619147564492',
                  'datetime' => '2021-04-23T03:12:44.492Z',
                  'info' => {
                              'symbol' => 'AAVE-BTC',
                              'makerOrderId' => '60823a7d82ed340006d2eafc',
                              'size' => '0.001',
                              'tradeId' => '60823b2c8336721f1130db62',
                              'type' => 'match',
                              'time' => '1619147564492212586',
                              'takerOrderId' => '60823b2c6ac0850006385035',
                              'sequence' => '1612815705242',
                              'price' => '0.006722',
                              'side' => 'buy'
                            },
                  'id' => '60823b2c8336721f1130db62',
                  'price' => '0.006722',
                  'takerOrMaker' => undef,
                  'order' => undef,
                  'type' => undef,
                  'cost' => '6.722e-06',
                  'fee' => undef,
                  'amount' => '0.001',
                  'symbol' => 'AAVE/BTC'
                },
       'recv_time' => '1619147564.56878',
       'symbols' => 'AAVE/BTC',
       'exchange' => 'kucoin'
     };





#coinbasepro: (info{time}) symbol price amount side id info{type}[0] info{taker_order_id}- info{maker_order_id}-

$s = {
       'dat' => {
                  'price' => '244.044',
                  'info' => {
                              'side' => 'sell',
                              'taker_order_id' => '3443cd1f-94a7-4828-9412-3b57f96f4a0b',
                              'trade_id' => 316853,
                              'time' => '2021-04-23T03:12:49.293715Z',
                              'price' => '244.044',
                              'sequence' => 161772785,
                              'product_id' => 'AAVE-GBP',
                              'maker_order_id' => '457a187e-da2c-4f02-8c5f-8ad2efde7dd8',
                              'type' => 'match',
                              'size' => '0.829'
                            },
                  'id' => '316853',
                  'datetime' => '2021-04-23T03:12:49.293Z',
                  'side' => 'buy',
                  'timestamp' => '1619147569293',
                  'symbol' => 'AAVE/GBP',
                  'amount' => '0.829',
                  'fee' => {
                             'rate' => undef,
                             'cost' => undef,
                             'currency' => undef
                           },
                  'cost' => '202.312476',
                  'order' => undef,
                  'type' => undef,
                  'takerOrMaker' => undef
                },
       'recv_time' => '1619147569.3479',
       'symbols' => 'AAVE/GBP',
       'exchange' => 'coinbasepro'
     };

#bitstamp: info{microtimestamp}/1000000 symbol price amount side id info{sell_order_id} info{buy_order_id}

$s = {
       'recv_time' => '1619147573.54741',
       'exchange' => 'bitstamp',
       'symbols' => 'BCH/USD',
       'dat' => {
                  'takerOrMaker' => undef,
                  'type' => undef,
                  'order' => undef,
                  'fee' => undef,
                  'cost' => '43.61672',
                  'amount' => '0.056',
                  'symbol' => 'BCH/USD',
                  'timestamp' => '1619147573402',
                  'side' => 'sell',
                  'datetime' => '2021-04-23T03:12:53.402Z',
                  'info' => {
                              'price_str' => '778.87',
                              'type' => 1,
                              'amount_str' => '0.05600000',
                              'amount' => '0.056',
                              'microtimestamp' => '1619147573402000',
                              'timestamp' => '1619147573',
                              'id' => 166731011,
                              'price' => '778.87',
                              'sell_order_id' => '1352960404459520',
                              'buy_order_id' => '1352960396931074'
                            },
                  'id' => '166731011',
                  'price' => '778.87'
                }
     };

#kraken: info[2] symbol price amount side

$s = {
       'dat' => {
                  'cost' => '216.384',
                  'fee' => undef,
                  'symbol' => 'AAVE/USD',
                  'amount' => '0.64',
                  'takerOrMaker' => undef,
                  'order' => undef,
                  'type' => 'market',
                  'info' => [
                              '338.10000',
                              '0.64000000',
                              '1619147575.199312',
                              'b',
                              'm',
                              ''
                            ],
                  'id' => undef,
                  'price' => '338.1',
                  'timestamp' => '1619147575199',
                  'side' => 'buy',
                  'datetime' => '2021-04-23T03:12:55.199Z'
                },
       'recv_time' => '1619147575.23437',
       'symbols' => 'AAVE/USD',
       'exchange' => 'kraken'
     };


```

* bitstamp - I'm not sure if the microtimestamp trailing 000 is significant

**Comment by gitcnd** [comment]
Those are websockets (we've got a pro license) FYI - this is the code:
```
ts = await ex.watch_trades(sym)
```
