### ISSUE TITLE
Stale Price Feed from Binance USDT Futures & FTX

### ISSUE THREAD

**Issue by deceneucapital** [ccxt/ccxt#9046]
Hi Kroitor,

I think I'm getting a stale/delayed price feed from Binance USDT Futures and FTX. I only need the Best Bid & Offer from each of the exchanges pushed in real-time (I don't need orderbooks). Sometimes the FTX price or the Binance price just stops updating. Is there anything in the code you can see that would be causing this?

import threading
import asyncio
import ccxtpro
import loggin_util
from definitions.exchanges import Exchanges
from definitions.trading_util import ConnectionState
import ccxtpro_exchanges
import definitions.app_values as apv

# from principal import Principal

class DataFeedManager(threading.Thread):
    def __init__(self, exchange: Exchanges, symbol_name: str, data_coin_command, print_info: bool,
                 entry_delta: float, exit_delta: float, entry_size: float, _data_feed_stopped,
                 _executing_methods_event, assigned_pair_id):
        threading.Thread.__init__(self)
        self.exchange = exchange
        self.symbol_name = symbol_name
        self.print_info = print_info
        self.print_info = False  # for testing
        self.bid = 0.0
        self.ask = 0.0
        self.entry_delta = entry_delta
        self.exit_delta = exit_delta
        self.entry_size = entry_size
        self.logger = loggin_util.create_logger(__name__ + '_' + self.exchange.name + '_' +
                                                self.symbol_name.replace('/', ''))
        self.conn_state = ConnectionState.DISCONNECTED
        self.data_coin_command = data_coin_command
        self.data_feed_enabled = True
        self.data_feed_stopped = _data_feed_stopped
        self.executing_methods_event = _executing_methods_event
        self.binance_pro = ccxtpro.binance({'enableRateLimit': True,
                                            'options': {
                                                'defaultType': 'future',
                                            }})
        self.ftx_pro = ccxtpro.ftx({'enableRateLimit': True})
        self.assigned_pair_id = assigned_pair_id

        # print(self.symbol_id.replace('/', ''))

    async def get_tick(self):
        exchange_switcher = {
            Exchanges.binance: ccxtpro.binance({'enableRateLimit': True,
                                                'apiKey': apv.binance_api_key,
                                                'secret': apv.binance_secret_key,
                                                'options': {
                                                    'defaultType': 'future',
                                                    'watchTicker': {
                                                        'name': 'bookTicker'
                                                    }
                                                }}),
            Exchanges.ftx: ccxtpro.ftx({'enableRateLimit': True}),
        }
        exchange = exchange_switcher.get(self.exchange)
        while self.data_feed_stopped.wait():

            if not self.data_feed_enabled:
                print("Stopping Data Feed")
                self.data_feed_stopped.clear()
                print("Data Feed Stopped? %s" % self.data_feed_stopped)
                break

            if self.print_info: print("----------------------")
            if self.print_info: print("data_feed_enabled: %s" % self.data_feed_enabled)
            if self.print_info: print(exchange.id)
            if self.print_info: print("Symbol: ", self.symbol_name)

            try:
                # order_book = await exchange.watch_order_book(self.symbol_name)
                order_book = await exchange.watch_ticker(self.symbol_name)
            except Exception as e:
                self.conn_state = ConnectionState.DISCONNECTED
                self.logger.error('Disconnected')
                print("Exception: ", e)
                continue
            if self.conn_state == ConnectionState.DISCONNECTED:
                self.logger.info('Connected')
                self.conn_state = ConnectionState.CONNECTED

            # self.bid = order_book['bids'][0][0] if len(order_book['bids']) > 0 else None
            # self.ask = order_book['asks'][0][0] if len(order_book['asks']) > 0 else None
            self.bid = order_book['bid'] if order_book['bid'] is not None else self.bid
            self.ask = order_book['ask'] if order_book['ask'] is not None else self.ask
            spread = (self.ask - self.bid) if (self.bid and self.ask) else None
            mid = (self.bid + self.ask) / 2 if (self.bid and self.ask) else None
            if self.print_info: print("bid: ", self.bid)
            if self.print_info: print("ask: ", self.ask)
            if self.print_info: print("spread: ", spread)
            if self.print_info: print("mid: ", mid)
            self.data_coin_command(self.symbol_name,
                                   self.bid,
                                   self.ask,
                                   self.entry_delta,
                                   self.exit_delta,
                                   self.entry_size,
                                   self.executing_methods_event,
                                   self.assigned_pair_id)

    def run(self):
        asyncio.run(self.get_tick())

**Comment by kroitor** [comment]
Hi @deceneucapital !

Do you have this issue with the most recent version of CCXT Pro + the following script:

```Python
# -*- coding: utf-8 -*-

import ccxtpro
from asyncio import gather, get_event_loop


async def exchange_symbol_loop(exchange, symbol):
    print('Starting the', exchange.id, 'symbol loop with', symbol)
    while True:
        try:
            ticker = await exchange.watch_ticker(symbol)
            now = exchange.milliseconds()
            print(exchange.iso8601(now), exchange.id, symbol, ticker['bid'], ticker['ask'])
        except Exception as e:
            print(str(e))
            # raise e  # uncomment to break all loops in case of an error in any one of them
            break  # you can break just this one loop if it fails


async def exchange_loop(asyncio_loop, exchange_id, symbols):
    print('Starting the', exchange_id, 'exchange loop with', symbols)
    exchange = getattr(ccxtpro, exchange_id)({
        'enableRateLimit': True,
        'asyncio_loop': asyncio_loop,
        'options': {
            'defaultType': 'future',
            'watchTicker': {
                'name': 'bookTicker',
            },
        },
    })
    loops = [exchange_symbol_loop(exchange, symbol) for symbol in symbols]
    await gather(*loops)
    await exchange.close()


async def main(asyncio_loop):
    exchanges = {
        'ftx': ['BTC/USDT', 'ETH/BTC'],
        'binance': ['BTC/USDT', 'ETH/BTC'],
    }
    loops = [exchange_loop(asyncio_loop, exchange_id, symbols) for exchange_id, symbols in exchanges.items()]
    await gather(*loops)


if __name__ == '__main__':
    asyncio_loop = get_event_loop()
    asyncio_loop.run_until_complete(main(asyncio_loop))
```

Does it get stale?

**Comment by deceneucapital** [comment]
Will check and come back to you - thanks!

**Comment by deceneucapital** [comment]
That fixed it, thanks!

**Comment by kroitor** [comment]
@deceneucapital thank you for your feedback! We appreciate it!
