### ISSUE TITLE
Mess with the BCC and BCH currencies on the balance in BitBay

### ISSUE THREAD

**Issue by Felipe-Mangueira** [ccxt/ccxt#905]
Hi again, @kroitor.

I noticed that in fetch_order method in bitbay exchange, there is a confusion with the Bitcoin Cash code in the returned dictionary: in the 'info' key, the code is 'BCC' and in the others keys, the code is BCH. Please, could you fix this code to the default one used in ccxt (BCH). Please, see the returned dictionary as showed in the example below:

```
{'info': {'BTC': {'available': '0', 'locked': '0'}, 'BCC': {'available': '0.15000000', 'locked': '0'}, 'EUR': {'available': '0', 'locked': '0'}, 'PLN': {'available': '0', 'locked': '0'}, 'GAME': {'available': '0', 'locked': '0'}, 'BTG': {'available': '0', 'locked': '0'}, 'LSK': {'available': '0', 'locked': '0'}, 'USD': {'available': '0', 'locked': '0'}, 'ETH': {'available': '0', 'locked': '0'}, 'LTC': {'available': '1.00000000', 'locked': '0'}, 'DASH': {'available': '0', 'locked': '0'}}, 'BCH': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'BTC': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'BTG': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'DASH': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'ETH': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'EUR': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'GAME': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'LSK': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'LTC': {'free': 1.0, 'used': 0.0, 'total': 1.0}, 'PLN': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'USD': {'free': 0.0, 'used': 0.0, 'total': 0.0}, 'free': {'BCH': 0.0, 'BTC': 0.0, 'BTG': 0.0, 'DASH': 0.0, 'ETH': 0.0, 'EUR': 0.0, 'GAME': 0.0, 'LSK': 0.0, 'LTC': 1.0, 'PLN': 0.0, 'USD': 0.0}, 'used': {'BCH': 0.0, 'BTC': 0.0, 'BTG': 0.0, 'DASH': 0.0, 'ETH': 0.0, 'EUR': 0.0, 'GAME': 0.0, 'LSK': 0.0, 'LTC': 0.0, 'PLN': 0.0, 'USD': 0.0}, 'total': {'BCH': 0.0, 'BTC': 0.0, 'BTG': 0.0, 'DASH': 0.0, 'ETH': 0.0, 'EUR': 0.0, 'GAME': 0.0, 'LSK': 0.0, 'LTC': 1.0, 'PLN': 0.0, 'USD': 0.0}}
```
- OS: Windows 10
- Language: English
- CCXT version: 1.10.412
- Exchange: BitBay
- Method: fetch_balance

**Comment by kroitor** [comment]
Hi, @Felipe-Mangueira ! You're interpreting the returned value incorrectly. [From the Manual](https://github.com/ccxt/ccxt/wiki/Manual#querying-account-balance):

```JavaScript
{
    'info':  { ... },    // the original untouched non-parsed reply with details

    //-------------------------------------------------------------------------
    // indexed by availability of funds first, then by currency

    'free':  {           // money, available for trading, by currency
        'BTC': 321.00,   // floats...
        'USD': 123.00,
        ...
    },

    'used':  { ... },    // money on hold, locked, frozen, or pending, by currency

    'total': { ... },    // total (free + used), by currency

    //-------------------------------------------------------------------------
    // indexed by currency first, then by availability of funds

    'BTC':   {           // string, three-letter currency code, uppercase
        'free': 321.00   // float, money available for trading
        'used': 234.00,  // float, money on hold, locked, frozen or pending
        'total': 555.00, // float, total balance (free + used)
    },

    'USD':   {           // ...
        'free': 123.00   // ...
        'used': 456.00,
        'total': 579.00,
    },

    ...
}
```

The `info` field is the reply from the exchange itself, as is, untouched, unparsed by ccxt. Because we don't touch the contents of that field and return it along with other fields, you can see that some exchanges are having non-unified BCC currency codes instead of BCH... 

However you should not look into that `info` field in the first place, if you're working with the unified API. Look at all other fields around the `info` field. All other fields are unified and standardized / categorized, so you can easily access `balance['free']['BCH']`, or `balance['BCH']['total']`... And currency naming is correct (BCH) in the Unified API. No mess there. So, most of the time you should not look into exchange-specific `info`, that is *for technical purposes only*... 

Note, the same is true for unified methods – they return an object containing untouched raw `info` and a bunch of unified fields added around `info`. Let me know if the above answers your question or not.

**Comment by Felipe-Mangueira** [comment]
Sorry, @kroitor, but i was not so clear: there is no problem with the unified API. However, I actually have 0.15 BCH on my account, but 0.15 is not the value showed on balance['free']['BCH'], its 0. So, where is the problem? Why cannot I access the correct balance of BCH on balance['free']['BCH']?

**Comment by kroitor** [comment]
@Felipe-Mangueira ok, this must be a bug then, now I got it, thanks for the clarification. Will look into it and will fix it asap.

**Comment by Felipe-Mangueira** [comment]
Ok, @kroitor, thank you!!

**Comment by kroitor** [comment]
Fixed in 1.10.421. Thx for reporting!

**Comment by kroitor** [comment]
Oh, sorry, apparently, there's one more bug there... Will get back to you on this very soon.

**Comment by Felipe-Mangueira** [comment]
No problem, @kroitor, I'm waiting patiently

**Comment by kroitor** [comment]
@Felipe-Mangueira can you please try 1.10.422 now?

**Comment by Felipe-Mangueira** [comment]
@kroitor, it's working fine! Thank you once again!

**Comment by Felipe-Mangueira** [comment]
@kroitor, sorry for keeping disturbing you with this BCH code issue, but the withdraw and create_order methods with this currency is not working properly:

About the withdraw method:

When I run...
```
transfer_order = bitbay.withdraw('BCC', 0.1, 'anyaddress')
```
...it works fine.
But when I run...
```
transfer_order = bitbay.withdraw('BCH', 0.1, 'anyaddress')
```
... it does not work properly (a ccxt.base.errors.ExchangeNotAvailable is raised).

About the create_order method:

When I run...
```
limit_order = bitbay.create_order('BCH/PLN', 'limit', 'sell', 0.05, 12000)
```
... it does not work properly (I get the dictionary {'code': 510, 'message': 'Invalid market name'}).

And when I run...
```
limit_order = bitbay.create_order('BCC/PLN', 'limit', 'sell', 0.05, 12000)
```
... it does not work properly as well (the follow error is raised: ccxt.base.errors.ExchangeError: bitbay does not have market symbol BCC/PLN)

Could you also take a look at this two methods for me? I suppose that it might have more issues involving this currency, so If you have more time, please make a general check up with the codes of BCH from Bitbay exchange. If not, I will report to you as soon as I detect a new issue.

Thanks for your continuous suppot.

**Comment by kroitor** [comment]
> Could you also take a look at this two methods for me?

Done in 1.10.424.

> I suppose that it might have more issues involving this currency

I would also suspect that, but it turns out that there are no unified methods left for now %) The rest of them are still not implemented yet. All existing unified methods (the ones that are implemented already) should now work normally with all symbols and currencies. However, if you can do some testing of your use-cases and report back, you would really help us a lot! Thx!

**Comment by Felipe-Mangueira** [comment]
Sure. I'll test it right now. Meanwhile, if i notice any new issue, I report back to you.
Thank you!

**Comment by Felipe-Mangueira** [comment]
@kroitor, apparently, it's working as expected. Thx!

**Comment by kroitor** [comment]
@Felipe-Mangueira thank you for the feedback, we will be happy to help further.

**Comment by Felipe-Mangueira** [comment]
Ok, @kroitor, thanks for your helpfulness!
