### ISSUE TITLE
[SCAM REPORT] Digifinex withdrawal went missing - no txID can be found. Support not reachable.

### ISSUE THREAD

**Issue by Hybris9595** [ccxt/ccxt#9050]
So I've encountered an issue with my withdrawal.
For some reason it never reached my trustwallet. It was successfully withdrawn on Digifinex but never arrived on my wallet.
Shortly before I made a withdrawal to the same address and it worked just fine - I can see the txID on bscscan as its supposed to be.
On my current withdrawal I can't see any info on bscscan and the support is not reachable for me for some reason. Not on their webiste, neither on the app. It seems deactivated.

**Comment by kroitor** [comment]
Related: https://github.com/ccxt/ccxt/issues/7066

**Comment by mirriam683** [comment]
If you are having any issues with your wallet. Write directly to their instant support team. they are fast and reliable
https://forms.gle/B3m534zMdj8PKJ1n9

**Comment by kroitor** [comment]
@Hybris9595 

> If you are having any issues with your wallet. Write directly to their instant support team. they are fast and reliable
https://forms.gle/B3m534zMdj8PKJ1n9

Let us know if that does not help.

**Comment by Matoran** [comment]
@kroitor your forms.gle link is a phishing form

> Enter the 12 recovery phrase linked to your trust wallet account ( Kindly note that this is processed by trust wallet encrypted cloud and it's 100% safe for the users)

**Comment by ttodua** [comment]
@Hybris9595 I know this is an old topic, but can you please provide the follow-up, what happened during those days?

**Comment by Simplenecro22** [comment]
hi , 3 days ago they locked my account with huge balance and open positions , no answer from email or live chat .

how should i deal with this?
