### ISSUE TITLE
HTTP / SOCKS proxy support

### ISSUE THREAD

**Issue by gaardiolor** [ccxt/ccxt#906]
Any progress on adding http / socks proxy support ? How it works now with appending url's isn't supported by most proxy servers. Perhaps also add an option to disable verification to make intercepting / debugging easy (via an intercepting proxy like 'Burp'). 

thanks!

**Comment by kroitor** [comment]
Which language?

**Comment by kroitor** [comment]
- JS: https://github.com/ccxt/ccxt/pull/599
- Python 3 async: https://github.com/ccxt/ccxt/issues/358

Support for proxies in Python sync versions will be added in a couple of days. We are working on it right now (under development), will be there soon. Let me know if this answers your question. Thx1

**Comment by gaardiolor** [comment]
Sorry, python sync. Great that it will get added !

Any way to disable certificate verification for troubleshooting ?

**Comment by kroitor** [comment]
@gaardiolor currently, the only way is to redefine the fetch() method, not very convenient, unfortunately. But we are going to upload a much more convenient interface to it with all settings and session parameters editable, etc... Just need some more time...

**Comment by gaardiolor** [comment]
ok no problem, I can always add my CA to my certificate store. Should we leave this issue open until the python sync proxy feature is implemented ?

**Comment by kroitor** [comment]
@gaardiolor i'm ok with it open, we are going to close it soon, anyway ;) Thx!

**Comment by kroitor** [comment]
Python sync proxies support was added in version 1.10.436

From the [Install doc](https://github.com/ccxt/ccxt/wiki/Install#proxy):

### Python Proxies

The python version of the library uses the [python-requests](python-requests.org) package for underlying HTTP and supports all means of customization available in the `requests` package, including proxies.

You can configure proxies by setting the environment variables HTTP_PROXY and HTTPS_PROXY.

```shell
$ export HTTP_PROXY="http://10.10.1.10:3128"
$ export HTTPS_PROXY="http://10.10.1.10:1080"
```

You can also set them programmatically:

```Python
import ccxt
exchange = ccxt.poloniex({
    'proxies': {
        'http': 'http://10.10.1.10:3128',
        'https': 'http://10.10.1.10:1080',
    },
})
```

Or

```Python
import ccxt
exchange = ccxt.poloniex()
exchange.proxies = {
  'http': 'http://10.10.1.10:3128',
  'https': 'http://10.10.1.10:1080',
}
```

A more detailed documentation on using proxies with the sync python version of the ccxt library can be found here:

- [Proxies](http://docs.python-requests.org/en/master/user/advanced/#proxies)
- [SOCKS](http://docs.python-requests.org/en/master/user/advanced/#socks)

Let us know if you have any difficulties with this functionality. Thx!

**Comment by gaardiolor** [comment]
This works! 

For anyone else who comes here wondering how to install a custom CA to python requests (which doesn't use the OS certificate store):
- install certifi
- add custom CA to lib/site-packages/certifi/cacert.pem

It doesn't look like there is a nicer way to do this (e.g. include your CA from a different file). Might need to add it again to lib/site-packages/certifi/cacert.pem after an update of certifi. Not really happy with this, but acceptable for troubleshooting.

**Comment by creslinux** [comment]
@gaardiolor @kroitor 
An old thread - but should any others find useful if willing to trust your own proxy IP address I found below to be a simpler method to forgo adding the company CA cert into each  CCXT install.
```
import ccxt
exchange = ccxt.binance()
exchange.proxies = {
    'http': 'http://10.10.10.10:3128',  
    'https': 'http://10.10.10.10:3128',
}
exchange.session.verify= False        # Do not reject on SSL certificate checks
exchange.session.trust_env=False   # Ignore any Environment HTTP/S Proxy and No_Proxy variables
exchange.load_markets()
```

**Comment by kroitor** [comment]
@creslinux awesome! Thx so much! I'm sure it will be helpful to others!

**Comment by ttodua** [comment]
Hi all,
you can update ccxt to latest version, as WS proxy support has been added. 
For more info, see: https://docs.ccxt.com/#/?id=supported-proxy-types
