### ISSUE TITLE
yarl==1.1.0 needed?

### ISSUE THREAD

**Issue by r4VP4** [ccxt/ccxt#9075]
- OS: Windows 10
- Programming Language version: Python 3.8.7
- CCXT version: 1.48.84

Installing ccxt and gql==3.0.0a5 brings this warning!

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ccxt 1.48.84 requires yarl==1.1.0; python_version >= "3.5.2", but you have yarl 1.6.3 which is incompatible.
```

Is the fixation to yarl==1.1.0 needed for ccxt?

**Comment by kroitor** [comment]
Let us know if you have this issue with the most recent version of CCXT! Thanks for your feedback!
