### ISSUE TITLE
Upbit market order doesn't work.

### ISSUE THREAD

**Issue by jeonghwan-kang** [ccxt/ccxt#9079]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows 10 64bit
- Programming Language version:
- CCXT version: 1.47.61

```
import ccxt

API_KEY = ''
SECRET_KEY = ''

exchange = ccxt.upbit({
    'apiKey' : API_KEY,
    'secret' : SECRET_KEY,
})

exchange.create_market_buy_order('SRM/KRW', 1)
```

```
Traceback (most recent call last):
  File "/test.py", line 28, in <module>
    exchange.create_market_buy_order('SRM/KRW', 1)
  File "C:\Users\chanelacy\anaconda3\lib\site-packages\ccxt\base\exchange.py", line 1981, in create_market_buy_order
    return self.create_order(symbol, 'market', 'buy', amount, None, params)
  File "C:\Users\chanelacy\anaconda3\lib\site-packages\ccxt\upbit.py", line 820, in create_order
    raise InvalidOrder(self.id + " createOrder() requires the price argument with market buy orders to calculate total order cost(amount to spend), where cost = amount * price. Supply a price argument to createOrder() call if you want the cost to be calculated for you from price and amount, or, alternatively, add .options['createMarketBuyOrderRequiresPrice'] = False to supply the cost in the amount argument(the exchange-specific behaviour)")
ccxt.base.errors.InvalidOrder: upbit createOrder() requires the price argument with market buy orders to calculate total order cost(amount to spend), where cost = amount * price. Supply a price argument to createOrder() call if you want the cost to be calculated for you from price and amount, or, alternatively, add .options['createMarketBuyOrderRequiresPrice'] = False to supply the cost in the amount argument(the exchange-specific behaviour)
```

**Comment by kroitor** [comment]
Hi!

Do you have an issue with this error message or is it not clear?

ccxt.base.errors.InvalidOrder: upbit createOrder() requires the price argument with market buy orders to calculate total order cost(amount to spend), where cost = amount * price. Supply a price argument to createOrder() call if you want the cost to be calculated for you from price and amount, or, alternatively, add .options['createMarketBuyOrderRequiresPrice'] = False to supply the cost in the amount argument(the exchange-specific behaviour)

**Comment by jeonghwan-kang** [comment]
That's right. But I can't understand why price need to market order.

**Comment by kroitor** [comment]
```Python
import ccxt

API_KEY = ''
SECRET_KEY = ''

exchange = ccxt.upbit({
    'enableRateLimit': True,  # https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
    'apiKey' : API_KEY,
    'secret' : SECRET_KEY,
})

markets = exchange.load_markets()

# exchange.verbose = True

amount = 1
price = YOUR_PRICE_HERE 
exchange.create_order('SRM/KRW', 'market', 'buy', amount, price)
```

Let us know if the above does not answer your question.

**Comment by kroitor** [comment]
@jeonghwan-kang upbit requires a total cost for market-buy orders. And, logically, cost (KRW) = amount (SRM) * price (KRW).
There's two ways to specify the cost:
1. either also supply the price for CCXT to calculate it:

```Python
exchange.create_order('SRM/KRW', 'market', 'buy', amount, price)
```

2. or set exchange.options and supply the cost (in quote currency KRW) as amount

```Python
exchange.options['createMarketBuyOrderRequiresPrice'] = False
exchange.create_market_buy_order('SRM/KRW', YOUR_COST_HERE)
```

Feel free to reopen this issue or just ask further questions if any.

**Comment by jeonghwan-kang** [comment]
But I don't know.
I input amount=1 and price = 20000
And It buy total round 20,000. and quantity is over 1. Exactly 1.5974.

Amount doesn't mean quantity?

**Comment by kroitor** [comment]
@jeonghwan-kang do not confuse these three things:

- amount (how much SRM)
- price (for how much KRW per SRM)
- cost = amount (SRM) * price (KRW) = cost (KRW)

When your amount is 1 and your price is 20000, that means your cost will be 20000 KRW. So you will spend 20000 KRW to buy SRM. How much SRM you get for your 20000 KRW – depends on the current price of SRM. Therefore you get 1.5974 SRM for your 20000 KRW. 

Does that answer your question?

**Comment by jeonghwan-kang** [comment]
Thank you. I understood. Have a good day!
