### ISSUE TITLE
commonCurrencies (symbols mapping) not applied

### ISSUE THREAD

**Issue by c0dehunter** [ccxt/ccxt#9080]
I added mapping for coin "CHI" -> "CHI2" to [coinex.php](https://github.com/ccxt/ccxt/blob/master/php/coinex.php#L151)  to `commonCurrencies` because on our system we use the CHI2 instead of CHI. But it seems it not taken into consideration, we still get "CHI" as output. I checked the code, it seems the `common_currency_code()` in [Exchange.php:safe_currency()](https://github.com/ccxt/ccxt/blob/2e64277ed91463fae8169883d3ae9f288d6eb82d/php/Exchange.php#L2078)  is never reached. 

Do we need to enable the mapping somehow? I checked how it works in "binance.php" and just followed same pattern without any luck.

![image](https://user-images.githubusercontent.com/1484658/116231302-f7209380-a758-11eb-83c2-063ca6ff3ef1.png)

**Comment by kroitor** [comment]
Hey! Have you solved this? You don't have to edit the source for that, cause you can override all properties using the constructor params.

**Comment by c0dehunter** [comment]
Hey @kroitor, yes it was a mistake on our side. Working correctly now. I am aware of the possibility to override properties and will rewrite it as such. Thanks!
