### ISSUE TITLE
CCXT missing some trades

### ISSUE THREAD

**Issue by rbdm-qnt** [ccxt/ccxt#9081]
Hi,

I'm using CCXT to download aggTrades from Binance; sometimes, for a few hours, it looks like Binance can't provide trades, as you can see here from 3:59AM to 8AM:

"Binance - ETH/USDT - 2021-04-25T00:59:40.174Z - 24394 trades
Binance - ETH/USDT - 2021-04-25T01:59:38.974Z - 19803 trades
Binance - ETH/USDT - 2021-04-25T02:59:38.711Z - 33256 trades
Binance - ETH/USDT - 2021-04-25T03:59:37.932Z - 443 trades
Binance - ETH/USDT - 2021-04-25T04:00:57.550Z - 1 trades
Binance - ETH/USDT - 2021-04-25T05:00:57.550Z - 0 trades
Binance - ETH/USDT - 2021-04-25T06:00:57.550Z - 0 trades
Binance - ETH/USDT - 2021-04-25T07:00:57.550Z - 0 trades
Binance - ETH/USDT - 2021-04-25T08:00:57.550Z - 15619 trades
Binance - ETH/USDT - 2021-04-25T09:00:57.262Z - 69031 trades
Binance - ETH/USDT - 2021-04-25T10:00:57.238Z - 71676 trades
Binance - ETH/USDT - 2021-04-25T11:00:57.217Z - 44956 trades
Binance - ETH/USDT - 2021-04-25T12:00:57.021Z - 53653 trades"

You can see that the 8AM slot only has 15k trades, so it probably resumed downloading from 7:40AM or something.

This is probably an issue on Binance side I imagine, but by any change does anybody know if there is a fix for this?

I'm using CCXT 1.39.36 on Python 3.8 on Ubuntu 18.04.

**Comment by kroitor** [comment]
@rbdm-qnt first of all, i'd recommend updating to the most recent version of CCXT asap. As for the gaps – you can verify what exactly is happening in verbose mode: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
Unfortunately, without a very detailed code and output we can only guess what could be a possible cause, hope for your understanding. If you can provide a code to reproduce + the verbose log, we will look into it.

**Comment by kroitor** [comment]
JFYI, Binance has pushed a number of updates to the Spot API recently: https://t.me/binance_api_announcements

**Comment by rbdm-qnt** [comment]
Thank you so much for your quick response! I updated to the latest version, but nothing changed; 
the code I'm using to download is pretty much this: https://github.com/ccxt/ccxt/blob/master/examples/py/binance-fetch-all-trades.py

Here's the verbose output:


Request: GET https://api.binance.com/api/v3/aggTrades?symbol=ETHUSDT&startTime=1619323257550&endTime=1619326857550 {'User-Agent': 'python-requests/2.25.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.binance.com/api/v3/aggTrades?symbol=ETHUSDT&startTime=1619323257550&endTime=1619326857550 200 {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '119', 'Connection': 'keep-alive', 'Date': 'Tue, 27 Apr 2021 13:10:17 GMT', 'Server': 'nginx', 'x-mbx-uuid': '00478fa8-cf3c-4869-bd44-a907f934bd55', 'x-mbx-used-weight': '7', 'x-mbx-used-weight-1m': '7', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, HEAD, OPTIONS', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 66dd60a280ca9f6b133d158ccf4dd40a.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'AMS50-C1', 'X-Amz-Cf-Id': 'GHC_7HnTiU-UtL54fF5wbe3oCJxpCyiGgNxDowxOtYGFPwEpqLFTWQ=='} [{"a":315295707,"p":"2193.43000000","q":"0.63867000","f":376013847,"l":376013847,"T":1619323257550,"m":false,"M":true}]
Binance - ETH/USDT - 2021-04-25T04:00:57.550Z - 1 trades

Request: GET https://api.binance.com/api/v3/aggTrades?symbol=ETHUSDT&startTime=1619326857550&endTime=1619330457550 {'User-Agent': 'python-requests/2.25.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.binance.com/api/v3/aggTrades?symbol=ETHUSDT&startTime=1619326857550&endTime=1619330457550 200 {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '2', 'Connection': 'keep-alive', 'Date': 'Tue, 27 Apr 2021 13:10:17 GMT', 'Server': 'nginx', 'x-mbx-uuid': '17d9e89d-2694-4dea-8db1-c192dd7cb277', 'x-mbx-used-weight': '8', 'x-mbx-used-weight-1m': '8', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, HEAD, OPTIONS', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 66dd60a280ca9f6b133d158ccf4dd40a.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'AMS50-C1', 'X-Amz-Cf-Id': '8dwfS1d3EL2UFdqxFxuYZ0fOIcXkgKa2qPygyZQjwf0AdWqQnmA-oA=='} []
Binance - ETH/USDT - 2021-04-25T05:00:57.550Z - 0 trades

Request: GET https://api.binance.com/api/v3/aggTrades?symbol=ETHUSDT&startTime=1619330457550&endTime=1619334057550 {'User-Agent': 'python-requests/2.25.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.binance.com/api/v3/aggTrades?symbol=ETHUSDT&startTime=1619330457550&endTime=1619334057550 200 {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '2', 'Connection': 'keep-alive', 'Date': 'Tue, 27 Apr 2021 13:10:18 GMT', 'Server': 'nginx', 'x-mbx-uuid': 'a5ad9d93-ffe8-49bd-a76c-fc47d218d949', 'x-mbx-used-weight': '9', 'x-mbx-used-weight-1m': '9', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, HEAD, OPTIONS', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 66dd60a280ca9f6b133d158ccf4dd40a.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'AMS50-C1', 'X-Amz-Cf-Id': 'Nj6d5-1yHOIg-E9GC1Xk3NhmPnOPrCCiOArdIeTQOVuO-sWyrj-oKg=='} []
Binance - ETH/USDT - 2021-04-25T06:00:57.550Z - 0 trades

Request: GET https://api.binance.com/api/v3/aggTrades?symbol=ETHUSDT&startTime=1619334057550&endTime=1619337657550 {'User-Agent': 'python-requests/2.25.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.binance.com/api/v3/aggTrades?symbol=ETHUSDT&startTime=1619334057550&endTime=1619337657550 200 {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '2', 'Connection': 'keep-alive', 'Date': 'Tue, 27 Apr 2021 13:10:18 GMT', 'Server': 'nginx', 'x-mbx-uuid': 'd5077230-69c1-427e-8e34-14ddf630cec2', 'x-mbx-used-weight': '10', 'x-mbx-used-weight-1m': '10', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains', 'X-Frame-Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, HEAD, OPTIONS', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 66dd60a280ca9f6b133d158ccf4dd40a.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'AMS50-C1', 'X-Amz-Cf-Id': 'gchbNdF5IERajO3nIL8SQuLtlLIECv0x1MTE1n1ZK9VIJzp8DWYqxQ=='} []
Binance - ETH/USDT - 2021-04-25T07:00:57.550Z - 0 trades

**Comment by rbdm-qnt** [comment]
Even just manually clicking on those links I can see that there are simply no trades on the Binance's servers at that URL. Is there any workaround to this? Maybe requesting trades instead of aggTrades?

**Comment by kroitor** [comment]
@rbdm-qnt yes, that script can be modified to jump over the gaps.

**Comment by rbdm-qnt** [comment]
> @rbdm-qnt yes, that script can be modified to jump over the gaps. Though, i find it very weird for ETH/USDT to have no trades. Need a bit more time to investigate.

I don't want to jump over the gaps (it's already doing so, the code isn't stopping). I'm checking other sources and it seems that Binance simply lost that data, you either recorded it in real time or you don't have it. 

Anyhow, this is downloaded directly from Binance servers:

315295706 | 2193.45 | 0.01 | 376013846 | 376013846 | 1619323256542 | False | True
315295707 | 2193.43 | 0.63867 | 376013847 | 376013847 | 1619323257550 | False | True
315295708 | 2193.33 | 0.54096 | 376013848 | 376013848 | 1619340301958 | False | True
315295709 | 2193.33 | 0.00615 | 376013849 | 376013849 | 1619340301978 | True | True

it skips 4 hours; case closed!
