### ISSUE TITLE
sapi_get_margin_isolated_account

### ISSUE THREAD

**Issue by kwadwobro1** [ccxt/ccxt#9082]
Please can someone help with the file in which the function sapi_get_margin_isolated_account is defined in the ccxt source tree

**Comment by kroitor** [comment]
This is covered in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#implicit-api-methods

I would highly recommend reading the entire Manual from top to bottom at least once – it will save your time:

- https://github.com/ccxt/ccxt/wiki
- https://github.com/ccxt/ccxt/wiki/Manual

**Comment by kwadwobro1** [comment]
Please with all due respect, please did you read my question? What I need help about is in which file among the source code of ccxt is the function sapi_get_margin_isolated_account defined in

**Comment by kroitor** [comment]
@kwadwobro1 please, click the first link i've posted above and read.
