### ISSUE TITLE
Limit parameter does not work in call

### ISSUE THREAD

**Issue by ttodua** [ccxt/ccxt#9083]
For example, [this ](https://ascendex.com/api/pro/v1/trades?symbol=BTC/USDT&n=20) returns 20 entries. But from ccxt limit parameter doesnt work, and still returns only 10 entries.

exchange.fetchTrades("BTC/USDT").then(myCallback, undefined, 20);

**Comment by kroitor** [comment]
You have an error in your code (wrongfully-placed arguments to the `fetchTrades` call):

```JavaScript
exchange.fetchTrades("BTC/USDT").then(myCallback, undefined, 20);
```

↓

```JavaScript
exchange.fetchTrades("BTC/USDT", undefined, 20).then(myCallback);
```

Let us know if that does not answer your question.

**Comment by ttodua** [comment]
OUCH, i dont believe i did such stupid. sorry and thanks! :))
