### ISSUE TITLE
is there no plan to update upbit.py?

### ISSUE THREAD

**Issue by jeonghwan-kang** [ccxt/ccxt#9086]
I don't know It is proper way to ask.

Is there any plan to update fetch_my_trade for upbit? for python?

If it is not proper way to ask update, reply to me.

Then I'll delete this issue. Thank you, always.

ccxt                           ver. 1.47.61
os                              ver. Win10 64bit

**Comment by kroitor** [comment]
> Is there any plan to update fetch_my_trade for upbit? for python?

If you have an issue with it, please provide the following details, including your version numbers, your code (without your keys), your request+response output in verbose mode:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

**Comment by jeonghwan-kang** [comment]
I update main!

**Comment by kroitor** [comment]
@jeonghwan-kang please, read this link and follow every step precisely: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by ttodua** [comment]
The issue didn't get any follow-up and was left without any detail to explain the issue. Closing for now.
If anyone has any issue, let us know.
