### ISSUE TITLE
wrong status in upbit fetch_withdraws status

### ISSUE THREAD

**Issue by uxtt2000** [ccxt/ccxt#9089]
Hello

for upbit withdraws there are inconsistent statuses in the unified dict.
eg 'DONE' instead of 'ok'
the suggested problem and solution is:
upbit returns the statuses in ALLCAPS, the status mapping is lowercase, so:

in:
upbit.py 
in the method:
parse_transaction

in lines 968-975
the mapping needs to bee ALLCAPS (as for the deposits)
hence the mapping fails and the original value is propagated

or in line 1022
safe_string_lower should be called instead of safe_string

`status = self.parse_transaction_status(self.safe_string(transaction, 'state'))`

apologies if this suggestion is not correct 
thanks for developing this. Looking fwd to use the library in the future

Kind regards

Max

**Comment by kroitor** [comment]
@uxtt2000 thx for reporting, fixed in 1.49.7!
