### ISSUE TITLE
examples/py/fetch-ohlcv-sequentially.py with GDAX does not work anymore

### ISSUE THREAD

**Issue by spallesen** [ccxt/ccxt#909]
Easy to replicate - just try it with [ccxt/examples/py/fetch-ohlcv-sequentially.py](https://github.com/ccxt/ccxt/blob/master/examples/py/fetch-ohlcv-sequentially.py) with Gdax as the exchange and from_datetime = '2017-12-01 00:00:00' (just to reduce the number of bars)

The bars are out of order with a wrong start date and ends with the error: IndexError: list index out of range.

3 days ago this was working fine - maybe the API have changed. Anyway would be nice if someone could verify the root cause. Thx.

**Comment by kroitor** [comment]
Hi! Thank you for reporting! I will take a look into it soon and will get back to you with an update on this.

**Comment by kroitor** [comment]
This is now working normally, let us know if you still have problems with it. Thank you!
