### ISSUE TITLE
Is there a way to distinguish Spot, Margin and Futures trades in fetchMyTrades

### ISSUE THREAD

**Issue by powwr** [ccxt/ccxt#9091]
Is there a way to distinguish Spot, Margin and Futures trades in fetchMyTrades?
Are there any fields or markers that can tell me which type trade in the past was?

There is an Account Type, but as long as I get trades are mixed in Trade History, so account type doesn't help at all, as there could be Margin trades and then Spot trades, etc.

![image](https://user-images.githubusercontent.com/55096169/116519212-e3506b00-a8d9-11eb-8e7d-8b0dd4a3c371.png)

Thanks a lot!

**Comment by kroitor** [comment]
@powwr

> There is an Account Type, but as long as I get trades are mixed in Trade History, so account type doesn't help at all, as there could be Margin trades and then Spot trades, etc.

When you fetch margin trades, you should get margin trades only (without the spot trades) and vice versa.
So the general way of doing this is to just have two instances of the same exchange and fetch the trade history separately for each defaultType.

Let us know if that does not answer your question.
