### ISSUE TITLE
Convert Symbols between Internal API to CCXT

### ISSUE THREAD

**Issue by leonardoaraujosantos** [ccxt/ccxt#9096]
I have the following function to set the Leverage size on Binance Future APIs (calling fapiPrivate_post_leverage)

```python
    def set_leverage(self, symbol: str, leverage: int):
        """
        Set leverage size ie: 1x .. 125x
        """
        result = self.binance.fapiPrivate_post_leverage({
            'symbol': symbol,
            'leverage': leverage,
        })
        self.leverage = leverage
        return result
```
The issue is that the parameter symbol will be compatible with internal Binance Rest API (BTCUSDT) instead of the common symbol name inside CCXT (BTC/USDT) there is any internal method that does this conversion?

**Comment by kroitor** [comment]
> there is any internal method that does this conversion?

Of course! This is covered in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#methods-for-markets-and-currencies

Make sure you load the markets first!

In general, I'd highly recommend reading the entire Manual from top to bottom at least once – it has the answers to most of starting questions and it will really save your time.

- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/wiki/Manual

Let us know if the above does not help.

**Comment by leonardoaraujosantos** [comment]
Awesome @kroitor thanks, I'm adding here for reference
```python
    def set_margin_type(self, symbol: str, type_name: str):
        """
        Set margin type (CROSSED/ISOLATED)
        """
        internal_symbol = self.binance.markets[symbol]['id']
        result = self.binance.fapiPrivate_post_margintype({
            'symbol': internal_symbol,
            'marginType': type_name,
        })
        return result
```
