### ISSUE TITLE
Getting more error information?

### ISSUE THREAD

**Issue by codemonkeyno1** [ccxt/ccxt#9098]
Python3.8, 
Hi, sometimes I get random errors from ccxt when I send/cancel orders, and I don't get much information from the try/catch exception.  If I try to print the exception I only get the following:
`ftx POST https://ftx.com/api/orders`

This is from submitting the order using something like this:
`order = exchange.create_order('BTC/USD','limit','buy',0.01,50000)`
Most of the time it works, but sometimes (maybe 1% of the time), it will give the `ftx POST https://ftx.com/api/orders` exception.  Is there any way to get more information about the error using the ccxt API?

Thank you for any advice.

**Comment by kroitor** [comment]
> Is there any way to get more information about the error using the ccxt API?

Yes, check this section, especially `verbose` option which you can control:

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

In general, we highly recommend reading the entire Manual from top to bottom – it will really save your time:

- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/wiki/Manual

Also see the examples here: https://github.com/ccxt/ccxt/tree/master/examples

Let us know if that does not answer your question.

**Comment by kroitor** [comment]
```Python
exchange.verbose = True  # Add this line before the problematic call:

order = exchange.create_order('BTC/USD','limit','buy',0.01,50000)
```
