### ISSUE TITLE
exchange.timeframes['1d'] missing from ByBit

### ISSUE THREAD

**Issue by wirwl** [ccxt/ccxt#9103]
When i try using **exchange.timeframes['1d']** for ByBit exchange - i see this error: **[ExceptionsHandler] timeframe unit D is not supported**

```typescript
          for (const date of dates) {
            await sleep(exchange.rateLimit); // milliseconds
            const fData = await exchange.fetchOHLCV(
              symbol,
              exchange.timeframes['1d'],
              exchange.parse8601(`${date}T00:00:00Z`),
              1,
            );
```
How fix this problem, i need 1 day timeframe? I'm using last version of ccxt 1.49.21

**Comment by kroitor** [comment]
@wirwl you're sending `exchange.timeframes['1d']`, just send `'1d'` instead:

```JavaScript
            const fData = await exchange.fetchOHLCV(
              symbol,
              '1d', // ←-------------------------------------- HERE
              exchange.parse8601(`${date}T00:00:00Z`),
              1,
            );
```

Let us know if that does not answer your question.

**Comment by wirwl** [comment]
> @wirwl you're sending `exchange.timeframes['1d']`, just send `'1d'` instead:
> 
> ```js
>             const fData = await exchange.fetchOHLCV(
>               symbol,
>               '1d', // ←-------------------------------------- HERE
>               exchange.parse8601(`${date}T00:00:00Z`),
>               1,
>             );
> ```
> 
> Let us know if that does not answer your question.

Yes, '1d' it's work. Thank you!
