### ISSUE TITLE
how to order stop_loss_limit correctly for binance api?

### ISSUE THREAD

**Issue by pnama** [ccxt/ccxt#9105]
I'm trying to make a stop_loss_limit order and I have tried two different ways like below. But I'm getting ccxt.base.errors.InsufficientFunds: binance Account has insufficient balance for requested action. I believe I tried enough random numbers to see if I really don't have insufficient balance but really couldn't figure out why i'm getting that message. Any suggestions would be appreciated.

```
order = exchange.create_order(
  symbol='BTC/USDT',
  type='STOP_LOSS_LIMIT',
  amount=0.0005,
  price=56750,
  side='sell',
  params={'stopPrice': 56750}
)
```

```
symbol = 'BTC/USDT'
type = 'STOP_LOSS_LIMIT'  # or 'market', other types aren't unified yet
side = 'buy'
amount = 0.005     # your amount
price = 57800

# overrides
params = {
    'stopPrice': 57000,
    'stopLimitPrice': 56900
}

exchange.verbose = True
order = exchange.create_order(symbol, type, side, amount, price, params)
```

**Comment by diwenshi61** [comment]
Check your balances, and make sure you have enough balances. What is your free BTC or USDT balance in the account associated with the API keys? If you are submitting a buy order, you need to have stop limit price * amount in USDT funds. If you are submitting a sell order, you need to have amount in BTC funds. As well, if you provide the full trace of the exception and code used to produce it, it may be easier to find the issue.

**Comment by pnama** [comment]
![캡처](https://user-images.githubusercontent.com/40021155/116800781-121b4b00-ab3f-11eb-984a-d19d68948bb5.PNG)

Thank you for helping me by the way. I have attached the photo of my current order. 2.29 USDT is about 0.005 BTC I believe. And my balance shows {'free': 12.35926833, 'used': 2.30837433, 'total': 14.66313019}. Is there anything I could try based on the information? Thank you again

**Comment by diwenshi61** [comment]
Ahh ok. For futures the math will change. I would check [this page](https://www.binance.com/en/support/articles/360033162192), but I don't know the exact reason why Binance might reject the order in question. For USD-M futures, make sure that you have specified defaultType future or else it will be on spot exchange.
```
ccxt.binance({
    'apiKey': apiKey,
    'secret': apiSecret,
    'options': {
        'defaultType': 'future'
    }
})
```
Sorry I can't help you more.
