### ISSUE TITLE
Binance Futures get real time funding rate

### ISSUE THREAD

**Issue by YuxinSUN89** [ccxt/ccxt#9118]
OS: Windows
Programming Language version: Python 3.7
CCXT Version: 1.49.28
Exchange: Binance Futures

ccxt is the best library to access crypto data feed!
I'm trying to get the funding rate for example for BTC/USDT on Binance Futures in real time (currently about **0.0390%** as of  1620035130 Unix Timestamp, funding countdown in 06:13:32 ).

I followed https://github.com/ccxt/ccxt/issues/8028  (Thanks @kroitor ) to extract funding rate , and I found those are historical funding rates, not real time funding rates. The latest funding rate extracted was **0.00036188** compared to the real time funding rate on webpage **0.00039**. 

So can someone shed some light on how to extract real time funding rate? Thanks.

**Comment by diwenshi61** [comment]
[Endpoint for all predicted funding rates](https://fapi.binance.com/fapi/v1/premiumIndex)
[Documentation of this endpoint](https://binance-docs.github.io/apidocs/futures/en/#mark-price)
Binance decided for whatever reason to call the variable 'lastFundingRate' which doesn't make much sense, but you can doublecheck to see that the rates match [over here](https://www.binance.com/en/futures/funding-history/0).
In CCXT use the corresponding implicit function in order to get the data. See docs [here](https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods).

**Comment by YuxinSUN89** [comment]
> [Endpoint for all predicted funding rates](https://fapi.binance.com/fapi/v1/premiumIndex)
> [Documentation of this endpoint](https://binance-docs.github.io/apidocs/futures/en/#mark-price)
> Binance decided for whatever reason to call the variable 'lastFundingRate' which doesn't make much sense, but you can doublecheck to see that the rates match [over here](https://www.binance.com/en/futures/funding-history/0).
> In CCXT use the corresponding implicit function in order to get the data. See docs [here](https://github.com/ccxt/ccxt/wiki/Manual#implicit-api-methods).

Thanks @diwenshi61  for replying. Yeah 'lastFundingRate' is a bit confusing. 
Is it the lastest real time funding rate? or lastest historical funding rate ? 
I have compared those two funding rates and they are not the same. I dont understand why we can access real time funding rate from [webpage](https://www.binance.com/en/futures/funding-history/0), but not from endpoint.  Maybe I miss something here.

**Comment by YuxinSUN89** [comment]
OK..... following @diwenshi61  's weblink(and idea), I might find the way to extract real time funding rate. 
`
import json
import requests
import csv
import pandas as pd
url = 'https://fapi.binance.com/fapi/v1/premiumIndex' 
res = requests.get(url)
js0=json.loads(res.text)
df=pd.DataFrame(js0)
print(df)
`

That should be the way to extract real time funding rate for all future instruments. Please correct me if I am wrong. 
If @kroitor agrees with me, please close this post. Many Thanks  ！

**Comment by kroitor** [comment]
@YuxinSUN89 you can do it with implicit API methods as @diwenshi61 mentioned above, like so:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api

```Python
import ccxt
from pprint import pprint
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.binance({
    'enableRateLimit': True,
})
response = exchange.fapiPublicGetPremiumIndex()
pprint(response)
```

Let us know if that does not answer your question.
