### ISSUE TITLE
Delist FCoin

### ISSUE THREAD

**Issue by ndubel** [ccxt/ccxt#9120]
https://www.fcoin.com/
Exchange didn't work more than a year after hacker acttack. 
There are some retweets here https://twitter.com/fcoinofficial but nothing interesting. There are no any news about resumption of work. Probably it's time to remove FCoin from ccxt

**Comment by kroitor** [comment]
@ndubel are you able to access fcoinjp?

**Comment by kroitor** [comment]
@ndubel looks like both of them are dead.
