### ISSUE TITLE
Support for exchange-specific types of orders

### ISSUE THREAD

**Issue by slideup-benni** [ccxt/ccxt#913]
Hello,
some exchanges offer conditional orders. It would be very nice when you could provide a method to create such orders. Is this possible?
I would be very thankful

**Comment by kroitor** [comment]
Hello! You already have them ) CCXT supports all methods offered by all exchanges intrinsically.

- https://github.com/ccxt/ccxt/wiki/Manual#api-methods--endpoints
- https://github.com/ccxt/ccxt/wiki/Manual#api-method-naming-conventions

> To get a list of all available methods with an exchange instance, you can simply do the following:
> ```
> console.log (new ccxt.kraken ())   // JavaScript
> print (dir (ccxt.hitbtc ()))        # Python
> var_dump (new \ccxt\okcoinusd ()); // PHP
> ```

So, you just choose your method, your params and there you go. I'd recommend to read the entire Manual, there's a lot of useful info there ;)

Does this answer your question?

**Comment by kroitor** [comment]
Let us know if we can help with anything else. Thx!
