### ISSUE TITLE
Reusing TCP Connection

### ISSUE THREAD

**Issue by deceneucapital** [ccxt/ccxt#9134]
Hi Kroitor,

Is there a way to reuse or keepalive TCP connections to the exchanges when using CCXT?

For example, I am trading with FTX but it opens a new TCP connection for each order which of course adds latency.

Also, for each coin I am trading, there is a separate WS connection. Is this best practice or should there be one WS connection for all coins I'm trading?

Thanks!

**Comment by kroitor** [comment]
@deceneucapital the keepAlive functionality is controlled by the underlying networking lib, that is https.Agent in node.js, `requests` or `aiohttp` in python and curl in PHP. 

Afaik, you're using Python sync version of CCXT, which is built on top of `requests`, which in turn has keepAlive enabled by default.

**Comment by deceneucapital** [comment]
@kroitor Thanks for the explanation.

What would be the reason do you think that new orders sent are opening new TCP connections instead of reusing existing ones?

**Comment by deceneucapital** [comment]
@kroitor Any update?

**Comment by frosty00** [comment]
@deceneucapital what code are you using? we expect that ccxt already reuses tcp connections.

```
Also, for each coin I am trading, there is a separate WS connection. 
```

we still have yet to add support for multi-coin subscriptions in ccxtpro

**Comment by deceneucapital** [comment]
I'm having trouble understanding why my RTT latency to FTX is so slow (usually around 200 - 300ms to receive an order placement confirmation) when its under 20ms with Binance. Both exchanges are in AWS TY and my server is in AWS TY as well. 

Any ideas?

**Comment by kroitor** [comment]
@deceneucapital how do you measure the latency?

**Comment by deceneucapital** [comment]
I am using FTX's definition from their Latency Specifications December 1st 2020 (relevant section attached as a screenshot)
![FTX](https://user-images.githubusercontent.com/72634085/119503180-07ef1400-bdae-11eb-9b02-6171d8cc1716.PNG)

Further, as per the same document, I can see that my median order placement server latency is 67 milliseconds (using the URL on the FTX documents - again, attached as a screenshot as is the result from this URL)
![FTX II](https://user-images.githubusercontent.com/72634085/119503392-44bb0b00-bdae-11eb-8c1e-d958f2adf5b0.PNG)
![FTX Latency Stats](https://user-images.githubusercontent.com/72634085/119503396-4553a180-bdae-11eb-94f3-9157ed4cd854.PNG)

So I measure latency as the time between sending the order to the exchange and receiving an order placement confirmation. With FTX this should be around 100ms (70ms through the risk engine and 30ms from my server in AWS TY to theirs and back). However, you can see in the attached example that this is around 300ms.

By comparison, I attach the order placement latency of a Binance order which is around 20ms (and also to show that my server is in fact in AWS TY)

Can you please help?

**Comment by kroitor** [comment]
@deceneucapital you can try this script to measure your latency with CCXT (edit for your keys):

- https://github.com/ccxt/ccxt/blob/master/examples/py/measure-latency.py

Please, post your output.

**Comment by deceneucapital** [comment]
Does this code measure the time between sending an order to FTX and the timestamp FTX receives the order (created at)?

Or the time between sending an order (local server time) and receiving the order placement confirmation (again local server time)?

Also, can you amend the code so it sends a new order every 1000ms (1s)? FTX has higher latency for orders sent in a short amount of time

**Comment by kroitor** [comment]
> Does this code measure the time between sending an order to FTX and the timestamp FTX receives the order (created at)?
> Or the time between sending an order (local server time) and receiving the order placement confirmation (again local server time)?

It's the time between sending an order (local time) and receiving a confirmation (local time)

> Also, can you amend the code so it sends a new order every 1000ms (1s)? FTX has higher latency for orders sent in a short amount of time

Yes, just add `exchange.sleep (1000)` inside the loop, before or after measuring.

**Comment by deceneucapital** [comment]
![image](https://user-images.githubusercontent.com/72634085/120100158-8ec33880-c182-11eb-9c8f-ffe676e0f992.png)

I have tested - the first lot of results was sending the order 1 minute apart, the 2nd set was 6 minutes and the 3rd was 10 minutes (5 orders sent for each time interval)

On the 3rd set I also ran a WireShark capture - as you can see, there were 6 separate TCP connection. 1 when the exchange instantiation occured and one every 10 minutes thereafter (when it sent the order)

![image](https://user-images.githubusercontent.com/72634085/120100228-ebbeee80-c182-11eb-88dc-3736fa0f4291.png)


It seems like the KeepAlive is not working (on orders sent 1 min apart it reused the same connection but not on the orders sent 5 and 10 mins apart as the latency was higher on average and had a wider range of values) - do you concur?

**Comment by kroitor** [comment]
@deceneucapital I'm not entirely sure how to interpret your reply.
On your first screenshot we see an average round-trip time of 90ms and a reused connection. Then you stop the program and kill all connections. The you launch it again and it shows a different RTT for a different market which is logical. Then you repeat the third time. If you expect that the connections will be kept and reused in between those runs – that is not how  operating systems work in general – all connections are terminated when a process is terminated. If you launch multiple processes – every process will have its unique reused connection. The connection is only reused within a process and while that process is running. Hope that answers your question. Let us know if not.

**Comment by deceneucapital** [comment]
That’s not what I’m saying. 

On the first test I set exchange.sleep to 1000 (1s). It reuses the TCP connection when sending each of the 5 orders. 

On the second test I set exchange.sleep to 360000 (6mins) and it did not reuse the TCP connection for the 5 orders. 

It did not reuse then for the third test where exchange.sleep was set to 600000 (10mins) and I provided a wire shark capture. 

I am not saying that it should reuse the same connection between these tests. As you say this is not how it works. 

However, during the tests, should it not reuse the same connection?

On the last test for example, where it sent 5 orders, each 10 minutes apart, should it not reuse the connection if there is a KeepAlive?

**Comment by deceneucapital** [comment]
To further clarify, should the 2nd order in the 3rd test not use the same TCP connection as the first order (10 minutes prior) in that test?

**Comment by kroitor** [comment]
I think, 6-10 minutes is too long for the exchanges to keep your connection alive. It works for much shorter periods in general across the internet.

**Comment by deceneucapital** [comment]
Got it - thanks Kroitor!

**Comment by deceneucapital** [comment]
Sorry last question on this. 

Can CCXT send orders to FTX via their FIX protocol? Might test this if integrated to see if it’s any different

**Comment by kroitor** [comment]
Not yet, but we hope to add the support for FIX eventually. There's no ETA
on that however.
