### ISSUE TITLE
30m ohlcv is not available in ftx 

### ISSUE THREAD

**Issue by sofomryu** [ccxt/ccxt#9135]
- OS: Windows 10
- Programming Language version: jupyter notebook (python 3.8.5)
- CCXT version: ?

First of all, I'd like to say sorry that I can't check my ccxt version. I tried
```
import ccxt
print(ccxt.version)
```
but it said 'module 'ccxt' has no attribute 'version'

As a main issue, 30 m ohlcv in ftx is not available.
I tried 
```
import ccxt
ftx=ccxt.ftx()
ohlcv=ftx.fetch_ohlcv('BTC-PERP','30m')
```
it's working if I set timeframe as 5m or 15m or 1d ,etc but only 30m ohlcv is not available.
I checked ohlcv in ftx website, they provide 30m ohlcv in thier website.

Thanks in advance.

**Comment by kroitor** [comment]
Hi! FTX API does not support the 30m interval according to their API docs:

- https://docs.ftx.com/#get-historical-prices

<img width="1541" alt="Screenshot 2021-05-05 at 06 42 00" src="https://user-images.githubusercontent.com/1294454/117094703-2775bc80-ad6d-11eb-92f4-3e991e6e474c.png">

But the hint here is that you can always make a 30m candle from two 15m candles. I'll let you figure that out yourself, cause it's just basic arithmetics:

```Python
timestamp = 0
open = 1
high = 2
low = 3
close = 4
volume = 5

30m_candle[timestamp] = 15m_candles[i][timestamp]
30m_candle[open] = 15m_candles[i][open]
30m_candle[high] = max(15m_candles[i][high], 15m_candles[i+1][high])
30m_candle[low] = min(15m_candles[i][low], 15m_candles[i+1][low])
30m_candle[open] = 15m_candles[i+1][close]
30m_candle[volume] = 15m_candles[i][volume] + 15m_candles[i+1][volume]
```

Let us know if that does not answer your question.

**Comment by sofomryu** [comment]
Thanks! it helped a lot :)
Have a nice day.
