### ISSUE TITLE
FAQ - Time period to merge a New Exchange PR

### ISSUE THREAD

**Issue by munny-story** [ccxt/ccxt#9136]
Hi, @kroitor any idea of how much time takes by CCXT to merge or adding New Exchange PR after successful compilation and build? 
like in days or months etc.

Thanks

**Comment by kroitor** [comment]
@munny-story we currently have a backlog of free integrations for reviewing and merging, it might take a few weeks. If you wish to speed it up, please reach out to info@ccxt.trade
