### ISSUE TITLE
Can't fetch_trades anywhere other than Binance

### ISSUE THREAD

**Issue by rbdm-qnt** [ccxt/ccxt#9139]
I'm using CCXT 1.39.36 on Python 3.8 on Ubuntu 18.04.

I've been using fetch_trades to download tick data from Binance with this script:
https://github.com/ccxt/ccxt/blob/master/examples/py/binance-fetch-all-trades.py

When I try to use the same template script for other exchanges (I'm trying OKEX and HuobiPro) I can only get the last 5 or 15 minutes of trade data, no matter how I format the request, params, or since parameter. On the other hand, if I try to fetch OHLCV data, I can get it since the day of listing of the coin.

Any idea on why this happens? Is it a restriction on the exchange side or am I missing something?

Thanks in advance

**Comment by kroitor** [comment]
The pagination aspect is exchange-specific: https://github.com/ccxt/ccxt/wiki/Manual#pagination
Some exchanges will require id-based pagination and narrow time ranges (https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params)

- okex's fills pagination is ledger-id based: https://www.okex.com/docs/en/#spot-trade_fee
- huobi is also very non-standard in that regard, you have to mind the window and the gaps: https://huobiapi.github.io/docs/spot/v1/en/#get-account-history 

Let us know if that does not answer your question.

**Comment by rbdm-qnt** [comment]
Thank you! I'll try this out in the following days and let you know. Thank you so much as always

**Comment by elysianmichael** [comment]
> The pagination aspect is exchange-specific: https://github.com/ccxt/ccxt/wiki/Manual#pagination
> Some exchanges will require id-based pagination and narrow time ranges (https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params)
> 
> * okex's fills pagination is ledger-id based: https://www.okex.com/docs/en/#spot-trade_fee

For okex, the documentation says we can go back 3 months of transaction details (trades) but it seems to only let me access the past ~500 trades. Does anyone have this working?
