### ISSUE TITLE
PHP: RAM increases every time I call the methods

### ISSUE THREAD

**Issue by Juanperezc** [ccxt/ccxt#914]
Hello, I have a very serious problem. every time I execute one of the methods which at some point makes a file_get_contents. it is filling the ram memory until a putno to fill it in 1 hour if it is in a cycle running every so often.
Is there any way to avoid this ?

    OS: Windows 10
    Language: php
    CCXT version: 1.10
    Exchange: All
    Method: All

**Comment by kroitor** [comment]
Hi! Can you show a minimal snippet of code to reproduce the problem, please? Otherwise we will be guessing. We need something to work from. We are not doing any disk I/O in the library at all.

**Comment by Juanperezc** [comment]
Hello, this code is executed by console and with a cycle that uses reactphp, what is executed is what is inside the function, it is as if it were a while. the problem is that every time I call loadMarkets () the ram increases the same with other methods
`
<?php
require dirname(__FILE__).'/../vendor/autoload.php';
include dirname(__FILE__) ."/../vendor/ccxt/ccxt/ccxt.php";

date_default_timezone_set ('UTC');

use TomWright\Database\ExtendedPDO\ExtendedPDO as ExtendedPDO;
use TomWright\Database\QueryBuilder\SqlQueryBuilder as SqlQueryBuilder;

$loop = React\EventLoop\Factory::create();
function manual_bot($loop) {
    return function () use ($loop) {
  
echo "a";
// instantiate the exchange by id
$exchange = '\\ccxt\\poloniex';
$exchange = new $exchange ();

//var_dump ($exchange->loadMarkets());

if ($exchange->hasFetchOHLCV)
$a = $exchange->fetch_order_book("DOGE/BTC");

usleep(1000000);

         $loop->futureTick(manual_bot($loop));
    
         };
  }
$loop->futureTick(manual_bot($loop));
$loop->run();
}`

**Comment by kroitor** [comment]
There are multiple mistakes in your code. Unfortunately I can't really teach you the proper programming codeflow... 

You are creating a new exchange every time you enter the loop, so after calling this function 1000 times, you will have 1000 exchanges, and that goes indefinitely, eating your RAM. Don't create unnecessary instances if you only need one.

Obviously it comes from invalid usage of the language constructs. You really need to learn more basic programming, loops, function calls, recursive functions, if you want to code effectively.

This will not load your CPU and will not eat all your RAM:

https://github.com/ccxt/ccxt/blob/master/examples/php/built-in-rate-limiting-poller.php

```PHP
<?php

$root = dirname (dirname (dirname (__FILE__)));

include $root . '/ccxt.php';

date_default_timezone_set ('UTC');

$exchange = '\\ccxt\\poloniex';
$exchange = new $exchange (array (
    'enableRateLimit' => true,
));

$symbol = 'DOGE/BTC';

while (true) {
    $order_book = $exchange->fetch_order_book ($symbol);
    echo "----------------------------------------------------------------\n";
    echo date ('c') . "\n";
    echo count ($order_book['bids']) . " bids and " . count ($order_book['asks']) . " asks\n";
    echo sprintf ("bid: %.8f ask: %.8f", $order_book['bids'][0][0], $order_book['asks'][0][0]) . "\n";
}
```

----------------------------------

Your code should look like this:

```PHP
<?php

require dirname(__FILE__).'/../vendor/autoload.php';
include dirname(__FILE__) ."/../vendor/ccxt/ccxt/ccxt.php";

date_default_timezone_set ('UTC');

$loop = React\EventLoop\Factory::create ();

// instantiate the exchange by id
$exchange = '\\ccxt\\poloniex';
$exchange = new $exchange ();

$tick_function = function () use ($exchange, $loop, &$tick_function) {
    global $exchange, $loop;
    $order_book = $exchange->fetch_order_book ($symbol);
    echo "----------------------------------------------------------------\n";
    echo date ('c') . "\n";
    echo count ($order_book['bids']) . " bids and " . count ($order_book['asks']) . " asks\n";
    echo sprintf ("bid: %.8f ask: %.8f", $order_book['bids'][0][0], $order_book['asks'][0][0]) . "\n";

    $loop->futureTick ($tick_function);
};

$loop->futureTick ($tick_function);
$loop->run ();
```

--------------------------

Does any of the above scripts eat your RAM?

**Comment by kroitor** [comment]
I closed this for now, because, obviously, it is not related to ccxt directly. It is related to how you structure the other calls that are external to ccxt.

**Comment by Juanperezc** [comment]
I worked thank you very much
