### ISSUE TITLE
BIBOX exchange: wrong constant precision values for amount and price

### ISSUE THREAD

**Issue by Djusk8** [ccxt/ccxt#9142]
- OS: independent
- Programming Language version: Python
- CCXT version: latest 1.49.58

I found that constant values for `amount` and `price` precision used in `fetch_markets()` method for Bibox exchange is wrong.  

```
    def fetch_markets(self, params={}):
        request = {
            'cmd': 'marketAll',
        }
        response = self.publicGetMdata(self.extend(request, params))

        markets = self.safe_value(response, 'result')
        result = []
        
        for i in range(0, len(markets)):
            market = markets[i]

            .....
            
           ### !!! This walues is wrong ###
           precision = {
                'amount': 4,
                'price': 8,
            }
            .....
        return result

```

The exchange does not return these values explicitly, but you can calculate this values from `amount` and `high/low` returned values.

Data returned by exchange:

```
        #
        #     {
        #         "result": [
        #             {
        #                 "is_hide":0,
        #                 "high_cny":"1.9478",
        #                 "amount":"272.41",
        #                 "coin_symbol":"BIX",
        #                 "last":"0.00002487",
        #                 "currency_symbol":"BTC",
        #                 "change":"+0.00000073",
        #                 "low_cny":"1.7408",
        #                 "base_last_cny":"1.84538041",
        #                 "area_id":7,
        #                 "percent":"+3.02%",
        #                 "last_cny":"1.8454",
        #                 "high":"0.00002625",
        #                 "low":"0.00002346",
        #                 "pair_type":0,
        #                 "last_usd":"0.2686",
        #                 "vol24H":"10940613",
        #                 "id":1,
        #                 "high_usd":"0.2835",
        #                 "low_usd":"0.2534"
        #             }
        #         ],
        #         "cmd":"marketAll",
        #         "ver":"1.1"
        #     }
        #
```

I calculate precisions for the all markets and get only one value {2} for amount and seven {1, 2, 3, 4, 6, 7, 8} values for price.

```
        markets = self.safe_value(response, 'result')

        all_amounts_prec = [len(market['amount'].split('.')[1]) for market in markets]
        all_price_prec = [len(market['high'].split('.')[1]) for market in markets]

        print(set(all_amounts_prec))  # {2}
        print(set(all_price_prec))  # {1, 2, 3, 4, 6, 7, 8}
```

So I think it's better to calculate amount and price precisions for every market. Something like this:

```
           precision = {
                'amount': len(market['amount'].split('.')[1]),
                'price': len(market['high'].split('.')[1]),
            }
```

**Comment by Djusk8** [comment]
Additional info:
I've changed the code as suggested earlier and it works in most cases, but for some markets there are unexpected behaviour.

For example:

AWT\USDT market:

`{'is_hide': '0', 'high_cny': '0.9778', 'amount': '115339.03', 'coin_symbol': 'AWT', 'last': '0.144900', 'currency_symbol': 'USDT', 'change': '-0.004800', 'low_cny': '0.8383', 'base_last_cny': '0.94460162', 'area_id': '15', 'percent': '-3.21%', 'last_cny': '0.9446', 'high': '0.150000', 'low': '0.128600', 'pair_type': '6', 'last_usd': '0.1449', 'vol24H': '794921', 'id': '780', 'high_usd': '0.1500', 'low_usd': '0.1286'}`

Precision for `amount` is calculated as 2 (that's right), and `price` precision calculated as 6. But if you check the order book you can see that precision for price is 4.

In this case problem on the Exchange side, not CCXT library.


![изображение](https://user-images.githubusercontent.com/35682654/117276335-77d14500-ae67-11eb-8a6a-6374f3181750.png) 
![изображение](https://user-images.githubusercontent.com/35682654/117276507-a4855c80-ae67-11eb-84e6-cdb15383eef7.png)

**Comment by Djusk8** [comment]
Same problem for amount precision for some markets.

CORX/USDT

`{'is_hide': '0', 'high_cny': '0.0423', 'amount': '238211.80', 'coin_symbol': 'CORX', 'last': '0.005690', 'currency_symbol': 'USDT', 'change': '-0.000081', 'low_cny': '0.0355', 'base_last_cny': '0.03709305', 'area_id': '15', 'percent': '-1.40%', 'last_cny': '0.0371', 'high': '0.006495', 'low': '0.005446', 'pair_type': '1', 'last_usd': '0.0057', 'vol24H': '40411176', 'id': '773', 'high_usd': '0.0065', 'low_usd': '0.0054'}`

Any ideas how to deal with it?

Price precision calculated as 6 - that's right
Amount precision calculated as 2 - that's wrong, the real amount precision is 1.

![изображение](https://user-images.githubusercontent.com/35682654/117277618-b61b3400-ae68-11eb-833b-4fe4eb71ed62.png)

**Comment by Djusk8** [comment]
This problems are actual for USDT markets. For BTC and ETH markets all works great.

**Comment by ndubel** [comment]
In v3 API it looks like Bibox gives right precisions https://api.bibox.com/v3/mdata/pairList

**Comment by Djusk8** [comment]
> In v3 API it looks like Bibox gives right precisions https://api.bibox.com/v3/mdata/pairList

Yes, looks like v3 gives right precisions for amount.
Unfortunatelly `decimal` values in V3 are not related to price precision, so we still need these values.

**Comment by Djusk8** [comment]
>            precision = {
>                 'amount': len(market['amount'].split('.')[1]),
>                 'price': len(market['high'].split('.')[1]),
>             }

Update for this approach.

In some cases we can get `IndexError` exception, trying to find fraction length for values like this `'high': '479'`

{'is_hide': '0', 'high_cny': '3123.3291', 'amount': '302616892.00', 'coin_symbol': '5AAVE', 'last': '437.58', 'currency_symbol': 'USD', 'change': '-36', 'low_cny': '2821.5594', 'base_last_cny': '2853.24917661', 'area_id': '16', 'percent': '-7.60%', 'last_cny': '2853.2492', 'high': '479', 'low': '432.72', 'pair_type': '7', 'last_usd': '437.5800', 'vol24H': '302616892', 'id': '718', 'time': '1620361595166', 'high_usd': '479.0000', 'low_usd': '432.7200'}

**Comment by ndubel** [comment]
> > In v3 API it looks like Bibox gives right precisions https://api.bibox.com/v3/mdata/pairList
> 
> Confirm, v3 gives right precisions for amount.
> Unfortunatelly we still need price precision values.

Do you think `decimal` isn't right precision for price?

**Comment by Djusk8** [comment]
> Do you think `decimal` isn't right precision for price?

For some USDT markets, like BTC\USDT, ETH\USDT, LTC\USDT and etc. `decimal` is actual precision for price. 
But for another markets `decimal` is not correct.

For example:

```
id | 90
-- | --
pair | "BIX_USDT"
pair_type | 0
area_id | 15
is_hide | 0
decimal | 6
amount_scale | 2
```

The real price precision is 4:
![изображение](https://user-images.githubusercontent.com/35682654/118478017-0e2f2180-b718-11eb-8b6f-530f10d4a461.png)


```
id | 273
-- | --
pair | "FTM_USDT"
pair_type | 0
area_id | 15
is_hide | 0
decimal | 6
amount_scale | 4

```

The real price precision is 4:

![изображение](https://user-images.githubusercontent.com/35682654/118478377-77af3000-b718-11eb-8cea-d842c748b3f1.png)

**Comment by kroitor** [comment]
@Djusk8 thx for your feedback! We really appreciate it. There's indeed a problem with Bibox's precision, the only system that I can draw from the above is that there is no system...

**Comment by ndubel** [comment]
> > Do you think `decimal` isn't right precision for price?
> 
> For some USDT markets, like BTC\USDT, ETH\USDT, LTC\USDT and etc. `decimal` is actual precision for price.
> But for another markets `decimal` is not correct.
> 
> For example:
> 
> ```
> id | 90
> -- | --
> pair | "BIX_USDT"
> pair_type | 0
> area_id | 15
> is_hide | 0
> decimal | 6
> amount_scale | 2
> ```
> 
> The real price precision is 4:
> ![изображение](https://user-images.githubusercontent.com/35682654/118478017-0e2f2180-b718-11eb-8b6f-530f10d4a461.png)
> 
> ```
> id | 273
> -- | --
> pair | "FTM_USDT"
> pair_type | 0
> area_id | 15
> is_hide | 0
> decimal | 6
> amount_scale | 4
> ```
> 
> The real price precision is 4:
> 
> ![изображение](https://user-images.githubusercontent.com/35682654/118478377-77af3000-b718-11eb-8cea-d842c748b3f1.png)

I don't think so. Just try to create order on FTM/USDT and BIX/USDT with price precision 6 and it will be correctly created via API. But in UI on some reasons they displayed only precision 4.

**Comment by ndubel** [comment]
![image](https://user-images.githubusercontent.com/38309641/118482399-5b61c200-b71d-11eb-9a63-5e8bb9ca532d.png)
Proof.
But you can't create it with precision 7+

**Comment by Djusk8** [comment]
> But in UI on some reasons they displayed only precision 4. It's the old bibox bug (or feature).

Confirm. 
I have checked UI again and found that the price showed in trade history section with full (right) precision.

![изображение](https://user-images.githubusercontent.com/35682654/118484946-797cf180-b720-11eb-9ffd-2d6137e9f99b.png)

So, it means  [https://api.bibox.com/v3/mdata/pairList](https://api.bibox.com/v3/mdata/pairList) can be used to get right precisions for amount and price

**Comment by Djusk8** [comment]
I know you get Python code stanspiled from JS, unfortunatelly I don't know JS, but on Python it will be something like this:


```
Index: bibox.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/bibox.py b/bibox.py
--- a/bibox.py	(revision 6eaf0e7148494e347669466379526850ec2a2172)
+++ b/bibox.py	(revision 5ba12038df79592423ca277713f07cef91d5997b)
@@ -199,6 +199,13 @@
         #     }
         #
         markets = self.safe_value(response, 'result')
+
+        # get precision data
+        request = {'cmd': 'pairList',}
+        response = self.publicGetMdata(self.extend(request, params))
+        pairs_list = self.safe_value(response, 'result')
+        precisions = {item['pair']: {'price': int(item['decimal']), 'amount': int(item['amount_scale'])} for item in pairs_list}
+
         result = []
         for i in range(0, len(markets)):
             market = markets[i]
@@ -210,8 +217,8 @@
             symbol = base + '/' + quote
             id = baseId + '_' + quoteId
             precision = {
-                'amount': 4,
-                'price': 8,
+                'amount': precisions[id]['amount'],
+                'price': precisions[id]['price'],
             }
             result.append({
                 'id': id,

```

**Comment by kroitor** [comment]
Thanks to all of you, guys! We will get this fixed shortly.

**Comment by Djusk8** [comment]
Some more information:

Trying to buy min amount ONG for ONG/ETH market 

```
<bound method Exchange.create_limit_buy_order of ccxt.bibox()>
('ONG/ETH', 17.46480841105173, 0.00028629)
```
and got exception:

`(<class 'ccxt.base.errors.InvalidOrder'>, InvalidOrder('bibox {"result":[{"error":{"code":"2085","msg":"币种最小下单数量限制","min_amount":0.005,"symbol":"ETH"},"cmd":"orderpending/trade"}],"error":{"code":"2085","msg":"币种最小下单数量限制","min_amount":0.005,"symbol":"ETH"},"cmd":"orderpending/trade"}'), <traceback object at 0x7ff3241d89c8>)`

Error said that my order sum shouldn't be less than 0.005 ETH

But my ETH sum is exactly 0.005 ETH:  `17.46480841105173 * 0.00028629 = 0.005`

So I tried to place the same order in GUI and got this:

![изображение](https://user-images.githubusercontent.com/35682654/118962621-3b750d00-b96e-11eb-82e2-dde5e97e6b0a.png)

While I can't use 8-digits fraction, my total  price is rounded to 7-digits fraction and the total sum gets smaller than 0.005 ETH. So I think a similar situation occurs when sending a request via the API. 

I think this is not the CCXT problem, but the strange exchange bug. 

For myself, I used the following workaround: hardcoded min cost amoun for ETH markets as 0.0051 ETH

**Comment by Djusk8** [comment]
Some more information for this problem:

Trying to buy min amount ONG for ONG/ETH market 

```
<bound method Exchange.create_limit_buy_order of ccxt.bibox()>
('ONG/ETH', 17.46480841105173, 0.00028629)
```
and got exception:

`(<class 'ccxt.base.errors.InvalidOrder'>, InvalidOrder('bibox {"result":[{"error":{"code":"2085","msg":"币种最小下单数量限制","min_amount":0.005,"symbol":"ETH"},"cmd":"orderpending/trade"}],"error":{"code":"2085","msg":"币种最小下单数量限制","min_amount":0.005,"symbol":"ETH"},"cmd":"orderpending/trade"}'), <traceback object at 0x7ff3241d89c8>)`

Error said that my order sum shouldn't be less than 0.005 ETH

But my ETH sum is exactly 0.005 ETH:  `17.46480841105173 * 0.00028629 = 0.005`

So I tried to place the same order in GUI and got this:

![изображение](https://user-images.githubusercontent.com/35682654/118962621-3b750d00-b96e-11eb-82e2-dde5e97e6b0a.png)

While I can't use 8-digits fraction, my total  price is rounded to 7-digits fraction and the total sum gets smaller than 0.005 ETH. So I think a similar situation occurs when sending a request via the API. 

I think this is not the CCXT problem, but the strange exchange bug. 

For myself, I used the following workaround: hardcoded min cost amoun for ETH markets as 0.0051 ETH

**Comment by ndubel** [comment]
there is also v1 method with right precisions:
https://api.bibox.com/v1/mdata?cmd=pairList

**Comment by ttodua** [comment]
Late reply here, but I think in current version of ccxt, BIBOX fetchmarkets uses latest endpoints, where it seems fixed on first look.
If you find it otherwise, please report here again. Thanks

**Comment by ndubel** [comment]
@ttodua I see that ccxt uses v1 endpoints for `fetchMarkets`
v1: https://api.bibox.com/v1/mdata?cmd=pairList
v4: https://api.bibox.com/api/v4/marketdata/pairs

v1: 
`{"id":478,"pair":"ANT_USDT","pair_type":6,"area_id":15,"is_hide":0,"decimal":4,"alias":null,"amount_scale":4},`
v4: `{"symbol":"ANT_USDT","base":"ANT","quote":"USDT","min_price":0.00000001,"max_price":1000000,"min_quantity":0.0000001,"max_quantity":1000000,"price_scale":6,"quantity_scale":4,"price_increment":"0.000001","quantity_increment":"0.0001","min_order_value":"1"},`
even price precision is different in this versions for some pairs. And v4 has more info.

**Comment by ttodua** [comment]
yes, v4 has more info. you are right, I missed the current approach, as the [v4 markets](https://github.com/ccxt/ccxt/pull/14216) is yet not merged, sorry. You might check that PR and comment there. it will be merged soon.
