### ISSUE TITLE
Does ccxt support only Stop Trades? Is there a way to access Margin and Futures orders/trades?

### ISSUE THREAD

**Issue by powwr** [ccxt/ccxt#9148]
We compared all orders from ccxt and Binance library for the same account and that's what we found:

Binance library:
{ futuresOrders: 0, spotOrders: 89, marginOrders: 3 }

Whereas in ccxt the number of all orders is 89, so it seems like ccxt shows only spot orders.

We fetch all orders from ccxt using the following code

_const ccxt = require('ccxt');

const exchange = new ccxt['binance']({    
  apiKey: "",
  secret: "",
  
  enableRateLimit: true,  
});

exchange.fetchOrders('BTC/USDT', undefined, undefined, {
  recvWindow: 50000
})
  .then(orders => {
    console.log(orders);
  });_

Please, advise how to fetch Margin and Futures Orders/Trades through ccxt if you know. Thanks a lot!

It seems to be possible in Binance library though.
futuresAllOrders for future type, allOrders for spot typr and mgAllOrders for Margin type.

**Comment by kroitor** [comment]
- https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties
- https://github.com/ccxt/ccxt/blob/master/js/binance.js#L545

```JavaScript
const exchange = new ccxt['binance']({
    apiKey: "",
    secret: "",
    enableRateLimit: true,
    options: {
        defaultType: 'spot',  // 'margin' for sapi, 'future' for fapi, 'delivery' for dapi
    },
});
```

Let us know if that does not answer your question.
