### ISSUE TITLE
Allow fetchTrades() for non-specified (all) markets (where available)

### ISSUE THREAD

**Issue by osnwt** [ccxt/ccxt#915]
At the moment the unified API requires a market symbol to fetchTrades(symbol). Many exchanges (Poloniex and Cryptopia are examples) allow to fetch trades history for all markets by not specifying a particular symbol.

I use such feature for almost instant trade event notifications for exchanges without WebSocket API by polling the exchange, say, once per 5 seconds. Using separate calls per market makes impossible to implement the feature using unified API.

Would be great if fetchTrades() supports such requests to get all markets trades by a single request.

**Comment by kroitor** [comment]
We will add support for that in near future. Thx!

**Comment by osnwt** [comment]
Correction: actually, I am interested in **fetchMyTrades()** for all markets, not fetchTrades().
Still, both could be supported.

**Comment by kroitor** [comment]
@osnwt fetchMyTrades already supports that. So, Poloniex should work right away if you don't specify a symbol argument. The same is true for most markets, where supported, fetchMyTrades should be able to fetch all trades for all markets at once. As for Cryptopia, [from their docs](https://www.cryptopia.co.nz/Forum/Thread/256) it follows that they demand a symbol anyway. Dod you test their private trades endpoint for that? 

As for the fetchTrades – my previous answer still holds, we are going to add support for fetching all public trades as well. Let me know if this solves your issue for now.

**Comment by osnwt** [comment]
I did not test Poloniex, but tested Cryptopia right now. It works for all pairs too, read the API function description:

> GetTradeHistory
Returns a list of trade history for **all tradepairs** or specified tradepair

Their docs are not clear, they tell you must give either Market or TradePairId. But in reality you may send empty string or undefined (or nothing if it has any other parameters) and get all markets. And it also works for similar either/or pairs for other methods where all is an option.

This code works for Cryptopia:

```javascript
    async fetchMyTrades (symbol = undefined, since = undefined, limit = undefined, params = {}) {
        await this.loadMarkets ();
        let market = symbol ? this.market (symbol) : undefined;
        let id = market ? market['id'] : undefined;
        let response = await this.privatePostGetTradeHistory (this.extend ({
            'TradePairId': id,
        }, params));
        return this.parseTrades (response['Data'], market, since, limit);
    }
```

When I tested own Cryptopia API interface, I found that I must have at least one parameter to be able to sign the request successfully. If I have no optional parameters to send, I can send empty string instead (`Market: ''`), it works as unspecified and allows to sign the request.

**Comment by kroitor** [comment]
Ok, Poloniex should work anyway, and for Cryptopia we will add an enhancement to support for that. Thx for a comprehensive report!

**Comment by osnwt** [comment]
Works, thank you!

**Comment by kroitor** [comment]
@osnwt thx for the feedback!
