### ISSUE TITLE
fetch_orders id-based pagination  for binance futures not working

### ISSUE THREAD

**Issue by alvarolloret** [ccxt/ccxt#9150]
- Programming Language version: Python
- CCXT version: Latest

It seems pagination based on id is not working for binance futures

```
symbol = 'ETH/USDT'
from_id = 'xxxxxx'
since = None
limit = None
params = {
    'from_id': from_id, 
}
orders = client.fetch_orders(symbol, since, limit, params)

```

Running the code above does keeps getting me all the orders, no matter if it is the latest id of an order or any other order id

**Comment by kroitor** [comment]
@alvarolloret `params` will only support exchange-specific params, and the corresponding Binance endpoint does not support `from_id`:

- https://binance-docs.github.io/apidocs/spot/en/#all-orders-user_data

Let us know if that does not answer your question.
