### ISSUE TITLE
Coincheck: parameters are not available

### ISSUE THREAD

**Issue by forzavortis** [ccxt/ccxt#916]
Coincheck: parameters are not available.

- Language: python3
- CCXT version: newest
- Exchange: Coincheck

GET request with Parameters is not available in coincheck API.
```
coincheck.request('exchange/leverage/positions', 'private', method='GET')
```
and
```
coincheck.request('exchange/leverage/positions', 'private', method='GET', params={'status':'open'})
```
and
```
coincheck.request('exchange/leverage/positions', 'private', method='GET', params={'status':'closed'})
```
return same results.

I think parameters are not handled correctly in GET request.

Please check it.

**Comment by kroitor** [comment]
Can you show the output in verbose mode?

```Python
coincheck.verbose = True
coincheck.request('exchange/leverage/positions', 'private', method='GET', params={'status':'open'})
```

**Comment by forzavortis** [comment]
Thank you for quick reply.

>>> coincheck.request('exchange/leverage/positions', 'private',
method='GET', params={'status':'open'})

https://coincheck.com/api/exchange/leverage/positions GET
https://coincheck.com/api/exchange/leverage/positions

Request: {'ACCESS-KEY': 'c9PKWI8xrGXeaz5g', 'Content-Type':
'application/x-www-form-urlencoded', 'ACCESS-SIGNATURE':
'1522f6654690440f37c586c8a87bac09d6340b869c9d315d61c1a7cacf72fb3d',
'Accept-Encoding': 'gzip, deflate', 'ACCESS-NONCE': '1513829822200'} None

GET https://coincheck.com/api/exchange/leverage/positions

Response: Content-Type: application/json; charset=utf-8

Transfer-Encoding: chunked

Connection: close

Date: Thu, 21 Dec 2017 04:17:02 GMT

Server: nginx

X-XSS-Protection: 1; mode=block

X-Content-Type-Options: nosniff

ETag: W/"4e371d3c4b69a8044001da04678ee492"

Cache-Control: max-age=0, private, must-revalidate

X-Request-Id: d6310587-9bc5-4add-b435-ab9dac2f659e

X-Runtime: 0.043504

Content-Encoding: gzip

X-Cache: Miss from cloudfront

Via: 1.1 d9701bf2e4c70004317c0b657ad94239.cloudfront.net (CloudFront)

X-Amz-Cf-Id: 5ZsODraEb4OwOzQOp93C2F1lTABxKtchBNrytWo9zyj0h-rsXvIIjg==



{"success":true,"pagination":{"limit":10,"order":"desc","starting_after":null,"ending_before":null},"data":[{"id":4269237,"pair":"btc_jpy","status":"closed","created_at":"2017-12-20T13:54:09.000Z","closed_at":"2017-12-20T13:55:16.000Z","open_rate":"2040236.0","closed_rate":"2035451.0","amount":"0.0","all_amount":"1.0","side":"sell","pl":"3767.64839538","new_order":{"id":579207568,"side":"sell","rate":null,"amount":"1.0","pending_amount":"0","status":"complete","created_at":"2017-12-20T13:54:09.000Z"},"close_orders":[{"id":579210577,"side":"buy","rate":"2040000.0","amount":"1.0005","pending_amount":"0","status":"complete","created_at":"2017-12-20T13:55:16.000Z"}]},{"id":4260042,"pair":"btc_jpy","status":"open","created_at":"2017-12-20T07:56:06.000Z","closed_at":null,"open_rate":"1988517.0","closed_rate":null,"amount":"1.0005","all_amount":"1.0","side":"sell","pl":"11119.075","new_order":{"id":578388474,"side":"sell","rate":null,"amount":"1.0","pending_amount":"0","status":"complete","created_at":"2017-12-20T07:56:05.000Z"},"close_orders":[]},{"id":4260041,"pair":"btc_jpy","status":"open","created_at":"2017-12-20T07:56:01.000Z","closed_at":null,"open_rate":"1987544.0","closed_rate":null,"amount":"1.00050001","all_amount":"1.0","side":"sell","pl":"10145.50126771","new_order":{"id":578388174,"side":"sell","rate":null,"amount":"1.0","pending_amount":"0","status":"complete","created_at":"2017-12-20T07:56:01.000Z"},"close_orders":[]},{"id":4260038,"pair":"btc_jpy","status":"open","created_at":"2017-12-20T07:55:57.000Z","closed_at":null,"open_rate":"1988641.0","closed_rate":null,"amount":"1.0005","all_amount":"1.0","side":"sell","pl":"11243.2224482","new_order":{"id":578387970,"side":"sell","rate":null,"amount":"1.0","pending_amount":"0","status":"complete","created_at":"2017-12-20T07:55:56.000Z"},"close_orders":[]},{"id":4227990,"pair":"btc_jpy","status":"open","created_at":"2017-12-19T14:44:39.000Z","closed_at":null,"open_rate":"2108319.0","closed_rate":null,"amount":"1.001","all_amount":"1.0","side":"sell","pl":"129932.59","new_order":{"id":575754345,"side":"sell","rate":null,"amount":"1.0","pending_amount":"0","status":"complete","created_at":"2017-12-19T14:44:38.000Z"},"close_orders":[]},{"id":4227933,"pair":"btc_jpy","status":"open","created_at":"2017-12-19T14:44:19.000Z","closed_at":null,"open_rate":"2100091.0","closed_rate":null,"amount":"1.001","all_amount":"1.0","side":"sell","pl":"121704.59","new_order":{"id":575753205,"side":"sell","rate":null,"amount":"1.0","pending_amount":"0","status":"complete","created_at":"2017-12-19T14:44:18.000Z"},"close_orders":[]},{"id":4226851,"pair":"btc_jpy","status":"open","created_at":"2017-12-19T14:20:02.000Z","closed_at":null,"open_rate":"2093306.0","closed_rate":null,"amount":"1.001","all_amount":"1.0","side":"sell","pl":"114919.70088873","new_order":{"id":575687562,"side":"sell","rate":null,"amount":"1.0","pending_amount":"0","status":"complete","created_at":"2017-12-19T14:20:02.000Z"},"close_orders":[]},{"id":4226846,"pair":"btc_jpy","status":"open","created_at":"2017-12-19T14:19:56.000Z","closed_at":null,"open_rate":"2092374.0","closed_rate":null,"amount":"1.001","all_amount":"1.0","side":"sell","pl":"113987.8189488","new_order":{"id":575687269,"side":"sell","rate":null,"amount":"1.0","pending_amount":"0","status":"complete","created_at":"2017-12-19T14:19:55.000Z"},"close_orders":[]},{"id":4226844,"pair":"btc_jpy","status":"open","created_at":"2017-12-19T14:19:52.000Z","closed_at":null,"open_rate":"2092805.0","closed_rate":null,"amount":"1.00099998","all_amount":"1.0","side":"sell","pl":"114418.52061337","new_order":{"id":575687016,"side":"sell","rate":null,"amount":"1.0","pending_amount":"0","status":"complete","created_at":"2017-12-19T14:19:51.000Z"},"close_orders":[]},{"id":4226445,"pair":"btc_jpy","status":"open","created_at":"2017-12-19T14:10:57.000Z","closed_at":null,"open_rate":"2095463.0","closed_rate":null,"amount":"1.001","all_amount":"1.0","side":"sell","pl":"117076.27855458","new_order":{"id":575661607,"side":"sell","rate":null,"amount":"1.0","pending_amount":"0","status":"complete","created_at":"2017-12-19T14:10:56.000Z"},"close_orders":[]}]}

{'data': [{'new_order': {'id': 579207568, 'rate': None, 'side': 'sell',
'amount': '1.0', 'pending_amount': '0', 'status': 'complete', 'created_at':
'2017-12-20T13:54:09.000Z'}, 'id': 4269237, 'closed_at':
'2017-12-20T13:55:16.000Z', 'open_rate': '2040236.0', 'pl':
'3767.64839538', 'closed_rate': '2035451.0', 'all_amount': '1.0',
'close_orders': [{'id': 579210577, 'rate': '2040000.0', 'side': 'buy',
'amount': '1.0005', 'pending_amount': '0', 'status': 'complete',
'created_at': '2017-12-20T13:55:16.000Z'}], 'side': 'sell', 'amount':
'0.0', 'created_at': '2017-12-20T13:54:09.000Z', 'status': 'closed',
'pair': 'btc_jpy'}, {'new_order': {'id': 578388474, 'rate': None, 'side':
'sell', 'amount': '1.0', 'pending_amount': '0', 'status': 'complete',
'created_at': '2017-12-20T07:56:05.000Z'}, 'id': 4260042, 'closed_at':
None, 'open_rate': '1988517.0', 'pl': '11119.075', 'closed_rate': None,
'all_amount': '1.0', 'close_orders': [], 'side': 'sell', 'amount':
'1.0005', 'created_at': '2017-12-20T07:56:06.000Z', 'status': 'open',
'pair': 'btc_jpy'}, {'new_order': {'id': 578388174, 'rate': None, 'side':
'sell', 'amount': '1.0', 'pending_amount': '0', 'status': 'complete',
'created_at': '2017-12-20T07:56:01.000Z'}, 'id': 4260041, 'closed_at':
None, 'open_rate': '1987544.0', 'pl': '10145.50126771', 'closed_rate':
None, 'all_amount': '1.0', 'close_orders': [], 'side': 'sell', 'amount':
'1.00050001', 'created_at': '2017-12-20T07:56:01.000Z', 'status': 'open',
'pair': 'btc_jpy'}, {'new_order': {'id': 578387970, 'rate': None, 'side':
'sell', 'amount': '1.0', 'pending_amount': '0', 'status': 'complete',
'created_at': '2017-12-20T07:55:56.000Z'}, 'id': 4260038, 'closed_at':
None, 'open_rate': '1988641.0', 'pl': '11243.2224482', 'closed_rate': None,
'all_amount': '1.0', 'close_orders': [], 'side': 'sell', 'amount':
'1.0005', 'created_at': '2017-12-20T07:55:57.000Z', 'status': 'open',
'pair': 'btc_jpy'}, {'new_order': {'id': 575754345, 'rate': None, 'side':
'sell', 'amount': '1.0', 'pending_amount': '0', 'status': 'complete',
'created_at': '2017-12-19T14:44:38.000Z'}, 'id': 4227990, 'closed_at':
None, 'open_rate': '2108319.0', 'pl': '129932.59', 'closed_rate': None,
'all_amount': '1.0', 'close_orders': [], 'side': 'sell', 'amount': '1.001',
'created_at': '2017-12-19T14:44:39.000Z', 'status': 'open', 'pair':
'btc_jpy'}, {'new_order': {'id': 575753205, 'rate': None, 'side': 'sell',
'amount': '1.0', 'pending_amount': '0', 'status': 'complete', 'created_at':
'2017-12-19T14:44:18.000Z'}, 'id': 4227933, 'closed_at': None, 'open_rate':
'2100091.0', 'pl': '121704.59', 'closed_rate': None, 'all_amount': '1.0',
'close_orders': [], 'side': 'sell', 'amount': '1.001', 'created_at':
'2017-12-19T14:44:19.000Z', 'status': 'open', 'pair': 'btc_jpy'},
{'new_order': {'id': 575687562, 'rate': None, 'side': 'sell', 'amount':
'1.0', 'pending_amount': '0', 'status': 'complete', 'created_at':
'2017-12-19T14:20:02.000Z'}, 'id': 4226851, 'closed_at': None, 'open_rate':
'2093306.0', 'pl': '114919.70088873', 'closed_rate': None, 'all_amount':
'1.0', 'close_orders': [], 'side': 'sell', 'amount': '1.001', 'created_at':
'2017-12-19T14:20:02.000Z', 'status': 'open', 'pair': 'btc_jpy'},
{'new_order': {'id': 575687269, 'rate': None, 'side': 'sell', 'amount':
'1.0', 'pending_amount': '0', 'status': 'complete', 'created_at':
'2017-12-19T14:19:55.000Z'}, 'id': 4226846, 'closed_at': None, 'open_rate':
'2092374.0', 'pl': '113987.8189488', 'closed_rate': None, 'all_amount':
'1.0', 'close_orders': [], 'side': 'sell', 'amount': '1.001', 'created_at':
'2017-12-19T14:19:56.000Z', 'status': 'open', 'pair': 'btc_jpy'},
{'new_order': {'id': 575687016, 'rate': None, 'side': 'sell', 'amount':
'1.0', 'pending_amount': '0', 'status': 'complete', 'created_at':
'2017-12-19T14:19:51.000Z'}, 'id': 4226844, 'closed_at': None, 'open_rate':
'2092805.0', 'pl': '114418.52061337', 'closed_rate': None, 'all_amount':
'1.0', 'close_orders': [], 'side': 'sell', 'amount': '1.00099998',
'created_at': '2017-12-19T14:19:52.000Z', 'status': 'open', 'pair':
'btc_jpy'}, {'new_order': {'id': 575661607, 'rate': None, 'side': 'sell',
'amount': '1.0', 'pending_amount': '0', 'status': 'complete', 'created_at':
'2017-12-19T14:10:56.000Z'}, 'id': 4226445, 'closed_at': None, 'open_rate':
'2095463.0', 'pl': '117076.27855458', 'closed_rate': None, 'all_amount':
'1.0', 'close_orders': [], 'side': 'sell', 'amount': '1.001', 'created_at':
'2017-12-19T14:10:57.000Z', 'status': 'open', 'pair': 'btc_jpy'}],
'success': True, 'pagination': {'limit': 10, 'ending_before': None,
'order': 'desc', 'starting_after': None}}




2017年12月21日(木) 13:15 Igor Kroitor <notifications@github.com>:

**Comment by kroitor** [comment]
This is fixed in version 1.10.436. Thx for reporting!

**Comment by forzavortis** [comment]
Thank you so much!

**Comment by kroitor** [comment]
@forzavortis can you, please, confirm it works as seen on your side with the most recent version?

**Comment by forzavortis** [comment]
Perfect work! Great!
