### ISSUE TITLE
Kucoin Future Trading

### ISSUE THREAD

**Issue by AlexField26** [ccxt/ccxt#9162]
Hello community,

i am trying to get Kucoin with future trading to work with ccxt. With binance, this is very easy; can someone assit with the settings for Kucoin? I read the docu, but this did not really helped.

Thanks!
Alex

**Comment by Ali-moradi-dev** [comment]
@AlexField26 hi Alex #9839 I prepare some examples of KUCOIN future trading in CCXT

**Comment by DUK3135** [comment]
Thank you for your email i really appreciate it
