### ISSUE TITLE
HBTC (rebranded to BHEX) has endpoints with a new base url from BHEX 

### ISSUE THREAD

**Issue by KhaledYassin** [ccxt/ccxt#9163]
If you try to access the following website: https://www.hbtc.com/ for HBTC exchange you get redirected to https://www.bhex.co/ the new branding of the exchange. As such, all rest endpoints have a new base: https://api.bhex.com which is a step further from the current implementation where https://api.hbtc.com is the base. Usually, when exchanges rebrand they deprecate the old API version.

**Comment by kroitor** [comment]
BHEX is closing: https://support.hbtc.co/hc/en-us/articles/4406992059417
