### ISSUE TITLE
WAVES Exchange - Fetching Orders by Order ID

### ISSUE THREAD

**Issue by Maxximiliann** [ccxt/ccxt#9164]
https://github.com/ccxt/ccxt/blob/f9e3ed49aa775b89599365bc2e4183c9ba3be87d/python/ccxt/wavesexchange.py#L1004

How can the status of an order be retrieved using its id?

**Comment by kroitor** [comment]
@Maxximiliann you can filter the result of the `fetch_orders` call by order['id'] and then check the symbol in the remaining order structure:

- https://github.com/ccxt/ccxt/wiki/Manual#order-structure
- https://github.com/ccxt/ccxt/wiki/Manual#querying-orders

Let us know if that does not answer your question.

**Comment by fernandobender** [comment]
hi there.
freqtrade requires this method. fetch_order(), where the id is the input.
it works well binance, okex, kraken, ftx, etc.
could you please, implement it?
many thanks!
fernando a. bender

**Comment by fernandobender** [comment]
hello, @kroitor i'm not familiar with the flow on github and ccxt. so, excuse me if my question sounds redundant. is my request for implementation well placed? thanks in advance.

**Comment by kroitor** [comment]
@fernandobender yes, we will look into adding fetch_order for wavesexchange asap.

**Comment by fernandobender** [comment]
hi, there!
i've noticed that these other functions are both needed and missing out in wavesexchange.py
fetchTickers, fetchL2OrderBook
thank you!

**Comment by kroitor** [comment]
@fernandobender fetchTickers is not guaranteed to be available on all the exchanges, especially in cases when the exchange's API does not have a corresponding endpoint. This is documented in the Manual.
The fetchL2OrderBook is basically the same as fetchOrderBook in 99% cases. Hope that answers your question, let us know if not.
