### ISSUE TITLE
Ftx - Unexpected InsufficientFunds error

### ISSUE THREAD

**Issue by AlgoQ** [ccxt/ccxt#9166]
I was running my trading bot and got an unexpected InsufficientFunds error. I didn't have any order open. Also I'm using only 50% of my capital so this error is very weird. I was trying to open at a specific price with a post-only limit order which places a new one (after a slight delay to overcome spam errors). But suddenly it just stopped and got this error. Does someone have any clue how this could happen? Btw sorry for not providing that much code.

```python
connection = ccxt.ftx()

limitOrder = connection.create_order('AAVE-PERP', 'limit', 'buy', 1, 438.50, {'postOnly': True})
```

```
    limitOrder = self.connection.create_order(market, 'limit', 'buy', amount, price, params)
  File \"/usr/local/lib/python3.8/dist-packages/ccxt/ftx.py\", line 1128, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File \"/usr/local/lib/python3.8/dist-packages/ccxt/base/exchange.py\", line 470, in inner
    return entry(_self, **inner_kwargs)
  File \"/usr/local/lib/python3.8/dist-packages/ccxt/base/exchange.py\", line 495, in request
    return self.fetch2(path, api, method, params, headers, body)
  File \"/usr/local/lib/python3.8/dist-packages/ccxt/base/exchange.py\", line 491, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File \"/usr/local/lib/python3.8/dist-packages/ccxt/base/exchange.py\", line 618, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File \"/usr/local/lib/python3.8/dist-packages/ccxt/ftx.py\", line 1786, in handle_errors
    self.throw_broadly_matched_exception(self.exceptions['broad'], error, feedback)
  File \"/usr/local/lib/python3.8/dist-packages/ccxt/base/exchange.py\", line 514, in throw_broadly_matched_exception
    raise broad[broad_key](message)
ccxt.base.errors.InsufficientFunds: ftx {\"success\":false,\"error\":\"Account does not have enough margin for order.\"}
```

**Comment by Salz0** [comment]
Guys, anything here? Having the same issue
@kroitor ?
@frosty00 ?

**Comment by frosty00** [comment]
check the leverage you have set for that pair is enough, secondly check the the order of the args is

```
symbol, type, side, amount, price
```

make sure amount and price are in the correct order

make sure you have a balance on ftx, and that it is not used in any other orders or positions

**Comment by kroitor** [comment]
@Salz0 you can see what exactly is going on in `verbose` mode as documented here:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

**Comment by Salz0** [comment]
Thank you very much, @kroitor & @frosty00 .
Concise and on point

**Comment by ttodua** [comment]
As there has not been any follow-up, the above replies were mostly sufficient, so closing the issue.

**Comment by ttodua** [comment]
If anyone has any issues, feel free to ask.
