### ISSUE TITLE
create_order issue for huobipro

### ISSUE THREAD

**Issue by tandazhi** [ccxt/ccxt#917]
PASTE_YOUR_TEXT_DESCRIPTION_HERE

- OS: ubuntu
- Language: python
- CCXT version: 1.10.357
- Exchange: huobipro
- Method: create_order

```
p = ccxt.huobipro()
p.apiKey = ''
p.secret = ''
p.createLimitBuyOrder('BTM/ETH', 1, 0.0001)
```

```
>>> order = p.createLimitBuyOrder('BTM/ETH', 1, 0.0001)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 954, in create_limit_buy           _order
    return self.create_order(symbol, 'limit', 'buy', *args)
  File "/usr/local/lib/python3.6/dist-packages/ccxt/huobipro.py", line 390, in create_order
    response = self.privatePostOrderOrdersPlace(self.extend(order, params))
  File "/usr/local/lib/python3.6/dist-packages/ccxt/huobipro.py", line 436, in request
    raise ExchangeError(self.id + ' ' + self.json(response))
ccxt.base.errors.ExchangeError: huobipro {"status":"error","err-code":"order-orderamount-precision-e           rror","err-msg":"order amount precision error, scale: `0`","data":null}
```
Seems there is a problem with the function amount_to_precision(symbol, amount), it can not create a integer number for amount.

**Comment by kroitor** [comment]
Thank you for reporting this, will look into it and will fix it soon!

**Comment by gemini100** [comment]
exch.create_limit_buy_order(symb,qut, prixce)
i wrote it like that, but if it could help
when debugger ask precision it must your 1 set it with format float to 8 x,xxxxxxxx  i think(1.00000000)
you must try and see

huobipro {"status":"error","err-code":"order-orderamount-precision-e           rror","err-msg":"order amount precision error, scale: `0`","data":null}
