### ISSUE TITLE
FTX Subaccount Nickname

### ISSUE THREAD

**Issue by christophe-hall** [ccxt/ccxt#9170]
Might it be possible to set an optional 'nickname' property on FTX class in order to access a FTX subaccount?

ie. value corresponding to 'FTX-SUBACCOUNT' header as described here:

[https://blog.ftx.com/blog/api-authentication/](url)

Thanks.

**Comment by kroitor** [comment]
Yes: https://github.com/ccxt/ccxt/issues/8383#issuecomment-772391517

**Comment by ttodua** [comment]
Update: from now, you can now directly add the parameter in any method (without need to set the headers in exchange initialization properties), like:

`createOrder/FerchBalance( ..., ...,  params:{ "FTXUS-SUBACCOUNT":"mySubAcc"} ) `
