### ISSUE TITLE
should contain turnover of quote currency in ohlc data

### ISSUE THREAD

**Issue by foolcage** [ccxt/ccxt#9174]
now the ohlc data format:
```
[
    [
        1504541580000, // UTC timestamp in milliseconds, integer
        4235.4,        // (O)pen price, float
        4240.6,        // (H)ighest price, float
        4230.0,        // (L)owest price, float
        4230.7,        // (C)losing price, float
        37.72941911    // (V)olume (in terms of the base currency), float
    ],
    ...
]
```

It should contains turnover(volume of quote currency) if possible.

**Comment by foolcage** [comment]
Another suggestion: 
mabe we could give an option in the unitfied api to return original data?
e.g. return_original_data=True, and the result contains "orginal_data":{}

**Comment by kroitor** [comment]
> Another suggestion:
> mabe we could give an option in the unitfied api to return original data?
> e.g. return_original_data=True, and the result contains "orginal_data":{}

We already do that, you can find the original response in the `info` field.

**Comment by ttodua** [comment]
The feature will be implemented in near future.

**Comment by ttodua** [comment]
closing as wontfix for now. only reliable way is to override `parseOHLCV` (`parse_ohlcv`) method at this moment
