### ISSUE TITLE
Is it possible to fetch only closed candles from any interval from Binance.com ?

### ISSUE THREAD

**Issue by chromafunk** [ccxt/ccxt#9176]
I am interested only on closed candles, for all intervals. Is there a way to get them real time without opening a stream for each symbol and stream all klines until candle close ? This is very CPU intensive. Thanks !

**Comment by kroitor** [comment]
> Is there a way to get them real time without opening a stream for each symbol and stream all klines until candle close ? This is very CPU intensive.

Do you use CCXT Pro or some other software for streaming?

**Comment by chromafunk** [comment]
no, I'm just asking generally, I'm not using CCXT yet

**Comment by kroitor** [comment]
If architected properly, collecting the data is not CPU-intensive. You can get them with CCXT Pro or with CCXT. 
Calculating indicators over the data in realtime may be CPU intensive, but that's a different story.

- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/tree/master/examples

Let us know if that does not answer your questions. Feel free to reopen it or just ask further questions if any.
