### ISSUE TITLE
Arbitrage Trading question

### ISSUE THREAD

**Issue by adamrg73** [ccxt/ccxt#9178]
What would be the proper method to performing arbitrage trades with ccxt?

Like for example do you need to have money already deposited in each exchange? this is the main question im wondering if theres some sort of most efficient way of approaching this.

thanks

**Comment by Markusnarillious** [comment]
Now everyone is talking to me like i have some sort of money

**Comment by Markusnarillious** [comment]
Knowing to much is dangerous

**Comment by tuloski** [comment]
I don't think it's a question related to ccxt.
It's more about trading strategies for arbitrage.
BTW the steps are something like:

- Subscribe to books with watchOrderbook() to get the most recent books via ws (ccxt.pro)
- Implement the arbitrage strategy and calculate the trade prices and volumes
- Send trading orders with ccxt createLimitSellOrder (or buy order, or market orders depending on the strategies)

**Comment by HokhyTann** [comment]
> * via ws

what is ws?

**Comment by tuloski** [comment]
> > * via ws
> 
> what is ws?

websocket

**Comment by HokhyTann** [comment]
> > > * via ws
> > 
> > 
> > what is ws?
> 
> websocket

It's only available on ccxt.pro, right?

**Comment by kroitor** [comment]
@HokhyTann yes, it's available in ccxt.pro only at this time.

**Comment by adamrg73** [comment]
do you have to have funds in all the exchanges already in there before the orders are placed? I just wana make sure im not missing a technique? or do you send the funds in quick with the ccxt api and then do the trade? these details someone please outline the best steps most people use.

**Comment by tuloski** [comment]
> do you have to have funds in all the exchanges already in there before the orders are placed? I just wana make sure im not missing a technique? or do you send the funds in quick with the ccxt api and then do the trade? these details someone please outline the best steps most people use.

Please, this is not a forum on trading strategies. The best arbitrageurs won't discuss with you their technique learned in years of experience and trial/errors.
Consider taking a course on finance/trading. Arbitrage trading HAS risks and it requires some knowledge.
Please consider also closing this issue.

**Comment by kroitor** [comment]
@adamrg73 

> do you have to have funds in all the exchanges already in there before the orders are placed?

Yes, that's the only way to keep up with the arbitrage speeds.

> or do you send the funds in quick with the ccxt api and then do the trade?

That would be too slow, most of inter-exchange opportunities exists for seconds (if not milliseconds), and if your transfer takes minutes to confirm, you may lose the opportunity. There may still be some opportunities that exist long enough to catch them, but you should expect a lot of competition anyways.

In general, I think, @tuloski is right, we cannot really discuss it in-depth in this format, cause general arbitrage is a very wide field of ideas, covering it would require writing a book here on just this single issue alone. We can discuss technical questions on CCXT though. I would close this question for now, feel free to reopen it if you run into difficulties.
