### ISSUE TITLE
Binance - tracking exact filled quantities

### ISSUE THREAD

**Issue by serteikas** [ccxt/ccxt#9183]
I need to track the exact quantities available in the balance after executing a buy order on Binance.

The order structure gives me an indication that this is executed quantity:

> "filled": 0.035

However, in my wallet, I have 

> 0.03496500

I assume this amount is different due to fees. I looked into order structure and I see no fees indication so I cannot calculate it myself, nor do I see what is the actual filled amount (actual = available in my balance). All fields indicate it's 0.035.

Is there any way to see what actually gets filled (post fees) using CCXT?

Thanks.

**Comment by kroitor** [comment]
@serteikas there's several approaches to it:

1. First of all, Binance allows you to specify the default level of detail that you would get from a `create_order` call: https://github.com/ccxt/ccxt/blob/master/python/ccxt/binance.py#L572 . We are already using `FULL` details by default.

2. Secondly, you can call `fetch_my_trades` and filter those by the order id in question. From there you could take the actual filled sizes and fees for your order: https://github.com/ccxt/ccxt/wiki/Manual#personal-trades

Let us know if that does not answer your question.

**Comment by serteikas** [comment]
Clear.

Question: is there intent to add `fetch_order_trades `call for Binance?

**Comment by kroitor** [comment]
@serteikas afaik, Binance does not have a corresponding endpoint in the API: https://binance-docs.github.io/apidocs/spot/en/ Lmk if I am missing something.

**Comment by serteikas** [comment]
@kroitor I've just tried to do your purposed method of manual calculation - summing fees per trade and then subtracting from filled quantity.

However, it still doesn't add up precisely, take a look at associated trade (order size was 2.287):

> ['symbol': 'DOT/USDT', side': 'buy', 'takerOrMaker': 'taker', 'amount': 2.287, 'fee': {'cost': 0.002287, 'currency': 'DOT'}}]

expected end balance =` 2.284713`
actual end balance = `2.28494170`

I did not have any DOT in my wallet beforehand, and as you can see, the fees were taken from DOT itself rather than any other asset.

Any idea why I can't get it correct?

**Comment by kroitor** [comment]
@serteikas is that the only trade within that order?
> I did not have any DOT in my wallet beforehand, and as you can see, the fees were taken from DOT itself rather than any other asset.
Are you 100% sure? What do you see if you fetch your entire trade history for DOT/USDT ?

**Comment by serteikas** [comment]
@kroitor 

> @serteikas is that the only trade within that order?

Yes. Also indicated by the amount field in the trade, it is the whole quantity executed in a single trade.

> Are you 100% sure? What do you see if you fetch your entire trade history for DOT/USDT ?

I am pretty sure. I queried "free" balance just before I executed this order and I had no DOT available.

> What do you see if you fetch your entire trade history for DOT/USDT ?

The same single trade that's been executed, there are no more trades. And this is my first order with DOT. The unparsed exchange response `"info"` also indicates the same commission fee as parsed `"fees"` field.

I am sure that there has been no DOT in my wallet (baring technical issues on the exchange or some weird incident), but I'll wait for another transaction and then report if the calculation of the fees is still incorrect. Then we can at least verify that it's not a one-time occurrence and actually an issue.

**Comment by serteikas** [comment]
@kroitor 

Seems like it was a common floating-point arithmetic issue that I keep forgetting exists, lol.

I know it's unrelated, but do you have any suggestions on how to solve this specific issue? I've used `Decimal` module but even that doesn't really show the exact quantity.

As an example, `3e-7` doesn't get converted to `0.0000003`

**Comment by kroitor** [comment]
@serteikas you can use the new `Precise` class from CCXT, which we've added specifically to handle string-based representations.

**Comment by kroitor** [comment]
@serteikas also: https://github.com/ccxt/ccxt/wiki/Manual#methods-for-formatting-decimals

**Comment by serteikas** [comment]
@kroitor The problem wasn't in CCXT calculations actually, but just simple arithmetic between floats. Hence why the errors were incredibly marginal.

Executed quantity: `0.0003`
Sum fees: `3e-07`
Exec. qty - sum fees:` 0.00029969999999999997`

I still have not found a way which can fix this besides rounding numbers (decimal doesn't fix this). The problem with rounding numbers is that you need to know the exact precision beforehand. 

Ideally, `0.00029969999999999997` should be ` 0.0002997`

I just haven't found universal solution of converting/rounding numbers for all use cases like these.
