### ISSUE TITLE
What Time Does The Day Roll Over?

### ISSUE THREAD

**Issue by mmehrle** [ccxt/ccxt#9188]
Quick question: When do daily 'candles' roll over in ccxt? I am pulling daily data on a US server and for my system I need to know when the date stamps roll over into the new day/date. My understanding thus far is that it happens at 0:00 GMT. 

If correct then the roll over would be e.g. at 8:00pm in NYC, and 1:00am in London.

Can you please confirm or correct?

**Comment by kroitor** [comment]
Hi! Yes, all unified timestamps should be in UTC. Exchange-specific `info`s may have timestamps in other timezones, but CCXT converts them to UTC in the outer unified layer. If you find any inconsistencies, please let us know.

**Comment by mmehrle** [comment]
WOW - that was fast. You are the man. BTW, ccxt kicks ass - love it.

**Comment by mmehrle** [comment]
Follow up question. I'm setting up a cron job and my sys admin asked me if we are talking about UTC or GMT here. Because GMT accounts for DST while UTC does not. My 'guess' would be that exchanges use UTC but I just wanted to make sure.

Thanks in advance.

**Comment by mmehrle** [comment]
Never mind - you already answered that it's in UTC. My apologies - I have not gotten much sleep in the past few weeks :-}
