### ISSUE TITLE
Signature not valid: Verification failure [校验失败]

### ISSUE THREAD

**Issue by lingxiaolu18** [ccxt/ccxt#9189]
I'm encountering something that doesn't make sense to me. I'm using ccxt w/ huobi.pro exchange. I'm trying to get my order details and I've tried ex.privateGetOrderOrdersId() and ex.fetchOrder() but they all returned the same error while I can place orders as I want. I thought this couldn't be auth issue since place an order and get order details basically requires the same level of auth. bothered me for a while please help!!!!!!!!!
-----
I'm contructing the exchange instance by: 
```var ex = new ccxt.huobipro({ 'apiKey': process.env.accessKey, 'secret': process.env.secretKey});```
In addition, ```ex.privatePostOrderOrdersIdSubmitcancel()``` also returns the same err

- OS:macOS Catalina 10.15.7
- Programming Language version: Nodejs v12.16.3
- CCXT version:1.50.6

```
function getOrderDetail(orderId){
        return ex.fetch_order({'id': orderId})
  }
console.log(await getOrderDetail(orderId))
```

```
UnhandledPromiseRejectionWarning: AuthenticationError: huobipro {"status":"error","err-code":"api-signature-not-valid","err-msg":"Signature not valid: Verification failure [校验失败]","data":null}
```

**Comment by lingxiaolu18** [comment]
Any updates are appreciated :)

**Comment by lingxiaolu18** [comment]
@kroitor @frosty00 What's up guys!

**Comment by kroitor** [comment]
@lingxiaolu18

```Python
ex.fetch_order({'id': orderId})
```

↑ That is not a correct usage of CCXT, the first argument to `fetch_order` must be an order `id`, not an object:

```Python
ex.fetch_order(orderId, symbol)
```

- https://github.com/ccxt/ccxt/wiki/Manual#querying-orders
- https://github.com/ccxt/ccxt/wiki/Manual#by-order-id

Let us know if that does not answer your question.

**Comment by linnuo12** [comment]
@kroitor 
ccxtExchange.fetchBalance()

AuthenticationError: huobipro {"status":"error","err-code":"api-signature-not-valid","err-msg":"API签名无效: Incorrect IP address [IP地址错误]:14.198.128.41","data":null}

**Comment by kroitor** [comment]
@linnuo12 in your message KuCoin says that your IP address does not match the IP address that your API Key is bound to.

**Comment by linnuo12** [comment]
IP binding is normal, I will try again

**Comment by linnuo12** [comment]
@kroitor IP binding is normal, I will try again

**Comment by flowerDAI** [comment]
I have a similar question.    My key and secret is OK,
code:
var huobiExchange = new ccxt.huobi(new Dictionary<string, object>() {
    { "apiKey", "XXXXXX" },   
    { "secret", "XXXXXX" },
});
var accounts = await huobiExchange.FetchAccounts();
error:
{"status":"error","err-code":"api-signature-not-valid","err-msg":"Signature not valid: Verification failure [校验失败]","data":null}

**Comment by flowerDAI** [comment]
@lingxiaolu18 hello , May I ask how you solved it?

**Comment by carlosmiei** [comment]
@flowerDAI I managed to reproduce the issue, will open a new one and tag you there.
