### ISSUE TITLE
phemex fetchOrder BTC/USD order with id 9c9cb7c7-acd1-4f58-b396-3810e9f8f3c5 not found Python 3.8.3 phemex fetchOrder() if (difference <= 15000): out.write('[' + str(datetime.now()) + '] ' + "Liquidation Difference going Less than 15000\n\n") order_remaining = exchange.fetch_order(orderID, symbol)['remaining'] exchange.cancel_order(id=orderID, symbol=symbol) print("One Order has been cancel\nDifference less than 15000\nPlacing sell order")

### ISSUE THREAD

**Issue by RizwanAli-DTS** [ccxt/ccxt#9197]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:

```
REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS
```

```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
```

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/9158
