### ISSUE TITLE
None returned upon calling fetchCurrencies for Binance.

### ISSUE THREAD

**Issue by Kyusub-Hwang** [ccxt/ccxt#9198]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: windows10
- Programming Language version: Python3.5.2 on Jupyter notebook
- CCXT version: 1.49.94

```
import ccxt, time

myTime=str(int(time.time()*1000))
# from variable id
exchange_id = 'binance'
exchange_class = getattr(ccxt, exchange_id)
exchange = exchange_class({
    'apiKey': '-',
    'secret': '-',
    'timeout': 30000,
    'timestamp': myTime,
    'enableRateLimit': True,
})

print(exchange.fetchCurrencies())
```

```
None
```

I used the tutorials given in the manual and i could get data from some public endpoints. but when i use fetchCurrencies() function which requires private key, I get 'None ' although I found this method available in 'exchange.has',
I want to get each symbols(not pairs) and its withdrawability and depositability. Is there any other endpoints i could use maybe?
I'm a noob here and i'm totally lost T_T

**Comment by kroitor** [comment]
Hi! Binance's `fetchCurrencies` requires the apiKeys as you've noted correctly, therefore it's not a public method, and it's disabled by default, you can enable it via options (assuming you also pass the api keys to it). This should work, let us know if not:

```Python
import ccxt, time

myTime=str(int(time.time()*1000))
# from variable id
exchange_id = 'binance'
exchange_class = getattr(ccxt, exchange_id)
exchange = exchange_class({
    'apiKey': '-',
    'secret': '-',
    'timeout': 30000,
    'timestamp': myTime,
    'enableRateLimit': True,
    # ------------------------------------------- add this ↓
    'options': {
        'fetchCurrencies': True,
    },
})

print(exchange.fetchCurrencies())
```

**Comment by Kyusub-Hwang** [comment]
You saved my life !! thank you, K. i really appreciate your codes. it's marvellous !!! have a wonderful day!
