### ISSUE TITLE
Clarify the limitations on the number of exchanges in CCXT Pro tiers

### ISSUE THREAD

**Issue by tredondo** [ccxt/ccxt#9200]
https://ccxt.pro/pricing lists the "N exchanges" under different pricing tiers. What does that mean?

Simultaneous exchanges that can be watched during a given script execution?

Or maximum number of exchanges that can be instantiated at one time? (So for Beginner, I could instantiate 3 exchanges, then after one gets garbage collected, I can instantiate a different one?)

**Comment by kroitor** [comment]
I suggest reading this release issue: https://github.com/ccxt/ccxt/issues/6543 (expand hidden comments) – it has the answers to most of the licensing questions.

> Simultaneous exchanges that can be watched during a given script execution?
> Or maximum number of exchanges that can be instantiated at one time? (So for Beginner, I could instantiate 3 exchanges, then after one gets garbage collected, I can instantiate a different one?)

Max number of exchanges instantiated and watched simultaneously.

Let us know if that does not help.

**Comment by tredondo** [comment]
Thanks, I found the answer in [this comment](https://github.com/ccxt/ccxt/issues/6543#issuecomment-593094835).

That issue has a lot of comments, it might be worth making an FAQ out of it, or perhaps adding this particular question about the number of exchanges to the License doc.

**Comment by kroitor** [comment]
@tredondo 

> or perhaps adding this particular question about the number of exchanges to the License doc.

Will do!

Thx for your feedback, we really appreciate it!
