### ISSUE TITLE
Errors building CCXT Pro JavaScript from cloned repo

### ISSUE THREAD

**Issue by tredondo** [ccxt/ccxt#9201]
- OS: Linux
- Programming Language version: Node 15
- CCXT version: Cloned CCXT Pro repo

I'm having issues building CCXT Pro:
1. The [JS build instructions](https://github.com/ccxt/ccxt/wiki/ccxt.pro.install#javascript-installation-from-a-cloned-source-code-repository) should include `npm install`
2. I ran `npm install` myself. After that, `npm run build` fails at the `npm run check-js-syntax` step with many `Require statement not part of import statement  @typescript-eslint/no-var-requires` errors:

```
> ccxt.pro@0.6.90 check-js-syntax
> pwd && eslint --version && eslint 'js/*.js'

/z/prg/fin/ccxt.pro
v6.8.0

/home/tredondo/ccxt.pro/js/bequant.js
  5:16  error  Require statement not part of import statement  @typescript-eslint/no-var-requires

/home/tredondo/ccxt.pro/js/binance.js
    5:14  error    Require statement not part of import statement  @typescript-eslint/no-var-requires
 
etc.
```

**Comment by tredondo** [comment]
Hi, I wanted to check on the status of this as a customer, and to update that I managed to use the library [with TypeScript](https://github.com/ccxt/ccxt/issues/9208) simply by importing the JS. I haven't looked in detail, is the build step only necessary for PHP and Python?

**Comment by kroitor** [comment]
> I haven't looked in detail, is the build step only necessary for PHP and Python?

Yes, it's mostly needed for other languages, or if you're developing a new exchange integration.
If you just want to use it, then you don't have to build it.
The TypeScript support in CCXT and CCXT Pro is still rudimentary (we're working on making it better), so, for now the best way to use in a TS project is to import JS directly.

Let us know if that does not answer your question. Feel free to reopen this issue or just ask further questions if any.
