### ISSUE TITLE
How to catch error in throttling mode in ccxt pro

### ISSUE THREAD

**Issue by teneon** [ccxt/ccxt#9202]
- OS: Ubuntu 20.04
- Programming Language version: Typescript / Node
- CCXT version: 1.41.86

Hi there,

i have a question regarding ccxt pro. I am reading manual, section: "Real-Time vs Throttling".

```js
// real-time mode
const limit = 5 // optional
while (true) {
    try {
        const orderbook = await exchange.watchOrderBook (symbol, limit)
        // your reaction to the update takes place here
        // you arrive here after receiving the update from the exchange in real time
        console.log (orderbook) // every update
    } catch (e) {
        console.log (e)
        // throw e // uncomment to stop the loop on exceptions
    }
}
```

```js
// throttling mode
const limit = 5 // optional
// await is optional, alternatively you can launch it in bg without await
await exchange.watchOrderBook (symbol, limit)
while (true) {
    // your reaction takes place here
    // you arrive here every 100 ms regardless of whether there was an update or not
    // in throttling mode offloading the orderbook with .limit () is required
    console.log (exchange.orderbooks[symbol].limit (limit))
    await exchange.sleep (100) // every 100 ms
}
```
In realtime mode, i can catch an error and execute some actions based on the error output, which i am currently doing for counting subscriptions ,confirmations etc, basically i rely on it to see if pairs are unsubscribed or if everyone is subscribed etc.

Is it possible to catch the same error in throttling mode,  instantly as it happens (just like in realtime mode?).

Kind regards,
Neon

**Comment by kroitor** [comment]
@teneon hi!

> Is it possible to catch the same error in throttling mode, instantly as it happens (just like in realtime mode?).

Yes, you can override the onError method to add your handling:

```JavaScript
class MyBinance extends ccxtpro.binance {
    onError (client, error) {
        // your custom code ----------------
        console.log (error) // intercept it here
        // don't forget to call the parent method
        return super.onError (client, error)
    }
}

const exchange = new MyBinance ({ 'enableRateLimit': true })

// ...
```

Let us know if that does not answer your question or does not help.

**Comment by kroitor** [comment]
P.S. we will also some more methods ands hooks for granular control over the subscriptions and errors in throttling mode.
