### ISSUE TITLE
Probit: fetch public trades with time range

### ISSUE THREAD

**Issue by viktor-settlemint** [ccxt/ccxt#9203]
Hi guys, 

I am trying to easily fetch the public trades for a specific pair on Probit.
Without the since, it returns me the latest 100 trades. But I would like to have only the trades since a specific timestamp. I tried the below code but my params are not correct. I looked a bit in the doc but I was not able to find the proper answer. Can you guys help me please? Thanks

- OS: Ubuntu 18
- Programming Language version: Python 3.7
- CCXT version: 1.50.8

```
from datetime import datetime
from datetime import timedelta

probit = getattr(ccxt,'probit')({
        # https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
        'enableRateLimit': True
    })
END_TIME = datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%S.%f')[:-3]
START_TIME = (datetime.utcnow() - timedelta(seconds= 360)).strftime('%Y-%m-%dT%H:%M:%S.%f')[:-3]
trades = probit.fetch_trades('DTX/USDT', START_TIME, END_TIME)
```

```
BadRequest: probit {"errorCode":"INVALID_ARGUMENT","message":"","details":{"start_time":"invalid","limit":"invalid"}}
```

**Comment by Djusk8** [comment]
Unfortunatelly you can't use END_TIME.

If you check fetch_trades() method, you find there is only `since` parameter you can you. 
    `def fetch_trades(self, symbol, since=None, limit=None, params={})`

You need to pass START_TIME as `int`.
This works for me:


```
from datetime import datetime
from datetime import timedelta

import ccxt

probit = getattr(ccxt, 'probit')({'enableRateLimit': True})
START_TIME = int((datetime.utcnow() - timedelta(seconds=360)).timestamp())
trades = probit.fetch_trades('DTX/USDT', START_TIME)
print(trades)
```

**Comment by kroitor** [comment]
@Djusk8 thank you! Appreciate your help!

**Comment by kroitor** [comment]
@viktor-settlemint more about it here:

- https://github.com/ccxt/ccxt/wiki/Manual#pagination
