### ISSUE TITLE
binance DAI/USDT consistency of base and quote bug?

### ISSUE THREAD

**Issue by jom1337** [ccxt/ccxt#9205]
Hey,

other exchanges use DAI/USDT but binance seems to give data only on USDT/DAI
can someone give me a hint to fix this "financially and terminologically correct"?

https://ccxt.readthedocs.io/en/latest/manual.html#consistency-of-base-and-quote-currencies

- OS: macOS
- Programming Language version: nodejs v14.15.4
- CCXT version: 1.50.8

```
'use strict';

const ccxtpro = require ('ccxt.pro');

(async () => {

    const exchange = new ccxtpro.binance ({ enableRateLimit: true })
    const symbols = [ 'DAI/USDT', 'USDT/DAI' ]

    await Promise.all (symbols.map (symbol =>

        (async () => {

            while (true) {
                try {
                    const orderbook = await exchange.watchOrderBook (symbol)
                    console.log (new Date (), symbol, orderbook['asks'][0], orderbook['bids'][0])
                } catch (e) {
                    console.log (symbol, e)
                    // do nothing and retry on next loop iteration
                    // throw e // uncomment to break all loops in case of an error in any one of them
                    // break // you can also break just this one loop if it fails
                }
            }

        }) ())
    )
}) ()
```

```
2021-05-18T16:29:07.906Z DAI/USDT undefined undefined
2021-05-18T16:29:08.444Z USDT/DAI [ 1.0004, 168491.11 ] [ 1.0003, 42688.34 ]
```

**Comment by kroitor** [comment]
Let us know if this does not answer your question:

- https://www.binance.com/en/trade/USDT_DAI?type=spot
- https://www.binance.com/en/trade/DAI_USDT?type=spot

<img width="1567" alt="Screenshot 2021-05-18 at 21 56 41" src="https://user-images.githubusercontent.com/1294454/118708076-f47b0080-b823-11eb-8536-36d9b103de46.png">

- https://api.binance.com/api/v3/exchangeInfo

<img width="1376" alt="Screenshot 2021-05-18 at 21 59 05" src="https://user-images.githubusercontent.com/1294454/118708342-491e7b80-b824-11eb-83eb-31eafff1c609.png">

<img width="1376" alt="Screenshot 2021-05-18 at 21 59 05" src="https://user-images.githubusercontent.com/1294454/118708357-50de2000-b824-11eb-82ca-a2a7abd2034c.png">

**Comment by diwenshi61** [comment]
To clarify on @kroitor 's answer:
I believe what that section of the docs refers to is incorrect symbols, where an exchange might have for example
a market USDT/BTC with bid 42000 and ask 43000. So for consistency, that would be corrected.
Binance has USDT as the base currency and DAI as the quote currency in this case.

You should use the 'base' and 'quote' attributes of the market as described [here](https://ccxt.readthedocs.io/en/latest/manual.html#market-structure) in order to determine the base and quote currencies of a market rather than the symbol.
To do what you want, you should aggregate the markets containing DAI and USDT as the base and quote currencies from exchanges in any order, and 'flip' the ones that are USDT as base, DAI as quote, by taking the inverse of the ask and turning that into the bid, and vice versa for the bid.
i.e. from your format (ask, bid)
`[ 10, 15 ] [ 5, 10 ]`
becomes
`[ 0.2, 10 ] [ 0.1, 15 ]`

**Comment by kroitor** [comment]
@diwenshi61 you're right, but in this case, i think, the answer is simpler: https://t.me/binance_api_english

> Igor Kroitor, [18 May 2021, 22:01:38]:
> Hello, dear Binance support!
> We have a question on this endpoint: https://api.binance.com/api/v3/exchangeInfo
> On spot markets it serves two pairs: DAIUSDT and USDTDAI.
> But one of them is not available:
> - https://www.binance.com/en/trade/USDT_DAI?type=spot (works)
> - https://www.binance.com/en/trade/DAI_USDT?type=spot (does not work)
>
> And we don’t see the one that does not work here:
> https://user-images.githubusercontent.com/1294454/118708076-f47b0080-b823-11eb-8536-36d9b103de46.png
> The question is: does the exchangeInfo endpoint lie about spot DAI markets?
> We see both DAIUSDT and USDTDAI on the output from that endpoint here (Both markets appear to be tradeable, but one of them does not show up on the web UI)
> https://user-images.githubusercontent.com/1294454/118708342-491e7b80-b824-11eb-83eb-31eafff1c609.png
> https://user-images.githubusercontent.com/1294454/118708357-50de2000-b824-11eb-82ca-a2a7abd2034c.png

**Comment by kroitor** [comment]
@diwenshi61 actually, i think i accidentally missed it, but the second pair is market as "status: BREAK" (not tradeable)...

**Comment by diwenshi61** [comment]
@kroitor I think Binance originally has DAI/USDT pair, but reversed it later on. So the original is gone.
https://www.binance.com/en/support/announcement/cf77f566c9b64cc791fc152679175de8

**Comment by kroitor** [comment]
@jom1337 let us know if this does not help:

```shell
node examples/js/cli binance markets --table  # will print a very wide table
```

```JavaScript
const ccxtpro = require ('ccxt.pro')

async function main () {
    const exchange = new ccxtpro.binance ({
       'enableRateLimit': true,
    })
    const markets = await exchange.loadMarkets()
    const first = exchange.market('DAI/USDT')
    const second = exchange.market('USDT/DAI')
    console.log ({ symbol: first['symbol'], active: first['active'] })
    console.log ({ symbol: second['symbol'], active: second['active'] })
}

main ()
```

**Comment by kroitor** [comment]
@jom1337 more about market properties here: 
- https://github.com/ccxt/ccxt/wiki/Manual#markets
- https://github.com/ccxt/ccxt/wiki/Manual#market-structure

**Comment by jom1337** [comment]
yep, thanks @kroitor and a special thanks to @diwenshi61 for the math part.
For everyone else who has the question and is struggeling with math and english :) here is the answer:

DAI/USDT
```
{ ask: { price: 10, volume: 15 }, bid: { price: 5, volume: 10 } }
```

becomes USDT/DAI

```
bid.price = 1 / ask.price
bid.volume = ask.volume
ask.price = 1 / bid.price
ask.volume = bid.volume

{ ask: { price: 0.2, volume: 10 }, bid: { price: 0.1, volume: 15 } }
```
