### ISSUE TITLE
New Exchange: Blockchain.com

### ISSUE THREAD

**Issue by Droppix** [ccxt/ccxt#9206]
Hi,

Apparently, ccxt does not support Blockchain.com? Is there any particular reason?
(https://api.blockchain.com/v3/)

Thanks

**Comment by kroitor** [comment]
> Is there any particular reason?

No specific reason, most of the reasoning is outlined here: https://github.com/ccxt/ccxt/wiki/FAQ#can-you-implement-feature-foo-in-exchange-bar

**Comment by kroitor** [comment]
Added in CCXT 1.65.36+.
