### ISSUE TITLE
FTX: Can't cancel opened Order / Can't get Order ID's of open Orders (PHP)

### ISSUE THREAD

**Issue by hm291195** [ccxt/ccxt#9207]
i can successfully create orders with :

`$exchange->create_order($symbol, $type, $side, $amount, $price, $params);`
```
Array
(
    [info] => Array
        (
            [id] => 44022042
            [market] => BTC-PERP
            [future] => BTC-PERP
            [side] => sell
            [type] => take_profit
            [orderPrice] => 48100.0
            [triggerPrice] => 47000.0
            [size] => 0.001
            [status] => open
            [createdAt] => 2021-05-18T20:09:03.654365+00:00
            [triggeredAt] => 
            [orderId] => 
            [error] => 
            [reduceOnly] => 
            [trailValue] => 
            [trailStart] => 
            [cancelledAt] => 
            [cancelReason] => 
            [retryUntilFilled] => 
            [orderType] => limit
        )

    [id] => 44022042
    [clientOrderId] => 
    [timestamp] => 1621368543654
    [datetime] => 2021-05-18T20:09:03.654Z
    [lastTradeTimestamp] => 
    [symbol] => BTC-PERP
    [type] => take_profit
    [timeInForce] => 
    [postOnly] => 
    [side] => sell
    [price] => 47000
    [stopPrice] => 47000
    [amount] => 0.001
    [cost] => 
    [average] => 
    [filled] => 
    [remaining] => 
    [status] => open
    [fee] => 
    [trades] => 
)

```

but if i want to close this order with
`$exchange->cancel_order(44022042)`

i get an error

`ccxt\OrderNotFound: ftx {"success":false,"error":"Order not found"}`

also 

`$exchange->fetch_open_orders() `returns an empty array even though i have open orders

**Comment by kroitor** [comment]
@hm291195 if you're canceling a conditional take_profit order, you have to add a `type` param override, otherwise it will attempt to cancel a regular order with that id instead of the conditional order:

```PHP
$exchange->cancel_order(44022042, null, array('type'=>'takeProfit'));
```

Let us know if that does not answer your question.

**Comment by hm291195** [comment]
ok this works.

And regarding the second part - why does `$exchange->fetch_open_orders() `return an empty array even though i have open orders ? Is there also a param override neccessary ?


Last but not least i just figured out another ambiguity:

if i fetch my open positions with `$exchange->fetch_positions() `why does the array contain positions that are already closed ? Am i right, that the only way to find out my open positions is to check each key of the array if there is "openSize" which is then > 0 to find out if the position is still open or already closed ?

**Comment by kroitor** [comment]
@hm291195 

> And regarding the second part - why does $exchange->fetch_open_orders() return an empty array even though i have open orders ? Is there also a param override neccessary ?

Yes, you have to add a param override for conditionals: 

```PHP
$since = null;
$limit = null;
$params = array('type'=>'takeProfit');
$orders = $exchange->fetch_open_orders($symbol, $since, $limit, $params);
```

> Am i right, that the only way to find out my open positions is to check each key of the array if there is "openSize" which is then > 0 to find out if the position is still open or already closed ?

Yes, that is correct.

**Comment by hm291195** [comment]
sorry for the duplicate post, i thought my answer here might not show up since the question was closed yesterday after your answer!

thanks for clarifying.
