### ISSUE TITLE
CCXT Pro usage with TypeScript

### ISSUE THREAD

**Issue by tredondo** [ccxt/ccxt#9208]
Since I [wasn't able to build CCXT Pro](https://github.com/ccxt/ccxt/issues/9201), I tried to use it directly from its git repo:

```sh
git clone https://github.com/kroitor/ccxt.pro.git
cd ccxt.pro
npm install
npm install ts-node
node --loader ts-node/esm myccxt.ts
```

But, I get the error

> Unable to compile TypeScript:
> ccxt.ts(1,18): error TS2306: File '/home/tredondo/ccxt.pro/ccxt.pro.d.ts' is not a module.

**myccxt.ts**
```ts
import ccxt from './ccxt.pro.js';

const cbpro = new ccxt.coinbasepro({

});
```

I'm probalby doing something wrong since I wasn't able to complete the build step.

Is [TypeScript supported](https://github.com/ccxt/ccxt/pull/6510)? Would be nice to add TypeScript usage to [the wiki](https://github.com/ccxt/ccxt/wiki/ccxt.pro.install).

**Comment by kroitor** [comment]
```
cd ~
mkdir test_ccxtpro_install
cd test_ccxtpro_install
git clone https://github.com/kroitor/ccxt.pro.git
cd ccxt.pro
npm install
npm link
cd ..
mkdir my_ts_project
cd my_ts_project
npm init  # hit enter many times for all defaults
npm install ts-node
npm link ccxtpro
```

Then, in `my_ts_project/myccxt.ts`, you can `import ccxtpro from ccxt.pro` and run the code.
Let us know if the above does not help / does not work.

**Comment by tredondo** [comment]
Thanks, I'll check that. In the meantime I got it to work only by adding this `tsconfig.json`:
```json
{
  "compilerOptions": {
    "skipLibCheck": true,
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
  },
}
```

**Comment by kroitor** [comment]
@tredondo we will try to make it easier to import into a TS project. Thx for your feedback!

**Comment by frosty00** [comment]
#6510

**Comment by frosty00** [comment]
ccxt has since transitioned to typescript everywhere
