### ISSUE TITLE
Issues with FTX (PHP)

### ISSUE THREAD

**Issue by hm291195** [ccxt/ccxt#9209]
a) $exchange->fetch_open_orders() return an empty array even though i have open orders ? Is there a param override neccessary for open conditional orders ?

b) if i fetch my open positions with $exchange->fetch_positions() why does the array contain positions that are both - open and closed. Am i right, that the only way to find out my open positions is to check each key of the array if there is "openSize" which is then > 0 to find out if the position is still open or already closed ?

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/9207
