### ISSUE TITLE
Continuous Integration for Windows with Appveyor

### ISSUE THREAD

**Issue by thijstriemstra** [ccxt/ccxt#921]
It would be useful to have an appveyor windows build so we can verify this stuff is also able to compile on windows (for people that prefer that operating system aka noobs). I can look into a PR.

**Comment by kroitor** [comment]
Thanks for your proposal! We think it would be awesome! Let us know if you need any assistance.

**Comment by thijstriemstra** [comment]
@kroitor can you enable appveyor for this repository?

**Comment by kroitor** [comment]
@thijstriemstra sure, will do! Have to read more about setting it up, but this should be easy, I believe. Will get back to you on this when I have it all set.

**Comment by thijstriemstra** [comment]
yes, its same as enabling travis.

**Comment by kroitor** [comment]
https://ci.appveyor.com/project/ccxt/ccxt
