### ISSUE TITLE
ccxt 1.39.2 dissapeared from pypi

### ISSUE THREAD

**Issue by aurelianito** [ccxt/ccxt#9211]
Why was it erased? What version should we use instead? 

Thanks in advance!

**Comment by kroitor** [comment]
@aurelianito you have to upgrade to the most recent version 1.50+. We had to clean up old releases to free up PyPI space, since CCXT is quite a large lib and requires a lot of storage. Let us know if that does not help.

**Comment by kroitor** [comment]
P.S. we keep a history of the most recent five minor releases, 1.46-1.50+.

**Comment by aurelianito** [comment]
Did not knew that you removed releases as a policy. Are there some "stable" releases that you keep for longer?

**Comment by kroitor** [comment]
@aurelianito yes, 1.39.1 is still there, and every first version should be still there.

**Comment by aurelianito** [comment]
What's the criteria to make a version a "first version"?

**Comment by kroitor** [comment]
@aurelianito there's no fixed criteria, when we accumulate 100 fixes/patches/updates we just switch the minor version number. So, it is a smooth and linear history of versions/upgrades.

**Comment by aurelianito** [comment]
If I want a version to be kept should I bump to 1.50.1 instead of 1.50.11 (current latest)?

**Comment by kroitor** [comment]
@aurelianito yes, you can bump to 1.50.1, but we don't recommend keeping your versions for too long, cause the exchanges update their apis, add new features and symbol mappings, etc, etc – all of that makes CCXT a live project, not something "fixed".
