### ISSUE TITLE
FTX: Mark Price of an open Position is shown as Entry Price (php)

### ISSUE THREAD

**Issue by hm291195** [ccxt/ccxt#9213]
when fetching the open positions through `$this->exchange->fetch_positions()`
```

            [future] => ....
            [size] => 0.5
            [side] => buy
            [netSize] => 0.5
            [longOrderSize] => 0.0
            [shortOrderSize] => 0.0
            [cost] => 7.3695
            [entryPrice] => 14.739
            [unrealizedPnl] => 0.0
            [realizedPnl] => 120.8533476
            [initialMarginRequirement] => 0.05
            [maintenanceMarginRequirement] => 0.03
            [openSize] => 0.5
            [collateralUsed] => 0.368475
            [estimatedLiquidationPrice] => 5.633292620508
```

the 'entryPrice' is actually not the entry Price, but the Mark Price

**Comment by hm291195** [comment]
is there any quick workaround for this ?

**Comment by kroitor** [comment]
@hm291195 you can switch that on the user side, it's what the FTX API serves directly: https://docs.ftx.com/#get-positions
The `fetchPositions / fetch_positions` method is not fully unified yet, it's a work in progress. Let us know if that does not answer your question.

**Comment by hm291195** [comment]
i cant find any way to get my entry price or average entry price.

sure, i could calculate it on my own , if i save the average fill price from the buy order.
but this only works, if i have opened the trade through my script. if i open the trade on the exchange, there is no way, that my script can ever get the entry/average open price ?

i tried as well fetch_my_trades() but this will result in the same problem since i cant differ, which trades have been opened through my script and which have been opened directly on the exchange gui.

**Comment by hm291195** [comment]
found in the FTX API DOC https://docs.ftx.com/#get-account-information that they accept the Parameter showAvgPrice 
But the response is the same if i do 
`$Exchange->fetch_positions(null, array('showAvgPrice' => false)`
or
`$Exchange->fetch_positions(null, array('showAvgPrice' => true)`

**Comment by kroitor** [comment]
@hm291195 i don't think that the `showAvgPrice` is meant for getting the entry price. You might want to calculate it from the actual trades with fetchMyTrades on that symbol.
