### ISSUE TITLE
fetchBalance rounding problem

### ISSUE THREAD

**Issue by krychla1** [ccxt/ccxt#9214]
Hi kroitor,
currently fetchBalance rounds the string from exchange to nearest value at x decimals (e.g. 79742.2000000099941857 -> 79742.20000001). This might create a bit greater balance than available, causing troubles.

Is there any possibility to set the rounding of fetchBalance method? Or output mode (number/string)? Or is it possible to fix the default roundmode to round_down to prevent this? 

- OS: all
- Programming Language version: nodejs
- CCXT version: ccxt@1.50.11
- exchange: hitbtc

```
GET https://api.hitbtc.com/api/2/trading/balance 
{"currency":"xxx","available":"79742.2000000099941857","reserved":"0"}
```

```
balance object:
{
  "free": 79742.20000001,
  "used": 0,
  "total": 79742.20000001
}
```

**Comment by kroitor** [comment]
Hi @krychla1!

> currently fetchBalance rounds the string from exchange to nearest value at x decimals (e.g. 79742.2000000099941857 -> 79742.20000001). This might create a bit greater balance than available, causing troubles.

Yes, that is actually a side-effect of floats, we are aware of it and we are now moving to string-based representations everywhere that will solve this issue for all exchanges. This is already a work in progress.

**Comment by krychla1** [comment]
That seems like quite a big change. Is it scheduled for a particular major release? Or how will we know?
Thank you.

**Comment by kroitor** [comment]
@krychla1 it is already implemented for most of the exchanges' fetchBalance methods, check parseBalance here: https://github.com/ccxt/ccxt/blob/master/js/base/Exchange.js#L983. We will switch to using string-based representation when this process is complete for all other methods – at that point we will add a bunch of edits to the Manual and will post here.

**Comment by kroitor** [comment]
@krychla1 i will close this for now if you don't mind, we will post an update here: https://github.com/ccxt/ccxt/issues/522, feel free to reopen it or just ask further questions if any.
