### ISSUE TITLE
fetchOrderTrades not supported in huobipro

### ISSUE THREAD

**Issue by litcto** [ccxt/ccxt#9215]
Hi,

I'm using CCXT 1.49.53 on Python 3.7 on CentOS 7.

I want to use 'fetchOrderTrades' in huobi, but in ccxt, this method is not supported on huobipro.

I checked the huobi api, and it's supported it. The request url is: /v1/order/orders/{order-id}/matchresults.

Looking forward to your reply

Thanks in advance

**Comment by kroitor** [comment]
Hi! We will add it asap!

**Comment by litcto** [comment]
Hi, kroitor,

`trades = exchange.fetchMyTrades()`

`trades = exchange.fetchOrdersTrades('282249848497929')`

`print(trades)`

The above results are the same.

order-id parameter seems not take effect.

Is it that I am using incorrectly？

**Comment by kroitor** [comment]
@litcto looks like a bug, plz hold on, will push a fix shortly.

**Comment by kroitor** [comment]
@litcto plz let us know if you still have this issue with version 1.50.24+ (it will arrive in 20 minutes), thx for reporting it!

**Comment by litcto** [comment]
ok，i will try later, thx a lot!

**Comment by litcto** [comment]
@kroitor  I'm using version 1.50.27, the problem still exists...

**Comment by kroitor** [comment]
@litcto please paste the full code (without your keys, but including the instantiation) and your verbose output: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by litcto** [comment]
```
def getOrderById(exchange_id, apiKey ,apiSecret, password):
    try:
        exchange_class = getattr(ccxt, exchange_id)
        exchange = exchange_class({
            'apiKey': apiKey,
            'secret': apiSecret,
            'password': password,
            'timeout': 30000,
        })
        trades1 = exchange.fetchMyTrades()
        print(exchange.has['fetchOrderTrades'])
        trades2 = exchange.fetch_order_trades('282249848497929')
        print(len(trades1))
        print(len(trades2))
        return trades2
    except:
        return ""

getOrderById('huobipro', 'xxxxxxx' , 'xxxxxxxxx' , '1')
```

Help check please, thx！

**Comment by kroitor** [comment]
@litcto please, edit for your keys and paste your complete verbose output:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```Python
import ccxt
from pprint import pprint
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.huobipro({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})
markets = exchange.load_markets()
exchange.verbose = True
print('----------------------------------------------------------------------')
order = exchange.fetch_order('282249848497929')
pprint(order)
print('----------------------------------------------------------------------')
trades = exchange.fetch_order_trades('282249848497929')
pprint(trades)
print('----------------------------------------------------------------------')
```

**Comment by litcto** [comment]
Too many results.  Look at the screenshot.
fetch_order:
![image](https://user-images.githubusercontent.com/6800277/119790402-7ba43480-bf06-11eb-85ee-b96266afb9ab.png)
fetch_order_trades:
![image](https://user-images.githubusercontent.com/6800277/119790401-7ba43480-bf06-11eb-9fca-830dd3eda60e.png)

I guess the interface request is incorrect:
![image](https://user-images.githubusercontent.com/6800277/119790504-92e32200-bf06-11eb-9d68-731bda60d147.png)

**Comment by kroitor** [comment]
@litcto ok, i've pushed another fix for it, please, let us know if this issue still persists on your side after upgrading to version 1.50.51 (the new build will arrive in ~20 minutes). Thanks for your feedback!

**Comment by litcto** [comment]
@kroitor It works well. thx!
