### ISSUE TITLE
Bitfinex platform status is operative but fetchStatus() of the v2 API return maintenance

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#9217]
Hello,

I don't understand why this API call return `maintenance` and it seems to me that the inconsistency occured yesterday during the market crash.

```
b = ccxt.bitfinex2()
b.fetchStatus()
{'status': 'maintenance', 'updated': 1621499689085, 'eta': None, 'url': None}
```

When is reality the platforme status is `1` (.i.e. operative).
https://api-pub.bitfinex.com/v2/platform/status

https://docs.bitfinex.com/reference#rest-public-platform-status

What could be the reason ?

Thank you

**Comment by kroitor** [comment]
@Kinzowa fixed in 1.50.12 (will arrive in ~20 minutes), thx for reporting!
