### ISSUE TITLE
How to group orderbook data by prices?

### ISSUE THREAD

**Issue by sofomryu** [ccxt/ccxt#9220]
- OS: Windows10
- Programming Language version: python 3.8.5
- CCXT version:1.50.14

Hello, I'm trying to fetch orderbook data grouped by prices.
In ftx, data in orderbook(ask volume and bid volume) can be grouped by prices that I want.
For example, I can group orderbook of XRP as unit of 0.025, 0.01, etc. 
In the manual, it says the params for grouping may be found in each exchange's website.
Unfortunately, the ftx's website only provide 'limit' in orderbook, not params for group in orderbook.
Is there a param for grouping orderbook?

I tried 
`import ccxt`
`ftx=ccxt.ftx()`
`orderbook = ftx.fetch_order_book(s,params={'count'=1}) ` or `orderbook = ftx.fetch_order_book(s,params={'group'=1})`

Have a nice day!

**Comment by diwenshi61** [comment]
Unfortunately, according to FTX docs, grouping is only available on websocket orderbook data.
Using fetch_orderbook, you can manually group the orderbooks.
The following information is necessary to replicate the grouped orderbooks:
`Note that the price groupings are conservative: with a price grouping of 100, the size for a bid at 9395.5 would be attributed to the 9300 level, and the size for an ask at the same price would be attributed to the 9400 level.`
(https://docs.ftx.com/#grouped-orderbooks)

Currently, I don't believe that CCXT Pro natively supports the grouped orderbook channel either.
@kroitor can probably provide more information on websocket support for grouped orderbooks.

**Comment by frosty00** [comment]
the easiest way is to do this manually from the raw l2 data. anyway the grouped data is not so accurate...
