### ISSUE TITLE
FTX: cant fetch a conditional order (php)

### ISSUE THREAD

**Issue by hm291195** [ccxt/ccxt#9221]
trying 

`this->exchange->fetch_order($id, null, array('type' => 'stop'));`

results in

`ftx {"success":false,"error":"Order not found"}`

if using `$this->exchange->fetch_open_orders(null, null, null, array('type' => 'stop')); `
the order shows up...

**Comment by kroitor** [comment]
There is no documented endpoint for FTX API that would fetch a single conditional order by id: 

- https://docs.ftx.com/#get-open-trigger-orders
- https://docs.ftx.com/#get-trigger-order-triggers
- https://docs.ftx.com/#get-trigger-order-history

Let us know if that does not answer your question or if we are missing something.
