### ISSUE TITLE
Python error in manual

### ISSUE THREAD

**Issue by aribo** [ccxt/ccxt#9222]
In the manual (https://github.com/ccxt/ccxt/wiki/Manual) under the section on "Testnets And Sandbox Environments" the Python code is wrong.

```
# Python
const exchange = new ccxt.binance(config)
exchange.set_sandbox_mode(true)  # enable sandbox mode
```

It should be:
```
# Python
exchange = ccxt.binance(config)
exchange.set_sandbox_mode(True)  # enable sandbox mode
```

**Comment by aribo** [comment]
There's still an error.
`const exchange` => `exchange`

**Comment by kroitor** [comment]
@aribo ah, right, missed that! Thx for your attention!
