### ISSUE TITLE
Lending API

### ISSUE THREAD

**Issue by brandsimon** [ccxt/ccxt#9240]
Are there any plans to unify a lending API?
Has somebody already some experience with different exchanges in that area?

**Comment by ttodua** [comment]
A late reply here, but if you can, tell namely which exchanges and what common functionalities you mean?
(also, at this moment, you might search `borrow` or `margin` keywords across library to have a bit more insights about current state of ccxt)

**Comment by ttodua** [comment]
for future readers, if there is need of specific functionality, please mention few more details.

**Comment by posix4e** [comment]
Why was this closed?

**Comment by hmltn-0** [comment]
Here's how I would do it:

1. Base Class Definition (js/base/Exchange.js)
```javascript
class LendingApi {
  async fetchLendingMarkets (params = {}) {}
  async fetchLendingPositions (symbol = undefined, params = {}) {}
  async createLendingPosition (symbol, amount, rate, params = {}) {}
  async closeLendingPosition (id, params = {}) {}
  async fetchLendingRates (symbols = undefined, params = {}) {}
}
```

2. Exchange-Specific Implementations
```javascript
class bitfinex extends Exchange {
  async fetchLendingMarkets (params = {}) {
    // Bitfinex-specific implementation
  }
  // Implement other methods...
}
// Repeat for Gate.io and MEXC
```

3. API Mapping
```javascript
{
  'fetchLendingMarkets': 'GET /v2/conf/pub:info:margin',
  'fetchLendingPositions': 'POST /v2/auth/r/funding/loans',
  // Add other mappings...
}
```

4. Error Handling and Rate Limiting
- Implement exchange-specific error handling in each method
- Use CCXT's existing rate limiting mechanisms

5. Data Normalization
```javascript
parseLendingMarket (market, response) {
  return {
    'id': market['id'],
    'symbol': this.safeString(market, 'symbol'),
    'base': this.safeCurrencyCode(this.safeString(market, 'base')),
    'quote': this.safeCurrencyCode(this.safeString(market, 'quote')),
    // Add other relevant fields...
  }
}
```

6. Testing
- Unit tests in js/test/Exchange/test.lending.js
- Integration tests with exchange credentials

7. Documentation
- Update wiki/Manual.md with new lending API methods
- Provide usage examples and exchange-specific notes

8. Example Implementation
```javascript
async fetchLendingPositions (symbol = undefined, params = {}) {
  await this.loadMarkets ();
  const response = await this.privatePostAuthRFundingLoans (params);
  return this.parseLendingPositions (response, symbol);
}
```

9. Extensibility
- New exchanges: implement LendingApi methods, create API mappings, add normalizations

11. Key Considerations
- Consistent method signatures across exchanges
- Proper error handling and rate limit adherence
- Thorough documentation for developers
- Extensive testing to ensure reliability
- Flexibility for future exchange additions
