### ISSUE TITLE
gateio iceberg order

### ISSUE THREAD

**Issue by fredericcheminel** [ccxt/ccxt#9241]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: windows
- Programming Language version: python
- CCXT version: 0.6.96 pro

hi, i use ccxt pro with gate.io
i would like to create a limite order with iceberg params

i try
order = exchange.create_order(symbol, 'limit', 'sell', 103, 1, {'iceberg': True,})
and
order = await exchange.create_order(symbol, 'limit', 'sell', 103, 1, {'iceberg': "-1",})
it create order correctly but don't use iceberg.

from gateio doc,
{
  "text": "t-123456",
  "currency_pair": "ETH_BTC",
  "type": "limit",
  "account": "spot",
  "side": "buy",
  "iceberg": "0",
  "amount": "1",
  "price": "5.00032",
  "time_in_force": "gtc",
  "auto_borrow": false
}

Amount to display for the iceberg order. Null or 0 for normal orders. Set to -1 to hide the amount totally.

i would like to set it to -1
thank you for your help

**Comment by fredericcheminel** [comment]
any help?

**Comment by diwenshi61** [comment]
Try
`order = await exchange.create_order(symbol, 'limit', 'sell', 103, 1, {'iceberg': -1})`
Does this work for you?
Also to make sure that your order is showing on the orderbook, maybe try an uncommon price instead of a round number and check beforehand if there are any orders at that price.

**Comment by samgermain** [comment]
[Diwenshi61's answer](https://github.com/ccxt/ccxt/issues/9241#issuecomment-850908800), is how you do it, thanks.

[Here's the documentation](https://www.gate.io/docs/developers/apiv4/en/#create-an-order)

![](https://i.imgur.com/n5JJEIW.png)

------------------------

I'm going to close this issue. Feel free to reopen if you have any more questions
