### ISSUE TITLE
Binance Futures USDM: Problem with fetchFundingRate method

### ISSUE THREAD

**Issue by marcoismobile** [ccxt/ccxt#9243]
When calling the 'fetchFundingRate' method in the new BinanceUSDM exchange class, I got the following error:

```
exchange = ccxt.binanceusdm({
    'timeout': 10000,
    'enableRateLimit': True,
    'rateLimit': 250
})

response = exchange.fetchFundingRate()
```

```
  File "/home/marco/.local/lib/python3.8/site-packages/ccxt/binanceusdm.py", line 126, in fetch_funding_rate
    response = self.fapiPublicGetPremiumIndex(self.extend(request, params))
  File "/home/marco/.local/lib/python3.8/site-packages/ccxt/base/exchange.py", line 829, in extend
    result.update(arg)
TypeError: 'NoneType' object is not iterable
```

It seems the default of the 'params' agument is None instead of {}.
After that I got the following error when running:

```
response = exchange.fetchFundingRate(params={})
```

```
    result = exchange.fetchFundingRate(params={})
  File "/home/marco/.local/lib/python3.8/site-packages/ccxt/binanceusdm.py", line 141, in fetch_funding_rate
    values = list(response.values())
AttributeError: 'list' object has no attribute 'values'
```
It seems it is trying to convert a Dict into a List, but the response is already a list:
```
values = list(response.values())
```

Am I using this method in the wrong way?

Update: Seems the requiredment for the params={} is already documented on: https://github.com/ccxt/ccxt/wiki/Manual#fees

https://github.com/ccxt/ccxt/blob/0469ba10a2ce23161f1b5b0a952d922cb77cf82f/python/ccxt/binanceusdm.py#L119

**Comment by frosty00** [comment]
@marcoismobile thanks for reporting this, I'll fix it today. The `fetchPositions`, `fetchIsolatedPositions` and all the methods in that class have just been implemented this week so it is possible there are still bugs.

**Comment by marcoismobile** [comment]
I can see in the MR that the params argument now has a default, but the second problem was actually the one which prevented this method from working:

```
