### ISSUE TITLE
Question - is it possible to set a buy and sell amount rather than quantity? 

### ISSUE THREAD

**Issue by ukenpachi** [ccxt/ccxt#9246]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: linux
- Programming Language version: python
- CCXT version: latest

this is not an issue but rather a question. When placing a buy or sell order using binance. I cannot find any option which let you set the amount you want to buy or sell.  By amount I am referring to the USDT or BTC or XRP amount rather than quantity. e.g. I want to sell 500 USDT worth of BTC at X price or at market price. Thank you.

**Comment by kroitor** [comment]
Duplicate:

- https://github.com/ccxt/ccxt/issues/8539
- https://github.com/ccxt/ccxt/issues/7963
- https://github.com/ccxt/ccxt/issues/7853
- ...
- https://github.com/ccxt/ccxt/issues?q=binance+quoteOrderQty

**Comment by kroitor** [comment]
P.S. use the `quoteOrderQty` param override or specify `amount` + `price` (any amount and any price that would match your desired cost), so that CCXT would calculate your order cost = amount * price.

For example, you want to buy BTC for 100USDT on Binance:

```Python
exchange.create_order('BTC/USDT', 'market', 'buy', 1, 100)
# or
exchange.create_order('BTC/USDT', 'market', 'buy', 1, None, {'quoteOrderQty': 100})
```

**Comment by ukenpachi** [comment]
> ```python
> quoteOrderQty
> ```

thank you
