### ISSUE TITLE
How to stop watching / unsubscribe without dropping a socket?

### ISSUE THREAD

**Issue by wunderb1t** [ccxt/ccxt#9248]
Hello! We are going to watch many tickers simultaneously via single socket connection (I hope), using `watchTicker`. When ticker is not needed we need to stop watching it, how to do that?

- OS: DEBIAN (Docker)
- Programming Language version: NodeJS
- CCXT version: Pro version: 0.6.81

```
const exchange = new ccxt['binance'];

while (true) {
    try {
         // How to stop watching only 'BTC/USDT' without dropping the socket? 
         const ticker = await exchange.watchTicker('BTC/USDT');
    }
    catch (e) {
        
    }
}
```

**Comment by kroitor** [comment]
The unification of methods for unsubscribing from a single subscription is in progress (not all exchanges allow that), at this point there's no way to do that without resetting the instance, but we hope to add the support for precise unsubscriptions asap.

**Comment by wunderb1t** [comment]
Ok, is there an example how to call not unified method to unsubscribe in conjunction with `exchange.watchTicker `?

**Comment by kroitor** [comment]
@wunderb1t we will post a custom example for Binance here, but it will be exchange-specific.

**Comment by wunderb1t** [comment]
If it is possible to do "exchange-specific" for every exchange, it is fine.

**Comment by kroitor** [comment]
> If it is possible to do "exchange-specific" for every exchange, it is fine.

Unfortunately, it is not possible for every exchange, because some exchanges don't support unsubscribing at all.

**Comment by wunderb1t** [comment]
> @wunderb1t we will post a custom example for Binance here, but it will be exchange-specific (for now).

It would be nice to have an example :)

**Comment by d33m00n** [comment]
Hey, any updates on this?

**Comment by nikky78** [comment]
any news on this please?

**Comment by carlosmiei** [comment]
Hello, @nikky78 unfortunately not yet

**Comment by flowerchaton** [comment]
@wunderb1t @nikky78 
I just figured out how to do this in a hacky way
Basically all websocket clients are stored in `exchange.clients`.
All you need to do is check this value `exchange.clients[url].subscriptions` and then call the `exchange.clients[url].close()`

**Comment by mo-rijndael** [comment]
> All you need to do is check this value `exchange.clients[url].subscriptions` and then call the `exchange.clients[url].close()`

Sadly, this will not work, if you're monitoring several channels in same endpoint (for example, tickers) :(

**Comment by carlosmiei** [comment]
@nikky78 Right now, unsubscribing is not available yet.

**Comment by yazeed** [comment]
> @wunderb1t @nikky78 I just figured out how to do this in a hacky way Basically all websocket clients are stored in `exchange.clients`. All you need to do is check this value `exchange.clients[url].subscriptions` and then call the `exchange.clients[url].close()`

Maybe we should implement something on top of the hacky method?

**Comment by ttodua** [comment]
unsubscribing is becoming available using `unWatch` methods, e.g. `unWatchOrderBookForSymbols ( ['BTC/USDT', 'ETH/USDT'])` ... 
also, in near future we would release event-driven subscriptions, so anyone can subscribe to announcement channels to get notified ( https://t.me/ccxt_announcements or https://discord.com/channels/690203284119617602/1057748769690619984 )
