### ISSUE TITLE
base and quote not separated with slash when using fetchTickers (problem when new market added)

### ISSUE THREAD

**Issue by gregordoltar** [ccxt/ccxt#9251]
Hi,

using ccxt 1.50.10, Python 3.6.9 on binance

using fetchTickers I experience following problem (happens approx once per day):
base and quote are not separated by slash. Look at MASKBUSD. It only happes on some markets.
This is the extract of dict immediately after fetchTickers:

`'MDX/USDT': {'symbol': 'MDX/USDT', 'timestamp': 1621922401790, 'datetime': '2021-05-25T06:00:01.790Z', 'high': 2.58, 'low': 1.6071, 'bid': 2.0412, 'bidVolume': 157.37, 'ask': 2.0488, 'askVolume': 81.34, 'vwap': 2.05185347, 'open': 1.6071, 'close': 2.0412, 'last': 2.0412, 'previousClose': 1.6071, 'change': 0.4341, 'percentage': 27.011, 'average': None, 'baseVolume': 21599806.62, 'quoteVolume': 44319638.095837, 'info': {'symbol': 'MDXUSDT', 'priceChange': '0.43410000', 'priceChangePercent': '27.011', 'weightedAvgPrice': '2.05185347', 'prevClosePrice': '1.60710000', 'lastPrice': '2.04120000', 'lastQty': '8.74000000', 'bidPrice': '2.04120000', 'bidQty': '157.37000000', 'askPrice': '2.04880000', 'askQty': '81.34000000', 'openPrice': '1.60710000', 'highPrice': '2.58000000', 'lowPrice': '1.60710000', 'volume': '21599806.62000000', 'quoteVolume': '44319638.09583700', 'openTime': '1621836001790', 'closeTime': '1621922401790', 'firstId': '0', 'lastId': '100662', 'count': '100663'}}, 'MASKBNB': {'symbol': 'MASKBNB', 'timestamp': 1621922401784, 'datetime': '2021-05-25T06:00:01.784Z', 'high': 0.06, 'low': 0.02387, 'bid': 0.02509, 'bidVolume': 284.33, 'ask': 0.03812, 'askVolume': 10.23, 'vwap': 0.03890296, 'open': 0.02387, 'close': 0.03812, 'last': 0.03812, 'previousClose': 0.0, 'change': 0.01425, 'percentage': 59.698, 'average': None, 'baseVolume': 372.81, 'quoteVolume': 14.5034134, 'info': {'symbol': 'MASKBNB', 'priceChange': '0.01425000', 'priceChangePercent': '59.698', 'weightedAvgPrice': '0.03890296', 'prevClosePrice': '0.00000000', 'lastPrice': '0.03812000', 'lastQty': '82.04000000', 'bidPrice': '0.02509000', 'bidQty': '284.33000000', 'askPrice': '0.03812000', 'askQty': '10.23000000', 'openPrice': '0.02387000', 'highPrice': '0.06000000', 'lowPrice': '0.02387000', 'volume': '372.81000000', 'quoteVolume': '14.50341340', 'openTime': '1621836001784', 'closeTime': '1621922401784', 'firstId': '0', 'lastId': '8', 'count': '9'}}, 'MASKBUSD': {'symbol': 'MASKBUSD', 'timestamp': 1621922401719, 'datetime': '2021-05-25T06:00:01.719Z', 'high': 12.0, 'low': 8.117, 'bid': 11.0, 'bidVolume': 0.09, 'ask': 11.578, 'askVolume': 630.58, 'vwap': 10.06543265, 'open': 8.117, 'close': 11.0, 'last': 11.0, 'previousClose': 0.0, 'change': 2.883, 'percentage': 35.518, 'average': None, 'baseVolume': 3176.92, 'quoteVolume': 31977.0743, 'info': {'symbol': 'MASKBUSD', 'priceChange': '2.88300000', 'priceChangePercent': '35.518', 'weightedAvgPrice': '10.06543265', 'prevClosePrice': '0.00000000', 'lastPrice': '11.00000000', 'lastQty': '9.00000000', 'bidPrice': '11.00000000', 'bidQty': '0.09000000', 'askPrice': '11.57800000', 'askQty': '630.58000000', 'openPrice': '8.11700000', 'highPrice': '12.00000000', 'lowPrice': '8.11700000', 'volume': '3176.92000000', 'quoteVolume': '31977.07430000', 'openTime': '1621836001719', 'closeTime': '1621922401719', 'firstId': '0', 'lastId': '40', 'count': '41'}}, 'MASKUSDT': {'symbol': 'MASKUSDT', 'timestamp': 1621922401838, 'datetime': '2021-05-25T06:00:01.838Z', 'high': 11.0, 'low': 8.118, 'bid': 10.571, 'bidVolume': 112.19, 'ask': 11.0, 'askVolume': 23798.43, 'vwap': 10.90024645, 'open': 8.118, 'close': 10.571, 'last': 10.571, 'previousClose': 0.0, 'change': 2.453, 'percentage': 30.217, 'average': None, 'baseVolume': 13592.28, 'quoteVolume': 148159.20175, 'info': {'symbol': 'MASKUSDT', 'priceChange': '2.45300000', 'priceChangePercent': '30.217', 'weightedAvgPrice': '10.90024645', 'prevClosePrice': '0.00000000', 'lastPrice': '10.57100000', 'lastQty': '80.95000000', 'bidPrice': '10.57100000', 'bidQty': '112.19000000', 'askPrice': '11.00000000', 'askQty': '23798.43000000', 'openPrice': '8.11800000', 'highPrice': '11.00000000', 'lowPrice': '8.11800000', 'volume': '13592.28000000', 'quoteVolume': '148159.20175000', 'openTime': '1621836001838', 'closeTime': '1621922401838', 'firstId': '0', 'lastId': '262', 'count': '263'}}}
`

**Comment by gregordoltar** [comment]
I will retry with ccxt 1.50.34 and verbose mode

**Comment by gregordoltar** [comment]
I was able to reproduce it again.
My program terminated looking for "/" in symbol ETHUAH

I have attached bad.txt and good.txt. bad.txt is somehow incorrectly parsed by ccxt while good.txt is not.

I have compared the responses from binance and they appear to be ok. So it must be something else.
[good.zip](https://github.com/ccxt/ccxt/files/6560288/good.zip)
[bad.zip](https://github.com/ccxt/ccxt/files/6560289/bad.zip)

My program pseudo code:
```
r = ccxt.fetchTickers()
for symbol in r:
        s = a_symbol.split("/")
        base = s[0]
        quote = s[1]
```

**Comment by kroitor** [comment]
Can you please paste the complete code to reproduce it?

Do you have this issue with the following code using the most recent version of CCXT (1.50.64 or higher):

```Python
import ccxt
from pprint import pprint
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.binance({'rateLimit': 2000})
markets = exchange.load_markets()
while True:
    tickers = exchange.fetch_tickers()
    symbols_without_slashes = [symbol for symbol in tickers if '/' not in symbol]
    if len(symbols_without_slashes):
        print(symbols_without_slashes)
    else:
        print('All symbols have slashes in them')
```

Apart from the above, you should not attempt to parse the symbols, instead you should work with the markets to get the base and quote currencies, as explained in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#methods-for-markets-and-currencies
- https://github.com/ccxt/ccxt/wiki/Manual#market-structure

Let us know if the above code works for you.

**Comment by gregordoltar** [comment]
I will try reproducing with your example.

**Comment by gregordoltar** [comment]
I can reproduce issue with ccxt 1.50.76 but not with ccxt 1.23.4
The test program crashed due to connectivity issues.

My program is now something like:

`import ccxt
from pprint import pprint
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.binance({'rateLimit': 2000})
markets = exchange.load_markets()
while True:
    tickers = exchange.fetch_tickers()
    symbols_without_slashes = [symbol for symbol in tickers if '/' not in symbol]
    if len(symbols_without_slashes):
        print(symbols_without_slashes)
        markets = exchange.load_markets(reload=True)
    else:
        print('All symbols have slashes in them')
`
It seems that load_markets(reload=True) doesn't help.
I will try attaching the debugger.

**Comment by kroitor** [comment]
@gregordoltar which symbols don't have slashes in your case? Does it happen immediately?

**Comment by kroitor** [comment]
To avoid crashing you can simply added very basic error handling:

```Python
import ccxt
from pprint import pprint
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.binance({'rateLimit': 2000})
markets = exchange.load_markets()
while True:
    try:
        tickers = exchange.fetch_tickers()
        symbols_without_slashes = [symbol for symbol in tickers if '/' not in symbol]
        if len(symbols_without_slashes):
            print(symbols_without_slashes)
            markets = exchange.load_markets(reload=True)
        else:
            print('All symbols have slashes in them')
    except Exception as e:
        print(type(e).__name__, str(e))
```

Can you reproduce it with this code? ↑

**Comment by gregordoltar** [comment]
It does not happen immediately. It happens after binance adds some markets or coins (I am not sure).
My program runs days/weeks it is hard to reproduce.

**Comment by frosty00** [comment]
seems to be related to some market ids not being loaded. you can reload the markets using:

```
exchange.loadMarkets (true)
```
