### ISSUE TITLE
Exchange countries not accurate?

### ISSUE THREAD

**Issue by opub** [ccxt/ccxt#9260]
I am trying to filter exchanges to just those that support US customers. However the exchanges' countries list doesn't seem to be accurate or possibly just outdated?

For example, the following exchanges list "US" in countries but don't allow US customers.
- [oceanex](https://oceanex.pro/en/signup)
- [okex](https://www.okex.com/support/hc/en-us/articles/360021813691)
- [poloniex](https://poloniex.com/terms/)
- [qtrade](https://www.qtrade.ca/en/investor/faq.html)

- OS: Windows 10
- Programming Language version: Node 14.16
- CCXT version: 1.50.37

```
    for (const name of ccxt.exchanges) {
        const exchange = new ccxt[name];
        if(exchange.countries.includes('US')) {
            console.log(name);
        }
    }
```

Output
```
bibox
binanceus
bitmart
bittrex
btcalpha
coinbase
coinbaseprime
coinbasepro
coingi
coinmarketcap
equos
gemini
idex
itbit
kraken
lakebtc
ndax
oceanex
okcoin
okex
okex5
poloniex
qtrade
```

**Comment by kroitor** [comment]
> However the exchanges' countries list doesn't seem to be accurate or possibly just outdated?

Yes, it is outdated, we will fix that shortly. This is mostly for historical reasons, when those exchanges were integrated, they were accepting the US customers just fine.
