### ISSUE TITLE
Whether watchTicker reuse socket connection for multiple subscriptions?

### ISSUE THREAD

**Issue by wunderb1t** [ccxt/ccxt#9265]
I have found solution how to watch multiple symbols simultaneously from [https://github.com/ccxt/ccxt/issues/8245](https://github.com/ccxt/ccxt/issues/8245)
As I understood, `watchTicker` is executed in `while` cycle for every symbol. The question is, does `watchTicker` use the same socket connection for watching symbol update? I'm afraid that for example on 100 symbols, 100 sockets will be opened... 

- OS: DEBIAN (Docker)
- Programming Language version: NodeJS
- CCXT version: Pro version: 0.6.81

**Comment by kroitor** [comment]
@wunderb1t the same connection will be reused. Let us know if it tries to open 100 sockets.
