### ISSUE TITLE
coinbasepro.py granularity too small for the requested time range. Count of aggregations requested exceeds 300

### ISSUE THREAD

**Issue by a178235** [ccxt/ccxt#9268]
https://github.com/ccxt/ccxt/blob/master/python/ccxt//coinbasepro.py
https://github.com/ccxt/ccxt/blob/master/python/ccxt/async_support/coinbasepro.py

granularity * 1000 is too large and returns more than 300 rows. A lower number like 500 works.

- OS: Ubuntu
- Programming Language version: Python 3.8
- CCXT version: 1.50.43

```
    async def fetch_ohlcv(self, symbol, timeframe='1m', since=None, limit=None, params={}):
        await self.load_markets()
        market = self.market(symbol)
        granularity = self.timeframes[timeframe]
        request = {
            'id': market['id'],
            'granularity': granularity,
        }
        if since is not None:
            request['start'] = self.iso8601(since)
            if limit is None:
                # https://docs.pro.coinbase.com/#get-historic-rates
                limit = 300  # max = 300
            request['end'] = self.iso8601(self.sum((limit - 1) * granularity * 1000, since))
```

```
freqtrade.exchange.common - WARNING - _async_get_candle_history() returned exception: "Could not fetch historical candle (OHLCV) data for pair BTC/USD due to ExchangeError. Message: coinbasepro granularity too small for the requested time range. Count of aggregations requested exceeds 300"
```

**Comment by kroitor** [comment]
@a178235 1000 is the milliseconds-multiplier, it has nothing to do with the number of candles returned. The `limit` is 300 by default. 

Please, paste your verbose output from Python:

```Python
import ccxt
from pprint import pprint
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.coinbasepro()
markets = exchange.load_markets()
exchange.verbose = True
ohlcv = exchange.fetch_ohlcv('BTC/USD', '1m', exchange.parse8601('2020-01-01T00:00:00Z'))
pprint(ohlcv)
```

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by kroitor** [comment]
@a178235 Let us know if you have this issue with CCXT 1.50.44 (it will arrive in ~20 minutes).

**Comment by a178235** [comment]
There is still some issue. There are gaps in the coinbasepro data. Bittrex works correctly, but coinbasepro jumps from 1619823600000 to 1621641600000.

bittrex
[1621638000000,36708.61,37500.0,36362.02,37340.77,1772.39794866],[1621641600000,37333.09,37784.57,36963.83,37718.21,954.12311628],[1621645200000,37717.71,38023.16,37242.24,37671.84,1273.17170743],[1621648800000,37671.84,38134.86,37202.84,37430.36,1377.49076526],

coinbasepro
[1619823600000,57167.254,58023.881,57159.876,57784.83,31.02634316],[1621641600000,37344.031,37782.213,36987.317,37706.81,33.4187199],[1621645200000,37718.627,38026.838,37260.295,37689.89,30.35321563],[1621648800000,37686.906,38121.64,37251.041,37451.16,29.96097882],
