### ISSUE TITLE
Issues with binance fetch_ticker

### ISSUE THREAD

**Issue by rlarudqls630** [ccxt/ccxt#9269]
I think there is currenly a issue getting ticker values using fetch_ticker.
'open' value and few other values using fetch_ticker is different from binance website.
I checked it with BTC/USDT.
can someone check this issue please?

**Comment by kroitor** [comment]
@rlarudqls630 please, paste your versions, your code to reproduce it and your verbose output: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by rlarudqls630** [comment]
def calculations():
    datas = pd.read_csv('BTCUSDT_DATA.csv')

    span_a = round((datas.iloc[-30]['tenkan_sen'] + datas.iloc[-30]['kijun_sen']) / 2, 2)
    span_b = round((datas.iloc[-151:-30]['high'].max() + datas.iloc[-151:-30]['low'].min()) / 2, 2)

    temp = binance.fetch_ticker('BTC/USDT')                                     #현재 ohlcv

    pprint(temp)


this is what is printed from the code
check the open value of the code and the screen shot.
they r different. 

{'ask': 38864.49,
 'askVolume': 0.325601,
 'average': None,
 'baseVolume': 94937.548356,
 'bid': 38864.48,
 'bidVolume': 1.502168,
 'change': -1378.56,
 'close': 38864.48,
 'datetime': '2021-05-27T09:02:00.651Z',
 'high': 40428.9,
 'info': {'askPrice': '38864.49000000',
          'askQty': '0.32560100',
          'bidPrice': '38864.48000000',
          'bidQty': '1.50216800',
          'closeTime': '1622106120651',
          'count': '2166012',
          'firstId': '872761892',
          'highPrice': '40428.90000000',
          'lastId': '874927903',
          'lastPrice': '38864.48000000',
          'lastQty': '0.13431200',
          'lowPrice': '37134.27000000',
          'openPrice': '40243.04000000',
          'openTime': '1622019720651',
          'prevClosePrice': '40243.05000000',
          'priceChange': '-1378.56000000',
          'priceChangePercent': '-3.426',
          'quoteVolume': '3677167970.84356957',
          'symbol': 'BTCUSDT',
          'volume': '94937.54835600',
          'weightedAvgPrice': '38732.49346038'},
 'last': 38864.48,
 'low': 37134.27,
 'open': 40243.04,
 'percentage': -3.426,
 'previousClose': 40243.05,
 'quoteVolume': 3677167970.8435698,
 'symbol': 'BTC/USDT',
 'timestamp': 1622106120651,
 'vwap': 38732.49346038}




![Screen Shot 2021-05-27 at 18 02 57](https://user-images.githubusercontent.com/11022460/119798091-caa59600-bf15-11eb-95f4-3c0b55cb9aa4.png)

**Comment by kroitor** [comment]
@rlarudqls630 you are comparing OHLCV candles to the ticker values, that is incorrect to do.  You can't compare those values. The ticker is a 24h rolling window. The OHLCV candles are fixed in time. Those are datas of different types and you should not confuse them.

The difference is explained in the Manual: 

- https://github.com/ccxt/ccxt/wiki/Manual#price-tickers
- https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-candlestick-charts

Hope that answers your question.

**Comment by rlarudqls630** [comment]
oh awesome thank you.
