### ISSUE TITLE
Binance USD-M and COIN-M futures market type improvement

### ISSUE THREAD

**Issue by diwenshi61** [ccxt/ccxt#9285]
On Binance USD-M and COIN-M markets use their defaultType to define the market type, which means that all USD-M markets are future and all COIN-M markets are delivery.

Unfortunately this is no longer true anymore and there are delivery USD-M futures and perpetual COIN-M futures.
Example:
```
import ccxt

usdm = ccxt.binanceusdm()
coinm = ccxt.binancecoinm()

usdm.load_markets()
coinm.load_markets()

for market in usdm.markets.values():
    print(market['symbol'], market['future'], market['delivery'])
for market in coinm.markets.values():
    print(market['symbol'], market['future'], market['delivery'])

# output:
# BTC/USDT True False
# ETH/USDT True False
# BCH/USDT True False
# XRP/USDT True False
# EOS/USDT True False
# LTC/USDT True False
# TRX/USDT True False
# CHR/USDT True False
# MANA/USDT True False
# ALICE/USDT True False
# BTCUSDT_210625 True False
# ETHUSDT_210625 True False
# ...
# BTC/USD False True
# BTCUSD_210625 False True
# BTCUSD_210924 False True
# ETH/USD False True
# ETHUSD_210625 False True
# ETHUSD_210924 False True
# LINK/USD False True
# BNB/USD False True
# ...
```
The market type should be parsed in CCXT.

**Comment by kroitor** [comment]
> Unfortunately this is no longer true anymore and there are delivery USD-M futures and perpetual COIN-M futures.

We are in the process of renaming them from historical `future` and `delivery` to structures that will have flags like `linear`, `inverse`, `swap`, `futures` in order to address this.

**Comment by frosty00** [comment]
#12586
