### ISSUE TITLE
Bitvavo `watch_orders` - missing initialization of `self.orders`

### ISSUE THREAD

**Issue by Matthias-Thul** [ccxt/ccxt#9286]
- OS: macOS 11.3.1
- Programming Language version: Python 3.9.5
- CCXT version: 0.7.7

```
bitvavo = ccxtpro.bitvavo({"apiKey": "#####", "secret": "#####"})
await bitvavo.authenticate()
await bitvavo.watch_orders('BTC/EUR')
```

```
Traceback (most recent call last):
  File "/Users/###/opt/anaconda3/envs/python-3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/###/###/venv/lib/python3.9/site-packages/ccxtpro/base/fast_client.py", line 25, in handler
    self.handle_message(message)
  File "/Users/###/###venv/lib/python3.9/site-packages/ccxtpro/base/aiohttp_client.py", line 32, in handle_message
    self.handle_text_or_binary_message(message.data)
  File "/Users/###/###/venv/lib/python3.9/site-packages/ccxtpro/base/aiohttp_client.py", line 27, in handle_text_or_binary_message
    self.on_message_callback(self, decoded)
  File "/Users/###/###/venv/lib/python3.9/site-packages/ccxtpro/bitvavo.py", line 633, in handle_message
    return method(client, message)
  File "/Users/###/###/venv/lib/python3.9/site-packages/ccxtpro/bitvavo.py", line 449, in handle_order
    self.orders[symbol] = defaultKey
TypeError: 'NoneType' object does not support item assignment
```

What happens here is that `self.orders` has never been initialized.

**Comment by kroitor** [comment]
@Matthias-Thul what is your version of CCXT and CCXT Pro? If your version of CCXT is older than 1.50, please, upgrade:

```Python
import ccxt
import ccxtpro
print('CCXT Version', ccxt.__version__)
print('CCXT Pro Version', ccxt.__version__)
```

Let us know if upgrading to the most recent version does not help. Feel free to reopen this issue or just ask further questions if any.

**Comment by Matthias-Thul** [comment]
Apologies - wasn't aware that the versions differ.

```
CCXT Version 1.50.64
CCXT Pro Version 0.7.7
```

**Comment by kroitor** [comment]
@Matthias-Thul do you still have this issue with CCXT 1.50.64?

**Comment by Matthias-Thul** [comment]
Yes - these were my versions all along and I still have this issue.

**Comment by Matthias-Thul** [comment]
For good measure I upgraded to the very latest just now but no difference.

```
CCXT Version 1.50.66
CCXT Pro Version 0.7.8
```

What makes the error go away is to put a 

```python
        if self.orders is None:
            self.orders = {}
```

in `ccxtpro/bitvavo.py` right before line 449. Not sure this is correct in all cases though.

**Comment by kroitor** [comment]
@Matthias-Thul we will fix it shortly, thx!

**Comment by kroitor** [comment]
@Matthias-Thul we've pushed the edits, it should work normally as of CCXT Pro 0.7.9+. Please, don't hesitate if you have further difficulties with it. Thanks again for your feedback, we appreciate it!
