### ISSUE TITLE
    raise AuthenticationError('requires `' + key + '`') ccxt.base.errors.AuthenticationError: requires `password`

### ISSUE THREAD

**Issue by tanjhysj0** [ccxt/ccxt#9288]
raise AuthenticationError('requires `' + key + '`')
ccxt.base.errors.AuthenticationError: requires `password`

**Comment by kroitor** [comment]
This is documented in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#authentication

We recommend reading the entire Manual from top to bottom – it will really save your time.
Hope that answers your question, let us know if not.
