### ISSUE TITLE
Exception when new pair added by exchange

### ISSUE THREAD

**Issue by Mobocop** [ccxt/ccxt#9290]
I'm getting an exception when an exchange (cex.io) has added a new pair (or pairs). The exception comes from exchange.fetch_tickers(). It looks like the new pair isn't in self.markets and I can't see a way for the code to add it.

As a terrible workaround I have added a try: except KeyError: to catch it for the moment, then re-initialise the ccxt instance. However there is still no way of knowing what the new market(s) are. I could interrogate the exception, but that would only tell me 1 of N pairs added. I also don't want to make loads of unnecessary api calls to check which markets are available.

My question is, is this the intended behaviour, and is there a good way of handling this sort of error?

- OS: Linux
- Programming Language version: Python 3.8.5
- CCXT version: 1.48.23

```
import ccxt, time
exchange = ccxt.cex()
while True:
    market_tickers = exchange.fetch_tickers() # fails when a new pair has been added
    time.sleep(1)
```

```
Exception caught: 'TRX/GBP' Traceback (most recent call last):
File "cex.py", line 194, in <module>
    market_tickers = exchange.fetch_tickers()
File "~/.local/lib/python3.8/site-packages/ccxt/cex.py", line 501, in fetch_tickers
    market = self.markets[symbol]
KeyError: 'TRX/GBP'
```

FYI TRX/GBP was added to cex.io on 2021/05/25

Link to line in current source https://github.com/ccxt/ccxt/blob/master/python/ccxt/cex.py#L502

**Comment by ttodua** [comment]
Late reply here, but yes, that problem has been a known issue and in near future we will make some solution for that.

**Comment by ttodua** [comment]
late reply here, but this issue was partially fixed in the past and new symbols are going through safeMarket, so there wont be an error anymore.
however, markets auto-reloading is not yet done and users are suggested to reload markets when they encounter a new symbol, like `if ( !(symbol in ex.makets)) await ex.loadMarkets()`
