### ISSUE TITLE
[binance] Inconsistent authentication error message with fetchCurrencies option in binance

### ISSUE THREAD

**Issue by adtm** [ccxt/ccxt#9296]
I was using `options: fetchCurencies` with binance and have noticed that I receive an error of `ExchangeError: binance {"code":-2008,"msg":"Invalid Api-Key ID."}` when the key is invalid.

When I don't have this option and the key is invalid (not the secret) I receive the expected error of `AuthenticationError: binance {"code":-2014,"msg":"API-key format invalid."}`

- OS: Mac OS Catalina
- Programming Language version: JS/TS
- CCXT version: 1.50.74

```ts
const exchangeClient = new ccxt.binance({
  apiKey, 
  secret,
  password,
  options: { <-- this and without it
      fetchCurrencies: true,
    },
 })
```

```md
// received with options (not expected)
ExchangeError: binance {"code":-2008,"msg":"Invalid Api-Key ID."}

// received without options (expected)
AuthenticationError: binance {"code":-2014,"msg":"API-key format invalid."}
```

**Comment by kroitor** [comment]
The message you see – is from Binance itself, we classify both errors as `AuthenticationError`. Does that answer your question?

**Comment by adtm** [comment]
Yes, I understand that they are from Binance, but the -2008 should be `AuthenticationError` and now it's `ExchangeError`. At least I see `ExchangeError` and I couldn't find mapping for the code -2008.

**Comment by kroitor** [comment]
@adtm thx for pointing it out – we pushed a fix, please let us know if you have this issue with version 1.50.75 (the new build will arrive in ~20 minutes).

**Comment by adtm** [comment]
Yes, thank you @kroitor, now it works as expected. 🎉
