### ISSUE TITLE
Printing the API requests and responses sent to/received from exchanges

### ISSUE THREAD

**Issue by deceneucapital** [ccxt/ccxt#9298]
Hi Kroitor,

Is there a way I can print the actual API requests and responses sent to the exchange?

For example, when sending an order to FTX (using CCXT), can I print the request and response in the actual format sent/received from FTX (as per the screenshot from FTX's API docs)? 

![image](https://user-images.githubusercontent.com/72634085/120422479-b34e2900-c3ab-11eb-98df-5ca341bfcbed.png)

**Comment by kroitor** [comment]
Yes, you can, just add `exchange.verbose = true` before the calls you want to debug, after `loadMarkets()`.
This is documented in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
