### ISSUE TITLE
placing future order

### ISSUE THREAD

**Issue by 2744jaspreet** [ccxt/ccxt#9302]
hi, using following PHP code 
$symbol = "1000SHIB/USDT";
		$quantity = 10000;
		$price = 0.009;
		
		
		$binance->load_markets();
		$binance->verbose = true; // ←------ verbose mode on
		
		var_dump ($binance->id, $binance->createOrder($symbol,"limit","sell",$quantity, $price));

getting this:

Array
(
    [0] =&gt; Request:
    [1] =&gt; POST
    [2] =&gt; https://fapi.binance.com/fapi/v1/order
    [3] =&gt; Array
        (
           ................................................................

;symbol=1000SHIBUSDT&amp;type=LIMIT&amp;side=SELL&amp;newClientOrderId=x-xcKtGhcu8065df841995f940ec4474&amp;newOrderRespType=RESULT&amp;quantity=10000&amp;price=0.009&amp;timeInForce=GTC&amp;signature=eb56ca97e3876b95d9ab916e919fbfb45fa27d7dbac2a77219a36f773b6e5025
)
Array
(
    [0] =&gt; Response:
    [1] =&gt; POST
    [2] =&gt; https://fapi.binance.com/fapi/v1/order
    [3] =&gt; 400
    [4] =&gt; 
    [5] =&gt; Array
        (
            [Content-Type] =&gt; application/json
            [Content-Length] =&gt; 75
            [Connection] =&gt; keep-alive
            [Date] =&gt; Thu, 03 Jun 2021 08:32:37 GMT
            [Server] =&gt; Tengine
            [X-MBX-USED-WEIGHT-1M] =&gt; 0
            [X-MBX-ORDER-COUNT-10S] =&gt; 0
            [X-MBX-ORDER-COUNT-1M] =&gt; 1
            [x-response-time] =&gt; 3ms
            [Access-Control-Allow-Origin] =&gt; *
            [Access-Control-Allow-Methods] =&gt; GET, POST, PUT, DELETE,
 OPTIONS
            [X-Cache] =&gt; Error from cloudfront
            [Via] =&gt; 1.1 
b838ef1ff22a4a994af82d5178c30e1d.cloudfront.net (CloudFront)
            [X-Amz-Cf-Pop] =&gt; SEA19-C1
            [X-Amz-Cf-Id] =&gt; 
ENKxSqjN7Z2cqOn26uB574gXKE5jJ8pzLuMdZ9sM0-sr21DtjqS-qQ==
        )

    [6] =&gt; {"code":-4061,"msg":"Order's position side does not match 
user's setting."}
)
<br>
<font size="1">
( ! )  Fatal error: Uncaught ccxt\ExchangeError: binanceusdm  {"code":-4061,"msg":"Order's position side does not match user's  setting."} in E:\wamp\www\vendor\ccxt\ccxt\php\binance.php on line 3156
--

</font>

**Comment by 2744jaspreet** [comment]
i turned off hedge mode and it worked, but i want hedge mode on so i used
		'hedgeMode'=> true,
after searching arround but it did not work.
please help. thanks.

**Comment by frosty00** [comment]
@2744jaspreet you need to log into binance and set hedge mode 
<img width="758" alt="Screenshot 2021-06-03 at 11 15 05" src="https://user-images.githubusercontent.com/14319357/120628746-f4524600-c45c-11eb-88a8-9c587ccec5e9.png">

You can find this slider to the right of grid trading

**Comment by kroitor** [comment]
@2744jaspreet closing this for now, feel free to reopen it or just ask further questions, if any.
