### ISSUE TITLE
Does this library support aggregated price across exchanges?

### ISSUE THREAD

**Issue by orlandodiaz** [ccxt/ccxt#9309]
Is it possible to get the average price for a coin across multiple exchanges in one method call?

Ex. getAggregatedPriceData('BTC') would return the average price combined from Binance, Huobi, and all other supported exchanges.

**Comment by kroitor** [comment]
> Is it possible to get the average price for a coin across multiple exchanges in one method call?

In short CCXT gives you all the tools necessary to write such a method. Then you can call it. CCXT does not include a method like that out of the box, but it includes the building blocks for making any kinds of methods like you mentioned.

We suggest starting from here:

- https://github.com/ccxt/ccxt/wiki
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/tree/master/examples

Hope that answers your question, let us know if not.
