### ISSUE TITLE
Difference between fetch_free_balance, fetch_total_balance, fetch_used_balance

### ISSUE THREAD

**Issue by Salz0** [ccxt/ccxt#9310]
What is the difference between the values they return? I am unable to test it myself and am asking for some clarification. 

Thank you!

**Comment by kroitor** [comment]
It's `total = free + used`.
The `free` amount is the amount you can trade for
The `used` value is the amount already locked in some of your orders.

We suggest reading the entire Manual from top to bottom – it has the answers to most of starting questions and it will really save your time:

- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/wiki/Manual

Hope that helps, let us know if not.
