### ISSUE TITLE
Lykke: create_order function does not work properly; wrong "Asset" field

### ISSUE THREAD

**Issue by paolazz** [ccxt/ccxt#9311]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Win10
- Programming Language version: Python 3.7
- CCXT version: 1.50.86

```
symbol ='BTC/EUR'
type = 'market'
side = 'buy'
amount =1
order = exchange.create_order(symbol, type, side, amount, {'Asset':'BTC'})
```

```
400 Bad Request {"Asset":["The Asset field is required."]}
```

Asset field is defined... I got this on lykke.py:

def create_order(self, symbol, type, side, amount, price=None, params={}):
        self.load_markets()
        market = self.market(symbol)
        query = {
            'AssetPairId': market['id'],
            'OrderAction': self.capitalize(side),
            'Volume': amount,
            **'Asset': market['baseId'],**
        }

but **market['baseId']** is none by default... **'baseId': None**.
It should be changed with **market['base']**, that corresponds to the correct asset field: **'base': 'ETH'**

Thank you.

**Comment by paolazz** [comment]
Just understood that Lykke is not working on ccxt, v2 API is not yet implemented... Can you confirm that? @kroitor

**Comment by kroitor** [comment]
@paolazz yes, that is the case. We will try to update it as soon as we can.
