### ISSUE TITLE
kucoin err 

### ISSUE THREAD

**Issue by amengCow** [ccxt/ccxt#9312]
cctxpro  version  0.7.13
kucoin fetchOrderBook err Tips ,NotSupported: kucoin not exist
I have re installed cctxpro and related dependencies and replaced apikey, but this problem still occurs

**Comment by kroitor** [comment]
Please, paste your code and your verbose request+response:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

What do you see:

```Python
import ccxtpro
from pprint import pprint
from asyncio import get_event_loop


print('CCXT Pro Version:', ccxtpro.__version__)

async def main():
    exchange = ccxtpro.kucoin()
    markets = await exchange.load_markets()
    orderbook = await exchange.fetch_order_book('BTC/USDT')
    pprint(orderbook)
    
loop = get_event_loop()
loop.run_until_complete(main())
```

**Comment by amengCow** [comment]
`   const exchange = new ccxtpro.kucoin()
    const orderbook = await exchange.fetchOrderBook('TONE/ETH')
    console.log(orderbook);
`
(node:3476) UnhandledPromiseRejectionWarning: NotSupported: kucoin not exist
    at kucoin.throwExactlyMatchedException (/root/node/ccxt.pro-master/node_modules/ccxt/js/base/Exchange.js:538:19)
    at kucoin.handleErrors (/root/node/ccxt.pro-master/node_modules/ccxt/js/kucoin.js:2218:14)
    at /root/node/ccxt.pro-master/node_modules/ccxt/js/base/Exchange.js:600:18
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async timeout (/root/node/ccxt.pro-master/node_modules/ccxt/js/base/functions/time.js:195:24)
    at async kucoin.fetchOrderBook (/root/node/ccxt.pro-master/node_modules/ccxt/js/kucoin.js:847:26)
  
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3476) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3476) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by kroitor** [comment]
Paste your output:

```JavaScript
const ccxtpro = require('ccxt.pro')
console.log('CCXT Pro Version:', ccxtpro.version)
```

**Comment by amengCow** [comment]
CCXT Pro Version: 0.7.13

**Comment by kroitor** [comment]
@amengCow this error is on the exchange side: https://openapi-v2.kucoin.com/api/v2/market/orderbook/level2?symbol=TONE-ETH you might want to report it to KuCoin's tech support.

**Comment by amengCow** [comment]
OK, I can solve this problem by replacing the URL

**Comment by kroitor** [comment]
@amengCow actually, hold on a sec, we're investigating...

**Comment by amengCow** [comment]
it's not long since this problem appeared

**Comment by kroitor** [comment]
@amengCow looks like KuCoin has changed their API with those specific URLs: https://docs.kucoin.com/#upcoming-changes. We will do our best to update it in both CCXT and CCXT Pro as soon as possible.

**Comment by amengCow** [comment]
goods

**Comment by kroitor** [comment]
The will require Authentication for the orderbook data now, unfortunately: https://openapi-v2.kucoin.com/api/v3/market/orderbook/level2?symbol=ETH-BTC

**Comment by kroitor** [comment]
Please, upgrade your version of CCXT to 1.50.87 (the new build will arrive in ~20 minutes) and let us know if you have the same issue with this code:

```JavaScript
const ccxt = require('ccxt')
console.log ('CCXT Version:', ccxt.__version__)

async function main () {

    const exchange = new ccxt.kucoin({
        'apiKey': 'YOUR_API_KEY',
        'secret': 'YOUR_SECRET',
        'password': 'YOUR_API_PASSPHRASE',
    })

    const markets = await exchange.loadMarkets()
    // exchange.verbose = true // uncomment for debugging purposes if necessary
    const orderbook = await exchange.fetchOrderBook('TONE/ETH')
    console.log(orderbook)
}

main ()
```

**Comment by yurilozorio** [comment]
@kroitor the endpoint level2 with limit is still public, ex: https://openapi-v2.kucoin.com/api/v1/market/orderbook/level2_20?symbol=KLV-USDT ... I think we should maintain the level2 with limit using the public endpoint.

**Comment by kroitor** [comment]
@yurilozorio it is kept as v1, according to the docs:

- https://github.com/ccxt/ccxt/blob/master/js/kucoin.js#L319
- https://docs.kucoin.com/#get-part-order-book-aggregated

**Comment by yurilozorio** [comment]
@kroitor but in your commit you are using the private one.. no?
https://github.com/ccxt/ccxt/commit/568c2746fae4b21598f89299f0f987351f97ac3a#diff-01b07f5bb85bf5f4a7f48579dc34b463d5a07f14759585953d6c6596c2a737fcR843

**Comment by kroitor** [comment]
@yurilozorio ah, ok, will change that shortly, thx for pointing it out!
