### ISSUE TITLE
How can I error catch an incorrect symbol for OHLCV in Python?

### ISSUE THREAD

**Issue by Fast421** [ccxt/ccxt#9313]
Hello, I'm trying to error catch for incorrect ticker pairs when fetching the OHLCV data, I've reproduced the error here. I tried to follow this https://github.com/ccxt/ccxt/wiki/Manual#error-handling post but I'm not sure what's wrong in my code.

I've looked through these previous posts and they haven't been much help:
https://github.com/ccxt/ccxt/issues/7315
https://github.com/ccxt/ccxt/issues/1956

- OS: Windows 10
- Programming Language version: Python 3.8.5
- CCXT version: 1.50.51

```
import ccxt
exchange = ccxt.binance({
    "apiKey": api_key,
    "secret": secret_key
})
try:
    bars = exchange.fetch_ohlcv("AAAA/USDT", timeframe="1D", limit=50)
except ccxt.BadSymbol as e:
    print("Bad Symbol")

```

```
Exception has occurred: BadSymbol
binance does not have market symbol AAAA/USDT
  File "C:\Users\Documents\Python\test.py", line 7, in <module>
    bars = exchange.fetch_ohlcv("AAAA/USDT", timeframe="1D", limit=50)
```

**Comment by kroitor** [comment]
Run this code for testing:

```Python
import ccxt
exchange = ccxt.binance()
try:
    bars = exchange.fetch_ohlcv("AAAA/USDT", timeframe="1D", limit=50)
    print("Ok")
except ccxt.BadSymbol as e:
    print("Bad Symbol")
```

This is my output:

```
~/ccxt/python $ python3
Python 3.8.2 (default, Apr  8 2021, 23:19:18)
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccxt
>>> exchange = ccxt.binance()
>>> try:
...     bars = exchange.fetch_ohlcv("AAAA/USDT", timeframe="1D", limit=50)
...     print("Ok")
... except ccxt.BadSymbol as e:
...     print("Bad Symbol")
...
Bad Symbol
>>>
```

**Comment by Fast421** [comment]
![image](https://user-images.githubusercontent.com/85361019/120862878-98cda880-c581-11eb-8d28-9c89cf5069b2.png)
I'm getting an exception when I'm running it still

**Comment by kroitor** [comment]
@Fast421 your VSCode debugger is configured to intercept all exceptions: https://stackoverflow.com/questions/52674581/why-is-try-except-block-not-working-in-visual-studio-code-for-python-3-7
This is not an issue with CCXT. Let us know if that does not answer your question.

**Comment by kroitor** [comment]
P.S. Also shown in this video: https://www.youtube.com/watch?v=JDaZEAn42pg
