### ISSUE TITLE
Is it planned to implement watchTickers for Binance in near future? 

### ISSUE THREAD

**Issue by wunderb1t** [ccxt/ccxt#9314]
Is it planned to implement `whatchTickers` for `Binance` in near future? Subscribing 1000 pairs one by one via `whatchTicker` takes much time.

- OS: DEBIAN (Docker)
- Programming Language version: NodeJS
- CCXT version: Pro version: 0.6.81

```
const exchange = ccxtpro.binance();
let symbols = []; // 1000+ symbols

async function subscribePairs() {
  while(symbols.length) {
      // takes > 1 sec to subscribe fro each symbol 
      await exchange.instance.watchTicker(symbols.shift());
  }
}
```

**Comment by frosty00** [comment]
#12656
