### ISSUE TITLE
Deribit: is it possible to fetch index?

### ISSUE THREAD

**Issue by nerddan** [ccxt/ccxt#9316]
Deribit provides indices of BTC and ETH and volatility index of BTC.

Can we fetch them with ccxt?

https://www.deribit.com/main#/indexes

**Comment by kroitor** [comment]
@nerddan you can do that using the implicit API endpoints:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api
- https://github.com/ccxt/ccxt/blob/master/js/deribit.js#L103

Let us know if that does not help.
