### ISSUE TITLE
ccxtpro Permission denied

### ISSUE THREAD

**Issue by VadimSFedin** [ccxt/ccxt#9318]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: AWS LInux
- Programming Language version: Python 3.8
- CCXT version: 1.50.88

```
I had Python 3.6 and everything worked fine, I installed Python 3.8 today and I am not able to install ccxtpro.
I tried to install ccxtpro on AWS Linux server with:

ec2-user:~/environment $ python3 -m pip install git+ssh://git@github.com/kroitor/ccxt.pro.git#subdirectory=python

```

```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS

Defaulting to user installation because normal site-packages is not writeable
Collecting git+ssh://****@github.com/kroitor/ccxt.pro.git#subdirectory=python
  Cloning ssh://****@github.com/kroitor/ccxt.pro.git to /tmp/pip-req-build-ayt89_ao
  Running command git clone -q 'ssh://****@github.com/kroitor/ccxt.pro.git' /tmp/pip-req-build-ayt89_ao
  Permission denied (publickey).
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.
WARNING: Discarding git+ssh://****@github.com/kroitor/ccxt.pro.git#subdirectory=python. Command errored out with exit status 128: git clone -q 'ssh://****@github.com/kroitor/ccxt.pro.git' /tmp/pip-req-build-ayt89_ao Check the logs for full command output.
ERROR: Command errored out with exit status 128: git clone -q 'ssh://****@github.com/kroitor/ccxt.pro.git' /tmp/pip-req-build-ayt89_ao Check the logs for full command output.

```

**Comment by kroitor** [comment]
What do you see in the log file mentioned in the error message above?

> WARNING: Discarding git+ssh://****@github.com/kroitor/ccxt.pro.git#subdirectory=python. Command errored out with exit status 128: git clone -q 'ssh://****@github.com/kroitor/ccxt.pro.git' /tmp/pip-req-build-ayt89_ao Check the logs for full command output.
> ERROR: Command errored out with exit status 128: git clone -q 'ssh://****@github.com/kroitor/ccxt.pro.git' /tmp/pip-req-build-ayt89_ao Check the logs for full command output.

**Comment by kroitor** [comment]
In order to use git+ssh authentication, you have to configure your GitHub SSH authentication on your AWS server:

- https://docs.github.com/en/github/authenticating-to-github

Alternatively, you can use the `git+https` schema to authenticate with a login and password: https://github.com/ccxt/ccxt/wiki/ccxt.pro.install#python

**Comment by VadimSFedin** [comment]
Oh, git+https works! thanks for your quick response!
