### ISSUE TITLE
Transfer between Binance wallets return status, datetime and timestamp = None

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#9321]
Hello all,

I noticed that transfer between Binance wallets return some missing information, please find an example:

```
b.transfer('USDT', 1, 'future', 'spot')

{'info': {'tranId': '65052934028'},
 'id': '65052934028',
 'timestamp': None,
 'datetime': None,
 'currency': 'USDT',
 'amount': 1,
 'fromAccount': 'future',
 'toAccount': 'spot',
 'status': None}
```

As you can see status, timestamp and datetime are set to None even when transfer is successful. It's a minor issue but it's useful to have these data in order to monitor transfers.

Best,
Kinzowa

**Comment by kroitor** [comment]
Hi! The `info` structure contains the response from the exchange "as is", untouched: `'info': {'tranId': '65052934028'},` ← there's no timestamp there, therefore it's not populated. This is documented throughout the Manual – not all exchanges will provide all the fields in all the structures. If you need a timestamp, you can just call `exchange.milliseconds()` or `exchange.iso8601(exchange.milliseconds())`. Hope that answers your question. Let us know if not.

**Comment by Kinzowa** [comment]
Thanks Igor, I will do that
