### ISSUE TITLE
Unable to create DOGE/USDT orders on bybit + Massive latencies on binance

### ISSUE THREAD

**Issue by SITZ** [ccxt/ccxt#9323]
- OS: `RedHat Linux 8.3`
- Programming Language version: `Python 3.8`
- CCXT version: `1.49.5`

```
bybit_client = client = ccxt.bybit(
        {
            'apiKey': api_key, 'secret': api_secret,
            "options": {
                "defaultType": 'future'
            }
        }
    )
bybit_client.set_sandbox_mode(True)  # enable testnet

res = bybit_client.create_market_sell_order(symbol='DOGE/USDT', amount=100)
```

```
BadRequest: bybit {"ret_code":10001,"ret_msg":"Param validation for 'symbol' failed on the 'symbol' tag","ext_code":"","ext_info":"","result":null,"time_now":"1622972584.829989","rate_limit_status":99,"rate_limit_reset_ms":1622972584828,"rate_limit":100}
```

Given bybit recently launched the instrument, I suspected ccxt had to be updated somehow for support. So, I upgraded ccxt to latest version `1.50.88` for possible new support addition and that seems to indeed solve it.

2/ But, on upgrading the ccxt libraries, new / cancel order times at binance jump through the roof to around 500ms, making it not possible to use the upgraded version of library at all.

Latencies with `ccxt=1.49.5`, jitter spikes happen till 100ms
<img width="1399" alt="Screenshot 2021-06-06 at 11 52 56" src="https://user-images.githubusercontent.com/356043/120920154-c0299000-c6bd-11eb-980c-7672ea255135.png">

Latencies with `ccxt=1.50.88`, jitter spikes continuously happening upto 500ms
<img width="1396" alt="Screenshot 2021-06-06 at 11 53 37" src="https://user-images.githubusercontent.com/356043/120920173-d8011400-c6bd-11eb-93e4-66e0f71959b3.png">

We're also users of ccxt pro and tried async client as well, but issue seems to persist with newer libraries and I'm unable to resolve this after days of debugging. Earlier version's jitter also is pretty big, but now it's un-workable with.
Would appreciate any support!

**Comment by kroitor** [comment]
How do you measure the latencies?

**Comment by SITZ** [comment]
We calculate 3 latencies:
1/ Round trip time, (local finish time - local start time)
2/ Server to Exchange, (Binance `updateTime` - local start time)
3/ Exchange to server, (local finish time - binance `updateTime`)

Graphs above are showing 2 & 3 and we're seeing server to exchange showing this behavior, return time stays pretty consistent before and after upgrades. So, working on assumption that this is caused by us while reaching exchange.

**Comment by kroitor** [comment]
Do you adjust for the time difference before comparing to server time, though?
Can you paste the code you use to measure the latencies or something we could reproduce?

**Comment by SITZ** [comment]
We're directly working with unix epoch timestamps locally and response received from exchange. so should not have discrepancy that way?
(ps: we're also geo-located close to binance servers already for optimal network latency setup)

this segment should explain how we are doing it right now:
```
pre_execution = Decimal(str(time.time())) * 1000
response = api_client.create_limit_order(
    symbol=self.pair_name,
    price=message.price,
    amount=message.quantity,
    side=message.side
)
post_execution = Decimal(str(time.time())) * 1000
exchange_updated_time = Decimal(response['info']['updateTime'])

print('quote-server-to-exchange', exchange_updated_time - pre_execution)
print('quote-exchange-to-server', post_execution-exchange_updated_time)
```

**Comment by kroitor** [comment]
I suggest this:

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit

```Python
import ccxt
print('CCXT Version:', ccxt.__version__)

exchange = ccxt.binance({
    'enableRateLimit': True,
    # 'rateLimit': 500,  # adjust the default rate limit how you want
})

exchange.set_sandbox_mode(True)
markets = exchange.load_markets()

# exchange.verbose =True  # uncomment for debugging purposes

rtt_sum = 0
attempts = 10
while i in range(0, attempts):
    now = exchange.milliseconds()
    order = exchange.create_market_sell_order('DOGE/USDT', 100)
    rtt = exchange.milliseconds() - now
    print(rtt, 'ms')
    rtt_sum += rtt
    
print('Average RTT:', rtt_sum/attempts) 
```

What's your output with both versions?

**Comment by SITZ** [comment]
Just ran the script your way and numbers don't look that different from 1st glance (latency average and jitter)
but these avg testnet numbers are way too high vs 20ms avg on production times showing spikes of 500ms.

so, not sure if this is fair benchmark. What other metrics can explain the discrepancy in jitter in prod from your POV?
```
CCXT Version: 1.49.5
467 ms
510 ms
491 ms
509 ms
497 ms
499 ms
497 ms
500 ms
501 ms
501 ms
Average RTT: 497.2
```

```
CCXT Version: 1.50.95
471 ms
503 ms
499 ms
495 ms
503 ms
496 ms
507 ms
499 ms
507 ms
497 ms
Average RTT: 497.7
```

**Comment by kroitor** [comment]
> What other metrics can explain the discrepancy in jitter in prod from your POV?

I think the very assumption that the testnet is as fast as the production system – is wrong, the testnet is usually not even remotely as powerful as the production backend, so i'm not sure if it's ok to compare them at all.

**Comment by SITZ** [comment]
Indeed - I was saying the exact same thing.

I ran these benchmarks on testnet just now, but original metrics I reported were showing production metrics - so hard to show the discrepancy between version upgrades from testnet it seems. Thinking if can run this again in some prod setting!

**Comment by kroitor** [comment]
You can tweak the rate-limiter, or turn it off to do a pure test without the rate limiting.

**Comment by SITZ** [comment]
Oh wow, just spotted rate limiter is enabled by default, so disabling them on testnet totally turns the numbers.
We have been using the default config all this time - wonder if that's been the reason all this time! 🤔 
```
CCXT Version: 1.49.5
25 ms
18 ms
23 ms
14 ms
29 ms
26 ms
20 ms
10 ms
15 ms
12 ms
Average RTT: 19.2
```

```
CCXT Version: 1.50.95
18 ms
27 ms
15 ms
16 ms
27 ms
11 ms
19 ms
17 ms
11 ms
16 ms
Average RTT: 17.7
```

**Comment by kroitor** [comment]
@SITZ yes, but also, make sure your read this very-very carefully, it's all documented:

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/wiki/Manual#notes-on-rate-limiter
- https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties

In general, we recommend reading the entire Manual from top to bottom at least once – that will save your time, really.

You want to be careful with your rate limit, since otherwise they will ban you. So the balance of "latency" vs "reactivity" is up to you and you can tweak the rate limit for bursty orders. We are also working on a better rate-limiter with tokenBucket algorithm that will allow bursts and call costs.

All about rate-limiting here:

- https://github.com/ccxt/ccxt/issues/5565#issuecomment-513635562

Hope the above answers your question, let us know if not. Feel free to reopen this issue or just ask further questions if any.

**Comment by SITZ** [comment]
Thanks @kroitor, that was indeed the culprit all this time and we missed it altogether. Appreciate the help 🙏🏼 

_Closure:_

I did read through the doc before but never looked into this being the reason because the doc mentioned that default behavior is rate limit being **disabled** and users have to custom build (which we did and were relying on all this time)
https://ccxt.readthedocs.io/en/latest/manual.html
<img width="681" alt="Screenshot 2021-06-06 at 13 16 52" src="https://user-images.githubusercontent.com/356043/120922514-eead6800-c6c9-11eb-8cea-ce296991db3a.png">

But, code shows that it's **enabled** by default

<img width="486" alt="Screenshot 2021-06-06 at 13 21 20" src="https://user-images.githubusercontent.com/356043/120922544-18ff2580-c6ca-11eb-8849-ee3287abe2e3.png">

**Comment by kroitor** [comment]
The RTD version of the docs is slightly outdated, the original doc is here: 

- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/wiki/Manual

**Comment by frosty00** [comment]
@SITZ I've started updating the read the docs already, I expect it to be updated by the end of the week or the week after
