### ISSUE TITLE
How to solve:  Invalid Order: binance {"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}

### ISSUE THREAD

**Issue by theishantha** [ccxt/ccxt#9324]
Invalid Order: binance {"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}

**Comment by kroitor** [comment]
MIN_NOTIONAL = minimal order cost = amount * price.
Make sure that your total  is greater than the minimal cost of the market in question:

- https://github.com/ccxt/ccxt/wiki/Manual#market-structure
- https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits
- https://github.com/ccxt/ccxt/issues/6420#issuecomment-579029799
