### ISSUE TITLE
okex quarter contract data symbol?

### ISSUE THREAD

**Issue by xgdgsc** [ccxt/ccxt#933]
How to fetch okex btc quarter data ? Using symbol of `BTC/USD` seems return the `this_week` contract.

**Comment by kroitor** [comment]
Pass `{'contract_type': 'quarter'}` in the additional params, like shown here: https://github.com/ccxt/ccxt/wiki/Manual#custom-order-params. Most methods support additional params which you can use to override the defaults. Does this help?

**Comment by xgdgsc** [comment]
Thanks. That works.
