### ISSUE TITLE
WHY REMOVE the binance's market's `type`  prop ?

### ISSUE THREAD

**Issue by airwin** [ccxt/ccxt#9332]
As many exchange's market, I use `fetchMarkets`'s 'type' prop to recognize market between spot/margin/future/etc..
But in the new vertsion of binance.js, there's no 'type' prop in the market.
This change make a lots of errors in my code, will it be added back later?

- OS: ubuntu
- Programming Language version: node v14
- CCXT version: latest

**Comment by frosty00** [comment]
@airwin we were trying to unify the naming of the future / delivery, since some contracts on binance may be future but also delivery, we suggest to use binanceusdm binancecoinm for futures trading

**Comment by airwin** [comment]
I think the `type` prop is part of the unify structure and should be keep (as other exchanges).
And the new version should be friendly for those users rely on that prop (or publish a BREAK CHANGE notice?).

**Comment by kroitor** [comment]
We will restore the `type` in binance markets shortly.
