### ISSUE TITLE
504 Server Error: Gateway Time-out for url ....

### ISSUE THREAD

**Issue by mohammadtirex** [ccxt/ccxt#9338]
Hi 
For monitor/follow price data of a cryptocurrency market, I try to get data in a for loop by frequently (every 10 to 50 sec) send request for price checking, In some iteration of for loop I got Error "504 Server Error"  I guess the total number of request sent to an exchange is limit, Is this True? If so, How Can I check or get market data without frequently  ?

`exchange = ccxt.coinex()                                                                        # get coinex exchange
Markets  = exchange.load_markets()    
for m in Markets:
      do somthing...`

**Comment by kroitor** [comment]
Hi! 

- What is your version of CCXT?
- Can you please paste your code?
- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by mohammadtirex** [comment]
Thank You!
ccxt ver: 1.50.76

`import ccxt
import pandas as pd
from time import sleep

exchange = ccxt.coinex()                                             
Markets  = exchange.load_markets()    

for m in Markets:
    ### Get Tick Data
    ticker              = (exchange.fetchOHLCV(m,timeframe='1h',limit=(10)))  
    df                  = pd.DataFrame(ticker,columns=('date','open','high','low','close','volume'))
    # if some condition: 
    print(m)
    sleep(10)
    
print('Finish')`

**Comment by ttodua** [comment]
The issue might be with rate-limits. Our rate-limit unification and filling the gaps are work-in-progress.
You might catch the exception too, to avoid the break of whole script, like amending your snippet to:
```
for m in Markets:
    try {
        ticker = (exchange.fetchOHLCV(m,timeframe='1h',limit=(10)))
    } catch (ex) {
        console.log("Error while fetching :" + m);
        console.log(ex);
    }
```
Additionally, this issue might be caused for other reasons too (network connectivity or exchange downtimes , if exchange is low-end).
Please let us know if you still experience any issue or it was gone away automatically.
