### ISSUE TITLE
FTX: support watching a single market on orders, trades

### ISSUE THREAD

**Issue by pietrodn** [ccxt/ccxt#9341]
- OS: macOS 11
- Programming Language version: Python 3.9
- CCXT version: ccxt 1.51.20, ccxtpro 1.0.1

In the `ftx` class of CCXT Pro, the `watch_orders()` and `watch_my_trades()` methods always subscribes to the WebSocket feed of the orders and the trades for **all the markets**, even if the `symbol` parameter is passed.

FTX supports subscribing to a single market (seethe  [WebSocket API docs](https://docs.ftx.com/#request-format)), but CCXT Pro is not passing the correct parameter to do so.

Indeed, when calling `client.watch_orders("ETH-PERP")`, it sends a subscribe message like this:
```json
{"op": "subscribe", "channel": "orders"}
```

instead than:
```json
{"op": "subscribe", "channel": "orders", "market": "ETH-PERP"}
```

This is caused by a bug in the `watch_private()` method that builds the request without the `market` attribute.

This is simply fixed by adding:
```python
        if symbol is not None:
            request['market'] = market['id']
```
at the end of `watch_private()`.

**Comment by pietrodn** [comment]
Uhm, by experimenting with it it seems that FTX does not actually support listening for one symbol only on private channels, but only on public ones. Indeed if I send `{"op": "subscribe", "channel": "orders", "market": "ETH-PERP"}` I receive back `{'type': 'subscribed', 'channel': 'orders'}`.

I see that CCXT filters by symbol client side... that looks like the correct behaviour, so I'm closing the issue. Sorry 🤷

**Comment by kroitor** [comment]
@pietrodn thx for the feedback!
