### ISSUE TITLE
Implement order book checksum validation for FTX in CCXT Pro

### ISSUE THREAD

**Issue by pietrodn** [ccxt/ccxt#9347]
When listening to FTX order book data via WebSocket, FTX sends an initial full snapshot of the order book for the symbol, and then only sends some incremental "deltas" containing the newly added and removed order book levels ([documentation](https://docs.ftx.com/#orderbooks)).

Those "delta" message also contain a CRC32 checksum of the full order book, which should be compared with the local state of the order book to check if the local state is synchronized with the exchange. For example, if one delta message is dropped  by the WebSocket, the checksum will not match from that moment on, and the client will know that it is time to ask for a full fresh snapshot.

CCXT Pro correctly handles the delta order book messages, but does not compute nor validate the checksum (there is a `TODO` in the code). I think it would be nice to implement these 2 features in CCXT Pro.

## 1. Order book checksum check

Computing the checksum is easy, by following the algorithm outlined in the FTX documentation. Sample implementation in Python:
```python
import binascii
from itertools import chain, zip_longest
from typing import Iterable, Sequence

def compute_order_book_checksum(
    bids: Iterable[Sequence[float]], asks: Iterable[Sequence[float]]
) -> int:
    """
    Compute the checksum for the order book.

    Bids and asks are iterables of 2-item lists <price, quantity>.
    The algorithm to compute the checksum of the order book is described here:
    https://docs.ftx.com/#orderbooks

    :param bids: the list of bids
    :param asks: the list of asks
    :return: the CRC32 checksum of the order book
    """

    order_book_hash_iterator = zip_longest(bids, asks, fillvalue=tuple())
    check_string = ":".join(
        (
            str(token)
            for ask_level, bid_level in order_book_hash_iterator
            for token in chain(ask_level, bid_level)
        )
    )

    return binascii.crc32(check_string.encode("ascii"))
```

Then, the `handle_order_book_update()` method of `ftx.py` must be modified to compute the checksum and reject the future with a specific exception if it does not match (let's call it `OrderBookCorrupted`).

As a result, `watch_order_book()` will raise the exception.

## 2. Implement a recovery mechanism

If we acknowledge that the local state of the order book is corrupted, there must be a way to recover and resume the order book streaming.

From my experiments, the only way to obtain a fresh snapshot of the order book from FTX on the WS connection is to send an unsubscribe message and then subscribe again.

Unfortunately, the unsubscribe functionality is not yet implemented in CCXT Pro, so that's another feature request.

There are 2 possible design solutions here:
1. The `ftx.watch_order_book()` method simply raises an `OrderBookCorrupted` exception, and lets the library user unsubscribe and resubscribe to resume the order book streaming by exposing an appropriate unsubscribe API.
2. The recovery (unsubscribe+resubscribe) happens directly inside `ftx.watch_order_book()`, and it is 100% transparent to the library user.

**Comment by SaneBow** [comment]
@kroitor Any update on this? The checksum validation is still marked as `TODO` in the CCXT Pro code.

**Comment by samgermain** [comment]
@kroitor @carlosmiei @frosty00 

Is this specific to FTX? Or could other exchanges have it implemented?

**Comment by frosty00** [comment]
#15287 ftx delisted
