### ISSUE TITLE
exchange.watchBalance sometimes fails after reconnection  to the Binance Spot

### ISSUE THREAD

**Issue by RusDyn** [ccxt/ccxt#9349]
exchange.watchBalance sometimes fails after reconnection to the Binance Spot

- OS: Mac
- Programming Language version: Node.js
- CCXT.Pro version: 0.7.7

Log
```
this.balance[accountType]['info'] = message;
                                          ^
TypeError: Cannot set property 'info' of undefined
    at binance.handleBalance (./ccxt-pro/js/binance.js:885:43)
    at binance.handleMessage (./ccxt-pro/js/binance.js:1349:27)
```

Steps to reproduce:
```
- Run await exchange.watchBalance
- Switch off internet access
- Wait for NetworkError
- Switch on internet
- Error
```

It seems that this happens in handleBalance (js/binance.js) because of calling to subscriptions[0]. It could contain spot (works) or spotPrivate (fails).

**Comment by frosty00** [comment]
@RusDyn the `binance.options['defaultType']` should never be spotPrivate. This issue can be closed.
