### ISSUE TITLE
okex5 handles_error

### ISSUE THREAD

**Issue by ItisDL** [ccxt/ccxt#9358]
- OS: big sur 11.4 (20F71)
- Programming Language version: python 3.8.6
- CCXT version: 1.50.44

```
handle_errors func
When my symbol is not my order type
You cannot catch exceptions to this result format
```

```
Response: GET https://www.okex.com/api/v5/trade/order?instId=XRP-USDT&ordId=317333131091132416 200 
{"code":"51603","data":[],"msg":"Order does not exist"}
```

**Comment by kroitor** [comment]
We've changed that to `OrderNotFound`, let us know if upgrading to 1.51.33+ does not resolve this issue. Thanks for your feedback!

**Comment by ItisDL** [comment]
> We've changed that to `OrderNotFound`, let us know if upgrading to 1.51.33+ does not resolve this issue. Thanks for your feedback!

`
def handle_errors(self, httpCode, reason, url, method, headers, body, response, requestHeaders, requestBody):
        if not response:
            return  # fallback to default error handler
        #
        #     {"code":"1","data":[{"clOrdId":"","ordId":"","sCode":"51119","sMsg":"Order placement failed due to insufficient balance. ","tag":""}],"msg":""}
        #
        code = self.safe_integer(response, 'code')
        if code == 1:`
 
 
{"code":"51603","data":[],"msg":"Order does not exist"}

I mean handle_ Error function cannot capture errors with code not 1😝

**Comment by ItisDL** [comment]
So I tried to modify the function to accommodate this return value
`
    def handle_errors(self, httpCode, reason, url, method, headers, body, response, requestHeaders, requestBody):
        if not response:
            return  # fallback to default error handler
        #
        #     {"code":"1","data":[{"clOrdId":"","ordId":"","sCode":"51119","sMsg":"Order placement failed due to insufficient balance. ","tag":""}],"msg":""}
        #
        code = self.safe_integer(response, 'code')
        if code == 1:
            feedback = self.id + ' ' + body
            data = self.safe_value(response, 'data', [])
            for i in range(0, len(data)):
                error = data[i]
                errorCode = self.safe_string(error, 'sCode')
                message = self.safe_string(error, 'sMsg')
                self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
                self.throw_broadly_matched_exception(self.exceptions['broad'], message, feedback)
            raise ExchangeError(feedback)  # unknown message
        else:
            self.throw_exactly_matched_exception(self.exceptions['exact'], str(code), self.id + ' ' + body)
`

**Comment by ItisDL** [comment]
```
    def handle_errors(self, httpCode, reason, url, method, headers, body, response, requestHeaders, requestBody):
        if not response:
            return  # fallback to default error handler
        #
        #     {"code":"1","data":[{"clOrdId":"","ordId":"","sCode":"51119","sMsg":"Order placement failed due to insufficient balance. ","tag":""}],"msg":""}
        #
        code = self.safe_integer(response, 'code')
        if code == 1:
            feedback = self.id + ' ' + body
            data = self.safe_value(response, 'data', [])
            for i in range(0, len(data)):
                error = data[i]
                errorCode = self.safe_string(error, 'sCode')
                message = self.safe_string(error, 'sMsg')
                self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
                self.throw_broadly_matched_exception(self.exceptions['broad'], message, feedback)
            raise ExchangeError(feedback)  # unknown message
        else:
            self.throw_exactly_matched_exception(self.exceptions['exact'], str(code), self.id + ' ' + body)
```

**Comment by kroitor** [comment]
@ItisDL thx for pointing it out, i've pushed a fix for that to the master, it will arrive in 1.51.52+ in ~20 minutes. Let us know if you have issues with it after upgrading.

**Comment by ItisDL** [comment]
> @ItisDL thx for pointing it out, i've pushed a fix for that to the master, it will arrive in 1.51.52+ in ~20 minutes. Let us know if you have issues with it after upgrading.

`if (code is not None) and (code > 0):`

But the code is 0 ..

**Comment by ItisDL** [comment]
> @ItisDL thx for pointing it out, i've pushed a fix for that to the master, it will arrive in 1.51.52+ in ~20 minutes. Let us know if you have issues with it after upgrading.

Hi~ o(*￣▽￣*)ブ because data[] so raise ExchangeError(feedback)  # unknown message

**Comment by kroitor** [comment]
@ItisDL in this case we will have to check the message, cause data can be empty legitimately. Thx for your feedback, will push another fix shortly.

**Comment by kroitor** [comment]
@ItisDL hold on a sec, in your message above, the code is not 0. So code > 0 should match it.

**Comment by kroitor** [comment]
@ItisDL plz let us know if you still have it with 0.51.54+. Tested it on my side and it now says this:

```
OrderNotFound okex5 {"code":"51603","data":[],"msg":"Order does not exist"}
```

**Comment by omoxyron** [comment]
@kroitor it raises base ExchangeError (code 1) instead of more specific error in case of such a message:
`{"code":"1","data":[{"clOrdId":"","ordId":"","sCode":"51119","sMsg":"Order placement failed due to insufficient balance. ","tag":""}],"msg":""}`
(expected InsufficientFunds, got ExchangeError)
`{"code":"1","data":[{"clOrdId":"","ordId":"","sCode":"51402","sMsg":"Cancellation failed as the order is already completed."}],"msg":""}`
(expected OrderNotFound, got ExchangeError)
