### ISSUE TITLE
OKEx v5 showing incorrect taker fees for SWAP type instrument

### ISSUE THREAD

**Issue by hjastenger** [ccxt/ccxt#9361]
- Programming Language version: Python3.9
- CCXT version: latest

Hi, came across the SWAP fees listed in the OKEx5 python code base(https://github.com/ccxt/ccxt/blob/ffc66582fdb57ff56e7aea7fec8c66a9d6be3796/python/ccxt/okex5.py#L196).

- CCXT currently states that takers pays 0.075%.
- From OKEx fee listing it shows that takers pay 0.050%.

Any idea?

**Comment by kroitor** [comment]
The fees get propagated from the hardcoded defaults: https://github.com/ccxt/ccxt/blob/master/js/okex5.js#L177
Apparently, OKEX has updated their swap fees. Will get that fixed in a few minutes in the build 1.51.39+, thanks for reporting!
