### ISSUE TITLE
KUCOIN Invalid KC-API-PASSPHRASE

### ISSUE THREAD

**Issue by AndrNic** [ccxt/ccxt#9369]
I get Invalid KC-API-PASSPHRASE. Where is the error?
public async Task<string> GetOpenOrders()
    {
      string url = "https://api.kucoin.com";
      string endpoint = "/api/v1/orders";
      HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Get, new Uri(url + endpoint));
      var timestamp = DateTimeOffset.UtcNow.ToUnixTimeMilliseconds().ToString();
      var preSign = timestamp + "GET" + endpoint;
      var hmac1 = new HMACSHA256(Encoding.UTF8.GetBytes(API_SECRET));
      var signature = BitConverter.ToString(hmac1.ComputeHash(Encoding.UTF8.GetBytes(preSign))).ToLower().Replace("-", "");
      var hmac2 = new HMACSHA256(Encoding.UTF8.GetBytes(API_SECRET));
      var phrase = BitConverter.ToString(hmac2.ComputeHash(Encoding.UTF8.GetBytes(PASSPHRASE))).ToLower().Replace("-", "");

      request.Headers.Add("KC-API-KEY", API_KEY);
      request.Headers.Add("KC-API-SIGN", signature);
      request.Headers.Add("KC-API-TIMESTAMP", timestamp);
      request.Headers.Add("KC-API-PASSPHRASE", phrase);
      request.Headers.Add("KC-API-KEY-VERSION", "2");
      HttpResponseMessage response = await httpClient.SendAsync(request).ConfigureAwait(false);
      string message = await response.Content.ReadAsStringAsync();
      return message;//"{\"code\":\"400004\",\"msg\":\"Invalid KC-API-PASSPHRASE\"}"
    }

**Comment by sloppyjuicy** [comment]
@AndrNic @znarf @xpl @speedmax

**Comment by kroitor** [comment]
@AndrNic have you tried making a new keypair?
Does your password match to the passphrase set on your key?
Have you checked your keys with the KuCoin website?

**Comment by kroitor** [comment]
@AndrNic we can only support you on CCXT, however we cannot support you on arbitrary code. Make sure that the password is properly encoded and the request is properly signed.

**Comment by AndrNic** [comment]
I just made a new key pair. I only have one api-key, one api-secret, one api name and one api passphrase: https://help.3commas.io/en/articles/3109059-kucoin-how-to-create-api-keys
I ran the code with this new data and got the same message:  Invalid KC-API-PASSPHRASE

**Comment by kroitor** [comment]
@AndrNic what is your version of CCXT?

**Comment by AndrNic** [comment]
I don't use CCXT because I write in C#. But if you have a method for requesting an order in another language, I'll ask someone to translate it. I used the code from the documentation. Can the error be related to the fact that I have not yet conducted any transactions and have not entered a cryptocurrency? Do you have any API-KEY, API-SECRET, or PASSPHRASE open for testing?
