### ISSUE TITLE
help authenticating to KuCoin Exchange using ccxtPro

### ISSUE THREAD

**Issue by korchix** [ccxt/ccxt#9371]
Hello Guys, 

i tried to authenticate to Kucoin using ccxtPro but it doesn't work, can someone please correct what i'm doing wrong here ?

here is my code:

```
exchange_kucoin = ccxtpro.kucoin({
    'apiKey': const.API_KEY,
    'secret': const.API_SECRET,
    'password': const.API_PASSPHRASE,
    'enableRateLimit': True,
    'headers': {
        'KC-API-KEY': const.API_KEY,
    }
})
```
i have also tried this without the "header" but still the same issue

but when i try to run a function to get some informations about my account, i get this error: 

`kucoin KC-API-KEY not exists`

the ccxtpro version i'm using is: print(ccxtpro.__version__) ==> 0.7.19

**Comment by kroitor** [comment]
@korchix have you tried recreating your API Key?

**Comment by korchix** [comment]
@kroitor it works now with the new key, thank you for the hint.
