### ISSUE TITLE
Websocket many coins' ticker

### ISSUE THREAD

**Issue by Salz0** [ccxt/ccxt#9378]
- OS: Windows 10
- Programming Language version: python 3.9.2

Greetings!

I have read the documentation about ohlcv's and want to find out how do you retrieve the ohlcv's of multiple coins via a WebSocket?
I need live data with a socket but haven't found async/WebSocket implementations in examples.py

Could anyone help with this?
My exchange is Binance

**Comment by kroitor** [comment]
Hi! Please, check here:

- https://github.com/ccxt/ccxt/issues/6543
- https://ccxt.pro/
