### ISSUE TITLE
Serialization issue in codebase

### ISSUE THREAD

**Issue by ttodua** [ccxt/ccxt#9381]
We are experiencing the issues due to minor mistakes in the codebase.
We use local file-storing (to cache some things, to have available for next calls):

```
	public function cache_file_get_serialize($uniqFileName)
	{
		return unserialize( file_get_contents(__DIR__."/$uniqFileName") );
	}
	public function cache_file_set_serialize($uniqFileName, $content)
	{
		return file_put_contents(__DIR__."/$uniqFileName", serialize($content) );
	}
...
...
...


$key = "cached_$exchangeName";
if (!  ($exchange= $this->cache_file_get_serialize($key) )  )
{
            $exchange = new \\ccxt\\binance();
            $exchange->load_markets();
            $this->cache_file_set_serialize($key,  $exchange);
}

$result = $exchange->fetch_tickers() ;// or whatever function
var_dump($result);
```

However, on next calls the results are different, because the cached object is not able to reinstate correctly. However,after hours of debugging, we found that there are only minor tiny issues that needs to be fixed, and then everything will work well.
Specifically, when reinstating from cached object, the exchange's  `$this->number='floatval';` value is not being reinstated. So, it is not existent after reinstating and when calling the detrimental base function, named:

``` 
public function number($n) {
     return call_user_func($this->number, $n);
}
// and this function is being called primarily from `parse_number` function.
```

it thows exception,  because `$this->number` property doesnt exist when object is reinstated (however, on fresh instantiation, it is being set with `$this->number = 'floatval';` insied exchange's constructor function. So, at this moment, i have to pause here my investigation and wait your response, as this is critical thing (inability to cache, while there is so tiny fix needed). I think that parent's constructor is not being called during reinstation, but I am not sure at this moment, and want your thougts.

(btw, same happens with `apcu_fetch / apcu_store` variations which are similar to the above custom cache-get/set functions)

**Comment by frosty00** [comment]
@ttodua we'll look into this, btw you can just set $exchange->number = 'floatval' for now until we are able to fix it more.

**Comment by ttodua** [comment]
Thank you guys, your prompt  (even "we will look into that") responses are one of the best I've met across any other projects.

**Comment by kroitor** [comment]
@ttodua thx for your reporting!

**Comment by ttodua** [comment]
I've made a further look, and found that (when I compare with `WinMerge`) the diference between fresh-initiated object and cached-reinstated object, is this two things (among thousands of other properties & values):

"lastRestRequestTimestamp" - reinstated object has a different, later timestamp|
 "number"   - exists only in fresh-object, not in reinstated. 
( and some unnecessary differences between "last_response_headers" values of fresh VS reinstated )

everything other (around 300 k lines of serialized data) is same. So, fortunately, seems very simple issue.

**Comment by ttodua** [comment]
Ok, i've fixed it. Whenever you need, you can fix it correctly, but i've used @frosty00 's above suggestion to manually set it.
