### ISSUE TITLE
Would it be possible to fetch amount of single currency in Futures?

### ISSUE THREAD

**Issue by avatar-lavventura** [ccxt/ccxt#9385]
- OS: mac
- Programming Language version: Python 3.8.5
- CCXT: version: `1.49.73`

----------

I was wondering is it possible to fetch only a single corresponding currency’s `total` (`free` and `locked`) quantity?  Like I just want to obtain the total quantity amount of a given symbol I own in `futures`, instead of fetching all and iterate over them.

My approach:

```
exchange = ccxt.binance(
        {
            "apiKey": api_key,
            "secret": api_secret,
            "enableRateLimit": True,  # https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
            "options": {"defaultType": "future",},
        }
)

wanted_symbol = "ETHUSDT"
futures = await bot.exchange_future.fetch_balance()
for future in futures["info"]["positions"]:
    if float(future["positionAmt"]) != 0.0:
        print(future["symbol"])
        if future["symbol"] == wanted_symbol:
            print(f"{wanted_symbol} exists")
            break
```

----------------

Is it possible to do something like: `output_future = await exchange_future.fetch_balance("ETH")`?

**Comment by ttodua** [comment]
It depends on exchange, as from 'balance endpoint' some exchanges support adding currency argument in request, and some exchanges just return balance and that's all. So, the `currency` argument (at this moment, before we introduce [`.features` functionality](https://github.com/ccxt/ccxt/issues/6772)) might work on some exchanges and might not work on other exchanges.  This is not what we can fix, if exchange doesn't support it. However, we might filter our the response to return balance of `currency` object only .
