### ISSUE TITLE
binance reduce only params connot be used

### ISSUE THREAD

**Issue by yihsiulee** [ccxt/ccxt#9386]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:mac osx 11.4
- Programming Language version:  react.js  
- CCXT version:1.51.40

I want to use the createMarketOrder or createOrder functions with the params of binance api in ccxt, but there are some errors.
here is the binance [api](https://binance-docs.github.io/apidocs/futures/en/#new-order-trade)
```
binance_exchange.createMarketOrder( symbol, side, amount, null, {"reduceOnly":true} )
```

```
Uncaught (in promise) BadRequest: binance {"code":-1102,"msg":"A mandatory parameter was not sent, was empty/null, or malformed."}
```
If I instead null to any price ( e.g. 0.3)
```
binance_exchange.createMarketOrder( symbol, side, amount, 0.3, {"reduceOnly":true} )
```
It show me the same error 

And I don't know why i need to input the price number even I used the "MARKET" order type 
Why the price isn't be the market price now?
Can I just input params of these functions below?
```
binance_exchange.createMarketOrder( symbol, side, amount, {"reduceOnly":true} )
```
or
```
binance_exchange.createOrder(symbol, 'market', side, amount,{"reduceOnly":true})
```

thanks for your help!

**Comment by kroitor** [comment]
This will work:

```JasaScript
const type = 'market'
const price = undefined
// exchange.verbose = true // uncomment for debugging purposes if necessary
exchange.createOrder(symbol, type, side, amount, price, {'reduceOnly': true})
```

Answered here: 

- https://github.com/ccxt/ccxt/wiki/Manual#market-buys
- https://github.com/ccxt/ccxt/search?q=binance+reduceOnly&type=issues
- https://github.com/ccxt/ccxt/search?q=binance+quoteOrderQty&type=issues

Hope that helps, let us know if not.

**Comment by yihsiulee** [comment]
thanks , it works!!
