### ISSUE TITLE
How to create an order for bitget

### ISSUE THREAD

**Issue by pnama** [ccxt/ccxt#9388]
I'm trying to create a limit order but I'm having the error message. Any ideas what I'm doing wrong?

bitget = ccxt.bitget({'apiKey': '', 'secret': '', 'password': '', 'options': {'defaultType': 'swap'}})
balances = bitget.fetch_balance()
balance = balances['CMT_BTCUSDT']
pprint.pprint(balance)

order = bitget.create_limit_buy_order(
    symbol='CMT_BTCUSDT',
    amount=0.0001,
    price=40000,
    params={'type': '1'}
)

error message:
ccxt.base.errors.ExchangeError: bitget {"code":"40017","msg":"Parameter verification failed,Number of ordersRange error","requestTime":16237965,"data":null}

**Comment by kroitor** [comment]
> Any ideas what I'm doing wrong?

Paste your verbose output, and your version numbers:

```Python
print('CCXT Version:', ccxt.__version__)
bitget = ccxt.bitget({'apiKey': '', 'secret': '', 'password': '', 'options': {'defaultType': 'swap'}})
bitget.load_markets()
bitget.verbose = True
balances = bitget.fetch_balance()
balance = balances['CMT_BTCUSDT']
pprint.pprint(balance)

order = bitget.create_limit_buy_order(
    symbol='CMT_BTCUSDT',
    amount=0.0001,
    price=40000,
    params={'type': '1'}
)

```

**Comment by pnama** [comment]
CCXT Version is 1.48.45 and error happens when https://capi.bitget.com/api/swap/v3/order/placeOrder :(


Request: GET https://api.bitget.com/api/v1/account/accounts?method=accounts&sign=xxxxx&req_time=xxxxx&accesskey=xxxxx{'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://api.bitget.com/api/v1/account/accounts?method=accounts&sign=xxxxxxx&req_time=xxxxx&accesskey=xxxxxx200 {'Date': 'Tue, 15 Jun 2021 23:00:28 GMT', 'Content-Type': 'text/html;charset=UTF-8', 'Content-Length': '95', 'Connection': 'keep-alive', 'Access-Control-Allow-Origin': '*', 'Cache-Control': 'no-cache', 'X-Frame-Options': 'SAMEORIGIN', 'X-XSS-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Server': 'Nginx', 'Strict-Transport-Security': 'max-age=15768000;includeSubDomains;preload'} {"status":"ok","ts":1623798028314,"data":[{"id":"3751092291","type":"spot","state":"working"}]}

Request: GET https://capi.bitget.com/api/swap/v3/account/accounts {'ACCESS-KEY': 'xxxxxx', 'ACCESS-SIGN': 'xxxxxx/e+GHWdXk=', 'ACCESS-TIMESTAMP': 'xxxx', 'ACCESS-PASSPHRASE': 'xxxxx', 'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://capi.bitget.com/api/swap/v3/account/accounts 200 {'Date': 'Tue, 15 Jun 2021 23:00:28 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': 'locale=en-US; Max-Age=604800; Expires=Tue, 22-Jun-2021 23:00:28 GMT; Path=/', 'X-RateLimit-Limit': '10', 'X-RateLimit-Remaining': '9', 'X-RateLimit-Used': '1', 'X-RateLimit-Reset': '1623798029414', 'X-Content-Type-Options': 'nosniff, nosniff', 'X-XSS-Protection': '1; mode=block, 1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Frame-Options': 'DENY, SAMEORIGIN', 'Content-Encoding': 'gzip', 'Server': 'Nginx', 'Strict-Transport-Security': 'max-age=15768000;includeSubDomains;preload'} 
{'free': 8.3333866, 'total': 8.3333866, 'used': 0.0}

Request: POST https://capi.bitget.com/api/swap/v3/order/placeOrder {'ACCESS-KEY': 'xxxxxxxx', 'ACCESS-SIGN': 'j/xxxxx=', 'ACCESS-TIMESTAMP': 'xxxxx', 'ACCESS-PASSPHRASE': 'xxxx', 'Content-Type': 'application/json', 'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate'} {"symbol":"cmt_btcusdt","order_type":"0","client_oid":"xxxxx","size":"0","type":"1","match_price":"0","price":"40000"}

Response: POST https://capi.bitget.com/api/swap/v3/order/placeOrder 400 {'Date': 'Tue, 15 Jun 2021 23:00:28 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Set-Cookie': 'locale=en-US; Max-Age=604800; Expires=Tue, 22-Jun-2021 23:00:28 GMT; Path=/', 'X-RateLimit-Limit': '20', 'X-RateLimit-Remaining': '19', 'X-RateLimit-Used': '1', 'X-RateLimit-Reset': '1623798029642', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Frame-Options': 'DENY', 'Server': 'Nginx'} {"code":"40017","msg":"Parameter verification failed,Number of ordersRange error","requestTime":1623798028643,"data":null}
Traceback (most recent call last):
  File "C:\Users\xxx\PycharmProjects\AutoCoin\venv\lib\site-packages\ccxt\base\exchange.py", line 606, in fetch
    response.raise_for_status()
  File "C:\Users\xxx\PycharmProjects\AutoCoin\venv\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://capi.bitget.com/api/swap/v3/order/placeOrder

**Comment by kroitor** [comment]
@pnama please, upgrade your version of CCXT to 1.51+ and let us know if that does not help resolve your issue:

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by pnama** [comment]
I have upgraded to 1.51.49 but still having the error message "ccxt.base.errors.ExchangeError: bitget {"code":"40017","msg":"Parameter verification failed,Number of ordersRange error","requestTime":1623798647552,"data":null}"

**Comment by kroitor** [comment]
@pnama I will debug it on my side and will get back to you asap.

**Comment by pnama** [comment]
you are the best

**Comment by pnama** [comment]
@kroitor Hello again. I wonder if there's any changes? I have tried few minutes ago but couldn't create an order correctly :(
