### ISSUE TITLE
The documentation shows the broken POST code for Kucoin

### ISSUE THREAD

**Issue by AndrNic** [ccxt/ccxt#9390]
The documentation https://docs.kucoin.com/#authentication shows the broken POST code.
url = 'https://openapi-sandbox.kucoin.com/api/v1/deposit-addresses'
now = int(time.time() * 1000)
data = {"currency":"BTC"}
data_json = json.dumps(data)
str_to_sign = str(now) + 'POST' + '/api/v1/deposit-addresses' + data_json
signature = base64.b64encode(
hmac.new(api_secret.encode('utf-8'), str_to_sign.encode('utf-8'), hashlib.sha256).digest())
passphrase = base64.b64encode(
hmac.new(api_secret.encode('utf-8'), api_passphrase.encode('utf-8'), hashlib.sha256).digest())
headers = {
        "KC-API-SIGN": signature,
        "KC-API-TIMESTAMP": str(now),
        "KC-API-KEY": api_key,
        "KC-API-PASSPHRASE": passphrase,
        "KC-API-KEY-VERSION": "2"
    }
response = requests.request('post', url, headers=headers, data=data_json)
print(response.status_code)
print(response.json())

 Instead of "KC-API-KEY-VERSION": 2, it should be "KC-API-KEY-VERSION": "2"
If static IP and API with Trade and Transfers the code returns error 403 {'code': '400007', 'msg': 'Access denied, require more permission.'. If static IP and API Trade 415 {'code': '415000', 'msg': 'Unsupported Media Type'} Which code POST requests is correct? 
For request '/api/v1/accounts' always return 400{'code': '400000', 'msg': 'Bad Request'}
I use  to successfully make GET requests and get a list of open orders and the balance.
What is the correct code for the request POST?  What permissions are required to create a new order, requests '/api/v1/deposit-addresses' and '/api/v1/accounts'?

**Comment by kroitor** [comment]
@AndrNic do you have an issue with the KuCoin implementation from CCXT? If so, please, paste your code and version numbers: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help. Unfortunately, we cannot explain every single inconsistency on the internet, some info maybe outdated. We can solve bugs and fix CCXT though. Feel free to reopen this issue if necessary, or just ask further questions if any.
