### ISSUE TITLE
Semantic versioning for ccxt?

### ISSUE THREAD

**Issue by sitz** [ccxt/ccxt#9391]
Hi there - We've been using ccxt as great solution to some of our trading operations. Thank you for all the effort!

Given fast releases and essential patches coming in continuously for exchange updates & improvements we'd like to be on the latest non-breaking version of ccxt all the time.

But, Couple of recent examples of easily tripping on this:
- Rate limit switched from default disabled to enabled (`enableRateLimit` parameter)
- `binance` futures was split into `binanceusdm` and the former stopped loading right fees in the context.

Caveat right now is that because of sequential versions it's super easy to screw up functionalities on seemingly small update. I noticed that #151 mentioned [semantic versioning](https://semver.org/) which differentiates breaking and non-breaking for quickly deciding backward compatibility of library. This'd make decision much faster for users on effort needed to upgrades. 
Would it be possible to adopt something similar practice for ccxt here?

**Comment by ttodua** [comment]
A late reply, but to add my thoughts, it's not easy to do that in a guaranteed way, as what update could be a major/minor/patch? for example, only changing binance, or say, huobi, would it be minor or major? 
or just changing a base function named 'costToPrecision', would it be minor (even though it affects all of exchange). So, i would say that semver might better be suitable as concept to each/specific exchange, as opposed to the whole lib (though, it's obvious that whole lib can have major updates, but i specifically mean where would be borderline to decide between patch/minor/major, as some 'patch' in base files might be a minor or even a major change affecting all exchange).
Though still a good idea.
