### ISSUE TITLE
availableWithoutBorrow balance

### ISSUE THREAD

**Issue by playerone2000** [ccxt/ccxt#9392]
For ftx api:
there is a key value call "availableWithoutBorrow" for get balances, but it is not currently included in the fetch_balance function as a key value.   This becomes problematic, if say I want to sell all the spot balance available without incurring a short position, if I use the "free" or "total" balance as a value to sell, it will include my available margin and will end up having a net short position.

Is there anyway to get just the spot balance available without including the margin available? Thank you

**Comment by playerone2000** [comment]
Is there anyway to get just the spot balance available without including the margin available?  Thank you

**Comment by playerone2000** [comment]
Just see that it is possible to get that by using the privateGetWalletBalances() to get customized result

**Comment by kroitor** [comment]
@playerone2000 you can that in three ways:

1. by accessing the `info` substructure in the balance response you get from ccxt (see https://github.com/ccxt/ccxt/wiki/Manual#balance-structure)
2.  it via `privateGetWalletBalances()` (see https://github.com/ccxt/ccxt/wiki/Manual#implicit-api)
3. or via `exchange.last_json_response` after your fetchBalance call

Hope that answers your question, let us know if not.
