### ISSUE TITLE
CEX.io  fetch_currencies_from_cache issue 

### ISSUE THREAD

**Issue by ttodua** [ccxt/ccxt#9397]
We get this issue with latest ccxt lib. Nothing more special info to provide, just plain load_markets() .

```
Fatal error: Uncaught TypeError: array_merge(): Argument #1 must be of type array, bool given in /.../ccxt-master/php/cex.php:175
Stack trace:
#0 /ccxt-master/php/cex.php(175): array_merge(true, Array)
#1 /ccxt-master/php/cex.php(182): ccxt\cex->fetch_currencies_from_cache(Array)
#2 /ccxt-master/php/Exchange.php(1708): ccxt\cex->fetch_currencies() 
```

(p.s. one-two month ago version didnt fire this issue. at this moment it's firing, i dont think that is because of executing from ["cached" exchange object](https://github.com/ccxt/ccxt/issues/9381).)

**Comment by kroitor** [comment]
@ttodua please, paste your version number and your verbose request/response.
