### ISSUE TITLE
Inconsistent Unified Api

### ISSUE THREAD

**Issue by Lindsor** [ccxt/ccxt#9398]
- OS: Mac OS Big Sur 11.4
- Programming Language version: Node 16.3.0
- CCXT version: 1.51.51

```
const kucoin = new ccxt.kucoin({
  apiKey: '<KEY>',
  secret: '<SECRET>',
  password: '<PASSWORD>',
});
kucoin.fetchBalance()
  .then(response => console.log(JSON.stringify(response)))
  .catch(console.error);

const bittrex = new ccxt.bittrex({
  apiKey: '<KEY>',
  secret: '<SECRET>',
});
bittrex.fetchBalance()
  .then(response => console.log(JSON.stringify(response)))
  .catch(console.error);
```

```
Kucoin Response:
{
  "info": {
    "code": "20000",
    "data": [... Accounts]
  }
}

Bittrex Response:
{
  "info": [... Accounts]
}
```

I expected the unified API's to have responses which have the same format, for Kicoin the info has a wrapper while for Bittrex the info is the accounts directly.

**Comment by kroitor** [comment]
The `info` substructure is not a part of the unified API – it contains the response from the exchange as is, untouched. So `info` is always exchange-specific. The purpose of `info` is to give you the access to the original unified response, if you need it. All other fields around `info` are unified:

This is documented in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#balance-structure
