### ISSUE TITLE
How can I set leverage for bybit 'USDT' Market?

### ISSUE THREAD

**Issue by ohhagi** [ccxt/ccxt#9407]
I tried below, but it's not work.

markets = exchange.load_markets()
market = exchange.market('ETH/USDT')
resp = bybit.user_post_leverage_save({
    'symbol': market['id'],
    'leverage': 10    #  leverage 
})

I guess 'user_post_leverage_save()' works on only ETH/USD market
I want to do it on 'USDT' market of bybit

plz help me

**Comment by p2828** [comment]
Same question. Any updates on this anyone?

**Comment by kroitor** [comment]
@p2828 @ohhagi we are upgrading the Bybit integration right now, will post a working here asap.

**Comment by p2828** [comment]
@kroitor waiting for the upgrade. tnx for your efforts bro.

**Comment by ttodua** [comment]
Bybit has now `async setLeverage (leverage, symbol = undefined, params = {})` method. you can use that.
Let us know if you have any issues
