### ISSUE TITLE
PHP Exception: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by ddyuriev** [ccxt/ccxt#9410]
- OS: windows10
- Programming Language version: PHP 7.3.9
- CCXT version: 1.51.63

```
        $ccxt = new \ccxt\bitstamp([]);
        $ccxt->fetch_currencies();
```

```
local.ERROR: count(): Parameter must be an array or an object that implements Countable {"exception":"[object] (ErrorException(code: 0): count(): Parameter must be an array or an object that implements Countable at C:\\projects\\alfarates\\vendor\\ccxt\\ccxt\\php\\bitstamp.php:390)
```

**Comment by kroitor** [comment]
@ddyuriev plz paste your verbose output:

```PHP
$exchange = new \ccxt\bitstamp();
$exchange->verbose = true;
$exchange->load_markets();
```

**Comment by ddyuriev** [comment]
> @ddyuriev plz paste your verbose output:
> 
> * https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
> 
> ```
> $exchange = new \ccxt\bitstamp();
> $exchange->verbose = true;
> $exchange->load_markets();
> ```

Array
(
    [0] => Request:
    [1] => GET
    [2] => https://www.bitstamp.net/api/v2/trading-pairs-info/
    [3] => Array
        (
            [User-Agent] => Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
        )

    [4] => 
)
Array
(
    [0] => Response:
    [1] => GET
    [2] => https://www.bitstamp.net/api/v2/trading-pairs-info/
    [3] => 0
    [4] => Operation timed out after 10000 milliseconds with 0 out of 0 bytes received
    [5] => Array
        (
        )

    [6] => 
)
it looks like access from my country is denied

**Comment by kroitor** [comment]
@ddyuriev Bitstamp may be blocking Russia and Asia, afaik. You will have to use a proxy for it or try from a different location. Closing it for now, feel free to reopen it or just ask further questions if any.
