### ISSUE TITLE
Is there a list of pairs for Kucoin that can be traded using the API?

### ISSUE THREAD

**Issue by AndrNic** [ccxt/ccxt#9411]
Hello!
Is there a list of pairs for Kucoin that can be traded using the API? For example, it is not possible to place an order for USDN-USDT and for other currencies with USDT, and ETH-BTC is possible.

**Comment by kroitor** [comment]
> For example, it is not possible to place an order for USDN-USDT and for other currencies with USDT, and ETH-BTC is possible.

Can you elaborate a bit? Your verbose output and your code would help pin it down: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

KuCoin says that USDN/USDT is tradeable:

<img width="908" alt="Screenshot 2021-06-18 at 17 42 52" src="https://user-images.githubusercontent.com/1294454/122578657-c2480300-d05c-11eb-9d78-079d21ef7c76.png">

CCXT says the same:

```
~/ccxt $ node examples/js/cli kucoin markets --table
Node.js: v14.15.4
CCXT v1.51.61
         limits |               precision | tierBased | percentage | taker | maker |              id |          symbol |     baseId | quoteId |       base | quote | active
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
...
[object Object] |  {"amount":4,"price":8} |     false |       true | 0.001 | 0.001 |         STX-BTC |         STX/BTC |        STX |     BTC |        STX |   BTC |   true
[object Object] |  {"amount":4,"price":4} |     false |       true | 0.001 | 0.001 |        STX-USDT |        STX/USDT |        STX |    USDT |        STX |  USDT |   true
[object Object] |  {"amount":4,"price":4} |     false |       true | 0.001 | 0.001 |       USDN-USDT |       USDN/USDT |       USDN |    USDT |       USDN |  USDT |   true
[object Object] |  {"amount":4,"price":6} |     false |       true | 0.001 | 0.001 |        XSR-USDT |        XSR/USDT |        XSR |    USDT |        XSR |  USDT |   true
[object Object] |  {"amount":4,"price":2} |     false |       true | 0.001 | 0.001 |       COMP-USDT |       COMP/USDT |       COMP |    USDT |       COMP |  USDT |   true
...
756 objects
~/ccxt $
```

**Comment by AndrNic** [comment]
Just checking. For all pairs, you can get various data: current prices, OrderBook for each pair, etc. But you will not be able to trade all of them. For example, you can't place a trading order for the USDN-USDT pair. Server response: 200
{'code': '900001', 'msg': 'Symbol [USDN-USDT] Not Exists'} And there are a lot of such pairs. On github, I have previously met the statement that no pairs with USDT can be traded. I looked at the other pairs ()USD (), Too, to trade will not work. But pairs with BTC, for example, ETH-BTC are successfully traded.

**Comment by kroitor** [comment]
@AndrNic CCXT does not decide which symbol is tradeable, it just takes the info from the exchange first-hand. So, if the exchange indicates that a symbol is available and tradeable, then you might want to forward your question to the exchange tech support.
