### ISSUE TITLE
New Exchange: Tokocrypto

### ISSUE THREAD

**Issue by ReynardoEW** [ccxt/ccxt#9413]
Hello,
Is it possible for CCXT to support Tokocrypto exchange?
Tokocrypto API doesn't differs much from Binance API or even it's pretty much the same because Tokocrypto is powered by Binance Cloud (that what they said on the website) here's the API Documentation https://www.tokocrypto.com/apidocs/

Thank You

**Comment by ReynardoEW** [comment]
I've been trying to request API access from Tokocrypto exchange but still haven't got the access yet, will try to give more information by trying to implement the API to CCXT when I got the API access

**Comment by faberkeping** [comment]
Hi! Any updates on this issue?

**Comment by diazidabagus** [comment]
Hi will Tokocrypto exchange be integrated to ccxt anytime soon?
https://www.tokocrypto.com/apidocs/#api-document-description

**Comment by kroitor** [comment]
Tokocrypto is available in CCXT 1.92.42+
