### ISSUE TITLE
Can't run TEST-ORDERS

### ISSUE THREAD

**Issue by Salz0** [ccxt/ccxt#9422]
- OS: W10
- Programming Language version: python 3.9.2
- CCXT version: 1.51.73

```



exchange = ccxt.binance({
        'enableRateLimit': True,  # https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
        'options': {
            'defaultType': 'margin'
        },
        "apiKey": os.environ.get(f"API_KEY{count}"),
        "secret": os.environ.get(f"API_SECRET{count}"),
        # 'verbose': True,
    })

exchange.create_order(amount=20, symbol='USDC/USDT', side='BUY', type='MARKET', 
params={"orderType": "margin", 'test': True})

```
This code just executes, no test mode Is on :/

Also would like to know if there is a way of doing test borrows

**Comment by kroitor** [comment]
The `test` parameter is not supported with Binance since API v1. It is not API v3.
The CCXT Manual documents which params are supported: https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

You can find all params supported by Binance for this or that endpoint here: 

- https://binance-docs.github.io/apidocs/spot/en/
- https://binance-docs.github.io/apidocs/spot/en/#new-order-trade

Alternatively, you can use the sandbox/testnet to test the API, though I'm not sure if it will work with the margin API:

```Python
exchange = ccxt.binance({
        'enableRateLimit': True,  # https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
        'options': {
            'defaultType': 'margin'
        },
        "apiKey": os.environ.get(f"API_KEY{count}"),
        "secret": os.environ.get(f"API_SECRET{count}"),
        # 'verbose': True,
    })

markets = exchange.load_markets()
exchange.set_sandbox_mode(True)
symbol = 'USDC/USDT'
type = 'market'
side = 'buy'
amount = 20
price = None
params = {
    # YOUR EXTRA PARAMS OVERRIDES HERE
}
exchange.create_order(symbol, type, side, amount, price, params)
```

Hope that helps, let us know if not.

**Comment by Salz0** [comment]
Hi, tried this out, returns None and doesn't execute

**Comment by Salz0** [comment]
> The `test` parameter is not supported with Binance since API v1. It is not API v3.
> The CCXT Manual documents which params are supported: https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params
> 
> You can find all params supported by Binance for this or that endpoint here:
> 
> * https://binance-docs.github.io/apidocs/spot/en/
> * https://binance-docs.github.io/apidocs/spot/en/#new-order-trade
> 
> Alternatively, you can use the sandbox/testnet to test the API, though I'm not sure if it will work with the margin API:
> 
> ```python
> exchange = ccxt.binance({
>         'enableRateLimit': True,  # https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
>         'options': {
>             'defaultType': 'margin'
>         },
>         "apiKey": os.environ.get(f"API_KEY{count}"),
>         "secret": os.environ.get(f"API_SECRET{count}"),
>         # 'verbose': True,
>     })
> 
> markets = exchange.load_markets()
> exchange.set_sandbox_mode(True)
> symbol = 'USDC/USDT'
> type = 'market'
> side = 'buy'
> amount = 20
> price = None
> params = {
>     # YOUR EXTRA PARAMS OVERRIDES HERE
> }
> exchange.create_order(symbol, type, side, amount, price, params)
> ```
> 
> Hope that helps, let us know if not.

Hi, tried this out, returns None and doesn't execute

**Comment by kroitor** [comment]
@Salz0 paste your verbose output plz: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```Python
exchange = ccxt.binance({
        'enableRateLimit': True,  # https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
        'options': {
            'defaultType': 'margin'
        },
        "apiKey": os.environ.get(f"API_KEY{count}"),
        "secret": os.environ.get(f"API_SECRET{count}"),
    })

markets = exchange.load_markets()
exchange.verbose = True  # ←------------------------ add this
exchange.set_sandbox_mode(True)
symbol = 'USDC/USDT'
type = 'market'
side = 'buy'
amount = 20
price = None
params = {}
exchange.create_order(symbol, type, side, amount, price, params)
```

**Comment by Salz0** [comment]
> @Salz0 paste your verbose output plz: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help
> 
> ```python
> exchange = ccxt.binance({
>         'enableRateLimit': True,  # https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
>         'options': {
>             'defaultType': 'margin'
>         },
>         "apiKey": os.environ.get(f"API_KEY{count}"),
>         "secret": os.environ.get(f"API_SECRET{count}"),
>     })
> 
> markets = exchange.load_markets()
> exchange.verbose = True  # ←------------------------ add this
> exchange.set_sandbox_mode(True)
> symbol = 'USDC/USDT'
> type = 'market'
> side = 'buy'
> amount = 20
> price = None
> params = {}
> exchange.create_order(symbol, type, side, amount, price, params)
> ```

```py
Traceback (most recent call last):
  File "C:\Users\korol\AppData\Roaming\JetBrains\PyCharm2021.1\scratches\scratch_9.py", line 41, in <module>
    exchange.create_order(symbol, type, side, amount, price, params)
  File "C:\Users\korol\AppData\Local\pypoetry\Cache\virtualenvs\ts-bot-4iVuk_MM-py3.9\lib\site-packages\ccxt\binance.py", line 2084, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "C:\Users\korol\AppData\Local\pypoetry\Cache\virtualenvs\ts-bot-4iVuk_MM-py3.9\lib\site-packages\ccxt\base\exchange.py", line 461, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Users\korol\AppData\Local\pypoetry\Cache\virtualenvs\ts-bot-4iVuk_MM-py3.9\lib\site-packages\ccxt\binance.py", line 3780, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\Users\korol\AppData\Local\pypoetry\Cache\virtualenvs\ts-bot-4iVuk_MM-py3.9\lib\site-packages\ccxt\base\exchange.py", line 481, in fetch2
    request = self.sign(path, api, method, params, headers, body)
  File "C:\Users\korol\AppData\Local\pypoetry\Cache\virtualenvs\ts-bot-4iVuk_MM-py3.9\lib\site-packages\ccxt\binance.py", line 3671, in sign
    raise NotSupported(self.id + ' does not have a testnet/sandbox URL for ' + api + ' endpoints')
ccxt.base.errors.NotSupported: binance does not have a testnet/sandbox URL for sapi endpoints

```

**Comment by kroitor** [comment]
> ccxt.base.errors.NotSupported: binance does not have a testnet/sandbox URL for sapi endpoints

That message says itself: you cannot use the sandbox with defaultType `'margin'`, there is no Binance testnet for that yet.

**Comment by Salz0** [comment]
> > ccxt.base.errors.NotSupported: binance does not have a testnet/sandbox URL for sapi endpoints
> 
> That message says itself: you cannot use the sandbox with defaultType `'margin'`, there is no Binance testnet for that yet. You can margin-trade via their production servers only. Let us know if that does not answer your question.

Got you, thanks

**Comment by Salz0** [comment]
@kroitor sorry for being somewhat annoying. I'm just trying to understand.

I have 25$ in my coinm wallet (Converted to BTC)

The market limit for BTC is 1, see:
```py
{'amount': {'max': 1000000.0, 'min': 1.0},
 'cost': {'max': None, 'min': None},
 'market': {'max': 100000.0, 'min': 1.0},
 'price': {'max': 1000000.0, 'min': 1000.0}}
```
How do I execute a 15$ order, if the min amount for BTC is 1? There must be something wrong.
There is no cost parameter.
Trying to do a market one

**Comment by Salz0** [comment]
> @kroitor sorry for being somewhat annoying. I'm just trying to understand.
> 
> I have 25$ in my coinm wallet (Converted to BTC)
> 
> The market limit for BTC is 1, see:
> 
> ```python
> {'amount': {'max': 1000000.0, 'min': 1.0},
>  'cost': {'max': None, 'min': None},
>  'market': {'max': 100000.0, 'min': 1.0},
>  'price': {'max': 1000000.0, 'min': 1000.0}}
> ```
> 
> How do I execute a 15$ order, if the min amount for BTC is 1? There must be something wrong.
> There is no cost parameter.
> Trying to do a market one

Got the limits by executing
```py
market = exchange.market('BTC/USD')
pprint(market['limits'])
```

**Comment by Salz0** [comment]
> > @kroitor sorry for being somewhat annoying. I'm just trying to understand.
> > I have 25$ in my coinm wallet (Converted to BTC)
> > The market limit for BTC is 1, see:
> > ```python
> > {'amount': {'max': 1000000.0, 'min': 1.0},
> >  'cost': {'max': None, 'min': None},
> >  'market': {'max': 100000.0, 'min': 1.0},
> >  'price': {'max': 1000000.0, 'min': 1000.0}}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > How do I execute a 15$ order, if the min amount for BTC is 1? There must be something wrong.
> > There is no cost parameter.
> > Trying to do a market one
> 
> Got the limits by executing
> 
> ```python
> market = exchange.market('BTC/USD')
> pprint(market['limits'])
> ```

Do I need a special type of order to do them with leverage?
So if I want x100 leverage with 1$, what do I need to do?
