### ISSUE TITLE
GateIO missing `watch_my_trades`

### ISSUE THREAD

**Issue by Matthias-Thul** [ccxt/ccxt#9424]
- OS: macOS 11.3.1
- Programming Language version: Python 3.9.5
- CCXT version: 1.51.83
- CCXT Pro version: 0.7.29

GateIO API supports a user trades channel (https://www.gate.io/docs/apiv4/ws/index.html#user-trades-channel). There is no corresponding `watch_my_trades` in CCXT Pro though.

**Comment by Matthias-Thul** [comment]
I realized that this is not as easy as adding `watch_my_trades`. Seems like GateIO upgraded their API from v2 to v4. CCXT is still on v2 and the user trades channel is only available in v4. So this will only be possible after https://github.com/ccxt/ccxt/issues/8306.

**Comment by carlosmiei** [comment]
Closing this issue, `watchMyTrades` is already available
