### ISSUE TITLE
CCXT Trading Fee Discounts!

### ISSUE THREAD

**Issue by kroitor** [ccxt/ccxt#9425]
Good news, everyone!

You might have noticed a new column on our list of exchanges:

<img width="899" alt="Screenshot 2021-06-22 at 01 01 38" src="https://user-images.githubusercontent.com/1294454/122840889-a87c1980-d303-11eb-8b79-f029a29682f1.png">

It shows trading fee discounts that you get if you sign up with the corresponding exchanges using CCXT's referral links by clicking on the exchange names in the list. That will not only give you a decent discount, but will also help develop this project.

We have started adding our referral links and trading fee discounts to those tables.
Some of the exchanges will offer discounts of 20% or more!

We will keep up our work towards better integrations and lower trading fees for the CCXT users )

Thank you for using this project,
CCXT Dev Team

**Comment by gittest2013** [comment]
How about TokoCrypto?

**Comment by kroitor** [comment]
@gittest2013 TokoCrypto is discussed here https://github.com/ccxt/ccxt/issues/9413

**Comment by lsheynova** [comment]
The fee goes to the developers of CCXT?

**Comment by kroitor** [comment]
@lsheynova part of the fee goes to the users as a discount, and the exchanges share the rest of it with the developers of CCXT.

**Comment by nds-hub** [comment]
Is there anyway to access these discounts if I have already signed up to the exchange?
