### ISSUE TITLE
compilation errors (missing modules) due to missing polyfills in webpack 5 (stream, http, https, constants, assert)

### ISSUE THREAD

**Issue by yeus** [ccxt/ccxt#9437]
ccxt makes use of automatic polyfills which were used in webpack  pre-5 in webpack 5 these polyfills got discarded
and ccxt needs to upgrade its dependencies to make it compatible with webpack5 again.

- OS: ubuntu 20.04
- Programming Language version: javascript
- CCXT version: 1.51.92

more info on how to reproduce the error can be found here:

https://github.com/quasarframework/quasar/issues/9780

**Comment by ttodua** [comment]
this issue should be fixed since then, if anyone still experiences some issue, let us know
