### ISSUE TITLE
Precision and limits when using quoteOrderQty with Binance

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#9438]
Hello,

I would like to use the `quoteOrderQty` param to trade with Binance because some of my market orders are rejected due to lack of funds. However I have few question when it comes to precision and limits.

- In regard to limit I assume that [amount min and max](https://ccxt.readthedocs.io/en/latest/manual.html#precision-and-limits) are for the base not the quote, so what is the best solution to check these conditions when using quote amounts ?
- In regard to precision, could you please tell me if the `decimalToPrecision` method could also help format quote amount to the required decimal precision ?

Thank you,

**Comment by Kinzowa** [comment]
From the [Binance documentation:](https://binance-docs.github.io/apidocs/spot/en/#change-log)

> Quote Order Qty MARKET orders will not break LOT_SIZE filter rules; the order will execute a quantity that will have the notional value as close as possible to quoteOrderQty.

Not sure I undertand correctly what "will not break LOT_SIZE filter rules" means here. Do you think like me that LOT_SIZE filter rules on base amount still apply ?

**Comment by kroitor** [comment]
> In regard to limit I assume that amount min and max are for the base not the quote, so what is the best solution to check these conditions when using quote amounts ?

Check `market['limits']['cost']['min']` it should contain the minimal cost in quote currency.

> In regard to precision, could you please tell me if the decimalToPrecision method could also help format quote amount to the required decimal precision ?

That is done automatically by CCXT here: https://github.com/ccxt/ccxt/blob/master/js/binance.js#L2083

> Do you think like me that LOT_SIZE filter rules on base amount still apply ?

Nope, in this case it's the other filter – '`MIN_NOTIONAL`.

Let us know if the above does not help or does not answer your question.

**Comment by Kinzowa** [comment]
Hi Igor,

Thank you for you answer this is precisely what I was wondering.
