### ISSUE TITLE
Feature request: Webhooks from Tradingview

### ISSUE THREAD

**Issue by dorienh** [ccxt/ccxt#9441]
If we can have a webhook listener to automate trades from Tradingview that would be amazing... 

#featurerequest

**Comment by gittest2013** [comment]
OK, I am already using trading view alerts to make ccxt trades and it WAS working great until this thread was started. Now a simple market order is taking 5 MINUTES to reach the exchange and it costing me REAL MONEY. If you have changed something, please change it back or advise me ASAP. Thankyou (emphasis added, it's real money). I have deleted a keep alive alert that was trigerring a script while doing nothing(?), only webhooks alerts to ccxt now from me are REAL TRADES, and five minute delays to the exchange from ccxt for a market order is ridiculous...

**Comment by kroitor** [comment]
@gittest2013 plz paste your versions, your codes and your verbose output: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by ttodua** [comment]
I don't think it will be implemented in CCXT (at least in the near future), as that can't fall in the scope of CCXT. Let me describe in two words:
- CCXT is fully-featured engine which can do anything you want, but it has unified schema which allows you to execute any desired set of action. 
- However, it doesn't have integrations with 3rd party services (which are not REST/WS exchanges), like IFTTT, Zapier, TradingView or any like. That is what a developer can build on top of CCXT. "Tradingview alerts" is not a static action , as in T/V alerts you set just whatever message you want to be sent, and that message can have any format (as there is no API or deterministic format of webhooks, and it comes in format of POST request method). In the past, I've had scripted something (for someone) which was getting alerts from T/V webhooks, but every alert have its distinctive format and, so on your hosting (VPS/DEDICATED/ETC) you/developer must build a custom script, which is solely  customized to parse the same alert scheme which was used by you on your T/V webhooks. I can't see any theoretical scenario, how "TradingView webhook" alerts can be integrated into CCXT.
- said that, of course, there might be some answer to the problem: you need an example how to build and host a script on custom server (which is 24/7 running and webserver is ready to accept incoming webhook format). however, depending on your parsed message, you/developer has to code the action to use **CCXT** to trigger any action (buy/sell/exit) with specific amount & price that your script has parsed.

I advise you might ask on TradingView Support, that they provided the example JS/PHP/PYTHON script which listens to some exemplary formatted webhooks. Then you can easily use any CCXT's exchange/method to do anything you want depending on incoming message.

Let us know if you have any specific issue/question related to ccxt.

**Comment by ttodua** [comment]
I will note, and in the future we might try to make some example scripts, which demonstrates how to do the process.
