### ISSUE TITLE
Bittrex missing `watch_my_trades`

### ISSUE THREAD

**Issue by Matthias-Thul** [ccxt/ccxt#9442]
- OS: macOS 11.3.1
- Programming Language version: Python 3.9.5
- CCXT version: 1.51.83
- CCXT Pro version: 0.7.29

Bittrex API supports a user trades channel (https://bittrex.github.io/api/v3#method-Execution). There is no corresponding `watch_my_trades` in CCXT Pro though.

**Comment by carlosmiei** [comment]
@ttodua closing this issue, that was implemented in the meantime
![image](https://user-images.githubusercontent.com/43336371/180612028-f1942305-9f3f-4c29-acc6-63545b3f21ca.png)
