### ISSUE TITLE
Module asyncio' has no attribute 'create_task'

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#9443]
Hello,

I use nested asynchronous loops to collect order books from markets of several wallets(spot, delivery, future) in Binance and I noticed that when the `while True` of all markets loops are `break` Python returns an error saying: 

`<Task finished coro=<update_account.<locals>.main() done, defined at /home/abc/python/app/trading/tasks.py:3017> exception=AttributeError("module 'asyncio' has no attribute 'create_task'",)`

I updated my code to Python 3.9 and tried another implementation of asyncio (with event) but unfortunnately I had to get back to version 3.6.9 because others modules in my code are not compatible with 3.9.

To be honnest I have no idea if this error is related to ccxtpro implementation of asyncio or if it's related to my environement or code. I wanted to share this because maybe other traders encounter the same "issue" with their code. 

Help would be greatly appreciated. 

```

import asyncio

# Markets loop
async def watch_book(client, market):

    while True:
        try:
            ob = await client.watch_order_book(market.symbol)
            
           if do_stuff(ob):
               do_more()
           else:
                  log.info('Closing stream {0}'.format(market.symbol))
                  break

            await client.sleep(1000)

        except Exception as e:
            traceback.print_exc()
            raise e


# Wallets loop
async def wallet_loop(loop, wallet):

    client = getattr(ccxtpro, exchange.exid)({'enableRateLimit': True, 'asyncio_loop': loop, })
    markets = get_markets(wallet)

    ws_loops = [watch_book(client, market) for market in markets]

    await asyncio.gather(*ws_loops)
    await client.close()

# Main loop
async def main(loop):

    wallets = get_wallets()
    wallet_loops = [wallet_loop(loop, wallet) for wallet in wallets]
    await asyncio.gather(*wallet_loops)

loop = asyncio.get_event_loop()
gp = asyncio.wait([main(loop)])
loop.run_until_complete(gp)
```

**Comment by Kinzowa** [comment]
Apparently it's related to my version of Python. Need an update to 3.7
https://stackoverflow.com/questions/53247533/attributeerror-module-asyncio-has-no-attribute-create-task

**Comment by frosty00** [comment]
can you try to update to the latest stable python - 3.8?

**Comment by Kinzowa** [comment]
> can you try to update to the latest stable python - 3.8?

Hi, I will try and let you know
