### ISSUE TITLE
issue with creating an order with bybit testnet

### ISSUE THREAD

**Issue by pnama** [ccxt/ccxt#9445]
bybit = ccxt.bybit(config={
    'apiKey': '',
    'secret': '',
    'enableRateLimit': True,
    'verbose': True,
})
bybit.set_sandbox_mode(True)

order = bybit.create_order(symbol="BTC/USDT", type="limit", amount=1, price=37000.0, side="sell")
print(order)

I have created an api-key though the testnet api management page. I wonder if I wrote the code not properly or it's something else.

-----------------------------gives me error(with bybit.set_sandbox_mode(True))-----------------------
ccxt.base.errors.ExchangeError: bybit {"ret_code":130021,"ret_msg":"oc_diff[47750], new_oc[4700] with ob[0]+AB[0]","ext_code":"","ext_info":"","result":null,"time_now":"162456932408","rate_limit_status":99,"rate_limit_reset_ms":1624569528,"rate_limit":100}

-----------------------------gives me error(witt bybit.set_sandbox_mode(False))-----------------------
ccxt.base.errors.AuthenticationError: bybit {"ret_code":10003,"ret_msg":"invalid api_key","ext_code":"","ext_info":"","result":null,"time_now":"16245.322193"}

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/9149

**Comment by climber2002** [comment]
This seems not a duplicate, the error code is different. I also got `ret_code` as 130021

**Comment by kroitor** [comment]
@clibmer2002 we are reworking the Bybit integration right now, hope to get it fixed before the end of next week.

**Comment by climber2002** [comment]
Thanks @kroitor . Currently I tried ccxt on bybit testnet account, the get balance always returns 0 even though I can get the correct balance when using `postman`. Thanks for your effort!

**Comment by kroitor** [comment]
@climber2002 if possible, please enable verbose mode before the fetch_balance call and paste your request+response here.

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by climber2002** [comment]
@kroitor I used ccxt `1.58.76`, seems the problem is v2 API of bybit. When I turn on verbose mode and call get balance API, it gave me following log

```
handleRestResponse:
 bybit GET https://api-testnet.bybit.com/v2/private/wallet/balance?api_key=BAEWMOMSOVGRTLDRXQ&recv_window=5000&timestamp=1635758074545&sign=1203ebd27da35be1265f43bf3fc7bf55fc43515c54dc5669164931c983d1f9bb 200 OK 
Response:
 {
  'Cache-Control': 'max-age=0, no-cache, no-store',
  Connection: 'keep-alive',
  'Content-Length': '1629',
  'Content-Type': 'application/json; charset=utf-8',
  Date: 'Mon, 01 Nov 2021 09:14:34 GMT',
  Expires: 'Mon, 01 Nov 2021 09:14:34 GMT',
  Pragma: 'no-cache'
} 
 {"ret_code":0,"ret_msg":"OK","ext_code":"","ext_info":"","result":{"BTC":{"equity":0,"available_balance":0,"used_margin":0,"order_margin":0,"position_margin":0,"occ_closing_fee":0,"occ_funding_fee":0,"wallet_balance":0,"realised_pnl":0,"unrealised_pnl":0,"cum_realised_pnl":0,"given_cash":0,"service_cash":0},"DOT":{"equity":0,"available_balance":0,"used_margin":0,"order_margin":0,"position_margin":0,"occ_closing_fee":0,"occ_funding_fee":0,"wallet_balance":0,"realised_pnl":0,"unrealised_pnl":0,"cum_realised_pnl":0,"given_cash":0,"service_cash":0},"EOS":{"equity":0,"available_balance":0,"used_margin":0,"order_margin":0,"position_margin":0,"occ_closing_fee":0,"occ_funding_fee":0,"wallet_balance":0,"realised_pnl":0,"unrealised_pnl":0,"cum_realised_pnl":0,"given_cash":0,"service_cash":0},"ETH":{"equity":0,"available_balance":0,"used_margin":0,"order_margin":0,"position_margin":0,"occ_closing_fee":0,"occ_funding_fee":0,"wallet_balance":0,"realised_pnl":0,"unrealised_pnl":0,"cum_realised_pnl":0,"given_cash":0,"service_cash":0},"USDT":{"equity":0,"available_balance":0,"used_margin":0,"order_margin":0,"position_margin":0,"occ_closing_fee":0,"occ_funding_fee":0,"wallet_balance":0,"realised_pnl":0,"unrealised_pnl":0,"cum_realised_pnl":0,"given_cash":0,"service_cash":0},"XRP":{"equity":0,"available_balance":0,"used_margin":0,"order_margin":0,"position_margin":0,"occ_closing_fee":0,"occ_funding_fee":0,"wallet_balance":0,"realised_pnl":0,"unrealised_pnl":0,"cum_realised_pnl":0,"given_cash":0,"service_cash":0}},"time_now":"1635758074.607141","rate_limit_status":119,"rate_limit_reset_ms":1635758074601,"rate_limit":120} 
```

The Postman uses endpoint `/spot/v1/account`, as following screenshot,
![Screenshot from 2021-11-01 20-21-42](https://user-images.githubusercontent.com/634687/139650266-255b9b61-db2f-4688-85ea-314973e0838e.png)

**Comment by ttodua** [comment]
A late reply here, unfortunately I couldn't catch this topic earlier, as the error was simple. The top post ( @pnama ) used correct approach/script and api keys, and the first error message (like `oc_diff[....], new_oc[....] with ob[...]+AB[...]`) means that there was not sufficient balance. Those exception errors are now implemented in CCXT and you can easily see the reason with exception type (i.e. `InsufficientFunds`).

So, there was no problem in CCXT, but the error was vague and it was the reason. 

about @climber2002 's issue - can you please re-try now? it should work as I've tested myself and it works. if you still have issues, feel free to ask, however, as @kroitor told you, please paste some demonstrational snippet you used, which shows how you initiate ccxt exchange class and use its methods.

**Comment by ZhangYou0122** [comment]
I encountered the same issue here on bybit testnet, calling bybit.create_order on BTC/USDT:USDT would give me the same error:

> ccxt.base.errors.InsufficientFunds: bybit {"ret_code":130021,"ret_msg":"oc_diff[236895165], new_oc[236895165] with ob[0]+AB[0]","ext_code":"","ext_info":"","result":null,"time_now":"1660855074.574028","rate_limit_status":99,"rate_limit_reset_ms":1660855074572,"rate_limit":100} 

However, the bybit testnet webpage shows that I have enough funds to place an order, and I have no problem in creating the same order on the webpage.

**Comment by Tasjas** [comment]
where is the solution
