### ISSUE TITLE
Binance market order in quote currency fails with MARKET_LOT_SIZE error

### ISSUE THREAD

**Issue by steveharrison** [ccxt/ccxt#9446]
Hey, I think I followed the [documentation on Market Buys](https://ccxt.readthedocs.io/en/latest/manual.html#market-buys) when I just want to specify how much UDST quote currency I want to spend, but I'm getting the following error when I run my script:

```
(node:46313) UnhandledPromiseRejectionWarning: InvalidOrder: binance order amount should be evenly divisible by lot size {"code":-1013,"msg":"Filter failure: MARKET_LOT_SIZE"}
```

I would expect this to simply go through, like when I put in 250 USDT in the Total field in the Binance UI.

I've read the documentation on Binance's API about lot sizes, but I don't understand how it relates to my use case here. Surely I should be able to specify any amount I wish and `ccxt` will convert it into x.xxxxxxx units of, say, BTC in this example? 

Here is my source code:

```
import ccxt from 'ccxt';
import credentials from './credentials.json';

try {
  (async () => {
    let binance = new ccxt.binance({
      apiKey: credentials.binance.key,
      secret: credentials.binance.secret,
      enableRateLimit: true,
      options: {
        createMarketBuyOrderRequiresPrice: false,
      }
    });

    const order = await binance.createMarketBuyOrder('BTC/USDT', 250);
    console.log(order);
  })();
} catch (error) {
  console.error(error);
}
```

- OS: macOS 11.2 (20D64)
- Programming Language version: Node v14.17.1 with `nvm`
- CCXT version: 1.51.73

**Comment by frosty00** [comment]
To make a quoteOrderQty order can you do this:

```
import ccxt
from pprint import pprint

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.binance({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': True,
})

markets = exchange.load_markets()

exchange.verbose = True  # comment/uncomment for debugging purposes

symbol = 'BTC/USDT'
type = 'market'
side = 'buy'  # or 'sell'
amount = 250  # in quote currency, how much USDT you want to spend for buying BTC
price = None
params = {
    'quoteOrderQty': amount,
}
order = exchange.create_order(symbol, type, side, amount, price, params)
pprint(order)
```
