### ISSUE TITLE
EdDSA signModified function uses an unnecessary operation

### ISSUE THREAD

**Issue by dvshur** [ccxt/ccxt#9447]
https://github.com/ccxt/ccxt/blob/master/js/static_dependencies/elliptic/lib/elliptic/eddsa/index.js#L56

Hello, it seems to me like the `key` variable created here is only used for `key.secret()` method calls. As far I understand, it does not transform the secret in any way, so those calls can be replaced by simply using an already existing variable `secret`.

Which basically means that the key itself is not used, and all operations on its creation are unnecessary. Please correct me if I'm wrong.

**Comment by ttodua** [comment]
old topic, now seems unrelated. closing for now, if anyone have any issues again, let us know
