### ISSUE TITLE
ftx.py fetch_markets

### ISSUE THREAD

**Issue by Hairdmin** [ccxt/ccxt#9448]
Hi all,

For the python file /ccxt/python/ccxt/ftx.py , 
When I call self.fetch_markets({'whatever': market}) with anything in params, I get all the information about all the assets. Is it normal?

For example, I use binance.py and I can specify a market in the same function to get only the information for this specify market like this: fetch_markets({'symbol': market}) where market is for example 'BTCUSDT'

Thanks you for your return.

Code execution:
return for self.fetch_markets({'whatever': market}) in ftx.py : 
I have all assets 

return for self.fetch_markets({'whatever': market}) in binance.py : 
ccxt.base.errors.BadRequest: binance {"code":-1104,"msg":"Not all sent parameters were read; read '0' parameter(s) but was sent '1'."}

**Comment by kroitor** [comment]
Hi!

First and foremost, whenever you see `params` – those are exchange-specific. They're not interchangeable between the exchanges. The `params` dictionary is propagated to the exchange "as is". Therefore, if you send something in `params`, make sure it is supported by the corresponding exchange:

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

Binance does support a filtering parameter:

- https://binance-docs.github.io/apidocs/spot/en/#exchange-information

FTX does not support that:

- https://docs.ftx.com/#get-markets

Hope that answers your question. Let us know if not.
