### ISSUE TITLE
Bittrex crash in parse_ohlcvs

### ISSUE THREAD

**Issue by stonemonk** [ccxt/ccxt#945]
Very similar to the issue I reported about Poloniex, I get periodic crashes in Bittrex:

```
TypeErrorccxt.base.exchange in parse_ohlcvs
object of type 'NoneType' has no len()
```

I haven't seen this at all the past month, but have gotten it twice in last 2 days on different symbols.

<img width="913" alt="screen shot 2017-12-23 at 3 53 22 pm" src="https://user-images.githubusercontent.com/5236934/34318408-7702020a-e7f9-11e7-8791-4bad692a47b0.png">

**Comment by janeCMD** [comment]
I also have issues with this late days, before it didn't happen very often. I believe its problem on bittrex side, they also started to be laggy about placing or canceling orders, i had to add much more sophisticated checks, its sort of 'kraken-like' behavior if you know what i am talking about :)

**Comment by kroitor** [comment]
Thank you for reporting this, I will look into it and will get back to you with fixes.

**Comment by kroitor** [comment]
@stonemonk can you please paste the code you use to reproduce the problem?
