### ISSUE TITLE
Rightbtc delisted ccxtpro failing to load with latest ccxt code

### ISSUE THREAD

**Issue by kefa8** [ccxt/ccxt#9464]
Hi,

ccxtpro is failing to load with the latest ccxt code. rightbtc has been removed it seems. 

any chance we can make the code more robust if exchanges are removed?
  
File "xxx\ccxt.pro\python\ccxtpro\__init__.py", line 130, in <module>
    from ccxt.async_support.rightbtc import rightbtc                          # noqa: F401
ModuleNotFoundError: No module named 'ccxt.async_support.rightbtc'

**Comment by frosty00** [comment]
good point )

you need to either update your ccxtpro or run `cd ccxt.pro; node build/export-exchanges.js`

**Comment by kroitor** [comment]
@kefa8 please, upgrade your CCXT and CCXT Pro to the most recent versions (1.52.4 and 0.7.40 respectively)  – that should fix it. Let us know if that does not help. Thanks for your feedback!
