### ISSUE TITLE
Kucoin watchOHLCV() Support

### ISSUE THREAD

**Issue by quantumpacket** [ccxt/ccxt#9465]
- Programming Language version: Python 3.9.2
- CCXT Pro version: 0.7.39

I was wondering if we could get support for `watchOHLCV()` for the Kucoin exchange. According to https://docs.kucoin.com/#klines the websockets API supports the Klines channel, which provides:

- open price
- high price
- low price
- close price
- transaction volume
- transaction amount

This is available in the intervals: 1min, 3min, 15min, 30min, 1hour, 2hour, 4hour, 6hour, 8hour, 12hour, 1day, 1week

The ccxt.pro Kucoin class says `watchOHLCV` is "missing on the exchange side". That was 17 months ago, and if I am correct the Klines channel was added around 10 months ago.

Thank you for your time, and great product.

**Comment by kroitor** [comment]
@quantumpacket watchOHLCV added to KuCoin in CCXT Pro 0.7.41+, thx for your feedback!
