### ISSUE TITLE
How to place a Take profit and Stop Loss on Phemex

### ISSUE THREAD

**Issue by Gabriele-Sabatino** [ccxt/ccxt#9467]
Hello I would like to place an order on Phemex Contracts with a stoploss and a take profit.
How can I specify theses params ?
What is the correct writing ?

**Comment by carlosmiei** [comment]
Hello @Gabriele-Sabatino, please check out this snippet where an order with `takeProfit` and `stopLoss` prices is created: 

```Python
import ccxt # noqa: E402

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.phemex({
    'enableRateLimit': True,
	'apiKey': 'YOUR_API_KEY',
	'secret': 'YOUR_SECRET',
	'options': {
	'defaultType': 'swap',
	},
})
amount = 20
symbol = 'BTC/USD:USD'
exchange.create_order(symbol, 'market', 'buy', amount, None, {'stopLossPrice': 5000, 'takeProfitPrice': 100000})
```

You can also see the complete example here:  https://github.com/ccxt/ccxt/blob/master/examples/py/phemex-open-cancel-close-positions.py#L53
