### ISSUE TITLE
Signature for this request is not valid - while executing fapiPrivateDeleteBatchOrders ( fapi.binance.com/fapi/v1/batchOrders )

### ISSUE THREAD

**Issue by kodekeep4r** [ccxt/ccxt#9469]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows 10
- Programming Language version: Python 3.9.0
- CCXT version:  1.51.95

```

import calendar;
import time;
import math
import ccxt  # noqa: E402

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.binance({
    'verbose': True ,
    'adjustForTimeDifference': True,
    'enableRateLimit': True, # required https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
    'options': {
        'defaultType': 'future',
        'adjustForTimeDifference': True,
        'recvWindow': 5000,		# ←---- resolves the timestamp
    },
})

def ts():
    current_datetime = datetime.now(timezone.utc)
    timestamp = datetime.timestamp(current_datetime)*1000    
    return math.floor(timestamp)

def delete_batch_orders(symbol,orders):
    done = exchange.fapiPrivateDeleteBatchOrders({'symbol':symbol,
										'origClientOrderIdList':orders,										
										'timestamp': ts()})
        


to_be_deleted = ["take_profit_1","take_profit_2","take_profit_3"]
d = delete_batch_orders('BTCUSDT',to_be_deleted)


```
CCXT Version: 1.51.95

Request: DELETE https://fapi.binance.com/fapi/v1/batchOrders?timestamp=1624921365466&recvWindow=5000&symbol=BTCUSDT&origClientOrderIdList=['take_profit_1',+'take_profit_2',+'take_profit_3']&signature=mysignature {'X-MBX-APIKEY': 'mykey', 'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate'} None

Response: DELETE https://fapi.binance.com/fapi/v1/batchOrders?timestamp=1624921365466&recvWindow=5000&symbol=BTCUSDT&origClientOrderIdList=['take_profit_1',+'take_profit_2',+'take_profit_3']&signature=mysignature 400 {'Content-Type': 'application/json', 'Content-Length': '63', 'Connection': 'keep-alive', 'Date': 'Mon, 28 Jun 2021 23:02:46 GMT', 'Server': 'Tengine', 'X-MBX-USED-WEIGHT-1M': '1', 'x-response-time': '0ms', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 ac979e099d122e39d3a8fac95688a69a.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'AMS50-C1', 'X-Amz-Cf-Id': 'E-Sx0Mj4xPaj8YXy6poqUVF7OdUzIBAlTqJTM22zFEqezyRBdGcm3g=='} {"code":-1022,"msg":"Signature for this request is not valid."}
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\ccxt\base\exchange.py", line 593, in fetch
    response.raise_for_status()
  File "C:\Python39\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://fapi.binance.com/fapi/v1/batchOrders?timestamp=1624921365466&recvWindow=5000&symbol=BTCUSDT&origClientOrderIdList=%5B'take_profit_1',+'take_profit_2',+'take_profit_3'%5D&signature=mysignature

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xx\Documents\quick.py", line 86, in <module>
    d = delete_batch_orders('BTCUSDT',to_be_deleted)
  File "C:\Users\xx\Documents\quick.py", line 79, in delete_batch_orders
    done = exchange.fapiPrivateDeleteBatchOrders({'symbol':symbol,
  File "C:\Python39\lib\site-packages\ccxt\base\exchange.py", line 461, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Python39\lib\site-packages\ccxt\binance.py", line 3846, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "C:\Python39\lib\site-packages\ccxt\base\exchange.py", line 482, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Python39\lib\site-packages\ccxt\base\exchange.py", line 609, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:\Python39\lib\site-packages\ccxt\binance.py", line 3840, in handle_errors
    self.throw_exactly_matched_exception(self.exceptions, error, feedback)
  File "C:\Python39\lib\site-packages\ccxt\base\exchange.py", line 500, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.AuthenticationError: binance {"code":-1022,"msg":"Signature for this request is not valid."}```

*******************

Dear ccxt users, 

I'm facing this issue while trying to batch delete orders. All other commands work fine, like, placing an order, closing a position, querying pending orders, etc... only this one is causing me issues.

I've tried also with         

'recvWindow': 50000,		# ←---- resolves the timestamp

Commands like this one below, work without issues:
 
trades = exchange.fapiPrivate_get_openorders({'symbol': 'BTCUSDT','timestamp': ts()})																

Any hint? Thanks!!

**Comment by kodekeep4r** [comment]
Found the solution. It was really tricky. Hope this question helps others. Quote needs to be url encoded

Solution:
ids = ["take_profit_1","take_profit_2","take_profit_3"]
from urllib.parse import quote
from json import dumps

idsString = dumps(ids).replace(" ", "")
idsString = quote(idsString)

print(idsString)

**Comment by kroitor** [comment]
@kodekeep4r thanks for reporting back, we appreciate it!

**Comment by hendrixCrypto** [comment]
can work even without idsString = dumps(ids).replace(" ", ""), just applying quote on top works well for me too.
