### ISSUE TITLE
Question: What is the best way to handle a large number of exchange instances with different api keys in ccxt.pro?

### ISSUE THREAD

**Issue by koftyan** [ccxt/ccxt#9470]
Hello. I have a question about working with ccxt.pro. I need to run about 1000 WebSocket watchers with different api keys(on different exchanges) to watch personal trades and balance updates.
For now, if I run 1000 of exchange instances I came up with about 6GB consume of RAM and a lot of network requests(if I understand correctly, each instance loads markets for first time). I use code like this to run thousand watchers:

```Node.js
const apiKeys = getThousandApiKeys();
const exchanges = apiKeys.map(apiKey => new ccxtpro['binance'](paramsWithDifferentApiKeys)); // There might be another exchange
const watchers = exchanges.map(exchange => watchTrades(exchange));
await Promise.all(watchers);
```

```Node.js
// Watch function
async function watchTrades(exchange) {
  while(true) {
    try {
      const trades = await exchange.watchMyTrades();
      // handle trades somehow
    } catch(e) {
      // retry
    }
  }
}
```

I can cache markets for each type of exchange, and then use 
```exchange.setMarkets(cachedMarkets)```
for each of 1000 instances, it reduces count of network requests, but not solves memory consume.

If I set markets to empty object
```exchange.setMarkets({})```
for each of 1000 instances, it reduces memory consume. But I think that it can broke internal work of ccxt.pro.
What can happen if I set markets to empty object? I am asking this because when I set markets to {} ```exchange.watchMyTrades()``` still works, but I don't know is there any guaratees that it will work at long distance as expected.

Is there any way to correctly handle this situation and reduce size of memory consume and network requests?
What limitations may be encountered when implementing such an approach?
Thanks!

- OS: Different(Macos, Linux)
- Programming Language version: Node.js 14.x
- CCXT.PRO version: 1.50.x

**Comment by darkfennertrader** [comment]
Use message brokers like Kafka by Confluent ( https://developer.confluent.io/get-started/python/ )  to manage such massive qty of data. It requires a little experience with it (there are plenty of cheap and very good courses on Udemy) that explains how to setup local kafka clusters using docker). This is how I deal with thousands of websockets. Then you can use  the Confluent kafka-python wrapper to extract data from kafka and make your processing.

**Comment by ttodua** [comment]
@darkfennertrader thank you for your input, it gives us good directions about infrastructure.

@koftyan , as a second thought, i might suggest you a simple hack which will achieve what you want. Basically, it is a trick to make that 1000 individual exchange instances used one same shared 'markets' objects. The below is phseudo-code (for NodeJs) and you should actually build the logic depending your needs/logic:

- make a global scope dictionary, which hold exchange names, like:  
```
global.marketsContainer= { 'binance': null, 'bittrex':null };
```
- override the `setMarkets()` method to force it to visit that global-scope variable, to see that markets are set there, i.e.:
```
const binance = new ccxt.binance({...});
if (global.marketsContainer['binance'] === null) {
    await binance.loadMarkets();
    global.marketsContainer['binance'] = binance.markets;
} else {
    binance.markets = global.marketsContainer['binance'];
}
```

and try if that might do the trick, so all of 'binance' instances will use same 'binance's object (likewise will behave other exchanges, so there will be one markets object per exchange, be it 1000 instances). again, 've not tested the real code build on above phseudo-code, but it might give you directions and it might need slight modifications. if that will not help, you might override, maybe [`setMarkets`](https://github.com/ccxt/ccxt/blob/17af09191be9309fe52b1dabb1603d5609fd3b57/js/base/Exchange.js#L847), like:
```
binance.setMarketsOriginal = binance.setMarkets;
binance.setMarkets= function(markets, currencies=undefined) {
    // here set them from global-scope variable, i.e.
    if (global.marketsContainer[this.id] === null ){
         // your codes
         return whatever;
    } else {
        return this.setMarketsOriginal;
    }
};
```
So, try to think a bit outside-of-the-box to make some custom approach to achieve you goal.

As a last nore, (even though it rarely happens) once in a day (or watch for BadSymbol exception) re-load markets, to recognize if there has been added a new pair on exchange (which might have not been active when you initially loaded markets).

If you have any issues with CCXT, let us know.

**Comment by ttodua** [comment]
related: https://github.com/ccxt/ccxt/issues/9744
