### ISSUE TITLE
Add a new endpoint to Bitget

### ISSUE THREAD

**Issue by bongkook** [ccxt/ccxt#9471]
Dear ccxt teams,

We would appreciate it if you could add the endpoint below to Bitget.
POST /api/swap/v3/trace/closeTrackOrder

I look forward to your reply
Thank you.

**Comment by kroitor** [comment]
@bongkook added in CCXT 1.52.7, the new build will arrive in ~20 minutes. Thanks for your feedback!

**Comment by bongkook** [comment]
Thank you for your quick response.
Post is correct, not Get method.
Please change to Post.
Thank you.

**Comment by kroitor** [comment]
@bongkook pardon, my bad, pushed another fix, it will be available in 1.52.8 shortly. Thank you for pointing it out!

**Comment by bongkook** [comment]
A very big thanks for all your help!
