### ISSUE TITLE
Double-size of memory wasting

### ISSUE THREAD

**Issue by ttodua** [ccxt/ccxt#9476]
When we save data (as you might remember, I had a question about caching of $exchange object). However, when `serialize($exchange)` works well to save into file, the file-size is doubled, because we see there are two-properties with same data in every exchange object.

For example, try
```
$exchange = new  ..coinbase();
$exchange->load_markets();
file_put_contents('.../sample', serialize($exchange) );
```
The file size is up to 20 MB.  Reasonably big to server that from/to memory . However, when we checked, we found that most of the data are stored with two different properties, i.e. `markets_by_id` (which contains tons of data), and same data is also being stored in memory with the key `marketsById`.   

Please do something, so one property was just reference to another property (which will hold the true data) and not both properties taking quite considerable memory (either cached or in RAM).

**Comment by kroitor** [comment]
Yeah, unfortunately, PHP copies arrays by values as opposed to copying them by reference in other languages. We will address this. Thanks for your involvement!

**Comment by ttodua** [comment]
my bad, other properties are not being saved double-times. only marketsById. 

that simple fix will reduce memory usage two-times

**Comment by ttodua** [comment]
@kroitor thanks for being so fast :)) 
Well, could it be referenced to closure/function, so it didn't took that much memory ?  I also am not sure, maybe (if other properties are being used only once) why that "markets by id" has two versions? maybe it can be trimmed down to one variation (i.e.  `currencies_by_id` does not have `currenciesById`). 
actually, what I try is to reduce the object size from unnecessary datas, and `marketsById` seems perfect thing that should be removed to lighten-up the data. 
Thanks!

**Comment by kroitor** [comment]
> Well, could it be referenced to closure/function, so it didn't took that much memory ? 

We already do that with functions, apparently, we also have to do the same for properties. The current solution is not ideal, since it hardcodes transpiled methods, we will rework that.

- https://github.com/ccxt/ccxt/blob/master/php/Exchange.php#L2487

> I also am not sure, maybe (if other properties are being used only once) why that "markets by id" has two versions? maybe it can be trimmed down to one variation (i.e. `currencies_by_id` does not have `currenciesById`).

This is for historical reasons, mostly, I don't think we can reduce it without breaking the backward-compatibility, but it can be addressed via the `__call` method. 

> actually, what I try is to reduce the object size from unnecessary datas, and `marketsById` seems perfect thing that should be removed to lighten-up the data.

That is all reasonable. One possible workaround would be to exclude one of the two versions from serialization, and then restore it upon deserialization. In the meantime we will try to remove the duplication.

**Comment by ttodua** [comment]
> One possible workaround would be to exclude one of the two versions from serialization, and then restore it upon deserialization. In the meantime we will try to remove the duplication.
Yes, you are exact! thanks.

**Comment by frosty00** [comment]
I think that we should remove support for one of either `markets_by_id` or `marketsById`

**Comment by ttodua** [comment]
@frosty00  generally, that might be correct route in everything. two same things might even cause more confusion, that advantage. At this moment there are many references throughout the library for those two ones, but the another one might be replaced with `markets_by_id`  (  `currencies_by_id` is also named in underscores, but idk, you can decide better. )
