### ISSUE TITLE
Poloniex: fetchOrder not implemented

### ISSUE THREAD

**Issue by brandsimon** [ccxt/ccxt#9477]
On the poloniex exchange there is no fetch order implemented.
I looked through the API doc but have not found a way to obtain this data reliable.
Any ideas?

**Comment by qyvlik** [comment]
Try this

```js
const poloniex = new ccxt.poloniex({...});
poloniex.privatePostReturnOpenOrders({
    currencyPair: 'BTC_ETH'
});
```

[returnOpenOrders](https://docs.poloniex.com/#returnopenorders)

**Comment by brandsimon** [comment]
@kroitor 
If I implement this method with maximum two API calls (`returnOrderStatus` and `returnOrderTrades`), would it get merged?

**Comment by kroitor** [comment]
@brandsimon we have had fetchOrder with just one call `fetchOpenOrders` with the orders cache, but we have stripped it out, since it was quite buggy on the edge-cases.

**Comment by brandsimon** [comment]
@kroitor Interesting. Do you think, my proposed solution would work or would also be buggy on edge cases?
Not having `fetchOrder` makes the exchange quite useless to me. I would implement my solution in ccxt, or if it would not get merged, in my own project.

**Comment by kroitor** [comment]
@brandsimon you might want to check how we emulated fetchOrder before:

- https://github.com/ccxt/ccxt/blob/f4ca54f62e5a72ba78435cc1fe9bddd5c9669668/js/poloniex.js#L994
- https://github.com/ccxt/ccxt/issues/96
- https://github.com/ccxt/ccxt/pull/102

Also, Poloniex now has a true (non-emulated) `fetchOpenOrder` (single order).

**Comment by kroitor** [comment]
Also:

- https://github.com/ccxt/ccxt/issues/6227
- https://github.com/ccxt/ccxt/pull/6239

**Comment by brandsimon** [comment]
@kroitor 
Thank you for the clarification.
My approach would have been to app `fetchClosedOrder` based on `returnOrderTrades`.
Then in `fetchOrder` I wanted to do this:
```
try:
    return self.fetch_open_order(id, symbol, params)
catch OrderNotFound:
    return self.fetch_closed_order(id, symbol, params)
```

I understand that this is not wanted due to two api calls.
So I would still merge `fetchClosedOrder` to ccxt, but do the try ... catch on my side.
Any thoughts on this?

**Comment by kroitor** [comment]
> So I would still merge fetchClosedOrder to ccxt, but do the try ... catch on my side.
> Any thoughts on this?

That makes sense, however, i'm not sure if it's possible to restore all the info from returnOrderTrades.

**Comment by brandsimon** [comment]
Merged.

Btw, my pseudo code above was incorrect.
As stated here: https://docs.poloniex.com/#returnorderstatus
If both methods throw, the order was cancelled and not filled.
