### ISSUE TITLE
RuntimeError: Precise class initiated with something other than a string or int

### ISSUE THREAD

**Issue by Gabriele-Sabatino** [ccxt/ccxt#9479]
Hello, I keep getting the error; RuntimeError: Precise class initiated with something other than a string or int. My code is able to run perfectly fine on my local machine but when I attempt to run it on Google cloud Platform I get the error. Any help would be greatly appreciated.

![Screen Shot 2021-06-29 at 10 40 40 PM](https://user-images.githubusercontent.com/50143943/123900013-455b3a00-d936-11eb-8b2a-ebc74d49733e.png)
![Screen Shot 2021-06-29 at 11 13 07 PM](https://user-images.githubusercontent.com/50143943/123900014-455b3a00-d936-11eb-8e8a-43d6a6b98f8e.png)
![Screen Shot 2021-06-29 at 11 13 13 PM](https://user-images.githubusercontent.com/50143943/123900015-455b3a00-d936-11eb-80c9-1988425fbe0c.png)

**Comment by frosty00** [comment]
@Gabriele-Sabatino you need to pass strings to the functions to_ep instead of floats

you can do this:

```
Long_take = phemex.to_ep(str(last * 1.01), market)
Long_stop = phemex.to_ep(str(last * 0.99), market)
```

**Comment by frosty00** [comment]
now after this pr your `to_ep` code should also work with floats
