### ISSUE TITLE
New Exchange : CoinEx

### ISSUE THREAD

**Issue by jimako1989** [ccxt/ccxt#948]
Hi, I love this product ccxt.
Could you include this new exchange from HongKong?
Their API can be found here.
https://github.com/coinexcom/coinex_exchange_api/wiki

**Comment by jjhesk** [comment]
looks like a promising ex

**Comment by kroitor** [comment]
@Deathamns has uploaded the initial implementation of CoinEx in the above pull-request, If anyone would like to help us implement their private API – your contributions are welcome!

**Comment by dhensen** [comment]
Is this the same as https://www.coinexchange.io ?

**Comment by Deathamns** [comment]
https://www.coinex.com/ Not likely.
