### ISSUE TITLE
Incorrect fees loaded in Binance futures

### ISSUE THREAD

**Issue by SITZ** [ccxt/ccxt#9483]
```
- OS: macOS 11.4
- Programming Language version: Python 3.9
- CCXT version: 1.52.16
```

Fees (maker /taker) for futures seem to be loaded incorrectly for Binance client in market data and reflecting spot instead.

![Screenshot 2021-06-30 at 14 01 11](https://user-images.githubusercontent.com/356043/123957507-28614e00-d9ac-11eb-96f9-9e7b3f4117e5.png)

**Comment by frosty00** [comment]
0.004 and 0.002 is the correct future fee though...
