### ISSUE TITLE
Catch balance doesn't work

### ISSUE THREAD

**Issue by FireEath** [ccxt/ccxt#9489]
Hi, I'm trying to catch the total balance of my FTX's account, I've do it successful on python but I still can't get it to work in php.
I am trying to get the total balance for a website so on a server.

Except that after trying all the codes I found, after reading the manual and the examples you provided, I still can't get my balance

I find ccxt a wonderful idea for anyone in my genre who wants to develop things in the crypto world, thanks for the work you provide.

Do you have any clue on how to use ccxt in php to get very simple information.
Below is a simple authentication script that doesn't work in php :{
And my python's script who work but useless :(
```
<?php
date_default_timezone_set('UTC');

$exchange = new \ccxt\ftx(array(
    'apiKey' => 'MY_API_KEI',
    'secret' => 'MY_SECRET',
    'verbose' => true,
    'enableRateLimit' => true,
));

?>

from functools import total_ordering
from logging import info
import ccxt
import json
from ccxt.base import exchange 
import pandas as pd


apiKey = "MY_API_KEI"
secretApi = "MY_SECRET"

exchange = ccxt.ftx({
    'apiKey' : apiKey , 'secret' : secretApi , 'enableRateLimit' : True
})

pair = "BNB/USDT"
r1 = json.dumps(exchange.fetch_ticker(pair))
rit = json.loads(r1)

pi1 = json.dumps(exchange.fetch_total_balance())
pit = json.loads(pi1)

TOTAL = (pit['USDT']) + (pit['USD']) + ((pit['BNB']) * rit['last']) #I don't sucess to catch the full balance in usd so I took all my assets for have they values.

print(TOTAL)


```

```
Can't / doesn't know how to see the Error, because I see if the script work directly on my web page
```

**Comment by ttodua** [comment]
Please use the current up-to-date version of ccxt, the past issue should be fixed, and you would be able to do what you were trying to do. The past issue should be fixed. 
Also, in next cases, please read the following - https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help  to read what we need to understand your issue. Otherwise, "doesn't work" without providing those required details, we can't help much.

**Comment by ttodua** [comment]
Let us know if you still have any issues with CCXT.
