### ISSUE TITLE
Disable unified naming

### ISSUE THREAD

**Issue by FedererKK** [ccxt/ccxt#9490]
ccxt version: 1.52.23 

Hello,

I am looking to disable unified naming as it might induce inconsistencies in our tools, for example Bitmex will soon implement spot markets and BTC/USD would then refer to the spot markets, while right now it is used to refer to XBTUSD (perpetual swap).

I am looking for a way to override the unified naming function (and use the proper symbol as per the exchange) such that calling the method below 

```
symbol  = "XBTUSD",
bitmex.create_order(symbol, type, side, amount, price=None, params={}
```

would not result in the error below

```
ccxt.base.errors.ExchangeError: bitmex No market symbol XBTUSD
```

but successfully place the order, thanks.

**Comment by kroitor** [comment]
The unified function you might want to override is `fetchMarkets` (for a specific exchange) or `setMarkets` (for all exchanges). In particular, you want to redefine the `symbol` property of a market:

- https://github.com/ccxt/ccxt/wiki/Manual#market-structure
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/binance.py#L1085
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/exchange.py#L1311

You can override those methods with a subclass or by passing to exchange constructor directly.

Hope that answers your question, let us know if not.
