### ISSUE TITLE
Binance wapiGetSubAccountAssets will be discontinued On August 01, 2021 02:00 AM UTC

### ISSUE THREAD

**Issue by savomir84** [ccxt/ccxt#9492]
Hi, thank you for this great library :), maybe I am wrong but I think that CCXT library currently supports wapiGetSubAccountAssets implicit API call but that call will be deprecated as of August 01. According to the Binance documentation as of August 01 GET /sapi/v3/sub-account/assets should be used instead of GET /wapi/v3/sub-account/assets.html. 

https://www.binance.com/en/support/announcement/f45dde7da58b473aa885349946bed269

Is it possible that you include that change in one of next releases?

**Comment by kroitor** [comment]
@savomir84 hi! Yes, we will add that asap! Thx for your feedback!
