### ISSUE TITLE
New Exchange: Bitvo

### ISSUE THREAD

**Issue by ron7684** [ccxt/ccxt#9495]
Official Website:
https://www.bitvo.com/

Official API:
Testnet: wss://apibitvostage.cdnhop.net/WSGateway/
Production: wss://apibitvoprod.alphapoint.com/WSGateway/

API Documents:
https://alphapoint.github.io/slate/

Bitvo uses AlphaPoint which is the same whitelabel exchange software as NDAX.io (already in ccxt) so I would think it is an easy addition.

**Comment by ron7684** [comment]
Looking at the situation I realize NDAX is implemented with their REST API.

Would adding an exchange with only a ws API be acceptable?

**Comment by kroitor** [comment]
@ron7684 CCXT (MIT) does not support WS, however, CCXT Pro does: 

- https://ccxt.pro
- https://github.com/ccxt/ccxt/issues/56
- https://github.com/ccxt/ccxt/issues/6543

**Comment by ron7684** [comment]
I have a license for CCXT Pro but it seems that the classes there are all extended from the CCXT classes with REST APIs. Is an exchange without a REST API suitable for ccxt pro?

**Comment by kroitor** [comment]
@ron7684 we do support AlphaPoint's REST API which is almost identical to the WS API. If the exchange is an implementation of AlphaPoint, then it will most likely support the same interfaces. We have not tested yet, though.

**Comment by ron7684** [comment]
#9782

**Comment by ttodua** [comment]
dead exchange
