### ISSUE TITLE
phemex/ccxt websocket support

### ISSUE THREAD

**Issue by adamrg73** [ccxt/ccxt#9496]
Is there support in ccxt for websocket support?  Im having issues with retrieving orders theyre telling me they did some updates so the history of orders is not right, but he is going to fix it for me etc... and recommended using websocket im noticing for other issues as well..but they only have some java code, id prefer to use python and/or ccxt if possible..
thanks

**Comment by kroitor** [comment]
CCXT itself is REST-only, MIT license, free. We do support Phemex's WebSocket API in CCXT Pro, which is a commercial proprietary license with paid access: https://ccxt.pro

- https://github.com/ccxt/ccxt/wiki/ccxt.pro.manual#exchanges

More info about CCXT Pro and more answers to the licensing questions here: https://github.com/ccxt/ccxt/issues/6543
