### ISSUE TITLE
Do createLimit methods influence on rateLimit?

### ISSUE THREAD

**Issue by dimoff66** [ccxt/ccxt#9497]
I can not get this information: if createOrder methods reduce rateLimit? 
I think they should not, it would be senceless

**Comment by kroitor** [comment]
The exchanges usually track (IP + API Key + Account). The rate limit is applied to all requests, some of them may cost more than other requests. All types of requests affect your rate limiter count. Hope that answers your question, let us know if not.

**Comment by dimoff66** [comment]
Thanks, seems strange since orders are something which helps exchanges earn money, but okay, i will try to ask exchanges directly about cost of each operation. Thanks!

**Comment by kroitor** [comment]
> i will try to ask exchanges directly about cost of each operation

You don't have to. It's documented in their API docs. You can find links to all exchanges' docs in this table: https://github.com/ccxt/ccxt#supported-cryptocurrency-exchange-markets

**Comment by dimoff66** [comment]
> > i will try to ask exchanges directly about cost of each operation
> 
> You don't have to. It's usually documented in their API docs. You can find links to all exchanges' docs in this table: https://github.com/ccxt/ccxt#supported-cryptocurrency-exchange-markets

In binance docs is written "_Every request will contain X-MBX-USED-WEIGHT-(intervalNum)(intervalLetter) in the response headers which has the current used weight for the IP for all request rate limiters defined._"

Is there are any access in ccxt api to such information or may be intention to provide it in future?

**Comment by kroitor** [comment]
> Is there are any access in ccxt api to such information or may be intention to provide it in future?

You can access those headers with CCXT after issuing your call, in exchange.last_response_headers.
We are also working towards a better unification of that aspect.

**Comment by dimoff66** [comment]
I got. Thank you so much!
