### ISSUE TITLE
Multithreading/multiprocessing orders

### ISSUE THREAD

**Issue by serteikas** [ccxt/ccxt#9499]
Hello

I am currently looking to process many orders in the fastest way possible (mostly market orders). 

I intend to use a Python multithreading/multiprocessing approach for this. How feasible is it via CCXT? Has it been done before? Is there something I should know beforehand? Maybe there are better approaches/suggestions?

Thanks.

**Comment by Salz0** [comment]
Have you heard of asynchronous programming?

**Comment by serteikas** [comment]
@Salz0 Yes, of course. But I would also want an explanation as to why asyncio would be the preferred option over multi-threading or multiprocessing.

For each order, I expect to place an order, retrieve order information, perform calculations and construct data structures, load it into the database and repeat the process in parallel.

**Comment by kroitor** [comment]
@serteikas CCXT is implemented in:
- JavaScript, single-threaded native async concurrency
- Python, despite supporting threads it's single-threaded in GC, has native async concurrency
- PHP, also supports threads and has support for async concurrency

With the modern async/await approach you can do everything you would do with threads, and more. Managing concurrent execution is much more flexible. You can find examples and docs here:

- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/tree/master/examples
