### ISSUE TITLE
Close position in Hedge mode by side

### ISSUE THREAD

**Issue by mortezafouladi** [ccxt/ccxt#9505]
Hello,

I am looking for a way to close my take profit and stop-loss orders on Binance in hedge mode by their side. I tried the cancel_all_orders function however this function closes both close long and close short orders.

Is there any way to specify a side parameter for the cancel_all_order function?

**Comment by kroitor** [comment]
Hi!

> Is there any way to specify a side parameter for the cancel_all_order function?

No, afaik, Binance does not have it: https://binance-docs.github.io/apidocs/futures/en/#cancel-all-open-orders-trade
Looks like you will have to cancel specific orders by their ids.

Hope that answers your question.

**Comment by mortezafouladi** [comment]
I solved my problem through this code, I hope I was done it the right way.

`$open_orders = $exchange->fetchOpenOrders($symbol);
                    foreach ($open_orders as $open_order) {
                        if ($open_order['side'] == '$side') {
                            $exchange->cancelOrder($open_order['info']['orderId'], $symbol);
                        }
                    }`

**Comment by kroitor** [comment]
This is a bit more generic:

```PHP
$open_orders = $exchange->fetchOpenOrders($symbol);
foreach ($open_orders as $open_order) {
    if ($open_order['side'] == "$side") {
        $exchange->cancelOrder($open_order['id'], $symbol);
    }
}
```
