### ISSUE TITLE
Cryptopia - fetch_order() OrderNotCached

### ISSUE THREAD

**Issue by ricardodinucci** [ccxt/ccxt#951]
Hello,

I am trying to run 

$o = createLimitBuyOrder($m, $v, $p);

fetch_order($o['id'], $c);

Why you request the public function filter_by_since_limit() in Exchange.php line 1097?

After this call the result in fetch_orders() cryptopia.php line 509 lost the id and the fetch_order return throw new OrderNotCached ($this->id . ' order ' . $id . ' not found in cached .orders, fetchOrder requires .orders (de)serialization implemented for this method to work properly');

Why you have fetch_order and fetch_orders?

Look attached report.

Thanks.

- OS: Ubuntu
- Programming Language: PHP 7.1.1
- CCXT version: 1.10.459
- Exchange: Cryptopia
- Method: fetch_order()

$o = createLimitBuyOrder($m, $v, $p);

fetch_order($o['id'], $c);

**Comment by kroitor** [comment]
Hi!

> Why you request the public function filter_by_since_limit() in Exchange.php line 1097?

It filters the orders by `since` and `limit` params, that were added not so long ago. The purpose of the filtering is consistency across all exchanges, even the ones that don't support output-limiting params.

> After this call the result in fetch_orders() cryptopia.php line 509 lost the id and the fetch_order return throw new OrderNotCached ($this->id . ' order ' . $id . ' not found in cached .orders, fetchOrder requires .orders (de)serialization implemented for this method to work properly');

This indicates a bug in the above logic, I will fix it and will let you know when it's there. Thank you for reporting this.

> Why you have fetch_order and fetch_orders?

-` fetch_order`: fetch one order by id
- `fetch_orders`: fetch all (multiple) orders

**Comment by kroitor** [comment]
What is your value of $c ?

**Comment by kroitor** [comment]
@ricardodinucci does this work:

```PHP
$exchange = '\\ccxt\\cryptopia';
$exchange = new $exchange (array (
    'enableRateLimit' => true,
));
$symbol = 'ETH/BTC';
$amount = 0.01;
$price = 0.04;
$result = $exchange->create_limit_buy_order ($symbol, $amount, $price);
$order = $exchange->fetch_order ($result['id'], $symbol);
var_dump ($order);
```

?

**Comment by Pmant** [comment]
related to #660 ?

**Comment by kroitor** [comment]
@Pmant most likely, but it's hard to tell, from the posted code (too short).
