### ISSUE TITLE
Binance POST /sapi/v1/sub-account/universalTransfer signature issue

### ISSUE THREAD

**Issue by savomir84** [ccxt/ccxt#9511]
Hi,

I am testing following endpoint https://binance-docs.github.io/apidocs/spot/en/#sub-account-transfer-history-for-sub-account and I am getting "code":-1022,"msg":"Signature for this request is not valid.".

CCXT calls https://api.binance.com/sapi/v1/sub-account/universalTransfer with following parameters:
timestamp=1625494903406&recvWindow=5000&fromEmail=_________&toEmail=__________&fromAccountType=SPOT&toAccountType=SPOT&asset=BTC&amount=0.01&signature=__________

I googled this error message and I found official Binance post https://dev.binance.vision/t/faq-signature-for-this-request-is-not-valid/176 . As you can see they say that order of parameters is important and that timestamp and signature should be at the end.

**Comment by kroitor** [comment]
@savomir84 please, paste the code you use to reproduce it.

**Comment by savomir84** [comment]
Hello @kroitor, thank you for your quick reply :) .

I have tested this API call with following code:

$exchange_class = "\\ccxt\\binance";

$exchange_class_settings = [
	'verbose' => true, // uncomment for debugging
	'timeout' => 30000,
	'enableRateLimit' => true,  // required! https://github.com/ccxt/ccxt/wiki/Manual#rate-limit,
        'apiKey' => "________________________________________",
        'secret' => "_________________________________________"
];

$api = new $exchange_class($exchange_class_settings);

//api->set_sandbox_mode(true);

$api->check_required_credentials(); // throws AuthenticationError

$params = [];
$params['fromEmail'] = urlencode('trader1_virtual@noemail.com');
$params['toEmail'] = urlencode('fundwallet_virtual@noemail.com');
$params['fromAccountType'] = 'SPOT';
$params['toAccountType'] = 'SPOT';
$params['asset'] = 'BTC';
$params['amount'] = 0.01;
$params['timestamp'] = round(microtime(true) * 1000);

$api_response = $api->sapiPostSubAccountUniversalTransfer($params);

and I am getting following response:

Array ( [0] => Request: [1] => POST [2] => https://api.binance.com/sapi/v1/sub-account/universalTransfer [3] => Array ( [X-MBX-APIKEY] => _____________________________ [Content-Type] => application/x-www-form-urlencoded ) [4] => timestamp=1625645114357&recvWindow=5000&fromEmail=trader1_virtual%40noemail.com&toEmail=fundwallet_virtual%40noemail.com&fromAccountType=SPOT&toAccountType=SPOT&asset=BTC&amount=0.01&signature=________________________ ) Array ( [0] => Response: [1] => POST [2] => https://api.binance.com/sapi/v1/sub-account/universalTransfer [3] => 400 [4] => [5] => Array ( [Content-Type] => application/json;charset=UTF-8 [Content-Length] => 63 [Connection] => keep-alive [Date] => Wed, 07 Jul 2021 08:05:14 GMT [Server] => nginx [Strict-Transport-Security] => max-age=31536000; includeSubdomains [X-Frame-Options] => SAMEORIGIN [X-Xss-Protection] => 1; mode=block [X-Content-Type-Options] => nosniff [Content-Security-Policy] => default-src 'self' [X-Content-Security-Policy] => default-src 'self' [X-WebKit-CSP] => default-src 'self' [Cache-Control] => no-cache, no-store, must-revalidate [Pragma] => no-cache [Expires] => 0 [X-Cache] => Error from cloudfront [Via] => 1.1 ac979e099d122e39d3a8fac95688a69a.cloudfront.net (CloudFront) [X-Amz-Cf-Pop] => AMS50-C1 [X-Amz-Cf-Id] => FCSbI64TEOprmCOn6h-bdkK_ROPP0FJ0yMmc_W_TigrRlzm8rbKhsA== ) [6] => {"code":-1022,"msg":"Signature for this request is not valid."} )

**Comment by kroitor** [comment]
@savomir84 have you tried it without urlencoding the emails and without the `timestamp` parameter (it is handled in ccxt)?

Assuming your version is up to date (1.52.60+, plz upgrade if yours is older), what do you see:

```PHP
$exchange_class = "\ccxt\binance";

echo "CCXT v." . \ccxt\Exchange::VERSION . "\n";

$exchange_class_settings = [
'apiKey' => "________________________________________",
'secret' => "_________________________________________"
];

$api = new $exchange_class($exchange_class_settings);

//api->set_sandbox_mode(true);

$api->check_required_credentials(); // throws AuthenticationError

$markets = $api->load_markets();

$api->verbose = true; // after loading the markets

$params = [];
$params['fromEmail'] = 'trader1_virtual@noemail.com';
$params['toEmail'] = 'fundwallet_virtual@noemail.com';
$params['fromAccountType'] = 'SPOT';
$params['toAccountType'] = 'SPOT';
$params['asset'] = 'BTC';
$params['amount'] = 0.01;

$api_response = $api->sapiPostSubAccountUniversalTransfer($params);
```

**Comment by savomir84** [comment]
@kroitor it works now :), thank you very much, I removed urlencode() and I am not getting that error message anymore.
