### ISSUE TITLE
What would be secure way to save and load ccxt.binance() object in Python

### ISSUE THREAD

**Issue by avatar-lavventura** [ccxt/ccxt#9512]
- OS: `Ubuntu 20.04.2 LTS`
- Programming Language version:  `Python 3.8.10`
- CCXT version: `ccxt==1.52.40`

---------

This is a design question on Python end. I am just looking a proper way to secure `binance.exchange()` object that is authenticated using `api_key` and `api_secret`.

I am using `ccxt.binance()` to login into my Binance account and do some trading operations using `api_key` and its `secret`. Even I have disabled money transfer operations in Binance end, an attacker with bad intentions could do random tradings to losing all the money in the account. I was just looking a proper way to secure `binance.exchange()` object.

In order to save `binance.exchange()` object , I am using `pickle`.

```python
import ccxt
import pickle

ops = {"apiKey": api_key, "secret": api_secret, "options": {"adustForTimeDifference": True}}
exchange = ccxt.binance(ops)

_file = ".secret.pk"
with open(_file, "wb") as f:
    pickle.dump(exchange, f, pickle.HIGHEST_PROTOCOL)
```

-----

Afterwards, on my future usages, I just load the object instead of providing my `api_key` and `api_secret` again.

```python
import pickle

_file = ".secret.pk"
with open(_file, "rb") as f:
    exchange = pickle.load(f)

exchange.create_market_buy_order(...)
```

Would it be safe to save and load an object that has access to the trading account using `pickle.save()` and `pickle.load()`? If not, what would be safer ways to secure an object? During run time could `exchange` object read from an attacker and could be used?

**Update**: I observe that, when saved `pickle` object is loaded it returns empty object. Hence I have to do authentication again.

  [1]: https://github.com/ccxt/ccxt#python-1

**Comment by ttodua** [comment]
late reply here, but a broader (not specific) note would be - everything that is run on that device, can be read if that device is compromised. Though, that is common sense that as harder you will make process, the more energy will be needed to be spent by attacker. So it depends on the magnitude of attack - if you are targeted by someone, as if someone knew that you had millions in your account, then he will do all efforts, and can dump out you all your files and secret codes too. (also, if someone can access your running instance, then he can see anything (keys, secret,..) and it doesnt matter how you loaded it. )
However, if you are afraid by a random person, just accidentally accessing your VPS/device without having no specific clues and without thoroughly reading your script, then "obscurity" might well. the more obscurity, "the better" (however again, note that "security through obscurity" is not a real security and is not globally accommodated standard. the best thing to do is to safeguard your device (firewall/AV/ whatever) to avoid any break/hack. 
If you are afraid of the hosting itself (where you host it)  then you might change the hosting to other reliable provider. 
so, if you decide that obscurity is ok in your case, then yeah, you just use any compatible library (i am not familiar with pickle, but theoretically, i dont know why it couldnt save authorization keys...) should work (save & load the object without any problems).
let us know if you have any issue/questions related to CCXT.
