### ISSUE TITLE
count(): Argument #1 ($value) must be of type Countable|array

### ISSUE THREAD

**Issue by ttodua** [ccxt/ccxt#9513]
Just a cosmetic issue: Once in every X requests , liquid `fetch_tickers` throws exception:
```
 PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, string given in ccxt-master/php/liquid.php:583
ccxt-master/php/liquid.php(583): count()
ccxt\liquid->fetch_tickers()
```
exactly same happens in lbank. should it be handled or that is expected behavior if response is bad from their server?

**Comment by kroitor** [comment]
@ttodua hi! Can you please post your verbose response? That would help add a handler to it.
