### ISSUE TITLE
include vwap in OHLCV API

### ISSUE THREAD

**Issue by nerddan** [ccxt/ccxt#9516]
Many exchanges (such as Binance and BitMEX) have a "vwap" column in their OHLCV API, which is unfortunately abandoned in CCXT. Many institutions use vwap in their trading strategies, and I believe it is also important to many traders.

Is there a workaround to get the vwap data?

**Comment by kroitor** [comment]
> Many exchanges (such as Binance and BitMEX) have a "vwap" column in their OHLCV API, which is unfortunately abandoned in CCXT.

I don't see a vwap column with Binance OHLCV API here:

- https://binance-docs.github.io/apidocs/spot/en/#kline-candlestick-data
- https://binance-docs.github.io/apidocs/futures/en/#kline-candlestick-data
- https://binance-docs.github.io/apidocs/delivery/en/#kline-candlestick-data

BitMEX has it here:

- https://www.bitmex.com/api/explorer/#!/Trade/Trade_getBucketed

> Is there a workaround to get the vwap data?

Yes, you can override the parseOHLCV / parse_ohlcv method with subclassing just like you would do with any other OOP class in JS/Py/PHP.

```Python
import ccxt

class MyBitmex(ccxt.bitmex):
    def parse_ohlcv(self, ohlcv, market=None):
        #
        #     {
        #         "timestamp":"2015-09-25T13:38:00.000Z",
        #         "symbol":"XBTUSD",
        #         "open":237.45,
        #         "high":237.45,
        #         "low":237.45,
        #         "close":237.45,
        #         "trades":0,
        #         "volume":0,
        #         "vwap":null,
        #         "lastSize":null,
        #         "turnover":0,
        #         "homeNotional":0,
        #         "foreignNotional":0
        #     }
        #
        return [
            self.parse8601(self.safe_string(ohlcv, 'timestamp')),
            self.safe_number(ohlcv, 'open'),
            self.safe_number(ohlcv, 'high'),
            self.safe_number(ohlcv, 'low'),
            self.safe_number(ohlcv, 'close'),
            self.safe_number(ohlcv, 'volume'),
            self.safe_number(ohlcv, 'vwap'),  # add it somewhere here
        ]


def table(values):
    first = values[0]
    keys = list(first.keys()) if isinstance(first, dict) else range(0, len(first))
    widths = [max([len(str(v[k])) for v in values]) for k in keys]
    string = ' | '.join(['{:<' + str(w) + '}' for w in widths])
    return "\n".join([string.format(*[str(v[k]) for k in keys]) for v in values])


bitmex = MyBitmex()
candles = bitmex.fetch_ohlcv('BTC/USD')
print(table(candles))
```

**Comment by nerddan** [comment]
Thank you very much for replying! I didn't know it is possible to override a method in Python!

Just saying, in Binance API, "Quote asset volume" divided by "Volume" is "vwap".

**Comment by Smartromain** [comment]
> Thank you very much for replying! I didn't know it is possible to override a method in Python!
> 
> Just saying, in Binance API, "Quote asset volume" divided by "Volume" is "vwap".

correct, do you know if we can get upper and lower vwap bands from api somewhere on binance?
