### ISSUE TITLE
Bitmart failing to load contract markets

### ISSUE THREAD

**Issue by orientsun6** [ccxt/ccxt#9519]
- OS: MacOS
- Programming Language version: Python 3.7.4
- CCXT version: 1.52.46

```
xch = ccxt.bitmart()
depth = exch.fetch_order_book('BTC/USDT')
```

```
ExchangeError: bitmart {"errno":"OK","message":"CLOUD_SYSTEM_ERROR[I/O error on GET request for \"https://api.***.cloud/v1/ifcontract/contracts\": api.***.cloud; nested exception is java.net.UnknownHostException: api.***.cloud]","code":49999,"trace":"d7e85e1b-c8d7-4c2c-8293-56f9ed520427","data":{}}
```

**Comment by kroitor** [comment]
> Bitmart calling contracts api for spot orderbook

It does not call contracts for spot orderbooks, the exception happens in `loadMarkets()`, that is documented here: https://github.com/ccxt/ccxt/wiki/Manual#loading-markets . As documented in the Manual, all unified calls will preload the markets once, if you don't load them manually.

```Python
xch = ccxt.bitmart()

try:
    markets = exchange.load_markets()
except Exception as e:
    print('Failed to load markets with exception:', type(e).__name__, str(e))

try:    
    depth = exch.fetch_order_book('BTC/USDT')
except Exception as e:
    printf('Filed to fetch the orderbook:', type(e).__name__, str(e))
```

The question is why the endpoint stopped working, will get that resolved. Thx for reporting!

**Comment by trasmus3** [comment]
Same issue here
OS Fedore 34
Python 3.9.5
CCXT 1.52.53

notice that https://api-cloud.bitmart.com/contract/v1/ifcontract/contracts return
{"errno":"OK","message":"CLOUD_SYSTEM_ERROR[I/O error on GET request for \"https://api.***.cloud/v1/ifcontract/contracts\": api.***.cloud; nested exception is java.net.UnknownHostException: api.***.cloud]","code":49999,"trace":"2d8f573b-6fa1-4513-9fe4-1da7d2e94319","data":{}}

But V2 https://api-cloud.bitmart.com/contract/v2/ifcontract/contracts return
{"message":"Not found","code":30000,"trace":"f3ac6ddb-5b81-46e2-b522-91f10a99e961","data":{}}

problem/change at Bitmart ?

**Comment by kroitor** [comment]
@orientsun6 @trasmus3 thx for your feedback, we will fix it as soon as we can!

**Comment by 11101171** [comment]
@kroitor The spot API and the contract API are now invoked together. In this way, if BitMart maintains the contract API, the spot API cannot be invoked. Could you please call the contract API and the spot API separately.

**Comment by kroitor** [comment]
@11101171 yes, we will add a workaround for that, hopefully, very soon.

**Comment by 11101171** [comment]
I think this is a temporary decision by BitMart that the interface will be completely unusable in the near future.

**Comment by adeel94mirza** [comment]
https://developer-pro.bitmart.com/en/contract/

Is this relevant?

**Comment by adeel94mirza** [comment]
@kroitor Thanks for the quick fix to this issue! I want to mention that after this I started getting error that CPC/USDT is not a valid symbol. Its because the loadMarkets function now returns it as CPCoin/USDT instead of CPC/USDT. I just wanted to put it here so others may be informed

**Comment by kroitor** [comment]
@adeel94mirza 

> I want to mention that after this I started getting error that CPC/USDT is not a valid symbol. Its because the loadMarkets function now returns it as CPCoin/USDT instead of CPC/USDT. I just wanted to put it here so others may be informed

That is documented in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#naming-consistency
- https://github.com/ccxt/ccxt/wiki/Manual#notes-on-naming-consistency
- https://github.com/ccxt/ccxt/blob/master/js/bitmart.js#L300
