### ISSUE TITLE
[okex5] possible bug in market orders - is price really required?

### ISSUE THREAD

**Issue by npomfret** [ccxt/ccxt#9523]
Regarding: `InvalidOrder: okex5 createOrder() requires the price argument with market buy orders to calculate total order cost (amount to spend), where cost = amount * price. Supply a price argument to createOrder() call if you want the cost to be calculated for you from price and amount, or, alternatively, add .options['createMarketBuyOrderRequiresPrice'] = false and supply the total cost value in the 'amount' argument or in the 'sz' extra parameter (the exchange-specific behaviour)...`

Looking at the docs (https://www.okex.com/docs-v5/en/#rest-api-trade) it looks like buy market orders don't require a price.  It says `px ... Only applicable to limit order.`

**Comment by kroitor** [comment]
It is documented in the CCXT docs and you can control its behaviour if you follow what the error message literally. OKEX market-buys require a cost. 

- https://github.com/ccxt/ccxt/wiki/Manual#market-buys
- https://github.com/ccxt/ccxt/blob/master/js/okex5.js#L1288

Hope that answers the question, let us know if not.

**Comment by npomfret** [comment]
Sorry, I wasn't clear.  I *think* that the v5 api doesn't need this - you can just specify a buy side market order as normal... at least that's how I've interpreted the docs.

**Comment by kroitor** [comment]
@npomfret you can check that by scanning through all occurrences of "buy" in the OKEX v5 API docs:

- https://www.okex.com/docs-v5/en/#rest-api-trade-place-order

<img width="1089" alt="Screenshot 2021-07-07 at 19 17 50" src="https://user-images.githubusercontent.com/1294454/124795004-4acd0b80-df58-11eb-987c-8eae0b16f09c.png">
<img width="1095" alt="Screenshot 2021-07-07 at 19 19 01" src="https://user-images.githubusercontent.com/1294454/124795023-502a5600-df58-11eb-97a4-af4c7fe2bb42.png">

**Comment by npomfret** [comment]
Theres nothing here (https://www.okex.com/docs-v5/en/#rest-api-trade) that indicates you need to treat buy orders differently.  Have you tried just removing that code to see if it works?  I will try later if not

**Comment by kroitor** [comment]
> Theres nothing here (https://www.okex.com/docs-v5/en/#rest-api-trade) that indicates you need to treat buy orders differently.

You just have to scroll a bit, cause it's a longer section of the doc, the indication is highlighted on this screenshot:

<img width="1082" alt="Screenshot 2021-07-08 at 11 29 26" src="https://user-images.githubusercontent.com/1294454/124889563-e3f33500-dfdf-11eb-9780-b4cb712a784a.png">

**Comment by npomfret** [comment]
sorry - I totally missed that
