### ISSUE TITLE
Bitmart return "This service is down"

### ISSUE THREAD

**Issue by mustapha1509** [ccxt/ccxt#9526]
OS: MacOS
    Programming Language version: Python 3.7.4
    CCXT version: 1.52.46

```
ccxt.base.errors.ExchangeError: bitmart {"errno":"OK","message":"This service is down","code":1000,"trace":"","data":{}}
```

After Bitmart announced that its API has been updated, ccxt cannot fetch the order book, but if I try this url it works fine

```
https://api-cloud.bitmart.com/spot/v1/symbols/book?symbol=BTC_USDT
```

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/9519
