### ISSUE TITLE
I'm trying to contribute, but confused as to how self.privateGetOrdersId(...) works

### ISSUE THREAD

**Issue by dmastylo** [ccxt/ccxt#953]
For example, in `gdax.py` the `fetch_order` method is implemented as follows:
```
def fetch_order(self, id, symbol=None, params={}):  
    self.load_markets()                             
    response = self.privateGetOrdersId(self.extend({
        'id': id,                                   
    }, params))                                     
    return self.parse_order(response)               
```

Where is the declaration/implementation of the `self.privateGetOrdersId(...)` method?

**Comment by kroitor** [comment]
See `define_rest_api`, explained here: https://github.com/ccxt/ccxt/issues/237#issuecomment-332354313

**Comment by kroitor** [comment]
@dmastylo let us know if you have any other questions.

**Comment by dmastylo** [comment]
Makes sense to me, thanks
