### ISSUE TITLE
Cannot fetch Market or Balance

### ISSUE THREAD

**Issue by Gabriele-Sabatino** [ccxt/ccxt#9531]
Hello, so I can’t seem to load the balance or markets of any symbol except BTC on Phemex testnet account. Was wondering if anyone can help thx. Using verbose I get the following:

<img width="842" alt="Screen Shot 2021-07-08 at 1 45 08 PM" src="https://user-images.githubusercontent.com/50143943/124967866-e57a2880-dff2-11eb-9aeb-4b3b0e025999.png">

**Comment by kroitor** [comment]
@Gabriele-Sabatino hi! Please, paste your code and your verbose output: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by Gabriele-Sabatino** [comment]
After using verbose I get the following:

<img width="842" alt="Screen Shot 2021-07-08 at 1 45 08 PM" src="https://user-images.githubusercontent.com/50143943/124967933-02aef700-dff3-11eb-8e3f-246741f63b72.png">

**Comment by kroitor** [comment]
@Gabriele-Sabatino please, do this and paste your output here as [markdown text](https://guides.github.com/features/mastering-markdown/) (don't paste text as images):

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```Python
import ccxt

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.phemex()
exchange.verbose = true
markets = exchange.load_markets()
```

↑ paste your output here using github markdown, plz.

**Comment by Gabriele-Sabatino** [comment]
import ccxt
import config



phemex = ccxt.phemex({
'enableRateLimit': True,
'options': {
    'defaultType': 'swap',  
},
'apiKey': config.API_KEY,
'secret': config.API_SECRET,
'password': config.PASSWORD,
'urls': {
        'api': 'https://testnet.phemex.com/'
    }


})





phemex.urls['api'] = phemex.urls['test']




def trade_crypto(request):

    data = request.get_json()



    tickers = {

    'BTCUSDT': 'BTC/USDT',
    'BTCUSD': 'BTC/USD',
    'DOTUSDT': 'DOT/USDT',
    'DOTUSD': 'DOT/USD',
    'ADAUSDT': 'ADA/USDT',
    'ADAUSD': 'ADA/USD',
    'ETHUSDT': 'ETH/USDT',
    'ETHUSD': 'ETH/USD',
    'LTCUSD': 'LTC/USD',
    'LTCUSDT': 'LTC/USDT',
    }

    ticker = tickers[data['ticker']]


    phemex.verbose = True
    balance = phemex.fetch_balance({'code': 'ETH'})

    return str(balance['info']['data']['positions']) 

-->OUTPUT:


Request: GET https://testnet-api.phemex.com/accounts/accountPositions?currency=ETH {'x-phemex-access-token': '0f4dba73-fbc3-408f-a419-4908365509ec', 'x-phemex-request-expiry': '1625773133', 'x-phemex-request-signature': '2ced64af0d12240b8e06fcf19b30e01239fb5fa4537932e64d6f6be8fac6c7b1', 'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://testnet-api.phemex.com/accounts/accountPositions?currency=ETH 500 {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '45', 'Connection': 'keep-alive', 'Date': 'Thu, 08 Jul 2021 19:37:54 GMT', 'Set-Cookie': 'AWSALB=wCOg5JTnNfewTCEDGferuDniYre050Y3iNmDnYqj/OOgXozH70bTwpQhKqr8FdyNMviH27vsqmCw9yY6dVe0YatrYwRheFT7kATWB1m7mV8t2p5x8Hxqm4kWfydj; Expires=Thu, 15 Jul 2021 19:37:54 GMT; Path=/, AWSALBCORS=wCOg5JTnNfewTCEDGferuDniYre050Y3iNmDnYqj/OOgXozH70bTwpQhKqr8FdyNMviH27vsqmCw9yY6dVe0YatrYwRheFT7kATWB1m7mV8t2p5x8Hxqm4kWfydj; Expires=Thu, 15 Jul 2021 19:37:54 GMT; Path=/; SameSite=None, cookiesession1=678A3E11HIJKUV012345689890125820;Expires=Fri, 08 Jul 2022 19:37:54 GMT;Path=/;HttpOnly', 'Server': 'nginx', 'x-phemex-request-tracing': '6491a176-8698-4c5a-a080-9e66061f5774', 'X-RateLimit-Remaining-CONTRACT': '499', 'X-RateLimit-Capacity-CONTRACT': '500', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 4074a79e28cc4b1a455d24b3546c6c94.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'YTO50-C2', 'X-Amz-Cf-Id': 'UmpwwZ9VPl7BVhkeYDgNY19rK8c7eQpsziQz7GK-h2XiYbg514IADg=='} {"msg":"Please try again later","code":10500}
192.168.219.61 - - [08/Jul/2021 15:37:54] "POST / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/gabrielmyers/<Pythoners>/<Genv>/lib/python3.8/site-packages/ccxt/base/exchange.py", line 593, in fetch
    response.raise_for_status()
  File "/Users/gabrielmyers/<Pythoners>/<Genv>/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://testnet-api.phemex.com/accounts/accountPositions?currency=ETH

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gabrielmyers/<Pythoners>/<Genv>/lib/python3.8/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/gabrielmyers/<Pythoners>/<Genv>/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/gabrielmyers/<Pythoners>/<Genv>/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/gabrielmyers/<Pythoners>/<Genv>/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/gabrielmyers/<Pythoners>/<Genv>/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/gabrielmyers/<Pythoners>/<Genv>/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/gabrielmyers/<Pythoners>/<Genv>/lib/python3.8/site-packages/functions_framework/__init__.py", line 80, in view_func
    return function(request._get_current_object())
  File "/Users/gabrielmyers/<Pythoners>/<Genv>/bin/main.py", line 54, in trade_crypto
    balance = phemex.fetch_balance({'code': 'ETH'})
  File "/Users/gabrielmyers/<Pythoners>/<Genv>/lib/python3.8/site-packages/ccxt/phemex.py", line 1378, in fetch_balance
    response = getattr(self, method)(self.extend(request, params))
  File "/Users/gabrielmyers/<Pythoners>/<Genv>/lib/python3.8/site-packages/ccxt/base/exchange.py", line 461, in inner
    return entry(_self, **inner_kwargs)
  File "/Users/gabrielmyers/<Pythoners>/<Genv>/lib/python3.8/site-packages/ccxt/base/exchange.py", line 486, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "/Users/gabrielmyers/<Pythoners>/<Genv>/lib/python3.8/site-packages/ccxt/base/exchange.py", line 482, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "/Users/gabrielmyers/<Pythoners>/<Genv>/lib/python3.8/site-packages/ccxt/base/exchange.py", line 609, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "/Users/gabrielmyers/<Pythoners>/<Genv>/lib/python3.8/site-packages/ccxt/phemex.py", line 2405, in handle_errors
    raise ExchangeError(feedback)  # unknown message
ccxt.base.errors.ExchangeError: phemex {"msg":"Please try again later","code":10500}

**Comment by Gabriele-Sabatino** [comment]
[Main.MD](https://github.com/ccxt/ccxt/files/6786878/Main.MD)

**Comment by Gabriele-Sabatino** [comment]
import ccxt
import config

phemex = ccxt.phemex({
'enableRateLimit': True,
'options': {
'defaultType': 'swap',
},
'apiKey': config.API_KEY,
'secret': config.API_SECRET,
'password': config.PASSWORD,
'urls': {
'api': 'https://testnet.phemex.com/'
}

})

phemex.urls['api'] = phemex.urls['test']

def trade_crypto(request):

data = request.get_json()



tickers = {

'BTCUSDT': 'BTC/USDT',
'BTCUSD': 'BTC/USD',
'DOTUSDT': 'DOT/USDT',
'DOTUSD': 'DOT/USD',
'ADAUSDT': 'ADA/USDT',
'ADAUSD': 'ADA/USD',
'ETHUSDT': 'ETH/USDT',
'ETHUSD': 'ETH/USD',
'LTCUSD': 'LTC/USD',
'LTCUSDT': 'LTC/USDT',
}

ticker = tickers[data['ticker']]


phemex.verbose = True
balance = phemex.fetch_balance({'code': 'ETH'})

return str(balance['info']['data']['positions']) 


-->OUTPUT:

Request: GET https://testnet-api.phemex.com/accounts/accountPositions?currency=ETH {'x-phemex-access-token': '0f4dba73-fbc3-408f-a419-4908365509ec', 'x-phemex-request-expiry': '1625773133', 'x-phemex-request-signature': '2ced64af0d12240b8e06fcf19b30e01239fb5fa4537932e64d6f6be8fac6c7b1', 'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://testnet-api.phemex.com/accounts/accountPositions?currency=ETH 500 {'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '45', 'Connection': 'keep-alive', 'Date': 'Thu, 08 Jul 2021 19:37:54 GMT', 'Set-Cookie': 'AWSALB=wCOg5JTnNfewTCEDGferuDniYre050Y3iNmDnYqj/OOgXozH70bTwpQhKqr8FdyNMviH27vsqmCw9yY6dVe0YatrYwRheFT7kATWB1m7mV8t2p5x8Hxqm4kWfydj; Expires=Thu, 15 Jul 2021 19:37:54 GMT; Path=/, AWSALBCORS=wCOg5JTnNfewTCEDGferuDniYre050Y3iNmDnYqj/OOgXozH70bTwpQhKqr8FdyNMviH27vsqmCw9yY6dVe0YatrYwRheFT7kATWB1m7mV8t2p5x8Hxqm4kWfydj; Expires=Thu, 15 Jul 2021 19:37:54 GMT; Path=/; SameSite=None, cookiesession1=678A3E11HIJKUV012345689890125820;Expires=Fri, 08 Jul 2022 19:37:54 GMT;Path=/;HttpOnly', 'Server': 'nginx', 'x-phemex-request-tracing': '6491a176-8698-4c5a-a080-9e66061f5774', 'X-RateLimit-Remaining-CONTRACT': '499', 'X-RateLimit-Capacity-CONTRACT': '500', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 4074a79e28cc4b1a455d24b3546c6c94.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'YTO50-C2', 'X-Amz-Cf-Id': 'UmpwwZ9VPl7BVhkeYDgNY19rK8c7eQpsziQz7GK-h2XiYbg514IADg=='} {"msg":"Please try again later","code":10500}
192.168.219.61 - - [08/Jul/2021 15:37:54] "POST / HTTP/1.1" 500 -
Traceback (most recent call last):
File "/Users/gabrielmyers///lib/python3.8/site-packages/ccxt/base/exchange.py", line 593, in fetch
response.raise_for_status()
File "/Users/gabrielmyers///lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://testnet-api.phemex.com/accounts/accountPositions?currency=ETH

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/gabrielmyers///lib/python3.8/site-packages/flask/app.py", line 2088, in call
return self.wsgi_app(environ, start_response)
File "/Users/gabrielmyers///lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
response = self.handle_exception(e)
File "/Users/gabrielmyers///lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
response = self.full_dispatch_request()
File "/Users/gabrielmyers///lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/Users/gabrielmyers///lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
rv = self.dispatch_request()
File "/Users/gabrielmyers///lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/Users/gabrielmyers///lib/python3.8/site-packages/functions_framework/init.py", line 80, in view_func
return function(request._get_current_object())
File "/Users/gabrielmyers///bin/main.py", line 54, in trade_crypto
balance = phemex.fetch_balance({'code': 'ETH'})
File "/Users/gabrielmyers///lib/python3.8/site-packages/ccxt/phemex.py", line 1378, in fetch_balance
response = getattr(self, method)(self.extend(request, params))
File "/Users/gabrielmyers///lib/python3.8/site-packages/ccxt/base/exchange.py", line 461, in inner
return entry(_self, **inner_kwargs)
File "/Users/gabrielmyers///lib/python3.8/site-packages/ccxt/base/exchange.py", line 486, in request
return self.fetch2(path, api, method, params, headers, body)
File "/Users/gabrielmyers///lib/python3.8/site-packages/ccxt/base/exchange.py", line 482, in fetch2
return self.fetch(request['url'], request['method'], request['headers'], request['body'])
File "/Users/gabrielmyers///lib/python3.8/site-packages/ccxt/base/exchange.py", line 609, in fetch
self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
File "/Users/gabrielmyers///lib/python3.8/site-packages/ccxt/phemex.py", line 2405, in handle_errors
raise ExchangeError(feedback) # unknown message
ccxt.base.errors.ExchangeError: phemex {"msg":"Please try again later","code":10500}

**Comment by kroitor** [comment]
@Gabriele-Sabatino for the future, you can post it here in this issue, using the proper markup, by surrounding your code and output with triple backticks (\`), do not confuse with quotes (\'):

\`\`\`Python

YOUR PYTHON CODE HERE

\`\`\`

\`\`\`

YOUR VERBOSE OUTPUT HERE

\`\`\`

-----------------------------------------------------------

First and foremost let's make sure that you're using the testnet API keys, created here: https://testnet.phemex.com/ – is that correct?

**Comment by Gabriele-Sabatino** [comment]
Yes, Im using the right API keys. I am all to do contract trades with BTC/USD but with any other cryptocurrency contract it doesnt seem to work.

**Comment by kroitor** [comment]
@Gabriele-Sabatino the testnet might not really work with other coins, but we will investigate.

**Comment by kroitor** [comment]
@Gabriele-Sabatino according to Phemex's docs, the currency of fetchBalance must be a margin currency, that is BTC or USD. This should work:

- https://github.com/phemex/phemex-api-docs/blob/master/Public-Contract-API-en.md#query-trading-account-and-positions

```Python
import ccxt
import config

print('CCXT Version:', ccxt.__version__)
exchange = ccxt.phemex({
    'options': {
        'defaultType': 'swap',
    },
    'apiKey': config.API_KEY,
    'secret': config.API_SECRET,
    'password': config.PASSWORD,
})

exchange.set_sandbox_mode(True)

markets = exchange.load_markets()
# balance = phemex.fetch_balance({'code': 'BTC'})  # or
balance = phemex.fetch_balance({'code': 'USD'})

return str(balance['info']['data']['positions']) 
```

↑ That should work. Let us know if not. Feel free to reopen this issue or just ask further questions if any.
