### ISSUE TITLE
Bitfnex , can't parse "params" into Public  Get function

### ISSUE THREAD

**Issue by Darren199612** [ccxt/ccxt#9533]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows10
- Programming Language version: Python
- CCXT version: 1.52.64

```
import ccxt
bitfinex = ccxt.bitfinex()
path = {"key":"pos.size","size":"1m","symbol":"tBTCUSD"}
params = {"limit":20}
data = bitfinex.v2_get_stats1_key_size_symbol_long_hist(path,params=params)


Result:
TypeError: inner() got multiple values for argument 'params'
```
when only parse "path" to function, it run well, but when parse "params" to function, it got an error.  I check the source code of 
this function "v2_get_stats1_key_size_symbol_long_hist", it do have the input "parmas",but it can't parse in.
```
![image](https://user-images.githubusercontent.com/30572523/124958873-3585d900-e04d-11eb-83af-42a69f9d68d0.png)

![image](https://user-images.githubusercontent.com/30572523/124958606-ea6bc600-e04c-11eb-8577-eeb2eac4f93f.png)
```

**Comment by kroitor** [comment]
Do not split path and params, all implicit API methods accept just one argument, that is a dictionary of params:

- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api

```Python
import ccxt
bitfinex = ccxt.bitfinex()
params = {"key":"pos.size","size":"1m","symbol":"tBTCUSD","limit":20}
data = bitfinex.v2_get_stats1_key_size_symbol_long_hist(params)
```

**Comment by kroitor** [comment]
P.S. We suggest using `bitfinex2` for the above call.
