### ISSUE TITLE
Binance fetchBalance function works well but fetch_positions function doesn't work well.

### ISSUE THREAD

**Issue by Alexandr1227** [ccxt/ccxt#9534]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows 10
- Programming Language version: ReactJS
- CCXT version:1.49.73

hello
I have some serious problems.
When I use fetchBalance it works really well.
But when I use fetch_positions function, it occurs 401 authorized (Invalid API-key, IP, or permissions for action, request ip:) error occurs.
Could you please tell me why I have this kind of error?
And how can I get my binance account positions info using ccxt with ReactJS?
I need your help!
Thank you.

**Comment by kroitor** [comment]
@Alexandr1227 have you configured the API Key permissions for futures-trading with the Binance website (in your account's API settings) ?

**Comment by Alexandr1227** [comment]
Do I have to configure the future trading permission for that?
And is there any function which I can get current permission info in ccxt??

**Comment by kroitor** [comment]
> Do I have to configure the future trading permission for that?

Yes, and your API key has to be created after you enable futures-trading permissions. So, the old keys, you've made prior to enabling futures trading won't work.

> And is there any function which I can get current permission info in ccxt??

No, but you can call all available endpoints from Binance using CCXT the unified API and the implicit API: 

- https://github.com/ccxt/ccxt/wiki/Manual#unified-api
- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api

Hope that answers your question. Feel free to reopen this issue or just ask further questions if any.
