### ISSUE TITLE
A couple of exchange changes and PHP code notes

### ISSUE THREAD

**Issue by rxmg-joeldg** [ccxt/ccxt#954]
Two ccxt large exchange changes:
1. Bitfinex is listed as a US exchange in ccxt and is terminating all relationships with US customers.
2. 1Broker has terminated it's BTC market and is shifting BTC buys/sells to 1Fox.com which apparently opens later today (12/24/2017)

For the PHP part of CCXT:
1.  It may be good to reorganize the 'Market Makers' (like 1broker and them) into their own set of classes as they are not really exchanges and have only BTC deposit/withdrawals. Additionally their quotes are usually from Bifinex or another major exchange they 'key' off, so these will be delayed quotes at best. Also, the market makers all need to set default leverage amounts which introduces something sort of new to this. Honestly I don't know the best way to handle this, figured I would bring it up so you could think about it.
2. For organization, it might be good to move the exchange class files into their own directories so they are not mixed in with the Exchange.php and the Exception files. (it would make it a lot easier when working with the files) also, Just as a note, this seems like a classic example of utilizing a class interface.

I am integrating ccxt heavily into my project, so I would be more than happy to help.

**Comment by kroitor** [comment]
> Bitfinex is listed as a US exchange in ccxt and is terminating all relationships with US customers.

Fixed for that.

> 1Broker has terminated it's BTC market and is shifting BTC buys/sells to 1Fox.com which apparently opens later today (12/24/2017)

Got it, will add edits to this as well, if necessary, thx!

> It may be good to reorganize the 'Market Makers' (like 1broker and them) into their own set of classes as they are not really exchanges and have only BTC deposit/withdrawals. Additionally their quotes are usually from Bifinex or another major exchange they 'key' off, so these will be delayed quotes at best. Also, the market makers all need to set default leverage amounts which introduces something sort of new to this. Honestly I don't know the best way to handle this, figured I would bring it up so you could think about it.

Will consider this, thx for the proposal!

> For organization, it might be good to move the exchange class files into their own directories so they are not mixed in with the Exchange.php and the Exception files. (it would make it a lot easier when working with the files) also, Just as a note, this seems like a classic example of utilizing a class interface.

Five days ago it was exactly like that (exchange.php and exceptions in their own separate subfolder for base code), but then: 

- https://github.com/ccxt/ccxt/pull/865
- https://github.com/ccxt/ccxt/pull/873
- https://github.com/ccxt/ccxt/pull/876
- https://github.com/ccxt/ccxt/pull/918

;)

> I am integrating ccxt heavily into my project, so I would be more than happy to help.

All contributions are appreciated, but make sure to read this first: https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code. Your pull requests are welcome!

Thanks once again. If you don't mind, I am closing this for now. Feel free to reopen it if needed or just ask questions here if you have more.

**Comment by rxmg-joeldg** [comment]
Wait, did I read this right? You moved the files because of the namespace instead of just changing the namespace?
All you should have had to do is change
namespace ccxt;
to namespace ccxt\base;
Or am I missing something here?

**Comment by kroitor** [comment]
> You moved the files because of the namespace instead of just changing the namespace?

No, I moved them because this change was in the above requests and from those requests I thought that merging them would be the right thing to do, at least, I had that impression. However, I'm not sure on this now that you've asked the question. I would propose to ask the same question here: https://github.com/ccxt/ccxt/pull/876... Would be interesting to read the arguments from all sides.
