### ISSUE TITLE
How to add overload, if api URLS are different?

### ISSUE THREAD

**Issue by ttodua** [ccxt/ccxt#9540]
When creating exchange overload, typically we define it in options, like :
```
   'version' => 'v1',
   'urls' => array(
         'logo' => '#',
         'api' => 'https://www.example.com/api/',
         ......
```

However, strange thing is that the one i want to add, have different scheme of API urls, like:
```
https://www.example.com/info/api/v1/getKline
https://www.example.com/trading/api/v1/createOrder
```
So, the base is different, and thus, I cant create like below:
```
            'api' => array(
                'public' => array(
                    'get' => array(
                         'getKline',
                         ...
                'private' => array(
                    'post' => array(
                         'createOrder',
                          ...
```
So,what are workarounds in such cases, to create the class correctly? thus calling i.e. `$class->privatePostCreateOrder`  or  `..->publicGetKline` will be understood by ccxt?

**Comment by kroitor** [comment]
> So,what are workarounds in such cases, to create the class correctly? thus calling i.e. $class->privatePostCreateOrder or ..->publicGetKline will be understood by ccxt?

CCXT does not decide how to treat those names and urls, you just give it an arbitrary abstract structure like shown below (for exmaple):

```
'alpha': {
    'bravo': {
        'charlie': {
            'get': [
                'foo',
            ],
            'post': [
                'bar',
            ],
        },
    },
    'delta': {
        'public': {
            'get': [
                'data/{symbol}',
            ],
        },
    },
}
'private': {
    'epsilon': {
        'post': [
            'abc',
        ],
    },
}
```

And that will generate the following methods (for example):

- alphaBravoCharlieGetFoo
- alphaBravoCharliePostBar
- alphaDeltaPublicGetDataSymbol
- privateEpsilonPostAbc

That arrives to the `sign()` method and it's up to the exchange integration developer to code it right for the url-scheme of his design.

Some exchanges have a mess in their URLs and naming schemas, the above gives all the freedom to the dev and allows to code any path-structure.

The coder also has to apply some logical and semantical thinking (be a software architect) when designing the way to split and group those url-paths.

------------------------



> When creating exchange overload, typically we define it in options, like :
> 
> ```PHP
>    'version' => 'v1',
>    'urls' => array(
>          'logo' => '#',
>          'api' => 'https://www.example.com/api/',
>          ......
> ```

You can also do:

```PHP
    'version' => 'v1',
    'urls' => array(
        'logo' => '#',
        'api' => array(
            'public' => 'https://www.example.com/info/api',
            'private' => 'https://www.example.com/trading/api',
        ),
```

Or:

```PHP
    'version' => 'v1',
    'urls' => array(
        'logo' => '#',
        'api' => array(
            'info' => 'https://www.example.com/info/api',
            'trading' => 'https://www.example.com/trading/api',
        ),
```

> However, strange thing is that the one i want to add, have different scheme of API urls, like:
> 
> ```
> https://www.example.com/info/api/v1/getKline
> https://www.example.com/trading/api/v1/createOrder
> ```
> 
> So, the base is different, and thus, I cant create like below:
> 
> ```
>             'api' => array(
>                 'public' => array(
>                     'get' => array(
>                          'getKline',
>                          ...
>                 'private' => array(
>                     'post' => array(
>                          'createOrder',
>                           ...
> ```

From the examples above it follows that you still can create it like you've shown.

Either:

```PHP
    'version' => 'v1',
    'urls' => array(
        'logo' => '#',
        'api' => array(
            'public' => 'https://www.example.com/info/api',
            'private' => 'https://www.example.com/trading/api',
        ),
    ),
    ...
    'api' => array(
        'public' => array(
            'get' => array(
                'getKline', // publicGetGetKline
                ...
        'private' => array(
            'post' => array(
                'createOrder', // privatePostCreateOrder
               ...
```

Or:

```PHP
    'version' => 'v1',
    'urls' => array(
        'logo' => '#',
        'api' => array(
            'info' => 'https://www.example.com/info/api',
            'trading' => 'https://www.example.com/trading/api',
        ),
    ),
    ...
    'api' => array(
        'info' => array(
            'get' => array(
                'getKline', // infoGetGetKline
                ...
        'trading' => array(
            'post' => array(
                'createOrder', // tradingPostCreateOrder
               ...
```

Hope that answers your question. Let us know if not.

Also, if you want to get that merged into the master version of CCXT, you might want to read this:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#transpiled-generated-files
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes

Feel free to reopen this issue if necessary, or just ask further questions if any.

**Comment by ttodua** [comment]
Outstanding answer !
