### ISSUE TITLE
stop_loss_limit = waiting for a first order "filled"

### ISSUE THREAD

**Issue by rafalsza** [ccxt/ccxt#9549]
- OS:Ubuntu
- Programming Language version:Python 3.8
- CCXT version:ccxt-1.52.76

Hi!
I have a question, maybe you could help me with this case. I'm trying to add stop loss order but only when exchange.create_limit_buy_order will be filled
```
    if df['Buy_Signal'][previous_row_index] == 0 and df['Buy_Signal'][last_row_index] == 1:
        print("BUY!")
        if not in_position:
            order = exchange.create_limit_buy_order(symbol1, 0.15, df['close'][last_row_index])
            time.sleep(5)
            sl = exchange.create_order(symbol, type='stop_loss_limit',
                                       side='sell', amount=0.15, price=(order.get('price') - 5.20),
                                       params={'stopPrice': (order.get('price') - 5)})
            print(order)
            print(sl)
            in_position = True
```

how to code waiting for a first order?

**Comment by ttodua** [comment]
for future readers, there is no special instruction other than using `.fetch_order` or related methods, please see: https://docs.ccxt.com/#/README?id=querying-orders
