### ISSUE TITLE
Refused to set unsafe header "origin"

### ISSUE THREAD

**Issue by Bomper** [ccxt/ccxt#955]
I'm trying to use a CORS proxy to access BitMEX. https://crossorigin.me is down (I see the Cloudflare page), so I tried [the Node proxy](https://github.com/ccxt/ccxt/wiki/Install#nodejs-cors-proxy). I've verified that http://localhost:4080/https://www.bitmex.com/api/v1/instrument/activeAndIndices returns correct data in the browser.

The problems is that when I try `const markets = await bitmex.load_markets();` in the browser, I get this error:

> Refused to set unsafe header "origin"
(anonymous) @ fetch-browser.js:470
fetch-browser.js:473 GET http://localhost:4080/https://www.bitmex.com/api/v1/instrument/activeAndIndices 403 (Forbidden)

I get the same error with another proxy, https://cors-anywhere.herokuapp.com/:

![image](https://user-images.githubusercontent.com/34669048/34326849-b9d523b0-e86b-11e7-8611-8251a7c6fb44.png)

**Comment by kroitor** [comment]
Fixed in 1.10.467.

**Comment by Bomper** [comment]
Thanks for the quick fix. I no longer get that error, but I get an empty response.

```js
import ccxt from 'ccxt';

const bitmex = new ccxt.bitmex({
  verbose: true,
  proxy: 'http://localhost:4080/',
});

(async function main() {
  const markets = await bitmex.loadMarkets();
  console.log(markets);
}());
```

![image](https://user-images.githubusercontent.com/34669048/34333837-a9eb116e-e8f5-11e7-9eea-5f954c0c271a.png)

**Comment by kroitor** [comment]
@Bomper , if this http://localhost:4080/https://www.bitmex.com/api/v1/instrument/activeAndIndices returns correct data in browser, then:

1. You should open the network tab in your Web Inspector:
![network-tab](https://user-images.githubusercontent.com/1294454/34334062-1474d5ca-e954-11e7-957c-6839e07dfdc2.jpg)

2. Then refresh the page to see the request getting sent in the network tab, then after the refresh is complete, click the request on the left and scroll to request headers on the right:
![web-inspector](https://user-images.githubusercontent.com/1294454/34334072-390d2e6e-e954-11e7-94c9-b4fbd03a6f38.jpg)

3. Then copy the request headers to your CORS Node.js proxy script, like shown here:
https://github.com/Rob--W/cors-anywhere#server

If you copy proper headers, it should work.

**Comment by Bomper** [comment]
http://localhost:4080/https://www.bitmex.com/api/v1/instrument/activeAndIndices does return correct data. I've copied the request headers to `setHeaders` as follows:

```js
// JavaScript CORS Proxy using https://github.com/Rob--W/cors-anywhere
const port = process.argv[2] || 4080;
require('cors-anywhere').createServer({
  setHeaders: {
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'en-US,en;q=0.9',
    'Cache-Control': 'no-cache',
    'Connection': 'keep-alive',
    'Host': 'localhost:4080',
    'Pragma': 'no-cache',
    'Upgrade-Insecure-Requests': 1,
    'User-Agent:': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/63.0.3239.84 Chrome/63.0.3239.84 Safari/537.36',
  },
}).listen(port, 'localhost');
console.log('CORS proxy listening on port', port);
```

When I run the client in the browser, I no longer get 403 forbidden, but get a different error, "Network request failed":

![image](https://user-images.githubusercontent.com/34669048/34334306-1e5916be-e8fa-11e7-8f7b-d1c5b54e4769.png)

However, isn't the job of the bitmex CCXT library to put those headers in the request ? I don't think they should be in the proxy server code because the proxy just forwards any headers it receives.

Has nobody else used BitMEX from the browser? How did this work before?

**Comment by kroitor** [comment]
> However, isn't the job of the bitmex CCXT library to put those headers in the request ?

Not really, the point is that in the browser you can't set the Origin header at all. Bitmex does not support CORS at all. This is the reason for using the CORS proxy in the first place – we need to set some headers, but we can't do it in the browser (forbidden by the browser security settings), therefore we have to set those headers on the proxy.

> How did this work before?

With proper HTTPS tunneling via a CORS-proxy, it should work, like it does for most exchanges, however, it doesn't work for BitMEX for some reason. I will investigate further and will get back to you on this.

**Comment by imhazige** [comment]
This problem appear again. version v1.14.209.
I am sure when using v1.14.180, it have not such  a problem.
I am always using a proxy.
refer to issue #3171
