### ISSUE TITLE
How to implement leverage on Phemex Exchange?

### ISSUE THREAD

**Issue by Gabriele-Sabatino** [ccxt/ccxt#9556]
Hello, my question is how to implement leverage when using multiple params on the Phemex exchange. I was able to implement take profit and stop loss but need help with leverage.

**Comment by carlosmiei** [comment]
Hello @Gabriele-Sabatino, please check out this snippet where a contract order with leverage is created: 

```Python
import ccxt # noqa: E402

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.phemex({
    'enableRateLimit': True,
	'apiKey': 'YOUR_API_KEY',
	'secret': 'YOUR_SECRET',
	'options': {
	'defaultType': 'swap',
	},
})
amount = 5
symbol = 'BTC/USD:USD'

# Change leverage to the desired value
leverageResponse = exchange.set_leverage(5, symbol)

# Opening a pending contract (limit) order
order = exchange.create_order(symbol, 'market', 'buy', amount)
print(order)
```

You can also see a complete example here: https://github.com/ccxt/ccxt/blob/master/examples/py/phemex-leverage-orders.py
