### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [ccxt/ccxt#9557]
Hi there,

I couldn't find a `SECURITY.md` in your repository and am not sure how to best contact you privately to disclose a security issue.

Can you add a `SECURITY.md` file with an e-mail to your repository, so that our system can send you the vulnerability details? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, you should receive an e-mail within the next hour with more info.

Thanks! (cc @huntr-helper)

**Comment by frosty00** [comment]
Hi,

Send us the security issue to info@ccxt.trade

Cheers

**Comment by JamieSlome** [comment]
@frosty00 - please refer to https://github.com/ccxt/ccxt/pull/9559

**Comment by quantumpacket** [comment]
@JamieSlome Has there been an agreed upon timeline on disclosing the reported security issue?

**Comment by JamieSlome** [comment]
@quantumpacket - the issue has now been resolved and is visible via our platform.
