### ISSUE TITLE
ccxt pro start a new thread for execution

### ISSUE THREAD

**Issue by pickmone** [ccxt/ccxt#9558]
Hi, 

a general question about if it is possible to use ccxt pro with multiple thread.

in general, I use a lot of limit orders, and right now, if a market's condition is within my tolerance, I would place a limit order. however this would block the rest of my code by design, since I want to be able to cancel the order immediately when its not longer favorable using watch_orderbook, or market order an opposite leg if the order is filled/partially filled using watchOrders. 

I am looking at multiple markets, so right now can only cycle through market one by one. But I would like to be able to let the market that has a limit order run in a separate thread while the code continue to look at other markets. The normal async style add task doesn't work in my case because its more likely that the code is doing something else when it should be cancelling the order or creating the market order for the opposite leg. By the time it come back to the limit order, it usually is too late. 

I have tried to create a new event loop and thread it with the limit order function I have, but it always give an error of "await wasn't used with future" or "object attached to another loop". 

so just want to get a sense of if this is possible right now?

```
the general algorithm I tried is:

async def limit order function(args)
     calls other functions that includes watchorder, watch_orderbook, the calculation logics and execution logics. 

if conditions are met for this market:
     _thread = threading.Thread(target=asyncio.run, args=(limit order function))
     _thread.start()

the function does not return anything and doesn't need to be joined back to the main loop. 
```

**Comment by frosty00** [comment]
python is single threaded anyway with the GIL so you may aswell use proper async style instead of threads. you can implement virtual threads using locks and semaphores - https://docs.python.org/3/library/asyncio-sync.html#asyncio.Semaphore
