### ISSUE TITLE
Issue in zb

### ISSUE THREAD

**Issue by ttodua** [ccxt/ccxt#9565]
There is strange issue. To reproduce:

```
$x= new \ccxt\zb();
$x->load_markets(); 
exit;
```

However, to temporary debug internal functions, "set_markets" method (in `Exchange.php`), where it says:

```
        $this->markets = static::index_by($values, 'symbol');
        $this->markets_by_id = static::index_by($values, 'id');
        var_dump( count($this->markets ) );
        var_dump( count($this->markets_by_id ) );
```
 var-dump these two properties and you will see strange result (as opposed to all other exchanges, only this one misbehaves), that ` $this->markets` has '262' items, while ` $this->markets_by_id` has '266' items (the `$values` variable itself has size of 266 items).
(i've found that `bsv - usdt` pairs and some other one causes mess, i dont know what happens).
This seems a bug obviously.

**Comment by ttodua** [comment]
@kroitor thanks, one question - your committed .JS file.  Does it automatically reflect into PHP in the background of git-build process?

**Comment by kroitor** [comment]
> Does it automatically reflect into PHP in the background of git-build process?

Yes, it should be available in the most recent version in JS, Py and PHP:

- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#multilanguage-support

**Comment by ndubel** [comment]
https://web.zb.com/i/blog?item=1492&type=proclamation
no need soon
