### ISSUE TITLE
New Exchange - coindcx

### ISSUE THREAD

**Issue by innowebka** [ccxt/ccxt#9566]
Official Website - https://coindcx.com

Here is the API documentation for exchange: https://docs.coindcx.com
Referral page - https://coindcx.com/referral

**Comment by kroitor** [comment]
Duplicate:

- https://github.com/ccxt/ccxt/issues/4878 (requested here)
- https://github.com/ccxt/ccxt/pull/6235 (tested here, you can build and run it as documented)
