### ISSUE TITLE
[OKEX v5] ccxt throwing error on API options when calling fetch_balance() 

### ISSUE THREAD

**Issue by cryptoCCY** [ccxt/ccxt#9572]
I know that I am probably missing something obvious, but the most recent updates to okex5 broke my daily balance reporting.

I am getting the error output shown at the bottom of this post, and as far as I am aware the OKEX v5 balances endpoint has not changed, but ccxt has. Any additional clarity that you can provide would be appreciated.

It looks like ccxt requires defaultType  in params when making the balance call, but I already specified the default while instantiating ccxt. I did something similar to the quick and dirty test below to reproduce the error.

What am I missing?

- OS: Ubuntu 
- Programming Language version: Python 3
- CCXT version: 1.52.91

```
from pprint import pprint
import os
import sys
import csv
import time
import datetime
from texttable import Texttable
from dotenv import load_dotenv
sys.path.append("../")
project_folder = os.path.expanduser('~/WORKINGDIR')
load_dotenv(os.path.join(project_folder, '.OKEXAPIKEYS'))
​
import ccxt  # noqa: E402
​
try:
    okex_v3           = ccxt.okex  ({'apiKey': os.getenv("OKEX_V3KEY"),
                                            'secret'        : os.getenv("OKEX_V3SEC"),
                                            'password'  : os.getenv("OKEX_V3PAS"),
                                            'enableRateLimit' : True,
                                            'options'  : {
                                                'defaultType' :  'swap',
                                                'fetchMarkets': ['swap'],},
                                           })
    okex_v5         = ccxt.okex5 ({'apiKey': os.getenv("OKEX_V5KEY"),
                                            'secret'        : os.getenv("OKEX_V5SEC"),
                                            'password'  : os.getenv("OKEX_V5PAS"),
                                            'enableRateLimit' : True,
                                            'options'         : {
                                                'defaultType' :  'swap',
                                                'fetchMarkets': ['swap'],},
                                        })
except Exception as e:
    log_ts= datetime.datetime.now()
    print("OKEX CCXT init failed with an error at {0}".format(log_ts.strftime( "%Y-%m-%d_%H.%M.%S" )))
    print("Error reported was:\n{0}".format(str(e)))  
    interrupt = str(input("[Enter] to continue..."))
finally:
    okex_v3_mkts = okex_v3.load_markets ()
    okex_v5_mkts = okex_v5.load_markets ()
    okex_v3_bal = okex_v3.fetch_balance()
    okex_v5_bal = okex_v5.fetch_balance()
​

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-b3d79e84ff2c> in <module>
     43     okex_v5_mkts = okex_v4.load_markets ()
     44     okex_v3_bal            = okex_v3.fetch_balance()
---> 45     okex_v5_bal            = okex_v5.fetch_balance()

~/work/ndms/lib/python3.7/site-packages/ccxt/okex5.py in fetch_balance(self, params)
   1104     def fetch_balance(self, params={}):
   1105         self.load_markets()
-> 1106         defaultType = self.safe_string_2(self.options, 'defaultType')
   1107         options = self.safe_string(self.options, 'fetchBalance', {})
   1108         type = self.safe_string(options, 'type', defaultType)

TypeError: safe_string_2() missing 1 required positional argument: 'key2'
```

**Comment by kroitor** [comment]
Fixed in CCXT 1.53.3, the new build will arrive in ~20 minutes, thanks for reporting!
