### ISSUE TITLE
No Symbols for Bybit spot trading

### ISSUE THREAD

**Issue by Kobashun74** [ccxt/ccxt#9578]
- OS: Ubuntu 20.04.2 LTS
- Programming Language version: Python
- CCXT version:1.53.4

Hello,
The pilot version of spot trading at Bybit has began. I have just a question, when we can use the CCXT for the spot trading at Bybit?

Thank you

**Comment by kroitor** [comment]
We will add the support for Bybit's spot markets as soon as possible, hopefully this month. Let us know if that does not answer your question.
