### ISSUE TITLE
Problems with ccxtpro install

### ISSUE THREAD

**Issue by rianbowgift** [ccxt/ccxt#9579]
Hi. While I was programming with ccxt, I needed a socket function.
So I bought ccxtpro yesterday.

However, a problem occurred during the installation process.

I am using python on windows and registered github ssh for ccxtpro.

But when I enter "pip3 install git+ssh://git@github.com/kroitor/ccxt.pro.git#subdirectory=python"

I'm getting the following error:

--------------------------------------------------------------------------------------------------

Collecting git+ssh://****@github.com/kroitor/ccxt.pro.git
  Cloning ssh://****@github.com/kroitor/ccxt.pro.git to c:\users\rianb\appdata\local\temp\pip-req-build-3ny6yxje
  Running command git clone -q 'ssh://****@github.com/kroitor/ccxt.pro.git' 'C:\Users\rianb\AppData\Local\Temp\pip-req-build-3ny6yxje'
  ERROR: Repository not found.
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.
WARNING: Discarding git+ssh://****@github.com/kroitor/ccxt.pro.git. Command errored out with exit status 128: git clone -q 'ssh://****@github.com/kroitor/ccxt.pro.git' 'C:\Users\rianb\AppData\Local\Temp\pip-req-build-3ny6yxje' Check the logs for full command output.
ERROR: Command errored out with exit status 128: git clone -q 'ssh://****@github.com/kroitor/ccxt.pro.git' 'C:\Users\rianb\AppData\Local\Temp\pip-req-build-3ny6yxje' Check the logs for full command output.
WARNING: You are using pip version 21.1.2; however, version 21.1.3 is available.
You should consider upgrading via the 'c:\users\rianb\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.

----------------------------------------------------------------------------------------

I don't know if this is a github configuration problem or a ccxtpro problem.

Kind of a stupid question, but can you help me?

I can not speak english very well! Please understand even if the grammar is weird.

**Comment by kroitor** [comment]
> I don't know if this is a github configuration problem or a ccxtpro problem.

Hi! I suggest to test that first. As far as we see, you have not accepted the invitation to CCXT Pro's GitHub repository (a notification is sent automatically to your primary GitHub email, when you preorder the access to it). If you don't see it, you can also test that by trying these links in your browser: 

- https://github.com/kroitor/ccxt.pro
- https://github.com/kroitor/ccxt.pro/invitations

It should work after you accept the invite.
Let us know if that does not help. Feel free to reopen this issue or just ask further questions if any.

**Comment by rianbowgift** [comment]
good.
i was stupid
good.good
the problem is solved
