### ISSUE TITLE
want to upgrade ccxt from Version: 1.34.38 - Phemex

### ISSUE THREAD

**Issue by adamrg73** [ccxt/ccxt#9580]
I want to upgrade but have bots running, just want to make sure that my code doesnt break somewhere..
Im using ccxt with phemex..
It shouldnt break old code right?
Otherwise I have to make a new vps to test..

reason why i need to upgrade is because new contract pairs arent showing with my current version.
Let me know your thoughts
thanks

**Comment by adamrg73** [comment]
hi, fetchedOrders=exchange.fetchOpenOrders(symbol)
appears to be broken moving from ccxt version 1.34.38 to 1.53.14

and im getting this for some items in json like indexEp and avg entry price.. appears that from older ccxt or phemex api dont know which yet the json item is being treated as a string instead of a float, and now i had to typecast it to float to fix the exception.
found exception: unsupported operand type(s) for /: 'str' and 'int'

all i did to this server was upgrade pip3 as the pip3 install ccxt --upgrade was failing.. didnt upgrade python3 or anything else..

after the fixes I did I appear to be trading okay for now.. ill keep posted if anything else comes up.
let me know your thoughts..
thanks..

**Comment by kroitor** [comment]
@adamrg73 hi! Please, paste your verbose output (enable verbose mode before fetchOpenOrders call): https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by frosty00** [comment]
It looks like this issue is related to the strings inside of the `info` response, so I think this issue can be closed.

**Comment by ttodua** [comment]
Current ccxt version is too above 1.90, so you can check out the current version too.
Also, as commented above by frosty00/kroitor, and not getting any follow up, this issue can be closed.
Let us know if you experience any issue with CCXT
