### ISSUE TITLE
How to place OCO order with market price on Binance Futures Python

### ISSUE THREAD

**Issue by fuvser** [ccxt/ccxt#9582]
How do I open an OCO order with Binance Futures but with market price
- OS: Windows 10 Pro 20H2 64-bit
- Programming Language version: Python 3.9.6
- CCXT version:  Latest

**Comment by kroitor** [comment]
Afaik, Binance does not support OCO orders for usdt-m/coin-m futures. Binance supports OCO orders for spot markets only.
