### ISSUE TITLE
Can you add watchBalance of Kucoin

### ISSUE THREAD

**Issue by iliuyongkang** [ccxt/ccxt#9590]
- OS:mac
- Programming Language version:3.7.5
- CCXT version:1.51.23
- - CCXTPRO version:0.7.65

i want use the ws of balance on the kucoin ,can you add watchBalance of Kucoin in the ccxtpro

**Comment by ttodua** [comment]
`watchBalance` is currently implemented in ccxt-pro.
Closing this issue.
