### ISSUE TITLE
How to override 'Exchange.php' methods?

### ISSUE THREAD

**Issue by ttodua** [ccxt/ccxt#9594]
Is there any viable/robust way to override any method of Exchange.php ? At this moment, with current version, I have hardcoded (changed) the file, but on next update it will be erased, so, I don't want to do by hand on every update of library. What is viable way for that?

**Comment by kroitor** [comment]
You can do that by subclassing:

```PHP
class MyBinance extends \ccxt\binance {
        public function nonce() { // this is a method from Exchange.php
            return $this->milliseconds();
        }
};
```

You can also put the overrides into a separate php file and then include it in multiple subclasses using the preprocessor:

```PHP
# overrides.php

        public function nonce() { // this is a method from Exchange.php
            return $this->milliseconds();
        }
```

```PHP
# classes.php
class MyBinance extends \ccxt\binance {
    include overrides.php;
};

class MyKraken extends \ccxt\kraken {
    include overrides.php;
};
```

If that is not your intent, please, clarify the question.

**Comment by ttodua** [comment]
Thanks for note, unfortunately, i probably didnt express well. 
I didn't want to mean the individual exchange classes, but itself the base `Exchange.php`, because there are some things that I wanted to change (some methods that are called by all of the inherited exchange classes, let's say, `load_markets` method, or any base method. I didn't want to individually override 10+ exchanges one-by-one).

**Comment by ttodua** [comment]
?

**Comment by frosty00** [comment]
I think the easiest way to do this in php is to create your own php/Exchange.php that the exchange inherits from the like this:

```
// file: php/Exchange.php
namespace ccxt;

include_once './OldExchange.php';

class Exchange extends extends OldExchange {
    // override any methods here
} 
```

**Comment by ttodua** [comment]
Frosty, sorry but you know better that it's not a solution. touching any file manually in library is not a way to go. I update package every second day, so, i should do it every day to manually replace the files? cant you please make some "hook"s available in exchange class?

**Comment by kroitor** [comment]
@ttodua it depends on which method is in question, but you can override most of methods with PHP's traits:

```PHP
<?php

include_once "ccxt.php";

trait OverrideTrait {

    public function load_markets($reload = false, $params = array()) {

        // --------------------------------------------------------------------
        // place your overrides here

        echo $this->id . "\n";
        exit();

        // -------------------------------------------------------------------

        return parent::load_markets($reload, $params);
    }
}

class MyBinance extends \ccxt\binance {
    use OverrideTrait;
}

class MyFTX extends \ccxt\ftx {
    use OverrideTrait;
}

$symbol = 'BTC/USDT';

$binance = new MyBinance();
$ticker = $binance->fetch_ticker($symbol);
var_dump($ticker);

$ftx = new MyFTX();
$ticker = $tx->fetch_ticker($symbols);
var_dump($ticker);
```

Apart from the above and https://github.com/ccxt/ccxt/issues/9594#issuecomment-881838235 i don't there's too many ways to do this without changing the source code of the lib.

**Comment by ttodua** [comment]
thanks kroitor, but nope, what you suggest is same, for 100 exchange we have to create 100 other classes and overrides, while there could be a better way, i.e. in exchange.php there could have been:

```
if (!trait_exists('ExchangeOverloads')) {
   trait ExchangeOverloads {}  // empty as default
}

class Exchange{

     private $suffix= 'overload';

     public function some_function( $params ) {
         if ( method_exists($this, "some_function_{$this->suffix}" ) ) {
            return call_user_func( [$this,"some_function_{$this->suffix}", $params );
         }
        else {
            ... exisiting codes
        }

     }
}
```
_// There is far better suggestion for which I opened topic about "hooks" (to have like wordpress). With that route, basically everyting stays same, not even "if/else" is needed inside function body, but in the end of function, where is `return $result` there will be `return apply_filters($result, 'load_markets')` or whatever function name it is._


The reason we think that is much worth of implementing is the following advantages:

1) there are many valid cases, when user needs to overload base (exchange) class, instead of creating 100's of 'overloaded classes' with same purpose, to overload **just a single method**.
2) there has been not just one problem, instead, many problems , for which I had to open the issue on github and ask your advise, and you are wasting your energy for nothing. If there was a way to override base exchange classes, you would have saved at least few topics from one user (from me) and who knows, how many are out there who would welcome to have exchange-override ability
3) I dont see any single disadvantage of the suggested solution. 

So, these 3 points are valid and I see only gain to CCXT with this step-forward.

**Comment by kroitor** [comment]
@ttodua the problem is that not all users will want an extra conditional on every single (even the smallest) method of the exchange.

**Comment by ttodua** [comment]
but  one conditional check in php takes 0.00001 milisecond probalby,, and to say right - none of users call 'load_markets' on every single second or minute.  I just meant for some important functions, like load_markets and some cornerstone methods. 
 
 however, as you wish, I just wished to take ccxt to upper level of easy development. The suggestion you suggested, is a total trouble for us, and we already have so many exchange-class overloads, that we are already messed in dependency hell.

**Comment by kroitor** [comment]
@ttodua we'll think of how to do this without introducing a wrapper to each method, most likely, it can be concentrated here: https://github.com/ccxt/ccxt/blob/master/php/Exchange.php#L2484

**Comment by ttodua** [comment]
Thanks Kroitor, any step-forward with this issue will be welcomed!

**Comment by kroitor** [comment]
@ttodua it can make things easier, if you list out all methods you consider cornerstone, apart from load_markets.

**Comment by ttodua** [comment]
Well, there has been some methods that came across till date  i.e. [this](https://github.com/ccxt/ccxt/issues/9514#issuecomment-874790726), where load_markets & price_to_precision functions were needed to be overloaded (btw, I am still waiting your suggestion in that topic, as that issue still persists - every new day that issue can be observed still with new pairs),    and [this](https://github.com/ccxt/ccxt/issues/9381) was because of 'float' function,  and [this ](https://github.com/ccxt/ccxt/issues/9345) was to create an additional method in exchange class;  and [this ](https://github.com/ccxt/ccxt/issues/9351) was intended by me to create an overload of base-exchange class at  all, where I wanted to implement a custom caching system myself, so i could re-instantiate exchange-classes in 0.1 second in php...

so, the list will go on when time goes and when developer comes across other needs. I cant think of other cases at this moment, but I am sure "extendibility" of exchange-base class will be very useful, and would have avoided many user-troubles too.

**Comment by kroitor** [comment]
> btw, I am still waiting your suggestion in that topic, as that issue still persists - every new day that issue can be observed still with new pairs

Yep, I saw, just didn't have the time to produce a working snippet yet. Will get to that issue asap.

> so, the list will go on when time goes and when developer comes across other needs

Ok, I see.

**Comment by ttodua** [comment]
_[just as future note related to this topic: https://github.com/ccxt/ccxt/issues/9382 ]_
