### ISSUE TITLE
Query Binance account API restrictions

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#9605]
Hello, 

Binance added the following entry point to query the user API key permission, could you please add it ? What I would like to do is the query account permissions.

`GET /sapi/v1/account/apiRestrictions
`
Thank you,

**Comment by Kinzowa** [comment]
Hi Igor,

Could you please tell me how to use this entry point ?

This how I list everything about restrictions:
```

>>> [print(i) for i in dir(c) if 'estriction' in i]
sapiDeleteBrokerSubAccountApiIpRestrictionIpList
sapiDeleteBrokerSubaccountapiIprestrictionIplist
sapiGetBrokerSubAccountApiIpRestriction
sapiGetBrokerSubaccountapiIprestriction
sapiGetMarginInterestratehistory
sapiPostBrokerSubAccountApiIpRestriction
sapiPostBrokerSubAccountApiIpRestrictionIpList
sapiPostBrokerSubaccountapiIprestriction
sapiPostBrokerSubaccountapiIprestrictionIplist
sapi_delete_broker_subaccountapi_iprestriction_iplist
sapi_get_broker_subaccountapi_iprestriction
sapi_get_margin_interestratehistory
sapi_post_broker_subaccountapi_iprestriction
sapi_post_broker_subaccountapi_iprestriction_iplist
[None, None, None, None, None, None, None, None, None, None, None, None, None, None]
>>> 
```

Unfortunnatly I can't find the one above.

Best,

**Comment by kroitor** [comment]
@Kinzowa please, upgrade to CCXT 1.53.30, it takes ~20 minutes for the new build to arrive – the new endpoint will appear in your list.
