### ISSUE TITLE
ByBit cancel open orders

### ISSUE THREAD

**Issue by rvleij** [ccxt/ccxt#9607]
My Environment:

    OS: MacOS
    Programming Language version: Python 3.9.0
    CCXT version: '1.53.25'

I'm running with bt-ccxt around ccxt with the following config:

```
store = CCXTStore(exchange='bybit', currency=COIN_REFER, config=broker_config, sandbox=True, retries=10, debug=DEBUG)
```

I'm trying to buy / sell "inverse perpetual" BTC/USD futures on ByBit. I'm running BackTrader as my platform, bt-ccxt as a wrapper (it provides the ccxt-store thing I'm using). The order process works fine (by now haha), so I get to the point where I'm trying to cancel an order and that seems to fail. I think there is an issue.

First I create an order using the following code (it's one of three orders I create, only the affected order I list):

```
self.buy_trail_order = self.sell(exectype=bt.Order.Limit, transmit=False, base_price=self.data0.close[0], size=self.stake_size, stop_px=(self.data0.close[0]*some_var), price=(self.data0.close[0]*some_other_var), parent=self.buy_order)
```

So far so good, executed, shows up in the console / web, all is fine. At some point I want to modify that order and for that I cancel it and create a new order. Or I manually do a "close position" because "it's time" and then I also want to remove my SL/TP order, which is the trail order. I don't remember why I'm doing the trailing myself, but that was because I didn't get the trailing stop order type to work on Bybit, which is a different issue.

Anyway, I do a:

```
self.cancel(self.buy_trail_order)
```

Which results in the following call to ByBit, first getting the order status which looks normal to me:

```
Request: GET https://api-testnet.bybit.com/v2/private/order?api_key=<api-key>&order_id=<order-id>&recv_window=5000&symbol=BTCUSD&timestamp=1626692103507&sign=<sign> {'Accept-Encoding': 'gzip, deflate'} None
```

returning the order status:

```
Response: GET https://api-testnet.bybit.com/v2/private/order?api_key=<api-key>&order_id=<order-id>&recv_window=5000&symbol=BTCUSD&timestamp=1626692103507&sign=<sign> 200 {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '799', 'Expires': 'Mon, 19 Jul 2021 10:55:05 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Mon, 19 Jul 2021 10:55:05 GMT', 'Connection': 'keep-alive'} {"ret_code":0,"ret_msg":"OK","ext_code":"","ext_info":"","result":{"user_id":<userid>,"position_idx":0,"symbol":"BTCUSD","side":"Buy","order_type":"Limit","price":"31025.5","qty":1000,"time_in_force":"GoodTillCancel","order_status":"Untriggered","ext_fields":{"o_req_num":9429130},"leaves_qty":1000,"leaves_value":"0.03223155","cum_exec_qty":0,"cum_exec_value":null,"cum_exec_fee":null,"reject_reason":"EC_NoError","cancel_type":"UNKNOWN","order_link_id":"","created_at":"2021-07-19T10:38:03.394657495Z","updated_at":"2021-07-19T10:38:03.394657495Z","order_id":"<order-id>","take_profit":"0.00","stop_loss":"0.00","tp_trigger_by":"UNKNOWN","sl_trigger_by":"UNKNOWN"},"time_now":"1626692105.865414","rate_limit_status":483,"rate_limit_reset_ms":1626692105863,"rate_limit":600}
```

then the cancel:

```
Request: POST https://api-testnet.bybit.com/v2/private/order/cancel {'Content-Type': 'application/json', 'Accept-Encoding': 'gzip, deflate'} {"symbol":"BTCUSD","order_id":"<order-id>","api_key":"<api-key>","recv_window":5000,"timestamp":"1626692103812","sign":"<sign>"}
```

which then returns in the following weird error that I didn't find much useful info on with my google skills:

```
Response: POST https://api-testnet.bybit.com/v2/private/order/cancel 200 {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '222', 'Expires': 'Mon, 19 Jul 2021 10:55:06 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Mon, 19 Jul 2021 10:55:06 GMT', 'Connection': 'keep-alive'} {"ret_code":30032,"ret_msg":"os[Untriggered] cs[Init] cannot replace_ao","ext_code":"","ext_info":"","result":null,"time_now":"1626692106.171083","rate_limit_status":99,"rate_limit_reset_ms":1626692106168,"rate_limit":100}
```

The same cancel method on the same ccxt towards Binance is working fine, so this must be something weird on the Bybit side? Reading their API documentation ([here]((https://bybit-exchange.github.io/docs/inverse/#t-cancelactive)) I see that really there's not much I can do wrong here: pass the order ID (I cross checked and it's the correct ID) and it should work. One thing that does confuse me is that the URL endpoint is for "active" orders, while this is really a conditional order. According to their documentation [here](https://bybit-exchange.github.io/docs/inverse/#t-cancelcond) there is a different endpoint for cancelling those, which makes we wonder if we're using the correct endpoint? But then again, we also created the order via the /private/order endpoint so we should be able to cancel it there as well.

**Comment by samgermain** [comment]
Is this issue about not being able to cancel stop orders? If so, then that should have been fixed with this PR 

https://github.com/ccxt/ccxt/pull/13116

**Comment by samgermain** [comment]
I'm going to close this issue, feel free to reopen it if you have any more questions
