### ISSUE TITLE
FTX Get Positions with showAvgPrice params not working

### ISSUE THREAD

**Issue by nickpagz** [ccxt/ccxt#9608]
- OS: MAC OS 10.15.7
- Programming Language version: Python 3.9.5
- CCXT version: 1.52.2

I'm running this function to get a list of my open positions (perpetual futures):

```
def get_positions():
    open_positions = {}
    all_positions = ftx.fetchPositions()
    print(all_positions)
    for x in all_positions:
        future = (x["future"])
        size = (x["size"])
        side = (x["side"])
        cost = (x["cost"])
        entryPrice = (x["entryPrice"])
        unrealizedPnl = (x["unrealizedPnl"])
        realizedPnl = (x["realizedPnl"])
        if size != '0.0':
            open_positions[future] = size, side, cost, entryPrice, unrealizedPnl, realizedPnl
    return open_positions

```

It works great. Except, the entryPrice parameter as defined by [FTX in their API docs](https://docs.ftx.com/?python#get-positions) says:

> Average cost of this position after pnl was last realized: whenever unrealized pnl gets realized, this field gets set to mark price, unrealizedPnL is set to 0, and realizedPnl changes by the previous value for unrealizedPnl.

...meaning, the entryPrice I see is not the entry price of the position in the original fills. What I actually need is the "Avg open price" or the "Break-even price" shown in the Positions window in the FTX trade terminal.

If I take a look at the whole response to `ftx.fetchPositions()`, those are not passed in the response. 

I then noticed in the FTX API docs a passable parameter, **showAvgPrice**. I assumed this could be what I was looking for. So I changed my fetchPositions() line to:

```
all_positions = ftx.fetchPositions({"showAvgPrice": True})
```

...but this didn't change anything in the response. The list of positions and the fields returned were all identical.

So either I'm using `{"showAvgPrice": True}` incorrectly, it doesn't work, or it's not what I think it is.

Would passing that parameter give me what I'm looking for? Is so, why doesn't it work, and if not, is there a way to get the "Avg open price" or the "Break-even price" for open positions?

Thanks!

**Comment by kroitor** [comment]
Hi!

We have added the support for `showAvgPrice` in CCXT 1.53.33, the new build will arrive in ~20 minutes. Please, the lib to the newest version, make sure it's 1.53.33+, then use this code:

```Python
symbols = None
params = {"showAvgPrice": True}
all_positions = ftx.fetchPositions(symbols, params)
```

**Comment by nickpagz** [comment]
a thousand kudos to you mate! 

Works perfectly :smiley:
