### ISSUE TITLE
OKEX v3 API missing endpoints

### ISSUE THREAD

**Issue by Darren199612** [ccxt/ccxt#9617]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:win10
- Programming Language version:python
- CCXT version:1.53.42

there is no implicit api for this in okex:
https://www.okex.com/docs/zh/#information-taker

api like these:
GET/api/information/v3/<currency>/taker
GET/api/information/v3/<currency>/sentiment
```
okex_api = ccxt.okex()
dir(okex_api)
# cant find any word like sentiment
```

```
```

**Comment by kroitor** [comment]
@Darren199612 thank you! Will add these endpoints shortly!

**Comment by frosty00** [comment]
> api like these:
> GET/api/information/v3//taker
> GET/api/information/v3//sentiment
> 
> ```
> okex_api = ccxt.okex()
> dir(okex_api)
> # cant find any word like sentiment
> ```

ccxt.okex is now the v5 api, so to instantiate okex v3 you need to do:

```
okex = ccxt.okex3()
```

**Comment by kroitor** [comment]
@frosty00 i have a commit for those, will push soon.
