### ISSUE TITLE
Bittrex OHLCV fetching problems

### ISSUE THREAD

**Issue by hunsnowboarder** [ccxt/ccxt#962]
- OS: Win7
- Programming Language: Python 2.7
- CCXT version: 10.477
- Exchange: Bittrex
- Method: fetch_ohlcv()

First of all thank you so much for the work you are doing! It is an amazing tool you guys created!

My problem is that I cant fetch OHLCV data for only the last day. No matter if I use since (code below) or not I will still get 5760 length for the OHLCV.
Why am I getting always all the candle data and not only the ones for the last day?

Thank you in advance for your help!

```
since = xchange.milliseconds() - 1 * 86400000 
limit = 2
my_data = xchange.fetch_ohlcv("ETH/BTC", '5m', since, limit)
print len(my_data)
print my_data
```

**Comment by kroitor** [comment]
This one looks strange, as if since and limit are None...

Here's what I have on Mac:

```shell
mbp:python igorkroitor$ python
Python 2.7.13 (default, Jun  5 2017, 10:04:07) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
```
```Python
>>> import ccxt
>>> exchange = ccxt.bittrex()
>>> since = exchange.milliseconds () - 86400000
>>> limit = 2
>>> data = exchange.fetch_ohlcv('ETH/BTC', '5m', since, limit)

>>> len(data)
2  # ←------------------ proper filtering, worked...

>>> [exchange.iso8601(candle[0]) for candle in data]
['2017-12-25T05:35:00.000Z', '2017-12-25T05:40:00.000Z']

>>> print(data)
[[1514180100000, 0.0518674, 0.05186742, 0.05153272, 0.05169228, 181.76694689], [1514180400000, 0.05169227, 0.0519, 0.051541, 0.05165, 231.32179279]]

>>> ccxt.__version__
'1.10.477'

>>> #                                   ↓ this is a proof of proper limit=2 filtering
>>> exchange.last_http_response # ←------------ last response contains 5760 candles
u'{"success":true,"message":"","result":[    
{"O":0.03605219,"H":0.03621868,"L":0.03605219,"C":0.03612818,"V":203.61919193,"T":"2017-12-06T05:35:00","BV":7.35361982},
{"O":0.03612818,"H":0.03621060,"L":0.03611001,"C":0.03612000,"V":483.19784217,"T":"2017-12-06T05:40:00","BV":17.46557084},
{"O":0.03611026,"H":0.03618283,"L":0.03611026,"C":0.03611027,"V":349.73663942,"T":"2017-12-06T05:45:00","BV":12.63578882},
{"O":0.03611027,"H":0.03621906,"L":0.03606101,"C":0.03609623,"V":250.87983358,"T":"2017-12-06T05:50:00","BV":9.06390131},
{"O":0.03607774,"H":0.03621905,"L":0.03598732,"C":0.03598732,"V":739.96709428,"T":"2017-12-06T05:55:00","BV":26.69147154},
{"O":0.03598429,"H":0.03607774,"L":0.03580000,"C":0.03588882,"V":805.96461560,"T":"2017-12-06T06:00:00","BV":28.97289536},
{"O":0.03588882,"H":0.03607634,"L":0.03572000,"C":0.03596212,"V":811.98497464,"T":"2017-12-06T06:05:00","BV":29.09296835},
...
```

**Comment by kroitor** [comment]
>My problem is that I cant fetch OHLCV data for only the last day. 

If you think of it carefully... 5760 * 5 minutes = 28800 minutes = 20 days. Whenever you fetch 5m-OHLCV from Bittrex, it will return last twenty days of history. This is why without any filtering you will see 2017-12-06 as the first date in the first candle (look at `.last_http_response` in my post above).

With filtering since last day (milliseconds - 86400000), you will see the first candle starting from 2017-12-25 (yesterday), -24 hours from now (look around `print(data)` in the above post).

With filtering since last day + limiting up to 2 candles, you will get two candles, starting from yesterday, -24 hours from now, each one representing 5 minutes, which is again clearly visible in my above post.

> No matter if I use since (code below) or not I will still get 5760 length for the OHLCV.

Bittrex will always return the same amount of 5760 candles and the filtering is done in ccxt on client-side. So after ccxt gets 5760 candles, it will filter by since and limit down to 2 candles.

> Why am I getting always all the candle data and not only the ones for the last day?

I guess, you're not filtering them or not interpreting the results correctly?

**Comment by hunsnowboarder** [comment]
Thank you very much for your reply.

...so I have two questions now. :)
1) You wrote that the filtering is done a client side. So there is no other option to decrease the size on server side? I am asking this because I go through all of the coins searching for candle patterns. I am really looking for the last 5 candles, therefore I do no care about the data before... But going through all of the coins takes almost 10 mins. Is there a way to retrieve OHLCV data faster, or without getting all the data back till the beginnig?

2) The code is still not working for me.

```
import ccxt
exchange = ccxt.bittrex()
since = exchange.milliseconds () - 86400000
limit = 2
print limit, since
data = exchange.fetch_ohlcv('ETH/BTC', '5m', since, limit)
print len(data)
```

Result:

2 1514181924752
5760
Process finished with exit code 0

Thank you very much in advance!

**Comment by kroitor** [comment]
> You wrote that the filtering is done a client side. So there is no other option to decrease the size on server side? 

Not for Bittrex. They don't have an option for filtering, I'm afraid. They don't have OHLCV in their API at all, and we are using their v2 undocumented web API to fetch their OHLCV at least somehow. So, while most exchanges allow filtering on server side, Bittrex does not and we have to do it on client side.

> I am asking this because I go through all of the coins searching for candle patterns. I am really looking for the last 5 candles, therefore I do no care about the data before... But going through all of the coins takes almost 10 mins. Is there a way to retrieve OHLCV data faster, or without getting all the data back till the beginnig?

There is an alternative: fetch trades for last 10 minutes and build OHLCV from trades (#751, #859, #894). However, last 10 minutes of trades might contain even more data on Bittrex... So, I can't say which one is faster right away.

> The code is still not working for me.

Can you run my sequence of commands to make it more clear, with versions, which dates are output, etc?

**Comment by hunsnowboarder** [comment]
Sorry for my late reply. I had very strange issues and finally figured out what the problem was. I did not update ccxt for a while now only some of the exchanges. 

So I did a thorough update of everything and now it works like a charm. Thank you again for your continuous support and help! Have a happy new year!

**Comment by kroitor** [comment]
@hunsnowboarder thanks for reporting back! Happy holidays!
