### ISSUE TITLE
OKEx incorrect handling of WS keep alive pings

### ISSUE THREAD

**Issue by hjastenger** [ccxt/ccxt#9620]
- OS: NIX
- Programming Language version: Python 3.9
- CCXT version: 0.7.2

The websocket is occasionally closing due to a missed pong. If im not mistaken, for OKEx this should mean that the server didn't respond within 5 seconds (https://www.okex.com/docs/en/#spot_ws-limit). I get the idea this logic isn't supported by looking at the aiohttp_client.

```
now = Exchange.milliseconds()
            self.lastPong = now if self.lastPong is None else self.lastPong
            if (self.lastPong + self.keepAlive * self.maxPingPongMisses) < now:
                self.on_error(RequestTimeout('Connection to ' + self.url + ' timed out due to a ping-pong keepalive missing on time'))
```
Shouldn't this be the timing from last PING to current ts, not PONG? Since that window shouldn't exceed 5 seconds, right now that is going to be compared to self.keepAlive * self.maxPingPongMisses = 2000 * 2 = 4000ms. From docs I get the impression that this timing window should be 30 seconds, is that being enforced?

```
client = ccxtpro.okex3({
            'options': {
                'defaultType': 'swap',
                'newUpdates': True
            }
})
client.watch_order_book(symbol='BTC-USDT-SWAP')
```

```
Connection to wss://wsaws.okex.com:8443/ws/v3 timed out due to a ping-pong keepalive missing on time
```

**Comment by kroitor** [comment]
Hi! Please, upgrade to CCXT Pro to version 0.7.75+, we have added the support for okex v5 to it. Let us know if you have the same issues with it.

**Comment by kroitor** [comment]
@hjastenger can you paste a minimal complete working snippet of code to reproduce it (without your keys but including the instantiation)?
