### ISSUE TITLE
Average break even price of a position for FTX

### ISSUE THREAD

**Issue by playerone2000** [ccxt/ccxt#9622]
Hi,

Is there anyway to get the average break-even price of an active future positon?   The entryprice figure that is obtained from fetchposition is actually always the latest market price? 

Thanks

**Comment by m-thomson** [comment]
I faced the same problem by just found this closed issue: 

https://github.com/ccxt/ccxt/issues/9608

This seems to be just recently implemented and the solution described there worked for me: Look for 'recentPnl' and 'recentBreakEvenPrice' returned from `ftx.fetchPositions()` called with the 'showAvgPrice' option.

**Comment by playerone2000** [comment]
> I faced the same problem but just found this closed issue:
> 
> #9608
> 
> This seems to be just recently implemented and the solution described there worked for me: Look for 'recentPnl' and 'recentBreakEvenPrice' returned from `ftx.fetchPositions()` called with the 'showAvgPrice' option.

Thank you for sharing!
