### ISSUE TITLE
watch_balance hangs and does not return data

### ISSUE THREAD

**Issue by Prometheus3142** [ccxt/ccxt#9625]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Debian 10
- Programming Language version: Python 3.7
- CCXT version: 0.7.75

```
import ccxtpro
import asyncio

async def watch_order(loop):
    
    exchange = ccxtpro.binance({'enableRateLimit': True, 'asyncio_loop': loop, 'newUpdates': True, 'verbose': True, 'apiKey': 'myApiKey', 'secret': 'mySecret'})
    params = {}
    
    if exchange.has['watchBalance']:
        while True:
            try:
                print('got to await balance')
                balance = await exchange.watch_balance(params)
                print(exchange.iso8601(exchange.milliseconds()), balance)
            except Exception as e:
                print(e)
                # stop the loop on exception or leave it commented to retry
                # raise e

loop = asyncio.new_event_loop()
loop.run_until_complete(watch_order(loop))
```

```
python3 test_balance.py 
got to await balance

```
Program seems to work but hangs on watch_balance. fetch_balance works fine..... Not sure if it only returns data when there is a change. Any info would be appreciated.

**Comment by kroitor** [comment]
> Not sure if it only returns data when there is a change.

That's exactly how it works, it will return a value when your balance changes. Try launching the same snippet, then go to the exchange's web ui and place/cancel some orders. Hope that answers your question, let us know if not.
