### ISSUE TITLE
BITFINEX new endpoint

### ISSUE THREAD

**Issue by Darren199612** [ccxt/ccxt#9626]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Win10
- Programming Language version: python
- CCXT version: 1.52.64

```
Some new endpoint in bitfnex
https://api-pub.bitfinex.com/v2/funding/stats/Symbol/hist
https://api-pub.bitfinex.com/v2/pulse/hist
https://api-pub.bitfinex.com/v2/pulse/profile/Nickname
```

**Comment by kroitor** [comment]
Will add those shortly, thx for your feedback!
