### ISSUE TITLE
Bitstamp withdraw function

### ISSUE THREAD

**Issue by pmizel** [ccxt/ccxt#963]
Bitstamp exchnage don't implement a withdraw function.

when is ok, i will create a pr.

- OS: Win
- Programming Language: Node/JavaScript
- CCXT version: 1.10.477
- Exchange: Bitstamp
- Method: withdraw

```
↑↑↑ DO_NOT_DELETE_THE_BACKTICKS_AROUND_THE_CODE

MUST_READ_THIS https://github.com/kroitor/ccxt/wiki/Manual#troubleshooting

↓↓↓ DO_NOT_DELETE_THE_BACKTICKS_AROUND_THE_CODE
```

**Comment by kroitor** [comment]
Hi!

Thanks for your contribution! Unfortunately, it break a few several rules from here: 
https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#derived-exchange-classes

If you could clean it up a bit to conform to those transpilation rules, you would make it much easier for me to merge it. Let me know, if you're going to give it a try. Thx again!

Also related/duplicate to: #777.
