### ISSUE TITLE
create_market_buy_order became very slow after version upgrade. 

### ISSUE THREAD

**Issue by chulwoohan** [ccxt/ccxt#9636]
I recently upgraded the version of ccxt and submitting orders using the function 'create_market_buy_order' or getting the order status using 'fetch_order' became noticeably slow (about 0.5 sec for each call). I am trading futures on Binance. I don't remember the previous version but the last time I upgraded the version was when an order for BTCUSDT or ETHUSDT was trading quarterly futures, not perpetual futures. Have there been any changes in the package?

**Comment by kroitor** [comment]
> Have there been any changes in the package?

That is hard to tell, without your code to reproduce it and your verbose output: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help – can you post those details?

> Have there been any changes in the package?

There were some changes, but CCXT never used BTCUSDT or ETHUSDT, the unified symbols are BTC/USDT and ETH/USDT and those are mapped to perpetuals, if you're trading futures on Binance: https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

**Comment by chulwoohan** [comment]
The code is as follows:
    binace = ccxt.binance(
        {'apiKey': key,
         'secret': secret,
         'options': {'defaultType': 'future'}}
    )
    binance.verbose = True
    symbol = 'ADA/USDT'
    qty = 1
    response0 = binance.create_market_buy_order(symbol, 1)

The output is as below. I noticed that 'exchangeinfo' is called before order is submitted. Perhaps this is what makes it slow?

Request: GET https://fapi.binance.com/fapi/v1/exchangeInfo {'User-Agent': 'python-requests/2.24.0', 'Accept-Encoding': 'gzip, deflate'} None
Response: GET https://fapi.binance.com/fapi/v1/exchangeInfo 200 {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Fri, 23 Jul 2021 07:59:49 GMT', 'Server': 'Tengine', 'X-MBX-USED-WEIGHT-1M': '550', 'x-response-time': '0ms', 'Access-Control-Allow-Origin': '*', 
...
pe":"PERCENT_PRICE"}],"orderTypes":["LIMIT","MARKET","STOP","STOP_MARKET","TAKE_PROFIT","TAKE_PROFIT_MARKET","TRAILING_STOP_MARKET"],"timeInForce":["GTC","IOC","FOK","GTX"]}]}

Request: POST https://fapi.binance.com/fapi/v1/order {'X-MBX-APIKEY': 'LfRirLzZsugfhsHtyvqBkyQSJjdI2ORhTbiDxUNItR2mQLWAYmmA0PUcENQDnHAg', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.24.0', 'Accept-Encoding': 'gzip, deflate'} timestamp=1627027190355&recvWindow=5000&symbol=ADAUSDT&type=MARKET&side=BUY&newClientOrderId=x-xcKtGhcu91238523122954665bb03e&newOrderRespType=RESULT&quantity=1&signature=3959b4ec1f65ba4de030b65d2c8e4e8898d9f7906d86eadbaab5252128727d60
Response: POST https://fapi.binance.com/fapi/v1/order 400 {'Content-Type': 'application/json', 'Content-Length': '99', 'Connection': 'keep-alive', 'Date': 'Fri, 23 Jul 2021 07:59:50 GMT', 'Server': 'Tengine', 'X-MBX-USED-WEIGHT-1M': '551', 'X-MBX-ORDER-COUNT-10S': '0', 'X-MBX-ORDER-COUNT-1M': '1', 'x-response-time': '1ms', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 6371e42dc4882f0fa4f731d1a82340f3.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'ICN51-C1', 'X-Amz-Cf-Id': 'WWsoI80Lv7FJNGzfD4IYGTeIAhnM_fY0kjHjGX2Gg_AjSKqV2wgPWw=='} {"code":-4164,"msg":"Order's notional must be no smaller than 5.0 (unless you choose reduce only)"}


When I said 'BTCUSDT', I meant 'BTC/USDT'. ccxt version 1.39.77 traded quarterly futures, not perpetual futures.

**Comment by kroitor** [comment]
>  When I said 'BTCUSDT', I meant 'BTC/USDT'. ccxt version 1.39.77 traded quarterly futures, not perpetual futures.

There was a transition period, when Binance updated their market info schema (it was fixed in the ccxt repo back then). That could be the cause of the symbol issue, if any. BTC/USDT stands for perpetuals, not for delivery futures.

> The output is as below. I noticed that 'exchangeinfo' is called before order is submitted. Perhaps this is what makes it slow?

It is explained here: 

- https://github.com/ccxt/ccxt/wiki/Manual#loading-markets
- https://github.com/ccxt/ccxt/wiki/Manual#notes-on-rate-limiter

If you are recreating the exchange instance before `create_market_buy_order` without reusing the exchange instance – it has to load the market info beforehand. Hope that answers your question. Let us know if not.

**Comment by chulwoohan** [comment]
Thanks for the quick reply. Actually, fetching exchange info isn't the reason. I gave you a simple example but what I actually do is to call create_market_buy_order() repeatedly for different coins after creating binance instance. So it's more like

binace = ccxt.binance(
{'apiKey': key,
'secret': secret,
'options': {'defaultType': 'future'}}
)
for symbol, qty in zip(symbols, qtys):
    response0 = binance.create_market_buy_order(symbol, qty)

And it takes about 0.5 secs for each call of create_market_buy_order().

**Comment by kroitor** [comment]
@chulwoohan try this:

```Python

exchange = ccxt.binanceusdm({
    'apiKey': key,
    'secret': secret,
})

started_loading = exchange.milliseconds()
markets = exchange.load_markets()
ended_loading = exchange.milliseconds()
print('Loaded markets in', ended_loading - started_loading, 'ms')
exchange.verbose = True
for symbol, qty in zip(symbols, qtys):
    started_ordering = exchange.milliseconds()
    response = exchange.create_market_buy_order(symbol, qty)
    ended_ordering = exchange.milliseconds()
    print('Placed an order in', ended_ordering - started_ordering, 'ms')
```

Please, paste your verbose output here.

> And it takes about 0.5 secs for each call of create_market_buy_order().

That can depend on your location or "network distance" from Binance's servers, but it's hard to tell without seeing the complete profiling log.

**Comment by chulwoohan** [comment]
Below is the output. I tried submitting an order without using ccxt and it's almost immediate. So the network isn't an issue. Also, it became slow after the recent upgrade. Never had this issue before.

Loaded markets in 206 ms
Request: POST https://fapi.binance.com/fapi/v1/order {'X-MBX-APIKEY': 'LfRirLzZsugfhsHtyvqBkyQSJjdI2ORhTbiDxUNItR2mQLWAYmmA0PUcENQDnHAg', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.24.0', 'Accept-Encoding': 'gzip, deflate'} timestamp=1627029843309&recvWindow=5000&symbol=ADAUSDT&type=MARKET&side=BUY&newClientOrderId=x-xcKtGhcu335efcf1406b7b6139fb1b&newOrderRespType=RESULT&quantity=5&signature=0becc2954d0feecf29a06627998424ad53d808162e61a936f95aa1ca47ec2116
Response: POST https://fapi.binance.com/fapi/v1/order 200 {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Fri, 23 Jul 2021 08:44:03 GMT', 'Server': 'Tengine', 'Vary': 'Accept-Encoding', 'X-MBX-USED-WEIGHT-1M': '72', 'X-MBX-ORDER-COUNT-10S': '0', 'X-MBX-ORDER-COUNT-1M': '1', 'x-response-time': '3ms', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': '*,clienttype,Content-Type,lang,x-ui-request-trace,bnc-uuid', 'Content-Security-Policy': "default-src 'self'", 'cache-control': 'no-cache, no-store, must-revalidate', 'expires': '0', 'pragma': 'no-cache', 'strict-transport-security': 'max-age=31536000; includeSubdomains', 'x-content-type-options': 'nosniff', 'x-frame-options': 'SAMEORIGIN', 'x-xss-protection': '1; mode=block', 'Content-Encoding': 'gzip', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 26c873e20c5c3f54394cc9e2a6195da4.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'ICN51-C1', 'X-Amz-Cf-Id': 'xwkHOe_nJwjB2OCPgMvNmCOz_zWh2bx9cxDMKNnIC3WBMjbeAFf-Tw=='} {"orderId":15070583291,"symbol":"ADAUSDT","status":"FILLED","clientOrderId":"x-xcKtGhcu335efcf1406b7b6139fb1b","price":"0","avgPrice":"1.18330","origQty":"5","executedQty":"5","cumQty":"5","cumQuote":"5.91650","timeInForce":"GTC","type":"MARKET","reduceOnly":false,"closePosition":false,"side":"BUY","positionSide":"BOTH","stopPrice":"0","workingType":"CONTRACT_PRICE","priceProtect":false,"origType":"MARKET","updateTime":1627029843268}
Placed an order in 337 ms
Request: POST https://fapi.binance.com/fapi/v1/order {'X-MBX-APIKEY': 'LfRirLzZsugfhsHtyvqBkyQSJjdI2ORhTbiDxUNItR2mQLWAYmmA0PUcENQDnHAg', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.24.0', 'Accept-Encoding': 'gzip, deflate'} timestamp=1627029843810&recvWindow=5000&symbol=ALGOUSDT&type=MARKET&side=BUY&newClientOrderId=x-xcKtGhcue9660856752872f67d1767&newOrderRespType=RESULT&quantity=7&signature=e117e1ecc78d0979053bd7fd4a69734234e686332a5a073326c30c3475c31727
Response: POST https://fapi.binance.com/fapi/v1/order 200 {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Fri, 23 Jul 2021 08:44:03 GMT', 'Server': 'Tengine', 'Vary': 'Accept-Encoding', 'X-MBX-USED-WEIGHT-1M': '79', 'X-MBX-ORDER-COUNT-10S': '1', 'X-MBX-ORDER-COUNT-1M': '2', 'x-response-time': '5ms', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': '*,clienttype,Content-Type,lang,x-ui-request-trace,bnc-uuid', 'Content-Security-Policy': "default-src 'self'", 'cache-control': 'no-cache, no-store, must-revalidate', 'expires': '0', 'pragma': 'no-cache', 'strict-transport-security': 'max-age=31536000; includeSubdomains', 'x-content-type-options': 'nosniff', 'x-frame-options': 'SAMEORIGIN', 'x-xss-protection': '1; mode=block', 'Content-Encoding': 'gzip', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 26c873e20c5c3f54394cc9e2a6195da4.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'ICN51-C1', 'X-Amz-Cf-Id': '81lzvVCojMHYO4O56l2FmUA6v9-B2WNqeBxd_N6DAX3gO8CiG1tNLg=='} {"orderId":2634769457,"symbol":"ALGOUSDT","status":"FILLED","clientOrderId":"x-xcKtGhcue9660856752872f67d1767","price":"0","avgPrice":"0.79230","origQty":"7","executedQty":"7","cumQty":"7","cumQuote":"5.54610","timeInForce":"GTC","type":"MARKET","reduceOnly":false,"closePosition":false,"side":"BUY","positionSide":"BOTH","stopPrice":"0","workingType":"CONTRACT_PRICE","priceProtect":false,"origType":"MARKET","updateTime":1627029843771}
Placed an order in 504 ms

**Comment by kroitor** [comment]
CCXT uses the `'newOrderRespType': 'RESULT'` by default, which, upon placing the order, will wait till the order is filled, and then will return the result. If you don't want it to wait and you want it to return immediately, regardless of the state of the order, then you can change the `newOrderRespType` to `'ACK'`:

```Python
exchange = ccxt.binanceusdm({
    'apiKey': key,
    'secret': secret,
})

started_loading = exchange.milliseconds()
markets = exchange.load_markets()
ended_loading = exchange.milliseconds()
print('Loaded markets in', ended_loading - started_loading, 'ms')
exchange.verbose = True
for symbol, qty in zip(symbols, qtys):
    started_ordering = exchange.milliseconds()
    params = {'newOrderRespType': 'ACK'}  # <--------------------------------------- HERE
    response = exchange.create_market_buy_order(symbol, qty, params)  # <----------- HERE
    ended_ordering = exchange.milliseconds()
    print('Placed an order in', ended_ordering - started_ordering, 'ms')
```

Let us know if the above does not help or does not answer your question.

**Comment by chulwoohan** [comment]
Just tried it. Don't think that solves the problem.

Loaded markets in 108 ms
Request: POST https://fapi.binance.com/fapi/v1/order {'X-MBX-APIKEY': 'LfRirLzZsugfhsHtyvqBkyQSJjdI2ORhTbiDxUNItR2mQLWAYmmA0PUcENQDnHAg', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.24.0', 'Accept-Encoding': 'gzip, deflate'} timestamp=1627030904468&recvWindow=5000&symbol=ADAUSDT&type=MARKET&side=BUY&newClientOrderId=x-xcKtGhcudad256ab3a5351112742a6&newOrderRespType=ACK&quantity=5&signature=e1d2171ee3a2a56462bda82faa05dcdd22a1b5b58b93a79151cc156b907352ae
Response: POST https://fapi.binance.com/fapi/v1/order 200 {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Fri, 23 Jul 2021 09:01:44 GMT', 'Server': 'Tengine', 'Vary': 'Accept-Encoding', 'X-MBX-USED-WEIGHT-1M': '617', 'X-MBX-ORDER-COUNT-10S': '0', 'X-MBX-ORDER-COUNT-1M': '1', 'x-response-time': '4ms', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': '*,clienttype,Content-Type,lang,x-ui-request-trace,bnc-uuid', 'Content-Security-Policy': "default-src 'self'", 'cache-control': 'no-cache, no-store, must-revalidate', 'expires': '0', 'pragma': 'no-cache', 'strict-transport-security': 'max-age=31536000; includeSubdomains', 'x-content-type-options': 'nosniff', 'x-frame-options': 'SAMEORIGIN', 'x-xss-protection': '1; mode=block', 'Content-Encoding': 'gzip', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 e67bc999d3ae69aeca2e64717fe718be.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'ICN51-C1', 'X-Amz-Cf-Id': 'wINDVw1AMGeW39qIaSziM8QLRJuQ_-t68E4ln221rcINFm__LCORGQ=='} {"orderId":15070814545,"symbol":"ADAUSDT","status":"NEW","clientOrderId":"x-xcKtGhcudad256ab3a5351112742a6","price":"0","avgPrice":"0.00000","origQty":"5","executedQty":"0","cumQty":"0","cumQuote":"0","timeInForce":"GTC","type":"MARKET","reduceOnly":false,"closePosition":false,"side":"BUY","positionSide":"BOTH","stopPrice":"0","workingType":"CONTRACT_PRICE","priceProtect":false,"origType":"MARKET","updateTime":1627030904429}
Placed an order in 440 ms
Request: POST https://fapi.binance.com/fapi/v1/order {'X-MBX-APIKEY': 'LfRirLzZsugfhsHtyvqBkyQSJjdI2ORhTbiDxUNItR2mQLWAYmmA0PUcENQDnHAg', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.24.0', 'Accept-Encoding': 'gzip, deflate'} timestamp=1627030904969&recvWindow=5000&symbol=ALGOUSDT&type=MARKET&side=BUY&newClientOrderId=x-xcKtGhcu7d02415241f7dd5d8459fb&newOrderRespType=ACK&quantity=7&signature=d72d6b68221b181d087098ec71b7d3122e82094aba91334ceb46a856dbaed9c6
Response: POST https://fapi.binance.com/fapi/v1/order 200 {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Fri, 23 Jul 2021 09:01:44 GMT', 'Server': 'Tengine', 'Vary': 'Accept-Encoding', 'X-MBX-USED-WEIGHT-1M': '630', 'X-MBX-ORDER-COUNT-10S': '1', 'X-MBX-ORDER-COUNT-1M': '2', 'x-response-time': '3ms', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': '*,clienttype,Content-Type,lang,x-ui-request-trace,bnc-uuid', 'Content-Security-Policy': "default-src 'self'", 'cache-control': 'no-cache, no-store, must-revalidate', 'expires': '0', 'pragma': 'no-cache', 'strict-transport-security': 'max-age=31536000; includeSubdomains', 'x-content-type-options': 'nosniff', 'x-frame-options': 'SAMEORIGIN', 'x-xss-protection': '1; mode=block', 'Content-Encoding': 'gzip', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 e67bc999d3ae69aeca2e64717fe718be.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'ICN51-C1', 'X-Amz-Cf-Id': 'ErmwZNg8FdNf4ZwKNTLKqHJ34SxkKV4gtHn8bHx7tHDGO8irup2XrQ=='} {"orderId":2634834814,"symbol":"ALGOUSDT","status":"NEW","clientOrderId":"x-xcKtGhcu7d02415241f7dd5d8459fb","price":"0","avgPrice":"0.00000","origQty":"7","executedQty":"0","cumQty":"0","cumQuote":"0","timeInForce":"GTC","type":"MARKET","reduceOnly":false,"closePosition":false,"side":"BUY","positionSide":"BOTH","stopPrice":"0","workingType":"CONTRACT_PRICE","priceProtect":false,"origType":"MARKET","updateTime":1627030904927}
Placed an order in 497 ms

**Comment by kroitor** [comment]
@chulwoohan those are not communication delays, those are rate-limiter delays, CCXT uses a built-in rate-limiter by default, which is documented in the Manual: 

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/wiki/Manual#notes-on-rate-limiter

Before CCXT 1.39, the rate-limiter was disabled by default and you had to enable it manually (apparently, you have not used it). After CCXR 1.39, the rate limiter is enabled by default, so if you want to disable it, you have to add one more line to your code. You can disable the built-in rate limiter, but be aware that if you switch the rate limiting off, the exchange may ban you for too many aggressive requests in a short period of time:

```Python
exchange = ccxt.binanceusdm({
    'apiKey': key,
    'secret': secret,
    'enableRateLimit': False,  # <------------------------------ HERE
})

started_loading = exchange.milliseconds()
markets = exchange.load_markets()
ended_loading = exchange.milliseconds()
print('Loaded markets in', ended_loading - started_loading, 'ms')
exchange.verbose = True
for symbol, qty in zip(symbols, qtys):
    started_ordering = exchange.milliseconds()
    params = {'newOrderRespType': 'ACK'}  # <--------------------------------------- HERE
    response = exchange.create_market_buy_order(symbol, qty, params)  # <----------- HERE
    ended_ordering = exchange.milliseconds()
    print('Placed an order in', ended_ordering - started_ordering, 'ms')
```

**Comment by chulwoohan** [comment]
That solved the problem. I guessed ccxt was intentionally waiting internally in the newer version, but couldn't find change logs. Thanks.
