### ISSUE TITLE
Fetch ETH positions and balance on deribit

### ISSUE THREAD

**Issue by aceffer** [ccxt/ccxt#9642]
- OS: Windows 10
- Programming Language version: Python
- CCXT version: 1.53.60

On deribit, one must specify the currency of which one requests balance and positions. For further details, see [https://docs.deribit.com/#private-get_positions](https://docs.deribit.com/#private-get_positions) and [https://docs.deribit.com/#private-get_account_summary](https://docs.deribit.com/#private-get_account_summary). In the ccxt implementation "BTC" is hard-coded, so it is not possible to fetch ETH (and USDT) balance and positions.

**Comment by kroitor** [comment]
Duplicate:

- https://github.com/ccxt/ccxt/issues/6533#issuecomment-592150682
- https://github.com/ccxt/ccxt/issues?q=deribit+eth

**Comment by kroitor** [comment]
P.S. It's not hardcoded and you can override it how you want, as shown in the issues linked above.
