### ISSUE TITLE
New Exchange: ChainEX

### ISSUE THREAD

**Issue by end-debug** [ccxt/ccxt#9647]
Hi,
I would like Coinbene and chainex to be added to ccxt.

Official Website - https://www.coinbene.com/
                          - https://chainex.io/
Here is the API documentation for their exchange - https://www.coinbene.com/exchange-openapi-rest.html#basic-information
                                                                                - https://chainex.io/api

**Comment by kroitor** [comment]
You can help test Coinbene here:

- https://github.com/ccxt/ccxt/pull/8124
- https://github.com/ccxt/ccxt/pull/6388
- https://github.com/ccxt/ccxt/issues/2162

**Comment by end-debug** [comment]
ok will try my best, still new to all this coding

**Comment by ttodua** [comment]
Coinbene was shut down.

**Comment by frosty00** [comment]
chainex has no volume, so neither exchanges will get added soon
