### ISSUE TITLE
BadSymbol: binanceusdm does not have market symbol

### ISSUE THREAD

**Issue by JonBlue** [ccxt/ccxt#9661]
OS: win 10
Programming Language version: typescript 4.1.6 with angular 11.1.4
CCXT version: 1.53.71 with ccxtpro 0.7.83

This happens regardless of the symbol I'm trying to watch

```
this.ethTicker = await this.tradeService.binance.watchTicker( 'ETH/BTC')

```
Error: 
`BadSymbol: binanceusdm does not have market symbol ETH/BTC`

**Comment by frosty00** [comment]
right, you are using binanceusdm, you should be using `ccxtpro.binance` instead, let us know if this doesn't solve the problem

**Comment by JonBlue** [comment]
Sorry if I don't understand. I need to watch symbols and trade with binance USDⓈ-M Futures Perpetual only. Should I not be using binanceusdm?

Currently instantiating a new exchange like. Should I do it diffferently if I want to use the binance futures api? 
https://binance-docs.github.io/apidocs/futures/en/#change-log

```
new ccxt.binanceusdm({
      apiKey: apiKey,
      secret: apiSecret
      proxy: // my proxy
    });
```

**Comment by kroitor** [comment]
@JonBlue there is no Binance USDM perpetual ETH/BTC contract. Binance USDM are USDT-margined. So, all contracts with Binance USDM involve USDT.

If you want to trade Binance ETH/USDT perpetual:

```Python
new ccxt.binanceusdm({
      apiKey: apiKey,
      secret: apiSecret
      proxy: // my proxy
});
```

If you want to trade Binance ETH/BTC spot:

```Python
new ccxt.binance({
      apiKey: apiKey,
      secret: apiSecret
      proxy: // my proxy
});
```

Hope that answers your question. Let us know if not. Feel free to reopen this issue or just ask further questions. More info on market symbols: https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids
