### ISSUE TITLE
Specifically BTC floors down USD-M order size

### ISSUE THREAD

**Issue by Salz0** [ccxt/ccxt#9662]
- OS: W10
- Programming Language version:  Python 3.9.6
- CCXT version: "^1.52.83"

Hello, I am executing USD-M trades and have everything set up.

Ethereum is looking good, doing precisely what I send as the size.
BTC though rounds the size to the lower end always.

F.e. I see through the logs, that I've passed in  `0.00356472 BTC`, but it always floors it down to `0.003 BTC`
The leverage and everything is set correctly, 

I use the `currency_to_precision` function for the sizes and it all doesn't do what I want specifically for BTC

**Comment by kroitor** [comment]
@Salz0 hi! This is documented in the Manual, amounts are truncated, prices are rounded:

- https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits

You can round-up in userland how you want. Let us know if that does not answer your question.
