### ISSUE TITLE
Breaking Change: Removing hardcoded withdrawal fees

### ISSUE THREAD

**Issue by kroitor** [ccxt/ccxt#9676]
Good news, everyone!

CCXT will drop the support for hardcoded withdrawal fees and will replace that with unified methods for fetching funding fees  from the underlying exchange APIs directly (`fetchFundingFees`, `loadFundingFees`, `loadFees`, etc). Most of those settings are outdated anyway, relying on them is a bad idea, so, it's not a huge loss. Moreover hardcoding is not the best practice in general, we believe that removing those outdated lines will help improve this library further.

The related Pull Request is here: 

- https://github.com/ccxt/ccxt/pull/9671

The change will be added before CCXT 1.54+

Thanks for using CCXT!

**Comment by ndubel** [comment]
Why ccxt doesn't call `loadMarkets()` before `fetchFundingFees/fetchFundingFee`? For example in kucoin or stex. It's not possible to parse request/response correctly without it

**Comment by ttodua** [comment]
Right changes.

**Comment by ndubel** [comment]
There is confusion in `fetchFundingFees` response structure. Most of exchanges has different withdrawal network for example for USDT. So all examples for USDT `response['withdraw']['USDT']`.

On Binance withdraw USDT: 
`{ BNB: 1, BSC: 0.8, ETH: 10, OMNI: 0, TRX: 1 }`
So in this case we use TRX network for withdraw but we pay fee in USDT.

On CREX24: 
`{  BTC: 0.00032,  ETH: 0.0054,  DOGE: 64.65977,  LTC: 0.0919,  BCH: 0.02442,  USDT: 13.176,  USDC: 13.1722,  TRX: 205.61806,  EOS: 3.26612 }`
In this case we use ETH (ERC-20) network but pay fee in BTC, ETH, etc
CREX24 also has an opportunity to withdraw via TRC-20 and BSC but there is nothing about it in their API.

On Bitstamp:
`2.5`
In this case we only get withdrawal cost,

I don't found an example in current ccxt implementations but it also possible when exchange gives only blockchain names and response will be something like that:
`{ TRC20: 1, ERC20: 10 }`

Maybe we need more complex structure for this `fetchFundingFees` that will consider both fee currency and blockchain name

**Comment by kroitor** [comment]
@ndubel yes, we are working on unifying the `network` aspect for addresses of the same currency on different networks, and will incorporate network into the structure.
