### ISSUE TITLE
[help] CCXT: How to fetch binance's current timestamp value?

### ISSUE THREAD

**Issue by avatar-lavventura** [ccxt/ccxt#9678]
- OS: `Ubuntu 20.04.2 LTS`
- Programming Language version:  `Python 3.8.10`
- CCXT version: `ccxt==1.53.71`

-------------------

I was wondering would it be possible to fetch exchange's latest/current timestamp value?

my code:

```
class Exchange:
    def __init__(self):        
        ops = {
            "apiKey": api_key,
            "secret": api_secret,
            "options": {"adustForTimeDifference": True},
            # "verbose": True,  # for debug output
        }
        self.future: Final = ccxt.binanceusdm(ops)


exchange = Exchange()
await exchange.future.get_timestamp()  # <== would it be possible, or which can function can achieve it
```

PS: I am sorry if this question is basic.

**Comment by kroitor** [comment]
> I was wondering would it be possible to fetch exchange's latest/current timestamp value?

There are methods like `fetchTime()` for this. That is one way of fetching the timestamp from the exchange.

If the exchange sends that info in the balance API response – CCXT will propagate it to you. Binance does not send a timestamp with the balance response. However, you can still fetch the timestamp of the most recent response from HTTP headers:

```Python
import ccxt
from pprint import pprint
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.binanceusdm({
    "apiKey": "YOUR_API_KEY",
    "secret": "YOUR_SECRET"
})
markets = exchange.load_markets()
balance = exchange.fetch_balance()
print(exchange.last_response_headers['Date'])
```

Hope that answers your question. Let us know if not.

**Comment by avatar-lavventura** [comment]
This is smart approach! Can we convert `Date` into `timestamp`?

**Comment by kroitor** [comment]
- https://stackoverflow.com/questions/1471987/how-do-i-parse-an-http-date-string-in-python
- https://stackoverflow.com/questions/6999726/how-can-i-convert-a-datetime-object-to-milliseconds-since-epoch-unix-time-in-p

```Python
from email.utils import parsedate
from datetime import datetime
import ccxt
from pprint import pprint
print('CCXT Version:', ccxt.__version__)
exchange = ccxt.binanceusdm({
    "apiKey": "YOUR_API_KEY",
    "secret": "YOUR_SECRET"
})
markets = exchange.load_markets()
print(exchange.last_response_headers['Date'])
parsed_date = parsedate(exchange.last_response_headers["Date"])
datetime_object = datetime(*parsed_date[:6])
unix_timestamp = datetime_object.timestamp()
unix_timestamp_ms = int(unix_timestamp * 1000)
print(unix_timestamp_ms)
```
