### ISSUE TITLE
Error when fetch_ticker binance php

### ISSUE THREAD

**Issue by mikaelhc86** [ccxt/ccxt#9681]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Ubuntu
- Programming Language version: PHP 7.4
- CCXT version: 1.53.51

```
$result = $exchange->fetch_ticker($symbol);
```

```
Undefined index: linear
/vendor/ccxt/ccxt/php/binance.php(1543)

1535     public function fetch_ticker($symbol, $params = array ()) {
1536         $this->load_markets();
1537         $market = $this->market($symbol);
1538         $request = array(
1539             'symbol' => $market['id'],
1540         );
1541         $method = 'publicGetTicker24hr';
1542         echo "<pre>".print_r($market)."</pre>";
1543         **if ($market['linear']) {**
```

The solution is add "if isset()" first :

        if (**isset($market['linear'])** && $market['linear']) {
            $method = 'fapiPublicGetTicker24hr';
        } else if (**isset($market['inverse'])** && $market['inverse']) {
            $method = 'dapiPublicGetTicker24hr';
        }

**Comment by kroitor** [comment]
@mikaelhc86 

> The solution is add "if isset()" first 

The thing is that both flags must always be set in the current version of CCXT. Do you have this issue with CCXT version 1.53.83?

**Comment by mikaelhc86** [comment]
I have upgrade from 1.53.51 to 1.53.83 and i'm still having same problem

**Comment by mikaelhc86** [comment]
Ups, yes, its solved.
