### ISSUE TITLE
gateio fetchOpenOrders for all pairs

### ISSUE THREAD

**Issue by ndubel** [ccxt/ccxt#9683]
- CCXT version: 1.53.84

current `fetchOpenOrders` method required `symbol` argument or we get an error `gateio does not have market symbol undefined` 
but Gate also has endpoint for all open orders: https://www.gate.io/docs/apiv4/en/index.html#list-all-open-orders
It will be cool to call this method if `symbol` is not specified

**Comment by ndubel** [comment]
it's a typo, should be `privateSpotGetOpenOrders `instead of `privateGetSpotOpenOrders`
But a bigger problem that this endpoint has a bit different response:
```
[
  {
  "currency_pair":"BTC_USDT",
  "total":1,
  "orders":[
      {"id":"65838211447","text":"apiv4"....}
    ]
  },

  {
  "currency_pair":"ETH_USDT",
  "total":2,
  "orders":
   [
      {"id":"65854761762","text":"apiv4"...}, 
      {"id":"65854759028","text":"apiv4"...}]
   ]
  }
]
```

**Comment by kroitor** [comment]
@ndubel my bad, will get back to it shortly.
