### ISSUE TITLE
binance.fetch_ohlcv not fetching correct values

### ISSUE THREAD

**Issue by memory942** [ccxt/ccxt#9686]
- OS: windows10
- Programming Language version: python 3.9
- CCXT version: 1.52.10

code : binance.fetch_ohlcv('BTC/USDT', limit=1000)

it fetches o/h/l/v values correctly but c values are wrong(i manually compared them with actual values), with only the latest 3~4 candles being correct.

even though the difference is small, it's still enough to be a potential issue. Does the pro version fix this?

**Comment by kroitor** [comment]
The data you get from fetchOHLCV is the data sent to you from the exchange API directly. We don't change those numbers, CCXT returns them to the user as is. You can verify that the data is indeed the data from the exchange in verbose mode: 
- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

Hope that answers your question, let us know if not.
