### ISSUE TITLE
Property 'BadRequest' does not exist on type 'typeof import("ccxt.pro")'

### ISSUE THREAD

**Issue by JonBlue** [ccxt/ccxt#9689]
OS: win 10
Programming Language version: typescript 4.1.6 with angular 11.1.4
CCXT version: 1.53.71 with ccxtpro 0.7.89

Getting does not exists on type errors on every instanceof Error check

I'm importing the typing in Angular like so:

`declare var ccxt: typeof import('ccxt.pro');`

and getting
```
 if (e instanceof ccxt.BadRequest) {
          throw e;
}
```

```
Property 'BadRequest' does not exist on type 'typeof import("ccxt.pro")'
```

Looking into node_modules/ccxt_pro/dist/ccxt.pro.browser.js it seems that some code is commented out. might this be the issue?

```
const ccxt = require ('ccxt')
    , { deepExtend } = ccxt
    , Exchange  = require ('./js/base/Exchange')
    , { unique } = require ('ccxt/js/base/functions')
    // , errors    = require ('ccxt/js/base/errors')
```

**Comment by kroitor** [comment]
@JonBlue the BadRequest export is placed in ccxt.d.ts, they're not in ccxt.pro.d.ts, we will probably add the error declarations to ccxt.pro.d.ts file as well. Hope that answers your question, let us know if not.
