### ISSUE TITLE
Binance fetchPositions+ parseAccountPositions - Cannot read property 'crossMargin' of undefined

### ISSUE THREAD

**Issue by gmalca** [ccxt/ccxt#9690]
This issue seems to happen more and more often.

```
Error TypeError: Cannot read property 'crossMargin' of undefined
     at binance.parseAccountPositions (/bot/node_modules/ccxt/js/binance.js:3447:46)
     at binance.fetchPositions (/bot/node_modules/ccxt/js/binance.js:3820:29)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

Restarting the system seems to fix it sometimes, so it may be a memory issue that builds up over time.  It is failing at this part:

```
            const parsed = this.parsePosition (this.extend (position, {
                'crossMargin': balances[code]['crossMargin'],
                'crossWalletBalance': balances[code]['crossWalletBalance'],
            }), market);
```

where `balances[code]` is undefined in that instance and it does not recover gracefully

**Comment by frosty00** [comment]
i've been running a loop for a few hours and it hasn't happened yet, how frequently does it happen? On binancecoinm or binanceusdm?

**Comment by gmalca** [comment]
Yes it just happened again just now at 8pm EDT.
I tried adding verbose mode to see if it helps track it down, but this is
happening way too often.
---------------------------------------------
Gabriel Malca

**Comment by smyth64** [comment]
I have the same problem. I ended up getting the positions directly from Binance API. I cannot tolerate this error because it's making my bot unreliable.

**Comment by smyth64** [comment]
Wow that was fixed quickly! Thanks man @kroitor

**Comment by kroitor** [comment]
@smyth64 all thanks to @frosty00
