### ISSUE TITLE
How to test BinanceUS API when not living in the US?

### ISSUE THREAD

**Issue by viniciussvl** [ccxt/ccxt#9692]
- OS: W10
- Programming Language version: JavaScript
- CCXT version: 1.52.5

Hello,
I'm not American and I don't live in the US, how do I test the BinanceUS API on my bot? Is her API the same as Binance.com? I looked at the documentation a bit and didn't find much difference, anyway, I would like to test this API, is it possible?

**Comment by samgermain** [comment]
You need a U.S. phone number for verification, I've talked to customer support and they don't have any advice more than this
