### ISSUE TITLE
Allcoin, wont work load_markets

### ISSUE THREAD

**Issue by mazertwo** [ccxt/ccxt#970]
Hello, ccxt team! 

Allcoin block some API commands, and now wont work load_markets().

**Comment by kroitor** [comment]
Hi! Which version do you have? https://github.com/ccxt/ccxt/pull/966

**Comment by mazertwo** [comment]
Thank you! New version working.

**Comment by kroitor** [comment]
@mazertwo thanks for reporting back as always! Happy holidays! )
