### ISSUE TITLE
KuCoin part after ? in URL included in signature calculation, causing "Invalid KC-API-SIGN" error

### ISSUE THREAD

**Issue by hansvanzutphen** [ccxt/ccxt#9702]
OS Windows 10
PHP 7.0.30
CCXT version 1.54.9
kucoin.php

Not really a bug, but something that has just cost me an hour to figure out: The KuCoin V2 API code needs to sign the API call. It does that, but if your command contains extra fields that are included after the ? in the URL, that part is used for the signature as well, which causes a "Invalid KC-API-SIGN" reply. Which is extremely confusing.

The reason that this failed on my end is that some API's require that you send extra data in a cancel_order command, so I had them included in my call (I have now explicitly removed them for KuCoin):

`exchange->cancel_order("XXXX", "SNX/BTC", array("currencyPair" => "SNX/BTC", "type" => "BUY"));`

Which generates an URL like this:

`https://openapi-v2.kucoin.com/api/v1/orders/XXXX?currencyPair=SNX%2FBTC&type=BUY`

Full verbose output:

```
Array
(
    [0] => Request:
    [1] => DELETE
    [2] => https://openapi-v2.kucoin.com/api/v1/orders/XXXX?currencyPair=SNX%2FBTC&type=BUY
    [3] => Array
        (
            [KC-API-KEY-VERSION] => 2
            [KC-API-KEY] => XXXX
            [KC-API-TIMESTAMP] => 1627684335080
            [KC-API-PASSPHRASE] => XXXX
            [KC-API-SIGN] => XXXX
        )

    [4] =>
)
Array
(
    [0] => Response:
    [1] => DELETE
    [2] => https://openapi-v2.kucoin.com/api/v1/orders/XXXX?currencyPair=SNX%2FBTC&type=BUY
    [3] => 401
    [4] =>
    [5] => Array
        (
            [Date] => Fri, 30 Jul 2021 22:32:17 GMT
            [Content-Type] => application/json
            [Content-Length] => 45
            [Connection] => keep-alive
            [Set-Cookie] => XXXX
        )

    [6] => {"code":"400005","msg":"Invalid KC-API-SIGN"}
)
```

**Comment by kroitor** [comment]
@hansvanzutphen KuCoin's endpoint for canceling orders does not support `currencyPair` and `type` params:

- https://docs.kucoin.com/#cancel-single-order-by-clientoid

You should not specify the overrides if the exchange does not require them, also all specified overrides must conform to exchange's API docs.

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

This should work for KuCoin:

```PHP
exchange->cancel_order("XXXX", "SNX/BTC");
```

Hope that answers your question. Let us know if not. Feel free to reopen this issue or just ask further questions if any.
