### ISSUE TITLE
Clarification regarding Exceptions

### ISSUE THREAD

**Issue by PranavJoshi2** [ccxt/ccxt#9703]
- OS: win7
- Programming Language version: Python 3.7.1
- CCXT version: 1.53.55

**Question 1:** 
what i want to do is:
For rate limit hit (https://github.com/ccxt/ccxt/wiki/Manual#rate-limit):
```
except (DDoSProtectionError or ExchangeNotAvailable or ExchangeError or InvalidNonce) as e:
    # retry with wait 30 min intervals 
```
AND,
For many other exceptions DERIVED FROM the 'ExchangeError' demands a different kind of response
e.g. 
```
except (AuthenticationError) as e:
    # exit
except (InsufficientFunds) as e:
    # dont retry move on
etc..
```
BUT 
'ExchangeError' is a parent to some of these other exceptions like AuthenticationError or InsufficientFunds
so my question is will the following work?
```
except (DDoSProtectionError or ExchangeNotAvailable or ExchangeError or InvalidNonce) as e:
    # retry with wait 30 min intervals 
except (AuthenticationError) as e:
    # exit
except (InsufficientFunds) as e:
    # dont retry move on
```
If not, what is the standard practice when the parent and the derived exceptions demands different responses?

**Question 2.** 
the manual seems to use two names for the apparently same exception - 'DDoSProtectionError' and 'DDoSProtection'
Is it DDoSProtectionError or DDoSProtection?

**Comment by kroitor** [comment]
> **Question 2.**
> the manual seems to use two names for the apparently same exception - 'DDoSProtectionError' and 'DDoSProtection'
> Is it DDoSProtectionError or DDoSProtection?

The correct one is `DDoSProtection`– will fix the Manual, thank you for pointing that out!

> BUT
> 'ExchangeError' is a parent to some of these other exceptions like AuthenticationError or InsufficientFunds
> so my question is will the following work?
> 
> ```
> except (DDoSProtectionError or ExchangeNotAvailable or ExchangeError or InvalidNonce) as e:
>     # retry with wait 30 min intervals 
> except (AuthenticationError) as e:
>     # exit
> except (InsufficientFunds) as e:
>     # dont retry move on
> ```

No, that will intercept ExchangeError before AuthenticationError and before InsufficiendFunds. You want to place more specific exceptions on top, and more generic exceptions below, like so:

```Python
except (DDoSProtectionError or ExchangeNotAvailable or InvalidNonce) as e:
    # retry with wait 30 min intervals 
except (AuthenticationError) as e:
    # exit
except (InsufficientFunds) as e:
    # dont retry move on
except (ExchangeError) as e:
    # your reaction to ExchangeError that does not fall into any other category
```

Hope that answers your questions. Let us know if not.

**Comment by PranavJoshi2** [comment]
thanks.
it clarifies everything nicely.
