### ISSUE TITLE
Feature request: Standard OHLCV timeframes 

### ISSUE THREAD

**Issue by bentt6** [ccxt/ccxt#9704]
It would be great if you could make a Standard for the OHLCV timeframes (for exchanges that supports OHLCV).
Creating "emulated" timeframes from a smaller ones (for example 2H from 1H timeframes).
I'm currently doing it manually by wrapping the interfaces.

#featurerequest

**Comment by kroitor** [comment]
CCXT will not emulate the timeframes missing from the exchange, however, CCXT does contain the code that could be reused with some minor edits for conversions from lower timeframes to higher timeframes:

- https://github.com/ccxt/ccxt/blob/b9f5441a44e740579c9274f84487b6ba7da8e107/js/base/functions/misc.js#L43
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/exchange.py#L1665
- https://github.com/ccxt/ccxt/blob/master/php/Exchange.php#L538

The emulation functionality will be kept outside of the lib for the time being. We will most likely add that in a standalone plugin sometime later.
