### ISSUE TITLE
Is there a way to historically fetch_balance ?

### ISSUE THREAD

**Issue by thawatchai-w** [ccxt/ccxt#9717]
I want to see my balance on date 01.01.2021. Is there a way ?

Thank you in advance

- OS: Windows10
- Programming Language version: python3.9
- CCXT version: 1.50.14

```
REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS
```
import ccxt
import datetime 

api_key = "apikey"
api_secret = "secret"
date='01.01.2021 00:00:00,00'
temp=datetime.datetime.strptime(date, "%d.%m.%Y %H:%M:%S,%f")
dt=temp.timestamp()*1000
params = {'end_time': int(dt/1000)}

trades=ftx.fetch_balance(params)
```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
```

**Comment by kroitor** [comment]
> I want to see my balance on date 01.01.2021. Is there a way ?

Afaik, there is no such direct way.

You can restore your history, if you collect it over time by polling the balance periodically, or you can retrieve the history of your trades and deposits/withdrawals/transactions, and restore the money movement and balance from that history. CCXT provides the related APIs: 

- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/wiki/Manual

Hope that answers your question, let us know if not.
