### ISSUE TITLE
How to modify 'create_order' by Bitget

### ISSUE THREAD

**Issue by yudaiharis** [ccxt/ccxt#9720]
- OS: Windows 10
- Programming Language version: Python 3.9
- CCXT version: 1.53.87

The following "create_order" is working. I would like to modify the takeprofit after ordering. Please let me know if there is a good way.
```
def __create_entry_order(self, buy, bid, ask, balance):
    side = 'Buy' if buy else 'Sell'
    type = '1' if buy else '2'
    price = ask if buy else bid
    params = {
        'type' : type, 
        'presetStopLossPrice' : self.entry_sl, 
        'presetTakeProfitPrice' : self.entry_tp01
    }
    if self.fixed_lot:
        amount = self.fixed_lot_size
    else:
        amount = math.ceil(balance * self.flexible_lot_percent)
    if self.order_market:
        order = self.bitget.create_order(self.symbol, 'market', side, amount, params)
    else:
        order = self.bitget.create_order(self.symbol, 'limit', side, amount, price, params)
    return order['info']['order_id'], side, amount, price

order = self.bitget.create_order(self.symbol, 'limit', side, amount, price, params)
```

```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
```

**Comment by carlosmiei** [comment]
Since this exchange does not have the edit order capability, it is not possible to edit ongoing orders, only canceling them @kroitor ?

**Comment by kroitor** [comment]
@carlosmiei yes, in this case `exchange.has['editOrder']` will be `'emulated'` from the base class and will default to canceling the old order and then placing a new order:

- https://github.com/ccxt/ccxt/blob/master/python/ccxt/base/exchange.py#L2107
- https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties

@yudaiharis let us know if that does not answer your question.

**Comment by yudaiharis** [comment]
@kroitor 

Yes, I understand. Thank you for your reply.
