### ISSUE TITLE
[Binance] sapi_get_sub_account_assets raises 404 Not Found 

### ISSUE THREAD

**Issue by MatthewDLove** [ccxt/ccxt#9724]
Hello,

Using Python 3.8.7 with CCXT 1.53.72

Updated my code to accommodate Binance's delisting of the `WAPI` endpoints and received a 404 Not Found Error for the implicit method `sapi_get_sub_account_assets`. This is because the Binance describe dict currently uses the base URL `https://api.binance.com/sapi/v1'` for all Binance `sapi` endpoints, but `query_sub_account_assets` uses ` /sapi/v3/sub-account/assets` instead.

Docs here: https://binance-docs.github.io/apidocs/spot/en/#query-sub-account-assets-for-master-account

### My Code:
```
sub_account_email: str = ...
resp = exchange.sapi_get_sub_account_assets(
      {'email': sub_account_email}
  )
```

### Error
```
404 Client Error:  for url: https://api.binance.com/sapi/v1/sub-account/assets?timestamp=1627906407443&recvWindow=5000&email={sub_account_email}&signature={signature}
```

**Comment by kroitor** [comment]
Yep, it's a v3 endpoint, will get it fixed asap! Thx for your feedback!

**Comment by pankracy40i4** [comment]
Hi @kroitor. Firstly thanks for all great work on the project. Could u please share when the fix may be addressed?

**Comment by DUK3135** [comment]
I'm hoping I'm doing the right thing Cuz I'm doing something wrong on my
end Cuz nobody wants to pay me nor have I got paid if someone help me with
some answers about this

**Comment by DUK3135** [comment]
How would I go about doing this sir
