### ISSUE TITLE
RFI: Stock exchange broker

### ISSUE THREAD

**Issue by royteeuwen** [ccxt/ccxt#9725]
Hey, this is more of a request for information / feasibility type of question. Would it in theory be feasible to connect to a stock exchange broker instead of a crypto exchange? Or is there code in ccxt that would definitely not make it workable? 

I was thinking for myself to try out some automated trading with Interactive Brokers, but it would be nice if in one way or another I could use freqtrade for that, which uses ccxt to connect. 

Of course everything is possible in theory, the question is more like, how much refactoring would it be compared to a crypto exchange and has anyone ever tried it / thought about it?

**Comment by kroitor** [comment]
Hi!

Yes, integrating IB's API is possible, there's a standalone issue for it: 

- https://github.com/ccxt/ccxt/issues/6508

We hope to implement it asap. Hope that answers your question.

I would close this issue for now if you don't mind. Feel free to reopen it if needed or just ask further questions if any. If it's about Interactive Brokers, i suggest posting in the dedicated issue linked above. Thx!
