### ISSUE TITLE
Bitstamp - watchTicker(s) support

### ISSUE THREAD

**Issue by dimoff66** [ccxt/ccxt#9728]
- OS:
- Programming Language version: javascript
- CCXT version: 

Bitstamp api page informs they have "live ticker" subscription for ws
https://www.bitstamp.net/websocket/v2/

but ccxt.pro shows watchTicker(s) = false

Any plans to add watchTicker method to bitstamp exchange or any reasons why it is not possible?

**Comment by kroitor** [comment]
@dimoff66 we will look into it and will hopefully add it asap. Will post related updates here.

**Comment by kroitor** [comment]
@dimoff66 the "live ticker" subscription is for `watchTrades`, not for `watchTicker`. Bitstamp's `watchTrades` is already implemented. Bitstamp's API suggests that you calculate the ticker from trades. Hope that answers your question. Let us know if not.

**Comment by dimoff66** [comment]
> @dimoff66 the "live ticker" subscription is for `watchTrades`, not for `watchTicker`. Bitstamp's `watchTrades` is already implemented. Bitstamp's API suggests that you calculate the ticker from trades. Hope that answers your question. Let us know if not.

Yes, i'm sorry for desinformation
