### ISSUE TITLE
Clarification on Isolated vs Non-Isolated Accounts on Binance

### ISSUE THREAD

**Issue by cadmufasa** [ccxt/ccxt#9739]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Linux
- Programming Language version: Python 2.7
- CCXT version: 1.34.38

```
There is not code - looking for an explanation regarding the use of Isolated vs non-isolated accounts on Binance.

see: https://money.stackexchange.com/questions/143987/isolated-margin-vs-shared-margin-on-the-futures-exchange

```
see: https://money.stackexchange.com/questions/143987/isolated-margin-vs-shared-margin-on-the-futures-exchange

```

**Comment by frosty00** [comment]
Isolated margin means that all the capital for the position is put upfront so the maximum loss is the amount of collateral in that positions, typically just the initialMargin if you didn't add any more. 

Cross margin positions typically mean that if you have multiple positions open, let's say DOGE/USDT, BCH/USDT, BTC/USDT and the DOGE tanks, it will cause your collateral to go to zero and all of your positions which share the same collateral will be liquidated.

**Comment by ttodua** [comment]
Question has been answered. Closing this issue.
If you have any issues with CCXT, let us know.
