### ISSUE TITLE
What is the best practice to write custom rate limiter for multiple CCXT exchange instances?

### ISSUE THREAD

**Issue by koftyan** [ccxt/ccxt#9744]
Hello. I need to run large amount of exchange instances with different api keys(to call REST API with fetchMyTrades and another methods). What is the best way to handle rate limits of exchange between all of them? I can not found any examples about technique in docs. I see good examples about reusing exchange instance, but if I uderstand correctly this not suitable for my situation. Should I control rateLimit field somehow for each instance? Maybe you have some example of custom rate limiter?
Thanks!

- OS: Any
- Programming Language version: Node.js 14.x
- CCXT version: Any

**Comment by Djusk8** [comment]
I had to solve the same problem some time ago.

While you are sending all requests from one IP address (regardless the different API keys), the exchange can block your IP address for the reason of rate-limit or DDOS errors.

So you have two ways to avoid this:
1. Limit the rate of the requests of all exchange instances.
2. Use different IP addresses for every instance of the exchange. But this does not save you from problems of blocking IP if instance will send requests too fast.

I used the following approach:

* For every exchange instance dedicated proxy-server was bought. I used the separate VPS's for every instance before, but maintaining such an infrastructure is much more difficult than using proxy servers. 

To use the proxy you need to update the exchange instance with the dict:
 `exchange_instance.proxies = {'https': 'YOUR_PROXY_SERVER'}`

* To work with DDOS and RATE-limit errors of the every instance I use the following code:

**note**: the code is simplified. For every exchange I write custom `exception_handler()` with much more handlers.

```
    def exception_handler(self, func: classmethod, *args, **kwargs):

        while True:
            try:
                data = func(*args, **kwargs)

            except (ccxt.DDoSProtection, ccxt.RateLimitExceeded):
                self.increase_rate_limit()  # decrease speed of the requests to avoid blocking the proxy in the future
                self.change_proxy_server()  # because you current proxy is blocked now for some time
                continue

            ...................
            ...................

            return data

    def increase_rate_limit(self):
        self.rateLimit += 500

```

**Comment by koftyan** [comment]
Thanks for your reply!
I am currently using similar approach with proxies but it is very expensive in my case(now I am running about 3000 instances, but in future this count may be increased up to 10000). 
Now I want to sacrifice a little the speed of updates, but try to get rid of the use of proxy servers as much as possible.

**Comment by Djusk8** [comment]
I can only guess your trading strategy, but if your one exchange instance works with the only one market (one pair), the number of instances can be significantly decreased  by increasing number of pairs one instance is working with. But this is not a question of the CCXT library, but of a programming approach. 

It might be time to try asynchronous code and websockets also. Not all exchanges support websockets, but the largest exchanges do.

**Comment by flieks** [comment]
@koftyan where do you get quality proxies ? I tried with residential proxies but after 5 requests i get always `The selected relay is offline or busy processing other threads` and also the speed is unacceptable for me

**Comment by ttodua** [comment]
This is related: #9470 so maybe that also answers also this topic as some degree.

**Comment by ttodua** [comment]
issue has been stale, so closing for now. however, any future readers are welcome to add their notes in this thread.
