### ISSUE TITLE
bitfinex v2 websocket?

### ISSUE THREAD

**Issue by pickmone** [ccxt/ccxt#9745]
Hi, 

I don't see any watch function for bitfinex2 in ccxt pro. 

does this mean we have to use bitfinex in ccxt pro to use websocket functions?

thanks,

**Comment by kroitor** [comment]
Yes, at this point CCXT Pro supports Bitfinex v1 WS API, we will add the support for Bitfinex v2 WS API to CCXT Pro this month, we hope. Feel free to reopen this issue if that does not answer your question.
