### ISSUE TITLE
Support for `watch_orders()` in Binance Isolated Margin Wallet

### ISSUE THREAD

**Issue by pietrodn** [ccxt/ccxt#9746]
Hello, I'm using the latest version of CCXT Pro and would like to adapt the code to listen to the live WebSocket stream of order updates for the **isolated margin wallet in Binance**.

I understand that isolated margin is not yet supported, so I'm not asking for the full support of it right away.
However I'd need some parts to be refactored in order to make it possible to extend CCXT Pro with my code.

To listen to the orders WebSocket stream in Binance, it is necessary to create a _listen key_.
Now, to listen to orders in the isolated margin wallet, it is necessary to pass an additional parameter, `symbol`. It is also necessary to change the endpoint.

From the [documentation](https://binance-docs.github.io/apidocs/spot/en/#user-data-streams):

|                 | API Endpoint                            | Parameters |
|-----------------|-----------------------------------------|------------|
| Spot            | `/api/v3/userDataStream`           | none       |
| Cross Margin    | `/sapi/v1/userDataStream`          | none       |
| Isolated Margin | `/sapi/v1/userDataStream/isolated` | `symbol`   |

### Pass `params` to the HTTP request in `authenticate()`

In the Binance client of CCXT Pro, in the `authenticate()` method, swap this row:
```python
response = await getattr(self, method)()
```

with this row:
```python
response = await getattr(self, method)(params=params)
```

This way, I would be able to pass the `symbol` parameter from outside.
The same change would need to be done in `keep_alive_listen_key()`.

### Parametrize the endpoints

In `authenticate()` and `keep_alive_listen_key()`, it would be nice to parametrize the endpoint paths, so that I can provide the new endpoint in the client configuration. Currently, they are implemented as an if-elif chain that is not easy to extend:

```python
method = 'publicPostUserDataStream'
if type == 'future':
    method = 'fapiPrivatePostListenKey'
elif type == 'delivery':
    method = 'dapiPrivatePostListenKey'
elif type == 'margin':
    method = 'sapiPostUserDataStream'
```

**Comment by ttodua** [comment]
@carlosmiei whenever you have time, you might be able to make a good enhancement for that.

**Comment by TomToms55** [comment]
This would be very useful 🙏

**Comment by TomToms55** [comment]
@carlosmiei when you have some time please take a look at this PR (#16479) that hopefully fixes this long time critical issue. 
Thank you! 🙂

**Comment by carlosmiei** [comment]
Hello @pietrodn, @nikky78, @TomToms55 

The PR will be merged very soon, so you will be able to access `isolated` margin through `watchOrders` and `watchMyTrades` using the `marginMode` parameter.

Example:
```Python

isolated_orders = await binance.watch_orders("BTC/USDT", params = {"marginMode":"isolated"}
isolated_trades= await binance.watch_my_trades("BTC/USDT", params = {"marginMode":"isolated"}
```

Thank you for your patience and let us know if anything! 🙂

**Comment by nikky78** [comment]
Has it been merged yet please?

**Comment by nikky78** [comment]
Did anyone manage to make the isolated margin websocket work?

**Comment by carlosmiei** [comment]
> 

@nikky78 You sure your margin account is working?
