### ISSUE TITLE
Include raw response from exchange in raised errors

### ISSUE THREAD

**Issue by rasmustaarnby** [ccxt/ccxt#975]
It seems Binance requires a symbol param for the `openOrders`, `allOrders` and `myTrades` endpoints. This seems a little odd, given that you would have to try all symbols to make sure you'd actually got a complete list of your recent orders. 

Info:
https://www.binance.com/restapipub.html#user-content-account-endpoints
https://www.reddit.com/r/binance/comments/768fw7/hows_the_api/?st=jbcd102s&sh=3d907801

Now, this is not an issue with ccxt itself but the raised error from ccxt could definitely be improved. 

The raised error I get calling `allOrders`:
```
binance GET https://api.binance.com/api/v3/allOrders?timestamp=1514328539008&signature=XXX 400 not accessible from this location at the moment
```
The raw error from Binance dumping the `$result` var in Exchange.php in the fetch function:
```
{"code":-1102,"msg":"Mandatory parameter 'symbol' was not sent, was empty/null, or malformed."}
```
While I did find the reason eventually it took some time to realize, as I at first thought it was related to the time syncing issue mentioned in #936 

A solution to this could be to either parse and append the `msg` from the response or simply just append the raw response, given that exchanges might not follow the same conventions. Maybe you have already thought of this or I'm overlooking some obvious issues doing this, if so, forgive me. 

Besides that, this is really great work and I truly appreciate it. 

- OS: Ubuntu Trusty
- Programming Language: PHP 7.*
- CCXT version: 1.10.488
- Exchange: Binance
- Method: GET

Regards, 
Rasmus

**Comment by kroitor** [comment]
> The raised error I get calling allOrders:

If you want human errors and human API, use the Unified CCXT API: 
- https://github.com/ccxt/ccxt/wiki/Manual#overview
- https://github.com/ccxt/ccxt/wiki/Manual#api-methods--endpoints

You will get adequate exceptions with proper readable messages, described here: https://github.com/ccxt/ccxt/wiki/Manual#error-handling

Basically, you need to get acquainted with the library, because you're not using it now )

**Comment by rasmustaarnby** [comment]
HA! Damn, Please excuse my stupidity. This is what I get for jumping in to fast, not paying attention. 

Just tested and everything I need to know is right there in the error message `binance fetchOrders requires a $symbol param`

I'll let myself out.

**Comment by kroitor** [comment]
@rasmustaarnby no worries ) Thanks for reporting back! Let us know if you have any questions after reading the Manual ) Cheers!

**Comment by kroitor** [comment]
@rasmustaarnby also make sure to read on [Market Ids and Symbols](https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids), etc, I'd recommend to read it all, you would save yourself a lot of time.

**Comment by rasmustaarnby** [comment]
@kroitor I most certainly will., thanks. I have sent a little something to your tip jar as a sort of penalty fee for asking questions for which I should have found the answers myself.

Happy new year.

**Comment by kroitor** [comment]
@rasmustaarnby thank you, much appreciated! ) Happy holidays to you too! )
