### ISSUE TITLE
How to get balances, orderbook and open orders asynchronously?

### ISSUE THREAD

**Issue by TomaszLakota** [ccxt/ccxt#9752]
Hello,
is it possible to get balances, orderbook and open orders asynchronously (or send multiple create_order requests) to reduce time it takes to fetch data from exchange?
Something similar to [example](https://github.com/ccxt/ccxt/blob/master/examples/py/async-orderbooks-from-multiple-exchanges-at-once.py), but with exchange instance create like this:
```
ccxt.ftx({
        'apiKey': 'somekey',
        'secret': 'somekey',
        'headers': {'FTX-SUBACCOUNT': 'somename'},
        'quoteJsonNumbers': False
})
```

- OS: Windows
- Programming Language version: Python 3.8.6
- CCXT version: latest

**Comment by kroitor** [comment]
Hi!

> is it possible to get balances, orderbook and open orders asynchronously (or send multiple create_order requests) to reduce time it takes to fetch data from exchange?

In general, yes, however, there are certain limitations on the number of requests you send per period of time (1m, 1h, 24h), and if you are too aggressive with your requests, the exchange may ban you.

This is explained in the Manual, we highly recommend reading the entire Manual from top to bottom, it has the answers to most questions and it will really save your time:

- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/wiki/Manual

See the async examples here: 

- https://github.com/ccxt/ccxt/tree/master/examples/py/async-multiple-parallel-calls.py

```Python
# -*- coding: utf-8 -*-

import os
import sys

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.append(root + '/python')


import ccxt.async_support as ccxt
from asyncio import get_event_loop, gather

print('CCXT Version:', ccxt.__version__)

# This example demonstrates how to execute multiple requests asynchronously.
# The requests will be executed in parallel independently of each other.
# In order to let them run in parallel the user has to disable the rate limiter.
# Disabling the rate limiter is not recommended, unless you really know
# what you are doing! If you are too aggressive with your requests and
# you don't do proper request timing precisely, the exchange can ban you!
# https://github.com/ccxt/ccxt/wiki/
# https://github.com/ccxt/ccxt/wiki/Manual
# https://github.com/ccxt/ccxt/wiki/Manual#rate-limit


async def main():
    exchange = ccxt.ftx({
        'apiKey': 'YOUR_API_KEY',
        'secret': 'YOUR_SECRET',
        'enableRateLimit': False,  # not recommended
    })
    markets = await exchange.load_markets()
    # exchange.verbose = True  # uncomment for debugging purposes
    symbol = 'BTC/USDT'
    loops = [
        exchange.fetch_balance(),
        exchange.fetch_order_book(symbol),
        exchange.fetch_open_orders()
    ]
    results = await gather(*loops)
    print('Balance:')
    print(results[0])
    print('------------------------------------------------------------------')
    print(symbol, 'orderbook:')
    print(results[1])
    print('------------------------------------------------------------------')
    print('Open orders:')
    print(results[2])
    await exchange.close()

loop = get_event_loop()
loop.run_until_complete(main())
```

**Comment by TomaszLakota** [comment]
Thank you, I was trying to use gather, but it didn't work, because I'd imported  `ccxt` instead of `ccxt.async_support`.

**Comment by kroitor** [comment]
@TomaszLakota this is covered here: https://github.com/ccxt/ccxt/wiki/Manual#synchronous-vs-asynchronous-calls
