### ISSUE TITLE
[binance] [CCXT Pro] Wrong clientOrderId returned by `watch_orders()` after order cancellation

### ISSUE THREAD

**Issue by pietrodn** [ccxt/ccxt#9757]
- OS: macOS 11.5.1
- Programming Language version: Python 3.9
- CCXT version: CCXT Pro 0.7.58

## Steps

These steps reproduce the problem in Binance Spot and margin trading. The problem is not present for futures, which have a different API.

1. Watch the order updates with `binance.watch_orders()` in CCXT Pro, store all updates in a list
2. Create a limit order in Binance Spot market, providing `clientOrderId` to `create_order()`
3. Send a cancel order, by providing `origClientOrderId` with the original client order ID
4. Observe the object returned by `watch_orders()` after the cancellation

## Problem
**What happens**: the object returned by `watch_orders()` after the cancellation has a different `clientOrderId` than the one I provided in the insert order command. It is a string generated by Binance, which is also returned in the response of `cancel_order()` (`newClientOrderId`, see [docs](https://binance-docs.github.io/apidocs/spot/en/#cancel-order-trade)).

**What I expect**: the `clientOrderId` should instead be the ID I provided when I inserted the order. This is the behaviour of the futures trading API.

Indeed, in the [spot documentation for the WebSocket order stream](https://binance-docs.github.io/apidocs/spot/en/#payload-order-update):

```
"c": "mUvoqJxFIILMdfAW5iGSOW", // Client order ID
"C": "",                       // Original client order ID; This is the ID of the order being canceled
```

## Workaround
I temporarily solved this problem by overriding the original CCXT Pro behaviour:

```python
def parse_ws_order(self, order: dict[str, Any], market: Optional[str] = None) -> dict[str, Any]:
    order = super().parse_ws_order(order=order, market=market)
    order["clientOrderId"] = self.safe_string(order["info"], "C") or self.safe_string(
        order["info"], "c"
    )
    return order
```

**Comment by pietrodn** [comment]
@frosty00 I see you fixed, but beware that `safeString2` does not work properly in this case, because `C` may be an empty string instead of `None`... so the returned `clientOrderId` is an empty string instead of `c`.

**Comment by pietrodn** [comment]
I confirm this is fixed. Thanks!

**Comment by pietrodn** [comment]
I just tested the latest version and everything works as expected both for spot, margin, and futures accounts. 🎉

**Comment by kroitor** [comment]
@pietrodn thank you for your involvement!
