### ISSUE TITLE
Where can I find the update log for CCXT Pro / CCXT?

### ISSUE THREAD

**Issue by pickmone** [ccxt/ccxt#9758]
Hi, 

Just wondering where I can find the update log? I just upgraded CCXT Pro and CCXT from older version and some codes needed to be changed. 

for example, for FTX the private_get_wallet_coins function became public_get_wallet_coins function. 

Is there somewhere where we can see all the changes version over version?

thank you

**Comment by kroitor** [comment]
Hi!

You can find the commit logs here:

- https://github.com/ccxt/ccxt/commits/master
- https://github.com/kroitor/ccxt.pro/commits/master

Let us know if that does not answer your question.
