### ISSUE TITLE
Add a hook to work via cloudscraper

### ISSUE THREAD

**Issue by osnwt** [ccxt/ccxt#976]
In some cases it is necessary (see for instance #884). Would be great to have an option to replace request calls for particular exchange by cloudscraper.request or similar, like a proxy option.

**Comment by kroitor** [comment]
Ok, this is commited to the master branch now, will be available in version 1.10.525 in 5-10 minutes. Use the `.fetchImplementation = yourFetchFunction` override to pass your custom fetch() to it.

**Comment by osnwt** [comment]
Great, thanks! Please read my last comment in #884.
