### ISSUE TITLE
Would it be possible to fetch price of a given symbol based on given timestamp?

### ISSUE THREAD

**Issue by avatar-lavventura** [ccxt/ccxt#9774]
- OS: `Ubuntu 20.04.2 LTS`
- Programming Language version:  `Python 3.8.10`
- CCXT version: `ccxt==1.52.40`

---------

I was wondering would it be possible to obtain price of a given pair like (`ETH/BTC`) in history based on given timestamp.

=> Can we fetch its price based on given timestamp as key?

something like:
```
timestamp = "1628351659000"
ticker = await exchange.fetch_ticker(symbol, timestamp)
```

or  ```ticker_history[timestamp]```

----------

Overall, I am trying to come up with a solution to find entry price in Binance spot. It is kind challenging where we have to handle `PAIR/BTC` and `PAIR/USDT` buy and sell operation. In order to achieve this I am require to have pairs' BTC value on a given timestamp.

I am sorry if its already asked.

**Comment by ttodua** [comment]
Late reply, but I'll answer this: that might be directly done with `fetchTrades` (if exchange supports it generally). binance (of course) supports it and you can do:
```
timestamp = 1628351659000 # should be numeric, not string
trades = await exchange.fetch_trades(symbol, timestamp, limit = 1)
print(trades)  #or print(trades[0])
```
let us know if you have any further issues with CCXT
