### ISSUE TITLE
How to send a market order on Binance

### ISSUE THREAD

**Issue by znat** [ccxt/ccxt#9775]
I am trying to create a market order on Binance.

- OS: OSX
- Programming Language version: JS
- CCXT version: 1.54.58

```
createOrder('ALICE/USDT', 'MARKET', 'sell', 1)
```
I tried many variations, tried with price,`quoteOrderQty`, but I always have the same error:
```
A mandatory parameter was not sent, was empty/null, or malformed.
```
Any idea?

**Comment by kroitor** [comment]
```JavaScript
const order = await exchange.createOrder('ALICE/USDT', 'market', 'sell', 1)
```

- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki/Manual#placing-orders
- https://github.com/ccxt/ccxt/tree/master/examples

**Comment by znat** [comment]
Thanks
