### ISSUE TITLE
Cryptopia fetchOrders requires a symbol param

### ISSUE THREAD

**Issue by ericvrp** [ccxt/ccxt#978]
Is the following message the result of a bug or is there a suggested way to work around it? (it works for other exchanges like Poloniex and Bittrex)

(node:2040) UnhandledPromiseRejectionWarning: Error: cryptopia fetchOrders requires a symbol param

- OS: Linux
- Programming Language: JS
- CCXT version: 1.10.492
- Exchange: Cryptopia
- Method: fetchOrders

```

**Comment by kroitor** [comment]
It is a requirement of the exchange (Cryptopia). Of all exchanges 50% require a symbol for most endpoints, even for canceling an order by a known id, the other 50% don't require a symbol. It's just the way it is and we have to **always pass a symbol**.

**Comment by ericvrp** [comment]
Yes thank you. So to fetch all orders I have to iterate over all symbols and fetch per symbol.

**Comment by kroitor** [comment]
@ericvrp if you want to do it universally for all exchanges - yes, but you can make a shortcut and use fetchOrder without a symbol to fetch them all at once. We will think of adding ways of detecting the capabilities of exchanges more precisely. Do you mind if I close this issue? Feel free to reopen it or just ask questions, if any.

**Comment by ericvrp** [comment]
"use fetchOrder without a symbol to fetch them all at once". You mean fetchOrders ? Yes, closing is fine. Thanks for the very active developement BTW!! Having an easy way to see if an exchange is capable of this would be nice indeed. The same thing with the capability of market order .

**Comment by kroitor** [comment]
> You mean fetchOrders ?

Yes, of course, made a typo... my bad.

> Having an easy way to see if an exchange is capable of this would be nice indeed. The same thing with the capability of market order .

Working on it. ;)

**Comment by rokcarl** [comment]
So what I ended up doing is working around it like this:

1. get a list of currencies in my Cryptopia portfolio using `fetch_balance()`,
2. check which one of those currency pairs are an actual market on Cryptopia: `exchange.load_markets()` and `exchange.symbols`,
3. Fetch orders for every supported symbol.

The downside of this is of course that if I have an order for a currency that I don't already hold, this will miss it :(. That's too bad because the exchange does show all of them.

Here's some of my code for this:

```
  def get_open_orders(self):
    try:
      return self.api.fetch_open_orders()
    except ccxt.errors.ExchangeError as e:
      if "requires a symbol" not in str(e):
        raise e
    # this is an exchange that requires a symbol for orders, e.g. Cryptopia
    currencies = self.get_balance().keys()
    currency_pairs = [(c1, c2) for c1 in currencies for c2 in currencies]
    possible_symbols = ["{}/{}".format(c1, c2) for c1, c2 in currency_pairs]
    supported_symbols = self.supported_symbols()
    symbols = [s for s in possible_symbols if s in supported_symbols]
    order_groups = [self.api.fetch_open_orders(s) for s in symbols]
    orders = [o for og in order_groups for o in og]
    return orders
```
