### ISSUE TITLE
What does time represent in OHLCV?  bar-start or bar-end time?

### ISSUE THREAD

**Issue by ttodua** [ccxt/ccxt#9783]
I've read through https://github.com/ccxt/ccxt/wiki/Manual#ohlcv-candlestick-charts and it mentions time parameter like:

1504541580000, // UTC timestamp in milliseconds, integer

however, it is not said, whether is it bar-close time or bar-open time?
tradingview charts use bar-open time, i.e. when you see 18:44 bar (on 1 minute chart), it means bar opened at 18:44 and will continue will 18:45.
In other platforms, however, 18:44 bar means that it shows formation from 18:43 and at 18:44 the bar will be finally closed/formed.

So, how CCXT considers time -is it open or end date of bar?

**Comment by ttodua** [comment]
(btw, it might be good, if you have retained one docs-page, either here on github or on [readthedocs](https://ccxt.readthedocs.io/en/latest/manual.html). I am not sure whichever is your main doc-site).

**Comment by ttodua** [comment]
Turned out it is "bar-start" timestamp. 
If i am correct, close this issue. thanks.

**Comment by kroitor** [comment]
@ttodua yes, it should represent the starting timestamp of a corresponding period.

**Comment by ttodua** [comment]
Thanks, btw, what about two different doc-sites?  which is abandoned and which not?
