### ISSUE TITLE
error using ccxt in react-native project

### ISSUE THREAD

**Issue by itsnyx** [ccxt/ccxt#9786]
- OS:Windows 10
- Programming Language version: java script in react-native
- CCXT version: 1.54.64 latest...

hello every one , i have issues on using ccxt in my react-native project
i just simply did npm install ccxt and now want to use this how can i solve this error?
i've created the project with npm init ==> blank .
thanks.

```
var ccxt = require("ccxt");
console.log(ccxt.exchanges); // print all available exchanges```

```
Failed building JavaScript bundle.
Unable to resolve module ccxt from C:\Users\username\Desktop\React\cryptolead\App.js: ccxt could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
  4 | import "node-libs-react-native/globals";
  5 |
> 6 | var ccxt = require("ccxt");
    |                     ^
  7 | console.log(ccxt.exchanges); // print all available exchanges
  8 |
  9 | export default function App() {```

**Comment by kroitor** [comment]
It will depend on the your react app config, and you also have to make sure that the app is properly webpack'ed. This, however, is outside the scope of this lib, so we cannot really consult you on how to configure a react project, hope for your understanding. Note that we also have ccxt.browser.js and if your intent is to use CCXT in react frontend, then you might need to make a custom build, to reduce the size of the app.

Let us know if that does not help:
- https://github.com/ccxt/ccxt/issues?q=react
- https://github.com/ccxt/ccxt/issues/6327

**Comment by itsnyx** [comment]
thanks on info, I've changed my implementation of the ccxt in my project and moved into backend which makes more sense.
