### ISSUE TITLE
[Bitget]the Trace command supported by CCXT?

### ISSUE THREAD

**Issue by yudaiharis** [ccxt/ccxt#9790]
OS: Windows 10
Programming Language version: Python 3.9
CCXT version: 1.53.87
Exchange: Bitget

I would like to use following APIs, 'trace/currentTrack' and 'trace/closeTrackOrder', are these APIs supported by CCXT?
I checked CCXT's sorce code, but I could not find the code that can be used.

https://bitgetlimited.github.io/apidoc/en/swap/#get-the-current-list
GET /api/swap/v3/trace/currentTrack
POST /api/swap/v3/trace/closeTrackOrder

**Comment by kroitor** [comment]
You can call those methods using the Implicit API as documented in the Manual. We highly recommend reading the entire Manual from top to bottom – it will really save your time.

- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki/Manual#implicit-api

```Python
import ccxt

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.bitget({
    # ...
})
exchange.load_markets()
symbol = 'CMT_AAVEUSDT'
market = exchange.market(symbol)
# exchange.verbose = True  # uncomment for debugging purposes
response = exchange.swap_get_trace_currenttrack({
    'symbol': market['id'],
    'pageIndex': '1',
    'pageSize': '100',
})
pprint(response)
response = exchange.swap_post_trace_closetrackorder({
    'symbol': market['id'],
    'trackingNo': YOUR_TRACKING_ORDER_NUMBER  # use the currentTrack result here
})
pprint(response)
```

**Comment by yudaiharis** [comment]
@kroitor 
I am very grateful for the guidance of "Implicit API". However, "swap_post_trace_closetrackorder()" does not work. I also read the manual, but I don't know what to do. Do you have any hints?
"swap_get_trace_currenttrack()" works well, thanks.

```
import ccxt
from pprint import pprint

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.bitget({
   # ...
})
exchange.load_markets()
symbol = 'CMT_BTCUSDT'
market = exchange.market(symbol)
pprint(market)
exchange.verbose = True  # uncomment for debugging purposes

response = exchange.swap_get_trace_currenttrack({
    'symbol': market['id'],
    'pageIndex': '1',
    'pageSize': '100',
})
pprint(response)

trackingNo = response[0]['orderNo']
pprint(response)

response = exchange.swap_post_trace_closetrackorder({
    'symbol': market['id'],
    'trackingNo': trackingNo,  # use the currentTrack result here
})
pprint(response)
```

```
AttributeError: 'bitget' object has no attribute 'swap_post_trace_closetrackorder'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
c:\Users\haris\OneDrive\デスクトップ\bitget_track3.py in 
     29 pprint(response)
     30 
---> 31 response = exchange.swap_post_trace_closetrackorder({
     32     'symbol': market['id'],
     33     'trackingNo': trackingNo,  # use the currentTrack result here

AttributeError: 'bitget' object has no attribute 'swap_post_trace_closetrackorder'
```

**Comment by yudaiharis** [comment]
I have confirmed that the feature 'swap_post_trace_closetrackorder' is enabled in CCXT Version: 1.57.36.
I appreciate it very much.
