### ISSUE TITLE
Binance Futures Dollar Amount Trade Vs Contract Quantity

### ISSUE THREAD

**Issue by iMichaelM** [ccxt/ccxt#9791]
Hey All, hopefully just a quick question on this, since I wasn't really able to find an answer.
Is it possible to specify the amount of dollars we want to use to execute a trade on Binance futures, as opposed to stating the quantity we want to buy?
In essence, make it so that the below at the end could act as dollar value, not ETH quantity.
`exchange.create_market_buy_order('ETH/USDT', 0.1)`
Many thanks!

**Comment by frosty00** [comment]
yeah look at the contractSize of the markets in the binance coin margined futures, in particular you should look at:

```
const coinmargined = ccxt.binancecoinm()
await coinmargined.loadMarkets ()
console.log (coinmargined.market ('BTC/USD'))
```

and look for `contractSize`

<img width="603" alt="Screenshot 2021-08-11 at 12 28 42" src="https://user-images.githubusercontent.com/14319357/129021328-d18f6de9-dfe2-478b-93fa-7924f5e09e4c.png">

**Comment by iMichaelM** [comment]
Thanks a lot.
