### ISSUE TITLE
Add new exchange: Crypto.com

### ISSUE THREAD

**Issue by koala974** [ccxt/ccxt#9797]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version: PHP
- CCXT version:v.1.53.92

```
PLease is it possible to add Crypto.com exchange
```

**Comment by kroitor** [comment]
We will merge this PR: https://github.com/ccxt/ccxt/pull/9610
Your help testing it out is very much appreciated.
