### ISSUE TITLE
Memory Leak - Heap size increasing - Binance watchOrderBook

### ISSUE THREAD

**Issue by fvsgit** [ccxt/ccxt#9799]
### The problem

I implemented a very basic application with the recommended pattern to get realtime orderbook updates via websockets. What I have realised is that there seems to be a memory leak calling the **watchOrderBook** function ( tested both Binance and FTX). It seems the heap size is just increasing over time. For smaller applications is goes unnoticed, but if you start to stream orderbook data for multiple pairs, you see the heap size increase quite quickly. The details of the code and screenshots can be found below.

Am I doing something wrong here with my implementation? 

### Environment

- OS: Windows 10
- Programming Language version: Nodejs v14.17.0
- CCXT Pro version: 0.8.9

### How to reproduce
- Start the application in debug mode inside vscode
- Check the Realtime Performance data ( Extension needs to be installed )

### Code to reproduce
```
'use strict';
const ccxtpro = require('ccxt.pro');

(async function () {

    try {
        const markets = ['ETH/USDT'];
        const exchange = new ccxtpro.binance({ enableRateLimit: true })

        while (true) { 
            const orderbook = await exchange.watchOrderBook(markets[0]);
        }

    } catch (e) {
        console.error(e);
    }

})();
```
### Results

When I start the code above and monitor the heap size, it increases over time. Below are two screenshots. The first was taken after about 2 minutes. At this point the heap was at 100 MB. The second screenshot was taken after about 8 minutes. At this point the heap was at 150 MB. 

My observation is that the rate at which the heap increases slows down over time, but it still increases. When you ramp this up with multiple pairs and more logic you quickly reach 2GB of heap size.

**Screenshot 1 - After +- 2 mins**
![2](https://user-images.githubusercontent.com/19401449/129104959-19449ae3-5ef9-48bf-ba06-9eec33dcf78c.png)

**Screenshot 2 - After +- 8 mins**
![3](https://user-images.githubusercontent.com/19401449/129104896-4676136d-5b0e-40e7-9b79-5dd4406932aa.png)

**Comment by frosty00** [comment]
I think that the leak is coming from the orderbooks... will have to rewrite it probably

**Comment by frosty00** [comment]
<img width="1330" alt="Screenshot 2021-08-12 at 10 04 45" src="https://user-images.githubusercontent.com/14319357/129169956-2a56b7e4-6c8c-4c71-b6aa-dc1ffc292871.png">

After 5 mins running the above script...

**Comment by frosty00** [comment]
<img width="1328" alt="Screenshot 2021-08-12 at 10 10 44" src="https://user-images.githubusercontent.com/14319357/129170826-59e4419b-23a0-4130-8d74-d7e81776b0b8.png">

can confirm

**Comment by fvsgit** [comment]
Yes seems so. The only reason I picked this up was becuase I ran multiple worker threads for +- 300 markets :D For a small amount of markets you would probably not notice it if you are not looking for it explicitly

**Comment by Djusk8** [comment]
I can confirm the problem with leaking memory is exist.

I use Python and CCXT (not PRO) with standart REST APi requests.

When all the bots are started (all works on the one VM) it looks like this:

![изображение](https://user-images.githubusercontent.com/35682654/130018172-8b76e64e-2784-4ee9-93a7-d1a816d45adf.png)

After 5-7 days the memory will be completely full:

![изображение](https://user-images.githubusercontent.com/35682654/130016777-d309d485-4832-4ac5-b237-14d99f124b6b.png)

**Comment by frosty00** [comment]
@Djusk8 I don't think the issue is easily relevant in your case since this is reporting a node js issue and you are reporting a python issue, are you sure this is not a memory leak in your code?

**Comment by Djusk8** [comment]
I agree that my problem may have other reasons. 

I have checked potentially problematic blocks of my code, but without success. Unfortunately, I don't have enough free time right now to dive deeper into the problem. 

But `orderbooks` was mentioned before as a potential possible cause and while I use `orderbooks` a lot, so I assumed that our problems may have the same roots.

In any case, I haven't reported the issue yet because I'm not sure that the reason is in the CCXT library.

**Comment by Djusk8** [comment]
Well, yesterday I started similar simple code, working with `orderbooks` only:

```
import time
import ccxt

ex1 = ccxt.gateio()
ex2 = ccxt.bitmart()
ex3 = ccxt.poloniex()

while True:
    try:
        order_book1 = ex1.fetch_order_book("BTC/USDT", 50)
        order_book2 = ex2.fetch_order_book("BTC/USDT", 50)
        order_book3 = ex3.fetch_order_book("BTC/USDT", 50)
        time.sleep(5)  # to avoid DDOS ban
        print(str(order_book1)[:50])  # to check code is working
    except:
        time.sleep(5)
        continue
```

At the start script used 40,8 Mb:
![изображение](https://user-images.githubusercontent.com/35682654/130186094-e7a36a57-c494-4c5e-b851-abf42dcf809a.png)

After 8 hours of working it consumes 45,3 Mb of memory (+12%):
![изображение](https://user-images.githubusercontent.com/35682654/130185497-fbddc7db-1ee8-4ace-a5e8-a4455d9974f9.png)

Script is still working so I will report the dynamic of memory consumption later.

Do you think I need to open a new issue, if memory consumption will increase?

**Comment by fvsgit** [comment]
@frosty00 any news on this topic? Please let me know if I can help to test.

**Comment by frosty00** [comment]
@fvsgit I don't think this is a memory, could just be a normal behaviour of the garbage collector. Moreover pls feel free to make a separate issue for this as it is not related to the original issue.

**Comment by frosty00** [comment]
@fvsgit the issue is still there, working on it...

**Comment by fvsgit** [comment]
@frosty00 thanks for the update. In the meantime I switched to the python implimentation and running my orderbook services on that. Seems to be stable. However would like to also run it on node. Looking forward to the update.

**Comment by Showgofar** [comment]
Hello
Is there any updates?
Because its huge problem with memory leaks at PHP version

**Comment by Showgofar** [comment]
here is some research
The blue bar is the memory at the start of the cycle, the red one after the "ccxt.watchOrderBook" call, and the yellow one after my handler. Jumps to the beginning of the cycle are most likely associated with the parallel work of coroutines.I did not find any leaks in my part, and this can be seen from the graphs.

**Comment by Showgofar** [comment]
![image](https://user-images.githubusercontent.com/38069687/208590184-2c50a3ae-dd8d-469f-bd94-dfd6cc10777c.png)

**Comment by fvsgit** [comment]
@ttodua / @frosty00 any news on this one? Is this isssue still open and confirmed for Node JS?

**Comment by Showgofar** [comment]
actually this test were made on PHP

**Comment by fvsgit** [comment]
Hi @Showgofar,

Yes I know, I was refering to the leak in NodeJS, as I ceated this issue originally for NodeJS already back in Agust 2021.

**Comment by frosty00** [comment]
@fvsgit I'm currently refactoring all the fetchOrderBooks, going to do binance and kucoin next, hope I will fix it soon #16366

**Comment by fvsgit** [comment]
Hi @frosty00,

That is great news! Just checking, my observation was in the **watchOrderBook** function, is this related to the  **fetchOrderBooks** function somehow?

**Comment by frosty00** [comment]
no this is only related to the `watchOrderBook` function (on binance it fetches an orderbook snapshot using the fetchOrderBook function)

**Comment by fvsgit** [comment]
Understood, happy to test when the PR is ready.

**Comment by fvsgit** [comment]
This bug is solved. I have executed the same code for 12 hours straight. The total heap used was only 53 Mb.
FYI @frosty00

**Comment by fvsgit** [comment]
This bug is solved. I have executed the same code for 12 hours straight. The total heap used was only 53 Mb.
FYI @frosty00

**Comment by ttodua** [comment]
> This bug is solved. I have executed the same code for 12 hours straight. The total heap used was only 53 Mb. FYI @frosty00

good to hear! thanks
