### ISSUE TITLE
Will support bybit spot APIs?

### ISSUE THREAD

**Issue by Moogiid** [ccxt/ccxt#9803]
I think currently ccxt is not supported Bybit spot APIs.
When will support Bybit spot trade APIs?

https://bybit-exchange.github.io/docs/spot/#t-introduction

**Comment by phips28** [comment]
@kroitor is that something you are working on?

**Comment by kroitor** [comment]
Yes, we will add the missing parts asap!

**Comment by Moogiid** [comment]
I am looking forward to release updated one.

**Comment by dyustc** [comment]
is bybit spot APIs supported now? any updates, thanks

**Comment by tklau10** [comment]
hi team, is there any update on this? thanks a lot!

**Comment by kroitor** [comment]
Hi! I'm working on it right now, will hopefully deliver it before the end of the year.

**Comment by furryboffin** [comment]
Hi. Thanks for your work on this. Any idea on when this might be ready for testing?

**Comment by kroitor** [comment]
> Any idea on when this might be ready for testing? 

It will be available this month.

> I notice that there is no branch on github for this integration. How do you guys work here? Do you keep your updates local and only push them to github for pull request? I assume if it's a collaborative work then one would keep a branch on github during development too?

Most often, a single integration cannot be split into parts, it's either all or nothing. Each dev is working on a separate exchange integration according to the common codestyle and in line with the contributing guidelines. We usually submit complete integrations.

**Comment by bugb** [comment]
+1 for this, keep up the good work CCXT team!

**Comment by Emilianocm23** [comment]
+1 for this it will be really useful. Thanks Kroitor and CCXT team

**Comment by kroitor** [comment]
Bybit Spot API is now supported in the most recent version of CCXT (1.84.40+):

- https://github.com/ccxt/ccxt/issues/13399
