### ISSUE TITLE
Fetching FTX subaccount balances with subaccount API Key fails

### ISSUE THREAD

**Issue by srisi** [ccxt/ccxt#9805]
Hi, 
I'm trying to fetch balances for an FTX subaccount with an FTX subaccount API key with trade and withdraw permissions and I'm doing something wrong. I can fetch the subaccount balance with the main account key but not with the subaccount key. Am I forgetting to set a header?

- OS: Ubuntu
- Programming Language version: Python
- CCXT version: 1.54.83

```
import ccxt

main_account_api_key = '<my_main_account_api_key>'
main_account_secret = '<my_main_account_secret>'
sub_account_api_key = '<my_subaccount_api_key>'
sub_account_secret = '<my_subaccount_secret>'

exchange = ccxt.ftx({
    'apiKey': main_account_api_key,
    'secret': main_account_secret,
    'hostname': 'ftx.us',
    'headers': {
        'FTX-SUBACCOUNT': '<my_subaccount>'
    }
})

exchange.private_get_subaccounts_nickname_balances(params={'nickname': '<my_subaccount>'})
# Works with main account key. Subaccount balance returned

exchange.apiKey = sub_account_api_key
exchange.secret = sub_account_secret

exchange.private_get_subaccounts_nickname_balances(params={'nickname': '<my_subaccount>'})
# Fails -> ccxt.base.errors.PermissionDenied: ftx {"success":false,"error":"Only have permissions for subaccount <my_subaccount>"}

exchange.fetch_balance()
# Fails -> ccxt.base.errors.PermissionDenied: ftx {"success":false,"error":"Only have permissions for subaccount <my_subaccount>"}
```

Complete traceback for `
exchange.private_get_subaccounts_nickname_balances(params={'nickname': '<my_subaccount>'})` :
```
Traceback (most recent call last):
  File <...>/python3.8/site-packages/ccxt/base/exchange.py", line 597, in fetch
    response.raise_for_status()
  File <...>/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: UNAUTHORIZED for url: https://ftx.us/api/subaccounts/<my-subaccount>/balances
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File <...>/python3.8/site-packages/ccxt/base/exchange.py", line 613, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File <...>/python3.8/site-packages/ccxt/ftx.py", line 1891, in handle_errors
    self.throw_broadly_matched_exception(self.exceptions['broad'], error, feedback)
  File <...>/python3.8/site-packages/ccxt/base/exchange.py", line 509, in throw_broadly_matched_exception
    raise broad[broad_key](message)
ccxt.base.errors.PermissionDenied: ftx {"success":false,"error":"Only have permissions for subaccount <my-subaccount>"}
```

**Comment by kroitor** [comment]
If you're using FTX.us, the header prefix must be FTXUS:

Try this:

```Python
exchange = ccxt.ftx({
    'apiKey': main_account_api_key,
    'secret': main_account_secret,
    'hostname': 'ftx.us',
    'headers': {
        'FTXUS-SUBACCOUNT': '<my_subaccount>'
    }
})
```

Let us know if that works or not.

**Comment by srisi** [comment]
Thanks for the quick response. That worked with the general fetch_balance request.
```
exchange = ccxt.ftx({
    'apiKey': sub_account_api_key,
    'secret': sub_account_secret,
    'hostname': 'ftx.us',
    'headers': {
        'FTXUS-SUBACCOUNT': '<my_subaccount>'
    }
})
balance = exchange.fetch_balance()
```

Btw: Are the special configurations that FTX and FTX US require (e.g. `FTXUS-SUBACCOUNT`) documented somewhere? I don't want to create work for you that could be resolved by just reading the documentation.

**Comment by kroitor** [comment]
@srisi 

> Are the special configurations that FTX and FTX US require (e.g. FTXUS-SUBACCOUNT) documented somewhere?
> I don't want to create work for you that could be resolved by just reading the documentation.

It is documented in their API docs, you can find links to their docs in the CCXT Manual. To address this issue we will add a `ccxt.ftxus` exchange alias for your convenience, so that it would not require any custom code at all.

**Comment by srisi** [comment]
Excellent, thanks!

**Comment by ttodua** [comment]
Update: from now, you can now directly add the parameter in any method (without need to set the headers in exchange initialization properties), like:

`createOrder/FerchBalance( ..., ...,  params:{ "FTXUS-SUBACCOUNT":"mySubAcc"} ) `

**Comment by chanhw3** [comment]
> Update: from now, you can now directly add the parameter in any method (without need to set the headers in exchange initialization properties), like:
> 
> `createOrder/FerchBalance( ..., ..., params:{ "FTX-SUBACCOUNT":"mySubAcc"} ) `
> 
> Note: `FTXUS-SUBACCOUNT` for ftx.us users.

it is not working for me
to use  fetch_balance(params={'FTX-SUBACCOUNT': 'Sub1'})

may i know if this function has launched in what ccxt version, any documentation?

**Comment by kroitor** [comment]
@chanhw3 it should work with the most recent version 1.73.83+
Please, paste your verbose output:

```Python
print('CCXT Version:', ccxt.__version__)
markets = exchange.load_markets()
exchange.verbose = True
response = exchange.fetch_balance({'FTX-SUBACCOUNT': 'Sub1'})
print(response)
```

**Comment by ttodua** [comment]
@chanhw3 as you see in your code, it doesn't match the example what you had quoted there. the difference is between prefixes `FTX..` and `FTXUS..`
