### ISSUE TITLE
Does ccxt support bitget

### ISSUE THREAD

**Issue by pnama** [ccxt/ccxt#9806]
Hello, I wonder if ccxt supports bitget the crypto exchange website? I have tried few different ways to connect with bitget but it seems like there's an issue with ordering commends. Could you share any codes that can make creating an order to buy and sell? Thank you

print('CCXT Version:', ccxt.__version__)  # ←---------- add this
bitget = ccxt.bitget({'apiKey': '', 'secret': '', 'password': '', 'options': {'defaultType': 'swap'}})
bitget.load_markets()  # ←---------- add this
bitget.verbose = True  # ←------------- add this after load_markets()
balances = bitget.fetch_balance()
balance = balances['CMT_BTCUSDT']
pprint.pprint(balance)

order = bitget.create_limit_buy_order(
    symbol='CMT_BTCUSDT',
    amount=0.0001,
    price=40000,
    params={'type': '1'}
)

**Comment by jorisw** [comment]
It does, as Bitget is listed in the README.

If it doesn't work from the code examples, best to paste any errors you're seeing.

**Comment by pnama** [comment]
Thank you for checking it out. Here's my output :) Any suggestions will be appreciated. :)

return self.create_order(symbol, 'limit', 'buy', amount, price, params)
response = getattr(self, method)(self.extend(request, params))
return self.fetch2(path, api, method, params, headers, body)
return self.fetch(request['url'], request['method'], request['headers'], request['body'])
self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
ccxt.base.errors.ExchangeError: bitget {"status":"error","ts":1628864013501,"err_code":"bad-request","err_msg":"2014"}
