### ISSUE TITLE
Error on Novadax

### ISSUE THREAD

**Issue by fabiomattes2016** [ccxt/ccxt#9810]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Pop OS 21.04
- Programming Language version:
- CCXT version:  latest

Sugest correction on: 
file: novadax.py
method: sign(self, path, api='public', method='GET', params={}, headers=None, body=None)

```python
if method == 'POST':
   body = self.json(query)
  queryString = self.hash(body.encode('utf-8'), 'md5')
  headers['Content-Type'] = 'application/json'
```

**Comment by kroitor** [comment]
@fabiomattes2016 can you plz elaborate a bit? Why the above change is suggested? Did you have any issues with it? If yes, can you paste the code to reproduce it?

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by ttodua** [comment]
The issue didn't got any follow-up and become stale. I'm closing this, and if you face any issues, please let us know with required details.

**Comment by ttodua** [comment]
@fabiomattes2016 if you can, please let us know why/where that issue was happening, if you remember any detail would be appreciated.
