### ISSUE TITLE
Binance Futures: dapiPrivate_get_adlquantile (Python)

### ISSUE THREAD

**Issue by TommyDee123** [ccxt/ccxt#9811]
I am trying to submit a GET request using the binance futures API. For some reason I get an invalid symbol error, even though the exact same symbol works with a different function. I checked the offical API documentation and can't find any issues:
https://binance-docs.github.io/apidocs/futures/en/#position-adl-quantile-estimation-user_data

- OS: Windows 10
- Programming Language version: Python 3.7.9
- CCXT version: 1.54.59

```
import ccxt
Binance = ccxt.binanceusdm({"apiKey": YOUR_API_KEY,
                            "secret": YOUR_SECRET,
                            "enableRateLimit" : True,
                            "timeout" : 20000,
                            "options": { "adjustForTimeDifference": True }
                            })
Binance.set_sandbox_mode(True)
markets = Binance.load_markets()
symbol = "BTC/USDT"
market = Binance.market(symbol)
try:
    response = Binance.dapiPrivate_get_adlquantile({"symbol": market["id"]})
    print(response )
except Exception as e:
    print(e)
```

Returns:
```
binanceusdm {"code":-1121,"msg":"Invalid symbol."}
```

What's strange is that if I use a different function using `market["id"]` works perfectly fine. Ex:

```
try:
    response = Binance.fapiPrivate_post_leverage({"symbol": market["id"], "leverage": 20})
    print(response)
except Exception as e:
    print(e)
```

Returns:
```
{'symbol': 'BTCUSDT', 'leverage': '20', 'maxNotionalValue': '10000000'}
```

**Comment by kroitor** [comment]
If you're using Delivery API (dapi), you have to instantiate `binancecoinm` instead of `binanceusdm`. Hope that answers your question, Let us know if not.

**Comment by TommyDee123** [comment]
Is there a FAPI option for `adlquantile` ? I couldn't find one under `dir(Binance)`...
When I instantiate `binancecoinm` it returns the following error:
`binancecoinm does not have market symbol BTC/USDT`
My positions are in BTC/USDT and I can see the little bars (ADL) when I login to the account through my browser. How can I access this information in `binanceusdm`?
![ADL](https://user-images.githubusercontent.com/88915147/129432889-ac1403c8-0c2a-4cd4-8a7b-406d18712d02.PNG)

**Comment by kroitor** [comment]
> When I instantiate `binancecoinm` it returns the following error:
> `binancecoinm does not have market symbol BTC/USDT`
> My positions are in BTC/USDT and I can see the little bars (ADL) when I login to the account through my browser. How can I access this information in `binanceusdm`?

Your positions are on BTC/USDT perpetuals, those are USDT-margined positions, if i get it correctly, and that means they are related to `fapi` and `binanceusdm`.

> Is there a FAPI option for `adlquantile` ? I couldn't find one under `dir(Binance)`...

Yes, it was missing, I've pushed it just now, and it will arrive in the new build 1.54.93 in ~20 minutes. Please, upgrade your version of CCXT and retry fapi adlquantile endpoint. Let us know if that does not help.

**Comment by TommyDee123** [comment]
Works like a charm! Thank you
