### ISSUE TITLE
binanceus limit sell order does not work

### ISSUE THREAD

**Issue by TokarM** [ccxt/ccxt#9812]
I'm trying to send a regular limit sell order on binanceus and keep getting the following error:

AuthenticationError: binanceus {"code":-1022,"msg":"Signature for this request is not valid."}

The market order executes properly

This is working as expected:
await taking_exchange.createMarketBuyOrder('ADA/USD', 6, params);

But this one is not:
await exchange.createLimitSellOrder('ADA/USD', 6, 2.5, params);

I also tried createOrder function but it doesn't work as well:

await exchange.createOrder('ADA/USD', 'LIMIT', 'SELL', 6, 2.5, { "timeInForce": "GTC"});

await exchange.createOrder('ADA/USD', 'LIMIT', 'SELL', '6', 2.5, { "timeInForce": "GTC"});

await exchange.createOrder('ADA/USD', 'LIMIT', 'SELL', 6, 2.5);

await exchange.createOrder('ADA/USD', 'LIMIT', 'SELL', '6', '2.5', { "timeInForce": "GTC"});

none of this is working.

**Comment by kroitor** [comment]
@TokarM please, paste your code including instantiation (without your keys) and your output with verbose mode turned on: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help. Also, does `fetchBalance()` work with that API key? Have you used this key with any other software before?

**Comment by TokarM** [comment]
@kroitor fetchBalance() works properly. I used the same code with Kraken and everything was working as expected.

**Comment by kroitor** [comment]
@TokarM what is your version of CCXT? Do you have this issue with the most recent version of the lib? Can you paste your verbose output?

**Comment by TokarM** [comment]
@kroitor 

I'm using ccxt.pro 6.14.14 version.

This is the first time I'm running it with binanceus.

const exchange = new ccxtpro[exchangeId] ({ enableRateLimit: true , newUpdates: true});
exchange.apiKey = config.get(key);
exchange.secret = config.get(secret);
exchange.verbose = true;

Output:

binanceus POST https://api.binance.us/api/v3/order 
Request:
 {
  'X-MBX-APIKEY': 't6eYoeNuojRg63zOQZqEujpe0xWNlir4d2ydVdGOuSQry1nvaE1yE1wAVPwUuk1Q',
  'Content-Type': 'application/x-www-form-urlencoded'
} 
 timestamp=1628918544279&recvWindow=5000&symbol=ADAUSD&type=MARKET&side=BUY&newClientOrderId=x-R4BD3S8269a973cbb57f40418413ab&newOrderRespType=FULL&quantity=6&signature=b7fc228ffc7c82200f341af8725eef2b0727c353fe8febd54c99b97c7078845d 

handleRestResponse:
 binanceus POST https://api.binance.us/api/v3/order 400 Bad Request 
Response:
 {
  'Cache-Control': 'no-cache, no-store, must-revalidate',
  Connection: 'keep-alive',
  'Content-Length': '63',
  'Content-Security-Policy': "default-src 'self'",
  'Content-Type': 'application/json;charset=UTF-8',
  Date: 'Sat, 14 Aug 2021 05:22:24 GMT',
  Expires: '0',
  Pragma: 'no-cache',
  Server: 'nginx',
  'Strict-Transport-Security': 'max-age=31536000; includeSubdomains',
  Via: '1.1 9fd0fd3ab227f7918e7e92e96b386326.cloudfront.net (CloudFront)',
  'X-Amz-Cf-Id': 'KKgFt481O6PaBJcOcW1o-0xNqRWimg35g-PJVqzywlxYnxvqTMBReg==',
  'X-Amz-Cf-Pop': 'ORD51-C1',
  'X-Cache': 'Error from cloudfront',
  'X-Content-Security-Policy': "default-src 'self'",
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'SAMEORIGIN',
  'X-Mbx-Used-Weight': '33',
  'X-Mbx-Used-Weight-1m': '33',
  'X-Mbx-Uuid': '0673b263-6601-4d6f-bdf5-8a9fe55a7c5f',
  'X-Webkit-Csp': "default-src 'self'",
  'X-Xss-Protection': '1; mode=block'
} 
 {"code":-1022,"msg":"Signature for this request is not valid."} 

(node:4596) UnhandledPromiseRejectionWarning: AuthenticationError: binanceus {"code":-1022,"msg":"Signature for this request is not valid."}
    at binanceus.throwExactlyMatchedException (/home/vagrant/nodejs_ccxt/trading_platform/node_modules/ccxt/js/base/Exchange.js:539:19)
    at binanceus.handleErrors (/home/vagrant/nodejs_ccxt/trading_platform/node_modules/ccxt/js/binance.js:4091:18)
    at /home/vagrant/nodejs_ccxt/trading_platform/node_modules/ccxt/js/base/Exchange.js:601:18
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async timeout (/home/vagrant/nodejs_ccxt/trading_platform/node_modules/ccxt/js/base/functions/time.js:195:24)
    at async binanceus.request (/home/vagrant/nodejs_ccxt/trading_platform/node_modules/ccxt/js/binance.js:4100:26)
    at async binanceus.createOrder (/home/vagrant/nodejs_ccxt/trading_platform/node_modules/ccxt/js/binance.js:2173:26)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4596) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4596) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by TokarM** [comment]
I have two different APIs for binanceus and one of them is working properly but the other one gives me this error. In my case, I was sending Market order with one API and then limit order with the other. The second API I'm using is not able to fetchBalance as well. However, I can watchMyTrades with second API. I checked permissions on binanceus and it is the same for both APIs.

**Comment by kroitor** [comment]
@TokarM 

> I'm using ccxt.pro 6.14.14 version.

Pardon, but there's no such version of CCXT Pro. Please, run this:

```JavaScript
const ccxtpro = require ('ccxtpro')
console.log ('CCXT Pro Version:', ccxtpro.version)
```

**Comment by TokarM** [comment]
CCXT Pro Version: 0.7.78

**Comment by kroitor** [comment]
@TokarM please, try to create a new API key on the second account and make sure it's the same new key in the logs (you can see it in verbose mode output). Let us know if that does not help.

**Comment by TokarM** [comment]
@kroitor It helped. Thank you! I guess it was a problem on binanceus end.
