### ISSUE TITLE
bitget parameter verification failed

### ISSUE THREAD

**Issue by pnama** [ccxt/ccxt#9813]
order = bitget.create_limit_buy_order(
    symbol='CMT_BTCUSDT',
    amount=0.002,
    price=47600
)

Above is my code for creating a new order. But it gives me an error "raise ArgumentsRequired(self.id + " createOrder() requires a type parameter, '1' = open long, '2' = open short, '3' = close long, '4' = close short for " + market['type'] + ' orders')
ccxt.base.errors.ArgumentsRequired: bitget createOrder() requires a type parameter, '1' = open long, '2' = open short, '3' = close long, '4' = close short for swap orders"

So I added params={'type':'1'} but it gives me "ccxt.base.errors.ExchangeError: bitget {"code":"40017","msg":"Parameter verification failed,Number of ordersRange error","requestTime":1628939642030,"data":null}"

I don't get the results. Could anyone help me fixing it? Thank you

**Comment by kroitor** [comment]
> amount=0.002,

You cannot order 0.002 of a CMT_BTCUSDT contract, you can only buy and sell whole numbers of contracts (amount 1, 2, 3, etc...). The CMT_BTCUSDT contract has a value of 0.001.

This is explained here: 

- https://github.com/ccxt/ccxt/wiki/Manual#precision-and-limits

You can verify that in verbose mode:

- https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting
