### ISSUE TITLE
New Exchange: CoinDCX

### ISSUE THREAD

**Issue by rohit366** [ccxt/ccxt#9816]
Hi,
Can we please add CoinDCX to ccxt.

Official Website - https://coindcx.com/
Here is the API documentation for their exchange - https://docs.coindcx.com/

**Comment by kroitor** [comment]
Duplicate: https://github.com/ccxt/ccxt/issues/4878

**Comment by rohit366** [comment]
Is this exchange added to the master branch of ccxt ?

**Comment by kroitor** [comment]
@rohit366 not yet, your help testing this [PR 4878](https://github.com/ccxt/ccxt/issues/4878) will be very much appreciated!

**Comment by Vaikunth87** [comment]
Has Coin DCX been included in the list ? Looks like it has not.
