### ISSUE TITLE
question about Binance's request limit

### ISSUE THREAD

**Issue by memory942** [ccxt/ccxt#9817]
- OS: windows 10
- Programming Language version: python 3.9
- CCXT version: 1.52.10

Binance has a per second weight request limit of 10.
I fetch 600 candles per second which counts as exactly 5 weighted requests.
However, as I'm not pulling the data directly from Binance but through ccxt, I don't know how that request is handled by Binance.
Does Binance think I(my personal API key) requested the data? Or does it think ccxt requested the data?

sorry if this has been answered already, I googled for about 15 minutes or so but couldn't find definitive answers.

**Comment by kroitor** [comment]
When you are using CCXT, you're talking to Binance directly, CCXT is not a server nor a service – it's just a software library. Binance sees that as any other API user and thinks it is your API key, your IP address, your machine and your account. Hope that answers your question. More about the built-in rate limiter here:

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/issues/1399#issuecomment-359233015
