### ISSUE TITLE
Adding New exchange: Bitrue

### ISSUE THREAD

**Issue by minglan01** [ccxt/ccxt#9822]
Hi, could you add this change https://www.bitrue.com/
Thanks!

**Comment by kroitor** [comment]
Related PR for testing: https://github.com/ccxt/ccxt/pull/7943

**Comment by HartS** [comment]
Hi @kroitor , @minglan01 , take a look at my PR from just now ( #9837 ), which includes fixes from #7943

**Comment by minglan01** [comment]
Thanks @HartS for quick response. The commit looks good for me however I'm not familiar with the codebase to be honest. I don't know if I'm supposed to approve the code or other people?

**Comment by HartS** [comment]
@minglan01 the maintainers have to approve it. I just mean, if you need something to use for right now you can check out the  source branch for that PR (though actually it might be better for you to use https://github.com/system9development/ccxt/tree/s9-build , as that's where we have it built with the corresponding python/php changes). And it wouldn't hurt to share your experience on the PR also, let me know if anything isn't working, etc.
