### ISSUE TITLE
Bittrex timeInForce

### ISSUE THREAD

**Issue by AskDavis** [ccxt/ccxt#9826]
On a create_order in bittrex I see this:
             if ($uppercaseType === 'LIMIT') {
                $request['limit'] = $this->price_to_precision($symbol, $price);
                $request['timeInForce'] = 'GOOD_TIL_CANCELLED';
            } else {
                // bittrex does not allow GOOD_TIL_CANCELLED for $market orders
                $request['timeInForce'] = 'IMMEDIATE_OR_CANCEL';
            }

Can we add an option to add a timeInForce rather than it being set to IMMEDIATE_OR_CANCEL? 
Thanks

**Comment by kroitor** [comment]
You can already override it (it is already almost "an option"), just like any other param:

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

```PHP
$exchange->create_order('ETH/USDT', 'limit', 'sell', 1, 3500, ['timeInForce' => 'YOUR_VALUE_HERE' ]);
```

Hope that answers your question, let us know if not.
