### ISSUE TITLE
Support for delisted markets

### ISSUE THREAD

**Issue by meskis** [ccxt/ccxt#983]
Hey,

Just noticed, that you are only supporting current markets. Are you planing on supporting removed markets (like XRP/USD on Kraken)?

Thanks!

**Comment by kroitor** [comment]
Hi!

> Are you planing on supporting removed markets (like XRP/USD on Kraken)?

No we are not planning to support them. However, we do support them, where possible. Take a look here: https://github.com/ccxt/ccxt/blob/master/js/kraken.js#L266. If you see some delisted market missing, and you think it is necessary (for historical trades or whatever), you can add contribute it by adding the missing symbol there.

Let me know if the above answers your question or not. Thx!
