### ISSUE TITLE
i cant access to private perpetual in coinex exchange

### ISSUE THREAD

**Issue by aydin-j** [ccxt/ccxt#9834]
hi 
how can I access private perpetual coinex? I see codes for public perpetual and its work.

**Comment by ttodua** [comment]
Please describe better what you specifically want to access (wallet balance, make a trade , or what)?
https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by ttodua** [comment]
coinex has been updated since 2022, so new version should work. if anyone faces any issue, feel free to re-open the issue
