### ISSUE TITLE
[Q] (Why) do we have to reset balances after a stream disconnection for Binance (at multiple places)?

### ISSUE THREAD

**Issue by frzsombor** [ccxt/ccxt#9835]
In Binance.js (CCXT Pro v0.8.14) there are three functions (`watchOrders`, `watchMyTrades` and `watchBalance`) that contains the following code:

```javascript
//...
if (!(type in client.subscriptions)) {
    // reset this.balances after a disconnect
    this.balance[type] = {};
}
//...
```

I would like to keep track of and access my balance anytime, and I don't understand why do we have to reset balance in these (even in watchBalance) functions if any of them disconnects. I think it would be better to just keep the last updated values for most cases (and for mine) than reseting it completely if there is no good reason for it. Out of date data is better than no data. Do we have to really reset balances?

**Comment by frosty00** [comment]
I think it is to avoid stale / outdated balances

**Comment by kroitor** [comment]
Closing it, will continue here: https://github.com/ccxt/ccxt/issues/9836
