### ISSUE TITLE
Binance futures watchBalance/handleBalance not working

### ISSUE THREAD

**Issue by frzsombor** [ccxt/ccxt#9836]
There are a few problems in the implementation of Binance futures balances.
What I would like to achieve: load balances, and keep them up to date. 

1) The first problem is that [`watchBalance()`](https://github.com/kroitor/ccxt.pro/blob/0.8.14/js/binance.js#L822) only gets information about _changes_ in the balance, so if I start the [watch loop](https://github.com/ccxt/ccxt/wiki/ccxt.pro.manual#watchbalance), I will not get any balance information, only balance updates. Because of this, I tried calling `fetchBalance()` first, and set its results to the balance property manually: `exchange.balance.future = await exchange.fetchBalance();` then start the watcher. This could work in theory, but as soon as I call `watchBalance()`, it [resets `this.balances`](https://github.com/kroitor/ccxt.pro/blob/0.8.14/js/binance.js#L829-L832) (if no other stream is running/started), so again, I have empty balances. (this is also related to [#9835](https://github.com/ccxt/ccxt/issues/9835))

2) The other problem with balances is with [`handleBalance()`](https://github.com/kroitor/ccxt.pro/blob/0.8.14/js/binance.js#L838) as the [handling of the response](https://github.com/kroitor/ccxt.pro/blob/0.8.14/js/binance.js#L900-L902) only works with SPOT streams as it matches the [SPOT balance docs](https://binance-docs.github.io/apidocs/spot/en/#payload-account-update), but if you check the [FUTURE balance docs](https://binance-docs.github.io/apidocs/futures/en/#event-balance-and-position-update), you can see two things: 
a) they are sending different parameters for future balance updates, 
b) as I can see, unfortunately there is not even any info about 'free', 'used' and 'total' balance, only info about 'wallet balance', and positions, and some other stuff. Maybe we can calculate the free/used/total based on these?
(this applies to USD-M and COIN-M futures too)

---

- Programming Language version: NodeJS
- CCXT version: 1.55.18
- CCXT Pro version: 0.8.14

**Comment by frosty00** [comment]
> The first problem is that watchBalance() only gets information about changes in the balance, so if I start the watch loop, I will not get any balance information, only balance updates. Because of this, I tried calling fetchBalance() first, and set its results to the balance property manually: exchange.balance.future = await exchange.fetchBalance(); then start the watcher. This could work in theory, but as soon as I call watchBalance(), it resets this.balances (if no other stream is running/started), so again, I have empty balances. (this is also related to #9835)

we can make watchBalance instantiate the balance to the result of fetchBalance, binance balance response contains a timestamp and so do the watchBalance updates 

> The other problem with balances is with handleBalance() as the handling of the response only works with SPOT streams as it matches the SPOT balance docs, but if you check the FUTURE balance docs, you can see two things:
a) they are sending different parameters for future balance updates,
b) as I can see, unfortunately there is not even any info about 'free', 'used' and 'total' balance, only info about 'wallet balance', and positions, and some other stuff. Maybe we can calculate the free/used/total based on these? Well, I guess this is the moment I have to rely on you.

in order to receive the futures balance updates you must set `binance.options['defaultMode'] = 'future'` or use `ccxtpro.binanceusdm`

**Comment by kroitor** [comment]
> we can make watchBalance instantiate the balance to the result of fetchBalance, binance balance response contains a timestamp and so do the watchBalance updates

If we do, I think this should be made optional, since it's app-specific.

@frzsombor Will post a short snippet on how to initialize the balance with fetchBalance's result using the current version of the lib here.

**Comment by frzsombor** [comment]
@frosty00 
> we can make watchBalance instantiate the balance to the result of fetchBalance, binance balance response contains a timestamp and so do the watchBalance updates

I guess that would be great for most projects!

> in order to receive the futures balance updates you must set `binance.options['defaultMode'] = 'future'` or use `ccxtpro.binanceusdm`

Done that, the problem is that the part that I [linked](https://github.com/kroitor/ccxt.pro/blob/0.8.14/js/binance.js#L900-L902) above does not make a difference and always expects a response based on the [spot docs](https://binance-docs.github.io/apidocs/spot/en/#payload-account-update) which is different from the [future docs](https://binance-docs.github.io/apidocs/futures/en/#event-balance-and-position-update) (link with anchor).

**Comment by frzsombor** [comment]
@kroitor 

> Will post a short snippet on how to initialize the balance with fetchBalance's result using the current version of the lib here.

That would be great, thanks!

**Comment by frosty00** [comment]
> Done that, the problem is that the part that I linked above does not make a difference and always expects a response based on the spot docs which is different from the future docs (links with anchor).

Have you tried making an order on the futures api while watching the futures balance?

**Comment by frzsombor** [comment]
@frosty00 Yes, and I have received a balance update, but it didn't work as I described above.

However I see that you guys have made a great progress to fix this in just a few hours.
I will start testing it soon.

**Comment by frzsombor** [comment]
Reporting back as of v0.8.17:

1) Right now it looks like we are looking for [`currencyId`](https://github.com/kroitor/ccxt.pro/blob/0.8.17/js/binance.js#L936) on a _wrong "level"_, and the variable gets a corrupted value, so the rest of the code fails too. From the [docs](https://binance-docs.github.io/apidocs/futures/en/#event-balance-and-position-update) I see that `message.a` is the full _"Update Data"_, which can contain _"Balances"_ data under `message.a.B` which is an array, and I think we should iterate through that array (of objects). Those objects do have an `a` property that is actually the currencyId for each array elem we are looking for.
2) Other thing I noticed is that we are trying to get a _"delta"_ from `message.d`, but unfortunately I don't see anything like this in the [future docs](https://binance-docs.github.io/apidocs/futures/en/#event-balance-and-position-update) (and in the response). That endpoint does not provide this value anywhere on any object level. It seems like `delta` is only available in [SPOT](https://binance-docs.github.io/apidocs/spot/en/#payload-balance-update) but not in futures.

Hope that this helps!

Image attached:

![image](https://user-images.githubusercontent.com/7306657/130076103-891245bc-14e2-454b-bf55-426cb0a331a7.png)

**Comment by frosty00** [comment]
I've refixed it https://github.com/kroitor/ccxt.pro/pull/206

**Comment by frzsombor** [comment]
Thanks for your quick help, it looks like it's working now for the "total" balance amount.

_Just for future reference:_ 
Will Binance _Future_ (USD-M & COIN-M) watchBalance only watch the "total" balance and can not track "free" and "used" amounts like in _Spot trading_ mode?
