### ISSUE TITLE
Max position leverage FTX

### ISSUE THREAD

**Issue by zyang87** [ccxt/ccxt#9838]
Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows
- Programming Language version:
- CCXT version: 

```
Hi - this might be the wrong place for this but could you direct me to a way that we can ping the "max position leverage" on FTX
i see 
 def fetch_account_positions(self, symbols=None, params={}):
        self.load_markets()
        response = self.privateGetAccount(params)

and this gets me the account/ sub account wide but im looking for each position.

EX BTC vs ETH vs XRP vs other alt coins will have different values as i take larger positions 

![Capture](https://user-images.githubusercontent.com/37151523/130114544-97ba7531-7003-4b1a-b62b-8e078a86b98f.JPG)

to clarify this would be different than margin marginFraction as it is contract specific 
https://help.ftx.com/hc/en-us/articles/360027668832-Contracts-Specs

```

```

**Comment by ttodua** [comment]
as noted recently, FTX has reduced all future/perpetuals' maximum leverage down to `20x`. so, that is maximum leverage.
We are in the process to implement getters/setters for leverages and some exchanges in ccxt already implement `fetchLeverageTies, fetchLeverage, setLeverage` methods, you might check them out if needed for specific exchange.

Let us know if you have any issue with CCXT.
