### ISSUE TITLE
How to make a Kucoin futures order with ccxt in python?

### ISSUE THREAD

**Issue by slhawk98** [ccxt/ccxt#9839]
- OS: Windows 10
- Programming Language version: Python 3.8.5
- CCXT version: 1.55.20

The following code work binance futures using ccxt. What is the correct code/configuration for kucoin futures?

import ccxt 
import  pandas as pd

binance = ccxt.binance() 
binance.options = {'defaultType': 'delivery', 'adjustForTimeDifference': True}
securities = pd.DataFrame(binance.load_markets()).transpose() 
print(securities)

**Comment by slhawk98** [comment]
I get the following errors when I substitute "binance = ccxt.kucoin()"

Traceback (most recent call last):
  File "c:/vscode/kucoin.ccxt.py", line 7, in <module>
    securities = pd.DataFrame(binance.load_markets()).transpose()
defaultVersion = self.safe_string(methodVersions, path, self.options['version'])
KeyError: 'version'

**Comment by kroitor** [comment]
Kucoin Futures has been added in CCXT 1.65.30+.
