### ISSUE TITLE
idex bsc. does ccxt do it?

### ISSUE THREAD

**Issue by fernandobender** [ccxt/ccxt#9840]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: lubuntu 20.04
- Programming Language version: python.
- CCXT version: 1.55.13

```
REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS
```
$ docker-compose run --rm freqtrade list-pairs --exchange idex --quote bnb
```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
```
Exchange IDEX has 0 active pairs with bnb as quote currency.

i am not sure idex.py includes bsc. i think it doesn't. hence it assumes all pairs are on eth mainnet.
could this be fixed?
trading on dexes is important for custody reasons.
trading on eth network is unfeasible.
bsc is one of the good options and idex.bsc is a way through.

thank you.
fernando a. bender

**Comment by frosty00** [comment]
@fernandobender, you can switch to bsc by doing:

```
idex.options['network'] = 'BSC'
```
