### ISSUE TITLE
No timestamp-like field when loading markets for FTX

### ISSUE THREAD

**Issue by DavideColdebellaMelanion** [ccxt/ccxt#9842]
Currently using ccxt on Jupyter Notebook, version: 1.55.20, on Windows 10, python 3.8.11.

When loading markets for exchanges like binance, binancecoinm, binanceusdm there is a timestamp field in the JSON file called "expiryDatetime", from which a user can get the expiry of a particular market.

For another exchange like deribit, a user can recover the expiry by looking at the field "info" > "expiration_timestamp".

However, there is no such timestamp-like field for ftx. Looking at their API, there are two relevant methods:
 - https://docs.ftx.com/#get-markets
 - https://docs.ftx.com/#list-all-futures
and they provide similar/overlapping information, but the second method especially returns the "expiry" field.

Is this a bug or is this intentional?

**Comment by ttodua** [comment]
Currently, CCXT market(s) include key named `expiry`. I've checked and it is set for FTX markets too, but only expirable futures, ccxt symbols for them are like: `AAVE/USD:USD-220930` or etc... you can check then by `console.log( Object.keys(exchange.markets))`.

for spot/swaps, of course there is no expiry set (the value of `expiry` key is set to `undefined`).

let us know if you have issues with ccxt.
