### ISSUE TITLE
Place an order at a rival price error

### ISSUE THREAD

**Issue by pnama** [ccxt/ccxt#9845]
hello. I'm trying to make a stop limit order for bitgt exchchange. But I'm getting an error message "msg":"Place an order at a rival price must not be blank". What is the proper way to create a stop limit order? :(

Thank you always!

params = {
  'type': 3,
  'stopPrice': 49000   // also tried price instead of stopPrice
}
order = bitget.create_order('CMT_BTCUSDT', 3, 'sell', 1, None, params)

**Comment by kroitor** [comment]
@pnama please, paste your versions, your code and your verbose output: https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

**Comment by pnama** [comment]
Sorry about that. My current environment is pycharm with ccxt v1.55.22 running on windows 10 and the verbose output shows as below.

Traceback (most recent call last):
    response.raise_for_status()
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://capi.bitget.com/api/swap/v3/order/placeOrder

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    order = bitget.create_order('CMT_BTCUSDT', 3, 'sell', 1, None, params)
    response = getattr(self, method)(self.extend(request, params))
    return entry(_self, **inner_kwargs)
    return self.fetch2(path, api, method, params, headers, body)
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
    self.throw_exactly_matched_exception(self.exceptions['exact'], errorCode, feedback)
    raise exact[string](message)
ccxt.base.errors.ExchangeError: bitget {"code":"40017","msg":"Place an order at a rival price must not be blank","requestTime":1629560076887,"data":null}

**Comment by kroitor** [comment]
@pnama please, paste your code, including the definition of `params` and exchange instantiation, but without your keys. Also, please, enable verbose mode output.

```Python
import ccxt

exchange = ccxt.bitget({
    # your keys here
})

markets = exchange.load_markets()

exchange.verbose = True

symbol = 'CMT_BTCUSDT'
type = 'market'  # or 'market'
side = 'sell'
amount = 1
price = None
params = {}

order = exchange.create_order(symbol, type, side, amount, price, params)
```

Paste your entire output here.

**Comment by pnama** [comment]
import ccxt

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.bitget({
    # your keys here
})

markets = exchange.load_markets()

exchange.verbose = True

params = {
    'type': 3,
    'stopPrice': 49000
}

order = exchange.create_order('CMT_BTCUSDT', 3, 'sell', 1, None, params)

------------------------------------------------------------------------------------------------------------

CCXT Version: 1.55.22

Request: GET https://api.bitget.com/api/v1/account/accounts?method=accounts&sign=
Response: GET https://api.bitget.com/api/v1/account/accounts?method=accounts&sign=
Request: POST https://capi.bitget.com/api/swap/v3/order/placeOrder
Response: POST https://capi.bitget.com/api/swap/v3/order/placeOrder 400 {'Date': 'Sat, 21 Aug 2021 16:12:40 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '114', 'Connection': 'keep-alive', 'Vary': 'Origin, Access-Control-Request-Method, Access-Control-Request-Headers', 'Set-Cookie': 'locale=en-US; Max-Age=; Expires=Sat, 28-Aug-2021 ; Path=/', 'X-RateLimit-Limit': '10', 'X-RateLimit-Remaining': '9', 'X-RateLimit-Used': '1', 'X-RateLimit-Reset': '1629562361642', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Frame-Options': 'DENY', 'Server': 'Nginx'} {"code":"40017","msg":"Place an order at a rival price must not be blank","requestTime":1629562360642,"data":null}
Traceback (most recent call last):
  File "C:" line 597, in fetch
    response.raise_for_status()
  File "C:", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://capi.bitget.com/api/swap/v3/order/placeOrder

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/", line 18, in <module>
    order = exchange.create_order('CMT_BTCUSDT', 3, 'sell', 1, None, params)
  File "C:", line 1979, in create_order
    response = getattr(self, method)(self.extend(request, params))
  File "C:", line 463, in inner
    return entry(_self, **inner_kwargs)
  File "C:", line 490, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:", line 486, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:", line 613, in fetch
    self.handle_errors(http_status_code, http_status_text, url, method, headers, http_response, json_response, request_headers, request_body)
  File "C:", line 2761, in handle_errors
    self.throw_exactly_matched_exceptaion(self.exceptions['exact'], errorCode, feedback)
  File "C:", line 504, in throw_exactly_matched_exception
    raise exact[string](message)
ccxt.base.errors.ExchangeError: bitget {"code":"40017","msg":"Place an order at a rival price must not be blank","requestTime":1629562360642,"data":null}

Process finished with exit code 1

**Comment by pnama** [comment]
I opened bitget.py to fix the issue mentioned above and I found 'stopPrice': None. Does this mean we cannot order stop-loss order at this point?

**Comment by DUK3135** [comment]
I'm not really sure bro all I know is you might have to put things even
more simplified more than you already are so if you bare with me and if I
can do any one a favor back I will make it happen o just know that i have
to owed actually I know I have payments coming or owed on top of that I
also know that its probably my fault or my significant inexperience on the
details of a lot of this stuff but I'm learning sorry for any inconvenience
or hold ups i may have caused

**Comment by pnama** [comment]
I just switched back to Binance which has been working since the beginning. Everything is cool.
