### ISSUE TITLE
What's the difference ccxt.binance({'options': { 'defaultType': 'future', }}) and cctx.binanceusdm()?

### ISSUE THREAD

**Issue by shuaixr** [ccxt/ccxt#9846]
I've noticed that there are two options for using binance future
`ccxt.binance({
    'options': {
        'defaultType': 'future',
    }
})`
and
`ccxt.binanceusdm({...})`
What's the difference between them?

**Comment by frosty00** [comment]
There is no difference, binanceusdm is just an alias for the former syntax
