### ISSUE TITLE
Which manual is maintained?

### ISSUE THREAD

**Issue by ttodua** [ccxt/ccxt#9847]
I've asked this question as a comment, but it was left unanswered. So, my question:

which Manual is up-to-date and which one is abandoned?

- https://github.com/ccxt/ccxt/wiki/Manual
- https://ccxt.readthedocs.io/en/latest/manual.html

**Comment by kroitor** [comment]
At this time both versions are maintained and should be up to date. In fact, the same doc source is used to generate them both. One is a mirror of the other. Hope that answers your question, let us know if not.

**Comment by ttodua** [comment]
Well, imho, it's better there was one public-facing version of DOCS site, making less confusion. thnx.

**Comment by kroitor** [comment]
> Well, imho, it's better there was one public-facing version of DOCS site, making less confusion. thnx.

We would be happy to have just one, but the source websites can be occasionally unavailable, therefore we have two. You can think of them as of a mirror. They're both updated simultaneously+automatically on each build.
