### ISSUE TITLE
Bittrex fetchMyTrades incomplete

### ISSUE THREAD

**Issue by ThaddeusB** [ccxt/ccxt#9851]
It appears that the "fetchMyTrades" function for Bittrex is implemented by using privateGetOrdersClosed.  However, this won't capture partial fills.  In version 3 of the API, there is an executions endpoint that will do this: https://bittrex.github.io/api/v3#operation--executions-get

**Comment by ttodua** [comment]
Late reply here - that was updated several months ago, and bittrex implementation now uses that endpoint.
Let us know if you will face other issues.
