### ISSUE TITLE
Missing data from 2am UTC to 5am UTC with binance

### ISSUE THREAD

**Issue by NicolasWent** [ccxt/ccxt#9854]
Hello,

I got an issue with binance and ccxt : The ohlcv data in hours is inexistent every day from 2am to 5am UTC.

Here are the required fields:

- OS: Manjaro v21.0.5
- Programming Language version: Python 3.9.5
- CCXT version: 1.51.23

Code to reproduce

```
import ccxt
exchanges = ccxt.binance()
data = exchanges.fetch_ohlcv("BTC/EUR", '1h', since=1628028000000, limit=2463704)
print(data[219][0])
print(data[220][0])
```

With this code you will get:
1628816400000 and 1628834400000

Which are the milliseconds for Fri Aug 13 2021 01:00:00 UTC and Fri Aug 13 2021 06:00:00 UTC (data from website: https://currentmillis.com/)

We can get data for these two but not the one between. We get the data correctly for the rest of the day.

I find it weird that we do not have data during this time since the cryptocurrency market is oppened 24/7.

I hope someone can help me with this issue

**Comment by kroitor** [comment]
Let us know if this does not answer your question: https://www.binance.com/en/support/announcement/3ef1861772a44c67acc2c9f5ec9f87e4

**Comment by NicolasWent** [comment]
Hello,

Thank you very much for your answer, I didn't know I was testing right during binance upgrade.
