### ISSUE TITLE
Standalone version?

### ISSUE THREAD

**Issue by ttodua** [ccxt/ccxt#9859]
I want to avoid `npm install` of ccxt to have it in node_modules. Is there any way, to build a single js file, which I can include in my project like:

`const ccxt = require ("./my_complete_ccxt.js"); `

the `ccxt.browser.js` in dist folder doesn't work in nodejs when doing:

`const ccxt = require ("./ccxt.browser.js"); `

---
I've tried `npm install` and then `npm run build`  and neither a new .js file is created in "dist" folder.

**Comment by kroitor** [comment]
@ttodua you can clone the repository and include 'ccxt.js' from the repo root. Alternatively, you can even install ccxt globally from your local working copy and avoid having it in node_modules. You can also use npm linking to achieve the same effect. It mostly depends on your requirements and goals, please, elaborate on that if possible.

**Comment by ttodua** [comment]
Thanks kroitor, yes, the case is specific and I'll elaborate now.
I've a small app, where I don't have node_modules folder , instead only several js files only. (even NPM is not installed on system where the app will be used). So,  I want to include only one full-build of ccxt-js file (even if it will be 10mb), without need to have ccxt with its folders.  Is something like that possible? thanks

**Comment by kroitor** [comment]
@ttodua we use `browserify` for the purpose. In general, it's a tool that takes a JS file (and the walks the require-tree over all underlying files), and compiles it into a single large script bundling various node polyfills into it. You can achieve the same result with the `browserify` tool if you switch off unnecessary browser-functionality with the `--bare` key or using other command line args: https://github.com/browserify/browserify#usage
Hope that helps, let us know if not. Feel free to reopen this issue or just ask further questions if any.

**Comment by kroitor** [comment]
P.S. https://browserify.org/

**Comment by ttodua** [comment]
Tons of thanks!

**Comment by ttodua** [comment]
btw Kroitor, :)) I promise this is my last remainder and I wouldnt bother you again - if there is any chance that you replied in "load-markets dont load newly added pairs" topic, let me know.

**Comment by kroitor** [comment]
@ttodua i'll do my best to post that example soon, thx for your patience!
