### ISSUE TITLE
How to use networks in withdrawal ?

### ISSUE THREAD

**Issue by developer-devo** [ccxt/ccxt#9865]
We are using CCXT to connect with exchanges, we are using withdrawal and deposit but we didnt find option to select network for a particular token. How can we get list of networks for a token ?

Please help!

**Comment by kroitor** [comment]
@developer-devo the `network` aspect is not fully unified yet, it's a work in progress. At this point you can already use that with CCXT as a param-override for the `withdraw()` call and for the `fetchDepositAddress()` call in an exchange-specific way:

- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

You can find some examples here:

- https://github.com/ccxt/ccxt/tree/master/examples/py/kucoin-withdraw-chain.py
- https://github.com/ccxt/ccxt/blob/master/js/kucoin.js#L1477
- https://github.com/ccxt/ccxt/blob/master/js/binance.js#L874
- https://github.com/ccxt/ccxt/blob/master/js/binance.js#L3255
- https://github.com/ccxt/ccxt/blob/master/js/binance.js#L3400

Also, OKEX, for example, will serve them as separate currency codes for different networks:

- https://github.com/ccxt/ccxt/blob/master/js/okex.js#L2124

We hope to deliver a better unification of the underlying networks soon.

Related: https://github.com/ccxt/ccxt/issues/9676#issuecomment-890374595
