### ISSUE TITLE
Issue in "fetch-markets" precisions.

### ISSUE THREAD

**Issue by ttodua** [ccxt/ccxt#9867]
The "precision" parameter, which is returned from specific exchange's "fetch_markets" function, is not consistent across ccxt library, and causes problems in applications.
For example, try binance's and ascendex's  fetch-markets, and check "btc/usdt". you will see, the "precision.price" parameter of that market is  0.0001 for Ascendex, and  4 for binance.
Actually, they both mean exactly same thing (to have 4 decimals in price after dot, like `49999.1234`) , however, the CCXT API is not consistent and reliable to rely on that parameter. 

Is there any plans to revise all "precision" components of exchange classes, whether they are coded correctly or not?  What is the standard -  in my specific given example, should there be 0.0001 or 4?

**Comment by ttodua** [comment]
(at this moment, as a possible workaround I am thinking to use:   `var pricePrecision= pricePrecision==0 ? 0 : ( pricePrecision<1 && pricePrecision>0 ? pricePrecision: 1/pricePrecision);`  but not sure if that will solve the problem correctly. )

**Comment by kroitor** [comment]
@ttodua this is actually documented in the Manual, see the `exchange.precisionMode` flag. If precisionMode is DECIMAL_DIGITS, then the precision is in decimal places after the dot. If precisionMode is TICK_SIZE, then it is the step between two consequent values. We support both types of precision, depending on the rules of the underlying exchange.

- https://github.com/ccxt/ccxt/wiki/Manual#methods-for-formatting-decimals

> Actually, they both mean exactly same thing (to have 4 decimals in price after dot, like `49999.1234`) , however, the CCXT API is not consistent and reliable to rely on that parameter.

No, they don't mean the same thing. The TICK_SIZE precision may be 0.05, while decimal precision can handle powers of ten only.

> What is the standard - in my specific given example, should there be 0.0001 or 4?

The standard is that it should be either 0.0XXX with TICK_SIZE, and YYY with DECIMAL_PLACES.

Hope that answers your question, let us know if not.

**Comment by kroitor** [comment]
P.S. There's also a third mode called `SIGNIFICANT_DIGITS` (bitfinex / bitfinex2) with a meaning slightly different from TICK_SIZE and DECIMAL_PLACES.

**Comment by ttodua** [comment]
Excellent answer, thanks.
