### ISSUE TITLE
bybit rate limit status is missing in ccxt responses

### ISSUE THREAD

**Issue by coinabc123** [ccxt/ccxt#9869]
Hi,

the rate limit status is missing from the ccxt answers for the exchange bybit.

In the response from the exchange these are still preserved, but in the parsed resulte variable these are then no longer preserved.

These are the keys in the response dict:

'rate_limit_status' = {str} '99'
'rate_limit_reset_ms' = {str} '1629850386340'
'rate_limit' = {str} '100'

I tested it with the latest ccxt version 1.55.45 (python)

**Comment by kroitor** [comment]
You can get that from `exchange.last_response_headers` after each call. Hope that answers your question. Let us know if not.

- https://github.com/ccxt/ccxt/wiki/Manual#exchange-properties
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki/
