### ISSUE TITLE
Some exchanges do not implement fetchOHLCV properly

### ISSUE THREAD

**Issue by jakemayeux** [ccxt/ccxt#987]
The following exchanges do not use the 'since' parameter of fetchOHLCV. For example, bitlish always get data 30 days back, it should use the data passed in the since parameter instead.

```
    async fetchOHLCV (symbol, timeframe = '1m', since = undefined, limit = undefined, params = {}) {
        await this.loadMarkets ();
        // let market = this.market (symbol);
        let now = this.seconds ();
        let start = now - 86400 * 30; // last 30 days
        let interval = [ start.toString (), undefined ];
        return await this.publicPostOhlcv (this.extend ({
            'time_range': interval,
        }, params));
    }
```
should be changed to something like this
```
    async fetchOHLCV (symbol, timeframe = '1m', since = undefined, limit = undefined, params = {}) {
        await this.loadMarkets ();
        // let market = this.market (symbol);
        let now = this.seconds ();
        let start = since || now - 86400 * 30; // last 30 days
        let interval = [ start.toString (), undefined ];
        return await this.publicPostOhlcv (this.extend ({
            'time_range': interval,
        }, params));
    }
```
- OS: Arch Linux
- Programming Language: JavaScript
- CCXT version: 1.10.391
- Exchanges: 
```
_1btcxe
allcoin
bitlish
bitmarket
bittrex
btcexchange
btcturk
gatecoin
getbtc
hitbtc2
huobi
huobicny
huobipro
```

**Comment by kroitor** [comment]
We also need to add `parse_ohlcvs()` calls where time ranges are not supported by the exchange to filter on client side. As you may know this library is under development, some aspects may still be missing or may be not unified yet. But we are working on it. Your help would be really appreciated! 

https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

Thanks for reporting!

**Comment by jjhesk** [comment]
huobi logo
<img width="64" alt="2018-04-06 4 34 14" src="https://user-images.githubusercontent.com/629338/38411063-ce4d9374-39b8-11e8-8182-81dd15f193ce.png">

**Comment by cooperkernan** [comment]
Hmmm... assuming this is still not fixed? Purely curious!

**Comment by kroitor** [comment]
@cooperkernan as long as it is open, it means that the issue is still open. Fixed issues are usually closed )

**Comment by cooperkernan** [comment]
Makes sense. Thanks.
