### ISSUE TITLE
bitget API question

### ISSUE THREAD

**Issue by BitgetLimited** [ccxt/ccxt#9871]
hi,  I’m from bitget exchange.  our spot api address has been upgraded, this is the [new spot  Api](https://bitgetlimited.github.io/apidoc/zh/spot/#185368440e). I think ccxt should need to be synchronized.

and our swap api will be offline later, I would like to invite you to access the [Mix Api](https://bitgetlimited.github.io/apidoc/zh/mix/)

**Comment by BitgetLimited** [comment]
@kroitor  hi, I want to ask how we are progressing on the spot and mix interfaces，Is there anything i can help

**Comment by Orangat** [comment]
@kroitor Can you please provide estimates for this?

**Comment by kroitor** [comment]
@Orangat please, check this FAQ: https://github.com/ccxt/ccxt/wiki/FAQ#when-will-you-add-the-support-for-an-exchange-requested-in-the-issues

**Comment by kroitor** [comment]
Good news! Bitget API has been updated in CCXT 1.74.41+
