### ISSUE TITLE
how to place OCO order in okex 

### ISSUE THREAD

**Issue by jaype0x** [ccxt/ccxt#9873]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:

```
REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS
```

```
AttributeError: 'okex5' object has no attribute 'private_post_order_oco'```

**Comment by Ali-moradi-dev** [comment]
dear @jaype0x, in OKEx we have [AlgoOrder](https://www.okex.com/docs-v5/en/#rest-api-trade-place-algo-order) to place a stop order or OCO orders 
you can check out this link 

you can see how to implement an [AlgoOrder](https://www.okex.com/docs-v5/en/#rest-api-trade-place-algo-order) in OKEx:
```
markets = exchange.load_markets()
market = exchange.market(symbol)
data = exchange.privatePostTradeOrderAlgo({
    "instId": market['id'],
    "side": side,
    "tdMode": "cash",
    "ordType": "oco",
    "sz": amount,
    "tpTriggerPx": tp_trigger_price,
    "tpOrdPx": tp_order_price,
    "slTriggerPx": sl_trigger_price,
    "slOrdPx": sl_order_price
}) 
```

**Comment by kroitor** [comment]
@Ali-moradi-dev hey! Thanks a lot for your involvement and your help answering the questions! It would be great to get in contact with you! If possible, please, reach out to igor@ccxt.trade if/when you have the time. Thx again!

**Comment by akwin1234** [comment]
> dear @jaype0x, in OKEx we have [AlgoOrder](https://www.okex.com/docs-v5/en/#rest-api-trade-place-algo-order) to place a stop order or OCO orders you can see how to implement an [AlgoOrder](https://www.okex.com/docs-v5/en/#rest-api-trade-place-algo-order) in OKEx:
> 
> ```
> markets = exchange.load_markets()
> market = exchange.market(symbol)
> data = exchange.privatePostTradeOrderAlgo({
>     "instId": market['id'],
>     "side": side,
>     "tdMode": "cash",
>     "ordType": "oco",
>     "sz": amount,
>     "tpTriggerPx": tp_trigger_price,
>     "tpOrdPx": tp_order_price,
>     "slTriggerPx": sl_trigger_price,
>     "slOrdPx": sl_order_price
> }) 
> ```

What will be the same for mask or last in oco?

**Comment by ttodua** [comment]
> What will be the same for mask or last in oco?

Depends whether that exchange supports that parameter at all, and if not, then what is its default (i suppose in most cases it's last price, but still, refer to that specific exchange's api docs, until CCXT unifies them)
