### ISSUE TITLE
fetch_ticker() call 3 requests to API

### ISSUE THREAD

**Issue by JosefJezek** [ccxt/ccxt#988]
Why fetch_ticker() call 3 requests to API?

```py
bittrex = ccxt.bittrex ({ 'verbose': True })
print(bittrex.fetch_ticker('ETH/BTC'))
```

GET https://bittrex.com/api/v2.0/pub/Markets/GetMarketSummaries
GET https://bittrex.com/api/v1.1/public/getcurrencies
GET https://bittrex.com/api/v1.1/public/getmarketsummary?market=BTC-ETH

**Comment by kroitor** [comment]
https://github.com/ccxt/ccxt/wiki/Manual#loading-markets

**Comment by JosefJezek** [comment]
@kroitor ok

Could you add an option for load only markets data, without currencies?

**Comment by kroitor** [comment]
@JosefJezek sure, will do that soon, hopefully.

**Comment by kroitor** [comment]
@JosefJezek until we add an option for it, a temporary solution for you would be to change the code like this:

```Python
bittrex = ccxt.bittrex({ 'verbose': True })
markets = bittrex.fetch_markets()  # Just one call for markets, no currencies
bittrex.set_markets(markets)
print(bittrex.fetch_ticker('ETH/BTC'))
```
