### ISSUE TITLE
Introducing Wormhole!

### ISSUE THREAD

**Issue by frosty00** [ccxt/ccxt#9882]
CCXT is proud to announce it's most recent venture - [wormhole](https://bpaybridge.com). Instantly send crypto-assets between exchange for a fraction of the fee!

[![Wormhole](https://bpaybridge.com/static/logo.png)](https://bpaybridge.com)

### How it works

Wormhole allows users to send crypto assets between exchanges instantly by utilising internal transfers on exchanges. Currently you may use wormhole to send crypto assets to anybody with an okex account. Simply go to the website and add your okex account email in https://bpaybridge.com/settings the make a new transfer in https://bpaybridge.com/send

Once you have created the transfer scan the qr code on in binance pay and pay the order. Automatically will make an internal transfer on okex to the email you specified and credit your okex account without making an on-chain transfer. The makes it is faster and cheaper than traditional cryptocurrencies.

Please feel free to use the website and provide us with any feedback

**Comment by drsavant-pub** [comment]
When I try to look at the docs for "wormhole" (so I can see how it works) it takes me to a page for CCXT.

How do I find out how this works, does it have an api, and can I implement it into my bot?  How many exchanges does it work with?  Does it only work with Binance and Okex right now?

**Comment by frosty00** [comment]
@drsavant-pub I've made some edits to the website now, you can checkout https://bpaybridge.com

We are currently researching the ability to add more exchanges

**Comment by cdcv** [comment]
Is wormhole working?  The https://bpaybridge.com website appears to be down.  Thanks.

**Comment by frosty00** [comment]
@cdcv, the webpage is offline rn, we hope to release a new version soon

**Comment by cdcv** [comment]
Thank you.  Do you know about when you expect the new version to available?  Is there still a working version of the old version that can be used in the meantime?  I couldn't find the documentation for it since the website wasn't available.

**Comment by frosty00** [comment]
> Thank you. Do you know about when you expect the new version to available? Is there still a working version of the old version that can be used in the meantime? I couldn't find the documentation for it since the website wasn't available.

should come sometime this week hopefully
