### ISSUE TITLE
Possibility to CREATE a Binance FUTURES TRADING GRID with API

### ISSUE THREAD

**Issue by AxelGUILLAUMET** [ccxt/ccxt#9883]
Dear friends.

I searched a lot about that and I didn't found anything... Is there a posibility to doing that? Create THIS but with the API

![image](https://user-images.githubusercontent.com/47301337/131061901-8f4d70ac-1021-492b-a0ae-605e3f2ab130.png)

Best regards.

**Comment by YuriyTigiev** [comment]
@AxelGUILLAUMET  check this example https://youtu.be/kLATKNzbUOE

**Comment by kroitor** [comment]
@YuriyTigiev  thank you! Closing this as answered for now. @AxelGUILLAUMET feel free to reopen it if necessary or just ask further questions if any.
