### ISSUE TITLE
List open transactions - PHP - fapiPrivateV2_get_positionrisk

### ISSUE THREAD

**Issue by alidogrull** [ccxt/ccxt#9885]
- OS: Windows 10
- Programming Language version: PHP 7.3.28
- CCXT version: 1.55.43

Hello,

I want to take all open positions. The code below shows multiple positions that are not open. How can I get only open positions? The currently open position is BNB/USDT.

Thanks...
![indir](https://user-images.githubusercontent.com/45078905/131119618-2fd315dc-c7e3-42db-86f9-6a636e363b34.png)

```
$exchange_id = 'binance';
$exchange_class = "\\ccxt\\$exchange_id";
$exchange = new $exchange_class(array(
    'apiKey' => "xxxx",
    'secret' => "xxxx",
));

$exchange->load_markets();
$exchange->verbose = true;


$result = $exchange->fapiPrivateV2_get_positionrisk();
var_dump($result);

```

**Comment by ttodua** [comment]
why not use the unified methods? you should do this:
```
$exchange_id = 'binanceusdm';  // this is for  swap/future
...
$result = $exchange->fetchPositions();
```

Let us know if you have any further issue.
