### ISSUE TITLE
crypto-watchdog shown in examples not included?

### ISSUE THREAD

**Issue by robertbelgrave** [ccxt/ccxt#989]
Hi, I'd love to repurpose and use the 'crypto-watchdog' shown on the examples page and in the gif below.

https://user-images.githubusercontent.com/1294454/31798504-ca2af4cc-b53c-11e7-946c-620d744f6d16.gif

Is there any chance you can send me the javascript or include it in the examples folder?

Thanks

**Comment by kroitor** [comment]
Hi! 

I did it briefly with a few small tools, and now I can't find it in my history, but it didn't take too long. It's mostly there, check out the following:
- https://github.com/ccxt/ccxt/blob/master/examples/js/basic-chart.js
- https://github.com/ccxt/ccxt/blob/master/examples/js/fetch-ohlcv-cex.js
- https://github.com/ccxt/ccxt/blob/master/examples/py/basic-chart.py
- https://github.com/ccxt/ccxt/blob/master/examples/py/binance-fetch-ohlcv.py
- https://github.com/kroitor/asciichart
- https://github.com/xpl/ansicolor
- https://github.com/kroitor/asciichart/issues/3#issuecomment-338340713
- https://github.com/chjj/blessed

↑ From there making such a *terminal window* should be straightforward.

I also used [GetWindowId](https://github.com/smokris/GetWindowID) and `screencapture + a shell script` for Mac OS to make the a screenshot once in a minute and compile it into an accelerated gif animation.

```shell
# i=100;while [ 1 ];do screencapture -l$(../GetWindowID/GetWindowId "Terminal" "crypto-watchdog") -t jpg -x $i.jpg; let i++;sleep 60; done
i=100;while [ 1 ];do screencapture -o -l1762 -t jpg -x $i.jpg; let i++;sleep 60; done
```

Let me know if it answers your question. Thx!
