### ISSUE TITLE
kucoin Incorrect withdrawal address

### ISSUE THREAD

**Issue by kicksomedust** [ccxt/ccxt#9891]
- OS: Ubuntu
- Programming Language version: "typescript": "^4.3.5"
- CCXT version: 
  "packages": {
    "": {
      "version": "1.0.0",
      "license": "MIT",
      "dependencies": {
        "ccxt": "^1.55.55",
        "dotenv": "^10.0.0",
        "ts-node": "^10.1.0",
        "typescript": "^4.4.2"
      }
    },
//sellExchange is binance
//buyExchaneg is kucoin
const symbol = "COTI"
let address = await sellExchange.fetchDepositAddress(symbol);
await buyExchange.withdraw(symbol, 40, 0x63634...);
It seems that kucoin supposes the network to be of a certain type that is not the type binance returns, binance returns a BSC type. kucoin expects a native type (if it's called thus).

```
kucoin Incorrect withdrawal address
```

**Comment by kroitor** [comment]
You can do that as documented in the Manual:

- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params

See this example:

- https://github.com/ccxt/ccxt/blob/master/examples/js/withdraw-from-one-exchange-to-another.js

```JavaScript
"use strict";

const ccxt = require ('ccxt')

console.log ('CCXT Version', ccxt.version)

async function main () {

    const binance = new ccxt.binance ({
        'apiKey': 'YOUR_API_KEY',
        'secret': 'YOUR_SECRET',
        'options': {
            'fetchCurrencies': true,
        },
    })

    const kucoin = new ccxt.kucoin ({
        'apiKey': 'YOUR_API_KEY',
        'secret': 'YOUR_SECRET',
        'password': 'YOUR_API_PASSWORD',
    })

    await binance.loadMarkets ()
    await kucoin.loadMarkets ()

    binance.verbose = true
    kucoin.verbose = true

    const code = 'COTI'
    const amount = 40

    // https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params
    // https://binance-docs.github.io/apidocs/spot/en/#deposit-address-supporting-network-user_data
    const deposit = await binance.fetchDepositAddress (code, { 'network': 'ETH' })

    console.log ('-----------------------------------------------------------')

    console.log (depositAddress)

    console.log ('-----------------------------------------------------------')

    // https://github.com/ccxt/ccxt/wiki/Manual#overriding-unified-api-params
    // https://docs.kucoin.com/#apply-withdraw-2
    const withdrawal = await kucoin.withdraw (code, amount, deposit['address'], deposit['tag'], { 'chain': 'ERC20' })

    console.log ('-----------------------------------------------------------')

    console.log (withdrawal)

}

main ()
```

**Comment by kicksomedust** [comment]
Sorry. I missed that, but thanks for taking the trouble to let me know.
