### ISSUE TITLE
kucoin load futures markets and open positions

### ISSUE THREAD

**Issue by GoodyNick** [ccxt/ccxt#9894]
I can instantiate exchange class in python with kucoin futures api keys and pass, and I can get my account balance, but when I call exchange.load_markets(), the list returned just contains spot markets, i.e. it does not have symbols such as XBTUSDM, 
besides, I can not open positions via create_order() function, Here is the sample code:

    exchange = ccxt.kucoin({
            'options':{
                    'defaultType': 'future',       
            },        
            'apiKey': cf.api_key_kucoin_2,
            'secret': cf.secret_key_kucoin_2,
            'password': cf.api_pass_kucoin_2,
    })
    # exchange.verbose = True
    pprint(exchange.fetchBalance({'type': 'futures', 'currency': 'USDT'}))
    # pprint(exchange.fetch_ohlcv(symbol='XRP-USDT', limit=10))
    pprint(exchange.load_markets(params={'type': 'future'}))

**Comment by Ali-moradi-dev** [comment]
@GoodyNick  hi ,
the future section in KUCOIN is a separate part you should get another apiKey from the future section
you have to implement them manually because CCXT does not contain futures methods 
checkout this link:
[implicit-api-methods]( https://ccxt.readthedocs.io/en/latest/manual.html#implicit-api-methods)
you can search in ccxt/kucoin.py and see all of the methods you can implement
in describe section of code you can see these:
```
      'futuresPrivate': {
          'get': [
              'account-overview',
              'transaction-history',
              'deposit-address',
              'deposit-list',
              'withdrawals/quotas',
              'withdrawal-list',
              'transfer-list',
              'orders',
              'stopOrders',
              'recentDoneOrders',
              'orders/{order-id}',  # ?clientOid={client-order-id}  # get order by orderId
              'orders/byClientOid',  # ?clientOid=eresc138b21023a909e5ad59  # get order by clientOid
              'fills',
              'recentFills',
              'openOrderStatistics',
              'position',
              'positions',
              'funding-history',
          ],
          'post': [
              'withdrawals',
              'transfer-out',  # v2
              'orders',
              'position/margin/auto-deposit-status',
              'position/margin/deposit-margin',
              'bullet-private',
          ],
          'delete': [
              'withdrawals/{withdrawalId}',
              'cancel/transfer-out',
              'orders/{order-id}',
              'orders',
              'stopOrders',
          ],
      },
  },
```
for opening a market order you should act like this :
```
clientOrderId = exchange.safe_string_2({}, 'clientOid', 'clientOrderId', exchange.uuid())
data = exchange.futuresPrivatePostOrders({
    'clientOid': clientOrderId,
    'symbol': 'XLMUSDTM',
    'side': 'buy',
    'type': 'market',
    'size': '1',
    'leverage': 1
})
```

for getting order info in kucoin : 
```
data = exchange.futuresPrivateGetOrders({
    'order-id': '612b3ca1e05e8d00063a7201'
})
```
good luck

**Comment by heeropunjabi** [comment]
Suggest me idea to develop in the crypto space.
Getting bored from MNC work.
https://docs.google.com/spreadsheets/d/1j9TsMk9_ne-Rkq2LbBMAV5d6IJzR0i2Dr9_SjSMaC4s/edit?usp=sharing

**Comment by GoodyNick** [comment]
Thanks for your reply, your template works for me for opening a position in a specific futures market, but still it seems that the load_markets() method does not return list of fututes markets, 
to be more precise, the marketId argument in create order is only taken from spot markets,
so for now, it seems there is no endpoint in [kucoin futures api](https://docs.kucoin.com/futures/#general) to load list of all futures markets as it is completely implemented in Binance for example :(

**Comment by kroitor** [comment]
@GoodyNick you can still call the implicit futures API of KuCoin as documented in the Manual: https://github.com/ccxt/ccxt/wiki/Manual#implicit-api

**Comment by Ali-moradi-dev** [comment]
@GoodyNick  check out this endpoint on kucoin [open-contract-list](https://docs.kucoin.com/futures/#get-open-contract-list )

to use it with CCXT :
```
data = exchange.futuresPublicGetContractsActive({})
print(len(data['data']))
-----
65
```
there are 65 contracts in KUCOIN futures and you can see the details

**Comment by DUK3135** [comment]
Damn I really appreciate you if there is anything I can do

**Comment by Ali-moradi-dev** [comment]
@DUK3135 your welcome .

**Comment by GoodyNick** [comment]
@Ali-moradi-dev , thank you a lot! I will definitely try that :)

**Comment by jorisw** [comment]
KuCoin Futures has been added as a separate exchange as of ccxt version 1.65.33.

`const client = new ccxt.kucoinfutures({})`

**Comment by xibalbas** [comment]
@jorisw nice job
