### ISSUE TITLE
[OHLCV][Average] Get average price for a day

### ISSUE THREAD

**Issue by NicolasWent** [ccxt/ccxt#9896]
Hello,

What I would like to get is the average price of a certain coin for the day.

In the documentation I found nothing about getting the average for OHLCV values, maybe it should be a great feature to add, for example if we want the data for a day, we get the average selling price of the day, same for a minute.

I saw that there is something similar for Tickers, but the equation is: (last + open) / 2 do you think that it is good to compute the average using OHLCV with a similar equation like: (open price + closing price) / 2 ?

I hope someone can help me with that :)

**Comment by ttodua** [comment]
I think that would be beyond of CCXT's scope to calculate averages for OHLCV. However, as an optional feature, it might be possible to be built, if there are many people who might be using it. 
@kroitor it is worth to be implemented in core, enabled only by explicitly setting smth option to true?

**Comment by kroitor** [comment]
> @kroitor it is worth to be implemented in core, enabled only by explicitly setting smth option to true?

I would say, calculating the average is a one-liner expression in most languages that does not require any complex code, so it is beyond the scope of the library and it can be easily done outside of the lib, in the userland.
