### ISSUE TITLE
Volume returned from bittrex via fetch_tickers is None

### ISSUE THREAD

**Issue by irfansamdani** [ccxt/ccxt#9901]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- OS: Linux
- Programming Language version: python 3.8.10
- CCXT version: 1.55.54

```
>>> import ccxt
>>> exchange = ccxt.bittrex()
>>> tickers = exchange.fetch_tickers()
```

```
>>> tickers['BTC/USD']
{'symbol': 'BTC/USD', 'timestamp': None, 'datetime': None, 'high': None, 'low': None, 'bid': 48700.147, 'bidVolume': None, 'ask': 48707.33, 'askVolume': None, 'vwap': None, 'open': None, 'close': 48706.591, 'last': 48706.591, 'previousClose': None, 'change': None, 'percentage': None, 'average': None, 'baseVolume': None, 'quoteVolume': None, 'info': {'symbol': 'BTC-USD', 'lastTradeRate': '48706.59100000', 'bidRate': '48700.14700000', 'askRate': '48707.33000000'}}
```
As you can see from the output above, the volume is None. Am I doing something wrong?

**Comment by kroitor** [comment]
Bittrex serves very little info for tickers. Let us know if that does not answer your question: https://bittrex.github.io/api/v1-1

**Comment by irfansamdani** [comment]
Thanks for the quick reply kroitor! v1.1 still returns quite a bit of information for market summaries from bittrex (https://api.bittrex.com/api/v1.1/public/getmarketsummaries) that isn't captured in fetch_tickers. Perhaps the question I posed above stems from my lack of understanding of fetch_tickers. How does it gather the data in the background?

**Comment by kroitor** [comment]
@irfansamdani sorry, that was an old link, the proper doc is here: https://bittrex.github.io/api/v3

<img width="1608" alt="Screenshot 2021-08-31 at 13 13 04" src="https://user-images.githubusercontent.com/1294454/131485131-b3d4942a-cdb3-40e6-affb-8d21fb39ec8b.png">

> How does it gather the data in the background?

Check the source code: 

- https://github.com/ccxt/ccxt/blob/master/js/bittrex.js
- https://github.com/ccxt/ccxt/blob/master/python/ccxt/bittrex.py
- https://github.com/ccxt/ccxt/blob/master/php/bittrex.php

**Comment by irfansamdani** [comment]
Thanks for that @kroitor . That helps understand the flow. I have a follow-up question. I see the following in fetch_tickers method

```
    def fetch_tickers(self, symbols=None, params={}):
        self.load_markets()
        options = self.safe_value(self.options, 'fetchTickers', {})
        defaultMethod = self.safe_string(options, 'method', 'publicGetMarketsTickers')
        method = self.safe_string(params, 'method', defaultMethod)
        params = self.omit(params, 'method')
        response = getattr(self, method)(params)
        #
        # publicGetMarketsTickers
        #
        #     [
        #         {
        #             "symbol":"4ART-BTC",
        #             "lastTradeRate":"0.00000210",
        #             "bidRate":"0.00000210",
        #             "askRate":"0.00000215"
        #         }
        #     ]
        #
        # publicGetMarketsSummaries
        #
        #     [
        #         {
        #             "symbol":"4ART-BTC",
        #             "high":"0.00000206",
        #             "low":"0.00000196",
        #             "volume":"14871.32000233",
        #             "quoteVolume":"0.02932756",
        #             "percentChange":"1.48",
        #             "updatedAt":"2020-09-29T07:34:32.757Z"
        #         }
        #     ]
        #
        ```
Is there a specific reason that publicGetMarketsTickers was chosen over publicGetMarketsSummaries for bittrex? I see the data returned by the latter to be more inline with what other exchanges are reporting (at least the ones I've tried e.g. binance, kraken etc). Apologies in advance for not knowing the history behind this.

**Comment by kroitor** [comment]
> Is there a specific reason that publicGetMarketsTickers was chosen over publicGetMarketsSummaries for bittrex? I see the data returned by the latter to be more inline with what other exchanges are reporting (at least the ones I've tried e.g. binance, kraken etc). Apologies in advance for not knowing the history behind this.

You can call the latter endpoint like so:

```Python
import ccxt
from pprint import pprint
exchange = ccxt.bittrex({
    'options': {
        'fetchTickers': {
            'method': 'publicGetMarketsMarketSymbolSummary'
        },
    },
})
tickers = exchange.fetch_tickers()
pprint(tickers)
```

- https://github.com/ccxt/ccxt/blob/master/python/ccxt/bittrex.py#L209

**Comment by irfansamdani** [comment]
Awesome. Exactly what I was looking for. Thanks @kroitor
