### ISSUE TITLE
binance {"code":-1130,"msg":"Data sent for parameter 'limit' is not valid."}

### ISSUE THREAD

**Issue by SreekanthAvala** [ccxt/ccxt#9904]
- OS: Windows
- Programming Language version: python
- CCXT version: 1.55.15

Getting error when I add limit = more than 100
 ex: 
     allTrades = self.exchange.fetch_my_trades(symbol=symbol,since=since,limit=200)

 error : binance {"code":-1130,"msg":"Data sent for parameter 'limit' is not valid."}

it's working when limit = 100

**Comment by kroitor** [comment]
@SreekanthAvala post your verbose output plz: 

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```Python
self.exchange.verbose = True
allTrades = self.exchange.fetch_my_trades(symbol=symbol,since=since,limit=200)
```

**Comment by SreekanthAvala** [comment]
Request: GET https://testnet.binancefuture.com/dapi/v1/userTrades?timestamp=1630400302088&recvWindow=5000&symbol=BTCUSD_PERP&startTime=1630002600000&limit=200&signature=5ae56f8b3b602dc328dc5f26283ac1811101833dad2c81450491d59e930476b4 {'X-MBX-APIKEY': 'd6d082bd735115eb2e9079d0abad783787db57d1465dd35d41858d46b0a93494', 'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://testnet.binancefuture.com/dapi/v1/userTrades?timestamp=1630400302088&recvWindow=5000&symbol=BTCUSD_PERP&startTime=1630002600000&limit=200&signature=5ae56f8b3b602dc328dc5f26283ac1811101833dad2c81450491d59e930476b4 400 {'Content-Type': 'application/json', 'Content-Length': '68', 'Connection': 'keep-alive', 'Date': 'Tue, 31 Aug 2021 08:58:22 GMT', 'Server': 'Bengine', 'X-MBX-USED-WEIGHT-1M': '120', 'x-response-time': '1ms', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 7dda57f7e6978046952c757eba986c68.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'HYD50-C1', 'X-Amz-Cf-Id': 'mdsZidU9cskfcSyYpeFIkdv8be7ir8illxD7cgF4r9LjR2pMVevuqA=='} {"code":-1130,"msg":"Data sent for parameter 'limit' is not valid."}

**Comment by kroitor** [comment]
- https://binance-docs.github.io/apidocs/futures/en/#account-trade-list-user_data

> The time between startTime and endTime cannot be longer than 7 days.

Does it work like this for you ? ↓

```Python
self.exchange.verbose = True
params = {
    'endTime': startTime + 24 * 7 * 60 * 60 * 1000
}
allTrades = self.exchange.fetch_my_trades(symbol, since, 200, params)
```

**Comment by SreekanthAvala** [comment]
@kroitor  again I got the same error
```
            since = 1629657000000 
            params = {
                'endTime': since + 24 * 7 * 60 * 60 * 1000
                # 'endTime': 1630175400000  
            }
            self.exchange.verbose = True
            allTrades = self.exchange.fetch_my_trades(symbol, since, 200, params)
```


Request: GET https://testnet.binancefuture.com/dapi/v1/userTrades?timestamp=1630403936667&recvWindow=5000&symbol=BTCUSD_PERP&startTime=1629657000000&limit=200&endTime=1630261800000&signature=298dbacc90fb127540f9b3baf436d9058a875d6a1e13ba6b045b4a47efbea029 {'X-MBX-APIKEY': 'd6d082bd735115eb2e9079d0abad783787db57d1465dd35d41858d46b0a93494', 'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://testnet.binancefuture.com/dapi/v1/userTrades?timestamp=1630403936667&recvWindow=5000&symbol=BTCUSD_PERP&startTime=1629657000000&limit=200&endTime=1630261800000&signature=298dbacc90fb127540f9b3baf436d9058a875d6a1e13ba6b045b4a47efbea029 400 {'Content-Type': 'application/json', 'Content-Length': '68', 'Connection': 'keep-alive', 'Date': 'Tue, 31 Aug 2021 09:58:57 GMT', 'Server': 'Bengine', 'X-MBX-USED-WEIGHT-1M': '23', 'x-response-time': '1ms', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 11bda279a9e6aa2f34e957379f64a2ae.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'HYD50-C1', 'X-Amz-Cf-Id': 
'xghMMDE8DlzdSvUr9D9vEPKJYqV9kEQS9pxAIXeejDxSK-kwymgDTw=='} {"code":-1130,"msg":"Data sent for parameter 'limit' is not valid."}

**Comment by Seshasai-N** [comment]
Hi Sreekanth i'm also getting same issue Please send solution @kroitor. @SreekanthAvala Please let me know if you got solution.
Thanks in advance.

**Comment by ungaratto93** [comment]
Hi,

Maybe can I help u.

I look this links 
[binance-testnet-docs](https://binance-docs.github.io/apidocs/delivery_testnet/en/#account-trade-list-user_data )

[binance-delivery-docs](https://binance-docs.github.io/apidocs/delivery/en/#position-information-user_data)

endpoint: GET /dapi/v1/userTrades (HMAC SHA256)


And I search on docs the endpoint  that you are trying to get trades data, there show me the limit is max 100 and default 50. 

`<html>
<body>


limit | INT | NO | Default 50; max 100.
-- | -- | -- | --



</body>
</html>`


note: Sorry for my poor english skill communication or wrong style comment.

**Comment by ttodua** [comment]
@SreekanthAvala 
before the valid answer will be posted here, please note: in your comments you haven't mangled your API key-data (they are visible in your above posts). At this moment, please go to binance and revoke the api keys you used (while you've been posting this) and re-create a new api keys.  Note, in future, I advise not to include API-KEY info in posts.

**Comment by ttodua** [comment]
As noted/answered above, the maximum limit is `100` for that specific endpoint, thus you get error when it's more than 100 in your request. if you want to get earlier data, set the `since` parameter accordingly.
Let us know if you have any further issues with CCXT.

**Comment by ttodua** [comment]
we will try to cap it at max 1000 (which seems actual limit). the referenced PR above will do that.
