### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by imran300** [ccxt/ccxt#9905]
Hello, 
Installing via Composer gives error
See attachment

![1](https://user-images.githubusercontent.com/7050400/131496598-40da5e84-775e-47e2-838b-1f2b9c453241.PNG)

**Comment by kroitor** [comment]
Hmm.. there's no extra trailing comma in composer.json on line 982 in composer.json in the master branch here: https://github.com/ccxt/ccxt/blob/master/composer.lock#L982

What is your version of composer? What is your version of PHP? Which sequence of commands do you run to install ccxt?

**Comment by kroitor** [comment]
```
~/tmp $ mkdir composer-test
~/tmp $ cd composer-test
~/tmp/composer-test $ composer init


  Welcome to the Composer config generator



This command will guide you through creating your composer.json config.

Package name (<vendor>/<name>) [igorkroitor/composer-test]:
Description []:
Author [Igor Kroitor <igor.kroitor@gmail.com>, n to skip]:
Minimum Stability []:
Package Type (e.g. library, project, metapackage, composer-plugin) []:
License []:

Define your dependencies.

Would you like to define your dependencies (require) interactively [yes]?
Search for a package:
Would you like to define your dev dependencies (require-dev) interactively [yes]?
Search for a package:

{
    "name": "igorkroitor/composer-test",
    "authors": [
        {
            "name": "Igor Kroitor",
            "email": "igor.kroitor@gmail.com"
        }
    ],
    "require": {}
}

Do you confirm generation [yes]?
~/tmp/composer-test $ composer require ccxt/ccxt
Using version ^1.55 for ccxt/ccxt
./composer.json has been updated
Running composer update ccxt/ccxt
Loading composer repositories with package information
Updating dependencies
Lock file operations: 3 installs, 0 updates, 0 removals
  - Locking ccxt/ccxt (1.55.60)
  - Locking pear/console_table (v1.3.1)
  - Locking symfony/polyfill-mbstring (v1.23.1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Downloading pear/console_table (v1.3.1)
  - Downloading ccxt/ccxt (1.55.60)
  - Installing symfony/polyfill-mbstring (v1.23.1): Extracting archive
  - Installing pear/console_table (v1.3.1): Extracting archive
  - Installing ccxt/ccxt (1.55.60): Extracting archive
6 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
2 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
~/tmp/composer-test $ php -v
PHP 7.4.22 (cli) (built: Jul 27 2021 15:38:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.22, Copyright (c), by Zend Technologies
~/tmp/composer-test $ composer -v
   ______
  / ____/___  ____ ___  ____  ____  ________  _____
 / /   / __ \/ __ `__ \/ __ \/ __ \/ ___/ _ \/ ___/
/ /___/ /_/ / / / / / / /_/ / /_/ (__  )  __/ /
\____/\____/_/ /_/ /_/ .___/\____/____/\___/_/
                    /_/
Composer version 2.0.8 2020-12-03 17:20:38
````

**Comment by imran300** [comment]
> Hmm.. there's no extra trailing comma in composer.json on line 982 in composer.json in the master branch here: https://github.com/ccxt/ccxt/blob/master/composer.lock#L982
> 
> What is your version of composer? What is your version of PHP? Which sequence of commands do you run to install ccxt?

Composer 2.0.8
PHP 7.3

composer require ccxt/ccxt 

this is what i run and gets an error

**Comment by DUK3135** [comment]
Those are great questions that I could not even begin to tell you why nor
do I know I'm just really starting out and I am using cloud console I get
some of it but please bear with me

**Comment by kroitor** [comment]
@imran300 

> composer require ccxt/ccxt

In which folder do you run that command? You should run it in your own project, make sure that your project is initialized with composer properly. This set of commands should do a clean install if you follow it precisely to a letter: https://github.com/ccxt/ccxt/issues/9905#issuecomment-909182075
Hope that answers your question, let us know if not.

**Comment by imran300** [comment]
> @imran300
> 
> > composer require ccxt/ccxt
> 
> In which folder do you run that command? You should run it in your own project, make sure that your project is initialized with composer properly. This set of commands should do a clean install if you follow it precisely to a letter: [#9905 (comment)](https://github.com/ccxt/ccxt/issues/9905#issuecomment-909182075)
> Hope that answers your question, let us know if not.

I already have fresh installation of laravel and i am running it in laravel root folder so it shoudl work..
