### ISSUE TITLE
watch_order_book error with Binance : Connection closed by remote server, closing code 1008

### ISSUE THREAD

**Issue by Kinzowa** [ccxt/ccxt#9907]
Hello,

I upgraded both CCXT and CCXT Pro to the latest version and I receive this error when I try to watch Binance order book for one spot symbol : 
```

  File "/home/abc/env/lib/python3.6/site-packages/ccxtpro/binance.py", line 155, in watch_order_book
    orderbook = await self.watch(url, messageHash, message, messageHash, subscription)
ccxt.base.errors.NetworkError: Connection closed by remote server, closing code 1008
```

Error code1008 is not referenced in the Binance API.

What do you think is the reason for this issue and how can I fix it?

Thank you,

This is how I initiate the loop:

```

    async def watch_book(account, client, market, i, j):
        while True:
            try:
                ob = await client.watch_order_book(market.symbol)
            except Exception as e:
                break

    async def wallet_loop(account, loop, i, wallet):
        client = getattr(ccxtpro, exchange.exid)({'enableRateLimit': True, 'asyncio_loop': loop, })
        ws_loops = [watch_book(account, client, market, i, j) for j, market in enumerate(markets_monitor)]
        await asyncio.gather(*ws_loops)
        await client.close()

    async def main(account, loop, wallets):
        wallet_loops = [wallet_loop(account, loop, i, wallet) for i, wallet in enumerate(wallets)]
        await asyncio.gather(*wallet_loops)

    loop = asyncio.get_event_loop()
    gp = asyncio.wait([main(account, loop, wallets)])
    loop.run_until_complete(gp)
    loop.close()

```

**Comment by Kinzowa** [comment]
Hello, 

Am'I the only one having this issue ? my trading bot is currently not working due to this problem.

Best,
Kinzowa

**Comment by frosty00** [comment]
@Kinzowa replace this code

```
    async def watch_book(account, client, market, i, j):
        while True:
            try:
                ob = await client.watch_order_book(market.symbol)
            except Exception as e:
                break
```

```
    async def watch_book(account, client, market, i, j):
        while True:
            try:
                ob = await client.watch_order_book(market.symbol)
            except Exception as e:
               print('oh no an error', str(e))
               continue # CHANGE THIS LINE
```

ccxt will handle the disconnects and reconnect automatically.

Let us know if this does not solve your problem and thanks for using ccxt pro!

**Comment by Kinzowa** [comment]
Hi @frosty00 thanks for the answer.

I did the modification, unfortunnatly the error is thrown in loop until my IP is banned by the remote host. However I noticed that when there is only 4 markets stream to monitor there is no error. Any idea what could be the reason ?

With 5 markets:

```

2021-09-03 07:30:10.931245 [info     ] Start loop spot DOT/USDT for account 3      [trading.tasks] 
2021-09-03 07:30:10.931554 [info     ] Start loop spot FTM/USDT for account 3      [trading.tasks] 
2021-09-03 07:30:10.931805 [info     ] Start loop spot DOT/BUSD for account 3     [trading.tasks] 
2021-09-03 07:30:10.932036 [info     ] Start loop spot  FTM/BUSD for account 3      [trading.tasks] 
2021-09-03 07:30:10.932273 [info     ] Start loop spot SOL/USDT for account 3     [trading.tasks] 
2021-09-03 07:30:12.969453 [warning  ] Stream DOT/USDT: Connection closed by remote server, closing code 1008 [trading.tasks] 
2021-09-03 07:30:12.970113 [warning  ] Stream FTM/USDT: Connection closed by remote server, closing code 1008 [trading.tasks]
2021-09-03 07:30:12.970336 [warning  ] Stream DOT/BUSD: Connection closed by remote server, closing code 1008 [trading.tasks] 
2021-09-03 07:30:12.970572 [warning  ] Stream  FTM/BUSD: Connection closed by remote server, closing code 1008 [trading.tasks] 
2021-09-03 07:30:12.970774 [warning  ] Stream SOL/USDT: Connection closed by remote server, closing code 1008 [trading.tasks] 
2021-09-03 07:30:14.364808 [warning  ] StreamDOT/USDT: Connection closed by remote server, closing code 1008 [trading.tasks] 
2021-09-03 07:30:14.365674 [warning  ] Stream FTM/USDT: Connection closed by remote server, closing code 1008 [trading.tasks] 
2021-09-03 07:30:14.365972 [warning  ] Stream DOT/BUSD: Connection closed by remote server, closing code 1008 [trading.tasks] 
2021-09-03 07:30:14.366246 [warning  ] Stream  FTM/BUSD: Connection closed by remote server, closing code 1008 [trading.tasks] 
2021-09-03 07:30:14.366481 [warning  ] Stream SOL/USDT: Connection closed by remote server, closing code 1008 [trading.tasks] 
```

With 4 markets:

```
2021-09-03 07:46:25.941250 [info     ] Start loop spot DOT/USDT for account 3      [trading.tasks] 
2021-09-03 07:46:25.941517 [info     ] Start loop spot FTM/USDT for account 3      [trading.tasks] 
2021-09-03 07:46:25.941712 [info     ] Start loop spot DOT/BUSD for account 3      [trading.tasks] 
2021-09-03 07:46:25.941908 [info     ] Start loop spot FTM/BUSD for account 3      [trading.tasks] 
Best ask 33.01
Best ask 0.8398
Best ask 33.02
Best ask 0.8397
```

What could be the reason for this ?

**Comment by Kinzowa** [comment]
Please find below a reproducible example:

```
import ccxtpro
import asyncio

async def watch_book(client, symbol):

    while True:
        try:
            ob = await client.watch_order_book(symbol)
            print(ob['asks'][0][0])
        
            await client.sleep(1000)
            
        except Exception as e:
            print('error {0}'.format(symbol), str(e))
            break
            
async def markets_loop(loop):

    client = getattr(ccxtpro, 'binance')({'enableRateLimit': True, 'asyncio_loop': loop, })
    client.options['defaultType'] = 'spot'

    symbols = ['DOT/BUSD',
              'FTM/BUSD',
              # 'FTM/USDT',    #  <- REMOVE TO MONITOR 5 MARKETS INSTEAD OF 4
              'SOL/USDT',
              'DOT/USDT']

    ws_loops = [watch_book(client, symbol) for symbol in symbols]

    await asyncio.gather(*ws_loops)
    await client.close()
        
loop = asyncio.get_event_loop()
gp = asyncio.wait([markets_loop(loop)])
loop.run_until_complete(gp)
loop.close()
```

**Comment by Abyiss-Zach** [comment]
Hello, I am having the same issue for BinanceUS with the watch_trades function in ccxtpro. I find that I can only connect to 4 markets before getting the same error.

**Comment by Kinzowa** [comment]
Hi @frosty00, any idea how we could investigate this issue ?

Thank you,
Kinzowa

**Comment by Kinzowa** [comment]
> Hello, I am having the same issue for BinanceUS with the watch_trades function in ccxtpro. I find that I can only connect to 4 markets before getting the same error.

Hi, is your IP banned if you `continue` the while loop after 1008 errors ?

**Comment by fqlx** [comment]
I'm having the same issue +1

**Comment by YuriyTigiev** [comment]
I'm having the same issue +1. 
Any work around?

**Comment by kroitor** [comment]
@YuriyTigiev could you paste the code to reproduce it ?

**Comment by kroitor** [comment]
@YuriyTigiev you're using a synchronous blocking api (`write_api.write`) with the async concurrency, and that will cause problems most of the time. Use an async connector to your database instead if you don't want it to interfere with the async websockets. Also, you're trying to subscribe to 1000+ pairs from a single IP address, the exchanges will not tolerate more than 50-100 subscriptions per IP.

Let me know if you have the same issue with the following snippet:

```Python
# -*- coding: utf-8 -*-

from asyncio import run, gather
import ccxtpro


print('CCXT Pro Version:', ccxtpro.__version__)


async def loop(exchange, symbol):
    while True:
        try:
            trades = await exchange.watch_trades(symbol)
            print(exchange, symbol, len(trades), trades[0]['id'], trades[-1]['id'], trades[0]['timestamp'], trades[-1]['timestamp'])
        except Exception as e:
            print(str(e))
            # raise e  # uncomment to break all loops in case of an error in any one of them
            # break  # you can also break just this one loop if it fails

async def main():
    exchange = ccxtpro.binance({'newUpdates': True})
    markets = await exchange.load_markets()
    symbols = ['BTC/USDT', 'ETH/BTC', 'ETH/USDT']
    await asyncio.gather(*[loop(exchange, symbol) for symbol in symbols])
    await exchange.close()

run(main())
```

**Comment by YuriyTigiev** [comment]
> @YuriyTigiev you're using a synchronous blocking api (`write_api.write`) with the async concurrency, and that will cause problems most of the time. Use an async connector to your database instead if you don't want it to interfere with the async websockets. Also, you're trying to subscribe to 1000+ pairs from a single IP address, the exchanges will not tolerate more than 50-100 subscriptions per IP.
> 
> Let me know if you have the same issue with the following snippet:
> 
> ```python
> # -*- coding: utf-8 -*-
> 
> from asyncio import run, gather
> import ccxtpro
> 
> 
> print('CCXT Pro Version:', ccxtpro.__version__)
> 
> 
> async def loop(exchange, symbol):
>     while True:
>         try:
>             trades = await exchange.watch_trades(symbol)
>             print(exchange, symbol, len(trades), trades[0]['id'], trades[-1]['id'], trades[0]['timestamp'], trades[-1]['timestamp'])
>         except Exception as e:
>             print(str(e))
>             # raise e  # uncomment to break all loops in case of an error in any one of them
>             # break  # you can also break just this one loop if it fails
> 
> 
> async def main():
>     exchange = ccxtpro.binance({'newUpdates': True})
>     markets = await exchange.load_markets()
>     symbols = ['BTC/USDT', 'ETH/BTC', 'ETH/USDT']
>     await asyncio.gather(*[loop(exchange, symbol) for symbol in symbols])
>     await exchange.close()
> 
> 
> run(main())
> ```

1) In my code you can comment write to database and select only one symbol 'FTM/BUSD' and you will get the same result. 
2) I tried to run your code and got error. (see the screenshot) I have installed asyncio.


![image](https://user-images.githubusercontent.com/22752322/154552811-8e1eaef7-2d6d-4f11-bed6-13fdae2ce397.png)

**Comment by kroitor** [comment]
@YuriyTigiev it was a minor typo, try this one:

```Python
# -*- coding: utf-8 -*-

from asyncio import run, gather
import ccxtpro


print('CCXT Pro Version:', ccxtpro.__version__)


async def loop(exchange, symbol):
    while True:
        try:
            trades = await exchange.watch_trades(symbol)
            print(exchange, symbol, len(trades), trades[0]['id'], trades[-1]['id'], trades[0]['timestamp'], trades[-1]['timestamp'])
        except Exception as e:
            print(str(e))
            # raise e  # uncomment to break all loops in case of an error in any one of them
            # break  # you can also break just this one loop if it fails


async def main():
    exchange = ccxtpro.binance({'newUpdates': True})
    markets = await exchange.load_markets()
    symbols = ['BTC/USDT', 'ETH/BTC', 'ETH/USDT']
    await gather(*[loop(exchange, symbol) for symbol in symbols])
    await exchange.close()


run(main())
```

**Comment by YuriyTigiev** [comment]
Your code works without issues.

**Comment by kroitor** [comment]
@YuriyTigiev try adding more pairs to it to see where it breaks. Then add the database connector. Make sure you use an async connector, for example: https://aioinflux.readthedocs.io/en/stable/

**Comment by caiusCitiriga** [comment]
> @YuriyTigiev you're using a synchronous blocking api (`write_api.write`) with the async concurrency, and that will cause problems most of the time. Use an async connector to your database instead if you don't want it to interfere with the async websockets. Also, you're trying to subscribe to 1000+ pairs from a single IP address, the exchanges will not tolerate more than 50-100 subscriptions per IP.
> 
> Let me know if you have the same issue with the following snippet:
> 
> ```python
> # -*- coding: utf-8 -*-
> 
> from asyncio import run, gather
> import ccxtpro
> 
> 
> print('CCXT Pro Version:', ccxtpro.__version__)
> 
> 
> async def loop(exchange, symbol):
>     while True:
>         try:
>             trades = await exchange.watch_trades(symbol)
>             print(exchange, symbol, len(trades), trades[0]['id'], trades[-1]['id'], trades[0]['timestamp'], trades[-1]['timestamp'])
>         except Exception as e:
>             print(str(e))
>             # raise e  # uncomment to break all loops in case of an error in any one of them
>             # break  # you can also break just this one loop if it fails
> 
> 
> async def main():
>     exchange = ccxtpro.binance({'newUpdates': True})
>     markets = await exchange.load_markets()
>     symbols = ['BTC/USDT', 'ETH/BTC', 'ETH/USDT']
>     await asyncio.gather(*[loop(exchange, symbol) for symbol in symbols])
>     await exchange.close()
> 
> 
> run(main())
> ```

@kroitor where did you find the limitation on binance subscriptions that shouldn't be more than 50/100 markets? 

Their docs says 1024 subs Max per single Conn. And I'm facing the same 1008 error

**Comment by ttodua** [comment]
related: https://github.com/ccxt/ccxt/issues/12031
