### ISSUE TITLE
coinbase pro / kucoin margin trading using licenced ccxt pro?

### ISSUE THREAD

**Issue by csidi90** [ccxt/ccxt#9908]
Im wondering how to do margin trading using ccxt.pro or even ccxt with the coinbasepro and kucoin instances. Should be possible since I can trade with margin on both exchanges but can not find any functions in terms of margin trading besides when using binance.

**Comment by ttodua** [comment]
Margin related methods are not yet unified in ccxt. You should use ['implicit' API ](https://docs.ccxt.com/en/latest/manual.html#implicit-api) to achieve your needs. You can look inside those `coinbasepro.js` and `kucoin.js` files to see the supported implicit api endpoints or directly in their API docs, and use those ccxt implicit methods.
( @kroitor did I miss anything? )

**Comment by kroitor** [comment]
@ttodua it would be great if we could make some short example snippets showing how to place basic margin-trading orders with the unified/implicit API for the above two exchanges. That would help the other users as well.

**Comment by ttodua** [comment]
There are many different endpoints in margin-trading and it's impossible at this moment to list snippets for any of them (moreover for different exchanges, as they are specific in their implementations and not unified), however, just a typical example would be:

* endpoint: https://docs.kucoin.com/#post-borrow-order
```
const kucoin = new ccxt.kucoin( { ... } ); 
await kucoin.loadMarkets();
const params1 = {
    "currency":"BTC",
    "type": "IOC",
    "size": 0.001,
}
const borrowResult =await kucoin.privatePostMarginBorrow(params1);

const pairToTrade = 'BTC/USDT';
const params2 = {
    "clientOid": kucoin.uuid (),
    "side": "buy",
    "symbol": kucoin.marketId(pairToTrade),
    "type": "limit",
    "price": 49123,
    "size": 0.001,
};
const orderResult =await kucoin.privatePostMarginOrder(params2);
```

So, after looking into the documentations, then you can use such examples for doing other things with implicit api.

**Comment by ttodua** [comment]
If you feel there is need more help with the issue, feel free to reopen.
