### ISSUE TITLE
Front end for ccxt

### ISSUE THREAD

**Issue by kiahmed** [ccxt/ccxt#991]
could any one suggest any open source front end for ccxt out there that could be integrated with much less customization?

**Comment by kroitor** [comment]
Hi!

Currently, there is no such front-end, that we know of. However, you can look at these promising projects that integrate CCXT and offer end-user functionality:
- [GDAX Trading Toolkit](https://github.com/coinbase/gdax-tt)
- [Enigma Catalyst](https://blog.enigma.co/enigma-announces-catalyst-0-4-our-biggest-release-yet-fa31a5ffa4b1)
- [backtrader](https://www.backtrader.com)
- [zenbot](https://github.com/carlos8f/zenbot)
- https://github.com/ccxt/ccxt/tree/master/examples#see-also
- https://github.com/ccxt/ccxt/network/dependents

Hope it helps.
