### ISSUE TITLE
Work

### ISSUE THREAD

**Issue by DUK3135** [ccxt/ccxt#9911]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS:
- Programming Language version:
- CCXT version:

```
REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS
```

```
REPLACE_THIS_WITH_YOUR_OUTPUT_ERROR_EXCEPTION_IN_TEXT_NO_SCREENSHOTS
```

**Comment by drsavant-pub** [comment]
Do you know one of these programming languages: Javascript, Node, PHP or Python?  

If so, then you should be able to follow most, if not all, of the documentation, [click here](https://ccxt.readthedocs.io/en/latest/manual.html).

If not, you need to learn one of these languages first before you will be able to implement ccxt.  (There are simply too many variables to answer your question.)

**If all you need to do is buy some crypto-currency so you can send it to someone, there are wallets that will allow you to do this.**  They charge a premium to buy crypto, but they are great multi-crypto-currency wallets:
- https://atomicwallet.io/
- https://guarda.com/

You can also choose a crypto-currency exchange and create an account and then buy and transfer crypto-currency from within your account.
