### ISSUE TITLE
How to execute Bybit futures trades?

### ISSUE THREAD

**Issue by freegab** [ccxt/ccxt#9917]
I'm having trouble finding details on how to execute bybit futures trades. Can someone provide some examples of buying/selling longs and shorts on bybit?

I have this code to get into a long position with 'buy' and I can get into a short position using 'sell', but I don't know how to close the positions:
```
exchange_id = 'bybit'
exchange_class = getattr(ccxt, exchange_id)
log.info(f"exchange id: {exchange_id}, api_key: {api_key[:5]}, api_secret: {api_secret[:5]}")
exchange = exchange_class({
    'apiKey': api_key,
    'secret': api_secret,
    'enableRateLimit': True, 
    'options': {
        'defaultType': 'future',
        'adjustForTimeDifference': True
    },
})

# go long
exchange.create_order('BTC/USDT', 'market', 'buy', 0.05)

# go short
exchange.create_order('BTC/USDT', 'market', 'sell', 0.05)
```

I've also tried adding the options for 'reduce_only' and 'close_on_trigger' but it won't close the long/short positions:
```
    params = {
        'reduce_only': True,
        'close_on_trigger': True,
        'time_in_force': 'GTC'
    }
    # order = exchange.create_order('BTC/USDT', 'market', 'buy', 0.05, params)
    order = exchange.create_order('BTC/USDT', 'market', 'sell', 0.05, params)
```

**Comment by joomong** [comment]
Did you solve this problem?

**Comment by joomong** [comment]
add params `'side':Sell `

**Comment by freegab** [comment]
I tested buying with:
`exchange.create_order('BTC/USDT', 'market', 'buy', 0.05)`
This created a long position, then I tried to sell the long:
`params = {
        'reduce_only': True,
        'close_on_trigger': True,
        'time_in_force': 'GTC',
        'side': 'Sell'
}
exchange.create_order('BTC/USDT', 'market', 'buy', 0.05, params)`

This added to my long position...

**Comment by freegab** [comment]
turning on verbose shows some odd  things also:
`
params = {
        'reduce_only': True,
        'close_on_trigger': True,
        'time_in_force': 'GTC',
        'side': 'Sell'
}
exchange.create_order('BTC/USDT', 'market', 'buy', 0.01, params)
`
Running this shows in the logging the params are not being submitted correctly for reduce_only and close_on_trigger:
`
Request: POST https://api-testnet.bybit.com/private/linear/order/create {'Content-Type': 'application/json', 'Accept-Encoding': 'gzip, deflate'} {"side":"Buy","symbol":"BTCUSDT","order_type":"Market","qty":0.01,"time_in_force":"GoodTillCancel","reduce_only":false,"close_on_trigger":false,"api_key":"removed","recv_window":5000,"timestamp":1634708134571,"sign":"removed"}

`

The response shows additionally time_in_force is not correct from what was sent in the request:
`
Response: POST https://api-testnet.bybit.com/private/linear/order/create 200 {'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '679', 'Expires': 'Wed, 20 Oct 2021 05:35:35 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Wed, 20 Oct 2021 05:35:35 GMT', 'Connection': 'keep-alive'} {"ret_code":0,"ret_msg":"OK","ext_code":"","ext_info":"","result":{"order_id":"fc6f7c14-3efa-4e7a-86b4-d3811ccf79c9","user_id":261646,"symbol":"BTCUSDT","side":"Buy","order_type":"Market","price":67090.5,"qty":0.01,"time_in_force":"ImmediateOrCancel","order_status":"Created","last_exec_price":0,"cum_exec_qty":0,"cum_exec_value":0,"cum_exec_fee":0,"reduce_only":false,"close_on_trigger":false,"order_link_id":"","created_time":"2021-10-20T05:35:35Z","updated_time":"2021-10-20T05:35:35Z","take_profit":0,"stop_loss":0,"tp_trigger_by":"UNKNOWN","sl_trigger_by":"UNKNOWN"},"time_now":"1634708135.180760","rate_limit_status":99,"rate_limit_reset_ms":1634708135175,"rate_limit":100}

`
