### ISSUE TITLE
Poloniex timestamp Issue in PHP

### ISSUE THREAD

**Issue by geethpw** [ccxt/ccxt#9919]
- OS: Mac OS Catalina
- Programming Language version: PHP 7.3.26
- CCXT version: 1.40
- PHP Time zone: EST
- Server Time zone:  EST

Poloniex trade data timestamp converts to the timezone of the system instead of UTC. For example, look at the following array that represents a single trade
```
1 => array:13 [
    "id" => "522628925"
    "info" => array:11 [
      "globalTradeID" => "522628925"
      "tradeID" => "29344377"
      "date" => "2021-02-26 05:11:05.000000"
      "rate" => "0.000009290000"
      "amount" => "0.00009300"
      "total" => "0.00000000"
      "fee" => "0.00125000"
      "feeDisplay" => "0.00000011 XRP (0.125%)"
      "orderNumber" => "342551282940"
      "type" => "buy"
      "category" => "exchange"
    ]
    "timestamp" => 1614334265000
    "datetime" => "2021-02-26T10:11:05.000Z"
    "symbol" => "XRP/BTC"
    "order" => "342551282940"
    "type" => "limit"
    "side" => "buy"
    "takerOrMaker" => null
    "price" => 9.29E-6
    "amount" => 9.3E-5
    "cost" => 0.0
    "fee" => array:3 [
      "cost" => 1.1E-7
      "currency" => "XRP"
      "rate" => 0.00125
    ]
  ]
```

Poliniex reports the timestamp as :  "date" => "2021-02-26 05:11:05.000000"
This converted using `strtotime()`: **1614316265000**
CCXT reports the timestamp as:  **1614334265000**

If CCXT is using a string to date conversion method such as `strtotime()`, the "UTC" flag should be passed as a part of that conversion. IE:
```
strtotime("2021-02-26 05:11:05.000000 UTC");
```

Another point: The results in the Poloniex is not sorted by timestamp per page.

**Comment by kroitor** [comment]
Hi! Do you set the default timezone to UTC at the start of your script? It is mentioned in CCXT's Manual: https://github.com/ccxt/ccxt/wiki/Manual#instantiation

**Comment by geethpw** [comment]
@kroitor that seemed to be the problem. The funny thing is it worked on Kucoin, FTX, etc. We only had the issue for this exchange. But UTC at the initiation fixed it. 

Thanks
