### ISSUE TITLE
Binance staking balance

### ISSUE THREAD

**Issue by tredondo** [ccxt/ccxt#9921]
Hi, how can we request the staking balance for Binance? Staked coins are not returned from `fetchBalance()`.

I looked for similar examples:
- For Kraken, fetchBalance() returns coins with a `.S` at the end, e.g. `ATOM.S`.
- For HitBTC, a [`type` parameter need to be passed](https://github.com/ccxt/ccxt/issues/288#issuecomment-335549106) for the `trading` vs. main balance.

But in the [Binance API docs](https://binance-docs.github.io/apidocs/spot/en/#account-information-user_data) I couldn't find anything.

**Comment by frosty00** [comment]
you can try:

```
binance.fetchBalance ({ type: 'savings' })
```

let me know if this helped or if you need something else.

this will return the total amount staked in the flexible and locked savings products only, not the other products they offer, such as dual staking and defi staking.

**Comment by tredondo** [comment]
Thanks @frosty00, that helped. The shape of the returned object is a bit different though. It looks like for `({ type: 'savings' })`, the library doesn't parse balances per coin.

Here is `data` from `binance.fetchBalance().then(data => console.log('just fetchBalance', data));`:

```
just fetchBalance {
  info: {
    makerCommission: '10',
   ...
    accountType: 'SPOT',
    balances: [
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      ... 350 more items
    ],
    permissions: [ 'SPOT' ]
  },
  BTC: { free: 0, used: 0, total: 0 },
  LTC: { free: 0, used: 0, total: 0 },
  ...
  free: { ... },
  used: { ... },
  total: { ... },
}
```

And here is `data` from `binance.fetchBalance({ type: 'savings' }).then(data => console.log('SAVINGS', data));`:

```
SAVINGS {
  info: {
    makerCommission: '10',
    ...
    accountType: 'SPOT',
    balances: [
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object], [Object], [Object],
      [Object], [Object], [Object], [Object],
      ... 350 more items
    ],
    permissions: [ 'SPOT' ]
  },
  free: {},
  used: {},
  total: {}
}
```

If I log `data.info.balances`, I do see 350 elements like `{ asset: 'BTC', free: '0.00000000', locked: '0.00000000' },`.

Not sure if the object shape should be the same for the two requests, i.e. if the library should try to parse the `{ type: 'savings' }` output into `free`, `asset` & `locked` instead of `free`, `used` and `total`, and then per coin as in the `fetchBalance()` case. If not, please disregard and thanks again for the help.

**Comment by phips28** [comment]
JFYI: Binance does not offer endpoints for balance of "Locked Staking" products.

**Comment by tredondo** [comment]
Unfortunately, @phips28 seems to be right. In the `binance.fetchBalance({ type: 'savings' })` results, those `{ asset: 'BTC', free: '0.00000000', locked: '0.00000000' }` entries don't match what I have staked. `locked` is 0 for a coin I have staked.

So there's no way to get the amount of staked coins via the Binance API?

**Comment by phips28** [comment]
Nope. They dont have an endpoint for that.

**Comment by MalteToenjes** [comment]
FYI: Binance has a staking Endpoint now: https://binance-docs.github.io/apidocs/spot/en/#staking-endpoints

**Comment by Chuox** [comment]
> { type: 'savings' }

I just get:

`BadRequest: binance {"code":-1101,"msg":"Too many parameters; expected '3' and received '4'."}`
