### ISSUE TITLE
How I can watch for breaking change releases? What's versioning system do you use?

### ISSUE THREAD

**Issue by bifot** [ccxt/ccxt#9925]
When you update minor version and when the patch? Also any list of breaking changes?

**Comment by kroitor** [comment]
Let us know if this does not answer your question:

- https://github.com/ccxt/ccxt/issues/9758
- https://github.com/ccxt/ccxt/issues/9391
- https://github.com/ccxt/ccxt/issues/2483

**Comment by bifot** [comment]
Didn’t receive an answer about versioning, the referenced issue still open

**Comment by kroitor** [comment]
@bifot in short, we used to have a CHANGELOG, but since we are pushing new fixes and updates daily we cannot maintain such a changelog. You can see the commit log to this repo instead. If a change is breaking the backward-compatibility we usually announce it separately.

**Comment by bifot** [comment]
Where do you post announces?

**Comment by kroitor** [comment]
@bifot we usually post them here in the issues: https://github.com/ccxt/ccxt/issues?q=is%3Aissue+label%3Aannouncement+is%3Aclosed
