### ISSUE TITLE
How to fetch Deribit's Velocity Index data?

### ISSUE THREAD

**Issue by kadnan** [ccxt/ccxt#9926]
Hi

I need to grab the data returned by the API endpoint `get_volatility_index_data` ([link](https://docs.deribit.com/#public-get_volatility_index_data)). How can I fetch it?

I am using the ccxt version `1.42.25` in Python.

**Comment by tentechit** [comment]
I also need that one too.

**Comment by ttodua** [comment]
Every endpoint for exchanges can be called through ccxt. Please take a couple of minutes to read [How to use Implicit Api](https://docs.ccxt.com/en/latest/manual.html#implicit-api).

In your example, that will be:
```
const result = await deribit.publicGetGetVolatilityIndexData({currency:'BTC', ... });
```

Let us know if you have further issues with CCXT.
