### ISSUE TITLE
Huobi Exchange parse ticker None type error

### ISSUE THREAD

**Issue by jamesbaber1** [ccxt/ccxt#9928]
- OS: ubuntu 18.04
- Programming Language version: Python 3.8
- CCXT version: 1.55.56

```
import ccxt
from pprint import pprint

exchange_class = getattr(ccxt, 'huobipro')
exchange = exchange_class({
            'apiKey': '',
            'secret': '',
            'timeout': 30000,
            'enableRateLimit': True,
})
exchange.verbose = True

pprint(exchange.fetch_ticker('BTC3L/USDT'))
pprint(exchange.fetch_tickers())
```

```
File "/freqtrade/freqtrade/exchange/exchange.py", line 946, in fetch_ticker
    data = self._api.fetch_ticker(pair)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/huobi.py", line 605, in fetch_ticker
    ticker = self.parse_ticker(response['tick'], market)
  File "/home/ftuser/.local/lib/python3.9/site-packages/ccxt/huobi.py", line 489, in parse_ticker
    if 'bid' in ticker:
TypeError: argument of type 'NoneType' is not iterable
```

I have done some testing and this code doesnt repro the error, but I think technically should if run long enough.  I am running a bot that uses ccxt and will run it for a few days until it randomly fails.  The None type error comes from a case when the ticker value is None in the parse_ticker method. 
https://github.com/ccxt/ccxt/blob/ea4bf62b9aa42c8a0d29dfa0e91040b06ddd81e7/python/ccxt/huobi.py#L489

Again this only happens every so often.  I dont know what the correct approach would be, to make ccxt retry to get the ticker when this happens or check if the ticker is none. But probably still raise some kind of exception to the user instead of hitting a None type error.  @kroitor What are your thoughts?

**Comment by ttodua** [comment]
I think this issue could have been fixed, because `ticker` object shouldn't be `None` in any case, because it's being 'safeValue'd at this moment: 
```
        const tick = this.safeValue (response, 'tick', {});
        const ticker = this.parseTicker (tick, market);
```

So, it shouldn't happen atm.
