### ISSUE TITLE
CCXT Pro: 'fetchBalanceSnapshot': True on Binance, doesn't seem to be working like how I was expecting it to

### ISSUE THREAD

**Issue by me1029134** [ccxt/ccxt#9929]
- OS: Windows 
- Programming Language version: 3.8
- CCXT version: CCXT Pro version 0.8.29 (just updated)

Description: 
Maybe I don't understand what 'fetchBalanceSnapshot' is doing, but I was expecting it to maintain an active full Balance of my coins locally. 
If I set 'fetchBalanceSnapshot' to False. Then it does print my balance, but only the balance that the last trade was affecting (i.e. only BTC, USD, BNB (because of fees maybe) if I'm doing a trade with BTC and USD). 

``` Python
import ccxtpro
import asyncio
import json

async def handling_loop(exchange):
    delay = 5
    while True:
        await asyncio.sleep(delay)
        print('Balance:')
        print(exchange.balance)

async def symbol_loop(exchange):
    while True:
        try:
            balance = await exchange.watch_balance()

        except Exception as e:
            print(str(e))
            # raise e  # uncomment to break all loops in case of an error in any one of them
            break  # you can break just this one loop if it fails

async def main(asyncio_loop):
    loops = [symbol_loop(exchange)]
    loops += [handling_loop(exchange)]
    await asyncio.gather(*loops)


if __name__ == '__main__':
    asyncio_loop = asyncio.get_event_loop()

    exchange = getattr(ccxtpro, 'binanceus')({
        'apiKey': key, 
        'secret': secret,
        'verbose': True,
        'enableRateLimit': True,
        'asyncio_loop': asyncio_loop,
        'newUpdates': True,
        'options': {
            'watchBalance': {
                    'fetchBalanceSnapshot': True,  # or True
            },
        }    
    })

    asyncio_loop.run_until_complete(main(asyncio_loop))
```

```
Balance:
{}
```

**Comment by ttodua** [comment]
Late reply, though I'll add the answer:
To maintain the full balance records on your side (as Websocket stream in most cases only emit the 'changed/affected' balances, as you have seen yourself too), then you need at first, to get the initial balance, and then use WS after that. A sample code for reference (in JS, but same logic for python):
```
let initialBalance = await this.WalletFetchRegular();
while (true) {
	try { 
		...
		let update = await exch.watchBalance();
		let newBalance =  exch.deep_extend(initialBalance, update);
		...
	} catch (ex) {
		console.log(ex); 
		sleep(1000);
		... 
	}
}
```
Feel free to reopen if that doesn't answer the question.

**Comment by ttodua** [comment]
Issue was answered and there has not been any follow-ups. Closing the issue.
Let us know if you have any issue with CCXT
