### ISSUE TITLE
The CCXT fetch_balance is about 5/6 times slower than get_account on Binance

### ISSUE THREAD

**Issue by wkamer** [ccxt/ccxt#9931]
MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: MacOS
- Programming Language version: Python
- CCXT version: 1.55.69

```
import ccxt
from binance.client import Client
import time

apiKey = "*****"
secret = "*****"

# binance-python client
client = Client(apiKey, secret, testnet=True)

# ccxt client
exchange_id = 'binance'
exchange_class = getattr(ccxt, exchange_id)
exchange = exchange_class({
    "apiKey": apiKey, 
    "secret": secret,
})
exchange.set_sandbox_mode(True)

start_time = time.time()
exchange.fetch_balance()
end_time = time.time()
print(f"ccxt: {end_time - start_time}")

start_time = time.time()
client.get_account()
end_time = time.time()
print(f"binance: {end_time - start_time}")
```

```
ccxt: 1.3862950801849365
binance: 0.24796199798583984
```

**Comment by kroitor** [comment]
This is explained in the Manual:

- https://github.com/ccxt/ccxt/wiki/Manual#rate-limit
- https://github.com/ccxt/ccxt/wiki/Manual#notes-on-rate-limiter

Let us know if this example does not answer your question:

- https://github.com/ccxt/ccxt/blob/master/examples/py/binance-poll-balance.py

```Python
# -*- coding: utf-8 -*-

from pprint import pprint
import ccxt


print('CCXT Version:', ccxt.__version__)


exchange = ccxt.binanceusdm({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
})

markets = exchange.load_markets()

# exchange.verbose = True  # uncomment for debugging purposes if necessary

previous_timestamp = exchange.milliseconds()
while True:
    try:
        balance = exchange.fetch_balance ()
        print('--------------------------------------------------------------')
        current_timestamp = exchange.milliseconds()
        print(exchange.iso8601(current_timestamp), 'balance:')
        pprint(balance)
        print('Fetched in', current_timestamp - previous_timestamp, 'milliseconds')
        previous_timestamp = current_timestamp
    except Exception as e:
        print(type(e).__name__, str(e))


```

**Comment by wkamer** [comment]
Thank you for your reply, but I do not really understand what this does explain.

What does 'ccxt.binanceusdm' have to do with 'ccxt.binance'?

**Comment by kroitor** [comment]
@wkamer pardon, that was a copy-paste typo, i've edited the above reply, if you set your keys and run it on your side, you will see that ccxt works as fast as the other software.

**Comment by wkamer** [comment]
Thanks, I tried the script your way and see it has good results by. Still a little slower, but around 500ms. I will have to look were my delay came from. I have also slower result (mostly above 1.4s)with my FastAPI app. Suggestions how to debug this?

**Comment by kroitor** [comment]
@wkamer 

> Still a little slower, but around 500ms.

If you don't want any delays, you can disable the rate limiter entirely, at your risk (since if you disable the rate limiter, your requests may be too aggressive for the exchange API and they might ban you temporarily for too many requests).

```Python
# -*- coding: utf-8 -*-

from pprint import pprint
import ccxt


print('CCXT Version:', ccxt.__version__)


exchange = ccxt.binance({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_SECRET',
    'enableRateLimit': False,  # <<<<<<<<<<<<<< disable rate limiter
})

markets = exchange.load_markets()

# exchange.verbose = True  # uncomment for debugging purposes if necessary

while True:
    try:
        previous_timestamp = exchange.milliseconds()
        balance = exchange.fetch_balance()
        print('--------------------------------------------------------------')
        current_timestamp = exchange.milliseconds()
        print(exchange.iso8601(current_timestamp), 'balance:')
        pprint(balance)
        print('Fetched in', current_timestamp - previous_timestamp, 'milliseconds')
        # change this delay as you like
        print('Sleeping for 5 seconds...')
        exchange.sleep(5000)  # sleep 5 seconds between the requests, for example
    except Exception as e:
        print(type(e).__name__, str(e))
```

> How to handle this when I use the fetch_balance as an api endpoint? I do an instantiate every time I call the fetch_balance.

Reuse the exchange instance instead – create it once at the start of your script. Then do a fetch_balance call. Then leave your script running, and repeat the consequent fetch_balance calls on the already existing exchange instance, instead of exiting the script and restarting it again and again. The snippet in this post does exactly that.
