### ISSUE TITLE
Poloniex is giving 403 for all methods

### ISSUE THREAD

**Issue by 1hakr** [ccxt/ccxt#994]
Any method call on poloniex is not working

- OS: OSX
- Programming Language: JavaScript
- CCXT version: 1.10.503
- Exchange: Poloniex
- Method:fetchTicker

Just try this
```
 new ccxt.poloniex ({'verbose': True}).fetchTicker ('ETH/BTC')
```
```
[Exchange Not Available Error] poloniex GET https://poloniex.com/public?command=returnTicker 403 Forbidden Poloniex - Bitcoin/Cryptocurrency Exchange (possible reasons: invalid API keys, bad or old nonce, exchange is down or offline, on maintenance, DDoS protection, rate-limiting)
```

**Comment by kroitor** [comment]
Does this work for you? ↓

```JavaScript
new ccxt.poloniex ({
    'verbose': True,
    'proxy': 'https://cors-anywhere.herokuapp.com/',
    'origin': 'foobar',
}).fetchTicker ('ETH/BTC')
```

Have you tried this? ↓

https://github.com/ccxt/ccxt/wiki/Manual#troubleshooting

**Comment by 1hakr** [comment]
@kroitor yes, thank you so much. Sorry for the trouble, I will double check next time before opening an issue. 
👍🏽 great library mate!
