### ISSUE TITLE
javascript works for FTX us, but not python

### ISSUE THREAD

**Issue by gshippee** [ccxt/ccxt#9941]
- OS: Microsoft Windows 10
- Programming Language version: Python3.8.1, Javascript
- CCXT version: 1.55

Hi, I've been trying to get the python version of the ftx api working with the following code. 

```
import ccxt
exchange = ccxt.ftx({
    'apiKey': '',
    'secret': '',
    'hostname': 'ftx.us',
    'name': 'FTXUS',
})

print(exchange.fetch_balance())
```

And am receiving the following error:
```
AuthenticationError: ftx {"success":false,"error":"Not logged in"}
```

If, however, I download ccxt with npm and run the following javascript code, using the same key and secret as in the code above, the command to fetch account balances, it goes through fine. 
```
"use strict";

const ccxt = require ('C:/Users/guysh/node_modules/ccxt/ccxt.js')
;(async function main () {

    const exchange = new ccxt.ftx ({
        'apiKey': '',
        'secret': '',
        'hostname': 'ftx.us',
        'enableRateLimit': true,
    })

    await exchange.loadMarkets ()

    const ninetyDays = 90 * 24 * 60 * 60 * 1000;
    let startTime = exchange.parse8601 ('2018-01-01T00:00:00')
    const now = exchange.milliseconds ()
    const currencyCode = undefined // any currency

    const balances = await exchange.fetchBalance()
    console.log(JSON.stringify(balances, null, 4));
```
I've compared the signatures being created for a given timestamp between the two scripts as well, and they are identical. As a result, I'm really not sure why the js code goes through fine, and the python code returns an authentication error. Any insight would be greatly appreciated.

**Comment by kroitor** [comment]
@gshippee hi, do you have this issue in python with the most recent version of the lib?

**Comment by gshippee** [comment]
Hi kroitor, thank you for replying. I just performed an update to version 1.55.88 and am still running into the same issue.

**Comment by kroitor** [comment]
@gshippee 

Let's try these two snippets and compare them:

Python:

```Python
import ccxt 

print('CCXT Version:', ccxt.__version__)

exchange = ccxt.ftx({
    'apiKey': 'YOUR_API_KEY',
    'secret': 'YOUR_API_SECRET',
    'hostname': 'ftx.us',
})

markets = exchange.load_markets()

exchange.verbose = True  # uncomment for debugging purposes if necessary

balance = exchange.fetch_balance()
print('------------------------------------------------------')
pprint(balance)
```

JavaScript

```JavaScript
const ccxt = require ('ccxt')

async function main () {
    const exchange = new ccxt.ftx ({
        'apiKey': 'YOUR_API_KEY',
        'secret': 'YOUR_API_SECRET',
        'hostname': 'ftx.us',
    })
    
    const markets = await exchange.loadMarkets ()
    
    exchange.verbose = true  // uncomment for debugging purposes if necessary
    
    const balance = await exchange.fetchBalance ()
    console.log ('------------------------------------------------------------------')
    console.log (balance)
}

main()
````

**Comment by gshippee** [comment]
For Python:
```
CCXT Version: 1.55.88

Request: GET https://ftx.us/api/wallet/balances {'FTXUS-KEY': '', 'FTXUS-TS': '1630950324898', 'FTXUS-SIGN': '', 'User-Agent': 'python-requests/2.23.0', 'Accept-Encoding': 'gzip, deflate'} None

Response: GET https://ftx.us/api/wallet/balances 401 {'Date': 'Mon, 06 Sep 2021 17:46:01 GMT', 'Content-Type': 'application/json', 'Content-Length': '42', 'Connection': 'keep-alive', 'Cache-Control': 'private, max-age=0, no-cache', 'account-id': 'None', 'Vary': 'Origin, Accept-Encoding', 'CF-Cache-Status': 'MISS', 'Expect-CT': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'X-Content-Type-Options': 'nosniff', 'Server': 'cloudflare', 'CF-RAY': '68a983b1db84ead7-LAX', 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400, h3-28=":443"; ma=86400, h3-27=":443"; ma=86400'} {"success":false,"error":"Not logged in"}
```

For Javascript, interestingly enough this snippet doesn't seem to return the balances. The one I posted above still does (which was just a slight modification to one of the scripts in your examples directory), however. 

```
CCXT Version: 1.55.88
-----------------------------------------------------------------------------------
Canceled
```

**Comment by kroitor** [comment]
@gshippee how do you launch the javascript code? What is your version of node? Both snippets should output the verbose request+response for the fetch_balance call. The idea is to compare the keys in the output between the two snippets.

**Comment by gshippee** [comment]
I see. Yes, my apologies I'm not too familiar with running javascript code (just learned it to run this library), and you're correct, when I comment out the verbose line it is revealing that the command is going through ok, it was just being truncated before...
I was running it in visual studio code with the node.js debugger, and I think that's why the output was truncated.

Just ran the same snippet in my terminal and got the following ouptut
```
CCXT Version: 1.55.88
fetch:
 ftx GET https://ftx.us/api/wallet/balances
Request:
 {
  'FTXUS-KEY': '',
  'FTXUS-TS': '1630951584759',
  'FTXUS-SIGN': ''
}
 undefined

handleRestResponse:
 ftx GET https://ftx.us/api/wallet/balances 200 OK
Response:
 {
  'Account-Id': '4233603',
  'Alt-Svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400, h3-28=":443"; ma=86400, h3-27=":443"; ma=86400',
  'Cache-Control': 'private, max-age=0, no-cache',
  'Cf-Cache-Status': 'MISS',
  'Cf-Ray': '68a9a176abee31e5-LAX',
  Connection: 'keep-alive',
  'Content-Encoding': 'gzip',
  'Content-Type': 'application/json',
  Date: 'Mon, 06 Sep 2021 18:06:21 GMT',
  Etag: 'W/"bac7d1d631cd699655bde8bb9d7e592b"',
  'Expect-Ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  Server: 'cloudflare',
  'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload',
  'Transfer-Encoding': 'chunked',
  Vary: 'Accept-Encoding, Origin',
  'X-Content-Type-Options': 'nosniff'
}
 {"success":true,"result":[{"coin":"SOL","...}
```
 The node version I'm using is 14.15.3. I can confirm the FTXUS-KEY is the same for both the python output and the javascript output.

**Comment by kroitor** [comment]
@gshippee i don't have a windows system to test it rn, but will install on a virtual machine and will check on my side. Both snippets work for me on MacOS (basically, the same thing as Debian Linux).

**Comment by gshippee** [comment]
Ok, I will try to do the same with a linux system and let you know the results on my side. Thank you for your support in helping debug this.

**Comment by gshippee** [comment]
Hi Kroitor, just resolved the issue. Somehow my clock wasn't syncing correctly for python, so the timestamp was getting messed up. Thank you for your time and for helping me remove the other variables that could have potentially been an issue here from the list.

**Comment by kroitor** [comment]
@gshippee thx for reporting back! Good to know you figured it out!
