### ISSUE TITLE
Code Stuck

### ISSUE THREAD

**Issue by pickmone** [ccxt/ccxt#9945]
Not sure how I can reproduce this. but once in a while, when I examine my code because it hasn't done anything in a while, I find that the code is stuck in a loop somewhere, but usually it would have something to do with watchorder or network errors. Not exactly sure where, 

but is anyone else having this issue?

**Comment by kroitor** [comment]
Hi! We need more info to be able to help:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

Please, check these duplicate issues (we suggest moving this discussion there for less duplication):

- https://github.com/ccxt/ccxt/issues/9602
- https://github.com/ccxt/ccxt/issues/8698
- https://github.com/ccxt/ccxt/issues/7858
- https://github.com/ccxt/ccxt/issues/7011
