### ISSUE TITLE
Symbols not being universal

### ISSUE THREAD

**Issue by serteikas** [ccxt/ccxt#9946]
Cannot place_order with symbol "ADAUSDT" on Binance Spot, "ADA/USDT" works though. 
- CCXT version: 1.55.88

```
return self.decimal_to_precision(amount, TRUNCATE, self.markets[symbol]['precision']['amount'], self.precisionMode, self.paddingMode)
KeyError: 'ADAUSDT'
```

**Comment by kroitor** [comment]
Please, read the Manual: https://github.com/ccxt/ccxt/wiki/Manual#symbols-and-market-ids

**Comment by frosty00** [comment]
fixed in https://github.com/ccxt/ccxt/pull/9949
