### ISSUE TITLE
Bybit fetchPositions undefined result when market is inverse

### ISSUE THREAD

**Issue by fasenderos** [ccxt/ccxt#9961]
Hi, the response from `fetchPositions` when market type is `inverse` (Inverse Perpetual) returns `undefined`, because the bybit response is stringified, so you have to parse it.

https://github.com/ccxt/ccxt/blob/bea845ba3e13edc717e5dc3496cd32ed232128b7/js/bybit.js#L2339

For `linear` market there is no need to parse the response, i did not try the `inverseFuture`.

One more question, why did you decide to expect the market `type` as a param of the `fetchPositions`, instead of get that param from the market (when a symbol is passed)? I mean something like that:
```
## bybit.js
async fetchPositions (symbols = undefined, params = {}) {
        await this.loadMarkets ();
        const request = {};
        let typeFromSymbol = undefined;
        if (Array.isArray (symbols)) {
            const length = symbols.length;
            if (length !== 1) {
                throw new ArgumentsRequired (this.id + ' fetchPositions takes exactly one symbol');
            }
            const market = this.market (symbols[0]);
            request['symbol'] = market['id'];
            typeFromSymbol = market['inverse'] ? 'inverse' : market['futures] ? 'inverseFuture' : 'linear';
        }
        const defaultType = this.safeString (this.options, 'defaultType', 'linear');
        const type = typeFromSymbol || defaultType;
       ....
}
```

Beacuse now if I want to fetch the position of my Inverse Perpetual, I have to call the method like this
`fetchPositions(['BTC/USD'], { type: 'inverse' })`.

Thanks

- OS: Window
- Programming Language version: NodeJS
- CCXT version: 1.55.84

**Comment by fasenderos** [comment]
I can confirm that `fetchPositions` did not work also with the `inverseFuture` market, because the bybit response is stringified.

**Comment by kroitor** [comment]
Thanks for reporting, fixed in CCXT 1.56.27. Appreciate your feedback!

**Comment by fasenderos** [comment]
Thanks @kroitor, but you’re missing to parse also the `inverseFutures`

**Comment by kroitor** [comment]
@fasenderos thx for pointing it out, will add that as well.
