### ISSUE TITLE
Placing a stop-limit order on Gate.io

### ISSUE THREAD

**Issue by steveharrison** [ccxt/ccxt#9968]
I'm trying to use CCXT to place a stop-limit order on Gate.io using CCXT. I understand that I need to use the optional `params` object to pass in the Gate.io-specific parameters, but it doesn't seem to be working as I would expect. I've included in `params` what the [Gate.io docs](https://www.gate.io/docs/apiv4/en/#create-a-price-triggered-order) say to pass in as the body of the request. Instead, the following code just places a standard sell order for selling 2 ALGO at $4, as per the main arguments, but doesn't place a stop-limit order based on any of the info provided in `params`:
```
  const sellOrder = await gateio.createLimitSellOrder("ALGO/USDT", 2, 4, {
      "trigger": {
        "price": "100",
        "rule": ">=",
        "expiration": 3600
      },
      "put": {
        "type": "limit",
        "side": "sell",
        "price": "2.15",
        "amount": "2.00000000",
        "account": "normal",
        "time_in_force": "gtc"
      },
      "market": "ALGO_USDT"
   });
```

Any ideas what I'm doing wrong, or if there is a better way to place a stop-limit order on Gate.io?

**Comment by kroitor** [comment]
> but it doesn't seem to be working as I would expect.

Can you please paste your verbose request+response output:

- https://github.com/ccxt/ccxt/wiki/FAQ#what-is-required-to-get-help

```
gateio.verbose = true
const sellOrder = await gateio.createLimitSellOrder("ALGO/USDT", 2, 4, {
      "trigger": {
      "price": "100",
      ...
```

**Comment by steveharrison** [comment]
Sure, I've created a repository with this issue and another issue, and have included the Terminal output plus screenshots of what happens on the Gate.io side: https://github.com/steveharrison/ccxt-gateio-issues/tree/master/Output%20on%20my%20machine.

**Comment by kroitor** [comment]
@steveharrison thank you! Will investigate and will be back to you asap!
