### ISSUE TITLE
Exchanges not supporting fetchOpenOrders, fetchClosedOrders

### ISSUE THREAD

**Issue by BHruska** [ccxt/ccxt#9970]
Why do some top exchanges not support these functions?   fetchOpenOrders, fetchClosedOrders

Is it just their API doesn't support them?  Or CCXT hasn't implemented it?  Seems like basic functionality, as most do.  I've got some routines that can't accurately track my history without this, so its frustrating.

Is there any other way I get this info, like fetchXXXXXX something else?

Thanks,
Brian

- https://github.com/ccxt/ccxt/wiki/FAQ
- https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

- OS: Windows 10
- Programming Language version:  Python
- CCXT version:  CCXT Version: 1.55.18

```
        if not self.exchange.has['fetchOpenOrders']:
            print('No fetchOpenOrders')
        if not self.exchange.has['fetchClosedOrders']:
            print('No fetchClosedOrders')
```

```
BITSTAMP
No fetchOpenOrders
No fetchClosedOrders

FTX
No fetchClosedOrders

GEMINI
No fetchClosedOrders
```

**Comment by kroitor** [comment]
```Python
import ccxt
from pprint import pprint
print('CCXT Version:', ccxt.__version__)

exchange = ccxt.bitstamp()
print(exchange.id, 'fetchOpenOrders:', exchange.has['fetchOpenOrders'])
print(exchange.id, 'fetchClosedOrders:', exchange.has['fetchClosedOrders'])
print(exchange.id, 'fetchOrders:', exchange.has['fetchOrders'])
print(exchange.id, 'fetchOrder:', exchange.has['fetchOrder'])
print(exchange.id, 'fetchMyTrades:', exchange.has['fetchMyTrades'])
```

Bitstamp has `fetchOpenOrders()`. 

I've added some clarifications to the Manual: 

- https://github.com/ccxt/ccxt/wiki/Manual#understanding-the-orders-api-design

Let us know if that does not answer your question.
