### ISSUE TITLE
Opening the Order(long) by Open of candle(Open by time)

### ISSUE THREAD

**Issue by BahramianArmin** [ccxt/ccxt#9986]
Hello to every one...
I want to excute  the position in ccxt based on time ( open the position by opening of candle & close that with right befor of candle's closing)
so how can i do that??
thanks for your attention!

**Comment by DUK3135** [comment]
If anyone is directly talking to me or need me get at me with a direct message me

**Comment by kroitor** [comment]
> I want to excute the position in ccxt based on time ( open the position by opening of candle & close that with right befor of candle's closing)
> so how can i do that??

Can you elaborate on what exactly is not clear?
The usage of CCXT is explained in the Manual and in the examples:

- https://github.com/ccxt/ccxt/wiki/
- https://github.com/ccxt/ccxt/wiki/Manual
- https://github.com/ccxt/ccxt/tree/master/examples

CCXT allows you to place orders, fetch the candles, etc. However, it will not manage your strategy, you have to code it using one of the supported programming languages. You just set your timers and place your orders accordingly.

Hope that answers your question. Feel free to reopen it or just ask further questions if any.

**Comment by BahramianArmin** [comment]
yes i can !
if i want to  place order with time maybe there is not enough volume for trade! at that second!(Just that)...
when we order position by price it is diffrent with ordering by time!
thank for your links...
