### ISSUE TITLE
Python In The Cloud

### ISSUE THREAD

**Issue by iMichaelM** [ccxt/ccxt#9992]
Hey All, not sure if this is the best place to ask this but given that we're all working on some sort of algos here, I thought it'd only make sense to do so. 
What would you recommend as the most budget & user-friendly option to run dozens of scripts 24/7 simultaneously in the cloud? Ideally, it's as simple as just taking my scripts and deploying them.

Appreciate any and all suggestions!

**Comment by kroitor** [comment]
@iMichaelM i'd recommend using google cloud + ccxt as explained in this video tutorial: https://www.youtube.com/watch?v=mtpA3vDg5js
